### ISSUE TITLE
Errno::ECONNREFUSED: Connection refused - connect(2) for "your-dns-needs-immediate-attention.network" port 443

### ISSUE THREAD

**Issue by jumph4x** [rubygems/rubygems#1001]
Hey all,

This may or may not end up being RubyGems problem, but for posterity's sake and for Google discoverability, the canonical Rubygems repo issue page seemed like the best place to begin. 

Starting at some point today, new gem installations (as opposed to gem bundling) started failing using this error message, which to me (former CCNA) is extremely perplexing. 

```
➜  ~  gem install rails 
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    Errno::ECONNREFUSED: Connection refused - connect(2) for "your-dns-needs-immediate-attention.network" port 443 (https://your-dns-needs-immediate-attention.network/quick/Marshal.4.8/rails-4.1.5.gemspec.rz)
```

Not before spending the better portion of the day fucking with RVM and RBenv, local dnsmaq and bind9 and even upgrading bBuntu from 14.04 to 14.10, I tried girlfriend's computer with identical results. 

I did a little bit of RubyGems source spelunking (via the --debug flat during gem installations) and it looks like a part of the source code performs an SRV DNS query to determine the final endpoint to download the actual gems from. 

```
Exception `OpenSSL::SSL::SSLErrorWaitReadable' at /home/denis/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/openssl/buffering.rb:182 - read would block
Exception `Resolv::DNS::Config::NXDomain' at /home/denis/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/resolv.rb:547 - _rubygems._tcp.api.rubygems.org
Exception `Errno::ECONNREFUSED' at /home/denis/.rvm/rubies/ruby-2.1.2/lib/ruby/2.1.0/net/http.rb:879 - Connection refused - connect(2) for "your-dns-needs-immediate-attention.network" port 443
```

The failure seems to be at the Resolv level. I haven't found much regarding this online, yet. Either everyone is in FUCKIT-TGIF mode or this is a relatively localized network issue. I am in Oakland, CA and I use Comcast as my ISP. 

Found this ICANN resource talking about name collision, but it is mostly beyond me: http://newgtlds.icann.org/sites/default/files/agreements/name-collision-assessment-04aug14-en.htm

What do?

**Comment by NathanBockrath** [comment]
There is a problem in mongoid.yml, where 'localhost' is interpreted as an IPv6 address (::1) and not as an IPv4 address 127.0.0.1 .  Try changing 'localhost' to your machine's IPv4 address in config/mongoid.yml .

There is an issue open for this on the mogoid JIRA server.
