### ISSUE TITLE
Slow installation starting with v2.2.0

### ISSUE THREAD

**Issue by toy** [rubygems/rubygems#1017]
Following script and its output show that time went from ~5s for v2.1.11 to 1m28 for v2.2.0 and ~2m32 for v2.4.1:

``` sh
for version in 2.1.11 2.2.0 2.4.1; do
  update_rubygems _"$version"_ > /dev/null
  gem --version
  time gem install image_optim
done
```

```
2.1.11
Successfully installed image_optim-0.16.0
1 gem installed

real    0m4.888s
user    0m2.051s
sys 0m0.174s
2.2.0
Successfully installed image_optim-0.16.0
1 gem installed

real    1m28.511s
user    0m3.557s
sys 0m0.314s
2.4.1
Successfully installed image_optim-0.16.0
1 gem installed

real    2m32.421s
user    0m0.338s
sys 0m0.100s
```

Running `gem install` with `--debug` shows that starting with v2.2.0 there are `Resolv::ResolvTimeout` errors rescued.

Checking source got me to `Gem::RemoteFetcher#api_endpoint` which uses resolving and `Gem::Source#api_uri` which was not used before v2.2.0.
Following code takes around 1m15 to fail:

``` ruby
require 'resolv'
Resolv::DNS.new.getresource '_rubygems._tcp.rubygems.org', Resolv::DNS::Resource::IN::SRV
```

**Comment by jamesmeador** [comment]
Is this still causing problems for anyone else? We're seeing this even with our own local RubyGems repos. Workaround suggestions?

**Comment by chino** [comment]
This is also an issue if your using a proxy and don't have dns at all in an isolated network.  When using a proxy the proxy handles any required dns resolutions for you.

**Comment by kch** [comment]
seeing this with vmware fusion 8.

**Comment by djberg96** [comment]
How is this looking with the release of 2.5.0 and its new resolver?

**Comment by geoff-codes** [comment]
I'm still running into this with ruby 2.3.0 ...

**Comment by msiemens** [comment]
Having this with ruby 2.3.0 on Windows 7 using msys2

**Comment by larsch** [comment]
Same issue on Ruby 2.2.4 on Windows.

The problem is really in Win32::Resolv which attemps to detect the configured DNS address. But it has the bad habbit of returning DNS server from interfaces that have been configured previously, but that you are no longer connected to (e.g. Wifi, USB Ethernet Dongles, etc.). As a workaround, you can remove these from HKLM\SYSTEM\CurrentControlSet\Services\Tcpip\Parameters\Interfaces in the registry.

I have filed https://bugs.ruby-lang.org/issues/12604 on the issue.

**Comment by ceefour** [comment]
```
$ gem install --verbose bundler
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://rubygems.org/specs.4.8.gz)
Getting SRV record failed: DNS result has no information for _rubygems._tcp.rubygems.org
```

:(

**Comment by rmoriz** [comment]
@colby-swandale why was this issue closed? It's still an issue :-(
