### ISSUE TITLE
Unresolved dependency when using a pull request branch

### ISSUE THREAD

**Issue by ryan2johnson9** [rubygems/rubygems#1052]
I cannot wait for a pull request on another gem to be merged (mail gem) so I wanted to get the gem straight from the branch for the pull request.

so I've added this to my gemfile:

```
gem 'mail', github: 'robin850/mail', branch: 'composition-parts-list' 
```

but now when my capistrano deploy runs this command:

rbx-2.2.10 bundle exec gem install --file Gemfile

i get the following error

```
gem stderr: ERROR:  While executing gem ... (Gem::DependencyError)
    Unresolved dependency found during sorting - mail (>= 2.5.4, ~> 2.5) (requested by actionmailer-4.1.6)
```

Running bundle in my development environment seems to work and adds this to my gemfile.lock

```
remote: git://github.com/robin850/mail.git
revision: a71fba146778773c92b683100376027c2e4f7c67 
branch: composition-parts-list
specs:
  mail (2.6.2.edge)
     mime-types (>= 1.16, < 3)
```

So the branch is 2.6.2 edge which is higher than the dependency specified in the error message.
I've seen a similar error resolved on your issue #990 but that is for gem versions ending with '.pre'.

Is this a bug or do I simply need to wait for that pull request on the mail gem to be merged so that I can specify a proper gem version rather than the github branch?

**Comment by sonalkr132** [comment]
Hi, I am not able to reproduce it with rubygems 2.6.6. Content of my `Gemfile`:
```Ruby
source 'https://rubygems.org'

gem 'mail', github: 'robin850/mail', branch: 'composition-parts-list' 
gem 'actionmailer', '4.1.6'
```
Using `bundle exec gem install --file Gemfile` gave:
> The git source git://github.com/robin850/mail.git is not yet checked out. Please run `bundle install` before trying to start your application
