### ISSUE TITLE
Simpler version matching

### ISSUE THREAD

**Issue by seanlinsley** [rubygems/rubygems#1053]
Since Rubygems doesn't have a way to require optional runtime dependencies, when working on the Active Admin gem I've often been frustrated by the available methods to version-check a loaded gem.

It seems like the correct way is:

``` ruby
Gem::Requirement.create('> 3').satisfied_by? Gem.loaded_specs['rails'].version
```

Not the easiest thing to remember, which I assume is why I often see developers comparing against the split version constants Rails provides:

``` ruby
Rails::VERSION::MAJOR > 3 && Rails::VERSION::MINOR > 2
```

Or, for gems that only have a version string:

``` ruby
Draper::VERSION > '1.3.0'
```

Both approaches get more complex of you want to correctly deal with prerelease versions, or match a range of versions.

To make development easier I built an [abstraction layer](https://github.com/activeadmin/activeadmin/blob/506c47e71/lib/active_admin/dependency.rb):

``` ruby
ActiveAdmin::Dependency.rails? '>= 3.2', '< 4.2'

ActiveAdmin::Dependency.rails >= 3.2

ActiveAdmin::Dependency.rails! '~> 4.1'
# raises an exception: You provided rails 3.2.18 but we need: ~> 4.1.

ActiveAdmin::Dependency.devise!
# when not provided, raises an exception: To use devise you need to specify it in your Gemfile.

ActiveAdmin::Dependency['jquery-ui-rails'] < 5
```

Would this general feature set be desirable for Rubygems itself?

**Comment by copiousfreetime** [comment]
Proposal is:

* update  `Gem::Requirement#satisfied_by?` to accept a `Gem::Version` or `Gem::Specification`
* update `Gem::Specification#satisfies_requirement?` to accept a `Requirement`, Requirement string or a `Dependency`
