### ISSUE TITLE
error : gem install rails -v 4.2.0.beta4 - Unresolved dependency found during sorting

### ISSUE THREAD

**Issue by govidat** [rubygems/rubygems#1062]
I am trying to install ver 4.2.0.beta4 on Ubuntu and am getting this error.

Versions:
ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-linux]
gem version 2.4.1

Error message on command : gem update
ERROR:  While executing gem ... (Gem::DependencyError)
    Unresolved dependency found during sorting - activesupport (>= 4.1.0) (requested by globalid-0.3.0)

Error message on command : gem install rails -v 4.2.0.beta4 
ERROR:  While executing gem ... (Gem::DependencyError)
    Unresolved dependency found during sorting - rack (~> 1.0) (requested by sprockets-2.12.3)

**Comment by coolgandhi** [comment]
Did you find the solution for this? I am having same issue and I have tried gem version from 2.3.0 to 2.4.5

gem -v
2.4.5

Gemfile 
...
...
gem 'thor', '~> 0.18.1'
gem 'activeresource', git: 'git://github.com/Shopify/activeresource', branch: 'threadsafe'
gem 'shopify_api', '>= 3.2.5'
....
...

ERROR:  While executing gem ... (Gem::DependencyError)
    Unresolved dependency found during sorting - activeresource (>= 3.0.0) (requested by shopify_api-3.2.6)


Thanks
