### ISSUE TITLE
gem list and gem install should take --yaml flag

### ISSUE THREAD

**Issue by zenspider** [rubygems/rubygems#107]
Idea: gem list --yaml | ssh server gem install --yaml

From: http://rubyforge.org/tracker/index.php?func=detail&aid=29230&group_id=126&atid=578

**Comment by djberg96** [comment]
@zenspider RF link is defunct. How would this work with other command line switches?

IMO a general formatting architecture would be better, so that all commands could take a --format option with text, yaml, xml and json as options.

**Comment by zenspider** [comment]
I don't understand your question. It has nothing to do with other command-line switches. It just affects the output (and input) as described above.

**Comment by copiousfreetime** [comment]
Checking if there is still interest. As I understand the feature it is adding the ability some commands have a structured stdin/stdout. The first use case being `list` and `install` so you could easily install a known set of gems into an new location. I could also see a structured input/output need for `fetch` and `uninstall`

**Comment by copiousfreetime** [comment]
This may be a consolidation of the `install -g` option. Where `list` may generate a gem dependency file.
