### ISSUE TITLE
Unresolved specs during Gem::Specification.reset

### ISSUE THREAD

**Issue by jordansissel** [rubygems/rubygems#1070]
```
WARN: Unresolved specs during Gem::Specification.reset:
      ffi (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
```

I don't know what causes this, and while it appears to cause no behavioral problems, the 4-line warning will cause users of my project to file bugs about it.

**Comment by jordansissel** [comment]
@drbrain I'll buy that we are doing weird things (possibly in weird orders) in `gems.rake` and elsewhere. Thanks for the advice on tracking that down!

On the other hand simply invoking `gem whatever` directly from the command line seems to cause this as well. It's totally funky. It may be because JRuby ships with a kind of fake ffi gemspec with the core release and it's always being loaded somehow?

**Comment by jordansissel** [comment]
Myself, @colinsurprenant, and @ph are hitting this pretty regularly, so I expect we'll be directing some more energy into debugging this. I hope we are able to fix it, and if there's any code needed, I think we can help provide that. 

More details as we have them :)

**Comment by mkristian** [comment]
@jordansissel with the next release 1.7.20 and already with 9k there is no default gem ffi anymore in jruby. before this a ```require 'openssl'``` did activated ffi due to jruby-openssl needed krypt which again depended on ffi (but never used it in the jruby case).

maybe worth looking a snapshot build of the jruby-1_7 first ;)

**Comment by steakknife** [comment]
We're also seeing this issue all over the place too in deployment-bundled rails apps and elsewhere.  The logstash donkey-punch appears to silence it.

**Comment by michaelrkn** [comment]
FWIW I get this warning all the time as well, but only with I have `RUBYGEMS_GEMDEPS=-`.

**Comment by shawndeprey** [comment]
I get this same warning after an upgrade to rails 4 when running `rake test:prepare`. It actually blocks the test prepare from running.

```
rake test:prepare
WARN: Unresolved specs during Gem::Specification.reset:
      minitest (~> 5.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
```

**Comment by williscool** [comment]
happened to me using https://github.com/quaertym/ember-cli-compass-compiler in ember.js project

by default it runs compass without bundle exec

Fixed my issues updating its command to be `bundle exec compass` re: https://github.com/quaertym/ember-cli-compass-compiler/issues/6

home that helps track it down

**Comment by copiousfreetime** [comment]
Is this still an issue for folks?

**Comment by michaelrkn** [comment]
I'm not working a ton with Ruby right now, but I just updated to the latest Rubygems and played around with a project where I used to get this, and I'm not seeing it right off the bat. I'll keep my eyes open, though.

**Comment by tururay** [comment]
I solved this problem with this answer: http://stackoverflow.com/a/18127613/2753913

    gem cleanup <gem-name>

...or:

    gem list <gem-name>

    gem uninstall

**Comment by seanlerner** [comment]
I had this problem.
It turned out I didn't have 
`eval "$(rbenv init -)"`
in my 
`.zshrc` file.

(I had just upgraded to oh-my-zsh from bash).
