### ISSUE TITLE
gem spec --ruby leaves duplicate deps

### ISSUE THREAD

**Issue by swills** [rubygems/rubygems#1079]
For example, see the output of gem spec --ruby with tilt 1.4.1, you get this line twice:

      s.add_development_dependency(%q<rdoc>, [">= 0"])

**Comment by swills** [comment]
I see this still has an indication that it's in need of feedback. What is needed?

**Comment by copiousfreetime** [comment]
This looks to be resolved. See https://github.com/rubygems/rubygems/blob/master/lib/rubygems/specification.rb#L2857-L2860

As an example on one of my gems:

```
% gem build envolve.gemspec
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    duplicate dependency on rdoc (~> 4.2, development), (~> 4.2) use:
    add_development_dependency 'rdoc', '~> 4.2', '~> 4.2'
```
