### ISSUE TITLE
missing 2.0.15 release file

### ISSUE THREAD

**Issue by mpapis** [rubygems/rubygems#1107]
http://production.cf.rubygems.org/rubygems/rubygems-2.0.15.tgz

**Comment by sai43** [comment]
same issue happen to me

**Comment by mpapis** [comment]
@sai43 what version of RVM is it? can you try again after `rvm get head`? if it fails again open a ticket for RVM => https://github.com/wayneeseguin/rvm/issues

**Comment by barkerd427** [comment]
I had the same problem as @sai43, and `rvm get stable` worked just fine in fixing it.

**Comment by hakunin** [comment]
had the same issue using rvm version `1.25.15 (stable)`, updating it fixed the issue

**Comment by RanSolo** [comment]
``` rvm get head ``` did the trick form me

**Comment by jcfigueiredo** [comment]
@RanSolo thanks for that.

**Comment by vcavallo** [comment]
Thanks @barkerd427!

**Comment by vincentmaithu** [comment]
@RanSolo :+1:

**Comment by aug-riedinger** [comment]
`rvm get head` did the trick for me too. :+1:

**Comment by copiousfreetime** [comment]
Sounds like this issue is no longer an issue. Closing.
