### ISSUE TITLE
Write up a guide / documentation about the plugin system

### ISSUE THREAD

**Issue by zenspider** [rubygems/rubygems#111]
Folks should know what the plugin system is, what it's intended use is, that there are some things it _isn't_ meant to be used for, but also, where to go to ask for help to determine whether something is a good fit for the plugin system

and/or ask for extension points to be added to the plugin system API. I will do some research on my own on this if there is time available and contribute if I end up coming up with anything useful, but please don't let that stop anyone who's actively working on RubyGems from beating me to it.

From: http://rubyforge.org/tracker/index.php?func=detail&aid=29243&group_id=126&atid=578

**Comment by djberg96** [comment]
Any progress?

**Comment by copiousfreetime** [comment]
There is some very basic documentation in the [rubygems plugin guide](https://github.com/rubygems/guides/blob/gh-pages/plugins.md) which ends up getting published on the rubygems site: http://guides.rubygems.org/plugins/

A pull request for in [rubygems guides repo](https://github.com/rubygems/guides) would probably be the best.

**Comment by tjouan** [comment]
I attempted a draft here:
https://github.com/rubygems/guides/pull/198

It's not complete, and most probably contains errors (either about the
plugin system, or english texts correctness), but I can fix and update
it.

> what it's intended use is, that there are some things it isn't meant to be used for

This part I'm not sure how to address it, @zenspider would you please
have one or more example about what we shouldn't do with the plugin
API?

**Comment by zenspider** [comment]
6.5 years later? No.

**Comment by tjouan** [comment]
Sorry I decided to start contributing here only a few days ago :-)
I like to start by oldest entries.

By the way I used your gem graph as an example in the draft I wrote, I
hope you don't mind.

If there are no other concerns, then maybe my changes once merged will
allow to close this issue eventually :-)

**Comment by bronzdoc** [comment]
closed by https://github.com/rubygems/guides/pull/198
