### ISSUE TITLE
Not able to update Ruby Gem Gem::RemoteFetcher::FetchError

### ISSUE THREAD

**Issue by steelx** [rubygems/rubygems#1116]
I'm trying to update my Jeykyll version. But not able to update the Ruby gem.

Im facing this issue. Im using Windows 8.1. Firewall is already checked, no blocking.

```
Microsoft Windows [Version 6.3.9600]
(c) 2013 Microsoft Corporation. All rights reserved.

C:\windows\system32>gem update jekyll
Updating installed gems
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certif
icate verify failed (https://api.rubygems.org/specs.4.8.gz)

C:\windows\system32>gem sources -a http://rubygems.org
https://rubygems.org is recommended for security over http://rubygems.org

Do you want to add this insecure source? [yn]  yes
http://rubygems.org added to sources

C:\windows\system32>gem update jekyll
Updating installed gems
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certif
icate verify failed (https://api.rubygems.org/specs.4.8.gz)

C:\windows\system32>

```

**Comment by Josephkouroma** [comment]
Thanks so much for sharing after days of googling and trying all sorts of weird and wonderful solutions yours is the only one that worked. Respect!

**Comment by drbrain** [comment]
I redacted the solution above as it is insecure and leaves you open to a man-in-the-middle attack.  Instead you need to [install the latest SSL CA certificates](https://gist.github.com/luislavena/f064211759ee0f806c88).

**Comment by sriharshakappala** [comment]
@drbrain That is the only solution in the entire internet that works! Thanks a ton. But I still wonder why no Stackoverflow answers point to that link!

**Comment by ushatel** [comment]
You may also use cmd set SSL_CERT_FILE=<path_to_ruby/GlobalSignRootCA.crt>

**Comment by Adilkemo** [comment]
Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed

**Comment by colby-swandale** [comment]
@Adilkemo see http://guides.rubygems.org/ssl-certificate-update/

**Comment by ieatcode** [comment]
try running it as Administrator
