### ISSUE TITLE
'gem generate_index' command doesn't fail if it can't write index files

### ISSUE THREAD

**Issue by coofercat** [rubygems/rubygems#1118]
Due to various permissions and ownership issues, "gem generate_index" claimed to run fine, but actually created an unusable repo.

I just tried to run "gem generate_index ." as a non-root user in a gem directory that had an unwritable (to me) 'quick' directory. The gem command output was normal (see below) but trying to install a new gem resulted in:
```
ERROR:  Could not find a valid gem 'rails' (>= 0), here is why:
          Unable to download data from http://gemserver.local/ruby-gems-repository/ - bad response Not Found 404 (http://gemserver.local/ruby-gems-repository/quick/Marshal.4.8/rails-4.2.0.gemspec.rz)
ERROR:  Possible alternatives: rails
```

Is there some overly broad exception catching going on somewhere? Can 'gem' be made to barf (even in an ugly way) if any of the critical files aren't written because of permissions, ownerships or disk full?

The output of the 'gem generate_index' was:
```
Generating Marshal quick index gemspecs for 225 gems
.................................................................................................................................................................................................................................
Complete
Generated Marshal quick index gemspecs: 0.105s
Generating specs index
Generated specs index: 0.004s
Generating latest specs index
Generated latest specs index: 0.002s
Generating prerelease specs index
Generated prerelease specs index: 0.000s
Compressing indicies
Compressed indicies: 0.001s
```
Resolution (for me) was to chown all the files to my non-root user and tore-run 'gem generate_index' (which gave much the same output once again, but correctly setup the files in the 'quick' directory).

**Comment by bronzdoc** [comment]
I think this is fixed in master, i just tried to reproduce it:

<code> gem generate_index . </code> inside a dir which i don't have write permission

<pre>
...
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ dir_s_mkdir - ./quick
</pre>

**Comment by djberg96** [comment]
@bronzdoc Ok, closing.
