### ISSUE TITLE
'gem generate_index' should include 'default' gems

### ISSUE THREAD

**Issue by coofercat** [rubygems/rubygems#1121]
(For the purposes of this issue: 'default gems' are the ones that come bundled with Ruby before any others are installed).

I assert that 'gem generate_index' should not treat default gems any differently from any other gems. It's arguable that 'gem install' should do something different for default gems, and it's clear than 'gem uninstall' shouldn't uninstall the default gems.

My reasoning is that things (like the json gem) have had quite a few updates which some other gems want. I can't see any problems after manually downloading an updated json gem and installing it on a system with an old one. The system correctly shows both versions installed, and its possible to remove the updated version. If something needs a specific version, it can require it via the usual mechanisms.

After quite a bit of sleuthing, I've found quite a bit of logic in indexer.rb that filters out 'default' gems from the indexes that 'gem generate_index' makes. I'll also point out that no warnings or notices are made about this - it just silently skips adding those gems to the indexes (which means that they're not properly available from the private repo). That silence cost me a few hours trying to figure out why some gems just weren't appearing in my repo :-(

I don't think the indexer should be making decisions about what can and can't be in my repo (especially not without a way to override those decisions). As I say above, I can accept that at install time I might need to supply a flag to say "yes, I know I'm updating a default gem", although I'm not really sure that's a requirement either.

If this idea is accepted, I can take a look at producing a patch for indexer.rb that removes the slient-default-skipping code.

**Comment by tenderlove** [comment]
Have you figured out *why* default gems are skipped?  I haven't looked in to the specific code, but if it's done on purpose, the git blame may give us some help.  On the surface, including default gems in `gem generate_index` seems reasonable to me, but maybe there is a deeper issue?

**Comment by coofercat** [comment]
That's sort of my point - whatever the reason this was built in doesn't seem to make sense to me, hence I'm asserting that the behaviour should be removed (or at the very least, made optional).

FWIW, one of our users is having a problem with minitest (another default gem). He needs version 4.7.x, but has 5.5 installed. I've put 4.7.0 into the repo, and reindexed but it's not showing up, so he can't install it (well, he can't even attempt to install it because the repo won't show it). To workaround, I've given him the gem file to install locally.

**Comment by drbrain** [comment]
Default gems are not included because there are no .gem files available to index or serve. There isn't a manifest to use to reconstruct the .gen file either.

**Comment by coofercat** [comment]
@drbrain I'm providing the .gem files in the repo for it to index (the files come from rubgems.org). It sees them, but specifically steps over them due to a whole lot of logic that skips gems of the same name as the default ones.

That's a good point - if I use Rubygems.org as my gem source, then I can get default gems, but if I'm using a local gem repo, I can't.

**Comment by copiousfreetime** [comment]
I believe this issues does not exist anymore. I've tested downloading default gems and running `generate_index` on them and the index appears to do everything right. 

If it can be shown that this is the incorrect behavior, please reopen

```
% gem list -d json minitest rake

*** LOCAL GEMS ***

json (1.8.3)
    Author:
    Installed at (default): /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0

    This json is bundled with Ruby

*** LOCAL GEMS ***

minitest (5.8.3)
    Author: Ryan Davis
    Homepage: https://github.com/seattlerb/minitest
    License: MIT
    Installed at: /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0

*** LOCAL GEMS ***

rake (10.4.2)
    Authors: Eric Hodel, Jim Weirich
    Homepage: https://github.com/ruby/rake
    License: MIT
    Installed at: /opt/rubies/ruby-2.3.0/lib/ruby/gems/2.3.0

    Rake is a Make-like program implemented in Ruby
% tree
.
└── gems
    ├── json-1.8.3.gem
    ├── minitest-4.7.5.gem
    ├── minitest-5.8.3.gem
    ├── minitest-5.8.4.gem
    ├── rake-0.9.6.gem
    ├── rake-10.4.2.gem
    └── rake-10.5.0.gem

1 directory, 7 files
% gem generate_index -V
Generating Marshal quick index gemspecs for 7 gems
1/7: json-1.8.3
2/7: minitest-5.8.4
3/7: minitest-5.8.3
4/7: minitest-4.7.5
5/7: rake-10.5.0
6/7: rake-10.4.2
7/7: rake-0.9.6
Complete
Generated Marshal quick index gemspecs: 0.004s
Generating specs index
Generated specs index: 0.000s
Generating latest specs index
Generated latest specs index: 0.000s
Generating prerelease specs index
Generated prerelease specs index: 0.000s
Compressing indices
Compressed indices: 0.001s
Moving index into production dir .
mkdir -p ./quick
rm -rf ./quick/Marshal.4.8
mv -f /var/folders/21/96m8fv9j3wg6wpm3bvwj05x80000gn/T/gem_generate_index_19200/quick/Marshal.4.8 ./quick/Marshal.4.8
rm -rf ./specs.4.8
mv -f /var/folders/21/96m8fv9j3wg6wpm3bvwj05x80000gn/T/gem_generate_index_19200/specs.4.8 .
rm -rf ./specs.4.8.gz
mv -f /var/folders/21/96m8fv9j3wg6wpm3bvwj05x80000gn/T/gem_generate_index_19200/specs.4.8.gz .
rm -rf ./latest_specs.4.8
mv -f /var/folders/21/96m8fv9j3wg6wpm3bvwj05x80000gn/T/gem_generate_index_19200/latest_specs.4.8 .
rm -rf ./latest_specs.4.8.gz
mv -f /var/folders/21/96m8fv9j3wg6wpm3bvwj05x80000gn/T/gem_generate_index_19200/latest_specs.4.8.gz .
rm -rf ./prerelease_specs.4.8
mv -f /var/folders/21/96m8fv9j3wg6wpm3bvwj05x80000gn/T/gem_generate_index_19200/prerelease_specs.4.8 .
rm -rf ./prerelease_specs.4.8.gz
mv -f /var/folders/21/96m8fv9j3wg6wpm3bvwj05x80000gn/T/gem_generate_index_19200/prerelease_specs.4.8.gz .

% tree
.
├── gems
│   ├── json-1.8.3.gem
│   ├── minitest-4.7.5.gem
│   ├── minitest-5.8.3.gem
│   ├── minitest-5.8.4.gem
│   ├── rake-0.9.6.gem
│   ├── rake-10.4.2.gem
│   └── rake-10.5.0.gem
├── latest_specs.4.8
├── latest_specs.4.8.gz
├── prerelease_specs.4.8
├── prerelease_specs.4.8.gz
├── quick
│   └── Marshal.4.8
│       ├── json-1.8.3.gemspec.rz
│       ├── minitest-4.7.5.gemspec.rz
│       ├── minitest-5.8.3.gemspec.rz
│       ├── minitest-5.8.4.gemspec.rz
│       ├── rake-0.9.6.gemspec.rz
│       ├── rake-10.4.2.gemspec.rz
│       └── rake-10.5.0.gemspec.rz
├── specs.4.8
└── specs.4.8.gz

3 directories, 20 files
% ruby -e "Marshal.load(IO.read('specs.4.8')).each { |s| puts s.inspect }"
["json", #<Gem::Version "1.8.3">, "ruby"]
["minitest", #<Gem::Version "4.7.5">, "ruby"]
["minitest", #<Gem::Version "5.8.3">, "ruby"]
["minitest", #<Gem::Version "5.8.4">, "ruby"]
["rake", #<Gem::Version "0.9.6">, "ruby"]
["rake", #<Gem::Version "10.4.2">, "ruby"]
["rake", #<Gem::Version "10.5.0">, "ruby"]
% ruby -e "Marshal.load(IO.read('latest_specs.4.8')).each { |s| puts s.inspect }"
["json", #<Gem::Version "1.8.3">, "ruby"]
["minitest", #<Gem::Version "5.8.4">, "ruby"]
["rake", #<Gem::Version "10.5.0">, "ruby"]
```
