### ISSUE TITLE
Source argument fails in several cases, ignored in others

### ISSUE THREAD

**Issue by stevepereira** [rubygems/rubygems#1122]
Trying to use --source or -s with either gem install or gem fetch fails with `invalid argument: -s http://mysourceURI`

I've tried also installing a private gem from my own http:// repo and a local file:// repo and despite being found by `gem search`, my blank gem: 'version 0.0.0' from rubygems is always the one installed. Adding `--verbose` and `--backtrace` don't make any difference in revealing a cause for this

This is within a brand new gemset, with rubygems up to date.

So I tried adding the http:// source via `gem source --add` and the following results from an install attempt:
```
$ gem install my_gem --pre
ERROR:  While executing gem ... (TypeError)
    incompatible marshal file format (can't be read)
	format version 4.8 required; 60.63 given
```

This is after a fresh gem `generate_index` and rebuilding the repo, also the search fails if the repo isn't properly built, so I assume it's correct.

```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.5
  - RUBY VERSION: 2.2.0 (2014-12-30 patchlevel 0) [java]
  - INSTALLATION DIRECTORY: /home/vagrant/.rvm/gems/jruby-1.7.16.11@gem_tasks
  - RUBY EXECUTABLE: /home/vagrant/.rvm/rubies/jruby-1.7.16.11/bin/jruby
  - EXECUTABLE DIRECTORY: /home/vagrant/.rvm/gems/jruby-1.7.16.11@gem_tasks/bin
  - SPEC CACHE DIRECTORY: /home/vagrant/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/vagrant/.rvm/rubies/jruby-1.7.16.11/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-java-1.7
```

I have no idea what else to do, I feel like I've tried every possible way to get this to work...

**Comment by drbrain** [comment]
You don't show your sources in your output or in your commands.

It appears that your source does not point to a rubygems repository.  The first two characters are `<?` (60.63).  Run with `-V` to see what RubyGems is attempting to fetch and make sure those URLs work.

**Comment by stevepereira** [comment]
Seems like it was somehow related to s3 storage/serving - switching to geminabox resolved
