### ISSUE TITLE
gem open does not change current working directory

### ISSUE THREAD

**Issue by awood** [rubygems/rubygems#1129]
The newish gem open command looks like it was inspired by tpope's gem-browse, but there is one major difference.  In gem-browse, opening a gem will change the current working directory to the gem's directory making it easy and convenient to open additional files or browse with a tree like vim's NERDTree.  

However the new builtin command doesn't change the working directory (at least for me it doesn't) even though the help text says it does: "The open command opens gem in editor and changes current path to gem's source directory."

tpope's plugin has some code like

```ruby
Dir.chdir(gemspec.full_gem_path) do
  edit(gemspec.full_gem_path)
end
```

but I don't see anything like that in the new builtin.  Perhaps this is intentional or I am missing something?  If not, I'd love to see the change working directory functionality added and would be willing to submit a PR if this is infact a defect.

For the record, I am using 2.4.1 but I don't see any code to change the directory even in master for open_command.rb.

**Comment by tenderlove** [comment]
I don't think you are missing anything, it sounds like a bug.  Can you make a PR to fix this?
