### ISSUE TITLE
Specification#ruby_code should be more secure with arrays

### ISSUE THREAD

**Issue by zenspider** [rubygems/rubygems#113]
Either check that everything within is clean, or recurse on each member.

From: http://rubyforge.org/tracker/index.php?func=detail&aid=28902&group_id=126&atid=575

**Comment by djberg96** [comment]
@zenspider Can you update please? With RF now defunct, I'm not sure what this is in reference to.

**Comment by zenspider** [comment]
No, I can't update this.

**Comment by copiousfreetime** [comment]
Closing this as the original bug on rubyforge is gone and we don't know what this is in reference too.
