### ISSUE TITLE
Slow require for the first not exist file

### ISSUE THREAD

**Issue by Locke23rus** [rubygems/rubygems#1132]
Example is here: https://gist.github.com/Locke23rus/96276a524ada8b43d1c1
What I found is that [this code](https://github.com/rubygems/rubygems/blob/e53c54a87c3b964206e47a127e3126f7b2c33edc/lib/rubygems/specification.rb#L705) is called only for the first not exist file and took 75ms. The problem is in method `#to_spec`.

**Comment by mfazekas** [comment]
see #1167

**Comment by copiousfreetime** [comment]
At the moment, this slow down does not appear to be as drastic as it once was.
```
% ruby -v
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
% gem -v
2.5.1

% gem list

*** LOCAL GEMS ***

bigdecimal (1.2.8)
did_you_mean (1.0.0)
io-console (0.4.5)
json (1.8.3)
minitest (5.8.3)
net-telnet (0.1.1)
oj (2.14.4)
power_assert (0.2.6)
psych (2.0.17)
rake (10.4.2)
rdoc (4.2.1)
test-unit (3.1.5)

% ruby slow_require.rb
2.5ms - time
1.37ms - oj/error
0.29ms - not_exist_file1
0.23ms - not_exist_file2
```

 I think #1167 probably is doing a more thorough investigation of this issue on a whole. I'm going to close this as a duplicate.
