### ISSUE TITLE
Is it possible to get current signed in user handle

### ISSUE THREAD

**Issue by waterlink** [rubygems/rubygems#1146]
When using `gem push` for the first time, it authenticates you with email/handle and password. Subsequent pushes use retrieved api_key.
Given I have 2-3 rubygems accounts on one laptop, how am I supposed to check if I'm using the right account or not?
I was hoping for something like: `gem whoami` but I can't find anything that would resemble it.

**Comment by djberg96** [comment]
I don't see one. I feel like this might be a nice option to add to "gem owner".

**Comment by bronzdoc** [comment]
A PR implementing this would be accepted, but i'm going a close this issue meanwhile since it has been ide for too long
