### ISSUE TITLE
Please remove malicious rails-assets-angular gem

### ISSUE THREAD

**Issue by teamon** [rubygems/rubygems#1148]
I am writing on behalf of http://rails-assets.org maintainers.

Please remove all versions of rails-assets-angular gem from official rubygems repository.
This gem is nearly the same as rails-assets-angular from http:/rails-assets.org, but includes 
`alert("I'm in your app.")` line in `angular.js` file.

Gems prefixed with `rails-assets-` are supposed to be bower packages repacked as ruby gems and downloaded only from http://rails-assets.org source.

Publishing malicious rails-assets-angular gem to rubygems.org is clearly not acceptable behaviour. 

Thanks to @sheerun there is already a workaround in place to prevent future attacks - https://twitter.com/railsassets/status/558376685566181376

We apologise all users that have accidentally downloaded the malicious gem. 
The new block syntax will hopefully block such attempts. 

We still strongly believe in the good will of Open Source community around rubygems.org and rails-assets.org. In case of any issues with rails-assets.org service please contact any of us via twitter or [rails-assets.org GitHub Issues](https://github.com/rails-assets/rails-assets/issues)

**Comment by tenderlove** [comment]
/cc @evanphx @qrush 

I think this ticket needs to be reported to the rubygems.org issues, but I'm ccing some rubygems.org folks for attention.

**Comment by evanphx** [comment]
@teamon We don't have any such agreement about how the name prefix of a gem is used within rubygems.org, so this isn't really something we'd do.

Have you contacted the author of the gem? That's what you really need to do. Given the trivial change that was done, I'm guessing perhaps it was pushed on accident or as a simple test.

**Comment by sheerun** [comment]
Hey. I already contacted him before. I'm waiting for response. It could be an accident.

Unfortunately in meantime many installations of this gem are happening and possibly some productions are breaking.. If you have possibility to yank this gem manually, please do so.

**Comment by sheerun** [comment]
By the way:

1. Does rubygems lock source for installed gems?
2. Even after putting RubyGems and RailsAssets in separate source blocks, we get all gem names in our /dependencies API endpoint. Is it desired behavior? I think we should receive gem names only from our source block.

**Comment by evanphx** [comment]
@sheerun We don't yank gems under these circumstances, sorry. I certainly sympathize with it breaking things but the breakage is not related to using rubygems.org in an invalid way. We have to watch out for the policy that applies to all rubygems.org users.

**Comment by sheerun** [comment]
Sorry, these are probably bundler questions, not rubygems.. Never mind.

**Comment by evanphx** [comment]
@sheerun You're question is rubygems related (while this is under the rubygems repo, the issue is really a rubygems.org one). Are you using the builtin rubygems dependency management or bundler?

**Comment by sheerun** [comment]
FYI it seems it's impossible to go back after malicious gem is already installed without uninstalling to manually: https://github.com/bundler/bundler/issues/3360

**Comment by dwradcliffe** [comment]
Closed since this is being discussed in the other issue.

**Comment by sheerun** [comment]
:+1:
