### ISSUE TITLE
[gem spec] Output plaintext format instead of ruby 

### ISSUE THREAD

**Issue by frodsan** [rubygems/rubygems#1150]
Hi,

Is it possible to output spec fields in plaintext? Like this:

```
$ gem spec minitest version --plaintext
5.4.3
```

If not, I could add that option if you think is a good feature.

Thanks.

**Comment by bronzdoc** [comment]
Is this something we want?

**Comment by indirect** [comment]
Since this hasn't gotten any comments for two years, I think it impacts too few users to be worth adding right now.
