### ISSUE TITLE
error installing fastthread: extconf.rb:13:in `block in <main>': uninitialized constant Config (NameError)

### ISSUE THREAD

**Issue by pudx** [rubygems/rubygems#1151]
Initial searches did not find indication that this problem was previously logged. This error appears with a gem install on CentOS 6.4 x64 (2.6.32-431.20.5.el6.x86_64); the Ruby version is the recent 2.2.0, so it is remotely possible that something new in Ruby broke it.

$ gem --version
2.4.5

$  gem install fastthread --no-rdoc --no-ri
Fetching: fastthread-1.0.7.gem (100%)
Building native extensions.  This could take a while...
ERROR:  Error installing fastthread:
        ERROR: Failed to build gem native extension.

    /usr/local/rvm/rubies/ruby-2.2.0/bin/ruby -r ./siteconf20150126-24200-x0cdu4.rb extconf.rb
extconf.rb:13:in `block in <main>': uninitialized constant Config (NameError)
        from extconf.rb:12:in `open'
        from extconf.rb:12:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /usr/local/rvm/gems/ruby-2.2.0/gems/fastthread-1.0.7 for inspection.
Results logged to /usr/local/rvm/gems/ruby-2.2.0/extensions/x86_64-linux/2.2.0/fastthread-1.0.7/gem_make.out

**Comment by evanphx** [comment]
This is fastthread related. It doesn't work on newer rubies (nor do you need it.)

**Comment by pudx** [comment]
OK, thank you for explaining.

**Comment by Vishal-Joshi** [comment]
I am getting the same error on MacOS-El Capitan (10.11.6 (15G1004)).

`RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-darwin15]
  - INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/2.3.0`

When I do, 

> bundle install, then it fails saying 
`Installing debugger 1.6.8 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /usr/local/lib/ruby/gems/2.3.0/gems/fastthread-1.0.7/ext/fastthread
/usr/local/opt/ruby/bin/ruby -r ./siteconf20170123-65307-18rwwfb.rb extconf.rb 
extconf.rb:13:in `block in <main>': uninitialized constant Config (NameError)
Did you mean?  RbConfig
        from extconf.rb:12:in `open'
        from extconf.rb:12:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/2.3.0/gems/fastthread-1.0.7 for inspection.
Results logged to /usr/local/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0/fastthread-1.0.7/gem_make.out
`

@evanphx, as you say it is not needed on newer rubies, then how can we avoid it from bundle install?

**Comment by drbrain** [comment]
You don't need the fastthread gem with modern ruby (2.3.0), so contact the maintainer of the debugger gem to remove the dependency.
