### ISSUE TITLE
Invalid Download Count

### ISSUE THREAD

**Issue by LouHenryAlvarez** [rubygems/rubygems#1153]
rubygems.org is not keeping correct count of downloads.  I have had several of my friends download gems while watching the rubygems.org page for that gem and the count does not change, even when downloading on different machines.

**Comment by tenderlove** [comment]
Can you file this on [rubygems/rubygems.org](https://github.com/rubygems/rubygems.org)?  This issue tracker is for rubygems itself, not the website.

Thanks!

**Comment by LouHenryAlvarez** [comment]
Sorry, my bad.

Thanks,

Lou
