### ISSUE TITLE
Feature request: Adding a dev_path to gem 'dependency'

### ISSUE THREAD

**Issue by alexturek** [rubygems/rubygems#1154]
The team I'm working on is using a Gemfile (e.g. in ```package A```) that includes some of our own gems (either specified by version or with a git url) (e.g. ```package B```). When we're changing both A and B at the same time, it's a lot easier to change the Gemfile to say ```path: '../package_b'```, but then we have a change in our Gemfile that shows up in Git, that we have to be careful about not committing.

Right now ```gem``` in a Gemfile has at most one of (path, git repo, or version). I think it'd be handy to be able to specify a fallback mechanism where ```dev_path: '../package_b'``` supersedes the others, e.g. turn this:

    # gem 'foobar', '~> 3.0' # This is commented out and shows up as a git change
    gem 'foobar', path: '../foobar' # This is uncommented and shows up as a git change

into this:

    gem 'foobar', '~> 3.0', dev_path: '../foobar'

I'm sure the name of the argument could be improved, but the behavior I'd like to see is "check in this local path before using the normally-specified gem location"

**Comment by alexturek** [comment]
Also please tell me if there's already a way to do this and I'm just being dumb :)

**Comment by alexturek** [comment]
#448 looks related too

**Comment by drbrain** [comment]
I use `ruby -I` (with the appropriate directory) when developing multiple gems at the same time.  It allows me to use the latest version without having to worry about accidentally committing something I didn't want to.

Since Bundler is the owner if this feature I'm going to pull in @indirect on this one.

**Comment by indirect** [comment]
Fallback mechanisms are messy and make everything confusing. Bundler provides a [git locals](http://bundler.io/v1.7/git.html#local) feature that might do what you want. If that's not what you want, you should manage your own load paths (using `-I` or otherwise).

**Comment by alexturek** [comment]
@drbrain Thanks for the suggestion and help getting this to the right person
@indirect Totally understood; I wasn't too excited about how that was structured

I'll probably just end up writing a function to use in the Gemfile that does what my team wants
