### ISSUE TITLE
gem generate_index and SELinux

### ISSUE THREAD

**Issue by jakerobinson** [rubygems/rubygems#1158]
When performing a `gem generate_index` the security context remains as `user_tmp_t`, requiring a need to run `restorecon` on the file.

before `restorecon`:

```
# ls -Z /var/www/gems/specs.4.8.gz 
-rw-rw-r--. gemserver gemserver unconfined_u:object_r:user_tmp_t:s0 /var/www/gems/specs.4.8.gz
```

after `restorecon`:

```
# ls -Z /var/www/gems/specs.4.8.gz 
-rw-rw-r--. gemserver gemserver unconfined_u:object_r:httpd_sys_content_t:s0 /var/www/gems/specs.4.8.gz
```

**Comment by tenderlove** [comment]
Do you know why this is happening? I don't have SELinux handy.

**Comment by jakerobinson** [comment]
I think I do... it has to do with the security context being copied. I believe that `generate_index` is doing a copy from /tmp, which is why it keeps its security context.

https://www.centos.org/docs/5/html/Deployment_Guide-en-US/rhlcommon-chapter-0017.html

**Comment by copiousfreetime** [comment]
If what @jakerobinson links to is the correct SELinux item we need to work around, it stems from the use of a tmp directory that is created (https://github.com/rubygems/rubygems/blob/master/lib/rubygems/indexer.rb#L67) and then the items in that tmp directory are moved into the destination directory with `FileUtils.mv` (https://github.com/rubygems/rubygems/blob/master/lib/rubygems/indexer.rb#L300-L331). 

The quick solution would be to switch to using `FileUtils.cp` and then a `rm` nstead of `mv` which would avoid this situation.

**Comment by bronzdoc** [comment]
@jakerobinson is this still an issue for you?

**Comment by bronzdoc** [comment]
Closing for lack of response
