### ISSUE TITLE
install should suggest pre-release Gems

### ISSUE THREAD

**Issue by rubychan** [rubygems/rubygems#116]
Simple story: I read about some gem (shoulda-context), so I tried "gem install shoulda-context":

    ERROR:  Could not find a valid gem 'shoulda-context' (>= 0) in any repository
    ERROR:  Possible alternatives: shield-contrib, tu-context

Then I found out that there _is_ a gem, only it's (as of now) a prerelease gem: 1.0.0.beta1.

It would be nice for RubyGems to inform me about that. I think it's obvious that one wants to know about pre-release versions of a gem when no gem was found.

**Comment by djberg96** [comment]
I think this is just a matter of appending "available_specs(:prerelease)" in the suggest_gems_from_name method in spec_fetcher.rb. I don't know how much of a hit that adds, though.

**Comment by copiousfreetime** [comment]
I concur, upon a failure to install, the install command will end up calling `Command#show_lookup_failure` which in turn calls `Gem::SpecFetcher.fetcher.suggest_gems_from_name`. 

I think the solution would be, if no matches were found when looking at the latest specs (https://github.com/rubygems/rubygems/blob/master/lib/rubygems/spec_fetcher.rb#L189) then it should try again with the `:pre_release` specs
