### ISSUE TITLE
NoSecurity / No policy behavior is not consistent

### ISSUE THREAD

**Issue by wied03** [rubygems/rubygems#1160]
**Steps to recreate:**

1. Create an unsigned GEM (or fetch one off the Internet)
1. Instantiate a Gem::Package object (pkg = Gem::Package.new 'capistrano-3.3.5.gem')
1. pkg.security_policy = Gem::Security::Policies['NoSecurity']
1. pkg.verify

**Expected result:** The same as running pkg.verify with a nil security policy

**Actual result:** Get an undefined 'extensions' for nil:NilClass error in policy.rb because we have digests but no signatures.  This comes from an alert_warning "#{subject signer} call inside policy's verify method.

Shouldn't NoSecurity behave the same as not setting a policy at all?

**Comment by copiousfreetime** [comment]
Just tested this, and this appears to no longer be a bug, `NoSecurity` behaves the same as a nil policy other than the `WARNING` that prints out. There is no exception.
```
>> require 'rubygems/package'
=> true
>> pkg = Gem::Package.new 'stickler-2.4.2.gem'
=> #<Gem::Package:0x007fe8fa2c1290 @gem=#<Gem::Package::FileSource:0x007fe8fa2c13d0 @path="stickler-2.4.2.gem", @start="metadata.gz\x00\x00\x00\x00\x00\x00\x00\x00\x00">, @build_time=2016-03-14 10:43:21 -0600, @checksums={}, @contents=nil, @digests={}, @files=nil, @security_policy=nil, @signatures={}, @signer=nil, @spec=nil>
>> pkg.verify
=> true
>> pkg.security_policy
=> nil
>> pkg.security_policy =  Gem::Security::Policies['NoSecurity']
=> [Policy: No Security - data: false signer: false chain: false root: false signed-only: false trusted-only: false]
>> pkg.verify
WARNING:  stickler-2.4.2 is not signed
=> true
```
