### ISSUE TITLE
silence install message via .gemrc

### ISSUE THREAD

**Issue by grosser** [rubygems/rubygems#1163]
most post install messages are either garbage or I get tired of them after I saw them 10 times ...
would a PR to remove them via .gemrc option / commandline option be merged ?

case in point: 200+ stars on https://github.com/tpope/gem-shut-the-fuck-up so this is a common issue I'd think, just not a big one

/cc @tpope

**Comment by simi** [comment]
actually https://github.com/rubygems/rubygems/pull/1162

**Comment by grosser** [comment]
perfect, thx! :D
