### ISSUE TITLE
Feature request: Add sensible aliases

### ISSUE THREAD

**Issue by dt1973** [rubygems/rubygems#1165]
Could we add a few aliases to RubyGems, ie.:

```
# gem remove foo
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command remove
# gem delete foo
ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown command delete
# gem uninstall foo
Remove executables:
        foo

in addition to the gem? [Yn]  y
```

**Comment by djberg96** [comment]
"gem alias" sounds like a nice idea for a plugin. :)

**Comment by copiousfreetime** [comment]
Personally I'm thinking this would better be done as a plugin to start and then see how much it catches on.

This functionality appears to have already been written once as [gem-alias](https://rubygems.org/gems/gem-alias) although that gem appears to be abandoned and doesn't work with today's rubygems. 

I would suggest that if someone wanted to work on this they take inspiration from that old gem.

**Comment by segiddins** [comment]
I'm :-1: on adding aliases -- it's a maintenance burden with very little benefit, most of which can be achieved through plugins / shell aliases already.

**Comment by copiousfreetime** [comment]
I'm :-1: myself, so lets close it.
