### ISSUE TITLE
Requiring may now raise Gem::Ext::BuildError instead of LoadError

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems#1166]
Because of the new "autobuilding" extension behavior, it is possible to raise a `Gem::Ext::BuildError` error simply by calling `require`. This runs counter to all expectations of how `require` works, and makes it impossible to rescue errors and handle them in a sensible way.

For example, in [this backtrace](https://github.com/bundler/bundler/issues/3372), Rubygems tries to build the Nokogiri gem because the net/http/persistent gem tries to require net/http/pipeline, like so:

```ruby
begin
  require 'net/http/pipeline'
rescue LoadError
end
```

I'm pretty sure that net/http/pipeline does not depend on Nokogiri, so this is surprising on multiple levels. Furthermore, as that block shows, it should be impossible for a call to `require` to raise any exceptions other than `LoadError`.

**Comment by ryanatball** [comment]
require executes ruby code, so it can and does raise any possible exception in the Ruby language.    LoadError only occurs when require can't find the file given.

**Comment by drbrain** [comment]
True, but this is a change in behavior. I consider this a bug and LoadError should be raised instead.

**Comment by ryanatball** [comment]
Perhaps Gem::Ext::BuildError should be a subclass of LoadError?

**Comment by evanphx** [comment]
If we do want to expose it, we should rescue `BuildError` and raise a different one that is specific to getting a BuildError while loading.

**Comment by copiousfreetime** [comment]
I've attempted to replicate this, and it appears that a9c1aaffec may have, as a side effect, fixed this issue.

Confirmation from @indirect maybe?

**Comment by indirect** [comment]
@copiousfreetime sounds like it is indeed fixed.
