### ISSUE TITLE
uninitialized constant Gem::UserInteraction (NameError)

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#1174]
This was originally reported as #784 and since part of the issue was resolved, I create this ticket to solve the other part. There might happen tracebacks like this https://gist.github.com/indirect/90a19aa3eee72e412bfa and this is my analysis originally posted in #784

> Another issue is this commit:
>
> 68da16d
>
> If you will take a look on the tracebak, you'll se that during the load of "user_interaction.rb", RubyGems are trying to load "io/console" [1]. But in that moment, the Gem::UserInteraction is not know to Ruby yet, so indeed, the Builder cannot obviously find the constant. I tried to move the "require 'io/console'" to the end of the file, which resolved one particular issue, but soon I hit similar problem with Gem::Ext::ExtConfBuilder. The #924 might be cure for this.
>
> To conclude, I am afraid that the 'io/console' should be lazily loaded, as it used to be.
>
> [1] https://gist.github.com/indirect/90a19aa3eee72e412bfa#file-gistfile1-txt-L20

**Comment by zzak** [comment]
@voxik Thanks for following up! Did you try my patch in #924? Did it fix your issues?

**Comment by JacobEvelyn** [comment]
I'm seeing this issue but embarrassingly I don't know where the `rubygems` source lives on my computer to apply the patch your patch, @zzak. Any guidance would be much appreciated!

**Comment by voxik** [comment]
@zzak sorry for delay.

Well, the patch itself does not help, since rubygems/ext/builder is using Gem::UserInteraction and it cannot require the file, since it is already somewhere on the way to build the extensions.

Nevertheless, since the autobuilding of gem's extensions was disabled in #796, I don't think this is necessary anymore. Unfortunately, this leaves RubyGems 2.2.x broken (and Bundler still executes its test suite against it) :/

**Comment by zzak** [comment]
@voxik If you can convince me this is a bug, I may be able to release a bugfix for 2.2.

**Comment by copiousfreetime** [comment]
This does not appear to be a bug anymore. Please reopen if that is no longer the case.
