### ISSUE TITLE
Locks and NFS mounted drives

### ISSUE THREAD

**Issue by mooreryan** [rubygems/rubygems#1176]
My issue seems to be similar to the one found here: https://github.com/rubygems/rubygems/issues/1036, but that one was closed for lack of activity.

I'm also having trouble with those two lines of code that @jnory commented out. Here they are for reference:

`~/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems.rb:773`
```
  def self.read_binary(path)
    open path, 'rb+' do |f|
      f.flock(File::LOCK_EX) # <= This line
      f.read
    end

  rescue Errno::EACCES
    open path, 'rb' do |f|
      f.read
    end
  end
```

and

`~/.rvm/rubies/ruby-2.2.0/lib/ruby/site_ruby/2.2.0/rubygems/remote_fetcher.rb:310`

```
def cache_update_path uri, path = nil, update = true
    mtime = path && File.stat(path).mtime rescue nil

    data = fetch_path(uri, mtime)

    if data == nil # indicates the server returned 304 Not Modified
      return Gem.read_binary(path)
    end

    if update and path
      open(path, 'wb') do |io|
        io.flock(File::LOCK_EX) # <= This line
        io.write data
      end
    end

    data
  end
```

I think it is related to this pull request: https://github.com/rubygems/rubygems/pull/1005. In particular, I'm trying to use `gem install` on an nfs mounted drive, e.g.,
```
$ gem install trollop
ERROR:  While executing gem ... (Errno::ENOLCK)
    No locks available @ rb_file_flock - ~/.gem/specs/api.rubygems.org%443/quick/Marshal.4.8/trollop-2.1.1.gemspec
```
I followed the stack trace and the lines shown above were the cuplrits.

Does ruby have anything like `stat -f -L -c %T my_file` to perhaps check if you're trying to lock a file on an nfs mounted drive? I see that the `rubygems.rb` file rescues `Errno::EACCES`, so perhaps it is possible to check for nfs mounted drives as well?

**Comment by djberg96** [comment]
I think you would have to use fcntl, and it wouldn't work on all platforms, and it has its own issues:

https://github.com/jruby/jruby/issues/828

**Comment by djberg96** [comment]
Just thinking out loud here, is the error distinguishable between already locked vs lock not supported? If so, we could rescue the error that indicates the lock isn't supported and simply ignore it.

**Comment by ahoward** [comment]
yeah that can't work on NFS.  even fcntl isn't enough. 

  https://github.com/ahoward/lockfile

**Comment by djberg96** [comment]
Would this work?

https://github.com/djberg96/rubygems/commit/b25d9a304b9fa48f96d41fb976c81d6e5a018c41

The idea here being that it would abandoned the lock attempt on an Errno::ENOLCK unless you're in a multithreaded environment.

It's a bit of a shot in the dark for me, so forgive me if this is dumb. ;)

**Comment by djberg96** [comment]
@ahoward That's what I suspected, thanks for looking. Your solution looks non-trivial.

**Comment by djberg96** [comment]
There doesn't seem to be any objections, going to merge.
