### ISSUE TITLE
gem from git source slows down ruby on load

### ISSUE THREAD

**Issue by khoan** [rubygems/rubygems#1177]
Not sure if this is the right tree to bark. But here goes:

When a gem is sourced from git remote in Gemfile, ruby load just slows down. Some side effect is pow.cx timing out __Error: timeout: waiting for /tmp/nack.8923.847587995.sock__ So pow is basically unusable.

Should we just skip going to git if gem is already bundled?

``` sh
$ bundle init; bundle
$ time ruby -e 1
real	0m0.173s
user	0m0.131s
sys	0m0.041s

$ echo 'gem "mongoid", github: "mongoid/mongoid"' >> Gemfile; bundle
#The terminal title changes from ruby to git to ruby
$ time ruby -e 1
real	0m3.445s
user	0m0.443s
sys	0m0.161s

# disconnect from net
$ ruby -e 1
fatal: Unable to look up github.com (port 9418) (nodename nor servname provided, or not known)

# setup
$ bundle --version
Bundler version 1.8.2
$ echo "_${RUBYGEMS_GEMDEPS}_"
_-_
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.6
  - RUBY VERSION: 2.2.0 (2014-12-25 patchlevel 0) [x86_64-darwin13]
  - INSTALLATION DIRECTORY: /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0
  - RUBY EXECUTABLE: /usr/local/var/rbenv/versions/2.2.0/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/var/rbenv/versions/2.2.0/bin
  - SPEC CACHE DIRECTORY: /Users/khoan/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/var/rbenv/versions/2.2.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-13
  - GEM PATHS:
     - /usr/local/var/rbenv/versions/2.2.0/lib/ruby/gems/2.2.0
     - /Users/khoan/.gem/ruby/2.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org
  - SHELL PATH:
     - /usr/local/var/rbenv/versions/2.2.0/bin
     - /usr/local/Cellar/rbenv/0.4.0/libexec
     - /usr/local/var/rbenv/shims
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /opt/X11/bin
```

**Comment by tenderlove** [comment]
If you're using Bundler, don't set `RUBYGEMS_GEMDEPS` to `-`.  For now, I think you should use bundler, or the `RUBYGEMS_GEMDEPS` thing, but not both at the same time.  Right now, it seems that RubyGems' Gemfile stuff will *always* try to resolve stuff in the Gemfile (even if there is a lockfile).

Out of curiosity, where did you learn about the `RUBYGEMS_GEMDEPS` environment variable?

**Comment by tenderlove** [comment]
Oh, I forgot to say, do `unset RUBYGEMS_GEMDEPS` to speed it up.

**Comment by khoan** [comment]
@tenderlove thanks for your reply

got sick of having to prefix commands with bundle exec so google suggested RUBYGEMS_GEMDEPS environment variable https://twitter.com/judofyr/status/416535759207034881

**Comment by indirect** [comment]
@khoan @tenderlove Setting `RUBYGEMS_GEMDEPS` is not a good way to fix the `bundle exec` problem. Right now, I would suggest either `alias b="bundle exec"` or `bundle binstubs GEMNAME; export PATH=bin:$PATH`. (But be aware that putting `./bin` on your path can be a potential security issue).

**Comment by jrochkind** [comment]
There's no way to use RUBYGEMS_GEMDEPS without using bundler, is there? it uses a Gemfile. Plus nobody wants to give up Bundler, my understanding is that the whole point of RUBYGEMS_GEMDEPS was to let you use bundler, but not have to do `bundle exec` all the time, have the equivalent functionality integrated into rubygems. 

So I'm thinking the advice "For now, I think you should use bundler, or the RUBYGEMS_GEMDEPS thing, but not both at the same time." actually means: RUBYGEMS_GEMDEPS is not ready for primetime yet, we've all got to keep bundle exec'ing.  

It would be useful if the rubygems devs could clarify the intent of RUBYGEMS_GEMDEPS, and what they consider it's current matureness/robustness status to be.

**Comment by jrochkind** [comment]
There's no way to use RUBYGEMS_GEMDEPS without using bundler, is there? it uses a Gemfile. Plus nobody wants to give up Bundler, my understanding is that the whole point of RUBYGEMS_GEMDEPS was to let you use bundler, but not have to do `bundle exec` all the time, have the equivalent functionality integrated into rubygems. 

So I'm thinking the advice "For now, I think you should use bundler, or the RUBYGEMS_GEMDEPS thing, but not both at the same time." actually means: RUBYGEMS_GEMDEPS is not ready for primetime yet, we've all got to keep bundle exec'ing.  

I learned about the `RUBYGEMS_GEMDEPS` from the [rubygems-bundler](https://github.com/mpapis/rubygems-bundler) README, which suggested `RUBYGEMS_GEMDEPS` obsoleted rubygems-bundler, and you could just use `RUBYGEMS_GEMDEPS`. That README suggests the intention of `RUBYGEMS_GEMDEPS` was to do the same thing as `rubygems-bundler`, let you skip `bundle exec`.  If that's mistaken, someone should maybe tell rubygems-bundler folks. 

It would be useful if the rubygems devs could clarify the intent of RUBYGEMS_GEMDEPS, and what they consider it's current matureness/robustness status to be.  

I don't know if I should give rubygems-bundler a try, even though it says it's been obsoleted by RUBYGEMS_GEMDEPS, or if I should just give up and resign myself to bundle exec forever.

**Comment by copiousfreetime** [comment]
Closing this as I think the discussion is complete and there doesn't appear to be a bug.
