### ISSUE TITLE
[gem install] installs multipe platforms

### ISSUE THREAD

**Issue by ABaumgaertner** [rubygems/rubygems#1179]
it is possible to install a gem for multiple platforms.
gems that have been build with devkit use --platform=ruby (devkit platform is x64-mingw32)
when you run gem install (or bundle install) the gem is installed again - with specific platform binaries: x64-mingw32

see https://bugs.ruby-lang.org/issues/10919 for full details.

**Comment by tenderlove** [comment]
Thanks for the report.  I'm not sure what to do about this.

> solution a:
> gem install should not install an additional platform, if the gem is already present

This is a tough one.  Doing a `gem install` will always install the gem, even if it's the same platform.  For example doing `gem install foo` on Linux will install the foo gem twice.  It doesn't care that foo was already installed.  I think this would be a large change.

> gem list should always display the platform (not only if there are more than 1)

I could get behind this.

> solution b:
> add an option to gem install that forces devkit build for specific platform so gem install will recognize that the platform is already present.

I think the "ruby" platform generally means that the gem **was not** precompiled for a particular platform.    Where "java" means the gem was precompiled for JRuby, "x64-mingw32" for windows, etc.  It seems possible to tag a gem with a platform on install, but since you actually installed the gem from source, that doesn't seem to make sense.

IMO, `gem install` is working as advertised.  When you did `gem install --platform=ruby`, you got what you asked for: the gem with the Ruby platform.  Since we implicitly default the platform on windows, the second `gem install` also fetched the platform it was supposed to.

Is this causing a bug?

**Comment by ABaumgaertner** [comment]
thanks for the infos ...

the initial issue, gems can only be compiled with devkit when using --platform=ruby
`gem install --platform=x64-mingw32` will download and install the gem with packaged binary and not compile the gem with devkit for this platform - changing this behavior doesn't make sense - in my example mysql2, there is some additonal code in the x64-mingw32 gem to determine the current ruby version and dynamically require the correct .so for it

the 2nd issue - ruby require does not support multiple platforms (which makes sense, since you would expect really only one) why would i have a gem with two platforms ruby and x64-mingw32 installed? ruby require prefers the ruby platform over the x64-mingw32. IMO - this should be the basis for a solution. see my test below (both platforms installed - require uses ruby)

> Since we implicitly default the platform on windows, the second gem install also fetched the platform it was supposed to.

this is is not what happens - `gem install mysql2` on windows does not default to mysql2-x64-mingw32 but will install mysql2 (platform=ruby)

suggested solution:
if platform ruby is installed, installation of additional platforms doesn't make sense (since ruby is ignoring them in require anyway) - throw at least a warning during installation
if other platform is present and ruby platform is installed, throw a warning that the existing platform will be ignored

some addtional info
the build for mysql2 --platform=ruby worked - running bundle install (e.g. redmine) will install also the mysql2-0.3.18-x64-mingw32.gem
I'll open issue for that with bundler.

for e.g. mysql2 - it leads to this problem - there is no .so for ruby 2.2 yet - see below
ruby seems to take the platform ruby first - the require tests works after both versions have been installed (ruby supercedes x64-mingw32). I've also tested this with ruby 2.1.5 (mysql2-0.3.18-x64-mingw32 has a working binary for ruby 2.1)

this installs
`gem install mysql2 -N --platform=x64-mingw32 -- "--with-mysql-dir=c:/apps/redmine_dev/mysql-5.6.23-winx64"`
this compiles
`gem install mysql2 -N --platform=ruby -- "--with-mysql-dir=c:/apps/redmine_dev/mysql-5.6.23-winx64"`

```
C:\apps\redmine_dev\bin>gem install mysql2
Fetching: mysql2-0.3.18-x64-mingw32.gem (100%)

======================================================================================================

 \ You've installed the binary version of mysql2.
  It was built using MySQL Connector/C version 6.1.5.
  It's recommended to use the exact same version to avoid potential issues.

  At the time of building this gem, the necessary DLL files were retrieved from:
  http://cdn.mysql.com/Downloads/Connector-C/mysql-connector-c-6.1.5-winx64.zip

 \ This gem *includes* vendor/libmysql.dll with redistribution notice in vendor/README.

======================================================================================================

Successfully installed mysql2-0.3.18-x64-mingw32
Parsing documentation for mysql2-0.3.18-x64-mingw32
Installing ri documentation for mysql2-0.3.18-x64-mingw32
Done installing documentation for mysql2 after 0 seconds
1 gem installed

C:\apps\redmine_dev\bin>more ..\test\mysql.rb
require 'mysql2'

C:\apps\redmine_dev\bin>ruby -v
ruby 2.2.2p86 (2015-03-03 revision 49825) [x64-mingw32]

C:\apps\redmine_dev\bin>ruby ..\test\mysql.rb
C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- mysql2/2.2/mysql2 (LoadError)
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/apps/redmine_dev/ruby/lib/ruby/gems/2.2.0/gems/mysql2-0.3.18-x64-mingw32/lib/mysql2/mysql2.rb:2:in `<top (required)>'
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
        from C:/apps/redmine_dev/ruby/lib/ruby/gems/2.2.0/gems/mysql2-0.3.18-x64-mingw32/lib/mysql2.rb:31:in `<top (required)>'
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
        from C:/apps/redmine_dev/ruby/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
        from ../test/mysql.rb:1:in `<main>'

C:\apps\redmine_dev\bin>gem install mysql2 -N --platform=ruby -- "--with-mysql-dir=c:/apps/redmine_dev/mysql-5.6.23-winx64"
Fetching: mysql2-0.3.18.gem (100%)
Temporarily enhancing PATH to include DevKit...
Building native extensions with: '--with-mysql-dir=c:/apps/redmine_dev/mysql-5.6.23-winx64'
This could take a while...
Successfully installed mysql2-0.3.18
1 gem installed

C:\apps\redmine_dev\bin>ruby ..\test\mysql.rb

C:\apps\redmine_dev\bin>gem list

*** LOCAL GEMS ***

bigdecimal (1.2.6)
bundle (0.0.1)
bundler (1.8.3)
ffi (1.9.6)
io-console (0.4.3)
json (1.8.1)
mini_portile (0.6.2)
mysql2 (0.3.18 ruby x64-mingw32)
psych (2.0.8)
puma (2.11.1)
rack (1.6.0)
rake (10.4.2)
rdoc (4.2.0)
rmagick (2.13.4)

C:\apps\redmine_dev\bin>
```

**Comment by tenderlove** [comment]
> this is is not what happens - gem install mysql2 on windows does not default to mysql2-x64-mingw32 but will install mysql2 (platform=ruby)

That's not [what your report on ruby-lang says](https://bugs.ruby-lang.org/issues/10919).  I will quote you below:

> here comes the acutal issue:
> rerun (also with other dependency managers e.g. bundle install) installs dupplicate gem for platform x64-mingw32
>
```
C:\apps\redmine_dev\bin>gem install mysql2
Fetching: mysql2-0.3.18-x64-mingw32.gem (100%)

======================================================================================================

 \ You've installed the binary version of mysql2.
  It was built using MySQL Connector/C version 6.1.5.
  It's recommended to use the exact same version to avoid potential issues.

  At the time of building this gem, the necessary DLL files were retrieved from:
  http://cdn.mysql.com/Downloads/Connector-C/mysql-connector-c-6.1.5-winx64.zip

 \ This gem *includes* vendor/libmysql.dll with redistribution notice in vendor/README.

======================================================================================================

Successfully installed mysql2-0.3.18-x64-mingw32
Parsing documentation for mysql2-0.3.18-x64-mingw32
Installing ri documentation for mysql2-0.3.18-x64-mingw32
Done installing documentation for mysql2 after 0 seconds
1 gem installed
```

`gem install mysql2` did exactly what you asked it to do.  You first installed the gem using the dev kit with the ruby platform, then you asked it to install `mysql2` with an implicit platform of `x64-mingw32`.

**Comment by ABaumgaertner** [comment]
sorry my mistake - you should not keep 2 shells with seperate ruby envs open
`gem install mysql2` on
ruby 2.1 installes mysql2 with platform ruby
ruby 2.2 installes mysql2 x64-mingw32

still seems uncessary on 2.2. to install x64-mingw32 additionally to existing ruby when require ignores x64-mingw32 anyway
