### ISSUE TITLE
show rdoc process verbosely with -V specified

### ISSUE THREAD

**Issue by zenspider** [rubygems/rubygems#118]
From: http://rubyforge.org/tracker/index.php?func=detail&aid=29049&group_id=126&atid=577

Has a patch attached to the original ticket.

When "gem install" is executed with -V option,
- unpack process of gem archive
- build process of C native codes
are shown verbosely. But rdoc process is always called with --quiet option so the process won't be shown verbosely,
which I think is inconsistent.

The patch is to show rdoc process verbosely when "gem install" is executed with -V option (verbose mode).
Please consider to apply this patch.

**Comment by djberg96** [comment]
@zenspider any chance this patch still exists elsewhere?

**Comment by zenspider** [comment]
Highly doubtful.

**Comment by copiousfreetime** [comment]
original patch is missing, closing
