### ISSUE TITLE
UTF-8 still getting error on Cygwin (under Windows)

### ISSUE THREAD

**Issue by orlleite** [rubygems/rubygems#1180]
I got it when I was doing my first command on gem after installed by 'ruby setup.rb install'

$ gem update --system --backtrace
ERROR:  While executing gem ... (ArgumentError)
    invalid byte sequence in UTF-8
        /usr/share/ruby/2.0.0/win32/registry.rb:173:in `tr'
        /usr/share/ruby/2.0.0/win32/registry.rb:173:in`initialize'
        /usr/share/ruby/2.0.0/win32/registry.rb:231:in `exception'
        /usr/share/ruby/2.0.0/win32/registry.rb:231:in`raise'
        /usr/share/ruby/2.0.0/win32/registry.rb:231:in `check'
        /usr/share/ruby/2.0.0/win32/registry.rb:284:in`QueryValue'
        /usr/share/ruby/2.0.0/win32/registry.rb:587:in `read'
        /usr/share/ruby/2.0.0/win32/registry.rb:637:in`read_s'
        /usr/share/ruby/2.0.0/win32/resolv.rb:72:in `block in get_info'
        /usr/share/ruby/2.0.0/win32/registry.rb:389:in`open'
        /usr/share/ruby/2.0.0/win32/registry.rb:496:in `open'
        /usr/share/ruby/2.0.0/win32/resolv.rb:62:in`get_info'
        /usr/share/ruby/2.0.0/win32/resolv.rb:20:in `get_resolv_info'
        /usr/share/ruby/2.0.0/resolv.rb:938:in`default_config_hash'
        /usr/share/ruby/2.0.0/resolv.rb:955:in `block in lazy_initialize'
        /usr/share/ruby/2.0.0/resolv.rb:948:in`synchronize'
        /usr/share/ruby/2.0.0/resolv.rb:948:in `lazy_initialize'
        /usr/share/ruby/2.0.0/resolv.rb:357:in`block in lazy_initialize'
        /usr/share/ruby/2.0.0/resolv.rb:355:in `synchronize'
        /usr/share/ruby/2.0.0/resolv.rb:355:in`lazy_initialize'
        /usr/share/ruby/2.0.0/resolv.rb:509:in `each_resource'
        /usr/share/ruby/2.0.0/resolv.rb:490:in`getresource'
        /usr/local/share/ruby/site_ruby/rubygems/remote_fetcher.rb:92:in `api_endpoint'
        /usr/local/share/ruby/site_ruby/rubygems/source.rb:46:in`api_uri'
        /usr/local/share/ruby/site_ruby/rubygems/source.rb:182:in `load_specs'
        /usr/local/share/ruby/site_ruby/rubygems/spec_fetcher.rb:262:in`tuples_for'
        /usr/local/share/ruby/site_ruby/rubygems/spec_fetcher.rb:228:in `block in available_specs'
        /usr/local/share/ruby/site_ruby/rubygems/source_list.rb:97:in`each'
        /usr/local/share/ruby/site_ruby/rubygems/source_list.rb:97:in `each_source'
        /usr/local/share/ruby/site_ruby/rubygems/spec_fetcher.rb:222:in`available_specs'
        /usr/local/share/ruby/site_ruby/rubygems/spec_fetcher.rb:102:in `search_for_dependency'
        /usr/local/share/ruby/site_ruby/rubygems/commands/update_command.rb:117:in`fetch_remote_gems'
        /usr/local/share/ruby/site_ruby/rubygems/commands/update_command.rb:139:in `highest_remote_version'
        /usr/local/share/ruby/site_ruby/rubygems/commands/update_command.rb:267:in`block in which_to_update'
        /usr/local/share/ruby/site_ruby/rubygems/commands/update_command.rb:263:in `each'
        /usr/local/share/ruby/site_ruby/rubygems/commands/update_command.rb:263:in`which_to_update'
        /usr/local/share/ruby/site_ruby/rubygems/commands/update_command.rb:189:in `rubygems_target_version'
        /usr/local/share/ruby/site_ruby/rubygems/commands/update_command.rb:235:in`update_rubygems'
        /usr/local/share/ruby/site_ruby/rubygems/commands/update_command.rb:88:in `execute'
        /usr/local/share/ruby/site_ruby/rubygems/command.rb:307:in`invoke_with_build_args'
        /usr/local/share/ruby/site_ruby/rubygems/command_manager.rb:168:in `process_args'
        /usr/local/share/ruby/site_ruby/rubygems/command_manager.rb:138:in`run'
        /usr/local/share/ruby/site_ruby/rubygems/gem_runner.rb:54:in `run'
        /usr/bin/gem:21:in`<main>'

I saw this (https://github.com/rubygems/rubygems/issues/863 closed topic), maybe related but I'm using the last version of it (2.4.6) and it persists.

**Comment by tenderlove** [comment]
Does this also happen on Ruby 2.2?

**Comment by developpeuse-web** [comment]
I have the same problem. Spend many times to search and try answers, but still impossible to make ruby gem work on cygwin under windows.

@tenderlove : this append on the ruby version available for cygwin, wich is 2.0.0. Can't find Ruby 2.2 for cygwin...

**Comment by developpeuse-web** [comment]
I've tried to install ruby 2.2 for window, but in this case Cygwin is unabble to use ruby, as explain here : http://stackoverflow.com/questions/3831131/rubygems-cygwin-posix-path-not-found-by-ruby-exe
From the discussions i've read about it, it seems that if you want to use Ruby with Cygwin on Windows, you musn't use the ruby installer, but just add the cygwin ruby lib.
Don't know what to do to be able to make ruby gem work fine with cygwin on windows...

**Comment by bronzdoc** [comment]
@orlleite is this still happening with the lastes ruby version?

**Comment by orlleite** [comment]
@bronzdoc I'm not able to test this anymore. I'm sorry, I have a vage memory about that, I think I was able to do in another what I were attempting to do at that time, and somehow I could get some gem working. I think this topic may should closed.

**Comment by bronzdoc** [comment]
Alright, thanks for the feedback @orlleite !
