### ISSUE TITLE
Install option --development ignores --prerelease option

### ISSUE THREAD

**Issue by olbat** [rubygems/rubygems#1182]
### Description
Rubygems installs the development dependencies of the stable version instead of the ones of the pre-release when installing with both the `--prerelease` and `--development` options.

### Example

**Context**
1. The gem `A v1.1.0` has the gem `B` in it's development dependencies
2. The gem `A v1.2.0.rc1` has the gem `B` and `C` in it's development dependencies

**Command**
`gem install --prerelease --development A`

**Expectations**
`A v1.2.0.rc1`, `B` and `C` should be installed,

**Reality**
`A v1.2.0.rc1`, `B` are installed

### Version
This has been tested with rubygems `v2.2.2` (Debian "jessie" current version).

**Comment by copiousfreetime** [comment]
I tested this locally, and this does not appear to be a bug anymore. At least from a locally installed gem. The prerelease gem when installed with --development installed its development dependencies.

If you can point out an existing gem in rubygems.org that demonstrates this behavior, please reopen.
