### ISSUE TITLE
gem pristine does not observe installer options

### ISSUE THREAD

**Issue by zenspider** [rubygems/rubygems#119]
From http://rubyforge.org/tracker/index.php?func=detail&aid=28661&group_id=126&atid=577 (and possibly other places too)

In `pristine_command.rb`, there are the following lines:

      # TODO use installer options
      installer = Gem::Installer.new gem, :wrappers => true, :force => true
      installer.install

Obviously it was intended that this code eventually propagate installer options, but it has never been done. Unfortunately rvm's gemset support uses `gem pristine --all`, which on JRuby will lose the `--env-shebang` default we require to allow using jruby's bash-based startup script in shebang likes for installed gem executables. This led to the following bug report: http://jira.codehaus.org/browse/JRUBY-5031

After a short exploration, I could not find the proper way to propagate installer options for pristine installs, so I ended up going with the following patch. RubyGems should be fixed to propagate installer options appropriately.

``` diff
diff --git a/lib/ruby/site_ruby/1.8/rubygems/commands/pristine_command.rb
b/lib/ruby/site_ruby/1.8/rubygems/commands/pristine_command.rb
index ef11129..61897cc 100644
--- a/lib/ruby/site_ruby/1.8/rubygems/commands/pristine_command.rb
+++ b/lib/ruby/site_ruby/1.8/rubygems/commands/pristine_command.rb
@@ -82,7 +82,11 @@ revert the gem.
       end
 
       # TODO use installer options
-      installer = Gem::Installer.new gem, :wrappers => true, :force => true
+      # Modified for JRUBY-5031, to propagate --env-shebang if set
+      installer = Gem::Installer.new gem,
+        :wrappers => true,
+        :force => true,
+        :env_shebang => !Gem::ConfigFile::PLATFORM_DEFAULTS['install'].to_s['--env-shebang'].nil?
       installer.install
 
       say "Restored #{spec.full_name}"
```

**Comment by duckinator** [comment]
This was made to propagate `env_shebang` in https://github.com/rubygems/rubygems/commit/de8afc406dfacc580c4c7645c8ea28bee25b800a and then to propagate `build_args` in https://github.com/rubygems/rubygems/commit/488c20cd2aa8ea4a304511121dd24e40c65adf82 &mdash; does that resolve this issue?

**Comment by copiousfreetime** [comment]
@duckinator Yes de8afc4 is logically the same as @zenspider's patch. So closing.
