### ISSUE TITLE
gem hazelcast-jars got Gem::RemoteFetcher::FetchError - bad response Not Found

### ISSUE THREAD

**Issue by wkchih** [rubygems/rubygems#1203]
Hi, I'm trying to install hazelcast-jars (gem install hazelcast-jars)
but I got 404 Not found error response,

> ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (http://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/hazelcast-jars-3.2.6-java.gemspec.rz)

Thanks a lot

**Comment by Overbryd** [comment]
I have the same problem with **hazelcast-client** and **hazelcast-jars**:

```
$ gem install hazelcast-client
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (http://aws-eu-cache01.rubygems.org/quick/Marshal.4.8/hazelcast-client-0.0.5-java.gemspec.rz)
```

```
$ gem install hazelcast-jars
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (https://aws-eu-cache01.rubygems.org/quick/Marshal.4.8/hazelcast-jars-3.2.6-java.gemspec.rz)
```

**Comment by Overbryd** [comment]
Tried updating using `gem update --system`, I am now on RubyGems 2.4.7 but the problem persists since days.

**Comment by copiousfreetime** [comment]
This is an with the hazelcast-client gem. The [platform on the hazelcast-client gemspecs](https://github.com/aemadrid/hazelcast-client/blob/master/hazelcast-client.gemspec#L9) is set to `jruby` instead of the correct `java`. I think this should be an issue with @aemadrid.
