### ISSUE TITLE
Be more verbose when installing dependencies from Gemfile

### ISSUE THREAD

**Issue by jirutka** [rubygems/rubygems#1212]
When I run `gem install --file Gemfile` on [gitlabhq](https://github.com/gitlabhq/gitlabhq) (a Rails-based application), it takes a very long time before I see _any_ output. To be honest, I’ve interrupted it after 2 minutes (still no output). I can see that it’s communicating with RubyGems API when I enable verbose mode (`-V`).

Dependencies resolution may take a long time, so it’s necessary to inform user what’s happening (by default, not just in verbose mode).

**Comment by bronzdoc** [comment]
You can set it to default in your .gemrc <code>verbose: true</code>
reference: http://guides.rubygems.org/command-reference/#gem-environment

**Comment by jirutka** [comment]
Sorry, but you’ve kinda missed the point of this issue…

**Comment by indirect** [comment]
@jirutka rubygems has since merged in the Molinillo resolver, and will in the future install Gemfiles via Bundler. There will be a lot of verbose output in the future once that's done. In the meantime, please use Bundler to install Gemfiles instead.
