### ISSUE TITLE
get rails working without bundler

### ISSUE THREAD

**Issue by mpapis** [rubygems/rubygems#1213]
1. get new app

    ```bash
    export RUBYGEMS_GEMDEPS=-
    rails new my_app --skip-bundle
    cd my_app
    gem i -g
    gem uninstall bundler -ax # pres "y" to remove it
    ```

2. comment out `group`s and `spring` in `Gemfile`
3. clean empty `config/boot.rb`
4. in `config/application.rb` replace `Bundler.require(*Rails.groups)` with:

    ```ruby
    require 'rails'
    require 'sqlite3'
    require 'sass-rails'
    require 'uglifier'
    require 'coffee-rails'
    require 'jquery-rails'
    require 'turbolinks'
    require 'jbuilder'
    require 'sdoc'
    require 'byebug'
    require 'web-console'
    ```

now I have a problem with step `4` - this is manual work is there a way to at least get list of gems listed in `Gemfile` - including information in `require` if any given?

**Comment by indirect** [comment]
What part of "RubyGems does not support and has no plans to support Bundler.require" was not clear?

**Comment by mpapis** [comment]
@drbrain I do nto ask for require but for the the parsed information, I can call require myself - can you reopen it?

**Comment by mpapis** [comment]
if rubygems wants to support `Gemfile` providing the information in `require` is essential as this is vital metadata from `Gemfile`

**Comment by drbrain** [comment]
I'll reopen this for exposing the `require` information somewhere accessible to a plugin author, at minimum, so an enterprising person can move this forward.
