### ISSUE TITLE
Activejob: Error 302

### ISSUE THREAD

**Issue by matthewjamesr** [rubygems/rubygems#1217]
Installing rails with gem is throwing a 302: Temp Moved when trying to grab this resource.
sudo gem install activejob

```
ERROR:  Could not find a valid gem 'activejob' (>= 0) in any repository
ERROR:  Possible alternatives: activejob
```

From gem install rails:

```
GET http://rubygems.org/quick/Marshal.4.8/actionmailer-4.2.1.gemspec.rz
302 Moved Temporarily
```

**Comment by drbrain** [comment]
`302 Moved Temporarily` is not an error, it's a redirect that RubyGems handles normally.

I'm able to install both activejob and actionmailer:

```
$ gem install -i ~/tmp/gems actionmailer --ignore-dependencies
Successfully installed actionmailer-4.2.1
Parsing documentation for actionmailer-4.2.1
Done installing documentation for actionmailer after 0 seconds
1 gem installed
$ gem install -i ~/tmp/gems activejob --ignore-dependencies
Successfully installed activejob-4.2.1
Parsing documentation for activejob-4.2.1
Done installing documentation for activejob after 0 seconds
1 gem installed
$ gem --version
2.4.5
```

Can you provide full output including RubyGems version?

**Comment by matthewjamesr** [comment]
Rubygems v: 2.4.6

$ gem install -i ~/tmp/gems actionmailer --ignore-dependencies
Fetching: actionmailer-4.2.1.gem (100%)
Successfully installed actionmailer-4.2.1
1 gem installed

$ gem install -i ~/tmp/gems activejob --ignore-dependencies
ERROR:  While executing gem ... (TypeError)
    no implicit conversion of nil into String


$ gem install rails
Fetching: thread_safe-0.3.5.gem (100%)
Successfully installed thread_safe-0.3.5
Fetching: minitest-5.5.1.gem (100%)
Successfully installed minitest-5.5.1
--terminated

$gem install rails -V
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=rails
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=actionmailer,actionpack,actionview,activejob,activemodel,activerecord,activesupport,bundler,railties,sprockets-rails
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=arel,builder,erubis,globalid,i18n,json,mail,minitest,rack,rack-test,rails-dom-testing,rails-html-sanitizer,rake,sprockets,thor,thread_safe,tzinfo
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=hike,loofah,mime-types,multi_json,nokogiri,rails-deprecated_sanitizer,tilt
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=mini_portile
200 OK
Downloading gem tzinfo-1.2.2.gem
GET https://api.rubygems.org/gems/tzinfo-1.2.2.gem
302 Moved Temporarily
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    Errno::ETIMEDOUT: Connection timed out - connect(2) for "bb-m.rubygems.org" port 443 (https://api.rubygems.org/gems/tzinfo-1.2.2.gem)

**Comment by drbrain** [comment]
You have a network issue contacting https://bb-m.rubygems.org.  It is up for me:

```
$ curl https://bb-m.rubygems.org/gems/tzinfo-1.2.2.gem > /dev/null
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  144k  100  144k    0     0   144k      0 --:--:-- --:--:-- --:--:--  144k
```

This isn't a bug in RubyGems.  Please check your firewalls or consult your ISP or network provider to diagnose.
