### ISSUE TITLE
xcodeproj 0.23.1 fails to install

### ISSUE THREAD

**Issue by plackemacher** [rubygems/rubygems#1218]
I'm currently having an issue where xcodeproj version 0.23.1 will not install even though it is mentioned as existing on the Rubygems page (https://rubygems.org/gems/xcodeproj/). Currently, the latest version that I can install is 0.22.0. I have tried adding the `--pre` argument to the install command it that doesn't help.

Steps to replicate:
```sh
gem install xcodeproj -v 0.23.1
```

**Comment by plackemacher** [comment]
This may not be an actual bug with rubygems itself but the system so I'm closing this and will refer others to a help discussion: http://help.rubygems.org/discussions/problems/20649-published-gem-version-not-found-cannot-install-0231-of-xcodeproj

**Comment by drbrain** [comment]
Thanks!
