### ISSUE TITLE
Gem install Travis fails on windows

### ISSUE THREAD

**Issue by sccolbert** [rubygems/rubygems#1219]
```
C:\Users\sccolbert>gem install travis
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (https://bb-m.rubygems.org/quick/Marshal.4.8/pry-
0.9.12.6-x86-mingw32.gemspec.rz)
```

Seems related to #1120

**Comment by tenderlove** [comment]
Ya, I think this is a dup of #1120

**Comment by cablegunmaster** [comment]
I Have a similar problem, 
ruby -v 
    ruby 2.2.3p173 (2015-08-18 revision 51636) [i386-mingw32]
using: "Gem install travis"
![geminstall](https://cloud.githubusercontent.com/assets/8159246/10417342/9974df8c-7038-11e5-9e4d-537f95ec338e.png)

**Comment by djberg96** [comment]
@cablegunmaster I cannot duplicate. What is the output of gem env?

**Comment by cablegunmaster** [comment]
Basically I just installed the windows environment setup on: Nothing more nothing less.
Using Ruby 2.2.3 installer on http://rubyinstaller.org/downloads/ and it created the  404 error after using the 'gem install travis' command.
'gem update --system 2.4.4' 
Seemed to resolve the issue.

**Comment by djberg96** [comment]
Nevermind, I see the same thing. Yes, it's a dup of #1120.

**Comment by duckinator** [comment]
Cannot reproduce on Windows 8.1. Is there something I'm missing to reproduce this, or is it resolved with 2.5.1 and/or is it specific to Windows 10?

```
C:\Users\Marie>ruby -v
ruby 2.2.3p173 (2015-08-18 revision 51636) [i386-mingw32]

C:\Users\Marie>gem -v
2.5.1

C:\Users\Marie>gem install travis
Fetching: travis-1.8.2.gem (100%)
Successfully installed travis-1.8.2
Parsing documentation for travis-1.8.2
Installing ri documentation for travis-1.8.2
Done installing documentation for travis after 3 seconds
1 gem installed

```

**Comment by duckinator** [comment]
Just realized this issue was said to be a duplicate of an issue which was closed after the last comment (besides mine) on this issue. Any reason to not consider this resolved?

**Comment by sccolbert** [comment]
Will be back on my Windows box in a couple days to check. If it works, I'll close the issue.

**Comment by duckinator** [comment]
Thanks!

**Comment by duckinator** [comment]
@sccolbert did you ever get around to checking this?

**Comment by sccolbert** [comment]
@duckinator thanks for the ping! Seems to be fixed.
