### ISSUE TITLE
adding more IO-like methods to Gem::Package::TarReader::Entry

### ISSUE THREAD

**Issue by skippy** [rubygems/rubygems#1225]
I've found `Gem::Package::TarReader` to be incredibly useful as a general-purpose utility for handling tar files programatically.  Having `Gem::Package::TarReader::Entry` smell more like an IO object would be helpful.  If adding a method or two to bring it more inline, such as
```ruby
  def gets(sep, limit = nil)
    check_closed
    return nil if @read >= @header.size

    ret = @io.gets(sep, limit)

    @read += ret.size

    ret
  end
```

I would be more than happy to submit a PR.

**Comment by drbrain** [comment]
Please submit a PR with tests, I don't see a reason offhand to reject it.
