### ISSUE TITLE
very very slow install from rubygems.global.ssl.fastly.net

### ISSUE THREAD

**Issue by jrochkind** [rubygems/rubygems#1226]
I am having very very slow gem installs.  By using `gem --verbose install` and other debugging tools, I've narrowed it down to this as an example bottleneck:

~~~
time curl -I https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/tzinfo-1.2.2.gemspec.rz

HTTP/1.1 200 OK
Date: Tue, 14 Apr 2015 21:03:39 GMT
Server: AmazonS3
x-amz-version-id: 8zZn.8wTqwc8MqWeowgupLLLPjAEmVfj
Last-Modified: Fri, 08 Aug 2014 18:00:22 GMT
ETag: "847da32582dc8b0c548c6a86465fc747"
Via: 1.1 5a891e2d49894a0530a20c0ea96ad494.cloudfront.net (CloudFront)
X-Amz-Cf-Id: h6quEE-KK8TwGELfUbn0nguby0fSVvcupwbszx4jZtDP_G8V0SiHWA==
Content-Length: 399
Accept-Ranges: bytes
Via: 1.1 varnish
Age: 0
X-Served-By: cache-iad2140-IAD
X-Cache: Hit from cloudfront, MISS
X-Cache-Hits: 0
X-Log-Message: for=request method=HEAD path=/quick/Marshal.4.8/tzinfo-1.2.2.gemspec.rz fwd="128.220.159.5" status=200 bytes=399 cache=Hit from cloudfront, MISS cache_hits=0 timing="(null)"


real	1m16.098s
user	0m0.013s
sys	0m0.009s
~~~

1m16s to fetch that URL. 

Is something wrong?  If you think it's my local network, do you have anything to suggest I could do to have evidence to convince the enterprise network engineers that it is the local network somehow? They are going to say, well, it's probably the remote server.

**Comment by jrochkind** [comment]
Also sometimes takes so long that it times out, same fastly.net host:

     Gem::RemoteFetcher::FetchError: Errno::ETIMEDOUT: Connection timed out - connect(2) for "rubygems.global.ssl.fastly.net" port 443 (https://rubygems.org/gems/mini_portile-0.6.2.gem)

**Comment by indirect** [comment]
@jrochkind can you create a gist with the entire page from http://www.fastly-debug.com and include it here? and a traceroute to that host as well, if you can?

**Comment by jrochkind** [comment]
Sure. How do I create a gist of an HTML page?  

The problem of course comes and goes, although it comes more often than it goes. 

traceroute to rubygems.global.ssl.fastly.net is working now, it's gonna take a while, and may not be able to complete, here's where it is so far:

~~~
traceroute to rubygems.global.ssl.fastly.net (199.27.76.249), 30 hops max, 40 byte packets
 1  128.220.205.1 (128.220.205.1)  4.737 ms  4.670 ms  4.642 ms
 2  10.160.255.149 (10.160.255.149)  0.540 ms  0.565 ms  0.520 ms
 3  10.200.255.57 (10.200.255.57)  1.216 ms  1.179 ms  1.128 ms
 4  10.200.255.26 (10.200.255.26)  1.051 ms  0.963 ms  0.952 ms
 5  * * *
 6  * * *
 7  * * *
 8  * * *
 9  * * *
10  * * *
11  * * *
12  * * *
13  * * *
~~~

**Comment by jrochkind** [comment]
oops, that's not too useful, it's all local IP's, hm.

**Comment by jrochkind** [comment]
It eventually completed with 20 more lines of * * *, not too useful. 

~~~
$ host rubygems.global.ssl.fastly.net
rubygems.global.ssl.fastly.net is an alias for global-ssl.fastly.net.
global-ssl.fastly.net is an alias for fallback.global-ssl.fastly.net.
fallback.global-ssl.fastly.net has address 199.27.76.249
fallback.global-ssl.fastly.net has address 23.235.46.249
~~~

**Comment by jrochkind** [comment]
I don't know how to create a gist of the HTML, but here's the copy and paste text of http://www.fastly-debug.com 

https://gist.github.com/jrochkind/a73eb6a8b6289e59d64d

**Comment by jrochkind** [comment]
tracerouting the individual IPs from the `host` lookup, on the 23.235.46.249  one I get a little bit further before it goes all `* * *`. 

~~~
$ traceroute 23.235.46.249
traceroute to 23.235.46.249 (23.235.46.249), 30 hops max, 40 byte packets
 1  128.220.205.1 (128.220.205.1)  1.058 ms  0.931 ms  0.908 ms
 2  10.160.255.149 (10.160.255.149)  0.863 ms  0.784 ms  0.734 ms
 3  10.200.255.57 (10.200.255.57)  1.275 ms  1.014 ms  0.986 ms
 4  10.200.255.30 (10.200.255.30)  1.120 ms  1.083 ms  1.590 ms
 5  162.129.255.250 (162.129.255.250)  2.292 ms  2.250 ms  2.197 ms
 6  162.129.253.58 (162.129.253.58)  11.767 ms  8.489 ms  2.065 ms
 7  4.59.246.1 (4.59.246.1)  3.527 ms  3.266 ms  3.268 ms
 8  ae-4-90.edge3.Washington1.Level3.net (4.69.149.209)  3.768 ms  3.751 ms ae-3-80.edge3.Washington1.Level3.net (4.69.149.145)  4.099 ms^[[A
 9  * * *
10  * * *
11  * * *
12  * * *
13  * * *
14  * * *
15  * * *
16  * * *
17  * * *
18  * * *
19  * * *
20  * * *
~~~

On `199.27.76.249`, it never gets out of the local network:

~~~
$ traceroute 199.27.76.249
traceroute to 199.27.76.249 (199.27.76.249), 30 hops max, 40 byte packets
 1  128.220.205.1 (128.220.205.1)  0.852 ms  0.775 ms  0.586 ms
 2  10.160.255.149 (10.160.255.149)  0.654 ms  0.593 ms  0.546 ms
 3  10.200.255.57 (10.200.255.57)  1.142 ms  1.126 ms  1.053 ms
 4  10.200.255.26 (10.200.255.26)  0.948 ms  0.910 ms  0.866 ms
 5  * * *
 6  * * *
~~~

**Comment by jrochkind** [comment]
And one last traceroute, of the "Server IP" mentioned in the fastly-debug output, which is a different IP than rubygems.global.ssl.fastly.net resolves to:

~~~
$ traceroute 199.27.76.64
traceroute to 199.27.76.64 (199.27.76.64), 30 hops max, 40 byte packets
 1  128.220.205.1 (128.220.205.1)  0.656 ms  0.570 ms  0.580 ms
 2  10.160.255.149 (10.160.255.149)  0.501 ms  0.445 ms  0.436 ms
 3  10.200.255.57 (10.200.255.57)  0.750 ms  0.708 ms  0.745 ms
 4  10.200.255.30 (10.200.255.30)  1.183 ms  1.059 ms  0.870 ms
 5  162.129.255.250 (162.129.255.250)  3.011 ms  2.792 ms  2.729 ms
 6  162.129.253.54 (162.129.253.54)  1.956 ms  1.977 ms  1.872 ms
 7  te7-4.ccr01.bwi01.atlas.cogentco.com (38.104.12.5)  5.088 ms  5.033 ms  4.981 ms
 8  te0-0-1-2.rcr21.phl01.atlas.cogentco.com (154.54.83.221)  10.101 ms te0-0-0-2.rcr22.phl01.atlas.cogentco.com (154.54.2.174)  9.294 ms  9.251 ms
 9  be2364.ccr41.jfk02.atlas.cogentco.com (154.54.3.141)  10.019 ms  10.122 ms  10.074 ms
10  be2061.ccr21.jfk05.atlas.cogentco.com (154.54.3.70)  9.816 ms  9.176 ms be2060.ccr21.jfk05.atlas.cogentco.com (154.54.31.10)  10.045 ms
11  * * *
12  * * *
13  * * *
~~~

**Comment by indirect** [comment]
I've opened a ticket with Fastly support, and I'll let you know what I find out. Thanks!

**Comment by jrochkind** [comment]
Thanks @indirect! Have you learned anything?

I am still experiencing very slow response times for rubygems.global.ssl.fastly.net.  Does not happen with every request, but seems to happen with the majority of them (may depend on exactly what load balanced server I end up with?)

It's making it very hard to get any work done, without being able to install gems reliably (generally get a timeout on bundle install eventually, after waiting quite a while for it to slowly go through what manages to come in under the timeout)

**Comment by jrochkind** [comment]
FWIW if anyone else runs into this, I discovered redhat runs a rubygems mirror at `http://mirror.ops.rhcloud.com/mirror/ruby/`.  

If I change my Gemfile `source` thusly, I at least can do a `bundle install` again.  Sadly, http not https, and of course you have to trust rhcloud to deliver you unaltered source. But at least I can start working again on my dev machine, even though I still don't want to do production deploys like that.

**Comment by indirect** [comment]
According to Fastly support, it looks like an issue with your local network. Here's what they said:

> We think this may be an issue with the John's Hopkins network -- the end user's debug page indicates they're downloading from within the university. Can you confirm with the user if this reproducible outside of the university network?

**Comment by jrochkind** [comment]
Yes, I am within the university. 

My problem is if I report this to my university network IT, they are going to say it looks to them like it's a problem with the remote host. 

Do they have any reason to believe it's a problem with my local network, other than the fact that I am on a campus network? If they had anything at all, it would be useful to include with my ticket to local IT. Otherwise, they are going to do the same thing that fastly did, say "We think this may be an issue with the remote host, as there are no problems with any other hosts but this one" (which is the case). 

Thanks!

**Comment by jrochkind** [comment]
I am not an expert at interpreting traceroute, but several of my traceroutes got outside the campus network, to level3.net or cogentco.com, before winding up all "* * *".  To me, not being an expert at traceroute, that seems to suggest the problem might not be my local network? But I am definitely no networking expert. Which is why it's hard to be trapped between two ends both blaming the other.

**Comment by evanphx** [comment]
They are very likely using a transparent HTTP proxy, which is why you don't see it in the traceroute.

**Comment by indirect** [comment]
I am not a network admin, but I think the traceroute that never made it past local IPs makes it seem like your traffic is being stopped before it leaves the John's Hopkins network. The phrase "downloading within the university" makes me suspect that your downloads are coming from an internal server rather than an external one hosted by fastly.

It's entirely possible that only the fastly host is problematic, but that doesn't mean it's fastly's problem--as far as thy can tell, they are delivering content at full speed to the John's Hopkins network.

**Comment by indirect** [comment]
A deciding factor would be trying the same connection from somewhere geographically close but not on the university network--if things are full speed there, then the problem is likely only solvable by university IT.

**Comment by jrochkind** [comment]
Okay, thanks. I have reported it to Johns Hopkins networking IT. I fully expect they're going to say they don't see a problem with any host but fastly, so it must be fastly's fault, and as far as local IT can tell there is no problem with their network.  

Perhaps it's time to find a new job. Or if you have any consultants you can recommend that we can hire to diagnose this and verify where the problem really is in a way that someone has to accept instead of blaming the other side. Just kidding. 

Please note that of the traceroutes I did to several fastly-associated IP's, two out of three of them DID get outside the local network, to level3.net and cogentco.com respectively, before losing the trace. Only one of the three lost the trace inside the local network.

**Comment by indirect** [comment]
@jrochkind while I may not be a network admin, I have a lot of experience being the person in the middle during network issues, and solving them usually requires getting both sides involved. I'm happy to keep debugging, but we definitely can't solve it without input from your IT department, since everything we can see from out here looks good.

**Comment by jrochkind** [comment]
Okay, thank you for your help! If I hear anything from IT, I will let you know unless you tell me you don't want to hear about it anymore! thanks!

**Comment by jrochkind** [comment]
You were of course right, local IT has eventually acknowledged that: "The 2 IP addresses associated with that site are being blocked by one of our threat reduction tools."

I am in the process of getting them to unblock the IP's.  What I'm worried about is that those two IP's just happen to be the ones fastly/cloudfront is currently using and can change at any time -- to more IP's that their mysterious 'thread reduction system' will block again. That's of course our problem on our end, but if you could confirm this is the case, and those IP's can change at any time, it might help me in my negotiations with IT. 

I've pretty much been unable to do ruby development, or deploy any of our ruby apps, all week. That's an issue for my local IT not you, but it does make one think about how nice it would be to have a network of rubygems mirrors.

**Comment by indirect** [comment]
Unfortunately, if your IT department views CDNs as a threat, you're unlikely to ever be able to download gems easily. :/





Can you set the fastly host to an IP that isn't being blocked in your /etc/hosts file?





Can you set your gemfile source to one of the other rubygems mirrors around the world?




Can you package the gems you need while you're on another network and then develop without needing to download gems?

**Comment by jrochkind** [comment]
Yeah, some of those are ideas I've been investigating in the days I've been unable to get any work done, thanks. 

Is there any official list of rubygems mirrors? I tried finding some, most I found googling were no longer available. I found a couple that were available, but they generally do not include pre-release gems, and/or sync daily at most. 

Setting fastly host to a different IP is an interesting idea -- is there any way I would get a list of different IP's that would also respond to  rubygems.global.ssl.fastly.net , even if more geographically remote? 

I don't really have another network to work on to package gems, and then there's the issue of C-compiled gems with platform dependencies.  It's of course not just a problem for development, but for deployment, since the methods of deployment we are using (which I think are quite standard) do a `bundle install` on the destination machine. 

Anyway, yeah, we're going to have to let IT networking know that their 'threat reduction' measures are making it impossible for us to work.  We have a super fast internet campus connection they've spent millions on -- which they randomly block IP's from, it's ridiculous.

**Comment by aspires** [comment]
Hey @jrochkind! I'm with Fastly. Could you shoot me an email at austin@fastly.com? We may be able to help with the IT problems you're running into.

**Comment by jrochkind** [comment]
Okay, I _thought_ I got IT networking to fix it. 

I am now getting:

$ gem install bundler
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://api.rubygems.org/quick/Marshal.4.8/bundler-1.9.4.gemspec.rz)

Can anyone tell me if it's my end again? I will report it locally too.

**Comment by jrochkind** [comment]
Okay, it's working again. Who knows.

**Comment by firedev** [comment]
Now I am having this issue: 
```
$ gem install bundler
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    Errno::ETIMEDOUT: Connection timed out - connect(2) for "rubygems.global.ssl.fastly.net" port 443 (https://api.rubygems.org/quick/Marshal.4.8/bundler-1.10.3.gemspec.rz)
```
```
$ ping fastly-debug.com
PING fastly-debug.com (104.156.81.64) 56(84) bytes of data.
64 bytes from 104.156.81.64: icmp_req=1 ttl=55 time=44.6 ms
64 bytes from 104.156.81.64: icmp_req=2 ttl=55 time=43.9 ms
64 bytes from 104.156.81.64: icmp_req=3 ttl=55 time=44.3 ms
^C64 bytes from 104.156.81.64: icmp_req=4 ttl=55 time=44.0 ms

--- fastly-debug.com ping statistics ---
4 packets transmitted, 4 received, 0% packet loss, time 15370ms
rtt min/avg/max/mdev = 43.940/44.238/44.666/0.287 ms
```
15 seconds?

Can't even open www.fastly-debug.com
