### ISSUE TITLE
gem install with security protocol TLS 1.2

### ISSUE THREAD

**Issue by lmayorga1980** [rubygems/rubygems#1227]
SSLv3 has been blocked at the network level. Is there a way to use TLS 1.2 connections to rubygems.org? It seems that **curl** already supports this in linux and OSX. 

I don't want to use the **http** sources instead of a secured connection.

**Comment by drbrain** [comment]
I thought OpenSSL no longer made outbound SSLv3 connections either.  What problem are you having?  Can you show error output, rubygems version, ruby version, and the version of openssl ruby is linked against?

```
$ ruby -ropenssl -ve 'puts Gem::VERSION, OpenSSL::OPENSSL_VERSION'
ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
2.4.5
OpenSSL 1.0.2a 19 Mar 2015
```

**Comment by lmayorga1980** [comment]
```
$ ruby -ropenssl -ve 'puts Gem::VERSION, OpenSSL::OPENSSL_VERSION'
ruby 2.2.2p95 (2015-04-13 revision 50295) [i386-mingw32]
2.4.5
OpenSSL 1.0.1l 15 Jan 2015
```

**Comment by drbrain** [comment]
What error are you seeing?

**Comment by lmayorga1980** [comment]
Wells since SSLv3 is blocked at the network level i am not able to install any gems from **https://rubygems.org**. But I could see that Chrome, Firefox are using TLS 1.2 to establish the connection to secure sites. 

Now it seems that the client connection started from **gem install**  uses SSLv3.

**Comment by tenderlove** [comment]
@lmayorga1980 what is the exact error you're seeing?  Is it similar to [this](https://github.com/rubygems/rubygems/issues/1087)?

**Comment by lmayorga1980** [comment]
Yes. This is the same error but i must say that if i disconnect myself from my corporate network then everything works perfectly. So I guess SSLv3 is blocked but TLS1.2 is supported

**Comment by copiousfreetime** [comment]
Closing for now as I think this is not an issue anymore. Please reopen if that is not the case.

**Comment by dmore** [comment]
This is still an issue.
