### ISSUE TITLE
`gem search --exact`?

### ISSUE THREAD

**Issue by chancancode** [rubygems/rubygems#1229]
I find myself going to rubygems.org a lot just to check the available versions for a given gem (to check if I am on the latest patch version, to find the last patch version of the previous minor release, etc), so I was wondering if I can do this from the command line.

Seems like the command I need to run is `gem search -a [--prerelease] \^rails\$`. Would it make sense to add an option to treat the last argument as a string (i.e. exact matches) instead of a regexp? Perhaps `gem search -a --exact rails`?

**Comment by chancancode** [comment]
(I suppose this would apply for all descendants of `QueryCommand`)

**Comment by tenderlove** [comment]
@chancancode I think adding that is a good stop gap.  Though IMO if you do `gem search rails` it should be an exact match.

Another option is that `gem list` takes a string and you can to `gem list STRING -r`, but it doesn't show all the versions and seems to treat that string as a regexp when you use -r.  Maybe we could fix that, and also add an option to show all versions.

**Comment by indirect** [comment]
I usually use `gem list -r '^rails$'` (with maybe a `--pre`), which shows only versions of the Rails gem. It would be really nice to have `gem list` be exact, while `gem search` did substring matching.

**Comment by tenderlove** [comment]
The help for `gem list` clearly says it takes a string and not a regexp:

```
[aaron@TC rubygems (master)]$ gem help list
Usage: gem list [STRING ...] [options]
```

No idea why it's doing matching.  I think we could treat that as a bug.

**Comment by indirect** [comment]
Considering that it's been doing matching for the last 10 years, I would suggest that it warrants a major release to change that. Many, many, many scripts that interact with `gem` programmatically know that it is required to use a regex to match a single gem. They will all break in a change to straight strings. :/

**Comment by tenderlove** [comment]
Sure, but we can treat strings like `^rails$` as a regexp, and strings like `rails` as just a string.  `^$` clearly can't be part of a gem name.  The question is if "many many many scripts" expect the bare string to do regexp matching.

**Comment by indirect** [comment]
How do we distinguish between gems with punctuation in their names and strings that are regexps? I don’t think many scripts expect a “bare” string, but I have no idea how to tell if a string is bare or not.

**Comment by chancancode** [comment]
See also https://github.com/rubygems/rubygems/pull/1228 and #905.

**Comment by tenderlove** [comment]
> How do we distinguish between gems with punctuation in their names and strings that are regexps?

The only non-word character that has special meaning outside of a character class that Rubygems.org accepts [is dot](https://github.com/rubygems/rubygems.org/blob/e448169b7025d1bf369fed17f685a292ab99a403/lib/patterns.rb#L4).  IOW, if the string matches `^[A-Za-z_-]*$`, then the user is definitely not using a regular expression.

**Comment by tenderlove** [comment]
@chancancode can you move forward with adding the extra flag?  I'd rather do the flag than try to deal with backwards compatibility issues around the name.  I agree with André that `list` should do exact matching and `search` should do regexp matching, but we definitely can't change the default in a non-major release.

**Comment by chancancode** [comment]
I am hopping on a plane in the next few minutes, so I probably can! :smile:

**Comment by andhapp** [comment]
@chancancode Hey, just had the same issue myself. Searched for 'pg' gem and it does a regex match and returns a huge list of gems. 

If you need a hand with implementation, please let us know, as I would love to see this merged.

**Comment by pedz** [comment]
Oh, this is curious.  "gem help list" as tenderlove says has "Usage: gem list [STRING ...] [options]" at the top but then further down it says:
  Arguments:
    REGEXP        regexp to look for in gem name

  Summary:
    Display local gems whose name matches REGEXP

Perhaps the fix is to just change STRING to REGEXP at the top of the help.

**Comment by andhapp** [comment]
@chancancode Hey, were you able to find time for this?

**Comment by Zearin** [comment]
Just arrived at this page after looking for a way to restrict searches to exact matches.  

I’m either for adding an option like `--exact` or `--literal` to specify this behavior, OR treating the input as a RegEx if it contains characters that are clearly illegal in gem names.  (Perhaps if the search term were `/«REGEX»/`, with the slashes being the indicator to treat it as RegEx?)

**Comment by bronzdoc** [comment]
This should be closed =)

**Comment by andhapp** [comment]
@bronzdoc Is there an alternative approach to this? If not, why have you suggested to close it?

**Comment by andhapp** [comment]
@bronzdoc: Please enlighten. Thanks.

**Comment by drbrain** [comment]
@andhapp see #1344 (also linked 2 updates above this issue being closed.)

**Comment by andhapp** [comment]
Thanks @drbrain
