### ISSUE TITLE
Version upload dates wrong

### ISSUE THREAD

**Issue by mcandre** [rubygems/rubygems#1232]
I uploaded new versions of several of my rubygems today, 21 April 2015, such as [rb-swatch](https://rubygems.org/gems/rb-swatch). However, RubyGems claims the upload dates of the new versions are six months or more in the past for some reason.

**Comment by tenderlove** [comment]
Rubygems or Rubygems.org?

**Comment by mcandre** [comment]
rubygems.org, the front-end pages describing my gems.

**Comment by drbrain** [comment]
Don't set the date in your Gemspec, let RubyGems set it for you: https://github.com/mcandre/rb-swatch/blob/master/swatch.gemspec#L10
