### ISSUE TITLE
Require 'digest/sha1' fails

### ISSUE THREAD

**Issue by rye** [rubygems/rubygems#1242]
I opened this issue over on bundler/bundler#3615, but I think it must be a RubyGems issue.

I have Ruby 2.2.2 installed (via RVM, I was trying from source before and got the same issue), but when I try to load `digest/sha1` (for example, whenever I run `bundle install`, this is done internally), I get the following error:

```
LoadError: /home/kristofer/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/x86_64-linux/digest/sha1.so: undefined symbol: rb_Digest_SHA1_Init - /home/kristofer/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/x86_64-linux/digest/sha1.so
	from /home/kristofer/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /home/kristofer/.rvm/rubies/ruby-2.2.2/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
```

But, the file that it's reading, `/home/kristofer/.rvm/rubies/ruby-2.2.2/lib/ruby/2.2.0/x86_64-linux/digest/sha1.so`, contains the rb_Digest_SHA1_Init symbol&mdash;I just checked with `readelf -a`.

Any suggestions?

**Comment by rye** [comment]
It is very important to note that I *do have* OpenSSL installed and the latest version, and I've recompiled and reinstalled 73 times now, with no change in behavior no matter what I do differently.

**Comment by tenderlove** [comment]
Do you get the same error if you do `ruby --disable-gems -rdigest/sha1 -e' '`?

**Comment by copiousfreetime** [comment]
I'm unable to dupclicate this, closing. Please reopen if it can be reproduce.
