### ISSUE TITLE
An interrupted gem update is registered as a succeeded update

### ISSUE THREAD

**Issue by breun** [rubygems/rubygems#1243]
I sometimes encounter gem updates that cause RubyGems to hang on my OS X 10.10.3 machines. Lately I have been having this problem with the documentation installation tasks of the `commander` gem. When I interrupt the update with `ctrl+c` I get an "ERROR: Interrupted" message, but when I run the update again there are no longer any updates. This makes me believe updates are not installed in a transaction and that installations can be corrupted this way.

Is this expected behavior?

```
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.10.3
BuildVersion:	14D136
$ gem --version
2.1.10
$ sudo gem update
Updating installed gems
Updating commander
Fetching: commander-4.3.4.gem (100%)
Successfully installed commander-4.3.4
Parsing documentation for commander-4.3.4
Installing ri documentation for commander-4.3.4
Installing darkfish documentation for commander-4.3.4
^CERROR:  Interrupted
$ sudo gem update
Updating installed gems
Nothing to update
```

**Comment by tenderlove** [comment]
Ya, it is.  The documentation tasks are done in an after install hook.  By the time they get around to running, the gem installation transaction is complete.  I think there is a different command to rebuild the docs for a particular gem.

/cc @drbrain

**Comment by drbrain** [comment]
When you get to "Successfully installed" then the gem is usable by `require` and is considered installed.

As @tenderlove noted, installing documentation is a post-install step and isn't necessary for `require` to work.

This is intended behavior.
