### ISSUE TITLE
Please consider simplifying the API for obtaining dependencies of a given gem-based project.

### ISSUE THREAD

**Issue by shevegen** [rubygems/rubygems#1246]
Hi guys,

I can obtain dependencies of a ruby gem by issuing something like:

```
GEM_CMD = Gem::Commands::DependencyCommand.new
name_of_the_gem = 'cookbook'
dependency = GEM_CMD.gem_dependency(name_of_the_gem, nil, nil)
GEM_CMD.fetch_remote_specs(dependency).uniq.sort
```

And then iterating over that, and invoking the method
.dependencies() on it.

The above is rather unwieldy and hard to remember.

Could it be simplified perhaps?

I'd love to have an API like:

  Gem::Commands::GemDependenciesOf.new('rails')

And the above could give me back an Array, with all of
rails dependencies.

That would be lovely. I am not sure if this is worth to report,
if it is too much of a hassle or work, just close this issue
here. Thanks.

**Comment by bronzdoc** [comment]
I'm going to close this since has been idle for almost 3 years and nobody else has requested this feature
