### ISSUE TITLE
Warn about invalid SPDX license identifiers

### ISSUE THREAD

**Issue by kemitchell** [rubygems/rubygems#1247]
Would RubyGems be interested in a pull request to warn users whose gemspecs contain invalid SPDX license identifiers?

A rough and ready study of licensing metadata on RubyGems shows the biggest problem is lack of license metadata full stop, followed by wide variety in non-SPDX license strings:

https://gist.github.com/kemitchell/31911e3b750af04e6186 (frequency chart of license strings)

https://gist.github.com/kemitchell/641c56926f48003cdd4b (gems without "licenses" metadata)

`"BSD"`, for instance, is ambiguous. (`"BSD-2-Clause"`? `"BSD-3-Clause"`?) Fortunately, the most popular option, `"MIT"`, is fine. But any license with a version, like `"Apache-2.0"`, ends up getting expressed dozens of ways. That means complying with a FOSS licensing policy devolves to a manual process.

The list of licenses (http://spdx.org/licenses), isn't that long, and could easily be rolled into a YAML file. The only potential bikeshed I see is what to do about non-standard or custom licensing. Gem might set some "magic value", like `"See LICENSE"`, for such projects, or just accept that users will get warnings about descriptions of custom licenses in the gemspec.

I recently helped @npm do much the same: https://github.com/npm/npm/releases/tag/v2.10.0 . For historical reasons, we ended up using SPDX license expressions like `"(Ruby OR GPL-2.0 OR BSD-2-Clause)"`, but arrays seem best for RubyGems. The additional logic for SPDX validation would be simpler.

Thanks to all for much fine work!
K

**Comment by tenderlove** [comment]
As long as the warning is only emitted at gem build time, it seems fine to me.

> arrays seem best for RubyGems

I think it's already an array on the spec.  Should just be a matter of adding a list of valid license names and some code to check it.

**Comment by kemitchell** [comment]
Thanks for your reply! 10-4 on build-time warnings only. I will PR ASAP.
