### ISSUE TITLE
Please consider adding --norc to avoid having to load any .gemrc file - thanks!

### ISSUE THREAD

**Issue by shevegen** [rubygems/rubygems#1248]
certainty> hmm can i make the gem command ignore the ~/.gemrc?
shevy> certainty you have funny ideas
shevy> usually this would be like --norc I think
shevy> not sure if gem has that... let's see
jhass> certainty: yeah, just use the rm command on the file
certainty> jhass: :)
shevy> "bash --help" has --norc
certainty> shevy: it doesn't look like it
shevy> I can't find this for gem
certainty> maybe i'm doing things wrong. Ok i want to query a specific gemserver for a given gem using gem list. However the -s option only appends the given soure URL to the list of existing URLs. I assume those come from the .gemrc. (I hope it doesn't have a hardcoded default)
certainty> shevy: ok got it, while there is no --norc, you can use --config-file which gives you back the control
shevy> cool
shevy> I will note this down too
shevy> how did you find out though?
certainty> "gem list --help" xD
certainty> now i can query a specific server to see which gems are available
shevy> certainty oh but --config-file is a workaround right? it is not equal to --norc
certainty> shevy: it's not equal. correct, but you can of course generate an empty config file or somesuch and use that with --config-file

Ok, long conversation above.

Short summary:

- Please add a --norc option so we don't have to rely on
workarounds such as --config-file EMPTY_FILE_HERE

Thanks for considering!

**Comment by mkristian** [comment]
with https://github.com/torquebox/jruby-maven-plugins and https://github.com/jruby-gradle/jruby-gradle-plugin we want to control of how the gems are installed by those plugins within the plugin. in order to achieve we set all kinds of  switches to overwrite the values from ~/.gemrc

a ```--norc``` would be helpful in the sense that it is shorter and furture prove (for any new features), i.e. it would nice to have.

**Comment by simi** [comment]
I can try to implement this.

**Comment by bronzdoc** [comment]
FYI: https://github.com/rubygems/rubygems/pull/1329

**Comment by bronzdoc** [comment]
This should be closed =)
