### ISSUE TITLE
Backport 65ab980dbc13d1b8e95b7d1f7266406720718c24 to 2.4.x

### ISSUE THREAD

**Issue by tenderlove** [rubygems/rubygems#1256]
Hi,

Can you backport 65ab980dbc13d1b8e95b7d1f7266406720718c24 to 2.4.x?  It fixes a bug that was introduced by e2935c85 and that commit was added to v2.4.5 and up.

I can do the cherry-pick, but I wanted to give people a heads up. :smile:

**Comment by copiousfreetime** [comment]
@tenderlove this appears to have never been backported, do we still need to do it?

**Comment by tenderlove** [comment]
Ya we definitely should.  I'll do the backport.

**Comment by tenderlove** [comment]
Done.

**Comment by hsbt** [comment]
@tenderlove 

I created backport ticket to ruby core too.

https://bugs.ruby-lang.org/issues/12248

**Comment by hsbt** [comment]
tests on 2.4 branch is failing now. We can't backport this patch into ruby 2.2.x
