### ISSUE TITLE
specify dependencies per ruby version

### ISSUE THREAD

**Issue by tenderlove** [rubygems/rubygems#126]
Hi,

I think it would be nice if I could specify dependencies depending on the ruby version.  For example, the perftools.rb gem [has a dependency if it's on 1.9](https://github.com/tmm1/perftools.rb/blob/master/ext/extconf.rb#L14-28), but does not require that dependency on 1.8.

Thanks.

**Comment by copiousfreetime** [comment]
Although this is a lovely idea, This issue has had no traffic in 3 years. Closing.
