### ISSUE TITLE
RubyGems can't find JRuby's Java extensions defined in default_ext_dir_for paths

### ISSUE THREAD

**Issue by strzibny** [rubygems/rubygems#1260]
Current gems with Java extensions adds compiled `.jar` in `/lib`, but on Fedora we implement our own `operating_system.rb` to tell RubyGems that the path for Java extensions should be in ` /usr/share/gems/jruby/`. 

`Gem.default_ext_dir_for` returns correct paths, but the paths are never added since RubyGems only checks for `gemspec.extensions` in https://github.com/rubygems/rubygems/blob/540d1d92d076ac478bf47c5c5c4c4cccbc04ad7a/lib/rubygems/basic_specification.rb#L241. This is unfortunately undefined only for Java extensions as there is no `extconf.rb` file, since JARs are included in .gem files. There are gems like **thread_safe** that provide only Java extension and therefore lack any `gemspec.extensions` entry in gemspec file and RubyGems treat such gems as a gems without extension.

IMHO RubyGems should have a way of detecting if Java extension is present and should try to add it to require paths.

**Comment by mkristian** [comment]
jruby can tread any ".class" or ".jar" as resource and can require them as any other ".rb" files. in case of a jar there is some "introspection" going on to find some BasicLibraryExtension.class which will be loaded. 

but there are plenty of gems which just pack some jar dependencies inside the gem and requires them when needed. examples are: xerces, xalan, jackson, bouncy-castle, jline, snakeyaml, etc

the ruby code expect those jar where they are or on the $LOAD_PATH

so what makes a jruby only gem one with an extension ? how do you distinguish vendored jars from "extension" jars ?

what is the benefit of copying some jars from under lib/ to another directory ?

what do you do if the ruby code does something like
```
Dir[ File.expand_path( "../*.jar, __FILE__ )].each { |jar| require jar }
``` 
?

**Comment by copiousfreetime** [comment]
There has been no more traction on this ticket, going to close for now. If this is still an issue for folks, please reopen.
