### ISSUE TITLE
Load error while attempting to run ruby setup.rb

### ISSUE THREAD

**Issue by whotooktwarden** [rubygems/rubygems#1261]
Ran apt-get install ruby and I had the latest version of ruby installed.  I then ran git clone and cd to the rubygems directory and ran ruby setup.rb and received this error:

root@vps1484:~/rubygems# ruby setup.rb 
/root/rubygems/lib/rubygems/specification.rb:15:in `require': cannot load such file -- rubygems/util/stringio (LoadError)
        from /root/rubygems/lib/rubygems/specification.rb:15:in `<top (required)>'
        from /root/rubygems/lib/rubygems.rb:1213:in `require'
        from /root/rubygems/lib/rubygems.rb:1213:in `<module:Gem>'
        from /root/rubygems/lib/rubygems.rb:115:in `<top (required)>'
        from setup.rb:32:in `require'
        from setup.rb:32:in `<main>'

**Comment by djberg96** [comment]
Should be fixed in https://github.com/rubygems/rubygems/pull/1262. Please try again.

**Comment by whotooktwarden** [comment]
setup.rb now functions as expected.
