### ISSUE TITLE
rubygems incompatible with $SAFE=1

### ISSUE THREAD

**Issue by rubys** [rubygems/rubygems#1265]
Test case:

```ruby
$SAFE=1
require 'rack'
```

Results:
/usr/lib/ruby/2.2.0/rubygems/basic_specification.rb:79:in `file?': Insecure operation - file? (SecurityError)
	from /usr/lib/ruby/2.2.0/rubygems/basic_specification.rb:79:in `block (2 levels) in contains_requirable_file?'
	from /usr/lib/ruby/2.2.0/rubygems/basic_specification.rb:79:in `any?'
	from /usr/lib/ruby/2.2.0/rubygems/basic_specification.rb:79:in `block in contains_requirable_file?'
	from /usr/lib/ruby/2.2.0/rubygems/basic_specification.rb:77:in `any?'
	from /usr/lib/ruby/2.2.0/rubygems/basic_specification.rb:77:in `contains_requirable_file?'
	from /usr/lib/ruby/2.2.0/rubygems/specification.rb:937:in `block in find_inactive_by_path'
	from /usr/lib/ruby/2.2.0/rubygems/specification.rb:936:in `each'
	from /usr/lib/ruby/2.2.0/rubygems/specification.rb:936:in `find'
	from /usr/lib/ruby/2.2.0/rubygems/specification.rb:936:in `find_inactive_by_path'
	from /usr/lib/ruby/2.2.0/rubygems.rb:187:in `try_activate'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:126:in `rescue in require'
	from /usr/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from test.rb:2:in `<main>'
```

**Comment by tenderlove** [comment]
@rubys did this ever work?  AFAICT, `$SAFE=1` isn't compatible with `require` in general:

```
[aaron@TC xxx (master)]$ ruby --disable-gems -I. -e'$SAFE=1; require "foo"'
-e:1:in `require': Insecure operation - require (SecurityError)
	from -e:1:in `<main>'
[aaron@TC xxx (master)]$
```

**Comment by rubys** [comment]
I have been using this for years.  I still haven't tracked down why it stopped working for me this week.

To be more specific, what was working for me before was more along the lines of:

```ruby
require 'rack'
$SAFE=1
require 'rack'
```

**Comment by rubys** [comment]
I'll close until I can provide a better test case.

**Comment by rubys** [comment]
I lied.  Reopening without a better test case.  I still don't fully understand what has changed, but

  1. I note that rubygems/basic_specification.rb contains a number of calls to `untaint`
  2. My problem goes away with adding one more call to untaint: `File.join full_gem_path, path.untaint`

**Comment by rubys** [comment]
Workaround: https://github.com/rubys/whimsy-agenda/commit/1bb2a551daa5089d18ccc4db2abb21d8a395a59f

**Comment by rubys** [comment]
and now with a small test case, including a workaround that you can enable:

```ruby
require 'sinatra'
require 'wunderbar'
require 'whimsy/asf'

if ARGV.include? 'workaround'
  Gem::Specification.stubs.each do |stub|
    stub.full_require_paths.each {|path| path.untaint}
  end
end

get '/data' do
  _json do
    ['abc'.unicode_normalize(:nfd)]
  end
end
```
