### ISSUE TITLE
Add gemspec#add_optional_dependency

### ISSUE THREAD

**Issue by kbrock** [rubygems/rubygems#1266]
I find I'm running into more and more gems that have optional dependencies: [bundler] [html-pipeline]

You run the gem and it raises an error for you to manually install the optional dependency (gem/version).

I had thought `metric_fu` had optional dependencies, since it was notoriously hard to get installed. Looks like it now uses hard dependencies. Probably due to this difficulty.

Existing package managers like `rpm`, do not have this. But I guess they don't have developer dependencies either. And I really like having developer dependencies in those gemspecs.

Thanks

[bundler]: https://github.com/bundler/bundler/blob/master/lib/bundler/cli/viz.rb#L13-L16
[html-pipeline]: https://github.com/jch/html-pipeline/blob/master/lib/html/pipeline/emoji_filter.rb#L3-L7

**Comment by djberg96** [comment]
@kbrock I think you can do it now: https://github.com/rubygems/rubygems/issues/346

**Comment by kbrock** [comment]
thanks @djberg96
