### ISSUE TITLE
Unresolved specs during Gem::Specification.reset: minitest (~> 5.1)

### ISSUE THREAD

**Issue by shawndeprey** [rubygems/rubygems#1267]
I wasn't sure where to put this, but I saw a similar issue here(https://github.com/rubygems/rubygems/issues/1070) being discussed and figured it was the right place.

I am running into the following issue:
```
$ rake test:prepare
WARN: Unresolved specs during Gem::Specification.reset:
      minitest (~> 5.1)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
```

Normally this warning doesn't block the command from running like in the above output, but the warning does show on almost all commands I run which load my environment. I have tried quite a few different fixes to this issue. I have tried using minitest 5.1. Uninstalling/installing my bundle. I've even tried just rebuilding my whole environment. Nothing allows me to prepare test cases though.

I am not sure how to remedy this issue/if there is a remedy. I have prepared a GIST with information about my environment and can update it with whatever information is needed to figure this problem out. I recently updated to Rails 4 and hope there is just some incompatibility I am overlooking. Sorry if this isn't the right place to ask about this, it's a rather ambiguous issue.

https://gist.github.com/shawndeprey/68653f2cae4c140f97d6

**Comment by shawndeprey** [comment]
Maybe this will help, I did figure out some incompatibilities which may shed some light on this issue.

```
rails (= 4.2.1) ruby depends on
      activesupport (= 4.2.1) ruby depends on
        minitest (~> 5.1) ruby
```

It looks like Rails 4.2.1, the version I am using, depends on minitest 5.1. However, as you will see in the following the latest release version of minitest-rails (2.1.1) depends on minitest 5.4.

```
minitest-rails (= 2.1.1) ruby depends on
      minitest (~> 5.4) ruby
```

I can't find a version of minitest-rails which supports the same version of minitest as rails itself, and it seems like this might be the issue. Maybe minitest-rails and rails are technically incompatible in their current release states? Or am I just reading that wrong?

**Comment by tenderlove** [comment]
This is the right place!  What version of Ruby and RubyGems are you using?  What is the output of `gem list minitest` (without bundle exec)?

Those two should be compatible.  If the version is X.Y.Z, then `~> 5.1` means X = 5, Y >= 1, Z = anything.  `~> 5.4` means X = 5, Y >= 4, Z = anything.  So minitest 5.4.X should work for both.

It seems like something is depending on minitest, and the spec is being activated before bundler has a chance to do it's thing.  If you do `bundle exec rake test:prepare`, do you still get the warning?

**Comment by shawndeprey** [comment]
Thanks for the quick response, I have been doing some testing based on what you said.

I am using `ruby '2.2.2'` combined with `rubygems-bundler (1.4.4)`. The output I get from the gem list is the following:
```
$ gem list minitest

*** LOCAL GEMS ***

minitest (5.6.1, 5.4.3)
minitest-rails (2.1.1)
```

When I run `bundle exec rake test:prepare` I do not get the warning, in fact I don't get any output at all. However, the result is also the same as running the command without `bundle exec`. Does any of that information help?

**Comment by tenderlove** [comment]
Sorry, just to be clear: whey you run `rake test:prepare`, you get the error, but when you run `bundle exec rake test:prepare`, you don't?

**Comment by shawndeprey** [comment]
@tenderlove yes, but in both cases the process still doesn't happen. That makes me think the error is just being suppressed.

**Comment by shawndeprey** [comment]
@tenderlove I think I figured this one out, at least in part. So it looks like the spec reset might have been a red herring to the actual problem. My problem ended up being that my test database wasn't created. I got the idea to just manually create my database after checking out the following thread: https://github.com/rspec/rspec-rails/issues/936

I used the following commands to do it:
```
RAILS_ENV=test;bundle exec rake db:create;RAILS_ENV=development
RAILS_ENV=test;bundle exec rake db:migrate;RAILS_ENV=development
```

I then was able to run my tests correctly with the following commands(depending on my use case):
```
RAILS_ENV=test;bundle exec rake test;RAILS_ENV=development
RAILS_ENV=test;bundle exec m test/functional/controllers/api/v4/companies_controller_test.rb:13;RAILS_ENV=development
```

All this is to say I think the red herring means this issue can be closed. I am not sure if I just missed something in the way you are supposed to configure your test environment in rails 4, but in any case the gem spec isn't the issue. Thanks for the help.

**Comment by msievers** [comment]
I have a similar problem with `activesupport` and `minitest`.

Assume the following Gemfile

```
source "https://rubygems.org"
gem "activesupport"
```

If a ran bundle a get
```
Using i18n 0.7.0
Using json 1.8.3
Using minitest 5.7.0 # <= shouldn't this be 5.1.x as requested by activesupport gemspec ?
Using thread_safe 0.3.5
Using tzinfo 1.2.2
Using activesupport 4.2.3
Using bundler 1.10.6
```

I tested this simple `Gemfile` with MRI 2.2.2 and bundler 1.10.6 and jruby 1.7.19 + bundler 1.8.2. Both give the same `minitest 5.7.0`.

The Gemfile.lock states minitest 5.7.0 as sole dependency, but I don't know where this comes from.

```
GEM
  remote: https://rubygems.org/
  specs:
    activesupport (4.2.3)
      i18n (~> 0.7)
      json (~> 1.7, >= 1.7.7)
      minitest (~> 5.1)
      thread_safe (~> 0.3, >= 0.3.4)
      tzinfo (~> 1.1)
    i18n (0.7.0)
    json (1.8.3)
    minitest (5.7.0)
    thread_safe (0.3.5)
    tzinfo (1.2.2)
      thread_safe (~> 0.1)

PLATFORMS
  ruby

DEPENDENCIES
  activesupport

BUNDLED WITH
   1.10.6
```

I removed all minitests gems, rebundled, but everytime it reinstalls the `5.7.0`.

**Comment by SRod86** [comment]
I was getting this same warning message too and thought I'd share what fixed it (for me).

Apparently, my issue was I had different versions of the same gem(s) and Rspec wasn't sure which to use. All I did was `gem cleanup` with the name of the gems popping up in the warning. 

Ex1: `gem cleanup minitest`
Ex2: `gem cleanup loofah`

Once that was done, the warning went away. Hope this helps! :)

**Comment by troystarwalt** [comment]
Thanks for the follow up btw SRod86. Had the same error.

**Comment by Netznarkose** [comment]
@SRod86 your approach solved it for me!

**Comment by steakknife** [comment]
There's another un/common pathology when using bundler with bundled projects *and* making the mistake of requiring bundled gems *before* `require 'bundler/setup'` can result in output similar to the following:

```
...
WARN: Unresolved specs during Gem::Specification.reset:
      minitest (~> 5.1)
      rake (>= 0.8.7)
WARN: Clearing out unresolved specs.
...
```

**Solution:** require bundled gems *after* bundler/setup, i.e., for Rails: require gems only *after* `require 'bundler/setup'` in config/boot.rb or later.

**Comment by agasthik** [comment]
@SRod86 . Your approach helped resolve a similar issue I was facing

```
WARN: Unresolved specs during Gem::Specification.reset:
json_pure (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
```

```
bash-3.2# gem cleanup json_pur
Cleaning up installed gems...
Clean Up Complete
bash-3.2# gem cleanup json_pure
Cleaning up installed gems...
Attempting to uninstall json_pure-1.8.1
Successfully uninstalled json_pure-1.8.1
Clean Up Complete
```

**Comment by thinkbui** [comment]
I ran into a similar problem with the same warning message.  The problem was that I had both minitest-5.8.4 and minitest-5.9.0 installed.  After running `gem cleanup minitest` to remove 5.8.4, rspec kept complaining that it was missing and bundling would reinstall it despite 5.9.0 also installed.  In the end I was forced to run `gem uninstall minitest` to remove both versions and re-bundle.

I was never able to determine what was requiring 5.8.x specifically since no version was explicitly listed in my Gemfile and all of the dependencies I was able to find showed '~> 5.8' at the highest or something else that 5.9.0 should have met.

**Comment by kpheasey** [comment]
RVM global gemset was the cause of my issue.

```sh
$ gem list minitest

*** LOCAL GEMS ***

minitest (5.10.1, 5.8.3)
```

`gem uninstall minitest` was only removing 5.10.x, but `rvm @global do gem uninstall minitest` removed the 5.8.x.

```sh
$ rvm @global do gem uninstall minitest
Successfully uninstalled minitest-5.8.3
```

**Comment by thom801** [comment]
Cleanup was not doing the trick but `rvm @global do gem uninstall minitest` solved it for me thank you @kpheasey!

**Comment by vynessa** [comment]
I used `bundle clean --force` and then ran `bundle install` to reinstall gems. Fixed the issue here.

**Comment by necatierol** [comment]
I used `gem uninstall -i /usr/share/rubygems-integration/all minitest` and fixed for me.

**Comment by rosalynnas** [comment]
Sometimes when this happens, `bundle clean/prisitine` doesn't work and I usually can't run `bundle clean --force` on a big project. I solved it by identifying the gem that depended on the problematic gem then running `bundle update <gem>` (careful with this too because you could introduce breaking changes if it was a big version bump).
