### ISSUE TITLE
IPv6 literal not recognised for --http-proxy config option

### ISSUE THREAD

**Issue by mpalmer** [rubygems/rubygems#1269]
```
$ gem install rails --http-proxy='http://[2001:db8::1]:3128'
ERROR:  Could not find a valid gem 'rails' (>= 0) in any repository
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SocketError: getaddrinfo: Name or service not known (http://rubygems.org/latest_specs.4.8.gz)
$ grep mahproxy /etc/hosts
2001:db8::1 mahproxy
$ gem install rails --http-proxy='http://mahproxy:3128'
[Installation proceeds normally]
```

So, the problem isn't that rubygems can't handle IPv6 proxies, it's simply that it doesn't recognise a properly-formed IPv6 literal URL as a proxy address.  BTW, I *know* it's using the proxy when it successfully installs, because this is on an IPv6-only machine and the proxy logs show the requests transiting the proxy when the installation completes.

As an aside, it *also* doesn't work when setting the `http_proxy` env var, which I assume is the same fundamental bug.

**Comment by jrafanie** [comment]
I don't have a http proxy locally to test @mpalmer, but I do see rubygems sending along `uri.host` to Net::HTTP.

Can you make these changes locally to see if it works?   Unfortunately, `URI#hostname` wasn't added until ruby 1.9.3 so we may have to monkey patch it in rubygems if we need to support earlier rubies.

```diff
diff --git a/lib/rubygems/request/connection_pools.rb b/lib/rubygems/request/connection_pools.rb
index 7a0a6e6..2b396b3 100644
--- a/lib/rubygems/request/connection_pools.rb
+++ b/lib/rubygems/request/connection_pools.rb
@@ -61,18 +61,18 @@ class Gem::Request::ConnectionPools # :nodoc:
   end

   def net_http_args uri, proxy_uri
-    net_http_args = [uri.host, uri.port]
+    net_http_args = [uri.hostname, uri.port]

     no_proxy = get_no_proxy_from_env

-    if proxy_uri and not no_proxy?(uri.host, no_proxy) then
+    if proxy_uri and not no_proxy?(uri.hostname, no_proxy) then
       net_http_args + [
-        proxy_uri.host,
+        proxy_uri.hostname,
         proxy_uri.port,
         Gem::UriFormatter.new(proxy_uri.user).unescape,
         Gem::UriFormatter.new(proxy_uri.password).unescape,
       ]
-    elsif no_proxy? uri.host, no_proxy then
+    elsif no_proxy? uri.hostname, no_proxy then
       net_http_args + [nil, nil]
     else
       net_http_args
```

**Comment by drbrain** [comment]
Note that URI#hostname doesn't exist for all versions of ruby supported by RubyGems.

**Comment by drbrain** [comment]
Oh, oops, I should read better, sorry!

**Comment by jrafanie** [comment]
Note, the tests seem to create a Fake Net::HTTP so we probably aren't seeing them fail here... but I can recreate it with master:

```ruby
irb(main):001:0> $:.unshift "./lib"
=> ["./lib", ...]
irb(main):002:0> require 'rubygems/request'
=> true
irb(main):003:0> Gem::Request.create_with_proxy(URI("http://[::1]/abc"), nil, nil, nil).connection_for(URI("http://[::1]/abc"))
SocketError: getaddrinfo: nodename nor servname provided, or not known
```

With above changes, it works, (ruby 1.9.3+ have URI#hostname), it gets past the SocketError but fails because I don't have a webserver proxy locally on port 80:

```ruby
irb(main):001:0> $:.unshift "./lib"
=> ["./lib", ...]
irb(main):002:0> require 'rubygems/request'
=> true
irb(main):003:0> Gem::Request.create_with_proxy(URI("http://[::1]/abc"), nil, nil, nil).connection_for(URI("http://[::1]/abc"))
Errno::ECONNREFUSED: Connection refused - connect(2) for "::1" port 80
```

**Comment by jrafanie** [comment]
@drbrain @tenderlove I'll put together a PR since it's easier than tossing around patches, but we may have to monkey patch URI::Generic#hostname.  Additionally, it's really hard to tell where we're passing around URIs vs. fields that get handed off to the Socket layer via net/http or elsewhere so there may be others.

https://github.com/ruby/ruby/blob/fd4ec2bc905d945648f1ea18d68f52d13dffa73d/lib/uri/generic.rb#L648-651

**Comment by jrafanie** [comment]
Opened #1275 in case this fixes the reported issue by @mpalmer (since I can't really recreate it exactly as reported without a http proxy setup).

**Comment by mpalmer** [comment]
I've tested the patch in #1275 and it seems to do the trick on modern Rubies.
