### ISSUE TITLE
When validating, check file exists before .stat ing it

### ISSUE THREAD

**Issue by segiddins** [rubygems/rubygems#1273]
This would allow a nice exception message than an ERRNO::ENOENT

**Comment by drbrain** [comment]
How do we reproduce this?  Can you show an example?

**Comment by segiddins** [comment]
https://github.com/bundler/bundler/issues/3698

**Comment by drbrain** [comment]
That issue doesn't have any steps to reproduce either.

Can you add some steps that don't require bundler to this issue?

**Comment by segiddins** [comment]
That's just the first example I've seen -- I'm at work right now, but how about I just fix it when I get home?

**Comment by drbrain** [comment]
That would be excellent, thanks!
