### ISSUE TITLE
Unable to install any gems on Windows

### ISSUE THREAD

**Issue by TaylorHuston** [rubygems/rubygems#1279]
Windows 7 x64. I get this error when I try install any gem.

```
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol (https://your-dns-needs-immediate-attention.win/quick/Marshal.4.8/fast-stemmer-1.0.2.gemspec.rz)
```

Gem version 2.2.3.

I don't believe it is the same error as https://gist.github.com/luislavena/f064211759ee0f806c88

**Comment by segiddins** [comment]
`https://your-dns-needs-immediate-attention.win` seems suspect...

**Comment by TaylorHuston** [comment]
Yes, though what's causing it I don't know. My DNS is working fine, I can do everything else webernets related. I tried swapping to Google's public DNS, that didn't change anything. I don't think it's a problem with my router or ISP as my Macbook doesn't have any issues.

**Comment by tenderlove** [comment]
Seems like an issue with name resolution on your windows machine.  Googling around [lead me here](http://triple-networks.com/2015/03/26/your-dns-needs-immediate-attention/) though I'm not sure it'll help much.  FWIW, it doesn't seem like a windows specific issue.  Can you check your name servers and search on the windows machine?

**Comment by TaylorHuston** [comment]
I figured it out. The VPN software I use for work appended some DNS suffixes for some reason (regardless of whether I was connected to said VPN or not). Removed that, gems work fine (and so does my VPN).

**Comment by tymfear** [comment]
@TaylorHuston and how to remove that?

**Comment by TaylorHuston** [comment]
Network and Sharing Center -> Local Area Connection -> Properties -> IPv4 -> Advanced -> DNS
