### ISSUE TITLE
uninitialized constant Gem::NoAliasYAMLTree with JRuby dev

### ISSUE THREAD

**Issue by djberg96** [rubygems/rubygems#1280]
OSX (Yosemite)
jruby 9.0.0.0-SNAPSHOT (2.2.2) 2015-06-02 798fd22 Java HotSpot(TM) 64-Bit Server VM 25.45-b02 on 1.8.0_45-b14 +jit [darwin-x86_64]

This is an obscure error caused by a dumb gemspec, but it might be indicative of a larger issue so I thought I should report it. Basically I was futzing around with the DependencyInstaller class inside the gemspec and stumbled on this error when I try to create the gem:

    uninitialized constant Gem::NoAliasYAMLTree 

Here's the gemspec

    # foo.gemspec
    require 'rubygems'
    require 'rubygems/dependency_installer'

    Gem::Specification.new do |spec|
      spec.name      = 'foo'
      spec.version   = '0.0.1'
      spec.author    = 'Daniel J. Berger'
      spec.license   = 'Artistic 2.0'
      spec.email     = 'djberg96@something.com'
      spec.homepage  = 'http://github.com/djberg96/foo'
      spec.summary   = 'Foo'
      spec.test_file = 'test/test_foo.rb'
      spec.files     = Dir['**/*'].reject{ |f| f.include?('git') }

      installer = Gem::DependencyInstaller.new
      installer.install 'win32-ipc'

      spec.extra_rdoc_files  = ['README']

      spec.description = "Test spec for general futzing"
    end

It looks like psych isn't loaded first before trying to access Gem::NoAliasYAMLTree.

**Comment by duckinator** [comment]
Can't reproduce.

jruby 9.0.5.0 (2.2.3) 2016-01-26 7bee00d Java HotSpot(TM) Client VM 25.73-b02 on 1.8.0_73-b02 +jit [Windows 8.1-x86]
gem 2.6.1

Testcase: https://gist.github.com/duckinator/329ea833a43b969fa45f

**Comment by duckinator** [comment]
@djberg96 can you run the testcase and let me know if you can reproduce this still?

**Comment by djberg96** [comment]
@duckinator Looks like whatever was causing this has been changed/updated/fixed, so I'll close it. Thanks for investigating.
