### ISSUE TITLE
Gem.install doesn't work when a requirement already exists

### ISSUE THREAD

**Issue by segiddins** [rubygems/rubygems#1281]
The following script should exit 0, but instead raised during the install.
```ruby
#!/usr/bin/ruby
`gem uninstall bundler -v 1.9.9`

version = '1.9.9'

require 'rubygems'

begin
  gem 'bundler', version
rescue Gem::LoadError, LoadError => e
  Gem.install('bundler', version, :domain => :both)
  retry
end
```

**Comment by segiddins** [comment]
The cause of this seems to be https://github.com/rubygems/rubygems/blob/8f6bcea9e70d93a1092bbd174672f0dab5587753/lib/rubygems/request_set.rb#L171, which seems dubious to me.

**Comment by bf4** [comment]
1. watch out for infinite retries.
2. Why would you want to do this in a ruby script?  Better for shell, I think.

**Comment by segiddins** [comment]
@bf4 neither of those concerns really applies to the issue at hand

**Comment by bf4** [comment]
( @segiddins agreed, sorry for not being more clear I was just FYI)
