### ISSUE TITLE
`gem install --file` (NoMethodError)

### ISSUE THREAD

**Issue by mcelicalderon** [rubygems/rubygems#1286]
I was trying to run `gem install --file` and got NoMethodError. This is the stack trace:

ERROR:  While executing gem ... (NoMethodError)
    undefined method `version' for nil:NilClass
	/Users/mceli/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/request_set/lockfile/parser.rb:324:in `pinned_requirement'
	/Users/mceli/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/request_set/lockfile/parser.rb:99:in `parse_DEPENDENCIES'
	/Users/mceli/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/request_set/lockfile/parser.rb:22:in `parse'
	/Users/mceli/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/request_set.rb:282:in `load_gemdeps'
	/Users/mceli/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/request_set.rb:207:in `install_from_gemdeps'
	/Users/mceli/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/commands/install_command.rb:213:in `install_from_gemdeps'
	/Users/mceli/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/commands/install_command.rb:189:in `execute'
	/Users/mceli/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/command.rb:307:in `invoke_with_build_args'
	/Users/mceli/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/command_manager.rb:168:in `process_args'
	/Users/mceli/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/command_manager.rb:138:in `run'
	/Users/mceli/.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/gem_runner.rb:54:in `run'
	/Users/mceli/.rvm/rubies/ruby-2.1.6/bin/gem:21:in `<main>'

- Gemfile: https://gist.github.com/mcelicalderon/20bbd7ecdacb8d7e27b8/raw/d7e6f4f955418510bb1592490630cfe2091362d2/Gemfile

- Gemfile.lock: https://gist.github.com/mcelicalderon/20bbd7ecdacb8d7e27b8/raw/c343f4463e63ac0fa488355c556252b5583cb8cc/Gemfile.lock

**Comment by mayurkhatri** [comment]
@mcelicalderon  while installing which gem did you get this error?

**Comment by mcelicalderon** [comment]
@mayurkhatri All gems were already installed using bundler, I was just trying to test that `gem install --file` works and got that error @mpapis can probably provide more feedback on the issue.

**Comment by mpapis** [comment]
there are two bugs:

1. `Gemfile`: `gem ... source: ...` does not handle the `:source` - see #1305
2. `Gemfile.lock`: `GEM ... remote ...` looks like RG does not handle the `remote` - did not find direct problem there yet

**Comment by mpapis** [comment]
could you rerun this on Rubygems master as #1355 just landed and might be solving some of those problems (in RVM `rvm rubygems master`, otherwise checkout the repo and `ruby setup.rb`)

**Comment by bronzdoc** [comment]
Closing, fixed by https://github.com/rubygems/rubygems/pull/1355
