### ISSUE TITLE
Unable to install pry gem on Windows 7

### ISSUE THREAD

**Issue by echristopherson** [rubygems/rubygems#1293]
I currently get an error when trying to gem install pry in Windows 7 using Ruby 2.2.2p95 (32-bit):

    X:\Scripts>gem install pry
    ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
        bad response Not Found 404 (https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/pry-0.10.1-x86-mingw32.gemspec.rz)

    X:\Scripts>gem install pry --platform ruby
    ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
        bad response Not Found 404 (https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/pry-0.10.1-x86-mingw32.gemspec.rz)

    X:\Scripts>gem install pry --pre
    ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
        bad response Not Found 404 (https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/pry-1.0.0.pre1-x86-mingw32.gemspec.rz)

    X:\Scripts>gem install pry --pre --platform ruby
    ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
        bad response Not Found 404 (https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/pry-1.0.0.pre1-x86-mingw32.gemspec.rz)

I first noticed this problem on June 17. But I was able to install pry on my Mac that same day with no problems.

**Comment by echristopherson** [comment]
I'm going to put this on https://github.com/rubygems/rubygems.org/issues .

**Comment by dwradcliffe** [comment]
From the other issue:

> The gems you are referencing are actually only available for platforms `i386-mswin32` or `i386-mingw32` (for windows). For some reason, the urls above are for `x86-mingw32`. We've double checked the server and index and everything is consistent there. So it seems like your rubygems client is requesting the wrong platform/url for some reason.

**Comment by echristopherson** [comment]
My output from `ruby -e 'puts Gem.platforms.inspect'` is `["ruby", #<Gem::Platform:0x15324fc @cpu="x86", @os="mingw32", @version=nil>]`.

**Comment by echristopherson** [comment]
My Ruby is from rubyinstaller.org; its `--version` string is `ruby 2.2.2p95 (2015-04-13 revision 50295) [i386-mingw32]`.

**Comment by basarat** [comment]
Have the same issue (windows 8.1 though, but same ruby version `ruby 2.2.2p95 (2015-04-13 revision 50295) [i386-mingw32]`). This is the reason why I cannot install travis : https://github.com/travis-ci/travis.rb/issues/300

**Comment by basarat** [comment]
> but same ruby version

FWIW I just installed the `x64` version of ruby it everything worked fine.  

```
C:\Users\bas>ruby --version
ruby 2.2.2p95 (2015-04-13 revision 50295) [x64-mingw32]
```

**Comment by djberg96** [comment]
This was basically a problem in the way pry gem was created. As of 0.10.3 the pry gem has its platform set properly and should install without issue.
