### ISSUE TITLE
i18n 0.7.0

### ISSUE THREAD

**Issue by pkouman72** [rubygems/rubygems#1294]
error message could bot find valid gem i18n 0.7.0 in any repository

**Comment by segiddins** [comment]
@pkouman72 this isn't a very informative issue -- what's the exact error message that you're seeing?

**Comment by pkouman72** [comment]
Hi,
I'm trying to create a new project in rails. After I do 
rails new blog this is the message I get
DL is deprecated, please use Fiddle
Fetching gem metadata from https://rubygems.org/............
Fetching additional metadata from https://rubygems.org/..
Resolving dependencies...
Using rake 10.4.2

Gem::RemoteFetcher::FetchError: SSL_connect returned=1 errno=0 state=SSLv3 read
server certificate B: certificate verify failed (https://rubygems.org/gems/i18n-
0.7.0.gem)
An error occurred while installing i18n (0.7.0), and Bundler cannot continue.
Make sure that `gem install i18n -v '0.7.0'` succeeds before bundling.

I have seach for the i18n 0.7.0 on rubygems.org but when I follow instructions to download
gem install i18n 0.70
I get this message
C:\Sites>gem install i18n
ERROR:  Could not find a valid gem 'i18n' (>= 0) in any repository
Please help, I'm new but I've been at this for 5 days and have tried just about every solution.

**Comment by segiddins** [comment]
I think the issue there is that your ruby install is linking against a very old version of openSSL, since I believe rubygems.org has disabled SSLv3 support, due to a couple of known flaws.

**Comment by pkouman72** [comment]
what do you suggest I do?

**Comment by andremedeiros** [comment]
What does `gem update --system` give you?

**Comment by pkouman72** [comment]
latest version currently installed aborting

**Comment by andremedeiros** [comment]
Alright, so that just leaves @segiddins' suggestion. Can you upgrade your ruby version? Seems to me that you're in Windows. Maybe try the latest RubyInstaller?

**Comment by pkouman72** [comment]
yes, I'm in windows I installed through rubyinstaller version 2.2.2. I just uninstalled and reinstalled through rubyinstaller 2.2.1

**Comment by pkouman72** [comment]
sorry 2.1.6

**Comment by pkouman72** [comment]
what is the i18n gem this seems to be my problem I can't install it

**Comment by andremedeiros** [comment]
It's the internationalisation gem. Unfortunately it's a Rails dependency, so you can't do without. :-(

**Comment by pkouman72** [comment]
No clue as to why I ca't install it?

**Comment by Smulligan85** [comment]
@pkouman72 Are you working on a mac? I had a similar issue when I updated Xcode and realized I had not subsequently agreed to all terms and completed the upgrade. Have you upgraded Xcode recently. If so, open Xcode and complete the install and try creating a new rails project. Hope this helps.
