### ISSUE TITLE
Ruby installation problem . There has been an error while trying to extract rubygems. Halting the installation. 

### ISSUE THREAD

**Issue by ashusrock** [rubygems/rubygems#1295]
I am new to Ruby. and this is my first time installing it and i am getting this error.

ruby-2.2.1 - #downloading rubygems-2.4.8
ruby-2.2.1 - #extracting rubygems-2.4.8....
Error running '__rvm_package_extract /home/student/.rvm/archives/rubygems-2.4.8.tgz /home/student/.rvm/src',
showing last 15 lines of /home/student/.rvm/log/1434911081_ruby-2.2.1/rubygems.extract.log
++ [[ -n '' ]]
++ __rvm_tar xzf /home/student/.rvm/archives/rubygems-2.4.8.tgz -C /home/student/.rvm/tmp/rvm-tmp.tm6t1t1IF --no-same-owner
++ tar xzf /home/student/.rvm/archives/rubygems-2.4.8.tgz -C /home/student/.rvm/tmp/rvm-tmp.tm6t1t1IF --no-same-owner

gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
++ return 2
++ return 2
++ __return=2
++ ((  __return == 0  ))
++ [[ -n /home/student/.rvm/tmp/rvm-tmp.tm6t1t1IF ]]
++ command rm -rf /home/student/.rvm/tmp/rvm-tmp.tm6t1t1IF
++ rm -rf /home/student/.rvm/tmp/rvm-tmp.tm6t1t1IF
++ return 2
There has been an error while trying to extract rubygems. 
Halting the installation.

**Comment by segiddins** [comment]
This looks like an issue with RVM, rather than RubyGems?
