### ISSUE TITLE
minor issue: `gem list -q -i foo` produces output

### ISSUE THREAD

**Issue by e2** [rubygems/rubygems#1302]
It would be nice if the '-q' option worked with `gem list`, e.g.:

Example:
```ruby
puts `gem list -q -i foo`.inspect
```

Expected: `""`
Actual: `"false\n"`

Other: although `gem list -q` probably makes little sense, I think it also shouldn't output anything (since commonly '-q' is only expected to output errors or warnings).

**Comment by djberg96** [comment]
I'm not sure what -q should do in the context of gem list. @e2 what's your use case? Just curious.

**Comment by e2** [comment]
I'd expect it to work like grep - just return zero or nonzero depending if anything was found - this is for automation and shell scripting.

The output forces capturing/redirecting output, which makes it hard to capture failures (which I'd expect to occur on stderr).

**Comment by djberg96** [comment]
I think this might break scripts that are also using -i to return true or false. I know that's what I do in some of my appveyor settings with gem query.

**Comment by copiousfreetime** [comment]
@e2 it appears that the option you want is `--silent` instead of `-q`.

```
% gem list -h | egrep "(silent|quiet)"
    -q, --quiet                      Silence command progress meter
        --silent                     Silence rubygems output
```

Example:

```
% gem list --silent -i foo
% echo $?
1
% gem list --silent -i bundler
% echo $?
0
```

Closing.

**Comment by e2** [comment]
Thanks @copiousfreetime! 

First time ever I see a tool supporting both "silent" and "quiet" with different semantics. Did I miss that, or is this addition recent - I wonder...

**Comment by copiousfreetime** [comment]
@e2 not sure, feel free to delve into the git commit history :-).
