### ISSUE TITLE
(ArgumentError) marshal data too short

### ISSUE THREAD

**Issue by spncrgr** [rubygems/rubygems#1307]
I've been getting an error that has been preventing me from installing some Gems. The error is

```
$ gem install bundler -v 1.9
ERROR:  While executing gem ... (ArgumentError)
    marshal data too short
```

I also see a similar error when running `bundle install`

```
Fetching gem metadata from https://rubygems.org/.Retrying dependency api due to error (2/3): Bundler::MarshalError ArgumentError: marshal data too short
Retrying dependency api due to error (3/3): Bundler::MarshalError ArgumentError: marshal data too short
```

Seems to happen fairly consistently across all the machines I work on. Not sure where the issue lies, but I figured I'd start here.

**Comment by tenderlove** [comment]
@spncrgr when you start seeing this issue again, can you do `ruby -d -S gem install whatever`?  That should give us the stack trace.  It sounds like something to do with the rubygems API server, but I'm not sure.  I've seen people report this before, so it would be nice to figure out better errors or just how to fix it.

**Comment by djberg96** [comment]
@spncrgr What platform are you running this on? What's the output of "gem env"?

**Comment by spncrgr** [comment]
Apologies for taking so long to respond. I've changed jobs and moved halfway across the country...so things have been a little busy :)

However, I ran across the issue today. I'm at my new job so the environment is brand new (new MacBook). However, my setup is similar to before. I'm using `jruby-1.7.19` (via RVM).

I executed the command @tenderlove suggested. I hope this doesn't confuse, or over-complicate, the issue, but I tried using both `ruby` and `jruby` at the CLI (`rvm current` remained `jruby-1.7.19`). I'm including a link to a gist (attaching wasn't working). Hopefully that will make it clearer than the way I'm explaining it.

https://gist.github.com/spncrgr/96616cea138542518b67

**Comment by djberg96** [comment]
@spncrgr, does this go away if you upgrade to JRuby 9k?

**Comment by spncrgr** [comment]
@djberg96 it appears to, yes

```
$ rvm use jruby-9.0.1.0
Using /Users/spen2299/.rvm/gems/jruby-9.0.1.0
$ gem install net-ssh -v '3.0.1'
Fetching: net-ssh-3.0.1.gem (100%)
Successfully installed net-ssh-3.0.1
1 gem installed
```

**Comment by djberg96** [comment]
@spncrgr I highly suspect this is an issue with JRuby and its resolv library rather than rubygems itself, as there have been bug reports. If you can't use JRuby 9k, try 1.7.22 at least and see if that works. I highly recommend 9k, though.

**Comment by spncrgr** [comment]
makes sense. And yes, I agree, JRuby 9k is _definitely_ the way to go ;-)
