### ISSUE TITLE
Gem.install raises LoadError

### ISSUE THREAD

**Issue by sax** [rubygems/rubygems#1315]
Assuming that one does not already have the `a` gem installed, please attempt the following with rubygems version >= 2.3.0

```ruby
errors = {}

begin
  begin
    require 'a'
  rescue LoadError => error1
    errors[:one] = error1
    begin
      Gem.install('a')
    rescue LoadError => error2
      errors[:two] = error2
    end
  end
rescue LoadError => error3
  errors[:three] = error3
end

errors
# => {:one=>#<LoadError: cannot load such file -- a>, :two=>#<LoadError: cannot load such file -- a>}
```

When `Gem.install` runs, it raises a LoadError even though it *successfully* installs the gem. 

Also note that this successfully runs without a LoadError in versions 2.2.2 - 2.2.5, and began failing in 2.3.0.

**Comment by segiddins** [comment]
I fixed this in https://github.com/rubygems/rubygems/pull/1282

**Comment by sax** [comment]
Awesome!

You are very fast with your responses :)
