### ISSUE TITLE
`gem rdoc` generate documents not found css and js files. HTTP 404

### ISSUE THREAD

**Issue by windwiny** [rubygems/rubygems#1316]
use `gem rdoc ` generate gem document, and run `gem server` show it, but not found css and js files.

gem rdoc thread

    Parsing documentation for thread-0.2.1
    Installing ri documentation for thread-0.2.1

gem server

    localhost - - [20/Jul/2015:20:33:44 CST] "GET /doc_root/thread-0.2.1/ HTTP/1.1" 304 0
    http://0.0.0.0:8808/ -> /doc_root/thread-0.2.1/
    localhost - - [20/Jul/2015:20:33:44 CST] "GET /doc_root/css/rdoc.css HTTP/1.1" 404 2048
    http://0.0.0.0:8808/doc_root/thread-0.2.1/ -> /doc_root/css/rdoc.css
    localhost - - [20/Jul/2015:20:33:44 CST] "GET /doc_root/thread-0.2.1/js/search_index.js HTTP/1.1" 304 0
    http://0.0.0.0:8808/doc_root/thread-0.2.1/ -> /doc_root/thread-0.2.1/js/search_index.js
    localhost - - [20/Jul/2015:20:33:44 CST] "GET /doc_root/css/fonts.css HTTP/1.1" 404 2048
    http://0.0.0.0:8808/doc_root/thread-0.2.1/ -> /doc_root/css/fonts.css
    localhost - - [20/Jul/2015:20:33:44 CST] "GET /doc_root/thread-0.2.1/js/navigation.js HTTP/1.1" 404 2815
    http://0.0.0.0:8808/doc_root/thread-0.2.1/ -> /doc_root/thread-0.2.1/js/navigation.js
    localhost - - [20/Jul/2015:20:33:45 CST] "GET /doc_root/thread-0.2.1/js/searcher.js HTTP/1.1" 404 2813
    http://0.0.0.0:8808/doc_root/thread-0.2.1/ -> /doc_root/thread-0.2.1/js/searcher.js
    localhost - - [20/Jul/2015:20:33:45 CST] "GET /doc_root/thread-0.2.1/js/search.js HTTP/1.1" 404 2811
    http://0.0.0.0:8808/doc_root/thread-0.2.1/ -> /doc_root/thread-0.2.1/js/search.js

**Comment by tenderlove** [comment]
I think this is a bug in RDoc and not in RubyGems.  @drbrain can you confirm?

**Comment by bronzdoc** [comment]
can this be closed @drbrain ?

**Comment by copiousfreetime** [comment]
I think this is is a bug in `RDoc::Servlet` as running webrick solo with just `RDoc::Servlet` mounted gave a similar webpage to what it looks like in `gem server`.

```
require 'webrick'
require 'rdoc'
server = WEBrick::HTTPServer.new Port: 8000
server.mount '/', RDoc::Servlet

server.start
```

Closing for now. If this is in error, please reopen.
