### ISSUE TITLE
SSL issue with DNS

### ISSUE THREAD

**Issue by quannt** [rubygems/rubygems#1317]
I am running on Windows 7 Service Pack 1. Ruby is installed using RubyInsaller. Version is 2.1.6 Encounter this error

> ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
>   SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: sslv3 alert handshake failure > (https://your-dns-needs-immediate-attention.starhub/quick/Marshal.4.8/sass-3.4.16.gemspec.rz)

whenver I run `gem install`. Had to change the machine DNS to Google DNS and it works fine after that.

 I believe this has something to do with my ISP as Starhub is my current ISP. Just want to bring this up to you guys attention.

**Comment by drbrain** [comment]
This is not a RubyGems issue.  You need to fix your resolver settings, likely by removing `starhub` from your search list as [.starhub is a valid TLD](http://www.starhub.com/nic) now.
