### ISSUE TITLE
An error occurred while installing cairo (1.14.1), and Bundler cannot continue. Make sure that `gem install cairo -v '1.14.1'` succeeds before bundling.

### ISSUE THREAD

**Issue by mallick7** [rubygems/rubygems#1318]
rubygem cario (1.14.1) is not supported to 10.10.3 mac OS but earlier i was using 10.9. and it was working fine. Please find below attached screenshots.

Could you please provide me any patch to resolve this issue.
<img width="1440" alt="screen shot 2015-07-21 at 18 56 13" src="https://cloud.githubusercontent.com/assets/11551588/8846423/bff550a2-3144-11e5-87e1-0d069bf8c565.png">
<img width="1440" alt="screen shot 2015-07-21 at 19 18 35" src="https://cloud.githubusercontent.com/assets/11551588/8846427/c5eb2db0-3144-11e5-8afe-1ae745832638.png">
<img width="1440" alt="screen shot 2015-07-21 at 19 23 03" src="https://cloud.githubusercontent.com/assets/11551588/8846431/cb206f02-3144-11e5-9f1c-22147b4bc78b.png">

**Comment by andremedeiros** [comment]
This isn't a problem with rubygems, but a problem with the compiler that you're on right now.

**Comment by mallick7** [comment]
can you suggest me any compiler..???

**Comment by tenderlove** [comment]
@mallick7 try filing a ticket [here](https://github.com/rcairo/rcairo/issues).  I think they may be better equipped to help you get `cairo` installed.
