### ISSUE TITLE
Documentation link problems

### ISSUE THREAD

**Issue by jzakiya** [rubygems/rubygems#1319]
I updated my 'roots' gem a couple of days ago, and created a github page with a README.md file.
When I go to -- https://rubygems.org/gems/roots -- and click on the 'Documentation' link it take me here --  http://rootsdoc.tumblr.com/ -- instead of here -- http://www.rubydoc.info/gems/roots/1.0.2.

The tumblr site is just a hold page that says -- 'There's nothing here.'

There is also a problem with the rubydoc.info site because it doesn't link to 'roots' README.md file and display its info, similar to my 'primes-utils' gem I recently updated.

1) Is the link to the tumblr page a bug in rubydoc and/or rubygems?
2) How can the 'Documentation' link be changed to point to the rubydoc.info page?
3) Can the rubydoc.info page be made to show the info from 'roots' README.md file, as it does with my 'primes-utils' gem.

**Comment by drbrain** [comment]
You'll have to contact the gem author or rubydoc.info, rubygems and rubygems.org do not control where those links go.
