### ISSUE TITLE
Bug or feature? System gems used when RUBYGEMS_GEMDEPS is set

### ISSUE THREAD

**Issue by e2** [rubygems/rubygems#1323]
ACTUAL: Given just an empty `Gemfile` (`touch Gemfile`), I'd assume the following should fail:

```
RUBYGEMS_GEMDEPS=Gemfile ruby -e 'require "rubygems"; require "rspec"'
```

Am I wrong?

EXPECTED: When using Bundler instead, I get this:

```
 RUBYGEMS_GEMDEPS=Gemfile ruby -e 'require "rubygems"; require "bundler/setup"; require "rspec"'
-e:1:in `require': cannot load such file -- rspec (LoadError)
	from -e:1:in `<main>'
```

Info:

```
- RUBYGEMS VERSION: 2.4.5
- RUBY VERSION: 2.2.2 (2015-04-13 patchlevel 95) [x86_64-linux]
```

(using RVM, but this shouldn't be relevant, since I get the same even with `--disable-gems` passed to Ruby)

**Comment by e2** [comment]
It seems RubyGems *always* tries to activate a gem, regardless of the RUBYGEMS_GEMDEPS setting:

https://github.com/rubygems/rubygems/blob/65ab980dbc13d1b8e95b7d1f7266406720718c24/lib/rubygems/core_ext/kernel_require.rb#L126

**Comment by copiousfreetime** [comment]
This is now working as you expected. Not sure when it was fixed.

```
% touch Gemfile
% RUBYGEMS_GEMDEPS=Gemfile ruby -v -e 'require "rubygems"; require "rspec"'
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
/opt/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- rspec (LoadError)
        from /opt/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
```
