### ISSUE TITLE
 An error occurred while installing metasploit-concern (1.0.0), and Bundler cannot continue. #2 

### ISSUE THREAD

**Issue by Mualter** [rubygems/rubygems#1331]
Hello everyone, as you can see on the topic I am trying to install Metasploit on ubuntu 14.04 
and i got an error while installing bundle

```
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/..
Resolving dependencies....
Using rake 10.4.2
Using i18n 0.7.0
Using minitest 4.7.5
Using multi_json 1.11.1
Using thread_safe 0.3.5
Using tzinfo 0.3.44
Using activesupport 4.0.13
Using builder 3.1.4
Using erubis 2.7.0
Using rack 1.5.5
Using rack-test 0.6.3
Using actionpack 4.0.13
Using activemodel 4.0.13
Using activerecord-deprecated_finders 1.0.4
Using arel 4.0.2
Using activerecord 4.0.13
Using arel-helpers 2.1.0
Using bcrypt 3.1.10
Using bundler 1.10.6
Using coderay 1.1.0
Using diff-lcs 1.2.5
Using docile 1.1.5
Using factory_girl 4.5.0
Using thor 0.19.1
Using railties 4.0.13
Using factory_girl_rails 4.5.0
Using fivemat 1.2.1
Using rkelly-remix 0.0.6
Using jsobfu 0.2.1
Using json 1.8.3
Installing metasploit-concern 1.0.0

Gem::InstallError: metasploit-concern requires Ruby version >= 2.1.
An error occurred while installing metasploit-concern (1.0.0), and Bundler
cannot continue.
Make sure that `gem install metasploit-concern -v '1.0.0'` succeeds before
bundling.
```

what i can conclude from reading the error message is that the 'metasploit-concern 1.0.0' gem requires Ruby version >= 2.1. .
But the thing is I have ruby2.1 already
this is the output of the command rvm list:
rvm rubies

=* ruby-2.1.0 [ x86_64 ]
   ruby-2.1.5 [ x86_64 ]
   ruby-2.1.6 [ x86_64 ]
   ruby-2.2.1 [ x86_64 ]

# => - current
# =* - current && default
#  * - default
******************************************
As you can see ruby-2.1.0 is already installed and set as =* - current && default
so what is the problem ?
is ruby 2.1. different from 2.1.0 ?

any help is highly appreciated.
Thank you.

**Comment by drbrain** [comment]
You have pasted bundler output.

Per the message, please show the output of `gem install` but also `gem env`.

**Comment by mixturez** [comment]
Hi, 

I am also having the same issue 

gem install ('1.0.0')
==========
gem install metasploit-concern -v '1.0.0'
Successfully installed metasploit-concern-1.0.0
Parsing documentation for metasploit-concern-1.0.0
Done installing documentation for metasploit-concern after 0 seconds
1 gem installed


bundle install 
==============

Errno::EACCES: Permission denied @ rb_sysopen - metasploit-framework-4.11.4.gem
An error occurred while installing metasploit-framework (4.11.4), and Bundler
cannot continue.
Make sure that `gem install metasploit-framework -v '4.11.4'` succeeds before
bundling.

gem install (4.11.4)
=================
ERROR:  Could not find a valid gem 'metasploit-framework' (= 4.11.4) in any repository
ERROR:  Possible alternatives: genesis_framework, import_framework, magellan-framework, metasploit-concern, metasploit-erd


gem env 
=======
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.5
  - RUBY VERSION: 2.2.0 (2014-12-25 patchlevel 0) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/iskaba/.rvm/gems/ruby-2.2.0
  - RUBY EXECUTABLE: /home/iskaba/.rvm/rubies/ruby-2.2.0/bin/ruby
  - EXECUTABLE DIRECTORY: /home/iskaba/.rvm/gems/ruby-2.2.0/bin
  - SPEC CACHE DIRECTORY: /home/iskaba/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/iskaba/.rvm/rubies/ruby-2.2.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/iskaba/.rvm/gems/ruby-2.2.0
     - /home/iskaba/.rvm/gems/ruby-2.2.0@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/iskaba/.gvm/groovy/current/bin
      ......................
     - /home/iskaba/.rvm/gems/ruby-2.2.0/bin
     - /home/iskaba/.rvm/gems/ruby-2.2.0@global/bin
     - /home/iskaba/.rvm/rubies/ruby-2.2.0/bin
     - /home/iskaba/.rvm/bin

I also tried with a normal & root account still the same issue. Please can you point me in the right direction in finding the solution.

**Comment by djberg96** [comment]
metasploit-concern doesn't even have a .gemspec file. How was this gem created? It doesn't appear that there is any metasploit-framework gem. Perhaps it was yanked?

**Comment by drbrain** [comment]
Maybe metasploit-framework's install problem should be opened as a bundler issue?

**Comment by djberg96** [comment]
Here's the gemspec:

https://github.com/rapid7/metasploit-concern/blob/master/metasploit-concern.gemspec

What's "rails_version_constraints" ?

I don't think this is a rubygems issue.

**Comment by Abdulaziz959** [comment]
i have a problem with metasploit-concern-1.0.0 when i try to install it i got this msg:

ERROR:  Could not find a valid gem 'metasploit-concern-1.0.0' (>= 0) in any repository
