### ISSUE TITLE
Getting SSL Certificate Issue When I upgraded my ruby to version 2.0,0

### ISSUE THREAD

**Issue by vgr787878** [rubygems/rubygems#1336]
Hi Guys,

I am getting below error when I upgraded Ruby version to 2.0.0.Can some one suggest me what was issue.

Error Message :
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol

**Comment by drbrain** [comment]
You probably need to upgrade your OpenSSL library then rebuild ruby.  https://rubygems.org no longer supports SSLv3 or earlier as the protocol is broken.

**Comment by bronzdoc** [comment]
@vgr787878 is this still an issue for you after drbrain suggestion?
