### ISSUE TITLE
.gemrc sources used without deduplication

### ISSUE THREAD

**Issue by Zapotek** [rubygems/rubygems#1338]
Sources defined in `~/.gemrc` don't seem to be deduplicated, leading to behavior which can be confusing.

In my case, for unknown reasons, `~/.gemrc` had about a hundred `http://rubygems.org/` entries listed in `:sources` and one entry for `https://rubygems.org/`.

The above introduced a large amount of latency during installs, due to seemingly identical requests:
```
$ gem install capybara-webkit -v '1.4.1' --verbose
HEAD http://api.rubygems.org/api/v1/dependencies
200 OK
[repeat about 100 times]
GET http://api.rubygems.org/api/v1/dependencies?gems=capybara-webkit
200 OK
[repeat about 100 times]
GET http://api.rubygems.org/api/v1/dependencies?gems=mime-types,nokogiri,rack,rack-test,xpath
200 OK
[repeat about 100 times]
```

So, keep an eye out for something that may add identical entries to the sources automatically, during updates perhaps. And for good measure, deduplicate the entries prior to using them.

**Comment by Zapotek** [comment]
As it turns out, the large number of identical sources was due to a setup script of mine, meant to remove the default HTTPS one and add HTTP.
I wasn't expecting the sources to be added blindly though, resulting in duplicates.

Maybe revisit that behavior?

**Comment by segiddins** [comment]
If that change is desired,  the following patch should do the trick

```diff
diff --git a/lib/rubygems/source_list.rb b/lib/rubygems/source_list.rb
index e01f11c..896efd0 100644
--- a/lib/rubygems/source_list.rb
+++ b/lib/rubygems/source_list.rb
@@ -58,7 +58,7 @@ class Gem::SourceList
             Gem::Source.new(URI.parse(obj))
           end
 
-    @sources << src
+    @sources << src unless @sources.include?(src)
     src
   end
 ```
