### ISSUE TITLE
ERROR:  While executing gem ... (Errno::ECONNREFUSED)     Connection refused - recvfrom(2)

### ISSUE THREAD

**Issue by HurtleHD** [rubygems/rubygems#1345]
Can someone help me fix this Issue 

gem install bundler
ERROR:  While executing gem ... (Errno::ECONNREFUSED)
    Connection refused - recvfrom(2)

**Comment by djberg96** [comment]
Are you still seeing this? Can you paste the output of "gem env" please? Any other information about your environment (particularly firewalls) you can provide?
