### ISSUE TITLE
ERROR:  Error installing ffi-1.9.8.gem: ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by JustGr00ve** [rubygems/rubygems#1346]
![fii](https://cloud.githubusercontent.com/assets/11280701/10091058/86ab5d72-6304-11e5-8a6b-2e166411cbd8.png)

Jeffreys-iPad:/private/var root# gem install --force --local ffi-1.9.8.gem
Building native extensions.  This could take a while...
ERROR:  Error installing ffi-1.9.8.gem:
        ERROR: Failed to build gem native extension.

    /usr/local/bin/ruby -r ./siteconf20150924-2268-oql2z6.rb extconf.rb
checking for ffi.h... *** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary libraries and/or headers.  Check the mkmf.log file for more
details.  You may need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/usr/local/bin/ruby
        --with-ffi_c-dir
        --without-ffi_c-dir
        --with-ffi_c-include
        --without-ffi_c-include=${ffi_c-dir}/include
        --with-ffi_c-lib
        --without-ffi_c-lib=${ffi_c-dir}/lib
        --with-libffi-config
        --without-libffi-config
        --with-pkg-config
        --without-pkg-config
/usr/local/lib/ruby/1.9.1/mkmf.rb:368:in `try_do': The complier failed to generate an executable file. (RuntimeError)
You have to install development tools first.
        from /usr/local/lib/ruby/1.9.1/mkmf.rb:452:in `try_cpp'
        from /usr/local/lib/ruby/1.9.1/mkmf.rb:834:in `block in have_header'
        from /usr/local/lib/ruby/1.9.1/mkmf.rb:693:in `block in checking_for'
        from /usr/local/lib/ruby/1.9.1/mkmf.rb:280:in `block (2 levels) in postpone'
        from /usr/local/lib/ruby/1.9.1/mkmf.rb:254:in `open'
        from /usr/local/lib/ruby/1.9.1/mkmf.rb:280:in `block in postpone'
        from /usr/local/lib/ruby/1.9.1/mkmf.rb:254:in `open'
        from /usr/local/lib/ruby/1.9.1/mkmf.rb:276:in `postpone'
        from /usr/local/lib/ruby/1.9.1/mkmf.rb:692:in `checking_for'
        from /usr/local/lib/ruby/1.9.1/mkmf.rb:833:in `have_header'
        from extconf.rb:16:in `<main>'

extconf failed, exit code 1

Gem files will remain installed in /usr/local/lib/ruby/gems/1.9.1/gems/ffi-1.9.8 for inspection.
Results logged to /usr/local/lib/ruby/gems/1.9.1/extensions/-darwin-10/1.9.1-static/ffi-1.9.8/gem_make.out

**Comment by segiddins** [comment]
The error message says `You have to install development tools first`. Are you sure you've installed developer tools?

**Comment by JustGr00ve** [comment]
@segiddins Where can i find this developer tools?

**Comment by segiddins** [comment]
@JustGr00ve it depends on the platform you use, but you need to have stuff like a compiler available on the `PATH`
