### ISSUE TITLE
`alias add_dependency add_runtime_dependency`

### ISSUE THREAD

**Issue by bf4** [rubygems/rubygems#1349]
Is there a preferred method to use in the gemspec? [`alias add_dependency add_runtime_dependency`](https://github.com/rubygems/rubygems/blob/6169822a17596a72098e1a30eb28bf6b19466c6c/lib/rubygems/specification.rb#L1497) leads me to believe it would be `add_runtime_dependency`, which I prefer because it is more explicit, but most gems use `add_dependency`, in part because [that is what Rails uses and use in its templates](https://github.com/rails/rails/blob/3e36db4406beea32772b1db1e9a16cc1e8aea14c/railties/lib/rails/generators/rails/plugin/templates/%25name%25.gemspec#L22).

Any thoughts as to direction or just up to taste?

**Comment by drbrain** [comment]
There's no preference from RubyGems' standpoint.

When development dependencies were added the alias was added to allow for some symmetry.

There's no plan to remove add_dependency, I think it would be impossible to deprecate.

**Comment by duckinator** [comment]
Closing since this question has been answered (the two methods are considered equivalent by RubyGems), and no further action needs to be taken.
