### ISSUE TITLE
Command name change for uninstalling gem

### ISSUE THREAD

**Issue by kulbida** [rubygems/rubygems#1351]
I would love to suggest to change the command to unnstall, unistall, damn... `uninstall` the gem.
The suggestion is to change the command to be `remove`, which is easier to write and it still self explanatory.
So instead of
```bash
gem uninstall <gem_name>
```
use
```bash
gem remove <gem_name>
```

**Comment by drbrain** [comment]
RubyGems allows you to use the shortest unambiguous prefix for command names so `gem uni` works as well.

We can't change the command name and I'm unsure about an alias.

**Comment by kulbida** [comment]
alright, let it be `uni`. `rem` would still be more accurate though. :)
