### ISSUE TITLE
rubygems fails with 'gem help --help'

### ISSUE THREAD

**Issue by bogem** [rubygems/rubygems#1352]
rubygems fails with 'gem help --help'
![2015-10-04 20 51 25](https://cloud.githubusercontent.com/assets/13235519/10269507/0fbad656-6ada-11e5-9ade-9bc0c65ff1f0.png)

**Comment by djberg96** [comment]
Confirmed with 2.4.8.

**Comment by djberg96** [comment]
The immediate problem is in command_manager.rb, line 122. However, we should probably solve this within the command line parser.

**Comment by djberg96** [comment]
Fixed by PR #1357

**Comment by djberg96** [comment]
Thank you for the report!
