### ISSUE TITLE
"gem" calls slow subsequent requires to stdlib

### ISSUE THREAD

**Issue by HoneyryderChuck** [rubygems/rubygems#1358]
Running in a system with GlusterFS setup, we're experiencing very slow performance in scripts which only load ruby libraries. The scripts belong to a gem with a fair amount of dependencies, and are installed in the system and available to all users, which means, rubygems has to parse all of the gemspecs available.  Every subsequent call to the my "test" script will load the gem (let's call it 'ruby-test'):

``` ruby
# possible binstub for my test script
require 'rubygems'
...
gem 'ruby-test', version
load Gem.bin('ruby-test', 'test', version)
```

my script only has the following:

``` ruby
!#/usr/bin/env ruby
require 'abbrev'
puts "test"
```

The "problem" seems to be the "gem" call in the bin stub. This will load all dependencies in my gem's gemspec and prepend them to `$LOAD_PATH`, which means, every subsequent require will first be looked up in the dependencies tree before reaching the ruby stdlib, and that represents a performance penalty for requiring 'abbrev', because I cannot control the my dependency trees. ruby itself doesn't have a huge amount of internal libraries, which should make lookups very fast. 

This seems to be the "culprit":

https://github.com/rubygems/rubygems/blob/c18805ca48f533fbde40025df41a8f817cd6ff48/lib/rubygems.rb#L575-L587

This method returns 0, which means, calls to `gem` will effectively prepend the gem paths in `$LOAD_PATH`.

Now, I don't know if this is a "bug", or just the way rubygems is designed, with the assumption that all gem executables require all dependencies. But this decision increases exponentially the number of `lstat`and `stat` syscalls, which is noticeably even worse when a distributed file system is involved. 

Wouldn't it be best do "prepend" dependencies after the ruby stdlib paths?

Using Rubygems 2.4.7

**Comment by TiagoCardoso1983** [comment]
Just for result sake:

```bash
>  strace -o test2.dump ruby -e "puts $:.length ; require 'abbrev'"
8
> cat test1.dump| grep lstat | wc -l
166
>  strace -o test2.dump ruby -e "require 'thegemimeant' ; puts $:.length ; require 'abbrev'"
49
>  cat test2.dump| grep lstat | wc -l
526
```

**Comment by segiddins** [comment]
I believe this might be one of the things @tenderlove has optimized on master, could you see if master is any faster? If not, providing a script that can be used to test against would be ace.

**Comment by TiagoCardoso1983** [comment]
I will see about testing this in master. As for providing a script, that's what I just did above, right?

**Comment by TiagoCardoso1983** [comment]
Results with master:

```
> strace -o test1.dump ruby --disable-gems -I./lib -e "require 'rubygems'; puts $:.length ; require 'abbrev'"
9 
> cat test1.dump| grep stat | wc -l
295
> strace -o test2.dump ruby --disable-gems -I./lib -e "require 'rubygems'; require 'thegemimeant' ; puts $:.length ; require 'abbrev'"
50
> cat test2.dump | grep stat | wc -l
8696
```

there was an improvement, as the difference in raw numbers seems to be the additional rubygems require call:

```
# with 2.4.7
> strace -o test1.dump ruby -e "require 'rubygems'; puts $:.length ; require 'abbrev'"
8
> cat test1.dump| grep stat | wc -l
336
> strace -o test2.dump ruby -e "require 'rubygems'; require 'thegemimeant' ; puts $:.length ; require 'abbrev'"
49
> cat test2.dump | grep stat | wc -l
12925
```

My conclusion is: there will be in the end a performance improvement (a massive one), but I don't think that the described error will be "resolved" (if we indeed perceive it as a "bug"). I read the test2.dump from the rubygems master example, and I saw that the abbrev.rb/so lookup will always start by the dependencies before arriving at the stdlibs from ruby:

```
....
# first 'stat' reference of abbrev
stat("/opt/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/gems/akami-1.3.0/lib/abbrev", 0x7fffdff0bf50) = -1 ENOENT (No such file or directory)
stat("/opt/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/gems/akami-1.3.0/lib/abbrev.rb", 0x7fffdff0c030) = -1 ENOENT (No such file or directory)
stat("/opt/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/gems/akami-1.3.0/lib/abbrev.so", 0x7fffdff0c030) = -1 ENOENT (No such file or directory)
stat("/opt/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/gems/builder-3.2.2/lib/abbrev", 0x7fffdff0c1f0) = -1 ENOENT (No such file or directory)
stat("/opt/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/gems/builder-3.2.2/lib/abbrev.rb", 0x7fffdff0c1f0) = -1 ENOENT (No such file or directory)
stat("/opt/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/gems/builder-3.2.2/lib/abbrev.so", 0x7fffdff0c1f0) = -1 ENOENT (No such file or directory)
....
# last 'stat' reference of abbrev
stat("/opt/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/gems/sequel-4.20.0/lib/abbrev", 0x7fffdff0c200) = -1 ENOENT (No such file or directory)
stat("/opt/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/gems/sequel-4.20.0/lib/abbrev.rb", 0x7fffdff0c200) = -1 ENOENT (No such file or directory)
stat("/opt/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/gems/sequel-4.20.0/lib/abbrev.so", 0x7fffdff0c200) = -1 ENOENT (No such file or directory)
.... 
# first 'open' reference to abbrev
open("/home/rubygems/lib/abbrev.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/gems/noc-db-0.1.4/lib/abbrev.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/gems/mime-types-1.25.1/lib/abbrev.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/gems/mail-2.6.3/lib/abbrev.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/gems/noc-mail-0.0.9/lib/abbrev.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
...
# last 'open' reference to abbrev
open("/opt/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/gems/sptsoap-4.0.8/lib/abbrev.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/rubies/ruby-2.0.0-p576/lib/ruby/gems/2.0.0/gems/thegemimeant-0.2.3/lib/abbrev.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/rubies/ruby-2.0.0-p576/lib/ruby/site_ruby/2.0.0/abbrev.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/rubies/ruby-2.0.0-p576/lib/ruby/site_ruby/2.0.0/x86_64-linux/abbrev.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/rubies/ruby-2.0.0-p576/lib/ruby/site_ruby/abbrev.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/rubies/ruby-2.0.0-p576/lib/ruby/vendor_ruby/2.0.0/abbrev.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/rubies/ruby-2.0.0-p576/lib/ruby/vendor_ruby/2.0.0/x86_64-linux/abbrev.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/rubies/ruby-2.0.0-p576/lib/ruby/vendor_ruby/abbrev.rb", O_RDONLY|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/rubies/ruby-2.0.0-p576/lib/ruby/2.0.0/abbrev.rb", O_RDONLY|O_CLOEXEC) = 7
```

My conclusion is, the code for lookups hasn't changed in the upstream, i.e. the additional gem paths are always appended to the beginning of the ```$LOAD_PATH```

**Comment by tenderlove** [comment]
@TiagoCardoso1983 we can't add paths after stdlib because some code in stdlib is packaged as a gem.  For example, `psych` is a gem and is also distributed as part of stdlib.  If we put the gem activations *after* stdlib, then users that install a newer version of psych will not get the version when they do the require.

We could come up with a cache on Ruby install that knows what gems are stdlib or not and make exceptions for those, but the current behavior has a purpose.

**Comment by TiagoCardoso1983** [comment]
@tenderlove but when I require psych, it doesn't add any new directory to the $LOAD_PATH. Surely rubygems already infers that the file to require can be found within the directories in $LOAD_PATH, right? I mean, I do not see any change:

```ruby
irb(main):005:0> $LOAD_PATH
=> ["/opt/rubies/ruby-2.0.0-p645/lib/ruby/site_ruby/2.0.0", "/opt/rubies/ruby-2.0.0-p645/lib/ruby/site_ruby/2.0.0/x86_64-linux", "/opt/rubies/ruby-2.0.0-p645/lib/ruby/site_ruby", "/opt/rubies/ruby-2.0.0-p645/lib/ruby/vendor_ruby/2.0.0", 
"/opt/rubies/ruby-2.0.0-p645/lib/ruby/vendor_ruby/2.0.0/x86_64-linux", "/opt/rubies/ruby-2.0.0-p645/lib/ruby/vendor_ruby", "/opt/rubies/ruby-2.0.0-p645/lib/ruby/2.0.0", "/opt/rubies/ruby-2.0.0-p645/lib/ruby/2.0.0/x86_64-linux"]
irb(main):006:0> gem 'psych'
=> true
irb(main):007:0> $LOAD_PATH
=> ["/opt/rubies/ruby-2.0.0-p645/lib/ruby/site_ruby/2.0.0", "/opt/rubies/ruby-2.0.0-p645/lib/ruby/site_ruby/2.0.0/x86_64-linux", "/opt/rubies/ruby-2.0.0-p645/lib/ruby/site_ruby", "/opt/rubies/ruby-2.0.0-p645/lib/ruby/vendor_ruby/2.0.0", 
"/opt/rubies/ruby-2.0.0-p645/lib/ruby/vendor_ruby/2.0.0/x86_64-linux", "/opt/rubies/ruby-2.0.0-p645/lib/ruby/vendor_ruby", "/opt/rubies/ruby-2.0.0-p645/lib/ruby/2.0.0", "/opt/rubies/ruby-2.0.0-p645/lib/ruby/2.0.0/x86_64-linux"]
irb(main):008:0> require 'psych'
=> true
irb(main):009:0> $LOAD_PATH
=> ["/opt/rubies/ruby-2.0.0-p645/lib/ruby/site_ruby/2.0.0", "/opt/rubies/ruby-2.0.0-p645/lib/ruby/site_ruby/2.0.0/x86_64-linux", "/opt/rubies/ruby-2.0.0-p645/lib/ruby/site_ruby", "/opt/rubies/ruby-2.0.0-p645/lib/ruby/vendor_ruby/2.0.0", 
"/opt/rubies/ruby-2.0.0-p645/lib/ruby/vendor_ruby/2.0.0/x86_64-linux", "/opt/rubies/ruby-2.0.0-p645/lib/ruby/vendor_ruby", "/opt/rubies/ruby-2.0.0-p645/lib/ruby/2.0.0", "/opt/rubies/ruby-2.0.0-p645/lib/ruby/2.0.0/x86_64-linux"]
```

My point is, if requiring the gem has to insert some new path, then one could assume that it is not distributed with the stdlib and should therefore be appended after the stdlib paths. Or is there something in my missing in this process?

**Comment by tenderlove** [comment]
> but when I require psych, it doesn't add any new directory to the $LOAD_PATH

It sounds like you may not have the psych gem installed.  I have it installed, so when I require "psych" it gets added to the load path:

```
[aaron@TC ~]$ ruby -e'x = $LOAD_PATH.dup; require "psych"; p $LOAD_PATH - x'
["/Users/aaron/.rbenv/versions/ruby-trunk/lib/ruby/gems/2.3.0/gems/psych-2.0.15/lib", "/Users/aaron/.rbenv/versions/ruby-trunk/lib/ruby/gems/2.3.0/extensions/x86_64-darwin-15/2.3.0-static/psych-2.0.15"]
[aaron@TC ~]$
```

> Surely rubygems already infers that the file to require can be found within the directories in $LOAD_PATH, right?

No, it does not.  Rubygems doesn't know how to search the load path for requireable files, it [leverages Ruby's built-in require](https://github.com/rubygems/rubygems/blob/b6f3b5fac7ec01e5dcc57d6768a7e9b456feaea8/lib/rubygems/core_ext/kernel_require.rb#L54) (`gem_original_require` is an alias of the `require` method built in to Ruby).  If Ruby's `require` can't find the file after searching the load path, it raises an exception, [rubygems catches the exception, then the gem is activated and put on the load path, and Ruby's `require` is called again](https://github.com/rubygems/rubygems/blob/b6f3b5fac7ec01e5dcc57d6768a7e9b456feaea8/lib/rubygems/core_ext/kernel_require.rb#L123-L128).

Since default gems need to be inserted before stdlib, [there's a special cache that keeps track of them](https://github.com/rubygems/rubygems/blob/b6f3b5fac7ec01e5dcc57d6768a7e9b456feaea8/lib/rubygems.rb#L1115-L1142), and they're [found here](https://github.com/rubygems/rubygems/blob/b6f3b5fac7ec01e5dcc57d6768a7e9b456feaea8/lib/rubygems/core_ext/kernel_require.rb#L43-L47).

Default gems definitely need to be pushed to the front of the list.  Though, now that I'm typing all this out, I can't think of a reason why we couldn't have two cursors in to the list.  We already have to have a way to differentiate default gems from regular gems, so I don't see why we couldn't push default gems to the front of the list and just append all others.

/cc @matthewd

**Comment by TiagoCardoso1983** [comment]
me neither, and that's a start :-) I just wanted to report the issue to state that require might not scale properly to many gems in a sub-standard distributed file system. how and where it can be solved, that's another question. About the psych issue, good catch. I got confused with the true value as response, I was somewhat under the impression it was there indeed.

**Comment by bronzdoc** [comment]
We’re going to close this because it is so old, but if this problem is still happening with the latest version of RubyGems please feel free to let us know with a new issue!”
