### ISSUE TITLE
gem uninstall -f should remove items outside of GEM_HOME

### ISSUE THREAD

**Issue by telemachus** [rubygems/rubygems#136]
Using rvm with gemsets, I've recently run into semi-regular cases where I have a hard time removing gems because of the difference between `GEM_HOME` and where the gem is installed (often in rvm's `@global` gemset). One example is here: https://gist.github.com/1101675 

Drbrain [suggested in irc](https://gist.github.com/1101967) that `gem uninstall -f` might help out by removing gems no matter where they're installed.

**Comment by krainboltgreene** [comment]
Is this even a problem anymore @mpapis?

**Comment by indirect** [comment]
rubygems currently suggests running gem uninstall with the full path to the gem in question--I would consider this solved by that

**Comment by krainboltgreene** [comment]
Agreed.
