### ISSUE TITLE
Unresolved specs during Gem::Specification.reset:

### ISSUE THREAD

**Issue by pironim** [rubygems/rubygems#1360]
I constantly get warning from subject when do bundle install on rails project.
we use jruby-1.7.16.1
```
$ bundle install
WARN: Unresolved specs during Gem::Specification.reset:
      ffi (>= 0)
WARN: Clearing out unresolved specs.
Please report a bug if this causes problems.
Using rake 10.1.1
.....
```

I grep a little bit and find where it comes from
```
$ grep -ri 'Clearing out unresolved specs' ./
./versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:      warn "#{w}: Clearing out unresolved specs."
./versions/jruby-1.7.16.1/lib/ruby/shared/rubygems/specification.rb:      warn "#{w}: Clearing out unresolved specs."
✔ ~/.rbenv [master|✔] 
$ grep -ri 'Unresolved specs during Gem::Specification.reset' ./
./versions/2.2.2/lib/ruby/2.2.0/rubygems/specification.rb:      warn "#{w}: Unresolved specs during Gem::Specification.reset:"
./versions/jruby-1.7.16.1/lib/ruby/shared/rubygems/specification.rb:      warn "#{w}: Unresolved specs during Gem::Specification.reset:"
```

guys with rvm and rbenv has the same problem 
and this error appear even with latest rubygems version

gem --version
2.4.8

looks like this gem cause this issue https://github.com/headius/spoon/blob/master/spoon.gemspec
because only here we have ffi without version.

**Comment by pironim** [comment]
I remove pry which has spoon as dependency and it does not help :(

**Comment by djberg96** [comment]
@pironim Does it go away if you upgrade to JRuby 1.7.20 or JRuby 9k?

I was able to run "gem install spoon" with both versions without issue, but I haven't tried bundler.

**Comment by pironim** [comment]
@djberg96 can't reproduce it on JRuby 1.7.20 .. is there any way to fix it without upgrade ? I have prawn gem which does not work on 1.7.20

**Comment by djberg96** [comment]
@pironim The latest 1.7 branch is actually 1.7.22. Does that work with Prawn?

**Comment by pironim** [comment]
@djberg96 Sorry for bothering you. I finally got where it comes from
it's definitely Pry gem
this repo has all code to reproduce the problem https://github.com/pironim/PryAndJrubyIssue
I need to open issue in pry Repository

**Comment by djberg96** [comment]
Ok, chalking it up to a JRuby issue then. Closing.
