### ISSUE TITLE
Possible incorrect result for latest version API?

### ISSUE THREAD

**Issue by swatosh** [rubygems/rubygems#1365]
For example: https://rubygems.org/api/v1/versions/win32-api/latest.json returns {"version":"1.4.8"}

But reading through the output of https://rubygems.org/api/v1/versions/win32-api.json makes it look like the latest version is 1.5.3. Also looking at https://rubygems.org/gems/win32-api there is 1.4.8 at the top of the page, but the versions list starts with 1.5.3.

https://rubygems.org/api/v1/gems/win32-api.json also says 1.4.8.

Is there some other way of invoking the latest version API that would give 1.5.3 (which appears to be the correct answer)? Maybe 1.4.8 is the last Ruby architecture version?

Thanks for any insights

--
Joe

**Comment by segiddins** [comment]
This seems like an issue for rubygems.org, not rubygems.

**Comment by swatosh** [comment]
Looks like I misread http://help.rubygems.org/! Thanks, and sorry for the noise.
