### ISSUE TITLE
Issue with gem mirror with recent update

### ISSUE THREAD

**Issue by vandita31** [rubygems/rubygems#1366]
Hi ,

We are currently facing issues with updating gems using gem mirror after an update today.

This are the steps taken 

This is what the directory currently has -
[root@atlassync-wc-1d gems]# ls
gems              latest_specs.4.8.gz  Marshal.4.8.Z         prerelease_specs.4.8.gz  specs.4.8     yaml
latest_specs.4.8  Marshal.4.8          prerelease_specs.4.8  quick                    specs.4.8.gz  yaml.Z

After deleting the "gems" directory , i ran the command again but it gave no update to the "gems" directory

[root@atlassync-wc-1d gems]#  /app/interpreters/ruby/1.9.3/bin/gem mirror
Fetching: http://rubygems.org/specs.4.8.gz with 10 threads
Total gems: 628391
Fetching 628390 gems
Fetching yaml...[Done]
Fetching yaml.Z...[Done]
Fetching latest_specs.4.8...[Done]
Fetching latest_specs.4.8.gz...[Done]
Fetching Marshal.4.8...[Done]
Fetching Marshal.4.8.Z...[Done]
Fetching prerelease_specs.4.8...[Done]
Fetching prerelease_specs.4.8.gz...[Done]
Fetching specs.4.8...[Done]
Fetching specs.4.8.gz...[Done]

----------------------------------------------------------------------------------------------------
0 Gems need to updateDeleting 0 gems

Could someone look into this issue at the earliest ? This is currently impacting many of our internal applications.

Thanks!

**Comment by drbrain** [comment]
Using [geminabox](https://github.com/geminabox/geminabox) is the current best-practice for setting up a gem mirror as it uses a pass-through proxy to fetch gems from rubygems.org as-needed.
