### ISSUE TITLE
git:// scheme is not supported in source code URL

### ISSUE THREAD

**Issue by ogryb** [rubygems/rubygems#1368]
I'm trying to update a source code URL in my project, but am getting "Invalid URL" valid for the the following URL:

git://git.code.sf.net/p/b-scan/trunk

Please make git:// scheme valid

**Comment by indirect** [comment]
Hello! Thank you for reporting this issue. Unfortunately, this isn't enough information for us to reproduce your problem. Please follow the steps in [ISSUES](https://github.com/bundler/bundler/blob/master/ISSUES.md), and provide the information requested there if your problem is still unsolved.

**Comment by indirect** [comment]
Whoa, I totally misread which project this was! :grimacing: Sorry about that! Please use [Bundler](https://github.com/bundler/bundler) instead. It supports git URLs for sources.

**Comment by ogryb** [comment]
Andre,

Thanks for the quick response. This is actually about rubygems.org UI.

How to reproduce:

1. Login to rubygems.org
2. Go to your gem project
3. Select Edit
4. Try to enter git:// URL to the Source Code field.

Sorry for breivity. Typing from phone.
Oleg

**Comment by ogryb** [comment]
Andre,

Thanks for the quick response. This is actually about rubygems.org UI.

How to reproduce:

1. Login to rubygems.org
2. Go to your gem project
3. Select Edit
4. Try to enter git:// URL to the Source Code field.


Oleg

**Comment by indirect** [comment]
Got it. There's a separate tracker for rubygems.org at rubygems/rubygems.org where you can file tickets for the website.
