### ISSUE TITLE
Installing the qtbindings/nokogiri gem on 64-bit Windows fails starting with rubygems 2.5.0

### ISSUE THREAD

**Issue by ryanatball** [rubygems/rubygems#1369]
#Rubygems 2.5.0
gem install qtbindings # fail
gem install nokogiri # tries to build

#Rubygems 2.4.8
gem install qtbindings # success
gem install nokogiri # success without trying to build

Note: Only broken for the 64-bit version of the gem/ruby (x64-mingw32). 

Installs fine for the 32-bit version of the gem/ruby (x86-mingw32)

**Comment by ryanatball** [comment]
Note: Only broken for the 64-bit version of the gem/ruby (x64-mingw32).   Installs fine for the 32-bit version of the gem/ruby (x86-mingw32)

**Comment by ryanatball** [comment]
@tenderlove Can you help with this?

**Comment by jmthomas** [comment]
Could this be related to the new use of the Molinillo gem as the resolver library?

**Comment by tenderlove** [comment]
It sounds like the installer isn't selecting the right platform.  Do you get the same error if you to `Gem.install("nokogiri")` from irb?  If so, that might be an easier place to start debugging.  I don't have a windows machine to test on right now, but I can help walk you through debugging.

@jmthomas it's possible.  Also I think the new resolver library is embedded in RG, so maybe it needs to be updated?

**Comment by ryanatball** [comment]
```
irb(main):001:0> Gem.install("nokogiri")
Gem::InstallError: The 'nokogiri' native gem requires installed build tools.

Please update your PATH to include build tools or download the DevKit
from 'http://rubyinstaller.org/downloads' and follow the instructions
at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'

        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/defaults/operating_system.rb:12:in `rescue in block in <top (required)>'
        from C:/Ruby22-x64/lib/ruby/2.2.0/rubygems/defaults/operating_system.rb:4:in `block in <top (required)>'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:315:in `call'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:315:in `block in run_pre_install_hooks'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:314:in `each'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:314:in `run_pre_install_hooks'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/installer.rb:275:in `install'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:166:in `block in install'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:150:in `each'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/request_set.rb:150:in `install'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems/dependency_installer.rb:404:in `install'
        from C:/Ruby22-x64/lib/ruby/site_ruby/2.2.0/rubygems.rb:555:in `install'
        from (irb):1
        from C:/Ruby22-x64/bin/irb:11:in `<main>'
```

**Comment by ryanatball** [comment]
@tenderlove Same error in irb.  I added the stack trace above.

**Comment by tenderlove** [comment]
Shot in the dark, but can you see what this script will output on 2.4.8 vs 2.5.0?

```ruby
require 'rubygems'
require 'rubygems/dependency_installer'

installer = Gem::DependencyInstaller.new
rs = installer.resolve_dependencies 'nokogiri', Gem::Requirement.default
rs.sorted_requests.each do |req|
  p req.spec.spec
end
```

**Comment by ryanatball** [comment]
```
#Rubygems 2.5.0
#<Gem::Specification:0x4e37d4 mini_portile-0.6.2>
#<Gem::Specification:0x19d03f4 nokogiri-1.6.6.2>

# Rubygems 2.4.8
#<Gem::Specification:0x16e9690 mini_portile-0.6.2>
#<Gem::Specification:0x162315c nokogiri-1.6.6.2-x64-mingw32>
```

**Comment by tenderlove** [comment]
Are you able to run against rubygems from git?  It should be a simple git bisect now, I think.  We just need to find where that behavior diverged.

**Comment by ryanatball** [comment]
```
C:\git\rubygems>git checkout 2fec00f
Previous HEAD position was f230215... Merge pull request #1298 from segiddins/seg-test-warnings
HEAD is now at 2fec00f... Get rid of warnings in the tests

C:\git\rubygems>ruby -I lib bin/gem install nokogiri
Nokogiri is built with the packaged libraries: libxml2-2.9.2, libxslt-1.1.28, zlib-1.2.8, libiconv-1.14.
Successfully installed nokogiri-1.6.6.2-x64-mingw32
Parsing documentation for nokogiri-1.6.6.2-x64-mingw32
Done installing documentation for nokogiri after 1 seconds
1 gem installed

C:\git\rubygems>git checkout e3088dd
Previous HEAD position was 2fec00f... Get rid of warnings in the tests
HEAD is now at e3088dd... Merge pull request #1189 from segiddins/seg-molinillo

C:\git\rubygems>ruby -I lib bin/gem install nokogiri
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ rb_sysopen - /dev/null

# Same /dev/null error for f230215, 67bf21e, c202db2

C:\git\rubygems>git checkout 87475e8
Previous HEAD position was c202db2... bump developmnet version to 2.5.0
HEAD is now at 87475e8... backport r51095 and 51096 from ruby/ruby trunk

C:\git\rubygems>ruby -I lib bin/gem install nokogiri
ERROR:  Error installing nokogiri:
        The 'nokogiri' native gem requires installed build tools.

Please update your PATH to include build tools or download the DevKit
from 'http://rubyinstaller.org/downloads' and follow the instructions
at 'http://github.com/oneclick/rubyinstaller/wiki/Development-Kit'

```

**Comment by ryanatball** [comment]
Bringing in molinillo seems to be the culprit at e3088dd.

**Comment by tenderlove** [comment]
@ryanatball awesome, thanks for tracking that down. @segiddins have you seen this issue before? Does RG need molinillo to be updated?

**Comment by segiddins** [comment]
I'll try and throw together a test case, but I doubt it's anything molinillo-specific. The rubygems resolver code is probably not handling something related to platforms correctly.

**Comment by fivetanley** [comment]
@tenderlove I have 64-bit windows like you asked for on Twitter, but I'm not sure how to test the change @ryanatball made.

**Comment by tenderlove** [comment]
@fivetanley we don't have a fix yet.  It seems like we need to figure out a test case.  Essentially [the script I made here](https://github.com/rubygems/rubygems/issues/1369#issuecomment-153803653) will reproduce the bug on 64bit windows.  @ryanatball tracked down the regression to e3088dd.  Unfortunately it's a pretty large commit, so I can't easily point at the bug.  If we could get a test case for RG, I could track down the issue.

**Comment by segiddins** [comment]
I'm happy to investigate this in the resolver if someone can come up with a test case I can run, not having a windows box myself.

**Comment by drbrain** [comment]
`ruby -Ilib bin/gem install -V --platform x64-mingw32 nokogiri` should allow you to reproduce this on any platform.

**Comment by segiddins** [comment]
Hm so it seems to me it's the pure ruby version that's being installed... Not sure why that's an issue, since RubyGems considers that a platform match?

**Comment by drbrain** [comment]
Platforms should be preferred over ruby-platform gems (because they'll be compiled, etc. exactly for your platform).

**Comment by segiddins** [comment]
Yeah, I see now that that code is already in there...
Can someone see if the following diff helps?

```diff
diff --git a/lib/rubygems/resolver.rb b/lib/rubygems/resolver.rb
index 44f717e..4c2974e 100644
--- a/lib/rubygems/resolver.rb
+++ b/lib/rubygems/resolver.rb
@@ -232,7 +232,7 @@ class Gem::Resolver
       exc.errors = @set.errors
       raise exc
     end
-    possibles.sort_by { |s| [s.source, s.version, s.platform == Gem::Platform.local.to_s ? 1 : 0] }.
+    possibles.sort_by { |s| [s.source, s.version, s.platform.to_s == Gem::Platform.local.to_s ? 1 : 0] }.
       map { |s| ActivationRequest.new s, dependency, [] }
   end
 
```

**Comment by segiddins** [comment]
Alternatively, try out this diff:

```diff
diff --git a/lib/rubygems/resolver.rb b/lib/rubygems/resolver.rb
index 44f717e..7e8ae9a 100644
--- a/lib/rubygems/resolver.rb
+++ b/lib/rubygems/resolver.rb
@@ -232,7 +232,7 @@ class Gem::Resolver
       exc.errors = @set.errors
       raise exc
     end
-    possibles.sort_by { |s| [s.source, s.version, s.platform == Gem::Platform.local.to_s ? 1 : 0] }.
+    possibles.sort_by { |s| [s.source, s.version, s.platform == Gem::Platform::RUBY ? -1 : 1] }.
       map { |s| ActivationRequest.new s, dependency, [] }
   end
```

**Comment by djberg96** [comment]
@segiddins Your first diff worked (.to_s) for me, the second did not.

**Comment by segiddins** [comment]
@djberg96 strange thing is, neither one breaks the existing test coverage for preferring platform specific gems.

**Comment by tenderlove** [comment]
@drbrain are you sure that's the right way to reproduce?  I tried the command against a git checkout and it successfully installed the `x64-mingw32` (precompiled) gem on my OS X machine.

@segiddins thanks for the patches!  Maybe I can back in to the issue from them! :D

**Comment by ryanatball** [comment]
I can confirm that the first patch works (s.platform.to_s) and the second patch does not.

**Comment by ryanatball** [comment]
Another note - nokogiri is broken on 32-bit windows as well.  I think qtbindings must just be getting lucky with the sorting on my system with 32-bit windows.

**Comment by segiddins** [comment]
Why is it that `APISpecification#platform` returns a `Gem::Platform` but a ``Gem::Specification` returns a `String`?

**Comment by drbrain** [comment]
@segiddins for historical reasons.  Gem::Specification#platform was originally a String and there was no Gem::Platform class.  For backward compatibility it still returns a String.

[Gem::Resolver::Specification](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/resolver/specification.rb) subclasses are not user-accessible and are only used for resolving a set of gems.  Since there is no relationship between them and Gem::Specification (beyond the representation of a "gem") the API can return different types.

Also, items under the Gem::Resolver namespace are considered RubyGems internals and are subject to change at whim.

**Comment by jmthomas** [comment]
Thanks for the quick resolution of this issue. Obviously the 2.5 release is broken (at least for Windows users) so a patch release is greatly appreciated.

**Comment by jlnr** [comment]
Is there a workaround to force RG to install a precompiled gem on Windows?
