### ISSUE TITLE
gem push failed, can't go back nor forward.

### ISSUE THREAD

**Issue by cjheath** [rubygems/rubygems#1372]
I have a problem with my gem activefacts-metamodel, which is a core gem on which a number of others rely.
All have just been republished as 1.8.0, but the activefacts-metamodel push seems to have partly failed.

As a result, I cannot push it again (409 Conflict; Repushing gem versions is not allowed)
but I can't yank it either (422 Unprocessable Entity; The version 1.8.0 has already been deleted).

Has anyone seen this behaviour before?
Can someone please fix this gem so I can avoid rolling all its friends to 1.8.1?
Or should I just bite the bullet and bump everything?

The source for this gem is at http://github.com/cjheath/activefacts-metamodel

Thanks for any assistance you can offer.

**Comment by tenderlove** [comment]
/cc @qrush 

I'm really sorry!  This sounds like a rubygems.org bug, but it's a very unfortunate position.  :(

**Comment by cjheath** [comment]
It happened less than 24 hours ago in case there are any logs that would help with a diagnosis.

**Comment by drbrain** [comment]
Since this is a rubygems.org operation issues please open a help request at http://help.rubygems.org, this tracker is only for issues with the rubygems client.

I suspect you will need to push a 1.8.1 version.

RubyGems.org policy is that when you yank a gem you can't push to that version again.  This prevents you from confusing your users by pushing versions with different features or bugs.

**Comment by qrush** [comment]
@dwradcliffe any chance we have logging setup yet so we can see what happened here?

**Comment by cjheath** [comment]
@qrush It's possible that @drbrain has it right; I may have pushed, did a gem install to verify, realised I had a missing documentation file so yanked and re-pushed. The error, if any, was that I didn't realise that the second push had failed. In any case, it would be excellent if a re-push was allowed for a few minutes; just enough leeway for the author to verify correct installation.

**Comment by qrush** [comment]
We talked about a window like that for a while but it gets kind of iffy.
You're not going to run out of version numbers any day soon. If we hear a
lot of this, we could reconsider that policy.

**Comment by cjheath** [comment]
I agree about "iffy" but the problem is the cascade of six dependent gems; I have to bump them all :( 15 minutes of leeway (or detecting that a gem hasn't been downloaded except from where it was pushed) would have avoided the problem.

Thanks, everyone, for your explanations and help.
