### ISSUE TITLE
Can add a log file, record some thing on gem running?

### ISSUE THREAD

**Issue by windwiny** [rubygems/rubygems#1374]
Can we add a log file, when gem command running,  record install/uninstall/update gem's name, time, operation, and install reason(manual or because dependency ) ?

**Comment by drbrain** [comment]
If someone made a pull request it would be accepted.

The log would need to be configurable through an entry in `~/.gemrc`

**Comment by krainboltgreene** [comment]
This should basically operate like `npm`'s debug log.

**Comment by bronzdoc** [comment]
No one else has requested this feature in 3 years, closing
