### ISSUE TITLE
ECONNRESET: gem install

### ISSUE THREAD

**Issue by chenjus** [rubygems/rubygems#1378]
get the following error while issuing gem install xxx. Can someone help resolve this ?

ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    Errno::ECONNRESET: An existing connection was forcibly closed by the remote
host. - SSL_connect (https://api.rubygems.org/quick/Marshal.4.8/rack-1.6.4.gemsp
ec.rz)

**Comment by tenderlove** [comment]
Is it still happening?

**Comment by dharamgollapudi** [comment]
@tenderlove I couldn't reproduce the issue.
Following are the steps followed:

```
gem update ---system
gem -v #2.5.0
gem install rack
gem list rack # rack (1.6.4)
gem uninstall rack

# tried with 2.4.8 as well
gem update --system
gem -v #2.4.8
gem install rack
gem list rack # rack (1.6.4)
gem uninstall rack

**Comment by belfare** [comment]
1386 looks like the same issues as well.

**Comment by Lexvum** [comment]
I had the same issue several times lately. If you are using a VPN, try switching servers.
