### ISSUE TITLE
Error while installing activerecord-jdbc-adapter

### ISSUE THREAD

**Issue by GrowFinsTurkey** [rubygems/rubygems#1379]
Hi,

I'm a beginner to coding and I'm attempting to set up a workstation using JRuby on Windows. I have PostgreSQL installed.

While attempting a "jruby -S bundle install --binstubs" I received the following error message:

Errno::EACCES: Permission denied - C://jruby-9.0.0.0/libruby/gems/shared/gems/activerecord-jdbc-adapter-1.3.14/src/java/arjdbc/mssql/MssqlRubyJdbcConnection.java
An error occurred while installing activerecord-jdbc-adapter <1.3.14>, and bundler cannot continue.
Make sure that 'gem install activerecord-jdbc-adapter -v '1.3.14'' succeeds before bundling.

I attempted "gem install activerecord-jdbc-adapter -v '1.3.14' and received the following error:

ERROR: Could not find a valid gem 'activerecord-jdbc-adpater' (=1.3.14), here is why:
unable to download datafrom https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

Any ideas?

Thanks,
Cary Dane
![errno](https://cloud.githubusercontent.com/assets/15641933/11079650/e6f63e58-87db-11e5-8d53-8862cba5adf7.jpg)

**Comment by bronzdoc** [comment]
The first error <code>Errno::EACCES: Permission denied</code> is because the user in which you are running the command doesn't have access(read/write permissions) to the file <code>C://jruby-9.0.0.0/libruby/gems/shared/gems/activerecord-jdbc-adapter-1.3.14/src/java/arjdbc/mssql/MssqlRubyJdbcConnection.java</code>

For the second error check this guide https://gist.github.com/luislavena/f064211759ee0f806c88

**Comment by duckinator** [comment]
@GrowFinsTurkey can you let us know if @bronzdoc's response resolved your problems?

**Comment by duckinator** [comment]
Closing since part of this isn't a problem with RubyGems, and the other part should be resolved by the link @bronzdoc provided.

**Comment by Tom-Ash** [comment]
Maybe this will help:
https://gist.github.com/stungeye/fc58daa5fce1d7d3c99fe5a9db503a46
