### ISSUE TITLE
Pre-release gems inside a gemspec don't get installed 

### ISSUE THREAD

**Issue by did** [rubygems/rubygems#1380]
hi Rubygems team,

The problem we're facing with the last versions of Rubygem (2.5.0 but same behaviour with 2.4.x) is that pre-release gems inside a gemspec don't get be found and so they aren't installed.

A sample of the gemspec of my ruby gem:

````
...
gem.name = 'locomotivecms_wagon'
gem.version = '2.0.0.rc2' 
...
gem.add_dependency 'locomotivecms_coal',    '~> 1.0.0.rc1'
gem.add_dependency 'locomotivecms_steam',   '~> 1.0.0.rc2'
....
````

**Note**: these 2 gems have been correctly pushed to Rubygems. 

If I try to install locally my locomotivecms_wagon gem, I will get the following error message:
````
~ > gem install --local ./locomotivecms_wagon-2.0.0.rc2.gem --pre
ERROR:  Could not find a valid gem 'locomotivecms_coal' (~> 1.0.0.rc1) in any repository
````

**Note 2:** It used to work with Rubygems 2.3.x.

**Solution**: I think there should be an option to pass to the ````gem```` command to force pre-release gems to be installed. 

Thanks!

**Comment by segiddins** [comment]
I can't reproduce this when I just run `gem install locomotivecms_wagon-2.0.0.rc2.gem`

**Comment by did** [comment]
hey @segiddins, thanks for your answer. Actually, that's awkward, my bad. 
I was using this "--local" option that I got from a google search. Without the --local option, it works perfectly fine indeed. Again sorry for the noise.
