### ISSUE TITLE
Rubygems 2.5.0: Activating railties gem breaks "require"

### ISSUE THREAD

**Issue by mattbrictson** [rubygems/rubygems#1381]
One consequence of this bug is that `rails new` fails with rubygems 2.5.0, as described further here: https://github.com/rails/rails/issues/22286

I've found these to be the minimal steps to reproduce:

```
$ irb
>> require "rubygems"
false
>> gem "railties", "4.2.4"
true
>> require "bundler"
LoadError: cannot load such file -- bundler
	from /Users/mbrictson/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require'
	from /Users/mbrictson/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `rescue in require'
	from /Users/mbrictson/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:39:in `require'
	from (irb):3
	from /Users/mbrictson/.rbenv/versions/2.2.3/bin/irb:11:in `<main>'
```

Of course, the bundler gem is installed on my system, so as long as I do not activate railties first, it works fine:

```
$ irb
>> require "rubygems"
false
>> require "bundler"
true
```

Downgrading to rubygems 2.4.8 fixes the issue.

**Comment by segiddins** [comment]
I cannot reproduce this:

```ruby
# irb
gem 'railties'
require 'bundler'
```

succeeds for me

**Comment by mattbrictson** [comment]
Perhaps these additional clues will help? I dropped a `binding.pry` in at `rubygems/core_ext/kernel_require.rb:128` to debug and found this `load_error` is the cause:

```
Gem::LoadError: Could not find 'hoe' (~> 3.14) among 238 total gem(s)
```

So I manually installed hoe with `gem install hoe` and tried again. And then I got a different missing gem, and so I manually installed them, and on and on:

```
Gem::LoadError: Could not find 'permutation' (>= 0) among 239 total gem(s)
Gem::LoadError: Could not find 'sdoc' (~> 0.3.16) - did find: [sdoc-0.4.1]
Gem::LoadError: Could not find 'minitest' (~> 4.3) - did find: [minitest-5.8.2,minitest-5.7.0,minitest-5.4.3]
Gem::LoadError: Could not find 'racc' (~> 1.4) among 243 total gem(s)
Gem::LoadError: Could not find 'rake-compiler' (>= 0.4.1) among 244 total gem(s)
Gem::LoadError: Could not find 'rspec' (~> 2.8.0) among 245 total gem(s)
Gem::LoadError: Could not find 'hoe' (~> 2.12) - did find: [hoe-3.14.2]
Gem::LoadError: Could not find 'minitest' (~> 2.1) - did find: [minitest-5.8.2,minitest-5.7.0,minitest-5.4.3,minitest-4.7.5]
Gem::LoadError: Could not find 'cucumber' (~> 1.1.4) among 253 total gem(s)
```

And finally! After manually installing all of these, my problem was solved.

So perhaps the problem here is that my original `gem install rails` did not install all the necessary dependencies?

**Comment by mattbrictson** [comment]
I see for example that `rails` has these dependencies:

`rails` → `activesupport` → `json` → `permutation`

But `permutation` was not installed on my system when I did `gem install rails`.

**Comment by mattbrictson** [comment]
What I have been able to figure out is that when I `require "bundler"`, the first thing that `require` does is call `Gem::Specification.find_in_unresolved_tree`.

At this point `unresolved_deps` contains the following:

```ruby
{"json"=>Gem::Dependency.new("json", Gem::Requirement.new([">= 1.7.7", "~> 1.7"]), :runtime),
 "minitest"=>Gem::Dependency.new("minitest", Gem::Requirement.new(["~> 5.1"]), :runtime),
 "rake"=>Gem::Dependency.new("rake", Gem::Requirement.new([">= 0.8.7"]), :runtime)}
```

These deps are flattened out into a list of specs, which gives:

```
#<Gem::Specification name=json version=1.8.1>
#<Gem::Specification name=json version=1.8.3>
#<Gem::Specification name=minitest version=5.4.3>
#<Gem::Specification name=minitest version=5.7.0>
#<Gem::Specification name=minitest version=5.8.2>
#<Gem::Specification name=rake version=0.9.6>
#<Gem::Specification name=rake version=10.4.2>
```

And then `traverse` is called on each of these specs. Everything goes OK until we reach the spec for `json 1.8.3`.

The `traverse` method calls `dependencies` for this spec and gets these:

```ruby
[
Gem::Dependency.new("permutation", Gem::Requirement.new([">= 0"]), :development),
Gem::Dependency.new("sdoc", Gem::Requirement.new(["~> 0.3.16"]), :development)
]
```

And when it calls `to_specs` on the `permutation` dependency ([specification.rb:2572](https://github.com/rubygems/rubygems/blob/v2.5.0/lib/rubygems/specification.rb#L2572)), we blow up with a `LoadError`, because the permutation gem is not installed (it is a development dependency, so it shouldn't need to be):

```
Gem::LoadError: Could not find 'permutation' (>= 0)
```

Does this help?

**Comment by mattbrictson** [comment]
I see this key difference between 2.4.8 and 2.5.0 for `traverse`:

2.4.8: `runtime_dependencies.each`

2.5.0: `dependencies.each`

**Comment by segiddins** [comment]
I haven't gotten around to writing a spec yet but can anyone confirm if https://github.com/rubygems/rubygems/issues/1383 indeed fixes the issue for them?

**Comment by mattbrictson** [comment]
@segiddins Yes, #1383 fixes the issue in my environment. Thanks!
