### ISSUE TITLE
Blank gem owner?

### ISSUE THREAD

**Issue by dblock** [rubygems/rubygems#1384]
```
$ gem owner slack-ruby-client --add ...@...
Owner added successfully.
Owners for gem: slack-ruby-client
- 
- dblock@...
```

The first one comes back blank. That owner must have a clever blank name?

**Comment by segiddins** [comment]
Probably happening because the email for https://rubygems.org/profiles/mikz is hidden on rg.org

**Comment by segiddins** [comment]
I think this is a rubygems.org issue, rather than a client-side one.

**Comment by dblock** [comment]
I think you should reopen this @segiddins. The maintainers of the gem cannot add/remove a person like this without remembering what the email address was.

**Comment by segiddins** [comment]
@dblock there's nothing to do there on the client side though -- that information simply isn't available via the API

**Comment by dblock** [comment]
It should show "hidden" or something other than blank maybe ...

**Comment by segiddins** [comment]
Well as of `master` it will show the username or the user ID if the email isn't available
