### ISSUE TITLE
Problems with SSL Connection to rubygems.org hanging.

### ISSUE THREAD

**Issue by belfare** [rubygems/rubygems#1386]
$ curl -vvv -k https://rubygems.org                                                                                  130 ↵
* Rebuilt URL to: https://rubygems.org/
* Hostname was NOT found in DNS cache
*   Trying 54.186.104.15...
* Connected to rubygems.org (54.186.104.15) port 443 (#0)
* successfully set certificate verify locations:
*   CAfile: none
  CApath: /etc/ssl/certs
* SSLv3, TLS handshake, Client hello (1):

It looks like it permanently hangs from several different hosts at the client TLS handshake phase.  I see all of the packets going forward to the host on my side, but it appears there isn't the return after the initial connection.

I can confirm that I don't have this issue with any other TLS sites, so I'm not sure what's happening when it hits the rubygems.org server since I can't see the other end.

**Comment by tennsk** [comment]
Hello, got similar problem:
"Unable to download data from https://rubygems.org/ - Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://api.rubygems.org/quick/Marshal.4.8/rails-4.2.5.gemspec.rz)"

**Comment by zxlzh2015** [comment]
I also encountered this issue, how to solve

**Comment by belfare** [comment]
There isn't anything for the client side to fix, this is a server side issue.  The admins of rubygems.org will need to fix it.

**Comment by bronzdoc** [comment]
This issue belongs to rubygems.org, please submit the issue to rubygems.org repo thanks.
