### ISSUE TITLE
Call `hash -r` after installing to update executables cache

### ISSUE THREAD

**Issue by nathanl** [rubygems/rubygems#1391]
Summary: **`gem install` may add executables to directories in `$PATH`. When it finishes, it should call `hash -r` so that the new ones are used.**

Here's the use case:

- Start with a system that has Ruby and its utilities pre-installed at `/usr/bin/ruby` and `/usr/bin/gem`, and `/usr/bin/bundle` (I think Macs generally come this way)
- `cd` to a project folder with a `GEMFILE` and a `.ruby-version`
- Notice that `.ruby-version` calls for a Ruby that isn't installed
- Install that version of Ruby
- Switch to the newly-installed Ruby (eg, by manually using `chruby`)
- `gem install bundler`
- `bundle install`.

Here's the problem - you may have just installed `~/.gem/ruby/2.2.3/bin/bundle`, but the shell doesn't see that yet; `bundle install` runs `/usr/bin/bundle/`.

That means that gems like `json` will be compiled against the wrong version of Ruby. And (depending on the Ruby version mismatch) that may mean that `rails server` will segfault. Those gems must be uninstalled and reinstalled with the correct version of `bundle`.

That's a solution once you know what happened. If you don't, it looks like "sometimes when I install new versions of Ruby it breaks everything, and sometimes it doesn't." I won't tell you how long it took me to figure this out. :laughing: :sob: :laughing: 

So: given that `gem install` may add a new executable to `$PATH` - eg, `~/.gem/ruby/2.2.3/bin/bundle` - it should call `hash -r` when it finishes to ensure that the executables it installed are available in the current shell session.

I don't know if there's a Windows equivalent for `hash -r`.

**Comment by drbrain** [comment]
This can be added as via a post-install hook.  For example [this one](https://github.com/rubygems/rubygems/blob/4a778c9c2489745e37bcc2d0a8f12c601a9c517f/lib/rubygems/install_message.rb) shows the "Successfully installed …" message.

**Comment by nathanl** [comment]
Oh, nice! Would you like a PR for this?

**Comment by drbrain** [comment]
Sure, but will it work?

RubyGems will run `hash -r` from a shell inside of ruby inside of your original shell…

**Comment by postmodern** [comment]
This will not work. `hash` is a built-in shell function which , much like `cd`. AFAIK there's no way for a child process to influence the parent shell.

**Comment by nathanl** [comment]
So the issue is that `gem` is a Ruby script, which runs as a subprocess of the shell and therefore can't influence its state.

And the reason that `chruby` **can** call `hash -r` is because it's [not a script but a function](https://github.com/postmodern/chruby/blob/c6fb9f9e45cd470402d5d5da2fbc483fe72741f1/share/chruby/chruby.sh#L63), which means it executes in the current shell process. Correct?

**Comment by postmodern** [comment]
Correct. That's the reason why chruby/RVM have to be loaded into the shell. rbenv requires that it's binstub directory be in `$PATH` and that binstubs be generated for _every_ ruby and gem executable, in order to proxy any invocation of ruby.

Also, rubygems just installs bin stubs (`~/.gem/ruby/2.1.6/bin/bundle`) which attempt to load the best version of the gem. So even if you have multiple gem dirs in your `$PATH`, the first `bundle` executable found would try to load the latest version of bundler.

**Comment by nathanl** [comment]
Seems to confirm:

    $ function echo_pid(){ echo $$ }
    $ echo $$  # => 12509
    $ echo_pid # => 12509

**Comment by nathanl** [comment]
So, short of writing a `gem` function and making users load it into their shell, there's nothing we can do about this. :frowning:

The thing is - this is **super** easy to avoid now that I know about it. I just wish I could spare some others the pain of thinking "sometimes when I install a new version of Ruby then try to run my code, I get segfaults, and I don't know why." I had various wrong theories about how I had horked my system.

Maybe they will run across this GH issue. If so: **be sure that `which bundle` points to the one for the Ruby version you expect, dear readers!**

Thanks @postmodern for your insight (and of course, for chruby).
