### ISSUE TITLE
logstash-input-jdbc2.0.5 

### ISSUE THREAD

**Issue by kpchere** [rubygems/rubygems#1393]
Hi !
I am not able to install the logstash-input-jdbc2.0.5 plugin from https://rubygems.org/gems/logstash-input-jdbc/versions/2.0.5. I tried mentioning 'gem 'logstash-input-jdbc', '~> 2.0', '>= 2.0.5' entry inside gemfile as well mentioned seperate dependencies one after another but it always fails for logstash-core dependency. Even installing seperate gem for logstash-core fails for every version. Other dependencies of logstash-input-jdbc2.0.5 plugin get  fetched properly; only the issue about logstash-core gem. Please help.

c:\DevKit>bundle install
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
Bundler could not find compatible versions for gem "logstash-core":
  In Gemfile:
    logstash-input-jdbc (= 2.0.5) x64-mingw32 depends on
      logstash-core (< 3.0.0, >= 2.0.0.beta2) x64-mingw32
Could not find gem 'logstash-core (< 3.0.0, >= 2.0.0.beta2) x64-mingw32', which
is required by gem 'logstash-input-jdbc (= 2.0.5) x64-mingw32', in any of the
sources.

**Comment by segiddins** [comment]
Could you please share the output of `bundle env` so we can investigate? Thanks!

**Comment by ph** [comment]
@kpchere You have to run it under jruby, `logstash-core` only exist as a jruby gem.
