### ISSUE TITLE
Make ruby gem install to user-install by default

### ISSUE THREAD

**Issue by kallisti5** [rubygems/rubygems#1394]
This is spun off of https://bugs.ruby-lang.org/issues/11731

Installing gem's system-wide doesn't make sense 99% of the time...

Linux -- Need root access via sudo
Windows -- Need administrator
Max OS X -- Need root access via sudo
Haiku -- /boot/system read-only
gem currently installs gems system-wide by default

Since the most common use-case is to install gems for your own
user, why doesn't gem --user-directory by default?

Tools like rvm already set this manually.

Making --user-install default means gem package maintainers only need to --no-user-install while everyone else just gem install's

**Comment by kallisti5** [comment]
Nobuyoshi Nakada mentioned a good idea of "Maybe to fallback to user-install when no permission to the default place."

**Comment by voxik** [comment]
On Fedora and RHEL7+ we are installing all gem into user directory, but root installs the gems into /usr/local. Packaged gems goes into /usr. Check out our settings:

http://pkgs.fedoraproject.org/cgit/ruby.git/tree/operating_system.rb#n82
http://pkgs.fedoraproject.org/cgit/ruby.git/tree/operating_system.rb#n95

**Comment by kallisti5** [comment]
Thanks for confirming that @voxik

So that confirms ArchLinux, Fedora, RHEL, and Haiku already have this behavior patched in via a few different methods . We need to confirm what Ubuntu and Debian are doing.  Having this the default would remove a lot of the one-offs and make ruby gems more standardized.

**Comment by godfat** [comment]
I am all for this. I have this line in my `~/.gemrc` for years, and to be honest, it often breaks.

    gem: --user-install --env-shebang --no-rdoc --no-ri

Now with 2.6.0, all my installed gems were missing from `gem list` and friends, but I could still require them... Still digging why :(

**Comment by spk** [comment]
Ubuntu and Debian does not change the default behavior of Rubygem, you have to set the GEM_HOME or use `--user-install` option

**Comment by indirect** [comment]
I would be happy to default to of this for RubyGems 3. Chruby, for example, already defaults to this.

**Comment by copiousfreetime** [comment]
I think the result of this ticket as that `--user-install` could become the default in rubygems 3.0.

**Comment by ry167** [comment]
[I wrote a blog post about a method of working around this](http://blog.ryanhalliday.com/2016/08/ruby-gem-install-to-user-directory-by-default.html)

In short, add this to your `.bashrc`:
```
gem() {
	if [[ $1 == "install" ]]; then
		gemargs="$@"
		command gem install --user-install ${gemargs:7}
	else
		command gem "$@"
	fi
}
if hash ruby 2>/dev/null; then
	PATH="$(ruby -rubygems -e 'puts Gem.user_dir')/bin:$PATH"
fi
```

**Comment by tschoening** [comment]
> Nobuyoshi Nakada mentioned a good idea of "Maybe to fallback to user-install when no permission to the default place."

As mentioned in #1784, this approach might(!) have a drawback on modern versions of Windows. Those implement file system virtualization for legacy 32 Bit only applications, redirecting write access to system wide dirs to user specific ones automatically. Depending on how you decide if a target directory is writable or not for you to fallback, it might look like you are able to write system wide while actually the write access is redirected in a somewhat hidden user directory. Sometimes this confuses people and wouldn't be the case if you really default to user specific dirs instead of checking/trying things system wide first.

> For the purposes of this virtualization, Windows Vista treats a process as legacy if it’s 32-bit
(versus 64-bit), is not running with administrative rights, and does not have a manifest file
indicating that it was written for Windows Vista.

https://technet.microsoft.com/en-us/library/2007.06.uac.aspx

**Comment by hsbt** [comment]
I'm against this. we can easily make it on rbenv or chruby plugin or https://github.com/rubygems/rubygems/issues/1394#issuecomment-241688072 or https://github.com/rubygems/rubygems/issues/1394#issuecomment-189195205.

NOTE: I'm a maintainer of rbenv.

**Comment by kallisti5** [comment]
@hsbt Can you provide some concrete reasons why it shouldn't be default behavior?  So far we have had a lot of *good* reasons in this bug report and have shown that most distributions manually hack in this behavior.  I personally think it would be good for the ecosystem and standardize the behavior that "everyone seems to independently hack in"

You also seem pretty biased given your position :-)

**Comment by hsbt** [comment]
In the production development, We use multi-versions of Ruby like 2.3, 2.4 and 2.5. `--user-install` didn't care it. We need to add hack a PATH variable, care native extension, and etc each project.

It's a bad reason for your proposal.

**Comment by giner** [comment]
I would support the idea of falling back if system directories are not writable as it seems to cover most of use cases.

**Comment by hsbt** [comment]
@giner I'm okay to your idea.

**Comment by kallisti5** [comment]
I'm also onboard with the alternative @giner  mentioned.  I've managed a lot of ruby on rails deployments over the years where i've had to fight with system vs local vs user gem paths.  (I know ruby on rails is a small portion of the ruby ecosystem, just an example of projects with complex gem dependencies ;-) )

**Comment by segiddins** [comment]
Just quoting what I said in Slack:

> I am also in favor of making user install the default
> but maybe falling back to global install if there is no home directory?

**Comment by vfreefly** [comment]
+1 would like to see rubygems and bundler installing gems to the user directory by default.

**Comment by ams-tschoening** [comment]
Making `--user-install` the default doesn't seem to be enough at least for Windows, because when trying to install a GEM with that option I still get permissions errors:

	C:/Program Files/Ruby/2.7.0/lib/ruby/2.7.0/rubygems.rb:885:in `initialize': Permission denied @ rb_sysopen - C:/Program Files/Ruby/2.7.0/lib/ruby/gems/2.7.0/cache/nokogiri-1.10.7-x64-mingw32.gem (Errno::EACCES)
	Fetching ast-2.4.0.gem
	#<Thread:0x0000000007af7100 C:/Program Files/Ruby/2.7.0/lib/ruby/2.7.0/rubygems/request_set.rb:168 run> terminated with exception (report_on_exception is true):
	Traceback (most recent call last):
	        7: from C:/Program Files/Ruby/2.7.0/lib/ruby/2.7.0/rubygems/request_set.rb:174:in `block (2 levels) in install'
	        6: from C:/Program Files/Ruby/2.7.0/lib/ruby/2.7.0/rubygems/resolver/specification.rb:101:in `download'
	        5: from C:/Program Files/Ruby/2.7.0/lib/ruby/2.7.0/rubygems/source.rb:207:in `download'
	        4: from C:/Program Files/Ruby/2.7.0/lib/ruby/2.7.0/rubygems/remote_fetcher.rb:154:in `download'
	        3: from C:/Program Files/Ruby/2.7.0/lib/ruby/2.7.0/rubygems/remote_fetcher.rb:306:in `cache_update_path'
	        2: from C:/Program Files/Ruby/2.7.0/lib/ruby/2.7.0/rubygems.rb:885:in `write_binary'
	        1: from C:/Program Files/Ruby/2.7.0/lib/ruby/2.7.0/rubygems.rb:885:in `open'
	C:/Program Files/Ruby/2.7.0/lib/ruby/2.7.0/rubygems.rb:885:in `initialize': Permission denied @ rb_sysopen - C:/Program Files/Ruby/2.7.0/lib/ruby/gems/2.7.0/cache/ast-2.4.0.gem (Errno::EACCES)
	ERROR:  While executing gem ... (Errno::EACCES)
	    Permission denied @ rb_sysopen - C:/Program Files/Ruby/2.7.0/lib/ruby/gems/2.7.0/cache/ast-2.4.0.gem

Things shouldn't be cached system wide as well in case `--user-install` is given.

**Comment by MSP-Greg** [comment]
Something is odd.  What does the following output?
```
ruby -e "puts Gem.path"
```

JFYI, `nokogiri-1.10.7-x64-mingw32.gem` won't install on Ruby 2.7.0.

**Comment by ams-tschoening** [comment]
So providing `--user-install` should be enough in theory?

    C:\Ruby\bin>ruby -e "puts Gem.path"
    C:/Users/tschoening/.gem/ruby/2.7.0
    C:/Program Files/Ruby/2.7.0/lib/ruby/gems/2.7.0

I need to provide `--install-dir` using my user profile in `.gemrc` to work around the cache-related permission issue.

**Comment by MSP-Greg** [comment]
Sorry, you're correct.  I 'quickly' checked with a Ruby install that I overwrite often (master - daily or more), so all my gems are install with `--user-install` in my `.gemrc` file.

I just really checked it, and on my system, the gems are cached in both folders, which does seem odd...

**Comment by ams-tschoening** [comment]
thanks for testing. I can remember have been fiddling with permissions at some places in the past... Is this worth creating another issue? It's still related to what is the ultimate goal here.

**Comment by MSP-Greg** [comment]
Normally leave my Ruby installs 'free', but permissions are also an issue with some *nix builds.

There may be long/short file/dir issues, and spaces.  I should revisit some of those issues.  For instance, on the GitHub Actions images, ENV['TEMP'] is a short 'tilde' path.  If one needs to do any path comparisons that may cause issues.

Using Ruby since 1.8.7, so I've got some 'safeguard' habits that I should check to see if they still cause issues...

**Comment by rubyFeedback** [comment]
Does anyone know whether this works on HaikuOS? I have not been following things quite as much. If it is fixed, perhaps the issue could be closed; if not, could someone update this? Thanks.

**Comment by duckinator** [comment]
After 8 years, IT IS FINALLY DONE!

As of 6dddd33, if `GEM_HOME` isn't set _and_ the default install directory is not writable, RubyGems sets `Gem.paths.home` to `Gem.user_dir`.
