### ISSUE TITLE
RubyGems v 2.5.0 bundle issue on 'rails new'

### ISSUE THREAD

**Issue by michaelperrygoodman** [rubygems/rubygems#1395]
`OSX 10.11,
gem 2.5.0`

I've been trying to locate the reason why when I do `rails new Test` I get this error when it tries to `run bundle install`:

[edited backtick to apostrophe]
`/Users/michael/.rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in 'require': cannot load such file -- bundler (LoadError)
	from /Users/michael/.rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:128:in 'rescue in require'
	from /Users/michael/.rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:39:in 'require'
	from /Users/michael/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/generators/app_base.rb:319:in 'bundle_command'
	from /Users/michael/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/generators/app_base.rb:335:in 'run_bundle'
	from (eval):1:in 'run_bundle'
	from /Users/michael/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in 'run'
	from /Users/michael/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in 'invoke_command'
	from /Users/michael/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in 'block in invoke_all'
	from /Users/michael/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in 'each'
	from /Users/michael/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in 'map'
	from /Users/michael/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:133:in 'invoke_all'
	from /Users/michael/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/group.rb:232:in 'dispatch'
	from /Users/michael/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in 'start'
	from /Users/michael/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/commands/application.rb:17:in '<top (required)>'
	from /Users/michael/.rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in 'require'
	from /Users/michael/.rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in 'require'
	from /Users/michael/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.4/lib/rails/cli.rb:14:in '<top (required)>'
	from /Users/michael/.rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in 'require'
	from /Users/michael/.rbenv/versions/2.1.3/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:69:in 'require'
	from /Users/michael/.rbenv/versions/2.1.3/lib/ruby/gems/2.1.0/gems/railties-4.2.4/bin/rails:9:in '<top (required)>'
	from /Users/michael/.rbenv/versions/2.1.3/bin/rails:23:in 'load'
	from /Users/michael/.rbenv/versions/2.1.3/bin/rails:23:in '<main>'`

This wasn't happening on my work computer which was using Rubygems version 2.2.2. What broke here and how can I fix this? I am noticing some new variables in my `gem env` but I don't see how those correlate to my inability to run bundler on an extremely basic command.

Edit: I should also mention that I did a `gem update --system 2.2.2` and rolled the version back and now it's working fine and without error.

Note: bundler works fine when I go inside the new Test dir and run `bundle install` but I don't want to have to do this every single time. Please assist, thank you.

**Comment by maxjacobson** [comment]
This is a known issue (https://github.com/rubygems/rubygems/issues/1381) and should be resolved in the next version via this patch: https://github.com/rubygems/rubygems/pull/1383

**Comment by segiddins** [comment]
Yup, I've fixed this on master.

**Comment by michaelperrygoodman** [comment]
Great, thank you very much!

**Comment by michaelperrygoodman** [comment]
Great, thank you very much!

**Comment by jwoertink** [comment]
Not sure if this is related or not, but I'm getting issues with version 2.5.1. https://github.com/rbenv/rbenv/issues/669#issuecomment-219780221
