### ISSUE TITLE
Add add_optional_dependency or add_recommended_dependency

### ISSUE THREAD

**Issue by ghost** [rubygems/rubygems#1404]
As far as I know .gemspec does not allow you to specify optional dependencies right now.

There are dependencies that must be met; and then there are dev-dependencies for creating the gem.

I would like to be able to recommend extra "add ons", but without them being forced onto the user.

I check for these in my code anyway.

I can partially workaround by making use of .post_install_message but ideally I would also like to have an array where I can freely specify optional dependencies.

Feel free to close this if this is unwanted or if I missed seeing it.

Thanks.

**Comment by krainboltgreene** [comment]
I know `npm` supports this and I'm a big fan of `npm`. I'll ask around to see if they've got thoughts on it after having it for so long, maybe it's a trap. Feel free to update the issue with your thoughts on how this works in your mind.

**Comment by indirect** [comment]
Supporting this is a huge UX challenge (how do you choose to install optional deps?), but seems like a good idea in general. Once rubygems is stable and maintained, I'd like to do it.

**Comment by bronzdoc** [comment]
Closing since original person who requested this is a ghost now, and nobody has requested this feature in almost 3 years
