### ISSUE TITLE
Ignore whitespace for Licenses warnings

### ISSUE THREAD

**Issue by djberg96** [rubygems/rubygems#1412]
I had "Artistic 2.0" instead of "Artistic-2.0" as my license, and got a warning about an invalid license.
```
WARNING:  WARNING: license value 'Artistic 2.0' is invalid.  Use a license identifier from
http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
```

Maybe just convert spaces to hyphens before checking validity?

Also, I'm not sure why there are two "WARNING" in the output.

**Comment by segiddins** [comment]
I mean, it is a different identifier. What's the second warning you're seeing?

**Comment by djberg96** [comment]
@segiddins The second warning is the literal text 'WARNING:' appearing twice in the output.

**Comment by djberg96** [comment]
@segiddins 'Artistic-2.0' and 'Artistic 2.0' are identical in any pragmatic (human) sense.

Yes, yes, where do we draw the line? I say at hyphens. And I would ignore case, too.
