### ISSUE TITLE
Performance issues in DependencyInstaller?

### ISSUE THREAD

**Issue by lamont-granquist** [rubygems/rubygems#1415]
To first explain what I'm trying to do (since I may simply be barking up entirely the wrong tree).  I'm trying to improve how Chef uses the rubygem API in order to install gems.  In order to do this we must be able to fill in what we call a "candidate_version" which is the available version on the remote source of the gem the user wants to install so that Chef can do its own idempotency checks.

What I've determined is that the existing Chef code winds up doing a `GET /latest_specs.4.8.gz` and then inflates a ruby cache of every single one of those specs which is terrible for RAM performance.

![Chef Memory Usage](https://cloud.githubusercontent.com/assets/454857/9555300/f6b3a578-4d80-11e5-99bd-54325192fa2f.png)

That graph is of the live slots (each point taken after instrumenting the code to force a GC).  The big red spike is an unrelated performance issue that we had in our remote_directory provider which was fixed in chef/chef#3837, so please ignore that.  The sharp rise to 400,000 live slots is caused by the first time we try to install a gem and we grab latest_specs.4.8.gz and inflate the in-memory cache.  That's the problem that I'm trying to address.

I'd like to instead hit the newer APIs like 'gem install' uses that starts with API requests like `GET /api/v1/dependencies?gems=rspec` which does not slurp down the latest specs of all the gems as the first call.  There is a tradeoff here, obviously, where we'd add more round trips to the rubygems API and slow things down a bit, but should be able to significantly reduce our memory footprint (and not have our memory footprint grown without bounds as rubygems publishes ever more gems).

The 'slurpy' code that we're using does the following query to the DependencyInstaller:

```
                available_gems = dependency_installer.find_gems_with_sources(gem_dependency)
                available_gems.pick_best!
                best_gem = available_gems.set.first
```

The code that I've been playing with from looking how 'gem install' works looks like this instead:

```
                begin
                  rs = dependency_installer.resolve_dependencies gem_dependency.name, gem_dependency.requirement
                  rs.specs.first
                rescue Gem::UnsatisfiableDependencyError
                  nil
                end
```

On the wire, this appears to do what I want.

However, the performance is much worse than I expected because:

1.  there seems to be no caching at all behind resolve_dependencies
2.  the performance when pointing at 'http://production.cf.rubygems.org' is both extremely bad and not cached at all.

The 2nd point is important to me, because we may have users that have created internal rubygems mirrors naively by duplicating the s3 buckets and which do not offer the newer API endpoints.

Some benchmarks of the "slurpy" API that pulls down latest.specs.4.8.gz:

for a gem that exists on rubygems.org:

```
       user     system      total        real
first:  0.420000   0.070000   0.490000 (  1.556174)
second:  0.000000   0.000000   0.000000 (  0.000373)
third:  0.000000   0.000000   0.000000 (  0.000308)
```

for a gem that does not exist on rubygems.org:

```
       user     system      total        real
first:  0.270000   0.010000   0.280000 (  0.958228)
second:  0.000000   0.000000   0.000000 (  0.000174)
third:  0.000000   0.000000   0.000000 (  0.000115)
```

for a gem that exists accessed through http://production.cf.rubygems.org:

```
       user     system      total        real
first:  0.240000   0.020000   0.260000 (  0.422814)
second:  0.000000   0.000000   0.000000 (  0.000510)
third:  0.010000   0.000000   0.010000 (  0.000395)
```

The aggressive caching here is pretty obvious.  Now looking at `#resolve_dependencies` hitting the newer API endpoints.  In the case of a gem that exists on rubygems.org:

```
       user     system      total        real
first:  0.040000   0.010000   0.050000 (  0.944599)
second:  0.010000   0.000000   0.010000 (  0.795025)
third:  0.020000   0.000000   0.020000 (  0.821814)
```

Faster at first, but no caching.

For a gem that does not exist:

```
       user     system      total        real
first:  0.030000   0.010000   0.040000 (  0.470843)
second:  0.000000   0.000000   0.000000 (  0.410874)
third:  0.000000   0.000000   0.000000 (  0.399161)
```

Again, no caching.

For a gem accessed through production.cf.rubygems.org:

```
       user     system      total        real
first:  8.510000   0.110000   8.620000 (  9.356115)
second:  8.490000   0.040000   8.530000 (  8.653654)
third:  8.390000   0.030000   8.420000 (  8.525400)
```

The performance here is 10x to 20x slower, and there's no caching.  This is really the blocker for me, since a perf hit of 10 seconds times every gem resource in a chef-client run for users who have internal rubygems mirrors is very poor.

So to start off with, am I going about this roughly correctly, or is there just some different Gem API that I should be using?

Then, the second question would be if there are legitimate performance bugs in rubygems here or not?

And finally the work that I'm doing inside chef is at https://github.com/chef/chef/pull/3856 -- although the rubygems provider in Chef is definitely top 10 of the worst example of code inside of the Chef codebase that I can think of so you might not want to look at that.

**Comment by lamont-granquist** [comment]
I'm still very interested doing work to fix this issue, but would need to get some guidance from someone that knows the rubygems source code better than I do...

**Comment by copiousfreetime** [comment]
@lamont-granquist I'm having a bit of of an issue understanding what problem you are attempting to solve here. I do know that you should not point directly to `production.cf.rubygems.org`. There is a fastly cache in place now and letting the gem dependencies resolve naturally.

**Comment by lamont-granquist** [comment]
Yeah what I wrote is fairly confusing, there's two different APIs:

1.  `latest_specs_4.8.gz` which is very slurpy.  it has 'good' in-memory caching, but completely explodes the RAM when you hit it and it caches everything.

2.  `GET /api/v1/dependencies?gems=rspec` which only gets the gem specs that the depsolver needs, but appears to have no caching in RAM.

by caching, i'm not talking about fast.ly caching, but ruby objects.

i'm going to have to take a look at this on Monday, though.  clearly if you 'gem install chef' and then 'gem install nokogiri' you wouldn't expect to have cached any gems when using `resolve_dependencies` and hitting the  `GET /api/v1/dependencies?gems=rspec` endpoint (nokogiri only depends on mini_portile2 and i think that has limited deps and none of them are shared with chef).  i'm also working on fixing a bug we have in chef where if a gem is installed and satisfies the user requirements we go off and pull down the dependency metadata anyway.  between fixing that bug in chef and with the fast.ly caching in front of rubygems, its possible there's no problem to fix here and i was just confusing myself...

there may just simply be an inherent RAM/speed tradeoff here and we need a switch for users to toggle based on what they care about...

**Comment by lamont-granquist** [comment]
When I cut this I believe it was after a very long session of staring at the rubygems source code and I was not thinking clearly and wanted magic (mostly wanted to magic to work around *other* bugs in the Chef codebase that we have since fixed).  I'm going to ship it using both APIs and a switch so that users can select if they want to be slurpy and pull down latest_specs or if they want to be more RAM conservative and act like `gem install` and take more round trips.   Default will now be the latter since the RAM improvements are pretty huge.   I don't think there's any bug here, but we'll see if our users find anything...

**Comment by segiddins** [comment]
This will all be improved post-Bundler merger when the new index is also available to RubyGems.
