### ISSUE TITLE
warning: regular expression has ']' when I run `gem li a]`

### ISSUE THREAD

**Issue by takiy33** [rubygems/rubygems#1427]
Thank you for nice tool.

I have regular expression warning when I run `gem li a]` command on my console.
Below is log.

```
naiad% gem li a]
/Users/naiad/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/commands/query_command.rb:82: warning: regular expression has ']' without escape: /a]/

*** LOCAL GEMS ***

/Users/naiad/.rbenv/versions/2.3.0/lib/ruby/2.3.0/rubygems/commands/query_command.rb:138: warning: regular expression has ']' without escape: /a]/

```

## Environment

Environment|Version
---|----
Ruby|ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin14]
rubygems|2.5.1

**Comment by segiddins** [comment]
This is behaving as intended -- that command line argument is intentionally interpreted as a regexp

**Comment by indirect** [comment]
I believe the plan is to treat this argument as a prefix match starting with rubygems 3.0, but for now you will need to escape regex characters since the entire argument is treated as a regex.

**Comment by takiy33** [comment]
Thank you for replying. I got it.
