### ISSUE TITLE
How do I add an extra signing cert to an existing gem?

### ISSUE THREAD

**Issue by yb66** [rubygems/rubygems#1428]
Hello,

I've been added as a contributor to an existing project which has a signing certificate attached to the gem. I'll be pushing the next release so I need to add my cert to the gem. When I follow the instructions at http://guides.rubygems.org/security/#building-gems everything is fine up till I reach point 4 and run gem build… the following error presents itself:

    ERROR: While executing gem ... (Gem::Security::Exception) invalid signing chain: certificate (my details) was not issued by (existing cert owner's details)

I've never added a second cert to an existing gem, what would the next step be? Does the existing cert owner need to do something? Is a project supposed or able to have more than one cert?

I also read the [html docs on signing certs](http://ruby-doc.org/stdlib-2.2.2/libdoc/rubygems/rdoc/Gem/Security.html#module-Gem::Security-label-Signing+certificates), but they say "Obviously this RubyGems trust infrastructure doesn’t exist yet."

Any help or insight would be much appreciated.

Regards,
iain

**Comment by saghaulor** [comment]
:+1:

**Comment by indirect** [comment]
There is no infrastructure to support multiple certs, yet. Sorry. :(
