### ISSUE TITLE
Get LGTM hooked up to this repository

### ISSUE THREAD

**Issue by krainboltgreene** [rubygems/rubygems#1429]
lgtm.co is a free service that lets you :+1: a repo and have it merged after two core maintainers give the go-ahead.

**Comment by indirect** [comment]
We've been using homu.io for Bundler and it's been pretty great--it interacts with Travis to test the merge commit before fast forwarding master to the green merge.

**Comment by krainboltgreene** [comment]
Interesting! I put lgtm on vcr and its kinda help know "what's waiting".

**Comment by krainboltgreene** [comment]
We're all setup to try lgtm.co.

**Comment by duckinator** [comment]
Over in #1496, it was decided that we're going to use homu.io. As such, closing this issue in favor of #1501.
