### ISSUE TITLE
VMC Gem - 500 error on dependencies 

### ISSUE THREAD

**Issue by jamesRaybould** [rubygems/rubygems#1439]
Hello

We are having an issue in some of our ruby projects where the VMC gem exists in the project's gem dependencies. Bundle install fails with an "Internal Server Error" message. 

I believe this is because bundler is trying to access this endpoint: https://api.rubygems.org/api/v1/dependencies?gems=vmc

The endpoint returns a 500 error for the vmc gem, but for other gems the endpoint serves the gem's dependencies file like normal.

James

**Comment by flavorjones** [comment]
If someone on rubygems.org admin staff can dump the internal log message, which I'm assuming is related to the age of the gem, then I can have someone within Cloud Foundry fix and upload a point release of the gem. Right now it's not clear what's going wrong.

**Comment by indirect** [comment]
Based on a previous similar problem, I think that nothing is wrong with the gem, but the database query is timing out. We'll need to increase the Postgres statement timeout value.

**Comment by segiddins** [comment]
I upped the statement timeout, and the error is gone. thanks for the bug report!

**Comment by flavorjones** [comment]
Thank you!

**Comment by jamesRaybould** [comment]
Thank you!
