### ISSUE TITLE
Triage all the issues and apply appropriate labels

### ISSUE THREAD

**Issue by copiousfreetime** [rubygems/rubygems#1442]
- [x] Apply the `triage` label to every open issue and pull request in the repository
- [ ] Work through all the issues and pull request, updating labels, closing duplicates, closing items that only apply to unsupported version of ruby, etc.

Labels will be applied according to the updated documentation in #1441

**Comment by LynnCo** [comment]
I'll be picking up some of this, also working on merging issue labels and semantics with [the way it works on Bundler](https://github.com/bundler/bundler/pull/4638)

**Comment by LynnCo** [comment]
One particular thing is the category labels. I want to turn all the categories into milestones, and make them feature releases. 50% because I prefer not to have category labels, 50% because RubyGems doesn't have a roadmap for 2.X future releases.

**Comment by LynnCo** [comment]
So here are our new [issue labels](https://github.com/rubygems/rubygems/labels), new and improved and matching the ones I use for Bundler (including a typo that is fixed already)

<img width="319" alt="screen shot 2016-06-09 at 2 26 34 am" src="https://cloud.githubusercontent.com/assets/5768468/15924948/cc004382-2de9-11e6-8db2-5f5950908ec2.png">

These are the ones I'm going to work on turning into feature releases

<img width="322" alt="screen shot 2016-06-09 at 2 30 44 am" src="https://cloud.githubusercontent.com/assets/5768468/15925027/4ad5b21e-2dea-11e6-88b2-ddceb162eeae.png">

**Comment by LynnCo** [comment]
@bronzdoc can you swap your automatically applied label to `status: triage`

**Comment by bronzdoc** [comment]
@LynnCo Done

**Comment by LynnCo** [comment]
I just accidentally removed the old triage label without applying the new one \>_\<
