### ISSUE TITLE
wrong readme file of rails-asset-jqueryui

### ISSUE THREAD

**Issue by isaagar** [rubygems/rubygems#1445]
first line of README.md having  rails-asset-jqgrid instead of rails-asset-jqueryui

**Comment by segiddins** [comment]
@isaagar it's unclear to me what your issue is about -- this is the repository for the rubygems tool itself.

**Comment by isaagar** [comment]
sorry ,
i am talking about gem "ruby-rails-asset-jqueryui"
when i download that gem using gem2deb then downloaded README.md file in source directory having name rails-asset-jqgrid instead of rails-asset-jqueryui

**Comment by indirect** [comment]
This issue tracker is for bugs in the gem tool, not bugs in a particular gem. You'll need to talk to the creator of the gem in question.

**Comment by isaagar** [comment]
okay
