### ISSUE TITLE
Host is down (Gem::RemoteFetcher::FetchError)

### ISSUE THREAD

**Issue by MatzFan** [rubygems/rubygems#1449]
Your [status page](https://status.rubygems.org/) reports all is well, but I have just had this error whilst trying to download a gem:

```
$ gem install activesupport
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    Host is down - connect(2) for "rubygems.global.ssl.fastly.net" port 443 (https://rubygems.global.ssl.fastly.net/quick/Marshal.4.8/activesupport-4.2.5.gemspec.rz)
```

**Comment by MatzFan** [comment]
Ooops - my bad, had inadvertently added a  [Little Snitch](https://www.obdev.at/products/littlesnitch/index.html) rule to deny access to the server - 😵

**Comment by noahsussman** [comment]
Same 😆
