### ISSUE TITLE
More visibility for the resolved ruby version dependency for gems

### ISSUE THREAD

**Issue by tomilaine** [rubygems/rubygems#1459]
Hi,

This is more of a question or idea than an issue.

Some gems will install dependencies, which restrict e.g ruby version to be more recent than the parent gem. This is especially true for gems which use optimistic versioning for their dependencies. One can work around the issue of course by defining more exact versions for the dependencies of the parent gem but the needed versions and the restrictions are not easily visible anywhere.

Maybe the actual ruby version required could be transitionally resolved so that one could see that in rubygems.org. It would also be great to see the required versions of the dependencies for a particular ruby version to save the trouble of trial and error in these cases.

**Comment by duckinator** [comment]
This may be more appropriate on the [rubygems.org repo](https://github.com/rubygems/rubygems.org) than here, but I'm not 100% sure of that. /cc @krainboltgreene

**Comment by copiousfreetime** [comment]
@tomilaine Are you asking for something other than the required ruby version that appears on the rubygems.org page? Something added to the output of `gem dependency -r <gemname>` ?

**Comment by bronzdoc** [comment]
Open this in https://github.com/rubygems/rubygems.org if you still interested in the feature, thanks.
