### ISSUE TITLE
VMC Gem - bundler API error

### ISSUE THREAD

**Issue by tmharber** [rubygems/rubygems#1463]
Hi there,

We're getting some failures when trying to install the VMC gem through bundle install.

As an example, we have a gemfile that looks like:
```
source 'https://rubygems.org'
gem 'vmc'
```

When we run bundle-install, we get the following error:
```
Retrying dependency api due to error (2/4): Bundler::HTTPError Network error while fetching https://bundler.rubygems.org/api/v1/dependencies?gems=vmc
```

However, if we run with `bundle i --full-index`, it works fine. Following the URL above takes a while, but eventually downloads a 6.3MB `dependencies` file.

I found [this](https://github.com/rubygems/rubygems/issues/1439) issue from a month or so ago, could be a similar issue?

I've also posted this to VMC [here](https://github.com/cloudfoundry-attic/vmc/issues/75).

Thanks,
Tom

**Comment by segiddins** [comment]
This issue likely belongs on the bundler-API repo

**Comment by bronzdoc** [comment]
bundler-API repo https://github.com/bundler/bundler-api

**Comment by indirect** [comment]
@tmharber this just worked for me... are you still seeing this problem?

**Comment by tmharber** [comment]
I'm still seeing this problem, yes.
