### ISSUE TITLE
Getting "Reserved gem name" when pushing, despite being an owner

### ISSUE THREAD

**Issue by ajb** [rubygems/rubygems#1474]
Hi there,

I'm trying to publish a new version of Sync: https://github.com/chrismccord/sync/releases/tag/v0.4.0

However, despite being an owner, I'm getting this error:

> There was a problem saving your gem: Name 'sync' is a reserved gem name.

<img width="671" alt="screen shot 2016-02-06 at 8 59 39 am" src="https://cloud.githubusercontent.com/assets/1270317/12867014/fbffadfc-ccaf-11e5-999d-8464938d331f.png">

Any advice? Thanks!

**Comment by segiddins** [comment]
This issue belong over on the rubygems.org repo, sorry!
