### ISSUE TITLE
Could not find rb-inotify.gem (rubygems:rb-inotify:0.9.6)

### ISSUE THREAD

**Issue by tangming1** [rubygems/rubygems#1480]
It looks like there is a release on Feb 5th 2016.
https://rubygems.org/gems/rb-inotify/versions/0.9.6

But the release download has an issue. 

When I click the download link http://rubygems-proxy.torquebox.org/releases/rubygems/rb-inotify/0.9.6/rb-inotify-0.9.6.gem. I got the following error. 
<Error>
<Code>NoSuchKey</Code>
<Message>The specified key does not exist.</Message>
<Key>gems/rb-inotify-0.9.6.gem</Key>
<RequestId>104DC32AD0E7EE89</RequestId>
<HostId>
iNCxHQK3C5eLeHa8DbAaoW9lmAFhQrnRstBAqx0m5PFyjGJUPzM5endvQSLNh0Jl4hwNc0BOzJQ=
</HostId>
</Error>

**Comment by segiddins** [comment]
This belongs over on rubygems.org.

**Comment by indirect** [comment]
@tangming1 please note that we do not operate `http://rubygems-proxy.torquebox.org`. You should open a ticket with them.
