### ISSUE TITLE
rb-inotify-0.9.7.gem is missing in the S3 repository

### ISSUE THREAD

**Issue by bsautel** [rubygems/rubygems#1484]
Hi.

I use a ruby tool (compass) in a Java build that depends on `rubygems:rb-inotify:0.9.7`. My dependencies are resolved through TorqueBox's rubygem proxy which is a bridge to the JRuby world.

It sounds like TorqueBox is unable to resolve this dependency since it is not present in the Amazon S3 repository. It tries to resolve [this URL](http://s3.amazonaws.com/production.s3.rubygems.org/gems/rb-inotify-0.9.7.gem) which returns a `404` status code.

If I change the version (`0.9.5` for instance), I can resolve this gem [on S3](http://s3.amazonaws.com/production.s3.rubygems.org/gems/rb-inotify-0.9.5.gem) and also on TorqueBox. 

On the rubygems.org website, I can download the `0.9.7` gem directly thanks to [this link](https://rubygems.org/downloads/rb-inotify-0.9.7.gem) but it is not the one TorqueBox uses.

I am new to the rubygem world. Why is this gem not deployed to the S3 repository? I noticed the `0.9.7` was released a few days ago, is there a delay before it to be available?

In the dependency chain of the tool I am using there must be a dependency without a fixed version since I did not change anything and it worked well since this new gem was published.

Thanks a lot for your help.

**Comment by indirect** [comment]
@bsautel the S3 bucket has been changed, and those URLs are not valid. Please use only links with the domain `rubygems.org` if you want to be sure your links will continue to work.

**Comment by bsautel** [comment]
@indirect thanks for your reply. Now I know where the problem comes from. I am gonna see that with TorqueBox.

**Comment by mkristian** [comment]
@bsautel I patched the torquebox proxy code yesterday to not use a hardcoded redirect but follow the redirect manually: https://github.com/torquebox/rubygems-servlets/commit/7cb71d3ced512165591a80f0b0680d823ca9bd86
I contacted @bbrowning today to redeploy the server with this fix

**Comment by bsautel** [comment]
Thanks a lot @mkristian, could you keep me up to date when it is done?

**Comment by mkristian** [comment]
will do

**Comment by bbrowning** [comment]
I've deployed this fix to our rubygems proxy. Sorry for the delay - I was traveling internationally.

**Comment by bsautel** [comment]
Thank you @bbrowning, I confirm it is working now.
