### ISSUE TITLE
Code of Conduct link to project maintainers

### ISSUE THREAD

**Issue by mpapis** [rubygems/rubygems#1503]
while reading [COC](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md) I have noticed there:

> Instances of abusive, harassing, or otherwise unacceptable behavior may be reported by opening an issue or contacting one or more of the project maintainers.

it lacks the link to maintainers information, it would force anyone willing to report anything privately to search for the information and could discourage them from reporting.

**Comment by hsbt** [comment]
Should we setup address like `conduct@rubygems.org` ? /cc @drbrain @indirect

**Comment by krainboltgreene** [comment]
Any PR that fixes this should also update to 1.4.0, please.

**Comment by segiddins** [comment]
IMHO it should list individual maintainer emails, so someone can feel more comfortable reporting something about one of the other maintainers.

**Comment by krainboltgreene** [comment]
@segiddins Agreed, I believe that's the preferred choice as well.

**Comment by duckinator** [comment]
I agree with @segiddins. Would all maintainers be listed, or only ones that explicitly opt into being listed? If the latter, I'm 100% okay with being on that list. There needs to be multiple people to contact for this kind of thing, though.

**Comment by duckinator** [comment]
Bump. This has been idle for over two months. We should figure out a plan and move forward with it.

**Comment by LynnCo** [comment]
Closed by accident! CoC still needs to be updated to 1.4

**Comment by bronzdoc** [comment]
closed by https://github.com/rubygems/rubygems/pull/1796
