### ISSUE TITLE
[question] Dependency with a gem

### ISSUE THREAD

**Issue by ClementPadovani** [rubygems/rubygems#1504]
**_UPDATED ISSUE TO ADHERE TO ISSUE TEMPLATE_**

I'm having a problem or would like to suggest a feature.

My current problem is **_see below_**

This issue is related to:
- [ ] Network problems
- [ ] Installing a library
- [ ] Publishing a library
- [ ] The command line `gem`
- [x] Other

Here are my current envrionment details:

``` ruby
$ gem env version
2.6.0
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).
# Issue

Hey,

I’m having an issue running the gem [`synx`](https://github.com/venmo/synx).

When I run `gem update` it updated `clamp` to version `1.0.0` and when I run `synx` I’ll get the obvious output:

``` bash
/Library/Ruby/Site/2.0.0/rubygems/specification.rb:2285:in `raise_if_conflicts’: Unable to activate synx-0.2.0, because clamp-1.0.0 conflicts with clamp (~> 0.6) (Gem::ConflictError)
```

However when I run `gem dependency —reverse-dependencies clamp` (post-update) I get this:

``` bash
Gem clamp-0.6.5
  Used by
    synx-0.2.0 (clamp (~> 0.6))

Gem clamp-1.0.0
```

So basically to run `synx` I have to uninstall version 1.0.0 after running a `gem update`.

Is this an issue with my version of RubyGems (2.5.2)?

Here’s my RubyGem environment:

``` ruby
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2
  - RUBY VERSION: 2.0.0 (2015-04-13 patchlevel 645) [universal.x86_64-darwin15]
  - INSTALLATION DIRECTORY: /Users/clementpadovani/.gem
  - USER INSTALLATION DIRECTORY: /Users/clementpadovani/.gem/ruby/2.0.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/clementpadovani/.gem/bin
  - SPEC CACHE DIRECTORY: /Users/clementpadovani/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Library/Ruby/Site
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-darwin-15
  - GEM PATHS:
     - /Users/clementpadovani/.gem
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/clementpadovani/.gem/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin

```

Thanks for your help!

_original issue https://github.com/venmo/synx/issues/102_

**Comment by segiddins** [comment]
Try using `gem install` instead of `gem update` in the future?

**Comment by ClementPadovani** [comment]
@segiddins Hey, thanks for the fast reply.

What do you mean? I currently have `synx` installed, the issue occurs everytime I want to update my gems.

**Comment by segiddins** [comment]
What happens if you just run `gem uninstall synx && gem install synx`?

**Comment by ClementPadovani** [comment]
```bash
➜  ~ gem uninstall synx && gem install synx
Remove executables:
	synx

in addition to the gem? [Yn]  
Removing synx
Successfully uninstalled synx-0.2.0
Fetching: synx-0.2.0.gem (100%)
Successfully installed synx-0.2.0
1 gem installed
➜  ~ gem outdated 
clamp (0.6.5 < 1.0.0)
➜  ~ 
```

**Comment by bronzdoc** [comment]
@ClementPadovani does still happen with the lastest rubygems version? or this stil and issue for you?

**Comment by ClementPadovani** [comment]
@bronzdoc issues seems gone, closing!
