### ISSUE TITLE
How do I securely release gems?

### ISSUE THREAD

**Issue by saghaulor** [rubygems/rubygems#1505]
I followed the directions for building a gem securely per http://guides.rubygems.org/security/#building-gems

When following those steps, two questions surfaced:

1. Is the cert that is generated to sign a gem specific to the gem or to the author? Step three seems to suggest that the cert is specific to the author.

> gem cert --add certs/yourhandle.pem

2. Are the certs and checksum dirs intended to live in the project root or in the lib/ subdir? Step two and the section regarding including checksums seem to suggest adding them to the project root.

I would like to follow best practices but it seems like there aren't very many project that even participate in these security practices.

Any advice would be greatly appreciated. Thank you for your time.

**Comment by tarcieri** [comment]
The RubyGems signature system as it exists today is not particularly useful.

There was a lot of discussion around this after the RubyGems compromise. Some of us worked on implementing a framework called The Update Framework:

https://theupdateframework.github.io/

Some info here:

https://groups.google.com/forum/#!topic/rubygems-tuf/vCxUSX51bbo

See also @xaviershay's posts about it:

https://corner.squareup.com/2013/12/securing-rubygems-with-tuf-part-1.html
https://corner.squareup.com/2013/12/securing-rubygems-with-tuf-part-2.html
https://corner.squareup.com/2013/12/securing-rubygems-with-tuf-part-3.html

I believe Ruby Together is planning on resuming work on it after the Bundler 2 release /cc @indirect

**Comment by indirect** [comment]
Yes, @rubytogether is planning to fund work on adding TUF to RubyGems and Bundler... it's item number 2 or 3 on our high-level list right now.

**Comment by bf4** [comment]
Whether it's best practice or not, most people don't sign gems nor know how to. Most gems aren't signed so being able to use HighSecurity is rare. And even if a gem were signed, it's still going to execute code on your system. http://lanyrd.com/2013/rulu/scgxzr/  https://tonyarcieri.com/lets-figure-out-a-way-to-start-signing-rubygems https://github.com/sferik/twitter/commit/0291149557b625302ea14b2e61290aff132a64d8#commitcomment-5596115
