### ISSUE TITLE
Requiring an .so file via Ruby will not work with RubyGems

### ISSUE THREAD

**Issue by tenderlove** [rubygems/rubygems#1507]
If I require a .so file via Ruby's require, it works.  But if I do the same thing via RubyGems, it won't work.  Here is an example:

```
# Put nokogiri's lib dir on the load path so that RubyGems isn't used, then require the .so file
[aaron@TC ~]$ ruby -I $(dirname `gem which nokogiri`) -e'l = $LOADED_FEATURES.dup; require "nokogiri/nokogiri.so"; p $LOADED_FEATURES - l'
["/Users/aaron/.rbenv/versions/ruby-trunk/lib/ruby/gems/2.4.0/gems/nokogiri-1.6.8.rc3-x86_64-darwin-15/lib/nokogiri/nokogiri.bundle"]
```

Ruby automatically deals with the .so -> .bundle conversion (so that the require is cross platform).

If I remove Nokogiri from the load path, then RubyGems will not behave the same way Ruby does:

```
[aaron@TC ~]$ ruby -e'l = $LOADED_FEATURES.dup; require "nokogiri/nokogiri.so"; p $LOADED_FEATURES - l'
/Users/aaron/.rbenv/versions/ruby-trunk/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- nokogiri/nokogiri.so (LoadError)
    from /Users/aaron/.rbenv/versions/ruby-trunk/lib/ruby/2.4.0/rubygems/core_ext/kernel_require.rb:55:in `require'
    from -e:1:in `<main>'
[aaron@TC ~]$
```

I expect the `require` call to work without being changed, but what actually happens is that RubyGems raises an exception.

**Comment by indirect** [comment]
Wow, I didn't know that Ruby silently changed the require string. That's very surprising to me. Does it work if you instead `require "nokogiri/nokogiri"`?

**Comment by tenderlove** [comment]
> Does it work if you instead require "nokogiri/nokogiri"?

Yes, but that means that I can't have a `foo.rb` file and a `foo.bundle` file in the same directory and differentiate the two.  Ruby will pick up the `.rb` file if I don't provide an extension.

**Comment by indirect** [comment]
I'm very unconvinced that silently replacing `.so` with `.bundle` in a user-provided string is a good idea, but I do think that we should at least maintain compatibility with `require` if we're going to override it. Thanks for reporting this.

**Comment by segiddins** [comment]
This logic already exists, I believe, if you look at `BasicSpecification#requireable_file?` and `Gem.suffixes`

**Comment by deivid-rodriguez** [comment]
I haven't been able to reproduce this issue on any rubygems version, so I'll close this. Feel free to reopen if it's still a problem.

**Comment by Zogoo** [comment]
I had same problem with Ruby 2.7 and bundle 2.1.4, ruby gem 3.1.4
`require "extension/hello"` doesn't work until I specify "so" file extension in require. Like `require "extension/hello.so"`
Anything reported like this? Or it's same bug happening again?

**Comment by deivid-rodriguez** [comment]
Hi @Zogoo! Can you try with rubygems 3.2.0.rc.2 and verify if your issue is fixed there? You can upgrade with `gem update --system --pre`.

**Comment by Zogoo** [comment]
@deivid-rodriguez  thanks for your quick reply. Yes, it's working with rubygems 3.2.0.rc2.

**Comment by deivid-rodriguez** [comment]
That's great to hear @Zogoo!
