### ISSUE TITLE
Gems installed via --user-install missing from `gem list` in 2.6.0

### ISSUE THREAD

**Issue by godfat** [rubygems/rubygems#1510]
My gems were all installed to `~/.gem/ruby/2.3.0` and it works fine in 2.5.2,
however after updated to 2.6.0, they're missing from `gem list` -- it now
shows no gems. On the other hand, I could still `require` them regularly.

Here's some demonstrating this:

I can require it:
```
> ruby -rrib -ve 'puts Rib::VERSION'
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin12.0]
1.2.91
```

I cannot find it via `gem list`

```
> gem list rib

*** LOCAL GEMS ***
```

I could find it if I set `GEM_HOME` to be `Gem.path.first`: ([Fish](http://fishshell.com/) command)

```
> env GEM_HOME=(ruby -e 'puts Gem.path.first') gem list rib

*** LOCAL GEMS ***

rib (1.2.91)
```

I believe something is wrong, and I haven't figured out which commit broke this.
It seems that somewhere is not respecting `Gem.path`

**Comment by tenderlove** [comment]
Ok, I was able to reproduce this:

```
[aaron@TC rubygems (master)]$ ls ~/.gem/ruby/2.3.0/gems
[aaron@TC rubygems (master)]$ ruby -Ilib -S gem install --user-install sqlite3
WARNING:  You don't have /Users/aaron/.gem/ruby/2.3.0/bin in your PATH,
	  gem executables will not run.
Building native extensions.  This could take a while...
Successfully installed sqlite3-1.3.11
Parsing documentation for sqlite3-1.3.11
Done installing documentation for sqlite3 after 0 seconds
1 gem installed
[aaron@TC rubygems (master)]$ ls ~/.gem/ruby/2.3.0/gems
sqlite3-1.3.11
[aaron@TC rubygems (master)]$ ruby -I lib -S gem list | grep sqlite3
[aaron@TC rubygems (master)]$ 
```
