### ISSUE TITLE
rubygems 2.6.0 Gem.path lost system path at ruby 2.3.0

### ISSUE THREAD

**Issue by pbaolai** [rubygems/rubygems#1517]
ruby -v : ruby 2.3.0p0 (2015-12-25 revision 53290) [x64-mingw32]
gem -v : 2.6.0

In default status (both GEM_HOME and GEM_PATH unseted),
ruby -e "puts Gem.path" :
```
D:/Users/pbl/.gem/ruby/2.3.0
A:/Ruby/lib/ruby/gems/2.3.0
```
gem list :
```
*** LOCAL GEMS ***

bigdecimal (1.2.8)
did_you_mean (1.0.0)
io-console (0.4.5)
json (1.8.3)
minitest (5.8.3)
net-telnet (0.1.1)
power_assert (0.2.6)
psych (2.0.17)
rake (10.4.2)
rdoc (4.2.1)
rubygems-update (2.6.0)
test-unit (3.1.5)
```
set GEM_HOME=A:/rhome
ruby -e "puts Gem.path" :
```
D:/Users/pbl/.gem/ruby/2.3.0
A:/Ruby/lib/ruby/gems/2.3.0
A:/rhome
```
gem list :
```
*** LOCAL GEMS ***

bigdecimal (1.2.8)
io-console (0.4.5)
json (1.8.3)
psych (2.0.17)
rdoc (4.2.1)
```
set GEM_PATH=A:/rpath
ruby -e "puts Gem.path" :
```
A:/rpath
A:/rhome
```
gem list:
```
*** LOCAL GEMS ***

bigdecimal (1.2.8)
io-console (0.4.5)
json (1.8.3)
psych (2.0.17)
rdoc (4.2.1)
```
ruby -e "require 'minitest'"
```
C:/DXDK/Ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require': cannot load such file -- minitest (LoadError)
        from C:/DXDK/Ruby/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
        from -e:1:in `<main>'
```

report at ruby core they say is rubygems's bug

**Comment by indirect** [comment]
@segiddins @tenderlove are the changes to path handling in 2.6.0 responsible for this?

**Comment by hsbt** [comment]
> report at ruby core they say is rubygems's bug

@pbaolai Can you add to issue link of ruby core tracker(redmine)?

**Comment by pbaolai** [comment]
@hsbt
https://bugs.ruby-lang.org/issues/11971

**Comment by segiddins** [comment]
I'm unsure what the actual bug being reported here is? What in particular is behaving differently than expected?

**Comment by duckinator** [comment]
The following snippet is what I understand the issue to be about, but it's also how I would expect it to behave:

```
C:\Users\Marie>ruby -e "p Gem.path"
["C:/Ruby193/lib/ruby/gems/1.9.1", "C:/Users/Marie/.gem/ruby/1.9.1"]

C:\Users\Marie>set GEM_HOME=gemhome

C:\Users\Marie>set GEM_PATH=gempath

C:\Users\Marie>ruby -e "p Gem.path"
["gemhome", "gempath"]

C:\Users\Marie>
```

From what I can tell, the default value of `Gem.path` is `GEM_HOME` followed by `GEM_PATH` (split by the path separator &mdash; `;` on Windows and `:` on UNIX-y systems).

**Comment by pbaolai** [comment]
@duckinator @segiddins 
This behaver is different than before, and the more important is that require some standard ruby library will fail -- 'minitest'  'test-unit'  for example.

**Comment by duckinator** [comment]
@pbaolai by "different than before before" do you mean "different than before changing the variables", or "different than with older versions of Ruby and/or gems"? Overriding the variables it uses to find the standard library will cause requiring things from the standard library to fail &mdash; either `GEM_HOME` or `GEM_PATH` needs to point to the standard library, if you override the default values.

**Comment by pbaolai** [comment]
I see. Thanks

**Comment by tenderlove** [comment]
Haven't tested yet, but looks like it might be a duplicate of #1510

--
Aaron Patterson
http://tenderlovemaking.com/
I'm on an iPhone so I apologize for top posting.

**Comment by indirect** [comment]
@tenderlove cool, thanks.

@pbaolai this should be fixed in RubyGems 2.6.1. Can you test and let us know?

**Comment by hammerdr** [comment]
Not entirely sure if this is related, but here is something interesting

```
root@357892474bcd:/code# gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.3
  - RUBY VERSION: 2.3.0 (2015-12-25 patchlevel 0) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/local/bundle
  - USER INSTALLATION DIRECTORY: /root/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/local/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/bundle/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/local/bundle
     - /root/.gem/ruby/2.3.0
     - /usr/local/lib/ruby/gems/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "install" => "--no-document"
     - "update" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/bundle/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
root@357892474bcd:/code# export GEM_PATH=vendor/bundle/ruby/1.9.1
root@357892474bcd:/code# gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.3
  - RUBY VERSION: 2.3.0 (2015-12-25 patchlevel 0) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/local/bundle
  - USER INSTALLATION DIRECTORY: /root/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/local/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/bundle/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/local/bundle
     - vendor/bundle/ruby/1.9.1
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "install" => "--no-document"
     - "update" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/bundle/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
root@357892474bcd:/code# bundle
/usr/local/lib/ruby/site_ruby/2.3.0/rubygems.rb:250:in `find_spec_for_exe': can't find gem bundler (>= 0.a) (Gem::GemNotFoundException)
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems.rb:278:in `activate_bin_path'
	from /usr/local/bin/bundle:22:in `<main>'
```

After adding a GEM_PATH, the GEM_HOME is no longer loading correctly. I think this may be a change in behavior. Maybe it's the correct one, but before ruby 2.3.0 this wouldn't happen.

This caught us, but easy to fix because we don't need GEM_PATH to be set anyway. Helping us clean our environment variables :)

**Comment by robertoxyz20** [comment]
Hello, same here
C:\Ruby23>gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [i386-mingw32]
  - INSTALLATION DIRECTORY: C:/Ruby23/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: C:/Users/roberto/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: C:/Ruby23/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/Ruby23/bin
  - SPEC CACHE DIRECTORY: C:/Users/roberto/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86-mingw32
  - GEM PATHS:
     - C:/Ruby23/lib/ruby/gems/2.3.0
     - C:/Users/roberto/.gem/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Ruby23\bin
     - C:\Ruby23\bin
     - C:\Windows\system32
     - C:\Windows
     - C:\Windows\System32\Wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0\
     - C:\Program Files\Skype\Phone\
     - C:\Program Files\Shoes
any fix?
