### ISSUE TITLE
Cannot cleanup user gems

### ISSUE THREAD

**Issue by godfat** [rubygems/rubygems#1530]
Due to this commit: ec8a3fd60e4b22ff1f588efc225d8fcaff0273c9
I believe this is a regression from 2.6.0.

You could reproduce this by:

```
gem install rake -v 10.4.2 --user-install
gem install rake -v 10.4.1 --user-install
gem cleanup rake
```

Reverting it would restore the behaviour.

**Comment by bronzdoc** [comment]
Please provide your ```gem env```

**Comment by godfat** [comment]
It's pretty standard and I believe you could reproduce it by the above commands. The only thing I added was a line in `~/.gemrc`:

    gem: --user-install --env-shebang --no-rdoc --no-ri

Which I believe has the same effect as you use `--user-install` in `gem install`

Here's the `gem env`:

```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.1
  - RUBY VERSION: 2.3.0 (2015-12-25 patchlevel 0) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /home/godfat/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /usr/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/bin
  - SPEC CACHE DIRECTORY: /home/godfat/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/lib/ruby/gems/2.3.0
     - /home/godfat/.gem/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--user-install --env-shebang --no-rdoc --no-ri"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/godfat/bin
     - /home/godfat/.gem/ruby/2.3.0/bin
     - /home/godfat/.gem/rbx/2.2/bin
     - /home/godfat/.gem/jruby/2.2.0/bin
     - /home/godfat/.cabal/bin
     - /usr/local/bin
     - /usr/local/sbin
     - /usr/lib/hardening-wrapper/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/bin
     - /usr/lib/jvm/default/bin
     - /usr/bin/site_perl
     - /usr/bin/vendor_perl
     - /usr/bin/core_perl
```

**Comment by bronzdoc** [comment]
I just tried to reproduce this and I'm having the same results before and after the patch with user installed gems(not cleaning) and i think that's the expected behaviour of ```gem cleanup```  in this scenario.

```
Description:
    The cleanup command removes old versions of gems from GEM_HOME that are not
    required to meet a dependency.  If a gem is installed elsewhere in GEM_PATH
    the cleanup command won't delete it.
    
    If no gems are named all gems in GEM_HOME are cleaned.
```

**Comment by godfat** [comment]
Not sure why you can't reproduce this on your side, but I could assure you it would cleanup ~/.gem before 2.6.0 at least on my side (both on my Mac and Linux) and I've been using this for many years.

I don't have any `GEM_HOME` nor `GEM_PATH` set on the other hand. All defaults.

Perhaps I am relying on a bug which you fixed, if `gem clean` never intended to cleanup gems installed via `--user-install`. But well, why not? I don't quite understand the reason behind that.

If there's no strong reason, I would like to ask we preserve the behaviour, that is it should cleanup gems installed via `--user-install`.

**Comment by drbrain** [comment]
The install, uninstall and cleanup commands should only work on `GEM_HOME` so you don't accidentally destroy another "environment" when you didn't mean to.  `--user-install` should change `GEM_HOME` so it might be that we've been missing proper `--user-install` behavior for cleanup.

**Comment by bronzdoc** [comment]
Marking this as a feature request so cleanup supports the ```--user-install``` flag

**Comment by godfat** [comment]
@drbrain Thanks. So I think we agree to have install, uninstall, and cleanup being consistent with `--user-install`.

@bronzdoc I am not very sure if restoring an old behaviour should be considered a new feature, but as long as we could get this work, I don't mind which term should be used. Thanks for your attention, too.

**Comment by jonathonf** [comment]
Just in case anyone else finds this when wondering why `gem clean` stopped working as it used to, the "workaround" is to ensure `$GEM_HOME` is set to your user's gem path, e.g.:

```
GEM_HOME=$HOME/.gem/ruby/2.4.0 gem cleanup
```
Perhaps `$GEM_HOME` needs to be exported in a shellrc file, though if `gem install` uses a default value I'm not quite sure why `gem cleanup` doesn't use the same one...

**Comment by godfat** [comment]
@jonathonf Thanks, I was using that workaround for awhile. Lately I wrote this to help me: https://github.com/godfat/gem-compact (p.s. `gem compact` requires RubyGems 2.7.3+)

So I could just:

```
gem compact
```

And it would cleanup all gems in `GEM_PATH` (which would include user gems)

**Comment by godfat** [comment]
@bronzdoc Thank you for implementing it! A quick question, would it be implicitly granted if `gem: --user-install` is set in `~/.gemrc`?

**Comment by bronzdoc** [comment]
@godfat it should, but is not...  i'm checking into it

you could open a new issue about it, thanks!

**Comment by godfat** [comment]
Thank you, here you are: https://github.com/rubygems/rubygems/issues/2365
