### ISSUE TITLE
ERROR: While executing gem... (OpenSSL::X509::CertificateError) not enough data

### ISSUE THREAD

**Issue by gawbul** [rubygems/rubygems#1531]
I was getting the following error when trying to build a gem:

```
$ gem build -V --backtrace --debug sensu-plugins-splunk.gemspec
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `OpenSSL::X509::CertificateError' at /Users/smoss/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/security/signer.rb:59 - not enough data
ERROR:  While executing gem ... (OpenSSL::X509::CertificateError)
    not enough data
    /Users/smoss/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/security/signer.rb:59:in `initialize'
    /Users/smoss/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/security/signer.rb:59:in `new'
    /Users/smoss/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/security/signer.rb:59:in `block in initialize'
    /Users/smoss/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/security/signer.rb:54:in `map'
    /Users/smoss/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/security/signer.rb:54:in `initialize'
    /Users/smoss/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:481:in `new'
    /Users/smoss/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:481:in `setup_signer'
    /Users/smoss/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:250:in `build'
    /Users/smoss/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/package.rb:115:in `build'
    /Users/smoss/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/commands/build_command.rb:53:in `execute'
    /Users/smoss/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/command.rb:310:in `invoke_with_build_args'
    /Users/smoss/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:169:in `process_args'
    /Users/smoss/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/command_manager.rb:139:in `run'
    /Users/smoss/.rbenv/versions/2.2.3/lib/ruby/site_ruby/2.2.0/rubygems/gem_runner.rb:55:in `run'
    /Users/smoss/.rbenv/versions/2.2.3/bin/gem:21:in `<main>'
```

I tracked this down to [line 57 of security/signer.rb](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/security/signer.rb#L57) `cert = File.read cert if File.exist? cert`

This actually turned out to be my error in providing the incorrect certificate filename for the cert_chain in my gemspec file. However, if the file doesn't exist, the code simply returns the original filename as a String, which [line 59](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/security/signer.rb#L59) `OpenSSL::X509::Certificate.new cert` then attempts to continue as if it were the certificate file content.

There should probably be a more explicit check and error message here, e.g. something like:

```
begin
  cert = File.read cert
rescue => e
  puts "#{e.message}"
end
```

**Comment by duckinator** [comment]
So, what's the *expected* behavior if the file doesn't exist? Should it abort the entire process with an error, or what?

Also, I feel a better approach would be:

```ruby
      @cert_chain = @cert_chain.compact.map do |cert_path|
        next cert if OpenSSL::X509::Certificate === cert_path

        unless File.exist? cert_path
          # Handle the certificate not existing.
        end

        cert = File.read cert_path

        OpenSSL::X509::Certificate.new cert
      end
```

**Comment by bronzdoc** [comment]
@gawbul i tried to reproduce your problem but couldn't get the same result.

 I tired with a wrong cert path and with a .cer cert as this post suggest it will trigger your error https://stackoverflow.com/questions/12162975/openssl-not-enough-data but couldn't reproduce your `not enough data` error

We can't check for `File.exist?(cert)` and fail because cert could be just a cert string and not a file necessary, so i think tubygems is behaving correctly. If you can give me steps to reproduce the problem i will reopen this issue.

**Comment by yb66** [comment]
Hi all,

If it's any help, I got this error message too and for the same reason, an incorrect `cert_chain` (I copy and pasted `s.cert_chain  = ['certs/yourhandle.pem']` from [the instructions](https://guides.rubygems.org/security/) without reading them properly, tsk tsk! (0_º)

Obviously I've sorted it now but perhaps it'll help track down a bug.

Regards,
iain

**Comment by Nimesh-Msys** [comment]
I got this error while reading `DER-encoded certificate`. It got resolved by using `File.binread`. Check [this answer](https://stackoverflow.com/a/54704007) if it seems to be relevant.
