### ISSUE TITLE
Running update_rubygems may happen to fail on Windows

### ISSUE THREAD

**Issue by gallelli** [rubygems/rubygems#1533]
After installing/updating the rubygems-update gem, update_rubygems script execution may happen to fail on Windows with the following error:

Cannot find RubyGems Update Path!

In my opinion this happens in the following scenario:
- Install Ruby 2.2.4 on Windows, 32 or 64 bit version does not matter
- Install the rubygems-update gem, say version 2.5.2
- Run update_rubygems: it works fine
- Install and configure the appropriate Ruby Dev Kit for Windows:
  ruby dk.rb init
  ruby dk.rb install
- Update to rubygems-update version 2.6.1
- Run update_rubygems: now it fails with the above error

The reason for the failure is that the following line is missing from the update_rubygems script under the Ruby bin directory when updating to 2.6.1:

gem 'rubygems-update', version

I believe such line is missing only after installing the Ruby Dev Kit for Windows,

Here are my current envrionment details:

O.S.: Windows 10 64-bit version - Italian language
RubyGems Environment:
- RUBYGEMS VERSION: 2.6.1
- RUBY VERSION: 2.2.4 (2015-12-16 patchlevel 230) [i386-mingw32]
- INSTALLATION DIRECTORY: E:/ruby22/lib/ruby/gems/2.2.0
- USER INSTALLATION DIRECTORY: C:/Users/gallelli/.gem/ruby/2.2.0
- RUBY EXECUTABLE: E:/ruby22/bin/ruby.exe
- EXECUTABLE DIRECTORY: E:/ruby22/bin
- SPEC CACHE DIRECTORY: C:/Users/gallelli/.gem/specs
- SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
- RUBYGEMS PLATFORMS:
  - ruby
  - x86-mingw32
- GEM PATHS:
  - E:/ruby22/lib/ruby/gems/2.2.0
  - C:/Users/gallelli/.gem/ruby/2.2.0
- GEM CONFIGURATION:
  - :update_sources => true
  - :verbose => true
  - :backtrace => false
  - :bulk_threshold => 1000
  - "gem" => "--no-document"
- REMOTE SOURCES:
  - https://rubygems.org/

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by rubycoder** [comment]
I'm seeing the same behavior on Win 7 Pro SP 1 64 bit English language.

I had an existing install of ruby 2.3.1p112 32 bit and the devkit.

Install the rubygems-update gem, version 2.5.2
Run update_rubygems: it works fine
Run gem install --local downloads\rubygems-update-2.6.7.gem
Run update_rubygems: now it fails with "Error: Cannot find RubyGems Update Path!"

As described above, the update_rubygems script is missing the line:

gem 'rubygems-update', version

I manually added that line to update_rubygems, and now update_rubygems succeeds.

@gallelli Thanks for the information on how to fix this problem!

**Comment by sonalkr132** [comment]
I got this issue on Fedora 24 updating from rubygems 2.6.1 to any of versions from 2.6.2 to 2.6.7.
Steps to reproduce:
```
$ gem install --local ~/Downloads/rubygems-update-2.6.1.gem
$ update_rubygems
$ gem --version
2.6.1
$ gem uninstall rubygems-update
$ gem install --local ~/Downloads/rubygems-update-2.6.2.gem
 Error: Cannot find RubyGems Update Path!
RubyGems has already been updated.
The rubygems-update gem may now be uninstalled.
E.g. gem uninstall rubygems-update
```

Mentioned fix of missing line successfully updated the rubygems.

**Comment by evansendra** [comment]
+1 on manually adding the 

    gem 'rubygems-update', version

line after the version assignment in the update_rubygems file in the path to ruby's bin

**Comment by francoraconto** [comment]
Solved with this command:

`gem update --system`
