### ISSUE TITLE
Error building native Gems Ruby 2.2  RubyGems 2.6.1

### ISSUE THREAD

**Issue by mobill** [rubygems/rubygems#1540]
I'm updating to ruby 2.2 and am I'm getting an error building native Gems.  I've tried several different versions of RubyGems and Ruby 2.1 with no luck.

Thanks in advance for any help or pointers.

c:\>ruby -v
ruby 2.2.4p230 (2015-12-16 revision 53155) [i386-mingw32]

c:\>gem -v
2.6.1

DevKit-mingw64-32-4.7.2-20130224-1151-sfx.exe

    c:\>gem install json --platform=ruby
    Temporarily enhancing PATH to include DevKit...
    Building native extensions.  This could take a while...
    c:\DevKit\bin\make.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0
    c:\DevKit\bin\make.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0
    ERROR:  Error installing json:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby22/lib/ruby/gems/2.2.0/gems/json-1.8.3/ext/json/ext/generator
    C:/Ruby22/bin/ruby.exe -r ./siteconf20160308-10776-1hwe3bd.rb extconf.rb
    creating Makefile

    current directory: C:/Ruby22/lib/ruby/gems/2.2.0/gems/json-1.8.3/ext/json/ext/generator
    make "DESTDIR=" clean
          0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
    AllocationBase 0x0, BaseAddress 0x60E90000, RegionSize 0x380000, State 0x10000
    c:\DevKit\bin\make.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0

    current directory: C:/Ruby22/lib/ruby/gems/2.2.0/gems/json-1.8.3/ext/json/ext/generator
    make "DESTDIR="
          0 [main] us 0 init_cheap: VirtualAlloc pointer is null, Win32 error 487
    AllocationBase 0x0, BaseAddress 0x60E90000, RegionSize 0x380000, State 0x10000
    c:\DevKit\bin\make.exe: *** Couldn't reserve space for cygwin's heap, Win32 error 0

    make failed, exit code 1

    Gem files will remain installed in C:/Ruby22/lib/ruby/gems/2.2.0/gems/json-1.8.3 for inspection.
    Results logged to C:/Ruby22/lib/ruby/gems/2.2.0/extensions/x86-mingw32/2.2.0/json-1.8.3/gem_make.out

**Comment by tenderlove** [comment]
Does [this SO post](http://stackoverflow.com/questions/18502999/git-extensions-win32-error-487-couldnt-reserve-space-for-cygwins-heap-win32) help?

**Comment by mobill** [comment]
Hadn't seen that particular post.  -1 for google.

Saw rebase on another post. Will try it tomorrow.  I rebooted my machine
this morning.

Thanks!

**Comment by tenderlove** [comment]
@mobill OK! Please let us know how it goes! :D

**Comment by mobill** [comment]
Rebooting worked.    Might be worth a mention on the Ruby Installer DevKit page.
