### ISSUE TITLE
Source blocks not working after upgrading rubygems

### ISSUE THREAD

**Issue by jooshbzm** [rubygems/rubygems#1549]
We're getting a strange error when running bundle install after upgrading rubygems from 2.4.8 to 2.6.2. We originally install bundler with the gem version of 2.4.8, then run `gem update --system` before running bundle install (this is in a CI environment that we don't control).

When running bundle install, we get the following error:
```
$ bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
A block was passed to `source`, but Bundler versions prior to 1.7 ignore the block.  Please upgrade Bundler to 1.7 or specify your dependencies outside of the block passed to `source`.
A block was passed to `source`, but Bundler versions prior to 1.7 ignore the block.  Please upgrade Bundler to 1.7 or specify your dependencies outside of the block passed to `source`.
You are trying to install in deployment mode after changing
your Gemfile. Run `bundle install` elsewhere and add the
updated Gemfile.lock to version control.
```

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current envrionment details:

```
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 12.04.5 LTS
Release:	12.04
Codename:	precise

Linux Version
3.13.0-29-generic

$ ruby --version
ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-linux]
$ rvm --version
rvm 1.26.10 (latest-minor) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
$ bundle --version
Bundler version 1.11.2
```

```
$ gem env version
2.6.2
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by indirect** [comment]
The `bundle` command is not related to the `gem` command. Issues with the `bundle` command should be reported to [the Bundler issue tracker](https://github.com/bundler/bundler/issues).

**Comment by jooshbzm** [comment]
@indirect This doesn't occur with rubygems 2.6.1. It only started occurring with the 2.6.2 release. Should this still go to bundler?

**Comment by indirect** [comment]
@jooshbzm yes.

**Comment by jooshbzm** [comment]
Reported here: https://github.com/bundler/bundler/issues/4366
