### ISSUE TITLE
Add a new API endpoint for versioned gems

### ISSUE THREAD

**Issue by mrueg** [rubygems/rubygems#1571]
As a packager, I'd like to have an API endpoint for versioned gems, so that I can grab dependencies from the rubygems.org API.

As of now, there is only the https://rubygems.org/api/v1/versions/$GEM.json endpoint, which does not include required dependencies.
I use https://rubygems.org/api/v1/search/?query=$GEM endpoint to receive at least the dependencies for the latest version released.

It would be nice to have a new endpoint that could provide the dependency information on a version base.
e.g.:
https://rubygems.org/api/v1/versioned/$GEM/$VERSION.json

This would also be aligned with the current endpoint for the latest version:

https://rubygems.org/api/v1/versioned/$GEM/latest.json

**Comment by duckinator** [comment]
Hi! Issues related to the rubygems.org website should be made on the [rubygems/rubygems.org](https://github.com/rubygems/rubygems.org) repository. Could you please open an equivalent issue there, then close this one? Thanks!

**Comment by mrueg** [comment]
Sorry, will do! :)
