### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by altsab** [rubygems/rubygems#1574]
I'm having a problem or would like to suggest a feature.

My current problem is cannot install anything with gem install command, tried for jekyll and rails as well.

This issue is related to:

  - [x] The command line `gem`

Here are my current envrionment details:
Linux Ubuntu 14.04

user@Jarvis:~/altsab.github.io$ gem install jekyll
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://api.rubygems.org/quick/Marshal.4.8/jekyll-3.1.2.gemspec.rz)

user@Jarvis:~/altsab.github.io$  gem install rails --source http://rubygems.org
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://api.rubygems.org/quick/Marshal.4.8/rails-4.2.6.gemspec.rz)

```
$ gem env version
2.6.2
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by djberg96** [comment]
@altsab Can you please show us the full output of "gem env"? Also, is there a proxy between you and the rubygems server?

**Comment by altsab** [comment]
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.2
  - RUBY VERSION: 1.9.3 (2013-11-22 patchlevel 484) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/lib/ruby/gems/1.9.1
  - USER INSTALLATION DIRECTORY: /home/nrchst/.gem/ruby/1.9.1
  - RUBY EXECUTABLE: /usr/bin/ruby1.9.1
  - EXECUTABLE DIRECTORY: /usr/bin
  - SPEC CACHE DIRECTORY: /home/nrchst/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/lib/ruby/gems/1.9.1
     - /home/nrchst/.gem/ruby/1.9.1
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games

There is no proxy, actually I tried with proxy as well.

**Comment by altsab** [comment]
UPDATE:

I'm in China and there is a firewall, maybe this is a cause.

Kindly ask someone to send cache of gem installer:

$ gem install rails -i repo --no-rdoc --no-ri
$ cp -r repo/cache /some folder

**Comment by arlmy** [comment]
https://ruby.taobao.org/ @altsab

**Comment by altsab** [comment]
@arlmy Thank you a lot! I couldn't find this way because I'm not a chinese, thank you again.
