### ISSUE TITLE
Specs sorting in Gem::Specification._resort!() should be stable

### ISSUE THREAD

**Issue by a9udn9u** [rubygems/rubygems#1581]
I'm having a problem or would like to suggest a feature.
I'm having a problem

My current problem is _________
I have a script that has to run with JRuby, it depends on several gems, some with JRuby versions, some don't and some have both, I've setup my GEM_PATH so that JRuby gem path is before regular gem path, such as: [path-to-JRuby-gems-lib]:[path-to-non-JRuby-gems-lib]. My expectation is when a gem has JRuby version, RubyGems will load the JRuby version. I found that sometimes RubyGems behaves as I expected, sometimes it doesn't. After some digging up I found this method in [specification.rb](https://github.com/rubygems/rubygems/blob/0e3c58e7fa3a8f1f69ca3e74067af6fb3cb2eb11/lib/rubygems/specification.rb#L859), it uses Array.sort!() to sort specs by name and version, it is not stable sort, which means when a gem is installed in both the JRuby gems path and the regular gems path, it is non-deterministic about which version will be loaded after you add or remove new gems to your library.

This issue is related to:
- [ ] Network problems
- [ ] Installing a library
- [ ] Publishing a library
- [ ] The command line `gem`
- [x] Other

Here are my current envrionment details:

My environment doesn't matter, I've linked to the latest commit of [specification.rb](https://github.com/rubygems/rubygems/blob/0e3c58e7fa3a8f1f69ca3e74067af6fb3cb2eb11/lib/rubygems/specification.rb#L859) and it's still an unstable sort.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Could you build a reproducible case to explain the trouble this is causing you?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
