### ISSUE TITLE
cannot find rspec in gem list

### ISSUE THREAD

**Issue by knaseem** [rubygems/rubygems#1585]
I'm having a problem or would like to suggest a feature.

My current problem is  rspec is installed successfully but when I do gem list it does not show up.________

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current envrionment details:

Khalids-MBP:~ KNaseem$ gem list

*** LOCAL GEMS ***

bigdecimal (default: 1.2.0)
io-console (default: 0.4.2)
json (default: 1.7.7)
minitest (default: 4.3.2)
psych (default: 2.0.0)
rake (default: 0.9.6)
rdoc (default: 4.0.0)
test-unit (default: 2.0.0.0)
```
$ gem env version
PASTE HERE
Khalids-MBP:~ KNaseem$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.3
  - RUBY VERSION: 2.0.0 (2015-12-16 patchlevel 648) [universal.x86_64-darwin15]
  - INSTALLATION DIRECTORY: /Users/khalidnaseem/.rvm/gems/ruby-1.9.3-p194
  - USER INSTALLATION DIRECTORY: /Users/KNaseem/.gem/ruby/2.0.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/khalidnaseem/.rvm/gems/ruby-1.9.3-p194/bin
  - SPEC CACHE DIRECTORY: /Users/KNaseem/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Library/Ruby/Site
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-darwin-15
  - GEM PATHS:
     - /Users/khalidnaseem/.rvm/gems/ruby-1.9.3-p194
     - /Users/khalidnaseem/.rvm/gems/ruby-1.9.3-p194@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/khalidnaseem/.rvm/gems/ruby-1.9.3-p194/bin
     - /Users/khalidnaseem/.rvm/gems/ruby-1.9.3-p194@global/bin
     - /Users/khalidnaseem/.rvm/rubies/ruby-1.9.3-p194/bin
     - /Users/khalidnaseem/.rvm/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Users/KNaseem/.rvm/bin

```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by knaseem** [comment]
I am also getting this when installing rspec 2.8.0
Khalids-MBP:~ KNaseem$ sudo gem install rspec-system
Password:
Fetching: systemu-2.6.5.gem (100%)
Successfully installed systemu-2.6.5
Fetching: rspec-mocks-2.99.4.gem (100%)
Successfully installed rspec-mocks-2.99.4
Fetching: rspec-expectations-2.99.2.gem (100%)
Successfully installed rspec-expectations-2.99.2
Fetching: rspec-core-2.99.2.gem (100%)
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted - /usr/bin/autospec

**Comment by knaseem** [comment]
rspec -v shows the following:
Khalids-MBP:bin KNaseem$ rspec -v
/Library/Ruby/Site/2.0.0/rubygems/dependency.rb:308:in `to_specs': Could not find 'rspec-core' (>= 0) among 8 total gem(s) (Gem::MissingSpecError)
Checked in 'GEM_PATH=/Users/khalidnaseem/.rvm/gems/ruby-1.9.3-p194:/Users/khalidnaseem/.rvm/gems/ruby-1.9.3-p194@global', execute `gem env` for more information
	from /Library/Ruby/Site/2.0.0/rubygems/dependency.rb:320:in `to_spec'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_gem.rb:65:in `gem'
	from /usr/local/bin/rspec:22:in `<main>'
Khalids-MBP:bin KNaseem$

**Comment by knaseem** [comment]
I am studying for ruby/ROR and want to learn TDD but cannot have rspec run.

**Comment by bronzdoc** [comment]
Try installing the gem without <code>sudo</code> and report back, thanks.

**Comment by knaseem** [comment]
tried installing rspec without sudo:

Khalids-MBP:~ KNaseem$ gem install rspec --version 2.8.0
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied - /Users/khalidnaseem

**Comment by bronzdoc** [comment]
Ok, so your user `KNaseem` doesn't have write permission to `/Users/khalidnaseem`. 
Are you setting your `GEM_HOME` environment variable to `Users/khalidnaseem/.rvm/gems/ruby-1.9.3-p194` in any place? e.g your .bashrc 

I see a mix of `KNaseem` and `khalidnaseem` in your environment and you are using rvm, so that souldn't be happening.
```
  - INSTALLATION DIRECTORY: /Users/khalidnaseem/.rvm/gems/ruby-1.9.3-p194
  - USER INSTALLATION DIRECTORY: /Users/KNaseem/.gem/ruby/2.0.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/khalidnaseem/.rvm/gems/ruby-1.9.3-p194/bin
  - SPEC CACHE DIRECTORY: /Users/KNaseem/.gem/specs
```

**Comment by knaseem** [comment]
Thanks for the feedback.  How can I fix this issue?  I have not set anything in my GEM_HOME environment variable.  This is what's inside my .bashrc file=>
PATH=$PATH:$HOME/.rvm/bin # Add RVM to PATH for scripting

**Comment by bronzdoc** [comment]
When you use `sudo gem install` the gem will be installed at your system ruby paths, so when you do `gem list` rubygems will check your "non sudo environment" and will not find the gem(sorry for not telling you that before).

You could try a couple of things:
- Create a new rvm gemset and try to install the gem in that context
- Give the user in which you are running `gem install` write permissions to whatever is in your `INSTALLATION_DIRECTORY`

**Comment by knaseem** [comment]
Hi,
a) Can you help with creating the new rvm gemset and install the rspec gem?
b)  How should I give user write permissions?  Thanks.

**Comment by bronzdoc** [comment]
a)  to create a new gemset you do something like:
```
rvm gemset create my_rails_app
rvm gemset use my_rails_app
gem install rspec
```
https://rvm.io/gemsets/basics

b) http://www.tutorialspoint.com/unix/unix-file-permission.htm
