### ISSUE TITLE
Investigate why the check_manifest task is failing on Appveyor

### ISSUE THREAD

**Issue by segiddins** [rubygems/rubygems#1586]

**Comment by duckinator** [comment]
I still have Appveyor enabled on my fork of the repo (https://ci.appveyor.com/project/duckinator/rubygems).

Going to poke around on my fork using their RDP debugging stuff, in a bit: https://www.appveyor.com/docs/how-to/rdp-to-build-worker.

**Comment by duckinator** [comment]
@segiddins is this resolved by #1590?

**Comment by segiddins** [comment]
It is if the build is now passing on appveyor

**Comment by duckinator** [comment]
It passed on the PR that updated appveyor.yml, so that's a yes. :+1:
