### ISSUE TITLE
net/https and OpenSSL::SSL::VERIFY_PEER

### ISSUE THREAD

**Issue by GPif** [rubygems/rubygems#1597]
I'm having a problem or would like to suggest a feature.

My current problem is with net/https the OpenSSL::SSL::VERIFY_PEER flag fail on connect 

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

Here are my current envrionment details:
Ubuntu, ruby 2.2 via RVM
```
$ gem env version
2.4.8
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

I try to create a piece of code to contact a server via HTTPS with certificats.

The curl following curl command return the correct result :
`curl https://localhost --key crt/client.key --cert crt/client.crt --cacert crt/ca.pem`

But the following script :
```ruby
require "net/http"
require "net/https"
require "openssl"
require "uri"
require "pp"

request = Net::HTTP::Get.new("/")
response = Net::HTTP.start(
  "localhost",
  443,
  {
    :use_ssl => true,
    :key => OpenSSL::PKey::RSA.new(File.read("/home/gg/crt/client.key")),
    :cert => OpenSSL::X509::Certificate.new(File.read("/home/gg/crt/client.crt")),
    :ca_file => "/home/gg/crt/ca.pem",
    :verify_mode => OpenSSL::SSL::VERIFY_PEER,
    :verify_depth => 5,
  }
) do |http|
      http.request(request)
end
puts response.inspect
puts response.body
```

return 
```
/home/gg/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
    from /home/gg/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `block in connect'
    from /home/gg/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/timeout.rb:74:in `timeout'
    from /home/gg/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:923:in `connect'
    from /home/gg/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:863:in `do_start'
    from /home/gg/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:852:in `start'
    from /home/gg/.rvm/rubies/ruby-2.2.1/lib/ruby/2.2.0/net/http.rb:583:in `start'
    from testso.rb:8:in `<main>'
```
But it work fine when I replace the `OpenSSL::SSL::VERIFY_PEER` by `OpenSSL::SSL::VERIFY_NONE`

**Comment by segiddins** [comment]
@GPif are you sure this is an issue in RubyGems?

**Comment by GPif** [comment]
@segiddins I am not 100% sure, but the fact that it worked with curl and not with ruby make me believe it is. 
I try to dig the origin and the error occur when calling the connect method of the OpenSSL::SSL::SSLSocket. 
I ran it with a debugger to try to understand where it come from and at this call it immediately raise an exception.

**Comment by segiddins** [comment]
But I'm not seeing any RubyGems code in that backtrace...

**Comment by GPif** [comment]
@segiddins you are right it is an issue with net/http withc is not part of RubyGem, i mixed repos.
Deeply sory about that. I close the issue and will post it to ruby repo :D
