### ISSUE TITLE
Gem Update won't upgrade past 2.6.3.

### ISSUE THREAD

**Issue by envygeeks** [rubygems/rubygems#1602]
`rubygems-update` 2.6.4 constantly installs Gem 2.6.3 which results in me being able to loop over and install.
```
Updating rubygems-update
Successfully installed rubygems-update-2.6.4
Parsing documentation for rubygems-update-2.6.4
Done installing documentation for rubygems-update after 0 seconds
Parsing documentation for rubygems-update-2.6.4
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 2.6.3
RubyGems 2.6.3 installed
Parsing documentation for rubygems-2.6.3
Installing ri documentation for rubygems-2.6.3
```
This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

```
$ gem env version
2.6.3
```

---

- ***Distro***: Ubuntu GNU/Linux version 16.04
- ***Kernel***: 4.5 Custom Mainline

- Using System Ruby (ruby2.3 ruby2.3-dev)
- This has never been a problem before, until this last release.

---

Proof that it previously worked:
```
$ sudo gem update --system=2.6.2

Updating rubygems-update
Fetching: rubygems-update-2.6.2.gem (100%)
Successfully installed rubygems-update-2.6.2
Parsing documentation for rubygems-update-2.6.2
Installing ri documentation for rubygems-update-2.6.2
Installing darkfish documentation for rubygems-update-2.6.2
Done installing documentation for rubygems-update after 1 seconds
Parsing documentation for rubygems-update-2.6.2
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 2.6.2
RubyGems 2.6.2 installed
Parsing documentation for rubygems-2.6.2
Installing ri documentation for rubygems-2.6.2

$ gem -v
2.6.2
```

---

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
We're looking into this. For now, could you `gem install --system=2.6.4`?

**Comment by envygeeks** [comment]
@segiddins yes! I was able to get the proper version with `gem update --system=2.6.4`.

**Comment by cisolarix** [comment]
The same issue encountered.

```
➜  Desktop gem update --system
Updating rubygems-update
Successfully installed rubygems-update-2.6.4
Installing RubyGems 2.6.3
RubyGems 2.6.3 installed

=== 2.6.3 / 2016-04-05
output omitted for brevity
➜  Desktop gem -v
2.6.3
```

**Comment by bronzdoc** [comment]
This was fixed in https://github.com/rubygems/rubygems/pull/1601
