### ISSUE TITLE
Absolute names of length 101 characters are not handled properly by Gem::Package::TarWriter

### ISSUE THREAD

**Issue by ptomulik** [rubygems/rubygems#1608]
I'm having a problem.

My current problem is that I'm not able to write to Tar archive a file with absolute name having 101 characters - the leading slash "/" gets eaten somewhere within ``TarWriter``, ``TarHeader`` or so. 

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

I have this small example demonstrating the issue
```
# test.rb
require 'rubygems/package'

foo100 = '/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/1/foo.txt'
foo101 = '/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/12/foo.txt'
foo102 = '/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123/foo.txt'

File.open("foo.tar", "w") do |outf|
  ::Gem::Package::TarWriter.new(outf) do |tar|
    tar.add_file(foo100, 00644) { |io| io.write("Hello!") }
    tar.add_file(foo101, 00644) { |io| io.write("Hello!") }
    tar.add_file(foo102, 00644) { |io| io.write("Hello!") }
  end
end
```

Now, if I run ``ruby test.rb`` and then ``tar tvf foo.tar`` I see the following list of files
```
ptomulik@tea:$ tar tvf foo.tar                                                                                      
tar: Removing leading `/' from member names                                                                                
-rw-r--r-- wheel/wheel       6 2016-05-09 15:05 /123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/1/foo.txt
-rw-r--r-- wheel/wheel       6 2016-05-09 15:05 123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/12/foo.txt
-rw-r--r-- wheel/wheel       6 2016-05-09 15:05 /123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123/foo.txt
```

Please note, that the second file name (which originally was 101 characters long) is missing the leading slash.

Here are my current environment details:

```
$ gem env version
2.6.4
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
I believe the length of the file name in the header is actually limited to 100 characters

**Comment by ptomulik** [comment]
Well, it seems to work for 101 and longer names.

**Comment by ptomulik** [comment]
I started looking from https://github.com/rubygems/rubygems/blob/master/lib/rubygems/package/tar_writer.rb#L312, this function is used by all the ``add_xxx`` functions of TarWriter. Especially, if I add the following line just before the ``return name, prefix`` clause,

```
print("name: '#{name}', prefix: '#{prefix}'\n")
```

the output is following:

```
name: '/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/1/foo.txt', prefix: ''
name: '123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/12/foo.txt', prefix: ''
name: '123456789/123456789/123456789/123456789/123456789/123456789/123456789/123456789/123/foo.txt', prefix: '/123456789'
```

Looking at first and second line it's quite evident that none of the functions using result of ``split_name`` is kinda wrong for the second case. Also, from third line I see that 102-char long path is handled as intended.
