### ISSUE TITLE
Gem source sorting should preserve ordering of sources supplied by the user

### ISSUE THREAD

**Issue by ntl** [rubygems/rubygems#1609]
When resolving which dependency to install, the gem sources are sorted by their source and then version: https://github.com/rubygems/rubygems/blob/master/lib/rubygems/resolver.rb#L236

This is desirable as it allows sources to be prioritized. However, a `Gem::Source` is compared to another `Gem::Source` by an alphanumeric sort on the URL string. See the code here: https://github.com/rubygems/rubygems/blob/master/lib/rubygems/source.rb#L70

This means that the ordering of the sources specified by the user is not being respected. So, `gem install foo --source https://a.com --source https://b.com` will prefer any version of `foo` hosted at `b.com` over any version of `foo` hosted at `a.com` simply because `"b.com"` is "greater than" `"a.com"`. I would expect that, since I specified `https://a.com` first, any gems in `https://a.com` would be preferred over their similarly named counterparts in `https://b.com`.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by ntl** [comment]
As a possible resolution, I think line 70 here: https://github.com/rubygems/rubygems/blob/master/lib/rubygems/source.rb#L70 could be replaced with `return 0` and cause the ordering to be preserved.

**Comment by segiddins** [comment]
@ntl a PR making that change with tests would be much appreciated!

**Comment by ntl** [comment]
PR is submitted.
