### ISSUE TITLE
`rake newb` doesn't install right version of minitest

### ISSUE THREAD

**Issue by duckinator** [rubygems/rubygems#1610]
I'm having a problem or would like to suggest a feature.

My current problem is running `rake newb` on the RubyGems repo on a fresh install, I get:

```ruby
C:/Users/marie/dev/ruby/rubygems/rubygems/lib/rubygems/dependency.rb:310:in `to_specs': Could not find 'minitest' (~> 4.0) - did find: [minitest-5.8.3] (Gem::MissingSpecVersionError)
```

Running `gem install minitest -v "~> 4.0"` then running `rake newb` again works. It appears to install the latest version of minitest, then expect minitest ~> 4.0. I've experienced this behavior on three different systems (two Windows, one Linux).

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other (specific to RubyGems development)

Here are my current environment details:

```
$ gem env version
2.5.1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
So I think this is actually a hoe issue -- it seems to be installing the gem in a subprocess and not call `gem` again: https://github.com/seattlerb/hoe/blob/215e47bb1e201ea1bef28f919393babc764e05a5/lib/hoe/deps.rb#L59. I think you probably should report this over there?

**Comment by duckinator** [comment]
Done.

**Comment by duckinator** [comment]
https://github.com/seattlerb/hoe/issues/72#issuecomment-223744173

looks like it should be fixed in the next release of hoe.

**Comment by duckinator** [comment]
hoe 3.15.1 was released; we should make sure we're using it so this issue is actually properly resolved. http://blog.zenspider.com/releases/2016/06/hoe-version-3-15-1-has-been-released.html

**Comment by duckinator** [comment]
DISREGARD THAT. hoe is installed manually before running `rake newb`, so this is entirely resolved.
