### ISSUE TITLE
Gem does not load sources

### ISSUE THREAD

**Issue by kylekyle** [rubygems/rubygems#1613]
Ran into an interesting, but very reproducible problem today. I have a gemrc that only lists one source: 

> http://rubygems.local

When I drop into pry, I see the following:

```ruby
[0] pry (main)> Gem.sources
#<Gem::SourceList:0x0074325bad6234> @sources=[[Remote: https://rubygems.org/ API: https://rubygems.org]]>
[1] pry (main)> Gem.sources
#<Gem::SourceList:0x0074325bad6234> @sources=[[Remote: http://rubygems.local/ API: http://rubygems.local]]>
```

Which is probably not good behavior. This behavior is consistent across a number of platforms and versions, but here's an example: 

```bash
$ ruby --version 
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
$ gem --version
2.6.4
```

I hadn't noticed this until now because the `gem` utility always retries. So it gets the correct source list after the first try. But it too appears to always try `https://rubygems.org` first no matter what.

**Comment by segiddins** [comment]
I'm unable to reproduce this -- can you please try and boil this down to a script that reliably reproduces the issue? Thanks!

**Comment by kylekyle** [comment]
Sure. Empty your gem sources, then run:

```bash
ruby -e "puts Gem.sources.empty?"
``

**Comment by segiddins** [comment]
What do you mean by "empty your sources"?

**Comment by kylekyle** [comment]
Here's what it looked like for me: 

```bash 
MacBook-Air:~ kyle$ gem sources
*** CURRENT SOURCES ***

https://rubygems.org/
MacBook-Air:~ kyle$ gem sources --remove https://rubygems.org/
MacBook-Air:~ kyle$ gem sources
*** CURRENT SOURCES ***

MacBook-Air:~ kyle$ 
```

Alternatively, you can add an additional source, then run:

```bash
ruby -e "puts Gem.sources.count"
```

The point is, no matter what your sources look like, `Gem.sources` will initially return a list with only `https://rubygems.org/` in it.

**Comment by segiddins** [comment]
I couldn't reproduce this, sorry

**Comment by drbrain** [comment]
RubyGems does not read `~/.gemrc` until it needs to (say, installing gems) so it confusingly returns the default sources.

Besides the confusion, does this cause you any issue?

In the example below RubyGems correctly loads your `~/.gemrc` before attempting to install gems despite `Gem.sources` confusingly showing the default source.

```
$ gem source
*** CURRENT SOURCES ***

http://rubygems.example
$ irb
>> Gem.sources
=> #<Gem::SourceList:0x007fca2b1e5620 @sources=[#<Gem::Source:0x007fca2b1e5300 @uri=#<URI::HTTPS https://rubygems.org/>, @api_uri=nil>]>
>> Gem.install 'pry'
Gem::UnsatisfiableDependencyError: Unable to resolve dependency: user requested 'pry (>= 0)'
[exception backtrace trimmed]
>>   Gem.sources
=> #<Gem::SourceList:0x007fca2d966320 @sources=[#<Gem::Source:0x007fca2d965e48 @uri=#<URI::HTTP http://rubygems.example>, @api_uri=#<URI::HTTP http://rubygems.example>, @update_cache=true>]>
```

**Comment by kylekyle** [comment]
@segiddins: What version of `gem` are you running? What do your sources look like? What is the output of the command I gave you? 

@drbrain: I use this method to set Bundler sources in the [iruby-dependencies gem](https://github.com/jupyter-gallery/iruby-dependencies). It took me a long time to figure out that this method was the reason Bundler was always using `https://rubygems.org/` regardless of my sources. 

If this is the expected behavior, then the documentation should reflect that. Right now it is a bit misleading:

> Returns an Array of sources to fetch remote gems from. Uses default_sources if the sources list is empty.

It should really mention that it returns default sources until some gem activity triggers the loading of the configuration. It would also be nice to have a documented way of forcing the config to load, like `Gem.sources(load_config: true)`. 

I've forced the loading using `Gem::ConfigFile.new(['sources'])`. I'm not sure if that's the best way. It certainly isn't an obvious way. 

Is there any reason not to have`Gem.sources` check that the config has been loaded? Is there any reason to use that method *before* the config is loaded?

**Comment by drbrain** [comment]
I asked my question to discover what priority we should make a fix.

The reason it works the confusing way it does is in part historical accident.  Long, long ago RubyGems loaded `~/.gemrc` every time it was loaded.  Unfortunately this had an outsize impact on short-running programs (since it required loading YAML) so it was changed to only load for `gem` or installing gems.

Unfortunately I missed making `Gem.sources` trigger loading `~/.gemrc` so now it behaves confusingly and incorrectly.

Your workaround until we fix this can be `Gem::ConfigFile.new []`, there's no need to add a `'sources' ` since it gets treated as a command-line argument.
