### ISSUE TITLE
gem command should notify the user when it is out of date

### ISSUE THREAD

**Issue by swrobel** [rubygems/rubygems#1620]
I'm would like to suggest a feature.

This issue is related to:
The command line `gem`

I noticed that `pip` provides feedback as follows when it is out of date:

```
You are using pip version 7.1.2, however version 8.1.2 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
```

Similar behavior from rubygems would likely encourage many more users to update their client. I use ruby on a daily basis and often forget to run `gem update --system` for long periods of time.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
I'm 👎 on this -- I really don't like when command line tools print more than they need to

**Comment by duckinator** [comment]
I'm also :-1: on this. It would either make a network request _every time you run the `gem` executable_, or it would add a significant amount of code complexity to avoid doing so.

**Comment by swrobel** [comment]
Not really, I think you're overthinking it. Just include the latest rubygems version with every payload from the server.






On Sat, May 28, 2016 at 11:56 PM -0700, "Ellen Marie Dash" <notifications@github.com> wrote:












I'm also 👎 on this. It would either make a network request every time you run the gem executable, or it would add a significant amount of code complexity to avoid doing so.

**Comment by duckinator** [comment]
Fair enough! So, if that were to be a thing, a prerequisite would be rubygems.org including the latest rubygems version in every API response.

It would also need to have that version number printed only when appropriate. I can't even grok how the RubyGems executable handles I/O, so I'll yield to other people on how difficult that actually is. ([lib/rubygems/user_interaction.rb](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/user_interaction.rb) seems to be a big part of it, but I can't figure out how exactly it all goes together.)

**Comment by swrobel** [comment]
This seems more relevant in light of the [recent vulnerabilities](https://www.ruby-lang.org/en/news/2017/08/29/multiple-vulnerabilities-in-rubygems/), and considering the Bundler [implemented this feature](https://github.com/bundler/bundler/blob/v1.15.4/lib/bundler/cli.rb#L653)

**Comment by duckinator** [comment]
thanks for the nudge, @swrobel! I've got a bit too much on my plate right now to take it up myself, but I brought it up on Slack and hopefully someone else can at least figure out a plan for it.

**Comment by segiddins** [comment]
@swrobel I see what you did there ;)

I've got my hands quite full at the moment, and as I've said elsewhere, I personally consider this a "nice to have" rather than a necessity, but it might happen some day. Hopefully someone else beats me to it
