### ISSUE TITLE
Just published gem, can't install

### ISSUE THREAD

**Issue by jcoyne** [rubygems/rubygems#1622]
I'm having a problem.

My current problem is I published my gem curation_concerns 1.0.0.beta4.  It shows up on the web here:
https://rubygems.org/gems/curation_concerns/versions/1.0.0.beta4  When I try to install it I get an error message:

```
$ gem install curation_concerns -v 1.0.0.beta4
ERROR:  Could not find a valid gem 'curation_concerns' (= 1.0.0.beta4) in any repository
ERROR:  Possible alternatives: curation_concerns
```

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.5.1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by jcoyne** [comment]
I just noticed that there's presently an open incident: https://status.rubygems.org/incidents/trjgn655nf6b Possibly related?

**Comment by segiddins** [comment]
Yup, this has just been resolved! Please try installing again :)

**Comment by jcoyne** [comment]
Works now. 😄
