### ISSUE TITLE
bash tab completion

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#1627]
There are plenty queries to "rubygems bash tab completion" over the internet. There is one scrip suggested in rubygems help [1], there are thread with various suggestions on StackOverflow [2], Debian (used to) ships some custom bash completion script for RubyGems [3].

But since RubyGems are using OptionParser and since OptionParser is providing basic support for bash (and zsh) completion, I was thinking if you would consider PR with this simple script:

``` bash
#!/bin/bash
# Completion for bash:
#
# (1) install this file,
#
# (2) load the script, and
#      . ~/.profile.d/rubygems_completion_optparse.bash

_rubygems_optparse() {
  _get_comp_words_by_ref words cur cword

  if [[ $cword -gt 1 ]]; then 
    COMPREPLY=($("${words[0]}" "${words[1]}" "--*-completion-bash=${cur}"))
  fi

  return 0
} && complete -o default -F _rubygems_optparse gem
```

Although it does not complete everything, it might suggest at least the parameters for specific commands, e.g.:

```
$ bin/gem help --<tab><tab>
--backtrace     --config-file   --debug         --help          --[no-]verbose  --quiet         
$ bin/gem help --
```

Not sure where it should be placed and how it could be installed thought, but I am pretty sure that it would be useful for all RubyGems users.

There are also other options, such as ask bash-compleiton upstream [4] to ship this file. Not really sure where to start, so I chose this way. Thx for your feedback.

[1] http://help.rubygems.org/discussions/suggestions/40-bash-completion-script-for-1810
[2] http://stackoverflow.com/questions/902542/unable-to-find-a-tab-completion-for-rubygem-in-bash-zsh
[3] https://sources.debian.net/src/rubygems/1.8.24-1/debian/etc/bash_completion.d/gem1.8/
[4] https://github.com/scop/bash-completion/

**Comment by voxik** [comment]
Actually, this would need bash-completion package to have some macros available, so COMP_WORDS, COMP_CWORD, etc should be used instead.

**Comment by djberg96** [comment]
My gut tells me this should be a plugin.

**Comment by voxik** [comment]
Plugin? I can't see how plugin would do that. But for the start, it could be nice if the bash completion script was stored in upstream repository and the support was acknowledged by upstream (at least on the basic level, that some test case is executed in test suite, I don't thing anything fancier is necessary).

**Comment by segiddins** [comment]
I don't think we want to maintain this ourselves, sorry

**Comment by voxik** [comment]
That is a pity. You let everybody to invent again and again their own code completion .... I can create my own repository, but it will't hardly become the canonical source of code completion for RubyGems.
