### ISSUE TITLE
Different behaviour of fetch and install with platform specific gems

### ISSUE THREAD

**Issue by toy** [rubygems/rubygems#1629]
When checking how rubygems behave with platform specific gems, I've noticed different behaviour of fetch and install commands. Given my platform is `x86_64-darwin-15`, using geminabox and given there are originally following gems uploaded:
- abc-0.1.0
- abc-0.1.0-darwin
- abc-0.1.0-x86_64-darwin
- abc-0.1.0-x86_64-darwin-14
- abc-0.1.0-x86_64-darwin-15

I fetched/installed a gem, then removed the one that was fetched/installed from server and repeated.
For install the order was:
- abc-0.1.0-darwin
- abc-0.1.0-x86_64-darwin
- abc-0.1.0-x86_64-darwin-15
- abc-0.1.0
- ERROR:  Could not find a valid gem 'abc' (>= 0) …

For fetch the order was:
- abc-0.1.0-x86_64-darwin-15
- abc-0.1.0
- abc-0.1.0-x86_64-darwin
- abc-0.1.0-darwin
- ERROR:  Could not find a valid gem 'abc' (>= 0) …

This issue is related to:
- [ ] Network problems
- [ ] Installing a library
- [ ] Publishing a library
- [x] The command line `gem`
- [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.4
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
@toy is this still an issue for you, i apologize for not looking at this earlier :sweat_smile:

**Comment by MSP-Greg** [comment]
@bronzdoc

This issue may be something similar to PR #2312, in that RubyGems is doing odd things when a gem has several platform releases.  I didn't know that some Darwin gems were pre-compiled...

**Comment by toy** [comment]
@bronzdoc Rechecked using ruby 2.4.4, rubygems 2.7.7 on darwin 16, besides need to change 14/15 to 15/16 the behaviour is still identical

**Comment by MSP-Greg** [comment]
@toy

I'm a Windows type, and know almost nothing about MacOS.  Using your first 'group',  which gems can be properly installed on your system?

On Windows, the first gem `abc-0.1.0` would be `platform ruby`, and only one of the additional gems would match.  Would more than one match on MacOS?

Thanks, Greg

**Comment by toy** [comment]
@MSP-Greg The issue is most probably not related to MacOS, the only special thing about platforms is that there are darwin versions (darwin-14, darwin-15, …). All installed/fetched gems can be installed, x86_64-darwin-15 is the most specific platform.
For 64 bit windows platform the example would be with: `abc-0.1.0`, `abc-0.1.0-mingw32`, `abc-0.1.0-x64-mingw32` and I would expect the order to be:
- `abc-0.1.0-mingw32`, `abc-0.1.0-x64-mingw32`, `abc-0.1.0` for install
- `abc-0.1.0`, `abc-0.1.0-x64-mingw32`, `abc-0.1.0-mingw32` for fetch

**Comment by toy** [comment]
Stumbled upon this issue and wanted to check if it is still there, so created a gist with instructions to reproduce the issue: https://gist.github.com/toy/782815df91eb99cfe5884dd25803f792

**Comment by deivid-rodriguez** [comment]
Awesome @toy thanks so much, thanks makes it much easier to fix!

**Comment by deivid-rodriguez** [comment]
@toy I think #5037 fixes it, although I'm having a hard time writing a regression test.

**Comment by toy** [comment]
@deivid-rodriguez I've checked in a docker image and the order for install and fetch is the same, thanks for fixing this

**Comment by deivid-rodriguez** [comment]
No problem, thanks for your helpful report!
