### ISSUE TITLE
:authenticate_user! login problem

### ISSUE THREAD

**Issue by shwetasinghgosal** [rubygems/rubygems#1630]
I'm having a problem or would like to suggest a feature.

My current problem is devise :authenticate_user. As my website was working well but when i am implementing the gem "stripe" and install the bundle. After it stop working devise :authenticate_user.
Also, i revert back the code. But it is giving me the same problem. 

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
PASTE HERE
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
I don't see how this is a rubygems issue.
