### ISSUE TITLE
C-API change by the Integer unification 

### ISSUE THREAD

**Issue by nobu** [rubygems/rubygems#1637]
Although we have unified `Fixnum` and `Bignum` in the trunk, there still are `rb_cFixnum` and `rb_cBignum` C-level variables.
Now we will going to remove these variables at the preview release planed in the next week.
Please see the [patch] for the whole code.
With this change, `optional/capi/constants_spec.rb` will fail because of compilation errors.
I think this patch can fix the errors themselves, but am uncertain what guard should be in `optional/capi/constants_spec.rb`.
Any ideas?

```diff
diff --git a/optional/capi/ext/rubyspec.h b/optional/capi/ext/rubyspec.h
index fe42ac6..9a256e4 100644
--- a/optional/capi/ext/rubyspec.h
+++ b/optional/capi/ext/rubyspec.h
@@ -123,12 +123,16 @@
 
 /* Constants */
 #define HAVE_RB_CARRAY                     1
+#ifndef RUBY_INTEGER_UNIFICATION
 #define HAVE_RB_CBIGNUM                    1
+#endif
 #define HAVE_RB_CCLASS                     1
 #define HAVE_RB_CDATA                      1
 #define HAVE_RB_CFALSECLASS                1
 #define HAVE_RB_CFILE                      1
+#ifndef RUBY_INTEGER_UNIFICATION
 #define HAVE_RB_CFIXNUM                    1
+#endif
 #define HAVE_RB_CFLOAT                     1
 #define HAVE_RB_CHASH                      1
 #define HAVE_RB_CINTEGER                   1
```

[patch]: https://github.com/ruby/ruby/compare/trunk...nobu:bug/12427-integer-unification
This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by nobu** [comment]
For the time being, I added backward macros in `include/ruby/backward.h`.
I'll remove them as soon as the test is fixed.

**Comment by segiddins** [comment]
I'm sorry, but I'm not seeing what this has to do with RubyGems?

**Comment by hsbt** [comment]
@nobu Did you mistake to post to `ruby/spec` repository?

**Comment by nobu** [comment]
Exactly.
Sorry.
