### ISSUE TITLE
gem install bundler-1.9.3.gem makes outbound network call

### ISSUE THREAD

**Issue by Amit-PivotalLabs** [rubygems/rubygems#1640]
I'm having a problem or would like to suggest a feature.

My current problem is I'm trying to understand how `gem install` works, specifically in the context of having the `.gem` file provided as an argument.  More specifically, I want to understand why `gem` is making a network call to `https://api.rubygems.org/api/v1/dependencies?gems=bundler` when the gemspec inside the `.gem` file should contain all that information.

When running `gem install` with the `--local` flag, it doesn't make the network call, but I'm trying to understand why it does make the network call without the flag.  My understanding is the flag just ensures that it only tries to install local gems, but for determining dependencies of a `.gem` file it seems natural for it to refer to the internal metadata, not go to rubygems.org.

This issue is related to:

  - [x] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.2.5
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Hi @Amit-PivotalLabs this is a known issue, you can read more about here https://github.com/rubygems/rubygems/issues/816
