### ISSUE TITLE
Config check / Update configparser.

### ISSUE THREAD

**Issue by dopykuh** [rubygems/rubygems#1642]
I would like to suggest a feature.

My current problem is that the config parser (gemrc) differs between symbols and stings.
Wouldn't it be possible to add a command to check the config for unknown keys and also don't differ between symbols and strings.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

**Comment by drbrain** [comment]
The present situation is:

* Top-level Symbol keys are used for RubyGems settings.
* Top-level String keys are used to provide default options to RubyGems commands.
* Arbitrary RubyGems commands can be added through the plugin system.

RubyGems could check for commands (String keys) that aren't installed presently, but those keys may be valid if a plugin is installed.

RubyGems could check for settings (Symbol keys) that aren't recognized by the current version.

I don't think there's a maintainable, backward-compatible way to make RubyGems not care about String vs Symbol keys.  Allowing you to write either may cause collisions between settings and commands.

Changing the schema of the .gemrc means RubyGems must be able to understand both (which is more code to maintain).

Changing the schema of the .gemrc means new .gemrc can't be understood by old RubyGems (making graceful rollback of upgrades complicated for our users).
