### ISSUE TITLE
no_proxy activates if the no_proxy env var is the closing substring of the hostname

### ISSUE THREAD

**Issue by wadetandy** [rubygems/rubygems#1643]
I would like to suggest bug fix.

Today I discovered that even when a proxy is set correctly in the environment via `ENV['http_proxy']`, if `ENV['no_proxy']` includes a value that is the trailing substring of the rubygems host being accessed, the no proxy logic will have a false match and the proxy will be disabled silently for the request.  This causes the request to hang until timeout and was quite hard to debug.  It turns out in my case an environment configuration error had set `no_proxy=,example.com`, so the comma split included an empty string, but the broader issue still exists.

I have pushed up a branch with two failing tests demonstrating the problem: https://github.com/wadetandy/rubygems/tree/no_proxy_substring

This issue is related to:
- [ ] Network problems
- [X] Installing a library
- [ ] Publishing a library
- [ ] The command line `gem`
- [ ] Other

**Comment by gavinB-orange** [comment]
Simply having a leading comma in no_proxy is sufficient to mess up your proxy setup.

gavin@ibb1:~$ export no_proxy=localhost,127.0.0.1
gavin@ibb1:~$ gem list --remote | wc -l
131151
gavin@ibb1:~$ export no_proxy=,localhost,127.0.0.1
gavin@ibb1:~$ gem list --remote | wc -l
ERROR:  SSL verification error at depth 0: self signed certificate (18)
ERROR:  Certificate /CN=FG3K6C3A15800008/O=Fortinet Ltd. is not trusted
1

gavin@ibb1:~$ gem --version
2.6.12

Other tools do not interpret the empty string as a match for everything (curl, wget, ...) so this is particularly hard to debug.

**Comment by wadetandy** [comment]
As far as I can tell, this was _intended_ to solve the ability to no_proxy domain segments (AKA dev.example.com gets no proxy applied when no_proxy=example.com). However instead of breaking these up by `.` chars and applying some array math, the current approach does simple substring analysis.  In addition to an empty value from a leading or trailing comma causing a wildcard noproxy, noproxy=google.com would also cause definitelynotgoogle.com to get noproxied too, which is almost certainly incorrect.

**Comment by segiddins** [comment]
A pull request fixing this would be greatly appreciated 🚀
I'm not so familiar with how these env vars are supposed to be interpreted
