### ISSUE TITLE
gem uninstall --platform does not work

### ISSUE THREAD

**Issue by ermaker** [rubygems/rubygems#1656]
I want to uninstall with specifying platform and the help message says it is possible, but it does not work.
I also checked the latest rubygems source and it seems not to support --platform option.
Does not `uninstall` command support `--platform` option, yet?

```sh
> gem uninstall --help
Usage: gem uninstall GEMNAME [GEMNAME ...] [options]

  Options:

... omitted

    -v, --version VERSION            Specify version of gem to uninstall
        --platform PLATFORM          Specify the platform of gem to uninstall
        --vendor                     Uninstall gem from the vendor directory.
                                     Only for use by gem repackagers.

... omitted
```

```sh
> gem list ffi

*** LOCAL GEMS ***

ffi (1.9.10 ruby x86-mingw32)

> gem uninstall ffi --platform x86-mingw32

Select gem to uninstall:
 1. ffi-1.9.10
 2. ffi-1.9.10-x86-mingw32
 3. All versions
>
```

Here are my current environment details:

- Windows XP SP3

```sh
> ruby -v
ruby 2.0.0p648 (2015-12-16) [i386-mingw32]
> gem env version
2.6.6
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
So the issue is that `--platform` just _adds_ the platform to the list of platforms, so the ruby platform gem still matches (https://github.com/rubygems/rubygems/blob/ccb9c3300c063f5b5656669972d24a10ef8afbf5/lib/rubygems/version_option.rb#L35)

**Comment by drbrain** [comment]
The current `--platform` behavior is not useful even though it has behaved this same way since `--platform` was introduced:

```
$ GEM_HOME=~/tmp/gems GEM_PATH=~/tmp/gems gem list ffi

*** LOCAL GEMS ***

ffi (1.9.11 ruby x86-mingw32)

$ GEM_HOME=~/tmp/gems GEM_PATH=~/tmp/gems gem uninstall ffi 

Select gem to uninstall:
 1. ffi-1.9.11
 2. ffi-1.9.11-x86-mingw32
 3. All versions
> ^CERROR:  Interrupted

$ GEM_HOME=~/tmp/gems GEM_PATH=~/tmp/gems gem uninstall ffi --platform x86-mingw32

Select gem to uninstall:
 1. ffi-1.9.11
 2. ffi-1.9.11-x86-mingw32
 3. All versions
> 
```

**Comment by ermaker** [comment]
@segiddins @drbrain 
Thank you for easy explanation. That is exactly what I want to explain.

**Comment by VincentZhao** [comment]
Looks like this issue still exists in 2.6.7.

**Comment by segiddins** [comment]
@VincentZhao please open a new issue with steps to reproduce. Thanks!

**Comment by dloco01** [comment]
work thank you very much
