### ISSUE TITLE
gemspec: platform-dependent dependencies leading to inconsistent builds

### ISSUE THREAD

**Issue by HoneyryderChuck** [rubygems/rubygems#1662]
My current problem is :

I create this gemspec where I define multiple dependencies, one of them depending of `redcarpet`, which doesn't build on jruby. I've been naively setting it in the gemspec like this:

``` ruby
# mygem.gemspec
spec.add_runtime_dependency "md2man" unless RUBY_PLATFORM == "java"

# in my code, I require on a need basis:
require 'binman/rakefile' unless RUBY_PLATFORM == "java"
```

This works mostly in development mode, but breaks as soon as I install the gem on other projects. 
- If the `gem build` is performed with CRuby, `md2man` will be tagged as package dependency, and installing the gem won't work for jruby. 
- If the `gem build` is performed with JRuby, `md2man` will be missing from the package dependencies, and that `require` will fail in runtime. 

What is the proper way for setting platform-dependent dependencies in the gemspec?

This issue is related to:
- [ ] Network problems
- [x] Installing a library
- [x] Publishing a library
- [x] The command line `gem`
- [ ] Other

**Comment by segiddins** [comment]
Adding conditionals in your gem spec won't work -- it's eval'ed once and then re-serialized. You'll want to create platform-specific gems for your gem that has different dependencies

**Comment by TiagoCardoso1983** [comment]
and how do I do that?

**Comment by bronzdoc** [comment]
@HoneyryderChuck is this still and issue for you?

**Comment by HoneyryderChuck** [comment]
@bronzdoc I don't know, jumped out of that project... but what is the solution? `spec.platform=`? I've also been waiting for feedback since.

**Comment by bronzdoc** [comment]
@HoneyryderChuck  yes

http://guides.rubygems.org/specification-reference/#platform=
