### ISSUE TITLE
Please advise on openssl rubygem

### ISSUE THREAD

**Issue by mbailey** [rubygems/rubygems#1663]
I created [openssl rubygem](https://rubygems.org/gems/openssl/versions/0.2.0) to [verify a security vulnerability](http://help.rubygems.org/discussions/suggestions/7892-reporting-abuse-on-openssl).

I was pleased to see rubygems.org respond by [reserving core libs namespaces](https://github.com/rubygems/rubygems.org/issues/1155).

I have been contacted by people wanting me to transfer ownership of the gem. I'm not in a position to verify the authenticity or appropriateness of these requests. I don't know the parties involved personally.

**I would love for rubygems.org to take openssl rubygem away from my control**. 

You guys can take full responsibility for who controls this gem. I don't want to personally take any actions in regard to this Gem for security reasons.

**Comment by bronzdoc** [comment]
Hi @mbailey this issue correspond to https://github.com/rubygems/rubygems.org please submit it there, thanks!
