### ISSUE TITLE
gem install stops after full disk error

### ISSUE THREAD

**Issue by marko-avlijas** [rubygems/rubygems#1664]
I  have installed Gemfile for one of older versions of rails tutorials and ran out of disk space in process.
After making space, I got greeted with this message:

```
ERROR:  Error installing childprocess:
invalid gem: package metadata is missing in /home/marko/.gem/ruby/2.1.9/cache/childprocess-0.5.9.gem
```

Problem was that cached .gem file had file size 0. It fixed itself after I deleted all 0 size files in cache dir. Gem should automatically reload files in cache if they are 0 size or corrupt. Or at least ask you to do so.

**Comment by duckinator** [comment]
Potential solution:

Running out of disk space while writing to disk should raise an exception. RubyGems could catch that exception, and remove the guaranteed-invalid file and abort the command it's currently executing*. This would avoid creating the invalid files to start with.

<br>


\* major bonus points for completely reverting changes, but that is a VERY hard problem to solve correctly.

**Comment by djberg96** [comment]
It looks like this is coming from the `Gem::Package#verify_files` method, but I haven't narrowed it down further yet.

**Comment by marko-avlijas** [comment]
Best fix would be to make it so that before any file is downloaded, free disk space check is performed and operation is aborted with error message if there is not enough disk space to download the file.

That wouldn't leave users investigating why their gem files are corrupt and finding out 0 size file, then eventually figuring out that they ran out of disk space.

**Comment by djberg96** [comment]
@marko-avlijas That's hard to do in a cross-platform manner.

**Comment by tjouan** [comment]
Even if we ignore the cross-platform issue, I think it would be impossible to
solve this by checking "free disk space":

* we cannot "lock" the file system, so after checking available space, by the
  time you install there would be more or less available space than during the
  check;
* we cannot know how much space will take a gem before actually installing it;
* some file systems won't report available space, or a dummy one.

And some other file system particularities might complicate things too (quotas,
reserved space etc…), or even some aspects related to gems (C extension).

I would favor detecting the error and handling it like suggested by @duckinator
here:
https://github.com/rubygems/rubygems/issues/1664#issuecomment-253108573

**Comment by duckinator** [comment]
Looks like this is still reproducible.

I put a 128MB flash drive into my system, filled it most of the way up, then tried to reproduce. 

Version information:

```
/run/media/puppy/A87B-A154$ ruby --version
ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
/run/media/puppy/A87B-A154$ bundle --version
Bundler version 2.0.2
/run/media/puppy/A87B-A154$ gem --version
3.0.6
/run/media/puppy/A87B-A154$ 
```

Logs of reproducing it:

```
/run/media/puppy/A87B-A154$ du -sh .
120M    .
/run/media/puppy/A87B-A154$ GEM_HOME=. gem install inq
Fetching inq-26.0.0.gem
ERROR:  While executing gem ... (Errno::ENOSPC)
    No space left on device @ io_write - /run/media/puppy/A87B-A154/inq-26.0.0.gem
/run/media/puppy/A87B-A154$ rm a # this is the file filling the drive
/run/media/puppy/A87B-A154$ GEM_HOME=. gem install inq
ERROR:  Error installing inq:
        invalid gem: package is corrupt, exception while verifying: undefined method `size' for nil:NilClass (NoMethodError) in /run/media/puppy/A87B-A154/inq-26.0.0.gem
```

**Comment by duckinator** [comment]
Looks like this is still a problem.

Ran a similar testcase, on Windows 10.

```
PS F:\> ruby --version
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x64-mingw-ucrt]
PS F:\> gem --version
3.3.7
PS F:\> bundle --version
Bundler version 2.3.16
PS F:\> $Env:GEM_HOME = "F:\"
PS F:\> gem install boop
Fetching boop-0.5.0.gem
#<Thread:0x00000268af365d20 C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/request_set.rb:167 run> terminated with exception (report_on_exception is true):
C:/Ruby31-x64/lib/ruby/3.1.0/rubygems.rb:775:in `write': No space left on device @ io_write - F:/boop-0.5.0.gem (Errno::ENOSPC)
        from C:/Ruby31-x64/lib/ruby/3.1.0/rubygems.rb:775:in `block in write_binary'
        from C:/Ruby31-x64/lib/ruby/3.1.0/rubygems.rb:790:in `block in open_file'
        from C:/Ruby31-x64/lib/ruby/3.1.0/rubygems.rb:783:in `open'
        from C:/Ruby31-x64/lib/ruby/3.1.0/rubygems.rb:783:in `open_file'
        from C:/Ruby31-x64/lib/ruby/3.1.0/rubygems.rb:774:in `write_binary'
        from C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/remote_fetcher.rb:292:in `cache_update_path'
        from C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/remote_fetcher.rb:146:in `download'
        from C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/source.rb:215:in `download'
        from C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/resolver/specification.rb:112:in `download'
        from C:/Ruby31-x64/lib/ruby/3.1.0/rubygems/request_set.rb:173:in `block (2 levels) in install'
ERROR:  While executing gem ... (Errno::ENOSPC)
    No space left on device @ io_write - F:/boop-0.5.0.gem
PS F:\> gem install boop
ERROR:  Error installing boop:
        invalid gem: package metadata is missing in F:/boop-0.5.0.gem
PS F:\>
```

**Comment by duckinator** [comment]
Opened a PR for this: #5681.
