### ISSUE TITLE
test failures with umask 027

### ISSUE THREAD

**Issue by znz** [rubygems/rubygems#1665]
I built `ruby-trunk` and run `test-all` with `umask 027`.
Then some tests failed.
And `test/rubygems` has 6 failures.

See [full log on gist](https://gist.github.com/znz/687916a42f477347f63990d56babc3ea).

**Comment by bronzdoc** [comment]
@znz is this still and issue?

**Comment by segiddins** [comment]
Seems like those tests just need to set (explicit) permissions on the files they create

**Comment by bronzdoc** [comment]
WIll close this since is not a rubygems issue
