### ISSUE TITLE
Bundler in setup_command causes problems with rvm

### ISSUE THREAD

**Issue by Hanmac** [rubygems/rubygems#1679]
hi i am doing ```rvm reinstall ruby-head``` to rebuild my ruby again, but i got problems which i can narrow to this commit: https://github.com/rubygems/rubygems/commit/19a4b103b941571fe8fac9717754be285724f4eb

i causes this log output:
```
ruby-head - #installing rubygems-0b6befedc9ef63b20d4264de081fca5a6d8ac018.
Error running 'env GEM_HOME=/usr/local/rvm/gems/ruby-head@global GEM_PATH= /usr/local/rvm/rubies/ruby-head/bin/ruby -d /usr/local/rvm/src/rubygems-0b6befedc9ef63b20d4264de081fca5a6d8ac018/setup.rb --no-document',
showing last 15 lines of /usr/local/rvm/log/1470068129_ruby-head/rubygems.install.log
[2016-08-01 18:22:38] /usr/local/rvm/rubies/ruby-head/bin/ruby
current path: /usr/local/rvm/src/rubygems-0b6befedc9ef63b20d4264de081fca5a6d8ac018
GEM_HOME=/usr/local/rvm/gems/ruby-head
PATH=/usr/local/rvm/gems/ruby-head/bin:/usr/local/rvm/gems/ruby-head@global/bin:/usr/local/rvm/rubies/ruby-head/bin:/usr/local/rvm/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin
GEM_PATH=/usr/local/rvm/gems/ruby-head:/usr/local/rvm/gems/ruby-head@global
command(7): env GEM_HOME=/usr/local/rvm/gems/ruby-head@global GEM_PATH= /usr/local/rvm/rubies/ruby-head/bin/ruby -d /usr/local/rvm/src/rubygems-0b6befedc9ef63b20d4264de081fca5a6d8ac018/setup.rb --no-document
Exception `LoadError' at /usr/local/rvm/rubies/ruby-head/lib/ruby/2.4.0/rubygems.rb:1344 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /usr/local/rvm/rubies/ruby-head/lib/ruby/2.4.0/rubygems.rb:1353 - cannot load such file -- rubygems/defaults/ruby
Exception `Gem::MissingSpecError' at /usr/local/rvm/rubies/ruby-head/lib/ruby/2.4.0/rubygems/dependency.rb:308 - Gem::MissingSpecError
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ dir_chdir - bundler/lib
```

updating rvm or ruby itself does not seems to solve the problem.

**Comment by asvechkar** [comment]
ruby-head - #removing old rubygems.........
ruby-head - #installing rubygems-0b6befedc9ef63b20d4264de081fca5a6d8ac018.
Error running 'env GEM_HOME=/home/deploy/.rvm/gems/ruby-head@global GEM_PATH= /home/deploy/.rvm/rubies/ruby-head/bin/ruby -d /home/deploy/.rvm/src/rubygems-0b6befedc9ef63b20d4264de081fca5a6d8ac018/setup.rb --no-document',
showing last 15 lines of /home/deploy/.rvm/log/1470088636_ruby-head/rubygems.install.log
[2016-08-02 01:02:41] /home/deploy/.rvm/rubies/ruby-head/bin/ruby
current path: /home/deploy/.rvm/src/rubygems-0b6befedc9ef63b20d4264de081fca5a6d8ac018
GEM_HOME=/home/deploy/.rvm/gems/ruby-2.0.0-p353
PATH=/home/deploy/.rvm/gems/ruby-2.0.0-p353/bin:/home/deploy/.rvm/gems/ruby-2.0.0-p353@global/bin:/home/deploy/.rvm/rubies/ruby-2.0.0-p353/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/home/deploy/.rvm/bin:/home/deploy/.rvm/bin
GEM_PATH=/home/deploy/.rvm/gems/ruby-2.0.0-p353:/home/deploy/.rvm/gems/ruby-2.0.0-p353@global
command(7): env GEM_HOME=/home/deploy/.rvm/gems/ruby-head@global GEM_PATH= /home/deploy/.rvm/rubies/ruby-head/bin/ruby -d /home/deploy/.rvm/src/rubygems-0b6befedc9ef63b20d4264de081fca5a6d8ac018/setup.rb --no-document
Exception `LoadError' at /home/deploy/.rvm/rubies/ruby-head/lib/ruby/2.4.0/rubygems.rb:1344 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /home/deploy/.rvm/rubies/ruby-head/lib/ruby/2.4.0/rubygems.rb:1353 - cannot load such file -- rubygems/defaults/ruby
Exception `Gem::MissingSpecError' at /home/deploy/.rvm/rubies/ruby-head/lib/ruby/2.4.0/rubygems/dependency.rb:308 - Gem::MissingSpecError
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ dir_chdir - bundler/lib
deploy@209354-10001:~$ env GEM_HOME=/home/deploy/.rvm/gems/ruby-head@global GEM_PATH= /home/deploy/.rvm/rubies/ruby-head/bin/ruby -d /home/deploy/.rvm/src/rubygems-0b6befedc9ef63b20d4264de081fca5a6d8ac018/setup.rb --no-document
Exception `LoadError' at /home/deploy/.rvm/rubies/ruby-head/lib/ruby/site_ruby/2.4.0/rubygems.rb:1353 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /home/deploy/.rvm/rubies/ruby-head/lib/ruby/site_ruby/2.4.0/rubygems.rb:1362 - cannot load such file -- rubygems/defaults/ruby
Exception `Gem::MissingSpecError' at /home/deploy/.rvm/rubies/ruby-head/lib/ruby/site_ruby/2.4.0/rubygems/dependency.rb:308 - Gem::MissingSpecError
/home/deploy/.rvm/rubies/ruby-head/bin/ruby: No such file or directory -- setup.rb (LoadError)
deploy@209354-10001:~$

**Comment by JonasFromell** [comment]
Is there any workaround for this issue? Just installed RVM and got this error installing ruby-2.2-head. Tried to run bundle -v afterwards, not working.

**Comment by segiddins** [comment]
How are you installing RubyGems?

**Comment by Hanmac** [comment]
@segiddins who do you mean? we both try to install ruby using rvm, but the change with bundler does causes the install to crash when it does try to install rubygems

**Comment by segiddins** [comment]
Right, but as far as I know these changes haven't been upstreamed into Ruby Core yet

**Comment by Hanmac** [comment]
@segiddins as you can see above i try ```rvm reinstall ruby-head```
to get recent ruby, rvm seems to try to get recent rubygems too.

thats why i seems to be affected by it, even if it's not yet upstreamed into ruby core.

**Comment by segiddins** [comment]
How is rvm pulling rubygems and setting it up? Since just running `make install` from ruby won't do this

**Comment by Hanmac** [comment]
it happens in the doing when it does try to make a gemset
causing this function to be called:

https://github.com/rvm/rvm/blob/master/scripts/functions/rubygems#L171

and this is the output i got.
```
ruby-head - #downloading rubygems-a3135463508de3c33b94fc028400c3c04e2ad3f9
ruby-head - #extracting rubygems-a3135463508de3c33b94fc028400c3c04e2ad3f9.....
ruby-head - #removing old rubygems.........
ruby-head - #installing rubygems-a3135463508de3c33b94fc028400c3c04e2ad3f9.
Error running 'env GEM_HOME=/usr/local/rvm/gems/ruby-head@global GEM_PATH= /usr/local/rvm/rubies/ruby-head/bin/ruby -d /usr/local/rvm/src/rubygems-a3135463508de3c33b94fc028400c3c04e2ad3f9/setup.rb --no-document',
showing last 15 lines of /usr/local/rvm/log/1470844147_ruby-head/rubygems.install.log
[2016-08-10 17:55:39] /usr/local/rvm/rubies/ruby-head/bin/ruby
current path: /usr/local/rvm/src/rubygems-a3135463508de3c33b94fc028400c3c04e2ad3f9
GEM_HOME=/usr/local/rvm/gems/ruby-head
PATH=/usr/local/rvm/gems/ruby-head/bin:/usr/local/rvm/gems/ruby-head@global/bin:/usr/local/rvm/rubies/ruby-head/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin:/usr/local/rvm/bin
GEM_PATH=/usr/local/rvm/gems/ruby-head:/usr/local/rvm/gems/ruby-head@global
command(7): env GEM_HOME=/usr/local/rvm/gems/ruby-head@global GEM_PATH= /usr/local/rvm/rubies/ruby-head/bin/ruby -d /usr/local/rvm/src/rubygems-a3135463508de3c33b94fc028400c3c04e2ad3f9/setup.rb --no-document
Exception `LoadError' at /usr/local/rvm/rubies/ruby-head/lib/ruby/2.4.0/rubygems.rb:1344 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /usr/local/rvm/rubies/ruby-head/lib/ruby/2.4.0/rubygems.rb:1353 - cannot load such file -- rubygems/defaults/ruby
Exception `Gem::MissingSpecError' at /usr/local/rvm/rubies/ruby-head/lib/ruby/2.4.0/rubygems/dependency.rb:308 - Gem::MissingSpecError
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ dir_chdir - bundler/lib

```

**Comment by segiddins** [comment]
It looks like RVM is downloading the tgz from github, which isn't really supported (and is breaking since that doesn't include the necessary bundler submodule)

**Comment by madman3** [comment]
I currently have the exact problem stated above. Is there a solution proposed? @Hanmac, did you figure something out? Would appreciate the help. This is how my output looks like 

`ruby-2.3-head-rubygems - #installing rubygems-ba332a8e32438df6fa48bb839b4ead2bffd7d42f.
Error running 'env GEM_HOME=/Users/Suniltejs/.rvm/gems/ruby-2.3-head-rubygems@global GEM_PATH= /Users/Suniltejs/.rvm/rubies/ruby-2.3-head-rubygems/bin/ruby -d /Users/Suniltejs/.rvm/src/rubygems-ba332a8e32438df6fa48bb839b4ead2bffd7d42f/setup.rb --no-document',
showing last 15 lines of /Users/Suniltejs/.rvm/log/1471465748_ruby-2.3-head-rubygems/rubygems.install.log
[2016-08-17 22:34:00] /Users/Suniltejs/.rvm/rubies/ruby-2.3-head-rubygems/bin/ruby
current path: /Users/Suniltejs/.rvm/src/rubygems-ba332a8e32438df6fa48bb839b4ead2bffd7d42f
PATH=/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/bin:/usr/sbin:/sbin:/usr/local/bin:/opt/local/bin:/opt/local/sbin:/usr/local/git/bin:/Users/Suniltejs/.rvm/bin:/opt/local/bin
command(7): env GEM_HOME=/Users/Suniltejs/.rvm/gems/ruby-2.3-head-rubygems@global GEM_PATH= /Users/Suniltejs/.rvm/rubies/ruby-2.3-head-rubygems/bin/ruby -d /Users/Suniltejs/.rvm/src/rubygems-ba332a8e32438df6fa48bb839b4ead2bffd7d42f/setup.rb --no-document
Exception `LoadError' at /Users/Suniltejs/.rvm/rubies/ruby-2.3-head-rubygems/lib/ruby/2.3.0/rubygems.rb:1241 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /Users/Suniltejs/.rvm/rubies/ruby-2.3-head-rubygems/lib/ruby/2.3.0/rubygems.rb:1250 - cannot load such file -- rubygems/defaults/ruby
Exception `LoadError' at /Users/Suniltejs/.rvm/rubies/ruby-2.3-head-rubygems/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55 - cannot load such file -- did_you_mean
Exception `LoadError' at /Users/Suniltejs/.rvm/rubies/ruby-2.3-head-rubygems/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:132 - cannot load such file -- did_you_mean
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ dir_chdir - bundler/lib`

**Comment by Hanmac** [comment]
@madman3: no, not yet.

I think we need to notify @rvm that's their fault.

**Comment by madman3** [comment]
I actually just wanted a ruby version that was 2+. So, I ended up removing all the rubies I had and just installed ruby 2.2

**Comment by bronzdoc** [comment]
Closing since this is not a rubygems problem.

**Comment by havenwood** [comment]
Should support for RubyGems installation from the shipped tarball really be dropped?

**Comment by havenwood** [comment]
I'm being told the Github autogenerated tarball wasn't ever meant for installation so that answers my question. It's interesting that it's been installed from the Github release by RVM for years and seemingly worked.

**Comment by indirect** [comment]
@havenwood RubyGems has always been released and distributed as a gem. We do not create those tarballs ourselves, and they are not official releases. If RVM decides they want to use GitHub tarballs, they are of course able to do that, but we aren't going to suddenly start supporting GitHub tarballs now just because RVM is having problems with them. Sorry. :/

**Comment by goldWave** [comment]
i have got the same issues With use " rvm install ruby-head"


No checksum for downloaded archive, recording checksum in user configuration.
ruby-head - #extracting rubygems-78bc3b8a6816a74a82e617a0fd65777816d844af - please wait
ruby-head - #removing old rubygems - please wait
ruby-head - #installing rubygems-78bc3b8a6816a74a82e617a0fd65777816d844af - please wait
Error running 'env GEM_HOME=/Users/zhangxiaoping/.rvm/gems/ruby-head@global GEM_PATH= /Users/zhangxiaoping/.rvm/rubies/ruby-head/bin/ruby -d /Users/zhangxiaoping/.rvm/src/rubygems-78bc3b8a6816a74a82e617a0fd65777816d844af/setup.rb --no-document',
showing last 15 lines of /Users/zhangxiaoping/.rvm/log/1481706381_ruby-head/rubygems.install.log
Exception `LoadError' at /Users/zhangxiaoping/.rvm/rubies/ruby-head/lib/ruby/2.4.0/rubygems.rb:1345 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /Users/zhangxiaoping/.rvm/rubies/ruby-head/lib/ruby/2.4.0/rubygems.rb:1354 - cannot load such file -- rubygems/defaults/ruby
Exception `Gem::MissingSpecError' at /Users/zhangxiaoping/.rvm/rubies/ruby-head/lib/ruby/2.4.0/rubygems/dependency.rb:308 - Gem::MissingSpecError
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ dir_chdir - bundler/lib

**Comment by drbrain** [comment]
You need to tell @rvm to use [official tarballs](https://rubygems.org/pages/download) when installing RubyGems.
