### ISSUE TITLE
gem install --user-install doesn't work with native extensions

### ISSUE THREAD

**Issue by ttarczynski** [rubygems/rubygems#1680]
I'm having a problem.
My current problem is: 
`gem install --user-install` and `gem install --build-root` doesn't work for gems with native extensions (when run as non-root user):
```
$ /opt/sensu/embedded/bin/gem install --no-ri --no-rdoc --user-install unf_ext
WARNING:  You don't have /home/jenkins/.gem/ruby/2.3.0/bin in your PATH,
          gem executables will not run.
Building native extensions.  This could take a while...
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ dir_s_mkdir - /opt/sensu/embedded/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/unf_ext-0.0.7.2
```
```
$ /opt/sensu/embedded/bin/gem install --no-ri --no-rdoc --build-root /home/jenkins/ unf_ext
WARNING:  You build with buildroot.
  Build root: /home/jenkins
  Bin dir: /home/jenkins/opt/sensu/embedded/bin
  Gem home: /home/jenkins/opt/sensu/embedded/lib/ruby/gems/2.3.0
Building native extensions.  This could take a while...
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ dir_s_mkdir - /opt/sensu/embedded/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/unf_ext-0.0.7.2
```
Both these commands try to mkdir and put some files in the `/opt/sensu/embedded/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0` dir rather than in user's home.

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ /opt/sensu/embedded/bin/ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
$ /opt/sensu/embedded/bin/gem env version
2.6.6
$ echo $PATH
/opt/sensu/embedded/bin/:/usr/local/bin:/bin:/usr/bin:/usr/local/sbin:/usr/sbin:/home/jenkins/.local/bin:/home/jenkins/bin
```
I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by ttarczynski** [comment]
I've tried some troubleshooting:
* added write permissions to see what files are put in the wrong dir:
```
# chmod 777 /opt/sensu/embedded/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0
```
installations succeeded:
```
$ /opt/sensu/embedded/bin/gem install --no-ri --no-rdoc --user-install unf_ext
Fetching: unf_ext-0.0.7.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed unf_ext-0.0.7.2
1 gem installed
```
files put in the wrong dir:
```
$ ls -la /opt/sensu/embedded/lib/ruby/gems/2.3.0/extensions/x86_64-linux/2.3.0/unf_ext-0.0.7.2/
total 1160
drwxrwxr-x. 2 jenkins jenkins    4096 Aug  8 09:21 .
drwxrwxrwx. 7 root    root       4096 Aug  8 09:21 ..
-rw-rw-r--. 1 jenkins jenkins       0 Aug  8 09:21 gem.build_complete
-rw-rw-r--. 1 jenkins jenkins    1094 Aug  8 09:21 gem_make.out
-rw-rw-r--. 1 jenkins jenkins    1954 Aug  8 09:21 mkmf.log
-rwxr-xr-x. 1 jenkins jenkins 1168472 Aug  8 09:21 unf_ext.so
```
----
* I've also tried applying the patch from PR #1661 and it seems to fix the issue:

now `gem install --user-install` works OK
```
$ /opt/sensu/embedded/bin/gem install --no-ri --no-rdoc --user-install unf_ext
Fetching: unf_ext-0.0.7.2.gem (100%)
Building native extensions.  This could take a while...
Successfully installed unf_ext-0.0.7.2
1 gem installed
```
and native extension files are installed in `~/.gem/ruby/2.3.0/extensions/x86_64-linux/2.3.0/unf_ext-0.0.7.2/`
```
$ ls -l /home/jenkins/.gem/ruby/2.3.0/extensions/x86_64-linux/2.3.0/unf_ext-0.0.7.2/
total 1152
-rw-rw-r--. 1 jenkins jenkins       0 Aug  8 09:58 gem.build_complete
-rw-rw-r--. 1 jenkins jenkins    1085 Aug  8 09:58 gem_make.out
-rw-rw-r--. 1 jenkins jenkins    1954 Aug  8 09:58 mkmf.log
-rwxr-xr-x. 1 jenkins jenkins 1168472 Aug  8 09:58 unf_ext.so
```

**Comment by coderanger** [comment]
I did some digging, the issue seems to be that the Specification object used for building doesn't have `loaded_from` set so it falls back to using `Gem.dir` instead of seeing the installed non-ext gem files and using that as the install location for the extension.

**Comment by coderanger** [comment]
This was caused by https://github.com/rubygems/rubygems/commit/39fe061ea3c7b652d907b4ff48b657c374164632, by expanding `spec.extension_dir` before `loaded_from` gets set right below that, it gets `||=` cached and never re-checked. I think right fix is to move the `loaded_from setting` above the directory removal/creation step.

**Comment by godfat** [comment]
@coderanger Could you please create a pull request for that? Or I could verify and do that later.
