### ISSUE TITLE
Running 'bundle' command fails to build gems with native extensions with rubygems above version 2.6.4

### ISSUE THREAD

**Issue by RogerE** [rubygems/rubygems#1687]
Running the 'bundle' command for a rails project in my development environment(ubuntu vagrant instance) fails for me if a gem with native extensions should be installed.

For instance:
```
Installing byebug 9.0.5 with native extensions

Errno::EACCES: Permission denied @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.2.0/extensions/x86_64-linux/2.2.0-static/byebug-9.0.5
```
Using bundler 1.12.5.
Happens with rubygems 2.6.5 and 2.6.6, downgrading rubygems to version 2.6.4 solves the issue.

--------------------

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.5
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
This ought to be fixed when running against master

**Comment by RogerE** [comment]
Thanks, great to hear that you already fixed it. 

Not sure how to install rubygems from master, but no a problem, 2.6.4 works for me. My motivation for reporting it was that I spent a lot of time figuring out what the problems was after installing a fresh system and wanted to prevent the same from happening to others.

**Comment by segiddins** [comment]
Probably the easiest way is to clone RubyGems and set `RUBYOPT=-I/path/to/rubygems/lib` while running your `bundle` command

**Comment by RogerE** [comment]
Jepp,
working when running against master. Thanks.
