### ISSUE TITLE
Proposal: Update gem cert to support strong cryptography

### ISSUE THREAD

**Issue by sdaubert** [rubygems/rubygems#1688]
I would like to suggest an enhancement on gem cert command.

My current problem is gem cert uses weak algorithms:
- SHA-1 is considered weak since 2005, and real attacks arises,
- RSA private key is 2048 bits long, which should be safe for a use until 2030, but some cryptologists recommend 3072-bits keys. Another choice is to use ECDSA 256-bits keys

This issue is related to:
- [ ] Network problems
- [ ] Installing a library
- [ ] Publishing a library
- [X] The command line `gem`
- [ ] Other

Firstly, I think it would be better to use SHA-256 or SHA-384 instead of SHA-1.
Secondly, RSA key length should be 3072 bits.

This proposition is for new generated keys and new signatures. Of course, rubygems should continue to support RSA+SHA-1 to verify today gems. This should be easy as certificate contains algorithms used to sign.

If you are OK with this proposal, I will try to do a PR.

**Comment by segiddins** [comment]
@tarcieri thoughts on this?

**Comment by tarcieri** [comment]
SHA-256 should definitely be used, as SHA-1 is weak.

As @sdaubert said, most key length recommendations suggest RSA-2048 can be considered secure until at least 2030 if not 2040. See e.g.:

https://infoscience.epfl.ch/record/164539/files/NPDF-32.pdf

![screen shot 2016-08-17 at 10 25 31 am](https://cloud.githubusercontent.com/assets/797/17746468/042ce010-6465-11e6-83ff-9b8c44696b1f.png)

Up to you if you want to change it.

**Comment by sdaubert** [comment]
Ok, I will update to SHA-2 and RSA-3072.

**Comment by segiddins** [comment]
Closed by #1691.

**Comment by djberg96** [comment]
Yay!
