### ISSUE TITLE
Please improve this error message: "Invalid byte sequence in UTF-8" It does not tell me much at all

### ISSUE THREAD

**Issue by shevegen** [rubygems/rubygems#1689]
I have rewritten a gem of mine (studium).

```
https://rubygems.org/gems/studium
```

I am trying to push this gem right now but this has failed.

The error was:

"
    ERROR:  While executing gem ... (ArgumentError)
        invalid byte sequence in UTF-8
    gem push *.gem
    ERROR:  While executing gem ... (Gem::Package::FormatError)
            package metadata is missing in studium-0.0.261.gem
"

This unfortunately does not tell me anything at all.

Could ruby gem itself be more specific about this error in 
particular where it happens? I also bundle some text
files that are not .rb files. They contain ISO Umlauts
and are NOT stored in UTF. I do not know if there
are any other .rb files that have invalid UTF characters
but the thing is - with the above error message, I am
sorry, I simply do not know what is happening and
WHERE the error happens.

Please allow me to help you help me so I can fix this
problem - but without gem itself telling me where it
found the error and how, I have no way to find out.

**Comment by shevegen** [comment]
I found the culprit.

It were indeed the non .rb files, plain text files which are stored in non UTF.

I assume that gem itself repackages everything to be UTF-8. Hmmm.

I guess I will distribute these files separately via ftp. But it is still a bit strange.

I never had some error message like that with "tar" command.

**Comment by segiddins** [comment]
RubyGems should be packaging all of the gem's file in the `.gem` tar as binary, so this seems to me like an issue

**Comment by segiddins** [comment]
Out of curiosity, can you share an example gem that reproduces this issue? Thanks!

**Comment by duckinator** [comment]
@shevegen is there somewhere I can download the file that caused the issue?
