### ISSUE TITLE
Constant timeouts with rubygems.global.ssl.fastly.net - Gitlab.com CI / DigitalOcean

### ISSUE THREAD

**Issue by Nowaker** [rubygems/rubygems#1701]
I've recently migrated from Codeship to GitLab.com's internal CI and most of the time the build won't pass due to `Errno::ETIMEDOUT` from rubygems.global.ssl.fastly.net. The application I build consists of multiple git submodules, each having their own Gemfile, so there's a lot of deps to download. So many that my chances for a successful build are quite small. There's no particular gem that doesn't download - there's always *some* gem that won't download. Examples from three different builds:

```
Gem::RemoteFetcher::FetchError: Errno::ETIMEDOUT: Connection timed out - connect(2) for "rubygems.global.ssl.fastly.net" port 443 (https://rubygems.org/gems/web-console-2.2.1.gem)
```
```
Gem::RemoteFetcher::FetchError: Errno::ETIMEDOUT: Connection timed out - connect(2) for "rubygems.global.ssl.fastly.net" port 443 (https://rubygems.org/gems/tilt-2.0.1.gem)
```
```
Gem::RemoteFetcher::FetchError: Errno::ETIMEDOUT: Connection timed out - connect(2) for "rubygems.global.ssl.fastly.net" port 443 (https://rubygems.org/gems/rack-protection-1.5.3.gem)
```

Quote from #557 by @drbrain:

> ETIMEDOUT indicates there is a problem with your network connection, probably with your local machine. Please check for a firewall or other configuration change you made.

[GitLab.com CI uses DigitalOcean for builds](https://about.gitlab.com/2016/04/19/gitlab-partners-with-digitalocean-to-make-continuous-integration-faster-safer-and-more-affordable/), as seen in the build log below, so "problem with local network connection" is out of question. Everyone uses DigitalOcean. Docker image used for the build is Docker's official [ruby:2.2.2](https://hub.docker.com/_/ruby/) - here's the [Dockerfile](https://github.com/docker-library/ruby/blob/2d6449f03976ededa14be5cac1e9e070b74e4de4/2.2/Dockerfile).

```
Running on runner-30dcea4b-project-1582107-concurrent-0 via runner-30dcea4b-machine-1472325066-7915ab81-digital-ocean-4gb...
```

Here's some debug info:
```
$ gem env version
2.4.8
```

Anything else you need?

**Comment by Nowaker** [comment]
Other person complaining about the same thing too at Gitlab's support forum. https://gitlab.com/gitlab-com/support-forum/issues/994

**Comment by bronzdoc** [comment]
Hi @Nowaker please submit this to https://github.com/rubygems/rubygems.org thanks!
