### ISSUE TITLE
`gem install` doesn't use pre-compiled extensions for universal-darwin platform as expected

### ISSUE THREAD

**Issue by apolcyn** [rubygems/rubygems#1702]
My current problem is trouble with publishing a package containing pre-compiled native extensions, that can be used by `gem install` on OS X. We have published the grpc package on rubygems.org. (see https://rubygems.org/gems/grpc). This package contains native extensions. We have published packages that contain these extensions in pre-compiled form for different platforms, including the 'universal-darwin' platform.

The exact issue is:
1. `bundle install`, using a Gemfile containing a dependency on 'grpc', grabs the gem with pre-built binaries for the 'universal-darwin' platform as expected.
2. `gem install grpc`, however, attempts to compile the native extensions from source. 

More details of the issue on github are here: https://github.com/grpc/grpc/issues/7727

It's my understanding that the 'universal-darwin' platform should match my actual x86_64-darwin-15 platform, and should be used by gem, but this doesn't seem to be happening. I'm wondering if this differing behavior between gem and bundler is expected, or if there's something else we should be doing to let `gem install` just use the packages with pre-compiled extensions. Thanks in advance!

This issue is related to:
- [x] Installing a library
- [x] Publishing a library
- [x] The command line `gem`

Here are my current environment details:

```
$ gem env version
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.0 (2015-12-25 patchlevel 0) [x86_64-darwin15]
  - INSTALLATION DIRECTORY: /Users/apolcyn/.rvm/gems/ruby-2.3.0
  - USER INSTALLATION DIRECTORY: /Users/apolcyn/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /Users/apolcyn/.rvm/rubies/ruby-2.3.0/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/apolcyn/.rvm/gems/ruby-2.3.0/bin
  - SPEC CACHE DIRECTORY: /Users/apolcyn/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/apolcyn/.rvm/rubies/ruby-2.3.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-15
  - GEM PATHS:
     - /Users/apolcyn/.rvm/gems/ruby-2.3.0
     - /Users/apolcyn/.rvm/gems/ruby-2.3.0@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/apolcyn/cli/artifacts/osx.10.11-x64/stage2
     - /Users/apolcyn/.rvm/gems/ruby-2.3.0/bin
     - /Users/apolcyn/.rvm/gems/ruby-2.3.0@global/bin
     - /Users/apolcyn/.rvm/rubies/ruby-2.3.0/bin
     - /usr/local/git/current/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/local/sbin
     - /usr/sbin
     - /sbin
     - /usr/local/go/bin
     - /Library/Frameworks/Mono.framework/Versions/Current/Commands
     - /Users/apolcyn/.rvm/bin
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
When I run this on my Mac, I get the following:

```
Fetching: google-protobuf-3.0.0-universal-darwin.gem (100%)
Successfully installed google-protobuf-3.0.0-universal-darwin
Fetching: grpc-1.0.0-universal-darwin.gem (100%)
Successfully installed grpc-1.0.0-universal-darwin
2 gems installed
```

So I am unable to reproduce this issue

**Comment by djberg96** [comment]
@segiddins Were you using 2.5.1? @apolcyn Does it work if you upgrade to the latest rubygems version?

**Comment by segiddins** [comment]
@djberg96 I'm sure I was using whatever the latest released version or master was at the time

**Comment by apolcyn** [comment]
@segiddins after upgrading to rubygems 2.6.8 this now seems to work (`gem install grpc` now just fetches and installs the one for the universal-darwin platform). thanks!

**Comment by djberg96** [comment]
@apolcyn yay!

**Comment by ioquatix** [comment]
Sorry to necro-bump, but is there any documentation about how to actually release gems with pre-compiled native extensions?
