### ISSUE TITLE
https://rubygems.org/gems/ops_manager_cli namespace is taken

### ISSUE THREAD

**Issue by bonzofenix** [rubygems/rubygems#1704]
I'm having a problem.

My current problem is that I removed a gem from my personal rubygem account to move it to a corporate one. After using gemcutter the gem disappeared from my personal rubygems, but the namespace was not release.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [x] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Hi @bonzofenix please submit this to https://github.com/rubygems/rubygems.org thanks!
