### ISSUE TITLE
Add Core Infrastructure Iniative Best Practices badge

### ISSUE THREAD

**Issue by devonestes** [rubygems/rubygems#1707]
The Linux Foundation has their Core Infrastructure Initiative now to ensure that key open source projects are well taken care of and are following best practices that will help us avoid the next HeartBleed. One of the things that they've done is to create a badge that projects can put on their repos to show that they're following the best practices laid out by the foundation. This is currently missing from RubyGems, and I think it would be both a good thing to show to Rubygems users so they know that RubyGems is doing all it can to be safe and secure, as well as a good reason to do a quick survey to be sure that RubyGems is indeed meeting all these best practices 😉

More information about the badge can be found here: https://github.com/linuxfoundation/cii-best-practices-badge, including information about how to sign up to get the badge.

**Comment by indirect** [comment]
@devonestes Thanks for letting us know! You (or anyone else) is absolutely welcome to open a PR or issue about those best practices. 👍
