### ISSUE TITLE
session management

### ISSUE THREAD

**Issue by sunil797** [rubygems/rubygems#1710]
session are not expiring
steps to reproduce:
1.login to your account in two different browsers.
2.now change your password in one of the browser and go to other browser and refresh it.
3.you will see that the account in other browser is not expiring,leading to session takeover.
thanks!

**Comment by segiddins** [comment]
This seems to be an issue with https://github.com/rubygems/rubygems.org rather than the client-side CLI to rubygems

**Comment by simi** [comment]
Just to notice, I tried this now and I was logged out of second browser (where I wasn't changing my password).
