### ISSUE TITLE
gem install ERROR

### ISSUE THREAD

**Issue by amanmehta-maniac** [rubygems/rubygems#1712]
I'm having a problem 

My current problem is "Unable to download data from https://rubygems.org/ - no such name (https://api.rubygems.org/specs.4.8.gz"

This issue is related to:

  - [x] The command line `gem`

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
This repository did not handle infrastructure issue. Please submit to https://github.com/rubygems/rubygems.org/issues
