### ISSUE TITLE
Feature Request: Add ability to resign key with gem cert command

### ISSUE THREAD

**Issue by djberg96** [rubygems/rubygems#1720]
It would be nice if I could resign my key with the "gem cert" command instead of generating a new one.

I'm not that familiar with key signing, but looking at Gem::Security::Signer, I see a re_sign_key method, so I'm guess that it's possible.

Could we add a "-R/--resign" (or whatever) option to the gem cert command that would do this?

**Comment by drbrain** [comment]
Right now this happens automatically if the certificate expires.

**Comment by djberg96** [comment]
@drbrain How does the resigning happen? I have a gem with a key signed September 2, 2015. When I try to create a gem using that pubkey, it fails with this:

```
>rake gem:create
Enter PEM pass phrase:
rake aborted!
Gem::Security::Exception: certificate /CN=djberg96/DC=gmail/DC=com not valid after 2016-09-01 20:49:18 UTC
```

Where the `gem:create` task is:

    task :create => [:clean] do
      require 'rubygems/package'
      spec = eval(IO.read('sys-cpu.gemspec'))
      spec.signing_key = File.join(Dir.home, '.ssh', 'gem-private_key.pem')
      Gem::Package.build(spec, true)
    end

**Comment by drbrain** [comment]
Hrm, I guess this is a case I missed.  There's a [test for the signer with an expired key](https://github.com/rubygems/rubygems/blob/master/test/rubygems/test_gem_security_signer.rb#L135-L141) but not one for the Gem::Package.

**Comment by djberg96** [comment]
@drbrain Ok, so this is a bug then? I wonder if it should at least emit a notification/warning that the key was resigned when that happens.

**Comment by bronzdoc** [comment]
@djberg96 are you still interedted in this?

**Comment by djberg96** [comment]
@bronzdoc Yes, please.

**Comment by djberg96** [comment]
@bronzdoc Ah, I wasn't aware of the rule, thanks. Your suggestion sounds perfect.

**Comment by djberg96** [comment]
Fixed by https://github.com/rubygems/rubygems/pull/2380, thanks!
