### ISSUE TITLE
Docs / comments for Gem::InstallerTestCase#setup

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#1740]
The comments for [Gem::InstallerTestCase#setup](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/installer_test_case.rb#L69-L87) have a blank line between them (line 76).  This causes [RDoc](http://docs.seattlerb.org/rubygems/Gem/InstallerTestCase.html#method-i-setup) & [YARD](http://www.rubydoc.info/github/rubygems/rubygems/Gem/InstallerTestCase#setup-instance_method) to miss the first section of comments.

Would it be considered appropriate to join these two sections at line 76?

I'd submit a PR, but won't bother if no one will accept it.  Also, I haven't looked around to see how (or if) this repo 'connects' to the files at ruby/ruby...

Greg

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
A PR adding a # to that line would be great, thanks!
