### ISSUE TITLE
Certificate error on windows

### ISSUE THREAD

**Issue by SavaNDragos** [rubygems/rubygems#1750]
Latest installer for windows is having:
PS C:\WINDOWS\system32> gem install hiera-eyaml
ERROR:  Could not find a valid gem 'hiera-eyaml' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

Can you guys fix it or line by line explain how to solve it.

**Comment by JanJoris** [comment]
I had the same issue. [This](https://github.com/rubygems/rubygems/issues/1745#issuecomment-253739579) comment fixed it for me.

**Comment by bubulemaster** [comment]
Thanks @JanJoris commet work for me also.

But what is this problem ? Why always here ?

**Comment by SavaNDragos** [comment]
The problem is kind of ugly when stuff are done automatically, take the case of puppet; This issues makes from rubygems a headache on windows.

**Comment by duckinator** [comment]
Hi!

Are y'all still having this problem?

If so, can you make sure you're on RubyGems 2.6.8 (`gem update --system`), then try again + tell us any errors it generates? And can you also provide the output of `gem env`?

Thanks!

**Comment by SavaNDragos** [comment]
Hi guys,

I went with "Bash on windows" the new feature from windows 10 and yeahhh no certificate issues. It actually uses the ruby for linux 👍 .
The reality is: the bug is still there, because the certificates needs to work by default. A workaround should't be part of a puppet recepy.
You can close the ticket if you want. 

Thanks,
Dragos

**Comment by duckinator** [comment]
Closing because everyone reporting an issue in this thread has reported resolving it in some way, and there are other issues related to the certificate errors on Windows (#1757, #1769).
