### ISSUE TITLE
Activation error on `rake newb` with clean checkout

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems#1754]
It's impossible to run `rake newb` with a clean checkout of master on the latest Ruby and RubyGems. Here's an example:

```
$ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]

$ gem -v
2.6.7

$ gem list rake

*** LOCAL GEMS ***

rake (10.4.2)

$ gem list hoe

*** LOCAL GEMS ***

hoe (3.15.2)
hoe-seattlerb (1.3.5)

$ rake newb
git submodule update --init
rake aborted!
Gem::LoadError: can't activate rake-10.5.0, already activated rake-10.4.2
/Users/andre.arko/.gem/ruby/2.3.1/gems/hoe-3.15.2/lib/hoe/deps.rb:60:in `rescue in block in check_extra_deps_task'
/Users/andre.arko/.gem/ruby/2.3.1/gems/hoe-3.15.2/lib/hoe/deps.rb:54:in `block in check_extra_deps_task'
/Users/andre.arko/.gem/ruby/2.3.1/gems/hoe-3.15.2/lib/hoe/deps.rb:53:in `each'
/Users/andre.arko/.gem/ruby/2.3.1/gems/hoe-3.15.2/lib/hoe/deps.rb:53:in `check_extra_deps_task'
/Users/andre.arko/.gem/ruby/2.3.1/gems/hoe-3.15.2/lib/hoe/deps.rb:43:in `block in define_deps_tasks'
Gem::MissingSpecVersionError: Could not find 'rake' (~> 10.5) - did find: [rake-10.4.2]
Checked in 'GEM_PATH=/Users/andre.arko/.gem/ruby/2.3.1:/opt/rubies/2.3.1/lib/ruby/gems/2.3.0', execute `gem env` for more information
/Users/andre.arko/.gem/ruby/2.3.1/gems/hoe-3.15.2/lib/hoe/deps.rb:55:in `block in check_extra_deps_task'
/Users/andre.arko/.gem/ruby/2.3.1/gems/hoe-3.15.2/lib/hoe/deps.rb:53:in `each'
/Users/andre.arko/.gem/ruby/2.3.1/gems/hoe-3.15.2/lib/hoe/deps.rb:53:in `check_extra_deps_task'
/Users/andre.arko/.gem/ruby/2.3.1/gems/hoe-3.15.2/lib/hoe/deps.rb:43:in `block in define_deps_tasks'
Tasks: TOP => newb => check_extra_deps
(See full trace by running task with --trace)
```

It is possible to work around this problem by manually and explicitly installing `rake` at version `~> 10.5`. Maybe we can automate that?

```
$ gem install rake -v '~> 10.5'
Successfully installed rake-10.5.0
1 gem installed

$ rake newb
git submodule update --init
Parsing sources...
100% [183/183]  lib/ubygems.rb

Generating Darkfish format into /Users/andre.arko/workspace/rubygems/rubygems/doc...
[...]
```

**Comment by segiddins** [comment]
@indirect what version of hoe do you have installed? Can you try updating it? Thanks!

**Comment by indirect** [comment]
@segiddins I ran `gem install hoe` immediately before running `rake newb`. It installed `hoe-3.15.2`. As far as I can tell, that's the newest version.

**Comment by segiddins** [comment]
Any objects to me adding binstubs, then?

**Comment by indirect** [comment]
@segiddins do it, I guess.

**Comment by duckinator** [comment]
What would binstubs for this look like? And where would they go?

**Comment by segiddins** [comment]
We'd probably move `bin/gem` to `exe` and add binstubs in `bin` like Bundler has

**Comment by alyssais** [comment]
Hey, I've been trying to set up a development environment so I can make a PR, and have also run into this problem, except explicitly installing Rake doesn't help because the Rake that comes with my Ruby installation takes precedence.

I'd love to be able to contribute — is there anything I could do to help move this along and make that possible? :)

**Comment by duckinator** [comment]
@alyssais hey! glad you want to contribute. I'll try to get this handled ASAP. :)

@segiddins you said "like Bundler has," but looking at [Bundler's bin/rake](https://github.com/bundler/bundler/blob/master/bin/rake), it looks like it relies on Bundler's gemspec. But RubyGems doesn't _have_ a gemspec because it uses Hoe. Any ideas on how to deal with that?

**Comment by segiddins** [comment]
Hmm. Extract the gemspec-generating part into a second file the binstubs can load?

**Comment by duckinator** [comment]
hmm, okay. that's what I was thinking, too. I'll take a look into doing that in a bit.

**Comment by indirect** [comment]
@alyssais you can work around this in the meantime by running `rake _10.0.3_ newb` (replace the version number in between the underscores with the version that you need to run).

**Comment by alyssais** [comment]
@indirect awesome, thanks!

**Comment by wilson** [comment]
@segiddins Re: "Extract the gemspec-generating part", do you mean from Hoe or from RubyGems?
I'm happy to come back with a patch that does either, just wondering what the ideal should look like.

**Comment by colby-swandale** [comment]
@wilson Hey, great timing i've been working on solving this issue as well if you would like to help 👍 

I've made a PR @ #1983 if you would like to start adding to it

**Comment by duckinator** [comment]
Hi, I just wanted to drop a note here that if you're comfortable working with Docker, you can use the [rgdev gem](https://github.com/duckinator/rgdev#usage) I made until this is properly resolved!

If you have trouble using that, you can [open an issue on the rgdev repo](https://github.com/duckinator/rgdev/issues).

**Comment by duckinator** [comment]
As of https://github.com/rubygems/rubygems/pull/2160 , Hoe is no longer being used.

I'm working on a PR for a `rake newb` replacement, but for now you can do:

```
$ git clone https://github.com/rubygems/rubygems.git
$ cd rubygems
$ git submodule update --init
$ gem install rake 'builder:~> 2.1' 'rdoc:~> 4.0' 'minitest:~> 5.0'
$ rake test
```
