### ISSUE TITLE
WARN: Unresolved specs during Gem::Specification.reset

### ISSUE THREAD

**Issue by roberts1000** [rubygems/rubygems#1756]
Others have already mentioned this, but I'm still running into the `WARN: Unresolved specs during Gem::Specification.reset` and haven't found a resolution.  I'm developing a gem which has a executable defined at `exe/foo`.  (The gem project was initially created by running `bundle my_gem`.)

If I `cd` out of the gem directory, then run `my_gem/exe/foo`, the command works great.  There are no warnings.  

If I `cd` back into the directory and install the gem by doing

```
rake build
gem install pkg/my_gem....
```

when I execute `foo`, I get

```
WARN: Unresolved specs during Gem::Specification.reset:
      minitest (~> 5.1)
      mime-types (< 4, >= 1.16)
      rake (>= 0.8.7)
```

On my system, I have the following gem versions installed

```
minitest (5.9.1, 5.8.3, 4.7.5)
mime-types (3.1, 1.25.1)
rake (11.3.0, 10.5.0, 10.4.2)
```

All the recommendations for dealing with this issue suggest removing the old gem versions.  **This doesn't solve the real issue - why is RubyGems (or maybe bundler) having problems identifying the correct dependent gem?**

I've poked around trying to figure out what is causing the issue.  In the gem's .gemspec file, I have the following line

``` ruby
spec.add_development_dependency "rake", "~> 11.0"
```

I tried changing it to

``` ruby
spec.add_dependency "rake", "~> 11.0"
```

When I reinstall the gem and run the command, `rake` drops off the warning list!

Another thing I noticed, when I open the Gemfile.lock inside the gem and look at all of the gems that generate warnings, there's nothing that should be caussing ambiguity.  Take the `rake` gem for example.  Gemfile.lock has

``` ruby
GEM
  specs:
    railties (5.0.0.1)
      rake (>= 0.8.7)
    rake (11.3.0)

DEPENDENCIES
rake (~> 11.0)
```

From that list, it should be clear that rake 11.3.0 is the best choice.

I don't have much knowledge about how RubyGems and Bundler might work together for a system command like the one I'm developing.  It doesn't seem like Bundler would be involved which means  Gemfile and the Gemfile.lock wouldn't be a factor.  But I can't say for sure because maybe RubyGems is smart enough to look at the Gemfile and Gemfile.lock in certain situations...

Here's my full gemspec dependency section:

``` ruby
  spec.add_development_dependency "bundler", "~> 1.12"
  spec.add_development_dependency "rake", "~> 11.0"
  spec.add_development_dependency "pry", "~> 0.10.1"
  spec.add_development_dependency "pry-byebug", "~> 3.4.0"
  spec.add_development_dependency "rspec-rails", "~> 3.5.1"
  spec.add_development_dependency "capybara", "~> 2.7.1"
  spec.add_development_dependency "factory_girl_rails", "~> 4.7.0"
  spec.add_development_dependency "puma", "~> 3.0"
  spec.add_development_dependency "pg", "0.19.0"
  spec.add_development_dependency "web-console", "~> 3.0"

  spec.add_dependency "thor", "0.19.1"
  spec.add_dependency "rails", "~> 5.0"
  spec.add_dependency "corelib_ruby", "~> 1.2"
  spec.add_dependency "autorequire_rails", "~> 1.0"
  spec.add_dependency "font-awesome-rails", "~> 4.6.3.0"
  spec.add_dependency 'bootstrap-sass', '3.3.7'
  spec.add_dependency "sass-rails", "~> 5.0.6"
```

I'm still not clear what warning message actually means, but it suggests RubyGems has no way to figure which version of the gem to load.  It seems like it has all the info it needs.

I'm currently using RubyGems 2.6.7 and bundler 1.13.5.

**Comment by segiddins** [comment]
Please share steps to reproduce

**Comment by roberts1000** [comment]
I created a simple sample gem in [this repo](https://github.com/roberts1000/unresolved_specs_sample_gem) which triggers the Warning.  Setup instructions are in the gem README.

**Comment by segiddins** [comment]
Thanks!

**Comment by segiddins** [comment]
It appears to be pry calling reset, so I'm not sure this is actually a bug -- the specs are unresolved because nothing has "forced" rubygems to resolve the dependencies to specific versions yet

```
reset!
/Users/segiddins/.rubies/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems.rb:841:in `refresh'
/Users/segiddins/.gem/ruby/2.3.1/gems/pry-0.10.4/lib/pry/plugins.rb:71:in `locate_plugins'
/Users/segiddins/.rubies/2.3.1/lib/ruby/2.3.0/forwardable.rb:189:in `locate_plugins'
/Users/segiddins/.gem/ruby/2.3.1/gems/pry-0.10.4/lib/pry/pry_class.rb:320:in `init'
/Users/segiddins/.gem/ruby/2.3.1/gems/pry-0.10.4/lib/pry/pry_class.rb:375:in `<top (required)>'
/Users/segiddins/.rubies/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
/Users/segiddins/.rubies/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
/Users/segiddins/.gem/ruby/2.3.1/gems/pry-0.10.4/lib/pry.rb:148:in `<top (required)>'
/Users/segiddins/.rubies/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `require'
/Users/segiddins/.rubies/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:133:in `rescue in require'
/Users/segiddins/.rubies/2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:40:in `require'
/Users/segiddins/.gem/ruby/2.3.1/gems/unresolved_specs_sample_gem-1.0.0/exe/sample_cmd:7:in `<top (required)>'
/Users/segiddins/.gem/ruby/2.3.1/bin/sample_cmd:22:in `load'
/Users/segiddins/.gem/ruby/2.3.1/bin/sample_cmd:22:in `<main>'
```

**Comment by roberts1000** [comment]
Thanks for taking a look.  I have a real gem at my company (on a private gem server) that has about a dozen dependencies specified in the gemspec file, include pry.  I had hoped I could just remove the `require pry` call since it's on there to help with debugging.  The warning message still appears so one of the other gems must be triggering it.

1. What command did you use to get that stack output? 
2. Is there a way to force rubygems to resolve the dependencies before I start requiring other gems?
3. I notice that as long as I execute `sample_cmd` from within the gem folder, the error doesn't appear.  Outside the gem folder I get the warning.  Do you have any insight into why that might be happening?

**Comment by segiddins** [comment]
I just edited rubygems to print out the `caller` in `Gem::Specification.reset`

**Comment by segiddins** [comment]
> I notice that as long as I execute sample_cmd from within the gem folder, the warning doesn't appear. Outside the gem folder I get the warning. Do you have any insight into why that might be happening?

My guess is that the transitive deps are being eagerly activated somehow

**Comment by ddoherty03** [comment]
I get this message as well after a gem is deployed and an executable is called outside the context of the source tree.  I have gems that use pry not just for development but as a user-facing feature.  Is that the problem?  Any fixes?

**Comment by ddoherty03** [comment]
I at least partially worked around this by deferring 'require pry' until needed by the console portion of my app.  It still does the reset message there, but at least not at the very outset of the app.

So, looks like this is a problem with pry.

Thanks, @segiddins for the traceback.

**Comment by thomasv314** [comment]
@ddoherty03 FWIW I'm also currently experiencing the same issue, also with pry. If you happen to come across a solution, I'd love to hear it!

**Comment by ddoherty03** [comment]
@thomasv314, the gem I was working on was an application that includes a "console" command that allows the user to invoke pry on the objects in the application for trouble-shooting purposes.  So, I had to include pry as a runtime gem, not just a development gem.  I had been putting `require 'pry'` at the startup of the application along with other requires.  I moved the require to inside the "console" command code, so I no longer have users getting the reset message at startup.  They still get it when the console command starts, but that is much rarerer.  So it attenuates, but does not eliminate, the problem.  Hope that helps.

**Comment by voltechs** [comment]
@ddoherty03 been having this issue myself. I ended up leveraging something like this https://gist.github.com/moertel/11091573 to create a helper for temporarily suppressing STDOUT and then I used it like so (I had a `Debug` singleton utility class that was relatively appropriate for housing the suppression since I also had things like `Debug.print` and `Debug.puts`)

```ruby
Debug.suppress do
  require 'pry'
end
```

Kinda wonky, but this way I don't have to decide when to or not to require pry simply for cosmetics.

**Comment by ddoherty03** [comment]
@voltechs, thanks for taking the time to post the tip.  It's a pretty good bandage!

**Comment by deivid-rodriguez** [comment]
Could someone help me out with reproducing this?

**Comment by deivid-rodriguez** [comment]
Oh, I'm sorry for the noise, there's a repro [here](https://github.com/rubygems/rubygems/issues/1756#issuecomment-255465073). I'll have a look.

**Comment by roberts1000** [comment]
Hi @deivid-rodriguez. This issue has disappeared for me over the years, but I tend to work in containers more these days so my environment has less "baggage" in it. I tried to reproduce the issue by downgrading various libraries, but couldn't find the magic combo. Someone on my team ran into an `Unresolved specs ...` error recently (while working with the same project I was using in the initial bug report) so there still may be anunderlying issue lurking. 

If I run into the issue again, I'll update this issue with more info. (If you like, we could close this issue until new information appears.)

**Comment by deivid-rodriguez** [comment]
Sure, since the repo in the comment I referenced is no longer available and you're not able to reproduce this anymore at the moment, let's close for now and update this once we have a repro or more info in general :+1:.

Thanks for getting back!
