### ISSUE TITLE
Error: While executing gem ... <Gem::RemoteFetcher::FetchError> SSL_connect retuned=1 errorno=0 state=SSlv3

### ISSUE THREAD

**Issue by rajasajidmanzoor** [rubygems/rubygems#1757]
I'm having a problem while creating a new site and running server.
Please see issues below

![image](https://cloud.githubusercontent.com/assets/5917783/19599217/1581498c-97b9-11e6-8214-da6d1ed813c4.png)

I have followed most of Stackoverflow and github guides but still issue persists. Please tell me how can fix this

I have ruby version 2.4.5.1 installed on my machine.

please help

**Comment by jeunito** [comment]
+1 getting this issue too even after following the guide [here](http://guides.rubygems.org/ssl-certificate-update/#manual-solution-to-ssl-issue)

**Comment by indirect** [comment]
Can you paste the output from `gem env`?

**Comment by sajiddesigner** [comment]
Here is my gem env output

![image](https://cloud.githubusercontent.com/assets/5917783/19720421/854000d4-9b87-11e6-9938-c56a00e23392.png)

and 

![image](https://cloud.githubusercontent.com/assets/5917783/19720437/8e5459cc-9b87-11e6-8f13-c45da3b556f1.png)

**Comment by segiddins** [comment]
Please paste the output instead of attaching screenshots

**Comment by sajiddesigner** [comment]
@segiddins  you no i can not copy message from Command prompt.

**Comment by lynnco** [comment]
@sajiddesigner http://www.howtogeek.com/howto/windows-vista/copy-to-the-clipboard-from-the-windows-command-prompt/

**Comment by sajiddesigner** [comment]
@lynnco  thx for sharing.
@segiddins  please check logs below.

    C:\Sites>gem env
    RubyGems Environment:
    - RUBYGEMS VERSION: 2.4.5.1
    - RUBY VERSION: 2.2.4 (2015-12-16 patchlevel 230)
    - INSTALLATION DIRECTORY: C:/RailsInstaller/Ruby2.
    - RUBY EXECUTABLE: C:/RailsInstaller/Ruby2.2.0/bin
    - EXECUTABLE DIRECTORY: C:/RailsInstaller/Ruby2.2.
    - SPEC CACHE DIRECTORY: C:/Users/sajid.manzoor/.ge
    - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
    - RUBYGEMS PLATFORMS:
     - ruby
     - x86-mingw32
    - GEM PATHS:
     - C:/RailsInstaller/Ruby2.2.0/lib/ruby/gems/2.2
     - C:/Users/sajid.manzoor/.gem/ruby/2.2.0
     - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://rubygems.org/", "http:/gems.org/"]
     - REMOTE SOURCES:
     - https://rubygems.org/
     - http://rubygems.org
     - http://rubygems.org/
     - SHELL PATH:
     - C:\RailsInstaller\Git\cmd
     - C:\RailsInstaller\Ruby2.2.0\bin
     - C:\RailsInstaller\Ruby2.2.0\lib\ruby\gems\1.9
     - C:\RailsInstaller\DevKit\bin
     - C:\ProgramData\Oracle\Java\javapath
     - C:\Windows\system32
     - C:\Windows
     - C:\Windows\System32\Wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0\
     - C:\Program Files\Intel\DMIX
     - C:\Program Files (x86)\Intel\OpenCL SDK\3.0\b
     - C:\Program Files (x86)\Intel\OpenCL SDK\3.0\b
     - C:\xampp\php
     - C:\ProgramData\ComposerSetup\bin
     - c:\Program Files (x86)\Microsoft SQL Server\1
     - c:\Program Files\Microsoft SQL Server\100\Too
     - c:\Program Files\Microsoft SQL Server\100\DTS
     - c:\Program Files\Microsoft SQL Server\110\Too
     - c:\Program Files (x86)\Microsoft SQL Server\1io\
     - c:\Program Files (x86)\Microsoft SQL Server\1
     - c:\Program Files (x86)\Microsoft SQL Server\1
     - C:\Program Files (x86)\Windows Kits\8.1\Windo
     - C:\Program Files\Git\cmd
     - C:\Program Files\Git\mingw64\bin
     - C:\Program Files\Git\usr\bin
     - C:\Program Files (x86)\Skype\Phone\
     - D:\xampp\php
     - D:\xampp\apache\bin
     - C:\Program Files\nodejs\
     - C:\Windows\system32\config\systemprofile\.dnx
     - C:\Program Files\Microsoft DNX\Dnvm\
     - C:\RailsInstaller\Git\cmd
     - C:\RailsInstaller\Ruby2.2.0\bin
     - C:\Users\sajid.manzoor\AppData\Roaming\npm`

**Comment by duckinator** [comment]
@sajiddesigner could you try upgrading to RubyGems 2.6.8 and trying again, letting us know what errors that generates? (2.6.8 adds better errors.)

You can do that with with `gem update --system`.

**Comment by luislavena** [comment]
@duckinator actually users cannot upgrade with `gem update --system` when already having the SSLv3 errors.

Instead, is better to recommend manual download of `.gem` and installation using `gem install --local`, from the SSL guides:

http://guides.rubygems.org/ssl-certificate-update/#installing-using-update-packages

Hope that helps.

**Comment by duckinator** [comment]
@luislavena ah! my bad. thanks for following up with that.

**Comment by colby-swandale** [comment]
@rajasajidmanzoor were you able to resolve your problem?

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
