### ISSUE TITLE
ruby gem install crashes when installation path is long

### ISSUE THREAD

**Issue by NarineM** [rubygems/rubygems#1760]
gem should support long paths > 120 characters.

My current problem is In my environment I install ruby in a location which has a long path (more than 130 characters long). When running ruby/bin/gem from a long path, it is crashing with "bad interpreter. " error.

This issue is related to:
- [ ] The command line `gem`

Here are my current environment details:

```
$ gem env version
2.4.5
```

Is this something that got already fixed in newer version may be? We are using ruby 2.2 at the moment and are thinking about updating it to 2.3.

**Comment by segiddins** [comment]
What is the full output of `gem env`?

**Comment by NarineM** [comment]
my env: (this is the env where I shorten the gem path to be less than 60 chars:

RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.5
  - RUBY VERSION: 2.2.0 (2014-12-25 patchlevel 0) [x86_64-linux]
  - INSTALLATION DIRECTORY: /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0
  - RUBY EXECUTABLE: /opt/microsoft/omsagent/ruby/bin/ruby
  - EXECUTABLE DIRECTORY: /opt/microsoft/omsagent/ruby/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /opt/microsoft/omsagent/ruby/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /opt/microsoft/omsagent/ruby/lib/ruby/gems/2.2.0
     - /root/.gem/ruby/2.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://rubygems.org/", "http://rubygems.org/"]
  - REMOTE SOURCES:
     - https://rubygems.org/
     - http://rubygems.org/
  - SHELL PATH:
     - /usr/kerberos/sbin
     - /usr/kerberos/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /sbin
     - /bin
     - /usr/sbin
     - /usr/bin
     - /root/bin

**Comment by segiddins** [comment]
Can you also share the full error of the exception, running with the `--debug` flag?

**Comment by NarineM** [comment]
It is crashing with "bad interpreter: No such file or directory" error and can not even load the gem installer so it does not even get to calling it with --debug option.

**Comment by NarineM** [comment]
Easy to repro in 2.2 ruby. Just try installing it under long path.

**Comment by drbrain** [comment]
We need full steps to reproduce because I am confused.

You say RubyGems doesn't work with long paths, but paste output of `gem env` above.

Example steps:

1. Install ruby v2.2.5 in `/tmp/1234567890…` via …
2. Run: `/tmp/1234567890…/bin/gem something`
3. Run: `/tmp/1234567890…/bin/…`
4. … (any other steps)

Expected: …

Actual: …

Please fill in all "…" above so we can reproduce this.

**Comment by bronzdoc** [comment]
@NarineM Please provide what @drbrain and @segiddins requested to reopen this issue, thanks.
