### ISSUE TITLE
Ruby 2.3.1 Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

### ISSUE THREAD

**Issue by stevelake** [rubygems/rubygems#1761]
I'm having a problem.

My current problem is failure to install new gems: I tried installing capybara, but got...
ERROR:  Could not find a valid gem 'capybara' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

I've looked at the article at https://gist.github.com/luislavena/f064211759ee0f806c88#installing-using-update-packages-new but when I tried to download the certificate (AddTrustExternalCARoot-2048.pem) I got a '404 - Not Found' error

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:
ruby 2.3.1p112 (2016-04-26 revision 54768) [i386-mingw32] running on Windows 10
```
$ gem env version
2.5.1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by stevelake** [comment]
I've fixed it: the comment by chris-morgan in issue #1745 about "Copying https://raw.githubusercontent.com/rubygems/rubygems/master/lib/rubygems/ssl_certs/index.rubygems.org/GlobalSignRootCA.pem" resolved it.

**Comment by jasontylerb** [comment]
@stevelake Thank you for sharing your fix! I'm new to Ruby and it took me a while to hunt down the fix for the SSL error. Again, thanks!

**Comment by carivera** [comment]
@stevelake Really appreciate, you shared this solution.
you saved me a couple of hours of digging the web.

Thanks!!

**Comment by neerajsoni87** [comment]
The solution is very Simple :) 
To connect without using SSL, edit your Gemfile sources and change 'https' to
'http'.

**Comment by dennisnderitu254** [comment]
Thank you

**Comment by leif81** [comment]
Another option is upgrading to Ruby 2.3.3, it worked without the error for me.

**Comment by vickenliu** [comment]
yeah. update ruby to 2.3.x resolve this issue.

**Comment by Nibin96** [comment]
I resolved this problem by following steps 
gem sources --remove https://rubygems.org/
gem sources --add http://rubygems.org
gem update --system
gem sources --remove http://rubygems.org
gem sources --add https://rubygems.org
