### ISSUE TITLE
state=SSLv3 read server certificate B: certificate verify failed 

### ISSUE THREAD

**Issue by DiegoCardonaFSD** [rubygems/rubygems#1764]
I'm having a problem or would like to suggest a feature.

My current problem is when try to install any gem

This issue is related to:
gem install compass

Here are my current environment details:
ERROR:  Could not find a valid gem 'rb-fsevent' (>= 0.9.3), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

**Comment by DiegoCardonaFSD** [comment]
I found this solucion(http://guides.rubygems.org/ssl-certificate-update/#manual-solution-to-ssl-issue), but didn't work for me

**Comment by duckinator** [comment]
Hi! Can you provide the output of `gem env`? Thanks!

**Comment by duckinator** [comment]
And could you also update to RubyGems 2.6.8 and try again, then tell us any errors it generates? 2.6.8 adds better SSL-related errors.

**Comment by luislavena** [comment]
@DiegoCardonaFSD please download the `.gem` file and install using `gem install --local`:

http://guides.rubygems.org/ssl-certificate-update/#installing-using-update-packages

**Comment by DiegoCardonaFSD** [comment]
@duckinator  @luislavena  This is my gem env result

RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.7
  - RUBY VERSION: 2.2.1 (2015-02-26 patchlevel 85) [x86_64-darwin14]
  - INSTALLATION DIRECTORY: /Users/diego0123/.rvm/gems/ruby-2.2.1
  - USER INSTALLATION DIRECTORY: /Users/diego0123/.gem/ruby/2.2.0
  - RUBY EXECUTABLE: /Users/diego0123/.rvm/rubies/ruby-2.2.1/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/diego0123/.rvm/gems/ruby-2.2.1/bin
  - SPEC CACHE DIRECTORY: /Users/diego0123/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-14
  - GEM PATHS:
     - /Users/diego0123/.rvm/gems/ruby-2.2.1
     - /Users/diego0123/.rvm/gems/ruby-2.2.1@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Applications/MAMP/bin/php/php5.6.7/bin/
     - /Users/diego0123/.rvm/gems/ruby-2.2.1/bin
     - /Users/diego0123/.rvm/gems/ruby-2.2.1@global/bin
     - /Users/diego0123/.rvm/rubies/ruby-2.2.1/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/git/bin
     - /Users/diego0123/.rvm/bin

**Comment by bronzdoc** [comment]
@DiegoCardonaFSD  this still an issue for you? did you try what @luislavena suggested?
