### ISSUE TITLE
gem help cert does not show -d/--days

### ISSUE THREAD

**Issue by djberg96** [rubygems/rubygems#1768]
`gem -v => 2.6.8`

The option to add -d/--days to `gem cert` was merged: https://github.com/rubygems/rubygems/issues/1719

But when I run `gem help cert` I see no reference to the new option. It does actually work in practice, though.

**Comment by bronzdoc** [comment]
@djberg96 this feature is not in 2.6.8 but will be in 2.7

**Comment by bronzdoc** [comment]
said that... idk how are you using that flag in 2.6.8 :thinking:

**Comment by djberg96** [comment]
@bronzdoc Didn't complain when I used the options:

```
dberger:~ >gem -v
2.6.8

dberger:~ >gem cert -b djberg96@gmail.com -d 1000
Passphrase for your Private Key:  

Please repeat the passphrase for your Private Key:  

Certificate: /Users/dberger/gem-public_cert.pem
Private Key: /Users/dberger/gem-private_key.pem
Don't forget to move the key file to somewhere private!
```

**Comment by bronzdoc** [comment]
Yeah it's weird, I just tested it, also I tested it passing the flags to rubygems 2.6.0 and still accepts the flags without crashing. This is something that has been there for a long time probably even before 2.6.0, so this seems to work in the current version but the functionality isn't there...

if you do:
```
pem = File.read("./gem-public_cert.pem")
cert = OpenSSL::X509::Certificate.new(pem)
```
and then inspect cert you will see `not_before` and `not_after` are a year apart still, even if you did something like `gem cert -b djberg96@xxx.com -d 1000`

**Comment by bronzdoc** [comment]
@djberg96 I investigated it a little more and it seems that `OptionParser` will try to match a single letter flag to any existing flag, e.g `-l` will match '--list' in this case since there's no flag that explicitly defines the behavior of `-d` it will match to `--debug` which is a common option in rubygems.

**Comment by djberg96** [comment]
@bronzdoc Ok, thanks for looking into that.
