### ISSUE TITLE
I can't able to install sass on my windows 10 pc using cli 

### ISSUE THREAD

**Issue by GNSubrahmanyam** [rubygems/rubygems#1770]
I can't able to install sass on my windows 10 pc using cli 
My Ruby & Gem Version 
```
ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]

gem -v
2.5.1

gem install sass
ERROR:  Could not find a valid gem 'sass' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)
```
Thank in Advance

**Comment by djberg96** [comment]
@GNSubrahmanyam Can you try `gem update --system` and see if it works after that?

**Comment by GNSubrahmanyam** [comment]
@djberg96 & @bronzdoc When I used ```gem update --system``` command. This command it pops out new error.
```
>gem update --system
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)
```

**Comment by bronzdoc** [comment]
@GNSubrahmanyam please download `rubygems-update-2.6.7.gem` and follow the guide:
http://guides.rubygems.org/ssl-certificate-update/#installing-using-update-packages

Report back if that fixed your problem or if any error pops after that, thanks!

**Comment by GNSubrahmanyam** [comment]
@bronzdoc Got this error when I used this command

```
>gem install --local C:\rubygems-update-2.6.7.gem
ERROR:  Could not find a valid gem 'C:\rubygems-update-2.6.7.gem' (>= 0) in any repository
```

**Comment by bronzdoc** [comment]
Make sure you are passing to `gem install --local` the correct path where you installed `rubygems-update-2.6.7.gem`

**Comment by andreluizreis** [comment]
@bronzdoc I had the same problem reported by @GNSubrahmanyam and your post solved my problem. Now I am able to install SASS. Thank you so much.  
![capture](https://cloud.githubusercontent.com/assets/8194164/20243348/cac1bb00-a921-11e6-9d31-c7cce35ef9d5.PNG)

![capture2](https://cloud.githubusercontent.com/assets/8194164/20243352/efa94e7e-a921-11e6-8e95-b7484b2c251f.PNG)

**Comment by bronzdoc** [comment]
That is great @andreluizreis !

@GNSubrahmanyam did the instructions solved your problem?

**Comment by azzazkhan** [comment]
Thanks worked perfectly!
1.) Installed Ruby Installer v2.1.9
2.) Installed MSYS2
3.) Installed the rubygems-update-2.6.7.gem file
See @bronzdoc comment for docs
4.) Read the docs and proceed with it
5.) Sass installed successfully! :grinning:
