### ISSUE TITLE
win7  modify the gem source,get an strange error

### ISSUE THREAD

**Issue by xcchcaptain** [rubygems/rubygems#1772]
on win7 modify the gem source to an mirror ,but get an strange error_  
C:\Users\Administrator>gem sources -a https://ruby.taobao.org/
ERROR:  While executing gem ... (Errno::EADDRNOTAVAIL)
    The requested address is not valid in its context. - sendto(2) for "\u0000"
port 53_______

This issue is related to:

  - [x] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
win7 64bit 
 ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by xcchcaptain** [comment]
i'm not a ruby developer
just want to get a development enviroment for sass 
,i really get nothing about the problem from google , maybe the problem is about my system,any help will be appreciate!
i checked the port ,but get nothing be taked on port 53
i opened  a vpn ,is it matter?

**Comment by tschoening** [comment]
Port 53 is DNS, so this in deed might be an error message telling your that the host couldn't be resolved and this may be because of your VPN is your current default DNS resolver. So try without DNS using the public internet first.

**Comment by drbrain** [comment]
It's probably due to [looking up the RubyGems service record](https://github.com/rubygems/rubygems/blob/23f3d51cd4506af33c856b35411f43fff0919c9e/lib/rubygems/remote_fetcher.rb#L105-L106)

**Comment by xcchcaptain** [comment]
@tschoening  @drbrain 
yeah ,i tried  on an other computer with the same environment except the vpn
it worked
thanks
