### ISSUE TITLE
0.0.0.pre2 is < 0

### ISSUE THREAD

**Issue by hypnotortoise** [rubygems/rubygems#1782]
I'm having a problem.
My current problem is, I'm trying to install this new gem which was versioned as pre-release, set as `0.0.0.pre1`. Although the gem is installed using the `gem install --pre` option, I can't seem to load it. 

I've tracked this issue to the definition of the spaceship op in `Gem::Version`, which expands the version into `[0,0,0,"pre",2]`, thereby creating an unexpected compare between "pre" and 0, and breaking when I do:

```ruby
gem "mygem"
```

It also breaks when I specify the version:

```ruby
gem "mygem", "=0.0.0.pre2"
Gem::LoadError: Could not find 'mygem' (= 0.0.0.pre2) - did find: [mygem-0.0.0.pre2]
```

Even if `0.0.0.pre` is unacceptable and I should start with `0.0.1`, it still seems odd that it breaks when I specify the exact version to load. (odd as in a bug :=) ).

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

```
$ gem env version
2.6.2
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by drbrain** [comment]
Does `gem 'mygem', '>= 0.a'` work?

**Comment by jrafanie** [comment]
That seems to work in irb:

The reported issue:

```ruby
irb(main):013:0> r = Gem::Requirement.new(">=0")
=> #<Gem::Requirement:0x007f95bb205280 @requirements=[[">=", #<Gem::Version "0">]]>
irb(main):014:0> r.satisfied_by?(Gem::Version.new("0.0.0.pre2"))
=> false
```

@drbrain's suggestion:

```ruby
irb(main):015:0>
irb(main):016:0*
irb(main):017:0*
irb(main):018:0* r = Gem::Requirement.new(">0.a")
=> #<Gem::Requirement:0x007f95bc874d90 @requirements=[[">", #<Gem::Version "0.a">]]>
irb(main):019:0> r.satisfied_by?(Gem::Version.new("0.0.0.pre2"))
=> true
```

**Comment by TiagoCardoso1983** [comment]
I have been working on this with @hypnotortoise . A workaround is always doable. The question is, whether the reported case is intended behaviour or undefined behaviour. 

Also, the `gem "mygem"` call was a troubleshooting method we used. Our ruby scripts are calling `require "mygem"` (some indirectly, as this `mygem` is also a subdependency of other projects), and the `require` Rubygems core-extensions may or may not load the gem to the load path, causing the aforementioned bug.

**Comment by jrafanie** [comment]
@TiagoCardoso1983 can you use `>=0.0.0.pre2` in your Gemfile so you can opt-in for prerelease gem versions?  In my mind, that's more obvious than `>0.a`

**Comment by drbrain** [comment]
It is expected behavior that `0.a` is less that `0`.  This allows you to upgrade from prerelease versions to a release version.  This is documented [here](http://docs.seattlerb.org/rubygems/Gem/Version.html)

For example, a user with `1.0.0.rc.1` can upgrade to `1.0.0` because `1.0.0.rc1` < `1.0.0`

**Comment by TiagoCardoso1983** [comment]
@jrafanie there is no Gemfile. We have an internal cluster with custom gem server, and some of our internal  tools are ruby system scripts, which for convenience and versioning, are "deployed" as system gems (so the executables are system-wide accessible)m from the internal gem server. 

We also have web apps using these gems in prerelease, and using Gemfile/bundler, and haven't experienced the same issues when using this setup:

```ruby
# after bundle exec irb
> require "noc/dns"
#=> true
> MYGEM::VERSION
#=> "0.0.0.pre2"
```

However, system-wide installs don't depend on bundler, but rubygems alone.

@drbrain I just realized I didn't answer your previous comments.

> Does gem 'mygem', '>= 0.a' work?

```ruby
irb(main):005:0> gem "mygem", "=> 0.a"                                
Gem::Requirement::BadRequirementError: Illformed requirement ["=> 0.a"] 
```

Even if using the `Gem::Version` directly seem to provide the intended result, this seems not to be supported. However, as you already said, the comparison result is intended behaviour, which leaves us in a conundrum.

As previously stated, by not using the Gemfile and bundler, we'd have to setup in all gemspecs something like the following entry to count with prereleases:

```ruby
  gem.add_dependency "mygem", "0.0.0", ">= 0.a"
```

which seems quite verbose and not DRY (and I don't know if that would even work, have to test it). Still, I think that stuff should be like in the described bundler scenario: it should "just work". I assume bundler is not doing anything more than rubygems, although I could be proven wrong.

**Comment by jrafanie** [comment]
> irb(main):005:0> gem "mygem", "=> 0.a"                                
> Gem::Requirement::BadRequirementError: Illformed requirement ["=> 0.a"]

@TiagoCardoso1983 I believe you have a typo.  Try >= instead of =>.

```ruby
irb(main):001:0> gem 'psych', '>=0.a'
=> true
```

**Comment by TiagoCardoso1983** [comment]
@jrafanie , you are right, but I had just copy-pasted the line posted by @drbrain above. 

Still, I get the same error with it:

```ruby
irb(main):006:0> gem "mygem", ">=0.a"
Gem::LoadError: Could not find 'mygem' (>= 0.a) - did find: [mygem-0.0.0.pre2]
irb(main):006:0> gem "mygem", ">=0.0.a"
Gem::LoadError: Could not find 'mygem' (>= 0.0.a) - did find: [mygem-0.0.0.pre2]
irb(main):008:0> gem "mygem", ">=0.0.0.a"
Gem::LoadError: Could not find 'mygem' (>= 0.0.0.a) - did find: [mygem-0.0.0.pre2]
```

Although the `Gem::Version` comparator seems to work in isolation, it doesn't seem to work a few layers above.

**Comment by ridiculous** [comment]
@HoneyryderChuck what's the point of having a prerelease 0.0 gem? That's like having a negatively versioned gem 0.o 

Is the issue that rubygems should provide a better error message?

**Comment by HoneyryderChuck** [comment]
@ridiculous it's not like having a negatively versioned gem because I didn't version with negative numbers.
Saying that rubygems doesn't support x.x.0 (+prex) versions is also not a valid argument, it just works with 0.1.0, 0.2.0, 1.0.0 (+ prex), and so on.
It's just a matter of correctness, this is anyways a transient issue, as I know I can just bump and forget. Since this thread was started, I think the mentioned gem is already in 0.0.3, so you know, problem solved.

**Comment by bronzdoc** [comment]
This is a expected behavior and i think is not  a problem anymore @hypnotortoise @HoneyryderChuck ? let me know if it is to reopen this issue, thanks.
