### ISSUE TITLE
Error message for an invalid proxy is a bit misleading

### ISSUE THREAD

**Issue by petems** [rubygems/rubygems#1783]
I'm would like to suggest a feature.

My current problem is:

The error message for an incorrect http-proxy parametr is misleading

```
gem install rails -p=foo.bar.com
ERROR:  While executing gem ... (OptionParser::InvalidArgument)
    invalid argument: -p=foo.bar.com
```

I spent a while trying to figure out if I misspelt the parameter or something, before eventually realising it needs the http/https at the start.

It would be nicer if it could specify that 👍 

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.7
```

But I assume it affects all gem versions

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by shevegen** [comment]
If you use leading "https" it works? Or can you also add the correct syntax, just to simplify testing it.

If so then I guess adding an additional message such as "Preface URLs with http: or https" or something like that, would not be bad.

**Comment by ajwann** [comment]
@shevegen I can take a crack at this. I'll have a PR up shortly with the new error message.

**Comment by samir-majhi** [comment]
How about
ERROR:  While executing gem ... (OptionParser::InvalidArgument)
    invalid argument: -p=foo.bar.com 
    incomplete URL

Or should it just default to https and retry on http if that fails?
Whatever it does, that should be consistent with how URLs are treated in gem and ruby in general.

Hi. I'm new to open source. Please excuse the silly questions.
