### ISSUE TITLE
Permission denied @ rb_sysopen - C:/Program Files/Ruby23/lib/ruby/gems/2.3.0/cache/rdoc-data-4.1.0.gem

### ISSUE THREAD

**Issue by tschoening** [rubygems/rubygems#1784]
I'm having a problem or would like to suggest a feature.

My current problem is a permission error while installing gems in a user specific way. I installed Ruby itself globally, but want to be able to manage gems only per user and added the `--user-install` option to the needed command to install one example gem. The problem is that after downloading the gem, rubygems seems to try to move the downloaded file into the system wide cache dir for gems before actually installing it per user, but I don't have write permissions in that system dir. By default, no user on somewhat recent versions of Windows would have write permissions in such system wide dirs. Should even be the same on Linux depending on how Ruby is packaged.

My issued command:

> C:\Users\tschoening>gem install --user-install rdoc-data
> Fetching: rdoc-data-4.1.0.gem (100%)
> ERROR:  While executing gem ... (Errno::EACCES)
>     Permission denied @ rb_sysopen - C:/Program Files/Ruby23/lib/ruby/gems/2.3.0/cache/rdoc-data-4.1.0.gem

This only happens with 64 Bit versions of Ruby, because a 32 Bit version would trigger the write access being redirected to a per user VirtualStore folder:

> For the purposes of this virtualization, Windows Vista treats a process as legacy if it’s 32-bit
> (versus 64-bit), is not running with administrative rights, and does not have a manifest file
> indicating that it was written for Windows Vista.

https://technet.microsoft.com/en-us/library/2007.06.uac.aspx

And in fact issuing my above command with a 32 Bit version of Ruby succeeds, because the downloaded gem which should be stored in the system wide cache dir is redirected by Windows automatically into a copy of that dir in the user home. Afterwards the gem is additionally copied into a user wide cache dir.

Allowing to install gems per user using a special command line, while still relying on write access to some system wide cache dir doesn't make sense to me. So I suggest to change this to use a user wide cache dir by default at least if `--user-install` is provided.

This issue is related to:

  - [ ] Network problems
  - [X] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
C:\Users\tschoening>ver
Microsoft Windows [Version 10.0.10586]

C:\Users\tschoening>ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x64-mingw32]

$ gem env version
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.1
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [i386-mingw32]
  - INSTALLATION DIRECTORY: C:/Program Files/Ruby23/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: C:/Users/tschoening/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: "C:/Program Files/Ruby23/bin/ruby.exe"
  - EXECUTABLE DIRECTORY: C:/Program Files/Ruby23/bin
  - SPEC CACHE DIRECTORY: C:/Users/tschoening/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86-mingw32
  - GEM PATHS:
     - C:/Program Files/Ruby23/lib/ruby/gems/2.3.0
     - C:/Users/tschoening/.gem/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--user-install"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\ProgramData\Oracle\Java\javapath
     - C:\Program Files (x86)\Embarcadero\Studio\18.0\bin
     - C:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl
     - C:\Program Files (x86)\Embarcadero\Studio\18.0\bin64
     - C:\Users\Public\Documents\Embarcadero\Studio\18.0\Bpl\Win64
     - C:\Program Files\Perl\site\bin
     - C:\Program Files\Perl\bin
     - C:\Windows\system32
     - C:\Windows
     - C:\Windows\System32\Wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0\
     - C:\Program Files\doxygen\bin
     - C:\Program Files\TortoiseSVN\bin
     - C:\Program Files\nodejs\
     - C:\Program Files\Git\cmd
     - C:\Program Files\Apache Software Foundation\Ant\bin
     - C:\Program Files\Apache Software Foundation\Maven\bin
     - C:\Program Files (x86)\NASM
     - C:\Program Files (x86)\Enscript\bin
     - C:\Program Files\gs\gs9.19\bin
     - C:\Program Files (x86)\PuTTY
     - C:\Program Files (x86)\WiX Toolset v3.10\bin
     - C:\Program Files (x86)\pgmodeler
     - C:\Users\tschoening\AppData\Roaming\npm
     - C:\Users\tschoening\AppData\Roaming\Perl\x64\bin
     - C:\Program Files\Ruby23\bin
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by djberg96** [comment]
Is `File.writable?` coming back true for that directory? What happens if you do this in an irb session?

`File.writable?("C:/Program Files/Ruby23/lib/ruby/gems/2.3.0/cache")`

**Comment by tschoening** [comment]
It's `true` for a later explained reason, but the result is wrong:

> irb(main):001:0> File.writable?("C:/Program Files/Ruby23/lib/ruby/gems/2.3.0/cache")
=> false
irb(main):002:0> File.writable?("C:/Program Files/Ruby23/lib/ruby/gems/2.3.0/cache")
=> true

The first line contains the check without a 64 Bit version of Ruby installed, so the mentioned directory is missing and the result makes sense. The second line was directly after I installed Ruby in 64 Bit, but the result is wrong. My current user executing both lines can't add files or dirs in the mentioned dir in Windows Explorer or cmd.exe:

> C:\Program Files\Ruby23\lib\ruby\gems\2.3.0\cache>echo > test.txt
Zugriff verweigert

The error message is "Permission denied". Additionally, I used [Process Monitor](https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx) to monitor what happens when executing `echo` and contrary to your Ruby test, it really tries to create the file and fails with `ACCESS DENIED`. This is the same as with my initial error report, where I used Process Monitor to have a look at the behaviour of Ruby as well. `File.writable?` doesn't try to actually create the file, but only checks the attributes of the directory instead.

And that's the problem:

> When used with directories, _access determines only whether the specified directory exists; in Windows 2000 and later operating systems, all directories have read and write access.

https://msdn.microsoft.com/en-us/library/1w06ktdy.aspx

`File.writable?` ultimately checks using `eaccess` and `access` and that's why it thinks the directory is writable, while it actually isn't.

https://github.com/ruby/ruby/blob/trunk/file.c#L1629
https://github.com/ruby/ruby/blob/trunk/file.c#L1306
https://github.com/ruby/ruby/blob/trunk/missing/file.h#L17

**Comment by djberg96** [comment]
@tschoening Ok, can you try installing the `win32-file` gem, do a `require "win32-file"`, and see what results you get?

**Comment by tschoening** [comment]
This seems to provide correct results, if that's what you are after:

> irb(main):001:0> require "win32-file"
=> true
irb(main):002:0> File.writable?("C:/Program Files/Ruby23/lib/ruby/gems/2.3.0/cache")
=> false
irb(main):003:0>

**Comment by djberg96** [comment]
@tschoening Yeah, I think that may ultimately the problem. I reimplemented `File.writable?` (among others) so that it's more robust.

Let's test my theory. What happens if you require win32-file when you run your command?

**Comment by tschoening** [comment]
How do I do that? I don't see where I could `require` anything with `gem install`.

**Comment by djberg96** [comment]
@tschoening Oh, sorry. You can set RUBYOPT.

    $env:RUBYOPT="-rwin32-file" # powershell
    set RUBYOPT="-rwin32-file" # cmd shell

**Comment by tschoening** [comment]
At least with `cmd.exe` it needs to be:

> set RUBYOPT=-rwin32-file

But besides that, it seems to work. I needed to change write permissions to install `win32-file`, but after changing those permissions back to default, it first not worked again, like expected, but with your `RUBYOPT` it worked afterwards:

```
C:\Program Files\Ruby23\bin>gem install --user-install rdoc-data
Fetching: rdoc-data-4.1.0.gem (100%)
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - C:/Program Files/Ruby23/lib/ruby/gems/2.3.0/cache/rdoc-data-4.1.0.gem

C:\Program Files\Ruby23\bin>gem install --user-install win32-file
Successfully installed win32-file-0.8.1
Parsing documentation for win32-file-0.8.1
Done installing documentation for win32-file after 0 seconds
1 gem installed

C:\Program Files\Ruby23\bin>gem install --user-install rdoc-data
Fetching: rdoc-data-4.1.0.gem (100%)
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - C:/Program Files/Ruby23/lib/ruby/gems/2.3.0/cache/rdoc-data-4.1.0.gem

C:\Program Files\Ruby23\bin>set RUBYOPT=-rwin32-file

C:\Program Files\Ruby23\bin>gem install --user-install rdoc-data
Fetching: rdoc-4.3.0.gem (100%)
Successfully installed rdoc-4.3.0
Fetching: rdoc-data-4.1.0.gem (100%)
ERROR:  Error installing rdoc-data:
        rdoc-data requires rdoc (~> 4.0)
```
I don't see the last error message related to this problem, but to my different versions of Ruby, x86 vs. x86-64. I can see that `rdoc-4.3.0` is in the user specific gem dir and that it is not in the system wide cache dir of the running Ruby etc. This looks like as expected.

**Comment by djberg96** [comment]
Yep, sorry, I edited my response after I realized my mistake for the cmd shell.

Ok, then ultimately we can conclude that this is an issue with `File.writable?` on Windows. Assuming that's correct, there's little we can do within rubygems I'm afraid without lots of platform-specific contortions since the solution is non-trivial.

I would say leave your RUBYOPT set that way, but I think it breaks other gem commands somehow, e.g. `gem list`, so be careful.

On a side note that there's also some feeling that --user-install should be the default:

https://github.com/rubygems/rubygems/issues/1394

**Comment by tschoening** [comment]
> IMO this is a Ruby bug.

Agreed, so should I file one linking here or are you doing it or ...? Especially because of #1394, in theory this breaks for everyone by default if you switch the default behaviour. I suggest you should file the bug, simply because you are more closer to the Ruby community than I am I guess.

> I would say leave your RUBYOPT set that way, but I think it breaks other gem commands somehow, e.g. gem list, so be careful.

I would suggest using the x86 aka 32 Bit only version of Ruby instead to everyone on Windows who doesn't want to deal with permissions. VirtualStore is handling the problem transparently then and one doesn't need to remember `RUBYOPT` or deal with shell scripts or such. But it's good to have the workaround documented here of course.

**Comment by djberg96** [comment]
@tschoening I rarely report Windows bugs any more because I grew tired of fighting with the core team. It was easier to just redefine the methods I felt were broken and publish a gem. You are free to file one, however at http://bugs.ruby-lang.org.

**Comment by tschoening** [comment]
I'll give it a try:

https://bugs.ruby-lang.org/issues/13151

Thanks for your help!

**Comment by muliar** [comment]
When this will be fixed? I realised that ruby doesn't use user's profile to install "gems", why? C;\Program Files\ should be writable only to installer.

**Comment by MSP-Greg** [comment]
I'm a bit confused by this.  Does the current user role (Admin/Standard) affect it?  I often work with many Ruby builds, and I install most gems using `--user-install`.  I've also got a few Appveyor test builds that also installed gems that way....    Thanks, Greg

**Comment by zwarburg** [comment]
I'm still having this issue... Any idea how to resolve it?
