### ISSUE TITLE
Can't install Rails on Windows

### ISSUE THREAD

**Issue by githubbr** [rubygems/rubygems#1785]
I'm having a problem or would like to suggest a feature.

I installed Ruby on Windows 7 SP1 using RubyInstaller following this instruction: http://blog.teamtreehouse.com/installing-rails-5-windows but I can't seem to install Rails.

Here is the error message that I got

```
C:\Users\admin>ruby -v
ruby 2.2.5p319 (2016-04-26 revision 54774) [i386-mingw32]

C:\Users\admin>gem install rails --version 5.0.0
ERROR:  Could not find a valid gem 'rails' (= 5.0.0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect retur
ned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (
https://api.rubygems.org/specs.4.8.gz)

C:\Users\admin> ruby -ropenssl -e 'p OpenSSL::OPENSSL_VERSION' and openssl s_cli
ent -showcerts -connect rubygems.org:https
"OpenSSL 1.0.1l 15 Jan 2015"

C:\Users\admin>```
Please help. Thank you.

**Comment by djberg96** [comment]
Please try the following:

* gem sources -r https://rubygems.org/
* gem sources -a http://rubygems.org
* gem update --system
* gem sources -r http://rubygems.org
* gem sources -a https://rubygems.org

**Comment by Polydiac** [comment]
Thank you so much. I had the same problem with every other package and after a reinstall of ruby and it still didn't I found this and it now finally works.
