### ISSUE TITLE
I didn't know the current Ruby version when error was occured caused by old version of Ruby.

### ISSUE THREAD

**Issue by bake0937** [rubygems/rubygems#1786]
I'm having a problem or would like to suggest a feature.

My current problem is that I didn't know the current Ruby version when error was occured caused by old version of Ruby.

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

With ruby ​​version set to 2.1.3p242 Installing rails has the following result.

```
$ gem install rails
Fetching: activesupport-5.0.0.1.gem (100%)
ERROR:  Error installing rails:
	activesupport requires Ruby version >= 2.2.2.
```

In this error message the user don't know how to check the current version.
I propose the following two methods

1. Appending #{Ruby version} to error message

```
$ gem install rails
Fetching: activesupport-5.0.0.1.gem (100%)
ERROR:  Error installing rails:
	activesupport requires Ruby version >= 2.2.2. current version is #{Ruby version}
```

2. Describing how to check version

```
$ gem install rails
Fetching: activesupport-5.0.0.1.gem (100%)
ERROR:  Error installing rails:
	activesupport requires Ruby version >= 2.2.2. please execute 'ruby -v'
```

**Comment by segiddins** [comment]
Something like (1) seems reasonable, and we ought to do the same on rubygems version mismatches

**Comment by bronzdoc** [comment]
Should we add that ruby version message whenever a `Gem::InstallError` is raised?

**Comment by segiddins** [comment]
@bronzdoc only on `Gem::RuntimeRequirementNotMetError`, I think
