### ISSUE TITLE
installing gem bundler

### ISSUE THREAD

**Issue by abit2** [rubygems/rubygems#1792]
I'm having a problem or would like to suggest a feature.

My current problem is:
$ gem install bundler 
ERROR: Could not find a valid gem 'bundler' (>= 0), here is why: 
                  Unable to download data from https://rubygems.org/ - timed out(https://api.rubygems.org/specs.4.8.gz)

This issue is related to:

  - [1 ] Network problems
  - [1 ] Installing a library
  - [ 0] Publishing a library
  - [ 1] The command line `gem`
  - [0 ] Other

Here are my current environment details:

```
$ gem env version
2.5.1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Timeout errors are associated with Internet connectivity, is this still an issue for you @abit2 ?

**Comment by abit2** [comment]
@bronzdoc No, thanks for answering my query :). It was a network problem btw.
