### ISSUE TITLE
Yardoc autodocumentation ignores tags

### ISSUE THREAD

**Issue by snood1205** [rubygems/rubygems#1799]
I'm having a problem or would like to suggest a feature.

My current problem is that the auto documentation feature on RubyGems ignores my yard tags that work fine when I run `yardoc` locally.

This issue is related to:

 
  - [X] Publishing a library
  - [X] Other

Here are my current environment details:

```
$ gem env version
2.5.1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by drbrain** [comment]
There is no auto documentation feature on RubyGems.

If you are referring to http://rdoc.info you must file a bug there.
