### ISSUE TITLE
Gem installation error: `installing into parent path`

### ISSUE THREAD

**Issue by KrauseFx** [rubygems/rubygems#1802]
My current problem is whenever I package my gem using `rake build` and try to install it on any machine, the user gets the following error:

```
$ gem install /Users/krausefx/Developer/fastlane/pkg/fastlane-2.0.5.gem
ERROR:  While executing gem ... (Gem::Package::PathError)
    installing into parent path /Users/krausefx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/lib/core_ext/class.rb of /Users/krausefx/.rbenv/versions/2.3.1/lib/ruby/gems/2.3.0/gems/fastlane-2.0.5 is not allowed
```

I initially used rvm, and thought that's causing the issue, so I uninstalled it, and switched to rbenv. I installed the latest bundler, and the latest RubyGems. 

After building a `.gem` after `rake build` I can't install the gem on any machine, however I can deploy just fine from 2 other Macs.

Attached the generated gem file, which you can try installing using `gem install --local ...` to see the error posted above: [fastlane-2.0.5.gem.zip](https://github.com/rubygems/rubygems/files/659692/fastlane-2.0.5.gem.zip)

This seems to be not related to _fastlane_, as I have the same error for other gems I own too.

---

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [x] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.8
$ bundle -v
Bundler version 1.13.6
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
```yaml
files:
- "../lib/core_ext/class.rb"
- "../lib/core_ext/mini_magick/utilities.rb"
- "../lib/lolcommits.rb"
- "../lib/lolcommits/capturer.rb"
- "../lib/lolcommits/capturer/capture_cygwin.rb"
- "../lib/lolcommits/capturer/capture_fake.rb"
- "../lib/lolcommits/capturer/capture_linux.rb"
- "../lib/lolcommits/capturer/capture_linux_animated.rb"
- "../lib/lolcommits/capturer/capture_mac.rb"
- "../lib/lolcommits/capturer/capture_mac_animated.rb"
- "../lib/lolcommits/capturer/capture_windows.rb"
- "../lib/lolcommits/cli/fatals.rb"
- "../lib/lolcommits/cli/launcher.rb"
- "../lib/lolcommits/cli/process_runner.rb"
- "../lib/lolcommits/cli/timelapse_gif.rb"
- "../lib/lolcommits/configuration.rb"
- "../lib/lolcommits/git_info.rb"
- "../lib/lolcommits/installation.rb"
- "../lib/lolcommits/platform.rb"
- "../lib/lolcommits/plugin.rb"
- "../lib/lolcommits/plugins/dot_com.rb"
- "../lib/lolcommits/plugins/lol_protonet.rb"
- "../lib/lolcommits/plugins/lol_slack.rb"
- "../lib/lolcommits/plugins/lol_tumblr.rb"
- "../lib/lolcommits/plugins/lol_twitter.rb"
- "../lib/lolcommits/plugins/lol_yammer.rb"
- "../lib/lolcommits/plugins/lolsrv.rb"
- "../lib/lolcommits/plugins/loltext.rb"
- "../lib/lolcommits/plugins/tranzlate.rb"
- "../lib/lolcommits/plugins/uploldz.rb"
- "../lib/lolcommits/runner.rb"
- "../lib/lolcommits/version.rb"
```

The issue is the reference to files in `..` in the gemspec

**Comment by segiddins** [comment]
Also, for what it's worth, I was able to `rake install` fastlane from b1800cf2b14bd0ea38a1a941f72d22a708779471

**Comment by KrauseFx** [comment]
Perfect, thank you @segiddins, deleting the `lib` folder and other `lolcommit` related files in `..` resolved the issue 👍 

Thank you for the super quick reply and all your help @segiddins 💯
