### ISSUE TITLE
Wrong shebang on Windows

### ISSUE THREAD

**Issue by chabou** [rubygems/rubygems#1810]
I'm having a problem 

My current problem is: Shebang in rakefile gem can be better

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.5.2
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

On Windows, when installing Rake with ruby192 , it comes with a shebang:
`#!/usr/bin/env ruby` which is fine. Shebang is only used by Linux emulated environment like GitBash or Cygwin. With Ruby23x64, it comes with a shebang `#!"C:/Program Files/Ruby192/bin/ruby.exe"` which break Linux emulated environment compatibility.

This shebang is only used by Linux emulated environment. Windows use a .bat file which add prefix to execute ruby and not relay on shebang

I don't know if this issue concerns `gem`. Please redirect me if it don't

**Comment by chabou** [comment]
This issue https://github.com/oneclick/rubyinstaller/issues/317 recommends to use: `gem install rake --env-shebang`. But it should be default imo

**Comment by bronzdoc** [comment]
I dont see this being a rubygems issue,  try reporting it in https://github.com/ruby/rake
