### ISSUE TITLE
Remove ableist slur in codebase.

### ISSUE THREAD

**Issue by duckinator** [rubygems/rubygems#1814]
I'm having a problem or would like to suggest a feature.

My current problem is https://github.com/rubygems/rubygems/blob/master/test/rubygems/test_gem_remote_fetcher.rb#L166

If it said "retarded", there would be a _chance_ it wasn't intended as a slur. Just "tarded", not so much.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
Closed by #1823.
