### ISSUE TITLE
Can't redirect IO due to hard coded values

### ISSUE THREAD

**Issue by enkessler** [rubygems/rubygems#1815]
I'm having a problem or would like to suggest a feature.

My current problem is that IO redirection does not work with the `Gem::StreamUI` class (and possibly others in `user_interaction.rb`) because the relevant code references the constant `STDERR`/`STDOUT`/`STDIN` instead of the variable `$stderr`/`$stdout`/`$stdin`.

see: https://github.com/rubygems/rubygems/blob/master/lib/rubygems/user_interaction.rb#L668
see: https://github.com/rubygems/rubygems/blob/master/lib/rubygems/user_interaction.rb#L194

As such, I cannot properly capture the output of `Gem::Specification#validate` during testing in order to check that my gem does not have problems and I think that I need to be able to capture the output because `#validate` itself gives no other indication that there are problems.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

```
$ gem env version
2.6.7
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by drbrain** [comment]
You are looking for [Gem::MockGemUi](https://github.com/rubygems/rubygems/blob/0749715e4bd9e7f0fb631a352ddc649574da91c1/lib/rubygems/mock_gem_ui.rb#L9) which [uses StringIO](https://github.com/rubygems/rubygems/blob/0749715e4bd9e7f0fb631a352ddc649574da91c1/lib/rubygems/mock_gem_ui.rb#L46-L48) to capture input and output for testing.  [These methods](https://github.com/rubygems/rubygems/blob/0749715e4bd9e7f0fb631a352ddc649574da91c1/lib/rubygems/mock_gem_ui.rb#L65-L79) let you check what the rubygems code you ran output and let you set up input.

Here's an [example with input](https://github.com/rubygems/rubygems/blob/0749715e4bd9e7f0fb631a352ddc649574da91c1/test/rubygems/test_gem_uninstaller.rb#L46-L56) and an [example with output](https://github.com/rubygems/rubygems/blob/0749715e4bd9e7f0fb631a352ddc649574da91c1/test/rubygems/test_gem_uninstaller.rb#L73-L86).

**Comment by drbrain** [comment]
PS: Here's an example of how to switch out which UI you are using:

```
>> require 'rubygems/user_interaction'
=> true
>> s
=> #<Gem::Specification:0x3fe297831e2c junk-1>
>> s.validate
WARNING:  licenses is empty, but is recommended.  Use a license identifier from
http://spdx.org/licenses or 'Nonstandard' for a nonstandard license.
WARNING:  no email specified
WARNING:  no homepage specified
WARNING:  no summary specified
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
=> true
>> Gem::DefaultUserInteraction.use_ui Gem::SilentUI.new do s.validate end
=> true
```

**Comment by enkessler** [comment]
@drbrain That approach works for me. Thanks for the help and for the useful example as well!
