### ISSUE TITLE
installer.rb is swallowing exceptions from ext/builder.rb

### ISSUE THREAD

**Issue by mikz** [rubygems/rubygems#182]
I tried to install and compile capybara-webkit (using bundler) but Makefile had some strange characters.

Result was always successful compilation with no problem but install reported compilation error.

So I figured out that problem is in ext/builder - issue #181

Installer swallowed ext/builder (ArgumentException) exception and printed just useless information about compilation problem - which is not right.

So I think that would be better to somehow isolate compilation exceptions and exceptions from rubygems itself and print out some useful infromation like exception name, file, line number and message.

**Comment by bronzdoc** [comment]
This is the only request for this feature in 7 years and has been ide for 4 years, i'm going to close it
