### ISSUE TITLE
Sources without trailing slash not resolved correctly

### ISSUE THREAD

**Issue by randycoulman** [rubygems/rubygems#1829]
I'm having a problem or would like to suggest a feature.

My current problem is when attempting to run any `gem` command with a gem source that doesn't have a trailing slash, the last segment of the path is removed.  For example, following the [documentation for a gemstash private gem repository](https://github.com/bundler/gemstash/blob/master/docs/gemstash-private-gems.7.md), I might configure a gem source like `http://localhost:9292/private`.  When I attempt to install a gem (or list or search) from that source, the `gem` command line will attempt to `GET` `/api/v1/dependencies?gems=my_private_gem` instead of `/private/api/v1/dependencies?gems=my_private_gem`.

See the discussion starting with this comment: https://github.com/bundler/gemstash/pull/134#issuecomment-275400757

Also, see this skipped test on the gemstash repository: https://github.com/bundler/gemstash/blob/master/spec/integration_spec.rb#L140-L147

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.8
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by smellsblue** [comment]
I've investigated this before, and I think I found where the problem was. This line (https://github.com/rubygems/rubygems/blob/master/lib/rubygems/source.rb#L187):
```ruby
spec_path  = api_uri + "#{file_name}.gz"
```
is concatenating a URI with another string, which ends up dropping the path of the url. Here is a demonstration in IRB:
```
$ irb
irb(main):001:0> require "uri"
=> true
irb(main):002:0> uri = URI.parse("https://some-gem.server/custom-path")
=> #<URI::HTTPS https://some-gem.server/custom-path>
irb(main):003:0> puts(uri + "latest_specs.4.8.gz")
https://some-gem.server/latest_specs.4.8.gz
=> nil
```

I don't know if there are other places with the same problem, but it seems to me that this should instead result in `https://some-gem.server/custom-path/latest_specs.4.8.gz`... but maybe there are cases where the existing behavior is more correct?

**Comment by djberg96** [comment]
http://blog.honeybadger.io/why-is-uri-join-so-counterintuitive/

I wonder if File.join would be appropriate here.

**Comment by indirect** [comment]
`File.join` uses `\` on Windows, so probably not.

**Comment by randycoulman** [comment]
`gemcutter_utilities.rb` has this pattern: `uri = URI.parse "#{self.host}/#{path}"`.  I'm not sure if that would introduce its own issues with double-slashes, though.

**Comment by djberg96** [comment]
@indirect That's easy enough to deal with, but the bigger issue is that File.join returns a string, and spec_path is currently a URI object. It definitely causes test failures if you try to change it to a plain string.

This is a bit clumsy but seems to pass:

    spec_path  = URI.parse(File.join(api_uri.to_s, "#{file_name}.gz").tr("\\", "/"))

**Comment by randycoulman** [comment]
I've done a little bit more experimenting with this and made an interesting discovery:

This is only an issue when using gem sources from my `.gemrc` file.  If I supply the source on the command line with `--clear-sources --source http://localhost:9292/private`, everything works fine.
