### ISSUE TITLE
2.6.10 Gem::RemoteFetcher::FetchError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A

### ISSUE THREAD

**Issue by betam4x** [rubygems/rubygems#1835]
I'm having a rather odd issue with installing gems using SSL.  This is happening for me on 2 different machines.  1) A Windows 10 Machine running WSL (Windows subsystem for Linux) and 2) My Mac running MacOS 10.12.3.  When either using `gem install` or bundler, I randomly get the following error (this one reproduced with `bundle` for a Rails app, but I've managed to trigger a similar error with gem install as well)

```
Gem::RemoteFetcher::FetchError: SSL_connect SYSCALL returned=5 errno=0 state=SSLv2/v3 read server hello A (https://rubygems.org/gems/listen-3.0.8.gem)
An error occurred while installing listen (3.0.8), and Bundler cannot continue.
Make sure that `gem install listen -v '3.0.8'` succeeds before bundling.
```

Here is the contents of gem env on the Windows Machine (My Macbook is packed up right now, since I'm getting ready for work, but I can provide that if needed.)

```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.10
  - RUBY VERSION: 2.3.3 (2016-11-21 patchlevel 222) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/richard/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /home/richard/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /home/richard/.rbenv/versions/2.3.3/bin/ruby
  - EXECUTABLE DIRECTORY: /home/richard/.rbenv/versions/2.3.3/bin
  - SPEC CACHE DIRECTORY: /home/richard/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/richard/.rbenv/versions/2.3.3/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/richard/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0
     - /home/richard/.gem/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/richard/.rbenv/versions/2.3.3/bin
     - /home/richard/.rbenv/libexec
     - /home/richard/.rbenv/plugins/ruby-build/bin
     - /home/richard/.rbenv/shims
     - /home/richard/.rbenv/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/local/games
     - /usr/games
```

It happens much less frequently on my Mac then it did on WSL.   I initially ran into this issue on Ruby 2.4.0.  After cleanly downgrading back to 2.3.3, the problem went away until I downloaded a new RubyGems release.

**Comment by drbrain** [comment]
That's an error from bundler, what does `gem install listen -v 3.0.8` say?

**Comment by betam4x** [comment]
The issue is random.  I initially posted it here because I've seen the error before with gem install.  However, because it's random it's very hard for me to reproduce.  Even in the case where I ran a bundle install, simply retrying the operation would succeed and another gem would fail down the line.  That being said I will post an issue with bundler.  I haven't been able to cause the issue I had with rubygems to re-occur.
