### ISSUE TITLE
Feature request: chdir to gemspec directory when doing gem build and control output location

### ISSUE THREAD

**Issue by Rush** [rubygems/rubygems#1837]
My current problem is: when building a gem from outside and running `gem build ../some/path/file.gemspec` the resulting `.gem` has no contents. This is because `s.files` does not match anything. As part of my build system I'd like to run the `gem` command from a different working directory and I would also like to control the output location of the resulting `.gem` file. 

To sum up, there are two requests:
* [ ] Make sure the `gem` command chdirs to the `.gemspec` file location.
* [ ] Allow to output the `.gem` file to a different dir, or at least to the initial working dir before the chdir to the gemspec location.

This issue is related to:
  - [X] The command line `gem`

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
May be a duplicte of https://github.com/rubygems/rubygems/issues/448

**Comment by segiddins** [comment]
In the time being, you can set the gemspecs files to be relative to that of __FILE__

**Comment by kke** [comment]
Also ran into this. 

Currently you have to do something like this:

```console
gem build foofoo.gemspec && \
gem install `ls -t foofoo-*.gem|head -1` 
```

because there's no way to control where or what the resulting .gem will be called and `gem install foofoo-*.gem` will install any versions you have laying around in that dir.

Something like this would be nice:

```console
gem build foofoo.gemspec foofoo.gem
# and/or
gem build foofoo.gemspec --install
```

**Comment by deivid-rodriguez** [comment]
This is specially confusing if there's a gemspec in the current folder.

In my case, I have this:

```
$ ls -1 **/*.gemspec
decidim-accountability/decidim-accountability.gemspec
decidim-admin/decidim-admin.gemspec
decidim-api/decidim-api.gemspec
decidim-assemblies/decidim-assemblies.gemspec
decidim-budgets/decidim-budgets.gemspec
decidim-comments/decidim-comments.gemspec
decidim-core/decidim-core.gemspec
decidim-debates/decidim-debates.gemspec
decidim-dev/decidim-dev.gemspec
decidim.gemspec
decidim-meetings/decidim-meetings.gemspec
decidim-pages/decidim-pages.gemspec
decidim-participatory_processes/decidim-participatory_processes.gemspec
decidim-proposals/decidim-proposals.gemspec
decidim-surveys/decidim-surveys.gemspec
decidim-system/decidim-system.gemspec
decidim-verifications/decidim-verifications.gemspec
```

If I run

```
$ gem build decidim-accountability/decidim-accountability.gemspec
```

a file named `decidim-accountability-<version>.gem` will be generated with the contents of the root `decidim` gem.

I find this terribly confusing... :grimacing:

**Comment by bronzdoc** [comment]
closed by  https://github.com/rubygems/rubygems/pull/2204
