### ISSUE TITLE
$ gem check --doctor - checking installs for issues or orphans

### ISSUE THREAD

**Issue by zenspider** [rubygems/rubygems#184]
needs to check gem installs for basic sanity checks, pount out orphans, etc.

Also needs to walk your path and check for multiple ruby installs and point out potential problems.

**Comment by krainboltgreene** [comment]
I'm alllll for this and here's what I'd want to see this do:

  1. Point out orphans
  2. Point out older versions of gems (if you have an updated version, specifically important for bug fix differences)
  3. Show any gems that have bad gemspecs (installed via hackery)
  4. (Not sure if this is possible) Show gems that have screwed up native bindings

**Comment by bronzdoc** [comment]
This have been ide for too long and is the only request for this feature in 7 years, i'm going to close it
