### ISSUE TITLE
Cross compiling Ruby Gems uses Build System Linker Options

### ISSUE THREAD

**Issue by rkeene** [rubygems/rubygems#1840]
I'm having a problem.

My current problem is Cross compiling Ruby Gems uses Build System Linker Options.

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

When cross-compiling Ruby Gems under Ruby 2.4.0, the rbconfig system uses the build system's configuration to cross-compile Ruby Gems, resulting in linker flags that do not work for the host system's linker.

Example:

```text
curb_errors.c: At top level:
cc1: warning: unrecognized command line option "-Wno-self-assign"
cc1: warning: unrecognized command line option "-Wno-constant-logical-operand"
cc1: warning: unrecognized command line option "-Wno-parentheses-equality"
cc1: warning: unrecognized command line option "-Wno-tautological-compare"
compiling curb_multi.c
curb_multi.c: In function 'ruby_curl_multi_perform':
curb_multi.c:688:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   VALUE hash = rbcm->requests;
   ^
curb_multi.c: At top level:
cc1: warning: unrecognized command line option "-Wno-self-assign"
cc1: warning: unrecognized command line option "-Wno-constant-logical-operand"
cc1: warning: unrecognized command line option "-Wno-parentheses-equality"
cc1: warning: unrecognized command line option "-Wno-tautological-compare"
compiling curb_postfield.c
compiling curb_upload.c
linking shared-object curb_core.so
x86_64-coreadaptive-linux-gnu-ld: unrecognized option '--compress-debug-sections=zlib'
x86_64-coreadaptive-linux-gnu-ld: use the --help option for usage information
collect2: error: ld returned 1 exit status
Makefile:257: recipe for target 'curb_core.so' failed
make[2]: *** [curb_core.so] Error 1
make[2]: Leaving directory '/home/rkeene/devel/aurae/node/root/packages/installed/pkgs/workdir-NraJ6njvdJOx.tmp/lib/ruby/gems/2.4.0/gems/curb-0.9.3/ext'

make failed, exit code 2

Gem files will remain installed in /home/rkeene/devel/aurae/node/root/packages/installed/pkgs/workdir-NraJ6njvdJOx.tmp/lib/ruby/gems/2.4.0/gems/curb-0.9.3 for inspection.
Results logged to /home/rkeene/devel/aurae/node/root/packages/installed/pkgs/workdir-NraJ6njvdJOx.tmp/lib/ruby/gems/2.4.0/extensions/x86_64-linux/2.4.0-static/curb-0.9.3/gem_make.out
```

Cross-compiling from Linux/x86_64 to Linux/x86_64 (different platforms)

I previously raised this on the Ruby bug tracker and they directed me here.  https://bugs.ruby-lang.org/issues/13215

**Comment by drbrain** [comment]
Can you cross-compile the curb gem from source?

If you can provide instructions on how to do that it'll be easier to build support for cross-compiling gems into rubygems.

**Comment by rkeene** [comment]
I don't understand the question.  I am attempting to compile the "curb" gem, presumably there must be source involved so I would assume that I am cross-compiling the "curb" gem from source...

I run:

```sh
CROSS_COMPILE_RUBY_EXTENSIONS=yes
GEM_PATH="$(ls -1d "$(pwd)/.fakeroot/native-bin/native-ruby-install/lib/ruby/gems"/* | head -n 1)"
export CROSS_COMPILE_RUBY_EXTENSIONS GEM_PATH

gem install "rubygem-0.9.3.gem" --ignore-dependencies --no-document --build-root "${destdir}" --no-update-sources --ignore-dependencies --local --platform "x86_64-linux" --installdir "/lib/ruby/gems/${ruby_version}"
```

To compile and install the gem.  This fails, because it tries to use the build system's Ruby configuration to build the host system (target of compilation) flags to compile the source code.

**Comment by drbrain** [comment]
Download [the curb source](https://github.com/taf2/curb) and cross-compile it directly from a release tag.

Studying the source of [rake-compiler](https://github.com/rake-compiler/rake-compiler) may give you some ideas for how this is accomplished, I don't know myself.

**Comment by drbrain** [comment]
PS: I'm not sure what `export CROSS_COMPILE_RUBY_EXTENSIONS=yes` is supposed to do, the environment variable isn't used in [RubyGems](https://github.com/rubygems/rubygems/search?utf8=✓&q=CROSS_COMPILE_RUBY_EXTENSIONS) nor in [mkmf.rb](https://github.com/ruby/ruby/blob/trunk/lib/mkmf.rb) (which determines how extensions are built) nor in [ruby in general](https://github.com/ruby/ruby/search?utf8=✓&q=CROSS_COMPILE_RUBY_EXTENSIONS) nor in [curb](https://github.com/taf2/curb/search?utf8=✓&q=CROSS_COMPILE_RUBY_EXTENSIONS)

**Comment by rkeene** [comment]
That environment variable is part of the modification to the build system's Ruby:

```diff
$ cat native-ruby-2.2.0-supportcross.diff  
diff -uNr ruby-2.2.0.orig/tool/mkconfig.rb ruby-2.2.0-supportcross/tool/mkconfig.rb
--- ruby-2.2.0.orig/tool/mkconfig.rb    2014-07-06 22:07:01.000000000 -0400
+++ ruby-2.2.0-supportcross/tool/mkconfig.rb    2015-02-26 11:32:02.518297255 -0500
@@ -267,7 +267,13 @@
     )
   end
 end
-CROSS_COMPILING = nil unless defined? CROSS_COMPILING
+
+if ENV.has_key?("CROSS_COMPILE_RUBY_EXTENSIONS") then
+  CROSS_COMPILING = "yes" unless defined? CROSS_COMPILING
+else
+  CROSS_COMPILING = nil unless defined? CROSS_COMPILING
+end
+
 EOS
 
 $stdout = STDOUT
$
```

Otherwise, Ruby Gems is even worse off at figuring out if it is cross-compiling or not.

**Comment by drbrain** [comment]
`tool/mkconfig.rb` isn't installed so that patch has no effect on mkmf.rb.

mkmf.rb does check `CROSS_COMPILING`, but I suspect it is invoked specially (like RubyGems does with `siteconf.rb` to define the constant only when cross-compiling built-in C extensions (like socket).

If the patch did change how `mkmf.rb` or other parts of ruby worked, RubyGems could not use it in any changes we make to support cross-compiling.

Without instructions for cross-compiling `curb` (or any gem) from source we can't proceed to attempt to implement this feature.  For context, initial implementation of RubyGems' ability to compile gems with extensions started with a source checkout and list of commands to run.  (Namely, [this line](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/ext/ext_conf_builder.rb#L45) which is roughly `/path/to/ruby/you/ran/gem/with -r siteconf.rb path/to/extconf.rb --build-args-from-gem-install-here`.)

Setting up a cross-compilation environment is time-consuming, difficult, and hard to test to ensure we've done the right thing.  Your interest in this feature indicates you have a working cross-compilation environment and the ability to test.

We would like you to provide the command(s) that will correctly cross-compile a Ruby C extension.

My first guess is that `/path/to/ruby/you/ran/gem/with` will need to be `/path/to/cross/compiled/ruby` or something like that.  I'm unsure, but the `rake-compiler` gem linked in a previous comment may have answers.

With this information we can then work on a patch that causes RubyGems to execute the same command(s) you performed to cross-compile the extension.

**Comment by rkeene** [comment]
My entire Linux distribution, including hundreds of packages is cross-compiled.  The environment works fine for that.  Everything from the bootloader, kernel, glibc, Tcl, coreutils, sudo, Python, Ruby, gzip, ... cross-compiles fine.

Without that change to set the Ruby variable CROSS_COMPILING, `mkmf.rb` was trying to determine if cross-compiling was happening incorrectly -- it was looking at the GNU autoconfig configure script results, detecting if the Ruby being compiled is being cross-compiled.  Since it's doing that for the RUNNING Ruby, it's obviously not cross-compiled (this is in `rbconfig.rb`, `CONFIG["CROSS_COMPILING"]`) so this patch gives me a way to set CROSS_COMPILING to "yes" when building a Ruby extension.

I definitely won't be able to run `/path/to/cross/compiled/ruby`, since ... it's for a different platform.

**Comment by rkeene** [comment]
The changes to `tool/mkconfig.rb` show up as changes to `lib/ruby/<version>/<build-platform>/rbconfig.rb` in the installed Ruby installation.

**Comment by drbrain** [comment]
> The changes to tool/mkconfig.rb show up as changes to lib/ruby/<version>/<build-platform>/rbconfig.rb in the installed Ruby installation.

Ah, I see, I wasn't aware.

If you need to make that change ↑ before you can show us the command you need to run, or before the existing command that RubyGems runs will work, you need to submit a patch to Ruby.

Until the patch is incorporated in Ruby it's difficult for us to support any workarounds for older Ruby releases that do not have the patch.  It may occur that the workaround RubyGems incorporates was incorrect which increases our maintenance burden quite a bit.

You can demonstrate that the patch is necessary by doing the work I asked for above, showing that `ruby extconf.rb; make` without the patch in a cross-compilation environment does not generate a usable Makefile (`make` fails, as in your initial comment), but Ruby compiled with the patch does generate a usable Makefile (`make` succeeds).

**Comment by brainstorm** [comment]
I am hitting this [same issue reported upstream](https://bugs.ruby-lang.org/issues/13215) by the OP, not by cross-compiling anything but by simply trying to install rubygems via rvm:

```
$ rvm use ruby-2.4.1
Using /home/brainstorm/.rvm/gems/ruby-2.4.1

$ rvm install arvados-cli
Building native extensions.  This could take a while...
ERROR:  Error installing arvados-cli:
        ERROR: Failed to build gem native extension.

    current directory: /home/brainstorm/.rvm/gems/ruby-2.4.1/gems/curb-0.9.3/ext
/home/brainstorm/.rvm/rubies/ruby-2.4.1/bin/ruby -r ./siteconf20170626-15284-sp65l5.rb extconf.rb
checking for curl-config... yes
checking for curlinfo_appconnect_time... yes

(...)

current directory: /home/brainstorm/.rvm/gems/ruby-2.4.1/gems/curb-0.9.3/ext
make "DESTDIR="
compiling curb.c
compiling curb_easy.c
compiling curb_errors.c
curb_errors.c: In function 'raise_curl_easy_error_exception':
curb_errors.c:463:6: warning: function might be candidate for attribute 'noreturn' [-Wsuggest-attribute=noreturn]
 void raise_curl_easy_error_exception(CURLcode code) {
      ^
curb_errors.c: In function 'raise_curl_multi_error_exception':
curb_errors.c:519:6: warning: function might be candidate for attribute 'noreturn' [-Wsuggest-attribute=noreturn]
 void raise_curl_multi_error_exception(CURLMcode code) {
      ^
curb_errors.c: At top level:
cc1: warning: unrecognized command line option '-Wno-self-assign'
cc1: warning: unrecognized command line option '-Wno-constant-logical-operand'
cc1: warning: unrecognized command line option '-Wno-parentheses-equality'
cc1: warning: unrecognized command line option '-Wno-tautological-compare'
compiling curb_multi.c
curb_multi.c: In function 'ruby_curl_multi_perform':
curb_multi.c:688:3: warning: ISO C90 forbids mixed declarations and code [-Wdeclaration-after-statement]
   VALUE hash = rbcm->requests;
   ^
curb_multi.c: At top level:
cc1: warning: unrecognized command line option '-Wno-self-assign'
cc1: warning: unrecognized command line option '-Wno-constant-logical-operand'
cc1: warning: unrecognized command line option '-Wno-parentheses-equality'
cc1: warning: unrecognized command line option '-Wno-tautological-compare'
compiling curb_postfield.c
compiling curb_upload.c
linking shared-object curb_core.so
/usr/bin/ld: unrecognized option '--compress-debug-sections=zlib'
/usr/bin/ld: use the --help option for usage information
collect2: error: ld returned 1 exit status
make: *** [curb_core.so] Error 1

make failed, exit code 2

Gem files will remain installed in /home/brainstorm/.rvm/gems/ruby-2.4.1/gems/curb-0.9.3 for inspection.
Results logged to /home/brainstorm/.rvm/gems/ruby-2.4.1/extensions/x86_64-linux/2.4.0/curb-0.9.3/gem_make.out
```

**Comment by seanmsmith23** [comment]
Anyone have recommendations on how to workaround this issue? I don't totally understand what I might need to do to get around this. Has it been resolved in 2.5?

**Comment by deivid-rodriguez** [comment]
Have you tried using `rake-compiler`? I think that's what people uses and it seems to work fine.

**Comment by deivid-rodriguez** [comment]
Closing given there was no further feedback and people seem to no longer be having issues with this.

**Comment by rkeene** [comment]
For what it's worth, I tried it again and using "gem install" still looks at the *running* Ruby to determine how to cross-compile an extension, which is wrong.

**Comment by deivid-rodriguez** [comment]
> Have you tried using [`rake-compiler`](https://github.com/rake-compiler/rake-compiler#cross-compilation---the-future-is-now)? I think that's what people uses and it seems to work fine.
