### ISSUE TITLE
Ruby new Installation on windows 10 machine can't update gems or install gems 

### ISSUE THREAD

**Issue by zubintt1** [rubygems/rubygems#1848]
I'm having a problem or would like to suggest a feature.

My current problem is "I can't install or update gems in windows 10 using cmd run as administrator"

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [1] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.5.2
$ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]

$ruby -ropenssl -e 'p OpenSSL::OPENSSL_VERSION'
"OpenSSL 1.0.2j  26 Sep 2016"
$openssl s_client -showcerts -connect rubygems.org:https

-------------------------------------------------------------------------------------------------------------------
CONNECTED(00000003)
1619636256:error:140790E5:SSL routines:SSL23_WRITE:ssl handshake failure:s23_lib.c:184:
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 1460 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
SSL-Session:
    Protocol  : TLSv1
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1487760754
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
-------------------------------------------------------------------------------------------------------------------
```

I have tried very hard but still not able to resolve the issue. Please I need this help urgent. I have gone through all the previous post related to this and tried them and didn't get success.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by olleolleolle** [comment]
@zubintt1 Have you seen this Windows Rubygems article on SSL issues:

http://guides.rubygems.org/ssl-certificate-update/#installing-using-update-packages

**Comment by zubintt1** [comment]
Dear Olleolleolle,
I have tried it also but everytime I do the steps in the above article my problem remains the same. I have to then uninstall everything and then re-install the fresh copy.  I have also searched for the proxy settings in my organization and turns out it doesn't use a proxy. So I am getting helpless on this issue.

**Comment by bronzdoc** [comment]
We're going to close this because it is to old, but if this problem is still happening with the latest version of RubyGems please feel free to let us know with a new issue!
