### ISSUE TITLE
Question about installing milia with rails 5

### ISSUE THREAD

**Issue by benvarien** [rubygems/rubygems#1850]
I'm having a problem or would like to suggest a feature.

My current problem is that I can not install milia on rails 5

This issue is related to:

  - [ ] Network problems
  - [ x] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:
I have started a lesson called "Software as a service - Project Management App" from "The Complete Ruby on Rails Developer". I use Cloud 9 instead  of Nitrous so I had to get postgresql running, so I followed all of the steps that I got from: https://github.com/Aerogami/guides/wiki/Cloud9-workspace-setup-with-Rails-and-Postgresql and everything seemed fine. But when I got to the adding Milia and Devise section of the lesson I couldn’t get the steps to work. 
The first step was to add the gems to the Gemfile and that worked fine: gem ‘devise’ and gem ‘milia’, I saved that and then entered: bundle install —without production.  Then I followed directions and got rid of the: root ‘home#index’ in the route.rb file.
 
And here is the problem:
 
as directed I entered rails g milia:install --org_email=‘do-not-reply@example.com’ and pressed enter only to get a list of errors starting with:

/usr/local/rvm/gems/ruby-2.3.3/gems/activesupport-5.0.1/lib/active_support/callbacks.rb:641:in 'block (2 levels) in skip_callback': Before process_action callback :authenticate_tenant! has not been defined (ArgumentError)

I tried to follow the steps from https://github.com/jekuno/milia#application-controller on a checkout -b section starting from the section of the exercise where it deals with :authenticate_tenant but I am not sure if that is going to work because after that step it states changes that should be made to migrate files that I should have... but I don't.

Does anybody know of how to get rails g milia:install --org_email=‘do-not-reply@example.com’ to work for adding milia while using rails 5?

```
$ gem env version

```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by drbrain** [comment]
Since your problem is with the`milia` gem you will need to ask for help at [the milia repository](https://github.com/jekuno/milia)

**Comment by benvarien** [comment]
Thank you @drbrain!
