### ISSUE TITLE
Problem changing json default from 2.0.2 to 1.8.5

### ISSUE THREAD

**Issue by herobix** [rubygems/rubygems#1852]
I'm having a problem

My current problem is that I can't change the default json gem. It is stuck at: json (default: 2.0.2) and I would like to ONLY use 1.8.5 

I'm trying to use calabash and it is complaining that Json 1.8.5 is crashing with json 2.0.2

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

Here are my current environment details:
Gem version: 2.6.10
Running Mac OS X - 10.12.3 - Sierra

**Comment by hsbt** [comment]
It's calabash issue. not rubygems's one.

**Comment by drbrain** [comment]
Yes, the calabash direct dependencies specify `~> 1.8`.  I can install and run `calabash-ios` without problems.  If you need to use another gem with calabash you'll need to contact the maintainers about changing the dependency.
