### ISSUE TITLE
Login Problem - old email

### ISSUE THREAD

**Issue by nroose** [rubygems/rubygems#1853]
I'm having a problem or would like to suggest a feature.

My current problem is can't log in

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

I have forgotten my password and my email address on rubygems.org is an old one that I no longer have access to. Is there any way you can update that?

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Please open this issue in  https://github.com/rubygems/rubygems.org thanks
