### ISSUE TITLE
gem search should support exact match

### ISSUE THREAD

**Issue by joelpresence** [rubygems/rubygems#1857]
I'm having a problem or would like to suggest a feature.

Thanks for all of your hard work on gem.

My current problem is _gem search finds too many matches for popular gem words like rails________

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2
  - RUBY VERSION: 2.3.3 (2016-11-21 patchlevel 222) [x86_64-darwin16]
  - INSTALLATION DIRECTORY: /Users/joel/.rvm/gems/ruby-2.3.3
  - USER INSTALLATION DIRECTORY: /Users/joel/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /Users/joel/.rvm/rubies/ruby-2.3.3/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/joel/.rvm/gems/ruby-2.3.3/bin
  - SPEC CACHE DIRECTORY: /Users/joel/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/joel/.rvm/rubies/ruby-2.3.3/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-16
  - GEM PATHS:
     - /Users/joel/.rvm/gems/ruby-2.3.3
     - /Users/joel/.rvm/gems/ruby-2.3.3@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/joel/.rvm/gems/ruby-2.3.3/bin
     - /Users/joel/.rvm/gems/ruby-2.3.3@global/bin
     - /Users/joel/.rvm/rubies/ruby-2.3.3/bin
     - /Users/joel/.rvm/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /opt/X11/bin
     - /usr/local/share/dotnet
     - /Library/Frameworks/Mono.framework/Versions/Current/Commands
     - /usr/local/heroku/bin
     - /usr/local/Cellar/subversion/1.8.13/bin
```

I will abide by the [code of conduct] yes
(https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Problem:** When I do `gem search rails` I get 4,916 lines of matching gems and most of them are like "rails-x" or "y-for-rails" when I really want to search for "exactly rails, nothing more, nothing less, nothing related to rails, just the gem whose name is an exact match for rails".  Can we please add this as a feature to the gem command?

The reason why this is important is that for popular gems like `rails` or gems with popular words in them like auth, etc., there are just too many versions that pop up in search and often I want to be able to do an exact search on just the exact term `rails`.  When you return all gems whose names include rails in any form, it obscures the real result, the rails gem, that I want, and I have to scroll and look for it or pipe gem through grep.  Both of these are onerous and make gem less useful.

I often use this desired "gem name exact match" to look for the latest or all versions of a single gem.  I am absolutely not interested in all gems with the word rails in them, only the exact gem rails.

How can we add exact match search like this?

I am willing to help with a PR if somebody can give me some hints where to start, but the lack of this feature is really reducing my productivity.

**Comment by joelpresence** [comment]
NOTE: I also tried using a regexp, and none of these worked:

```
gem search "/\Arails\z/"
gem search "/\Arails\z/i"
gem search /\Arails\z/i
gem search rails
gem search /^rails$/i
```

All of these 5 regex searches returned zero results, even though all 5 of them match the string `rails` exactly.

Further, there's no indication in `gem search --help` of what flavor of regexp you want?  I assume you meant Ruby regex syntax ...

**Comment by drbrain** [comment]
Use `--exact`, which should be in your 2.5.2 version.

```
$ gem search --exact rails

*** REMOTE GEMS ***

rails (5.0.2)
```

See `gem search --help` or `gem help search` for details.

PS: regular expression works for me on 2.6.4:

```
$ gem search ^rails$

*** REMOTE GEMS ***

rails (5.0.2)
```

**Comment by joelpresence** [comment]
Thanks @drbrain .  I wasn't aware of the exact flag and it worked as described, awesome!

It still seems like the regexp matching is broken though ... Should I file a separate issue for that?

**Comment by joelpresence** [comment]
@drbrain could we add documentation on the regex option:

1. What kind of regex syntax? (I assume Ruby, but that should be documented in the help)
2. I assume the option takes a regex literal - `/^rails$/` is such a literal but `^rails$` is not, and it's not obvious from the documentation that we can just omit the `//` delimiters around the regex.

Thanks.

**Comment by drbrain** [comment]
Yes, we could add documentation.  The `REGEXP` argument doesn't use delimiters:

```
$ gem search '\Arails\z'

*** REMOTE GEMS ***

rails (5.0.2)
```

If you wanted to make this PR yourself, update these bits:

https://github.com/rubygems/rubygems/blob/master/lib/rubygems/commands/search_command.rb#L23-L33
https://github.com/rubygems/rubygems/blob/master/lib/rubygems/commands/list_command.rb#L25-L34
https://github.com/rubygems/rubygems/blob/master/lib/rubygems/commands/dependency_command.rb#L42-L51

They're the three commands where we use `REGEXP` arguments.  The CLI library isn't structured to reduce this duplication, but I think it would be OK to copy/paste this between commands.

You can check formatting from a rubygems checkout with `RUBYLIB=lib gem help search`, no need for tests.
