### ISSUE TITLE
make find_by_name return nil instead of rescue

### ISSUE THREAD

**Issue by grosser** [rubygems/rubygems#1858]
- more symmetric to find_all_by_name (which returns an empty array)
 - less surprising for people used to activerecord
 - more symmetric to rubies `Array#find`

**Comment by bronzdoc** [comment]
Actually both return a `Gem::StubSpecification` , `find_by_name`  will raise an exception if no matching specs are found.

Changing this seems like a lot of work and no one else has asked for this in a year, i'm going to close it for now.
