### ISSUE TITLE
Small typo: There should be a trailing '.' character when trying to yank a gem that has already been yanked successfully prior.

### ISSUE THREAD

**Issue by shevegen** [rubygems/rubygems#1860]
Typo:

When yanking a gem ("gemyank" is my alias), I got this:

  gemyank beautiful_url --version 1.0.340 

Output was:

"Yanking gem from https://rubygems.org...
beautiful_url 1.0.340 has already been deleted"

I would suggest a trailing '.' after the last part,
so instead I think it should be read:

"Yanking gem from https://rubygems.org...
beautiful_url 1.0.340 has already been deleted."

I know it is almost too trivial to report but since I
noticed it, I thought, why not report it, it may be
a simple fix. :)

**Comment by bronzdoc** [comment]
I noticed this should be opened in [rubygems/rubygems.org](https://github.com/rubygems/rubygems.org) since rubygems is only printing the api response https://github.com/rubygems/rubygems/blob/master/lib/rubygems/commands/yank_command.rb#L90
