### ISSUE TITLE
logstash-output-monasca_log_api 

### ISSUE THREAD

**Issue by michelechersich** [rubygems/rubygems#1861]
Hello,
I'm having problems in building a Docker container with Logstash 5.x and the logstash-output-monasca_log_api plugin version 0.5.3.

The plugin installation fails as shown below:

`Building monasca-log-agent
Step 1/4 : FROM logstash:5
 ---> 413f93f5f1f2
Step 2/4 : RUN logstash-plugin install logstash-output-monasca_log_api
 ---> Running in 21f002491274
Validating logstash-output-monasca_log_api
Installing logstash-output-monasca_log_api
Plugin version conflict, aborting
ERROR: Installation Aborted, message: Bundler could not find compatible versions for gem "logstash-codec-json":
  In snapshot (Gemfile.lock):
    logstash-codec-json (= 3.0.2)

  In Gemfile:
    logstash-output-udp (>= 0) java depends on
      logstash-codec-json (>= 0) java

    logstash-output-udp (>= 0) java depends on
      logstash-codec-json (>= 0) java

    logstash-output-udp (>= 0) java depends on
      logstash-codec-json (>= 0) java

    logstash-output-udp (>= 0) java depends on
      logstash-codec-json (>= 0) java

    logstash-output-udp (>= 0) java depends on
      logstash-codec-json (>= 0) java

    logstash-output-udp (>= 0) java depends on
      logstash-codec-json (>= 0) java

    logstash-output-udp (>= 0) java depends on
      logstash-codec-json (>= 0) java

    logstash-output-udp (>= 0) java depends on
      logstash-codec-json (>= 0) java

    logstash-output-udp (>= 0) java depends on
      logstash-codec-json (>= 0) java

    logstash-output-monasca_log_api (>= 0) java depends on
      logstash-codec-json (~> 0.1.6) java

    logstash-output-udp (>= 0) java depends on
      logstash-codec-json (>= 0) java

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.`

The problem seems to be that Logstash 5.x locks the logstash-codec-json plugin version to 3.0.2, whereas the logstash-output-monasca_log_api plugin depends on a previous version.

Note that the installation succeeds with previous versions of Logstash (2.x), even though producing runtime errors I will not signal here.
Any clarification on the problem or suggestion on how to solve it?

Thanks,
Michele

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
This is an issue with Bundler, not RubyGems. Please ensure you're running the latest version of Bundler, and open an issue on the bundler repo if it persists. Thank you!

**Comment by michelechersich** [comment]
Reported the same problem to the Logstash Docker image repository and here's the answer: https://github.com/elastic/logstash-docker/issues/17

According to their answer, it's an issue with the plugin author, who should update the dependencies.
