### ISSUE TITLE
error rails new

### ISSUE THREAD

**Issue by Ingosmar89219** [rubygems/rubygems#1862]
please help me! :(
 rails new SistemaReservaHotel
/home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:2278:in `check_version_conflict': can't activate activesupport-5.0.2, already activated activesupport-5.0.1 (Gem::LoadError)
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/specification.rb:1404:in `activate'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:89:in `block in require'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:88:in `each'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:88:in `require'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/gems/concurrent-ruby-1.0.5/lib/concurrent.rb:15:in `<top (required)>'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.1/lib/active_support/logger_silence.rb:3:in `<top (required)>'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.1/lib/active_support/logger.rb:1:in `<top (required)>'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/gems/activesupport-5.0.1/lib/active_support.rb:27:in `<top (required)>'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/generators.rb:6:in `<top (required)>'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/commands/application.rb:1:in `<top (required)>'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/lib/rails/cli.rb:14:in `<top (required)>'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/rubies/ruby-2.3.0/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/gems/railties-5.0.1/exe/rails:9:in `<top (required)>'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/bin/rails:23:in `load'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/bin/rails:23:in `<main>'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
	from /home/noeblack/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'

**Comment by segiddins** [comment]
Hi, what steps can we take to reproduce this bug? Thanks!

**Comment by Ingosmar89219** [comment]
yesterday i could generate a new project "rails new name" but today i cant create rails projects i dont know why :/ the error is when i write rails new, rails update, rails version, the error is the word rails <-- please help me

**Comment by subinhuang** [comment]
I have the same problem, Did you fix it? Thanks!

**Comment by bronzdoc** [comment]
This is probably an issue with your rvm configuration mand not arubygems issue , make sure you are using the correct gemset where you installed rails.

**Comment by fengwen91** [comment]
how to solve it ? i have the same problem,too.

**Comment by SGJunghyun** [comment]
gem install rails will solve it

**Comment by hankuksui** [comment]
我也有这个问题，到底咋整的啊？执行了类似`gem install rails  -v 5.0.1`之后还是不行
