### ISSUE TITLE
Rubygems.org API Error 503 Service unavailable

### ISSUE THREAD

**Issue by MLauper** [rubygems/rubygems#1863]
I'm having a problem while accessing the Rubygems API.

My current problem is that I often receive a 503 Service Unavailable error from the Rubygems API during dependency resolution. The error seems to be returned from the Varnish cache:

> <?xml version="1.0" encoding="utf-8"?>
> <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
>  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
> <html>
>   <head>
>     <title>503 Service Unavailable</title>
>   </head>
>   <body>
>     <h1>Error 503 Service Unavailable</h1>
>     <p>Service Unavailable</p>
>     <h3>Guru Mediation:</h3>
>     <p>Details: cache-hhn1528-HHN 1488788176 499936067</p>
>     <hr>
>     <p>Varnish cache server</p>
>   </body>
> </html>

After some retries (usually between the second and fourth) the call succeed and I can resolve my dependencies. 

Is this behavior known or might this desired (i.e. for throttling)?

This issue is related to:

  - [X] Network problems
  - [X] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.0.14
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by MLauper** [comment]
I was trying to resolve more than 200 Gems in one API call and it seems this caused the API to return a 503.

The issue can be resolved by using the Full Index. 

The expected behavior for me would be to return an appropriate error message to the user. 
Would this be a possibility to implement as an improvement? What do you think?

**Comment by bronzdoc** [comment]
Please open this issue in https://github.com/rubygems/rubygems.org thanks

**Comment by erran-r7** [comment]
For anyone else who hits this — this issue was re-opened by @MLauper at https://github.com/rubygems/rubygems.org/issues/1578. Check out the thread there.
