### ISSUE TITLE
Move lost account to new email address

### ISSUE THREAD

**Issue by kamstrup** [rubygems/rubygems#1867]
I seem to have got myself stuck between a rock and a hard place. I am the owner of this account https://rubygems.org/profiles/kamstrup, but it is tied to my old mikkelDOTkamstrupATxamarin.com email address. I have lost the password and no longer have access to that email address. Is there any chance I can have the account moved to my personal email mikkelDOTkamstrupATgmail.com?

If you have doubts about my authenticity you can verify that I am indeed the github account holder that my rubygems profile points to.

Sorry if this is the wrong place to post account questions, but http://help.rubygems.org/ says to "open a ticket" and I am not understanding what that could mean otherwise :-)

**Comment by bronzdoc** [comment]
Hi @kamstrup please open the ticket at https://github.com/rubygems/rubygems.org thanks!
