### ISSUE TITLE
ruby gems disappearing! were installed but they're not anymore

### ISSUE THREAD

**Issue by BarcoMasile** [rubygems/rubygems#1870]
My problem is with 'pdf-reader' and 'nokogiri'.
I used to have nokogiri installed (with no issues) and I happened to use it from now and then. Then suddenly when I went to use it again, one day, it just could not be "required" by the interpreter so I looked for it and it was not there anymore, the gem was not installed anymore (and I swear I never uninstalled it, since I need it). So I went to install it again and everything was fine.

The cycle repeated for three times. Never found anything online that addresses this issue.
Today the same thing happened with "pdf-reader"

```
> gem env version
2.6.10
```

In the meantime I didnt' execute the "gem cleanup" command . Just saying. 
If someone can help me solve this it would be awesome, I'm tired of installing nokogiri and then have it disappeared when I need it ;(

**Comment by bronzdoc** [comment]
Hi @BarcoMasile i'm sorry to hear about your issue, but i highly doubt is a rubygems problem.
Rubygems don't suddenly uninstall gems, make sure nothing in your environment is messing  with `GEM_HOME` , `GEM_PATH` environment variables.

I'm going to close this ticket, but will be glad to reopen it if you can provide steps to reproduce it.
