### ISSUE TITLE
rubygems json specification confusion

### ISSUE THREAD

**Issue by colby-swandale** [rubygems/rubygems#1871]
I'm working on a few things in Bundler and i have come across something i don't understand in rubygems.

```
› gem env version
2.6.11

› irb
irb(main):001:0> Gem::Specification.find_by_name('json').full_gem_path
=> "/Users/c/.rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/json-2.0.2"
irb(main):002:0> require 'json'
=> true
irb(main):003:0> JSON.method(:parse).source_location
=> ["/Users/c/.rubies/ruby-2.4.0/lib/ruby/2.4.0/json/common.rb", 155]

› cd /Users/c/.rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/json-2.0.2
/Users/c/.rubies/ruby-2.4.0/lib/ruby/gems/2.4.0/gems/json-2.0.2: no such file or directory
```

RubyGems has a specification for the default gem `json` that has a path which doesn't exist.

I've tried searching for anything similar but was unable to find any information. Is this an upstream problem or something quirky in rubygems? Any explanation is appreciated.

Thanks in advance.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
That's because json is a default gem which is vendoredin the Ruby stdlib

**Comment by colby-swandale** [comment]
thanks @segiddins
