### ISSUE TITLE
Incompatible character encodings: UTF-8 and ASCII-8BIT

### ISSUE THREAD

**Issue by n-kiran** [rubygems/rubygems#1872]
Hi,

When trying to install ruby gems the below error is encountered.

ERROR:  While executing gem ... (Encoding::CompatibilityError)
    incompatible character encodings: UTF-8 and ASCII-8BIT

Found Ruby version 2.3.3,
and the issue is observed only on some PC's.

Configuration of PC on which error is encountered.
Windows 7 Professional SP1(x64).

Thanks,
nkiran.

**Comment by bronzdoc** [comment]
@n-kiran  What command are you executing that triggers the error?
