### ISSUE TITLE
MinGW builds, rubygems tests, ENV['GIT']

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#1875]
Ruby doesn't use MinGW / MSYS2 to build Ruby, and they don't run test-all.  Call me crazy, but I've been running MinGW / MSYS2 builds of ruby trunk (for several months), and running test-all...

RubyGems runs appveyor tests, but the git environment is not set up, which causes many of the 73 skips.

The issue is the use of the string `'git'` in the following files (line highlighted) -

ruby / ruby [lib/rubygems/test_case.rb](https://github.com/ruby/ruby/blob/trunk/lib/rubygems/test_case.rb#L487)
rubygems / rubygems [lib/rubygems/test_case.rb](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/test_case.rb#L499)

If the first `Gem::Util.popen` parameter `'git'` is replaced with `@git`, and one set's ENV['GIT'] to a correct path (with no spaces), the skips drop to 36, with one failure and no errors.  I needed to create a symbolic link to a path with no spaces, since 'Git for Windows' installs to `Program Files`.

I can't test on a non Windows environment.  I would certainly appreciate if someone could check this.  Earlier in the files ([rubygems](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/test_case.rb#L289) and [ruby](https://github.com/ruby/ruby/blob/trunk/lib/rubygems/test_case.rb#L280)) is where `@git` is set, so it certainly seems like the change should not cause issues for any platform.

Here are my current environment details:

`ruby 2.5.0dev (2017-03-26 trunk 58142) [x64-mingw32]`
RubyGems 2.6.11

FYI, current failure info is:

```
TestGemRequestSetLockfile#test_to_s_gem_dependency_non_default [E:/GitHub/ruby/test/rubygems/test_gem_request_set_lockfile.rb:239]:
--- expected
+++ actual
@@ -22,5 +22,5 @@
 " +
 "  a
 " +
-"  b
+"  b (>= 1)
 "

```

I have not yet taken any time to track the failure down.  For those interested, current trunk test data is:
```
64 bit  16625 tests, 2233555 assertions,  8 failures, 1 errors, 113 skips
32 bit  16636 tests, 2226385 assertions, 10 failures, 2 errors, 112 skips
```
I'm working on code so I can post results on the web.

[Ruby, Rails, & AWS docs](https://msp-greg.github.io/)

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Closed by https://github.com/rubygems/rubygems/pull/1876
