### ISSUE TITLE
Requiring rubygems/config_file activates the etc gem

### ISSUE THREAD

**Issue by segiddins** [rubygems/rubygems#1888]
On Ruby 2.5, requiring `rubygems/config_file` will activate the default `etc` gem.

**Comment by segiddins** [comment]
This would've been caused by https://github.com/ruby/ruby/commit/55c13218d9c8320f694748efbd9b4a642380b7b6 (see https://github.com/rubygems/rubygems/blob/master/lib/rubygems/config_file.rb#L63)

**Comment by segiddins** [comment]
@hsbt any ideas how we could re-implement the required functionality ourselves?

**Comment by deivid-rodriguez** [comment]
The effects of this were alleviated by https://github.com/bundler/bundler/commit/c7ac5b38012051379fb87d40e31e0887833dca98, but still no real solution for this.

**Comment by djberg96** [comment]
@segiddins What is the issue with require'ing etc?

**Comment by segiddins** [comment]
Requiring activates the etc gem, so users effectively can’t pick another version of that gem

**Comment by djberg96** [comment]
Wouldn't that be true for every stdlib?

**Comment by deivid-rodriguez** [comment]
Yes... :disappointed:. It's true for every _gemified_ stdlib. That's why we try hard not to use those, or vendor them when we do. But with `etc` it's harder because it has a C-extension so we can't vendor it.

**Comment by djberg96** [comment]
There a way users can preload a different version, maybe in the .gemrc?

**Comment by segiddins** [comment]
Not really, no

**Comment by hsbt** [comment]
We need to announce its limitation or rewrite it because I will promote all of the stdlibs to gem.

**Comment by deivid-rodriguez** [comment]
This issue was fixed by https://github.com/rubygems/bundler/commit/c7ac5b38012051379fb87d40e31e0887833dca98, and now the `rubygems/config_file` is not required when it may conflict with user chosen gem activation (`bundler/setup`). We still have some issues with some default gems, but this particular problem is no longer an issue, so closing!
