### ISSUE TITLE
OpenSSL::X509::StoreError on IBM i (iSeries/AS400) system using Windows

### ISSUE THREAD

**Issue by regalbob** [rubygems/rubygems#1890]
I'm having a problem or would like to suggest a feature.

_My current problem is:_
When trying to install bundler get error "OpenSSL::X509::StoreError" :
**gem install bundler --version '1.14.6'**
ERROR: While executing gem ... (OpenSSL::X509::StoreError)

This issue is related to:
  - [ ] The command line `gem`

Here are my current environment details:
IBM i (iSeries / AS400) in their UNIX PASE shell using Windows 10.

$ gem env version: 2.2.5 
$ ruby 2.1.9p490
$ Rails 4.1.15

**Comment by segiddins** [comment]
Please see http://guides.rubygems.org/ssl-certificate-update/ for some information about this (long story short, we needed to update certs and we did that in RubyGems 2.6.8+)

**Comment by regalbob** [comment]
Thanks. I've already updated via:

```
gem install --gem /path/to/rubygems.gem
update-2.6.1.gem installed

```
...but I still get error "OpenSSL::X509::StoreError" when trying to install bundler.

**Comment by segiddins** [comment]
You need to update to 2.6.8+, 2.6.1 won't have the new certs

**Comment by regalbob** [comment]
Where is that version? The RubyGem points to 2.6.11 not 2.6.8:

[](http://guides.rubygems.org/ssl-certificate-update/)

![image 2017-04-07 07 46 13](https://cloud.githubusercontent.com/assets/26824751/24800655/88ad7bde-1b66-11e7-863a-fc6ef43d1654.png)

**Comment by segiddins** [comment]
In the output you commented, it said `2.6.1.gem`

**Comment by regalbob** [comment]
So I tried the RubyGems 2.6.11 install again and it installed it, but then when i run the bundle command it fails??

![image 2017-04-07 08 04 04](https://cloud.githubusercontent.com/assets/26824751/24801225/e68f6b98-1b68-11e7-82fb-66faa58b0441.png)

**Comment by regalbob** [comment]
Oh, so 2.6.11 is later than 2.6.8?

**Comment by colby-swandale** [comment]
yes

**Comment by regalbob** [comment]
Ok, thanks! That leaves me with the bundler error posted above...

Why would it install it but then not be found?

**Comment by bronzdoc** [comment]
I'm going to close this since your original issue was fixed @regalbob

**Comment by colby-swandale** [comment]
I'm not sure about the ruby setup on your platform but i'm guessing the gem executable path if not in your `$PATH`.

Run `gem env` and look for the entry: `EXECUTABLE DIRECTORY`. Make sure that's included in your `$PATH` env variable.

**Comment by regalbob** [comment]
Got it. Here it is. But how do I set my **%PATH env variable**?

```
RubyGems Environment:                                                  
  - RUBYGEMS VERSION: 2.6.11                                           
  - RUBY VERSION: 2.1.9 (2016-03-30 patchlevel 490) [powerpc-aix6.1]   
  - INSTALLATION DIRECTORY: /PowerRuby/prV2R1/lib/ruby/gems/2.1.0      
  - USER INSTALLATION DIRECTORY: /home/BOKOSHAR/.gem/ruby/2.1.0        
  - RUBY EXECUTABLE: /PowerRuby/prV2R1/bin/ruby                        
  **- EXECUTABLE DIRECTORY: /PowerRuby/prV2R1/bin**                        
  - SPEC CACHE DIRECTORY: /home/BOKOSHAR/.gem/specs                    
  - SYSTEM CONFIGURATION DIRECTORY: /PowerRuby/prV2R1/etc              
  - RUBYGEMS PLATFORMS:                                                
    - ruby                                                             
    - powerpc-aix-6                                                    
  - GEM PATHS:                                                         
    - /PowerRuby/prV2R1/lib/ruby/gems/2.1.0    
    - /home/BOKOSHAR/.gem/ruby/2.1.0           
 - GEM CONFIGURATION:                          
    - :update_sources => true                  
    - :verbose => true                         
    - :backtrace => false                      
    - :bulk_threshold => 1000                  
 - REMOTE SOURCES:                             
    - https://rubygems.org/                    
 - SHELL PATH:                                 
    - /QOpenSys/usr/bin                        
    - /usr/ccs/bin                             
    - /QOpenSys/usr/bin/X11                    
    - /usr/sbin                                
    - .                                        
    - /usr/bin                                 
```

**Comment by regalbob** [comment]
My $PATH is:

`PATH=/QOpenSys/usr/bin:/usr/ccs/bin:/QOpenSys/usr/bin/X11:/usr/sbin:.:/usr/bin `

**Comment by regalbob** [comment]
Thanks, but am I cut off now? I posted later comments where I need to change my $PATH.

Thanks in advance!

Thanks,
Bob Kosharek
Sr. Programmer/Analyst

**Comment by colby-swandale** [comment]
I'm not sure, i'm not familiar with your shell. Maybe looks for an `export` utility like in Bash or edit the shell environment (like `.bashrc`) to append to your `$PATH`. You'll need to consult the documentation of your platform.
