### ISSUE TITLE
405 Method not Allowed when trying to install a gem

### ISSUE THREAD

**Issue by TrayWeb** [rubygems/rubygems#1893]
Good Evening,

I'm having issues when trying to install a gem.
Please see below, thanks for helping !

`$ gem install rail
ERROR:  While executing gem ... (Net::HTTPServerException)
    405 "Method Not Allowed"
`

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.5.2
```

**Comment by segiddins** [comment]
Can you please try with rubygems 2.6.11? `gem update --system`, and then running with `--verbose` to see if there are any more details?

**Comment by TrayWeb** [comment]
Thanks for the answer, same issue apparently.
I've ask the network admin to put me out of the proxy but it's still the same:

gem update --system

`$ gem update --system
ERROR:  While executing gem ... (Net::HTTPServerException)
    405 "Method Not Allowed"
`

**Comment by segiddins** [comment]
Did you try running with `--verbose` to see if it prints any salient details?

**Comment by TrayWeb** [comment]
This is what it give me:

`bezy-r@TI518 MINGW64 /
$ gem update --system --verbose
ERROR:  While executing gem ... (Net::HTTPServerException)
    405 "Method Not Allowed"

bezy-r@TI518 MINGW64 /
$ gem update --verbose
ERROR:  While executing gem ... (Net::HTTPServerException)
    405 "Method Not Allowed"
Updating installed gems

bezy-r@TI518 MINGW64 /
$

`

**Comment by segiddins** [comment]
What's the entire output of `gem env`?

**Comment by Tekover** [comment]
Good Day,
It was a proxy issue. I have set up the http_proxy env variable and it works now.
Thanks

**Comment by bor8** [comment]
I had a similar prob: I forgot the port in HTTPS_PROXY ;)
