### ISSUE TITLE
Unable to install any gem - SSL issue

### ISSUE THREAD

**Issue by vkyt** [rubygems/rubygems#1894]
I'm having a problem or would like to suggest a feature.

My current problem: unable to install any gem under https://rubygems.org

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

## Here are my current environment details:

```
$ gem env version
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.11
  - RUBY VERSION: 2.4.1 (2017-03-22 patchlevel 111) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/local/ANT/vickylee/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0
  - USER INSTALLATION DIRECTORY: /home/local/ANT/vickylee/.gem/ruby/2.4.0
  - RUBY EXECUTABLE: /home/local/ANT/vickylee/.rbenv/versions/2.4.1/bin/ruby
  - EXECUTABLE DIRECTORY: /home/local/ANT/vickylee/.rbenv/versions/2.4.1/bin
  - SPEC CACHE DIRECTORY: /home/local/ANT/vickylee/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/local/ANT/vickylee/.rbenv/versions/2.4.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/local/ANT/vickylee/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0
     - /home/local/ANT/vickylee/.gem/ruby/2.4.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/local/ANT/vickylee/.rbenv/versions/2.4.1/bin
     - /home/local/ANT/vickylee/.linuxbrew/Cellar/rbenv/1.1.0/libexec
     - /home/local/ANT/vickylee/.rbenv/shims
     - /home/local/ANT/vickylee/JAVA/jdk1.8.0_121/bin
     - /home/local/ANT/vickylee/.linuxbrew/sbin
     - /home/local/ANT/vickylee/.linuxbrew/bin
     - /home/local/ANT/vickylee/.npm-global/bin
     - /usr/lib/lightdm/lightdm
     - /usr/local/bin
     - /usr/bin
     - /bin
```

## Here's what I've tried:

I'm on Ubuntu 12.04 and have used linuxbrew to install rbenv.
Installed ruby 2.4.1 but couldn't get any of the gem to install due to the following error:
Unable to pull data from 'https://rubygems.org/': SSL_CTX_set_ecdh_auto

Tried uninstalling and reinstall ruby 2.4.1 with
CONFIGURE_OPTS="--with-opessl-dir=home/.linuxbrew/bin/openssl" rbenv install 2.4.1
But no luck, the error message changes to:
Unable to pull data from 'https://rubygems.org/': SSL_CTX_set_ecdh_auto: cert already in hash table

Followed the SSL update guide from RubyGems.org but that didn't help either. My gem version is already the latest - 2.6.11

System Setup:
which rbenv
'home/.linuxbrew/bin/rbenv'
which openssl
'home/.linuxbrew/bin/openssl'
ruby -ropenssl -e 'puts OpenSSL::OPENSSL_VERSION'
OpenSSL 1.0.2k 26 Jan 2017
ruby -ropenssl -e 'p OpenSSL::X509::DEFAULT_CERT_FILE'
"/usr/lib/ssl/cert.pem"

Any help is greatly appreciated!

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by Hubro** [comment]
I just installed Ruby 2.4.1 via RVM and I'm getting the exact same error, can't install any gems.

**Comment by colby-swandale** [comment]
@vkyt were you able to resolve your issue?

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
