### ISSUE TITLE
Unable to install any Gem. 

### ISSUE THREAD

**Issue by sansin** [rubygems/rubygems#1895]
I'm having a problem 

My current problem is I am unable to install any Gem. Below is the error I see every time I try to install a Gem. 

ERROR:  Could not find a valid gem 'mysql2' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details: 

```
$ gem env version
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.7
  - RUBY VERSION: 2.1.5 (2014-11-13 patchlevel 273) [x86_64-darwin14.0]
  - INSTALLATION DIRECTORY: /Users/SS/.rvm/gems/ruby-2.1.5
  - USER INSTALLATION DIRECTORY: /Users/SS/.gem/ruby/2.1.0
  - RUBY EXECUTABLE: /Users/SS/.rvm/rubies/ruby-2.1.5/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/SS/.rvm/gems/ruby-2.1.5/bin
  - SPEC CACHE DIRECTORY: /Users/SS/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-14
  - GEM PATHS:
     - /Users/SS/.rvm/gems/ruby-2.1.5
     - /Users/SS/.rvm/gems/ruby-2.1.5@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/SS/.rvm/gems/ruby-2.1.5/bin
     - /Users/SS/.rvm/gems/ruby-2.1.5@global/bin
     - /Users/SS/.rvm/rubies/ruby-2.1.5/bin
     - /usr/local/opt/openssl/bin
     - /Library/Java/JavaVirtualMachines/jdk1.8.0_111.jdk/Contents/Home/bin
     - /Users/SS/Dropbox/Education/spark/bin
     - /usr/local/bin
     - /Users/SS/Library/Enthought/Canopy_32bit/User/bin
     - /usr/local/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Users/SS/.rvm/bin
```
Here is what i tried. Everything succeeded except last 2 steps. 
I followed this document. http://guides.rubygems.org/ssl-certificate-update/

  535  gem install --local ~/.ssh/rubygems-update-2.6.11.gem
  536  update_rubygems
  537  gem --version
  538  gem uninstall rubygems-update -x
  539  gem update --system
  541  gem which rubygems
  542  cd /Users/SS/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/ssl_certs/
  548  cp /Users/SS/.ssh/GlobalSignRootCA.pem .
  550  gem update --system
  551  gem install mysql2

ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
Please see http://guides.rubygems.org/ssl-certificate-update/

**Comment by sansin** [comment]
Yes, I did what mentioned in that link.

**Comment by bittner** [comment]
@segiddins I've update RubyGems to the current version, I've also verified that the installed certificate matches the one mentioned in the [manual update steps](http://guides.rubygems.org/ssl-certificate-update/#manual-solution-to-ssl-issue), but the issue remains.
``` bash
$ gem --version                                                         :(
2.6.12
```
Maybe worth mentioning, I'm trying to set up Debian 8 Jessie box with Puppet + The Foreman as described in [Andrew Wippler's blog](https://andrewwippler.com/2016/10/21/deploying-puppet-open-source/), and the problem pops up when I try to run the Puppet manifest `r10k-install.pp` mentioned in the blog post.
``` bash
Error: Execution of '/opt/puppetlabs/puppet/bin/gem install --no-rdoc --no-ri r10k --no-ri --no-rdoc' returned 2: ERROR:  Could not find a valid gem 'r10k' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/latest_specs.4.8.gz)
Error: /Stage[main]/R10k::Install/Package[r10k]/ensure: change from absent to present failed: Execution of '/opt/puppetlabs/puppet/bin/gem install --no-rdoc --no-ri r10k --no-ri --no-rdoc' returned 2: ERROR:  Could not find a valid gem 'r10k' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/latest_specs.4.8.gz)
```
Any idea what could still be wrong?

**Comment by colby-swandale** [comment]
I'm closing this issue, if anyone is still experiencing this issue don't be afraid to open a new issue with the details of your problem.
