### ISSUE TITLE
Checksum Inconsistent with the downloaded gem and expected value - azure gem

### ISSUE THREAD

**Issue by sarangan12** [rubygems/rubygems#1900]
I'm having a problem:

My current problem is: I have released the azure gem (v 0.7.8) on April 17, 2017. (Ref: https://rubygems.org/gems/azure/versions/0.7.8). In the page, the checksum value is mentioned as "6210f164e1ece6b68961a68cfc7a16d764033d53aa3016a6e51836a383a25798". 

But, while actually installing the gem using the gem install command and then checking the checksum, the value is "b5b99af4ac7153e074742a55ed1e3d1d9522ad6d79d94edba42ea172f5c22198". Our users are not able to install this gem using the bundler due to this inconsistency. (Ref:https://github.com/Azure/azure-sdk-for-ruby/issues/755) Please help me to resolve this issue.

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [x] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.11
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
This is actually an issue with rubygems.org, please see https://github.com/rubygems/rubygems.org/issues/1564 and https://github.com/rubygems/rubygems.org/issues/1551 for more information

**Comment by sarangan12** [comment]
@segiddins Thanks. The explanation in #1551 is clear. I have added condition to the deploy operation in the travis yaml file and released a new version of azure gem which resolved the issue. Closing this issue
