### ISSUE TITLE
selenium-webdriver 3.3.0 - action class double_click not working

### ISSUE THREAD

**Issue by gklueh** [rubygems/rubygems#1902]
I'm having a problem.

My current problem is I am unable to get the double_click method within the Action class of Ruby 2.3.1's gems to work using the selenium-webdriver 3.3.0 driver and the ChromeDriver version 2.28 or 2.29 using the following code:

Sample from [here](https://seleniumhq.github.io/selenium/docs/api/rb/Selenium/WebDriver/ActionBuilder.html#double_click-instance_method):
`el = driver.find_element(id: "some_id")`
`driver.action.double_click(el).perform`

Code:
`@article_zone = @driver.find_element(:id, "viewer-zone-overlay-13B27E79C7BC32F1")`
`@driver.action.double_click(@article_zone).perform`

Note: This same code works using selenium standalone server version 3.3.1 with both ChromeDrivers above.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ x] Other

Here are my current environment details:

```
$ gem env version
2.6.10
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
This looks like an issue with a particular gem, not the RubyGems runtime library. You should consult the authors of that gem for support.

**Comment by gklueh** [comment]
Thanks @segiddins
