### ISSUE TITLE
Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version 

### ISSUE THREAD

**Issue by jpswade** [rubygems/rubygems#1912]
My current problem is I can't get gems.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.0.14.1
$ sudo gem update --system
Latest version currently installed. Aborting.
$ sudo gem install bundler
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version (https://rubygems.org/latest_specs.4.8.gz)
```

**Comment by brentd-smith** [comment]
Could not find a valid gem 'dpl' (>= 0), here is why:

Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=unknown state: tlsv1 alert protocol version (https://api.rubygems.org/specs.4.8.gz)
The command "rvm $(travis_internal_ruby) --fuzzy do ruby -S gem install dpl" failed and exited with 2 during .

**Comment by ryanahall** [comment]
Following.

We are also seeing this issue in our internal build systems (e.g. travis).

**Comment by oliver-spryn** [comment]
Same here. I cannot download gems from a Terminal despite just updating to 2.6.12 and manually installing the prm cert.

**Comment by maxfierke** [comment]
Seems Fast.ly is only supporting TLS 1.2 according to this [TLS report](https://www.ssllabs.com/ssltest/analyze.html?d=index.rubygems.org&s=151.101.128.70&hideResults=on&latest) I just ran

**Comment by timsutton** [comment]
Running `/usr/bin/gem` on macOS will use Apple's Ruby 2.0.0 linked to their old OpenSSL 0.9.8, which will fail with servers supporting only TLS 1.2.

**Comment by nisavid** [comment]
Looks like the restriction to TLS 1.2 has been reverted, at least for rubygems.org:443.  See [the latest SSL Labs test result](https://www.ssllabs.com/ssltest/analyze.html?d=rubygems.org&s=151.101.194.2&latest) or test for yourself with one of the following commands:
```
openssl s_client -connect rubygems.org:443 -tls1
openssl s_client -connect rubygems.org:443 -tls1_1
```

**Comment by segiddins** [comment]
We've migrated to a fastly cert that will allow us to serve content over TLS 1.0 for the time being, however by the end of June 2018 that option will no longer be available

**Comment by haidangwa** [comment]
We're not able to connect today, as well.

**Comment by haidangwa** [comment]
I also updated the ca-certificates package on my machine (rhel6)

**Comment by robbyrussell** [comment]
We're seeing the same type of problem with api.rubygems.org

$ openssl s_client -connect api.rubygems.org:443 -tls1_2 -servername api.rubygems.org
CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    Start Time: 1495495578
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)

**Comment by robbyrussell** [comment]
@segiddins Did you setup a TLS1 cert for `api.rubygems.org`, too? 

I'm trying to sort out how to resolve this issue:

    curl https://api.rubygems.org/specs.4.8.gz
    curl: (35) Unknown SSL protocol error in connection to api.rubygems.org:443

**Comment by segiddins** [comment]
RubyGems comes bundled with all the certs needed to talk to the current set of RubyGems servers (and a whole bunch of other root CAs)

**Comment by colby-swandale** [comment]
I'm closing this issue, if anyone is still experiencing this issue don't be afraid to open a new issue with the details of your problem.

**Comment by a-lebedev** [comment]
had similar problem, i've updated ruby through homebrew and exec "bundle install" in the root of project

**Comment by lucasmpb** [comment]
```
We've migrated to a fastly cert that will allow us to serve content over TLS 1.0 for the time being, however by the end of June 2018 that option will no longer be available
```
Looks like the cert has expired, we are having the same issue again @segiddins.

**Comment by gdv-deepakk** [comment]
Same issue on MacOSX
```
$ gem env version
2.0.14.1

$ gem install rest-client --debug
Exception `Errno::EEXIST' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245 - File exists - /Users/deepakk/.gem/specs/rubygems.org%443
Exception `OpenSSL::SSL::SSLError' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921 - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version
Exception `OpenSSL::SSL::SSLError' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:929 - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version
Exception `Gem::RemoteFetcher::FetchError' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/remote_fetcher.rb:426 - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version (https://rubygems.org/latest_specs.4.8.gz)
Exception `Gem::RemoteFetcher::FetchError' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/remote_fetcher.rb:289 - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version (https://rubygems.org/latest_specs.4.8.gz)
Exception `Gem::SpecificGemNotFoundException' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/dependency_installer.rb:308 - Could not find a valid gem 'rest-client' (>= 0) locally or in a repository

ERROR:  Could not find a valid gem 'rest-client' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version 

(https://rubygems.org/latest_specs.4.8.gz)
Exception `Errno::EEXIST' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245 - File exists - /Users/deepakk/.gem/specs/rubygems.org%443
Exception `OpenSSL::SSL::SSLError' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921 - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version
Exception `OpenSSL::SSL::SSLError' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:929 - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version
Exception `Gem::RemoteFetcher::FetchError' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/remote_fetcher.rb:426 - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version (https://rubygems.org/prerelease_specs.4.8.gz)
Exception `Gem::RemoteFetcher::FetchError' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/remote_fetcher.rb:289 - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version (https://rubygems.org/prerelease_specs.4.8.gz)
Exception `Errno::EEXIST' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:245 - File exists - /Users/deepakk/.gem/specs/rubygems.org%443
Exception `OpenSSL::SSL::SSLError' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:921 - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version
Exception `OpenSSL::SSL::SSLError' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/net/http.rb:929 - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version
Exception `Gem::RemoteFetcher::FetchError' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/remote_fetcher.rb:426 - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version (https://rubygems.org/specs.4.8.gz)
Exception `Gem::RemoteFetcher::FetchError' at /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/remote_fetcher.rb:289 - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version (https://rubygems.org/specs.4.8.gz)
```

**Comment by renzors** [comment]
This guide worked for me to resolve the issu: https://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html

What I did?
Upgrade OpenSSL to latest version.
Upgrade Ruby to latest version.

**Comment by mustela** [comment]
Having the same issue. Upgrading open ssl didnt fix the problem and I cant use the last ruby version.

**Comment by szeck87** [comment]
Running `ruby -ropen-uri -e 'eval open("https://git.io/vQhWq").read'` in my appveyor.yml file yields:
```
C:/Ruby23/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
```

I've tried updating gem, but that didn't resolve it in that environment.

**Comment by aavram** [comment]
Im getting the following error when I run - sudo gem install cocoapods: 

Could not find a valid gem 'cocoapods' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert protocol version (https://rubygems.org/latest_specs.4.8.gz)

**Comment by indirect** [comment]
Please follow the [Bundler and RubyGems TLS/SSL Troubleshooting Guide](https://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html), and create a new ticket following the instructions if you are still having issues.
