### ISSUE TITLE
Obfuscate author emails on site profile pages

### ISSUE THREAD

**Issue by rlue** [rubygems/rubygems#1913]
I'm curious to know what policy the RubyGems.org team follows on this issue (if any).

In brief, some sites (like GitHub) will obfuscate users' email addresses in the raw HTML before publishing it online, in order to protect their users from email harvesting bots. For instance, this is the raw HTML corresponding to the email address shown on my profile page:

```
<a href="mailto:&#x68;&#x65;&#x6c;&#x6c;&#x6f;&#x40;&#x72;&#x79;&#x61;&#x6e;&#x6c;&#x75;&#x65;&#x2e;&#x63;&#x6f;&#x6d;">&#x68;&#x65;&#x6c;&#x6c;&#x6f;&#x40;&#x72;&#x79;&#x61;&#x6e;&#x6c;&#x75;&#x65;&#x2e;&#x63;&#x6f;&#x6d;</a>
```

In theory, this approach offers hardly any security at all – it would be trivial for a bot to convert HTML entity codes before scraping the content for potential emails – but it seems to be good enough for GitHub. RubyGems.org, on the other hand, publishes email addresses in the open, without obfuscation.

I myself am undecided on whether this issue is worthy of attention in practice (I certainly haven't received any spam since publishing my first gem), though in principle, I believe it to be the responsibility of web developers to protect their users' personal data. 

Does the RubyGems.org team have an opinion on this one? Would they even entertain a PR that implemented this sort of email obfuscation?

**Comment by colby-swandale** [comment]
This is an issue for rubygems.org not rubygems, you should open this ticket at [rubygems/rubygems.org](https://github.com/rubygems/rubygems.org)

**Comment by rlue** [comment]
Ahaha that's embarrassing, thanks.
