### ISSUE TITLE
2 Builds are triggered on Travis CI for each push to GitHub

### ISSUE THREAD

**Issue by BanzaiMan** [rubygems/rubygems#1921]
# Problem

RubyGems workflow triggers 2 identical builds on Travis CI. This is wasteful and unnecessary.

# Details

https://travis-ci.org/rubygems/rubygems/requests shows 2 builds for each commit (belonging to the same PR). For example, https://travis-ci.org/rubygems/rubygems/builds/231127909 and https://travis-ci.org/rubygems/rubygems/builds/231127929 test the same code.

It is not clear to me how this is happening.

------

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by BanzaiMan** [comment]
It is not just PRs.

**Comment by hsbt** [comment]
We need to configure webhook entries.

@segiddins @indirect Can you check it? (or please promote me to admin grant in this repository)

**Comment by segiddins** [comment]
I think this is because of how https://github.com/barosl/homu works

**Comment by indirect** [comment]
@hsbt I have checked the webhooks, and they seem okay to me. I have also added you as an admin to this repo so you can check the webhooks yourself, please let me know if you find anything.

@BanzaiMan I was under the impression that Travis would no-op any requests to build the exact same commit sha twice... is that wrong? The workflow with Homu is that the PR is automatically tested, but then after the PR is approved, Homu creates a new commit merging the approved PR with `master`, and force-pushes it to the `auto` branch. If that commit builds green, Homu then fast-forwards the `master` branch to that commit. If there are any more accepted PRs, it then repeats, creating a new merge commit with the next PR and the new tip of the `master` branch, etc. Would that cause double builds for the same commit?

**Comment by BanzaiMan** [comment]
@indirect There is no duplicate request detection with Travis CI right now. If, for some reason, we receive 2 build requests to bearing the same payload, we run the same build twice.

Homu's workflow is interesting, but I do not think it is not the cause of this issue; upon auto-merge of `#1917`, for example, Homu triggered two builds as expected, but each of these two builds had their companion build because of *this* issue, resulting in 4 builds: [3802](https://travis-ci.org/rubygems/rubygems/builds/231246601), [3803](https://travis-ci.org/rubygems/rubygems/builds/231246624), [3804](https://travis-ci.org/rubygems/rubygems/builds/231260656), [3805](https://travis-ci.org/rubygems/rubygems/builds/231260689).

I would think that there are 2 distinct notifications firing from GitHub as a result of a single push (on branch, or on a PR), but I can't confirm this. Maybe GitHub support can shed some light, if no one on the RubyGems team can troubleshoot it.

**Comment by indirect** [comment]
@BanzaiMan got it, thanks for the explanation. I checked the webhook settings, and we only seem to have one travis webhook. Maybe it's time to escalate this to GitHub support.

**Comment by colby-swandale** [comment]
This looks like it's still an issue, is there anything i can do to help?

**Comment by indirect** [comment]
@colby-swandale I just noticed that `rubygems/rubygems` had both an "Integration" set up for Travis CI, and also had a webhook set up pointing at `notify.travis-ci.org`. Maybe that was creating two builds?

**Comment by indirect** [comment]
I have removed the webhook, leaving only the "integration". Let's see if that fixes it. 👍

**Comment by colby-swandale** [comment]
This looks fixed now: https://travis-ci.org/rubygems/rubygems/requests

**Comment by abdelrhmanghreeb** [comment]
This is not fixed in python yet

**Comment by BanzaiMan** [comment]
@abdelrhmanghreeb How does Python come into play? Are you saying that a push to a certain Python repository results in 2 builds? If so, that is a problem with that repository. I'm happy to discuss that, but you should take that discussion elsewhere.
