### ISSUE TITLE
Unable To Access api.rubygems.org: Packet analysis shows "Application Type" header malformed. 

### ISSUE THREAD

**Issue by nathan-lochala** [rubygems/rubygems#1922]
I'm having a problem or would like to suggest a feature.

My current problem is: Unable to download gems as our hardware firewall is showing the application type for the api.rubygems.org:443 traffic as "meetup-base". Meetup-base, as defined by our Palo-Alto firewalls, is a social networking application. We are worried there might be a configuration problem on the api.rubygems.org web server.  

![screen shot 2017-05-15 at 1 40 06 pm](https://cloud.githubusercontent.com/assets/5444215/26081778/f4c12d40-3978-11e7-9dff-bdfdc5a94d5c.png)

This issue is related to:

  - [ X ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ X ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.0.14.1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by indirect** [comment]
@nathan-lochala hi nathan. Firstly, I'd suggest that you move this ticket over to the repo for the website: https://github.com/rubygems/rubygems.org. Second, you're going to need to provide more information for us to be able to do anything about this. Why does your firewall think this traffic is "meetup-base"? What is the actual network traffic you are seeing when you make requests? Thanks.
