### ISSUE TITLE
`gem server` has issues serving gemspecs for gems with numbers in their name

### ISSUE THREAD

**Issue by fbacall** [rubygems/rubygems#1924]
When trying to serve the gemspec for a gem named "rfc-822", the server responds with a 404 even though the gem is installed.

I checked out the repo and had a look at the code, and it seems like the regular expression here:
https://github.com/rubygems/rubygems/blob/master/lib/rubygems/server.rb#L576
is erroneously extracting the "822" from the gem name as its `version`, and the actual version "0.4.1" as the `platform`

I'm afraid regex skills are not really good enough to suggest an alternative!

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.12
$ ruby -v
ruby 2.2.7p470 (2017-03-28 revision 58194) [x86_64-linux]
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
Please see if https://github.com/rubygems/rubygems/pull/1926 fixes things for you!

**Comment by fbacall** [comment]
Yep, seems to work fine with that change
