### ISSUE TITLE
Wrong version of gem's binary is executed

### ISSUE THREAD

**Issue by x-yuri** [rubygems/rubygems#1932]
```
$ chruby 2.3.3
$ gem env version
2.5.2
$ gem list ^rails$
rails (5.1.1, 5.0.2)

$ rails _5.0.2_ --version
Rails 5.1.1

$ gem update --system
$ gem env version
2.6.12

$ rails _5.0.2_ --version
Rails 5.1.1

$ chruby 2.4.0
$ gem env version
2.6.8
$ gem list ^rails$
rails (5.1.1, 5.0.2)


$ rails _5.0.2_ --version
Rails 5.0.2
```

With both `ruby` versions correct binary gets executed (from `railties-5.0.2`). But when gem's binary tries to require `rails/cli`, `ruby-2.3.3` raises [exception][1], and jumps [here][2], where it supposedly falls back to latest gem version. Can you explain what's going on? This is supposed to be [fixed][3], isn't it? Or this can't be solved by `gem update --system`? Any workaround for `ruby-2.3.3`?

[1]: https://github.com/rubygems/rubygems/blob/v2.6.12/lib/rubygems/core_ext/kernel_require.rb#L55
[2]: https://github.com/rubygems/rubygems/blob/v2.6.12/lib/rubygems/core_ext/kernel_require.rb#L122
[3]: https://github.com/rubygems/rubygems/pull/1527#issuecomment-193606774

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by matthewd** [comment]
@x-yuri if your bin file was generated with a RubyGems version with the #1527 bug, you'll need to recreate it with something like `gem pristine --all --only-executables` after `gem update --system`.

(Though, as you're trying to run an older `rails`, note you may then run into #1931.)

**Comment by x-yuri** [comment]
Great, it helped, thanks.

What bothers me is that it changed

```ruby
load Gem.activate_bin_path('railties', 'rails', version)
```

in `~/.gem/ruby/2.3.3/bin/rails` to

```ruby
if Gem.respond_to?(:activate_bin_path)
load Gem.activate_bin_path('railties', 'rails', version)
else
gem "railties", version
load Gem.bin_path("railties", "rails", version)
end
```

But with `2.4.0` and `2.4.1` this file is as in the first snippet.

> (Though, as you're trying to run an older rails, note you may then run into #1931.)

Actually, I seem to have run into this issue while experimenting. Should I probably experiment some more...

**Comment by colby-swandale** [comment]
I'm closing this issue, feel free to open a new issue if you're still experiencing any issues.
