### ISSUE TITLE
Question: How to logout of `gem` cli?

### ISSUE THREAD

**Issue by shivabhusal** [rubygems/rubygems#1933]
I'm having a problem.

My current problem is: I am unable to logout of the `gem` cli. I have logged in with one email but want to login as another now.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by chrisarcand** [comment]
Try resetting your API key at https://rubygems.org/profile/edit and/or removing your local credential file containing that key at `~/.gem/credentials`

**Comment by shivabhusal** [comment]
wont it be better if we had a command like `gem logout` and `gem login` or something? @chrisarcand what do you think?

**Comment by chrisarcand** [comment]
I was thinking something along those lines myself, yes.

**Comment by simi** [comment]
Remove `~/.gem/credentials` should work also. I think it can be easy to implement logout this way. Will be PR welcomed?

**Comment by shivabhusal** [comment]
@simi I am on it, almost going to submit a PR

**Comment by dorianmariefr** [comment]
On rubygems `3.3.13` I have `gem logout` / `gem login` but there is no `~/.gem/credentials` file, has it changed?

**Comment by simi** [comment]
@dorianmariefr check ` Gem.configuration.credentials_path` in IRB.

**Comment by dorianmariefr** [comment]
thanks @simi, for reference it's `~/.local/share/gem/credentials` on my machine
