### ISSUE TITLE
Unable to push Gem

### ISSUE THREAD

**Issue by gURLmeetsCode** [rubygems/rubygems#1935]
I'm having a problem or would like to suggest a feature.

My current problem is with pushing ruby gem to rubygems.org page

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ X] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
Manually 

Successfully built RubyGem
  Name: dev_jobs
  Version: 0.1.0
  File: dev_jobs-0.1.0.gem
Natashas-MacBook-Pro:dev_jobs natashakelly$  gem push dev_jobs.gemspec
ERROR:  While executing gem ... (Gem::Package::FormatError)
    package metadata is missing in dev_jobs.gemspec
Natashas-MacBook-Pro:dev_jobs natashakelly$  gem push dev_jobs-0.1.0.gem
Pushing gem to https://rubygems.org...
Access Denied. Please sign up for an account at https://rubygems.org

I also tried with a rake release and got the same error

please help!
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by chrisarcand** [comment]
Hi! It looks like you're trying to push the gemspec file (`dev_jobs.gemspec`) instead of your built gem (`dev_jobs-0.1.0.gem`)

Please try `gem push dev_jobs-0.1.0.gem`, which should also ask you for your RubyGems credentials if you haven't already signed in on the command line. If you don't have an account, you can sign up here: https://rubygems.org/users/new

For more information about publishing your gem, see http://guides.rubygems.org/publishing/#publishing-to-rubygemsorg

**Comment by colby-swandale** [comment]
@chrisarcand Check the second command, @gURLmeetsCode did try pushing the gem to Rubygems.org and wasn't asked for the login credentials.

@gURLmeetsCode can you paste the output of `gem env` please.

**Comment by gURLmeetsCode** [comment]
@colby-swandale 

Here is the gem spec
`require_relative './lib/dev_jobs/version'


Gem::Specification.new do |spec|
  spec.name          = "dev_jobs"
  spec.version       = DevJobs::VERSION
  spec.authors       = ["Natasha Kelly"]
  spec.email         = "kellynatashav@yahoo.com"
  spec.date          = "2017-05-31"
  spec.files         = ["lib/dev_jobs.rb", "lib/dev_jobs/COMMAND_LINE_INTERFACE.rb", "lib/dev_jobs/scraper.rb", "lib/dev_jobs/job.rb", "config/environment.rb"]
  spec.summary       = "Stackoverflow Bay Area Dev Jobs"
  spec.description   = "Provides the job title, job link and when it was posted on the website."
  spec.homepage      = 'https://github.com/gURLmeetsCode/dev_jobs_CLI.git'
  spec.license       = 'MIT'
  spec.executables   << 'dev_jobs'

  spec.add_development_dependency "bundler", "~> 1.15"
  spec.add_development_dependency "rake", "~> 10.0"
  spec.add_development_dependency "rspec", ">= 0"
  spec.add_development_dependency "nokogiri", ">= 0"
  spec.add_development_dependency "pry", ">= 0"

end`

Here is the rakefile

 `require "bundler/gem_tasks"
require "rspec/core/rake_task"

RSpec::Core::RakeTask.new(:spec)


task :default => :spec
`

**Comment by colby-swandale** [comment]
@gURLmeetsCode were you able to resolve your problem with pushing that gem onto rubygems?

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
