### ISSUE TITLE
Windows 10: Errno::EACCESS error how to correct

### ISSUE THREAD

**Issue by kevin-marshall** [rubygems/rubygems#1936]
Attempting to upgrade from Ruby 2.2 to 2.4. Installed with Chocolatey v0.10.5.

Ruby version: ruby 2.4.1p111
Gem version: 2.6.12

> Error: Unable to download data from https://rubygems.org/ - Errno: :EACCES: Failed to open TCP connection to api.rubygems.org:443 (Permission denied - connect(2) for "api.rubygems.org" port 443 (https://api.rubygems.org/specs.4.8.gz) 

I have tried several solutions, don't have any idea what to do next. Have tried:

1. http://guides.rubygems.org/ssl-certificate-update/
2. http://guides.rubygems.org/ssl-certificate-update/#manual-solution-to-ssl-issue
3. <2.4 installation root>ssl/README-SSL.md

Is there a way to have the rubygems_update just correct the certificates?  Any ideas how to fix this? My 2.2 ruby installation was working, but now when I reinstall ruby 2.2 it has the same problem. , I am in a pretty good pickle, because ruby is central to my build process.

Is there a way to access the server in a non secure way until I can get the secure method working?

I have been running into this issue with the last few installations of ruby, is there any way to make the fix more transparent? 

Thanks,

Kevin

**Comment by kevin-marshall** [comment]
Just wanted to add that I was able to get out of my pickle. It was painful. I manually downloaded each gem and installed it locally. So there is no urgency for me currently, but I do need to figure out how to resolve this issue. I have been, personally, hitting this issue a lot, I think it has happened to me with each update after 2.2. I am at a loss, feel like I have tried all the suggestions I have been able to find.

**Comment by kevin-marshall** [comment]
This issue is now corrected on my machine. The solution was removing expired certificates from my machine.

**Comment by kevin-marshall** [comment]
Okay, I have solved this one. The issue was kaspersky. Scary that it is interfering with my network traffic. 

Anyway, speaking to the transparency issue what did end up helping me solve the issue was a couple of other programs started reporting errors. Luckily two of the programs reported the same error which turned me on to an environmental issue instead of an application specific issue.

Nuget package manager reported: 

> Unable to connect to the remote server
> An attempt was made to access a socket in a way forbidden by its access permissions

 

gitlab runner client reported: 

>... connectex: An attempt was made to access a socket in a way forbidden by its access permissions.

Ruby gems did state that it could not open the TCP connection (Permission denied - connect (2)). In all cases the error is vague, but having the exact same error message from multiple programs did help me to find a solution for the problem. 

So I am guessing that ruby's gem update is also receiving the error '_An attempt was made to access a socket in a way forbidden by its access permissions_', I think it would be helpful if that error message bubbled to the user.

**Comment by duckinator** [comment]
Glad you sorted it out, @kevin-marshall!

I don't feel it's worth the extra complexity to add that error message, given that it doesn't really add any more clarity as to what the problem. As such, I'm going to close this issue.

**Comment by mukulsaharia** [comment]
it is a anti virus issue. i uninstalled my anti virus and now rails working perfectly.... thumbs up...
