### ISSUE TITLE
Windows -x64-mingw32 gem version strings overwritten and then gem not found

### ISSUE THREAD

**Issue by skiprhudy** [rubygems/rubygems#1946]
In Windows I notice that installed gems are not being found when starting up Rails.

Specific issue: 
Ruby versions 2.2.5 and higher rename some Windows gems in version.rb by gsubbing '.pre.' for '-' in a gem's version string. Windows has some gems with installed names like:

bcrypt-3.1.11-x64-mingw32
bcrypt-ruby-3.1.5-x64-mingw32
nokogiri-1.7.2-x64-mingw32
tiny_tds-1.3.0-x64-mingw32

version.rb 'initialize' changes the version that was passed. For example passing in  '1.3.0-x64-mingw32':

```
def initialize version
    raise ArgumentError, "Malformed version number string #{version}" unless
      self.class.correct?(version)

    @version = version.to_s.strip.gsub("-",".pre.")
    @segments = nil
end
```
will result in the version changing to '1.3.0.pre.x64.pre.mingw32', which does not exist on the system and is also not in the Gemfile.

Is the renaming of the file strictly for some internal reason of version.rb? Should version.rb not be invoked in any way when trying to find real gems?  My Rails app definitely invokes version.rb 'initialize' when trying to load each gem specified in the Gemfile. The renamed (and now fictitious) gem can't be found, and Rails bombs out.

I found this trying to use Ruby 2.4.1 on Windows while in the context of starting up a Rails app with Bundler 1.15.1. By temporarily altering the initialize code to accept the real version string of the gem the problem went away.

The line of code that renames a file in version.rb was inserted in v2.2.5. 

v2.2.4, which is what I'm using, does not use the version re-naming code, and does not show this problem when Rails starts up. I'm using Rails 5.1.0

My current (2.2.4) environment doesn't have the problem but anyone using version.rb v2.2.5 and above could see this rename issue happen if their installed gems have -x64-mingw32 as part of the version string.

RubyGems Environment (sans re-name problem:
  - RUBYGEMS VERSION: 2.4.5.1
  - RUBY VERSION: 2.2.4 (2015-12-16 patchlevel 230) [x64-mingw32]
  - INSTALLATION DIRECTORY: C:/Ruby22-x64/lib/ruby/gems/2.2.0
  - RUBY EXECUTABLE: C:/Ruby22-x64/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/Ruby22-x64/bin
  - SPEC CACHE DIRECTORY: C:/Users/xxxx_xxxx/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x64-mingw32
  - GEM PATHS:
     - C:/Ruby22-x64/lib/ruby/gems/2.2.0
     - C:/Users/xxxx_xxxx/.gem/ruby/2.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Ruby22-x64\bin
...
     - C:\Code\Tools\DevKit\bin
     - C:\Code\Tools\DevKit\mingw
     - C:\Code\Tools\DevKit\mingw\bin
...
     - C:\Ruby22-x64\bin

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
`-x64-mingw32` shouldn't be part of the version string, but rather from the `platform` in the gemspec -- even though they look similar in `Gem::Specification#full_name`, they're not the same
