### ISSUE TITLE
Test Failure - TestGemRequestSetLockfile#test_to_s_gem_dependency_non_default

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#1948]
I have a test failure on a recent MinGW trunk build, although I've had it for a while.  The test is [here](https://github.com/rubygems/rubygems/blob/master/test/rubygems/test_gem_request_set_lockfile.rb#L214-L240).  I've been working with the Ruby test framework, but I doubt that changes the issue.  I believe the test passes in other architectures.  I also tried the test without a .gemrc file.

When the failure occurs, the strings are identical except the 'DEPENDENCIES' section:

```
----- expected -----
DEPENDENCIES
  a
  b

------ actual ------
DEPENDENCIES
  a
  b (>= 1)
```

The failure is odd, since most failures occur with code tracing back to some c source.  Added a few things to the test for debugging, then tried something.  The test contains the following two lines:

```ruby
    @set.gem 'b'
    @set.gem 'a'
```

If I swap the order so 'a' is set first, the test passes.  I haven't been too deep into RubyGems code, but I would guess that the test should have the same result regardless of order.

If that's wrong, a quick explanation would be appreciated.  If not, a hint as to where the source for some of this might be, and I'll see what I can find.

Here are my current environment details:

```
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.12
  - RUBY VERSION: 2.5.0 (2017-06-04 patchlevel -1) [x64-mingw32]
  - INSTALLATION DIRECTORY: C:/ruby25_64/lib/ruby/gems/2.5.0
  - USER INSTALLATION DIRECTORY: C:/Users/Greg/.gem/ruby/2.5.0
  - RUBY EXECUTABLE: C:/ruby25_64/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/ruby25_64/bin
  - SPEC CACHE DIRECTORY: C:/Users/Greg/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x64-mingw32
  - GEM PATHS:
     - C:/ruby25_64/lib/ruby/gems/2.5.0
     - C:/Users/Greg/.gem/ruby/2.5.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "install" => "--no-document --env-shebang --platform ruby -- --use-system-libraries"
     - "update" => "--no-document --env-shebang --platform ruby -- --use-system-libraries"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\ruby25_64\bin
     - C:\Windows\system32
     - C:\Windows
     - C:\Windows\System32\Wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0\
     - E:\msys64
     - C:\Program Files (x86)\GNU\GnuPG\pub
     - C:\Program Files\Git\cmd
     - C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
     -
     - C:\Program Files (x86)\Microsoft VS Code\bin
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
How are you running the tests?

**Comment by MSP-Greg** [comment]
Normally I run the ruby `test-all` and `spec` tests with every trunk build.  I've got a framework separate from ruby source so I can run the tests directly rather than running with `make`.  [`test-all` results](https://msp-greg.github.io/file.mingw_test-all.html) have been consistent for a while, so I decided to look at the regular failures.

**Comment by segiddins** [comment]
Does running `rake` in the RubyGems repo fail as well?

**Comment by MSP-Greg** [comment]
Current rakefile [line 69](https://github.com/rubygems/rubygems/blob/master/Rakefile#L69) is:

```
dependency 'minitest',      '~> 4.0',
```
ruby trunk is currently at 5.10.2.  My most recent trunk build is at 5.10.1, but I'll build today.

See [recent ruby commit](https://github.com/ruby/ruby/commit/39fbb2ea5f71e1f829532adaced07aa5eacdf58e).  Might this be considered for update?  That's why I have my own framework, which I used for another RubyGems testing issue regarding git.

**Comment by MSP-Greg** [comment]
After a bit of editing, tests are running with rake.  **Same failure**.

Bunch of errors due to ruby missing `make`.  I'll find a fix.

@hsbt - I get all sorts of warnings running `rake test` on this repo using ruby trunk with `minitest` dependency set to `>= 4.0` in test_case and rakefile. Have you tried that?

**Comment by MSP-Greg** [comment]
@segiddins @hsbt

[Minitest 5.0.0](https://github.com/seattlerb/minitest/blob/master/History.rdoc#500--2013-05-10) was released on 2013-05-10.

Maybe it's time?  I'm willing to work on it.  Maybe an MT5 branch?

**Comment by MSP-Greg** [comment]
@segiddins Sorry for the tirade.

Now, as I mentioned, test in 1st message failed in ruby/ruby tests.  Also fails using rubygems/rubygems `rake test`.

Making the change mentioned (flip order of `@set.gem 'b'` and `@set.gem 'a'`), test passes using `rake test`.

So, why does the operation seem to be 'order sensitive' on MinGW builds?

**Comment by segiddins** [comment]
I don't know, and unfortunately I won't be able to help debug it since I don't have a windows install handy.

**Comment by MSP-Greg** [comment]
Just started doing mswin builds (still doing MinGW builds), and the error is still present.  I tried deleting my .gemrc file, no difference.

Below is error info in a little different format:
```
Expected:
GEM
  remote: http://gems.example.com/
  specs:
    a (2)
      b (>= 1)
    b (2)

PLATFORMS
  ruby

DEPENDENCIES
  a
  b

Actual:
GEM
  remote: http://gems.example.com/
  specs:
    a (2)
      b (>= 1)
    b (2)

PLATFORMS
  ruby

DEPENDENCIES
  a
  b (>= 1)
```

I assume the 'DEPENDENCIES' are derived from the 'specs:'.  Is that correct?

Given the above output and available documentation, it's unclear to me what the  'DEPENDENCIES' section should contain...

**Comment by segiddins** [comment]
The dependencies section contains the dependencies declared directly in the gemfile.

**Comment by MSP-Greg** [comment]
There were two commits dealing with unstable sorting.  One addressed and fixed this issue.
