### ISSUE TITLE
Embedded Ruby and gem list

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#1957]
While working with an application with embedded ruby, the command equivalent of `gem list` was not showing default gems.  The issue is caused by [Gem::BasicSpecification.default_specifications_dir](https://github.com/rubygems/rubygems/blob/60006a8e46dbc307abf3ad02c6c4d8e8b85ceaee/lib/rubygems/basic_specification.rb#L37-L39), which is currently:

```ruby
def self.default_specifications_dir
  File.join(Gem.default_dir, "specifications", "default")
end
```

I changed it to:

```ruby
def self.default_specifications_dir
  dflt_dir = File.join(Gem.default_dir, "specifications", "default")
  Dir.exist?(dflt_dir) ? dflt_dir :
    File.join(Gem.dir, "specifications", "default")
end
```

And eveything works correctly.

I'd do a PR, but I'm not sure if more checks should be added, if this would be considered an issue with the embedded setup, etc.

But, using `Gem.default_dir` does seem to be making some assumptions about it being a standard ruby install...

RubyGems Environment (using a custom build of Ruby 2.3 stable):
```
  - RUBYGEMS VERSION: 2.6.12
  - RUBY VERSION: 2.3.5 (2017-05-01 patchlevel 310) [x64-mingw32]
  - INSTALLATION DIRECTORY: C:/Users/Greg/AppData/Roaming/SketchUp/SketchUp 2017/SketchUp/Gems64
  - USER INSTALLATION DIRECTORY: C:/Users/Greg/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: "C:/Program Files/SketchUp_23_1/SketchUp 2017/Tools/bin/ruby.exe"
  - EXECUTABLE DIRECTORY: C:/Users/Greg/AppData/Roaming/SketchUp/SketchUp 2017/SketchUp/Gems64/bin
  - SPEC CACHE DIRECTORY: C:/Users/Greg/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x64-mingw32
  - GEM PATHS:
     - C:/Users/Greg/AppData/Roaming/SketchUp/SketchUp 2017/SketchUp/Gems64
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "install" => "--no-document --env-shebang --platform ruby -- --use-system-libraries"
     - "update" => "--no-document --env-shebang --platform ruby -- --use-system-libraries"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Program Files\SketchUp_23_1\SketchUp 2017\Tools\RubyStdLib\platform_specific
     - C:\Program Files\SketchUp\SketchUp 2017\
     - C:\Windows\system32
     - C:\Windows
     - C:\Windows\System32\Wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0\
     - C:\ruby25_64\bin
     - C:\Program Files\Git\cmd
     - E:\msys64
     - C:\Program Files (x86)\GNU\GnuPG\pub
     - C:\Program Files\Microsoft SQL Server\130\Tools\Binn\
     - C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common
     - C:\Program Files (x86)\Microsoft VS Code\bin
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
This potentially sounds like an issue with your ruby installation, as I think default gems are supposed to be in the default dir...

**Comment by MSP-Greg** [comment]
@segiddins 

I don't believe so.  Too many terms.

1.  `gem list` has always worked for me in all the builds I've done.

2. In this embedded app, gems install, several commands that I've tested appear to work, etc.  Note that, at present, this embedded use of Ruby does not have a ruby.exe file.

3. I'm testing on Windows, and trying to get some info re the embedded layout on OSX.

4. Default gems - currently, the code for these is included in the ruby repo, and they are installed exactly like other std-lib items, except additionally, they have a gempec file in `specifications/default`.

5. Bundled gems - their code is not included in the ruby repo, and they are installed (by the ruby build code) like any other gem.  Their gemspec file is in `specifications`.

6. In this embedded application, the app is installed in a  protected directory, and all gem files are moved to a user folder where the user has full rights.  This is folder listed as `INSTALLATION DIRECTORY` in `gem environment`.  This folder is also where the only `specifications` folder exists.

Hence, I think I've got the method as it should be, as it only switches if
```ruby
File.join(Gem.default_dir, "specifications", "default")
```
does not exist.  That existence test could probably be for
```ruby
File.join(Gem.default_dir, "specifications")
```

This is obviously an edge case, but I think it can be handled properly.

**Comment by indirect** [comment]
Am I understanding correctly that you have written a wrapper for Ruby's build system that moves default gems from their location in Gem.default_dir, relocating them to Gem.dir? Default gems are deliberately not editable or uninstallable by the user of a ruby installation, so that situation seems unlikely to be supported by ruby core to me.

**Comment by MSP-Greg** [comment]
@indirect I'm sorry, no, that is not what I was implying, as I said

> they are installed exactly like other std-lib items,

I have verified that the OSX application has the same basic folder layout, so the patch I listed will also fix the issue on OSX.

Again, my issue is with one thing - `gem list` and the fact that default gems are not listed.  It requires that the code have the correct path to where the default gems' respective gemspec files are. 

As per the original method shown, it uses [Gem.default_dir](https://github.com/rubygems/rubygems/blob/60006a8e46dbc307abf3ad02c6c4d8e8b85ceaee//lib/rubygems/defaults.rb#L30-L53), which if you inspect it, assumes a standard, stand-alone ruby installation.

The code I listed still works with a standard installation, but also allows one embedded ruby application to function properly.  It may do the same for others.

**Comment by MSP-Greg** [comment]
@indirect @segiddins 

This might clarify things.  Settings from one of my stand-alone installs:
```
Gem.default_dir
   C:/ruby25_64/lib/ruby/gems/2.5.0
Gem.dir
   C:/ruby25_64/lib/ruby/gems/2.5.0
ENV['GEM_PATH']

ENV['GEM_HOME']

```

Same settings from embedded ruby:
```
Gem.default_dir
   C:/Program Files/SketchUp_23_1/SketchUp 2017/Tools/lib/ruby/gems/2.3.0
Gem.dir
   C:/Users/Greg/AppData/Roaming/SketchUp/SketchUp 2017/SketchUp/Gems64
ENV['GEM_PATH']
   C:/Users/Greg/AppData/Roaming/SketchUp/SketchUp 2017/SketchUp/Gems64
ENV['GEM_HOME']
   C:/Users/Greg/AppData/Roaming/SketchUp/SketchUp 2017/SketchUp/Gems64
```

For stand-alone ruby, `Gem.default_dir == Gem.dir`.  For embedded, `Gem.default_dir` doesn't even exist, since it's assembled based on assumptions of a stand-alone install and RbConfig.

In embedded, all three `Gem.dir`, `ENV['GEM_PATH']`, and `ENV['GEM_HOME']` all point to the correct folder, which is also the folder which contain a sub-folder `specifications`, and `specifications/default`.

Does this clear things up?

If anything, this seems to make clear that what should be really done is a check whether a `specifications` folder exists in `ENV['GEM_PATH']`, `ENV['GEM_HOME']`, and `Gem.default_dir`, and the first which exists should be used.

Given how many packaging systems exist, and the occasional issues with RbConfig...

**Comment by indirect** [comment]
Thanks for that information, that's helpful. I think this shows that we need to change `default_dir` rather than changing `default_specification_dir`.

**Comment by MSP-Greg** [comment]
@indirect Thanks.

As to what changes, I'll leave that up to you and the RubyGems team.  I have no idea what various packaging systems do to `ENV['GEM_PATH']` or `ENV['GEM_HOME']`, or where they're used in code...

**Comment by MSP-Greg** [comment]
@indirect 

> Thanks for that information, that's helpful. I think this shows that we need to change default_dir rather than changing default_specification_dir.

On a mission to close my (old) issues.  Any recollections on this one?  I could push a 2.3.5 build I've got into the 'embedded' app, but I haven't had time, and it is an issue that they could address with their build.

Hence, I'm okay to close...

**Comment by segiddins** [comment]
This seemed like a legit bug, it just hasn’t gotten patched yet

**Comment by MSP-Greg** [comment]
In that case, let me see if I can get `gem env` from the same app under OSX (@thomthom ?).  Maybe he can check `gem list` also.

Some of the none standard folder layout is due to the fact that anything under `Program Files` in Windows is 'admin/UAC' protected, while `Users` is not.  Thanks.  Obviously, I'll leave open.

**Comment by segiddins** [comment]
My guess is the proper fix might be to just concatenate the results from those two default directories and say both are default specs?

**Comment by MSP-Greg** [comment]
It's been a while since we discussed, and I haven't used the app much since then.

> concatenate the results from those two default directories and say both are default specs?

I assume that means that `self.default_specifications_dir` can be more of a path rather than a single folder, and, you'd know the answer to that better than I.

Let's see if Thomas replies, as I'm not familiar with OSX...

**Comment by thomthom** [comment]
> In that case, let me see if I can get `gem env` from the same app under OSX (@thomthom ?). Maybe he can check `gem list` also.
What are the Ruby equivalent commands I need to run to obtain that output?

**Comment by MSP-Greg** [comment]
@thomthom 

Apologies, when I pinged you, I hadn't read the whole thread again and seen that it wasn't apparent.

Main thing is the settings for:
```
Gem.default_dir
Gem.dir
ENV['GEM_PATH']
ENV['GEM_HOME']
```

Also whether what's listed as `Gem.default_dir` exists, and if so, what it contains.

The rb file I used that started this is [gem_env_list.rb.txt](https://github.com/rubygems/rubygems/files/1368566/gem_env_list.rb.txt)

Note - I've got three SU installs (the app with embedded ruby), but I've 'enhanced' all of them.  Hence, I don't currently have a base install I can check...

**Comment by thomthom** [comment]
Output of `gem_env_list.rb`:

```
-------------------------------------------------- Gem Environment
RubyGems Environment:
  - RUBYGEMS VERSION: 2.4.5.1
  - RUBY VERSION: 2.2.4 (2015-12-16 patchlevel 230) [x86_64-darwin14]
  - INSTALLATION DIRECTORY: /Users/tthomas2/Library/Application Support/SketchUp 2018/SketchUp/Gems
  - RUBY EXECUTABLE: "/Applications/SketchUp 2018/SketchUp.app/Contents/Frameworks/Ruby.framework/Versions/2.2/bin/ruby"
  - EXECUTABLE DIRECTORY: /Users/tthomas2/Library/Application Support/SketchUp 2018/SketchUp/Gems/bin
  - SPEC CACHE DIRECTORY: /Users/tthomas2/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/obirsoy/Downloads/ruby/ruby-install2/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-14
  - GEM PATHS:
     - /Users/tthomas2/Library/Application Support/SketchUp 2018/SketchUp/Gems
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin

-------------------------------------------------- Installed Gems

------------------------------------------------------------------
[nil, nil, nil]
```

**Comment by thomthom** [comment]
```
Gem.default_dir  missing  /Applications/SketchUp 2018/SketchUp.app/Contents/Frameworks/Ruby.framework/Versions/2.2/lib/ruby/gems/2.2.0
Gem.dir          missing  /Users/tthomas2/Library/Application Support/SketchUp 2018/SketchUp/Gems
ENV['GEM_PATH']  missing  /Users/tthomas2/Library/Application Support/SketchUp 2018/SketchUp/Gems
ENV['GEM_HOME']  missing  /Users/tthomas2/Library/Application Support/SketchUp 2018/SketchUp/Gems
```

**Comment by MSP-Greg** [comment]
@thomthom 

That's discouraging.  Maybe continue this in the SketchUp forum to see what you and others have done re gem resolution, etc on OSX?

**Comment by thomthom** [comment]
I'm able to install gems on both platforms out of the box (except Windows when extensions needs building).

**Comment by bronzdoc** [comment]
@MSP-Greg can this be closed?

**Comment by MSP-Greg** [comment]
Yes.  Thanks.
