### ISSUE TITLE
cannot load such file — mysql2/2.4/mysql2 (LoadError) - windows

### ISSUE THREAD

**Issue by araufit** [rubygems/rubygems#1961]
am new on Ruby on Rails. My Ruby version is ruby` 2.4.1p111 (2017-03-22 revision 58053) [x64-mingw32]`.

I have created a new project using `rails new sample_cms -d mysq`l command.

The command rails server is throwing following error.

`C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mysql2-0.4.6-x64-mingw32/lib/mysql2/mysql2.rb:2:in `require': cannot load such file -- mysql2/2.4/mysql2 (LoadError)`
I have installed mysql and mysql Connector C. I have installed the mysql2 gem like that.

`gem install mysql2 —platform=ruby — ‘—with-mysql-dir="C:\Program Files\MySQL\MySQL Connector C 6.1"’`
I have uninstall and install the mysql2 gem but still facing the issue. Here is the directory which may have issue.

![screenshot_1](https://user-images.githubusercontent.com/29669465/27505154-7b8f3f4e-58b2-11e7-8c8a-66980553443c.png)

Here is the gem file entry for mysql2

```
# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.1.1'
# Use mysql as the database for Active Record
gem 'mysql2', '>= 0.3.18', '< 0.5'
# Use Puma as the app server
gem 'puma', '~> 3.7'
```
Any Help?

**Comment by hsbt** [comment]
It seems mysql2 issue about missing binary for mingw platform with Ruby 2.4. 

Please report upstream repo: https://github.com/brianmario/mysql2

**Comment by araufit** [comment]
@hsbt ... yes, mysql2 is missing. Can i downgrade the Ruby to 2.3?

**Comment by hsbt** [comment]
You can install ruby 2.3 via https://rubyinstaller.org/downloads/

It's out of scope RubyGems. I will close this. If you found a problem of RubyGems about this issue, Please reopen this.
