### ISSUE TITLE
gem uninstall never reports errors even if it failed to remove executables

### ISSUE THREAD

**Issue by unak** [rubygems/rubygems#1967]
See https://github.com/rubygems/rubygems/blob/master/lib/rubygems/uninstaller.rb#L216-L217
As you know `FileUtils.rm_f` never raises any exception if it fails to remove the specified files.
Then users cannot know the files are really removed or not, and also cannot know why the removal was failed.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.12
```
(bundled version of MRI trunk)

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
Can you please provide an example of what error message you were expecting but did not receive?

**Comment by unak** [comment]
@segiddins I don't know.  I want to know it, really :-)
Rubygems reported nothing, so I could not know what was happened.

**Comment by segiddins** [comment]
But what failed?

**Comment by unak** [comment]
I don't know.  The executables were not removed.

**Comment by shevegen** [comment]
I did not write the rubygems code but if I were to change it, I would probably add a standalone method "def rm_rf()" which will handle all FileUtils.rm_rf calls.

Inside that method you could also more readily fine-tune what to do; such as in the example that unak said, to also provide error-reporting to the user. At the least from the code side but people are different and nobody has to agree with me - I just feel that methods are cleaner in general than direct calls to tools whose functionality may not always be what a user wants to see. :-)

On the topic itself, I do not know rubygems internal policy but from my memory of working with rubygems, rubygems in general tends to give very little output, which is probably deliberate. My scripts output a LOT, which is often spamming stuff down, for example - not good either. But I like to see rather more than less notification, personally.

Anyway, I feel that this could quite easily be handled. If the ruby gem team decides that no change is warranted, then an ENV variable could be used. Some verbosity level such as RUBY_GEM_VERBOSE or something like that. If this is then set, then code like the above, passed through a method, could check for that variable, and if it was set, to also provide information that unak wanted to have here (e. g. his use case that was documented in the first post).

Anyway that is just one suggestion - it'll all depends on the behaviour, so perhaps the oldschool gurus like drbrain etc... can say something about the gem-policy about removing files/directories and either failing, and/or not finding such files.

**Comment by colby-swandale** [comment]
This has been fixed in #2154
