### ISSUE TITLE
not working with beef pls help

### ISSUE THREAD

**Issue by LvDubz** [rubygems/rubygems#1973]
I'm having a problem or would like to suggest a feature.

My current problem is gems don't have the correct requirements

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [* ] The command line `gem`
  - [* ] Other

Here are my current environment details:

```
$ gem env version
/usr/lib/ruby/2.3.0/psych.rb:474:in `initialize': No such file or directory @ rb_sysopen - /usr/lib/ruby/data/geoip/country_code.yml (Errno::ENOENT)
	from /usr/lib/ruby/2.3.0/psych.rb:474:in `open'
	from /usr/lib/ruby/2.3.0/psych.rb:474:in `load_file'
	from /usr/lib/ruby/vendor_ruby/geoip.rb:68:in `<class:GeoIP>'
	from /usr/lib/ruby/vendor_ruby/geoip.rb:58:in `<top (required)>'
	from /root/beef/core/loader.rb:21:in `require'
	from /root/beef/core/loader.rb:21:in `<top (required)>'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from ./beef:25:in `<main>'
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by simi** [comment]
Looks more like beef problem. Maybe try to open issue there (https://github.com/beefproject/beef/issues).

**Comment by hsbt** [comment]
or geoip ( https://github.com/cjheath/geoip ) issue.
