### ISSUE TITLE
Provide special-cased `bundle` command that executes the correct version of Bundler

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems#1974]
With Bundler 2 coming, the smoothest possible transition path is to provide a `bundle` command that checks the Gemfile.lock and loads the correct version of Bundler (1.x or 2.0) depending on the version of Bundler listed in the lock file.

Over in Bundler, we spent a lot of effort trying to see if we could do this inside Bundler itself, and it turns out to be extremely problematic to remove an already-loaded library and load a different version of that library instead, from inside that library.

Instead, I'd like to propose that we ship a `bundle` command with RubyGems with the following behavior:

- if BUNDLE_GEMFILE is set, checks the lock for that file to find the bundler version
- if the current directory or parents of the current directory have a gemfile, use the lock to find the bundler version
- if no lock is found, default to the newest version of Bundler currently installed
- load the selected Bundler version and then hand off execution to the Bundler gem itself

**Comment by segiddins** [comment]
Should the same happen when `Kernel.gem "bundler"` is called?

**Comment by indirect** [comment]
I think it's an implementation detail and I don't care either way? Could make it easier for other binstubs that want to load the Bundle before running another gem's command, though.
