### ISSUE TITLE
Add a command to show gem's description before choose to install it

### ISSUE THREAD

**Issue by domcorvasce** [rubygems/rubygems#1975]
Basically I'd like to be able to see a description for a certain gem before I choose to install it or not.

Something like:

```shell
$ gem whatis dry-struct
```

```shell
dry-struct | 0.3.1
Typed structs and value objects.

Install it [Yn]
```

And, doing so, a developer can avoids to install the wrong gem (or get an error) due to a misspelling.

**PS: I know you're working hard on much important features so please don't be mad at me for this silly idea 😄**

**Comment by segiddins** [comment]
`gem search -rde` should do exactly what you're looking for 🚀

**Comment by domcorvasce** [comment]
Oh yeah, it works!
Thanks a lot ⚡️
