### ISSUE TITLE
A test fails when the sort order is unstable.

### ISSUE THREAD

**Issue by ko1** [rubygems/rubygems#1980]
I found test failure (a test included by ruby-trunk) on mswin64 (VS2017, Windows 10) environment.
and I found that if `Gem::Resolver#sort_dependencies()` returns stable result, no problem.

I fixed rubygems on ruby-trunk but I'm not sure it is common case or not. Please check by experts.

See https://svn.ruby-lang.org/cgi-bin/viewvc.cgi?view=revision&revision=59502 for details of my fix.

**Comment by segiddins** [comment]
Is `Enumerable#sort_by` not stable? Adding in the extra element to the sort is probably an unnecessary performance hit

**Comment by MSP-Greg** [comment]
@ko1,

The fix to rubygems on ruby-trunk fixes the issue for MinGW builds also.  This is one of a handful of failures left to be fixed.

See Test Failure - TestGemRequestSetLockfile#test_to_s_gem_dependency_non_default #1948 

Thanks ko1...

@segiddins 

> Adding in the extra element to the sort is probably an unnecessary performance hit

Like a blink of an eye vs reading your sentence...

**Comment by hsbt** [comment]
I already merged @ko1 's patch in RG 2.7.
