### ISSUE TITLE
gem installation in local mode is not finding prerelease dependencies 

### ISSUE THREAD

**Issue by rameshjanjyam** [rubygems/rubygems#1988]
I'm having a problem or would like to suggest a feature.

My current problem is `gem install --local` not finding prerelease gem dependencies. I am very new to ruby and came to know that we can download the .gem and all it dependent .gem s to local and can install it by using  `gem install --local required_gem.gem`

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.12
```

as per the accepted answer [here](https://stackoverflow.com/questions/4402819/download-all-gems-dependencies)  I have created a `Gemfile` and then `bundle package` to get all gems downloaded to `vendor\cache` folder. 

my `Gemfile`

```
# frozen_string_literal: true
source "https://rubygems.org"
 gem "fog-azure-rm", "0.2.7"
```

and then I took this `vendor\cache` to a machine without internet and ran 
`gem install --local --no-rdoc --no-ri fog-azure-rm-0.2.7.gem` this resulted in the error 

```
ERROR:  Could not find a valid gem 'azure-storage' (~> 0.11.5.preview) in any repository
```
is it because that this is a preview (prerelease) gem? please help

**Comment by segiddins** [comment]
Since you're using local, have you already installed that gem locally?

**Comment by rameshjanjyam** [comment]
no @segiddins. in `--local` mode, I was expecting `gem` to look for dependent gems in the same folder and install them when it finds the dependency

based on your answer I am now trying to install the `azure-storage` first and see whether fog-azure-rm works. I have now installed `azure-storage` gem using `gem --local`

```
gem install --local --no-ri --no-rdoc azure-storage-0.11.5.preview.gem 

Successfully installed pkg-config-1.1.9
Successfully installed mini_portile2-2.1.0
Building native extensions.  This could take a while...
Successfully installed nokogiri-1.6.8
Successfully installed multipart-post-2.0.0
Successfully installed faraday-0.13.0
Successfully installed faraday_middleware-0.12.2
Building native extensions.  This could take a while...
Successfully installed azure-core-0.1.10
Successfully installed azure-storage-0.11.5.preview
8 gems installed
```

and now trying `gem install --local --no-ri --no-rdoc fog-azure-rm-0.2.7.gem` Its been more than 10 minutes but it seems to be still running. 

couple of questions from this result
- does the dependency gem should be first installed before installing the required gem in --local mode?
- any reason why it is taking very long time even in --local mode? does it still try to go out to internet

**Comment by rameshjanjyam** [comment]
the fog-azure-rm `gem install --local --no-ri --no-rdoc fog-azure-rm-0.2.7.gem`

```
gem install --local --no-ri --no-rdoc fog-azure-rm-0.2.7.gem 
Successfully installed bit-struct-0.16
Successfully installed vhd-0.0.4
Successfully installed concurrent-ruby-1.0.5
Successfully installed timeliness-0.3.8
Successfully installed ms_rest-0.6.4
Building native extensions.  This could take a while...
Successfully installed unf_ext-0.0.7.4
Successfully installed unf-0.1.4
Successfully installed domain_name-0.5.20170404
Successfully installed http-cookie-1.0.3
Successfully installed faraday-cookie_jar-0.0.6
Successfully installed ms_rest_azure-0.6.2
Successfully installed azure_mgmt_key_vault-0.8.0
Successfully installed azure_mgmt_sql-0.8.0
Successfully installed azure_mgmt_traffic_manager-0.8.0
Successfully installed azure_mgmt_dns-0.8.0
Successfully installed azure_mgmt_network-0.8.0
Successfully installed azure_mgmt_storage-0.8.0
Successfully installed azure_mgmt_resources-0.8.0
Successfully installed azure_mgmt_compute-0.8.0
Successfully installed netrc-0.11.0
Successfully installed mime-types-1.25.1
Successfully installed rest-client-2.0.2
Successfully installed multi_json-1.12.1
Successfully installed formatador-0.2.5
Successfully installed excon-0.58.0
Successfully installed builder-3.2.3
Successfully installed fog-core-1.43.0
Successfully installed fog-json-1.0.2
Thanks for installing!
Successfully installed fog-azure-rm-0.2.7
29 gems installed
```

it is able to pick its other dependencies, as you can see in the above output, `fog-core-1.43.0`, `fog-json-1.0.2`, e.t.c. any reason why it is not able to find `azure-storage-0.11.5.preview.gem` with out `azure-storage-0.11.5.preview.gem` being installed first?

if `azure-storage-0.11.5.preview.gem` is not first installed then this is the error I see 

```
gem install --local --no-ri --no-rdoc ./fog-azure-rm-0.2.7.gem 
ERROR:  Could not find a valid gem 'azure-storage' (~> 0.11.5.preview) in any repository
```

**Comment by segiddins** [comment]
Gotcha, thanks for the extra context! This seems at a glance to be a bug to me.

**Comment by segiddins** [comment]
I tried to write a failing test for this but failed, in the meantime I would recommend installing using `bundle install` with that cache for now

**Comment by segiddins** [comment]
https://github.com/rubygems/rubygems/pull/1990 should fix this!

**Comment by rameshjanjyam** [comment]
Thank you @segiddins
