### ISSUE TITLE
add support for installing via git repo. 

### ISSUE THREAD

**Issue by r-obert** [rubygems/rubygems#1989]
I would like to request that the 'gem install' command be extended to support installing gems from remote Git repositories, eg: `gem install https://github.com/user/project.git`.

The main advantages I can think of are:

* It would provide a decentralised method for gem distribution, that sidesteps rubygems.org.
* Super convient.

Any plans to add this feature? If there's not, I will probably give it a shot myself in a plugin.
Cheers.

**Comment by segiddins** [comment]
I don't think we have any plans for such a major feature

**Comment by segiddins** [comment]
As far as a plugin, I think a specific-install one already exists

**Comment by r-obert** [comment]
Thanks! 
Do you happen to know its name, or homepage URL?

**Comment by bronzdoc** [comment]
Hey @r-obert 
I think this is the plugin you are looking for https://github.com/rdp/specific_install :)

**Comment by r-obert** [comment]
Thanks, made my day!
