### ISSUE TITLE
Symlink executables don't properly install

### ISSUE THREAD

**Issue by segiddins** [rubygems/rubygems#1996]
This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

**Comment by segiddins** [comment]
@krausefx any interest in fixing this?

**Comment by KrauseFx** [comment]
Is that something fastlane is causing problems with? What's the best way to reproduce the problem?

**Comment by segiddins** [comment]
`gem pristine fastlane --only-executables`

**Comment by segiddins** [comment]
(But I think I have a fix for it anyways)

**Comment by deivid-rodriguez** [comment]
I believe this was fixed by https://github.com/rubygems/rubygems/pull/2836, so I'm tentatively closing it.
