### ISSUE TITLE
gem install rhc  Error

### ISSUE THREAD

**Issue by marrygardensinfo** [rubygems/rubygems#2003]
C:\Users\Dharmendra>gem install rhc
ERROR:  Could not find a valid gem 'rhc' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect retur
ned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed (
https://rubygems.org/latest_specs.4.8.gz)

**Comment by colby-swandale** [comment]
Hi, it seems you're installation of RubyGems is unable to establish a secure connection to RubyGems.org. I recommend going through [RubyGems' SSL guide](http://guides.rubygems.org/ssl-certificate-update/) which will help provide some information to help solve your problem.

**Comment by colby-swandale** [comment]
ping @marrygardensinfo

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
