### ISSUE TITLE
mkfifo compile native extension fails on ruby 2.4.1p111

### ISSUE THREAD

**Issue by benny59** [rubygems/rubygems#2004]
I'm having a problem or would like to suggest a feature.

My current problem is 
error compiling extensions on win7 AND win10. Compilation successfully on Mint 18.2 
I am writing a crossplatform application and I am stalled
Thanks for any help

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mkfifo-0.1.1/ext
C:/Ruby24-x64/bin/ruby.exe -r ./siteconf20170904-4548-1851673.rb extconf.rb
creating Makefile

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mkfifo-0.1.1/ext
make "DESTDIR=" clean

current directory: C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/mkfifo-0.1.1/ext
make "DESTDIR="
generating mkfifo-x64-mingw32.def
compiling mkfifo.c
mkfifo.c: In function 'rb_cFile_mkfifo':
**mkfifo.c:30:9: warning: implicit declaration of function 'mkfifo'; did you mean 'mktime'? [-Wimplicit-function-declaration]**
     if (mkfifo(RSTRING_PTR(name), S_IRUSR | S_IWUSR | S_IRGRP | S_IWGRP) < 0) {
         ^~~~~~
         mktime
linking shared-object mkfifo.so
**mkfifo.o:mkfifo.c:(.text+0x85): undefined reference to `mkfifo'**
collect2.exe: error: ld returned 1 exit status
make: *** [Makefile:259: mkfifo.so] Error 1

make failed, exit code 2

This issue is related to:

  - [ ] Network problems
  - [x ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.11
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by colby-swandale** [comment]
HI, this seems like an issue with the `mkfifo` gem itself and not rubygems, I suggest you raise an issue there instead.

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.
