### ISSUE TITLE
Make full_gem_path always return the realpath to make symlinks and require_relative not double-require

### ISSUE THREAD

**Issue by grosser** [rubygems/rubygems#2005]
A symlinked GEM_HOME and require_relative will result in double require errors.

Noticed the [issue originally](https://github.com/bundler/bundler/issues/5953) when working with a symlinked bundler path `vendor/bundle`, but ideally the fix would live in rubygems to make it work consistently. 

Reproduce:
 - use symlinked GEM_HOME
 - require a file
 - require_relative the same file

Result: file is loaded twice

Expected: file is loaded once

/cc @colby-swandale @segiddins

**Comment by colby-swandale** [comment]
I'm not sure if this is a RubyGems issue, instead of trying to load a gem, i've replicated the issue by using a ruby file.

```
› cat test.rb
$LOAD_PATH.unshift File.expand_path('..', __FILE__)

require 'vendor/bundle/test'
require_relative './real-bundle/test.rb'

› ls -la vendor/bundle
lrwxr-xr-x  1 c  staff  14 23 Feb 16:07 vendor/bundle@ -> ../real-bundle

› ls  -la real-bundle
total 8
drwxr-xr-x   3 c  staff   96 23 Feb 16:15 ./
drwxr-xr-x  11 c  staff  352 23 Feb 16:18 ../
-rw-r--r--   1 c  staff   20 23 Feb 16:12 test.rb

› cat real-bundle/test.rb
puts "Hello World!"
```

```
› ruby test.rb
Hello World!
Hello World!
```

**Comment by hsbt** [comment]
I'm not sure it's spec of `require` or not and rubygems or ruby core.

@grosser Can you reproduce it without rubygems used by `--disabled-gems`?

**Comment by bronzdoc** [comment]
ping @grosser

**Comment by grosser** [comment]
Maybe just close this ... we are about to stop using this workflow anyway and fixing it would require some overhead that every other user would have to pay just to fix this edge-case ...
