### ISSUE TITLE
SSL issue with httparty

### ISSUE THREAD

**Issue by bvabhishek2510** [rubygems/rubygems#2008]
When i am trying to connect to an endpoint from rails console using httparty, I am getting the following error:
**SSL established
Conn close because of connect error SSL_connect returned=1 errno=0 state=SSLv3 read server certificate B: certificate verify failed**

I have found a solution, bypassing the ssl verification by adding **verify => false** to the httparty call. But, this is not the correct way form security point of view. 

Here are my current environment details:
env: dev
ruby gems latest version.

**Comment by segiddins** [comment]
This sounds like an issue with the `httparty` gem, rather than RubyGems itself.
