### ISSUE TITLE
invalid Homepage link for sup gem

### ISSUE THREAD

**Issue by RichMorin** [rubygems/rubygems#2014]
I'm having a problem or would like to suggest a feature.

My current problem is an invalid Homepage link for the sup gem

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x ] Other

Here are my current environment details:

NA

The Homepage link for the sup gem (https://rubygems.org/gems/sup) points to a site that sells shoes.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by colby-swandale** [comment]
This is not an issue with RubyGems, I suggest you raise an issue with the gem authors [on Github](https://github.com/sup-heliotrope/sup) asking to update the homepage URL.
