### ISSUE TITLE
gem install is very slow on Ubuntu 16.04

### ISSUE THREAD

**Issue by nicwortel** [rubygems/rubygems#2017]
I'm experiencing an issue on Ubuntu 16.04 where `gem install` takes a very long time. Ruby Gems seems to get stuck on resolving a DNS entry for `_rubygems._tcp.api.rubygems.org`.

```
$ ruby -v
ruby 2.3.1p112 (2016-04-26) [x86_64-linux-gnu]
$ gem -v
2.5.1
```

See this output of the CLI command `time gem install --verbose --debug mailcatcher`:

```
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `LoadError' at /usr/lib/ruby/2.3.0/resolv.rb:171 - LoadError
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=mailcatcher
200 OK
Exception `Resolv::ResolvTimeout' at /usr/lib/ruby/2.3.0/resolv.rb:694 - Resolv::ResolvTimeout
Exception `Resolv::ResolvTimeout' at /usr/lib/ruby/2.3.0/resolv.rb:694 - Resolv::ResolvTimeout
Exception `Resolv::ResolvTimeout' at /usr/lib/ruby/2.3.0/resolv.rb:694 - Resolv::ResolvTimeout
Exception `Resolv::ResolvTimeout' at /usr/lib/ruby/2.3.0/resolv.rb:694 - Resolv::ResolvTimeout
Exception `Resolv::ResolvError' at /usr/lib/ruby/2.3.0/resolv.rb:1108 - DNS resolv timeout: _rubygems._tcp.api.rubygems.org
Exception `Resolv::ResolvError' at /usr/lib/ruby/2.3.0/resolv.rb:494 - DNS result has no information for _rubygems._tcp.api.rubygems.org
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
(...)

real	1m16.112s
user	0m0.388s
sys	0m0.016s
```

When I try to resolve this host (`_rubygems._tcp.api.rubygems.org`) directly, I'm getting a timeout as well: 

```
$ time host _rubygems._tcp.api.rubygems.org
;; connection timed out; no servers could be reached

real	0m10.032s
user	0m0.016s
sys	0m0.016s
```

Which leads me to believe that Ruby Gems might be trying to resolve the wrong hostname?

I found a similar issue #1017 that talks about a different hostname: `_rubygems._tcp.rubygems.org` (without `api` in it), which is resolved (`time host _rubygems._tcp.rubygems.org`) in 0.052 seconds.

This is occurring inside a Vagrant box as well as on my host machine (both are running Ubuntu 16.04 and the default Ruby and Ruby Gems versions from the Ubuntu repositories).

This issue is related to:

  - Network problems
  - Installing a library

**Comment by bagmangood** [comment]
Just started experiencing this in some CentOS containers, the failures happen quickly in OS X but quite slow in CentOS

**Comment by colby-swandale** [comment]
Is this still an issue? I've tested `time host _rubygems._tcp.api.rubygems.org` several times and received the expected response.

**Comment by nicwortel** [comment]
Yes, this is still an issue.

What if you build the following Docker container, and run the command inside that container?

```
FROM ubuntu:16.04

RUN apt-get update && apt-get install -y dnsutils build-essential libsqlite3-dev ruby-dev
```

**Comment by nicwortel** [comment]
Maybe this helps. I changed my DNS to 8.8.8.8 (by editing `/etc/resolv.conf`) and now the DNS lookup still fails, but it fails a lot faster.

resolv.conf:
```
# Dynamic resolv.conf(5) file for glibc resolver(3) generated by resolvconf(8)
#     DO NOT EDIT THIS FILE BY HAND -- YOUR CHANGES WILL BE OVERWRITTEN
nameserver 8.8.8.8
```

```
time ruby -rresolv -e "Resolv::DNS.new.getresource '_rubygems._tcp.api.rubygems.org', Resolv::DNS::Resource::IN::SRV"
/usr/lib/ruby/2.3.0/resolv.rb:494:in `getresource': DNS result has no information for _rubygems._tcp.api.rubygems.org (Resolv::ResolvError)
	from -e:1:in `<main>'

real	0m0.110s
user	0m0.076s
sys	0m0.004s
```

This leads me to believe that there is an error with the DNS entry for `_rubygems._tcp.api.rubygems.org`, but some DNS's fail instantly while others keep retrying until you get a timeout.

**Comment by homm** [comment]
MY resolver fails instantly, while I still getting Resolv::ResolvTimeout very very long.

```
$ sudo gem install coveralls-lcov --verbose --debug mailcatcher
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `LoadError' at /usr/lib/ruby/2.3.0/resolv.rb:171 - LoadError
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=coveralls-lcov
200 OK
Exception `Resolv::DNS::Config::NXDomain' at /usr/lib/ruby/2.3.0/resolv.rb:549 - _rubygems._tcp.api.rubygems.org
Exception `Resolv::ResolvTimeout' at /usr/lib/ruby/2.3.0/resolv.rb:694 - Resolv::ResolvTimeout
Exception `Resolv::ResolvTimeout' at /usr/lib/ruby/2.3.0/resolv.rb:694 - Resolv::ResolvTimeout
Exception `Resolv::ResolvTimeout' at /usr/lib/ruby/2.3.0/resolv.rb:694 - Resolv::ResolvTimeout
Exception `Resolv::ResolvTimeout' at /usr/lib/ruby/2.3.0/resolv.rb:694 - Resolv::ResolvTimeout
Exception `Resolv::ResolvError' at /usr/lib/ruby/2.3.0/resolv.rb:1108 - DNS resolv timeout: _rubygems._tcp.api.rubygems.org
Exception `Resolv::ResolvError' at /usr/lib/ruby/2.3.0/resolv.rb:494 - DNS result has no information for _rubygems._tcp.api.rubygems.org
```

**Comment by bronzdoc** [comment]
@nicwortel is this still an issue for you?

**Comment by nicwortel** [comment]
@bronzdoc yes, unfortunately it is. I haven't run into it lately because we switched to a Docker image of the package, but running the same commands on my current system (I have upgraded to Ubuntu 18.04 since I reported this issue) still gives similar results:

```
$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]
$ gem -v
2.7.6
```
```
$ time gem install --verbose --debug mailcatcher
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `LoadError' at /usr/lib/ruby/2.5.0/resolv.rb:170 - LoadError
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=mailcatcher
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=eventmachine,mail,rack,sinatra,skinny,sqlite3,thin
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=daemons
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=mini_mime
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=rack-protection,tilt
200 OK
Exception `Resolv::ResolvTimeout' at /usr/lib/ruby/2.5.0/resolv.rb:691 - Resolv::ResolvTimeout
Exception `Resolv::ResolvTimeout' at /usr/lib/ruby/2.5.0/resolv.rb:691 - Resolv::ResolvTimeout
Exception `Resolv::ResolvTimeout' at /usr/lib/ruby/2.5.0/resolv.rb:691 - Resolv::ResolvTimeout
Exception `Resolv::ResolvTimeout' at /usr/lib/ruby/2.5.0/resolv.rb:691 - Resolv::ResolvTimeout
Exception `Resolv::ResolvError' at /usr/lib/ruby/2.5.0/resolv.rb:1101 - DNS resolv timeout: _rubygems._tcp.api.rubygems.org
Exception `Resolv::ResolvError' at /usr/lib/ruby/2.5.0/resolv.rb:491 - DNS result has no information for _rubygems._tcp.api.rubygems.org
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
Downloading gem mailcatcher-0.6.5.gem
Exception `Errno::ENOENT' at /usr/lib/ruby/2.5.0/rubygems/remote_fetcher.rb:325 - No such file or directory @ rb_file_s_stat - /home/nic/.gem/ruby/2.5.0/cache/mailcatcher-0.6.5.gem
GET https://api.rubygems.org/gems/mailcatcher-0.6.5.gem
Fetching: mailcatcher-0.6.5.gem (100%)
200 OK
Exception `Errno::EEXIST' at /usr/lib/ruby/2.5.0/fileutils.rb:232 - File exists @ dir_s_mkdir - /var/lib/gems/2.5.0
[removed irrelevant output]

real	1m15,693s
user	0m0,400s
sys	0m0,024s
```

Again, `gem` hangs for a long time while the `Exception `Resolv::ResolvTimeout' at /usr/lib/ruby/2.5.0/resolv.rb:691 - Resolv::ResolvTimeout` lines are printed. And again, when I try to resolve `_rubygems._tcp.api.rubygems.org` manually using `host _rubygems._tcp.api.rubygems.org`, it fails after a timeout:

```
$ time host _rubygems._tcp.api.rubygems.org
;; connection timed out; no servers could be reached

real	0m10,026s
user	0m0,005s
sys	0m0,021s
```

**Comment by nicwortel** [comment]
It seems that pull request #2433 has removed the dynamic lookup of the API host that is causing this issue, so as of version 3 of Ruby Gems this should no longer be an issue.

However, in the meantime, it would be nice if a SRV record similar to the one for `_rubygems._tcp.rubygems.org` could be added to `_rubygems._tcp.api.rubygems.org`.

**Comment by hsbt** [comment]
ref. #2600

**Comment by deivid-rodriguez** [comment]
> It seems that pull request #2433 has removed the dynamic lookup of the API host that is causing this issue, so as of version 3.0.0 of Ruby Gems this should no longer be an issue.

> However, to support older versions of Ruby Gems in the meantime, it would be nice if a SRV record similar to the one for `_rubygems._tcp.rubygems.org` could be added to `_rubygems._tcp.api.rubygems.org`.

I guess this is a separate issue to be raised at https://github.com/rubygems/rubygems.org, but this issue about the `gem` client can be closed?
