### ISSUE TITLE
Internet connection should not be required to install a standalone gem

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems#2019]
When I try to install a `.gem` that is already on my machine, that has no dependencies, RubyGems throws an exception because I have no network connection. This shouldn't happen, and indeed it is possible to force RubyGems to install by passing the `--ignore-dependencies` flag... but the gem I am installing has no runtime dependencies. So that shouldn't be necessary.

This issue is related to:

  - [x] Installing a library

Repro case:

```
$ gem env version
2.6.13

$ cd ~/src/bundler/bundler

$ git co v1.16.0.pre.2
HEAD is now at c1db119a5... Version 1.16.0.pre.2 with changelog

$ rake build
Install the ronn gem to build the help pages
bundler 1.16.0.pre.2 built to pkg/bundler-1.16.0.pre.2.gem.
build ran for   0.000000   0.000000   0.590000 (  0.595070)

$ gem spec pkg/bundler-1.16.0.pre.2.gem | grep type
  type: :development
  type: :development
  type: :development
  type: :development
  type: :development
  type: :development

$ gem install pkg/bundler-1.16.0.pre.2.gem 
ERROR:  While executing gem ... (Errno::EHOSTDOWN)
    Host is down - send(2)

$ gem install --ignore-dependencies pkg/bundler-1.16.0.pre.2.gem
Successfully installed bundler-1.16.0.pre.2
1 gem installed
```

**Comment by drbrain** [comment]
Historically we’ve said “use `-l` to install from local sources only because you may still need to fetch dependencies”

**Comment by colby-swandale** [comment]
@indirect does the response answer your issue? Could this be improved through documentation?

**Comment by colby-swandale** [comment]
ping @indirect
