### ISSUE TITLE
gemspec and `git ls-files`

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2021]
I came across this when I (mistakenly) thought I could remove git from PATH in my trunk build system.

A few gems have `git ls-files` in their gemspec file, and are packaged that way.  This caused the build system to not properly install bundled gems.  Since fixed.

If git is required for installing (some) gems, maybe `where git` could be added to `gem env`?

This issue is related to:

  - [ ] Network problems
  - [X] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

Here are my current environment details:

```
ruby 2.5.0dev (2017-09-26 trunk 60025) [x64-mingw32]
gem 2.6.13
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by colby-swandale** [comment]
This seems reasonable, a PR for this issue would be appreciated 👏

**Comment by lucasprag** [comment]
I could work on this @MSP-Greg @colby-swandale 
I will send a PR as soon as possible

**Comment by tjouan** [comment]
Just my opinion, but I think it would be better to fix the
corresponding gem specifications, I personally made the same "mistake"
in many of my gemspec files and later regretted it.

Or gem authors may keep using a shell command, but warn about the
build dependencies in the gem documentation.

About `gem env` you might have to add hg, svn, find… Also their
versions and which shell is needed, it seems complex, and I think too
late at this point.

An alternative might be a warning when building the gem, but I see
only an ugly way to do this:

    iseq = RubyVM::InstructionSequence.compile code
    if iseq.to_a[-1].flatten.grep(Hash).any? { |e| e[:mid] == :` }
      warn "[#{file}] shell command usage."
    end
(just a quick hack in Gem::Specification.load, but not acceptable IMO)
