### ISSUE TITLE
Issues with installing dm-sqlite-adapter gem on Ruby 2,4 (Windows 10)

### ISSUE THREAD

**Issue by Elbuddy66** [rubygems/rubygems#2030]
I'm having a problem installing dm-sqlite-adapter gem on Ruby 2,4 (Windows 10). 

Here are my current environment details:

```
$ gem env version
2.6.12
```
Error Message below:

C:\Ruby24x64\bin>gem install dm-sqlite-adapter
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions.  This could take a while...
ERROR:  Error installing dm-sqlite-adapter:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby24x64/lib/ruby/gems/2.4.0/gems/do_sqlite3-0.10.17/ext/do_sqlite3
C:/Ruby24x64/bin/ruby.exe -r ./siteconf20171007-3852-ecsuhy.rb extconf.rb
checking for sqlite3.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=C:/Ruby24x64/bin/$(RUBY_BASE_NAME)
        --with-sqlite3-dir
        --without-sqlite3-dir
        --with-sqlite3-include
        --without-sqlite3-include=${sqlite3-dir}/include
        --with-sqlite3-lib
        --without-sqlite3-lib=${sqlite3-dir}/lib

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  C:/Ruby24x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/do_sqlite3-0.10.17/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in C:/Ruby24x64/lib/ruby/gems/2.4.0/gems/do_sqlite3-0.10.17 for inspection.
Results logged to C:/Ruby24x64/lib/ruby/gems/2.4.0/extensions/x64-mingw32/2.4.0/do_sqlite3-0.10.17/gem_make.out

The content of the log file is pasted below:

have_header: checking for sqlite3.h... -------------------- no

"x86_64-w64-mingw32-gcc -o conftest.exe -IC:/Ruby24x64/include/ruby-2.4.0/x64-mingw32 -IC:/Ruby24x64/include/ruby-2.4.0/ruby/backward -IC:/Ruby24x64/include/ruby-2.4.0 -I. -I/usr/local/include -I/opt/local/include -I/usr/include -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64  -march=x86-64 -mtune=generic -O2 -pipe -Wall  -DHAVE_NO_DATETIME_NEWBANG conftest.c  -L. -LC:/Ruby24x64/lib -L/usr/local/lib -L/opt/local/lib -L/usr/lib -L. -pipe     -lx64-msvcrt-ruby240  -lgmp -lshell32 -lws2_32 -liphlpapi -limagehlp -lshlwapi  "
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: int main(int argc, char **argv)
6: {
7:   return 0;
8: }
/* end */

"x86_64-w64-mingw32-gcc -E -IC:/Ruby24x64/include/ruby-2.4.0/x64-mingw32 -IC:/Ruby24x64/include/ruby-2.4.0/ruby/backward -IC:/Ruby24x64/include/ruby-2.4.0 -I. -I/usr/local/include -I/opt/local/include -I/usr/include -D_FORTIFY_SOURCE=2 -D__USE_MINGW_ANSI_STDIO=1 -DFD_SETSIZE=2048 -D_WIN32_WINNT=0x0501 -D__MINGW_USE_VC2005_COMPAT -D_FILE_OFFSET_BITS=64  -march=x86-64 -mtune=generic -O2 -pipe -Wall  -DHAVE_NO_DATETIME_NEWBANG  conftest.c -o conftest.i"
conftest.c:5:10: fatal error: sqlite3.h: No such file or directory
 #include <sqlite3.h>
          ^~~~~~~~~~~
compilation terminated.
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: #include <winsock2.h>
4: #include <windows.h>
5: #include <sqlite3.h>
/* end */

--------------------

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by colby-swandale** [comment]
This is not an issue with RubyGems, you're missing required libraries the gem depends on. See the log:

```
checking for sqlite3.h... no
```
