### ISSUE TITLE
Unable to install bundler

### ISSUE THREAD

**Issue by liaogz82** [rubygems/rubygems#2036]
I'm having a problem.

My current problem is Step 13/18 : RUN bash -l -c 'rbenv global 2.4.2 && gem install bundler'
 ---> Running in fb99b2203d11
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - no such name (https://rubygems.org/specs.4.8.gz)
The command '/bin/sh -c bash -l -c 'rbenv global 2.4.2 && gem install bundler'' returned a non-zero code: 2

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.13
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by liaogz82** [comment]
tried running with backtrace and verbose

```
Step 13/18 : RUN bash -l -c 'rbenv global 2.4.2 && gem install bundler --verbose --backtrace'
 ---> Running in f708950ec2dd
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - no such name (https://rubygems.org/specs.4.8.gz)
Getting SRV record failed: DNS result has no information for _rubygems._tcp.rubygems.org
The command '/bin/sh -c bash -l -c 'rbenv global 2.4.2 && gem install bundler --verbose --backtrace'' returned a non-zero code: 2
```

**Comment by colby-swandale** [comment]
I doubt this is an issue with rubygems.org. Are you sure there is working internet connection?

**Comment by einSelbst** [comment]
I'm experiencing the same symptom from within a restored iterm session. However, when I open a new session everything works fine.

**Comment by colby-swandale** [comment]
ping @liaogz82
