### ISSUE TITLE
Add which gem has an invalid gem referred to (invalid == no longer existing gem, in this context here)

### ISSUE THREAD

**Issue by shevegen** [rubygems/rubygems#2039]
Hello rubygems maintainers,

Just now, on a new machine, I am testing my gems from a remote installation. One gem called "rbt":

> gem install rbt

The above is the command I use.

The next is the result I get:

ERROR:  Could not find a valid gem 'move_file' (>= 0) in any repository
ERROR: Possible alternatives: moveable, save_file, wavefile, zonefile, bookfile

Now, I know to some extent as to why the above error exists. I used to have
a gem called "move_file" but since then I integrated it into my larger tool-kit
gem called "roebe".

The thing is - right now I do not know which faulty package references to
the (no longer existing gem) called "move_file".

Now I come to my proposal:

- Would it be possible to show which particular gem referenced this 
gem? That way I could very easily see which gem has a broken 
dependency. It is a bit hard for me to know which gem has a stray
missing dependency in .gemspec, also because some gemspec
files are autogenerated or reference to another dependency 
file. :\

The above message does not have to change much - either a new
line that says which gems is flawed, or to integrate this into the
currently used messages, such as:

"ERROR:  Could not find a valid gem 'move_file' (>= 0) in any repository (referenced by the gem foobar"

But a new message may probably be better; if more than one gem
has this missing dependency, then all could be shown, but I am also
perfectly fine if only one gem is shown at a time. Then I can fix it
and try gem install again.

Hopefully others may find this also useful. Thanks for reading, please
feel free to close the issue at any moment in time.

**Comment by bronzdoc** [comment]
https://github.com/rubygems/rubygems/pull/2067 closes this
