### ISSUE TITLE
Is --minimal-deps deprecated?

### ISSUE THREAD

**Issue by pv4** [rubygems/rubygems#2046]
`gem --minimal-deps --conservative` updates already installed gem dependencies even if they satisfy the version requirements. Is it ok?

I guess it is somehow connected with deprecation of `dependency_installer.rb:add_found_dependencies` (only used in `dependency_installer.rb:gather_dependencies`) that is the only place where `options[:minimal_deps]` is used.

Here are my current environment details:

```
$ gem env version
2.6.13
```

**Comment by colby-swandale** [comment]
Hi, which command are you referring to?

**Comment by pv4** [comment]
I'm sorry, I don't understand your question. What do you mean by "command"?

As I wrote, I refer to running `gem --minimal-deps --conservative`.

**Comment by colby-swandale** [comment]
the `gem` command by itself only takes `-v` or `-h` as options, i don't remember it every taking those options you specified. `gem update` allows the `--minimal-deps --conservative` options.

**Comment by pv4** [comment]
```
$ gem help update |grep -E 'minimal-deps|conservative'
        --conservative               Don't attempt to upgrade gems already
        --minimal-deps               Don't upgrade any dependencies that already
```

> gem update allows the --minimal-deps --conservative options.

That's what I mean. `gem update` accepts the options but ignores them.

**Comment by colby-swandale** [comment]
Can you please demonstrate how these options are not working the way you expect.

**Comment by colby-swandale** [comment]
ping @

**Comment by colby-swandale** [comment]
ping @pv4

**Comment by colby-swandale** [comment]
I'm closing this for now. If you're still experiencing your original issue don't be afraid to re-open this ticket.

**Comment by pv4** [comment]
Sorry for the delay :(

Here is how I reproduce the issue for now:
``` sh
$ mkdir dir; cd dir; mkdir bundle
$ gem install --minimal-deps -N -i bundle -v 1.16.0 bundler
Fetching: bundler-1.16.0.gem (100%)
Successfully installed bundler-1.16.0
1 gem installed
$ ls -1 bundle/gems/
bundler-1.16.0
$ gem install --minimal-deps -N -i bundle bundler
Fetching: bundler-1.16.2.gem (100%)
Successfully installed bundler-1.16.2
1 gem installed
$ ls -1 bundle/gems/
bundler-1.16.0
bundler-1.16.2
```

I expect that after the second `gem install` no new versions of bundler is installed since the currently installed version (1.16.0) satisfies the version requirement (none) requested during the second run of `gem install`.

The issue is a pain when developing for rails. I have a set of (stable) gems tested to work well with each other. When starting a project I copy them to vendor/bundle/ and everything works fine until I need to use a new gem. I add it to Gemfile, run `gem install --minimal-deps ...` to install that only gem and update the gems it depends on that are really needed to be updated (i.e. the gems that the new gem depends on newer versions of). But at this time `gem` updates all my copied stable gems, not only the needed ones.

**Comment by pv4** [comment]
I cannot reopen the issue, could you do it please?

**Comment by segiddins** [comment]
> I expect that after the second gem install no new versions of bundler is installed since the currently installed version (1.16.0) satisfies the version requirement (none) requested during the second run of gem install.

I think you may want `--conservative` for the particular desired behavior you're describing

**Comment by pv4** [comment]
`--conservative` appears to help if GEMNAME is supplied on the command line.

But the actual issue for me is installing using Gemfile. In this case `--conservative` does not help:

``` sh
$ mkdir dir; cd dir; mkdir bundle
$ gem install --conservative -N -i bundle -v 1.16.0 bundler
Fetching: bundler-1.16.0.gem (100%)
Successfully installed bundler-1.16.0
1 gem installed
$ ls -1 bundle/gems/
bundler-1.16.0
$ cat >Gemfile <<EOF
source 'https://rubygems.org'
gem 'bundler'
EOF
# was: `gem install --minimal-deps -N -i bundle bundler`
$ gem install --conservative -N -i bundle -g Gemfile
Fetching: bundler-1.16.2.gem (100%)
Installing bundler (1.16.2)
$ ls -1 bundle/gems/
bundler-1.16.0
bundler-1.16.2
```

So, `gem install` behaves differently when passing gems via Gemfile, and passing them via command line. Is this an intended behavior? Also note that `gem install` output is different in these two cases (in the example above).

**Comment by MSP-Greg** [comment]
The following might be what you're looking for.  From `gem help gem_dependencies`

```
A gem dependencies file allows installation of a consistent set of gems across
multiple environments.  The RubyGems implementation is designed to be
compatible with Bundler's Gemfile format.  You can see additional
documentation on the format at:

  http://bundler.io

RubyGems automatically looks for these gem dependencies files:

* gem.deps.rb
* Gemfile
* Isolate

These files are looked up automatically using `gem install -g`, or you can
specify a custom file.
```

**Comment by MSP-Greg** [comment]
@pv4

Sorry for the last post, you didn't use the `-g` argument in your first code example, I missed it in the second.

As to your 2nd example.  Using a gem version constraint in the Gemfile, all works as expected.  The 2nd `gem install` generates a 'Using gem (vers)` statement.

By having no version constraint(s) in your Gemfile, RubyGems can't determine if the currently installed gem meets them.  It then switches to 'default' behavior, which is to install the latest version.

Thanks, Greg

**Comment by pv4** [comment]
> Using a gem version constraint in the Gemfile, all works as expected. The 2nd gem install generates a 'Using gem (vers)` statement.

Still no success :(

``` sh
$ gem --version
2.7.6
$ mkdir dir; cd dir; mkdir bundle
$ gem install --conservative -N -i bundle -v 1.16.0 bundler
Fetching: bundler-1.16.0.gem (100%)
Successfully installed bundler-1.16.0
1 gem installed
$ ls -1 bundle/gems/
bundler-1.16.0
$ cat >Gemfile <<EOF
source 'https://rubygems.org'
gem 'bundler', '>= 1.16.0'
EOF
$ gem install --conservative -N -i bundle -g Gemfile
Fetching: bundler-1.16.2.gem (100%)
Installing bundler (1.16.2)
$ ls -1 bundle/gems/
bundler-1.16.0
bundler-1.16.2
```

> By having no version constraint(s) in your Gemfile, RubyGems can't determine if the currently installed gem meets them

Imho, if Gemfile author does not specify the version required then "there is no version requirement" and any version is sufficient (otherwise he/she would specify the requirements).

**Comment by MSP-Greg** [comment]
@pv4

No matter what I do, I cannot repo your issue.  I always get 'using'.  I am using RG 2.7.7, which includes Bundler 1.16.2.  Also, have you checked what Gemfile.lock shows?  Probabbly not an issue...

> Imho, if Gemfile author does not specify the version required then "there is no version requirement" and any version is sufficient (otherwise he/she would specify the requirements).

Although I think there are valid reasons for both viewpoints, I suspect that RG would like to discourage open-ended (or missing) version requirements in Gemfile.

The point of all of this is to guarantee that an **unknown system** meets requirements, and hence, would default to the newest version if none were specified...

**Comment by MSP-Greg** [comment]
@pv4

I'm on Windows.  I've got Ruby versions from 1.9.3 thru trunk, although only 2.4+ are the most current.  At present, all have RG 2.7.7.  I will have another look at this, but I can't get to it right away...
