### ISSUE TITLE
Error occurred when executing `gem update --system` using 2.7.0

### ISSUE THREAD

**Issue by koic** [rubygems/rubygems#2052]
An error occurred when executing `gem update --system --no-document` using RubyGems 2.7.0.
(It probably only happens on the first upgrade to 2.7.0)

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.0
```

The error log is as follows.

```console
% gem update --system --no-document
Updating rubygems-update
Fetching: rubygems-update-2.7.0.gem (100%)
Successfully installed rubygems-update-2.7.0
Installing RubyGems 2.7.0
ERROR:  While executing gem ... (NoMethodError)
    undefined method `files=' for nil:NilClass
```

I first found RubyGems 2.7.0 problem with the following address.
https://ci.appveyor.com/project/bbatsov/rubocop/build/1299/job/dsm6428up5o9rqqr

**Comment by koic** [comment]
The following is additional information of reproduction.

```console
% gem -v
2.6.13
% gem update --system
Updating rubygems-update
Fetching: rubygems-update-2.7.0.gem (100%)
Successfully installed rubygems-update-2.7.0
Installing RubyGems 2.7.0
ERROR:  While executing gem ... (NoMethodError)
    undefined method `files=' for nil:NilClass
% gem -v
2.7.0
% gem update --system
Latest version already installed. Done.
```

**Comment by hsbt** [comment]
I can reproduce this.

**Comment by segiddins** [comment]
I can look into this after class if no one beats me to it

**Comment by brandonblack** [comment]
Came here to report the same thing. 

I can confirm this is reproducible on the following rubies:
- 2.1.9
- 2.2.2
- 2.2.3
- 2.3.1
- 2.4.2

Despite the error, rubygems does appear to install successfully.

```bash
$ gem update --system 
Updating rubygems-update
Fetching: rubygems-update-2.7.0.gem (100%)
Successfully installed rubygems-update-2.7.0
Installing RubyGems 2.7.0
ERROR:  While executing gem ... (NoMethodError)
    undefined method `files=' for nil:NilClass

$ gem --version
2.7.0
```

**Comment by thisismydesign** [comment]
I also ran into the same thing.

As @brandonblack pointed out the installation is successful regardless of the error. Some of our builds actually still work but others fail so I suspect there is something wrong in the background.

IMO you should also look into whether the installation should've failed and if so why did it not. https://github.com/rubygems/rubygems/pull/2054 doesn't seem to address that.

**Comment by karlwbrown** [comment]
I am seeing this too on Centos7 with Ruby 2.4.1 and Gem 2.7
Also, it is doing something else strange - this command seems to leave a bundle script in /usr/local/bin/bundle - that perhaps is supposed to be deleted once the upgrade completes, but it's left lying around. Anyone else seen this?

**Comment by thisismydesign** [comment]
@karlwbrown Yes, I have a similar issue with trying to install `bundler` afterwards:
```
ERROR:  Error installing bundler:
  "bundle" from bundler conflicts with /opt/ruby-2.4.2/bin/bundle
```

However I could not reproduce it outside of our environment using a [simple Travis setup](https://github.com/thisismydesign/rubygems-update-2.7.0-bug). Did you manage to reproduce it?
