### ISSUE TITLE
409 Conflict on non-existent gem

### ISSUE THREAD

**Issue by shreve** [rubygems/rubygems#2056]
I'm having a problem.

My current problem is I'm trying to publish a new gem, but I cannot.

```
$ gem install [gemname]
ERROR:  Could not find a valid gem '[gemname]' (>= 0) in any repository
ERROR:  Possible alternatives: regional, begin_cli, rebind, redis-aid, refined

$ gem push -V [gemname]-0.1.0.gem
GET https://api.rubygems.org/latest_specs.4.8.gz
304 Not Modified
Pushing gem to https://rubygems.org...
POST https://rubygems.org/api/v1/gems
409 Conflict
Repushing of gem versions is not allowed.
Please use `gem yank` to remove bad gem releases.

$ gem yank -V [gemname] -v 0.1.0
Yanking gem from https://rubygems.org...
DELETE https://rubygems.org/api/v1/gems/yank
403 Forbidden
You do not have permission to delete this gem.

$ gem owner [gemname]
Owners for gem: [gemname]

$ gem query -r [gemname]

*** REMOTE GEMS ***

```

Searches for this gem on rubygems.org return "No Gems Found"

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [x] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.11

$ ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

Thank you for any feedback.

**Comment by segiddins** [comment]
What is the gem in question? My guess is that it is indeed owned by someone else, but they've yanked all versions.

**Comment by shreve** [comment]
the name is `reginald`.

**Comment by colby-swandale** [comment]
This seems like a rubygems.org question, i suggest posting your question to http://help.rubygems.org/ instead.
