### ISSUE TITLE
Bundler fails to install after RubyGems update

### ISSUE THREAD

**Issue by thisismydesign** [rubygems/rubygems#2058]
My current problem is after updating RubyGems I cannot install `bundler`. This is the case when running `gem install bundler` after either `gem install rubygems-update && update_rubygems` or `gem update --system`. The issue is present in both `2.7.0` and `2.7.1`. The issue is **not** present in `2.6.14`. The error I'm seeing:
```
ERROR:  Error installing bundler:
  "bundle" from bundler conflicts with /opt/ruby-2.4.2/bin/bundle
```
This was also referenced in #2052 by @karlwbrown and myself. Unfortunately I could not reproduce on a minimal example. ([1](https://github.com/thisismydesign/rubygems-update-2.7.0-bug/tree/d1a258895c2cf6f13116d4e37d8adc74fb35a58e), [2](https://travis-ci.org/thisismydesign/rubygems-update-2.7.0-bug/builds/297052701))

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.0, 2.7.1
```

Building via rbenv and docker.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by Gerg** [comment]
I was able to reproduce this issue while building this "minimal" docker image: 

```
FROM ubuntu:trusty

ENV HOME /root
RUN \
  echo '' > $HOME/.bashrc && \
  echo "[ -f ~/.bashrc ] && source ~/.bashrc" >> $HOME/.bash_profile

RUN \
  echo "deb http://apt.gemnasium.com stable main" > /etc/apt/sources.list.d/gemnasium.list && \
  echo "deb http://archive.ubuntu.com/ubuntu trusty-backports main restricted universe multiverse" > /etc/apt/sources.list.d/backports.list && \
  apt-key adv --recv-keys --keyserver keyserver.ubuntu.com E5CEAB0AC5F1CA2A && \
  apt-get update && \
  apt-get -y install \
    bison \
    build-essential \
    curl \
    debconf-utils \
    gemnasium-toolbelt \
    jq/trusty-backports \
    libcurl4-openssl-dev \
    libpq-dev \
    libreadline-dev \
    libsqlite3-dev \
    libssl-dev \
    libxml2-dev \
    libxslt-dev \
    libyaml-dev \
    mercurial \
    software-properties-common \
    unzip \
    wget \
    zip \
    zlib1g-dev

RUN \
  add-apt-repository ppa:git-core/ppa -y && \
  apt-get update && \
  apt-get install -y git && \
  apt-get remove -y --purge software-properties-common


RUN \
  wget https://github.com/postmodern/ruby-install/archive/v0.4.1.tar.gz -P /tmp && \
  tar zxf /tmp/v0.4.1.tar.gz -C /tmp && \
  cd /tmp/ruby-install-0.4.1 && make install && \
  ruby-install ruby 2.4.2 && \
  rm -rf /usr/local/src/ruby-2.4.2 && \
  rm -rf /tmp/*

RUN \
  git clone https://github.com/postmodern/chruby /tmp/chruby && \
  cd /tmp/chruby && git reset --hard 310bd34d1fcbb3365814c85018114123cef5a41f && \
  cd /tmp/chruby && ./scripts/setup.sh && \
  echo 'source /usr/local/share/chruby/chruby.sh' >> $HOME/.bashrc && \
  echo 'chruby 2.4.2' >> $HOME/.bashrc && \
  rm -rf /tmp/*


RUN bash -l -c "gem update --system" && \
    bash -l -c "gem install bundler --no-rdoc --no-ri"
```

Building using `docker build .` reliably results in the following output:

```
Step 8/8 : RUN bash -l -c "gem update --system" &&     bash -l -c "gem install bundler --no-rdoc --no-ri"
 ---> Running in d582d684cba7
Updating rubygems-update
Successfully installed rubygems-update-2.7.1
Parsing documentation for rubygems-update-2.7.1
Installing ri documentation for rubygems-update-2.7.1
Installing darkfish documentation for rubygems-update-2.7.1
Done installing documentation for rubygems-update after 38 seconds
Parsing documentation for rubygems-update-2.7.1
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 2.7.1
fatal: Not a git repository (or any of the parent directories): .git
Bundler 1.16.0 installed
RubyGems 2.7.1 installed
Regenerating binstubs
RubyGems system software updated
ERROR:  Error installing bundler:
	"bundle" from bundler conflicts with /opt/rubies/ruby-2.4.2/bin/bundle
The command '/bin/sh -c bash -l -c "gem update --system" &&     bash -l -c "gem install bundler --no-rdoc --no-ri"' returned a non-zero code: 1
```

**Comment by hsbt** [comment]
@thisismydesign @Gerg This is an intentional behavior. You can aim it to use `--force` option.

Can you try with `gem i bundler --force` ?

**Comment by karlwbrown** [comment]
I'm not sure if this behavior is good; after this script runs, bundler isn't really installed (for example, the 'bundler' command doesn't exist, only bundle). Also, if you try to *remove* the bundler gem immediately afterwards, it will show as not installed.

I think this 'bundle' script is a relic of the gem install process, and in older versions of rubygems it was removed after the install completed, which is what I think should be done here.

**Comment by thisismydesign** [comment]
@hsbt I hope that's not the case.. This behaviour as you can see is environment dependent, as far as I can tell does not follow how `rubygems` works with other gems and introduces a breaking change in 2.6 -> 2.7.

**Comment by hsbt** [comment]
This behavior is same as rdoc, rake and other default gems/bundled gems. not only bundler's one.

**Comment by hsbt** [comment]
In other words, I have no idea to fix this situation with vendored bundler.

**Comment by thisismydesign** [comment]
Yep I can reproduce that. I can also confirm that `--force` works.

Can we identify the side effects? My understanding is that I can't update defaults gems simply via the `gem` command:
```
Step 5/12 : RUN gem update rdoc
 ---> Running in 2228ddccf38e
ERROR:  Error installing rdoc:
"rdoc" from rdoc conflicts with /opt/ruby-2.4.2/bin/rdoc
```
Is this expected? If so it should most certainly be documented. Would this limitation cease if there's a new version of these gems?

What is the workaround if I wouldn't want to use the force? :) Do I `update_rubygems` each time I want to update any of these gems? Does that do anything if there's no update for `rubygems` itself but only for the default gems?

**Comment by karlwbrown** [comment]
This behavior seems to have changed from 2.6 to 2.7, so one should be able to see what changed to cause this new problem.

**Comment by hsbt** [comment]
> Is this expected?

Yes, It's expected behavior.

**Comment by pmorton** [comment]
Hi @hsbt - I have also run into this issue and after reading the comments, you have made it clear that it is an intended behavior, but it is unclear why and why now. I am sure that there is a good reason for this and sharing the reasoning may help the community better understand this decision.

**Comment by colby-swandale** [comment]
ping @hsbt

**Comment by hsbt** [comment]
@colby-swandale ?

This issue is an intentional and expected behavior of default gems. I have no opinion this.

**Comment by colby-swandale** [comment]
can this be closed then?

**Comment by hsbt** [comment]
Yes. I do.

I welcome a patch that changes current behavior of default gems.
