### ISSUE TITLE
Git error log on screen when updating RubyGems

### ISSUE THREAD

**Issue by thisismydesign** [rubygems/rubygems#2059]
My current problem is that I see a git error log when running `gem update --system`:
`fatal: Not a git repository (or any of the parent directories): .git`
Even though the folder in which I'm running the command contains a .git file. The command exists successfully.

Reproduced here:
https://github.com/thisismydesign/rubygems-update-2.7.0-bug/tree/af708a682aad32a047caeda5a5332ff2e19ca844
https://travis-ci.org/thisismydesign/rubygems-update-2.7.0-bug/builds/297064597
See the output of the before_install scripts `ls -a` and `gem update --system && gem install bundler`.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
Can you try again with Rubygems 2.7.2?

**Comment by bronzdoc** [comment]
ping @thisismydesign can you try what @hsbt suggested? thanks

**Comment by thisismydesign** [comment]
@hsbt @bronzdoc Looks good with 2.7.2, thanks!
