### ISSUE TITLE
gem update --conservative --explain does not explain, it updates

### ISSUE THREAD

**Issue by jeremyjs** [rubygems/rubygems#2068]
I ran `gem update --conservative --explain` and instead of explaining which gems it would update, it updated my gems. It appears to have ignored the `--explain` flag.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.13
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by colby-swandale** [comment]
Thanks for the report! I'm looking into this issue.
