### ISSUE TITLE
Allow multiple versions with --version

### ISSUE THREAD

**Issue by drbrain** [rubygems/rubygems#207]
`gem install some_gem -v '~> 1.5' -v '>= 1.5.2'` only uses the last version.  Specifying -v multiple times should combine like dependencies can do.

**Comment by krainboltgreene** [comment]
This is definitely still around.

**Comment by copiousfreetime** [comment]
This will involve updating [`Gem::VersionOption#add_version_option`](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/version_option.rb#L52) to merge `Gem::Requirement` instances as the `--version` option is processed
