### ISSUE TITLE
Test failure on Alpine Linux

### ISSUE THREAD

**Issue by duckinator** [rubygems/rubygems#2075]
I'm having a problem or would like to suggest a feature.

My current problem is a test failure on Alpine Linux.

The [`test_self_build_fail`](https://github.com/rubygems/rubygems/blob/76ef5bb/test/rubygems/test_gem_ext_configure_builder.rb#L47-L66) test fails with the following error:

```
  1) Failure:
TestGemExtConfigureBuilder#test_self_build_fail [/home/developer/rubygems/test/rubygems/test_gem_ext_configure_builder.rb:64]:
Expected /(?-mix:(\.\/configure: .*)|((?:Can't|cannot) open \.\/configure(?:: No such file or directory)?))/ to match "sh: can't open './configure'\n".
```

I _think_ this is just a matter of updating the regular expression, but I'm not entirely sure.

If nobody else gets to this first, I'll look into it when I get back to working on [duckinator/rubygems-docker-dev](https://github.com/duckinator/rubygems-docker-dev) some more.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

```
$ gem env version
2.6.13
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
Yeah, I think the `Can't` bit in the regexp might need to be changed to `[Cc]an't`

**Comment by duckinator** [comment]
Made a PR fixing this. `Can't` -> `[Cc]an't` + adding optional single quotes around `./configure` was enough to fix it.
