### ISSUE TITLE
$ gem list command for multiple installs of a gem incorrectly reporting

### ISSUE THREAD

**Issue by bkabrda** [rubygems/rubygems#208]
Hi,
I think that the list command misbehaves when I have the same gem installed in multiple directories in GEM_PATHS.

Example:
```
$ gem env
...
  - GEM PATHS:
     - /home/bkabrda/.gem/ruby/1.9.1
     - /usr/local/share/rubygems/gems
     - /usr/share/rubygems/gems
…
```

I install a gem (for example tzinfo) to the first and second directories, then gem list command behaves like this:
```
$ gem list tzinfo

*** LOCAL GEMS ***

tzinfo (0.3.30 ruby)
```

I believe, that this is not an expected behaviour and it should output either tzinfo (0.3.30, 0.3.30) or just tzinfo (0.3.30).

**Comment by bronzdoc** [comment]
I can't reproduce this with the current rubygems version(2.5.1) 
\cc @bkabrda
