### ISSUE TITLE
RVM fails to install RubyGems 2.7.2 as part of installing Ruby 2.4.2 from source, on macOS Sierra

### ISSUE THREAD

**Issue by BrianHawley** [rubygems/rubygems#2082]
I'm having a problem or would like to suggest a feature.

My current problem is with the initial installation of rubygems 2.7.2 as a part of the process of installing ruby from source, using rvm after it merged support for rubygems 2.7.2.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

```
$ gem env version
2.6.12
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

This has been reported to rvm in https://github.com/rvm/rvm/issues/4237 and they suggested that I talk to the RubyGems people. Pardon the rvm installation logs. The process for replicating the problem, on macOS 10.12.6 (Sierra):
```
$ rvm get master
# it worked
$ rvm install --disable-binary ruby-2.4.2
Checking requirements for osx.
Certificates bundle '/usr/local/etc/openssl@1.1/cert.pem' is already up to date.
Requirements installation successful.
Installing Ruby from source to: /Users/bhawley/.rvm/rubies/ruby-2.4.2, this may take a while depending on your cpu(s)...
ruby-2.4.2 - #downloading ruby-2.4.2, this may take a while depending on your connection...
ruby-2.4.2 - #extracting ruby-2.4.2 to /Users/bhawley/.rvm/src/ruby-2.4.2....
ruby-2.4.2 - #configuring..................................................................
ruby-2.4.2 - #post-configuration.
ruby-2.4.2 - #compiling..............................................................
ruby-2.4.2 - #installing.......
ruby-2.4.2 - #making binaries executable..
ruby-2.4.2 - #downloading rubygems-2.7.2
ruby-2.4.2 - #extracting rubygems-2.7.2.....
ruby-2.4.2 - #removing old rubygems........
ruby-2.4.2 - #installing rubygems-2.7.2.
Error running 'env GEM_HOME=/Users/bhawley/.rvm/gems/ruby-2.4.2@global GEM_PATH= /Users/bhawley/.rvm/rubies/ruby-2.4.2/bin/ruby -d /Users/bhawley/.rvm/src/rubygems-2.7.2/setup.rb --no-document',
please read /Users/bhawley/.rvm/log/1510957038_ruby-2.4.2/rubygems.install.log
```

The log:
```
$ cat /Users/bhawley/.rvm/log/1510957038_ruby-2.4.2/rubygems.install.log
[2017-11-17 14:20:02] /Users/bhawley/.rvm/rubies/ruby-2.4.2/bin/ruby
current path: /Users/bhawley/.rvm/src/rubygems-2.7.2
PATH=/usr/local/opt/coreutils/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/bhawley/.rvm/bin
command(7): env GEM_HOME=/Users/bhawley/.rvm/gems/ruby-2.4.2@global GEM_PATH= /Users/bhawley/.rvm/rubies/ruby-2.4.2/bin/ruby -d /Users/bhawley/.rvm/src/rubygems-2.7.2/setup.rb --no-document
Exception `LoadError' at /Users/bhawley/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems.rb:1346 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /Users/bhawley/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems.rb:1355 - cannot load such file -- rubygems/defaults/ruby
Exception `Gem::MissingSpecError' at /Users/bhawley/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/dependency.rb:308 - Gem::MissingSpecError
Bundler 1.16.0 installed
RubyGems 2.7.2 installed
Regenerating binstubs
```

Trying to use it afterwards:
```
$ rvm use ruby-2.4.2
Gemset '' does not exist, 'rvm ruby-2.4.2 do rvm gemset create ' first, or append '--create'.
```

It was a little weird to see the LoadError exceptions in the log, given that they're rescued, but they didn't stop the install process. That `Gem::MissingSpecError` exception may have stopped the install though. It's also possible that it's something else.

Seen in macOS 10.12.6 and CentOS 6.3.

**Comment by BrianHawley** [comment]
In comparison, with `rvm get stable` (version 1.29.3), installing ruby-2.4.2 succeeds. The log:
```
$ cat /Users/bhawley/.rvm/log/1510958538_ruby-2.4.2/rubygems.install.log
[2017-11-17 14:45:50] /Users/bhawley/.rvm/rubies/ruby-2.4.2/bin/ruby
current path: /Users/bhawley/.rvm/src/rubygems-2.6.14
PATH=/usr/local/opt/coreutils/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/libtool/bin:/usr/local/opt/automake/bin:/usr/local/opt/autoconf/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/Users/bhawley/.rvm/bin
command(7): env GEM_HOME=/Users/bhawley/.rvm/gems/ruby-2.4.2@global GEM_PATH= /Users/bhawley/.rvm/rubies/ruby-2.4.2/bin/ruby -d /Users/bhawley/.rvm/src/rubygems-2.6.14/setup.rb --no-document
Exception `LoadError' at /Users/bhawley/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems.rb:1346 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /Users/bhawley/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems.rb:1355 - cannot load such file -- rubygems/defaults/ruby
Exception `Gem::MissingSpecError' at /Users/bhawley/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/dependency.rb:308 - Gem::MissingSpecError
RubyGems 2.6.14 installed
```
Then it lists the release notes for RubyGems 2.6.14, as usual. The log directory also includes files that weren't included in the log directory of the failing install: "gemset.wrappers.default.log", "gemset.wrappers.global.log" and "gemsets.import.global.log". The lack of those files means that the gemsets probably weren't created, which would explain the error on using the ruby version.

**Comment by pkuczynski** [comment]
Similar problems happen on other platforms: https://github.com/rvm/rvm/issues/4240

This issue appeared after this change in RVM: https://github.com/rvm/rvm/pull/4232/files

So no change on our side really...

**Comment by hsbt** [comment]
@pkuczynski I update tgz package today. Can you confirm new value of md5 and sha512?

* http://blog.rubygems.org/2017/11/08/2.7.2-released.html
* https://github.com/rubygems/rubygems/issues/2085

**Comment by pkuczynski** [comment]
@hsbt shouldn't we get new version fixing this issue? It does not seem to be related with #2085? I can re-upload new hashes, but where can I download correct versions?

**Comment by hsbt** [comment]
@pkuczynski 

Ah, sorry. #2085 is not related this issue. When I looked https://github.com/rvm/rvm/pull/4232/files, I confirmed you are rvm package maintainer. So, I update hashes of rubygems now. I notice this change to you.

You can download it packages from our distributed pages: https://rubygems.org/pages/download (now cache is purged)

@BrianHawley Thanks for your report. Can you make minimum reproducible instructions without rvm?

**Comment by pkuczynski** [comment]
@hsbt I updated rubygems hashes for versions 2.7.*. See https://github.com/rvm/rvm/commit/ff63fa117bd05e581ecbf2b0378d9ddbb263deb1

I also created a branch for you, so you can test and debug the issue. All you have to do is to install rvm and any ruby:

```
curl -sSL https://get.rvm.io | bash
rvm get branch /debug-rubygems-2.7-issue
rvm install 2.4.1
```

Would you find some time to work on this?

**Comment by PikachuEXE** [comment]
I got this error with branch `/debug-rubygems-2.7-issue`:
```
ruby-2.4.2 - #installing rubygems-2.7.3 - please wait
Error running 'env GEM_HOME=/Users/PikachuEXE/.rvm/gems/ruby-2.4.2@global GEM_PATH= /Users/PikachuEXE/.rvm/rubies/ruby-2.4.2/bin/ruby -d /Users/PikachuEXE/.rvm/src/rubygems-2.7.3/setup.rb --no-document',
please read /Users/PikachuEXE/.rvm/log/1512179771_ruby-2.4.2/rubygems.install.log
```
```
$ cat /Users/PikachuEXE/.rvm/log/1512179771_ruby-2.4.2/rubygems.install.log                                                                                                                                  [10:02:41]
Exception `LoadError' at /Users/PikachuEXE/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems.rb:1346 - cannot load such file -- rubygems/defaults/operating_system
Exception `LoadError' at /Users/PikachuEXE/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems.rb:1355 - cannot load such file -- rubygems/defaults/ruby
Exception `Gem::MissingSpecError' at /Users/PikachuEXE/.rvm/rubies/ruby-2.4.2/lib/ruby/2.4.0/rubygems/dependency.rb:308 - Gem::MissingSpecError
Bundler 1.16.0 installed
RubyGems 2.7.3 installed
Regenerating binstubs
```

Let me know how to get more info for debugging

**Comment by segiddins** [comment]
Does this happen when installing Ruby via its Makefile, or only via RVM?

**Comment by PikachuEXE** [comment]
I have no idea how to install through Makefile

But if I use `rvm get stable` first then install 2.4.x, then no error occured and also can update rubygems to 2.7.3.

**Comment by tjouan** [comment]
Run `make install`, complete instructions are in README.md file
(search for "How to compile and install") at the root. There is also a
summary here:
https://www.ruby-lang.org/en/documentation/installation/#building-from-source

I think having minimum reproducible instructions would help a lot,
ideally only with RubyGems, or optionally with Ruby.

If you use a tool to build and install, the commands run by the tool
should be determined (verbose mode? log file?), then attempted in
isolation. If you find the command or option that trigger the error,
then please report it so other can reproduce and check if it's a bug
and how it could be fixed.

**Comment by pkuczynski** [comment]
Possibly https://github.com/rvm/rvm/pull/4287 would fix this issue. @BrianHawley can you test with latest `rvm get master`?

**Comment by PikachuEXE** [comment]
On my current machine `rvm get master` and `rvm install 2.4.2` works well
I am gonna try it on my other machines this weekend too

**Comment by PikachuEXE** [comment]
Works fine on my another machine too (same OS version, able to reproduce this issue before)
Thanks :)

**Comment by BrianHawley** [comment]
Works for me too, thanks.
