### ISSUE TITLE
Warnings when extracting the source tarball (tar: Ignoring unknown extended header keyword 'SCHILY.dev')

### ISSUE THREAD

**Issue by mauromorales** [rubygems/rubygems#2085]
When extracting version 2.7.2 of the tar package on Linux, a lot of warnings are displayed. This is not the case for macOS or any of the previous tar packages. My assumption is that the package was built using BSD tar instead of GNU tar.

Steps to reproduce:

```
$ wget https://rubygems.org/rubygems/rubygems-2.7.2.tgz
...
$ tar zxvf rubygems-2.7.2.tgz
...
rubygems-2.7.2/lib/rubygems/commands/open_command.rb
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
rubygems-2.7.2/lib/rubygems/commands/specification_command.rb
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
rubygems-2.7.2/lib/rubygems/commands/environment_command.rb
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
rubygems-2.7.2/lib/rubygems/commands/build_command.rb
tar: Ignoring unknown extended header keyword 'SCHILY.dev'
tar: Ignoring unknown extended header keyword 'SCHILY.ino'
tar: Ignoring unknown extended header keyword 'SCHILY.nlink'
...
```

These are just warnings, the resulting value is still 0 and the packages is properly extracted in its own directory.

```
$ echo $?
0
$ ls
rubygems-2.7.2
```

Issue was tested on Ubuntu 14.04.5 LTS and openSUSE 42.3 and the results are the same.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
@mauromorales Thanks, I created 2.7.2 package with BSD-tar. I try to upload tgz again.

**Comment by hsbt** [comment]
@mauromorales I did create 2.7.2 package with gnu-tar. Can you try it?

**Comment by hsbt** [comment]
Note: CDN stored old package cache yet.

**Comment by mauromorales** [comment]
@hsbt thanks a lot! Closing as there are no more warnings

**Comment by CamJN** [comment]
This issue seems to be back for rubygems-2.7.7.tgz (at least via rvm)
