### ISSUE TITLE
Unable to use gem install on Lustre filesystem mounted with noflock

### ISSUE THREAD

**Issue by jschwab** [rubygems/rubygems#2092]
I am unable to use `gem install <name>` on a computing cluster that I use.  When I issue the command I get 

```
hyades: ~$ gem install mesa_reader
ERROR:  While executing gem ... (Errno::ENOSYS)
    Function not implemented @ rb_file_flock - /pfs/home/jschwab/.gem/specs/api.rubygems.org%443/quick/Marshal.4.8/mesa_reader-0.1.0.gemspec
```

This error is not specific to this gem.  It occurs for all gems I have tried.

This computing cluster uses the Lustre file system.  Given the error message, this issue seems related to the use of the mount option
```
  noflock
	Disable posix file locking (Applications trying to use
	the functionality will get ENOSYS)
```
That option cannot be changed.

As a workaround, if I download the gem file separately (e.g. with wget), I am then able to install the gem with `gem install <file>`.

For a single gem, this isn't so bad.  But for a gem with many dependencies, downloading installing them manually becomes a chore.

This issue is related to:

  - [ ] Network problems
  - [X] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.13
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
It's limitation of lustre filesystem. Can you try following patch? because I didn't try this code on lustre filesystem.

```
diff --git lib/rubygems.rb lib/rubygems.rb
index b7097f22..bf42395f 100644
--- lib/rubygems.rb
+++ lib/rubygems.rb
@@ -161,7 +161,7 @@ module Gem
   # these are defined in Ruby 1.8.7, hence the need for this convoluted setup.
 
   READ_BINARY_ERRORS = begin
-    read_binary_errors = [Errno::EACCES, Errno::EROFS]
+    read_binary_errors = [Errno::EACCES, Errno::EROFS, Errno::ENOSYS]
     read_binary_errors << Errno::ENOTSUP if Errno.const_defined?(:ENOTSUP)
     read_binary_errors
   end.freeze
@@ -171,7 +171,7 @@ module Gem
   # these are defined in Ruby 1.8.7.
 
   WRITE_BINARY_ERRORS = begin
-    write_binary_errors = []
+    write_binary_errors = [Errno::ENOSYS]
     write_binary_errors << Errno::ENOTSUP if Errno.const_defined?(:ENOTSUP)
     write_binary_errors
   end.freeze
```

**Comment by jschwab** [comment]
This patch resolved my issue.  (I manually applied the change to ruby 2.4.2.)  Thanks!
