### ISSUE TITLE
Hello guys, I'm having a problem. When I try to execute "gem install installer", I got this error. Any fix for this ?

### ISSUE THREAD

**Issue by SambitKumarPanda** [rubygems/rubygems#2095]
`ERROR:  Could not find a valid gem 'bundler' (>= 0) in any repository ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)     Errno::ECONNREFUSED: No connection could be made because the target machine actively refused it. - connect(2) (http://rubygems.org/latest_specs.4.8.gz)`

**Comment by lucasprag** [comment]
@SambitKumarPanda could you please post the output of the command `gem env version` ?

**Comment by lucasprag** [comment]
also, cut the error message of the title of the issue and paste it here as a comment please. =)

**Comment by SambitKumarPanda** [comment]
gem env version : 1.8.24

**Comment by lucasprag** [comment]
I think there is no gem installer [see](https://rubygems.org/search?utf8=%E2%9C%93&query=installer)
@SambitKumarPanda

**Comment by lucasprag** [comment]
@SambitKumarPanda as there is no gem called installer, I got the same output:

![gem-install-installer-output](https://user-images.githubusercontent.com/2293178/33127101-32d1e30a-cf6e-11e7-828d-10ed93498ca7.png)

@SambitKumarPanda maybe you have confused with other gem called something-installer =)

**Comment by lucasprag** [comment]
@SambitKumarPanda by something, I mean some of the available gems:
![something-installer](https://user-images.githubusercontent.com/2293178/33127213-b1decdca-cf6e-11e7-8d93-dfa8bf7d2a24.png)

**Comment by SambitKumarPanda** [comment]
@lucasprag I didn't get. I am a newbie in ruby :) Actually I was trying to install redmine in my pc from http://www.redmine.org/projects/redmine/wiki/redmineinstall . Got struck in step 4. Can you guide me on this ?

**Comment by olleolleolle** [comment]
@SambitKumarPanda In order to have an easier time installing new software, you may wish to:

Update [your RubyGems installation](http://guides.rubygems.org/rubygems-basics/) - the `gem` executable has this self-update command:

```
gem update --system
```

Install the [Bundler](http://bundler.io/) gem:

```
gem install bundler
```

When this has worked, you will have access to the `bundle` executable.

With that, you can follow Step 4 of the Redmine installation notes:

```
bundle install --without development test
```

---

The `connect(2)` issue reported is a network connectivity issue. (Here are some sample questions for you to narrow your search for this.)

- Can you access the `http://rubygems.org/latest_specs.4.8.gz` URL in some other way from your computer?
- Do you use a proxy?

---

Hope this helps you!

**Comment by lucasprag** [comment]
@SambitKumarPanda welcome to ruby =)

First of all, why are you trying to run the command `gem install installer` ?

**Comment by lucasprag** [comment]
as @olleolleolle described, in order to install the Redmine you need to run theses commands (step 4):

```
gem install bundler
bundle install --without development test
```
I think you confused `bundler` with `installer`

**Comment by lucasprag** [comment]
Please confirm that so we can close this issue @SambitKumarPanda 
Thank you =)

**Comment by SambitKumarPanda** [comment]
@olleolleolle @lucasprag Will try your suggestions now & update.

**Comment by SambitKumarPanda** [comment]
@olleolleolle Getting the same error on executing `gem update --system`. I guess it's a network issue since I am using my company's proxy.

**Comment by olleolleolle** [comment]
@SambitKumarPanda Thanks for focusing your investigation!

Can we close this issue, now that we know more?

**Comment by SambitKumarPanda** [comment]
Thanks @olleolleolle @lucasprag for all the help. Yes, you can close this issue now.

**Comment by olleolleolle** [comment]
@SambitKumarPanda Only _you_ can.

**Comment by SambitKumarPanda** [comment]
Sure! :)
