### ISSUE TITLE
gem yank not working

### ISSUE THREAD

**Issue by etm** [rubygems/rubygems#2097]
I'm having a problem. My current problem is: 

gem yank ruby-xml-smart -v 0.1.12.1 -p i486-linux
Yanking gem from https://rubygems.org...
The version 0.1.12.1 does not exist.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [X ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.6
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by colby-swandale** [comment]
This is a rubygems.org issue, please open an issue at http://help.rubygems.org/
