### ISSUE TITLE
gem yank - suggestion to exchange the HTML output on the commandline with some more succinct error/warning message to the user

### ISSUE THREAD

**Issue by shevegen** [rubygems/rubygems#2129]
Hello rubygems / gem maintainers,

This is a suggestion that arose out of a few noticed hiccups when
trying to yank away old gems. This, I believe, may also somehow
relate to a few unicorn-related problems on rubygems.org, but
I can not be sure here (it's difficult to say; other people may also
report unicorn-related problems but these may be unrelated with
what I noticed, for example).

Either way, this issue report is just about one thing.

- It is possible to yank away gems from the commandline, and
this works very well.

However had, in particular when I do **batch-yanks**, that is, several
yanking operations of gems on the commandline (like 20 yanks; I 
copy/paste these individual commands into a tab of KDE Konsole),
I get strange results after the first some gems. So the first some gems
work fine, then it is more likely that hiccups happen.

For example, a command like this:

    gemyank cookbooks --version 0.0.1086   # November 26, 2017 (834 KB) 

(gemyank is my alias for the gem yank command)

Then I get:

Yanking gem from https://rubygems.org...

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <link rel="shortcut icon" href="/favicon.ico" type="image/x-icon">
    
    <title>Unicorn! | RubyGems.org</title>
  </head>
  <body style="font-family: 'Helvetica Neue', Helvetica, Arial, sans-serif">
    <div style="margin-right: auto; margin-left: auto; width: 90%; max-width: 940px;">
      <div style="padding-top: 60px; position: relative;">
        <object height="530" type="image/svg+xml" alt="503 error" style="width: 100%;" data="/images/sea_level.svg"></object>
      </div>
      <div style="margin-right: auto; margin-bottom: 120px; margin-left: auto; max-width: 680px; text-align: center;">
        <h1 style="margin-top: 25px; margin-bottom: 8px; font-weight: 200; font-size: 60px; ">Unicorn!</h1>
        <p style="font-weight: 300; font-size: 18px; line-height: 1.66; ">We are having a bad problem and the app server will not talk to us.</p>
        <a href="/" style="font-weight: 300; font-size: 18px; line-height: 1.66;  text-decoration: none; color: #e9573f;">Back to RubyGems.org</a>
      </div>
    </div>
  </body>
</html>

---

Not sure if this is easy for you to see, so I explain it - I get some
HTML output on the commandline, saying that there was some 
unicorn-related problem.

HTML Output on the commandline is not very useful, so my
suggestion is to not show this HTML output, and instead 
provide some more succinct error message. For example:

"There was a problem yanking gem BLA version BLA."

Or something like this; could be a bit more descriptive as
well.

Hopefully I was able to explain the problem. It is difficult
for me to pinpoint where the problem is exactly, but I
am reasonably sure that it may have to do with batch-yanking
gems. I'll report this just in case someone is able to have
a look.

**Comment by segiddins** [comment]
I think this is just a matter of having rubygems.org return a response in the expected format on 5xx errors?

**Comment by bronzdoc** [comment]
should this issue be reported to https://github.com/rubygems/rubygems.org?

**Comment by bronzdoc** [comment]
So we are just printing the output of the rubygems.org api, please open this issue in   https://github.com/rubygems/rubygems.org thanks
