### ISSUE TITLE
Randomly failing Travis jobs after minitest5

### ISSUE THREAD

**Issue by hsbt** [rubygems/rubygems#2133]
We got following failure with minitest5. 

```
  1) Failure:
TestGemLocalRemoteOptions#test_clear_sources_option_idiot_proof [/home/travis/build/rubygems/rubygems/test/rubygems/test_gem_local_remote_options.rb:48]:
--- expected
+++ actual
@@ -1 +1,3 @@
-["https://rubygems.org/"]
+#<Gem::SourceList:0xXXXXXX
+ @sources=
+  [[Remote: http://test.example.com/ API URI: http://test.example.com/]]>
```

**Comment by segiddins** [comment]
This is the same failure that @MSP-greg has reported

**Comment by MSP-Greg** [comment]
@segiddins

@hsbt & I are working on a PR that includes a patch for this issue...  Thanks, Greg

**Comment by colby-swandale** [comment]
@hsbt has this issue been resolved?

**Comment by hsbt** [comment]
I'm not sure what is resolved. The test suite of rubygems still fails randomly like https://github.com/rubygems/rubygems/pull/2278#issuecomment-388574646

**Comment by bronzdoc** [comment]
I'm going to close this, for what i understand in https://github.com/rubygems/rubygems/pull/2311 tests are stable now, let me know if this should be reopened.
