### ISSUE TITLE
--destdir appears to be broken for installing rubygems 2.7.x

### ISSUE THREAD

**Issue by Roguelazer** [rubygems/rubygems#2134]
I'm having a problem.

Attempting to package rubygems 2.7 using the --destdir feature fails; the embedded bundle installation attempts to write to the actual prefix (`/opt/ruby2.3` in my case) instead of `$DESTDIR/{prefix}`. This behavior appears with either `--destdir` or setting the environment variable `DESTDIR` before running `ruby setup.rb`.

This functionality works correctly on 2.6.14 but not on any 2.7.x versions.

This issue is related to:

  - Other

Here are my current environment details:

```
$ gem env version
PASTE HERE
```

not applicable; the Ruby which I am attempting to package is 2.3.6 with Rubygems 2.7.4 (latest).

The tail of running `setup.rb` during my rpmbuild can be found at https://gist.github.com/Roguelazer/0be8a4229cb14fd31006a73998296cf2.

Obviously I don't expect y'all to do anything about my RPM in particular, but you can reproduce this by attempting to run `ruby setup.rb --destdir $HOME/some/directory` and observing that it fails when it can't write to your actual ruby prefix.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by tjouan** [comment]
If you package bundler as a separate RPM package, the following patch
might work for you:

``` patch
--- lib/rubygems/commands/setup_command.rb.orig	2017-12-04 22:29:02 UTC
+++ lib/rubygems/commands/setup_command.rb
@@ -148,8 +148,6 @@ By default, this RubyGems will install g
 
     remove_old_lib_files lib_dir
 
-    install_default_bundler_gem
-
     say "RubyGems #{Gem::VERSION} installed"
 
     regenerate_binstubs if options[:regenerate_binstubs]
@@ -217,7 +215,6 @@ By default, this RubyGems will install g
     @bin_file_names = []
 
     executables = { 'gem' => 'bin' }
-    executables['bundler'] = 'bundler/exe' if Gem::USE_BUNDLER_FOR_GEMDEPS
     executables.each do |tool, path|
       say "Installing #{tool} executable" if @verbose
 
```

If you want to fix where bundler default gem is installed, then maybe
apply this one:
``` patch
--- a/lib/rubygems/commands/setup_command.rb
+++ b/lib/rubygems/commands/setup_command.rb
@@ -350,7 +350,9 @@ def fake_spec.full_gem_path
   def install_default_bundler_gem
     return unless Gem::USE_BUNDLER_FOR_GEMDEPS
 
-    mkdir_p Gem::Specification.default_specifications_dir
+    specs_dir = File.join options[:destdir],
+      Gem::Specification.default_specifications_dir
+    mkdir_p specs_dir
 
     # Workaround for non-git environment.
     gemspec = File.open('bundler/bundler.gemspec', 'rb'){|f| f.read.gsub(/`git ls-files -z`/, "''") }
@@ -359,11 +361,12 @@ def install_default_bundler_gem
     bundler_spec = Gem::Specification.load("bundler/bundler.gemspec")
     bundler_spec.files = Dir.chdir("bundler") { Dir["{*.md,{lib,exe,man}/**/*}"] }
     bundler_spec.executables -= %w[bundler bundle_ruby]
-    Dir.entries(Gem::Specification.default_specifications_dir).
+    Dir.entries(specs_dir).
       select {|gs| gs.start_with?("bundler-") }.
-      each {|gs| File.delete(File.join(Gem::Specification.default_specifications_dir, gs)) }
+      each {|gs| File.delete(File.join(specs_dir, gs)) }
 
-    default_spec_path = File.join(Gem::Specification.default_specifications_dir, "#{bundler_spec.full_name}.gemspec")
+    default_spec_path = File.join specs_dir,
+      "#{bundler_spec.full_name}.gemspec"
     Gem.write_binary(default_spec_path, bundler_spec.to_ruby)
 
     bundler_spec = Gem::Specification.load(default_spec_path)
@@ -374,8 +377,15 @@ def install_default_bundler_gem
         each {|default_gem| rm_r File.join(bundler_spec.gems_dir, default_gem) }
     end
 
-    mkdir_p bundler_spec.bin_dir
-    bundler_spec.executables.each {|e| cp File.join("bundler", bundler_spec.bindir, e), File.join(bundler_spec.bin_dir, e) }
+    bundler_bin_dir = File.join(
+      options[:destdir], Gem.default_dir, 'gems',
+      bundler_spec.full_name, bundler_spec.bindir
+    )
+    mkdir_p bundler_bin_dir
+    bundler_spec.executables.each do |e|
+      cp File.join("bundler", bundler_spec.bindir, e),
+        File.join(bundler_bin_dir, e)
+    end
 
     if Gem.win_platform?
       require 'rubygems/installer'
```

You might also be interested by info in #2106.

**Comment by segiddins** [comment]
So is the issue here that `#bin_dir` and `.default_specifications_dir` don't respect the `--destdir` parameter?

**Comment by colby-swandale** [comment]
ping @Roguelazer

**Comment by Roguelazer** [comment]
Practically, the issue is that `--destdir` used to work (for building RPMs or such) and no longer does. I haven't dug deep enough to see if there are other issues besides those @segiddins mentioned.

**Comment by segiddins** [comment]
Looking at this a bit more, the 2nd diff @tjouan shared looks like a reasonable solution -- any interest in sending up a PR?
