### ISSUE TITLE
Update a gem but not its dependencies

### ISSUE THREAD

**Issue by Ana06** [rubygems/rubygems#2145]
As said in [the documentaion](http://bundler.io/man/bundle-update.1.html), when updating a gem its dependencies are updated as well:

> Sometimes, you want to update a single gem in the Gemfile(5), and leave the rest of the gems that you specified locked to the versions in the Gemfile.lock.
> 
> For instance, in the scenario above, imagine that nokogiri releases version 1.4.4, and you want to update it without updating Rails and all of its dependencies. To do this, run bundle update nokogiri.
> 
> Bundler will update nokogiri and any of its dependencies, but leave alone Rails and its dependencies.

An not only it dependencies, but the dependencies of the dependencies as well. That can end in updating a lot of gems, when we only wanted to update a a concrete ones. 

A recent example: when updating font-awesome-rails from 4.0.7.2 to 4.7.0.3 using `gem update font-awesome-rails`, the last version of  minitest (5.11.1) also gets installed . However `font-awesome-rails` do not have any dependency with minitest, as it is the dependency of its dependency. If this minitest version had a bug, It could break my program when I only wanted to update font-awesome-rails, which would have worked perfectly with the other version.

I would say that sometimes it would make sense to update a gem without updating its dependencies. What about introducing an option for that? 🤔

**Comment by colby-swandale** [comment]
This is not really doable because of how RubyGems works. If you have a gem installed that depends on another gem (ie: the Gem has `s.add_dependency <dependency>` in its `.gemspec`) which is not installed and you try to `require` the gem, RubyGems will raise a `Gem::MissingSpecError` error.

**Comment by Ana06** [comment]
Maybe I didn't explain it correctly. What I mean is when a gem is installed and it's dependencies as well. Then we want to update the gem, but not de dependencies if it is not needed.

So, for example font-awesome-rails 4.0.7.2 and minitest 5.10 are installed. We update font-awesome-rails yo 4.0.7.3 and although it would have worked with minitest 5.10, as it is a dependency of a dependency it get updated as well to 5.11.1.

**Comment by colby-swandale** [comment]
Ah, thanks for clarifying, `gem update` has an argument called `--minimal-deps` that won't update any dependencies that already meet version requirements from all the dependencies of the gem that's being updated. Does this help?

**Comment by segiddins** [comment]
`gem install --conservative` might also be what you're looking for

**Comment by colby-swandale** [comment]
ping @Ana06 were you able to solve your issue?

**Comment by Ana06** [comment]
I think so, thanks @colby-swandale
