### ISSUE TITLE
Shortcomings of `gem unpack`

### ISSUE THREAD

**Issue by bquorning** [rubygems/rubygems#2149]
I'm would like to suggest a feature.

My current problem is that `gem unpack <gem name> --target vendor/gems --spec` unpacks the gem’s gemspec to `pwd`. I would expect it to:

1. unpack to ./vendor/gems/, and
2. unpack the entire gem, including the gemspec.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.4
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by colby-swandale** [comment]
Thanks for the report. I'm going to mark this as a bug because from a UX perspective there shouldn't be any issues with being able to do this.

**Comment by shevegen** [comment]
I sort of agree with colby and bquorning since the user has, in this example, provided a specific --target.
