### ISSUE TITLE
gem install (& update?) build arg issues

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2151]
First of all, my 'use case'.  I use trunk, and I run under windows.  Hence, I must build any extension gems that I use.

My `.gemrc` file contains the following for install:
```
install: --no-document --env-shebang --platform ruby -- --use-system-libraries
```

When using arguments with `gem install` and the above `.gemrc` line, none of the CLI args are parsed.  Conversely, if I remove the build argument from `.gemrc`, everything works fine.

Hence, it seems that the handling of build arguments is broken.

Some thoughts / questions:

1. [`Gem::GemRunner#extract_build_args`](https://github.com/ruby/ruby/blob/trunk/lib/rubygems/gem_runner.rb#L66-L74) is a method that should probably be duplicated in `Gem::Command`.

2. [`Gem::Command#handle_options`](https://github.com/ruby/ruby/blob/trunk/lib/rubygems/command.rb#L385-L390) is where the OptionParser is used, and also where the `Gem::ConfigFile` options are merged with CLI options.

3. At the end of `Gem::Command#handle_options`, should all build arguments be included in `options[:build_args]`?

4. At the end of `Gem::Command#handle_options`, should all build arguments not be included in `options[:args]`?

5. How does `Gem::Command.build_args` enter in to all of this?  Should it be loaded when [`Gem::Command.add_specific_extra_args`](https://github.com/ruby/ruby/blob/trunk/lib/rubygems/command.rb#L92-L95) is called?

6. Or, should the above be ignored, and build args are left in the `specific_extra_args_hash`, and handled in [`Gem::Command#add_extra_args`](https://github.com/ruby/ruby/blob/trunk/lib/rubygems/command.rb#L395-L411), which is called in `Gem::Command#handle_options`?

I'm fine with doing a PR, just wanted to double check with a few questions.  Hope this makes sense...

Thanks, Greg 

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [X] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by MSP-Greg** [comment]
I just remembered...

`Gem::ConfigFile` states that 'gemrc files may exist in various locations and are read and merged'.  If build arguments exist in more than one, and given that the build arguments must be split separately, not after the 'merge', it would seem that `Gem::ConfigFile` should have a hash for `specific_build_args_hash`.   The hash would be merged with CLI args in `Gem::Command#handle_options`...

**Comment by MSP-Greg** [comment]
Just to be clear as to why this is a **bug**:
```
# .gemrc
install: --no-document --env-shebang --platform ruby -- --use-system-libraries

# running
gem <some gem> --user-install
# gem is incorrectly installed to INSTALLATION DIRECTORY
````

but, without build argument:
```
# .gemrc
install: --no-document --env-shebang --platform ruby

# running
gem <some gem> --user-install
# gem is installed to USER INSTALLATION DIRECTORY
```

**Comment by segiddins** [comment]
I've not looked into any of these parts of RubyGems, but all of your ideas seem like good ones to me?

**Comment by MSP-Greg** [comment]
Dumb question.  Are 'build arguments' mostly a windows issue?

FYI, I'm aware I've got the following, listed in the order I hope to work on them:
1. Test issues
2. Bin stub issues
3. This issue
4. Install/Update & ruby version constraint issues.

**Comment by segiddins** [comment]
> Dumb question. Are 'build arguments' mostly a windows issue?

I don't see why they would be?

**Comment by MSP-Greg** [comment]
Have you used them?  For instance, EventMachine & Puma (previous to some gemspec metadata being added) required build arguments to compile on Windows.  I've never seen mention of build arguments for MacOS or Linux...

**Comment by segiddins** [comment]
I'm pretty sure I have them set on my other machine for building either eventmachine or puma, but I can check on Monday. I typically just install stuff via bundler, which has its own mechanism for setting default build arguments

**Comment by indirect** [comment]
@MSP-Greg can you tell us more about the background of your situation? Do you install many gems via `gem install`, but less or no gems via `bundle install`? What are the underlying goals that you are able to accomplish by setting `--no-document --env-shebang --platform ruby -- --use-system-libraries`?

If definitely seems useful to be able to set build arguments separately from other flags. In fact, Bundler already lets you set build arguments on a per-gem basis, and applies them to any bundle containing that gem. Something similar in RubyGems seems very reasonable.

**Comment by MSP-Greg** [comment]
> can you tell us more about the background of your situation?

I use trunk on Windows.  I've also been somewhat active in trying to get more repos/gems to test with Windows and also trunk, whether it be on Travis, Appveyor, etc.  So:

1. Using Bundler just doesn't work with trunk, I don't consider this to be a Bundler issue. 
1. Every extension gem I use must be compiled.
2. Some (but not all) gems version constrict Ruby to 'less than trunk'.
3. I often edit gem ruby version restrictions and just install whatever is the newest, as it has (hopefully) been tested against trunk.

> In fact, Bundler already lets you set build arguments on a per-gem basis

Yes, I've taken advantage of that in some repos for testing.

I'm slowly getting more familiar with RubyGems code.  If you look at [gem_runner.rb:L42](https://github.com/rubygems/rubygems/blob/82b1b28511e5b090c81eb76c77769429345decb4/lib/rubygems/gem_runner.rb#L42), build arguments are only stripped out of CLI arguments.  Since `Gem::ConfigFile.new` 'prepends' config file items to the 'args array', if the 'config array' ends with build arguments (like my example), things blow up.

At present, my thought for a fix is to change the signature to 
```ruby
Gem::ConfigFile.new(args, build_args = nil)
```
and if build_args is not nil, strip the build arguments from config info.  I need to look at the Install & Update commands to see if this would solve the issue when they are used directly.

Thanks,

Greg

**Comment by bronzdoc** [comment]
This looks like it has been answered. Closing.
