### ISSUE TITLE
Warn for deprecated SPDX license identifiers?

### ISSUE THREAD

**Issue by wking** [rubygems/rubygems#2153]
Some of the current SPDX license and exception identifiers are deprecated by the SPDX (e.g. [`GPL-3.0` has been deprecated in favor of `GPL-3.0-only` in the SPDX license list v3.0][1]).  Since SPDX may eventually (year?) remove support for those deprecated identifiers, we may want to warn users who try to build packages that use the deprecated identifiers.  This would require recording deprecated identifiers in a separate location.  There's some past discussion about warning for improvable license values in #1249, and with #2152's bump to the SPDX license list v3.0 the whole GPL family of identifiers have been deprecated in favor of explicit `-only` and `-or-later` forms, so there are likely quite a few packages using deprecated identifiers.

[1]: https://github.com/spdx/license-list-XML/blob/v3.0/src/GPL-3.0.xml#L11-L12

**Comment by wking** [comment]
See also spdx/license-list-XML#392 which is in flight.  If it lands, future license list releases may contain structured information about recommended upgrades.  That would allow for more specific warnings than just “`${IDENTIFIER}` is deprecated”.  If that sounds interesting, you probably want to punt on this issue until spdx/license-list-XML#392 is merged and released.

**Comment by shevegen** [comment]
I am a bit confused how licences can become deprecated.

What is the net difference between GPL-3.0 and GPL-3.0-only? What does the only suffix refer to?

On a side issue, which licences does rubygems currently consider deprecated and where could one see that information?

**Comment by wking** [comment]
> I am a bit confused how licences can become deprecated.

The licenses have not changed, but the recommended SPDX license expressions for some of them have changed.

> What is the net difference between GPL-3.0 and GPL-3.0-only?

They mean the same thing, but the SPDX licence list maintainers feel like the latter identifier is less likely to be misinterpreted.

> What does the only suffix refer to?

There are two common license grants for the GPL-3.0: one which allows only v3 (with grant text like [this][1]) and one which allows v3 or any later version (with grant text like [this][2]).  Previously, SPDX had a single license identifier (`GPL-3.0`) and you could use for either, with a bare `GPL-3.0` for the only grant and `GPL-3.0+` (using  [the `+` operator][3]) for the or-later grant.  There were concerns that folks writing or reading the bare `GPL-3.0` would forget its only-ness, so with the 3.0 license list the SPDX recommends the new, and more obvious, `GPL-3.0-only` identifier for that grant.  `GPL-3.0-only+` would be strange, so they added a new `GPL-3.0-or-later` for or-later grants.

> On a side issue, which licences does rubygems currently consider deprecated...

It would be nice to specify in the Gem docs which version of SPDX license expressions were supported and which version of the SPDX license list was supported.  But I agree that is separate from issue's runtime validation warning.

> ... and where could one see that information?

Probably in the same place as the existing "unrecognized license" warnings.  See #1249.

[1]: https://github.com/spdx/license-list-XML/blob/v3.0/src/GPL-3.0-only.xml#L14
[2]: https://github.com/spdx/license-list-XML/blob/v3.0/src/GPL-3.0-or-later.xml#L14
[3]: https://spdx.org/spdx-specification-21-web-version#h.jxpfx0ykyb60

**Comment by wking** [comment]
I don't think this was fixed by #2257.  That added exception validation, but we're still not distingishing deprecated identifiers.  Can someone with write access reopen this until we do?

**Comment by bronzdoc** [comment]
My bad @wking i reopened it

**Comment by m1kit** [comment]
I'm working on this

**Comment by 806mondo3144** [comment]
`2018``Linus Toralds`
