### ISSUE TITLE
Ruby version incompatibility message wrong for multiplatform gem

### ISSUE THREAD

**Issue by deanilvincent** [rubygems/rubygems#2156]
I'm having a problem.

My current problem is in installing sass using gem. 

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.3
```
Additional details:
```
ruby 2.5.0p0 (2017-12-25 revision 61468) [x64-mingw32]
```

Error image:

![gem](https://user-images.githubusercontent.com/10904957/35329933-898e5458-013c-11e8-9a67-ddbc8ae8b619.PNG)

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
This seems to be cause by `ffi` having different ruby version requirements for windows and `ruby`. Thanks for the bug report!

**Comment by deanilvincent** [comment]
You're welcome @segiddins. I look forward to hearing from any changes soon. :)

**Comment by segiddins** [comment]
https://github.com/rubygems/rubygems/pull/2175 should improve the version suggestion!
