### ISSUE TITLE
"gem install GEMNAME" is installing some gems that are not even dependencies of the "GEMNAME" 

### ISSUE THREAD

**Issue by rameshjanjyam** [rubygems/rubygems#2170]
My current problem is - when installing `json 1.7.7` from any directory using the command 
`gem install json -v 1.7.7` the expected `json 1.7.7` is installed. but when I run the same command from a directory which has several `.gem` files in it the command is installing some gems that are not even dependencies of `json 1.7.7`.

This issue is related to:

  - [ ] Network problems
  - [X] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
ruby -v
  ruby 2.0.0p648 (2015-12-16) [x86_64-linux]
gem -v
  1.8.25
```

the output when current directory is the `cache` folder which has several .gem files in it. 
we can see that `multi_json`, `jsonpath` are installed. these .gem are present in the current cache directory. any reason that these gems are installed?
```
[root@localhost cache]# gem install json -v 1.7.7
Successfully installed multi_json-1.13.1
Successfully installed to_regexp-0.2.1
Successfully installed jsonpath-0.8.11
3 gems installed
Installing ri documentation for multi_json-1.13.1...
Installing ri documentation for to_regexp-0.2.1...
Installing ri documentation for jsonpath-0.8.11...
Installing RDoc documentation for multi_json-1.13.1...
Installing RDoc documentation for to_regexp-0.2.1...
Installing RDoc documentation for jsonpath-0.8.11...
```

when it is from any other directory. we can see that only json 1.7.7 is installed
```
[root@localhost ~]# gem install json -v 1.7.7
Fetching: json-1.7.7.gem (100%)
Building native extensions.  This could take a while...
Successfully installed json-1.7.7
1 gem installed
Installing ri documentation for json-1.7.7...
unable to convert "\xF0" from ASCII-8BIT to UTF-8 for lib/json/ext/generator.so, skipping
unable to convert "\xF8" from ASCII-8BIT to UTF-8 for lib/json/ext/parser.so, skipping
Installing RDoc documentation for json-1.7.7...
unable to convert "\xF0" from ASCII-8BIT to UTF-8 for lib/json/ext/generator.so, skipping
unable to convert "\xF8" from ASCII-8BIT to UTF-8 for lib/json/ext/parser.so, skipping
```

please help me in understanding this. 

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by colby-swandale** [comment]
This report is for a very old version of rubygems (1.8.25), please update to the latest version.

**Comment by colby-swandale** [comment]
ping @rameshjanjyam

**Comment by rameshjanjyam** [comment]
sorry for delay. as of now we are not able to upgrade rubygems to other versions. it didn't happen in newer version I have tried.

**Comment by bronzdoc** [comment]
Thanks for the getting back @rameshjanjyam! so it seems its fixed in newer versions of rubygems, closing.
