### ISSUE TITLE
The help for `gem push` needs to be updated

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems#2183]
When running `gem help push`, the end of the help text says:

> The gem can be removed from the index (but only the index) using the yank command.  For further discussion see the help for the yank command.

This is no longer true, and the yank command now not only removes the gem from the index but also deletes it from the server. We should update the help text for `gem push` and `gem yank` to accurately describe how those commands work now.

**Comment by domcorvasce** [comment]
IMHO the `gem yank` description is pretty explainatory as it is.

As regards the `gem push` you could change it in something like:

> The gem can be removed from the index (**and the server**) using the yank command
> **but you won't be able to repush the same version again**.
>
> For further discussion see the help for the yank command.
