### ISSUE TITLE
Intermittent SSL_connect errors while installing gems

### ISSUE THREAD

**Issue by jdbsfmc** [rubygems/rubygems#2184]
My current problem is that intermittently while running bundle install or gem install we are seeing the following error:
`(Retrying download gem from https://rubygems.org/ due to error (2/4): Gem::RemoteFetcher::FetchError Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/gems/semver2-3.4.2.gem))`

Running
`$ openssl s_client -connect api.rubygems.org:443 -servername api.rubygems.org`

Intermittently gives the following:
```
CONNECTED(00000003)
write:errno=104
---
no peer certificate available
---
No client certificate CA names sent
---
SSL handshake has read 0 bytes and written 0 bytes
---
New, (NONE), Cipher is (NONE)
Secure Renegotiation IS NOT supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : 0000
    Session-ID:
    Session-ID-ctx:
    Master-Key:
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1518202708
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
---
```

Running
`$ curl https://api.rubygems.org`

Intermittently causes the following:
`curl: (35) Network file descriptor is not connected`

As stated this is all very intermittent and very strange. Any ideas on where to look further to debug this problem or knowledge of existing issues most welcome. 

This issue is related to:

  - [X] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

Here are my current environment details:

```
$ gem env version
2.7.5
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by indirect** [comment]
This is a known issue for our upstream provider, Fastly, and they request affected developers to open tickets with them: https://status.fastly.com/incidents/k3zzxnkz4vcd

**Comment by jdbsfmc** [comment]
Looks like Fastly resolved the issue over teh weekend. I'll close this issue. Thanks for the fast response as to what the issue was!!
