### ISSUE TITLE
Release plan for RubyGems 3 & 4

### ISSUE THREAD

**Issue by hsbt** [rubygems/rubygems#2191]
Original post from https://github.com/rubygems/rubygems/pull/2182#issuecomment-364631805

----

Based on all of these suggestions, I'd like to propose that we do something like this:

- [x] Update the [POLICIES](https://github.com/rubygems/rubygems/blob/master/POLICIES.rdoc) document to make it clear that in the future, RubyGems minor releases will drop support for Ruby versions without no support from ruby-core. (#2202)
  That means dropping releases of Ruby in the first minor after that Ruby version loses security support. We will re-evaluate anytime ruby-core changes their support levels or plans.
- [x] Update `master` to 3.0 right away, and drop support for Ruby 1.8, 1.9, 2.0, and 2.1
  We can release 3.0 whenever we are ready for the next release, but this means we can stop supporting old Ruby right away.
- [x] Open PRs for planned deprecations that include 1) what is being deprecated, 2) why we want to deprecate it, 3) when the deprecation will become an error, and 4) expected impact on Ruby and RubyGems users
  That provides opportunities for feedback, and a record of why the deprecation seems like a good idea.
- [x] After merging deprecations, release a 3.x version of RubyGems with the deprecation warnings
  This lets us give deprecation warnings only to users on modern versions of Ruby. 👍
- [x] Backport just the deprecation warnings to RubyGems 2.7.x, so they will be released in Ruby 2.5.x
  The backport only needs to support Ruby 2.5, not old Rubies. Releasing method deprecations in Ruby will give us the widest reach possible, so the ecosystem will be better prepared when we remove.

Some time later (we should discuss when... maybe Oct/Nov 2018?):

- [ ] Change `master` to 4.0
- [ ] Remove deprecated code
- [ ] Release 4.0
- [ ] Fix all known issues with the 4.x.x series of RubyGems
- [ ] Merge 4.x.x to ruby-trunk to be released with Ruby 2.6 in Dec 2018

I think this plan accomplishes all of the goals stated above:

- Ruby users will get a major version bump to make them notice the big Ruby version drop
- Releasing 3.0 can be easy and fast because we aren't breaking anything else
- Removing methods will include a major bump to 4.0, with many months for deprecation warnings
- @hsbt can stop supporting old rubies right away
- @duckinator will have documented policies and discussion PRs with feedback
- @matthewd will (eventually) get versions of RubyGems that drop old Ruby versions in minor releases

----

**Comment by shevegen** [comment]
**@hsbt can stop supporting old rubies right away** \o/

**Comment by duckinator** [comment]
@hsbt is the checkbox (`Update master to 3.0 [...]`) done, now?

**Comment by hsbt** [comment]
@duckinator Thanks for your reminder. I did deprecate old methods and others. We can release 3.0 now. But I have some feedback from RubyGems 3.0.0.beta1 with Ruby 2.6.0-preview1. I will fix them and improve RG 3.0 targeted 2.6.0-preview2.

**Comment by hsbt** [comment]
Now, We are working to release RubyGems 3.1 on the master branch. Afte4r that, We can bump version to 4.0.
