### ISSUE TITLE
Grammar in `deprecate` method

### ISSUE THREAD

**Issue by ShockwaveNN** [rubygems/rubygems#2221]
I'm having a problem 

English is not my native language, but message for `deprecate` method seems wrong.
Currently there is a line 
`It will be removed on or after %4d-%02d-01" % [year, month]`
Is this unknown grammar structure for me or correct way to say this phrase are
`It will be removed  after %4d-%02d-01" % [year, month]`
This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

```
$ gem env version
2.7.3
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by brondum44** [comment]
Dear Pavel. It will be removed on the set date or after is correct. Kind regards, Christian

**Comment by ShockwaveNN** [comment]
Or, ok I finally understand that `on` and `after` relate to date, not that `removed on or` looks like lost word. Sorry for you time, thanks
