### ISSUE TITLE
Dependency cycle while updating

### ISSUE THREAD

**Issue by C-Bouthoorn** [rubygems/rubygems#2226]
While updating ruby from `ruby-2.5.0p0` to `ruby-2.5.0-5` and rubygems from `2.7.3` to `2.7.6-1`, I received the following warning:

```
$ pacman -Syu
[...]
warning: dependency cycle detected:
warning: rubygems will be installed before its ruby dependency
```

I am not sure this is an issue, but maybe you could state that `ruby` has to be installed/updated before `rubygems` to resolve this warning.

### Category
  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other: updating the package

### System details
Antergos Linux, `uname -r` gives `4.15.6-1-ARCH`
Using pacman version `v5.0.2`

### Code of Conduct
- [x] I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
These messages were displayed by Antergos Linux. Please report this issue to maintainer of rubygems and ruby on Antergos Linux.
