### ISSUE TITLE
Semver warning is brittle

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#2228]
My current problem is that I continuously get this warning when I build my gem:

```
WARNING:  pessimistic dependency on rails (~> 5.1.5) may be overly strict
  if rails is semantically versioned, use:
    add_runtime_dependency 'rails', '~> 5.1', '>= 5.1.5'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
```

I see some problems with it:

* What if the dependency is not semantically versioned? I don't like unfixable warnings...
* I can trick rubygems to remove the warning with `>= 5.1.5, < 5.2`. Since that's equivalent to `~> 5.1.5`, I'd say it's a bug in the detection of when to print the warning. But maybe it's intented and it's actually the expected fix when the dependency is not semantically versioned? In that case, it should be added to the message I guess. 

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.6
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
I personally don't love the warning being there, but I agree we should decide to either remove it or suggest `>=, <` as an alternative for gems that dont adhere to semver

**Comment by duckinator** [comment]
I'd personally prefer suggesting `>=, <` in this situation, but we should get other folks' input.
