### ISSUE TITLE
Issue with adding gem source

### ISSUE THREAD

**Issue by kaesy** [rubygems/rubygems#2234]
I am unable to add any gem source. 
Getting timeout error.
`
gem source --a https://rubygems.org/

Error fetching https://rubygems.org/:
        timed out (https://api.rubygems.org/specs.4.8.gz)`

**Comment by colby-swandale** [comment]
This is not an issue with rubygems, you need to check your internet connection to `api.rubygems.org` and make sure that your have a stable connection for rubygems to download the specs list.
