### ISSUE TITLE
Owner present for missing gem

### ISSUE THREAD

**Issue by kvokka** [rubygems/rubygems#2237]
My current problem is:

I created new gem named `shrek`, checked that the name is free with
`https://rubygems.org/search?utf8=%E2%9C%93&query=shrek`
also i tried to install the gem with such name

```
$ gem install shrek
ERROR:  Could not find a valid gem 'shrek' (>= 0) in any repository
ERROR:  Possible alternatives: shred, shrew
```

so, everything shows that there is not such gem. But, when I tried to push
```
$ gem push shrek-0.1.0.gem 
Pushing gem to https://rubygems.org...
You do not have permission to push to this gem. Ask an owner to add you with: gem owner shrek --add root_p@mail.ru
$ gem owner shrek --add root_p@mail.ru 
Adding root_p@mail.ru: You do not have permission to manage this gem.
$ gem owner shrek 
Owners for gem: shrek
- mbigras22@gmail.com
```

So it looks, like it is a bug, or I missed something.
Also user with email `mbigras22@gmail.com` have GitHub account `https://github.com/mbigras` but he does not have such repo. Wired.

This issue is related to:

  - [x] Publishing a library
  - [x] The command line `gem`

Here are my current environment details:

```
$ gem env version
2.7.6
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by BanzaiMan** [comment]
https://rubygems.org/gems/shrek/versions all versions are yanked.

**Comment by kvokka** [comment]
@BanzaiMan And this is why the question is standing as a bug.
Everything shows, that there is no more such gem and all versions are dropped, but the name is still owned by the first creator.

**Comment by BanzaiMan** [comment]
While no valid version of the gem is present, the gem definitely exists. I understand that you wish this were not the case, and maybe you can have the gem ownership bestowed on you by the rubygems.org administrators (I am not one, and I don't know the policies), but this is a fact.

> Everything shows, that there is no more such gem…

As I showed above, this is simply not true.

**Comment by kvokka** [comment]
Thank you for help, I think we may close it, and I'll get in touch with previous gem owner and rubygems administration.

**Comment by mbigras** [comment]
Hi @BanzaiMan,

@kvokka got in touch with me.
I added him as a gem owner and removed myself

```
gem owner shrek --add root_p@mail.ru
Owner added successfully.
Owners for gem: shrek
- root_p@mail.ru
- mbigras22@gmail.com
gem owner shrek --remove mbigras22@gmail.com
Owner removed successfully.
Owners for gem: shrek
- root_p@mail.ru
```

It seems like as of 2015 yanking a gem [deletes it permanently](https://blog.rubygems.org/2015/04/13/permadelete-on-yank.html). So maybe this one was from before 2015.

Checking `/api/v1/gems.json` it looks like I only have 1 gem:

```
curl -s -H "Authorization:$TOKEN" https://rubygems.org/api/v1/gems.json | jq -r '.[] | .name'
greeet
```

How do I permanently delete old gems that I yanked in the past?
