### ISSUE TITLE
 ERROR: Unable to download data from https://rubygems.org/

### ISSUE THREAD

**Issue by SdotVdot** [rubygems/rubygems#2240]
I'm having a problem.

My current problem is that I can't install gems. 

Example 01:
$ sudo gem install rmate
ERROR:  Could not find a valid gem 'rmate' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - timed out (https://api.rubygems.org/specs.4.8.gz)

Example 02:
$ gem update --system
ERROR:  While executing gem ... (Gem::RemoteFetcher::UnknownHostError)
    timed out (https://api.rubygems.org/specs.4.8.gz)

Am I doing something wrong here?

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.6
```

```
$ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux-gnu]
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
```
gem install rmate
Fetching: rmate-1.5.9.gem (100%)
Successfully installed rmate-1.5.9
Parsing documentation for rmate-1.5.9
Installing ri documentation for rmate-1.5.9
Done installing documentation for rmate after 0 seconds
1 gem installed
```

This is not  a rubygems issue, probably a problem with your network

**Comment by SdotVdot** [comment]
It is weird. I could gem install in two machines using Mac OS X, with the environment detail below. But I tested  in Debian Buster and it didn't work, again with the same error. 




MAC OS X (worked):
```
$ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
```
$gem env version
2.5.2
```

Debian Buster (It didn't work.)
```
$ gem env version
2.7.6
```
$ruby -v
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-linux-gnu]
```
