### ISSUE TITLE
SSL errors

### ISSUE THREAD

**Issue by alexvilper** [rubygems/rubygems#2241]
Hello everyone,

I have been at this issue for days, and I am not really sure what else to do at this point. 
The issue I am having is related to the SSL issues a lot of people are having, but none of the solutions I have found so far have had any effect for me, except the HTTP workaround below.

I have already looked and tried solutions in the following (and others):

https://gist.github.com/luislavena/f064211759ee0f806c88
https://gist.github.com/fnichol/867550
http://guides.rubygems.org/ssl-certificate-update/#installing-using-update-packages
https://github.com/rubygems/rubygems/issues/1848
http://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html#troubleshooting-certificate-errors

The only workaround that seem to work (for successfully installing/updating gems) is changing the source to use HTTP instead of HTTPS:

```
gem sources -r https://rubygems.org/
gem sources -a http://rubygems.org/
```
However, once I do that, I can no longer add https://rubygems.org/:

```
gem sources -r http://rubygems.org
gem sources -a https://rubygems.org
```
Returns the following error:
```

C:\>gem sources -a https://rubygems.org
ERROR:  SSL verification error at depth 1: self signed certificate in certificate chain (19)
ERROR:  Root certificate is not trusted (/O=WatchGuard_Technologies/OU=Fireware/CN=Fireware HTTPS Proxy (SN 80BE02C43F9B5 2012-08-19 05:43:01 GMT) CA)
Error fetching https://rubygems.org:
        SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

```
The problem I have is that, I use Ruby for Zendesk App development, and their gem uses SSL, so applying that workaround is not really a solution for my problem. The error I get from their gem is a little different:
```
C:\>zat validate
        info  Checking for new version of zendesk_apps_tools
C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:933:in `connect'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:852:in `start'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:584:in `start'
        from C:/Ruby23-x64/lib/ruby/2.3.0/net/http.rb:479:in `get_response'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/zendesk_apps_tools-2.8.4/lib/zendesk_apps_tools/command.rb:284:in `check_for_update'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/zendesk_apps_tools-2.8.4/lib/zendesk_apps_tools/command.rb:71:in `validate'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/command.rb:27:in `run'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/invocation.rb:126:in `invoke_command'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor.rb:369:in `dispatch'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/thor-0.19.4/lib/thor/base.rb:444:in `start'
        from C:/Ruby23-x64/lib/ruby/gems/2.3.0/gems/zendesk_apps_tools-2.8.4/bin/zat:13:in `<top (required)>'
        from C:/Ruby23-x64/bin/zat:23:in `load'
        from C:/Ruby23-x64/bin/zat:23:in `<main>'
```

UPDATES:

3/20/2018 5:44PM EST

- Downgraded to Ruby2.2 (32bit) and no changes.
- Ran https://github.com/bundler/ruby-ssl-check/blob/master/check.rb, here's the result:
```
Here's your Ruby and OpenSSL environment:

Ruby:           2.2.6p396 (2016-11-15 revision 56800) [i386-mingw32]
RubyGems:       2.7.6
Bundler:        1.16.1
Compiled with:  OpenSSL 1.0.2j  26 Sep 2016
Loaded version: OpenSSL 1.0.2j  26 Sep 2016
SSL_CERT_FILE:  C:/Users/Justin/Projects/knap-build/var/knapsack/software/x86-windows/openssl/1.0.2j/ssl/cert.pem
SSL_CERT_DIR:   C:/Users/Justin/Projects/knap-build/var/knapsack/software/x86-windows/openssl/1.0.2j/ssl/certs

With that out of the way, let's see if you can connect to rubygems.org...

Bundler connection to rubygems.org:       failed  ?  (certificate verification)
ERROR:  SSL verification error at depth 1: self signed certificate in certificate chain (19)
ERROR:  Root certificate is not trusted (/O=WatchGuard_Technologies/OU=Fireware/CN=Fireware HTTPS Proxy (SN 80BE02C43F9B5 2012-08-19 05:43:01 GMT) CA)
RubyGems connection to rubygems.org:      failed  ?  (certificate verification)
Ruby net/http connection to rubygems.org: failed  ?

Unfortunately, this Ruby can't connect to rubygems.org. ??
Your Ruby can't connect to rubygems.org because you are missing the certificate files OpenSSL needs to verify you are connecting to the genuine rubygems.org servers.

```

Any help would be greatly appreciated!

This issue is related to:

  - [X ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

Windows 10 64bit

```
C:\>gem env version
2.7.6

C:\>ruby -v
ruby 2.3.3p222 (2016-11-21 revision 56859) [x64-mingw32]

C:\>ruby -ropenssl -e 'p OpenSSL::OPENSSL_VERSION'
"OpenSSL 1.0.2j  26 Sep 2016"

```
I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by colby-swandale** [comment]
You seem to have a proxy server that is intercepting your traffic with a certificate that is not known to Ruby:

```
Root certificate is not trusted (/O=WatchGuard_Technologies/OU=Fireware/CN=Fireware HTTPS Proxy (SN 80BE02C43F9B5 2012-08-19 05:43:01 GMT) CA)
```

I suggest walking through the [Bundler/RubyGems SSL Guide](http://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html#installing-new-os-certificates) to install the CA certificate that your proxy server is using so that it's available to RubyGems.

**Comment by bronzdoc** [comment]
I'm going to close this since is a problem with the certificate you are generating rather than rubygems itself
