### ISSUE TITLE
Error Installaing Azure Ruby SDK Gem 

### ISSUE THREAD

**Issue by sarangan12** [rubygems/rubygems#2245]
I'm having a problem with ```gem install``` command.

My current problem is:

I have 2 gems [azure_sdk](https://rubygems.org/gems/azure_sdk) which depends on several gems. One of them is [azure_mgmt_api_management](https://rubygems.org/gems/azure_mgmt_api_management). When I try the following command:

```
$gem install azure_sdk 
ERROR:  Error installing azure_sdk:
	azure_sdk requires azure_mgmt_api_management (~> 0.16.0)
```

Now, my original thought was may be there is a problem with the azure_mgmt_api_management gem itself. But, when I tried the following commands, there were no issues:

```
$ gem fetch azure_sdk
Fetching: azure_sdk-0.16.3.gem (100%)
Downloaded azure_sdk-0.16.3

$ gem install ./azure_sdk-0.16.3.gem 
Fetching: azure_mgmt_api_management-0.16.1.gem (100%)
Successfully installed azure_mgmt_api_management-0.16.1
Successfully installed azure_sdk-0.16.3
Parsing documentation for azure_mgmt_api_management-0.16.1
Installing ri documentation for azure_mgmt_api_management-0.16.1
Parsing documentation for azure_sdk-0.16.3
Installing ri documentation for azure_sdk-0.16.3
Done installing documentation for azure_mgmt_api_management, azure_sdk after 29 seconds
2 gems installed
```

Now, when I uninstall both the gems (azure_sdk and azure_mgmt_api_management) and try ```gem install azure_sdk``` again, it fails. 

Also, as an additional information, I tried the following command:

```
$ gem install azure_sdk --explain | grep azure_mgmt_a
  azure_mgmt_analysis_services-0.16.0
  azure_mgmt_authorization-0.16.0
  azure_mgmt_automation-0.16.0
```
It should be listing azure_mgmt_api_management. But, it is not listing. 

But, when I try the following commands, the listing is fine:

```
$ gem fetch azure_sdk
Fetching: azure_sdk-0.16.3.gem (100%)
Downloaded azure_sdk-0.16.3

$ gem install ./azure_sdk-0.16.3.gem --explain | grep azure_mgmt_a
  azure_mgmt_automation-0.16.0
  azure_mgmt_authorization-0.16.0
  azure_mgmt_api_management-0.16.1 <<<<<<<<<<<<<
  azure_mgmt_analysis_services-0.16.0
```

Since, the gem file itself does not have any issues, I guess there might be some problem with rubygems servers (may be a caching issue???) So, I am creating this issue. Can someone take a look at it?

This issue is related to:

  - [ ] Network problems
  - [X] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.6
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by sarangan12** [comment]
Additional Info:

```
$ gem install azure_sdk  --debug
NOTE:  Debugging mode prints all exceptions even when rescued
Exception `LoadError' at /Users/saranganrajamanickam/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/resolv.rb:171 - LoadError
Exception `Resolv::DNS::Config::NXDomain' at /Users/saranganrajamanickam/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/resolv.rb:549 - _rubygems._tcp.api.rubygems.org
Exception `Resolv::DNS::Config::NXDomain' at /Users/saranganrajamanickam/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/resolv.rb:549 - _rubygems._tcp.api.rubygems.org.local
Exception `Resolv::ResolvError' at /Users/saranganrajamanickam/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/resolv.rb:494 - DNS result has no information for _rubygems._tcp.api.rubygems.org
Exception `Errno::EEXIST' at /Users/saranganrajamanickam/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/fileutils.rb:253 - File exists @ dir_s_mkdir - /Users/saranganrajamanickam/.rvm/gems/ruby-2.3.1
Exception `Gem::InstallError' at /Users/saranganrajamanickam/.rvm/rubies/ruby-2.3.1/lib/ruby/site_ruby/2.3.0/rubygems/installer.rb:386 - azure_sdk requires azure_mgmt_api_management (~> 0.16.0)
ERROR:  Error installing azure_sdk:
	azure_sdk requires azure_mgmt_api_management (~> 0.16.0)
```

**Comment by sarangan12** [comment]
Additional Info:

When I tried using the bundle install with the following ```Gemfile```: 

```
source 'https://rubygems.org'

gem 'azure_sdk'
```

I get the following error:

```
$ bundle install
...........
...........
Using azure_mgmt_storage 0.16.0
Using azure_mgmt_stream_analytics 0.16.0
Using azure_mgmt_subscriptions 0.16.0
Using azure_mgmt_traffic_manager 0.16.0
Using azure_mgmt_web 0.16.0
Fetching azure_sdk 0.16.3
Downloading azure_sdk-0.16.3 revealed dependencies not in the API or the lockfile (azure_mgmt_api_management (~> 0.16.0)).
Either installing with `--full-index` or running `bundle update azure_sdk` should fix the problem.

In Gemfile:
  azure_sdk
```

**Comment by sarangan12** [comment]
I am able reproduce the error in several machines and several versions of ruby. This is impacting several customers. Could someone please help me with this issue?

**Comment by bronzdoc** [comment]
Oh sorry that's probably not the answer you are looking for... it s a quick fix though since it worked for me, i'll investigate more after work.

**Comment by sarangan12** [comment]
@bronzdoc :-) Yes. The quick fix is fine. But, in automated customer impacting systems, the quick fix is not possible. I am trying to find the root cause. Appreciate the help....

**Comment by bronzdoc** [comment]
@sarangan12 i just tried `gem install azure_sdk` again and it worked, can you try to install again the gem please and confirm you can install it, thanks

Might have been a cache issue as you said, but it something illhave to check with the rubygems.org team

**Comment by segiddins** [comment]
This is happening because `https://api.rubygems.org/api/v1/dependencies.json?gems=azure_sdk` does not include `azure_mgmt_api_management` as a dependency, so I think this is looking like a `rubygems.org` issue, sorry

**Comment by sarangan12** [comment]
@bronzdoc @segiddins This issue has not been resolved. I am still getting the same issue. As mentioned by @segiddins, The https://api.rubygems.org/api/v1/dependencies.json?gems=azure_sdk does not include azure_mgmt_api_management as a dependency. Any idea how this rubygems issue could be fixed?

**Comment by sarangan12** [comment]
I released another version of azure_sdk today which actually resolved the older issue also. Closing this issue as its automatically resolved.
