### ISSUE TITLE
Cannot update AWS gems, getting Gem::RemoteFetcher::UnknownHostError 

### ISSUE THREAD

**Issue by alienlifeform** [rubygems/rubygems#2246]
I'm having a problem

My current problem is 

  I can't bundle install because rubygems is timing out on all aws requests (haven't got past them, so not sure if it is only aws)

This issue is related to:

  - [ ] Network problems
  - [X] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.14
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by alienlifeform** [comment]
Getting these for every aws-sdk related gem that has an update:

Retrying download gem from http://rubygems.org/ due to error (2/4): Gem::RemoteFetcher::UnknownHostError timed out (http://rubygems.org/gems/aws-partitions-1.72.0.gem)

**Comment by alienlifeform** [comment]
I saw on the internet that perhaps a `gem update --system` could help.

$ gem update --system
ERROR:  While executing gem ... (Gem::RemoteFetcher::UnknownHostError)
    timed out (http://api.rubygems.org/specs.4.8.gz)

**Comment by bronzdoc** [comment]
@alienlifeform can you share your `Gemfile` ?

**Comment by bronzdoc** [comment]
This is probably due a connection problem, will reopen if you still experimenting this

**Comment by mfriedman1** [comment]
This is still a problem. I'm trying to update a project called bigBlueButton and it's not able to update a bunch of Gems (fastimage, curb, mini_portile2)

**Comment by bobweston** [comment]
same problem

**Comment by jasonadkison** [comment]
Same today

**Comment by djberg96** [comment]
Transient DNS issue? What happens if you run with `--verbose`?

I did notice this, but it ultimately was successful:

```
>gem install curb --verbose
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=curb
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
GET https://api.rubygems.org/quick/Marshal.4.8/curb-0.9.6.gemspec.rz
200 OK
Downloading gem curb-0.9.6.gem
GET https://api.rubygems.org/gems/curb-0.9.6.gem
Fetching: curb-0.9.6.gem (100%)
200 OK
```

**Comment by szprutamich** [comment]
The same problem yesterday and today for two different stacks, different OS (Ubuntu 18.04 and 16.04), different locations (us-west-1 and eu-west-1). Part of the log:
```
[2020-03-12T16:49:42+00:00] ERROR: Running exception handlers
[2020-03-12T16:49:42+00:00] ERROR: Exception handlers complete
[2020-03-12T16:49:42+00:00] FATAL: Stacktrace dumped to /var/chef/runs/42f617c7-1ce7-44a2-a49f-d6e5ddd810b8/local-mode-cache/cache/chef-stacktrace.out
[2020-03-12T16:49:42+00:00] FATAL: Please provide the contents of the stacktrace.out file if you file a bug report
[2020-03-12T16:49:42+00:00] ERROR: Command timed out after 600s:
Command exceeded allowed execution time, process terminated
---- Begin output of bundle install ----
STDOUT: Don't run Bundler as root. Bundler can ask for sudo if it is needed, and
installing your bundle as root will break this application for all non-root
users on this machine.
Fetching gem metadata from https://rubygems.org/.............
Fetching version metadata from https://rubygems.org/..
Resolving dependencies.............................................................................................................................................................................................................................
Installing aws-eventstream 1.0.3
Installing aws-partitions 1.281.0
Installing jmespath 1.4.0
Installing aws-sigv2 1.0.1
Using bundler 1.12.5
Installing aws-sigv4 1.1.1
Installing aws-sdk-core 3.91.0
Installing aws-sdk-accessanalyzer 1.3.0
Installing aws-sdk-acm 1.28.0
 
Gem::RemoteFetcher::UnknownHostError: timed out (https://rubygems.org/gems/aws-sdk-acmpca-1.22.0.gem)
Installing aws-sdk-alexaforbusiness 1.34.0
Installing aws-sdk-amplify 1.14.0
Installing aws-sdk-apigateway 1.37.0
Installing aws-sdk-apigatewaymanagementapi 1.12.0
 
Gem::RemoteFetcher::UnknownHostError: timed out (https://rubygems.org/gems/aws-sdk-apigatewayv2-1.16.0.gem)
Installing aws-sdk-appconfig 1.1.0
 
Gem::RemoteFetcher::UnknownHostError: timed out (https://rubygems.org/gems/aws-sdk-applicationautoscaling-1.35.0.gem)
```

**Comment by hakanai** [comment]
I get similar issues. The network seems to be randomly dropping packets, and gem doesn't seem to retry fetch operations. Maybe there's a way to tell it to retry, but I haven't found it yet.
