### ISSUE TITLE
One failing test on osx when running make-test all on ruby trunk

### ISSUE THREAD

**Issue by benoittgt** [rubygems/rubygems#2251]
I'm having a problem.

My current problem is I have a failing test on rubygems on ruby trunk. Test seems to fail since they were introduced between v2_2_9 and v2_3_0. 

I have no issue when I run `rake test` on rubygems repo. 

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

Osx: 10.13.2

To reproduce the behavior. On a mac run in ruby trunk folder:
`make test-all TESTS='rubygems/test_require.rb'`

```
Run options: "--ruby=./miniruby -I../ruby/lib -I. -I.ext/common  ../ruby/tool/runruby.rb --extout=.ext  -- --disable-gems" --excludes-dir=../ruby/test/excludes --name=!/memory_leak/

# Running tests:

[ 2/21] TestGemRequire#test_dash_i_beats_gems = 0.05 s
  1) Error:
TestGemRequire#test_dash_i_beats_gems:
NameError: uninitialized constant HELLO
    /Users/bti/code/ruby/test/rubygems/test_require.rb:65:in `test_dash_i_beats_gems'

Finished tests in 0.656300s, 31.9976 tests/s, 135.6087 assertions/s.
21 tests, 89 assertions, 0 failures, 1 errors, 1 skips
```

I dig into the test but it's was unclear for me. I will try -this night- to find the difference between trunk and RubyGems repo.

See also: https://bugs.ruby-lang.org/issues/14626?next_issue_id=14625

**Comment by hsbt** [comment]
@benoittgt Thank you for your report. But test suite of the ruby core is out of the scope of rubygems repository.

**Comment by hsbt** [comment]
If you can reproduce in rubygems/rubygems standalone repository. Please re-open this. Thank you.

**Comment by benoittgt** [comment]
Thanks for your answer @hsbt
