### ISSUE TITLE
Problem Retrieving Gems

### ISSUE THREAD

**Issue by mbrecken76** [rubygems/rubygems#2256]
I'm having a problem or would like to suggest a feature.

My current problem is, after installing (Ruby 2.5.0, OS: Windows 10), I attempt to install or fetch a gem and I receive the following error:

"ERROR:  Could not find a valid gem 'rubocop' (>= 0), here is why:
          Unable to download data from https://rubygems.org - SSL_connect returned=1 errno=0 state=SSLv3/TLS write client hello: tlsv1 alert access denied (https://api.rubygems.org/latest_specs.4.8.gz)"

This is not the same as the "read server certificate B: certificate verify failed" error, as I have verified that my certs are current and valid. I've run the check.rb script and receive the following:

"Here's your Ruby and OpenSSL environment:

Ruby:           2.5.0p0 (2017-12-25 revision 61468) [x64-mingw32]
RubyGems:       2.7.6
Bundler:        1.16.1
Compiled with:  OpenSSL 1.1.0g  2 Nov 2017
Loaded version: OpenSSL 1.1.0g  2 Nov 2017
SSL_CERT_FILE:  C:/Ruby25-x64/ssl/cert.pem
SSL_CERT_DIR:   C:/Ruby25-x64/ssl/certs

With that out of the way, let's see if you can connect to rubygems.org...

Bundler connection to rubygems.org:       failed  ❌  (SSL_connect returned=1 errno=0 state=SSLv3/TLS write client hello: tlsv1 alert access denied)
RubyGems connection to rubygems.org:      failed  ❌  (SSL_connect returned=1 errno=0 state=SSLv3/TLS write client hello: tlsv1 alert access denied (https://rubygems.org))
Ruby net/http connection to rubygems.org: failed  ❌

Unfortunately, this Ruby can't connect to rubygems.org. 😡
Even worse, we're not sure why. 😕

Here's the full error information:
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=SSLv3/TLS write client hello: tlsv1 alert access denied
  C:/Ruby25-x64/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock'
  C:/Ruby25-x64/lib/ruby/2.5.0/net/protocol.rb:44:in `ssl_socket_connect'
  C:/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:981:in `connect'
  C:/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
  C:/Ruby25-x64/lib/ruby/2.5.0/net/http.rb:915:in `start'
  check1.rb:88:in `<main>'

You might have more luck using Mislav's SSL doctor.rb script. You can get it here:
https://github.com/mislav/ssl-tools/blob/8b3dec4/doctor.rb
Read more about the script and how to use it in this blog post:
https://mislav.net/2013/07/ruby-openssl/"

If I run Mislav's SSL doctor.rb script I get the following:

"C:/Ruby25-x64/bin/ruby (2.5.0-p0)
OpenSSL 1.1.0g  2 Nov 2017: C:/Ruby25-x64/ssl
SSL_CERT_DIR=""
SSL_CERT_FILE=""

HEAD https://status.github.com:443
#<Net::HTTPGatewayTimeOut 504 GATEWAY_TIMEOUT readbody=true>"

I've tried every suggestion available and nothing seems to work.

This issue is related to:

  - [x] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.6
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by mbrecken76** [comment]
I did more troubleshooting and found out is is my company's network causing the issue. I will now close this report.

**Comment by WedgeSparda** [comment]
@mbrecken76 I'm facing the same problem. What did your ISP do to fix the issue?
