### ISSUE TITLE
invalid byte sequence in UTF-8 - suggestion to show more details

### ISSUE THREAD

**Issue by shevegen** [rubygems/rubygems#2258]
- [x] The command line `gem`

gem version: 2.7.6

---

I have a problem building one of my project's gem (for the project studium).

In the past I used to have this problem related to german umlauts ("Umlaute").

However had, right now, I do not know where the error is. I think it is not
related to german umlauts but now related to UTF-8. I should add that I do
not use UTF-8 for the gem; I use ISO-8859-1 and this works very well.
Only gem has a problem - but also only sometimes. So I am confused.

The current gem output is totally useless to me:

---

```
WARNING:  open-ended dependency on cliner (>= 0) is not recommended
  if cliner is semantically versioned, use:
    add_runtime_dependency 'cliner', '~> 0'
WARNING:  open-ended dependency on colour_e (>= 0) is not recommended
  if colour_e is semantically versioned, use:
    add_runtime_dependency 'colour_e', '~> 0'
WARNING:  open-ended dependency on esystem (>= 0) is not recommended
  if esystem is semantically versioned, use:
    add_runtime_dependency 'esystem', '~> 0'
WARNING:  open-ended dependency on find_line_in_file (>= 0) is not recommended
  if find_line_in_file is semantically versioned, use:
    add_runtime_dependency 'find_line_in_file', '~> 0'
WARNING:  open-ended dependency on ftp_paradise (>= 0) is not recommended
  if ftp_paradise is semantically versioned, use:
    add_runtime_dependency 'ftp_paradise', '~> 0'
WARNING:  open-ended dependency on gruff (>= 0) is not recommended
  if gruff is semantically versioned, use:
    add_runtime_dependency 'gruff', '~> 0'
WARNING:  open-ended dependency on html_tags (>= 0) is not recommended
  if html_tags is semantically versioned, use:
    add_runtime_dependency 'html_tags', '~> 0'
WARNING:  open-ended dependency on opn (>= 0) is not recommended
  if opn is semantically versioned, use:
    add_runtime_dependency 'opn', '~> 0'
WARNING:  open-ended dependency on prawn (>= 0) is not recommended
  if prawn is semantically versioned, use:
    add_runtime_dependency 'prawn', '~> 0'
WARNING:  open-ended dependency on save_file (>= 0) is not recommended
  if save_file is semantically versioned, use:
    add_runtime_dependency 'save_file', '~> 0'
WARNING:  open-ended dependency on try_syck (>= 0) is not recommended
  if try_syck is semantically versioned, use:
    add_runtime_dependency 'try_syck', '~> 0'
WARNING:  open-ended dependency on web_images (>= 0) is not recommended
  if web_images is semantically versioned, use:
    add_runtime_dependency 'web_images', '~> 0'
WARNING:  open-ended dependency on xorg_buffer (>= 0) is not recommended
  if xorg_buffer is semantically versioned, use:
    add_runtime_dependency 'xorg_buffer', '~> 0'
WARNING:  open-ended dependency on verbose_truth (>= 0) is not recommended
  if verbose_truth is semantically versioned, use:
    add_runtime_dependency 'verbose_truth', '~> 0'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
ERROR:  While executing gem ... (ArgumentError)
    invalid byte sequence in UTF-8
gem push *.gem
ERROR:  While executing gem ... (Gem::Package::FormatError)
    package metadata is missing in studium-0.4.58.gem
```

---

The above does not tell me much. Ok so there is an ArgumentError... and it
says there is an invalid byte sequence in UTF-8.

Then the gem push does not like it due to some Package::FormatError.

My request is this:

**- Would it be possible to show more information when the above ERROR happens?**

In particular what I think may be most helpful is in which file(s) the problem happened.

That way I can easily check what changed. (May be my fault for not using git here
but it's just a problem that I got from gem and gem could, I hope, easily show the
precise error).

Showing the affected files would help a LOT. It may also be helpful to have some 
documentation as to where or how the error arises ... but showing the affected files
is more important I think.

Anyway, thank you for reading.

**Comment by duckinator** [comment]
So, what I _suspect_ is happening is that there's a ISO-8859-1 character somewhere, but `gem` thinks it's unicode.

I'll see if I can make a test case for it. If I can get a test case, I'll see what I can do in terms of improving the error.

**Comment by duckinator** [comment]
As an aside, this looks like [the exact same problem you reported back in May 2017](https://github.com/rubygems/rubygems/issues/1929).

**Comment by duckinator** [comment]
Err, looks like you're running into the same problem, rather. (Or at least a very closely related one.)

**Comment by duckinator** [comment]
As an aside, it looks like you're encountering a similar thing to what you reported [in May 2017](https://github.com/rubygems/rubygems/issues/1929).

**Comment by bronzdoc** [comment]
ping @shevegen

**Comment by duckinator** [comment]
@shevegen could you please try passing `--backtrace` when building it and let me know if that gives you more useful output?

**Comment by bronzdoc** [comment]
Closing for lack of response, would reopen if you provide what @duckinator suggested
