### ISSUE TITLE
Error when trying to install or list remote gems

### ISSUE THREAD

**Issue by tllucero** [rubygems/rubygems#2262]
I'm having a problem or would like to suggest a feature.

My current problem is I cannot install or list any remote gem. This problem persists in any version of ruby/rubygems. Everything else in ruby and my computer works fine.

Examples:
$gem install rubyfann-1.2.6
ERROR:  Could not find a valid gem 'rubyfann-1.2.6' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - timed out (https://api.rubygems.org/specs.4.8.gz)

$gem list -r ^rails
*** REMOTE GEMS ***
midas@wdc42:~$

```

This issue is related to:

  - [x ] Network problems
  - [x ] Installing a library
  - [ ] Publishing a library
  - [x ] The command line `gem`

```

Here are my current environment details:
$ gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.6
  - RUBY VERSION: 2.5.1 (2018-03-29 patchlevel 57) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/midas/.gem/ruby/2.5.1
  - USER INSTALLATION DIRECTORY: /home/midas/.gem/ruby/2.5.0
  - RUBY EXECUTABLE: /usr/local/rubies/2.5.1/bin/ruby
  - EXECUTABLE DIRECTORY: /home/midas/.gem/ruby/2.5.1/bin
  - SPEC CACHE DIRECTORY: /home/midas/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/rubies/2.5.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/midas/.gem/ruby/2.5.1
     - /usr/local/rubies/2.5.1/lib/ruby/gems/2.5.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://rubygems.org/"]
     - "benchmark" => false
     - "gem" => "--no-rdoc --no-ri"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/midas/commands
     - /home/midas/.gem/ruby/2.5.1/bin
     - /usr/local/rubies/2.5.1/lib/ruby/gems/2.5.0/bin
     - /usr/local/rubies/2.5.1/bin
     - /home/midas/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin

```

$ gem env version
2.7.6

$ chruby 2.3.1
$ gem env version
2.5.1
~$ gem list -r ^ra

*** REMOTE GEMS ***

```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Hi @tllucero is this sitll an issue for you? it looks like a network problem on the host

**Comment by tllucero** [comment]
Problem went away over the weekend. When I had the problem, tracert indicated I was never getting to the host of rubygems.org, so, yeah, network problem.
