### ISSUE TITLE
Could not install ruby gem file from github repository

### ISSUE THREAD

**Issue by ulutasalkan** [rubygems/rubygems#2263]
Hello everyone.
I uploaded a sample gemfile to my repository and try to install it by using code which is below:

Repository: https://github.com/ulutasalkan/test-gem

my first try is : gem install test-gem --source https://github.com/ulutasalkan/test-gem.git
second one:  bundle config source https://github.com/ulutasalkan/test-gem
then gem install basicMath-0.0.3

But i got below error:
ERROR:  Could not find a valid gem 'basicMath-0.0.3' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - Errno::ETIMEDOUT:                                                                                                               A connection attempt failed because the connected party did not properly respon                                                                                                              d after a period of time, or established connection failed because connected hos                                                                                                              t has failed to respond. - connect(2) for "api.rubygems.org" port 443 (https://a                                                                                                              pi.rubygems.org/specs.4.8.gz)

Thanks a lot.

**Comment by duckinator** [comment]
hi!

so, to my knowledge you can't install things directly from git like that &mdash; `gem install` has no `--source` option, and I can find no documentation for `bundle config source` so I don't know what it does.

I tested my usual approach for this, though, and it works:

1. In that repository, create a file named `Rakefile`, with the contents `require "bundler/gem_tasks"`
2. Do a git commit + push.
3. You can now use the usual Rake-based workflow:
   - `rake build` to build the gem
   - `rake install` to build + install locally.
   - `rake release` to build + release it.
