### ISSUE TITLE
Ruby does not installed SSL/ Cyberroam certificate error

### ISSUE THREAD

**Issue by ruchitaghodasara** [rubygems/rubygems#2270]
When i am trying to install gem it shows below error please help me for this 

gem install rails
ERROR:  SSL verification error at depth 1: self signed certificate in certificate chain (19)
ERROR:  Root certificate is not trusted (/C=IN/ST=Gujarat/L=Ahmedabad/O=Cyberoam/OU=Cyberoam Certificate Authority/CN=Cyberoam SSL CA_C43316094187/emailAddress=support@cyberoam.com)
ERROR:  SSL verification error at depth 1: self signed certificate in certificate chain (19)
ERROR:  Root certificate is not trusted (/C=IN/ST=Gujarat/L=Ahmedabad/O=Cyberoam/OU=Cyberoam Certificate Authority/CN=Cyberoam SSL CA_C43316094187/emailAddress=support@cyberoam.com)
ERROR:  SSL verification error at depth 1: self signed certificate in certificate chain (19)
ERROR:  Root certificate is not trusted (/C=IN/ST=Gujarat/L=Ahmedabad/O=Cyberoam/OU=Cyberoam Certificate Authority/CN=Cyberoam SSL CA_C43316094187/emailAddress=support@cyberoam.com)
ERROR:  Could not find a valid gem 'rails' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain) (https://api.rubygems.org/specs.4.8.gz)
ERROR:  SSL verification error at depth 1: self signed certificate in certificate chain (19)
ERROR:  Root certificate is not trusted (/C=IN/ST=Gujarat/L=Ahmedabad/O=Cyberoam/OU=Cyberoam Certificate Authority/CN=Cyberoam SSL CA_C43316094187/emailAddress=support@cyberoam.com)
ERROR:  SSL verification error at depth 1: self signed certificate in certificate chain (19)
ERROR:  Root certificate is not trusted (/C=IN/ST=Gujarat/L=Ahmedabad/O=Cyberoam/OU=Cyberoam Certificate Authority/CN=Cyberoam SSL CA_C43316094187/emailAddress=support@cyberoam.com)

**Comment by bronzdoc** [comment]
I'm going to close this since is a problem with the certificate you are generating rather than rubygems itself

you can check http://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html#installing-new-os-certificates to troubleshoot your issue
