### ISSUE TITLE
how to fix

### ISSUE THREAD

**Issue by abbadilah** [rubygems/rubygems#2272]
I'm having a problem or would like to suggest a feature.

My current problem is _________
C:\Users\abbadilah>gem install rails
Temporarily enhancing PATH for MSYS/MINGW...
Building native extensions. This could take a while...
ERROR:  Error installing rails:
        ERROR: Failed to build gem native extension.

    current directory: C:/Ruby25/lib/ruby/gems/2.5.0/gems/nio4r-2.3.0/ext/nio4r
C:/Ruby25/bin/ruby.exe -r ./siteconf20180422-6436-111ahl3.rb extconf.rb

current directory: C:/Ruby25/lib/ruby/gems/2.5.0/gems/nio4r-2.3.0/ext/nio4r
make "DESTDIR=" clean
'make' is not recognized as an internal or external command,
operable program or batch file.

current directory: C:/Ruby25/lib/ruby/gems/2.5.0/gems/nio4r-2.3.0/ext/nio4r
make "DESTDIR="
'make' is not recognized as an internal or external command,
operable program or batch file.

make failed, exit code 1

Gem files will remain installed in C:/Ruby25/lib/ruby/gems/2.5.0/gems/nio4r-2.3.
0 for inspection.
Results logged to C:/Ruby25/lib/ruby/gems/2.5.0/extensions/x86-mingw32/2.5.0/nio
4r-2.3.0/gem_make.out

This issue is related to:

  - [ ] Network problems
  - [v ] Installing a library
  - [v ] Publishing a library
  - [v ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
PASTE HERE
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
Duplicates https://github.com/rubygems/rubygems/issues/2168
