### ISSUE TITLE
Updating user installed gems on macOS

### ISSUE THREAD

**Issue by dsoreilly** [rubygems/rubygems#2273]
I'm having a problem or would like to suggest a feature.

I've been installing additional Ruby Gems on macOS (10.13.2) using the `gem install GEMNAME --user-install` command. In order to use them, I've created a **.bash_profile** and added the following line to it:

`export PATH=$PATH:~/.gem/ruby/2.3.0/bin`

The issue arises when I then try to update these Gems. I can update them all individually by specifying the name, but running `gem update` causes a file permission error due to the command trying to also update the system Gems.

Likewise, when I use the command `gem update --user-install`, this tries to install the latest versions all of the local Gems into the user directory, which seems like bad practice.

Essentially, I'm looking for a way to run `gem update` and only target the Gems currently in the **/Users/USERNAME/.gem/ruby/2.3.0** directory.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
Ruby RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2
  - RUBY VERSION: 2.3.3 (2016-11-21 patchlevel 222) [universal.x86_64-darwin17]
  - INSTALLATION DIRECTORY: /Library/Ruby/Gems/2.3.0
  - USER INSTALLATION DIRECTORY: /Users/USERNAME/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /Users/USERNAME/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Library/Ruby/Site
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-darwin-17
  - GEM PATHS:
    - /Library/Ruby/Gems/2.3.0
    - /Users/USERNAME/.gem/ruby/2.3.0
    - /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0
  - GEM CONFIGURATION:
    - :update_sources => true
    - :verbose => true
    - :backtrace => false
    - :bulk_threshold => 1000
  - REMOTE SOURCES:
    - https://rubygems.org/
  - SHELL PATH:
    - /usr/local/bin
    - /usr/bin
    - /bin
    - /usr/sbin
    - /sbin
    - /Users/USERNAME/.gem/ruby/2.3.0/bin
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by duckinator** [comment]
hi!

Could you try adding the following to `~/.gemrc`, and letting me know if it works?:

```
gem: --user-install
```

(If you already have a `~/.gemrc`, just add `--user-install` to the end of the `gem:` line.)

**Comment by bronzdoc** [comment]
@dsoreilly can you provide feedback with what @duckinator suggetsed? thanks

**Comment by dsoreilly** [comment]
Apologies for the delay in trying this. I've just created a **.gemrc** file in my home directory and added the `gem: --user-install` line, unfortunaltey this hasn't produced the desired effect—all the system gems still get installed into the **~/.gem/ruby/2.3.0/gems** directory.

**Comment by ecnelises** [comment]
I don't have the problem on macOS 10.13.5 with both Ruby 2.3.5 and 2.4.2. (RubyGems version 2.6.10) Maybe you can update RubyGems version?

**Comment by bronzdoc** [comment]
```
gem: --user-install
```
isn't working for me neither :thinking:

**Comment by MSP-Greg** [comment]
Having used `-user-install` quite a bit (on Windows), there are certainly quirks.

Maybe add additional options like:

```
gem update --only-gem-dir    => only gems installed in Gem.dir or --no-user-install
gem update --only-user-dir   => only gems installed with --user-install
gem update --only-default    => only default (std-lib) gems
```

I believe this would cover all gems, question as to what a simple `gem update` would do...

Greg

**Comment by MSP-Greg** [comment]
@dsoreilly

I believe something like the following is what I have in my .gemrc file (add other options as desired):

```
install: "--user-install"
update: "--user-install"
```
Greg

**Comment by bronzdoc** [comment]
@dsoreilly  is this still an issue for you? could you try with:
```yaml
:gem: --user-install
```

**Comment by bronzdoc** [comment]
closing due lack of response
