### ISSUE TITLE
Problems installing or updating gems with windows 10

### ISSUE THREAD

**Issue by Rubemlrm** [rubygems/rubygems#2274]
I'm having a problem or would like to suggest a feature.

My current problem is related to the install and update of gems, in the past few weeks everytime i try to install or an update for some gem i get problems with SSL_Certs or a message saying too many connection resets. I've tested this with 2 laptops in 2 diferent networks. I'm running windows 10 64bits and i've installed ruby with rubyInstaller for windows.

This issue is related to:

  - [x] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.6
$ ruby -v
ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]
```

Besides the info added above, i've runned the test 
```ruby -ropen-uri -e 'eval open("https://git.io/vQhWq").read' ```
That outputs the following info

```
Here's your Ruby and OpenSSL environment:

Ruby:           2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]
RubyGems:       2.7.6
Bundler:        1.16.1
Compiled with:  OpenSSL 1.0.2o  27 Mar 2018
Loaded version: OpenSSL 1.0.2o  27 Mar 2018
SSL_CERT_FILE:  C:/Ruby24-x64/ssl/cert.pem
SSL_CERT_DIR:   C:/Ruby24-x64/ssl/certs

With that out of the way, let's see if you can connect to rubygems.org...

Bundler connection to rubygems.org:       failed  ❌  (An existing connection was forcibly closed by the remote host. - SSL_connect)
RubyGems connection to rubygems.org:      failed  ❌  (Errno::ECONNRESET: An existing connection was forcibly closed by the remote host. - SSL_connect (https://rubygems.org))
Ruby net/http connection to rubygems.org: failed  ❌

Unfortunately, this Ruby can't connect to rubygems.org. 😡
Even worse, we're not sure why. 😕

Here's the full error information:
Errno::ECONNRESET: An existing connection was forcibly closed by the remote host. - SSL_connect
  C:/Ruby24-x64/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock'
  C:/Ruby24-x64/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_connect'
  C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:948:in `connect'
  C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
  C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:882:in `start'
  (eval):88:in `<main>'
  -e:1:in `eval'
  -e:1:in `<main>'

You might have more luck using Mislav's SSL doctor.rb script. You can get it here:
https://github.com/mislav/ssl-tools/blob/8b3dec4/doctor.rb
Read more about the script and how to use it in this blog post:
https://mislav.net/2013/07/ruby-openssl/
```

After that i've runned the doctor.rb script that give me the following output:

```
C:/Ruby24-x64/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock': An existing connection was forcibly closed by the remote host. - SSL_connect (Errno::ECONNRESET)
        from C:/Ruby24-x64/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_connect'
        from C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:948:in `connect'
        from C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
        from C:/Ruby24-x64/lib/ruby/2.4.0/net/http.rb:876:in `start'
        from doctor.rb:60:in `<main>'
C:/Ruby24-x64/bin/ruby (2.4.4-p296)
OpenSSL 1.0.2o  27 Mar 2018: C:/Ruby24-x64/ssl
SSL_CERT_DIR=""
SSL_CERT_FILE=""

HEAD https://rubygems.org:443
```

Last i've tried to add new sources to gemrc so i can check if is a problem with api.rubygems,org or not, and got the same problems. I don't have any proxy config and the firewall that i'm using its the native one from windows.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by djberg96** [comment]
What is the full output of `gem env`? Are you using a proxy? Is the `http_proxy` environment variable set?

**Comment by Rubemlrm** [comment]
hi @djberg96 

i have the following output for that command 

``` 
RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.6
  - RUBY VERSION: 2.4.4 (2018-03-28 patchlevel 296) [x64-mingw32]
  - INSTALLATION DIRECTORY: C:/Ruby24-x64/lib/ruby/gems/2.4.0
  - USER INSTALLATION DIRECTORY: C:/Users/rubem/.gem/ruby/2.4.0
  - RUBY EXECUTABLE: C:/Ruby24-x64/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/Ruby24-x64/bin
  - SPEC CACHE DIRECTORY: C:/Users/rubem/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x64-mingw32
  - GEM PATHS:
     - C:/Ruby24-x64/lib/ruby/gems/2.4.0
     - C:/Users/rubem/.gem/ruby/2.4.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://gems.hashicorp.com", "http://rubygems.org/", "https://rubygems.org/"]
  - REMOTE SOURCES:
     - https://gems.hashicorp.com
     - http://rubygems.org/
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Program Files\Docker\Docker\Resources\bin
     - C:\WINDOWS\system32
     - C:\WINDOWS
     - C:\WINDOWS\System32\Wbem
     - C:\WINDOWS\System32\WindowsPowerShell\v1.0\
     - C:\WINDOWS\System32\OpenSSH\
     - C:\Program Files\PuTTY\
     - C:\Program Files\nodejs\
     - C:\Program Files\Git\cmd
     - C:\Ruby24-x64\bin
     - C:\Users\rubem\AppData\Local\Programs\Python\Python36\Scripts\
     - C:\Users\rubem\AppData\Local\Programs\Python\Python36\
     - C:\Users\rubem\AppData\Local\Microsoft\WindowsApps
     - C:\Users\rubem\AppData\Roaming\npm
     - C:\Program Files\Microsoft VS Code\bin

```

I'm not using any proxy and i never defined the http_proxy env variable, its needed to set that variable ?

**Comment by djberg96** [comment]
@Rubemlrm No, you don't need your proxy set, I just wanted to eliminate that as a possibility.

What happens if you remove `https://gems.hashicorp.com` from your gem sources? You can do this by editing your .gemrc file, or doing `gem sources -r https://gems.hashicorp.com`.

**Comment by Rubemlrm** [comment]
I have the same problem. Only added to test other sources for gems. The same for the http version of ruby gems. But i can't install or update any gem.

**Comment by tomshaw** [comment]
Can you ping rubygems.org? If not it's a Windows Firewall issue.

**Comment by Rubemlrm** [comment]
@tomshaw at the moment i can't test, but yesterday even for acessing the rubygems.org site i had several problems, and most of the times i needed to try enter on http version to get a redirect. 
Relative to the firewall, i have disabled the windows firewall and home router firewall to check that possibility and even with both firewalls turned off i get the same problems.

**Comment by Rubemlrm** [comment]
Found the problem with the help of @fastly team. Looks that was causing this problem was a problem with ipv6 and domain name, after disable the ipv6 dhcp and dhcpd of my router eveything started working without any type of problem. thhanks for the help @tomshaw @djberg96
