### ISSUE TITLE
FR: Enable publishing forks of other gems

### ISSUE THREAD

**Issue by danowar2k** [rubygems/rubygems#2276]
The world of Github is full of stale repositories. Some of which have been published as gems.
For example, the Vagrant plugin [vagrant-disksize](https://github.com/sprotheroe/vagrant-disksize).

The gem is published on RubyGems, but the repository hasn't been updated for two years. Multiple issues have been filed. I am afflicted by one of them. A fix has been proposed but the pull request has never been merged. It quite likely never will.

A feature to prevent RubyGems clutter would be one or more of the following:
- automatically identify forks when publishing a RubyGem
- if a fork is identified, add the published gem to the list of forks of the original gem
- provide a way to choose whether to install the original gem (the "master" gem) or a fork of it.

As of right now, I've installed Vagrant in Windows and am trying to automatically install the plugin fork. Vagrant uses an embedded Ruby and I haven't found a way to either install the github fork manually or apply a patch to the installed gem. With the ability to choose gem forks for installation, stale repositories would not be that much of a problem anymore.

**Comment by bronzdoc** [comment]
This issue corresponds to https://github.com/rubygems/rubygems.org
