### ISSUE TITLE
When will v2.7.7 be released?

### ISSUE THREAD

**Issue by reedloden** [rubygems/rubygems#2277]
v2.7.6 was a security release, and yet a lot of people can't upgrade due to bugs like #2180, https://github.com/bundler/bundler/issues/6311, etc. In fact, people are explicitly downgrading to vulnerable versions just to get rubygems to work.

When is v2.7.7 going to be released with #2208 (and any related fixes)? Would be great to have people running a rubygems that includes all the security fixes mentioned in https://blog.rubygems.org/2018/02/15/2.7.6-released.html.

https://github.com/rubygems/rubygems/issues/2180#issuecomment-368389324 says it was supposed to happen a while ago, but it hasn't yet.

https://github.com/rubygems/rubygems/pull/2208#issuecomment-385142171 says May.

Anything the community can do to help here? or is there anybody besides @hsbt that could do this, as he seems to be pretty busy?

Thanks!

**Comment by indirect** [comment]
Thanks for asking!

To address the security concern first, anyone running the latest bugfix Ruby version  (2.2.10, 2.3.7, 2.4.4, and 2.5.1) has the security fixes included, and does not need to upgrade their RubyGems to be secure.

In an attempt to save end-users some deprecation message pain, we're working to push Bundler 1.16.2 and then RubyGems 2.7.7. We don't have exact dates for those, since we're still working on it.

I hope that helps!

**Comment by hsbt** [comment]
HI, I can release RubyGems 2.7.7 now. Just finished preparing to release with https://github.com/rubygems/rubygems/commits/2.7 .

But I hope to enable deprecated warnings about `Gem::Util`. I'm waiting to release bundler-1.16.2 a few weeks.

**Comment by reedloden** [comment]
@indirect / @hsbt 
> To address the security concern first, anyone running the latest bugfix Ruby version (2.2.10, 2.3.7, 2.4.4, and 2.5.1) has the security fixes included, and does not need to upgrade their RubyGems to be secure.

The problem with that is that many folks in managed environments have pinned rubygems versions in order to be able to patch security issues without ruby being upgraded. As such, those users are still vulnerable, as they install their own rubygems version separate than using what comes with ruby.

**Comment by hsbt** [comment]
@reedloden I released 2.7.7 now. https://git.pepabo.com/suzuri/suzuri/issues/4566
