### ISSUE TITLE
gem install fails using rubygems 2.7 with custom gem server first in gem sources list

### ISSUE THREAD

**Issue by holtrop** [rubygems/rubygems#2279]
My current problem is:
The command `gem install rake` fails to install rake with Rubygems 2.7.6 on Ruby 2.5 with a local gem server listed in my gem sources list as the only source. This works with Rubygems 2.6.14 on Ruby 2.3.

The command outputs:

    $ gem install rake
    Done installing documentation for  after 0 seconds

With Ruby 2.3 and Rubygems 2.6.14:

    $ gem install rake
    Successfully installed rake-12.0.0
    Parsing documentation for rake-12.0.0
    Done installing documentation for rake after 0 seconds
    1 gem installed

If I place 'https://rubygems.org' ahead of my custom server in the gem sources list then the command works fine and installs rake from rubygems.org. Placing 'https://rubygems.org' after my custom server in the gem sources list exhibits the same problem and no gem is installed.

The gem server logs for the request are as follows (for the Ruby 2.5 / Rubygems 2.7.6 case):

    myserver:80 10.48.163.64 - - [04/May/2018:10:40:24 -0400] "HEAD /api/v1/dependencies HTTP/1.1" 200 394 "-" "Ruby, RubyGems/2.7.6 x86_64-linux Ruby/2.5.1 (2018-03-29 patchlevel 57)"
    myserver:80 10.48.163.64 - - [04/May/2018:10:40:24 -0400] "GET /api/v1/dependencies?gems=rake HTTP/1.1" 200 608 "-" "Ruby, RubyGems/2.7.6 x86_64-linux Ruby/2.5.1 (2018-03-29 patchlevel 57)"

The gem server logs for the request under Ruby 2.3 / Rubygems 2.6.14 are similar:

    myserver:80 10.48.163.64 - - [04/May/2018:10:40:17 -0400] "HEAD /api/v1/dependencies HTTP/1.1" 200 394 "-" "Ruby, RubyGems/2.6.14 x86_64-linux Ruby/2.3.4 (2017-03-30 patchlevel 301)"
    myserver:80 10.48.163.64 - - [04/May/2018:10:40:17 -0400] "GET /api/v1/dependencies?gems=rake HTTP/1.1" 200 608 "-" "Ruby, RubyGems/2.6.14 x86_64-linux Ruby/2.3.4 (2017-03-30 patchlevel 301)"

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.6
```

- [x] I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
@holtrop is this still an issue for you?

**Comment by holtrop** [comment]
@bronzdoc No, it appears to no longer be an issue. I have done several updates since then, and was on rubygems 2.7.7. But I went back to 2.7.6 just to try it and it is still working now to install gems (even after uninstalling them) with just a local server listed. So I am not sure what changed but this appears to be working fine now. Thank you for checking. I guess if I notice it again and can pinpoint what is causing it then I can reopen.
