### ISSUE TITLE
gem-open fails for default gems

### ISSUE THREAD

**Issue by jasonkarns** [rubygems/rubygems#2281]
I'm having a problem.

My current problem is `gem open <any default gem>` fails with:

```
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ dir_chdir - /usr/local/lib/ruby/gems/2.5.0/gems/zlib-1.0.0
```

All default gems (except rdoc for some reason), fail with the above error if `gem open` is attempted.

Tested with: `for g in `gem list | grep default | cut -f1 -d' '`; do gem open $g; done`

Conversely, all of the non-default gems can be successfully opened.

Default gems that fail to open:

```
bigdecimal, bundler, cmath, csv, date, dbm, etc, fcntl, fiddle, fileutils, io-console, ipaddr, json, openssl, psych, scanf, sdbm, stringio, strscan, webrick, zlib
```

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.6
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
This is a known issue, what we really should be doing is printing out a better error that says default gems cannot be opened
