### ISSUE TITLE
gem install failure in docker

### ISSUE THREAD

**Issue by saritanavale** [rubygems/rubygems#2285]
I'm having a problem or would like to suggest a feature.

Running below commands:
sudo docker run -it --rm --net red_cluster ruby sh -c '\
  gem install redis \
  && wget http://download.redis.io/redis-stable/src/redis-trib.rb \
  && ruby redis-trib.rb create --replicas 1 \
  '"$(for red in 1 2 3 4 5; do \
    echo -n "$(sudo docker inspect --format '{{ (index .NetworkSettings.Networks "redis-net").IPAddress }}' "redis-$red")"':6379 '; \
  done)"

ERROR:  Could not find a valid gem 'redis' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - no such name (https://rubygems.org/specs.4.8.gz)

My current problem is _________

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
PASTE HERE
```2.5.2.1


I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by duckinator** [comment]
hi!

it looks like it's encountering issues specifically on the `gem install redis` part.

can you run the following, and let me know if it gives the same error?:

```
sudo docker run -it --rm --net red_cluster ruby sh -c 'gem install redis'
```

and can you also provide the output of the following command?:

```
sudo docker network inspect red_cluster
```

**Comment by bronzdoc** [comment]
@saritanavale can you provide what @duckinator  suggested?

**Comment by saritanavale** [comment]
He provided me below details:
hi!
it looks like it's encountering issues specifically on the gem install redis part.
can you run the following, and let me know if it gives the same error?:
sudo docker run -it --rm --net red_cluster ruby sh -c 'gem install redis'
and can you also provide the output of the following command?:
sudo docker network inspect red_cluster

**Comment by bronzdoc** [comment]
Hey @saritanavale can you run the commands that @duckinator suggested and paste the ouput here? thanks

**Comment by bronzdoc** [comment]
I'm going to close this, @saritanavale  if you provide the output of the commands we requested to help you i will reopen it.
