### ISSUE TITLE
Purpose of the index.rubygems.org service

### ISSUE THREAD

**Issue by salsa-dev** [rubygems/rubygems#2287]
_I'm having a problem in the corporate network with strict firewall rules that restrict access to rubygems.org.
Chef-client requests "index.rubygems.org" and I cannot find the description of the service._

**Is it being used only for fetching index or could also be used for downloading gems?**

This issue is related to:

  - [x ] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
@salsa-dev could you open this in https://github.com/rubygems/rubygems.org thanks
