### ISSUE TITLE
gem update --system issues - Bundler & Git

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2300]
ruby-loco trunk build installs bundler as a gem, and `bundle version` returns:
```
Bundler version 1.16.2 (2018-05-16 commit 9f7bf0ac3)
```

When using rubygems-update on Appveyor, if warnings/stderr are on/output, there is a 'not a git repository' message, and `bundle version` returns the following (with the current date):
```
Bundler version 1.16.2 (2018-05-23 commit )
```

I assume this means that the `bundler-1.16.2.gemspec` file is not being 'parsed' before the update package is created/assembled...

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [X] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
The RubyGems packaging task needs to update the Bundler build metadata file, like the Bundler release task does

**Comment by ncreuschling** [comment]
This is a bug IMHO, not a feature.
