### ISSUE TITLE
[RESOLVED - Issue can be closed] Some openssl-related problem - can not publish new gems; this problem was probably already reported in 2016

### ISSUE THREAD

**Issue by shevegen** [rubygems/rubygems#2306]
I am having some SSL-related problems.

When trying to update one of my gems I get:

    gem push *.gem

    ERROR:  SSL verification error at depth 0: certificate is not yet valid (9)
    ERROR:  Certificate /C=US/ST=California/L=San Francisco/O=Fastly, Inc./CN=f2.shared.global.fastly.net not valid until 2018-05-30T10:24:11Z
    ERROR:  While executing gem ... (RuntimeError)
        Can't find 'rubygems-update' in any repo. Check `gem source list`.

Not sure how to resolve it. There is an older thread here at rubygems from 2016
where some advice is given how to resolve it.

A link goes to this here:

https://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html#troubleshooting-certificate-errors

On a side note, Windows and Mac has a walk-through - could someone also add a linux entry, at the least for one distribution? I am not sure how to proceed and how to resolve this error.

I am also not sure why that error occurred... yesterday I could publish new gems and update without
a problem. Now suddenly I have this problem hmm ...

I will also show the output of the following command run:

    **ruby -ropen-uri -e 'eval open("https://git.io/vQhWq").read'**

Here's your Ruby and OpenSSL environment:

Ruby:           2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
RubyGems:       2.7.6
Bundler:        1.16.2
Compiled with:  OpenSSL 1.1.0h  27 Mar 2018
Loaded version: OpenSSL 1.1.0h  27 Mar 2018
SSL_CERT_FILE:  /etc/ssl/cert.pem
SSL_CERT_DIR:   /etc/ssl/certs

With that out of the way, let's see if you can connect to rubygems.org...

Bundler connection to rubygems.org:       failed  â  (certificate verification)
ERROR:  SSL verification error at depth 0: certificate is not yet valid (9)
ERROR:  Certificate /C=US/ST=California/L=San Francisco/O=Fastly, Inc./CN=f2.shared.global.fastly.net not valid until 2018-05-30T10:24:11Z
RubyGems connection to rubygems.org:      failed  â  (certificate verification)
Ruby net/http connection to rubygems.org: failed  â

Unfortunately, this Ruby can't connect to rubygems.org. ð¡
Your Ruby can't connect to rubygems.org because you are missing the certificate files OpenSSL needs to verify you are connecting to the genuine rubygems.org servers.

Hopefully with rubygems 3.x and bundler united together, issues such as the above could more easily be resolved. I'd love being able to automatically resolve it too - right now it is a bit cumbersome to try to download .pem files and put them into the right place ... all I want to do is update my published rubygems. :(

PS: Sorry for the above encoding problems; it is output I pasted from my non-unicode terminal. Not sure why the above ruby code leads to these weird token outputs when "ruby -ropen-uri -e 'eval open("https://git.io/vQhWq").read'" is run.

**Comment by djberg96** [comment]
@segiddins We're hosted by AWS, right? Coincidentally, we ran into an issue on our own product where I discovered that a connection would fail if the clock skew was greater than 5 minutes when trying to authenticate against AWS using the aws-sdk.

There is a net-ntp library but it's not in the stdlib afaik, so I'm guessing there would be resistance to using it internally. Maybe a plugin, though.

**Comment by segiddins** [comment]
Yeah, AWS fronted by fastly. It’s just a shame TLS error messages are so unhelpful.
