### ISSUE TITLE
Gem I released is still not available to me

### ISSUE THREAD

**Issue by krainboltgreene** [rubygems/rubygems#2310]
I'm having a problem or would like to suggest a feature.

My current problem is that I can't install the gem version I published.

This issue is related to:

  - [x] Network problems
  - [ ] Installing a library
  - [x] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.3
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

```
$ bundle exec rake release
jsonapi-home 1.1.3 built to pkg/jsonapi-home-1.1.3.gem.
Tag v1.1.3 has already been created.
rake aborted!
Pushing gem to https://rubygems.org...
Repushing of gem versions is not allowed.
Please use `gem yank` to remove bad gem releases.
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.1/lib/bundler/gem_helper.rb:177:in `sh'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.1/lib/bundler/gem_helper.rb:102:in `rubygem_push'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/bundler-1.16.1/lib/bundler/gem_helper.rb:69:in `block in install'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/gems/rake-12.3.1/exe/rake:27:in `<top (required)>'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `eval'
/Users/krainboltgreene/.rvm/gems/ruby-2.5.0/bin/ruby_executable_hooks:15:in `<main>'
Tasks: TOP => release => release:rubygem_push
(See full trace by running task with --trace)
```

<img width="298" alt="screen shot 2018-06-02 at 5 48 35 pm" src="https://user-images.githubusercontent.com/334809/40882111-3146e1aa-668d-11e8-86cd-a99c94eb0312.png">

```
$ gem list jsonapi-home

*** LOCAL GEMS ***

jsonapi-home (1.1.2, 1.1.1, 1.1.0, 1.0.0)
$ bundle install --no-cache
Fetching gem metadata from https://rubygems.org/..........
Fetching gem metadata from https://rubygems.org/.
Could not find gem 'jsonapi-home (= 1.1.3)' in any of the gem sources listed in your Gemfile.
```

**Comment by krainboltgreene** [comment]
For reference, I published nearly 20 minutes ago.

**Comment by krainboltgreene** [comment]
While `gem show` still doesn't show the latest version, I'm now able to `bundle install`

```
Fetching jsonapi-home 1.1.3 (was 1.1.2)
Installing jsonapi-home 1.1.3 (was 1.1.2)
```

**Comment by segiddins** [comment]
Sounds like an issue with a delay in rubygems.org updating?

**Comment by krainboltgreene** [comment]
It's weird that the website had data faster than the index.

**Comment by segiddins** [comment]
The index is heavily cached, so it’s possible there’s a cache invalidation issue

**Comment by krainboltgreene** [comment]
This is the second time it's happened, but I didn't end up making a issue for it last time since it felt like a fluke. What can I do to investigate this?

**Comment by segiddins** [comment]
I'm not really sure, to be honest. I think that's a better question for the rubygems.org maintainers. Maybe ping them in slack if you see it happen again so logs can be pulled?

**Comment by colby-swandale** [comment]
This is an issue with RubyGems.org and not RubyGems
