### ISSUE TITLE
Very frequently used command "gem i" doesn't work on 3.0.0.beta1

### ISSUE THREAD

**Issue by tagomoris** [rubygems/rubygems#2314]
On 3.0.0.beta1 (released with MRI 2.6.0-preview2), I ran the command below, but it doesn't work.

```shell
$ gem i pry
ERROR:  While executing gem ... (Gem::CommandLineError)
    Ambiguous command i matches [info, install]
$ ruby --version
ruby 2.6.0preview2 (2018-05-31 trunk 63539) [x86_64-darwin17]
```

This is caused by the newly added subcommand `info`. I can understand that this error is correct and expected for rubygems developers.
But on the other hand, `gem i NAME` is very frequently used manyally, or shown in many blog posts, examples and also in probably code snippets actually works in many environments.

My expectation is `gem i` is mapped to `gem install` intentionally.

---

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by tagomoris** [comment]
This pull-req seems to solve this problem (after release of 3.0.0.beta2 and MRI 2.6.0-preview3 ?).
https://github.com/rubygems/rubygems/pull/2308

Let me close this issue right now.

**Comment by hsbt** [comment]
@tagomoris Thanks, I totally agree your opinion. I will release rubygems-3.0.0.beta2 or 2.6.0-preview3 with #2308.

**Comment by amatsuda** [comment]
For those who are still suffering from this issue, there's a gem from 3.years.ago that should perfectly solve your problem: https://rubygems.org/gems/gem_i
HTH
