### ISSUE TITLE
Can't update gems

### ISSUE THREAD

**Issue by ethikz** [rubygems/rubygems#2316]
I'm having a problem or would like to suggest a feature.

My current problem is: Everytime I try to run `gem install` I am getting an error

```
ERROR:  While executing gem ... (TypeError)
    incompatible marshal file format (can't be read)
	format version 4.8 required; 60.104 given
```

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

Here are my current environment details:

I currently use RVM and have **ruby-2.1.4** installed.  It was working fine this past Friday.  I've tried imploding and reinstall RVM, removing the cache, using unsecured sources to no avail.

```
$ gem env version
2.6.14
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by ethikz** [comment]
I am behind a proxy and I deleted my `.gem` folder and even reinstalled Ruby.

When I change my `GEM_HOME` to just `/User/name` it still returns

```
ERROR:  While executing gem ... (TypeError)
    incompatible marshal file format (can't be read)
	format version 4.8 required; 60.104 given
```

**Comment by MSP-Greg** [comment]
I'm a windows user, so paths might be different.  Some marshalled data is stored in `Gem.spec_cache_dir`, which, in Windows, is not within the Ruby TOPDIR.

```
ruby -e "puts Gem.spec_cache_dir"
```

Maybe rename (not delete) that folder and see if it helps?

Greg

**Comment by ethikz** [comment]
I renamed the `/Users/name/.gem/specs` to /Users/name/.gem/specs_backup` and still receiving the same error

**Comment by MSP-Greg** [comment]
I suggested it because it was an easy thing to try.  Thanks,

Other than downloading some gem files and trying to install locally (or installing a RubyGems update locally), I have no idea.  Sorry, Greg

**Comment by drbrain** [comment]
60.104 is the ASCII characters "<h" probably followed by "tml…". This probably means the insecure source has been detected and is being blocked.

`gem install -V some_gem` will show which the URLs RubyGems is trying to download and you should be able to load one in your browser to see why your insecure proxy no longer works.

**Comment by ethikz** [comment]
I ended up having to remove the ENV Variables for the proxy.  For whatever reason it stopped accepting it, once I commented them out and re-installed everything it works.

Thanks for everyones help
