### ISSUE TITLE
FileOverlfow when I create a new gem

### ISSUE THREAD

**Issue by pedro-mourao** [rubygems/rubygems#2317]
Hello

I'm having a problema when I create a new gem (**gem build myproject.gemspec**)

Here are my current environment details:

C:\Ruby193\lib\ruby\gems\1.9.1\gems\myproject> bundle package

 ... ... ... 

_Updating files in vendor/cache Your bundle is complete! Use bundle show [gemname] to see where a bundled gem is installed. Updating files in vendor/cache_

C:\Ruby193\lib\ruby\gems\1.9.1\gems\myproject> gem build myproject.gemspec

_WARNING: licenses is empty
 WARNING: no email specified 
WARNING: no homepage specified 
WARNING: description and summary are identical
 **ERROR: While executing gem ... (Gem::Package::TarWriter::FileOverflow) 
You tried to feed more data than fits in the file._**

**Comment by pedro-mourao** [comment]
gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.6
  - RUBY VERSION: 1.9.3 (2012-11-10 patchlevel 327) [i386-mingw32]
  - INSTALLATION DIRECTORY: C:/Ruby193/lib/ruby/gems/1.9.1
  - USER INSTALLATION DIRECTORY: C:/Users/XXX/.gem/ruby/1.9.1
  - RUBY EXECUTABLE: C:/Ruby193/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/Ruby193/bin
  - SPEC CACHE DIRECTORY: C:/Users/XXX/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86-mingw32
  - GEM PATHS:
     - C:/Ruby193/lib/ruby/gems/1.9.1
     - C:/Users/XXX/.gem/ruby/1.9.1
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH

**Comment by colby-swandale** [comment]
Does this error happen on later version of Ruby?

**Comment by bronzdoc** [comment]
Closing for lack of response, we'll be happy to reopen if you provide answers to what @colby-swandale  asked @pedro-mourao thanks!
