### ISSUE TITLE
unable to download gems from rubygems.org with ruby 1.9.1

### ISSUE THREAD

**Issue by dineshkm** [rubygems/rubygems#2325]
I'm having a problem or would like to suggest a feature.

My current problem is unable to download gems from rubygems.org

```
C:\opscode\chef\embedded\bin>gem install logging
ERROR:  Could not find a valid gem 'logging' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect retur
ned=1 errno=0 state=error: certificate verify failed (https://rubygems.org/lates
t_specs.4.8.gz)
```
This issue is related to:

- [x] Installing a library
  
Here are my current environment details:

```
$ gem env version
RubyGems Environment:
  - RUBYGEMS VERSION: 2.1.11
  - RUBY VERSION: 1.9.3 (2013-11-22 patchlevel 484) [i386-mingw32]
  - INSTALLATION DIRECTORY: C:/opscode/chef/embedded/lib/ruby/gems/1.9.1
  - RUBY EXECUTABLE: C:/opscode/chef/embedded/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/opscode/chef/embedded/bin
  - SPEC CACHE DIRECTORY: C:/Users/Administrator/.gem/specs
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86-mingw32
  - GEM PATHS:
     - C:/opscode/chef/embedded/lib/ruby/gems/1.9.1
     - C:/Users/Administrator/.gem/ruby/1.9.1
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => nil
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - C:\Windows\system32
     - C:\Windows
     - C:\Windows\System32\Wbem
     - C:\Windows\System32\WindowsPowerShell\v1.0\
     - C:\Windows\System32\WindowsPowerShell\v1.0\
     - C:\Program Files\Amazon\cfn-bootstrap\
     - C:\Program Files (x86)\Portable Python 2.7.6.1\App
     - C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\
     - C:\Program Files\Microsoft SQL Server\100\Tools\Binn\
     - C:\Program Files\Microsoft SQL Server\100\DTS\Binn\
     - C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\VSShell\Common
7\IDE\
     - C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\
     - C:\Program Files (x86)\Portable Python 2.7.6.1\App\Scripts
     - C:\opscode\chef\bin
     - C:\Users\Administrator\Downloads\openssl-1.0.2o-x64_86-win64


I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by djberg96** [comment]
Is updating your version of ruby and rubygems an option? That is quite old.

**Comment by dineshkm** [comment]
No. we cannot update ruby version. i have tried to updating the rubygems but that didnt help me.

**Comment by tcfodor** [comment]
I'm having the same problem when updating/installing any gems.  I'm on Windows with ruby 2.0.0p643 and rubygems-update 2.4.8.  I've tried on various machines and networks.

**Comment by szeck87** [comment]
Running `ruby -ropen-uri -e 'eval open("https://git.io/vQhWq").read'` in my appveyor.yml file yields:
```
C:/Ruby23/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (OpenSSL::SSL::SSLError)
```
I've tried updating gem, but that didn't resolve it in that environment.

**Comment by MSP-Greg** [comment]
@tcfodor @szeck87

I haven't recently worked those Ruby versions,  Does `ENV['SSL_CERT_FILE']` point to a valid cert file?

If not, download:

https://curl.haxx.se/ca/cacert.pem

and point the environment variable to where you store it.  May help...

**Comment by indirect** [comment]
@dineshkm @tcfodor @szeck87 If the suggestion from @MSP-Greg does not help you, there are specific instructions in the [SSL troubleshooting guide](https://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html) telling you to collect certain information and then open a new ticket. Please follow those instructions if you are still having problems.
