### ISSUE TITLE
RubyGems.org issues - Windows Info

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2330]
If you're having issues connecting to RubyGems.org (installing or upgrading gems) and using Windows, the following may be helpful.

For Windows users of Ruby less than version 2.0, it's time to upgrade.

There are issues with YAML & OpenSSL.  In Ruby 1.9.3, OpenSSL only supports up to TLSv1.  I believe that RubyGems.org now only supports connections using TLSv1_2.  There is essentially no way to upgrade this in Ruby 1.9.3.

On Windows, Ruby 2.0 and later all support TLSv1_2.

If you want to try, you may be able to use a PowerShell script (or a browser) to download gems (or the RubyGems system update) and install them locally.  But, this really isn't the place for support for that solution.

HTH, Greg

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by MSP-Greg** [comment]
@indirect

After you closed #2325, I had the time to look at the Windows issue.  I forgot that RubyGems includes its own cert files, and a quick look seemed to show that they've been included for a number of years.

**Comment by hsbt** [comment]
@MSP-Greg First of all, #2325 is out of scope for ruby and rubygems responsibility. Because the embedded ruby interpreter is not controlled for us. It's same as a binary of Linux distribution like Debian and RHEL.

And, The issue of OpenSSL is out of scope for rubygems. It's the issue of RubyInstaller or RubyIntaller2.

**Comment by MSP-Greg** [comment]
Have you tried adding a `gem update --system` to your Appveyor.yml, maybe insert at line 21?

Appveyor has upgrading to RubyGems 2.7.7 on their list...

Recently, I've had issues trying to get to keyservers on Appveyor.

**Comment by szeck87** [comment]
I get an error when doing that:
```
ERROR:  While executing gem ... (Gem::Package::PathError)
    installing into parent path bin/gem of C:/ruby24-x64/lib/ruby/gems/2.4.0/gems/rubygems-update-2.7.7 is not allowed
```

**Comment by MSP-Greg** [comment]
Maybe try:
```
gem install rubygems-update -N
ruby.exe update_rubygems
```

**Comment by MSP-Greg** [comment]
@szeck87 

You need the 2nd line.  Installing the rubygems-update gem does not update rubygems.  It needs the second line...

**Comment by szeck87** [comment]
Yea I got a `ruby.exe: No such file or directory -- update_rubygems (LoadError)` having that second line in there.  I'm going to try without https in my Gemfile.

**Comment by bronzdoc** [comment]
@MSP-Greg i'm going to close this, since is not an issue but you providing information about solving another issue.
