### ISSUE TITLE
Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/

### ISSUE THREAD

**Issue by edap** [rubygems/rubygems#2340]
I'm having a problem or would like to suggest a feature.

My current problem is the same as described here https://github.com/rubygems/rubygems/issues/1912
Before to close the issue and marked as solved, note that the guide that you linked (https://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html)  does not address the problem. It says:

1)If the output reads “Your Ruby can’t connect to rubygems.org because you are missing the certificate” you have a certificate verification error, and need to update your certs.

2)If you instead see “Your Ruby can’t connect to rubygems.org because your version of OpenSSL is too old” your OpenSSL version is old and incompatible with TLSv1.2, and you need to upgrade your OpenSSL and/or recompile Ruby to use a newer version of SSL.

It does not cover the case where the output of the script is "Even worse, we're not sure why".

This issue is related to:

  - [x] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

This is the output of check.rb

```bash
Here's your Ruby and OpenSSL environment:

Ruby:           2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
RubyGems:       2.6.11
Bundler:        1.15.0
Compiled with:  OpenSSL 1.0.1c 10 May 2012
Loaded version: OpenSSL 1.0.1c 10 May 2012
SSL_CERT_FILE:  /usr/lib/ssl/cert.pem
SSL_CERT_DIR:   /usr/lib/ssl/certs

With that out of the way, let's see if you can connect to rubygems.org...

Bundler connection to rubygems.org:       failed  ❌  (SSL_connect returned=1 errno=0 state=unknown state: tlsv1 alert protocol version)
RubyGems connection to rubygems.org:      failed  ❌  (SSL_connect returned=1 errno=0 state=unknown state: tlsv1 alert protocol version (https://rubygems.org))
Ruby net/http connection to rubygems.org: failed  ❌

Unfortunately, this Ruby can't connect to rubygems.org. 😡
Even worse, we're not sure why. 😕

Here's the full error information:
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=unknown state: tlsv1 alert protocol version
  /home/dapx/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock'
  /home/dapx/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_connect'
  /home/dapx/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:948:in `connect'
  /home/dapx/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
  /home/dapx/.rbenv/versions/2.4.1/lib/ruby/2.4.0/net/http.rb:882:in `start'
  check.rb:88:in `<main>'

You might have more luck using Mislav's SSL doctor.rb script. You can get it here:
https://github.com/mislav/ssl-tools/blob/8b3dec4/doctor.rb
Read more about the script and how to use it in this blog post:
https://mislav.net/2013/07/ruby-openssl/
dapx@my:~/my/current$ gem install bundler
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=unknown state: tlsv1 alert protocol version (https://api.rubygems.org/specs.4.8.gz)
```

I can not even download the gem manually:

```bash
wget  https://rubygems.org/rubygems/rubygems-2.7.7.tgz
--2018-06-30 09:18:12--  https://rubygems.org/rubygems/rubygems-2.7.7.tgz
Resolving rubygems.org (rubygems.org)... 151.101.0.70, 151.101.64.70, 151.101.192.70, ...
Connecting to rubygems.org (rubygems.org)|151.101.0.70|:443... connected.
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection.
```

same result with:

```ruby
wget --no-check-certificate https://rubygems.org/rubygems/rubygems-2.7.7.tgz
```

**Update:**

I have downloaded the certificates as explained in "Step 3: Copy new trust certificate".
But I am still not able to update rubygems.

I have installed ruby using rbenv & ruby-build on ubuntu (case that is not covered in the tutorial).

I have rebuild ruby doing:
```
rbenv install 2.4.1
rbenv: /home/dapx/.rbenv/versions/2.4.1 already exists
continue with installation? (y/N) y
Installing ruby-2.4.1...
Installed ruby-2.4.1 to /home/dapx/.rbenv/versions/2.4.1
```

Then same errors as before:

```bash
dapx@my:~/.rbenv/plugins/ruby-build/bin$ gem install bundler
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=unknown state: tlsv1 alert protocol version (https://api.rubygems.org/specs.4.8.gz)
dapx@my:~/.rbenv/plugins/ruby-build/bin$ gem update --system
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=unknown state: tlsv1 alert protocol version (https://api.rubygems.org/specs.4.8.gz)
```

**Comment by segiddins** [comment]
> SSL_connect returned=1 errno=0 state=unknown state: tlsv1 alert protocol version

looks like the underlying error -- my guess is that negotiating to use a supported TLS version (1.2) is failing

**Comment by edap** [comment]
And how can I solve this?

**Comment by indirect** [comment]
@edap please see [How to troubleshoot RubyGems and Bundler TLS/SSL Issues ](https://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html). If you are still having trouble after following the guide, it contains instructions on how to open a new issue with more information.
