### ISSUE TITLE
Documentation does not cover all the cases

### ISSUE THREAD

**Issue by edap** [rubygems/rubygems#2341]
I'm referring to this https://github.com/rubygems/rubygems/issues/2340#event-1710188952. @indirect I know that you have a lot of issues follow, but in my issue I explain where this document https://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html is not helping me. Closing an issue without leaving to a person the possibility to reply is not really helpful.

My current problem is https://github.com/rubygems/rubygems/issues/2340

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by indirect** [comment]
@edap my apologies for not reading your entire issue. You still have not followed [the instructions in the guide for opening a new issue](https://github.com/bundler/bundler-site/blob/master/source/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html.md#creating-an-issue). Your previous issue does not have enough information for us to help you. Please come back with the listed information.

**Comment by indirect** [comment]
After a more careful read of your previous issue, it looks like the problem is with your machine's OpenSSL version, and it has nothing to do with Ruby, RubyGems, or Bundler. Please update OpenSSL to something released more recently than 2012, make sure that `wget` is able to connect to rubygems.org, and then try again. 👍🏻

**Comment by edap** [comment]
Thank, you are right, this openssl version is really old, I have updated it.

```
openssl version
OpenSSL 1.0.2l  25 May 2017
```

And I am able to use wget, for example:
```
wget https://www.openssl.org/source/openssl-1.0.2l.tar.gz
```

works.

But: 
```
 wget https://rubygems.org/rubygems/rubygems-2.7.7.tgz
Resolving rubygems.org (rubygems.org)... 151.101.192.70, 151.101.64.70, 151.101.0.70, ...
Connecting to rubygems.org (rubygems.org)|151.101.192.70|:443... connected.
OpenSSL: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Unable to establish SSL connection.
```

still gives me an error. Why is this happening?
