### ISSUE TITLE
Xcode path not escaped

### ISSUE THREAD

**Issue by BasThomas** [rubygems/rubygems#2357]
I'm having a problem.

My current problem is that while installing a library that uses the Xcode developer tools, the Xcode path is not escaped. The path to my Xcode was `Xcode 9.3`. It would subsequently fail because "`/Applications/Xcode`" did not exist.

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.12
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by colby-swandale** [comment]
Can you elaborate more on the problem? What command are you running? What's the output of `gem env`?

**Comment by MSP-Greg** [comment]
Can ruby itself find any of the build tools?  I use gcc on Windows, does an equivalent to the following work?

```
ruby -e "puts %x[make --help]"
```

I know there are warning about using spaces in paths with the Windows MSYS2/MinGW tools.  A quick look for XCode docs also showed paths without spaces (like `Xcode8.3.3`).

**Comment by segiddins** [comment]
> My current problem is that while installing a library that uses the Xcode developer tools, the Xcode path is not escaped. The path to my Xcode was Xcode 9.3. It would subsequently fail because "/Applications/Xcode" did not exist.

please share the full output of whatever command you're running that's failing

**Comment by BasThomas** [comment]
```bash
$ bundle
Fetching ffi 1.9.23
Installing ffi 1.9.23 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

current directory:
/Users/bas.broek/.rvm/gems/ruby-2.3.1/gems/ffi-1.9.23/ext/ffi_c
/Users/bas.broek/.rvm/rubies/ruby-2.3.1/bin/ruby -r
./siteconf20180713-26294-1pq7fr7.rb extconf.rb
checking for ffi.h... no
checking for ffi.h in /usr/local/include,/usr/include/ffi... yes
checking for ffi_call() in -lffi... yes
checking for ffi_closure_alloc()... no
checking for ffi_raw_call()... no
checking for shlwapi.h... no
checking for rb_thread_blocking_region()... no
checking for rb_thread_call_with_gvl()... yes
checking for rb_thread_call_without_gvl()... yes
creating extconf.h
creating Makefile

current directory:
/Users/bas.broek/.rvm/gems/ruby-2.3.1/gems/ffi-1.9.23/ext/ffi_c
make "DESTDIR=" clean

current directory:
/Users/bas.broek/.rvm/gems/ruby-2.3.1/gems/ffi-1.9.23/ext/ffi_c
make "DESTDIR="
Configuring libffi
clang: error: unsupported option '-print-multi-os-directory'
clang: error: no input files
cd
"/Users/bas.broek/.rvm/gems/ruby-2.3.1/gems/ffi-1.9.23/ext/ffi_c/libffi-x86_64-darwin16"
&& /Applications/Xcode 9.4.1.app/Contents/Developer/usr/bin/make
/bin/sh: /Applications/Xcode: No such file or directory
make: ***
["/Users/bas.broek/.rvm/gems/ruby-2.3.1/gems/ffi-1.9.23/ext/ffi_c/libffi-x86_64-darwin16"/.libs/libffi_convenience.a]
Error 127

make failed, exit code 2
```

**Comment by BasThomas** [comment]
Now that I am writing this... this is probably an `ffi` bug, right?

**Comment by BasThomas** [comment]
> What's the output of `gem env`?

For what it's worth:

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.12
  - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-darwin16]
  - INSTALLATION DIRECTORY: /Users/bas.broek/.rvm/gems/ruby-2.3.1
  - USER INSTALLATION DIRECTORY: /Users/bas.broek/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /Users/bas.broek/.rvm/rubies/ruby-2.3.1/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/bas.broek/.rvm/gems/ruby-2.3.1/bin
  - SPEC CACHE DIRECTORY: /Users/bas.broek/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/bas.broek/.rvm/rubies/ruby-2.3.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-16
  - GEM PATHS:
     - /Users/bas.broek/.rvm/gems/ruby-2.3.1
     - /Users/bas.broek/.rvm/gems/ruby-2.3.1@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["http://rubygems.org/", "http://gems.xing.com", "https://gems.xing.com/"]
  - REMOTE SOURCES:
     - http://rubygems.org/
     - http://gems.xing.com
     - https://gems.xing.com/
  - SHELL PATH:
     - /Users/bas.broek/.rvm/gems/ruby-2.3.1/bin
     - /Users/bas.broek/.rvm/gems/ruby-2.3.1@global/bin
     - /Users/bas.broek/.rvm/rubies/ruby-2.3.1/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/munki
     - /Users/bas.broek/.rvm/bin
```

**Comment by segiddins** [comment]
Looks to me like it's probably an issue in FFI's extension configuration

**Comment by MSP-Greg** [comment]
@BasThomas

Can you install other extension gems, maybe puma, eventmachine, or nokogiri?

**Comment by segiddins** [comment]
Alternatively -- what's the output of `env | grep -i make` ?

**Comment by BasThomas** [comment]
`env | grep -i make` does not return anything.

Installing `puma` and `eventmachine` works as expected.

**Comment by MSP-Greg** [comment]
@BasThomas

> Installing puma and eventmachine works as expected.

Thanks for testing that.

Since both are 'extension' gems, it would seem that RubyGems is working correctly with Xcode and its path, but bundler and/or ffi is causing the issue?

Being a windows type, I'm not exactly sure what you mean by 'Xcode developer tools'...

**Comment by BasThomas** [comment]
Awesome, thanks for the help. I'll open an issue there. The Xcode developer tools are a set of tools installed alongside Xcode, that include command line tools and other applications.

**Comment by MSP-Greg** [comment]
@BasThomas

I'm not really sure where the issue is.  Your original example was using bundler, and involved an issue with compiling ffi, an extension gem.  But, you can install other extension gems with RG...

Since I'm not that familiar with bundler, the issue could be with bundler, ffi, or XCode.  I wish I could help further, but being a windows type, I obviously can't test anything involving XCode...

**Comment by BasThomas** [comment]
Thanks so much for the input @MSP-Greg, really appreciated!

Just FYI — by default, the Xcode installation path does not contain any spaces, which means it shouldn't cause any issues for a default installation and therefore not touch most users.
