### ISSUE TITLE
Gem::Version should handle `nil` like it used to before 2.7.7

### ISSUE THREAD

**Issue by aried3r** [rubygems/rubygems#2359]
My current problem is the change introduced in https://github.com/rubygems/rubygems/pull/2203. I rely on comparing versions that are `nil`, for example some gems didn't have a version in very old versions, which then correctly meant that `Gem::Version.new(nil) < Gem::Version.new('2.0')` is correctly evaluated to `true`.

An argument could be made that `nil.to_i` is `0` and thus also `< 2.0`.

CocoaPods also [faced this issue](https://github.com/CocoaPods/CocoaPods/issues/7765).

Please reconsider this change, for me it was a breaking change in a minor version.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

```
$ gem env version
2.7.7
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
As you mention you can do `Gem::Version.new(nil.to_i) < Gem::Version.new('2.0')` to get the behavior you want.

**Comment by aried3r** [comment]
Hi! Thank you for your reply. I was looking more for a discussion about why this was changed. :)

I can't seem to find a rationale as to why handling `nil` differently than `0` or `""` makes sense and was changed in a minor version.

```Ruby
» Gem::Version.new(0) < Gem::Version.new('1.0')
=> true
Gem::Version.new('') < Gem::Version.new('1.0')
=> true
Gem::Version.new(nil) < Gem::Version.new('1.0')
ArgumentError: Malformed version number string
```

Could I propose a softer transition? Like having a "strict mode" that doesn't allow `nil` which you can opt into until it becomes the default.

Your suggestion to use `.to_i` doesn't really work for most cases I think, because usually that would come in from some variable. In my concrete case I iterate over client app versions. Older clients in the database don't have a version set, so it can happen that `client_version` is `nil`.
Calling `.to_i` works for _just nil_ because something like `Gem::Version.new('2.2.0.beta1'.to_i) < Gem::Version.new('2.1')` would return `true` because the result of `.to_i` would be just `2`.

Of course I can handle `nil` myself, but I'm wondering if there is any particular reason for RubyGems to introduce this change? It would greatly help me understand, because personally I liked that this method was very liberal in what it accepted.

**Comment by indirect** [comment]
I agree that this is a breaking change in a bugfix release, and we should keep the previously existing behavior. I propose that we print a warning on `nil` in 3.x, and reject `nil` in 4.x. /cc @segiddins @hsbt  @bronzdoc @colby-swandale

**Comment by indirect** [comment]
@deivid-rodriguez pointed out that we should treat empty string (`""`) the same as `nil`: print a warning in RubyGems 3.x, and reject in 4.x. 👍🏻

**Comment by segiddins** [comment]
I’m the maintainer of CocoaPods, and we only fixed the regression on the latest version — it’s bitten a bunch of our users

**Comment by hsbt** [comment]
I'm still waiting to response of @aried3r

**Comment by aried3r** [comment]
Oh, I didn't see your question before, sorry. Let me quickly reply.

I am not the maintainer of CocoaPods, I just have some internal Ruby software where we compare version numbers in a few places. One is our internal API client versions, where old records do not have an `app_version` in the database because they are from a time when we didn't record that. This is basically what tripped us up. I stripped down the code and simplified it to show our use case:

```Ruby
# app_version is `nil` in some cases
# `NEW_FEATURE_VERSION` is some version where something else should happen

if Gem::Version.new(device_1.app_version) < Gem::Version.new(NEW_FEATURE_VERSION)
  do_the_old_thing
else
  do_the_new_thing
end
```

That, in my mind, was the correct behavior as "no version" is (in our case) older than whatever version is recorded. This might not make sense in a strict sense, but it's pretty much how I image it to work.

Another example is – although very old code – versions in libraries, I'm taking Rails' ActionPack for this example.

In Rails 3.2 there was only a string, `VERSION`:
https://github.com/rails/rails/blob/3-2-stable/actionpack/lib/action_pack/version.rb
In Rails 4.0 both `.version` and `VERSION` is available.
https://github.com/rails/rails/blob/4-0-stable/actionpack/lib/action_pack/version.rb

We – naively, admittedly – compare such versions using the safe navigation operator:
```Ruby
Gem::Version.new(LibraryName&.version) < Gem::Version.new('42.3')
``` 

In our actual codebase of course there's more sanity checks, but we tested how `Gem::Version` handles `nil` beforehand and kinda of relied on that feature, especially since it was confirmed by specs. We got bitten by that in a minor version update :\

**Comment by hsbt** [comment]
@aried3r Thanks. I understood. Your usecase is reasonable to revert my changes. I will work to release RG 2.7.8 later.
