### ISSUE TITLE
Grant `--user-install` for `cleanup` from `~/.gemrc`

### ISSUE THREAD

**Issue by godfat** [rubygems/rubygems#2365]
We got `--user-install` for the `cleanup` command in https://github.com/rubygems/rubygems/pull/2362 and we should also grant it from `~/.gemrc` if it's set.

Originally mentioned in: https://github.com/rubygems/rubygems/issues/1530#issuecomment-406782298

/cc @bronzdoc

**Comment by bronzdoc** [comment]
@godfat can you show me your `.gemrc` ? thanks

**Comment by bronzdoc** [comment]
@godfat actually it's working for me, the reason it wasn't was because i have set as it seems "invalid" `gemrc` keys set

This work

`yaml
gem: --user-install
` 

this not

`yaml
:gem: --user-install
`
Can you confirm this please, thanks!

**Comment by godfat** [comment]
@bronzdoc I just tried 672ddcbe14f49c48f6c5492b38480a9162680b5b with `ruby -Ilib -S gem cleanup` and comparing to `gem cleanup` and I could confirm it works!

My `.gemrc` is:

```
gem: --user-install --no-check-development --env-shebang --no-rdoc --no-ri
```

Thank you!
