### ISSUE TITLE
Updates needed to util/ci (Travis)?

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2368]
Just checking test setup on Appveyor & Travis.  Should any of the following be updated, re minitest (v?), bundler (1.16.3), & Robocop (0.58.2)?

https://github.com/rubygems/rubygems/blob/7bbd0dec854f869c44fce58063ca5f4161d9154f/util/ci#L52-L60

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

Here are my current environment details:

```
$ gem env version
NA
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
They could be, there just pinned to make sure there's no unexpected breakage

**Comment by segiddins** [comment]
> Maybe the question should have been - should Travis & Appveyor CI scripts be updated so both are using the same (and newer) versions of needed gems?

ah in that case, sure!

**Comment by MSP-Greg** [comment]
I'll run tests on my fork with Appveyor & Travis.  Not tonite.

**Comment by duckinator** [comment]
Would doing what `rake setup` does and having it install the dependencies from [rubygems-update.gemspec](https://github.com/rubygems/rubygems/blob/master/rubygems-update.gemspec) work?

https://github.com/rubygems/rubygems/blob/8ceb7cacc87fb9c69c8cc3f946495abbd1778c5a/Rakefile#L13-L20

**Comment by segiddins** [comment]
I think it should!

**Comment by duckinator** [comment]
@segiddins in that case: should it call `rake setup` directly, or does `rake setup` relying on `rake bundler:checkout` make it not usable as-is? (that's an easily-adjusted thing, i just don't know whether or not it's a problem.)

**Comment by segiddins** [comment]
Should be fine to call it directly, give it a try? If it doesn’t work, we can figure something out

**Comment by MSP-Greg** [comment]
Reviewing this, there are some issues with the Travis builds, related to bundler & (missing) bundled gems...

I'll try to keep an eye on whether Travis improves the situation, as I've opened issues there.  Then there's the issue of whether to test with released or updated dependencies...

Closing...
