### ISSUE TITLE
Unable to load Maven meta-data from http://rubygems.lasagna.io/proxy/maven/releases/rubygems/rspec/maven-metadata.xml

### ISSUE THREAD

**Issue by piersf** [rubygems/rubygems#2371]
Hello there,

My apologies if this is not the right place for this issue. 
Our gradle project tries to download rubygems from http://rubygems.lasagna.io/proxy/maven/releases/rubygems/rspec/maven-metadata.xml

The piece of code in the `build.gradle` file is:

```
repositories {
    mavenCentral()
}

apply plugin: com.bmuschko.gradle.docker.DockerRemoteApiPlugin
apply plugin: com.github.jrubygradle.JRubyPlugin

dependencies {
    jrubyExec 'rubygems:rspec:3.3.0'
    jrubyExec 'rubygems:dockerspec:0.3.+'
}
```

But since last week, this is now failing with the below errors:

```
> Could not resolve all dependencies for configuration ':DOCKER.Base.Centos:jrubyExec'.
   > Could not resolve rubygems:rspec:[3.6.0,3.6.0].
     Required by:
         DOCKER.Base.Centos:unspecified
      > Could not resolve rubygems:rspec:[3.6.0,3.6.0].
         > Failed to list versions for rubygems:rspec.
            > Unable to load Maven meta-data from http://rubygems.lasagna.io/proxy/maven/releases/rubygems/rspec/maven-metadata.xml.
               > Could not GET 'http://rubygems.lasagna.io/proxy/maven/releases/rubygems/rspec/maven-metadata.xml'.
                  > The target server failed to respond
   > Could not resolve rubygems:dockerspec:[0.3,0.3.99999].
     Required by:
         DOCKER.Base.Centos:unspecified
      > Could not resolve rubygems:dockerspec:[0.3,0.3.99999].
         > Failed to list versions for rubygems:dockerspec.
            > Unable to load Maven meta-data from http://rubygems.lasagna.io/proxy/maven/releases/rubygems/dockerspec/maven-metadata.xml.
               > Could not GET 'http://rubygems.lasagna.io/proxy/maven/releases/rubygems/dockerspec/maven-metadata.xml'.
                  > The target server failed to respond
```

It seems that [http://rubygems.lasagna.io/proxy/maven/releases/rubygems/dockerspec/maven-metadata.xml](http://rubygems.lasagna.io/proxy/maven/releases/rubygems/dockerspec/maven-metadata.xml) is now down. And it appears to have been down for the past 6-7 days. There's another issue found here https://github.com/asciidoctor/asciidoctor-gradle-examples/issues/38, that reports rubygems.lasagna.io to have been down since 6 days ago.

Anyone knows if this site is going to come back up? And if not, how can i change my `build.gradle` file, to download these gems from elsewhere?

Thank you,

**Comment by colby-swandale** [comment]
The website you have specified is not associated with this project.
