### ISSUE TITLE
Change requires to require_relative?

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2373]
Since RG is now Ruby 2.2+, does anyone object to changing appropriate `require` statements to `require_relative`?  I'll do a PR if ok...

  - [X] Other

Here are my current environment details:

```
$ gem env version
NA
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
What's advantage that used `require_relative`?

**Comment by segiddins** [comment]
The biggest advantage is usually performance, since you dont have to search over the entire `$LOAD_PATH`, or go through RubyGems' custom `Kernel#require`, which can be rather heavy

**Comment by MSP-Greg** [comment]
@segiddins

Thanks, I was just typing something similar.  Disk I/O is bad.

**Comment by hsbt** [comment]
@segiddins Can you show the benchmark results?

The ruby core team has been confirming the measurement results with `require_relative` and rails. It has no biggest effect for performance.

**Comment by MSP-Greg** [comment]
@hsbt

So you're saying you want a benchmark for something that obviously lowers disk i/o?  I work a lot with Appveyor, and test times vary a great deal.  I don't what exactly is the cause, but network and/or disk i/o are certainly part of it.

I'm not saying it will make a big difference, but it is good programming practice.  Why search a path for a file when you know where it is?

**Comment by hsbt** [comment]
@MSP-Greg I'm not sure what your motivation about this issue. Do you want a performance improvement? or Coding Style? or other?

If It's performance improvement, I never accept performance changes without benchmark results like Disk I/O, Network, CPU time. We shouldn't relay [Cargo cult programming](https://en.wikipedia.org/wiki/Cargo_cult_programming).

**Comment by MSP-Greg** [comment]
@hsbt

Your 'Cargo cult programming' link doesn't apply here.  This involves one statement, not a pattern strategy or something similar. 

> I never accept performance changes without benchmark results

It should be obvious that system configuration will greatly affect benchmark results.

> The ruby core team

I can also point to issues [8781 Use require_relative() instead of require() if possible](https://bugs.ruby-lang.org/issues/8781) and [12973 [RFC] net/http: use require_relative to reduce syscalls](https://bugs.ruby-lang.org/issues/12973).  In particular, Eric's message in 12973.

In 8781, the main issue against using `require_relative` seems to be what work may be involved if some/all of the files are re-arranged.  I don't think that will be an issue with RG...

**Comment by hsbt** [comment]
@MSP-Greg 

Did you read this? https://bugs.ruby-lang.org/issues/8781#note-26. At least, You should show the benchmark result. When It shows performance improvement, I'm okay to merge its changes.

**Comment by MSP-Greg** [comment]
@hsbt

> Did you read this?

Yes.  That's 5 years old, and states things like 'because Bundler already made require faster in a different way' and 'Use Bundler'.  What if one isn't using bundler?

Eric's post is much newer.

Today, SSD's are certainly faster than mechanical disks, but the use of concurrent apps and multi-threaded apps is probably more common.

Hence, I fall back to:

1. No one has shown `require_relative` to be slower than `require`
2. Eric shows that `require_relative` improves one metric compared to `relative`
3. Why search a path when you don't need to?

Given your (IMO, somewhat rigid) rule structure, I won't bother with a PR here.

You want a benchmark, I'd like a response to point 3...

**Comment by bronzdoc** [comment]
I don't see this going anywhere? lol 

If any of you @MSP-Greg @hsbt take action please reopen :grin:

**Comment by lamont-granquist** [comment]
require_relative is absolutely faster.

benchmarks here:

https://github.com/chef/chef/pull/8508

it gets a lot worse on windows.

**Comment by lamont-granquist** [comment]
Ah I see its buggy until ruby 2.5 per the other issue...
