### ISSUE TITLE
ENOENT when updating from 2.7.6 to 2.7.7

### ISSUE THREAD

**Issue by duckinator** [rubygems/rubygems#2375]
**UPDATE:** Workaround: `gem update --system --install-dir=/usr/local/share/gems --bindir /usr/local/bin`

---

My current problem is upgrading RubyGems 2.7.6 to 2.7.7 results in an `Errno::ENOENT` error when attempting due to system-default `--install-dir`.

## Short Version

- Default gem flags for root, according to `gem env`, are `--install-dir=/usr/local/share/gems --bindir /usr/local/bin`.
- `sudo gem update --system` expects `/usr/share/gems/gems/rubygems-update-2.7.7` to exist.
- `sudo gem update --system` actually puts it in `/usr/local/share/gems/gems/rubygems-update-2.7.7`.
- RubyGems thus fails to find it, and the entire upgrade fails.

I did not set this default, and I am unsure where my system is finding it.

## System Information

- Fedora 28
- Ruby 2.5.1p57 (installed from the official repos)
- RubyGems 2.7.6 (installed from the official repos)
- No gemrc anywhere in /root or /etc.
- No environment variables including the words `RUBY` or `GEM`.

## Details

Output from the attempt:

```
~$ sudo gem update --system
Updating rubygems-update
Successfully installed rubygems-update-2.7.7
Parsing documentation for rubygems-update-2.7.7
Done installing documentation for rubygems-update after 0 seconds
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ dir_chdir - /usr/share/gems/gems/rubygems-update-2.7.7
~$
```

It appears to originate in the `Gem::Commands::UpdateCommand#install_rubygems` function:

https://github.com/rubygems/rubygems/blob/5971b486d4dbb2bad5d3445b3801c456eb0ce183/lib/rubygems/commands/update_command.rb#L154-L169

According to the error, it wants: `/usr/share/gems/gems/rubygems-update-2.7.7`
However, it winds up installing it to: 

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.6
```

<details>
<summary>Full `gem env` output.</summary>

```
$ sudo gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.6
  - RUBY VERSION: 2.5.1 (2018-03-29 patchlevel 57) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/share/gems
  - USER INSTALLATION DIRECTORY: /root/.gem/ruby
  - RUBY EXECUTABLE: /usr/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/share/gems
     - /root/.gem/ruby
     - /usr/local/share/gems
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--install-dir=/usr/local/share/gems --bindir /usr/local/bin"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin

~$ 
```
<details>

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by MSP-Greg** [comment]
Interesting.  I did the same thing on Windows, except I did:

```
gem install rubygems-update
ruby update_rubygems
```

And I believe that worked.  It's an update script that I use when I want to reset my ruby installs.  It works, so I've never tried `gem update --system`...

**Comment by duckinator** [comment]
Looks like both `Gem.paths` and `RbConfig::CONFIG` include references to `/usr/share/gems`.

And, given that `Gem.dir` is just `Gem.paths.home`, that means it's ultimately coming from `Gem.paths`.

Miscellaneous results from poking around in irb:

```
~$ sudo irb
irb(main):001:0> Gem.dir                                                       
=> "/usr/share/gems"
irb(main):002:0> Gem.paths
=> #<Gem::PathSupport:0x000055d7b53b4ee8 @home="/usr/share/gems", @path=["/root/.gem/ruby", "/usr/share/gems", "/usr/local/share/gems"], @spec_cache_dir="/root/.gem/specs">
irb(main):003:0> pp RbConfig::CONFIG.select { |k, v| v.include?("local") && k != "configure_args" }; nil
{"sitearchdir"=>"/usr/local/lib64/ruby/site_ruby",                                  
 "sitelibdir"=>"/usr/local/share/ruby/site_ruby",
 "sitedir"=>"/usr/local/share/ruby/site_ruby",                                      
 "localedir"=>"/usr/share/locale"}                                                  
=> nil
irb(main):004:0> puts RbConfig::CONFIG["configure_args"].split("'").map(&:strip).reject(&:empty?)                                                                        
--build=x86_64-redhat-linux-gnu                                                     
--host=x86_64-redhat-linux-gnu
--program-prefix=
--disable-dependency-tracking
--prefix=/usr
--exec-prefix=/usr
--bindir=/usr/bin
--sbindir=/usr/sbin
--sysconfdir=/etc
--datadir=/usr/share
--includedir=/usr/include
--libdir=/usr/lib64
--libexecdir=/usr/libexec
--localstatedir=/var
--sharedstatedir=/var/lib
--mandir=/usr/share/man
--infodir=/usr/share/info
--with-rubylibprefix=/usr/share/ruby
--with-archlibdir=/usr/lib64
--with-rubyarchprefix=/usr/lib64/ruby
--with-sitedir=/usr/local/share/ruby/site_ruby
--with-sitearchdir=/usr/local/lib64/ruby/site_ruby
--with-vendordir=/usr/share/ruby/vendor_ruby
--with-vendorarchdir=/usr/lib64/ruby/vendor_ruby
--with-rubyhdrdir=/usr/include
--with-rubyarchhdrdir=/usr/include
--with-sitearchhdrdir=$(sitehdrdir)/$(arch)
--with-vendorarchhdrdir=$(vendorhdrdir)/$(arch)
--with-rubygemsdir=/usr/share/rubygems
--with-ruby-pc=ruby.pc
--with-compress-debug-sections=no
--disable-rpath
--enable-shared
--with-ruby-version=
--enable-multiarch
--with-prelude=./abrt_prelude.rb
build_alias=x86_64-redhat-linux-gnu
host_alias=x86_64-redhat-linux-gnu
CFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
LDFLAGS=-Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld
CXXFLAGS=-O2 -g -pipe -Wall -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection
=> nil
```

**Comment by duckinator** [comment]
My other system updated fine. Summary of what I've found so far is below.

Works:

- Fedora 27
- Ruby 2.4.4p296
- RubyGems 2.7.6 (installed 2.6.14 from the official repos, and updated previously using `gem update --system`)

Does not work:

- Fedora 28
- Ruby 2.5.1p57 (installed from the official repos)
- RubyGems 2.7.6 (installed from the official repos)

Notable differences:

- Fedora releases.
- Ruby versions.

**Comment by duckinator** [comment]
I did some more poking around.

Here's a summary of what happens, as best as I can tell:

1. The location of the file is dictated by `Gem.dir`, which is just a call to `Gem.paths.home`.
2. `Gem.paths.home` is controlled by the `GEM_HOME` environment variable.
3. When using sudo, `GEM_HOME` is unset, so it uses [`Gem.default_dir`](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/defaults.rb#L26-L53).
4. On the system in question, `Gem.default_dir` does not exist.

And some notes regarding `Gem.default_dir`:

1. RubyGems 2.7.6 + Ruby 2.5.1p57 on Fedora 28 exhibits this problem.
2. RubyGems 2.7.6 + Ruby 2.4.4p296 on Fedora 27 does not exhibit this problem.
3. There were no changes to `Gem.default_dir` between those versions.

Given all of this, **my current suspicion is that the problem is caused by build flags Fedora uses or previously used for Ruby, and how those are exposed via `RbConfig::CONFIG`.**

**Comment by duckinator** [comment]
Also encountering an issue on this with RubyGems 2.7.6 + Ruby 2.5.3p105 on Fedora 29.

**Comment by duckinator** [comment]
I figured out a workaround!

As I mentioned in the original issue description, `gem env` says that for root the default gem flags are `--install-dir=/usr/local/share/gems --bindir /usr/local/bin`.

Passing those after `gem update --system` makes it work.

So, all I had to do is: `gem update --system --install-dir=/usr/local/share/gems --bindir /usr/local/bin`

**Comment by duckinator** [comment]
As a note, `--system` causes the `gem update` command to split into a completely separate execution path.

* Without `--system`: https://github.com/rubygems/rubygems/blob/master/lib/rubygems/commands/update_command.rb#L93-L119
* With `--system`: https://github.com/rubygems/rubygems/blob/master/lib/rubygems/commands/update_command.rb#L239-L252

**Comment by duckinator** [comment]
Upgrading to 3.0.3 just now, I had to do:

```
gem update --system --install-dir=/usr/share/gems --bindir /usr/local/bin
```

Same workaround, different directory.

I have no idea why. :woman_shrugging:

**Comment by bronzdoc** [comment]
Closing since it seems you found a workaround

**Comment by sarahscheffler** [comment]
FYI: I had the same issue just now, updating to 3.0.3, on Fedora 29.  The workaround posted by @duckinator on 3/29 worked for me.

**Comment by duckinator** [comment]
While working on a different issue, I unintentionally found a testcase for this using Docker:

This:
`docker run --rm -it fedora /bin/bash -c 'dnf install -y ruby rubygems && gem update --system'`

Results in this output (ignoring all the dnf-related output above it):

```
Updating rubygems-update
Fetching rubygems-update-3.1.1.gem
Successfully installed rubygems-update-3.1.1
Parsing documentation for rubygems-update-3.1.1
Installing ri documentation for rubygems-update-3.1.1
Installing darkfish documentation for rubygems-update-3.1.1
Done installing documentation for rubygems-update after 57 seconds
Parsing documentation for rubygems-update-3.1.1
Done installing documentation for rubygems-update after 0 seconds
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ dir_chdir - /usr/share/gems/gems/rubygems-update-3.1.1
```

Whereas using my workaround above works:

`docker run --rm -it fedora /bin/bash -c 'dnf install -y ruby rubygems && gem update --system --install-dir=/usr/share/gems --bindir /usr/local/bin'`
