### ISSUE TITLE
SSL_connect error when uploading a gem to Nexus

### ISSUE THREAD

**Issue by chortels** [rubygems/rubygems#2376]
I'm having a problem or would like to suggest a feature.

My current problem is that, when I try to upload a gem to Nexus from Jenkins, the job returns me this error: 

ERROR:  While executing gem ... (OpenSSL::SSL::SSLError)
    SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol

I don't know what's causing this issue, because yesterday I was able to work with Jenkins, RubyGems and Nexus with no problems. 

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [x ] Publishing a library
  - [x ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version

YAML safe loading is not available. Please upgrade psych to a version that supports safe loading (>= 2.0).
2.7.7


I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by colby-swandale** [comment]
Please see [our guide on TLS issues](https://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html)

**Comment by chortels** [comment]
Hi @colby-swandale, thanks for your response. Yesterday I followed that guide and, after installing the latest versions of ruby and gems I was able to upload a gem with root user. However, I can't upload the same gem when trying with a non-root user, because I obtain the following message: 

ERROR:  While executing gem ... (OpenSSL::SSL::SSLError)
    SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: unknown protocol

It sounds strange to me that a connection problem happen depending on the user I'm working with.

**Comment by colby-swandale** [comment]
The first thing that pops into my mind is that the `root` user and the normal user are running 2 different versions of Ruby. And the version of Ruby that the normal user is being linked an old version of OpenSSL that does not support TLS 1.2.

What's the full output when you run the TLS script for both the `root` user and the normal user?

**Comment by chortels** [comment]
Hi @colby-swandale . Sorry for my late answer. I've checked that non-root and root user are both using the same version of Ruby (2.5.1p57) and Gems (2.7.7).

**Comment by colby-swandale** [comment]
Can you provide the output of the [TLS Check](https://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html#automated-ssl-check) for both `sudo` and a regular user?

**Comment by colby-swandale** [comment]
ping @chortels

**Comment by bronzdoc** [comment]
Closing for lack of respone, we'll reopen the issue if you provide what Colby asked, thanks.
