### ISSUE TITLE
Instructions on updating OpenSSL removed from Troubleshooting guide

### ISSUE THREAD

**Issue by johnavink** [rubygems/rubygems#2385]
Using the troubleshooting guide at <https://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html>, I determined that I had an old version of OpenSSL:

```
> ruby -ropen-uri -e 'eval open("https://git.io/vQhWq").read'
Here's your Ruby and OpenSSL environment:

Ruby:           2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
RubyGems:       2.0.14.1
Compiled with:  OpenSSL 0.9.8zc 19 Mar 2015
Loaded version: OpenSSL 0.9.8zh 14 Jan 2016
SSL_CERT_FILE:  /System/Library/OpenSSL/cert.pem
SSL_CERT_DIR:   /System/Library/OpenSSL/certs

With that out of the way, let's see if you can connect to rubygems.org...

Bundler connection to rubygems.org:       failed  ❌  (uninitialized constant Bundler)
RubyGems connection to rubygems.org:      failed  ❌  (SSL/TLS protocol version mismatch)
Ruby net/http connection to rubygems.org: failed  ❌

Unfortunately, this Ruby can't connect to rubygems.org. 😡
Your Ruby can't connect to rubygems.org because your version of OpenSSL is too old. You'll need to upgrade your OpenSSL install and/or recompile Ruby to use a newer OpenSSL.

```

The guide then says "The instructions in this guide can help you troubleshoot both problems."  However, there are absolutely no instructions on how I can update my OpenSSL.

**Comment by indirect** [comment]
@johnavink the openssl version is typically set when your ruby is compiled. If you are on a mac, you can install a newer Ruby with a newer OpenSSL using Homebrew, ruby-build, or ruby-install.

**Comment by colby-swandale** [comment]
We should add a section that talks updating OpenSSL but the amount we would support/document would have to be very little. installing versions of OpenSSL that is not available in your OS package manager and getting Ruby to link against that can be a very deep rabbit hole.

**Comment by bronzdoc** [comment]
@johnavink How to update  your OpenSSL is out of the scope of rubygems.
