### ISSUE TITLE
install timeout when connecting through vpn

### ISSUE THREAD

**Issue by sadtoot** [rubygems/rubygems#2389]
I'm having a problem

after some trial and error, it seems that no gems will install while my vpn (private internet access) is connected.

This issue is related to:

  - [X] Network problems
  - [X] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.6
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by colby-swandale** [comment]
There is very little information to go on to let us help you. Can you please provide more information about what the problem you're having is. What errors are you encountering?

I would also check your environment and make sure that you have an internet connection that is not blocking RubyGems.

**Comment by colby-swandale** [comment]
It looks like your connection is blocking Rubygems' connection to RubyGems.org. Can you download the file outside of Rubygems?

**Comment by bronzdoc** [comment]
ping @sadtoot

**Comment by colby-swandale** [comment]
Closing due to lack of response.
