### ISSUE TITLE
I can't install a gem that I just push

### ISSUE THREAD

**Issue by LucasAndrad** [rubygems/rubygems#2398]
I just published this question on StackOverflow:

I just published my gem at rubygems.org, [here is the link](https://rubygems.org/gems/uix_validations/). Everything looks nice.

But when I try to add to a project with `gem 'uix_validations', '~> 0.5.0'`, I got this error at bundle install:

    Could not find gem 'uix_validations (~> 0.5.0)' in any of the gem sources listed
    in your Gemfile

And I have no idea how to fix this.

I published using this steps:

    gem build uix_validations.gemspec

This generate a file: `uix_validations-0.5.0.gem`

And to publish:

    gem push uix_validations-0.5.0.gem

**My problem has any relation with this?**
![problem_rubygems-org](https://user-images.githubusercontent.com/17948392/45600874-68610d00-b9da-11e8-8627-791ce6fa429e.png)

**Comment by colby-swandale** [comment]
Your gem has been published but you need to wait for RubyGems.org to refresh it's cache. It should only take a short while.
