### ISSUE TITLE
Shouldn't allow common misspellings of bundler to be downloaded without a warning

### ISSUE THREAD

**Issue by zachaysan** [rubygems/rubygems#2400]
I almost accidentally mis-typed `gem install bundler`. I then realized that there could be other people that do this, and if they did, it would be easy to for an attacker to also download the real bundler. And just alias it to act like normal. Since being asked for sudo when installing stuff via bundler is possible (to download a shared library, say) this could be a way to gain root. Also, unlike gems in Gemfiles, bundler is often installed on the fly.

I looked for a couple common misspellings at rubygems.com and I found [this](https://rubygems.org/gems/bunlder/) package, and other [hostile ones](https://rubygems.org/gems/better_date_to_s) by the same author. Gems shouldn't attack, no matter what warnings come in the description. Users do not look up gems before installing them.

As an aside, rubygems.org should always have a way of investigating the source of a gem (including hooks) without downloading it. I'm not going to run a gem install command just to check out its source. Also, it's probably smart to write a tool to look for other gems that rely on common misspellings, but bundler is the worst contender. 

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [x] Other

Here are my current environment details:

```
$ gem env version
2.7.7
```

I, of course, will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by indirect** [comment]
Thanks for the report! We'll investigate the gems you mentioned. If you want to view the contents of a gem without installing it, you can either download the .gem file from rubygems.org using your browser, or use the `gem fetch` and `gem unpack` commands.

We are actively working on blocking typosquats right now, in these previously opened issues:

https://github.com/rubygems/rubygems.org/issues/1777
https://github.com/rubygems/rubygems.org/issues/1776

If you're willing, we would love to have your help setting up RubyGems.org to protect Ruby developers from these kind of malicious gems in the future!
