### ISSUE TITLE
SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert access denied

### ISSUE THREAD

**Issue by noorul9001** [rubygems/rubygems#2401]
I'm having a problem

My current problem is as below.
>gem update --system
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=SSLv2/v3 read server hello A: tlsv1 alert access denied (https://api.rubygems.org/specs.4.8.gz)

I have tried the suggestion here(https://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html#updating-rubygems)  but it i'm still having same error when i'm running the gem commands.
My initial objectives is to install the rails and i'm using Windows platform
$gem install rails

Please help!
This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [/] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
C:\Users\nmathussin>gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.7
  - RUBY VERSION: 2.4.4 (2018-03-28 patchlevel 296) [x64-mingw32]
  - INSTALLATION DIRECTORY: C:/Ruby24-x64/lib/ruby/gems/2.4.0
  - USER INSTALLATION DIRECTORY: C:/Users/nmathussin/.gem/ruby/2.4.0
  - RUBY EXECUTABLE: C:/Ruby24-x64/bin/ruby.exe
  - EXECUTABLE DIRECTORY: C:/Ruby24-x64/bin
  - SPEC CACHE DIRECTORY: C:/Users/nmathussin/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: C:/ProgramData
  - RUBYGEMS PLATFORMS:
    - ruby
    - x64-mingw32
  - GEM PATHS:
     - C:/Ruby24-x64/lib/ruby/gems/2.4.0
     - C:/Users/nmathussin/.gem/ruby/2.4.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - c:\program files (x86)\common files\oracle\java\javapath
     - C:\windows\system32
     - C:\windows
     - C:\windows\system32\wbem
     - C:\windows\system32\windowspowershell\v1.0\
     - c:\program files\hewlett-packard\hp manageability live feed 1.4.0\bin
     - c:\program files\hewlett-packard\hp manageability live feed 1.4.0\tools\boost\lib
     - c:\program files\hewlett-packard\hp manageability live feed 1.4.0\tools\protobuf\lib
     - c:\program files\hewlett-packard\hp manageability live feed 1.4.0\tools\qpid\bin
     - c:\program files\putty\
     - c:\program files\tortoisesvn\bin
     - c:\program files (x86)\symantec\vip access client\
     - C:\Program Files\Java\jdk1.8.0_171\bin
     - C:\Program Files (x86)\scala\bin
     - C:\Program Files\apache-maven-3.5.4\bin
     - c:\program files (x86)\sbt\bin
     - c:\program files (x86)\gow\bin
     - c:\program files\git\cmd
     - c:\windows\system32
     - c:\windows\system32
     - C:\OpenSSL\bin
     - C:\Ruby24-x64\bin
     - C:\Users\nmathussin\AppData\Local\Microsoft\WindowsApps
     - C:\OpenSSL\bin

C:\Users\nmathussin>bundle env
fatal: not a git repository (or any of the parent directories): .git
## Environment

```
Bundler       1.16.2
  Platforms   ruby, x64-mingw32
Ruby          2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]
  Full Path   C:/Ruby24-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      2.7.7
  Gem Home    C:/Ruby24-x64/lib/ruby/gems/2.4.0
  Gem Path    C:/Users/nmathussin/.gem/ruby/2.4.0;C:/Ruby24-x64/lib/ruby/gems/2.4.0
  User Path   C:/Users/nmathussin/.gem/ruby/2.4.0
  Bin Dir     C:/Ruby24-x64/bin
Tools
  Git         2.18.0.windows.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2018-09-19
Git SHA
Released Version  false
```

C:\Users\nmathussin>ruby -ropenssl -e 'puts OpenSSL::OPENSSL_LIBRARY_VERSION'
OpenSSL 1.0.2o  27 Mar 2018
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by MSP-Greg** [comment]
@noorul9001

You've got `C:\OpenSSL\bin` in your path.  I've had conflicts with that building trunk on Appveyor (ruby-loco).

As a test, try renaming the folder (or `C:\OpenSSL`), then running the gem command.  Ruby should be loading the OpenSSL dll's it has, but it would be good to know if this affects it.

Also, the output from [Automated SSL check](https://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html#automated-ssl-check) would be helpful.

**Comment by noorul9001** [comment]
Hi,
Just found out the issue. It turn out the access restricted from my working place network. I tried again the gem install today from my home internet and it installing fine. Not sure why my company network did not allow that.
