### ISSUE TITLE
confirm email link not working. 

### ISSUE THREAD

**Issue by dshelbyo** [rubygems/rubygems#2402]
I'm having a problem

My current problem is creating a rubygems.org account. I clicked on confirm email link in email. When I try to log in I am Still getting error saying I need to authenticate account. 

Clicking on send auth link again, had same issue. 

now when i click on send auth link I do not get the email anymore. 
 

This issue is related to:
  - [ X ] Other
   Rubygems Account Creation 

Here are my current environment details:
      From mac firefox and chrome 

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Please open this issue in https://github.com/rubygems/rubygems.org thanks!
