### ISSUE TITLE
Have a 'includedir' specifier in Gem::Specification.

### ISSUE THREAD

**Issue by v0dro** [rubygems/rubygems#2408]
I would like to suggest a feature.

My current problem is that I need a way to specify C headers for C extensions from other Ruby gems.

This issue is related to Publishing a library

Here are my current environment details:

```
$ gem env version
2.6.14
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

Currently if one Ruby gem depends on the C extension of another Ruby gem, the only way
find the header of that gem is to run a `Gem::Specification.find_by_name` in the `extconf.rb`
of the gem needing the header and then adding the folder containing the header relative to
that path.

This approach is error-prone for three reasons:

* It relies on the gem developer to do the hard work of finding out exactly where the needed header file is located inside the sources of the gem.
* It assumes that the location of header file will never change irrespective of gem releases.
* The gem author then needs to re-dig the sources of the source gem to find where the header is now located.

This is a considerable maintenance burden, especially given that there is no 'standard' way
of keeping public header files for C extensions of ruby gems.

I propose a new approach that will allow a gem developer to specify the path of the public
C header files in a new attribute within `Gem::Specification` in the gemspec of the source
gem. Thus, if someone wants to use the public headers of a gem, they can simply add the
following lines to their extconf.rb:

``` ruby
spec = Gem::Specification.find_by_name 'source-gem-name', 'source-gem-version'
find_header("source_gem.h", *spec.includedir)
```

The way the source gem can specify the header file in their source-gem-name.gemspec can
be like so:

``` ruby
Gem::Specification.new do |spec|
  # lots of other specs
  spec.includedir = ["path/to/headers/1", "path/to/headers/2"]
end
```

**Comment by Hanmac** [comment]
Options/Questions:
* i think it should fall back to ext path, because most gems has header there
* how it is done for prebuild gems? i don't know if they still ship with the header files?

**Comment by v0dro** [comment]
> Options/Questions:
> 
>     i think it should fall back to ext path, because most gems has header there

That seems reasonable. If a gem writer does not specify it, it can fall back to `Gem::Specification.find_by_name('gem-name').gem_dir + "/ext"`.

>     how it is done for prebuild gems? i don't know if they still ship with the header files?

If by pre-built gems you mean the core library, most of the headers can found in the folder pointed to by `RbConfig::CONFIG["includedir"]`.

**Comment by Hanmac** [comment]
with pre-built gems i meant stuff like pre compiled like nokogiri gem on windows, so you don't need to build it yourself.

but it looks like that this still has their header files shipped

**Comment by v0dro** [comment]
Yes. Also I've never come across a use case where one had to access nokogiri's internal structures for any reason so I don't they have a C API that they would want to reveal anyway.

I can make a PR for this issue if you're okay with making this a feature.

**Comment by Hanmac** [comment]
@v0dro nokogiri was only an example because that is one i know is precompiled on windows.

but this also include the header files you want to find

**Comment by v0dro** [comment]
OK I'm trying to write a patch for this feature. So far I've written a `includedir` and `includedir=` method in `specification.rb` file.

However, I'm unable to find exactly where to write the tests. Can you please point me to the correct location?

**Comment by bronzdoc** [comment]
@v0dro i think the test should be in `test_gem_specification.rb`

**Comment by bronzdoc** [comment]
Closing since this has been idle for too long
