### ISSUE TITLE
Using AWS S3 as Gemsource with different auth methods 

### ISSUE THREAD

**Issue by jenshoffmann1331** [rubygems/rubygems#2409]
We tried to use rubygems with its support using AWS S3 as gem source and recognized that the implementation only allows to use an AWS users access key as authentication source. Anyhow, our authentication policy in AWS is role-based using only temporary credentials (that is querying the metadata endpoint with an EC2 instance role receiving access key, access id *and* a session token). The current S3 support in rubygems does not seem to support this authentication method.

It would be nice for us to see this authentication method implemented in rubygems. Do you already have any plans to improve this?

**Comment by bronzdoc** [comment]
> (that is querying the metadata endpoint with an EC2 instance role receiving access key, access id and a session token).

I'm not sure how easy would be to implement that :sweat_smile:

**Comment by colby-swandale** [comment]
This sounds something more suitable for a plugin. having complex authentication logic for specifically AWS does seem like something we want to manage/support.

**Comment by bronzdoc** [comment]
I'm going to close this since is more suitable for a plugin and not a Rubygems feature
