### ISSUE TITLE
Http 403 on gem install nuget

### ISSUE THREAD

**Issue by getsunil** [rubygems/rubygems#2410]
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Forbidden 403 (https://<username>.<api-key>:REDACTED@myorg.jfrog.io/myorg/api/gems/rubygems-org/quick/Marshal.4.8/nuget-4.7.0.gemspec.rz)

using ruby 2.4.4p296 (2018-03-28 revision 63013) [x64-mingw32]

using gem version 2.6.14.1

**Comment by colby-swandale** [comment]
Hi, this is not an error in RubyGems. It seems to be a misconfiguration on your RubyGems server host.
