### ISSUE TITLE
OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate))

### ISSUE THREAD

**Issue by guillaumelebovic** [rubygems/rubygems#2415]
I'm having a trouble with OpenSSL

My current problem is that I cannot connect to any api through https  (i wanted to integrate the geocoder gem) :

here is the display in rails console (it s just an example) :

Loading development environment (Rails 5.0.7)
2.5.1 :001 > require 'open-uri'
 => true 
2.5.1 :002 > p open(URI.encode('https://google.com'))
Traceback (most recent call last):
       16: from /Users/guillaumelebovic/.rvm/gems/ruby-2.5.1/gems/railties-5.0.7/lib/rails/commands/console_helper.rb:9:in `start'
       15: from /Users/guillaumelebovic/.rvm/gems/ruby-2.5.1/gems/railties-5.0.7/lib/rails/commands/console.rb:65:in `start'
       14: from (irb):2
       13: from /Users/guillaumelebovic/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/open-uri.rb:35:in `open'
       12: from /Users/guillaumelebovic/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/open-uri.rb:735:in `open'
       11: from /Users/guillaumelebovic/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/open-uri.rb:165:in `open_uri'
       10: from /Users/guillaumelebovic/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/open-uri.rb:224:in `open_loop'
        9: from /Users/guillaumelebovic/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/open-uri.rb:224:in `catch'
        8: from /Users/guillaumelebovic/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/open-uri.rb:226:in `block in open_loop'
        7: from /Users/guillaumelebovic/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/open-uri.rb:755:in `buffer_open'
        6: from /Users/guillaumelebovic/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/open-uri.rb:337:in `open_http'
        5: from /Users/guillaumelebovic/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:909:in `start'
        4: from /Users/guillaumelebovic/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
        3: from /Users/guillaumelebovic/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/http.rb:981:in `connect'
        2: from /Users/guillaumelebovic/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/protocol.rb:44:in `ssl_socket_connect'
        1: from /Users/guillaumelebovic/.rvm/rubies/ruby-2.5.1/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock'
**OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate))**

Here are my current RubyGems environment details:
RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.7
  - RUBY VERSION: 2.5.1 (2018-03-29 patchlevel 57) [x86_64-darwin17]
  - INSTALLATION DIRECTORY: /Users/guillaumelebovic/.rvm/gems/ruby-2.5.1
  - USER INSTALLATION DIRECTORY: /Users/guillaumelebovic/.gem/ruby/2.5.0
  - RUBY EXECUTABLE: /Users/guillaumelebovic/.rvm/rubies/ruby-2.5.1/bin/ruby
  - EXECUTABLE DIRECTORY: /Users/guillaumelebovic/.rvm/gems/ruby-2.5.1/bin
  - SPEC CACHE DIRECTORY: /Users/guillaumelebovic/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/guillaumelebovic/.rvm/rubies/ruby-2.5.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-17
  - GEM PATHS:
     - /Users/guillaumelebovic/.rvm/gems/ruby-2.5.1
     - /Users/guillaumelebovic/.rvm/gems/ruby-2.5.1@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/opt/openssl/bin
     - /opt/local/bin
     - /opt/local/sbin
     - /Users/guillaumelebovic/.rvm/gems/ruby-2.5.1/bin
     - /Users/guillaumelebovic/.rvm/gems/ruby-2.5.1@global/bin
     - /Users/guillaumelebovic/.rvm/rubies/ruby-2.5.1/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/git/bin
     - /usr/local/mysql/bin
     - /usr/local/mysql/bin
     - /Users/guillaumelebovic/.rvm/bin

## Environment

Here are my current Bundler environment details:

```
Bundler             1.16.4
  Platforms         ruby, x86_64-darwin-17
Ruby                2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
  Full Path         /Users/guillaumelebovic/.rvm/rubies/ruby-2.5.1/bin/ruby
  Config Dir        /Users/guillaumelebovic/.rvm/rubies/ruby-2.5.1/etc
RubyGems            2.7.7
  Gem Home          /Users/guillaumelebovic/.rvm/gems/ruby-2.5.1
  Gem Path          /Users/guillaumelebovic/.rvm/gems/ruby-2.5.1:/Users/guillaumelebovic/.rvm/gems/ruby-2.5.1@global
  User Path         /Users/guillaumelebovic/.gem/ruby/2.5.0
  Bin Dir           /Users/guillaumelebovic/.rvm/gems/ruby-2.5.1/bin
Tools               
  Git               2.15.2 (Apple Git-101.1)
  RVM               1.29.4 (latest)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2018-08-20
Git SHA           a356d8cf9
Released Version  true
```

## Bundler settings

```
build.pg
  Set for the current user (/Users/guillaumelebovic/.bundle/config): "--with-pg-config=/Applications/Postgres.app/Contents/Versions/9.3/bin/pg_config"
build.puma
  Set for the current user (/Users/guillaumelebovic/.bundle/config): "--with-opt-dir=/usr/local/opt/openssl"
```

### Gemfile

```ruby
source 'https://rubygems.org'

git_source(:github) do |repo_name|
  repo_name = "#{repo_name}/#{repo_name}" unless repo_name.include?("/")
  "https://github.com/#{repo_name}.git"
end


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '~> 5.0.7'
# Use postgresql as the database for Active Record
gem 'pg', '>= 0.18', '< 2.0'
# Use Puma as the app server
gem 'puma', '~> 3.0'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.2'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes navigating your web application faster. Read more: https://github.com/turbolinks/turbolinks
gem 'turbolinks', '~> 5'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.5'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 3.0'
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

gem "jsonapi-resources"
gem 'rack-cors'
gem 'devise'
gem 'exception_notification'
gem "ransack"
gem 'stripe'
gem 'doorkeeper'
gem 'geocoder'
gem 'railties'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug', platform: :mri
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> anywhere in the code.
  gem 'web-console', '>= 3.3.0'
  gem 'listen', '~> 3.0.5'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
  gem 'spring-watcher-listen', '~> 2.0.0'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: [:mingw, :mswin, :x64_mingw, :jruby]
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.0.7)
      actionpack (= 5.0.7)
      nio4r (>= 1.2, < 3.0)
      websocket-driver (~> 0.6.1)
    actionmailer (5.0.7)
      actionpack (= 5.0.7)
      actionview (= 5.0.7)
      activejob (= 5.0.7)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.0.7)
      actionview (= 5.0.7)
      activesupport (= 5.0.7)
      rack (~> 2.0)
      rack-test (~> 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.0.7)
      activesupport (= 5.0.7)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.0.7)
      activesupport (= 5.0.7)
      globalid (>= 0.3.6)
    activemodel (5.0.7)
      activesupport (= 5.0.7)
    activerecord (5.0.7)
      activemodel (= 5.0.7)
      activesupport (= 5.0.7)
      arel (~> 7.0)
    activesupport (5.0.7)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    arel (7.1.4)
    bcrypt (3.1.12)
    bindex (0.5.0)
    builder (3.2.3)
    byebug (10.0.2)
    coffee-rails (4.2.2)
      coffee-script (>= 2.2.0)
      railties (>= 4.0.0)
    coffee-script (2.4.1)
      coffee-script-source
      execjs
    coffee-script-source (1.12.2)
    concurrent-ruby (1.0.5)
    crass (1.0.4)
    devise (4.5.0)
      bcrypt (~> 3.0)
      orm_adapter (~> 0.1)
      railties (>= 4.1.0, < 6.0)
      responders
      warden (~> 1.2.3)
    doorkeeper (5.0.0)
      railties (>= 4.2)
    erubis (2.7.0)
    exception_notification (4.2.2)
      actionmailer (>= 4.0, < 6)
      activesupport (>= 4.0, < 6)
    execjs (2.7.0)
    faraday (0.15.2)
      multipart-post (>= 1.2, < 3)
    ffi (1.9.25)
    geocoder (1.5.0)
    globalid (0.4.1)
      activesupport (>= 4.2.0)
    i18n (1.1.0)
      concurrent-ruby (~> 1.0)
    jbuilder (2.7.0)
      activesupport (>= 4.2.0)
      multi_json (>= 1.2)
    jquery-rails (4.3.3)
      rails-dom-testing (>= 1, < 3)
      railties (>= 4.2.0)
      thor (>= 0.14, < 2.0)
    jsonapi-resources (0.9.3)
      activerecord (>= 4.1)
      concurrent-ruby
      railties (>= 4.1)
    listen (3.0.8)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    loofah (2.2.2)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.0)
      mini_mime (>= 0.1.1)
    method_source (0.9.0)
    mini_mime (1.0.1)
    mini_portile2 (2.3.0)
    minitest (5.11.3)
    multi_json (1.13.1)
    multipart-post (2.0.0)
    nio4r (2.3.1)
    nokogiri (1.8.4)
      mini_portile2 (~> 2.3.0)
    orm_adapter (0.5.0)
    pg (1.1.2)
    puma (3.12.0)
    rack (2.0.5)
    rack-cors (1.0.2)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (5.0.7)
      actioncable (= 5.0.7)
      actionmailer (= 5.0.7)
      actionpack (= 5.0.7)
      actionview (= 5.0.7)
      activejob (= 5.0.7)
      activemodel (= 5.0.7)
      activerecord (= 5.0.7)
      activesupport (= 5.0.7)
      bundler (>= 1.3.0)
      railties (= 5.0.7)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.0.4)
      loofah (~> 2.2, >= 2.2.2)
    railties (5.0.7)
      actionpack (= 5.0.7)
      activesupport (= 5.0.7)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (12.3.1)
    ransack (2.0.1)
      actionpack (>= 5.0)
      activerecord (>= 5.0)
      activesupport (>= 5.0)
      i18n
    rb-fsevent (0.10.3)
    rb-inotify (0.9.10)
      ffi (>= 0.5.0, < 2)
    responders (2.4.0)
      actionpack (>= 4.2.0, < 5.3)
      railties (>= 4.2.0, < 5.3)
    sass (3.5.7)
      sass-listen (~> 4.0.0)
    sass-listen (4.0.0)
      rb-fsevent (~> 0.9, >= 0.9.4)
      rb-inotify (~> 0.9, >= 0.9.7)
    sass-rails (5.0.7)
      railties (>= 4.0.0, < 6)
      sass (~> 3.1)
      sprockets (>= 2.8, < 4.0)
      sprockets-rails (>= 2.0, < 4.0)
      tilt (>= 1.1, < 3)
    spring (2.0.2)
      activesupport (>= 4.2)
    spring-watcher-listen (2.0.1)
      listen (>= 2.7, < 4.0)
      spring (>= 1.2, < 3.0)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    stripe (3.25.0)
      faraday (~> 0.10)
    thor (0.20.0)
    thread_safe (0.3.6)
    tilt (2.0.8)
    turbolinks (5.2.0)
      turbolinks-source (~> 5.2)
    turbolinks-source (5.2.0)
    tzinfo (1.2.5)
      thread_safe (~> 0.1)
    uglifier (4.1.18)
      execjs (>= 0.3.0, < 3)
    warden (1.2.7)
      rack (>= 1.0)
    web-console (3.7.0)
      actionview (>= 5.0)
      activemodel (>= 5.0)
      bindex (>= 0.4.0)
      railties (>= 5.0)
    websocket-driver (0.6.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.3)

PLATFORMS
  ruby

DEPENDENCIES
  byebug
  coffee-rails (~> 4.2)
  devise
  doorkeeper
  exception_notification
  geocoder
  jbuilder (~> 2.5)
  jquery-rails
  jsonapi-resources
  listen (~> 3.0.5)
  pg (>= 0.18, < 2.0)
  puma (~> 3.0)
  rack-cors
  rails (~> 5.0.7)
  railties
  ransack
  sass-rails (~> 5.0)
  spring
  spring-watcher-listen (~> 2.0.0)
  stripe
  turbolinks (~> 5)
  tzinfo-data
  uglifier (>= 1.3.0)
  web-console (>= 3.3.0)

BUNDLED WITH
   1.16.4
```
##########

here is the output when i do :
ruby -ropenssl -e 'puts OpenSSL::OPENSSL_LIBRARY_VERSION'

OpenSSL 1.0.2p  14 Aug 2018

Does anyone have the same issue (and hopefully a way to fix it?)
I tried everything on this page without any success :  
https://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html#troubleshooting-certificate-errors

Many thanks

**Comment by bronzdoc** [comment]
@guillaumelebovic is this still an issue for you?

**Comment by guillaumelebovic** [comment]
Hello,

Yes it is!

Kind regards

**Comment by djberg96** [comment]
So you can install gems without issue, it's just the `open` call that's failing? Are you able to `curl https://google.com`?

**Comment by guillaumelebovic** [comment]
Yes exactly, I don't understand, I can do:
> open('https://google.com')
 => #<Tempfile:/var/folders/py/km6ph1rx7hs2pf1w41279ys80000gn/T/open-uri20181009-8625-grd3in> 

**But it fails with :** 
uri = URI('https://google.com')
        Net::HTTP.start(uri.host, uri.port,
          :use_ssl => true) do |http|
          request = Net::HTTP::Get.new uri
          response = http.request request 
        end

I still get the following :

**OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed (unable to get local issuer certificate))**

**Comment by bronzdoc** [comment]
Closing due to lack of response

**Comment by alomau-hctv** [comment]
```
curl -fsSL curl.haxx.se/ca/cacert.pem -o "$(ruby -ropenssl -e 'puts OpenSSL::X509::DEFAULT_CERT_FILE')"
```
Worked for me.

**Comment by jepunband** [comment]
help please .. i'm getting this error:  OpenSSL::SSL::SSLError SSL_connect returned=1 errno=0 state=error: certificate verify failed.

tried this solution here, but it did not work for me. :https://www.engineyard.com/blog/ruby-ssl-error-certificate-verify-failed

Auxiliary failed: 
[-] Call stack:
[-]   /opt/metasploit-framework/embedded/lib/ruby/2.4.0/net/protocol.rb:44:in `connect_nonblock'
[-]   /opt/metasploit-framework/embedded/lib/ruby/2.4.0/net/protocol.rb:44:in `ssl_socket_connect'
[-]   /opt/metasploit-framework/embedded/lib/ruby/2.4.0/net/http.rb:948:in `connect'
[-]   /opt/metasploit-framework/embedded/lib/ruby/2.4.0/net/http.rb:887:in `do_start'
[-]   /opt/metasploit-framework/embedded/lib/ruby/2.4.0/net/http.rb:876:in `start'
[-]   /opt/metasploit-framework/embedded/lib/ruby/2.4.0/net/http.rb:1407:in `request'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/gather/shodan_search.rb:59:in `shodan_query'
[-]   /opt/metasploit-framework/embedded/framework/modules/auxiliary/gather/shodan_search.rb:109:in `run'
[*] Auxiliary module execution completed

**Comment by jdittric** [comment]
Try setting SSL's environment variables to the proper location for your distro, e.g.,
CentOS/RHEL:
export SSL_CERT_DIR=/etc/pki/tls/certs
export SSL_CERT_FILE=/etc/pki/tls/cert.pem
Ubuntu/Debian:
export SSL_CERT_DIR=/etc/ssl/certs
export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
This worked for me.

**Comment by aji91** [comment]
Hi everyone,

Am also facing same below error.

**OpenSSL::SSL::SSLError
SSL_connect SYSCALL returned=5 errno=0 state=error: certificate verify failed** 

It's working when I restart the server. After some time it's again started throwing error.

Many thanks

**Comment by mlamei** [comment]
> export SSL_CERT_FILE=

Thank you, what would be the directory for Windows?

**Comment by MSP-Greg** [comment]
@mlamei

This has been closed for a while, if you continue to have problems, an issue should be opened elsewhere.

Windows Ruby versions 2.4 and later should not have any OpenSSL issues, as they bundle certs with the build binary.  With 2.3 and earlier, one needs to obtain a ca cert file, and where it's located is your choice.

Note that Windows Ruby 2.5 is the first version using OpenSSL 1.1.1, so I would recommend that as the minimum version to use.

**Comment by mlamei** [comment]
> @mlamei
> 
> This has been closed for a while, if you continue to have problems, an issue should be opened elsewhere.
> 
> Windows Ruby versions 2.4 and later should not have any OpenSSL issues, as they bundle certs with the build binary. With 2.3 and earlier, one needs to obtain a ca cert file, and where it's located is your choice.
> 
> Note that Windows Ruby 2.5 is the first version using OpenSSL 1.1.1, so I would recommend that as the minimum version to use.

Thank you, I have Ruby 2.3 and I could solve the issue downloading a ca cert file ( https://gist.github.com/fnichol/867550 )

**Comment by chirazbenhassine** [comment]
> Try setting SSL's environment variables to the proper location for your distro, e.g.,
> CentOS/RHEL:
> export SSL_CERT_DIR=/etc/pki/tls/certs
> export SSL_CERT_FILE=/etc/pki/tls/cert.pem
> Ubuntu/Debian:
> export SSL_CERT_DIR=/etc/ssl/certs
> export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt
> This worked for me.

please how i can set SSL's environment variables to the proper location ?

**Comment by alinaMaksumova** [comment]
I had similar issue, together with tinify errors, so had to update it. For macos below commands helped me:

    $	brew upgrade ruby
	$	brew update --system
	$	gem update httpclient
	$	Gem update tinify
	$	brew install openssl
	$	brew link openssl --force

**Comment by kokorolx** [comment]
In my case, change to `rbenv` save my life.

I'm using Macbook M1, OS 13.5.1 (22G90)

**Comment by floricrisostomo** [comment]
Buenos dias,
Tengo este errror al intentar ejecutar una prueba
 SSL_connect returned=1 errno=0 peeraddr=40.126.45.26:443 state=error: certificate verify failed (unable to get local issuer certificate) (RestClient::SSLCertificateNotVerified)
Por favor si me pueden ayudar

**Comment by deivid-rodriguez** [comment]
Check out https://github.com/rubygems/ruby-ssl-check, quizás te ayude! 👍

**Comment by TallNutAlt** [comment]
> Buenos dias, Tengo este errror al intentar ejecutar una prueba
> 
> SSL_connect returned=1 errno=0 peeraddr=40.126.45.26:443 state=error: certificate verify failed (unable to get local issuer certificate) (RestClient::SSLCertificateNotVerified)
> 
> Por favor si me pueden ayudar

Have you solved the same problem
