### ISSUE TITLE
Remove support for SRV records

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems#2418]
Today, RubyGems [uses SRV DNS records to change API endpoint domains](https://github.com/rubygems/rubygems/blob/1923fb0603208f7a4fa2ee384f454d662e114d75/lib/rubygems/remote_fetcher.rb#L105-L117). That has turned out to a huge security headache, and also we don't actually use that ability anymore—everything is served directly from rubygems.org. Let's remove it.

**Comment by bronzdoc** [comment]
@arlandism that's great! thanks!

**Comment by bronzdoc** [comment]
closed by https://github.com/rubygems/rubygems/pull/2433
