### ISSUE TITLE
ERROR: While executing gem ... (errno: : ENOENT)

### ISSUE THREAD

**Issue by Kasperait** [rubygems/rubygems#2431]
I'll try to explain in more detail, plus I'll attach a photo. When installing rubygems originally wrote (lib). I thought that it is worth copying the lib folder and to throw in the specified folder, but after I again decided to try to install rubygems, and here I began to write that I need to throw in a folder some exe file. But what I do not know, I do not even know what I did right that threw (lib) in this folder, because I'm new to this. Here is a picture showing the bug:https://imgur.com/a/9hDi3ef
P. S:I need rubygems for metasploit

**Comment by bronzdoc** [comment]
Try executing `rake setup` inside the rubygems directory, and then try again `ruby setup.rb`

**Comment by bronzdoc** [comment]
Closing due to lack of response
