### ISSUE TITLE
Here or ruby/ruby trunk ?

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2445]
@hsbt

From working so much with trunk, I tend to start there.  I suspect trunk will never use RuboCop, but it's used here.

1. Are tests here identical to the trunk test/rubygems test-all tests (assuming everything is 'synced')?

2. I assume the preference is to have commits/PR's done here rather than ruby/ruby?

3. If above is true, same for other std-lib items contained in GitHub Ruby account?  Just looking for yes/no/it's complicated...

4. Should tests be able to be run against an existing install's rubygems files?  I do that with ruby-loco's test-all, needed to patch TestCase for cert & pem paths, etc.

Sorry for the ping, but I suspect you're the person with the answers.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
>Are tests here identical to the trunk test/rubygems test-all tests (assuming everything is 'synced')?

Yes.

> 2\. I assume the preference is to have commits/PR's done here rather than ruby/ruby?

Please send a patch in this repository. `ruby/ruby` is not the upstream repository for rubygems.

> 3\. If above is true, same for other std-lib items contained in GitHub Ruby account?

Maybe, Yes. Because it's work in progress.

> 4\. Should tests be able to be run against an existing install's rubygems files?  I do that with ruby-loco's test-all, needed to patch TestCase for cert & pem paths, etc.

Wthat's mean `an existing install's rubygems files?`? I know your project named `ruby-loco`, But I have no responsibility to maintain it and I didn't know its goal.

**Comment by MSP-Greg** [comment]
Thanks for the answers.

Re  "an existing install's rubygems files?", if I run `rake test` on this repo, it tests the files within the repo.  If I run `test-all` with the rubygems folder in ruby/ruby, it tests the files in that repo.

What if one wants to test the files in their install?  That is what I'm doing in ruby-loco, since MinGW is now tested in trunk, I thought testing the install folder would be better (I use runner.rb).  After all, I don't use the build folder.

Re tests, trunk runs parallel, here they're run random.  Not that I've had issues...

**Comment by bronzdoc** [comment]
I'm going to close this, since is not a Rubygems issue, but you might want to continue the conversation or slack
