### ISSUE TITLE
gem install/update - add --explain-tree option ?

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2459]
Anyone think output like the below would be helpful?  Generated from rails...

```
rails-5.2.1
   actioncable-5.2.1
      nio4r-2.3.1
      websocket-driver-0.7.0
         websocket-extensions-0.1.3
   actionmailer-5.2.1
      mail-2.7.1
         mini_mime-1.0.1
   actionpack-5.2.1
      rack-2.0.6
      rack-test-1.1.0
      rails-dom-testing-2.0.3
         nokogiri-1.8.5-x64-mingw32
            mini_portile2-2.3.0
   actionview-5.2.1
      builder-3.2.3
      erubi-1.7.1
      rails-html-sanitizer-1.0.4
         loofah-2.2.3
            crass-1.0.4
   activejob-5.2.1
      globalid-0.4.1
   activemodel-5.2.1
   activerecord-5.2.1
      arel-9.0.0
   activestorage-5.2.1
      marcel-0.3.3
         mimemagic-0.3.2
   activesupport-5.2.1
      concurrent-ruby-1.1.1
      i18n-1.1.1
      minitest-5.11.3
      tzinfo-1.2.5
         thread_safe-0.3.6
   bundler-1.17.1
   railties-5.2.1
      method_source-0.9.1
      rake-12.3.1
      thor-0.20.0
   sprockets-rails-3.2.1
      sprockets-3.7.2
```

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
I'm going to close this one too @MSP-Greg since i don't see interest in it

**Comment by djberg96** [comment]
Maybe a plugin?

**Comment by MSP-Greg** [comment]
@djberg96

I'm assuming that with Bundler integration, there will be a combining of the two API's re rubygems.org, as has already been discussed re the 'compact_index'. etc.  Hence, maybe once the dust settles...

Generally, the main issue here is trying to improve the CLI so one isn't jumping between using a browser and the console.
