### ISSUE TITLE
gem update - dependencies

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2460]
Should `gem update` check dependencies?  At present, it simply updates installed gems with no regard for their dependencies.  Dependencies can change, and a user might also accidentally remove one...

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by colby-swandale** [comment]
Can you provide an example of this behavior and what you're existing to be doing instead?

**Comment by bronzdoc** [comment]
@MSP-Greg i think that will doing what bundler does? can you answer Colby or can we close this?

Thanks!

**Comment by MSP-Greg** [comment]
@colby-swandale 

Apologies, I must have accidentally marked your msg as read, as I don't recall it.

Some of this issue may  be tied to issues with --explain not correctly reporting what will be updated.

From what I saw, assume I had installed gem 'A' with dependencies 'B,C,D', and the newest version had dependencies of ''C,D,E'.

`gem update` would not install gem 'E'.  If this is intended...

**Comment by MSP-Greg** [comment]
@colby-swandale

I said:
> Some of this issue may be tied to issues with --explain not correctly reporting what will be updated.

I just wrote a test for this, and the issue is `--explain` when used with `gem update`, which is a bit different from the information shown in `gem install`.

When not using `--explain`, `gem install` & `gem update` essentially behave the same.  Or, `gem update` does check the dependencies, but doesn't report them when used with `--explain`.

I think that made sense.  Happy Holidays...

**Comment by MSP-Greg** [comment]
Lot's of commits later. The only issue I haven't checked recently is a `gem update` issue.

Let's say I have gem 1.0 installed, and I do `gem update`, which installs version 2.0.  If 2.0 has different dependencies than 1.0, are they installed?  Obviously, one can use `gem install`.  Closing.
