### ISSUE TITLE
Tests - style(?) changes, failures vs errors, etc

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2467]
I recently came across test code similar to:

```
assert <A should support length>.length > 0
assert <B should support length>.length.zero?
assert_equal 0, <B should support length>.length
```
This could be re-written
```
refute_empty <A should support length>
assert_empty <B should support length>
assert_empty <B should support length>
```

1. Would changes such as this be accepted?
2. Preference for whether they're independent of other changes?

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

Here are my current environment details:

master tests

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by colby-swandale** [comment]
> Would changes such as this be accepted?

Yes

> Preference for whether they're independent of other changes?

Preferably, it would make merging a PR easier.

**Comment by MSP-Greg** [comment]
@colby-swandale 

Thanks.  Probably worth mentioning that there may be differences between the assert & refute methods available here (from test gems) and in Ruby trunk.  I've made that mistake before...
