### ISSUE TITLE
severe performance degredation during dependency resolution when sudoing due to not using cache

### ISSUE THREAD

**Issue by znep** [rubygems/rubygems#2475]
We have been seeing it take up to 30 minutes to run `gem install aws-sdk`.  I have narrowed the problem down to running `sudo gem install aws-sdk` with a `HOME` environment variable set to `/home/ubuntu` but being root.  4919512c3aa791b1d99276f900770281bec2bba7 introduced a change to silently skip using the cache if `HOME` does not exist (https://github.com/rubygems/rubygems/blob/2105f5a82885b54959830e594b760a3bbe6c4675/lib/rubygems/remote_fetcher.rb#L295), however the code also has checks
to not update the cache if the home directory is not owned by the current user (https://github.com/rubygems/rubygems/blob/2105f5a82885b54959830e594b760a3bbe6c4675/lib/rubygems/source.rb#L120).  

The net result is it silently doesn't use the cache because `$HOME/.gem` is owned by a different user, so during dependency resolution it repeatedly refetches the gemspecs and because `aws-sdk` has a very large number of dependencies that both takes a very long time and makes an insane number of requests to the rubygems CDN.

I can repro this by just launching an Ubuntu 18.04 LTS AMI in AWS, doing an `sudo apt-get update && sudo apt-get install ruby2.5` then doing a `sudo gem install aws-sdk` as the `ubuntu` user.  It takes ~25 minutes, while if I instead do a `sudo -H gem install aws-sdk` to reset the `HOME` environment variable and use the cache it takes ~2 minutes.  Most of the time difference is spent repeatedly fetching gemspecs during dependency resolution.

I am happy to put together a PR to make this situation better, but to do that I would appreciate some guidance on the desired trade-offs.  One simple fix would just be to print a warning when it can't use the cache.  That would have let us figure out this problem much more quickly and solves my needs as a user, once I know that is the problem it is easy for me to ensure `HOME` is set appropriately.  However, if I were responsible for the CDN infrastructure serving these requests I'd be interested in ensuring client side caching is happening, but that is a user experience trade-off of "it won't work if you don't have a cache" versus "it will work but make a kind of crazy number of requests".

@drbrain FYI 

Here are my current environment details:

```
$ gem env version
2.7.6
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by znep** [comment]
For reference, I just ran it again to count, the `sudo gem install aws-sdk` downloads 184,740 gemspecs from api.rubygems.org.

**Comment by MSP-Greg** [comment]
A warning would certainly be a good idea.   In addition, switching to a tempdir for cache in this situation?

I haven't been in the cache code for a while, so I'm not sure.  Changes could affect the `--user-install` option...

Not part of this issue, but the commit you referenced might have the duplicated code moved to `Gem`, since it is dependent on a `Gem` attribute.

**Comment by maboelnour** [comment]
Any updates relating this issue?
