### ISSUE TITLE
Gem install installs gems to the different directory than current Ruby version

### ISSUE THREAD

**Issue by vifreefly** [rubygems/rubygems#2505]
I'm having a problem or would like to suggest a feature.

My current problem is: `gem` command install gems to the different directory than current ruby version. _Current behavior:_

```
$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux-gnu]

$ sudo gem install nokogiri
...
1 gem installed

$ sudo gem which nokogiri
/var/lib/gems/2.5.0/gems/nokogiri-1.8.5/lib/nokogiri.rb
```

_Expecting behavior:_ **Gems folder should follow the current Ruby version.** For example if Ruby version is 2.5.3, then gems folder should be `/var/lib/gems/2.5.3/gems/`, not `/var/lib/gems/2.5.0/gems/` like now. 

This issue is related to:
  - [x] The command line `gem`

Here are my current environment details:
Linux Ubuntu 18.04 LTS 

```
$ gem env version
2.7.6
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
`2.5.0` is ABI version, not Ruby version. See "ABI compatibility" section on the following document.

https://www.ruby-lang.org/en/news/2013/12/21/ruby-version-policy-changes-with-2-1-0/
