### ISSUE TITLE
Wrong gem build warning for unrestricted dependency

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#2508]
I'm having a problem or would like to suggest a feature.

My current problem is that if you specify an unrestricted dependency in your gemspec, for example `s.add_dependency 'formtastic_i18n'`, `gem build` will include the following warning

```
WARNING:  open-ended dependency on formtastic_i18n (>= 0) is not recommended
  if formtastic_i18n is semantically versioned, use:
    add_runtime_dependency 'formtastic_i18n', '~> 0'
```

This warnings makes no sense to me since as far as I know, it suggests something equivalent to the previous, considered wrong, code.

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [x] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.0.0.beta2
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
closed by https://github.com/rubygems/rubygems/pull/2511
