### ISSUE TITLE
Rubocop 0.61.1 compatible with trunk psych

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2513]
RuboCop 0.61.1 compatible with trunk psych.  Just tested locally, passed.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

Here are my current environment details:

Current trunk

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
You want us to update rubocop to 0.6.11? sorry i don't understand this.

**Comment by deivid-rodriguez** [comment]
Me neither... If you updated rubocop to the latest version locally, I guess you can open a PR directly?

**Comment by MSP-Greg** [comment]
https://travis-ci.org/rubygems/rubygems/jobs/463635817
