### ISSUE TITLE
Allow gem push from Azure DevOps Release Pipeline

### ISSUE THREAD

**Issue by saigkill** [rubygems/rubygems#2522]
´The standard way for pushing a gem to Rubygems.org is:
1.) Prepare a .gem credentials directory
2.) Do a gem push

My current problem is that i want to use Azure DevOps for the test, build and release process in its pipelines. The build and release process happens in a temporary subdirectory. But it looks like it doesn't possible to place a credentials directory inside the build user home place.

This issue is related to:

  - [X] Publishing a library
  - [X] The command line `gem`

A possible solution could be to add a --apikey attribute to the gem push command. Azure provides a variablegroup with possible hidden variables.
So a `gem push mygem.gem --apikey $(apikey)` could be possible without any security breaks.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Hi @saigkill 

> But it looks like it doesn't possible to place a credentials directory inside the build user home place.

what makes it not possible to do that? how is that a Rubygems issue?

**Comment by bronzdoc** [comment]
closing due to lack of response

**Comment by saigkill** [comment]
Hi @bronzdoc 
Sorry for the delay. I was sick,
In general it was just a feature request, a idea for providing a new parameter for the gem binary.
There are many CI services what are providing build pipelines. The new parameter would simplify the gem push process in that pipelines.

**Comment by bronzdoc** [comment]
Ah ok @saigkill !

Maybe you can help me to understand why that can't be done with the current state of rubygems for you?

**Comment by saigkill** [comment]
Hello @bronzdoc ,
thank you for your patience and your reopening of this issue. Please forgive my bad english tongue, but i will try to give my best to show my thoughts.
My current workflow is to add a .gem directory in my local user space and put there a yaml file, what contains just the api key for rubygems.org. Then i use "gem push" for pushing the gem to rubygems.org. 
If i'm using any CI with a build and release pipeline i have two options:
1. prepare a .gem directory online and download that to the pipeline and move that to workers home place
2. prepare a script what creates the needed directory and prepare a yaml file and put that to that direcotry.
Depending on the used CI it can be difficult to store a directory inside a workers home directory. In my case specially Azure DevOps allows to provide build and release pipelines, but a modification of workers home directory isn't easy. I also opened a question on Azure Help forums, but it looks, it isn't easy to use workers directory in that case, what i need.
My idea is to extend the "gem push" command, so it allows to provide the api key as parameter. So it is'nt important, what CI is currently used. I just can provide a step, what pushes the gem after passing the tests.
Do you know, what i mean?

**Comment by bronzdoc** [comment]
ahhh i understand what you mean now, thanks for the clarification @saigkill, sounds reasonable.

**Comment by colby-swandale** [comment]
IMO this shouldn't be a command line option, the API key is just like a password and having an CLI option that takes a value will mean that it will be stored in the terminal history, build information, logs etc.

Instead of taking a string, the option should instead ask for the API key or can be set via an ENV var.

**Comment by saigkill** [comment]
Hi @colby-swandale,
i don't know how other CI handle this. But in Azure you can store the apikey as ENV Variable, what resolved at runtime. Also the ENV Var can be set as invisible, so no one can see it.
With the mentioned terminal history, build Information and logs i'm unsure. I think that These Information are deleted by launching the worker. Must check it.

**Comment by colby-swandale** [comment]
This is not just about CI though, this option would be used generally by people as well.

**Comment by bronzdoc** [comment]
@saigkill you can now use the `GEM_HOST_API_KEY` to solve your issue

**Comment by cyclotron3k** [comment]
Hi @bronzdoc 
Will this feature be made available in 2.x.x, or is this 3.x.x. only?
