### ISSUE TITLE
.gitignore - add lib/rubygems/defaults ?

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2527]
Assuming there is a desire to allow people to easily contribute to RubyGems, sometimes it's helpful to use the actual repo as the source of files, especially if one wants to check against several Ruby versions.

Some builds (including MinGW) add files to `lib/rubygems/defaults` to hook build systems, etc.

Any objections to adding this to `.gitignore`?

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

Here are my current environment details:

```
Multiple
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
What's happened? Please show the reproduce instructions and its results.

**Comment by hsbt** [comment]
Please provided the reproduction instructions. I can do it with my windows environment.

**Comment by MSP-Greg** [comment]
AFAIK, there's two ways to use RG git repo in an existing Ruby install.

1. Either from the command line or thru RUBYOPT, add the RG master lib folder with `-I`.  This does leave the RG files in both install & git repo accessible (they're both in $LOAD_PATH).

2. Remove the RG folders/files from the install, and symlink to the RG git repo items.

I've got lots of Ruby versions on my system, so adding more using the second option is not an issue.  JFYI, the folder names match Appveyor, which makes local testing easier.  I've also got a .ps1 file to switch PATH around...

Hence, to repo, from an install:

a) remove `rubygems.rb`, `ubygems.rb`, and the `rubygems` folder.  

b) add symlinks to the above into the RG git repo.

c) try to build an extension gem

`rubygems/defaults/operating_system` enables the build system, so adding `defaults` to `.gitignore`...

**Comment by hsbt** [comment]
I also have the many of ruby versions, but I never encountered its situation.

So, It seems your environmental problem. It's out of scope from the upstream repository.

**Comment by MSP-Greg** [comment]
> So, It seems your environmental problem.

No.  Been using MSFT OS’s since DOS days, configured lots of PC’s and servers…

Ruby on Windows does not require having build tools in one’s path, and the MSYS2 system may conflict with other software, like Git for Windows (which is built with it).  I prefer to set up my systems the same way normal users would.

That’s what 'defaults/operating_system.rb’ is for.

Maybe /misc and /notes.txt should be removed from .gitignore?
