### ISSUE TITLE
 getting error bundle exec cucumber  command

### ISSUE THREAD

**Issue by umapathireddy** [rubygems/rubygems#2532]
D:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/source/path.rb:199:in `load_spec_files': The path `D:/Jenkins/workspace/SUPA/Hubmodules_supa/com.sap.it.spc.siteadmin.Q2/target/MemphisQ2Utils` does not exist. (Bundler::PathError)
	from D:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/source/path.rb:97:in `local_specs'
	from D:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/source/path.rb:105:in `specs'
	from D:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/definition.rb:587:in `specs_for_source_changed?'
	from D:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/definition.rb:572:in `specs_changed?'
	from D:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/definition.rb:613:in `block in converge_paths'
	from D:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/definition.rb:612:in `any?'
	from D:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/definition.rb:612:in `converge_paths'
	from D:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/definition.rb:108:in `initialize'
	from D:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/dsl.rb:200:in `new'
	from D:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/dsl.rb:200:in `to_definition'
	from D:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/dsl.rb:12:in `evaluate'
	from D:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/definition.rb:33:in `build'
	from D:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler.rb:129:in `definition'
	from D:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler.rb:95:in `setup'
	from D:/Ruby23/lib/ruby/gems/2.3.0/gems/bundler-1.15.4/lib/bundler/setup.rb:19:in `<top (required)>'
	from D:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from D:/Ruby23/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
Build step 'Execute Windows batch command' marked build as failure

**Comment by bronzdoc** [comment]
Closing since this is not a rubygems issue
