### ISSUE TITLE
rubygems-update requires Ruby version >= 2.3.0.

### ISSUE THREAD

**Issue by khiav223577** [rubygems/rubygems#2534]
I'm having a problem or would like to suggest a feature.

My current problem is that I have projects using `travis-ci` to test them under ruby 2.2.
The command `gem update --system` broken after `rubygems` 3.0.0 being released.
https://github.com/rubygems/rubygems/blob/297c725d5051135f4a7ab6425c5a5dd8e34287d5/History.txt#L3

The error messages:
```
gem update --system
Updating rubygems-update
ERROR:  Error installing rubygems-update:
	rubygems-update requires Ruby version >= 2.3.0.
ERROR:  While executing gem ... (NoMethodError)
    undefined method `version' for nil:NilClass
The command "gem update --system" failed and exited with 1 during .

Your build has been stopped.
```

I would like to known how to update `rubygems` to the latest compatible version without throwing errors?

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ ruby --version
ruby 2.2.7p470 (2017-03-28 revision 58194) [x86_64-linux]

$ rvm --version
rvm 1.29.3 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]

$ bundle --version
Bundler version 1.16.0

$ gem env version
2.6.11
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by amatsuda** [comment]
>  would like to known how to update rubygems to the latest compatible version without throwing errors?

I hit the same problem and worked around like this. https://github.com/colszowka/simplecov/commit/ba423820d1d1164fcc038e7b6163b8a96d1786be

**Comment by MSP-Greg** [comment]
RubyGems 3.0.0 is only installable on Ruby >- 2.3

For 2.2 & 2.2.10, try
```
  - gem install "rubygems-update:<3.0.0" --no-document
  - update_rubygems
```

At present, RubyGems does not correctly handle ruby version constraints.

**Comment by hsbt** [comment]
Please use solutions of @amatsuda or @MSP-Greg.

**Comment by PutawanDE** [comment]
I'm having a permission error while running `update_rubygems`.
```
ERROR:  While executing gem ... (Errno::EPERM)
            Operation not permitted @ rb_sysopen - 
        /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/gem
```

So, I install ruby through home brew and force linking instead. https://stackoverflow.com/a/42286604/11968036
