### ISSUE TITLE
test suite & RUBY_VERSION in code

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2540]
While writing tests for PR #2539, I ran into an issue with the following line in `Gem::Util.glob_files_in_dir`:

https://github.com/rubygems/rubygems/blob/eb01ecde57029338477d10fa2154f064111d0100/lib/rubygems/util.rb#L124

`Gem::TestCase` has several methods affecting `RUBY_VERSION`.  If `util_set_RUBY_VERSION` is used in testing and `Gem::Util.glob_files_in_dir` is called, an error may occur.

There's several ways of working around this issue, so I thought an issue would be best...

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

Here are my current environment details:

```
Multiple / RG master
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Whats the error @MSP-Greg ?

**Comment by MSP-Greg** [comment]
@bronzdoc 

Same error as running `ruby -e "puts Dir.glob('**/*gemspec', base: Gem.user_dir)"` with a version of Ruby less than 2.5, where the keyword argument isn't supported.  Since RG is tested on 2.3 & 2.4...

The error is 'TypeError: no implicit conversion of Hash into Integer'

With the tests I wrote, I could get around the issue.  The greater issue is when testing modifies the 'appearance' of the Ruby engine/version, etc, code that relies on correctly knowing that fails...

**Comment by MSP-Greg** [comment]
@bronzdoc 

Add the following file to test/rubygems, run it under Ruby < 2.5 and Ruby >= 2.5, and you'll see the error generated.   As you know, can't attached *.rb files, so a rename is needed...

[test_gem_installer_set.rb.txt](https://github.com/rubygems/rubygems/files/2703572/test_gem_installer_set.rb.txt)

**Comment by bronzdoc** [comment]
@MSP-Greg this one still an issue for you?

**Comment by MSP-Greg** [comment]
@bronzdoc 

I'm here!  I was looking at all my open issues...

Sometime ago the RG tests 'converted' to running random.  There have been several commits addressing problems with interfering tests (which is the issue here).  This issue seems to have been fixed...
