### ISSUE TITLE
Permission error with  bundler installed in a process of `gem update --system`

### ISSUE THREAD

**Issue by Shinpeim** [rubygems/rubygems#2541]
I'm having a problem.

My current problem is that the permission of a bundler installed in a process of `gem update --system` is too strict, so only the user who ran `gem update --system` can run `bundle` but others can't. 

1. Is this a expected behavor?
1. If this is the expected behavor, are there any solutions for this problem?

# How to reproduce the problem

enviroment

```
Amazon linux
ruby 2.5.3 (installed by rbenv)
```

command

```
$ sudo su -

# yum install -y git gcc openssl-devel readline-devel zlib-devel

# cd /usr/local/
# git clone https://github.com/rbenv/rbenv.git
# git clone  https://github.com/rbenv/ruby-build.git rbenv/plugins/ruby-build

# export RBENV_ROOT=/usr/local/rbenv
# export PATH="/usr/local/rbenv/bin:${PATH}"
# eval "$(rbenv init --no-rehash -)"

# rbenv install 2.5.3
# rbenv global 2.5.3

# gem -v
2.7.6
# gem update --system
# gem -v
3.0.0
# bundle -v
Bundler version 1.17.2

# exit

$ export RBENV_ROOT=/usr/local/rbenv
$ export PATH="/usr/local/rbenv/bin:${PATH}"
$ eval "$(rbenv init --no-rehash -)"
$ bundle -v
Traceback (most recent call last):
	4: from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
	3: from <internal:gem_prelude>:2:in `require'
	2: from /usr/local/rbenv/versions/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems.rb:1395:in `<top (required)>'
	1: from /usr/local/rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/usr/local/rbenv/versions/2.5.3/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- rubygems/core_ext/kernel_warn (LoadError)

$ ls -l /usr/local/rbenv/versions/2.5.3/lib/ruby/site_ruby/2.5.0/
合計 76
drwx------ 14 root root  4096 12月 21 05:08 bundler
-rw-r--r--  1 root root 18248 12月 21 05:08 bundler.rb
drwx------ 13 root root  4096 12月 21 05:08 rubygems
-rw-r--r--  1 root root 36966 12月 21 05:08 rubygems.rb
-rw-r--r--  1 root root   548 12月 21 05:08 ubygems.rb
drwxr-xr-x  2 root root  4096 12月 21 05:03 x86_64-linux
```

The permissions of `/usr/local/rbenv/versions/2.5.3/lib/ruby/site_ruby/2.5.0/bundler` and `/usr/local/rbenv/versions/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems` are `0700` so unprivilleged user can't load needed files. 

I got a workarround like below for now but that is bad workarround IMO. Are there any better solutions? Or is this expected behavor?

workarround:

```
$ sudo chmod -R 0755 /usr/local/rbenv/versions/2.5.3/lib/ruby/site_ruby/2.5.0/bundler
$ sudo chmod -R 0755 /usr/local/rbenv/versions/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems
$ bundle -v
Bundler version 1.17.2
```

---

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.0.0
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
This is not a Rubygems issue, is just expected linux behavior? if you install things with root level and then you try to execute a program in a non-root context that interact with things you installed as root things like this will happen. 

Maybe i'm not understanding your use case, but why you have to do the following as root?

```
# cd /usr/local/
# git clone https://github.com/rbenv/rbenv.git
# git clone  https://github.com/rbenv/ruby-build.git rbenv/plugins/ruby-build

# export RBENV_ROOT=/usr/local/rbenv
# export PATH="/usr/local/rbenv/bin:${PATH}"
# eval "$(rbenv init --no-rehash -)"

# rbenv install 2.5.3
# rbenv global 2.5.3

# gem -v
2.7.6
# gem update --system
# gem -v
3.0.0
# bundle -v
Bundler version 1.17.2
```

**Comment by bronzdoc** [comment]
this might be a duplicated of https://github.com/rubygems/rubygems/issues/2535 ?

**Comment by envygeeks** [comment]
You can't upgrade RubyGems without root? And this is *not* expected Linux behavior, the default permissions for Linux are 755, this would have to be a RubyGems bug, somehow unless Linux magically selects *only* bundler-1.17.2 folder to remove all permissions on.

<img width="992" alt="image" src="https://user-images.githubusercontent.com/99763/50347345-da298500-04fa-11e9-902d-e833d282d4e8.png">

**Comment by bronzdoc** [comment]
Ahh thanks for pointing that out @envygeeks that will help me to understand the problem better.

**Comment by hsbt** [comment]
@Shinpeim Can you try the current master branch like [this instructions](https://github.com/rubygems/rubygems/issues/2543#issuecomment-449564989)?

**Comment by bkuhlmann** [comment]
Is this issue not fully resolved yet? I ask because I'm seeing the following issues with my Circle CI builds today:

``` 
#!/bin/bash -eo pipefail
gem update --system
bundle install --path vendor/bundle
Updating rubygems-update
Fetching rubygems-update-3.0.2.gem
Successfully installed rubygems-update-3.0.2
Installing RubyGems 3.0.2
/usr/local/lib/ruby/2.6.0/rubygems/commands/update_command.rb:171: warning: Insecure world writable dir /usr/local/bundle in PATH, mode 042777
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /usr/local/lib/ruby/site_ruby/2.6.0/ubygems.rb
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.org/.
Could not find gem 'bond (~> 0.5)' in any of the gem sources listed in your
Gemfile.
Exited with code 7
```

Note that the builds were passing prior to this [Ruby Gems Status Update](https://status.rubygems.org/incidents/dh3cd8fjd5qw). Maybe they are related? The Circle CI build commands look like this in case it's of interest:

``` 
# Ruby Install
curl https://cache.ruby-lang.org/pub/ruby/${CI_RUBY_VERSION::-2}/ruby-$CI_RUBY_VERSION.tar.bz2 > ../ruby-$CI_RUBY_VERSION.tar.gz
cd ..
tar --extract --bzip2 --verbose --file ruby-$CI_RUBY_VERSION.tar.gz
cd ruby-$CI_RUBY_VERSION
./configure
make
make update-gems
make extract-gems
sudo make install

# Bundler Install
gem update --system
bundle install --path vendor/bundle
```

By the way, do no experience any issues when running locally (macOS - Mojave).

**Comment by envygeeks** [comment]
@bkuhlmann it would seem that error is caused by Circle CI (or you.) You really shouldn't have a world writeable gem folder.  I would escalate an issue with Circle CI, or set GEM_HOME to somewhere in your home directory with good permissions.

**Comment by bkuhlmann** [comment]
:bow: @envygeeks, it looks like Circle CI resolved the issue this morning as rebuilding my various projects is passing again. Sorry for the false alarm but added this to my notes as something to double check in the future.
