### ISSUE TITLE
3.0.0 fails to install on jruby

### ISSUE THREAD

**Issue by andreaseger** [rubygems/rubygems#2542]
My current problem is that `gem update --system` on jruby 9.2.5.0 to rubygems version 3.0.0 fails with the following error:

```
Updating rubygems-update
Fetching: rubygems-update-3.0.0.gem (100%)
Successfully installed rubygems-update-3.0.0
Installing RubyGems 3.0.0
FrozenError: can't modify frozen object
            untaint at org/jruby/RubyKernel.java:2055
          user_home at /var/home/ane/.rbenv/versions/jruby-9.2.5.0/lib/ruby/gems/shared/gems/rubygems-update-3.0.0/lib/rubygems.rb:1067
       default_path at /var/home/ane/.rbenv/versions/jruby-9.2.5.0/lib/ruby/gems/shared/gems/rubygems-update-3.0.0/lib/rubygems/defaults.rb:94
       default_path at /var/home/ane/.rbenv/versions/jruby-9.2.5.0/lib/ruby/gems/shared/gems/rubygems-update-3.0.0/lib/rubygems/path_support.rb:75
     split_gem_path at /var/home/ane/.rbenv/versions/jruby-9.2.5.0/lib/ruby/gems/shared/gems/rubygems-update-3.0.0/lib/rubygems/path_support.rb:67
         initialize at /var/home/ane/.rbenv/versions/jruby-9.2.5.0/lib/ruby/gems/shared/gems/rubygems-update-3.0.0/lib/rubygems/path_support.rb:34
              paths at /var/home/ane/.rbenv/versions/jruby-9.2.5.0/lib/ruby/gems/shared/gems/rubygems-update-3.0.0/lib/rubygems.rb:382
               path at /var/home/ane/.rbenv/versions/jruby-9.2.5.0/lib/ruby/gems/shared/gems/rubygems-update-3.0.0/lib/rubygems.rb:428
               dirs at /var/home/ane/.rbenv/versions/jruby-9.2.5.0/lib/ruby/stdlib/rubygems/defaults/jruby.rb:70
              stubs at /var/home/ane/.rbenv/versions/jruby-9.2.5.0/lib/ruby/gems/shared/gems/rubygems-update-3.0.0/lib/rubygems/specification.rb:826
               _all at /var/home/ane/.rbenv/versions/jruby-9.2.5.0/lib/ruby/gems/shared/gems/rubygems-update-3.0.0/lib/rubygems/specification.rb:747
       latest_specs at /var/home/ane/.rbenv/versions/jruby-9.2.5.0/lib/ruby/gems/shared/gems/rubygems-update-3.0.0/lib/rubygems/specification.rb:1131
  find_latest_files at /var/home/ane/.rbenv/versions/jruby-9.2.5.0/lib/ruby/gems/shared/gems/rubygems-update-3.0.0/lib/rubygems.rb:546
       load_plugins at /var/home/ane/.rbenv/versions/jruby-9.2.5.0/lib/ruby/gems/shared/gems/rubygems-update-3.0.0/lib/rubygems.rb:1111
             <main> at /var/home/ane/.rbenv/versions/jruby-9.2.5.0/lib/ruby/gems/shared/gems/rubygems-update-3.0.0/lib/rubygems/gem_runner.rb:86
            require at org/jruby/RubyKernel.java:983
             (root) at /var/home/ane/.rbenv/versions/jruby-9.2.5.0/lib/ruby/gems/shared/gems/rubygems-update-3.0.0/lib/rubygems/core_ext/kernel_require.rb:1
             <main> at /var/home/ane/.rbenv/versions/jruby-9.2.5.0/lib/ruby/gems/shared/gems/rubygems-update-3.0.0/lib/rubygems/core_ext/kernel_require.rb:54
```

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

```
$ gem env version
2.7.8
$ ruby -v
jruby 9.2.5.0 (2.5.0) 2018-12-06 6d5a228 OpenJDK 64-Bit Server VM 25.191-b12 on 1.8.0_191-b12 [linux-x86_64]
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
I can reproduce this with the given steps

**Comment by headius** [comment]
`Dir.home` appears to be frozen in JRuby. It seems like it ought to be, but I'll figure out why we differ.

**Comment by headius** [comment]
This is due to the fact that JRuby uses the Ruby-facing `ENV` structure to retrieve `HOME` for `Dir.home`. All `ENV` keys and values are frozen strings so `Dir.home`  was returning a frozen string as well. In MRI, the implementation of `Dir.home` calls `getenv` directly from C code, using that result to populate a mutable string for return to the caller.

RubyGems triggers the error by attempting to `untaint` that home directory string.

I have a fix that will dup the `HOME` value so it's mutable but still tainted. This fix will not be released until after the holidays, so we may see additional reports.

It would help us out a lot if we could get some JRuby-related test run into your CI, even if it's just installing RubyGems and running a few sanity checks. As it is, small changes can end up crippling JRuby users, all for want of a few basic tests.

**Comment by headius** [comment]
It may be worth raising this as an issue in MRI, since the trend is for system-related methods like this to return frozen strings, and the overall trend of MRI is toward frozen strings by default. `Dir.home` definitely seems like it *should* be frozen.

**Comment by headius** [comment]
I've made Dir.home return a mutable string for JRuby 9.2.6. The workaround will be required for all JRuby versions to make use of RubyGems 3.0.0.

**Comment by hsbt** [comment]
@headius Do you know the workaround of rubygems side?
