### ISSUE TITLE
RubyGems does not respect GEM_HOME when doing upgrade

### ISSUE THREAD

**Issue by envygeeks** [rubygems/rubygems#2543]
My current problem is RubyGems does not respect GEM_HOME after doing bundle upgrade.

Given you are going from RubyGems 2.7 to 3.0, after you upgrade, if you have GEM_HOME, and GEM_BIN set, to isolate system installed gems from image local gems, RubyGems will instead select the gem installed in the system directory (read: /usr/local/lib/ruby/gems/2.5.0, instead of /usr/gem,) this was discovered while I was investigating why my image https://github.com/envygeeks/jekyll-docker was failing on the recent upgrade.

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/99763/50350903-2b8b4180-0506-11e9-8d58-3f64e2651775.png">
<img width="1340" alt="image" src="https://user-images.githubusercontent.com/99763/50350948-465db600-0506-11e9-91f3-810fa4c70b55.png">

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [x] Other

Here are my current environment details:

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.0
  - RUBY VERSION: 2.5.3 (2018-10-18 patchlevel 105) [x86_64-linux-musl]
  - INSTALLATION DIRECTORY: /usr/gem
  - USER INSTALLATION DIRECTORY: /root/.gem/ruby/2.5.0
  - RUBY EXECUTABLE: /usr/local/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/gem/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/gem
     - /root/.gem/ruby/2.5.0
     - /usr/local/lib/ruby/gems/2.5.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "install" => "--no-document"
     - "update" => "--no-document"
     - "gem" => "--no-ri --no-rdoc"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/jekyll/bin
     - /usr/local/bundle/bin
     - /usr/local/bundle/gems/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
@envygeeks Thanks for your report. I understand your problem and its causes.

**Comment by hsbt** [comment]
@envygeeks Can you try with the current master branch of rubygems?

Replace ```gem update --system``` to ```git clone https://github.com/rubygems/rubygems && cd rubygems && ruby bin/update_rubygems```.
