### ISSUE TITLE
The `--no-document [TYPES]` option doesn't work as documented

### ISSUE THREAD

**Issue by havenwood** [rubygems/rubygems#2544]
The `--[no-]document [TYPES]` option doesn't work as documented for `--no-document [TYPES]`. This appears to affect multiple versions of RubyGems since the introduction of `--no-document`.

This issue was raised in #1147, which was closed several years ago. I'm opening this issue since the mismatch between documentation and behavior is still ongoing. (Someone ran into this again in the #rubygems IRC channel on Freenode.net.) This could be resolved by changing the documented feature from `--[no-]document [TYPES]` to `--document [TYPES]` or by implementing the `--no-documnet [TYPES]` behavior. The latter seems preferable to me.

```sh
$ gem env version
3.0.0
```

The `--document [TYPES]` option works as expected:

```sh
~ gem install hola --document="rdoc,ri"
Fetching hola-0.1.3.gem
Successfully installed hola-0.1.3
Parsing documentation for hola-0.1.3
Installing ri documentation for hola-0.1.3
Installing darkfish documentation for hola-0.1.3
Done installing documentation for hola after 0 seconds
1 gem installed
```

The `--no-document [TYPES]` option doesn't work as expected:

```sh
$ gem install hola --no-document="rdoc,ri"
ERROR:  While executing gem ... (OptionParser::NeedlessArgument)
    needless argument: --no-document=rdoc,ri
```

I will adhere to the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Hi @havenwood 

Since --no-document will be the default behaviour in future versions of rubygems, it's prefereed to just fix the description around `--document`

see https://github.com/rubygems/rubygems/pull/2358

**Comment by hsbt** [comment]
> Since --no-document will be the default behaviour in future versions of rubygems,

Wait. It is not decided.

**Comment by hsbt** [comment]
#2555 is okay to me because the current behavior is not working.
