### ISSUE TITLE
Travis CI issues

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2564]
After a recent failure in Travis, I took a look at the ruby-head logs.  There was a lot of output from the `RbConfig::CONFIG['sitelibdir']` folder.  Travis' head build is non-standard, and includes RG 2.7.7.

I added the following to the end of util/ci 'before_script':
```
  if /trunk/ =~ RUBY_DESCRIPTION
    require 'fileutils'
    Dir.chdir(RbConfig::CONFIG['sitelibdir']) { |d|
      FileUtils.rm_r 'bundler'
      FileUtils.rm_r 'rubygems'
      FileUtils.rm %w( bundler.rb rubygems.rb ubygems.rb )
    }
  end
```

This removes the 'Travis changes' to RG & Bundler and leaves the normal head/trunk code.

A 'Ruby: ruby-head TEST_TOOL=rubygems' is at https://travis-ci.org/MSP-Greg/rubygems/jobs/474104123

A 'Ruby: ruby-head TEST_TOOL=bundler' is at https://travis-ci.org/MSP-Greg/rubygems/jobs/474104124

Comparing them to current logs here, both logs are cleaner.

As to 'TEST_TOOL=bundler', the log here reports:
2570 examples, 25 failures, 2 pending

The log from my CI is:
2620 examples, 7 failures, 2 pending

The main reason this is an issue is that I would think that when the spec tests are running, there should be no RG code running from the Ruby install folder, and this seems to indicate that there is.

Also, I thought there might be fewer failures, but I wasn't expecting a difference in the example count.

Obviously, it would be helpful if Travis had a standard trunk/head build, but setting `RUBYOPT` may correct the issue.  I haven't looked thru the Travis code that much, nor am I familiar with the Bundler test code...

Happy New Year, Greg

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by MSP-Greg** [comment]
Above I said:

> Travis' head build is non-standard, and includes RG 2.7.7

I'm not that familiar with rvm (windows type), but I've got two PR's in at Travis that hopefully adds bundled gems to their Ruby builds (`make up`, they build from the repo, not tarballs) and also removes RG 2.7.7 from ruby-head...

**Comment by bronzdoc** [comment]
@MSP-Greg is this still an issue for you?

**Comment by MSP-Greg** [comment]
@bronzdoc

Sorry, my bad.  Should have closed this a long time ago.

As I recall, Travis head/trunk has been stable, and they are now using the RG & Bundler versions included in trunk...
