### ISSUE TITLE
Gem.version...

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2566]
I hate to ask, but might it be possible to increment `Gem.version` to something like `3.0.3.pre`?

https://github.com/rubygems/rubygems/blob/66c3bcaadc6fcd6e59bdae3e1faed0049f1cfe20/lib/rubygems.rb#L11-L13

Today while getting frustrated with Travis ruby-head (which has RG 2.7.7 installed), I was checked for "what's loaded now", and saw the 3.0.0...

I hate to ask because @hsbt has enough tasks like syncing commits, code, etc...

Thanks, Greg

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

Here are my current environment details:

```
Too many versions...
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by segiddins** [comment]
That definitely should be increments during releases

**Comment by hsbt** [comment]
It should be set `3.1.0.preX` and merge `3.0` branch.

**Comment by hsbt** [comment]
Done https://github.com/rubygems/rubygems/commit/f30ac2bf1ebc7c68436bddd74f3fa3c965d82dcb
