### ISSUE TITLE
gem update --system errors for Ruby < 2.3

### ISSUE THREAD

**Issue by NobodysNightmare** [rubygems/rubygems#2570]
I'm having a problem or would like to suggest a feature.

My current problem is that `gem update --system` fails for old (unsupported) ruby versions. While I understand that unsupported versions of ruby will not receive further updates (e.g. for rubygems), it would be great if the generic `gem update --system` would not error out if my ruby version is unsupported by the latest version of rubygems.

My expectation/assumption:
* There is no new version available for my system, so an update is not possible
* This is probably worth a warning, because I am using an outdated ruby version
    * but not an error, since "no newer version available" is generally not considered to be an error
* If I could make a wish, I would hope for `gem update --system` to get me as far as supported on my platform, but that is far into "nice to have" for my purposes

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here is what happens if I run an update:

```
$ gem update --system
Updating rubygems-update
ERROR:  Error installing rubygems-update:
	rubygems-update requires Ruby version >= 2.3.0.
ERROR:  While executing gem ... (NoMethodError)
    undefined method `version' for nil:NilClass
```

Here are my current environment details:

```
$ gem env version
2.4.5.1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by MSP-Greg** [comment]
Try
```
gem update --system 2.7.8
```

RubyGems performs two 'steps' when installing a gem.  The first takes any user supplied options and selects which gem to install, based on info from the gem server.  The second is to download the selected gem file and install it.

The first step, selection, is ignorant of Ruby version constraints.  The second step, installation, is not.  Hence, the failure you mentioned.

This is often an issue in CI scripts, as many test on several Ruby versions.  Having a package manager that in some respects encourages the installation of packages that are not the most recent compatible version is not acceptable.

See PR #2539

**Comment by sodapopcan** [comment]
We solved this by running:

 ```shell
$ RUBYOPT= gem update --system
```
  Is this a horrible idea?

**Comment by bronzdoc** [comment]
@NobodysNightmare is this still an issue for you? did @MSP-Greg or @sodapopcan suggestion helped?

**Comment by NobodysNightmare** [comment]
I think I can work around it... but still feel that `gem update --system` should never lead to expected errors...  (apart from "no internet" ;-) )
