### ISSUE TITLE
Bundler 2 trying to match minor version instead of major version

### ISSUE THREAD

**Issue by schneems** [rubygems/rubygems#2576]
Based on the discussion in #2515 bundler 2.x should look for a compatible major version of bundler (as seen in the Gemfile.lock file). However, it fails for me when it cannot find the exact minor version. Here's what it looks like on my machine: 

```
$ cd /tmp
$ mkdir bundle_exact_version_bug
$ cd bundle_exact_version_bug/
$ touch Gemfile
$ gem install bundler -v 2.0.1 --no-document
$ bundle
$ gem uninstall bundler -v 2.0.1
$ bundle -v
Traceback (most recent call last):
  2: from /Users/rschneeman/.gem/ruby/2.6.0/bin/bundle:23:in `<main>'
  1: from /Users/rschneeman/.rubies/ruby-2.6.0/lib/ruby/2.6.0/rubygems.rb:302:in `activate_bin_path'
/Users/rschneeman/.rubies/ruby-2.6.0/lib/ruby/2.6.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.0.1) required by your /private/tmp/bundle_exact_version_bug/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.0.1`
```

Environment:

```
$ gem env version
3.0.1
$ ruby -v
ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin17]
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
@schneems I can't reproduce... https://asciinema.org/a/q8DdWqQERbAbU0Uz7yeSsPVkS. Maybe you're using bundler 1.x?

**Comment by colby-swandale** [comment]
This seems to be working as expected? You've installed Bundler 2, ran `bundle install` and then uninstalled it. Which i guess then leaves just leaves Bundler 1 left?

You can provide more information about what you're expecting?

**Comment by hsbt** [comment]
ref. https://github.com/bundler/bundler/issues/6882

**Comment by bronzdoc** [comment]
Should this issue be moved to the bundler repo?

**Comment by schneems** [comment]
I'm also unable to reproduce my own issue. Going to close unless someone else runs into this and can give some more details. Sorry for the false alarm, thanks for the triage!
