### ISSUE TITLE
Missing 2.7.8 tag - please add

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2578]
While trying to rid ruby-head CI on Travis of all the warnings, I ended up at bundler, then thought I'd check to see if things could be updated.

It's CI loads various versions of RubyGems from the repo, and I noticed that there isn't a `v2.7.8` tag, although the gem `rubygems-update-2.7.8.gem` exists...

Hence, please add the tag to the repo.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

Here are my current environment details:

```
Everything new & shiny...
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
Thanks for your reminder. I've created:  https://github.com/rubygems/rubygems/releases/tag/v2.7.8
