### ISSUE TITLE
Introduce `gem build .` and `gem install .` 

### ISSUE THREAD

**Issue by LemonAndroid** [rubygems/rubygems#2580]
I'm having a problem or would like to suggest a feature.

My current problem is that it is cumbersome to retype the name of the gemspec file when building and vice-versa the .gem file when installing.

I  propose that the `build` and `install` commands also work for folder or at least for the current directory `.` by:

Bundling: Looking for the `.gemspec` file.
Installing: Choosing `.gem` file in directory that matches `.gemspec` version number or building beforehand if it's not existing.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x ] The command line `gem`
  - [ ] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by djberg96** [comment]
True, I can't think of a situation in local development where I would have more than one gemspec in the current directory. I would even say just skip the "." and build or install the first gemspec found.

**Comment by voxik** [comment]
I don't mind if `gem build` pick some `.gemspec` file from current directory, either the only one which is present, the first one, the one which matches the directory name or it can fail if there is more then one `.gemspec` files, but @djberg96 please be careful with statements like "I can't think of a situation in local development where I would have more than one gemspec in the current directory". IMO, there are chances that you are wrong. Moreover, if #2587 is not resolved, there are quite high chances that we will need to place second .gemspec file into the directory to be able to package gems on Fedora.

**Comment by djberg96** [comment]
@voxik Ok, I was only speaking for myself. But, this would only be a default, you could still specify a file. That, or perhaps it should build every gemspec in the current directory if none is specified.

@LemonAndroid on what the behavior should be if there are multiple gemspecs?

**Comment by LemonAndroid** [comment]
@djberg96 @voxik I think it should just build or install for all gemspecs by default.

**Comment by LemonAndroid** [comment]
Closing, since use-case is not understood.
