### ISSUE TITLE
gem uninstall GEM removes all versions without asking

### ISSUE THREAD

**Issue by Kjarrigan** [rubygems/rubygems#2582]
I just updated to 3.x and noticed that now (different than before) if I uninstall a gem I don't get the dialog for the version anymore and instead it just removes *all* the versions instantly. That was rather surprising and unexpected. I couldn't find any hint that this was an intended changes - so is it?

This issue is related to:

  - [x ] The command line `gem`

Before: 
```
$ gem env version
2.7.7
$ gem uninst mygem

Select gem to uninstall:
 1. mygem-0.8.8
 2. mygem-0.8.9.pre.rc3
 3. mygem-0.8.9
 4. All versions
```

Upgrade
```
$ gem update --system
Updating rubygems-update
Fetching: rubygems-update-3.0.2.gem (100%)
Successfully installed rubygems-update-3.0.2
Parsing documentation for rubygems-update-3.0.2
Installing ri documentation for rubygems-update-3.0.2
...
```

Now:
```
$ gem env version
3.0.2
$ gem uninst mygem
Successfully uninstalled mygem-0.8.8
Successfully uninstalled mygem-0.8.9.pre.rc3

You have requested to uninstall the gem:
        mygem-0.8.9

mygem-cli-0.5.1 depends on mygem (>= 0)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by djberg96** [comment]
Confirmed, seeing the same thing here, even with `--no-all` passed.
