### ISSUE TITLE
`gem build ../foo.gemspec` does not work anymore

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#2587]
This does not work anymore:

~~~
$ ls
COPYING  GPLv2  GPLv3  Gemfile  LICENSE  Rakefile  lib  pdf-core.gemspec
$ ls ..
pdf-core-0.8.1  pdf-core-0.8.1.gem  pdf-core.gemspec
$ gem build ../*.gemspec
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    ["COPYING", "GPLv2", "GPLv3", "Gemfile", "LICENSE", "Rakefile"] are not files
~~~

The problem is that we are for some time using this approach in Fedora for building our packages [[1]]. Please consider reverting #2204, because it broke the functionality which was in RubyGems for years while there is not provided any alternative (the previous behavior was possible to workaround by simple `cd` command).

This was originally reported here [[2]] by @pvalena

[1]: https://docs.fedoraproject.org/en-US/packaging-guidelines/Ruby/#_building_gems
[2]: https://bugs.ruby-lang.org/issues/15516

**Comment by hsbt** [comment]
@voxik Caution: I understand you and fedora problem. Do not blame the contributors and maintainers.

**Comment by voxik** [comment]
Apologies, it was not intentional. I tried to reword the original description a bit. I hope it is better now.

**Comment by deivid-rodriguez** [comment]
My proposed fix for this would be:

* Restore the previous behavior.
* Add `-C` argument to `gem build` that behaves similarly to `git -C`. If given, files are picked up from the given directory, and also the gemspec is resolved from that directory if given relatively.

**Comment by voxik** [comment]
> My proposed fix for this would be:
>     * Restore the previous behavior.
>     * Add `-C` argument to `gem build` that behaves similarly to `git -C`.

And similarly to `make -C`. That would be nice.

**Comment by hsbt** [comment]
I'm +1 to https://github.com/rubygems/rubygems/issues/2587#issuecomment-452616438 .
