### ISSUE TITLE
Stack level too deep when overriding `Warning.warn`

### ISSUE THREAD

**Issue by Edouard-chin** [rubygems/rubygems#2588]
Hello everyone 👋 ,

Thanks a lot for maintaining rubygems ❤️. I encountered an issue when upgrading rubygems to 3.0 yesterday, the exception is: `SystemStackError (stack level too deep)`

The issue can be reproduced when your application uses the new `Warning.warn` method from ruby 2.5 (https://ruby-doc.org/core-2.5.0/Warning.html)

```ruby
module Warning
  def warn(str)
    # some custom pre-processing of the warning message
    super
  end
end

warn 'Foo Bar'
```

<details>
  <summary> StackTrace </summary>

   ```
    Traceback (most recent call last):
       16: from /opt/rubies/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_warn.rb:17:in `block in <module:Kernel>'
       15: from /opt/rubies/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_warn.rb:17:in `call'
       14: from /opt/rubies/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_warn.rb:17:in `warn'
       13: from (irb):4:in `warn'
       12: from /opt/rubies/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_warn.rb:17:in `block in <module:Kernel>'
       11: from /opt/rubies/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_warn.rb:17:in `call'
       10: from /opt/rubies/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_warn.rb:17:in `warn'
        9: from (irb):4:in `warn'
        8: from /opt/rubies/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_warn.rb:17:in `block in <module:Kernel>'
        7: from /opt/rubies/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_warn.rb:17:in `call'
        6: from /opt/rubies/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_warn.rb:17:in `warn'
        5: from (irb):4:in `warn'
        4: from /opt/rubies/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_warn.rb:17:in `block in <module:Kernel>'
        3: from /opt/rubies/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_warn.rb:17:in `call'
        2: from /opt/rubies/2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_warn.rb:17:in `warn'
        1: from (irb):4:in `warn'
SystemStackError (stack level too deep)
```
</details>

-------------

This commit seems to have caused this regression https://github.com/rubygems/rubygems/commit/7153a317c3e545658459d84aeafdad891d3a8a36#diff-5f3c1066128b69ac52cca10be3eee4f0

```
$ gem env version
3.0.2
$ ruby -v
ruby 2.5.3p105 (2018-10-18 revision 65156) [x86_64-darwin17]
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

Thanks !

**Comment by MSP-Greg** [comment]
@nobu

I remember this PR.  Don't know whether this is considered an issue, but the attached patch passes here and also `TestException#test_kernel_warn_uplevel` in `test_exception.rb` with rubygems enabled...

[uplevel.patch.txt](https://github.com/rubygems/rubygems/files/2738807/uplevel.patch.txt)

Sorry for the ping...

**Comment by MSP-Greg** [comment]
@Edouard-chin

I'm not  a c type, but I think the problem relates to last of the error.c code for [Kernel#warn](https://github.com/ruby/ruby/blob/671ef4e9e3d8cb3c397547934902a6a4fd312816/error.c#L396-L402), which seems to be based on the caller.  I have no idea where the fix should go...

```c
if (exc == rb_mWarning) {
    rb_must_asciicompat(str);
    rb_write_error_str(str);
}
else {
    rb_write_warning_str(str);
}
```

**Comment by deivid-rodriguez** [comment]
Without having looked in depth on this, it's been suggested that the problem might actually lie in ruby-core? Should we open a ruby-core ticket to get some feedback?

**Comment by deivid-rodriguez** [comment]
Hi @Edouard-chin! I added a fix for this in #3985.

It seems to work under all supported rubies, except for truffleruby, but in truffleruby the script you posted also leads to SystemStackError without rubygems, so it sounds like a truffleruby bug.

**Comment by eregon** [comment]
I think we should change the docs of the Warning module, overriding seems a bad idea in general and doesn't compose, it seems much better to `prepend`. cc @jeremyevans

**Comment by eregon** [comment]
Also I think the docs mean to override `Warning.warn`, never `Warning#warn` which naturally ends in infinite recursion (`super` will call `Kernel#warn`, which calls `Warning.warn`, which is just `Warning#warn` since `Warning` extend `self`, and since it is overridden that will call the custom `Warning#warn`).

**Comment by jeremyevans** [comment]
Warning extends itself, so you should do `Warning.extend(OtherModule)` to override, you don't need to do `Warning.prepend`.  In general, it's best to only use `Module#prepend` in cases where you must.  The warning gem uses `Warning.extend` (https://github.com/jeremyevans/ruby-warning/blob/master/lib/warning.rb#L247), and overides `warn` and calls `super` for the default behavior.

**Comment by eregon** [comment]
Good point, actually `Warning.prepend` actually doesn't override. `Warning.extend` (which is the same as `Warning.singleton_class.include`) works.
(`Warning.singleton_class.prepend` also works but is needlessly complicated).
```
$ ruby -e 'Warning.prepend Module.new { def warn(*args); p [:got, args]; super; end }; p Warning.singleton_class.ancestors; warn "foobar"'
[#<Class:Warning>, Warning, Module, Object, Kernel, BasicObject]
foobar

$ ruby -e 'Warning.extend Module.new { def warn(*args); p [:got, args]; super; end }; p Warning.singleton_class.ancestors; warn "foobar"'
[#<Class:Warning>, #<Module:0x0000561e469312e0>, Warning, Module, Object, Kernel, BasicObject]
[:got, ["foobar\n"]]
foobar

$ ruby -e 'Warning.singleton_class.prepend Module.new { def warn(*args); p [:got, args]; super; end }; p Warning.singleton_class.ancestors; warn "foobar"'
[#<Module:0x000055dadb351310>, #<Class:Warning>, Warning, Module, Object, Kernel, BasicObject]
[:got, ["foobar\n"]]
foobar
```

I'll make a PR to ruby/ruby to try to clarify that.
