### ISSUE TITLE
bundle command looks for bundler 2 when not present on the system

### ISSUE THREAD

**Issue by schneems** [rubygems/rubygems#2592]
When using rubygems 3.0.2, an error will be raised when trying to use a Gemfile.lock generated with Bundler 2.0.1 when no 2.x version is present. It was my understanding that on systems with only a bundler 1.x that the `BUNDLE WITH` was purely cosmetic and would not cause any errors.

To reproduce, first get a docker image with Ruby 2.5:

```
$ docker run -it --rm ruby:2.5 bash
```

Then make sure you're using the latest rubygems, and then generate a Gemfile.lock with a 2.0.1 `BUNDLE WITH`. Next remove that version of bundler and try to run `bundle` with a 1.x version of bundler:

```
gem update --system
gem -v 
ruby -v 
cd /tmp && mkdir rubygems-issue &&  cd rubygems-issue/
gem install bundler -v 2.0.1
touch Gemfile && bundle install
gem uninstall bundler -a -x
gem install bundler -v 1.17.3
bundle -v
```

You'll then get this error:

```
Traceback (most recent call last):
  2: from /Users/rschneeman/.gem/ruby/2.5.3/bin/bundle:23:in `<main>'
  1: from /Users/rschneeman/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems.rb:302:in `activate_bin_path'
/Users/rschneeman/.rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems.rb:283:in `find_spec_for_exe': Could not find 'bundler' (2.0.1) required by your /private/tmp/rubygems-issue/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:2.0.1`
```

This behavior means that anyone who is using Ruby 2.6 and has Bundler 2.x in their Gemfile.lock will get an error on Heroku, or any other cloud provider where only one version of bundler is currently available, will get an error.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by colby-swandale** [comment]
`BUNDLE WITH was purely cosmetic and would not cause any errors.`

This is not true, RubyGems has to assume that every major version includes a breaking change in the Gemfile.lock that the previous version of Bundler won't be able to parse.

**Comment by deivid-rodriguez** [comment]
Yes, I think this is expected.

If a Gemfile is locked to bundler 1.17, that means that version should be used in every developer environment, in CI, and also in cloud providers. This is the same as a gem being locked to a specific version.

If a lock file is upgraded to bundler 2, then that version will be used in all environments, and the team should make sure the new version is available in all environments before upgrading.

It could be argued that `bundle install` should transparently be able to resolve this situation, and auto-upgrade `bundler`. I agree, but bundler is not yet able to handle it. So if you upgrade the major version of bundler in your lock file, you need to make in advance that all your environments are ready for it.

**Comment by MSP-Greg** [comment]
@deivid-rodriguez

Good explanation, especially for people who are unfamiliar with the issue.  I ran into it again last night working first with trunk, then moving backward with Ruby versions.  I know how to work around it, but it's both frustrating and something that shouldn't need to be done...

`Gem::Specification#specification_version`  exists, and hasn't changed for several years, both RG 2.7.x and 3.x work with the current version.  Does Bundler need something similar?  Or, are 2.0 Gemfiles & lock files really incompatible with the ones from 1.x?

Do new 1.x & 2.x Bundler versions need to be released that solve this issue?

**Comment by schneems** [comment]
Rather than an exception, how about if we issue a warning instead. Rubygems does not know for sure if there is an actual discrepancy. 

Either that or allow for some kind of escape valve, such as an env var:

```
RUBYGEMS_DO_NOT_ERROR_ON_BUNDLER_VERSION=1 bundle exec
```

Sure the developer may still experience bad/failing behavior, but at least give them that option to explicitly opt-in to that experience.

**Comment by schneems** [comment]
Any additional thoughts here? Can we add in some kind of escape valve?

**Comment by deivid-rodriguez** [comment]
@schneems Yeah, I agree that we should issue a warning for now instead of raising.

**Comment by deivid-rodriguez** [comment]
I'm working on downgrading this to a warning :+1:.

**Comment by schneems** [comment]
Thanks!

**Comment by schneems** [comment]
It looks like this issue is not just a factor of rubygems, bundler's 1.x lockfile parser also raises an error when being used on a lockfile with 2.x

```
-----> Ruby app detected
 !
 !     You must use Bundler 2 or greater with this lockfile.
 !
/tmp/d20190207-99-1ghispi/bundler-1.15.2/gems/bundler-1.15.2/lib/bundler/lockfile_parser.rb:108:in `warn_for_outdated_bundler_version': You must use Bundler 2 or greater with this lockfile. (Bundler::LockfileError)
	from /tmp/d20190207-99-1ghispi/bundler-1.15.2/gems/bundler-1.15.2/lib/bundler/lockfile_parser.rb:95:in `initialize'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/helpers/bundler_wrapper.rb:130:in `new'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/helpers/bundler_wrapper.rb:130:in `block in parse_gemfile_lock'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:18:in `block (2 levels) in instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:40:in `yield_with_block_depth'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:17:in `block in instrument'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/vendor/ruby/heroku-18/lib/ruby/2.5.0/benchmark.rb:308:in `realtime'
	from /app/tmp/buildpacks/b7af5642714be4eddaa5f35e2b4c36176b839b4abcd9bfe57ee71c358d71152b4fd2cf925c5b6e6816adee359c4f0f966b663a7f8649b0729509d510091abc07/lib/language_pack/instrument.rb:16:in `instrument'
```

So even if this issue is fixed in Rubygems it also needs to be fixed in older versions of bundler.

**Comment by deivid-rodriguez** [comment]
I'll have a look at that next :+1:!

**Comment by schneems** [comment]
Thanks! Originally reported on https://github.com/bundler/bundler/issues/6784

**Comment by schneems** [comment]
There's yet another failure mode https://github.com/heroku/heroku-buildpack-ruby/issues/856#issuecomment-466189633.

When bundler 2.0.1 is present on the system, but command is invoked without `bundle exec` then there are cases where the built-in version of bundler in Ruby 2.6.1 is loaded even though there's a more recent version of bundler available (2.0.1). I'll work on a reproduction and open an issue with the Ruby issue tracker.

**Comment by schneems** [comment]
Reported the issue to Ruby core in https://bugs.ruby-lang.org/issues/15622

**Comment by deivid-rodriguez** [comment]
Just making sure everything is linked together: this last problem reported is already fixed in Ruby core's 2.6's stable branch (see https://bugs.ruby-lang.org/issues/15582), and the fix should be released in the next patch level version. Running `gem update --system` workarounds the issue.

**Comment by schneems** [comment]
To add on I just reported https://github.com/rubygems/rubygems/issues/2666 which shows an error when trying to use a bundler 2 with a Gemfile that contains a bundler 2 pre-release version.

**Comment by deivid-rodriguez** [comment]
Great, thanks for all the work you're doing to support `bundler` in heroku and for your positive, non-blaming attitude :heart:.

**Comment by schneems** [comment]
@deivid-rodriguez thanks for all your hard work. I understand that OSS is hard and there's certainly a lot of moving parts. I think we're close to getting a majority of issues ironed out! ❤️❤️❤️
