### ISSUE TITLE
`gem search`/`gem outdated` returning old gem version

### ISSUE THREAD

**Issue by JacobEvelyn** [rubygems/rubygems#2594]
I'm having a problem. My current problem is that I published a new version (`0.44`) of the `friends` gem 17 hours ago, and although the [RubyGems website](https://rubygems.org/gems/friends) lists this version, `gem search friends` and `gem outdated` do not. I've seen similar behavior for a few minutes in the past, but 17 hours seems long even for a caching issue. Or is this normal?

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.3
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by MSP-Greg** [comment]
Doesn't change the above issues, but `gem install friends --explain` does show `0.44`...

**Comment by JacobEvelyn** [comment]
For what it's worth, `gem search friends` now gives me `0.44` as I expected. My question about the long delay remains, however.

**Comment by hsbt** [comment]
Can you file this into https://github.com/rubygems/rubygems.org? This repository only handles rubygems client issues.
