### ISSUE TITLE
Fix up PR 2567 &  9c66e1e ?

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2606]
Took a break and looked at recent ruby/ruby commits, saw some odd code from PR #2567 &  9c66e1e

The code currently is:

https://github.com/rubygems/rubygems/blob/1172320540c8c33c59fc1db5191b021c3b2db487/lib/rubygems/request.rb#L164-L173

So, re lines 171 thru 173, why is the `no_env_proxy` value checked three times, and why is `scheme` used for one test and `_scheme` used for another?

```
Removing no_env_proxy from the conditionals becomes:

    if no_env_proxy
171   return :no_proxy                 if _scheme == 'https'
172   return get_proxy_from_env 'http' if _scheme != 'http'
173   return :no_proxy
    end

What does the above do?
                                 --- _scheme value ---
     Return value                'https'  'http'  other
171  :no_proxy                      T        F      F
172  get_proxy_from_env 'http'               F      T
173  :no_proxy                               T

So, is the following an improvement?

if no_env_proxy
  return ( _scheme == 'https' or _scheme == 'http' ) ?
    :no_proxy : get_proxy_from_env('http')
end
```
I just looked at the three lines, didn't check whether the `scheme` parameter is validated elsewhere, etc...

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

Here are my current environment details:

```
code in master
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Hi @MSP-Greg 

i'll give it a more detailed look and get back, at first glance it seems like the use of `scheme` instead of `_scheme` might be wrong
