### ISSUE TITLE
BUNDLE_GEM__PUSH_KEY is not working anymore

### ISSUE THREAD

**Issue by johan-smits** [rubygems/rubygems#2609]
I'm having a problem or would like to suggest a feature.

My current problem is BUNDLE_GEM__PUSH_KEY is not working anymore

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [x] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:
```
$ gem env version
3.0.1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md). :+1: 

Since version 3.0.1 (maybe the 3.0.x) we notice that our CI is unable to push gems to our private repo.
We did this by setting the env `BUNDLE_GEM__PUSH_KEY=my_private_key` and in `~/.gem/credentials` added the key: `:my_private_key: secret`. This was working with `2.7.6`.

Now I get the error:
```
ERROR:  No such API key. Please add it to your configuration (done automatically on initial `gem push`).
```

I also noticed this PR #2559 but this seems like the same purpose by setting the ENV as I do now.

**Comment by MSP-Greg** [comment]
Not sure if it's applicable...

https://github.com/bundler/bundler/blob/master/man/bundle-config.ronn

**Comment by johan-smits** [comment]
@bronzdoc we use it in a build script yes, but with a normal `gem push` this variable in 2.7.6 works to set the key. How I could't not find it in the source.

@MSP-Greg found the documentation for it. And it is in master so it should work?

Not sure how this got broken or what should be the recommended way to select the push key?

**Comment by bronzdoc** [comment]
Ok, thanks @johan-smits 

Could could you try using `GEM_HOST_API_KEY`

**Comment by johan-smits** [comment]
The issue has been resolved. Jenkins changes their home directory and to a non existing directory on our slave builds. Then bundler could not find the correct home directory for the credentials.
So this issue is not a rubygems or bundler issue but it was an environment problem introduces by jenkins updates that where applied.

It is working with the old parameters as I opened the issue.

@bronzdoc did not test the new ENV because in our CI env we use docker images and no ruby image has this option.

**Comment by nabheet** [comment]
GEM_HOST_API_KEY -> is this supposed to contain the B64 encoded HTTP credentials or the key name?

I can't get this to work and can't find an example anywhere.

**Comment by bronzdoc** [comment]
@nabheet  In your `~/.gem/credentials` you will have something like:
```
---
:rubygems_api_key: 3ab457e64c838d7e19c0c0fb6fe68109
```
You will set `GEM_HOST_API_KEY` to `3ab457e64c838d7e19c0c0fb6fe68109`

**Comment by nabheet** [comment]
so gem is acting as if the variable is not set and I have deleted the ~/.gem/credentials file:

```
[root@1d28b7f4c542 /]# curl -s -uUSERNAME:PASSWORD https://CUSTOM_ARTIFACTORY_URL/api/v1/api_key.yaml | grep ':rubygems_api_key'
BLA_BLA_BLA_BLA_BLA
[root@1d28b7f4c542 /]# export GEM_HOST_API_KEY=BLA_BLA_BLA_BLA_BLA
[root@1d28b7f4c542 /]# rm ~/.gem/credentials
rm: cannot remove '/root/.gem/credentials': No such file or directory
[root@1d28b7f4c542 /]# gem yank package_name -v 1.2.1114.pre.branchname
Enter your https://CUSTOM_ARTIFACTORY_URL credentials.
Don't have an account yet? Create one at https://CUSTOM_ARTIFACTORY_URL/sign_up
   Email:   ^CERROR:  Interrupted
[root@1d28b7f4c542 /]# set | grep GEM_
GEM_HOME=/usr/local/bundle
GEM_HOST_API_KEY=BLA_BLA_BLA_BLA_BLA
PASSENGER_GEM_VERSION=6.0.1
[root@1d28b7f4c542 /]#```
