### ISSUE TITLE
rubygems failed update brokes gems

### ISSUE THREAD

**Issue by Skoti** [rubygems/rubygems#2622]
Hi I tried updating _rubygems_ by calling:
`gem update --system`
but it failed with: `Permission denied @ rb_sysopen`
which is weird as **before** that I have updated all gems successfully by:
`gem update && gem cleanup`

Full output:
<details><pre>
Updating rubygems-update
Successfully installed rubygems-update-3.0.2
Parsing documentation for rubygems-update-3.0.2
Done installing documentation for rubygems-update after 0 seconds
Parsing documentation for rubygems-update-3.0.2
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 3.0.2
ERROR:  While executing gem ... (Errno::EACCES)
    Permission denied @ rb_sysopen - /Users/{redacted_user}/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/source_local.rb
</pre></details>
<br/>

Now any invocation of any installed gem or `gem` command itself gives:
<details><pre>
Traceback (most recent call last):
	4: from <internal:gem_prelude>:2:in `<internal:gem_prelude>'
	3: from <internal:gem_prelude>:2:in `require'
	2: from /Users/{redacted_user}//.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems.rb:1395:in `<top (required)>'
	1: from /Users/{redacted_user}//.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
/Users/{redacted_user}//.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require': cannot load such file -- rubygems/core_ext/kernel_warn (LoadError)
</pre></details>
<br/>

I'm running:
macOS High Sierra 10.13.6
`ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin16]`
and I also use _homebrew_ which was updated before I tried updating _rubygems_.
`brew doctor` gives:
`Your system is ready to brew.`

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
can you provide the output of `gem env`? thanks

**Comment by Skoti** [comment]
> Now any invocation of any installed gem or `gem` command itself gives:

I cannot run `gem env` as it ends with the error described above.

**Comment by duckinator** [comment]
@Skoti it looks like a permissions issue with your `~/.rbenv/` directory. What's the output of this commands (replacing `{redact_user}` as appropriate)?

```
stat /Users/{redacted_user}/.rbenv/versions/2.5.1/lib/ruby/site_ruby/2.5.0/rubygems/
```

**Comment by Skoti** [comment]
Thanks for getting back to this issue.
Output:
`16777221 4026921 drwxr-xr-x 74 root staff 0 2368 "Feb 19 16:19:06 2019" "May 24 09:55:48 2018" "May 24 09:55:48 2018" "May 24 09:55:48 2018" 4096 0 0`

I think `root` is the problem here? Instead it should be my username - correct me if I am wrong. Anyway, I do not know whether it was changed before (for sure I did not change it myself) or during the update.

**Comment by duckinator** [comment]
Yup, you're exactly right. If you accidentally used rbenv via `sudo` at some point, that'd explain it. Otherwise, I'm not sure what would've caused it.

This should fix the permissions for it: `sudo chown -R {redacted_user} ~/.rbenv/`

(Again, replacing `{redacted_user}` as appropriate.)

After doing that, you'll probably need to use rbenv to reinstall Ruby v2.5.1 then do another `gem update --system`, since the installation seems to have been broken by this problem.

I don't know much about rbenv, but if you run into problems doing that, just let me know here -- I'd be happy to read up on it and give you a hand.

**Comment by duckinator** [comment]
(You could also just remove `~/.rbenv/` then start your rbenv setup from scratch, if you'd prefer -- this would make the most sense if Ruby 2.5.1 is the only version you have installed.)

**Comment by Skoti** [comment]
It worked! 💪 Thanks for your help!
