### ISSUE TITLE
gen install --explain problems

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2629]
Two issues with `gem install`:

1. When `--explain` is used with `--ignore-dependencies`, the command proceeds to install the gem(s)

```
> gem install did_you_mean --explain --ignore-dependencies
ERROR:  Error installing did_you_mean:
        did_you_mean requires Ruby version >= 2.5.0. The current ruby version is 2.4.5.335.
```

2. When `--explain` is used, platforms are not shown:
```
> gem install jekyll --explain
Gems to install:
  public_suffix-3.0.3
  addressable-2.6.0
  colorator-1.1.0
  http_parser.rb-0.6.0
  eventmachine-1.2.7
  em-websocket-0.5.1
  concurrent-ruby-1.1.4
  i18n-0.9.5
  rb-fsevent-0.10.3
  ffi-1.10.0
  rb-inotify-0.10.0
  sass-listen-4.0.0
  sass-3.7.3
  jekyll-sass-converter-1.5.2
  ruby_dep-1.5.0
  listen-3.1.5
  jekyll-watch-2.1.2
  kramdown-1.17.0
  liquid-4.0.1
  mercenary-0.3.6
  forwardable-extended-2.6.0
  pathutil-0.16.2
  rouge-3.3.0
  safe_yaml-1.0.4
  jekyll-3.8.5
```

`eventmachine-1.2.7` is listed, it should be `eventmachine-1.2.7-x64-mingw32`, which is what would be installed.

3. The output shown with `Jekyll` is is not user friendly.  Could it be alpha sorted, or tree sorted, as in #2459?

The code for `gem install` is affected by the `required_ruby_version` issue, so the 1st & 2nd issues are fixed.  Looking for input on the third.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
RubyGems 3.0.2
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
closed by https://github.com/rubygems/rubygems/pull/2635 and https://github.com/rubygems/rubygems/pull/2647
