### ISSUE TITLE
gem install behavior, minimal_deps, etc

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2637]
While checking issues with `required_ruby_version`, I also did some other testing.

Using a spec setup like the following (a and b have different c dependencies):
```
spec_fetcher do |fetcher|
  fetcher.download 'a', 2.0, 'c' => '~> 2.5'
  fetcher.download 'b', 2.0, 'c' => '>= 2.5'
  fetcher.download 'c', 2.6
  fetcher.download 'c', 3.1
end
```

Below are test results for various operations:

```
—————  Installed gems  ————————  Commands  ————————————————————

a-2.0  b-2.0  c-2.6         ———  gem install a ; gem install b

a-2.0  b-2.0  c-2.6         ———  gem install a b

a-2.0  b-2.0  c-2.6         ———  gem install a b --minimal-deps


a-2.0  b-2.0  c-2.6  c-3.1  ———  gem install b ; gem install a

a-2.0  b-2.0  c-2.6  c-3.1  ———  gem install b a

a-2.0  b-2.0  c-2.6  c-3.1  ———  gem install b a --minimal-deps
```

Some interesting results.  Whether `gem install` should behave compositionally or commutatively is undefined, but one might think that `gem install a b --minimal-deps` and `gem install b a --minimal-deps` should yield the same results.

Test file: [test_gem_commands_install_command_dupl.rb.txt](https://github.com/rubygems/rubygems/files/2849493/test_gem_commands_install_command_dupl.rb.txt)

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
master
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Yeah, one would think that the order of arguments shouldn't affect, but given how `gem install <gem1> <gem2>` works (it just loops over the given gems and installs them one by one), it's not surprising.

We might be able to fix this at a later point when the rubygems + bundler merge is closer. For now I wouldn't give this much priority. If you want this kind of determinism, you can use `bundler`! :)

**Comment by MSP-Greg** [comment]
@deivid-rodriguez

Sorry for the delay.  I assume you're aware this has nothing to do with Bundler integration.

When fed multiple dependencies, RequestSet will resolve them just as listed in the first set (with only one c gem installed)...

**Comment by deivid-rodriguez** [comment]
I'm not sure what you mean.

When I looked at this, I saw that `gem install a b` is essentially a shortcut to `gem install a; gem install b`. So the results you're getting are not surprising because when you install `b` first, `c-3.1` gets correctly installed, whereas when you install `a` first, that installs `c-2.6` which satisfies `b`'s requirements, and thus skips `c-3.1` installation when installing `b`.

If you want to improve this to resolve all gems specified together, I would welcome that change.

**Comment by MSP-Greg** [comment]
> If you want to improve this to resolve all gems specified together

I think in the greater RG/Bundler system that it should be accessible from the command line.  But I'm also thinking about the where is the line between RB & Bundler.

An option would be to allow:
```
bundle install a,b
```
Some might consider that improper/crazy/etc, but it does somewhat flow from the idea that RG individually resolves gems, and bundler collectively resolves a gem 'group'...
