### ISSUE TITLE
yank responds with permission issue

### ISSUE THREAD

**Issue by djezzzl** [rubygems/rubygems#2641]
I'm having a problem or would like to suggest a feature.

My current problem is:

I just released a new version of my gem `database_validations` but I found a bug after few minutes and wanted to yank that version but I got the error.

```
gem yank database_validation -v 0.8.7
Yanking gem from https://rubygems.org...
You do not have permission to delete this gem.
```

We have two owners on the gem and another did `yank` succesfully. Is that a non-documented feature?

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [x] Other

Here are my current environment details:

```
$ gem env version
2.7.8
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
That is weird... :thinking:

Can you move this issue to https://github.com/rubygems/rubygems.org though? This error is happening in the server side, so I think they might be able to help better.

**Comment by rubyFeedback** [comment]
I don't know the specifics but it sounds like a bug to me. There should probably be no noticable difference between owners of a gem in this regard, in my opinion.

**Comment by djezzzl** [comment]
Asked here https://github.com/rubygems/rubygems.org/issues/1919
