### ISSUE TITLE
Can't update rubygems, get a 404 on specs.4.8.gz lookup

### ISSUE THREAD

**Issue by nfilzi** [rubygems/rubygems#2648]
I'm having a problem.

I can't update rubygems.

```
gem update --system
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    bad response Not Found 404 (http://gems.github.io/specs.4.8.gz)
```

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.6
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
It should be rubygems.org serving that file, not gems.github.io... Is that intentional? Can you check your `gem env`?

**Comment by timhaines** [comment]
I've been hitting this on osx mojave too.  I'm using rvm and have tried removing and reinstalling.

Running `gem env`, under gem configuration I have:
```
- :sources => ["http://rubygems.org/", "http://gems.github.com"]
```

And:
```
- REMOTE SOURCES:
     - http://rubygems.org/
     - http://gems.github.com
```

**Comment by dapi** [comment]
Same problem on Ubuntu:

```
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    server did not return a valid file (http://gems.rubyforge.org/specs.4.8.gz)
```

**Comment by dapi** [comment]
`gem install bundle` also did not work. I think why is similar.

```
# gem install bundle
ERROR:  While executing gem ... (TypeError)
    incompatible marshal file format (can't be read)
        format version 4.8 required; 60.33 given
```

**Comment by bronzdoc** [comment]
Can you share your `.gemrc`? thanks

**Comment by dapi** [comment]
@bronzdoc There was `http://gems.github.com` in sources. Removed it. Problems solved, thank you!

**Comment by WvanLelyveld** [comment]
See the solution typed out on https://github.com/rubygems/rubygems/issues/1589#issuecomment-466381653

**Comment by djberg96** [comment]
@bronzdoc Any way we could be nicer when this happens?

**Comment by deivid-rodriguez** [comment]
Yeah, we should probably print an error higher up in the stack.

**Comment by bronzdoc** [comment]
> @bronzdoc Any way we could be nicer when this happens?

@djberg96 I'll try to improve the error message if we hit a `404`

**Comment by tcurdt** [comment]
For anyone coming here from Google: I still had http://gems.rubyforge.org/ in my list and switched the source to http://rubygems.org/ to get it working.
