### ISSUE TITLE
Fixup - required_ruby_version constraints - platform questions

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#2653]
Regarding pushing the `required_ruby_version` PR, I've got a question that came up today.

Re PR #1093, I'm a little unclear as to the intent, as the PR is addressing expected behavior when
`--platform=x86-mingw32` is used with `gem install`.

RG's test setup sets the platform to `x86-mswin32-60`, so `Gem::platform.local` is not compatible with
`--platform=x86-mingw32`...

So, is the intent to allow **non-compatible gems** to be installed using the `gem install`  `--platform` option?

@kou - sorry for the ping, but I thought your opinion would be helpful.

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

Here are my current environment details:

```
master
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
@MSP-Greg did you get your answers?

**Comment by MSP-Greg** [comment]
@bronzdoc

No.  When one can do a fetch/unpack to look at a gem that is platform incompatible, I'm not sure why `gem install` should allow it?

**Comment by bronzdoc** [comment]
> So, is the intent to allow non-compatible gems to be installed using the gem install --platform option?

The intent is to allow the user to install the gem from the platform they specify with the `--platform`  flag, if it happens that the gem they are installing is not compatible with their current platform, that's their responsibility.
