### ISSUE TITLE
gem yank - problem: message is "Retry later". I would like to suggest to improve this message and the associated

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems#2657]
gem yank - problem: message is "Retry later". I would like to suggest to improve this message and the associated behaviour.

This issue is related to:

  - [x] The command line `gem`
  - [x] Other

Here are my current environment details:

```
ruby version: ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]
rubygems version: 3.0.2
```

I am having some problems lately; e. g. unicorn app crashes or slowdowns when I try to remove old gems. However, the issue here is not primarily about unicorn behaviour but about gem itself.

I can delete one version of a gem without a problem. However had, when I try to remove a second gem (old version of the same gem), I get a message like this:

"Yanking gem from https://rubygems.org...
Retry later"

I have not seen this before, so I am not sure what is going on. I can make a guess - perhaps there
were some problems noticed, e. g. with unicorn crashes, and this change was added or became more important, in order to allow the whole stack to function properly (since lots of people could remove gems at the same time, I guess - but again, I am speculating here, I don't know for certain).

To me, as a gem user or gem developer, it is however not clear what the message "Retry later" wants to tell me. Yes, I understand that it tells me TRY LATER :) - I just don't know what this really means.

So I firstly, would like to suggest this change:

- Rather than showing a simple "Retry later" string, I would like to propose to also notify the user WHEN exactly he can try again. For example.

    "Retry later, at the earliest in 10 minutes."

Or something like that. I would like to see the amount of time that I have to wait here.

Why would I like to know this? Well, I actually wrote a small ruby class that cleans up old gem versions and this operates in a batch-fashion. I just copy/paste the versions onto the terminal and then the class will proceed to remove all these specified versions. I can easily add sleep() to it, to still have it work, but right now rubygems does not tell me when I can remove my own gems. Which I think is unfortunate.

I understand that you may possibly not want to overload any of the servers, that part is fine - but I am here only asking for the specific delay/waiting time that we have to wait, before retrying again. Right now we are completely left in the dark as-is, which I don't think is good. (It does not have to be an exact measurement, it could be an approximate number too - I'd just then use that for sleep() and my script would still work. But right now I have no idea about the delay ... I guess I could look at the sources but I don't know where exactly.)

- I do, however had, also wonder whether the behaviour is necessary to begin with. This may probably require some code changes, since the whole API behaviour seems a bit slow to me, but in principle, if someone is the author of a certain gem, then it should be super fast and super easy to remove any gems, right? So I am not even sure if this behaviour could not be improved in the long run, but for now I guess it may just be better to improve on the behaviour above, and at a later time wonder whether something should be improved elsewhere.

I am fine with other people maintaining any of my code (all my code is under a permissive open source licence); I just would like to have cleaner project pages on rubygems for my gems, if that makes any sense. Some of my code is +5 years old and I don't have an interest in looking at old versions that have gone through lots of changes - it's fine if these old versions are available elswhere via rubygems.org by the way, but I just don't want to have them on any of my pages if I decided to not maintain these old versions. I maintain newer versions of these gems of course, and in the case that I no longer do so, I tend to remove such gems altogether so that others can use the "namespace".

Thanks for reading and considering! I am not dead-set to any of my own suggestions; part of this suggestion is to try to point out where the current behaviour is not ideal, and removing several older versions is, in my opinion, not ideal right now as-is. Removing single version is easy but removing more than one version is a bit cumbersome/delayed, without providing us with a lot of information other than the short "Retry later" information string.

**Comment by bronzdoc** [comment]
Please report this to https://github.com/rubygems/rubygems.org since seems like a server issue
