### ISSUE TITLE
OpenSSL::SSL::SSLContext::METHODS is deprecated

### ISSUE THREAD

**Issue by jepunband** [rubygems/rubygems#2667]
I'm having a problem or would like to suggest a feature.

My current problem is _________(eval):136: warning: constant OpenSSL::SSL::SSLContext::METHODS is deprecated.

root@kali:~# ruby -ropen-uri -e 'eval open("https://git.io/vQhWq").read'
Here's your Ruby and OpenSSL environment:

Ruby:           2.5.3p105 (2018-10-18 revision 65156) [arm-linux-gnueabihf]
RubyGems:       3.0.2
Bundler:        2.0.1
Compiled with:  OpenSSL 1.1.1a  20 Nov 2018
Loaded version: OpenSSL 1.1.1a  20 Nov 2018
SSL_CERT_FILE:  /usr/lib/ssl/cert.pem
SSL_CERT_DIR:   /usr/lib/ssl/certs

With that out of the way, let's see if you can connect to rubygems.org...

Bundler connection to rubygems.org:       success ✅
RubyGems connection to rubygems.org:      success ✅
Ruby net/http connection to rubygems.org: success ✅

Hooray! This Ruby can connect to rubygems.org. You are all set to use Bundler and RubyGems. 👌
(eval):136: warning: constant OpenSSL::SSL::SSLContext::METHODS is deprecated

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [* ] Other 
*

Here are my current environment details:

```
$ gem env version
Ruby:           2.5.3p105 (2018-10-18 revision 65156) [arm-linux-gnueabihf]
RubyGems:       3.0.2
Bundler:        2.0.1

```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Sorry but i don't understand how is this a Rubygems issue? what `gem` command are you running?

**Comment by jepunband** [comment]
just did ruby -ropen-uri -e 'eval open("https://git.io/vQhWq").read'

**Comment by MSP-Greg** [comment]
This is an issue with SSL check code (check.rb).  See:

https://github.com/bundler/ruby-ssl-check/pull/3

Also, https://git.io/vQhWq points to:

https://raw.githubusercontent.com/indirect/ruby-ssl-check/master/check.rb

Should it point to:

https://raw.githubusercontent.com/bundler/ruby-ssl-check/master/check.rb

Short URL is https://git.io/fhx5j

**Comment by hsbt** [comment]
It seems to not RubyGems issue.
