### ISSUE TITLE
The current release task was broken

### ISSUE THREAD

**Issue by hsbt** [rubygems/rubygems#2668]
This is a reminder for RubyGems maintainer. The current release task of master and 3.0 branches was broken.

```
~/D/g/r/rubygems (3.0) > rake release
rm -r doc
rm -r pkg
Gem::Indexer tests are being skipped.  Install builder gem.
Run options: --seed 58643

# Running:
(snip)
Finished in 73.997099s, 27.8119 runs/s, 84.6385 assertions/s.

2058 runs, 6263 assertions, 0 failures, 0 errors, 2 skips

You have skipped tests. Run with --verbose for details.
Coverage report generated for Unit Tests to /Users/hsbt/Documents/github.com/rubygems/rubygems/coverage. 7957 / 9083 LOC (87.6%) covered.
cd bundler
rake build_metadata
build_metadata ran for   0.000918   0.003583   0.234124 (  0.111954)
cd -
cd bundler
rake build_metadata:clean
build_metadata:clean ran for   0.000169   0.000299   0.000468 (  0.001121)
cd -
s3cmd put -P pkg/rubygems-3.0.3.zip pkg/rubygems-3.0.3.tgz s3://oregon.production.s3.rubygems.org/rubygems/
rake aborted!
Command failed with status (127): [s3cmd put -P pkg/rubygems-3.0.3.zip pkg/ru...]
/Users/hsbt/Documents/github.com/rubygems/rubygems/Rakefile:129:in `block in <top (required)>'
Tasks: TOP => release => postrelease => upload => upload_to_s3
```

I'm not sure why this code didn't invoke: https://github.com/rubygems/rubygems/blob/master/Rakefile#L94

I'm going to investigate and fix them.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Any news, @hsbt?

I got curious and "tried" this (skipping the actual `gem push` and postrelease tasks, of course :sweat_smile:). The package task was correctly invoked... :thinking:

How did you release 3.0.3, by the way? Run `rake package` manually, and then invoked `rake release` again without clobbering the `pkg` folder?

**Comment by bronzdoc** [comment]
ping @hsbt

**Comment by hsbt** [comment]
I close this. When I got the same issue, I'm going to re-open again 😇
