### ISSUE TITLE
Updating rubygems triggers irreversible bundler upgrade

### ISSUE THREAD

**Issue by schneems** [rubygems/rubygems#2671]
## Behavior

The `gem update --system` causes bundler to be updated to 1.17.3 and it cannot be uninstalled. This prevents people from using an older version of bundler on their system if they have a need for it.

Originally reported in https://github.com/heroku/heroku-buildpack-ruby/pull/835#issuecomment-469878345

## Expected Behavior

Having the rubygems update command also modify the version of bundler was unexpected to me. I expected it to only bump the rubygems version installed.

## Reproduction

Start docker

```
$  docker run -it --rm ruby:2.3.7 bash
```

Update the system

```
root@e4bcc426e52d:/# gem list | grep bundler
bundler (1.16.6, default: 1.16.2)
root@e4bcc426e52d:/# gem update --system
Updating rubygems-update
Fetching: rubygems-update-3.0.3.gem (100%)
Successfully installed rubygems-update-3.0.3
Installing RubyGems 3.0.3
Bundler 1.17.3 installed
RubyGems 3.0.3 installed
root@e4bcc426e52d:/# gem list | grep bundler
bundler (default: 1.17.3, 1.16.6)
```

Uninstall bundler, but it's still there:

```
root@e4bcc426e52d:/# gem uninstall bundler -v 1.17.3
root@e4bcc426e52d:/# gem list | grep bundler
bundler (default: 1.17.3, 1.16.6)
```

**Comment by hsbt** [comment]
It's intentional behavior. Because RubyGems 2.7.0+ has Bundler Integration for dependency resolver.

**Comment by jaredbeck** [comment]
> Uninstall bundler, but it's still there:
> 
>     root@e4bcc426e52d:/# gem uninstall bundler -v 1.17.3
>     root@e4bcc426e52d:/# gem list | grep bundler
>     bundler (default: 1.17.3, 1.16.6)

Maybe, in this situation, `gem uninstall bundler` should print an explanatory message, perhaps to stderr?

**Comment by bronzdoc** [comment]
I'm ok with an explanatory message

**Comment by deivid-rodriguez** [comment]
I just noticed about this issue when investigating #3044 and I think this is a bug.

It is fine that `gem update --system` upgrades to a newer default version of `bundler`, but it should keep the old version in the system as a regular gem. Otherwise, upgrading `rubygems` to a version that provides a different major version of `bundler` will break applications that are locked to the old version. Upgrading rubygems should never break applications like this.

Will provide a fix for this in the next days.

**Comment by deivid-rodriguez** [comment]
To further clarify, given the instructions posted in the OP:

```
root@e4bcc426e52d:/# gem list | grep bundler
bundler (1.16.6, default: 1.16.2)

root@e4bcc426e52d:/# gem update --system
Updating rubygems-update
Fetching: rubygems-update-3.0.3.gem (100%)
Successfully installed rubygems-update-3.0.3
Installing RubyGems 3.0.3
Bundler 1.17.3 installed
RubyGems 3.0.3 installed
```

The result should be

```
root@e4bcc426e52d:/# gem list | grep bundler
bundler (default: 1.17.3, 1.16.6, 1.16.2)
```

instead of

```
root@e4bcc426e52d:/# gem list | grep bundler
bundler (default: 1.17.3, 1.16.6)
```

**Comment by wisetara** [comment]
Is there any update to this card? I followed a path here from https://github.com/rvm/rvm/issues/4901, which is preventing Codeship from adding the newest rubies, and then to https://github.com/rubygems/rubygems/issues/3044, where @deivid-rodriguez indicated this card might be the source of that card's problems. 

Also, thanks for all your work on rubygems, folks. Truly appreciated. 👋 @schneems! - Tara

**Comment by eregon** [comment]
> Having the rubygems update command also modify the version of bundler was unexpected to me.

I also agree updating RubyGems shouldn't update Bundler.
That should be done with `gem update bundler`, if desired.
There is no need for it.
I would think most Rubyists expect `gem update --system` to update RubyGems and nothing else, as it always was before this change.

Whatever our point of view, Bundler is a gem, with possibly multiple versions installed, and using `site_ruby` to install Bundler on `gem update --system` and silently override the default Bundler gem tht ships with Ruby is a dangerous hack that brings confusion.

I think the solution is clear here: don't install Bundler as part of `gem update --system`. There is no need.

**Comment by eregon** [comment]
To clarify the last point, on a fresh Ruby 2.6 install:
```
$ ruby -v
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
$ gem list bundler

*** LOCAL GEMS ***

bundler (default: 1.17.2)
$ gem --version
3.0.3
$ cat Gemfile
source 'https://rubygems.org'

gem "rspec"
$ bundle install
... # works
$ gem update --system
...
$ bundle install
Traceback (most recent call last):
	2: from /home/eregon/.rubies/ruby-266-ruby-build/bin/bundle:23:in `<main>'
	1: from /home/eregon/.rubies/ruby-266-ruby-build/lib/ruby/site_ruby/2.6.0/rubygems.rb:296:in `activate_bin_path'
/home/eregon/.rubies/ruby-266-ruby-build/lib/ruby/site_ruby/2.6.0/rubygems.rb:277:in `find_spec_for_exe': Could not find 'bundler' (1.17.2) required by your /home/eregon/tmp/empty/project-bundle1/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.2`
$ gem list bundler

*** LOCAL GEMS ***

bundler (default: 2.1.4)
```

**Comment by deivid-rodriguez** [comment]
Repro steps are already posted in the [linked PR](https://github.com/rubygems/rubygems/pull/3045#issuecomment-568219655). But thanks.
