### ISSUE TITLE
 Latency or Timeout Reaching to: https://rubygems.global.ssl.fastly.net/test in China Network

### ISSUE THREAD

**Issue by Dragoncell** [rubygems/rubygems#2677]
I'm having a problem 

Impact Time: 05:45-09:00 PDT 03/08/2019
Latency or Timeout Reaching to: https://rubygems.global.ssl.fastly.net/test 

This issue is related to:

  - [ X] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

**Comment by colby-swandale** [comment]
I doubt this is an issue with the RubyGems library, i suggest moving this issue to https://github.com/rubygems/rubygems.org
