### ISSUE TITLE
Could not install cocoapods

### ISSUE THREAD

**Issue by ricardolousada** [rubygems/rubygems#2683]
I'm having a problem or would like to suggest a feature.

My current problem - not able to install cocoapods running the command: sudo gem install cocoapods

The terminal error is: 
ERROR:  Could not find a valid gem 'cocoapods' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/specs.4.8.gz)

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X ] Other

Here are my current environment details:
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.3
  - RUBY VERSION: 2.6.2 (2019-03-13 patchlevel 47) [x86_64-darwin17]
  - INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/2.6.0
  - USER INSTALLATION DIRECTORY: /Users/rlousada/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /usr/local/opt/ruby/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /usr/local/lib/ruby/gems/2.6.0/bin
  - SPEC CACHE DIRECTORY: /Users/rlousada/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/Cellar/ruby/2.6.2/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-17
  - GEM PATHS:
     - /usr/local/lib/ruby/gems/2.6.0
     - /Users/rlousada/.gem/ruby/2.6.0
     - /usr/local/Cellar/ruby/2.6.2/lib/ruby/gems/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/opt/ruby/bin
     - /Users/rlousada/anaconda3/bin
     - /Applications/google-cloud-sdk/bin
     - //anaconda/bin
     - /Library/Java/JavaVirtualMachines/jdk1.7.0_79.jdk/Contents/Home/bin
     - /Library/Frameworks/Python.framework/Versions/2.7/bin
     - /usr/local/mysql/bin/
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/go/bin
     - /opt/Ghostscript/bin
     - /opt/X11/bin
     - /opt/ImageMagick/bin
     - /usr/local/apache-maven/apache-maven-3.3.3/bin
     - /Users/rlousada/Library/Android/sdk/emulator
     - /Users/rlousada/Library/Android/sdk/tools
     - /Users/rlousada/Library/Android/sdk/tools/bin
     - /Users/rlousada/Library/Android/sdk/platform-tools
     - /Users/rlousada/.npm-global/bin
     - /Users/rlousada/urs/local/bin/npm

$ gem env version

Bundler       1.17.3
  Platforms   ruby, x86_64-darwin-17
Ruby          2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin17]
  Full Path   /usr/local/opt/ruby/bin/ruby
  Config Dir  /usr/local/Cellar/ruby/2.6.2/etc
RubyGems      3.0.3
  Gem Home    /usr/local/lib/ruby/gems/2.6.0
  Gem Path    /Users/rlousada/.gem/ruby/2.6.0:/usr/local/lib/ruby/gems/2.6.0:/usr/local/Cellar/ruby/2.6.2/lib/ruby/gems/2.6.0
  User Path   /Users/rlousada/.gem/ruby/2.6.0
  Bin Dir     /usr/local/lib/ruby/gems/2.6.0/bin
Tools         
  Git         2.14.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2019-03-04
Git SHA           d7089abb6
Released Version  false
```


OpenSSL 1.0.2q  20 Nov 2018

I'm running in macOS High Sierra version 10.13.6

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by ricardolousada** [comment]
@bronzdoc any updates on this issue? Can you help please?
I'm having issues again with another library:
error: /Users/rlousada/Documents/Developer/react-native/pushNotifications/ios/Pods/Target Support Files/Pods-pushnofifications/Pods-pushnofifications.debug.xcconfig: unable to open file (in target "pushnofifications" in project "pushnofifications") (in target 'pushnofifications')

I bealive this is because when EXPO is bulding the ios version to run it can't install the pods.

Help would be very much appreciated :)

**Comment by bronzdoc** [comment]
Hi @ricardolousada where you able to install cocoapods? if not please check https://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html#troubleshooting-certificate-errors

> error: /Users/rlousada/Documents/Developer/react-native/pushNotifications/ios/Pods/Target Support Files/Pods-pushnofifications/Pods-pushnofifications.debug.xcconfig: unable to open file (in target "pushnofifications" in project "pushnofifications") (in target 'pushnofifications')

Sorry but this is not a Rubygems issue, i don't know how to solve it

**Comment by ricardolousada** [comment]
Hi @bronzdoc no i did not, it's a mess tried +10 solutions and "killed" some dependencies on the process. I will try your recommendation and if does not work i will start a clean installation of the OS and all the products.

Thanks any way :)
