### ISSUE TITLE
uninstall all gems without interactive y/n prompts

### ISSUE THREAD

**Issue by jrochkind** [rubygems/rubygems#2691]
I would like to uninstall all my gems. 

If i run:

    gem uninstall --all --force

I still get lots of prompts for "Remove executables", for instance:

```
Remove executables:
	ascii85

in addition to the gem? [Yn]
```

So I need to babysit the process and keep hitting return to get past all those prompts. This would be worse if I wanted to automate it for some reason. 

Should there be a way to just bulk uninstall all gems without interactive prompts?

This is related to the discussion at #2331 and part of that same general issue of "prevent interactive prompts for automated processes", but a different use case than the one that ended up discussed there, so opening as a new issue per request of @hsbt .

**Comment by duckinator** [comment]
Possible workaround in the meantime, if you're on a \*nix system (e.g. Linux, macOS, BSD):

```
yes | gem uninstall --all --force
```

**Comment by dbuckwalter** [comment]
This works for me: 
```sh
gem uninstall --all --force --executables
```

**Comment by bronzdoc** [comment]
@jrochkind does @dbuckwalter or @duckinator suggestions would work for you?
