### ISSUE TITLE
Random CI failure

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#2708]
Last build on master failed possibily due to an order depedent issue: https://travis-ci.org/rubygems/rubygems/jobs/513112478.
 
This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by duckinator** [comment]
It looks like it's trying to use Windows paths on an Ubuntu system, for some reason. O.o

---

First, it says it's running "xenial", which is Ubuntu 16.04 LTS:

```
Worker information
hostname: e7c5f900-552c-46d0-a3f8-143b1a16c626@1.production-2-worker-org-gce-hlxz
version: v6.2.0 https://github.com/travis-ci/worker/tree/5e5476e01646095f48eec13196fdb3faf8f5cbf7
instance: travis-job-8b5b10f0-960e-4685-8281-7c3a1ea0f6fd travis-ci-sardonyx-xenial-1547455603-2c98a19 (via amqp)
startup: 6.812506515s
```

Yet, we then see this:

```
Errno::ENOENT: No such file or directory - C:/Ruby18/bin/ruby.exe
```

And then this:

```
C:/Ruby18/bin/ruby.exe -I /home/travis/build/rubygems/rubygems/lib -r ./siteconf20190329-3292-1hpreg6.rb extconf.rb
extconf failedNo such file or directory - C:/Ruby18/bin/ruby.exe
```
