### ISSUE TITLE
Array values in the parameter to `Gem.paths=` are deprecated in rails? 

### ISSUE THREAD

**Issue by kenkuts** [rubygems/rubygems#2714]
I'm having a problem or would like to suggest a feature.

My current problem is I forked a project from one of my coding bootcamp projects and after bundle installing and running rails console it gives me this error: 

Array values in the parameter to `Gem.paths=` are deprecated.
Please use a String or nil.
An Array ({"GEM_PATH"=>["/Users/kenkuts/.rvm/gems/ruby-2.5.3", "/Users/kenkuts/.rvm/gems/ruby-2.5.3@global"]}) was passed in from bin/rails:3:in `load'
/Users/kenkuts/.rvm/gems/ruby-2.5.3/gems/activesupport-4.2.5/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Fixnum is deprecated
/Users/kenkuts/.rvm/gems/ruby-2.5.3/gems/activesupport-4.2.5/lib/active_support/core_ext/numeric/conversions.rb:121: warning: constant ::Bignum is deprecated

Also when I check my rails version it gives me this error: 
Array values in the parameter to `Gem.paths=` are deprecated.
Please use a String or nil.
An Array ({"GEM_PATH"=>["/Users/kenkuts/.rvm/gems/ruby-2.5.3", "/Users/kenkuts/.rvm/gems/ruby-2.5.3@global"]}) was passed in from bin/rails:3:in `load'

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.8
rails -v
4.2.5
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Hi @kenkuts 👋 

Please report this to the Rails repository, since this is not a Rubygems issue, thanks.
