### ISSUE TITLE
Openssl showing intermittent connectivity issues to api.rubygems.org

### ISSUE THREAD

**Issue by SampadHota** [rubygems/rubygems#2724]
I'm having an intermittent problem connecting to rubygem. It's not the case to any other connectivity.

My current problem is intermittently openssl fail to connect same as https://help.rubygems.org/discussions/problems/31156-problems-connecting-to-rubygems

This issue is related to:

  - [x] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:
CentOS 6.7/Ubuntu
```
$ gem env version
PASTE HERE
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Hi @ricardolousada please check https://bundler.io/v1.16/guides/rubygems_tls_ssl_troubleshooting_guide.html#troubleshooting-certificate-errors

**Comment by bronzdoc** [comment]
Please let us know if the problem still persist after reading the Trooubleshooting guide

**Comment by ricardolousada** [comment]
Hi Luís, yes the problem still persist I have all the new versions installed but no connection, this time the error is:

Could not find a valid gem 'cocoapods' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - Errno::ECONNRESET: Connection reset by peer - SSL_connect (https://rubygems.org/specs.4.8.gz)

**Comment by SampadHota** [comment]
Here's your Ruby and OpenSSL environment:

Ruby: 2.3.1p112 (2016-04-26 revision 0) [x86_64-linux-gnu]
RubyGems: 2.5.2.1
Compiled with: OpenSSL 1.0.2g 1 Mar 2016
Loaded version: OpenSSL 1.0.2g 1 Mar 2016
SSL_CERT_FILE: /usr/lib/ssl/cert.pem
SSL_CERT_DIR: /usr/lib/ssl/certs

With that out of the way, let's see if you can connect to rubygems.org...

Bundler connection to rubygems.org: failed ❌ (uninitialized constant Bundler)
RubyGems connection to rubygems.org: success ✅
Ruby net/http connection to rubygems.org: failed ❌

Unfortunately, this Ruby can't connect to rubygems.org. 😡
Even worse, we're not sure why. 😕

Here's the full error information:
Errno::ECONNRESET: Connection reset by peer - SSL_connect
/usr/lib/ruby/2.3.0/net/http.rb:933:in `connect_nonblock'
/usr/lib/ruby/2.3.0/net/http.rb:933:in `connect'
/usr/lib/ruby/2.3.0/net/http.rb:863:in `do_start'
/usr/lib/ruby/2.3.0/net/http.rb:858:in `start'
(eval):90:in `<main>'
-e:1:in `eval'
-e:1:in `<main>'

**Comment by SampadHota** [comment]
it's not a certificate error, it's a connection reset

**Comment by MSP-Greg** [comment]
RubyGems is connecting to rubygems.org, but **Ruby** cannot.

RubyGems (both current & 2.5.2.1) has it's own certs bundled with it.  Ruby is using the certs at `/usr/lib/ssl/cert.pem`.

They may need to be updated.

**Comment by SampadHota** [comment]
Any update here ?

**Comment by MSP-Greg** [comment]
@SampadHota

You're on Linux, I'm a Windows type, but I'm familiar with OpenSSL, RubyGems, etc.

Given where things are and the troubles you're having, I might suggest updating RubyGems manually.

You can download them from
https://rubygems.org/downloads/rubygems-update-3.0.3.gem
or
https://rubygems.org/downloads/rubygems-update-2.7.9.gem

then something like
```
gem install -l <full path to gem file>
update_rubygems
```

After that, things should work...

**Comment by SampadHota** [comment]
This is not a viable option for the developers to install rubygems on each machine. Do you see 66.163.37.45 in your blacklist at all or related ? The problem is intermittent and can be reproduced at ease. Can we schedule a troubleshooting call w/ your engineers ?
