### ISSUE TITLE
config_file.rb attempts to load `C` drive as valid GEMRC path on Windows

### ISSUE THREAD

**Issue by briancain** [rubygems/rubygems#2733]
I discovered a bug with how the `config_file.rb` looks at the `GEMRC` environment variable for Windows paths:

https://github.com/rubygems/rubygems/blob/edf1dbd5b1ecf0cc55e06f59fa1007b4f55ef612/lib/rubygems/config_file.rb#L200

This regex looks at the `GEMRC` environment variable and splits the string on `:` and `;`, assuming that these characters delimit each path where a gemrc could live on the machine. However if you're on windows, that ends up splitting paths with the drive letter in it as two paths.

If you set your `GEMRC` path to anything on Windows, this line ends up handling the `C` in each file path as its own. Later on the next line, when the class goes to load any gemrc files, it attempts to load the folder C.

It looks like if the folder `C` does not exist locally from where the context has been invoked, it will return early without an error. However if in that directory there is a file "C", it fails since "C" is a directory and not a file.

So for example: `C:\Users\me\gem\gemrc` gets split into `["C", "\Users\me\gem\gemrc"]` and it attempts to load `"C"` as a gemrc.

```ruby
Errno::EISDIR: Is a directory @ rb_sysopen - C
```

Maybe the regex could be improved, or perhaps there's a better way of getting all the paths?

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

This bug is also currently on `master` (linked above).

```
$ gem env version
2.4.0
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md). :ok: :+1:

**Comment by briancain** [comment]
Happy to push up a fix if anyone has a good idea. I thought about changing the regex, but that will complicate things a lot there :thinking:

**Comment by MSP-Greg** [comment]
Maybe change:
```ruby
split(/[:;]/)
```
to
```ruby
split(File::PATH_SEPARATOR)
```

??

Kind of AFK right now...

**Comment by djberg96** [comment]
@MSP-Greg that should work.

**Comment by MSP-Greg** [comment]
@briancain 

You found the bug, I thought I'd let you do the PR.  Let us know...

**Comment by MSP-Greg** [comment]
@djberg96

While taking a break, I noticed that `config_file.rb` may also play a part in the issue where build arguments from the command line cause `.gemrc` info to be ignored...

**Comment by MSP-Greg** [comment]
See PR #2735

**Comment by briancain** [comment]
Hey @MSP-Greg ! Sorry, I was AFK this weekend. Thanks for the PR! Just patched it locally for testing and it fixes up the issue.

**Comment by bronzdoc** [comment]
closed by https://github.com/rubygems/rubygems/pull/2735
