### ISSUE TITLE
Gem::Specification#files is improperly including directories

### ISSUE THREAD

**Issue by djberg96** [rubygems/rubygems#2743]
Apparently, I've been building my files list improperly for a very long time. I was doing this in my gemspecs for setting the files:

`Dir['**/*'].reject{ |f| f.include?('git') }`

The problem with that is that it includes directories as separate elements. For example, in my [sys-admin](https://github.com/djberg96/sys-admin) gem, `Gem::Specification#files` returns this list on a `Gem.pre_install`:

```
["test","test/test_sys_admin_windows.rb", "test/test_sys_admin.rb", "test/test_sys_admin_unix.rb", "CHANGES", "MANIFEST", "README", "Rakefile", "certs", "certs/djberg96_pub.pem", "examples", "examples/example_users.rb", "examples/example_groups.rb", "lib", "lib/sunos", "lib/sunos/sys", "lib/sunos/sys/admin.rb", "lib/bsd", "lib/bsd/sys", "lib/bsd/sys/admin.rb", "lib/sys-admin.rb", "lib/unix", "lib/unix/sys", "lib/unix/sys/admin.rb", "lib/sys", "lib/sys/admin", "lib/sys/admin/common.rb", "lib/sys/admin/custom.rb", "lib/sys/admin.rb", "lib/linux", "lib/linux/sys", "lib/linux/sys/admin.rb", "lib/darwin", "lib/darwin/sys", "lib/darwin/sys/admin.rb", "lib/windows", "lib/windows/sys", "lib/windows/sys/admin.rb", "doc", "doc/sys-admin-windows.txt", "doc/sys-admin-unix.txt", "sys-admin.gemspec"]
```

You can see that it's including files like "lib/darwin", which is a subdirectory, as a separate thing. However, the comments in Gem::Specification specifically say these are stripped:

"Directories are automatically stripped from this list when building a gem, other non-files cause an error."

https://github.com/rubygems/rubygems/blob/4de1cfa37/lib/rubygems/specification.rb#L238-L239

So, is there code/validation missing somewhere? Or are the docs just wrong?

**Comment by bronzdoc** [comment]
@djberg96 Dirs should be stripped, see: https://github.com/rubygems/rubygems/blob/4de1cfa372df21a1e71a5752c420f7fe4afa8971/lib/rubygems/specification.rb#L2609 

So probably a bug, i'm looking into it right now.

**Comment by djberg96** [comment]
@bronzdoc In case it's significant, the `Package#contents` are correct, but `Specification#files` are not.

**Comment by bronzdoc** [comment]
@djberg96 I just checked, so this is not a bug and it's the intended behavior, the comment:
```
# Directories are automatically stripped from this list when building a gem, 
```
is correct

since we validate in https://github.com/rubygems/rubygems/blob/4de1cfa372df21a1e71a5752c420f7fe4afa8971/lib/rubygems/package.rb#L270

If i build the ` sys-admin gem` after `@spec.validate` i got:
```
["CHANGES", "MANIFEST", "README", "Rakefile", "certs/djberg96_pub.pem", "doc/sys-admin-unix.txt", "doc/sys-admin-windows.txt", "examples/example_groups.rb", "examples/example_users.rb", "lib/bsd/sys/admin.rb", "lib/darwin/sys/admin.rb", "lib/linux/sys/admin.rb", "lib/sunos/sys/admin.rb", "lib/sys-admin.rb", "lib/sys/admin.rb", "lib/sys/admin/common.rb", "lib/sys/admin/custom.rb", "lib/unix/sys/admin.rb", "lib/windows/sys/admin.rb", "sys-admin.gemspec", "test/test_sys_admin.rb", "test/test_sys_admin_unix.rb", "test/test_sys_admin_windows.rb"]
```

which is what you want isn't it?

**Comment by djberg96** [comment]
I think I see. I'm building with `Gem::Package.build(spec, true)` which is disabling it.

Alright, I'm pretty sure I don't like this behavior because I don't see what stripping/cleaning files has to do with validations. The other thing I don't like is that, even if I remove the second argument, there's no indication that any files were removed amongst the other warnings.

**Comment by bronzdoc** [comment]
>  I don't see what stripping/cleaning files has to do with validations
Agree

Will work on improve it, maybe we can ensure `spec.files` has actual files at the time of creating a new Specification object, so we don't have to rm directories when validating a specification

**Comment by djberg96** [comment]
Alright, going to close this since it's ultimately my own fault. We can create a separate issue for how we want to handle stripping and cleaning files.
