### ISSUE TITLE
Missing Rubygems Data dumps past March 11, 2019

### ISSUE THREAD

**Issue by krithika369** [rubygems/rubygems#2744]
I'm having a problem.

My current problem is that I cannot locate the Rubygems weekly data dumps past March 11. Has this been discontinued? https://rubygems.org/pages/data
I would like to retrieve the information on the newly added versions and do some analytics. While this can be accomplished using the APIs, the data dump was a lot more convenient. Please let me know if you require any other information.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [+] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
Can you file this to https://github.com/rubygems/rubygems.org ? This repository only handles rubygems client.
