### ISSUE TITLE
Is Gem::Installer#gem actually set?

### ISSUE THREAD

**Issue by djberg96** [rubygems/rubygems#2750]
While fiddling around with gem plugins and tinkering with the `Gem::Installer` class in general, I noticed that there's an attr_reader for `:gem`. However, near as I can tell, this value is never set. I don't see `@gem` set anywhere.

https://github.com/rubygems/rubygems/blob/master/lib/rubygems/installer.rb#L49

With Gem.pre_install, this value always comes back nil. You can try with the following code:

```
# Put this in 'lib/rubygems_plugin.rb' somewhere
# Run RUBYOPT=-Ilib gem install any_gem
#
Gem.pre_install do |installer|
  p installer.gem # nil
end
```

**Comment by djberg96** [comment]
@bronzdoc @segiddins Any idea if this is supposed to be set, and what it's supposed to be set to?

**Comment by segiddins** [comment]
Zero clue, sorry

**Comment by bronzdoc** [comment]
@djberg96 
well... it's suposed to be set to `Filename of the gem being installed.` but i don't see where is set or if it set at all as you mentioned, i ran the test suite with out it to see if there was something testing for it, but there is no test failures.

**Comment by djberg96** [comment]
@bronzdoc I wasn't entirely sure what the "filename of the gem" is supposed to be. Is it referring to the `.tar.gz` filename? Or just the gem name? Or perhaps the output of `gem which`?

Maybe I'm overthinking it.

**Comment by bronzdoc** [comment]
@djberg96 that's a good question, but i don't know the answer.

Could have been any of the tree but since it never was setup we will never know, but of the 3 options what would be the best to be in your opinion?

**Comment by djberg96** [comment]
My gut reaction is that it was meant to be the name of the `.tar.gz` file, but I'm not married to the idea or anything.

@drbrain Don't suppose you remember, do you?

**Comment by bronzdoc** [comment]
Can this be closed @djberg96 ?

**Comment by djberg96** [comment]
@bronzdoc was it fixed?

**Comment by djberg96** [comment]
@bronzdoc I spent some more time looking at this. I think we ultimately want the `package.gem.path`, but that means two accessors: the `package` reader for `Gem::Package` and, once that's in place, a method like so:

```
def gem
  @package.gem.path
rescue Gem::Package::Error => e
  raise Gem::InstallError, "invalid gem: #{e.message}"
end
```

Part 1 is at https://github.com/rubygems/rubygems/pull/2796

**Comment by djberg96** [comment]
Fixed in core, closing. Thanks!
