### ISSUE TITLE
Tab-completion when attempting to push a built gem results in command-line error

### ISSUE THREAD

**Issue by jwir3** [rubygems/rubygems#2758]
I'm having a problem.

My current problem is when I attempt to use `gem push` with a previously built gem and tab-complete the name, I get the following: 
```
_arguments:comparguments:325: doubled rest argument definition: *:gem:_files -g "*.gem(-.)"
```

Specific steps to reproduce:
1. Download the following source package: https://github.com/FoamFactory/bubbles
2. cd to `bubbles`
3. Run `gem build bubbles.gemspec`. This should create a `bubbles-rest-client-X.Y.Z.gem` file in the local directory.
4. Type `gem push bubb`, followed by <kbd>TAB</kbd>, in order to tab-complete the name of the file.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [x] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.11
```

Operating system:
Mac OS 10.14.5 Beta

 - [x] I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
This issue was fixed at https://github.com/zsh-users/zsh/pull/35 maybe.
