### ISSUE TITLE
SSL verification error at depth 2: certificate is not yet valid (9)

### ISSUE THREAD

**Issue by lengquan** [rubygems/rubygems#2759]
I'm trying to'gem install bundle',but every time I do it I get this error:

`ERROR:  SSL verification error at depth 2: certificate is not yet valid (9)
ERROR:  Certificate /C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA not valid until 1998-09-01T12:00:00Z
ERROR:  SSL verification error at depth 2: certificate is not yet valid (9)
ERROR:  Certificate /C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA not valid until 1998-09-01T12:00:00Z
ERROR:  SSL verification error at depth 2: certificate is not yet valid (9)
ERROR:  Certificate /C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA not valid until 1998-09-01T12:00:00Z
ERROR:  Could not find a valid gem 'bundle' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)
ERROR:  SSL verification error at depth 2: certificate is not yet valid (9)
ERROR:  Certificate /C=BE/O=GlobalSign nv-sa/OU=Root CA/CN=GlobalSign Root CA not valid until 1998-09-01T12:00:00Z`

`root@b:~# ruby -v
ruby 2.4.1p111 (2017-03-22 revision 58053) [armv7l-linux-eabihf]
root@b:~# gem -v
2.6.11
root@b:~# rbenv -v
rbenv 1.1.2
root@b:~# ruby -ropenssl -e 'p OpenSSL::OPENSSL_VERSION'
"OpenSSL 1.1.0j  20 Nov 2018"`

Hopefully you guys can help thanks

**Comment by duckinator** [comment]
It says the root CA crtificate isn't valid "until 1998", which implies your system clock is set to _before_ 1998.

Can you run this command and let me know the output?:

```
ruby -r date -e "puts DateTime.now"
```

**Comment by bronzdoc** [comment]
@lengquan please provide the requested output so we can reopen this, thanks.
