### ISSUE TITLE
Performance issue in rubygems Kernel.require

### ISSUE THREAD

**Issue by lamont-granquist** [rubygems/rubygems#2761]
Working on rubygems 3.0.3 and doing a lot of strace'ing of a process which has a lot of gems already in an activated state (via calling Kernel#gem).

What I see is that when Kernel#require is called into rubygems this code here is ultimately exercised to find the gem:

```
    if Gem::Specification.find_active_stub_by_path(path)
      RUBYGEMS_ACTIVATION_MONITOR.exit
      return gem_original_require(path)
    end
```

What happens is that `Gem::Specification.find_active_stub_by_path(path)` does all the work of walking through the filesystem and calling lstat() on a ton of files, it determines the correct path in the filesystem.  Then all it does is return a boolean true/false value and then calls the ruby gem_original_require with the original string which then re-walks the filesystem (using open() instead of stat() which is terrible on windows and greatly magnifies this perf issue, which is presumably a core ruby perf bug).  

So in my case I used `require "chef/mixin/from_file"` from the chef gem and ultimately find_active_stub_by_path finds the file:

```
stat("/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.279/lib/chef/mixin/from_file", 0x7ffdb4480bf0) = -1 ENOENT (No such file or directory)
stat("/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.279/lib/chef/mixin/from_file.rb", {st_mode=S_IFREG|0664, st_size=1834, ...}) = 0
```

I then threw debug logging into the call to see what string gem_original_require is being called with:

```
write(2, "DONE: chef/mixin/from_file\n", 27DONE: chef/mixin/from_file
) = 27
```

Then core-ruby re-walks the entire activated gemset using open:

```
open("/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/public_suffix-3.0.3/lib/chef/mixin/from_file.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/addressable-2.6.0/lib/chef/mixin/from_file.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/mixlib-shellout-2.4.4/lib/chef/mixin/from_file.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/mixlib-cli-2.0.3/lib/chef/mixin/from_file.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/appbundler-0.12.5/lib/chef/mixin/from_file.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/bcrypt_pbkdf-1.0.1/lib/chef/mixin/from_file.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/chef/embedded/lib/ruby/gems/2.6.0/extensions/x86_64-linux/2.6.0/bcrypt_pbkdf-1.0.1/chef/mixin/from_file.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/debug_inspector-0.0.3/lib/chef/mixin/from_file.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/chef/embedded/lib/ruby/gems/2.6.0/extensions/x86_64-linux/2.6.0/debug_inspector-0.0.3/chef/mixin/from_file.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
[...114 total open() calls...]
open("/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-zero-14.0.12/lib/chef/mixin/from_file.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/iniparse-1.4.4/lib/chef/mixin/from_file.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/syslog-logger-1.6.8/lib/chef/mixin/from_file.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/proxifier-1.0.3/lib/chef/mixin/from_file.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = -1 ENOENT (No such file or directory)
open("/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.279/lib/chef/mixin/from_file.rb", O_RDONLY|O_NONBLOCK|O_CLOEXEC) = 5
```

It seems like there is a bug on the rubygems side, because rubygems does the work of getting the correct answer of "/opt/chef/embedded/lib/ruby/gems/2.6.0/gems/chef-15.0.279/lib/chef/mixin/from_file.rb" and then it throws that away and forces core-ruby's require to rescan the filesystem.

**Comment by lamont-granquist** [comment]
I think a fix might be as simple as:

```
    if spec = Gem::Specification.find_active_stub_by_path(path)
      RUBYGEMS_ACTIVATION_MONITOR.exit
      return gem_original_require(spec.to_fullpath(path))
    end
```

almost seems to easy, not sure if i'm missing something...

**Comment by lamont-granquist** [comment]
Oh right this probably runs into the same ruby < 2.5.0 bugs that require_relative hits:

https://github.com/rubygems/rubygems/pull/2425#issuecomment-427535667

**Comment by lamont-granquist** [comment]
Actually maybe that bug doesn't affect this since that only seems to affect require_relative traversing symlinks

**Comment by lamont-granquist** [comment]
Testing on ruby-2.2 it seems to work fine:

```
% pry
[1] pry(main)> gem "chef"
=> true
[2] pry(main)> Kernel.send :gem_original_require, '/Users/lamont/.rvm/gems/ruby-2.2.10/gems/chef-12.22.5/lib/chef/mixin/from_file.rb'
=> true
[3] pry(main)> Kernel.send :gem_original_require, '/Users/lamont/.rvm/gems/ruby-2.2.10/gems/chef-12.22.5/lib/chef/mixin/from_file.rb'
=> false
[4] pry(main)> Kernel.send :gem_original_require, 'chef/mixin/from_file'
=> false
[5] pry(main)>
```

**Comment by deivid-rodriguez** [comment]
@lamont-granquist Nice investigation, your fix looks good to me :+1:. I don't think `require_relative` is involved here anyways though, right?

**Comment by lamont-granquist** [comment]
Yeah I thought that core ruby bug was broader than just require_relative, but it's isolated to that.  Doesn't look like that would be a concern here.

**Comment by lamont-granquist** [comment]
Doing some macro benchmarks, this seems to not quite have the impact that I thought it would have, but it is still forward progress.

Before I ripped require_relative across the chef-client code base internally, applying this patch produces about a 5% speedup in `chef-client --version` and reduces open() calls from 105846 to 78255:

```
Chef Infra Client: 15.0.276
/opt/chef/bin/chef-client --version  2.43s user 0.90s system 83% cpu 4.011 total

% strace -f -c /opt/chef/bin/chef-client --version
strace: Process 44180 attached
Chef Infra Client: 15.0.276
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 47.55    0.360709           3    138777    134075 stat
 39.71    0.301194           3    105846    102814 open
  5.87    0.044508           2     18266           lstat
```

to

```
Chef Infra Client: 15.0.276
/opt/chef/bin/chef-client --version  2.39s user 0.81s system 82% cpu 3.880 total

% strace -f -c /opt/chef/bin/chef-client --version
strace: Process 43306 attached
Chef Infra Client: 15.0.276
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 53.58    0.373261           3    139570    134440 stat
 32.42    0.225828           3     78255     75235 open
  6.71    0.046758           3     18266           lstat
```

Taking the chef-client codebase AFTER i ripped require_relative across it, and applying this patch produces about a 1-2% speedup in `chef-client --version` and reduces the open syscalls from 62605 to 56812.

This was tested on Linux, I suspect (but have not verified) that the impact on Windows is more substantial due to additional open() overhead.

I'll still work on a PR for this since it'll help, but its not quite the panacea I was hoping for yesterday.

**Comment by lamont-granquist** [comment]
So actually trying this patch and running the rubygems tests fail on this:

```
  # Providing -I on the commandline should always beat gems
  def test_dash_i_beats_gems
```

That might provide part of the answer to #2762 which is that the Kernel.gem_original_require call is responsible for correct load-ordering and ensures that -I beats gems which beats core libs

**Comment by lamont-granquist** [comment]
Okay this may not be a bugfixable problem in rubygems after all.

The culprit appears to be a stray unresolved spec.  The rubygems code which walks through the activated gems is only being called because `Gem::Specification.unresolved_deps.empty?` is not empty.

The actual spec which, in our case, is unresolved is (drumroll...):

```
{"bundler"=>
  Gem::Dependency.new("bundler", Gem::Requirement.new([">= 1.10"]), :runtime)}
```

so just `gem "bundler"` (or actually `require "bundler"`) will fix most of the rubygems-side of this perf issue.

So starting with our current baseline after chef's require_relative patch

```
% strace -f -c /opt/chef/bin/chef-client --version
strace: Process 13110 attached
Chef Infra Client: 15.0.279
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 54.78    0.308712           3    123343    117944 stat
 32.28    0.181912           3     63485     59588 open
```

Just throwing `gem "bundler"` at our entrypoint results in:

```
% strace -f -c /opt/chef/bin/chef-client --version
strace: Process 13613 attached
Chef Infra Client: 15.0.279
% time     seconds  usecs/call     calls    errors syscall
------ ----------- ----------- --------- --------- ----------------
 71.67    0.164895           3     63287     60180 open
 14.44    0.033229           2     17034           lstat
  2.50    0.005748           2      3664         5 read
```

still the same number of open calls, but almost all the lstat work by rubygems has disappeared.

**Comment by lamont-granquist** [comment]
And it turns out that now that I know what to look for this already got reported against the chef-dk project:

https://github.com/chef/chef-dk/issues/1987

**Comment by lamont-granquist** [comment]
Yeah closing this as it seems to come down to "make sure you don't have unresolved specs"

There may still be a perf bug here around the out of size perf hit that you take when there are unresolved specs, but I haven't done a deep enough dive into figuring out why rubygems needs to iterate through all the gems before handing off to ruby core to do it again.

And the bug I ran into was that the INC path `-I` args needs to come first before searching rubygems gems.  It seems to me like there's a separation-of-concerns problem here, and really I'd think that the searching code should get moved into rubygems proper and that rubygems would traverse the INC path correctly first and then send the resolved file into core ruby and keep core ruby simple.  Either that or the unresolved specs checking should be pushed into core ruby, but that smells wrong to me.

I suspect that a long time ago, the core ruby `Kernel.require` was extended for rubygems to support searching through rubygems because that seemed like the correct separation of concerns at the time.

Fixing this "right" though would be a large amount of surgery and definitely over my head.
