### ISSUE TITLE
Error when pushing a gem

### ISSUE THREAD

**Issue by matheussilvasantos** [rubygems/rubygems#2769]
I'm having a problem.

My current problem is pushing a gem to RubyGems.

When I try to push I receive this error:

```
Pushing gem to https://rubygems.org...
Repushing of gem versions is not allowed.
Please use `gem yank` to remove bad gem releases.
```

When I try to yank I receive this error:

```
Yanking gem from https://rubygems.org...
This gem could not be found
```

Here is the source code: https://github.com/matheussilvasantos/dynamorb

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [x] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.5.1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Can you provide the  gem command you are executing, thanks,

**Comment by matheussilvasantos** [comment]
I've tried:
- `gem build dynamorb.gemspec` and `gem push dynamorb-0.1.0.gem`;
- `rake install` and `rake release`.

**Comment by bronzdoc** [comment]
How are you getting this message?
 ```
Yanking gem from https://rubygems.org...
This gem could not be found
```

**Comment by matheussilvasantos** [comment]
When I execute these commands that I commented I get:
```
Pushing gem to https://rubygems.org...
Repushing of gem versions is not allowed.
Please use `gem yank` to remove bad gem releases.
```
Then, if I try to use `gem yank` I get this message:
```
Yanking gem from https://rubygems.org...
This gem could not be found
```

**Comment by bronzdoc** [comment]
it's weird you are getting that message with `gem yank` without passing any argument, since executing `gem yank` alone will show the following message:
```
A version argument is required: gem yank GEM -v VERSION [-p PLATFORM] [--key KEY_NAME] [--host HOST]
```

**Comment by matheussilvasantos** [comment]
Oh, I'm sorry. The command I've used was: `gem yank dynamorb -v 0.1.0`.

**Comment by keithrbennett** [comment]
What is the output of your `gem build` command?

I'm thinking there may be something in your gemspec that's making it fail. _In the gemspec file_, what is the gem name and gem version? Can you point us to your gemspec online, if not in the repo, then in a gist?

**Comment by matheussilvasantos** [comment]
Here is the output of `gem build`:
```
$ gem build dynamorb.gemspec 
  Successfully built RubyGem
  Name: dynamorb
  Version: 0.1.0
  File: dynamorb-0.1.0.gem
```

Here is the source code: https://github.com/matheussilvasantos/dynamorb

**Comment by keithrbennett** [comment]
Thanks. According to https://stackoverflow.com/questions/41454333/meaning-of-new-block-git-sourcegithub-in-gemfile, I think your code at https://github.com/matheussilvasantos/dynamorb/blob/master/Gemfile#L3 needs to be changed to include the repo name twice, separated by a slash.

**Comment by matheussilvasantos** [comment]
I've removed the line from Gemfile and I am still getting the error.

**Comment by matheussilvasantos** [comment]
The namespace is already in use, we can see it here: https://rubygems.org/names.
But it is weird because there is no gem at http://rubygems.org/gems/dynamorb.
Anyway, the problem is solved, thank you very much.

**Comment by keithrbennett** [comment]
Mattheus, sorry it didn't work out. Gem developers, is it that when a name is used for a gem that name will never be available again, even if it is deleted for a long time? And if so, is there a way to see that the name is unavailable for that reason? Preferably that the gem push error says so?

**Comment by shushugah** [comment]
Apparently the URL Param is case sensitive. And it was either pushed and yanked or something else. https://rubygems.org/gems/DynamoRB
