### ISSUE TITLE
macOS 10.14.4 - cannot run any app installed via gem

### ISSUE THREAD

**Issue by tddschn** [rubygems/rubygems#2770]
## My current problem is that I cannot run any app installed via gem on macOS 10.14.4.

This issue is related to:

  - [X] Other (it seems like some bug)

Here are my current environment details:

```
$ gem env version
3.0.3
```
```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.3
  - RUBY VERSION: 2.3.7 (2018-03-28 patchlevel 456) [universal.x86_64-darwin18]
  - INSTALLATION DIRECTORY: /Users/me/.gem
  - USER INSTALLATION DIRECTORY: /Users/me/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /Users/me/.gem/bin
  - SPEC CACHE DIRECTORY: /Users/me/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Library/Ruby/Site
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-darwin-18
  - GEM PATHS:
     - /Users/me/.gem
     - /Users/me/.gem/ruby/2.3.0
     - /Library/Ruby/Gems/2.3.0
     - /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /Users/me/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Library/TeX/texbin
     - /usr/local/MacGPG2/bin
     - /opt/X11/bin
     - /usr/local/sbin
     - /Users/me/.rvm/bin
```

## system info
ruby version: ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18] (ruby was installed via homebrew)

## how I installed ruby gem packages?
because of some kind of system protection on macOS, even root user does not have write permission to the /usr/bin directory, I use 
```
sudo gem install -n /usr/local/bin [package name]
```
instead of
```
sudo gem install [package name]
```
## what's the error message when I try to run an app installed via ruby gem?
```
$ bro # a ruby app called bro pages

/Library/Ruby/Site/2.3.0/rubygems.rb:283:in `find_spec_for_exe': can't find gem bropages (>= 0.a) with executable bro (Gem::GemNotFoundException)
        from /Library/Ruby/Site/2.3.0/rubygems.rb:262:in `bin_path'
        from /usr/local/bin/bro:22:in `<main>'
```
## what I did trying to fix the problem?
- searching, but did not find something useful.
- trying to reinstall ruby and gem on my mac, but don't know how.

thank you in advance for any help!

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Please share the oputput of `gem env`

**Comment by bronzdoc** [comment]
Cant reproduce @tddschn is this still an issue for you?

**Comment by tddschn** [comment]
yes, it is still an issue for me.

since I cannot provide detailed information, maybe you should close this issue. 

thank you for your help! :)
