### ISSUE TITLE
Need to more precisely report a failure to push caused by a previously yanked gem

### ISSUE THREAD

**Issue by keithrbennett** [rubygems/rubygems#2771]
This issue was born out of issue https://github.com/rubygems/rubygems/issues/2769. The poster of that issue went through a lot of time and effort troubleshooting his failure to push his gem. It turned out that the name of his gem was used by another gem, but that other gem had been yanked, so the cause of the problem was not apparent.

For example:

User #0 sometime in the past pushed DynamoRB version 0.1.0, and probably other versions.
User #0 subsequently yanked the gem.
User #1 writes a new gem named `dynamorb`, and tries to push version 0.1.0, but gets this error:

```
Pushing gem to https://rubygems.org...
Repushing of gem versions is not allowed.
Please use `gem yank` to remove bad gem releases.
```

However, `gem list --remote dynamorb` shows no gem by that name.

On the high level, I think we need a better way to identify and report this error.

Would it be possible for `gem push` to somehow consult the list of gem names at https://rubygems.org/names and output a more precise error message if this problem occurs?

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.0.3
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Please report this issue to https://github.com/rubygems/rubygems.org thanks
