### ISSUE TITLE
stringio is required eagerly by RubyGems

### ISSUE THREAD

**Issue by eregon** [rubygems/rubygems#2772]
Currently, RubyGems requires `stringio` eagerly:
https://github.com/rubygems/rubygems/blob/d470f1787a94f751c907e8299ec44f61b7689432/lib/rubygems/specification.rb#L17

The only usage in that file though seems in
https://github.com/rubygems/rubygems/blob/d470f1787a94f751c907e8299ec44f61b7689432/lib/rubygems/specification.rb#L2538
where it could be required on demand.

The effect of this is that `StringIO` is defined in MRI, without `require`, which makes some gems accidentally rely on RubyGems loading it:
```
$ ruby -e 'p StringIO'                                                
StringIO
```

How about requiring `stringio` lazily in RubyGems, so users of `stringio` must require it explicitly like other stdlibs, and notice easily the missing `require` if `--disable-gems` is used?

This issue is related to:
  - [x] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by eregon** [comment]
FWIW, there are quite a few files loaded eagerly by RubyGems on startup, making startup slower:
```
$ ruby --disable-gems -ve 'puts $"'         
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]
enumerator.so
thread.rb
rational.so
complex.so
/home/eregon/.rubies/ruby-2.6.2/lib/ruby/2.6.0/x86_64-linux/enc/encdb.so
/home/eregon/.rubies/ruby-2.6.2/lib/ruby/2.6.0/x86_64-linux/enc/trans/transdb.so
```

```
$ ruby -ve 'puts $"' | grep -v rubygems | grep -v did_you_mean
ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-linux]
enumerator.so
thread.rb
rational.so
complex.so
/home/eregon/.rubies/ruby-2.6.2/lib/ruby/2.6.0/x86_64-linux/enc/encdb.so
/home/eregon/.rubies/ruby-2.6.2/lib/ruby/2.6.0/x86_64-linux/enc/trans/transdb.so
Required by RubyGems:
/home/eregon/.rubies/ruby-2.6.2/lib/ruby/2.6.0/x86_64-linux/rbconfig.rb
/home/eregon/.rubies/ruby-2.6.2/lib/ruby/2.6.0/delegate.rb
/home/eregon/.rubies/ruby-2.6.2/lib/ruby/2.6.0/uri/rfc2396_parser.rb
/home/eregon/.rubies/ruby-2.6.2/lib/ruby/2.6.0/uri/rfc3986_parser.rb
/home/eregon/.rubies/ruby-2.6.2/lib/ruby/2.6.0/uri/common.rb
/home/eregon/.rubies/ruby-2.6.2/lib/ruby/2.6.0/uri/generic.rb
/home/eregon/.rubies/ruby-2.6.2/lib/ruby/2.6.0/uri/file.rb
/home/eregon/.rubies/ruby-2.6.2/lib/ruby/2.6.0/uri/ftp.rb
/home/eregon/.rubies/ruby-2.6.2/lib/ruby/2.6.0/uri/http.rb
/home/eregon/.rubies/ruby-2.6.2/lib/ruby/2.6.0/uri/https.rb
/home/eregon/.rubies/ruby-2.6.2/lib/ruby/2.6.0/uri/ldap.rb
/home/eregon/.rubies/ruby-2.6.2/lib/ruby/2.6.0/uri/ldaps.rb
/home/eregon/.rubies/ruby-2.6.2/lib/ruby/2.6.0/uri/mailto.rb
/home/eregon/.rubies/ruby-2.6.2/lib/ruby/2.6.0/uri.rb
/home/eregon/.rubies/ruby-2.6.2/lib/ruby/2.6.0/x86_64-linux/stringio.so
/home/eregon/.rubies/ruby-2.6.2/lib/ruby/2.6.0/monitor.rb
```

**Comment by deivid-rodriguez** [comment]
@eregon Yeah, I'm totally fine with lazily requiring `stringio` if we can :+1:

**Comment by deivid-rodriguez** [comment]
Also, since `stringio` is now gemified, this also means we won't impose any requirement on end users of the gem.

**Comment by eregon** [comment]
@deivid-rodriguez  @bronzdoc  Thanks for the discussion and fix!
