### ISSUE TITLE
Managing gem sources via CLI leaks sources defined outside of ~/.gemrc into ~/.gemrc

### ISSUE THREAD

**Issue by soulcutter** [rubygems/rubygems#2773]
I'm having a problem or would like to suggest a feature.

Some context: I wrote [a blog post suggesting a way of managing gem sources for people who commit their dotfiles to public repositories](http://www.soulcutter.com/articles/hiding-gemrc-credentials-in-dotfiles.html).

My current problem is that any time a `gem` command is used mutates gem sources, all sources are written to `~/.gemrc` . This is unexpected behavior since I expect that sources I define outside of `~/.gemrc` to remain outside of `~/.gemrc` so that they do not accidentally get published to a public dotfiles repository.

Steps to reproduce:

1. Create a file `~/.gemrc.local` with contents such as:
```yaml
---
:sources:
- https://rubygems.org/
- https://asdf@gemfury.io/me/
```
2. `$ export GEMRC=~/.gemrc.local`
3. `$ gem sources --remove https://rubygems.org/`
4. `$ cat ~/.gemrc` will show `https://asdf@gemfury.io/me/`

I can think of a couple of approaches that would be less-unexpected. As a side-note `$ gem sources` will still list `https://rubygems.org/` as in-effect because `~/.gemrc.local` is not edited at all and therefor the intent of the command was not fulfilled

1. The merging behavior of the gem command's configuration keeps track of where `sources` are defined and edits that location. This might be difficult (impossible?) to achieve.
2. The merging behavior of the gem command's configuration keeps track of where `sources` are defined and if that location is not `~/.gemrc` it errors / warns you that it is unable to mutate sources because sources are defined elsewhere (hinting that you will have to manually resolve that problem).

There may be a larger approach to examine, which is considering `sources` as a special configuration key that doesn't have the "shallow-merge" behavior that I describe in my blog post, and instead has a different form of configuration behavior. That could be heavy-handed for resolving this specific issue, but figured I'd throw that out there.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.0.3

$ echo $GEMRC
/Users/bradleyschaefer/.gemrc.local
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by soulcutter** [comment]
Reflecting on this after having written this up, I wonder if I buried the lede and the true problem is the thing I mentioned as an aside:
 > As a side-note `$ gem sources` will still list `https://rubygems.org/` as in-effect because `~/.gemrc.local` is not edited at all and therefor the intent of the command was not fulfilled

That seems super-weird because you are led to believe that the command is successful even though it isn't:

```
$ gem sources --remove https://rubygems.org/
https://rubygems.org/ removed from sources

$ gem sources
*** CURRENT SOURCES ***

https://rubygems.org/
https://asdf@gemfury.io/me/
```

Food for thought.

**Comment by bronzdoc** [comment]
Thanks for the report @soulcutter i was able to reproduce it.

I noticed also that by running `gem sources --remove https://rubygems.org/` my .gemrc is modified completely with the defaults i.e:

.gemrc
```
---
:sources:
- https://rubygems.org/
- https://asdf@gemfury.io/me/
```
 
After i execute  `gem sources --remove https://rubygems.org/` the .gemrc is modified to:

.germc
```
---
:backtrace: false
:bulk_threshold: 1000
:sources:
- https://asdf@gemfury.io/me/
:update_sources: true
:verbose: true
:concurrent_downloads: 8
```

which is a weird side effect for just wanting to remove a source
