### ISSUE TITLE
Pre-compiled gems for several ruby versions

### ISSUE THREAD

**Issue by giorgian** [rubygems/rubygems#2775]
I need to precompile a few ruby gems with native extensions and upload them on a private rubygems reporitory, making them available for different Ruby versions.

I've been reading the API documentation, but I still cannot find what I am supposed to do to obtain that "gem install my-gem -v 1.2.3" just installs the precompiled gem.

Am I supposed to name the gem file differently for each ruby version? To use a different directory?

This issue is related to:

  - [ ] Network problems
  - [X] Installing a library
  - [X] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
I don't know the answer to that, sorry.

This issue tracker is for issues related to the `gem` client tool, you might find a better answer using something like stackoverflow.

**Comment by giorgian** [comment]
Sorry, I thought this issue tracker was also about the rubygems API and tooling system and their documentation.
I'm trying to use the tooling and API to accomplish something that doesn't seem to me so much outside of their actual scope and would very much like to know whether what I'm trying to do is at all possible.

Is there an issue tracker for the rubygems tooling and API?

Thank you

**Comment by deivid-rodriguez** [comment]
@giorgian I've never shipped a gem with precompiled versions for each platform, but you can investigate how existing gems do this. For example, [nokogiri](https://github.com/sparklemotion/nokogiri). I think most gems use https://github.com/rake-compiler/rake-compiler-dock nowadays to help building these gems.
