### ISSUE TITLE
Kill bIll Stripe version Plugin failed 

### ISSUE THREAD

**Issue by goelscubic** [rubygems/rubygems#2786]
I am having problem to install stripe plugin with killbill 0.20 version . error 

OpenSSL::SSL::SSLError - certificate verify failed: 	org/jruby/ext/openssl/SSLSocket.java:215:in `connect' 	classpath:/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:800:in `connect' 	org/jruby/ext/timeout/Timeout.java:98:in `timeout' 	classpath:/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:800:in `connect' 	classpath:/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:756:in `do_start' 	classpath:/META-INF/jruby.home/lib/ruby/1.9/net/http.rb:745:in `start' 	classpath:/META-INF/jruby.home/lib/ruby/1.9/open-uri.rb:306:in `open_http' 	classpath:/META-INF/jruby.home/lib/ruby/1.9/open-uri.rb:776:in `buffer_open' 	classpath:/META-INF/jruby.home/lib/ruby/1.9/open-uri.rb:203:in `open_loop' 	org/jruby/RubyKernel.java:1242:in `catch' 	classpath:/META-INF/jruby.home/lib/ruby/1.9/open-uri.rb:201:in `open_loop' 	classpath:/META-INF/jruby.home/lib/ruby/1.9/open-uri.rb:146:in `open_uri' 	classpath:/META-INF/jruby.home/lib/ruby/1.9/open-uri.rb:678:in `open' 	classpath:/META-INF/jruby.home/lib/ruby/1.9/open-uri.rb:686:in `read' 	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/kpm-0.6.5/lib/kpm/plugins_directory.rb:9:in `all' 	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/lib/kpm/plugins_installer.rb:64:in `all' 	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/lib/kpm/application.rb:18:in `HEAD /plugins/killbill-kpm/plugins' 	org/jruby/RubyMethod.java:116:in `call' 	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:1293:in `compile!' 	org/jruby/RubyProc.java:281:in `call' 	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:860:in `route!' 	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:876:in `route_eval' 	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:860:in `route!' 	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:897:in `process_route' 	org/jruby/RubyKernel.java:1242:in `catch' 	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems/sinatra-1.3.6/lib/sinatra/base.rb:895:in `process_route' 	/var/lib/killbill/bundles/plugins/ruby/killbill-kpm/1.3.0/ROOT/gems/gems
--

Can anybody help

**Comment by bronzdoc** [comment]
Please provide steps to reproduce and the output of `gem env` to reopen this issue, thanks!

**Comment by Anirudh8841** [comment]
I am facing the same issue after deploying killbill i couldn't stripe plugin. it worked fine when i have killbill it locally. Can someone help me out of this?
