### ISSUE TITLE
resolving symlinks in GEM_HOME and GEM_PATH breaks normal workflows

### ISSUE THREAD

**Issue by kvechera** [rubygems/rubygems#2788]
Resolving symlinks for GEM_HOME and GEM_PATH breaks old behavior, when these pathes we intact. For example, the __FILE__ value are now contains a resolved path instead of original, or the shebang of binaries is written with a resolved path instead of original path.

The new behavior breaks portability, when a file hierarchy is moved to another location, and breaks normal workflow of some package management tools, relying on symbolic links.

The resolving of paths doesn't improve performance or brings any other significant benefits and I'd like to suggest roll back the commit eregon@87e7092b0d0c58e582bb8d707f9f46b9655f690c.

**Comment by bronzdoc** [comment]
Hey @kvecher.  Can you provide an example to reproduce your problem? thanks.

**Comment by bronzdoc** [comment]
Closing due to lack of response
