### ISSUE TITLE
AWS SigV2 deprecation in s3 source

### ISSUE THREAD

**Issue by apakulov-stripe** [rubygems/rubygems#2793]
Would like to suggest a feature.

[S3 source](https://guides.rubygems.org/using-s3-source) has been added a part of Rubygems 3.0.

AWS announced that they are planning to deprecated SigV2 soon  https://aws.amazon.com/blogs/aws/amazon-s3-update-sigv2-deprecation-period-extended-modified/ and current S3-Source functionality relies on SigV2 implementation and does it [without](https://github.com/rubygems/rubygems/blob/15706d3e853f9d1fd7b6ddbdcf38cf9a83a345b9/lib/rubygems/remote_fetcher.rb#L348:L361) `aws-sdk` dependency.

Also, current implementation does not support temporary credentials: https://docs.aws.amazon.com/IAM/latest/UserGuide/id_credentials_temp_request.html

This issue is related to:
  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

**Comment by apakulov-stripe** [comment]
It's possible to minimize the dependency list to these two gems:
- https://rubygems.org/gems/aws-sigv4/versions/1.1.0
- https://rubygems.org/gems/aws-sdk-core/versions/3.56.0

**Comment by bronzdoc** [comment]
closed by https://github.com/rubygems/rubygems/pull/2807
