### ISSUE TITLE
Ability to disable all Bundler version checks

### ISSUE THREAD

**Issue by schneems** [rubygems/rubygems#2800]
Can we add an escape valve into Rubygems 2.7 and 3.0 that prevents it from firing the version check, or at least tells it to emit a warning instead of an error?

Maybe an environment variable like `RUBYGEMS_BUNDLER_VERSION_CHECK=warn` ? 

This type of feature would be very useful to work around bugs that we've not yet found, similar to how a bug was not found until bundler 2.0.3 was released. https://github.com/bundler/bundler/issues/7205

**Comment by hsbt** [comment]
I think this feature didn't resolve your scenario. I can add this to RG 2.7.11 and RG 3.0.5 easily. But the many of Ruby users may not upgrade its version. So, If they upgraded the latest version each releases, They do not encounter this situation.

**Comment by hsbt** [comment]
Related with https://github.com/rubygems/rubygems/pull/3073
