### ISSUE TITLE
.gemrc not working on Windows

### ISSUE THREAD

**Issue by thisismydesign** [rubygems/rubygems#2805]
I'm having a problem.

In powershell:
```
echo "gem: --no-document --platform=ruby" > $HOME\.gemrc
gem install
> Failed to load C:/Users/user/.gemrc, (<unknown>): control characters are not allowed at line 1 column 1
```

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.3
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by MSP-Greg** [comment]
@thisismydesign

I'd suggest UTF-8, rather than piping UCS-2 to a file...

**Comment by thisismydesign** [comment]
@MSP-Greg 

Thanks, this works

`"gem: --no-document --platform=ruby" | Set-Content -Encoding utf8 $HOME\.gemrc`

But it'd be great if it worked out of the box.
