### ISSUE TITLE
Gem Install for logstash-codec-sflow failed

### ISSUE THREAD

**Issue by davidshirk80** [rubygems/rubygems#2809]
I'm having a problem or would like to suggest a feature.

=========================================================================================

My current problem is when I try install sflow codec for logstash, I get the following error:
xxx@xxx:~# sudo /usr/share/logstash/bin/logstash-plugin install logstash-codec-sflow
Validating logstash-codec-sflow
Unable to download data from https://rubygems.org - Connection reset by peer (https://api.rubygems.org/latest_specs.4.8.gz)
ERROR: Installation aborted, verification failed for logstash-codec-sflow

This issue is related to:
  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:
xxx@xxx:~# gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.7.6
  - RUBY VERSION: 2.5.1 (2018-03-29 patchlevel 57) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/xxx/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0
  - USER INSTALLATION DIRECTORY: /home/xxx/.gem/ruby/2.5.0
  - RUBY EXECUTABLE: /home/xxx/.rbenv/versions/2.5.1/bin/ruby
  - EXECUTABLE DIRECTORY: /home/xxx/.rbenv/versions/2.5.1/bin
  - SPEC CACHE DIRECTORY: /home/xxx/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/xxx/.rbenv/versions/2.5.1/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/xxx/.rbenv/versions/2.5.1/lib/ruby/gems/2.5.0
     - /home/xxx/.gem/ruby/2.5.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/xxx/.rbenv/versions/2.5.1/bin
     - /home/xxx/.rbenv/libexec
     - /home/xxx/.rbenv/plugins/ruby-build/bin
     - /home/xxx/.rbenv/shims
     - /home/xxx/.rbenv/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /snap/bin

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by davidshirk80** [comment]
Also - this should help - library does not contain the file:
xxx@xxx:~# DEBUG=1 /usr/share/logstash/bin/logstash-plugin install logstash-codec-sflow
Using GEM_HOME=/usr/share/logstash/vendor/bundle/jruby/2.5.0
Using GEM_PATH=/usr/share/logstash/vendor/bundle/jruby/2.5.0
DEBUG: exec /usr/share/logstash/vendor/jruby/bin/jruby /usr/share/logstash/lib/pluginmanager/main.rb install logstash-codec-sflow
Looking if package named: logstash-codec-sflow exists at https://artifacts.elastic.co/downloads/logstash-plugins/logstash-codec-sflow/logstash-codec-sflow-7.1.1.zip
Package not found at: https://artifacts.elastic.co/downloads/logstash-plugins/logstash-codec-sflow/logstash-codec-sflow-7.1.1.zip
Validating logstash-codec-sflow
Unable to download data from https://rubygems.org - Connection reset by peer (https://api.rubygems.org/latest_specs.4.8.gz)
ERROR: Installation aborted, verification failed for logstash-codec-sflow

**Comment by davidshirk80** [comment]
Is there anything I can do to help this?
I tried manually downloading the codec onto my machine, but that is pointless as the verification is forced to source reference the weblink and not local. 
If I knew what instruction set mad that call, I could change it to local - but I am having difficulty finding that!

**Comment by MSP-Greg** [comment]
@davidshirk80

Don't use either logstash or Linux, but your 1st post shows standard MRI/C Ruby.  The 2nd post has references to 'jruby' folders?

**Comment by davidshirk80** [comment]
yeah - thank you for pointing that out (jruby) - tunnel vision!

**Comment by davidshirk80** [comment]
Closing.....Cisco SFR redirect had been tripped.....that was a total pita to find.......
