### ISSUE TITLE
Install curb

### ISSUE THREAD

**Issue by robinson4k** [rubygems/rubygems#2810]
I'm having a problem.

My current problem is when I install the curb

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

Here are my current environment details:

# gem install curb
ERROR:  While executing gem ... (OpenSSL::SSL::SSLError)
    tlsv1 alert protocol version

Please, can anyone help me?

**Comment by bronzdoc** [comment]
@robinson4k please provide the full stacktrace, also you might find this guide helpful https://guides.rubygems.org/ssl-certificate-update/

**Comment by bronzdoc** [comment]
Closing due to lack of response
