### ISSUE TITLE
load error when use cocoapods

### ISSUE THREAD

**Issue by JackZhangDF** [rubygems/rubygems#2814]
I'm having a problem or would like to suggest a feature.

My current problem is _when use cocopods________

here is detail:
```
Traceback (most recent call last):
	7: from /usr/local/bin/pod:23:in `<main>'
	6: from /usr/local/bin/pod:23:in `load'
	5: from /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.2/bin/pod:36:in `<top (required)>'
	4: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	3: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	2: from /usr/local/lib/ruby/gems/2.5.0/gems/cocoapods-1.7.2/lib/cocoapods.rb:7:in `<top (required)>'
	1: from /usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/usr/local/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- active_support/core_ext/string/strip (LoadError)
```
This issue is related to:
  - [x] Other

Here are my current environment details:

```
environment version:
(base) bogon:FFRouter-master mengmengzhang$ ruby -v
ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-darwin17]
(base) bogon:FFRouter-master mengmengzhang$ gem -v
3.0.4


```

thanks.

**Comment by bronzdoc** [comment]
What are the steps to reproduce @JackZhangDF ?

**Comment by JackZhangDF** [comment]
> What are the steps to reproduce @JackZhangDF ?

hello @bronzdoc

thanks for your relpy.

1.it happend when i use cocopods.
2.it didn't work even if I reinstall the gem and cocopods.

here's my preliminary solution：
My solution is to manually add all the dependencies for the cocoapods。
My analysis was that a configuration file was corrupted。maybe i should reinstall Ruby . I'll try to resolve it .

**Comment by bronzdoc** [comment]
Ok, will close this for now, if you don't resolve it please ping us with the command you are using that triggers the problem
