### ISSUE TITLE
can I avoid unavoidable SSL errors?

### ISSUE THREAD

**Issue by jonhp** [rubygems/rubygems#2817]
below are the SSL errors received. The Sonicwall DPI-SSL support requires a self-signed certificate. This works fine with Windows and all browsers. However, gem is not so tolerant. Need some way to tell gem that this is OK and not a problem. BTW I am not a security/SSL expert so guidance is required. Thanks, Jon
gem version 2.7.6.2 on Windows 10
=============================================================
C:\Users\jon>gem install rack
ERROR:  SSL verification error at depth 1: self signed certificate in certificate chain (19)
ERROR:  Root certificate is not trusted (/C=US/ST=CA/O=SonicWALL Inc./CN=SonicWALL Firewall DPI-SSL)
ERROR:  SSL verification error at depth 1: self signed certificate in certificate chain (19)
ERROR:  Root certificate is not trusted (/C=US/ST=CA/O=SonicWALL Inc./CN=SonicWALL Firewall DPI-SSL)
ERROR:  SSL verification error at depth 1: self signed certificate in certificate chain (19)
ERROR:  Root certificate is not trusted (/C=US/ST=CA/O=SonicWALL Inc./CN=SonicWALL Firewall DPI-SSL)
ERROR:  Could not find a valid gem 'rack' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate in certificate chain) (https://api.rubygems.org/specs.4.8.gz)
ERROR:  SSL verification error at depth 1: self signed certificate in certificate chain (19)
ERROR:  Root certificate is not trusted (/C=US/ST=CA/O=SonicWALL Inc./CN=SonicWALL Firewall DPI-SSL)
ERROR:  SSL verification error at depth 1: self signed certificate in certificate chain (19)
ERROR:  Root certificate is not trusted (/C=US/ST=CA/O=SonicWALL Inc./CN=SonicWALL Firewall DPI-SSL)
.

**Comment by bronzdoc** [comment]
Try to set your sources to:

```
:sources:
  http://rubygems.org/
```
