### ISSUE TITLE
rubygem can't "require 'openssl'" with "$SAFE = 1"

### ISSUE THREAD

**Issue by Tarpaulin** [rubygems/rubygems#2824]
$SAFE = 1 can not be used to load some (default?) Gems, in particular openssl.

The following script:
```
$SAFE = 1
require 'openssl'
```
Aborts with 
```
/usr/lib/ruby/site_ruby/2.5.0/rubygems/util.rb:125:in `expand_path': Insecure operation - expand_path (SecurityError)
```

I found this happening after updating to 3.0.4, it was previously working in version 2.7.8.

I have experienced this problem on Ruby 2.5.3 and 2.6.3.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

```
$ gem env version
3.0.4
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by duckinator** [comment]
Looks like that's the `RUBY_VERSION >= "2.5" branch of `Gem::Util.glob_files_in_dir`.

As of v3.0.4 that was [on line 125](https://github.com/rubygems/rubygems/blob/v3.0.4/lib/rubygems/util.rb#L125), but now it's [on line 89](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/util.rb#L89).

I've confirmed that this happens with RubyGems 3.0.3 and Ruby 2.5+, but not RubyGems 3.0.3 and Ruby <=2.4.

![Screenshot_20190913_093056](https://user-images.githubusercontent.com/39698/64866444-735c7680-d609-11e9-8504-1852f7a6853a.png)

![Screenshot_20190913_093318](https://user-images.githubusercontent.com/39698/64866543-a0108e00-d609-11e9-9019-dbedb217ead1.png)

**Comment by duckinator** [comment]
The implications of that are that:

1. This breaks with `$SAFE=1`: `Dir.glob(glob, base: base_path).map! {|f| File.expand_path(f, base_path) }`
2. This works with `$SAFE=1`: `Dir.glob(File.expand_path(glob, base_path))`

**Comment by hsbt** [comment]
FYI: https://bugs.ruby-lang.org/issues/16131 The ruby language is going to remove `SAFE` feature in the near future. We should remove the related code of rubygems.

**Comment by hsbt** [comment]
I ignored some code related to the `$SAFE` mechanism at cee56a0f2c9b6aa8252153b63513ad910526f6ea

We sill not support this feature in the future.
