### ISSUE TITLE
Wrong test - test_self_stubs_for

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#2827]
I am afraid the `test_self_stubs_for` [[1]] does not test what it promises. I think these two lines are problematic:

~~~
full_names = ['a-3', 'a-2', 'a-1']

full_names = Gem::Specification.stubs_for('a').map { |s| s.full_name }
assert_equal full_names, Gem::Specification.stubs_for('a').map { |s| s.full_name }
~~~

You can see, that while the `full_names` is initialized first, later it is overwritten by the same content as it should test.

[1]: https://github.com/rubygems/rubygems/blame/master/test/rubygems/test_gem_specification.rb#L1147

**Comment by deivid-rodriguez** [comment]
Good catch. And I guess removing the second assignment makes the test fail?

**Comment by voxik** [comment]
Yes, it does.

Unfortunately, this is quite tricky. The issue is that the pattern matched by `stubs_for` is `pattern = "#{name}-*.gemspec"`, i.e. the `save_gemspec` should save the gemspec with version, but it does not do so :/

**Comment by voxik** [comment]
We could move the .gemspec around to appropriate names, but it would be much better if the `save_gemspec` stored also the version, IOW if it used `vendor_spec.gemspec_name`. But this breaks other stuff, mainly the resolver tests. May be this could be done optionally, because it is the right thing to do IMO.

**Comment by voxik** [comment]
Other option would be to change the `pattern`, but I think that every .gemspec used by RubyGems contains the `-{version}` so this is correct pattern IMO.
