### ISSUE TITLE
GEM_HOST_API_KEY not working

### ISSUE THREAD

**Issue by SkipKayhil** [rubygems/rubygems#2829]
I'm having a problem or would like to suggest a feature.

My current problem is GEM_HOST_API_KEY isn't working when pushing. It looks like the PR was merged back in January (and is in the master branch) but hasn't actually been released? The code is not present in any of the tagged releases.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [x] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.0.3
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
I just added a milestone to https://github.com/rubygems/rubygems/pull/2559 to be included in the next release, thanks @SkipKayhil
