### ISSUE TITLE
Support NTLM authentication when behind Windows proxies

### ISSUE THREAD

**Issue by emboss** [rubygems/rubygems#285]
Gem installation failed while I was playing around on a Windows machine that sat behind an NTLM-authenticated proxy. Could you please support NLTM auth for these cases?

Thanks in advance,

**Comment by copiousfreetime** [comment]
In #360 @ken-sands says:
> it works if you url encode the backslash between the domain and username, ie
>
> http://mydomain%5Cmyusername:password@proxy:port

This needs additional validation to see what works. @duckinator is this something you want to take a look at?

**Comment by duckinator** [comment]
@copiousfreetime I'm not sure I understand this well enough to be able to effectively do anything, tbh.

**Comment by bronzdoc** [comment]
I'm going to close this since has been ide for too long, but i'll reopen it if there's still interest in this feature...
