### ISSUE TITLE
Ruby gem SSL

### ISSUE THREAD

**Issue by imbargel** [rubygems/rubygems#2853]
I'm having a problem or would like to suggest a feature.

My current problem is _____I'm getting a SSL error when trying to install any gem but especially "redis gem" through Dockerfile. Though I can install it successfully when I'm doing it inside the container manually (using old image).  Tried various solutions found in the net like changing sources, manual gem installation, update CA certificates.

Container OS image is Ubuntu 16.04.5 LTS

Step 35/55 : RUN gem update --system

---> Running in 34c9317a6b89

[91mERROR: While executing gem ... (Gem::RemoteFetcher::FetchError)

SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

Here are my current environment details:

$ ruby -ropenssl -e 'puts OpenSSL::OPENSSL_LIBRARY_VERSION'

OpenSSL 1.0.2g 1 Mar 2016

```
$ gem env version

RubyGems Environment:

- RUBYGEMS VERSION: 2.5.2.1

- RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [x86_64-linux-gnu]

- INSTALLATION DIRECTORY: /var/lib/gems/2.3.0

- USER INSTALLATION DIRECTORY: /root/.gem/ruby/2.3.0

- RUBY EXECUTABLE: /usr/bin/ruby2.3

- EXECUTABLE DIRECTORY: /usr/local/bin

- SPEC CACHE DIRECTORY: /root/.gem/specs

- SYSTEM CONFIGURATION DIRECTORY: /etc

- RUBYGEMS PLATFORMS:

- ruby

- x86_64-linux

- GEM PATHS:

- /var/lib/gems/2.3.0

- /root/.gem/ruby/2.3.0

- /usr/lib/x86_64-linux-gnu/rubygems-integration/2.3.0

- /usr/share/rubygems-integration/2.3.0

- /usr/share/rubygems-integration/all

- GEM CONFIGURATION:

- :update_sources => true

- :verbose => true

- :backtrace => false

- :bulk_threshold => 1000

- REMOTE SOURCES:

- https://rubygems.org/

- SHELL PATH:

- /usr/local/sbin

- /usr/local/bin

- /usr/sbin

- /usr/bin

- /sbin

- /bin
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
@imbargel please check https://guides.rubygems.org/ssl-certificate-update/ and let us know if the issue persists
