### ISSUE TITLE
Let `gem build` without additional arguments build the only gemspec in a directory

### ISSUE THREAD

**Issue by ghost** [rubygems/rubygems#2859]
I'm having a problem or would like to suggest a feature.

My current problem is that it's an annoyance to always type out the full command (i.e. `gem build gemname.gemspec`), especially when working on multiple gems.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
`3.0.0.beta3`
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**I suggest to only allow this to work, when there is only one `gemspec` file in the current directory.**

**Comment by bronzdoc** [comment]
Maybe we can revisit https://github.com/rubygems/rubygems/pull/2610

**Comment by LemonAndroid** [comment]
pls no :D 

i mean yes, ofc, tho

**Comment by duckinator** [comment]
I'm very strongly in favor of this, explicitly with the condition of only having it work if there's exactly one gemspec in the current directory (as the original issue suggests).

@bronzdoc the approach taken in #2610 causes a pretty drastic increase in complexity, so I'd like to redirect back to the issue as it was opened here. It feels like a more streamlined and manageable subset of your idea, to me.

**Comment by bronzdoc** [comment]
@duckinator 
> explicitly with the condition of only having it work if there's exactly one gemspec in the current directory

Yeah, i'm working on something of that nature. 

Definitely https://github.com/rubygems/rubygems/pull/2610 brings more complexity
