### ISSUE TITLE
generate_index gets a SystemStackError when the gem set is large

### ISSUE THREAD

**Issue by evanphx** [rubygems/rubygems#286]
Originally reported here: http://help.rubygems.org/discussions/problems/810-create-rubygems-mirror-gem-generate_index-failed-in-stack-level-too-deep

**Comment by duckinator** [comment]
Has been resolved?

**Comment by copiousfreetime** [comment]
I believe this has been resolved. I just tested with snapshot of 21k gems and `generate_index`, although not the fasted thing in the world, did generate everything just fine.
