### ISSUE TITLE
429 for Publishing Gems, account backlisted?

### ISSUE THREAD

**Issue by cjyclaire** [rubygems/rubygems#2865]
Hello all, appreciate the help there in advance!

With AWS Ruby SDK v3 modularization, at high time, we are releasing almost 200 service gems on RubyGem almost everyday using rubygems Post API. Starting from last Friday, we are seeing 429 (too many request) and failing to publish gems and need to wait a long time (at least hours to see a bit less 429).

Is this a signal that @awscloud account has been blacklisted due to our release speed? Is there any suggestions for retry control or publishing pace recommend from yourside? If our account is blacklisted, anyone can help move it out from blacklist?

Let me know if more info. is needed.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [√] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
Duplicated with https://github.com/rubygems/rubygems.org/issues/2081

This repository was upstream of rubygems client.
