### ISSUE TITLE
NPX like command for gem with gem exec

### ISSUE THREAD

**Issue by emilebosch** [rubygems/rubygems#2872]
Sup folks 👋 I would like to have a npx like command to install a gem and immediately execute its exe  just like npx.

Install rails and generate a new blog

```
$ gem exec rails new blog 
$ gem x rails new blog
```
My current problem is that I am repeating myself too much, and I want to be able to start a project immediately therefore I want to have a `npx` https://github.com/npm/npx functionality in gems.

If anyone is interested in this I will make a PR and we can all 💃 and 🎉 

This issue is related to:

 - [x] Installing a library
 - [x] The command line `gem`
 - [x] Making stuff easier for everyone

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Hi @emilebosch Thanks for the proposal.
How would `gem x rails new blog` would be better that `gem i rails && rails new blog`  ?

**Comment by emilebosch** [comment]
It aint better :) its just a shorthand and more dry. Just like npx and it does allow for more convention between the cli and the gem, which is probably a good thing too. 

A gem exec —latest could also ensure you’re running the last version.

Its just a shorthand to make the workflow easier for things like jekyll, middleman, rails.

**Comment by emilebosch** [comment]
Also this is maybe good as a reference/inplementation and ideas https://github.com/junosuarez/awesome-npx

**Comment by bronzdoc** [comment]
I see, I think this would be a better fit as a plugin.

see: https://guides.rubygems.org/plugins/

**Comment by emilebosch** [comment]
Agreed

**Comment by DirtyF** [comment]
`npx` command solves a real problem when you have to make sure your scripts will run not matter what your local setup, is there such a bundler plugin as of today?

**Comment by simi** [comment]
@DirtyF can you explain a little more? Is there any edge-case where for example `gem i rails && rails new blog` (as metnioned at https://github.com/rubygems/rubygems/issues/2872#issuecomment-520408807) is not enough?

**Comment by DirtyF** [comment]
Let's say you run scripts through rake tasks or whatever on different environments (development, staging, production) and those environments slightly differ, maybe you can't install global packages on your staging. You would expect to be able to use the same commands no matter what (`bundle exec jekyll build` for instance). You don't want to manually manage the installation part, you would expect your dependency manager to be able to pick it up from global if it exists or install it locally if it's not available to run your command.

that would mean:
- checks if there is an aliased command in the current project
- if not; it recurses up until it finds one;
- if it can't; it checks globally installed gems;
- if it can't; it downloads it from Rubygems and runs it

See npx README to get a better understand of the problem it solves:
https://github.com/npm/npx#npx1----execute-npm-package-binaries

**Comment by emilebosch** [comment]
Gems exists is that smth you're looking for?

**Comment by emilebosch** [comment]
@DirtyF What is the actual problem you;'re facing at the moment?

**Comment by jjb** [comment]
looks like this happened! https://github.com/rubygems/rubygems/pull/6309

**Comment by Mark24Code** [comment]
It's really helpful!
