### ISSUE TITLE
Windows generated .bat commands broken for JRuby on RubyGems 3 / Bundler 2

### ISSUE THREAD

**Issue by karlhe** [rubygems/rubygems#2873]
I'm having a problem or would like to suggest a feature.

My current problem is the bundle command does not work as expected with JRuby on Windows.

Filed an issue against JRuby a while back (https://github.com/jruby/jruby/issues/5632), but I don't think it's a problem on the JRuby side.

```
C:\jruby-9.2.8.0\bin>bundle
'"C:\jruby-9.2.8.0\bin\ruby.exe"' is not recognized as an internal or external command,
operable program or batch file.
```

It simply appears as if the .bat files are not generated correctly. The contents of bundler.bat/bundle.bat are:

```
@ECHO OFF
@"%~dp0ruby.exe" "%~dpn0" %*
```

For comparison, it looks like this in my JRuby 9.2 folder (which is using older Rubygems/Bundler):

```
@ECHO OFF
IF NOT "%~f0" == "~f0" GOTO :WinNT
@"C:\jruby-9.2.0.0\bin\jruby.exe" "C:/jruby-9.2.0.0/bin/bundle" %1 %2 %3 %4 %5 %6 %7 %8 %9
GOTO :EOF
:WinNT
@"C:\jruby-9.2.0.0\bin\jruby.exe" "%~dpn0" %*
```

On the surface `jbundle` seems to work but then rails.bat, rake.bat, etc are still defined like this:

```
@ECHO OFF
@"%~dp0ruby.exe" "%~dpn0" %*
```

So any command other than `jbundle install` will end up failing anyway.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

Here are my current environment details:

```
$ gem env version
3.0.4
```
Bundler: 2.0.4 
JRuby 9.2.8.0 
Windows Server 2016 Standard

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
This seems caused by https://github.com/rubygems/rubygems/pull/2119.

@MSP-Greg Could you have a look at it?

**Comment by MSP-Greg** [comment]
@deivid-rodriguez

See PR #2876.  Uses the same logic as `Gem.ruby` for the exe file name.

**Comment by deivid-rodriguez** [comment]
Thanks @MSP-Greg!

@karlhe I think you can double check that @MSP-Greg's fix works by manually applying his patch to your rubygems installation (it's very simple), and then reinstalling `bundler` (`gem install bundler`). 

You can revert to your previous rubygems if you want after you confirm the fix with `gem update --system 3.0.4` (or whatever).

**Comment by karlhe** [comment]
Replaced the file at `lib\ruby\stdlib\rubygems\installer.rb`

`bundle.bat` and `rake.bat` both look correct, and seem to work as expected.

Thanks!

**Comment by hsbt** [comment]
@karlhe I released 3.0.6 with #2876 . Can you confirm to resolve this issue?

**Comment by karlhe** [comment]
It still seems to be the same behavior, I don't think the PR actually made it into 3.0.6?

https://github.com/rubygems/rubygems/blob/9c142f5d9d7576012a440dceb8335c3139fcc16f/lib/rubygems/installer.rb#L802

Still looks like the old one

**Comment by hsbt** [comment]
Ah, Sorry. I missed this at 3.0.5 and 3.0.6, I will release with 3.0.7.

**Comment by hsbt** [comment]
Relased https://blog.rubygems.org/2020/02/18/3.0.7-released.html
