### ISSUE TITLE
3.0.5 breaks command line gem on JRuby

### ISSUE THREAD

**Issue by gvassallo** [rubygems/rubygems#2879]
My current problem is that the latest `3.0.5` version seems to have broken the command line `gem` on JRuby, since the file `rubygems/compatibility`, which is required by JRuby, has been removed.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
/Users/gav/.rbenv/versions/jruby-9.2.7.0/lib/ruby/stdlib/rubygems.rb:12: warning: already initialized constant VERSION
LoadError: no such file to load -- rubygems/compatibility
  require at org/jruby/RubyKernel.java:987
   <main> at /Users/gav/.rbenv/versions/jruby-9.2.7.0/lib/ruby/stdlib/rubygems.rb:16
  require at org/jruby/RubyKernel.java:987
   <main> at /Users/gav/.rbenv/versions/jruby-9.2.7.0/bin/jgem:1
     load at org/jruby/RubyKernel.java:1022
   <main> at /Users/gav/.rbenv/versions/jruby-9.2.7.0/bin/jgem:8
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
Right. I missed picking https://github.com/rubygems/rubygems/pull/2848

**Comment by hsbt** [comment]
@gvassallo Can you try with 3.0.6? https://blog.rubygems.org/2019/08/16/3.0.6-released.html

I revert removing the change of `rubygems/compatibility.rb`

**Comment by gvassallo** [comment]
@hsbt yes, it seems working with `3.0.6`. Thanks!

**Comment by hsbt** [comment]
Thanks too! I'm happy to find this regression quickly.

**Comment by film42** [comment]
We didn't have `update_rubygems` installed, so we're looking for a quick solution to repair our servers. I think reinstalling jruby is the easiest solution right now.
