### ISSUE TITLE
Default gems location as framework on macOS

### ISSUE THREAD

**Issue by nobu** [rubygems/rubygems#2890]
In the case of installation as system bundled framework on macOS (when `RUBY_FRAMEWORK_VERSION` is defined), `Gem.default_dir` returns a  path derived from `RbConfig::CONFIG['sitedir']`.
Regarding the bundled framework on macOS Mojave, default gems are placed there but other vendor bundled gems are placed in `/usr/lib/ruby/gems/2.3.0/gems` (= `/System/Library/Frameworks/Ruby.framework/Versions/Current/usr/lib/ruby/`).

I think that also the former gems including defaults should be placed in the latter location.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

```
$ gem env version
PASTE HERE
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by nobu** [comment]
The branch by `RUBY_FRAMEWORK_VERSION` seems introduced  at rubygems/rubygems@f51b3d53fcacaf652a2d49c39075fcbf27e5d607.

**Comment by bronzdoc** [comment]
Can you provide steps to reproduce? thanks.

**Comment by nobu** [comment]
This is an output on macOS Catalina.
```
$ /usr/bin/ruby -v -e 'puts Gem.default_dir, RbConfig::CONFIG["sitedir"]'
ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
/Library/Ruby/Gems/2.6.0
/Library/Ruby/Site
```
```
$ /usr/bin/ruby -rnokogiri -e 'puts $".grep(/(nokogiri|did_you_mean)\.rb$/)'
/Library/Ruby/Gems/2.6.0/gems/did_you_mean-1.3.0/lib/did_you_mean.rb
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0/gems/nokogiri-1.10.1/lib/nokogiri.rb
```

`did_you_mean` is a default gem and `nokogiri` is a vendor bundled gem.

**Comment by deivid-rodriguez** [comment]
@nobu If I understand correctly, what you are suggesting is to completely remove `RUBY_FRAMEWORK_VERSION` specific code, correct? If that's the case, :+1: from me.

**Comment by nobu** [comment]
I guess that is correct, I can't remember it precisely now though.
