### ISSUE TITLE
Require 2FA for publishing gems

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [rubygems/rubygems#2891]
I'm would like to suggest a feature.

My current problem is a not security oriented gem publishing process.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

After seeing the recent hacked and published gems on rubygems.org, I highly recommend to make 2FA mandatory before publishing to rubygems.org. 

Any thoughts about this?

See the news: 

* https://github.com/rubygems/rubygems.org/wiki/Gems-yanked-and-accounts-locked
* https://github.com/rest-client/rest-client/issues/713
* https://www.theregister.co.uk/2019/08/20/ruby_gem_hacked/
* https://news.ycombinator.com/item?id=19569959

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
We already provide the 2FA for publishing gem.

https://guides.rubygems.org/setting-up-multifactor-authentication/

**Comment by h0jeZvgoxFepBQ2C** [comment]
Yeah I know, but this was also not my question :)

My suggestion was to make it *mandatory* from rubygems.org before publishing, to make it harder that these problems occur.

**Comment by hsbt** [comment]
see https://github.com/rubygems/rubygems.org/issues/2101#issuecomment-523237721

There is no plan to enforce 2FA for everyone yet.
