### ISSUE TITLE
uninstall a gem then crash on default (Gem::InstallError)

### ISSUE THREAD

**Issue by benoittgt** [rubygems/rubygems#2892]
Hello 😊

My current problem is that when I try to remove a gem, it say that the gem is uninstalled but then crash.

On RSpec we have to do some weird things to properly handle multiple Ruby and Rails version on Travis. https://github.com/rspec/rspec-rails/pull/2158/files#diff-b262826f376893c7c9a30ff4b124d72aR12

We do `gem uninstall -aIx bundler` but we get two information that seems to be the opposite (?)

```
Removing bundler
Successfully uninstalled bundler-2.0.2
ERROR:  While executing gem ... (Gem::InstallError)
    gem "bundler" cannot be uninstalled because it is a default gem
```

* Does it means the second error is for another bundler gem version?
* How could we avoid that crash on default gems?

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
ruby --version
ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-linux]

$ rvm --version
rvm 1.29.3 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]

$ bundle --version
Bundler version 1.16.2

$ gem --version
2.7.7
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
The error message should be better but I think the -a flag means "uninstall all versions" of the gem, so it's successfully uninstalling the non default one, and failing to uninstall the default one. Makes sense?

**Comment by benoittgt** [comment]
Completely. Thanks @deivid-rodriguez 

I am now trying to look at a way to delete all non-default versions. 

You can feel free to close the issue. :)

**Comment by deivid-rodriguez** [comment]
I consider this a rubygems issue, actually. The -a flag should ignore default gems by default.

If you specify a concrete name and version (like "gem uninstall bundler:1.17.2"), then it's fine to display an error, but in other cases I think it's preferable to ignore default gems without any errors?

As a workaround for now, you could add "|| true" at the end of the command.

**Comment by deivid-rodriguez** [comment]
@benoittgt I took a crack at fixing this at #2893.

**Comment by bronzdoc** [comment]
@benoittgt i noticed you are using an old version of Rubygems, could you try upgradig to `3.0.6` 
?

With the latest rubygems version:
```
$ gem --version
3.0.6

$ gem list | grep bundler
bundler (2.0.2, 2.0.1, default: 1.17.3)

$ gem uninstall --all --force bundler
Successfully uninstalled bundler-2.0.1
Successfully uninstalled bundler-2.0.2

$ gem list | grep bundler
bundler (default: 1.17.3)
```

**Comment by deivid-rodriguez** [comment]
@bronzdoc Try running the same command again, and you'll see the error. Currently if there are other versions of bundler other than the default, it removes those, whereas if there's only the default version, it crashes with that error. I prefer the behavior in my PR: consistenly and transparently ignore default versions, and uninstall the rest.

**Comment by benoittgt** [comment]
In our script we use the last version of gem. See : https://travis-ci.org/rspec/rspec-rails/jobs/575514817

```
$ script/update_rubygems_and_install_bundler
Updating rubygems-update
Fetching: rubygems-update-3.0.6.gem (100%)
Successfully installed rubygems-update-3.0.6
Installing RubyGems 3.0.6
```
