### ISSUE TITLE
Maybe a security issue in rubygems+bundler combination.

### ISSUE THREAD

**Issue by rg-3** [rubygems/rubygems#2895]
I'm not sure if this issue should be opened on Rubygems or Bundler, as it involves both.

When bundler installs gems by default it installs them as system gems, like they had been installed with `gem install`. If one of these gems overwrites a bin script of an already installed gem, no warning and confirmation prompt is shown (i am using bundler 1.15.2), like would happen when using `gem install`.

The absence of a warning and nothing to confirm the overwrite of a bin script is worrying because if a user were to unknowingly add a malicious gem to their gemfile, that overwrote bin scripts for popular gems or gems an attacker knows the user is using, then the user could easily be snooped on or run code that compromises their system, but since the user would likely have no clue their bin scripts have been replaced it also gives an attacker a good opportunity to remain hidden for a long time.

Does anyone else see a problem with how things currently work? When i am stopped and asked to confirm the overwrite, then fine, i will know if `rails` or `rake` is replaced, but with no warning, i never know a thing......

**Comment by hsbt** [comment]
In general, rubygems and bundler create the gem wrapper for any gems. Because It only happens the old default gems like rdoc and bundler.

**Comment by hsbt** [comment]
Ah, I found the case for this. If the malicious gem has `exe/bundle`, bundler and rubygems will overwrite it silently by gem wrapper.

**Comment by rg-3** [comment]
I think the problem is bundler because rubygems asks for confirmation before replacing a bin script but bundler does not.  i believe bundler should, especially when replacing system gem bin scripts !

**Comment by rg-3** [comment]
Check out the gem `riif`, it bundles `rake` ... https://github.com/linjunpop/riif/blob/master/bin/rake

When i add `riif` to my gemfile, and run bundle install, my original version of `rake` is replaced and `riif` rake gets run when invoking `rake`, i would have had no idea if the rake bin script didn't cause exceptions when run outside a bundler project.

**Comment by hsbt** [comment]
I got your concern. But I have also no idea.

**Comment by rg-3** [comment]
I think bundler should do the same as Rubygems: ask for confirmation before overwriting a system bin script. If I say no, then let the gem be installed without overwriting the bin script.

**Comment by bronzdoc** [comment]
> I think bundler should do the same as Rubygems: ask for confirmation before overwriting a system bin script. If I say no, then let the gem be installed without overwriting the bin script.

@rg-3 could you open this issue in bundler? thanks!
