### ISSUE TITLE
Error: Too Long Filename

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems#2898]
I just tried to push my gem but it fails:

[...]classes/move_all_files_from_this_directory_into_the_current_work_directory_unless_that_file_already_exists.rb has a too long name (should be 100 or less)

This is a very long name indeed. You can of course reason that you dislike this; that is fine. But do you have to like long file names? Do I have to like short file names in return?

My question is:

- Who decided that this is not allowed? I would like to read the reasoning behind the person who wrote the code that limits how long a filename should be. On my linux system I can easily create such a file name. Ruby itself also works fine, so I wonder why gem goes forward and restricts us in this way.

IMO this is something I would like to see removed. IF you really want to keep that arbitrary limit decided by some random dude, I'd like to see that length be extended to, say 200 or so. It really should not be up to gem itself to impose any arbitrary limit though; but even if you want to keep it, just increase that size.

This now means that I can not upload my gem.

Note that I follow a:

filename.rb
FileName

convention, so gem would force me to rename it. I can not do so because I would arbitrarily change the way how I operate based on random decisions made by random people, which I don't like on my own systems. That means that my gem can not be updated past that point, unless I would conform to this limitation (which I can not do) or if it is removed. Thus I hope others will agree that this limitation makes no sense.

It is an internal file anyway in a library, so I understand this arbitrary limitation even less. Or will gem crash if the filename is too long? 200 characters means the end of the world? Why not 220? 235? Who decides on this, anyway?

**Comment by duckinator** [comment]
@rubyFeedback the tar format only allows 100-character names, and gems use the tar format, so we inherit the limitations as well.

RubyGems didn't chose the number on a whim; it was a compromise required to use tar files. There are definitely arguments in favor of other formats, but it'd take significant effort to switch to one of those. And I'm not sure that it's worth the trade-offs.

So, as for "who decides on this":

1. AT&T Bell Laboratories around 40 years ago, and also
2. whoever decided RubyGems should use tar files at some point in the last ~13 years.

**Comment by bronzdoc** [comment]
Thanks @djberg96 @duckinator
