### ISSUE TITLE
Respect $GEM_HOME when storing credentials

### ISSUE THREAD

**Issue by annacrombie** [rubygems/rubygems#2903]
I'm having a problem or would like to suggest a feature.

My current problem is ~/.gem/credentials is hardcoded in to rubygems.  All other paths I have encountered can be configured via `GEM_HOME`, `GEM_PATH`, and `GEM_SPEC_PATH`.  I have set these variables but when I try to push a new ~/.gem/credentials file appears!

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.0.3
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
It's the expected behavior with the current implementation. I will change it with https://github.com/ruby/ruby/pull/2174
