### ISSUE TITLE
Uninstaller's use of File.realpath causing problems in symlinked dirs

### ISSUE THREAD

**Issue by zenspider** [rubygems/rubygems#2910]
#2720 by @deivid-rodriguez has broken some of our tests on OSX.

We have some tests that are trying to do an uninstall. With the PR above, `@gem_dir` has had `File.realpath` expansion on its original value... but the code in `path_ok?` doesn't do a corresponding `File.realpath` on the value from `spec.full_gem_path` so the paths can diverge (because on OSX, `File.realpath("/var") == "/private/var"`).

The values being compared in `path_ok?` are:

```ruby
"/private/var/folders/b4/mw_b83w5653glr4vvbnym26r0000gp/T/d20190911-60772-m2iu4i/gems/2.6.0/gems/inspec-test-fixture-0.1.0"
#vs
"/var/folders/b4/mw_b83w5653glr4vvbnym26r0000gp/T/d20190911-60772-m2iu4i/gems/2.6.0/gems/inspec-test-fixture-0.1.0"
```

I think any use of `realpath` should be evenly distributed if testing against one of those `realpath` values.

Here are my current environment details:

```
$ gem env version
3.0.6
```

**Comment by deivid-rodriguez** [comment]
Thanks for reporting this @zenspider. It sounds reasonable.

Are you able to send us a fix?

**Comment by duckinator** [comment]
If I'm understanding correctly, then the fix would be changing [line 284 of lib/rubygems/uninstaller.rb](https://github.com/rubygems/rubygems/blob/b44845a/lib/rubygems/uninstaller.rb#L284) to:

```ruby
File.realpath(full_path) == spec.full_gem_path || File.realpath(original_path) == spec.full_gem_path
```

(Or an equivalent change that may span more lines.)

@zenspider is that^ correct?

**Comment by deivid-rodriguez** [comment]
Even if we got no further feedback, it sounds like this issue is still present, and that @duckinator's suggestion would be the way to go. So I'll set this as ready.

**Comment by deivid-rodriguez** [comment]
This issue doesn't provide an easy repro (we only know that some tests started to fail on some repository, but it sounds too much work to try to repro only from that information). Also the fix suggested by @duckinator seems to break a bunch of other specs, and the only person that has run into this issue hasn't show any further interest.

So I'm going to close this based off that, but if you're still running into this and can provide a repro, please go ahead @zenspider and reopen. Thanks!
