### ISSUE TITLE
Gem owners who hide their email address are not removable

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems#2916]
I added [matiaskorhonen](https://rubygems.org/profiles/matiaskorhonen) to my gem [unpwn](https://rubygems.org/gems/unpwn). If you visit their profile, you will notice that their email address is hidden.

Now, when I try to list owners using `gem owner`, they are shown as a blank entry:

```
$ gem owner unpwn
Owners for gem: unpwn
- 
- andre@arko.net
```

This makes it impossible to know who the owner is, and also makes it impossible to remove said owner.

:(

**Comment by lmansur** [comment]
That's odd. When I run `gem owner unpwn`, I get this:

```
Owners for gem: unpwn
- matiaskorhonen
- andre@arko.net
```

What happens if you run `gem owner unpwn -r matiaskorhonen`?

**Comment by bronzdoc** [comment]
@indirect what rubygems version you using? i can't reproduce it either, I am seeing the same results as @lmansur

**Comment by indirect** [comment]
Now when I run `gem owner unpwn` I get the same thing. 😲 Ok, who knows what happened 😬 Thanks for checking on it!
