### ISSUE TITLE
Retire bundlerbot

### ISSUE THREAD

**Issue by hsbt** [rubygems/rubygems#2920]
@indirect @deivid-rodriguez @bronzdoc 

I did migrate GitHub Actions from Travis CI and AppVeyor(https://github.com/rubygems/rubygems/pull/2915). After that, bundlerbot is not working because it depends on Travis CI status(https://github.com/rubygems/rubygems/pull/2917#issuecomment-532684846).

It's time to retire bundlerbot on rubygems/rubygems. How do you think about this?

**Comment by indirect** [comment]
Bundlerbot works with any GitHub status, we just need to tell it that status name: https://bors.tech/documentation/getting-started/

Maybe we should change the name? 😅

**Comment by hsbt** [comment]
Yes, I already got it. But I'm not sure the status name of GitHub Actions. Do you know how digging a status name of GitHub Checks?

**Comment by hsbt** [comment]
https://github.com/rubygems/rubygems/pull/2917/commits/533089694bba5c93d44299064541504943a2913b was failed with bors

**Comment by hsbt** [comment]
ok, I'm going to get the status names via https://developer.github.com/v3/repos/statuses/#list-statuses-for-a-specific-ref

**Comment by hsbt** [comment]
Surprisingly, GitHub Actions have no status of GitHub API.

**Comment by bronzdoc** [comment]
I guess if Github actions doesn't have a status api and we already removed travis ci we would have to remove it. I really liked the bors workflow but if it's blocking us in any way maybe we should disable it for now.

**Comment by deivid-rodriguez** [comment]
I share @bronzdoc's sentiment.

I really like bundlerbot and I feel it's very useful, but if it can't currently work with Gihub actions, I guess we should stop using it for now?

I think github actions will bring us a lot of value, I haven't looked into it in depth but it looks very flexible, easy to configure, and we can have all our CIs in a single place, which seems also nice.

By the way, maybe this is a permissions issue? Since now we're checking "Github checks", instead of "Github statuses", maybe we need to grant extra permissions somewhere? See https://github.com/bors-ng/bors-ng#permission-summary.

**Comment by hsbt** [comment]
Thanks all. I only removed the duplicated tasks from .travis.yml 

https://github.com/rubygems/rubygems/blob/2e790f24949cb40be3ea5fa07f7b37c627b174e0/.travis.yml

Ruby 2.6 is duplicated now. But We can leave to issue of CI stack with this configuration. It makes me happy.

GitHub actions is still beta stage. I think github actions should returns status via API. I will request it to GitHub. We can decide to retire bors workflow after GA release of GitHub Actions.

**Comment by duckinator** [comment]
If we retire bundlerbot/bors, I think it's important to make sure whatever we move to _explicitly_ can handle semantic merge conflicts, which is the entire reason for using bors: https://bors.tech/essay/2017/02/02/pitch/

@hsbt does GitHub Actions handle semantic merge conflicts in any way? If it doesn't, I very strongly feel that we should keep bors. We have enough PRs that ignoring semantic merge conflicts and hoping they don't happen isn't an option.

**Comment by duckinator** [comment]
> https://github.com/rubygems/rubygems/pull/2917/commits/533089694bba5c93d44299064541504943a2913b was failed with bors

This is likely because you had a `.` instead of a `,` on line 3. But if `/repos/:owner/:repo/commits/:ref/statuses` isn't showing status names, I'm not sure that matters.

> and we can have all our CIs in a single place, which seems also nice.

There are other platforms that allow this _and_ work with bors, which is a big part of why I'm bothered by the lack of discussion that seemed to happen around moving to GitHub Actions.

I know for a fact that Cirrus CI is capable of Linux+Windows+macOS+FreeBSD because I've done that myself, and CircleCI claims it can do Linux+Windows+macOS (but I've not tried it).

**Comment by duckinator** [comment]
> It's time to retire bundlerbot on rubygems/rubygems. How do you think about this?

Also, I'm confused why you're asserting this.

Why do you think it's time to retire it? What problem(s) does removing it solve?

It serves a purpose: preventing semantic merge conflicts. I have only seen this problem handled well by homu (unmaintained) and bors (what bundlerbot currently uses). If you have another way to handle that, I'd really like to know so I can try it out.

**Comment by deivid-rodriguez** [comment]
The other way is to enable the "require up to date PRs" button on Github, but it's obviously less convenient than bundlerbot.

I think we should try to investigate what the current problem with Github Actions + bundlerbot is, and fix it.

**Comment by duckinator** [comment]
I agree; I think trying to get GitHub Actions + bundlerbot/bors working is probably the best approach at this point, since the former was already done.

**Comment by notriddle** [comment]
I think you actually can use bundlerbot with GitHub Actions. [I've seen other people do it](https://github.com/bors-ng/bors-ng/issues/730#issuecomment-527488484). What you need to do is get the check run name and use it in place of the status name.

You have a heck of a lot of check runs, so your resulting list is going to be pretty long:

```toml
status = [ "macos (2.3.x)", "build (2.3.x, rubygems)", "Build", "build (ruby-head, rubygems)", "build (2.4.x)", "macos (2.4.x)", "build (2.3.x, bundler)", "build (ruby-head, bundler)", "build (2.5.x)", "macos (2.5.x)", "build (2.4.x, rubygems)", "build (jruby-9.2.8.0, rubygems)", "build (2.6.x)", "macos (2.6.x)", "build (2.4.x, bundler)", "build (2.5.x, rubygems)", "build (2.5.x, bundler)", "build (2.6.x, rubygems)", "build (2.6.x, bundler)" ]
```

**Comment by duckinator** [comment]
@notriddle thanks for letting us know! :+1:

**Comment by deivid-rodriguez** [comment]
@notriddle Shouldn't the workflow be included in the check name? Like "ubuntu / build (2.6.x, bundler)"? Otherwise we have some ambiguous check names.

**Comment by notriddle** [comment]
@deivid-rodriguez Probably, yeah? When I designed the Checks integration, it was based on what Travis CI was doing with their GitHub App. There was no ambiguity, then.

I guess you have control over the check run name, so you can make it unambiguous. Or, if that's too hard, I can try to adjust bors-ng so it handles it correctly.

**Comment by deivid-rodriguez** [comment]
Yeah, I'm working on it in #2958, it seems to be working. Thanks so much for your help!

**Comment by hsbt** [comment]
If bors can use with GitHub Actions, We don't need to drop it. I will close this.

I'm going to track #2958
