### ISSUE TITLE
gem command doesn't work behind a http proxy without DNS

### ISSUE THREAD

**Issue by cliffe** [rubygems/rubygems#2939]
My current problem is: the gem command no longer works behind a proxy without a DNS server. This is not the way HTTP_PROXY needs to work, as the proxy server performs its own name resolution. Previous versions worked without a name server configured locally. Gem install results in a DNS time out or destination unreachable. 

The workaround was to set up a DNS server/forwarding on our network, but this shouldn't be necessary (it isn't the case for any other software in the technology stack we use to provision VMs). We have worked around this problem, but it would be beneficial to address it.

This issue is related to:

  - [x] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.5.2.1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
> the gem command no longer works behind a proxy without a DNS server.

@cliffe in what version it was working for you?

**Comment by cliffe** [comment]
> > the gem command no longer works behind a proxy without a DNS server.
> 
> @cliffe in what version it was working for you?

Sorry, @bronzdoc, I'm not sure on previous version numbers, but it stopped working without a DNS nameserver with a recent Debian Stretch apt-get upgrade. It was previously working correctly with HTTP_PROXY.

**Comment by deivid-rodriguez** [comment]
Could this be related to the ipv6 issues?

**Comment by deivid-rodriguez** [comment]
After a second look, it's probably not related to the issue I mentioned. Still it would be nice to get some information about which rubygems version broke this since I don't recall making any changes related to this :thinking:.

**Comment by deivid-rodriguez** [comment]
Since we didn't get more feedback here, I'll close this due to inactivity. If this is still not working for you, and can help us out figuring which rubygems version broke this, feel free to reopen!
