### ISSUE TITLE
ERROR:  While executing gem ... (Errno::EPERM)

### ISSUE THREAD

**Issue by Adobels** [rubygems/rubygems#2956]
My current problem is I can't update the ruby gems under macOS Catalina (10.15) from 3.0.3 to the latest (at this moment 3.0.6)

command: sudo gem update --system

result:
Password:
Updating rubygems-update
Fetching rubygems-update-3.0.6.gem
Successfully installed rubygems-update-3.0.6
Parsing documentation for rubygems-update-3.0.6
Installing ri documentation for rubygems-update-3.0.6
Installing darkfish documentation for rubygems-update-3.0.6
Done installing documentation for rubygems-update after 47 seconds
Parsing documentation for rubygems-update-3.0.6
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 3.0.6
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted @ rb_sysopen - /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/gem

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
  - RUBYGEMS VERSION: 3.0.6
  - RUBY VERSION: 2.6.3 (2019-04-16 patchlevel 62) [universal.x86_64-darwin19]
  - INSTALLATION DIRECTORY: /Library/Ruby/Gems/2.6.0
  - USER INSTALLATION DIRECTORY: /Users/xxx/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/bin
  - SPEC CACHE DIRECTORY: /Users/xxx/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Library/Ruby/Site
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-darwin-19
  - GEM PATHS:
     - /Library/Ruby/Gems/2.6.0
     - /Users/xxx/.gem/ruby/2.6.0
     - /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Library/Apple/usr/bin
     - /Library/Apple/bin
     - /usr/local/share/dotnet
     - ~/.dotnet/tools
     - /Library/Frameworks/Mono.framework/Versions/Current/Commands

```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by Dunaev** [comment]
Try without "sudo".

**Comment by bronzdoc** [comment]
@Adobels is this still an issue for you?

**Comment by bronzdoc** [comment]
Closing due to lack of response

**Comment by Adobels** [comment]
I have no more access to the machine on which I had this issue.

**Comment by gustavo-franco-iw** [comment]
I have the same issues.

Ive run  `sudo gem update --system` and I've got:

`Updating rubygems-update
Fetching: rubygems-update-3.0.6.gem (100%)
Successfully installed rubygems-update-3.0.6
Parsing documentation for rubygems-update-3.0.6
Installing ri documentation for rubygems-update-3.0.6
Installing darkfish documentation for rubygems-update-3.0.6
Done installing documentation for rubygems-update after 53 seconds
Parsing documentation for rubygems-update-3.0.6
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 3.0.6`

Now when I run `sudo gem update --system` again, I get "Latest version already installed. Done."

However when I run ruby -v I get "ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]" 

And gems installation are not working:

`	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6/ext/unf_ext
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -I /Library/Ruby/Site/2.3.0 -r ./siteconf20191129-11439-krnfwq.rb extconf.rb
Building has failed. See above output for more information on the failure.
extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/unf_ext-0.0.7.6 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/unf_ext-0.0.7.6/gem_make.out`

**Comment by dshalaby** [comment]
I have this same exact issue on Catelina 10.15 - any update on a fix?

**Comment by samhrncir** [comment]
I am also having this same issue as @dshalaby and @gustavo-franco-iw on Catelina 10.15

**Comment by dshalaby** [comment]
@samhrncir I fixed this by re-installing Ruby and Cocoapods through Homebrew.    For Homebrew, there's couple well known gotchas regarding folder permissions for the Homebrew install to succeed, but those are easy to search for online since they're well known issues.

**Comment by juancortesparra** [comment]
I try to install rails under rosetta by (M1 issue) and this error happened.

 gem install rails       
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted @ apply2files

**Comment by Juriy** [comment]
Tried both with and without SUDO on Mac:

```
❯ sudo gem update --system
Updating rubygems-update
Fetching rubygems-update-3.2.20.gem
Successfully installed rubygems-update-3.2.20
Parsing documentation for rubygems-update-3.2.20
Installing ri documentation for rubygems-update-3.2.20
Installing darkfish documentation for rubygems-update-3.2.20
Done installing documentation for rubygems-update after 171 seconds
Parsing documentation for rubygems-update-3.2.20
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 3.2.20
ERROR:  While executing gem ... (Errno::EPERM)
    Operation not permitted @ rb_sysopen - /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/gem
```

**Comment by faizzed** [comment]
I was getting the same error in maybe different context. I wanted to install a rails project.

The problem was, my ruby version was 2.6 and rails version was 7.0.2.2.

I switched to ruby 3.1.0 using `rvm use ruby-3.1.0 ` and this fixed the issue for me.

**Comment by camilo-Grability** [comment]
I had the same problem and it was solved when I looked at where my files were located, you must be in the base directory so that it can be installed correctly

**Comment by ekkis** [comment]
> I had the same problem and it was solved when I looked at where my files were located, you must be in the base directory so that it can be installed correctly

what does "base directory" mean?

**Comment by ericmerrill** [comment]
For me (and this was apart of a large brew install, so take it with a grain of salt), I had to do it in my home directory. It failed if I was elsewhere.

**Comment by disastrid** [comment]
Is there any update on this? I'm still having the same issue - permission failure when running without sudo, and `Operation not permitted @ rb_sysopen - /usr/share/man/man1/bundle-platform.1` when running with sudo.

**Comment by deivid-rodriguez** [comment]
I suggest to open a separate issue with whatever issue you are having. This one is closed, and very old, so unlikely to get any traction.
