### ISSUE TITLE
Proposal to change removal of gems + message output

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems#2965]
This issue is related to:

  - [x] The command line `gem`
  - [x] Hosting / Infrastructure

This takes a bit longer to explain, so please excuse that this will be a bit lengthier. It is also partially related to rubygems.org, but I already posted on that other issue tracker, so I will post one here that is partially related, but slightly different as well. Anyway, let me first **describe the current situation** that I am facing here.

I am **not able to yank old gems** that I published right now; I am the gem author of all these gems,
so these are just the gems that I maintain on rubygems.org.

I always almost instantly get this message as a result:

"Retry later"

The command I try is this:

    gem yank studium -v 0.9.328

No matter how long I wait, it seems to be hardcoded-set to this result. In the past, I could
wait e. g. for the next day or something like that, then try again and then it would work; but
right now it seems to not work at all whatsoever.

I have already suggested on rubygems.org that the part there is changed, so that
users can yank a gem (remove a gem), without being stopped by "Retry later"; in
the sense that the remove-action is REGISTERED anyway, but the server(s) at
rubygems.org will decide when the removal would happen. This may be important
because I think one reason for code changes here in the last 3 years were because
people might overload the server, which led to lots of "unicorn crashes" in the past.
So I think this is one reason why it was changed. But at the same time, this led
to some problems e. g. where right now I can not remove any of my old gems.

This may also be partially a problem with openssl here, but I can, as-is, right now,
publish NEW gems, so I believe the problem is not SOLELY confined to my situation
alone. Perhaps there is some cache/history that automatically leads to failure (for
me) to remove my old gems. I have no idea. I just notice that the behaviour is
different.

Anyway - perhaps the rubygems.org team can eventually change the situation
so that we can register the removal of gems (yank gems), without being stopped
by "Retry later". But I also wanted to make a suggestion here, which is a bit
different.

1) The first and most important thing I would like to propose here is to extend
the message "**Retry later**". One improvement would be to tell the user when
he should retry next, such as:

"Retry later (in 300 minutes)"  or any other message that indicates the time. This
will perhaps become irrelevant if the whole "Retry later" is changed towards a
"we have registered that you request the removal of a gem, and will do so at
a later time so you don't have to issue the same gem yank command again".

But for the time being, it may be helpful to show the time.

2) IF there is some other problem, be it openssl-related, or anything else,
then I would suggest that the message becomes more verbose. Right
now it just reads "Retry later", which tells me absolutely NOTHING about
the underlying problem at hand. It would help that, if there is a specific
problem, that gem could tell me which problem exists here. Perhaps this
requires that rubygems.org provides a bit more information to gem itself,
but I think this would be a convenient improvement anyway. As it is
right now, I am left in the dark why yanking gem fails. If instead the message
would be such as "your openssl is out of date, please upgrade", or anything
else, it would help me a LOT. Something isn't quite right here, e. g. I can
publish new gems as-is, which works fine, but I can not remove old published
gems, and that worked fine ~1 month ago or so. (I think there may have been
some code changes or something or some cache where checks are not 
correct right now or assumptions here.)

**Comment by duckinator** [comment]
@rubyFeedback this is really strange, and I can't seem to reproduce it. Were you trying to run a bunch of yank commands in a short timeframe, or something like that? And can you provide the output of `gem env`?

**Comment by bronzdoc** [comment]
Closing due to lack of response
