### ISSUE TITLE
Error with rubygems !

### ISSUE THREAD

**Issue by youssrii** [rubygems/rubygems#2975]
I got this error when try to launch metasploit 3 days ago.. i think it's related to ruby-gems stuff.
Any help would be greatly appreciated.

**root@dhcppc1:~# msfconsole**
Traceback (most recent call last):
4: from internal:gem_prelude:2:in <internal:gem_prelude>' 3: from <internal:gem_prelude>:2:in require'
2: from /usr/local/lib/site_ruby/2.5.0/rubygems.rb:1309:in <top (required)>' 1: from /usr/local/lib/site_ruby/2.5.0/rubygems.rb:1309:in require'
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:34:in `<top (required)>': uninitialized constant Gem::BasicSpecification (NameError)

**Comment by bronzdoc** [comment]
What is the output of `gem env` ?

**Comment by duckinator** [comment]
@youssrii can you provide the output of `gem env` (like @bronzdoc asked) and what operating system you're running?
