### ISSUE TITLE
Rubygems seems to be broken over IPv6

### ISSUE THREAD

**Issue by marctrem** [rubygems/rubygems#2977]
My current problem is: Rubygems does not work over IPv6 AND there is an AAAA record for it.

```
nslookup rubygems.org
Server:         1.1.1.1
Address:        1.1.1.1#53

Non-authoritative answer:
Name:   rubygems.org
Address: 151.101.0.70
Name:   rubygems.org
Address: 151.101.64.70
Name:   rubygems.org
Address: 151.101.128.70
Name:   rubygems.org
Address: 151.101.192.70
Name:   rubygems.org
Address: 2a04:4e42::70
```

This results in:
```
gem update
ERROR:  While executing gem ... (Gem::RemoteFetcher::UnknownHostError)
    timed out (https://rubygems.org/specs.4.8.gz)
```

This issue is related to:

  - [X] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.0.3
```

Possible solutions:
* Remove AAAA Record
* Have Rubygems.org available at the address specified by the AAAA record.

This could be a problem with my IPv6 setup but I doubt it since I can access other services over IPv6 without any issue.
I can access Rubygems.org over IPv4.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by duckinator** [comment]
@marcandre can you run this command and let me what the output is, if there is any? If your IPv6 setup is configured correctly, the entire command should return _nothing_.

```
curl -4 rubygems.org; curl -6 rubygems.org; curl -4 duckinator.net; curl -6 duckinator.net
```

---

I've confirmed that command works on my Digital Ocean VPS, which has IPv6:

```
~$ curl -4 rubygems.org; curl -6 rubygems.org; curl -4 duckinator.net; curl -6 duckinator.net
~$
```

But raises two errors locally, where I don't:

```
~$ curl -4 rubygems.org; curl -6 rubygems.org; curl -4 duckinator.net; curl -6 duckinator.net
curl: (7) Couldn't connect to server
curl: (7) Couldn't connect to server
~$
```

**Comment by marcandre** [comment]
@duckinator, you meant another Marc-André: @marctrem 
Cheers

**Comment by bronzdoc** [comment]
Ping @marctrem

**Comment by duckinator** [comment]
haha, sorry about that @marcandre. :sweat_smile:

**Comment by marctrem** [comment]
Sorry for the delay!

Please don't mind me. I tried accessing the site from my gateway over ipv6 and it works. Sorry for the disturbance! There is probably something wrong with my routing table.
