### ISSUE TITLE
Stale Version in ~/.gem/gems

### ISSUE THREAD

**Issue by below** [rubygems/rubygems#2990]
I'm having a problem or would like to suggest a feature.

My current problem is:

The context is a macOS gitlab runner, and we are trying to update the `fastlane` gem

`fastlane --version` and `bundle exec fastlane --version` return 2.136.0, and `gem list` confirms that version.

However, the runner appears to be using an older version at `~/.gem/gems/fastlane-2.94.0`.

* Why is the runner accessing this location? 
* Any idea how I can make the runner use the system wide `fastlane` gem?
* Can I uninstall the `~ /.gem/gems` directory?

Any hints are appreciated …

This issue is related to:

  - [X ] Installing a library

Here are my current environment details:

```
$ gem env version
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.6
  - RUBY VERSION: 2.6.5 (2019-10-01 patchlevel 114) [x86_64-darwin18]
  - INSTALLATION DIRECTORY: /usr/local/lib/ruby/gems/2.6.0
  - USER INSTALLATION DIRECTORY: /Users/jenkins/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /usr/local/opt/ruby/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/local/lib/ruby/gems/2.6.0/bin
  - SPEC CACHE DIRECTORY: /Users/jenkins/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/Cellar/ruby/2.6.5/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-18
  - GEM PATHS:
     - /usr/local/lib/ruby/gems/2.6.0
     - /Users/jenkins/.gem/ruby/2.6.0
     - /usr/local/Cellar/ruby/2.6.5/lib/ruby/gems/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/opt/ruby/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Please report this to the gitlab runner repo
