### ISSUE TITLE
Can't install "responders" because of ruby version which satisfies the requirement

### ISSUE THREAD

**Issue by rdcx** [rubygems/rubygems#2993]
I'm having a problem or would like to suggest a feature.

My current problem is, can't install gem even when requirements are satisfied

```
Gem::InstallError: responders requires Ruby version >= 2.4.0.
An error occurred while installing responders (3.0.0), and Bundler cannot continue.
Make sure that `gem install responders -v '3.0.0' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  devise-authy was resolved to 1.11.1, which depends on
    devise was resolved to 4.7.1, which depends on
      responders
$ ruby -v
ruby 2.4.0preview3 (2016-11-07 trunk 56661) [x86_64-linux]
```

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.6.8

```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by MSP-Greg** [comment]
I'm pretty sure that ruby 2.4.0preview3 does not meet the criteria 'Ruby version >= 2.4.0'.  It needs to be a release version.

**Comment by bronzdoc** [comment]
@rdcx use a release version and let us know if you are still having problems, thanks!
