### ISSUE TITLE
Cannot push double digit gem minor revisions e.g. 1.10.0

### ISSUE THREAD

**Issue by onewheelskyward** [rubygems/rubygems#2994]
I'm having a problem or would like to suggest a feature.

My current problem is I cannot push version 1.10.x because rubygems says I've already published it.  It's the double digit.  

Successfully built RubyGem
  Name: lita-onewheel-forecast-io
  Version: 1.10.2
  File: lita-onewheel-forecast-io-1.10.2.gem
Pushing gem to https://rubygems.org...
Repushing of gem versions is not allowed.
Please use `gem yank` to remove bad gem releases.

As you can see, I've never published anything greater than 1.9.1.  https://rubygems.org/gems/lita-onewheel-forecast-io

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [X] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.0.1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
@onewheelskyward Thanks fo the report.  I'm looking into this but I'm not being able to reproduce it locally with a test gem.

The only way I get the behavior you are describing is if I already have the version of a gem yanked so it won't let me push it again.

**Comment by onewheelskyward** [comment]
I'm fairly certain I've never yanked this particular gem, is there a way to verify that I haven't?  I've tried 1.10.0, 1.10.1 and 1.10.2, they all give the same error.  This is something I've run into before as well.

**Comment by onewheelskyward** [comment]
So if you update your gemspec to 1.10.x you can push it successfully?

**Comment by bronzdoc** [comment]
@onewheelskyward 
Running rubygems.org locally with a test gem
```
RUBYGEMS_HOST=http://localhost:3000 gem push nitv_yank-0.10.0.gem

Pushing gem to http://localhost:3000...
Successfully registered gem: nitv_yank (0.10.0)
```

I will try with a `1.10.x` version specifically to remove any doubts

**Comment by onewheelskyward** [comment]
I'm wondering if there isn't a text comparison that's running afoul of my 1.1.x versions.  I'll try to isolate steps to repro.  :)

**Comment by onewheelskyward** [comment]
Steps to repro still tbd but I'm still pretty stuck

```[23:25:26] c:/~/s/lita-onewheel-forecast-io  (master ☡=) 👍  gembp
  Successfully built RubyGem
  Name: lita-onewheel-forecast-io
  Version: 1.11.0
  File: lita-onewheel-forecast-io-1.11.0.gem
Pushing gem to https://rubygems.org...
You have enabled multi-factor authentication. Please enter OTP code.
Repushing of gem versions is not allowed.
Please use `gem yank` to remove bad gem releases.
```

**Comment by onewheelskyward** [comment]
Version: 1.12.0
  File: lita-onewheel-forecast-io-1.12.0.gem
Pushing gem to https://rubygems.org...
You have enabled multi-factor authentication. Please enter OTP code.
Repushing of gem versions is not allowed.
Please use `gem yank` to remove bad gem releases.

**Comment by onewheelskyward** [comment]
I iterate a lot.  :D

**Comment by onewheelskyward** [comment]
```  Name: lita-onewheel-forecast-io
  Version: 1.13.0
  File: lita-onewheel-forecast-io-1.13.0.gem
Pushing gem to https://rubygems.org...
You have enabled multi-factor authentication. Please enter OTP code.
Repushing of gem versions is not allowed.
Please use `gem yank` to remove bad gem releases.
```

**Comment by onewheelskyward** [comment]
Ok I performed a simple test- create a 1.1.0 gem and then create a 1.10.0 gem, that didn't recreate the issue.  But I guarantee you I've found a software issue since I certainly have not created the 6 versions of gems that the software is rejecting.  I'll try harder.   :D

**Comment by onewheelskyward** [comment]
Ok I finally got this sorted.  It was a local issue- it had to do with how I was sorting the available gems in the push to rubygems.org. And since the gem push doesn't report what it's trying to push, the issue remained hidden from view.  I've sorted it out now!
