### ISSUE TITLE
 "xx is not an octal string" error when excute gem install on some working path but works well on other working path

### ISSUE THREAD

**Issue by 111qqz** [rubygems/rubygems#2995]
I'm having a problem or would like to suggest a feature.

My current problem is gem install  ruby-protocol-buffers failed because of "ERROR:  While executing gem ... (ArgumentError)
   "2f4bd7fa" is not an octal string
". But when I excute this on another working path,everything works well.
![ruby.png](https://i.loli.net/2019/11/21/iCrPEAaV2UIjQ5f.png)

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

I'm using docker here.
```
Client:
 Debug Mode: false

Server:
 Containers: 39
  Running: 14
  Paused: 0
  Stopped: 25
 Images: 90
 Server Version: 19.03.2
 Storage Driver: overlay2
  Backing Filesystem: xfs
  Supports d_type: true
  Native Overlay Diff: true
 Logging Driver: json-file
 Cgroup Driver: cgroupfs
 Plugins:
  Volume: local local-persist
  Network: bridge host ipvlan macvlan null overlay
  Log: awslogs fluentd gcplogs gelf journald json-file local logentries splunk syslog
 Swarm: inactive
 Runtimes: runc
 Default Runtime: runc
 Init Binary: docker-init
 containerd version: 894b81a4b802e4eb2a91d1ce216b8817763c29fb
 runc version: 425e105d5a03fabd737a126ad93d62a9eeede87f
 init version: fec3683
 Security Options:
  seccomp
   Profile: default
 Kernel Version: 3.10.0-957.12.1.el7.x86_64
 Operating System: CentOS Linux 7 (Core)
 OSType: linux
 Architecture: x86_64
 CPUs: 16
 Total Memory: 15.51GiB
 Name: hk-ecs.novalocal
 ID: RDUI:M2XB:3FU2:6XUJ:QYOD:7XN7:6L3O:SBJI:DHOG:RGUX:CNBC:226I
 Docker Root Dir: /data1/docker
 Debug Mode: false
 Registry: https://index.docker.io/v1/
 Labels:
 Experimental: false
 Insecure Registries:
  127.0.0.0/8
 Live Restore Enabled: false
```
the base image is ubuntu:16.04

```
$ gem env version
2.5.2.1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Hi @111qqz. I think this issue was resolved on recent versions. Can you `gem update --system` and try again?

**Comment by bronzdoc** [comment]
Closing due to lack of response. @111qqz please let us know if this is still an issue after what David suggested to you, Thanks
