### ISSUE TITLE
PRs missing associated CI/Checks information

### ISSUE THREAD

**Issue by duckinator** [rubygems/rubygems#2996]
My current problem is multiple PRs have no CI information.

For some reason, #2835 ("Adds web command") and #2840 ("Support did_you_mean for the CLI") have no CI-related information associated with them:

![Screenshot_20191121_152124](https://user-images.githubusercontent.com/39698/69374789-d9522380-0c74-11ea-89bb-2a54c1d2c873.png)
![Screenshot_20191121_152611](https://user-images.githubusercontent.com/39698/69374793-dd7e4100-0c74-11ea-90b6-5f53df6e7d87.png)
![Screenshot_20191121_153856](https://user-images.githubusercontent.com/39698/69374871-0b638580-0c75-11ea-9090-3d973ccca32b.png)

Compare this to ones using the Travis+Appveyor setup, and ones using the GitHub Actions setup:

![Screenshot_20191121_154139](https://user-images.githubusercontent.com/39698/69375072-71e8a380-0c75-11ea-920b-afd7ba7a731e.png)
![Screenshot_20191121_152636](https://user-images.githubusercontent.com/39698/69374903-1e765580-0c75-11ea-9e30-619eb7c1ba01.png)

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by duckinator** [comment]
Looks like we can use `@bundlerbot try` as a workaround: https://github.com/rubygems/rubygems/pull/2835#issuecomment-557267950

Not great, but doable.

**Comment by deivid-rodriguez** [comment]
@duckinator I think the explanation is that those PRs were created _before_ we migrated to Github Actions and had not been rebased?

**Comment by duckinator** [comment]
@deivid-rodriguez at least one of them (#2835) had been rebased after the migration, but I also suspect it's related to the migration to GitHub Actions.

All of the PRs opened after the migration seem fine as best I can tell, so worst-case scenario should be needing to close+open replacements for old PRs or having a maintainer use bundlerbot to run the tests.

**Comment by hsbt** [comment]
@duckinator Is this still happened?

**Comment by duckinator** [comment]
Nope, one of the affected issues was closed and the other now has the correct CI information. I'll go ahead and close this.
