### ISSUE TITLE
Prevent downgrades to an older version than the one shipped with the current ruby

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#3004]
My current problem is that (don't ask me why, please :rofl:) I run `gem update --system 1.3.0`, and while the downgrade itself worked, that broke my `rubygems` & `bundler` installation because modern rubies don't work with such old `rubygems` versions.

Since, for each ruby version, we only test `bundler` against the `rubygems` versions higher than or equal to the `rubygems` version that shipped with that ruby, I propose that we forbid `gem update --system <target_version>` if `<target_version>` is lower than the `rubygems` version the currently running ruby shipped with.

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
👍 

We should prevent it explicitly.

**Comment by dentarg** [comment]
Hmm... just want to chime in that it was helpful in #2984 to be able to downgrade RubyGems in order to avoid the deprecation warning from `json` that was installed as a default gem on JRuby 9.2.11.1. I haven't looked at #3566 if that would still be possible to do.

**Comment by deivid-rodriguez** [comment]
Yeah. I had thought about that, and the PR would disallow a similar workaround in the future, indeed.

Regarding the problem you mention, it's already fixed in master and we should aim to fix similar issues in the future in a short time with quick patch level versions, so that "downgrading workarounds" are not needed.

However, let's start exploring this solution by only forbidding downgrades to the rubygems version that came with the oldest supported ruby for the moment. That would still allow a downgrade like the one that was useful in the situation you refer to.

I'll update the patch.
