### ISSUE TITLE
Rack gem to include '491' http status code

### ISSUE THREAD

**Issue by kvgana** [rubygems/rubygems#3007]
I'm having a problem or would like to suggest a feature.

My current problem is QA Automation Engineer

This issue is related to:
  - [ ] Installing a library
Rack gem currently does not include '491' HTTP error status code. Please include the same.

Here are my current environment details:
```Rack 2.0.7

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Please report this to https://github.com/rack/rack
