### ISSUE TITLE
`gem list` and `gem info` are being unintentionally deprecated

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#3008]
I'm having a problem or would like to suggest a feature.

My current problem is that running `gem list` or `gem info` against current rubygems master at 99bca8e80c7d7136d62623913b794d313e3bceaf, I get

```
NOTE: info command is deprecated. It will be removed on or after 2019-12-01
```

(or the same with `list`).

These two commands inherit from the `query` command, which will be _intentionally_ deprecated.

It sounds like a bug in #2974.

/cc @bronzdoc

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Working on this right now.

**Comment by bronzdoc** [comment]
Ugh thanks for catching this @deivid-rodriguez.
