### ISSUE TITLE
typoing or deprecated/removed gems should find a bit more, by relaxing the search (and allowing '-')

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems#3018]
I am updating some of my old gems, and noticed that the gem suggestion
on the commandline is a bit ... off, in my opinion.

Specifically take a gem named "taglib". In my old code I am using
it.

I then do this on the commandlie:

    gem install taglib

I find no useful result and instead gem displays this:

ERROR:  Could not find a valid gem 'taglib' (>= 0) in any repository
ERROR:  Possible alternatives: rtaglib, taglib2, taglob, agilib, alglib

Ok so far so fine - but the new release is actually:

    https://rubygems.org/gems/taglib-ruby

So the name is similar, same starting name "taglib", just that the
author added "-ruby" as string. (On a side note: none of my own
gems ever has any "-" character, but I do use "_").

I am not totally sure this is the new one, but the name is more
similar than the other variants. Yet it does not show up in the
suggestion offered here.

Not sure if the "Possible alternatives" listing is limited, but
I would also consider to include gems that

a) .start_with? the same input name, int his case "taglib"

and, more importantly

b) to consider ignoring "-" tokens if they happen past the
input given by the user.

That way the suggestion could also show "taglib-ruby",
which I think is the real variant that I want. At the least
I can not find another explanation why rtaglib would be
suggested, or taglob, but not taglib-ruby. (In the long
run perhaps we could have some additional meta-info or so
to make the message-response by gem better, but for the
time being this small change might help a little. The
only change would be to include it in the above listing.
It's even more logical than "alglib" IMO, since I'd have
to type quite a lot to come from "taglib" to "alglib".)

PS: I managed to typo twice in the title ... :\

**Comment by duckinator** [comment]
Hey!

I'm not entirely sure what the best way to handle this is, but figured I'd provide some background on how this works currently, for context. :slightly_smiling_face: 

---

These suggestions ultimately come from [`Gem::SpecFetcher#suggest_gems_from_name()`](https://github.com/rubygems/rubygems/blob/bde88f0/lib/rubygems/spec_fetcher.rb#L174-L198).

It's implemented using the [Levenshtein distance](https://en.wikipedia.org/wiki/Levenshtein_distance) to determine how similar a string is. My understanding of how this works is that two strings are considered more similar if fewer changes are required to get from one to the other, and less similar if it requires more changes.

In this specific case, `suggest_gems_from_name` removes underscores and hyphens from both strings before comparing them (see [line 175](https://github.com/rubygems/rubygems/blob/bde88f0/lib/rubygems/spec_fetcher.rb#L175) and [line 182](https://github.com/rubygems/rubygems/blob/bde88f0/lib/rubygems/spec_fetcher.rb#L182). (Looks like this already addresses item B above!)

**It, basically, returns the 5 most similar as determined using the Levenshtein distance.**

What this ultimately means is that:
- `rtaglib`, `taglib2`, `taglob` each require changing only 1 character.
- `agilib`, `alglib` each require changing only 2 characters.
-  `taglib-ruby` is treated as equivalent to `taglibruby`. `taglib` -> `taglibruby` requires changing 4 characters.

**Comment by deivid-rodriguez** [comment]
Closed by #31511.
