### ISSUE TITLE
Can't install it.

### ISSUE THREAD

**Issue by 0x-MRNOBODY-x0** [rubygems/rubygems#3019]
When I type ' apt install ruby ' command, it is runing few minutes and showing this error :- 

Fetching pg 0.21.0
Installing pg 0.21.0 with native extensions
Building native extensions. This could take a while...
Gem::Ext::BuildError: ERROR: Failed to build gem native
extension.

current directory:
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/pg-0.21.0/ext
/data/data/com.termux/files/usr/bin/ruby -I
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0 -r
./siteconf20191205-2882-1w5vbzy.rb extconf.rb
checking for pg_config... yes
Using config values from
/data/data/com.termux/files/usr/bin/pg_config
checking for libpq-fe.h... yes
checking for libpq/libpq-fs.h... yes
checking for pg_config_manual.h... yes
checking for PQconnectdb() in -lpq... no
checking for PQconnectdb() in -llibpq... no
checking for PQconnectdb() in -lms/libpq... no
Can't find the PostgreSQL client library (libpq)
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of
necessary
libraries and/or headers.  Check the mkmf.log file for more
details.  You may
need configuration options.

Provided configuration options:
        --with-opt-dir
        --without-opt-dir
        --with-opt-include
        --without-opt-include=${opt-dir}/include
        --with-opt-lib
        --without-opt-lib=${opt-dir}/lib
        --with-make-prog
        --without-make-prog
        --srcdir=.
        --curdir
        --ruby=/data/data/com.termux/files/usr/bin/$(RUBY_BASE_NAME)
        --with-pg
        --without-pg
        --enable-windows-cross
        --disable-windows-cross
        --with-pg-config
        --without-pg-config
        --with-pg_config
        --without-pg_config
        --with-pg-dir
        --without-pg-dir
        --with-pg-include
        --without-pg-include=${pg-dir}/include
        --with-pg-lib
        --without-pg-lib=${pg-dir}/lib
        --with-pqlib
        --without-pqlib
        --with-libpqlib
        --without-libpqlib
        --with-ms/libpqlib
        --without-ms/libpqlib

To see why this extension failed to compile, please check the
mkmf.log which can be found here:

/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/extensions/aarch64-linux/2.6.0/pg-0.21.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/pg-0.21.0
for inspection.
Results logged to
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/extensions/aarch64-linux/2.6.0/pg-0.21.0/gem_make.out

/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:99:in
`run'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:47:in
`block in build'
/data/data/com.termux/files/usr/lib/ruby/2.6.0/tempfile.rb:295:in
`open'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/ext/ext_conf_builder.rb:29:in
`build'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:185:in
`block in build_extension'
/data/data/com.termux/files/usr/lib/ruby/2.6.0/monitor.rb:235:in
`mon_synchronize'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:181:in
`build_extension'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:229:in
`block in build_extensions'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:226:in
`each'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/ext/builder.rb:226:in
`build_extensions'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/installer.rb:830:in
`build_extensions'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/rubygems_gem_installer.rb:30:in
`build_extensions'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/rubygems/installer.rb:320:in
`install'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/source/rubygems.rb:155:in
`block in install'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/rubygems_integration.rb:221:in
`preserve_paths'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/source/rubygems.rb:144:in
`install'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/installer/gem_installer.rb:63:in
`install'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/installer/gem_installer.rb:16:in
`install_from_spec'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/installer/parallel_installer.rb:164:in
`do_install'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/installer/parallel_installer.rb:148:in
`install_serially'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/installer/parallel_installer.rb:103:in
`call'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/installer/parallel_installer.rb:78:in
`call'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/installer.rb:289:in
`install_in_parallel'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/installer.rb:197:in
`install'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/installer.rb:92:in
`block in run'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/process_lock.rb:12:in
`block in lock'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/process_lock.rb:9:in
`open'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/process_lock.rb:9:in
`lock'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler//installer.rb:73:in
`run'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/installer.rb:25:in
`install'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/cli/install.rb:65:in
`run'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:235:in
`block in install'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/settings.rb:143:in
`temporary'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:234:in
`install'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in
`run'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:126:in
`invoke_command'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor.rb:387:in
`dispatch'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:27:in
`dispatch'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/vendor/thor/lib/thor/base.rb:466:in
`start'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/cli.rb:18:in
`start'
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/exe/bundle:30:in
`block in <top (required)>'
/data/data/com.termux/files/usr/lib/ruby/site_ruby/2.6.0/bundler/friendly_errors.rb:124:in
`with_friendly_errors'
/data/data/com.termux/files/usr/lib/ruby/gems/2.6.0/gems/bundler-1.17.3/exe/bundle:22:in
`<top (required)>'
  /data/data/com.termux/files/usr/bin/bundle:23:in `load'
  /data/data/com.termux/files/usr/bin/bundle:23:in `<main>'

An error occurred while installing pg (0.21.0), and
Bundler cannot continue.
Make sure that `gem install pg -v '0.21.0' --source
'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  metasploit-framework was resolved to 5.0.56, which depends on
metasploit-credential was resolved to 3.0.3, which depends
on
metasploit_data_models was resolved to 3.0.10, which
depends on
        pg
dpkg: error processing package metasploit (--configure):
 installed metasploit package post-installation script subprocess returned error exit status 5
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
MR.N0B0DY_@android:~$

Please help me to fix this.

**Comment by 0x-MRNOBODY-x0** [comment]
Hey.. help me to fix this. Please.

**Comment by bronzdoc** [comment]
This is not a rubygems issue.

Try installing `libpq-dev` package and try again

**Comment by 0x-MRNOBODY-x0** [comment]
Oh realy ?  Thank you for the reply.
