### ISSUE TITLE
Large number of methods where planned deprecation dates are 1+ year ago

### ISSUE THREAD

**Issue by duckinator** [rubygems/rubygems#3022]
After seeing #3013, I decided to poke around and see how many dates specified in `deprecate()`/`deprecate_command()` calls have passed.

It looks like 20 deprecated this month or earlier, and 14 were planned  to be removed at least a year ago.

We should probably go through this and either remove them, un-deprecate them, or determine an updated date/version to deprecate them, as appropriate.

It is worth noting that a few methods have comments that reference being removed with RubyGems 4, despite being in this list.

<details>
<summary>Commands ran + raw output</summary>

Planned to be removed this month or earlier:

```
$ git grep deprecate | grep -vE '.txt:|.md:|.rb: +#|^test/|: +@|: +def|^lib/rubygems/compatibility.rb:|^lib/rubygems/specification_policy:|:require .rubygems/deprecate.$|^lib/rubygems/command.rb:|^util|^lib/rubygems/deprecate.rb|^Rakefile:' | grep -E '200.|201.' | wc -l
20
```

Planned to be removed a year ago or more:

```
$ git grep deprecate | grep -vE '.txt:|.md:|.rb: +#|^test/|: +@|: +def|^lib/rubygems/compatibility.rb:|^lib/rubygems/specification_policy:|:require .rubygems/deprecate.$|^lib/rubygems/command.rb:|^util|^lib/rubygems/deprecate.rb|^Rakefile:' | grep -E '201[0-8]' | wc -l
14
$
```

</details>

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by duckinator** [comment]
Here's the ones previously planned to be removed a year ago or more:

```
lib/rubygems.rb:588:    deprecate :gunzip, "Gem::Util.gunzip", 2018, 12
lib/rubygems.rb:602:    deprecate :gzip, "Gem::Util.gzip", 2018, 12
lib/rubygems.rb:616:    deprecate :inflate, "Gem::Util.inflate", 2018, 12
lib/rubygems.rb:1234:    deprecate :detect_gemdeps, "Gem.use_gemdeps", 2018, 12
lib/rubygems/exceptions.rb:17:  deprecate :source_exception, :none, 2018, 12
lib/rubygems/gem_runner.rb:31:      Kernel.warn "NOTE: passing options to Gem::GemRunner.new is deprecated with no replacement. It will be removed on or after 2016-10-01."
lib/rubygems/installer.rb:857:  deprecate :extension_build_error, :none, 2018, 12
lib/rubygems/specification.rb:722:  deprecate :default_executable=, :none,       2018, 12
lib/rubygems/specification.rb:1730:  deprecate :default_executable,  :none,       2018, 12
lib/rubygems/specification.rb:1939:  deprecate :has_rdoc,            :none,       2018, 12
lib/rubygems/specification.rb:1949:  deprecate :has_rdoc=,           :none,       2018, 12
lib/rubygems/specification.rb:1952:  deprecate :has_rdoc?,           :none,       2018, 12
lib/rubygems/user_interaction.rb:367:  deprecate :debug, :none, 2018, 12
lib/ubygems.rb:12:warn "`ubygems.rb' is deprecated, and will be removed on or after 2018-12-01. Remove `-rubygems' from your command-line, or use `-r rubygems' instead"
```

Here's the list of ones previously planned to be removed this year:

```
lib/rubygems/commands/query_command.rb:9:  deprecate_command(2019, 12)
lib/rubygems/dependency_installer.rb:128:  deprecate :available_set_for, :none, 2019, 12
lib/rubygems/dependency_installer.rb:219:  deprecate :find_gems_with_sources, :none, 2019, 12
lib/rubygems/dependency_installer.rb:269:  deprecate :find_spec_by_name_and_version, :none, 2019, 12
lib/rubygems/remote_fetcher.rb:332:  deprecate :fetch_size, :none, 2019, 12
lib/rubygems/specification.rb:735:  deprecate :rubyforge_project=, :none,       2019, 12
```

**Comment by duckinator** [comment]
Of these, it _looks_ like everything deprecated in these files is explicitly not used in the RubyGems codebase (excluding tests related to the method in question):

- `lib/rubygems.rb`
- `lib/rubygems/exceptions.rb`
- `lib/rubygems/gem_runner.rb`
- `lib/rubygems/installer.rb`
- `lib/rubygems/specification.rb`
- `lib/rubygems/dependency_installer.rb`
- `lib/rubygems/remote_fetcher.rb`

These entire files are deprecated, and as best I can tell not required by the rest of the codebase:
- `lib/ubygems.rb`
- `lib/rubygems/commands/query_command.rb`

I had trouble confirming whether deprecated things in the following files are used or not:
- `lib/rubygems/user_interaction.rb`

It looks like some things in these files are still used by RubyGems, but _only in the files being defined_ (meaning we can potentially make them private):
- `lib/rubygems/dependency_installer.rb` (`find_gems_with_sources`, `find_spec_by_name_and_version`)

**Comment by deivid-rodriguez** [comment]
I think it's fine to drop most if not all of these. I think we're being overly conservative here and most of these methods are not meant for end users anyways.

**Comment by duckinator** [comment]
Yeah, the main ones that I'm unsure of are:

- anything mentioning that it should be removed in RubyGems 4.
- things in `lib/rubygems/specification.rb` (since they're explicitly accessible by end-users)
- `lib/ubygems.rb` (same reason)
- `lib/rubygems/commands/query_command.rb` (same reason)

The rest seem to not be intended for end-users at all.

**Comment by deivid-rodriguez** [comment]
That sounds right to me!

**Comment by duckinator** [comment]
Removing `Gem.gzip`/`Gem.gunzip` may be blocked by GitLab:

- I think https://gitlab.com/gitlab-com/www-gitlab-com/issues/2733 is resolved, but it's still open, so I asked if someone can confirm whether it's fixed. (See my comment on there for details.)
- It appears that `gitlab-exporter` uses a version of `unicode-display_width` older than 1.3.3, which uses those functions.

**Comment by duckinator** [comment]
As best I can tell, `Gem::Installer.new` is only used internally, so it may be okay to remove the deprecated ability to pass it a string.

**Comment by duckinator** [comment]
The deprecated attributes in `lib/rubygems/specification.rb` should likely be left alone, since those deprecation warnings are still occurring in the wild.

I'm unsure about the other deprecated functionality in that file.

**Comment by duckinator** [comment]
It appears the deprecated functionality in `lib/rubygems/dependency_installer.rb` is only used in that same file, and only in _other_ deprecated methods. I suspect these can be deprecated without issue, but we may need to check if it's used by e.g. Bundler.

**Comment by deivid-rodriguez** [comment]
We changed deprecations to no longer mention dates, and our release task will block a rubygems 4 release if we haven't dropped all these methods. That seems enough to close this ticket I guess?

**Comment by deivid-rodriguez** [comment]
Seems fixed, so closing.
