### ISSUE TITLE
The `--force` flag is ignored when installing the bundled bundler using `update --system`

### ISSUE THREAD

**Issue by sawanoboly** [rubygems/rubygems#3030]
I'm having a problem.

My current problem is installing rubygems to environment which already installed bundler .

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

docker image `ruby:2.5`.

```
$ docker run -it --rm ruby:2.5 gem env version
3.0.3
```

The installation pauses by asked whether to overwrite.

```
$ docker run -it --rm ruby:2.5 gem update --system --force
Updating rubygems-update
Fetching rubygems-update-3.1.0.gem
Successfully installed rubygems-update-3.1.0
Installing RubyGems 3.1.0
  Successfully built RubyGem
  Name: bundler
  Version: 2.1.0.pre.3
  File: bundler-2.1.0.pre.3.gem
bundler's executable "bundle" conflicts with /usr/local/bin/bundle
Overwrite the executable? [yN]  

```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by dentarg** [comment]
Same here, with RubyGems 3.1.1

```
$ travis_retry gem update --system
Updating rubygems-update
Fetching rubygems-update-3.1.1.gem
Successfully installed rubygems-update-3.1.1
Installing RubyGems 3.1.1
  Successfully built RubyGem
  Name: bundler
  Version: 2.1.0
  File: bundler-2.1.0.gem
bundler's executable "bundle" conflicts with /home/travis/.rvm/rubies/ruby-2.6.5/bin/bundle
Overwrite the executable? [yN]  
```

```
$ ruby --version
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-linux]
$ rvm --version
rvm 1.29.7 (latest) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]
$ bundle --version
Bundler version 1.17.3
$ gem --version
3.0.6
```

**Comment by hsbt** [comment]
@dentarg Your instructions are expected.

**Comment by dentarg** [comment]
@hsbt Okay, thanks, I guess that's a side-effect of https://github.com/rubygems/rubygems/pull/3028

**Comment by hsbt** [comment]
No. Your instructions missed `--force` flag. RubyGems will ask you before overwrite the executable file normally.

**Comment by dentarg** [comment]
@hsbt Yes, sorry, just wanted to show that there's a problem with `--force` and 3.1.1 too (just tried it)

**Comment by hsbt** [comment]
@sawanoboly Can you try https://github.com/puppetlabs/puppet/pull/7887/commits/7dd8187ce636828dfca3c9d367ba7caf32e6934e or https://github.com/voxpupuli/modulesync_config/pull/616/commits/d14b2b3982f472957d8495741e217c1d808a9f0f ?

**Comment by deivid-rodriguez** [comment]
@hsbt's links are valid workarounds but I think we should fix this. I'm trying to fix it in #3035.

**Comment by Zanadar** [comment]
This is also failing on `binstubs --force`. Guessing `--force` is broadly borked.

**Comment by deivid-rodriguez** [comment]
Can you open a separate issue with repro steps for that? What's the exact command that also fails?

**Comment by Zanadar** [comment]
Filed: https://github.com/rubygems/rubygems/issues/3037 for related issue

**Comment by sawanoboly** [comment]
@hsbt Thank you for your suggestion.

I did a workaround to just remove bundler in advance.
https://github.com/higanworks/knife-zero/blob/master/.circleci/config.yml#L11

**Comment by pirj** [comment]
Wondering if it's possible that RubyGems [incorrectly detects](https://github.com/rubygems/rubygems/blob/15706d3e853f9d1fd7b6ddbdcf38cf9a83a345b9/lib/rubygems/user_interaction.rb#L2530) that it's a [TTY](https://github.com/rubygems/rubygems/blob/15706d3e853f9d1fd7b6ddbdcf38cf9a83a345b9/lib/rubygems/user_interaction.rb#L210) and doesn't fall back to [default `false`](https://github.com/rubygems/rubygems/blob/cc3a02724b28fcd7d32f77c8cea837218cd975cc/lib/rubygems/installer.rb#L264)?
