### ISSUE TITLE
RubyGems 3.1.1?

### ISSUE THREAD

**Issue by dentarg** [rubygems/rubygems#3031]
I see that you have published RubyGems 3.1.1 (https://rubygems.org/gems/rubygems-update/versions) but there's no tag for it on https://github.com/rubygems/rubygems/tags

What's the difference between 3.1.0 and 3.1.1?

Ping @hsbt

**Comment by hsbt** [comment]
Please see https://blog.rubygems.org/2019/12/16/3.1.1-released.html

**Comment by dentarg** [comment]
Thanks, to save someone a click, the link says

>Vendor Bundler 2.1.0 again. The version of Bundler with RubyGems 3.1.0 was Bundler 2.1.0.pre.3. Pull request #3029 by SHIBATA Hiroshi.
