### ISSUE TITLE
Travis CI hangs after updating to v3.1.1

### ISSUE THREAD

**Issue by ashmaroli** [rubygems/rubygems#3036]
I'm having a problem.

My current problem is that Travis builds on my project after updating to Rubygems v3.1.1

## Details

My project's Travis builds are configured to use the latest version of Rubygems:
```yaml
before_install:
  - gem update --system --no-document
```

The build terminates with the following:
```sh
$ gem update --system --no-document
Updating rubygems-update
Successfully installed rubygems-update-3.1.1
Installing RubyGems 3.1.1
  Successfully built RubyGem
  Name: bundler
  Version: 2.1.0
  File: bundler-2.1.0.gem
bundler's executable "bundle" conflicts with /home/travis/.rvm/rubies/ruby-2.4.6/bin/bundle
Overwrite the executable? [yN]

No output has been received in the last 10m0s, this potentially indicates a stalled build or
something wrong with the build itself.
Check the details on how to adjust your build configuration on:
https://docs.travis-ci.com/user/common-build-problems/#build-times-out-because-no-output-was-received

The build has been terminated
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by ashmaroli** [comment]
@deivid-rodriguez Any workarounds for use in a CI or docker environment..?
Thanks.

**Comment by mihaibuzgau** [comment]
@ashmaroli this is what we've used as a workaround: https://github.com/puppetlabs/puppet/pull/7887

**Comment by ashmaroli** [comment]
Thank you @mihaibuzgau

**Comment by deivid-rodriguez** [comment]
Sorry about this.

This is actually the consequence of [a bug fix](https://github.com/rubygems/rubygems/pull/2690) with rubygems 3.1. Previous versions generated an incorrect binstub for `bundler`, and now that the newly generated binstub is correct, `rubygems` complains that the old incorrectly generated binstub was not generated by rubygems and refuses to overwrite it.

Once #3030 is released, you can use `gem update --system --force` to force the overwrite, but you could also workaround this with `yes | gem update --system` I believe.

**Comment by ashmaroli** [comment]
> but you could also workaround this with `yes | gem update --system` I believe.

Yes, that is exactly what @mihaibuzgau proposed for the `puppet` project.

**Comment by homeofmatt** [comment]
If anyone is still experiencing
```
ERROR:  While executing gem ... (Gem::InstallError)
    "bundle" from bundler conflicts with /usr/local/bin/bundle
```
Even with `yes` piped in, `sudo gem update --system 3.0.6` works as a band-aid until this is resolved (for anyone okay with downgrading).

**Comment by hsbt** [comment]
This behavior is expected.

> Once #3030 is released, you can use `gem update --system --force` to force the overwrite, but you could also workaround this with `yes | gem update --system` I believe.

Can you apply the above instructions explicitly? Thanks.

**Comment by ashmaroli** [comment]
@hsbt If explicit use of `yes | gem update --system` is the official solution, then please add a note to the README so that the solution gets more exposure.
Thanks.
