### ISSUE TITLE
Issues unpacking tar files "is not an octal string"

### ISSUE THREAD

**Issue by lacostej** [rubygems/rubygems#3050]
I am unable to unpack some tar files that tar handles properly. It fails at parsing the `size`

```
	2: from /Users/lacostej/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_reader.rb:61:in `each'
	1: from /Users/lacostej/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_header.rb:112:in `from'
/Users/lacostej/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_header.rb:130:in `strict_oct': "          0" is not an octal string (ArgumentError)
```
and `checksum`
```
	2: from /Users/lacostej/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_reader.rb:61:in `each'
	1: from /Users/lacostej/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_header.rb:114:in `from'
/Users/lacostej/.rvm/rubies/ruby-2.5.3/lib/ruby/site_ruby/2.5.0/rubygems/package/tar_header.rb:130:in `strict_oct': " 15423" is not an octal string (ArgumentError)
```

Stripping to the `size` and `checksum` fields make the problem go away:
```
        :size     => strict_oct(fields.shift.strip),
        :mtime    => strict_oct(fields.shift),
        :checksum => strict_oct(fields.shift.strip),
```

Here are my current environment details:

```
$ gem env version
3.1.2
```

(I was on 2.7.6 when I encountered the issue, and updated to see if that issue had been fixed)

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Hey @lacostej can you provide steps to reproduce? thank you

**Comment by lacostej** [comment]
@bronzdoc I cannot distribute the zip file I encountered the problem with: it is a unity package I purchased on Unity.com. So far I only have one file I reproduced it on.

Here's the output of the execution of the code that shows the regression between ruby 2.4.1 and 2.5.3

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/24282/71639634-45637680-2c7a-11ea-9f10-36b9a7465521.png">

and here's the script I use:

```ruby
cat `which unity-package.rb`
#!/usr/bin/env ruby
require 'rubygems/package'
require 'zlib'

def print_files(file, verbose)
	tar_extract = Gem::Package::TarReader.new(Zlib::GzipReader.open(file))
	tar_extract.rewind # The extract has to be rewinded after every iteration
	files=[]
	tar_extract.collect do |entry|
	  puts entry.full_name if verbose
	  next unless entry.full_name.end_with? "/pathname"
	  files << entry.read.split("\n")[0]
	end
	tar_extract.close

	puts files.sort
end

if ARGV.count > 0 && ARGV[0] == "-v"
	verbose = true
	ARGV.shift
end

ARGV.each do |file|
	puts "> #{file}"
	print_files(file, verbose)
end
```

the exceptions above show the content of the `strict_oct` strings. They appear to be padded with spaces.

I found some references about this on the web, at least for the checksum field: https://en.wikipedia.org/wiki/Tar_(computing)

```The checksum is calculated by taking the sum of the unsigned byte values of the header record with the eight checksum bytes taken to be ascii spaces (decimal value 32). It is stored as a six digit octal number with leading zeroes followed by a NUL and then a space. Various implementations do not adhere to this format. For better compatibility, ignore leading and trailing whitespace, and take the first six digits.```

Any idea how to proceed?

**Comment by bronzdoc** [comment]
@lacostej You are using the same version of Rubygems with two different versions of Ruby correct?
