### ISSUE TITLE
avoiding Kernel.warn patch

### ISSUE THREAD

**Issue by kares** [rubygems/rubygems#3053]
Seems like RGs 3.0 introduced a `Kernel.warn` replacement.
https://github.com/rubygems/rubygems/commit/7153a317c3e545658459d84aeafdad891d3a8a36#diff-5f3c1066128b69ac52cca10be3eee4f0
This is getting installed "globally" - but does not seem like filtering `:uplevel` is always necessary.

I understand why its being introduced but is it really needed globally?
My concern is that we're potentially walking the (uplevel) stack more than once.
If someone would able to confirm we could refactor to use a proper `Gem.warn` internally, instead. 

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Hi @kares!

Sorry for the delaying in getting back to you here.

The `Kernel.warn` patch was added at https://github.com/rubygems/rubygems/pull/2442. The idea was to fix a small issue where rubygems require would behave differently from ruby's require.

In https://github.com/rubygems/rubygems/pull/3985 I'm changing the patch to a version that seems friendlier and behaves better, so if you were having issues with the current version, maybe this one will behave better for you too.

Hope this helps!

**Comment by deivid-rodriguez** [comment]
It sounds like we'll probably be able to remove the `Kernel.warn` patch in the future, have a look at #3987. Closing this!
