### ISSUE TITLE
Documentation: executables into bin or exe?

### ISSUE THREAD

**Issue by hadmut** [rubygems/rubygems#3057]
Just a minor cosmetical issue:

https://guides.rubygems.org/make-your-own-gem/

tells to put executables into the gem’s bin directory. Which is somehow troublesome, since development progs like console are located there. 

And https://guides.rubygems.org/specification-reference/#executables
tells „all application-style files are expected to be found in bindir.”

When creating a new empty gem with bundler, it takes the exe dir for such purposes:

  spec.executables   = spec.files.grep(%r{^exe/}) { |f| File.basename(f) }

Please update either one to make docs and bundler match each other and be consistent.

Thanks

**Comment by bronzdoc** [comment]
Can you open this in https://github.com/rubygems/guides? thanks!
