### ISSUE TITLE
You have enabled multifactor authentication but no OTP code provided. Please fill it and retry.

### ISSUE THREAD

**Issue by mikosullivan** [rubygems/rubygems#3078]
I'm having a problem or would like to suggest a feature.

My current problem is when I try to use ```gem signin``` I get the error in the post title. Here's the complete transaction:

    Enter your RubyGems.org credentials.
    Don't have an account yet? Create one at https://rubygems.org/sign_up
       Email:   [mu email address]
    Password:   
    
    You have enabled multifactor authentication but no OTP code provided. Please fill it and retry.

I don't know what information I'm supposed to enter. It doesn't prompt me for an OTP code.

This issue is related to:

  - [x] Publishing a library

Here are my current environment details:

```
$ gem env version
2.7.6
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
RubyGems 2.x didn't support the OTP feature. Please upgrade to RubyGems 3.x.

**Comment by mikosullivan** [comment]
I updated to 3.1.2. Now I have all kinds of problems. First, any time I run ruby I get this:

    miko@audrey defaults # ruby
    /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
    /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
    /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
    /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated

If I run gem env version I get this:

    ~ # gem env version
    /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
    /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
    /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
    /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
    /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
    NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
    Gem::Specification#rubyforge_project= called from /usr/share/rubygems-integration/all/specifications/rack-1.6.4.gemspec:19.
    NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
    Gem::Specification#rubyforge_project= called from /var/lib/gems/2.5.0/specifications/thin-1.7.2.gemspec:22.
    /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
    /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:10: warning: constant Gem::ConfigMap is deprecated
    /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:29: warning: constant Gem::ConfigMap is deprecated
    /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:30: warning: constant Gem::ConfigMap is deprecated
    3.1.2

**Comment by hsbt** [comment]
Did you sign-in with OTP feature with RubyGems 3.x? These warnings are intentional behavior.

**Comment by mikosullivan** [comment]
Yes, I did.

**Comment by ecnelises** [comment]
Can you try `--otp DIGIT_CODE` option?

I can have a look at this :)

Regards,
Chaofan

**Comment by mikosullivan** [comment]
@ecnelises: Do you want me to do that in 2.7.6?

**Comment by mikosullivan** [comment]
I did try that option in 2.7.6 and got this error

    ERROR:  Invalid option: --otp. See 'gem --help'.

**Comment by hsbt** [comment]
@mikosullivan Thanks, I will close this.

**Comment by ecnelises** [comment]
Yes. It's version issue. Maybe we should add some text in rubygems.org saying only >3.0 is supported
