### ISSUE TITLE
Setting SOURCE_DATE_EPOCH env var breaks programs that allow it to be unset

### ISSUE THREAD

**Issue by mojavelinux** [rubygems/rubygems#3081]
I'm having a problem with the behavior of the new `Gem.source_date_epoch` function. I don't think it should set the environment variable `SOURCE_DATE_EPOCH` if isn't already set. This affects the behavior of other applications. Existing programs may allow this environment variable to be unset. By loading rubygems (via Bundler at least) into the runtime, it has the side effect that the environment variable is always set. But there's no way to know if it was set by the user's environment or by RubyGems.

Either RubyGems shouldn't set this environment variable itself, or it should honor a secondary environment variable to prevent it from being set (or allow it to be set, either way).

Here are my current environment details:

```
$ gem env version
3.1.2
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

Related issue: #2290

**Comment by mojavelinux** [comment]
To be clear, I'm fine with the `Gem.source_date_epoch` function and what it's doing (setting the build time for the gem based on SOURCE_DATE_EPOCH or the current time). The problem is with the fact that it's altering the environment variable in the process.

**Comment by bronzdoc** [comment]
Maybe we could add a flag to `unset` `SOURCE_DATE_EPOCH `at the end of a build.
What you think @mojavelinux? 

cc: @duckinator

**Comment by mojavelinux** [comment]
I'm not exactly sure "end of the build" would mean. In the case I'm observing, Bundler loads RubyGems to execute the program and that's what causes SOURCE_DATE_EPOCH to be set. It's never unset after that, which then alters how the program behaves. My users have reported they're not setting SOURCE_DATE_EPOCH, but it's behaving like it's set (because of RubyGems). It also causes problems for testing because there's no way to test the unset scenario.

**Comment by duckinator** [comment]
So, looking at the code now, I used the `Gem.source_date_epoch` function in only 3 places:

1. `Gem::Package` (in `lib/rubygems/package.rb`)
2. `Gem::Package::TarWriter` (in `lib/rubygems/package/tar_writer.rb`)
3. `Gem::Specification` (in `lib/rubygems/specification.rb`)

@bronzdoc given the change to # 3, I think it's ensuring the variable is set even when you're not building a gem, and I have a suspicion that's where the problem arises. Basically, my changes added the side-effect of setting `SOURCE_DATE_EPOCH` the first time `Gem::Specification.date` is called (if it wasn't already set).

Perhaps it would make more sense to have `Gem.source_date_epoch` store the value in a Ruby variable (not an environment variable), and have a `Gem.with_source_date_epoch { ... }` which sets it (if it's not set), runs the block, then unsets it (if it wasn't set originally). Something like:

```ruby
def with_source_date_epoch(&block)
  if ENV['SOURCE_DATE_EPOCH'].nil?
    ENV['SOURCE_DATE_EPOCH'] = Gem.source_date_epoch
    yield
    ENV['SOURCE_DATE_EPOCH'] = nil
  else
    yield
  end
end
```

... and then only call _that_ function for things that need to be reproducible, like `gem build`?

**Comment by duckinator** [comment]
I _think_, to make builds reproducible, `SOURCE_DATE_EPOCH` may only need to be set for the duration of `Gem::Package.build` and `Gem::Installer.install`, but I'm not 100% sure of that.

**Comment by duckinator** [comment]
I managed to reproduce by doing `rake install` with [Okay](https://github.com/duckinator/okay), then shrank that down to make a testcase.

Gemfile:
```ruby
source "https://rubygems.org"

gemspec
```

rubygems3081.gemspec:
```ruby
Gem::Specification.new do |spec|
  spec.name          = "rubygems3081"
  spec.version       = "1.0"
  spec.authors       = ["Ellen Marie Dash"]

  spec.summary       = "Testcase for RubyGems issue #3081."
  spec.require_paths = ["."]
end
```

Results:

```
~/test$ ls -a
./  ../  Gemfile  rubygems3081.gemspec
~/test$ cat Gemfile 
source "https://rubygems.org"

gemspec
~/test$ cat rubygems3081.gemspec 
Gem::Specification.new do |spec|
  spec.name          = "rubygems3081"
  spec.version       = "1.0"
  spec.authors       = ["Ellen Marie Dash"]

  spec.summary       = "Testcase for RubyGems issue #3081."
  spec.require_paths = ["."]
end
~/test$ bundle exec ruby -e "p ENV['SOURCE_DATE_EPOCH']"
"1579295120"
```

**Comment by duckinator** [comment]
Made a smaller but less-realistic testcase:

```
~/test$ ruby -e 'Gem::Specification.new("a", "1.0.0"); p ENV["SOURCE_DATE_EPOCH"]'
nil
~/test$ ruby -e 'Gem::Specification.new("a", "1.0.0").date; p ENV["SOURCE_DATE_EPOCH"]'
"1579295426"
~/test$
```

**Comment by duckinator** [comment]
Made an attempt at fixing this with #3088.

**Comment by bronzdoc** [comment]
closed by https://github.com/rubygems/rubygems/pull/3088
