### ISSUE TITLE
Incorrect bundler version gets required

### ISSUE THREAD

**Issue by x-yuri** [rubygems/rubygems#3082]
I'm having a problem.

My current problem is in the title. Steps to reproduce:

`1.sh`:

```sh
#!/bin/sh
# apk add build-base neovim
gem install bundler -v '~> 1.0'
mkdir app
cd app
touch Gemfile
bundle _1.17.3_
cat Gemfile.lock
cat > 1.rb <<\SCRIPT
require 'bundler/setup'
p Bundler::VERSION
SCRIPT
ruby 1.rb
```

```
$ docker run --rm -v $PWD/1.sh:/1.sh ruby:2.7-alpine ./1.sh
Successfully installed bundler-1.17.3
1 gem installed
The Gemfile specifies no dependencies
Resolving dependencies...
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
GEM
  specs:

PLATFORMS
  ruby

DEPENDENCIES

BUNDLED WITH
   1.17.3
"2.1.2"
```

So, as you can see it says, "BUNDLED_WITH 1.17.3," but "2.1.2" gets required. That doesn't happen with `ruby-2.6`:

`2.sh`:

```sh
#!/bin/sh
# apk add build-base neovim
gem install bundler
mkdir app
cd app
touch Gemfile
bundle
cat Gemfile.lock
cat > 1.rb <<\SCRIPT
require 'bundler/setup'
p Bundler::VERSION
SCRIPT
ruby 1.rb
```

```
$ docker run --rm -v $PWD/2.sh:/2.sh ruby:2.6-alpine
Successfully installed bundler-2.1.4
1 gem installed
Resolving dependencies...
Bundle complete! 0 Gemfile dependencies, 1 gem now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
GEM
  specs:

PLATFORMS
  ruby

DEPENDENCIES

BUNDLED WITH
   2.1.4
"2.1.4"
```

The reason why this is happening is because `rubygems` [doesn't find][1] the default `bundler` spec by path, as such the default `bundler` is always required. That in its turn happens because when the default spec (`bundler-2.1.2`) gets registered, none of its files make its way into `@path_to_default_spec_map`. Because the spec is considered to be in the new format, but [the following line][2] filters out all the `bundler` files. Let's take a look at the `bundler-2.1.2` spec [from `ruby-2.7`][3]:

`/usr/local/lib/ruby/gems/2.7.0/specifications/default/bundler-2.1.2.gemspec`:

```rb
...
  s.require_paths = ["lib".freeze]
  s.files = ["bundler.rb".freeze, ..., "libexec/bundle".freeze, "libexec/bundler".freeze]
...
```

That is, there are 2 files in `libexec` dir, that is the reason why `rubygems` decides it uses the new format. But `prefix_pattern` is `/^(lib\/)/`, it doesn't match any file, can't be removed, and so every file is skipped.

`ruby-2.6` spec [doesn't have][4] `libexec` dir.

I'm not sure if that's an issue with `rubygems`. The `bundler` spec might very well be wrong, like in [this case][5].

[1]: https://github.com/rubygems/rubygems/blob/v3.1.2/lib/rubygems/core_ext/kernel_require.rb#L78
[2]: https://github.com/rubygems/rubygems/blob/v3.1.2/lib/rubygems.rb#L1294
[3]: https://gist.github.com/x-yuri/2d2691a682cc933f7a06147c84e1fd2b
[4]: https://gist.github.com/x-yuri/2d2691a682cc933f7a06147c84e1fd2b
[5]: https://bugs.ruby-lang.org/issues/15582

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

```
$ gem env version
3.1.2
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
I introduced this regression when improving bundler's integration in ruby-core. I'll fix it, thanks for reporting.

**Comment by x-yuri** [comment]
Meanwhile (before `ruby-2.7.2` is released), you can rely on `rubygems` finding the [right version of `bundler`][1] (the one specified in your `Gemfile.lock` file). For that you need, unsurprisingly, to prepend `bundle exec` to your command, e.g. `bin/rails server` becomes `bundle exec bin/rails server`.

[1]: https://github.com/rubygems/rubygems/blob/v3.2.0.rc.1/lib/rubygems/bundler_version_finder.rb#L42-L51
