### ISSUE TITLE
Bundler version finder breaks when run in deleted current working dir

### ISSUE THREAD

**Issue by asf-stripe** [rubygems/rubygems#3087]
I'm having a problem or would like to suggest a feature.

My current problem is that `Gem::Specification.find_by_name('bundler')` raises an exception if the program running it is currently in a deleted directory

This issue is related to:

  - [x] Other

Here are my current environment details:

```
$ gem env version
3.1.2
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

# Reproducing this issue
Here's a repro case:

```ruby
require 'tmpdir'

Dir.mktmpdir do |dir|
  Dir.chdir(dir)
  puts "pwd is now #{Dir.pwd}"
end

# our current dir is now gone
bundler_gem = Gem::Specification.find_by_name('bundler') # ...and this breaks.
puts("Using Bundler #{bundler_gem.version.to_s}")
```

<details>
  <summary>output and backtrace</summary>

```
pwd is now /private/var/folders/nt/f37r9kbx1n73b4sj48rr4tsw0000gn/T/d20200117-32602-19akv9a
Traceback (most recent call last):
        10: from main.rb:9:in `<main>'
         9: from /Users/asf/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/specification.rb:988:in `find_by_name'
         8: from /Users/asf/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/dependency.rb:323:in `to_spec'
         7: from /Users/asf/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/dependency.rb:303:in `to_specs'
         6: from /Users/asf/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/dependency.rb:284:in `matching_specs'
         5: from /Users/asf/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:45:in `filter!'
         4: from /Users/asf/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:7:in `bundler_version'
         3: from /Users/asf/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:22:in `bundler_version_with_reason'
         2: from /Users/asf/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:73:in `lockfile_version'
         1: from /Users/asf/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:85:in `lockfile_contents'
/Users/asf/.rbenv/versions/2.6.3/lib/ruby/site_ruby/2.6.0/rubygems/bundler_version_finder.rb:85:in `pwd': No such file or directory - getcwd (Errno::ENOENT)
```
</details>

This is a mildly contrived example (I tried to make it self-contained), but sometimes the services we run have their working directory go away due to environmental conditions; it would be good if they were resilient to this scenario - I would expect the specification finder to either work as expected (it does find a bundler gem if you execute the code under `bundle exec` but raises `Errno::ENOENT` if no bundler is present in the currently-loaded gems.

I would expect this snippet to correctly find the bundler gem that's installed via rubygems, or if that's not installed on the global rubygems env, to return a nil specification.

**Comment by bronzdoc** [comment]
Hey @asf-stripe thanks for the report and the steps to reproduce!

The problem relies on how `Dir.pwd` behaves when the current directory is deleted. I'm working in a patch .
