### ISSUE TITLE
Better handling of the `required_ruby_version` constraint in gemspecs

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#3089]
This issue is completely equivalent to #2575, but for the `required_ruby_version` constraint.

As an example, using the latest version of `rubygems`, running `gem install rails` on `ruby-2.4.9` will fail like this:

```console
$ gem install rails
Fetching sprockets-4.0.0.gem
Fetching rack-test-1.1.0.gem
ERROR:  Error installing rails:
	There are no versions of activesupport (= 6.0.2.1) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
	activesupport requires Ruby version >= 2.5.0. The current ruby version is 2.4.9.362.
```

Instead, `rubygems` should install the latest version of `rails` compatible with ruby 2.4.9.

There's a WIP PR for this at https://github.com/rubygems/rubygems/pull/2655, but still needs work.

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.1.2
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by MSP-Greg** [comment]
@deivid-rodriguez

I thought there was agreement that the best way to implement this was to change RG over to the 'API' data used by Bundler, and drop the older (inefficient) API used by RG.  Especially with Bundler now integrated.

Am I mistaken?  It's been a while...

**Comment by deivid-rodriguez** [comment]
Mmmm, what do you mean? I just opened a ticket about a rubygems issue, I didn't suggest any implementations for the solution.

**Comment by deivid-rodriguez** [comment]
I do agree that's the best way to fix it, yeah.

**Comment by deivid-rodriguez** [comment]
Oh, I think I understand what you mean, you ask because I linked to your PR, right? Well, I think it's best to switch to the API used by bundler, but I think we can probably still reuse some of your work?

**Comment by MSP-Greg** [comment]
> you ask because I linked to your PR, right?

Yes.

> I think it's best to switch to the API used by bundler

Totally agree.

> I think we can probably still reuse some of your work?

I think when I did the PR, I was unaware of the Bundler API.

I hadn't really jumped into the Bundler codebase, as I often used Windows Ruby master, and it wanted to install pre-compiled gems, which most never supported Ruby master (depending on the timing, often didn't support the current Ruby release).

Hence, I always assumed that most of the code in the PR would be superseded by the change to the Bundler API.  Maybe I'm mistaken?

**Comment by deivid-rodriguez** [comment]
I don't know, maybe you're right. Hopefully we'll find out soon :)
