### ISSUE TITLE
rubygems update giving deprecation error

### ISSUE THREAD

**Issue by elizadizon** [rubygems/rubygems#3094]
I updated rubygems using the following instructions:

https://bundler.io/v2.0/guides/rubygems_tls_ssl_troubleshooting_guide.html#troubleshooting-certificate-errors

Now whenever I run a command, I get deprecation warnings.

19:48]# chef -v
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/specifications/timeliness-0.3.10.gemspec:18.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/specifications/systemu-2.6.5.gemspec:16.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/specifications/net-ssh-multi-1.2.1.gemspec:19.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/specifications/net-sftp-2.1.2.gemspec:19.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/specifications/highline-1.7.10.gemspec:20.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/specifications/erubis-2.7.0.gemspec:17.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/specifications/iniparse-1.4.4.gemspec:19.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/specifications/net-scp-1.2.1.gemspec:19.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/specifications/gyoku-1.3.1.gemspec:17.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/specifications/logging-2.2.2.gemspec:18.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/specifications/little-plugger-1.1.4.gemspec:18.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/specifications/nori-2.6.0.gemspec:17.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/specifications/inifile-3.0.0.gemspec:18.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/specifications/unicode_utils-1.4.0.gemspec:18.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/specifications/formatador-0.2.5.gemspec:18.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/specifications/coderay-1.1.2.gemspec:21.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/specifications/ffi-rzmq-2.0.7.gemspec:16.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/specifications/rufus-lru-1.1.0.gemspec:16.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/specifications/sshkey-1.9.0.gemspec:16.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /opt/chefdk/embedded/lib/ruby/gems/2.5.0/specifications/lockfile-2.1.3.gemspec:18.
Traceback (most recent call last):
        3: from /bin/chef:226:in `<main>'
        2: from /opt/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/core_ext/kernel_gem.rb:62:in `gem'
        1: from /opt/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/dependency.rb:323:in `to_spec'
/opt/chefdk/embedded/lib/ruby/site_ruby/2.5.0/rubygems/dependency.rb:313:in `to_specs': Could not find 'rdoc' (= 6.0.1) - did find: [rdoc-6.0.1.1] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/root/.chefdk/gem/ruby/2.5.0:/opt/chefdk/embedded/lib/ruby/gems/2.5.0', execute `gem env` for more information

Here are my current environment details:

redhat 7

```
$ gem env version

 gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.0.14.1
  - RUBY VERSION: 2.0.0 (2015-12-16 patchlevel 648) [x86_64-linux]
  - INSTALLATION DIRECTORY: /usr/local/share/gems
  - RUBY EXECUTABLE: /usr/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /usr/local/share/gems
     - /root/.gem/ruby
     - /usr/share/gems
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://rubygems.org/"]
     - "install" => "--user --no-document"
     - "update" => "--user --no-document"
     - "http_proxy" => nil
  - REMOTE SOURCES:
     - https://rubygems.org/

```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Please followup with: https://github.com/rubygems/rubygems/issues/2984

**Comment by elizadizon** [comment]
I have this issue as well (shown at the very bottom of the above excerpt) 

Could not find 'rdoc' (= 6.0.1) - did find: [rdoc-6.0.1.1] (Gem::MissingSpecVersionError)
Checked in 'GEM_PATH=/root/.chefdk/gem/ruby/2.5.0:/opt/chefdk/embedded/lib/ruby/gems/2.5.0', execute

**Comment by suraneti** [comment]
I am facing this issue.


**env**
```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.1.2
  - RUBY VERSION: 2.3.7 (2018-03-28 patchlevel 456) [universal.x86_64-darwin18]
  - INSTALLATION DIRECTORY: /Library/Ruby/Gems/2.3.0
  - USER INSTALLATION DIRECTORY: /Users/suraneti/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /usr/bin
  - SPEC CACHE DIRECTORY: /Users/suraneti/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Library/Ruby/Site
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-darwin-18
  - GEM PATHS:
     - /Library/Ruby/Gems/2.3.0
     - /Users/suraneti/.gem/ruby/2.3.0
     - /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/suraneti/.cargo/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /usr/local/share/dotnet
     - /Library/Frameworks/Mono.framework/Versions/Current/Commands
     - /Applications/Wireshark.app/Contents/MacOS
     - /usr/local/go/bin
     - /Users/suraneti/go/bin
     - /Users/suraneti/Library/Android/sdk/emulator
     - /Users/suraneti/Library/Android/sdk/tools
     - /Users/suraneti/Library/Android/sdk/tools/bin
     - /Users/suraneti/Library/Android/sdk/platform-tools
     - /Users/suraneti/flutter/bin
     - /Users/suraneti/google-cloud-sdk/bin
     - /Users/suraneti/Library/Android/sdk/tools
     - /Users/suraneti/Library/Android/sdk/build-tools/28.0.3
```


**log**
```
Suraneti's Macbook Pro:~ suraneti$ gem env
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /Library/Ruby/Gems/2.3.0/specifications/escape-0.0.4.gemspec:18.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /Library/Ruby/Gems/2.3.0/specifications/fuzzy_match-2.0.4.gemspec:17.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /Library/Ruby/Gems/2.3.0/specifications/highline-1.7.10.gemspec:20.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /Library/Ruby/Gems/2.3.0/specifications/i18n-0.9.5.gemspec:17.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /Library/Ruby/Gems/2.3.0/specifications/multipart-post-2.0.0.gemspec:17.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0/specifications/nokogiri-1.5.6.gemspec:22.
NOTE: Gem::Specification#rubyforge_project= is deprecated with no replacement. It will be removed on or after 2019-12-01.
Gem::Specification#rubyforge_project= called from /Library/Ruby/Gems/2.3.0/specifications/rouge-2.0.7.gemspec:18.
```

**Comment by simi** [comment]
:information_source: 3.1.4 was released - https://blog.rubygems.org/2020/06/03/3.1.4-released.html fixing this problem.

You can update by running `gem update --system 3.1.4`.
