### ISSUE TITLE
Installing a GEM with native extension fails when Ruby install dir contains spaces.

### ISSUE THREAD

**Issue by ams-tschoening** [rubygems/rubygems#3126]
I'm having a problem or would like to suggest a feature.

My current problem is that when Ruby is installed into a path with spaces, GEMs with native extension seem to still fail to build. In my case this is not in some called shell script or such, but in the generated `Makefile` of that GEM directly:

	C:\Program Files\Ruby\2.6.5\bin>gem install solargraph
	Fetching backport-1.1.2.gem
	Successfully installed backport-1.1.2
	Fetching benchmark-0.1.0.gem
	Successfully installed benchmark-0.1.0
	Fetching bundler-2.1.4.gem
	Successfully installed bundler-2.1.4
	Fetching e2mmap-0.1.0.gem
	Successfully installed e2mmap-0.1.0
	Fetching jaro_winkler-1.5.4.gem
	Temporarily enhancing PATH for MSYS/MINGW...
	Building native extensions. This could take a while...
	ERROR:  Error installing solargraph:
	        ERROR: Failed to build gem native extension.

	    current directory: C:/Users/tschoening/.gem/ruby/2.6.0/gems/jaro_winkler-1.5.4/ext/jaro_winkler
	C:/Program\ Files/Ruby/2.6.5/bin/ruby.exe -I C:/Program\ Files/Ruby/2.6.5/lib/ruby/2.6.0 -r ./siteconf20200204-13668-p6lmwi.rb extconf.rb
	creating Makefile

	current directory: C:/Users/tschoening/.gem/ruby/2.6.0/gems/jaro_winkler-1.5.4/ext/jaro_winkler
	make "DESTDIR=" clean
	Makefile:269: *** Mehrfache Ziel-Muster.  Schluss.

	current directory: C:/Users/tschoening/.gem/ruby/2.6.0/gems/jaro_winkler-1.5.4/ext/jaro_winkler
	make "DESTDIR="
	Makefile:269: *** Mehrfache Ziel-Muster.  Schluss.

	make failed, exit code 2

	Gem files will remain installed in C:/Users/tschoening/.gem/ruby/2.6.0/gems/jaro_winkler-1.5.4 for inspection.
	Results logged to C:/Users/tschoening/.gem/ruby/2.6.0/extensions/x64-mingw32/2.6.0/jaro_winkler-1.5.4/gem_make.out

English error message:

    C:\Users\tschoening\.gem\ruby\2.6.0\gems\jaro_winkler-1.5.4\ext\jaro_winkler>c:\msys64\usr\bin\make.exe
    Makefile:269: *** multiple target patterns.  Stop.

I've already read that the [FAQ](https://github.com/oneclick/rubyinstaller/wiki/faq#no_pgmfiles) [and](https://github.com/oneclick/rubyinstaller/wiki/Troubleshooting) [others](https://github.com/oneclick/rubyinstaller/wiki/Development-Kit#requirements) advise to not use paths with spaces and that the installer doesn't suggest them as well, but [other issues](https://github.com/rubygems/rubygems/issues/523) [like this](https://github.com/rubygems/rubygems/issues/1525) have been posted in the past already, so I'm doing the same.

Not sure, though, if the underlying problem is in rubygems, the concrete gem or a gem that gem uses, because it contains the following lines in `extconf.rb`:

    require 'mkmf'
    $CFLAGS << ' -std=c99 '
    create_makefile('jaro_winkler/jaro_winkler_ext')

Looking at the generated [Makefile.txt](https://github.com/rubygems/rubygems/files/4156078/Makefile.txt), some paths are properly quoted or escaped already:

    topdir = /C/Program\ Files/Ruby/2.6.5/include/ruby-2.6.0
    arch_hdrdir = "C:/Program Files/Ruby/2.6.5/include/ruby-2.6.0/x64-mingw32"

Though, after debugging things, it seems that using quotes for the path with spaces is the root of the issue. Changing that to the same approach like with `topdir`, the makefile gets executed properly.

    arch_hdrdir = "C:/Program Files/Ruby/2.6.5/include/ruby-2.6.0/x64-mingw32"

vs.

    arch_hdrdir = /C/Program\ Files/Ruby/2.6.5/include/ruby-2.6.0/x64-mingw32

Success:

    C:\Users\tschoening\.gem\ruby\2.6.0\gems\jaro_winkler-1.5.4\ext\jaro_winkler>c:\msys64\usr\bin\make.exe
     linking shared-object jaro_winkler/jaro_winkler_ext.so

The actual problem was `ruby_headers` at the line mentioned in the error message, which used that placeholder in one path:

    ruby_headers = $(hdrdir)/ruby.h [...] $(arch_hdrdir)/ruby/config.h

This issue is related to:

  - [ ] Network problems
  - [X] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.0.3
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by MSP-Greg** [comment]
@ams-tschoening

This may be an issue with Ruby's mkmf.rb file, rather than a RubyGems issue.  You might check that, I'll check this weekend...

**Comment by chriszo111** [comment]
I had the same issue, the location of ruby was `E:\Program Files\Ruby26-x64`. After I tried installing all gems, bundler exited:
```
current directory: E:/Program Files/Ruby26-x64/lib/ruby/gems/2.6.0/gems/websocket-driver-0.7.1/ext/websocket-driver
E:/Program\ Files/Ruby26-x64/bin/ruby.exe -I E:/Program\ Files/Ruby26-x64/lib/ruby/2.6.0 -r ./siteconf20200522-15776-djmkzq.rb extconf.rb
creating Makefile

current directory: E:/Program Files/Ruby26-x64/lib/ruby/gems/2.6.0/gems/websocket-driver-0.7.1/ext/websocket-driver
make "DESTDIR=" clean
Makefile:269: *** Mehrfache Ziel-Muster.  Schluss.

current directory: E:/Program Files/Ruby26-x64/lib/ruby/gems/2.6.0/gems/websocket-driver-0.7.1/ext/websocket-driver
make "DESTDIR="
Makefile:269: *** Mehrfache Ziel-Muster.  Schluss.

make failed, exit code 2
```
When I moved it to `E:\Ruby26-x64` bundler installed all gems without issues.

**Comment by deivid-rodriguez** [comment]
I _think_ we might have improved some extension building issues in recent versions. Could you try to reproduce this against the latest prerelease (`gem update --system --pre` will install it for you).

**Comment by deivid-rodriguez** [comment]
I'll assume this is fixed. Feel free to reopen if you can repro this on the latest rubygems prerelease.
