### ISSUE TITLE
3.1.2: Locally installed dependency not recognized

### ISSUE THREAD

**Issue by BertramScharpf** [rubygems/rubygems#3135]
Sorry, I cannot post my gems, they are confidential.

While installing a gem, RubyGems 3.1.2 is complaining about a dependency:

  ERROR:  Could not find a valid gem 'p...' (~> 3) (required by '...-2.0.gem' (>= 0)) in any repository

But the dependency is installed.

I found two ways to solve the problem: Either downgrade to Gems 3.0.6, or provide the gem in a local repository that I added to .gemrc.

It took me hours to find out what happens and I still have no clue where the bug could be. I give up. I do not feel like frisking this filthy piece of software any further. I am a great fan of Ruby, but this RubyGems should be thrown away and rewritten from scratch. It is a menace for the beautiful language Ruby,

**Comment by colby-swandale** [comment]
@BertramScharpf before trying to help resolve this problem, lets talk about your language. You're coming off as extremely rude and insulting by calling our project "filthy" and something that should be thrown away. I can assure you that it's a guaranteed way to not receive help here. I'll give you the opportunity to revise your wording, or I'll trash this issue. I also remind you that we have a [Code of Conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md)

**Comment by BertramScharpf** [comment]
I do not expect any help. I just wanted to tell that I tried to contribute by submitting a patch, but that this was not possible in more than 3 hours because of the internal structure of RubyGems. Good luck with fixing this issue yourself.
