### ISSUE TITLE
Can rubygems ignore RUBYGEMS_GEMDEPS automatically for the bundler gem?

### ISSUE THREAD

**Issue by lamont-granquist** [rubygems/rubygems#3142]
I wind up having to do `RUBYGEMS_GEMDEPS= bundle install` or `RUBYGEMS_GEMDEPS= bundle update` a lot.

I'd at least like an environment variable I could set so that it wouldn't wind up trying to `bundle exec bundle whatever` since that rarely makes any sense (maybe an environment variable to set to a space or comma separated list of gems or binstubs to ignore RUBYGEMS_GEMDEPS with?)

This would match the behavior of rvm and I believe https://github.com/rvm/rubygems-bundler (I was a happy user of rvm for years and loved the lack of having to bundle exec, but have been trying to switching to asdf and the almost seamless lack of needing to bundle exec is something that I miss).

**Comment by lamont-granquist** [comment]
Prior art here from rubygems-bundler:

https://github.com/rvm/rubygems-bundler/blob/0ac1c95377c7f0280e3b3eff52e324d5292bb508/lib/rubygems-bundler/noexec.rb#L108-L116

**Comment by deivid-rodriguez** [comment]
I started some work not long ago to automatically enable `RUBYGEMS_GEMDEPS` if there's a `Gemfile` to avoid the need for `bundle exec` altogether. Hopefully I can get back to it soon.

**Comment by lloeki** [comment]
To call on each `cd`:

```
_auto-rubygems_gemdeps() {
    local check_dir=$PWD
    local next_check_dir=${check_dir%/*}
    while [ "$next_check_dir" != "" ]; do
        if [[ -f "$check_dir/Gemfile" ]]; then
            export RUBYGEMS_GEMDEPS="$check_dir/Gemfile"
            return
        fi
        check_dir="$next_check_dir"
        next_check_dir=${check_dir%/*}
    done
    unset RUBYGEMS_GEMDEPS
}
```

How to have it called on each `cd`:

```
# zsh has a magic chpwd callback:
chpwd() {
    # you can add more things here...
    _auto-rubygems_gemdeps
    # ... but only add stuff calling to ruby after!
}
chpwd # call it directly once

# bash backport of zsh's chpwd callback system, define before `chpwd above`:
function chpwd   { :; }
__cd_invoke_chpwd() {
    builtin cd "$@"
    chpwd
}
cd() { __cd_invoke_chpwd "$@"; }
```

**Comment by lamont-granquist** [comment]
So that doesn't really solve this issue, there seems to be a bit of a misunderstanding here.

* If I am in directory with a Gemfile and Gemfile.lock which have been pulled from git so they are out of synch with my rubylib
* And I have `RUBYGEMS_GEMDEPS=-` set (which seems to work fine for me, or else just set it to the gemfile)
* Then when I 'bundle install' or 'bundle update' it attempts to 'bundle exec bundle install' which produces errors because the gems in the bundle have not been installed yet (chicken+egg)
* The solution is that for 'bundle install' or 'bundle update' (or any other bundle command) that the RUBYGEMS_GEMDEP behavior should be ignored to not auto-bundle-exec for those commands.

The `rvm/rubygems-bundler` command implemented this years ago and works well:

```
  def check
    if %w(bundle rubygems-bundler-uninstaller).include?(bin)
      log "Noexec - skipped binary: #{bin}"

    elsif ENV['NOEXEC_EXCLUDE'] && ENV['NOEXEC_EXCLUDE'].split(/ /).include?(bin)
      log "Noexec - ENV skipped binary: #{bin}"

    elsif ENV['BUNDLE_GEMFILE'] && ENV['BUNDLE_BIN_PATH'] && ENV['RUBYOPT']
      log "Noexec - already in 'bundle exec'"

    elsif %w(0 skip).include?( ENV['NOEXEC'] ) || ENV.key?('NOEXEC_DISABLE')
      #TODO: deprecated in 1.1.0, to be removed later -- 2012.09.05
      $stderr.puts "Warning, 'NOEXEC' environment variable is deprecated, switch to 'NOEXEC_DISABLE=1'." if ENV.key?('NOEXEC')
      log "Noexec - disabled with environment variable"

    else
      setup

    end
  end
```

The first line there skips running `bundle exec` on any `bundle xxx` command (and the commands own uninstaller).  Then it lets the user specify additional commands to skip with `ENV['NOEXEC_EXCLUDE`]`, it skips bundle execing if you're already in a bundle, and then supports using `NOEXEC_DISABLE=1` (which would be comparable to unsetting `RUBYGEMS_GEMDEPS=`).

My solution right now is to just do this a lot:  `RUBYGEMS_GEMDEPS= bundle install` or `RUBYGEMS_GEMDEPS= bundle update` which works fine, but its annoying when I forget that, and it might not be obvious to people who try using the env var what is going on when it explodes when you don't do that.

**Comment by lamont-granquist** [comment]
So this works pretty well:

```
export RUBYGEMS_GEMDEPS=-
alias bundle='RUBYGEMS_GEMDEPS= bundle'
alias gem='RUBYGEMS_GEMDEPS= gem'
```

I think it'd be nicer if bundler did that internally, possibly also with supporting the `NOEXEC_DISABLE=1` flag which would make e.g. the transition from rvm to asdf be smooth for former rvm users.

**Comment by deivid-rodriguez** [comment]
@lamont-granquist My mid/long term plan would be to indeed make this the default behaviour. But your suggestion to start off by making `RUBYGEMS_GEMDEPS` actually usable first makes sense to me. I started some work in that direction in https://github.com/rubygems/rubygems/pull/4532. Feel free to give that PR a try and let me know how it's working for you.

**Comment by deivid-rodriguez** [comment]
@lamont-granquist #4532 should be now ready, feel free to give it a try. With it, having  `RUBYGEMS_GEMDEPS=-` set should completely remove the need of using `bundle exec` at all.
