### ISSUE TITLE
Extend did_you_mean functionality to `gem install`

### ISSUE THREAD

**Issue by mperham** [rubygems/rubygems#3145]
If I type `gem install rials` today, rubygems will install something that I don't want; it's very possible I could pwn myself this way.

Ruby today comes with did_you_mean, which can detect typos. I would suggest that Rubygems include a list of the top N gems by downloads and check the requested gem name against this list before installing anything, doubling checking with the user if the name is not in the list but looks similar to an entry in the list.

This might be more appropriate in Bundler, happy to move it there.

**Comment by mperham** [comment]
Oops, dupe of #2840

**Comment by mperham** [comment]
This is separate from #2840, that suggests misspelled commands.  This is more of a security issue because it can lead to the installation of malicious code.

**Comment by bronzdoc** [comment]
What would happen to the people that do want to install the `rials` gem? 🤔

**Comment by mperham** [comment]
You type ‘y’ at the “Do you want to install this?” prompt.

**Comment by indirect** [comment]
I think it's worth pointing out that Ruby comes with "did you mean", but only ever uses it if you try to access something that doesn't exist at all. I both very much understand wishing that RubyGems would correct typos, and worry a lot about a human-maintained list that "demotes" some gems that do actually exist.

I think ultimately I want to stay consistent with other places where Ruby uses "did you mean", and only make suggestions if you try to reference something that doesn't exist (which is how RubyGems currently works).

**Comment by indirect** [comment]
To address the specific issue of malicious code: that's handled on the server-side. We actively remove gems that contain malicious code, and we actively block new gems from being pushed that typo-squat on popular gems. So evaluating this ticket based purely on "it's more of a security issue", I'm going to close this as resolved elsewhere. 👍🏻
