### ISSUE TITLE
Merge bundler repo into rubygems

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#3157]
This is an issue to track the implementation of phases 2 and 3 in https://github.com/rubygems/rfcs/blob/master/text/0003-merge-with-rubygems.md#reference-level-explanation.

Bundler & rubygems will be merged in a monorepo that will live here, at https://github.com/rubygems/rubygems.

The steps to be done involve:

* [x] Integrate the current `bundler` submodule into the rubygems repo, keeping the whole history of commits of the bundler repo. The plan is to use https://x3ro.de/integrating-a-submodule-into-the-parent-repository/.
* [x] Integrate CI's of both repositories. Bundler's current CI configuration needs to be moved to the root of the repo, and only needs to switch the `RGV=master` case to point to the local version of rubygems `RGV=..`. Rubygems CI configuration no longer needs to run bundler's tests.
* [x] Unify `CONTRIBUTING.md` and `CODE_OF_CONDUCT.md` at the root of the repository.
* [x] Transfer issues.
* [x] Transfer PRs from bundler repo.
* [x] Unify PR and issue templates.
* [x] Unify FUNDING.yml.
* [ ] Unify code style.
* [x] Unify welcome bot.
* [x] Fix broken specs (#3404).

After this issue is closed, the release process and "rake task tooling" of each library will still be independent, that can be unified at a later step. For now, we just want to become a monorepo.
 
This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
I created the retired message for the bundler repo: https://github.com/rubygems/bundler/pull/7671

**Comment by hsbt** [comment]
I created the branch with the latest commits of bundle submodule at https://github.com/rubygems/rubygems/tree/rubygems-bundler-submodule-head

**Comment by deivid-rodriguez** [comment]
I updated the issue description with a few more pending tasks.

**Comment by deivid-rodriguez** [comment]
Code style is not yet fully uniform but the other tasks are done, so I'm closing this!
