### ISSUE TITLE
`rubygems/source_local` requires the wrong file

### ISSUE THREAD

**Issue by duckinator** [rubygems/rubygems#3158]
My current problem is `rubygems/source_local` requires _itself_ instead of `rubygems/source/local` before printing a deprecation warning for the entire file.

This has been a problem since 2013, when https://github.com/rubygems/rubygems/commit/49250b3de was committed.

Perhaps it should just be removed, at this point?

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Yeah, nobody complained about it so let's remove it.

It's been 3 years and 1 major version since [we started printing this warning](https://github.com/rubygems/rubygems/commit/29ddda5d00897f6b9f1106c0ba0daaa8089a02d9), so even if this worked as expected, it was time for removing it anyways.
