### ISSUE TITLE
Improving code documentation

### ISSUE THREAD

**Issue by duckinator** [rubygems/rubygems#3159]
The RubyGems codebase lacks documentation in some areas. Let's try to fix that. :slightly_smiling_face: 

This issue is focusing on documenting classes, modules, and methods to help current contributors and make it easier for new contributors.

For discussing documenting how to use RubyGems itself and things of that sort, please open separate issues!

This is also intended as a kind of "meta issue", used mostly for coordination. If you want to discuss documenting a specific part of the codebase at-length, you can [join us on Slack](https://slack.bundler.io/)  or open a new issue about it and @-mention me in the issue.

**If you intend to work on documenting a particular file, leave a comment below saying so and I'll put your GitHub handle by the relevant file.** This helps avoid duplicated effort.

You can see [`lib/rubygems.rb`](https://github.com/rubygems/rubygems/blob/master/lib/rubygems.rb) and [`lib/rubygems/util.rb`](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/util.rb) for some good examples of how to document a class or method.

## Areas To Document

Here is the list of areas that need documentation improvements:

- [x] `lib/rubygems/deprecate.rb` (@duckinator, #4717)
  - [x] Update outdated information: It says it provides a single method, `deprecate`, but it actually provides `deprecated` + `deprecate_command`.
- [ ] `lib/rubygems/ext/builder.rb`
  - [ ] Class/module comment explaining common usage.
  - [ ] Method/function documentation.
- [ ] `lib/rubygems/ext/cmake_builder.rb`
  - [ ] Class/module comment explaining common usage.
  - [ ] Method/function documentation.
- [ ] `lib/rubygems/ext/configure_builder.rb`
  - [ ] Class/module comment explaining common usage.
  - [ ] Method/function documentation.
- [ ] `lib/rubygems/ext/ext_conf_builder.rb`
  - [ ] Class/module comment explaining common usage.
  - [ ] Method/function documentation.
- [ ] `lib/rubygems/ext/rake_builder.rb`
  - [ ] Class/module comment explaining common usage.
  - [ ] Method/function documentation.
- [ ] `lib/rubygems/request/connection_pools.rb`
  - [ ] Class/module comment explaining common usage.
  - [ ] Method/function documentation.
- [ ] `lib/rubygems/request_set/lockfile.rb`
  - [ ] Class/module comment explaining common usage.
  - [ ] Method/function documentation.
- [ ] `lib/rubygems/request_set/lockfile/parser.rb`
  - [ ] Class/module comment explaining common usage.
  - [ ] Method/function documentation.
- [ ] `lib/rubygems/request_set/lockfile/tokenizer.rb`
  - [ ] Class/module comment explaining common usage.
  - [ ] Method/function documentation.
- [ ] `lib/rubygems/resolver/stats.rb`
  - [ ] Class/module comment explaining common usage.
  - [ ] Method/function documentation.
- [ ] `lib/rubygems/bundler_version_finder.rb` (@devraj-kumar)
  - [ ] Class/module comment explaining common usage.
  - [ ] Method/function documentation.
- [ ] `lib/rubygems/psych_tree.rb`
  - [ ] Class/module comment explaining common usage.
  - [ ] Method/function documentation.
- [ ] `lib/rubygems/query_utils.rb`
  - [ ] Class/module comment explaining common usage.
  - [ ] Method/function documentation.
- [ ] `lib/rubygems/request.rb`
  - [ ] Class/module comment explaining common usage.
  - [ ] Method/function documentation.
- [ ] `lib/rubygems/s3_uri_signer.rb`
  - [ ] Class/module comment explaining common usage.
  - [ ] Method/function documentation.
- [ ] `lib/rubygems/uri_parsing.rb`
  - [ ] Class/module comment explaining common usage.
  - [ ] Method/function documentation.
  
- [ ] `lib/rubygems/commands/*.rb`
  - [ ] Class/module comment explaining common usage.
  - [ ] Method/function documentation.
## Miscellaneous notes

<details>
<summary>Files that appear okay</summary>

```
lib/rubygems/core_ext/kernel_gem.rb
lib/rubygems/core_ext/kernel_require.rb
lib/rubygems/core_ext/kernel_warn.rb
lib/rubygems/ext/build_error.rb
lib/rubygems/package/digest_io.rb
lib/rubygems/package/file_source.rb
lib/rubygems/package/io_source.rb
lib/rubygems/package/old.rb
lib/rubygems/package/source.rb
lib/rubygems/package/tar_header.rb
lib/rubygems/package/tar_reader/entry.rb
lib/rubygems/package/tar_reader.rb
lib/rubygems/package/tar_test_case.rb
lib/rubygems/package/tar_writer.rb
lib/rubygems/request/http_pool.rb
lib/rubygems/request/https_pool.rb
lib/rubygems/request_set/gem_dependency_api.rb
lib/rubygems/resolver/activation_request.rb
lib/rubygems/resolver/api_set.rb
lib/rubygems/resolver/api_specification.rb
lib/rubygems/resolver/best_set.rb
lib/rubygems/resolver/composed_set.rb
lib/rubygems/resolver/conflict.rb
lib/rubygems/resolver/current_set.rb
lib/rubygems/resolver/dependency_request.rb
lib/rubygems/resolver/git_set.rb
lib/rubygems/resolver/git_specification.rb
lib/rubygems/resolver/index_set.rb
lib/rubygems/resolver/index_specification.rb
lib/rubygems/resolver/installed_specification.rb
lib/rubygems/resolver/installer_set.rb
lib/rubygems/resolver/local_specification.rb
lib/rubygems/resolver/lock_set.rb
lib/rubygems/resolver/molinillo.rb
lib/rubygems/resolver/requirement_list.rb
lib/rubygems/resolver/set.rb
lib/rubygems/resolver/source_set.rb
lib/rubygems/resolver/specification.rb
lib/rubygems/resolver/spec_specification.rb
lib/rubygems/resolver/vendor_set.rb
lib/rubygems/resolver/vendor_specification.rb
lib/rubygems/security/policies.rb
lib/rubygems/security/policy.rb
lib/rubygems/security/signer.rb
lib/rubygems/security/trust_dir.rb
lib/rubygems/source/git.rb
lib/rubygems/source/installed.rb
lib/rubygems/source/local.rb
lib/rubygems/source/lock.rb
lib/rubygems/source/specific_file.rb
lib/rubygems/source/vendor.rb
lib/rubygems/util/licenses.rb
lib/rubygems/util/list.rb
lib/rubygems/available_set.rb
lib/rubygems/basic_specification.rb
lib/rubygems/command_manager.rb
lib/rubygems/command.rb
lib/rubygems/compatibility.rb
lib/rubygems/config_file.rb
lib/rubygems/defaults.rb
lib/rubygems/dependency_installer.rb
lib/rubygems/dependency_list.rb
lib/rubygems/dependency.rb
lib/rubygems/doctor.rb
lib/rubygems/errors.rb
lib/rubygems/exceptions.rb
lib/rubygems/ext.rb
lib/rubygems/gemcutter_utilities.rb
lib/rubygems/gem_runner.rb
lib/rubygems/indexer.rb
lib/rubygems/install_default_message.rb
lib/rubygems/installer.rb
lib/rubygems/installer_test_case.rb
lib/rubygems/installer_uninstaller_utils.rb
lib/rubygems/install_message.rb
lib/rubygems/install_update_options.rb
lib/rubygems/local_remote_options.rb
lib/rubygems/mock_gem_ui.rb
lib/rubygems/name_tuple.rb
lib/rubygems/package.rb
lib/rubygems/package_task.rb
lib/rubygems/path_support.rb
lib/rubygems/platform.rb
lib/rubygems/psych_additions.rb
lib/rubygems/rdoc.rb
lib/rubygems/remote_fetcher.rb
lib/rubygems/request_set.rb
lib/rubygems/requirement.rb
lib/rubygems/resolver.rb
lib/rubygems/safe_yaml.rb
lib/rubygems/security_option.rb
lib/rubygems/security.rb
lib/rubygems/server.rb
lib/rubygems/source_list.rb
lib/rubygems/source_local.rb
lib/rubygems/source.rb
lib/rubygems/specification_policy.rb
lib/rubygems/specification.rb
lib/rubygems/stub_specification.rb
lib/rubygems/syck_hack.rb
lib/rubygems/test_case.rb
lib/rubygems/test_utilities.rb
lib/rubygems/text.rb
lib/rubygems/uninstaller.rb
lib/rubygems/uri_formatter.rb
lib/rubygems/uri_parser.rb
lib/rubygems/user_interaction.rb
lib/rubygems/util.rb
lib/rubygems/validator.rb
lib/rubygems/version_option.rb
lib/rubygems/version.rb
```

</details>

Not checked:
- `resolver/molinillo/**/*.rb`

**Comment by devraj-kumar** [comment]
I will be looking forward to resolving this issue, I will be starting with ib/rubygems/bundler_version_finder.rb

**Comment by deivid-rodriguez** [comment]
I think this issue is too generic to keep open.

It will always be an ongoing task to have better docs, but we don't need an open ticket for that. Also, the list of classes will likely get out of date and not be updated as we improved things, and it didn't get much traction anyways.

So I'm closing this but always happy to take doc improvements!
