### ISSUE TITLE
Gem retrieval fails with https but succeeds with http

### ISSUE THREAD

**Issue by Andrew-Max** [rubygems/rubygems#3169]
I'm having a problem.

My current problem is when I use bundler to download a gem from rubygems.org, the gem cannot be found if I use 'https://rubygems.org', but succeeds with 'http://rubygems.org'

This issue is related to:

  - [ x] Network problems
  - [ x] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:
```
ruby '2.6.3'
Bundler version 1.17.2
gem : json_sti 0.1.1

```
```
$ gem env version
gem --version : 3.0.3
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
This is very likely a misconfiguration in the client in your machine, so I'll close this. If you still have issues, feel free to reach for help!
