### ISSUE TITLE
Bundler requires all `:path` gems to be in default group

### ISSUE THREAD

**Issue by fzakaria** [rubygems/rubygems#3177]
If you have a Gemfile with a local _path_ Gem such as:

```
group :development, :test do
   gem 'demo', :path => "./ruby-gems/demo"
end
```
Even though the `demo` gem is **not used** in any non-test files; bundler will complain:
```
The path `uri:classloader://warbler-example/ruby-gems/demo` does not exist.
```

This is an issue from running within a JAR using JRuby+ Warbler

I have created a minimal example at: https://github.com/fzakaria/warbler-bundler-jruby-failure/tree/demo-development
(Specifically the _demo-development_ branch)

## Environment
```
jruby 9.1.17.0 (2.3.3) 2018-04-20 d8b1ff9 OpenJDK 64-Bit Server VM 25.232-b09 on 1.8.0_232-b09 +jit [darwin-x86_64]

Darwin MacBook-Pro.localdomain 18.7.0 Darwin Kernel Version 18.7.0: Tue Aug 20 16:57:14 PDT 2019; root:xnu-4903.271.2~2/RELEASE_X86_64 x86_64
```

**Comment by fzakaria** [comment]
Hey @deivid-rodriguez not sure if you had a chance to look ?
I spent a while trying to dig through the Bundler source but couldn't make a lot of sense of it.

There's some dynamic for `:path` dependencies that doesn't play nicely.

**Comment by deivid-rodriguez** [comment]
@fzakaria Sorry for taking this long to get to this. I proposed a solution at #3902. Can you try it and check if it works for you?
