### ISSUE TITLE
Add warnings on bundle update when dependent updates go past --patch or --minor level 

### ISSUE THREAD

**Issue by chrismo** [rubygems/rubygems#3180]
...with an instruction to use --strict if user doesn't want that

Task spawned from rubygems/bundler#4676

**Comment by deivid-rodriguez** [comment]
I don't like this too much, honestly. I think most users don't care about this and will find the warning just annoying. In principle, allowed indirect dependency ranges should be the responsibility of direct dependencies, right?

**Comment by deivid-rodriguez** [comment]
Closing since as I said I'm not a fan of the idea and I received no further feedback on it.
