### ISSUE TITLE
Bundler will not find a gem after adding platform parameter to gem and then removing it

### ISSUE THREAD

**Issue by pavelbulanov** [rubygems/rubygems#3181]
Bundler v1.13.1

Steps to _reproduce_:
1) Add some gem to Gemfile, run "bundle install", gem with specific version added to Gemfile.lock
2) Add some platform (not matching your system) to that exact gem, e.g. adding "platform: :mswin". 
3) Run "bundle install" again. Gemfile.lock is updated, there is no longer gem name with version under GEM section, but it's still in `DEPENDENCIES`list (with no version as expected).
Interestingly, running just "bundle show gem_name" gives the same result - Gemfile.lock is updated even without running 'bundle install'!
4) Remove platform parameter from the gem (assume it was added by mistake), run "bundle install". 

_Result_:
Gem is not restored - Gemfile.lock remains as is, with no gem name under GEM section, and with gem name still present under `Dependencies`. Gem is not factually added in the application with Bundle.require. Re-running bundle install multiple times or manually installing / removing gem doesn't help.
Suppose the issue is that gem name remained under dependencies list in Gemfile.lock.

Interesting, running 'bundle show gem_name' shows the following funny error (mini_racer is my gem):

> "Could not find gem 'mini_racer'.
> Did you mean mini_racer?"

Spelling is exactly the same for both occurrences.

_Expected Result_:
'bundle install" will "re-enable" the gem after platform condition was removed. 

_Workaround_ - if I just remove the gem name from Gemfile completely, run bundle install - Gemfile.lock is updated and gem name is removed from `Dependencies`list. Re-adding gem in Gemfile again will turn it on. Alternatively, manually removing gem name from `Dependencies`list in Gemfile.lock and re-running "bundle install" will also re-enable gem without a need to remove / add it into Gemfile.

**Comment by deivid-rodriguez** [comment]
I'm pretty sure this is fixed in `bundler 2.2.0.rc.2` with all the platform improvements that come with it. Please reopen if it's not.
