### ISSUE TITLE
file permissions of installed files with UMASK=0027

### ISSUE THREAD

**Issue by retroj** [rubygems/rubygems#3182]
Hello,

On my user account, I use UMASK=0027, which means that files I create do not have any permissions on the 'other' category by default.  This causes a problem with bundler, when bundler installs files to my system gems directory with root:root ownership.

{{{
$ ls -la /var/lib/gems/2.3.0
...
drwxr-x---  4 root root 4096 Oct 16 19:01 railties-4.2.5
...
}}}

Gems installed in this way are not accessible by my user account (until I manually change the permissions on the gems directory).  It would be nice if bundler would set the permissions on files that it installs, so that it would work as expected on systems with a configuration like mine.

**Comment by deivid-rodriguez** [comment]
Hi @retroj!

Could you point us to the issues you reported to other language-specific package managers to see their response? I understand your issue, but I'm not sure how this would be a bundler issue, I don't think it messes with `umask`? :thinking:

Maybe your `root`' user's umask has an unexpected value?

**Comment by deivid-rodriguez** [comment]
Actually, there seems to be an issue here, but there's a more specific report at https://github.com/rubygems/rubygems/issues/3224, so I'll close this ticket in favor of that one. Feel free to subscribe to the other ticket for updates :smiley:!
