### ISSUE TITLE
Get CI running on JRuby

### ISSUE THREAD

**Issue by headius** [rubygems/rubygems#3183]
Bundler currently does not run CI on any Ruby implementation except MRI. This resulted in at least one "bug" (#4975) getting introduced that could have been caught in CI. I believe it would be in Bundler's best interest to get CI running on JRuby.

Challenges:
- The specs are not completely green on JRuby. This bug will track the process of making it green.
- The specs rely heavily on launching subprocesses; this will be very slow on JRuby.

This second point is the big challenge. JRuby takes a few seconds to start up for each of the commands run by the specs. Multiply this by hundreds or thousands of commands and the suite takes an incredibly long time. We will need to mitigate this by using some pre-launcher like https://github.com/drip/drip or by running the specs in-process in JRuby.

And here we go...

**Comment by deivid-rodriguez** [comment]
We now have a bare jruby CI, so that's something. It only runs a subset of the specs since running everything for every PR is too slow. Maybe a next step  would be to actually get the full test suite green on `jruby`, and run it daily just like we do with ruby-head, for example.

Of course, fixing the root cause of the slowness is welcomed too.

**Comment by headius** [comment]
The root cause of the slowness is still likely due to launching a new Ruby instance for so many tests.

The first way to mitigate this would be to run the JRuby CI with env `JRUBY_OPTS=--dev`, which should help startup time quite a bit.

If we want to eliminate the startup cost altogether, then we need to look at possibly launching some of these subprocesses as new JRuby instances within the same JVM; that allows us to take advantage of already-optimized JRuby code and largely eliminates all startup time overhead after one or two additional instances.

**Comment by simi** [comment]
@headius can you point me to some code related to your comment (launching new Ruby instance) and also show example of lunching subprocess as new JRuby instance within the same JVM?

**Comment by deivid-rodriguez** [comment]
Worth trying out a CI run with `JRUBY_OPTS=--dev` to see how long the whole thing takes, and how many failures we currently have.

**Comment by headius** [comment]
The main test suite (`rake test`) runs on my system (2017 MBP) in 209s with --dev. There are a number of slower-than-average tests that I assume are launching a JRuby subprocess:

Tests over 1s in length:
```
TestGemExtConfigureBuilder#test_self_build = 1.13 s = .
TestGemSpecification#test_to_ruby_with_rsa_key = 1.36 s = .
TestGemExtRakeBuilder#test_class_build_with_args = 2.95 s = .
TestGemExtRakeBuilder#test_class_build = 3.15 s = .
TestGemExtRakeBuilder#test_class_build_fail = 2.75 s = .
TestGemExtRakeBuilder#test_class_build_no_mkrf_passes_args = 1.42 s = .
TestGem#test_activate_bin_path_in_debug_mode = 1.56 s = .
TestGem#test_default_source_date_epoch_doesnt_change = 1.01 s = .
TestGemInstaller#test_keeps_plugins_up_to_date = 11.17 s = .
TestGemInstaller#test_install_creates_binstub_that_dont_trust_encoding = 2.79 s = .
TestGemInstaller#test_install_extension_dir = 1.54 s = .
TestGemInstaller#test_conflicting_binstubs = 5.84 s = .
TestGemInstaller#test_install_user_extension_dir = 1.74 s = .
TestGemInstaller#test_generate_plugins = 2.85 s = .
TestGemInstaller#test_install_with_no_prior_files = 5.80 s = .
TestGemInstaller#test_install_extension_dir_is_removed_on_reinstall = 3.09 s = .
TestGemInstaller#test_install_creates_binstub_that_prefers_user_installed_gem_to_default = 2.84 s = .
TestGemInstaller#test_install_creates_working_binstub = 2.95 s = .
TestGemInstaller#test_install = 2.83 s = .
TestGemInstaller#test_install_creates_binstub_that_understand_version = 2.81 s = .
TestGemCommandsPristineCommand#test_execute_extensions_explicit = 2.85 s = .
TestGemCommandsPristineCommand#test_execute_with_extension_with_build_args = 2.77 s = .
TestGemCommandsPristineCommand#test_execute_multi_platform = 4.15 s = .
TestGemCommandsPristineCommand#test_execute_no_extension = 1.52 s = .
TestGemRequestSetLockfile#test_to_s_git = 1.20 s = .
TestGemCommandsUninstallCommand#test_execute_prerelease = 2.82 s = .
TestGemExtExtConfBuilder#test_class_build_extconf_fail = 1.44 s = .
TestGemExtExtConfBuilder#test_class_build_extconf_success_without_warning = 1.53 s = .
TestGemExtExtConfBuilder#test_class_build_unconventional = 5.70 s = .
TestGemCommandsUpdateCommand#test_execute_system_specific_older_than_3_2_removes_plugins_dir = 1.13 s = .
TestGemCommandsUpdateCommand#test_execute_system = 1.15 s = .
TestGemCommandsUpdateCommand#test_execute_system_specific_newer_than_or_equal_to_3_2_leaves_plugins_dir_alone = 1.04 s = .
TestGemCommandsUpdateCommand#test_execute_system_multiple = 1.07 s = .
TestGemCommandsUpdateCommand#test_execute_system_specifically_to_latest_version = 1.06 s = .
TestGemCommandsUpdateCommand#test_execute_system_silent = 1.06 s = .
TestGemCommandsUpdateCommand#test_execute_system_specific = 1.06 s = .
TestGemDependencyInstaller#test_install_dependency_existing_extension = 2.99 s = .
TestProjectSanity#test_require_rubygems_package = 2.07 s = .
TestProjectSanity#test_manifest_is_up_to_date = 2.93 s = .
TestGemUninstaller#test_uninstall_extension = 1.54 s = .
TestGemRequire#test_no_other_behavioral_changes_with_warn = 2.25 s = .
TestGemRequire#test_no_kernel_require_in_warn_with_uplevel = 2.42 s = .
TestGemRequire#test_no_other_behavioral_changes_with_Kernel_warn = 2.27 s = .
TestGemRequire#test_no_kernel_require_in_Kernel_warn_with_uplevel = 2.33 s = .
TestGemRequire#test_realworld_upgraded_default_gem = 1.37 s = .
TestGemRequire#test_normal_gems_with_overridden_load_error_message = 1.52 s = .
TestKernel#test_gem_failing_inside_require_doesnt_cause_double_exceptions = 1.41 s = .
TestGemSourceGit#test_checkout_submodules = 1.00 s = .
TestGemRequestConnectionPool#test_thread_waits_for_connection = 1.02 s = .
```

There 49 tests account for 118 seconds of test time, or over half of the run. I have not dug into these to understand what they are doing.

**Comment by headius** [comment]
The long documentation for running an embedded JRuby focuses mostly on doing so from Java:

https://github.com/jruby/jruby/wiki/RedBridge

However you can just launch a new JRuby instance at any time from Ruby code using the same logic:

```ruby
require 'jruby'

puts "JRuby instance: #{JRuby.runtime}"

java_import org.jruby.embed.ScriptingContainer
java_import org.jruby.embed.LocalContextScope

container = ScriptingContainer.new(LocalContextScope::SINGLETHREAD)
container.run_scriptlet('require "jruby"; puts "JRuby instance: #{JRuby.runtime}"')
```

This code creates a new JRuby instance (as a `ScriptingContainer`) that is expected to be used on its own (`SINGLETHREAD`) and then feeds some code to it. `JRuby.runtime` shows the current JRuby instance, and you can see they're different from the output:

```
$ jruby subruby.rb 
JRuby instance: org.jruby.Ruby@15aeb7ab
JRuby instance: org.jruby.Ruby@345965f2
```

There are other ways to set up and configure the container, like giving it specific streams to use for stdio and setting ARGV and such. Some timing of starting up instances this way, compared to running subprocesses:

```
[] ~/projects/rubygems $ JRUBY_OPTS=--dev jruby subruby2.rb 
Launch process ten times:
  0.030000   0.000000   1.940000 (  1.282251)
  0.000000   0.000000   1.900000 (  1.274600)
  0.010000   0.010000   1.940000 (  1.287643)
  0.000000   0.000000   2.040000 (  1.360391)
  0.010000   0.000000   1.930000 (  1.293253)
  0.000000   0.000000   1.910000 (  1.280154)
  0.000000   0.000000   1.990000 (  1.325040)
  0.010000   0.010000   1.920000 (  1.278281)
  0.000000   0.000000   1.940000 (  1.313546)
  0.000000   0.000000   1.920000 (  1.283738)
Launch in-process times:
  0.300000   0.030000   0.330000 (  0.215841)
  0.300000   0.030000   0.330000 (  0.170693)
  0.200000   0.010000   0.210000 (  0.133376)
  0.300000   0.030000   0.330000 (  0.155757)
  0.180000   0.010000   0.190000 (  0.125120)
  0.170000   0.010000   0.180000 (  0.119609)
  0.300000   0.040000   0.340000 (  0.157544)
  0.150000   0.010000   0.160000 (  0.119620)
  0.130000   0.000000   0.130000 (  0.115010)
  0.130000   0.010000   0.140000 (  0.114578)

[] ~/projects/rubygems $ cat subruby2.rb 
require 'benchmark'

java_import org.jruby.embed.ScriptingContainer
java_import org.jruby.embed.LocalContextScope

puts "Launch process ten times:"

10.times do
  puts Benchmark.measure {
    `jruby -e 1`
  }
end

puts "Launch in-process times:"

10.times do
  puts Benchmark.measure {
    container = ScriptingContainer.new(LocalContextScope::SINGLETHREAD)
    container.run_scriptlet('1')
  }
end
```

**Comment by deivid-rodriguez** [comment]
@headius I should've been more clear. Rubygems tests are fast enough and we run them on every PR and make sure they are all green before merging anything (we still have some jruby specific skips we should have a look at, but still we're pretty good there). The problem is bundler specs, which heavily launch ruby processes from inside ruby and are very slow on jruby (last time we checked CI, it was ~4h).

**Comment by headius** [comment]
@deivid-rodriguez I will have a look and see if I can find any easy improvements.

**Comment by headius** [comment]
Ok, I see how these are being launched separately. Mostly it seems like this is used to run a bundler command line and then check the results, yes?

I believe most of these commands could be run in-process using code similar to what I showed above. Instead of building a command line and launching it directly, the in-process logic would instead build up a set of arguments, boot up another JRuby instance with those arguments and appropriate IO streams to capture the output, and then execute the bundle command that's requested.

There are a few complications that might arise:

* Running in-process obviously can't use a different cwd. We simulate cwd on a per-runtime basis, but there's bound to be some edge cases that expect the running subprocess to actually have that cwd.
* Clearly if sudo is needed that will still require a spawn.

**Comment by headius** [comment]
The problem is bigger than I thought. For some of these specs, `bundle` gets launched via a subprocess numerous times, such as to set and then get a config variable. It seems like a very large number of these commands should run ok in-process.

I have a partially-working prototype using an in-process JRuby instance to run an isolated command line. It works for many cases, but more complex command lines start to trip up my naive proxy. I can say that it runs much faster, but unfortunately so many specs fail it's hard to really quantify the improvement.

Isolating a test run to commands/config, seed 8371.

Baseline master run with no additional flags took 7m24s on my machine. There were two failures, 42 examples.

The same build with env `JRUBY_OPTS=--dev` took 4m48s, with the same two failures.

A hacked version of the build to run in-process, combined with --dev, took only 1m55s, but failed 37 out of the 42 examples. It does appear to be actually running the commands, but some env or path or arg is not propagating properly.

I provide the current hacky patch here: https://gist.github.com/headius/0c6939012466c2d34e9e9c14e85009c8

Exit codes are not being mapped properly, and I am taking some liberties with the environment and argument strings, but it's on its way to working. This may be worth doing "right" and making a utility library that matches JRuby's command-line `main` logic... something that can take your command + streams and fully simulate a separate process using a new JRuby instance.

**Comment by deivid-rodriguez** [comment]
Yes, specs should be ok to run in process, but the previous attempt to implement that failed (see https://github.com/rubygems/bundler/pull/4796). For now I'm going to try run the full suite with `JRUBY_OPTS=--dev`  and see how long it takes. As I said previously, maybe we can consider a daily run for now.

**Comment by deivid-rodriguez** [comment]
We do have a CI running on JRuby with a very minimal set of specs. But things seem quite stable now and when we do fix issues specific to JRuby, we add extra specs to this minimal sets.

I think this is good enough for now, so I will close this ticket. Any improvements in speed ups of our JRuby suite will be super welcome, specially if they allow us to run the whole test suite!
