### ISSUE TITLE
bundle check complains that it can't write to the Gemfile.lock when bundle is frozen but no changes are required

### ISSUE THREAD

**Issue by donnoman** [rubygems/rubygems#3184]
we were having a perplexing problem on our build systems because we wanted to enforce --deployment to catch Gemfile.lock errors before they reach production.

our build script had this line

```
bundle check --path $SHARED_BUNDLE_PATH || bundle install --jobs=1 --retry=3 --deployment --path $SHARED_BUNDLE_PATH
```

We do this because the build is started with the cache of a previous build and a full bundle install is not always necessary so we short-circuit it with a bundle check.

However, we were ending up with dirty Gemfile.locks on the build system. bundle install with --deployment didn't complain locally 

What I ended up figuring out is that it was the `bundle check` that is dirtying the Gemfile.lock by adding a gem in a different location.

I then removed --deployment from my local bundle install and it finally dirtied the Gemfile.lock but it wouldn't with --deployment.

Why does bundle check write to the Gemfile.lock at all?  Thats not bundle check's job.

bundle check doesn't support --frozen nor --deployment from the cli

However if we do this:

```
    bundle config --local FROZEN 1
    bundle check --path $SHARED_BUNDLE_PATH || bundle install --jobs=1 --retry=3 --deployment --path $SHARED_BUNDLE_PATH
```

Then bundle check will correctly refuse to write the Gemfile.lock and it will complain that bundle hasn't been satisfied and abort.

However, during the build now bundle check complains that it can't write to the Gemfile.lock even when everything is right.

```
+ bundle config --local FROZEN 1
You are replacing the current local value of FROZEN, which is currently nil
+ bundle check --path /home/ubuntu/app/vendor/bundle
Cannot write a changed lockfile while frozen.
The Gemfile's dependencies are satisfied
```

My preference would be that bundle check does not write at all to the Gemfile.lock.

If it must then we should be able to pass it --frozen and/or --deployment to get it to not write to the Gemfile.lock and exit with an error code if the bundle hasn't been satisfied.

```
ruby --version: ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-linux]
gem --version: 2.6.3
bundler --version: Bundler version 1.11.2
```

**Comment by deivid-rodriguez** [comment]
It sounds like this was no longer an issue?
