### ISSUE TITLE
Conservative update flags don't work with gemspecs?

### ISSUE THREAD

**Issue by chrismo** [rubygems/rubygems#3188]
Can't believe I didn't run across this previously ... but it doesn't appear to be working for me today. Need to make a reproducible case.

Seems to be consistent with both `outdated` and `update`

**Comment by deivid-rodriguez** [comment]
At some point I added the `status: confirmed` flag, I guess because I confirmed this myself, but I can no longer see any issues here. @chrismo Do you have a reproducible example?

**Comment by deivid-rodriguez** [comment]
I'll close since there was no further feedback.
