### ISSUE TITLE
bundle check should fail when missing git dependency after bundle package --all

### ISSUE THREAD

**Issue by grosser** [rubygems/rubygems#3189]
```
bundle package --all
rm -rf vendor/cache/something-sha
bundle check
The Gemfile's dependencies are satisfied
```

expected behavior: `bundle check` should read bundle config and tell me that `something-sha` is missing

**Comment by deivid-rodriguez** [comment]
I agree that this is not a bug.

The explanation was given by @indirect in https://github.com/rubygems/rubygems/issues/3189#issuecomment-232214168. `bundle check` checks whether the gems needed by your bundle are properly installed. By removing a folder in `vendor/cache` you're only invalidating the cache, but that doesn't change the fact that the gem is still properly installed.

@grosser I believe you are correct though, in that `bundle exec` should work if `bundle check` succeeds. But that's a different issue, probably https://github.com/rubygems/rubygems/issues/3204?

**Comment by grosser** [comment]
yes, with #3204 fixed this issue would be fixed too, both issues are
different approaches to fixing a similar behavior problem

**Comment by deivid-rodriguez** [comment]
Sure!

Since the end user problem is the same, and I prefer to fix it by making `bundle exec` succeed rather than by making `bundle check` fail, I'll go ahead and close this ticket :+1:.
