### ISSUE TITLE
Issues with concurrent bundle installs with shared gem cache

### ISSUE THREAD

**Issue by stefansedich** [rubygems/rubygems#3191]
I am attempting to use a shared gem cache with a docker-compose setup, a sample project is available here: https://github.com/stefansedich/bundle-test which easily replicates the issue by simply running `run.sh`.

The error is consistent and one of the two containers will fail to compile the native extensions for in this case the pg gem I assume due to the concurrent installs attempting to create the Makefile.

What is the best way to handle this scenario, my current solution is to wrap my bundle install in a script that will use flock to limit concurrent installs.

**Comment by deivid-rodriguez** [comment]
This was apparently fixed by https://github.com/rubygems/bundler/pull/5852, but never closed.
