### ISSUE TITLE
`bundle check --strict` or `bundle check --deployment`?

### ISSUE THREAD

**Issue by gondalez** [rubygems/rubygems#3192]
It would be nice to be able to check in CI that a `bundle --deployment` can succeed later.
This would give early feedback if the Gemfile.lock was not updated correctly, for example.

I'm thinking something that validates the first two items listed on the [Deployment Mode](http://bundler.io/v1.12/man/bundle-install.1.html#DEPLOYMENT-MODE) docs and returns the relevant message, error code.

Am I correct in assuming bundle check doesn't do this already?

Thanks for bundler in general btw :)

**Comment by deivid-rodriguez** [comment]
I'm going to close this ticket in favour of #3223, since they request the same thing.
