### ISSUE TITLE
Add public_api.md file

### ISSUE THREAD

**Issue by segiddins** [rubygems/rubygems#3196]
Let's do this for 2.0 --
public gemfile methods, public Bundler. methods, inline gemfiles, CLI, plugin API module, and -rbundler/setup

**Comment by deivid-rodriguez** [comment]
This is essentially what I did in #7964. Should I move the contents of that PR to a `public_api.md` file and link to it, or do you think what we got there is good enough? I don't mind either way.

**Comment by deivid-rodriguez** [comment]
Let's call what we have now enough.
