### ISSUE TITLE
Warn if the ruby version found on the path doesn't match the one Bundler was run with

### ISSUE THREAD

**Issue by lynncyrin** [rubygems/rubygems#3197]
_From @TimMoore on October 15, 2014 3:53_

A lot of people run into problems because they have installed Bundler under the system Ruby and not whatever one they have selected with rvm/rbenv/chruby/whatever.

Because gems installed under the system Ruby usually have executables on the default PATH, this often results in Bundler being run with a version of Ruby that is not what the user expects, causing it to install gems in the wrong place, complain about a mis-matched version, etc.

We could make `bundle install` warn about a version mismatch. Good idea or bad idea?

_Copied from original issue: bundler/bundler-features#66_

**Comment by deivid-rodriguez** [comment]
I've never seen this issue in real life since I maintain bundler, so I think it migth've been fixed either in rubygems/bundler or in version managers. So I'm closing this.
