### ISSUE TITLE
Gem in gemspec without ruby platform version is resolved to a wrong platform

### ISSUE THREAD

**Issue by toy** [rubygems/rubygems#3200]
I've stumbled upon an issue with using bundler for developing a gem that has a dependency on `sys-proctable` gem. The issue seems to be caused by two characteristics of `sys-proctable` gem: it has only platform specific versions and two of them (darwin and freebsd) have additional dependency on ffi gem. I was able to reproduce the behaviour on freebsd (10.3) and osx (darwin 16). 

Given `Gemfile`:
```ruby
source 'https://rubygems.org'
gemspec
```
and `test.gemspec`:
```ruby
Gem::Specification.new do |s|
  s.name        = 'test'
  s.version     = '1.0.0'
  s.summary     = 'test summary'
  s.authors     = ['Max Mustermann']
  s.add_dependency 'sys-proctable', '~> 1.0'
end
```
and running `bundle` on freebsd, produces:
```
Fetching gem metadata from https://rubygems.org/.........
Fetching version metadata from https://rubygems.org/.
Resolving dependencies...
Unable to use the platform-specific (universal-freebsd) version of sys-proctable (1.1.5) because it has different dependencies from the universal-aix5 version. To use the platform-specific version of the gem, run `bundle config specific_platform true` and install again.
Using bundler 1.15.4
Fetching sys-proctable 1.1.5 (universal-aix5)
Installing sys-proctable 1.1.5 (universal-aix5)
Using test 1.0.0 from source at `.`
Bundle complete! 1 Gemfile dependency, 3 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

Running `bundle config specific_platform true`, removing the `sys-proctable` gem from the system and repeating `bundle` will remove the warning, but will still fetch the `universal-aix5` platform specific gem.

**Comment by deivid-rodriguez** [comment]
Hello! :wave: :wave: 

I run Samuel's specs and it passes now! So it sounds that we might've fixed this with the recent multiplatform improvements! :tada: 

@toy Could you verify that this is now working fine?

**Comment by toy** [comment]
@deivid-rodriguez Using bundler 2.2.0.rc.2 if I change the dependency to `s.add_dependency 'sys-proctable', '~> 1.1.0'` (as sys-proctable `1.2.x` doesn't have platform specific versions) I still see the warning and universal-aix5 version is installed.

**Comment by deivid-rodriguez** [comment]
Interesting, I guess the issue doesn't repro with that spec after all. It does work if you set `specific_platform` setting as suggested, right?

**Comment by toy** [comment]
Setting the `specific_platform` makes it get and lock on right platform gem.
It is even a bit easier to reproduce than in my original post, given `Gemfile`:
```ruby
source 'https://rubygems.org'
gemspec
```
and `test.gemspec`:
```ruby
Gem::Specification.new do |s|
  s.name        = 'test'
  s.version     = '1.0.0'
  s.summary     = 'test summary'
  s.authors     = ['Max Mustermann']
  s.add_dependency 'sys-proctable', '~> 1.1.0'
end
```
and running bundle on osx will contain in the output:
```
Unable to use the platform-specific (universal-darwin) version of sys-proctable (1.1.5) because it has different dependencies from the universal-aix-5 version. To use the platform-specific version of the gem, run `bundle config set specific_platform true` and install again.
Using bundler 2.2.0.rc.2
Using sys-proctable 1.1.5 (universal-aix-5)
```
It is enough to delete `Gemfile.lock` and to run:
```shell
bundle config specific_platform true
bundle
```
To lock on the right gem.

It may be important that sys-proctable doesn't have version 1.1.5 with platform ruby.

**Comment by deivid-rodriguez** [comment]
Great! The plan is currently to [remove the `specific_platform` setting and enable it by default](https://github.com/rubygems/rubygems/pull/4015). So I guess this can be closed once we do that?
