### ISSUE TITLE
`bundle install` fails when exec'd from a process the uses bundler after a git ref has changed

### ISSUE THREAD

**Issue by metcalf** [rubygems/rubygems#3205]
To reproduce:
* Start a Ruby process that calls `Bundler.setup`.
* Update a git reference in the Gemfile to a value that isn't yet checked out.
* Exec a process from the original Ruby process that calls `bundle install`.
* It fails because the `RUBYOPT='-rbundler/setup'` environment variable causes
  a failure in `Bundler.setup` before the install can run. 

I believe this behavior is specific to git sources since they validate the repo when just loading at:
https://github.com/bundler/bundler/blob/v1.15.4/lib/bundler/source/git.rb#L200-L205

I wrote some scripts to reproduce this bug here:
https://github.com/metcalf/bundler-git-reexec-bug

This bit us in one of our developer tools at Stripe. We have a tool for running services in development that automatically reloads itself in development when relevant files change. That tool handles all of the necessary Bundler commands, but fails under the described condition if we don't clear out `RUBYOPT` before re-execing.

**Comment by jeromedalbert** [comment]
@metcalf Can you confirm this is still an issue? If so, have you tried segiddins's suggestion of using `Bundler.with_original_env { ... }`?

**Comment by metcalf** [comment]
Sorry, I'm not with Stripe anymore and haven't worked with Ruby since then. Feel free to close if you don't think there's value in investigating.

**Comment by jeromedalbert** [comment]
No problem! Since the issue and the possible fix cannot be confirmed or disproved by metcalf any more, I think the issue can be closed.

**Comment by deivid-rodriguez** [comment]
Yeah, and I think the `Bundler.with_original_env` suggestion fixes this kind of issue anyways. Closing!
