### ISSUE TITLE
bundle install asks for sudo password over and over again on windows subsystem

### ISSUE THREAD

**Issue by manuel-mauky** [rubygems/rubygems#3206]
I'm trying to get a ruby application (jekyll) to work and in this process I need to run `bundle install`. 
This asks me for my sudo password which is fine for me. However, It does so over and over again. After entering my password the 10th time I get the feeling that this is not the intended behavior. 

I'm using a Windows 10 computer with Linux/Ubuntu Subsystem. Maybe this is the reason?

**Comment by akostadinov** [comment]
Why can't `bundler` just install under user gem directory like `gem` does? Banging my head over it at the moment. In the past it did so.

**Comment by madprops** [comment]
This is still happening.

Bundler version 2.3.23

Also ctrl+c to quit it, shows something about sudo afterwards, not clean quit.

**Comment by deivid-rodriguez** [comment]
This will be fixed in Bundler 2.4.0, we hope to release it in about a month.
