### ISSUE TITLE
bundle package --all-platforms ignores BUNDLE_WITHOUT

### ISSUE THREAD

**Issue by loewenstein** [rubygems/rubygems#3207]
Steps to reproduce:
1. export BUNDLE_WITHOUT="development:test"
1. execute `bundle package --all-platforms`

Expected:
- vendor cache does _not_ contain rspec, etc.

Actual:
- vendor cache _does_ contain development and test dependencies like rspec and rake.

**Comment by deivid-rodriguez** [comment]
I think this was fixed by https://github.com/rubygems/bundler/pull/6113, released with bundler 2.1.4. Could you check @voelzmo?

**Comment by voelzmo** [comment]
In the meanwhile I don't have a project anymore that uses this kind of setup, sorry I can't provide valuable feedback here anymore. TBQH I had absolutely forgotten and given up on this one.

**Comment by deivid-rodriguez** [comment]
Thanks for getting back @voelzmo, that's completely understandable.

I'm pretty sure this was fixed, so I'll close this. @loewenstein if you can still repro using newer bundler versions feel free to reopen!
