### ISSUE TITLE
Non-deterministic install of json gem on Ruby 2.4.3p205 / bundler 1.16.1

### ISSUE THREAD

**Issue by Iristyle** [rubygems/rubygems#3211]
I'm seeing some unexpected behavior with the `json` gem under Ruby 2.4 on Windows / AppVeyor.

Given a project with a `Gemfile` that explicitly references an unversioned `json` dependency, but also transitively depends on `json` from an excluded gem group `system_tests` (`beaker` -> `beaker-aws` -> `aws-sdk-v1` -> `json ~> 1.4`), I've observed divergent behavior that I don't understand.

Given the same `Gemfile` / `1.16.1` bundler version / `2.4.3` Ruby runtime version / dependency hierarchy, one run fetches, compiles and installs the older `json 1.8.6` as expected. The other run does not. (Note that the code does have different SHAs, but the only difference is that one branch contains an additional `bundle show json` in the `appveyor.yml`). The bundle command run is `bundle install --jobs 4 --retry 2 --without system_tests`. The `Gemfile` in use is at the end of this report.

I have a gist diff'ing the two runs at https://gist.github.com/Iristyle/154ba00d4c9e96027a645ac7f50df78b#file-bundler-appv-diff

* The "YESTERDAY 2.4 x64" run is against commit https://github.com/puppetlabs/puppetlabs-scheduled_task/commits/0a203bea3249698c0995515f7016ab42615cc049
    * The complete run output is available at https://ci.appveyor.com/project/puppetlabs/puppetlabs-scheduled-task/build/1.1.x.143/job/pfae70sfa1kdv8cg
    * Note that it includes "Fetching json 1.8.6 / Installing json 1.8.6 with native extensions"
    * Also note that as a result, `bundle exec ruby -e 'require \"json\"; puts \"bundled json version: #{JSON::VERSION}\"'` emits `bundled json version: 1.8.6`
    * And `gem list` includes `json (default: 2.0.4, 1.8.6)`
    * This branch does not contain the `bundle show json` command but presumably we'd see the path to the 1.8.6 gem like `C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/json-1.8.6`
    
* The "TODAY 2.4 x64" run is against commit https://github.com/puppetlabs/puppetlabs-scheduled_task/commits/f011d8a6ae782317cae790494d5e03b57fe55c3a
    * The complete run output is available at https://ci.appveyor.com/project/puppetlabs/puppetlabs-scheduled-task/build/1.1.x.150/job/posetp03ctx267a5
    * Note that it does not fetch / build json gem
    * Also note that as a result, `bundle exec ruby -e 'require \"json\"; puts \"bundled json version: #{JSON::VERSION}\"'` emits `bundled json version: 2.0.4`
    * And `gem list` includes `json (default: 2.0.4)`
    * `bundle show json` returns `C:/Ruby24-x64/lib/ruby/gems/2.4.0/gems/multi_json-1.13.1` as there is no `json` gem in the bundle
    * Also of note is that `2.0.4` doesn't satisfy the transitive dependency for `~> 1.4` from `aws-sdk-v1` - but this dependency is, as mentioned, courtesy of an excluded gem group.

I was trying to document some Bundler behaviors in a chart at https://gist.github.com/Iristyle/8a2214a6dd5aa709ba2a1abd32b4eacd while I ran across this inconsistency.

My understanding could be wrong, but I've always understood that Bundler would use excluded gem groups in the dependency calculation in the event the group was included again, so that a new gemset didn't have to be downloaded. That would explain `json 1.8.6` being downloaded and built, despite its group being excluded with `--without`. Even if that assumption is not correct, I would expect multiple runs of the same code to install the same gems, so what I've observed is surprising.

#### Gemfile

```ruby
#This file is generated by ModuleSync, do not edit.

source ENV['GEM_SOURCE'] || "https://rubygems.org"

# Determines what type of gem is requested based on place_or_version.
def gem_type(place_or_version)
  if place_or_version =~ /^git:/
    :git
  elsif place_or_version =~ /^file:/
    :file
  else
    :gem
  end
end

# Find a location or specific version for a gem. place_or_version can be a
# version, which is most often used. It can also be git, which is specified as
# `git://somewhere.git#branch`. You can also use a file source location, which
# is specified as `file://some/location/on/disk`.
def location_for(place_or_version, fake_version = nil)
  if place_or_version =~ /^(git[:@][^#]*)#(.*)/
    [fake_version, { :git => $1, :branch => $2, :require => false }].compact
  elsif place_or_version =~ /^file:\/\/(.*)/
    ['>= 0', { :path => File.expand_path($1), :require => false }]
  else
    [place_or_version, { :require => false }]
  end
end

# Used for gem conditionals
ruby_version_segments = Gem::Version.new(RUBY_VERSION.dup).segments
minor_version = "#{ruby_version_segments[0]}.#{ruby_version_segments[1]}"

# The following gems are not included by default as they require DevKit on Windows.
# You should probably include them in a Gemfile.local or a ~/.gemfile
#gem 'pry' #this may already be included in the gemfile
#gem 'pry-stack_explorer', :require => false
#if RUBY_VERSION =~ /^2/
#  gem 'pry-byebug'
#else
#  gem 'pry-debugger'
#end

group :development do
  gem "puppet-module-posix-default-r#{minor_version}",    :require => false, :platforms => "ruby"
  gem "puppet-module-win-default-r#{minor_version}",      :require => false, :platforms => ["mswin", "mingw", "x64_mingw"]
  gem "puppet-module-posix-dev-r#{minor_version}",        :require => false, :platforms => "ruby"
  gem "puppet-module-win-dev-r#{minor_version}", '0.0.7', :require => false, :platforms => ["mswin", "mingw", "x64_mingw"]
  gem "json_pure", '<= 2.0.1',                            :require => false if Gem::Version.new(RUBY_VERSION.dup) < Gem::Version.new('2.0.0')
  gem "fast_gettext", '1.1.0',                            :require => false if Gem::Version.new(RUBY_VERSION.dup) < Gem::Version.new('2.1.0')
  gem "fast_gettext",                                     :require => false if Gem::Version.new(RUBY_VERSION.dup) >= Gem::Version.new('2.1.0')
end

group :system_tests do
  gem "puppet-module-posix-system-r#{minor_version}",                            :require => false, :platforms => "ruby"
  gem "puppet-module-win-system-r#{minor_version}",                              :require => false, :platforms => ["mswin", "mingw", "x64_mingw"]
  gem "beaker", *location_for(ENV['BEAKER_VERSION'] || '>= 3')
  gem "beaker-pe",                                                               :require => false
  gem "beaker-rspec", *location_for(ENV['BEAKER_RSPEC_VERSION'])
  gem "beaker-hostgenerator", *location_for(ENV['BEAKER_HOSTGENERATOR_VERSION'])
  gem "beaker-abs", *location_for(ENV['BEAKER_ABS_VERSION'] || '~> 0.1')
  gem "puppet-blacksmith", '~> 3.4',                                             :require => false
  gem "beaker-testmode_switcher", '<= 0.2.0',                                    :require => false
  gem "master_manipulator",                                                      :require => false
end

gem 'puppet', *location_for(ENV['PUPPET_GEM_VERSION'])
gem 'json'

# Only explicitly specify Facter/Hiera if a version has been specified.
# Otherwise it can lead to strange bundler behavior. If you are seeing weird
# gem resolution behavior, try setting `DEBUG_RESOLVER` environment variable
# to `1` and then run bundle install.
gem 'facter', *location_for(ENV['FACTER_GEM_VERSION']) if ENV['FACTER_GEM_VERSION']
gem 'hiera', *location_for(ENV['HIERA_GEM_VERSION']) if ENV['HIERA_GEM_VERSION']

# Evaluate Gemfile.local if it exists
if File.exists? "#{__FILE__}.local"
  eval(File.read("#{__FILE__}.local"), binding)
end

# Evaluate ~/.gemfile if it exists
if File.exists?(File.join(Dir.home, '.gemfile'))
  eval(File.read(File.join(Dir.home, '.gemfile')), binding)
end

# vim:ft=ruby
```

**Comment by deivid-rodriguez** [comment]
Hi @Iristyle. I'm not sure whether this is relevant to you anymore but I _think_ this should be fixed in newer bundler versions. Can you still repro this on bundler 2.1.4?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback, feel free to reopen if you can repro this on the latest bundler.
