### ISSUE TITLE
Unable to find a spec satisfying tzinfo-data 

### ISSUE THREAD

**Issue by PlanetDyna** [rubygems/rubygems#3212]
Hello folks,

I haven't used Ruby on Rails until now and want to clone an existing project from a web server. When I execute the command "bundler exec rails server", I get the following error message:

> C:\Sites\deploy\statusqoin\curent>bundler exec rails server
> C:/RailsInstaller/Ruby2.3.3/lib/ruby/gems/2.3.0/gems/bundler-1.16.1/lib/bundler/spec_set.rb:40:in `block in for': Unable to find a spec satisfying tzinfo-data (>= 0) in the set. Perhaps the lockfile is corrupted? (RuntimeError)

You know that mistake?

Best regards
PlanetDyna

**Comment by deivid-rodriguez** [comment]
I think this should just work without modifications on bundler 2.2.0.rc.1. Could someone confirm?

**Comment by deivid-rodriguez** [comment]
I'll assume this is fixed now.
