### ISSUE TITLE
Hook mechanism for completion of Bundler.require

### ISSUE THREAD

**Issue by logiclrd** [rubygems/rubygems#3216]
I'd like to add a mechanism to permit a Gem to register a block to be executed automatically once Bundler's Runtime has completed its `require` pass. I propose adding instance methods to Runtime and class methods to Bundler that would forward to the Bundler class's Runtime (Bundler.load) for this.
1. Code in a Gem would use syntax such as:
   
   ```
   Bundler.when_require_complete do
     # final initialization code here
   end
   ```
2. `Runtime.when_require_complete` would stash the provided block for later execution.
3. `Runtime.require` would, upon completion of its loop through the list of dependencies, call each registered block.

Thoughts that occur to me:
1. Does Bundler need to be threadsafe at all? What happens if two threads call `require` on the same Runtime object simultaneously? If that is a situation that currently works, then presumably I'll need to wrap accesses to the list of `when_require_complete` blocks in a Mutex.
2. If Bundler is called multiple times, of course the second invocation's `require` calls, if pointed at the same Ruby files, won't actually run any code. So, if we assume that the finalization code might need to run again if the loadout of Gems changes, the callback handlers need to persist from one call to `Runtime.require` to the next.

If this sort of functionality is likely to be approved by Bundler's maintainers, then I'll go ahead and make a pull request for them. :-)

Rationale:

We have a suite of Gems that tie into a common configuration subsystem, which is defined in its own Gem. Each Gem needs to add its embedded configuration directory to a central list before the configuration subsystem initializes itself and pulls in all of the values, based on order of precedence. Right now, we have no easy way to ensure that the configuration subsystem always initializes _after_ all of the other Gems have had a chance to add their directories to the list. One approach we've tried is to place the variable initialization into the root file for the Gem that handles the configuration, and then arranging things so that it is the last Gem that `Bundler.require` brings in, but this has hit a snag with a Gem that requires a specific version (or newer) of the Gem that handles the configuration. Because it declares it as a dependency, that guarantees that the configuration Gem gets pulled in _before_ this other Gem that wants to add to the configuration. We want to avoid having to explicitly initialize the configuration mechanism in every file that uses it -- there are hundreds of locations maintained by dozens of different teams.

Therefore, having the ability to register a block with Bundler to be automatically executed when the Runtime completes its `require` pass is a convenient mechanism to allow each of the Gems specified in the Gemfile (and brought in via dependencies) to initialize, and _then_ use the configuration state data those initializations have built up to fire up the configuration subsystem.

**Comment by deivid-rodriguez** [comment]
Sorry for being late to the party. I'm not sure I understand the original rationale for this feature explained at ttps://github.com/rubygems/rubygems/issues/3216#issue-581051650. Should this configuration system "configure itself", or should this be done by end users? The rationale explains the following

> We want to avoid having to explicitly initialize the configuration mechanism in every file that uses it -- there are hundreds of locations maintained by dozens of different teams.

This actually seems like a better approach to me in principle? If this is a code sharing issue, then maybe they could extract a `company-configuration` gem that setups the common configuration and let the different teams use it?

I'm not saying that we should not do this, or that this is not a valid use case, just want to make sure I understand it.

**Comment by logiclrd** [comment]
Well, so much time passed over the course of this issue that the company migrated entirely away from Ruby code for its build system to Team Foundation Server, then migrated from that to Azure DevOps, then some time later ultimately laid me off to boot. So, while it is absolutely fantastic that, in the end, the use case I had for this got covered, I am no longer in a position to actually make use of it. :-( But, as evidenced by at least one other comment in the discussion, we were not the only ones for whom such a feature plugs an important gap.

@deivid-rodriguez It appears that an actual working, tested implementation of the proposed feature was in fact merged into the main line 2 weeks ago, at which point this issue was also closed. So unless you're proposing _removing_ the feature, it would appear to be a _fait accompli_.

**Comment by deivid-rodriguez** [comment]
@logiclrd Thanks for sharing your context! And you're right, I should've probably commented on the merged PR instead. We did merge the feature but I want to make sure there's a good use case for doing this before I actually release it.

Happy to hear other use cases then, maybe @nestor-custodio or someone else can share their input!
