### ISSUE TITLE
ThreadError can't create Thread: Resource temporarily unavailable

### ISSUE THREAD

**Issue by stalker37** [rubygems/rubygems#3217]
Debian wheezy or  jessie. ruby 2.4 and bunder 1.16.1
error in bundle install 

user@labsrv:~/test$  rvm use 2.4 do bundle install --path ./gems
Fetching gem metadata from https://rails-assets.org/..
Fetching gem metadata from https://rubygems.org/.Failed to create threads for the Compact Index (rubygems.org) worker: can't create Thread: Resource temporarily unavailable

Retrying fetcher due to error (2/4): ThreadError can't create Thread: Resource temporarily unavailable.
Retrying fetcher due to error (3/4): ThreadError can't create Thread: Resource temporarily unavailable.
Retrying fetcher due to error (4/4): ThreadError can't create Thread: Resource temporarily unavailable.
...

in normal work user running ~25 processes
ps -mu user | wc -l
25

after run 'rvm use 2.4 do bunlde install':
root@labsrv:~# ps -mu user | wc -l
50

root@labsrv:~# ps -mu user
  PID TTY          TIME CMD
 4699 ?        00:00:05 bundle
    - -        00:00:05 -
    - -        00:00:00 -
 4731 ?        00:00:01 bundle
    - -        00:00:01 -
    - -        00:00:00 -
14124 ?        00:00:00 sshd
    - -        00:00:00 -
14125 pts/0    00:00:00 bash
    - -        00:00:00 -
22235 ?        00:00:11 ruby
    - -        00:00:11 -
    - -        00:00:00 -
22387 ?        00:18:33 ruby
    - -        00:18:33 -
    - -        00:00:00 -
26422 pts/0    00:00:02 bundle
    - -        00:00:01 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
    - -        00:00:00 -
29294 ?        00:00:24 ruby
    - -        00:00:24 -
    - -        00:00:00 -
29409 ?        01:50:08 ruby
    - -        01:50:08 -
    - -        00:00:00 -

and as a result, limits are triggered, according to the limits.conf

user    hard    rss            512000
user     hard    nproc           40
user    hard    priority        10
user     hard    cpu             20

downgrade to 1.11.2  the  fixes the problem

**Comment by deivid-rodriguez** [comment]
I'm going to close this ticket because we haven't heard of this issue in a very long time. If this is still reproducible against the latest bundler, please open a new ticket. Thanks!
