### ISSUE TITLE
`bundle gem` template improvement (dependency example)

### ISSUE THREAD

**Issue by fwolfst** [rubygems/rubygems#3236]
Bundlers (e.g. 1.16.2)  template for a new gems gemspec is helpful to get started.

From a user point of view I would like to include a commented-out example of how to get dependencies registered (`spec.add_dependency 'example-gem', '~> 1.0'`).

If I get heads up, I will create a PR.

**Comment by deivid-rodriguez** [comment]
Actually we moved all the `add_development_dependency` lines and moved them to the `Gemfile`, so your vim trick is not going to work anymore. :/

I don't have a strong opinion here. I'm fine with both adding an example, a link to docs, or both. Or none.

@colby-swandale Still on the fence?

**Comment by deivid-rodriguez** [comment]
Ok @fwolfst, if you're still interested, would you mind creating a PR adding both a commented out dependency example and a link to the documentation for more information?
