### ISSUE TITLE
very slow dependency resolver edge case

### ISSUE THREAD

**Issue by halfbyte** [rubygems/rubygems#3241]
Given this [Gemfile](https://gist.github.com/halfbyte/32248277a06547153c610eaa218d156e), I can reliably cause bundler to spend a ton of time in the resolver (30min and more) when running bundle install from scratch (without a Gemfile.lock). 

Here's a compact version of that Gemfile:
```ruby
source "https://rubygems.org"
gem "kitchen-inspec"
gem "net-scp",            ">= 1.1", "< 3.0" # pinning until we can confirm 3+ works
gem "net-ssh",            ">= 2.9", "< 6.0" # pinning until we can confirm 6+ works
gem "winrm-fs",           "~> 1.1"
```

Var | Value
-----|-----------
Ruby Version | Tested in 2.5.7 and 2.6.5
Bundler | 2.1.4 (also tested with 2.0.2)
Rubygems | 3.1.2
bundle config | empty

The example is contrived, but comes from a real case from within our Depfu machinery. The original repo where this comes from is [test-kitchen/test-kitchen](https://github.com/test-kitchen/test-kitchen) but interestingly, if the three bottommost gem entries live as gem.add_runtime_dependency in a specfile as they do on the original repo, resolution works fine. My assumption here is that resolving spec dependencies works differently than resolving Gemfile dependencies somehow?

We (Depfu) have, lately experienced a bunch of "interesting" performance regressions that seem to be similar to this issue and are probably due to weird dependency graphs with multiple circular dependencies, at least that's my current theory. As you can imagine, running a bundler process that never returns isn't an ideal situation for an automated service :)

**Comment by deivid-rodriguez** [comment]
I just noticed that the sample `Gemfile` you gave resolves in 3-4 seconds and 232 steps on 2.2.5, so it seems like this issue is solved! :tada:
