### ISSUE TITLE
add `bundle which <GEM>` command

### ISSUE THREAD

**Issue by jethrodaniel** [rubygems/rubygems#3243]
We already have `bundle open <GEM>`, but sometimes I just want the full path to an installed gem, instead of opening a new `$EDITOR`.

I think we should add a `which` command, that just prints the path of the installed gem.

Example:

```
$ bundle which racc
/home/user/.rbenv/versions/2.6.1/lib/ruby/gems/2.6.0/gems/racc-1.4.16
```

**Comment by jethrodaniel** [comment]
Personally, I'm content with `bundle show`.

Feel free to close this issue.

**Comment by deivid-rodriguez** [comment]
Actually we're deprecating `bundle show` in favor of `bundle info`, but now the command to get the same behavior is more complicated (`bundle info parser --path`).

Will need to dig back in history to check why we're doing this, but to me it'd be nice to keep `bundle show` to get the path to the gem directly. Maybe give it a better name (`bundle which`? `bundle path`?) if naming was the issue to deprecate it.

**Comment by jethrodaniel** [comment]
`bundle which` makes sense, given we have `gem which` (which is why I was initially surprised it didn't already exist).

**Comment by deivid-rodriguez** [comment]
The thing is, `gem which` gives you the "require entrypoint" for the gem, so it wouldn't be exactly the same thing.

```
$ gem which parser
/home/deivid/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/parser-2.7.0.4/lib/parser.rb
$  bundle info parser --path
/home/deivid/.rbenv/versions/2.7.0/lib/ruby/gems/2.7.0/gems/parser-2.7.0.4
```

**Comment by jethrodaniel** [comment]
ah, `gem which` makes sense now

**Comment by deivid-rodriguez** [comment]
Any feedback here? I feel a direct command to get the installation path a of gem is useful. So, we should:

* Investigate why `bundle show` was deprecated.
* Propose a new command (`bundle path`, `bundle which`) to replace `bundle show` if naming was the issue.

I'll tag this as a "good first issue".

**Comment by NeimadTL** [comment]
Hi @deivid-rodriguez, I'd like to work on this. Could elaborate on the investing part please ? also, should the `show` command work pretty much like  `show` ? happy to discuss that on slack if you'd rather do that.

**Comment by deivid-rodriguez** [comment]
Hei @NeimadTL, that's great! :)

The investigation part consists on digging into git history to find the PR that introduced the deprecation of `bundle show` and find out the motivations for it. Once we know why `bundle show` was deprecated we can make a decision here.

**Comment by deivid-rodriguez** [comment]
@NeimadTL and I investigated this. The conclusions are:

* It all started with https://github.com/rubygems/bundler/issues/3972, which reported a problem with incorrect help output of `bundle list`. In that issue, it was proposed to deprecate `bundle list`.
* Then `bundle list` was deprecated in https://github.com/rubygems/bundler/pull/4085.
* Then a typo (I guess?) was made in the [bundler 2 RFC](https://github.com/rubygems/rfcs/pull/6) and it was written there that it was `bundle show` that was supposed to be deprecated, not `bundle list`.
* So the situation was "fixed" in https://github.com/rubygems/bundler/pull/5853 to deprecate `bundle show` instead.

And that's where we're at now.

It sounds like we don't know what we want to remove or why, so we probably shouldn't remove anything :rofl:.

@NeimadTL If we undeprecate `bundle show`, this issue can be closed. Can you take care of that?

**Comment by NeimadTL** [comment]
@deivid-rodriguez, thank you very much for the investigation. I'll take care of it and make a PR very soon.
