### ISSUE TITLE
bundler crashes with net-http-persistent 3.x

### ISSUE THREAD

**Issue by pravi** [rubygems/rubygems#3244]
Full log and failure here https://ci.debian.net/data/autopkgtest/unstable/amd64/b/bundler/4243952/log.gz

We discussed this with @deivid-rodriguez earlier this month at debian ruby team sprint and he suggested updating bundler to 2.x but it is still failing.

**Comment by pravi** [comment]
See https://github.com/rubygems/rubygems/issues/3244#issuecomment-591307862

**Comment by deivid-rodriguez** [comment]
I understand, but I don't understand why you need to add it to `Conflicts`. Can you remove it completely? Since the code is vendored, I don't think you need to care about it and consider it a dependency.

**Comment by pravi** [comment]
Even if we remove it from Depends of bundler, the already installed copy does not get removed. It will be removed only if we add Conflicts, which means, these two should not be installed at the same.

**Comment by pravi** [comment]
Alternatively we can vendor net-http-persistent in ruby-mechanize and every other package that needs it, though that is a last resort option.

**Comment by deivid-rodriguez** [comment]
But why do you need the installed copy removed? Bundler should always use its own vendored copy of `net-http-persistent` and not care about other copies being installed globally. If it's not doing that, there's a bug somewhere.

**Comment by pravi** [comment]
Well, that is the bug here, right? Depends just installs net-http-persistent globally.

**Comment by deivid-rodriguez** [comment]
I'm not really sure where the bug is honestly. Can you patch the first line in `/usr/lib/ruby/vendor_ruby/net/http/persistent.rb` with `puts caller_locations.join("\n")` and run the failing autopkgtest with that and post the result?

**Comment by pravi** [comment]
```
==================================
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/vendored_persistent.rb:18:in `<top (required)>'
/usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/fetcher.rb:3:in `require_relative'
/usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/fetcher.rb:3:in `<top (required)>'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb:92:in `require'
/usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/cli/install.rb:54:in `run'
/usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/cli.rb:256:in `block in install'
/usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/settings.rb:124:in `temporary'
/usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/cli.rb:255:in `install'
/usr/lib/ruby/vendor_ruby/thor/command.rb:27:in `run'
/usr/lib/ruby/vendor_ruby/thor/invocation.rb:126:in `invoke_command'
/usr/lib/ruby/vendor_ruby/thor.rb:387:in `dispatch'
/usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/cli.rb:30:in `dispatch'
/usr/lib/ruby/vendor_ruby/thor/base.rb:466:in `start'
/usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/cli.rb:24:in `start'
/usr/share/rubygems-integration/all/gems/bundler-2.1.4/exe/bundle:46:in `block in <top (required)>'
/usr/share/rubygems-integration/all/gems/bundler-2.1.4/lib/bundler/friendly_errors.rb:123:in `with_friendly_errors'
/usr/share/rubygems-integration/all/gems/bundler-2.1.4/exe/bundle:34:in `<top (required)>'
/usr/bin/bundle:23:in `load'
/usr/bin/bundle:23:in `<main>'
==================================

```

**Comment by pravi** [comment]
lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb has a require call to net/http, I think that will need to be changed to relative path as well.

**Comment by deivid-rodriguez** [comment]
This is not making any sense to me. It seems to imply that this line https://salsa.debian.org/ruby-team/bundler/-/blob/master/lib/bundler/vendored_persistent.rb#L18 ends up requiring the system version of `net-http-persistent`. And that doesn't make any sense. Can you double check the content of the relevant files in the backtrace and post them here?

> lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb has a require call to net/http, I think that will need to be changed to relative path as well.

`net/http` should be picked up from the `ruby` installation, that's fine I think.

**Comment by pravi** [comment]
Ah seems like there is a patch forcing the system versions https://salsa.debian.org/ruby-team/bundler/-/blob/master/debian/patches/0002-Replace-bundled-libraries-with-system-versions.patch#L20 Usually we remove the vendor directory completely, so it did not occur to me to check the patch. Sorry for the noise and thanks a lot for your patience.

**Comment by deivid-rodriguez** [comment]
Great, I'm happy we sorted this out!
