### ISSUE TITLE
How do I update a gem in vendor/cache?

### ISSUE THREAD

**Issue by mperham** [rubygems/rubygems#3245]
Once you have a `bundle package` in vendor/cache, it would be nice if the man page mentioned how to update gems in that cache in the future. Does `bundle up <gem>` just work, do I delete the cached version first?, etc...

**Comment by deivid-rodriguez** [comment]
Hi @mperham, sorry for not replying earlier. I think the cache should be auto-managed, and get used & updated everytime you run `bundle install` or `bundle update`.
