### ISSUE TITLE
Use JRuby embedding to launch Ruby subprocess in same VM

### ISSUE THREAD

**Issue by headius** [rubygems/rubygems#3246]
JRuby supports running multiple isolated instances in the same JVM through a feature we call "embedding". This is used by many large applications to provide a way to keep changes in one JRuby instance separate from another.

It would also be a perfect way to avoid the second process launch from `bundle exec`.

This feature is partially implemented now, via the `disable_exec_load` option, but that does not truly isolate the incoming Ruby command from global environment changes that have happened while preparing the subprocess's environment. The code for that is here: https://github.com/rubygems/bundler/blob/master/lib/bundler/cli/exec.rb#L27

It should be easy to modify this logic such that on JRuby, the child command runs in its own isolated JRuby environment completely separate from the parent environment. This would cut in half the startup time for simple `bundle exec` commands, and for longer commands it would at least trim off several seconds of boot time.

A trivial example of embedding JRuby from within JRuby is below:

```ruby
subruby = org.jruby.Ruby.newInstance
subruby.eval_scriptlet(File.read('path/to/script'))
```

We will try to put together a PR, but anyone that wants to hack on this is welcome to stop by the [JRuby Matrix Room](https://matrix.to/#/#jruby:matrix.org) and work with us!

**Comment by eregon** [comment]
In which case is `disable_exec_load` true?
Could that be made the default or are there known issues with it?

> that does not truly isolate the incoming Ruby command from global environment changes that have happened while preparing the subprocess's environment

Which changes could matter here?
I guess it's all code loaded by the `bundle` stub, so all under the control of bundler, except things in `RUBYOPT` (but they probably don't matter, they would apply to the subprocess as well), right?

**Comment by eregon** [comment]
It looks accoding to the docs like `bundle exec` is no longer using a subprocess nowadays: https://github.com/rubygems/rubygems/blob/18c579ea5c6d5f7325ede312bad0c2294b6fa4e1/bundler/man/bundle-exec.1.txt#L83-L90

**Comment by eregon** [comment]
With `pid.rb`:
```ruby
puts "Executed in #{Process.pid} by #{RUBY_ENGINE}"
```

and Bundler 2.1.4 it seems to not `exec` on MRI:
```
$ RUBYOPT="-r$PWD/pid.rb" bundle exec rake --version 
Executed in 11231 by ruby
rake, version 13.0.1
```

But it does `exec` on TruffleRuby:
```
$ RUBYOPT="-r$PWD/pid.rb" bundle exec rake --version 
Executed in 10929 by truffleruby
Executed in 10929 by truffleruby
rake, version 12.3.2
32.68s user 0.61s system 388% cpu 8.574 total
```

Probably because [bin/rake](https://github.com/oracle/truffleruby/blob/b3faa0c24eb9a01922a0aa138d34b0ad137d7e41/bin/rake) doesn't look as usual to Bundler.
After `gem install rake` (to get a standard-looking bin/rake) it avoids the extra exec:
```
$ RUBYOPT="-r$PWD/pid.rb" bundle exec rake --version 
Executed in 11433 by truffleruby
rake, version 13.0.1
19.01s user 0.35s system 382% cpu 5.055 total
```

**Comment by headius** [comment]
`exec` reuses process ID.

```
$ jruby -e 'puts $$; exec %{jruby -e "puts $$"}'
85727
85727
```

**Comment by eregon** [comment]
Yes, so the above shows it by how many times it's printed. Twice means it exec'd (ruby was launched twice). Once means there was only 1 Ruby process (also the timings are clear).

**Comment by headius** [comment]
Ahh, I see what you mean now... the `pid.rb` file only gets loaded once, indicating that it's only launching Ruby once.

I also saw your links in https://github.com/oracle/truffleruby/issues/1981 to the logic that helps this magic happen. It scans the target command for a shebang of an appropriate form and if it matches it just runs the file directly.

This only covers cases where the shebang exists and matches, of course. If you're using `bundle exec` to run a script without a shebang, it will still double-launch. Perhaps that's not common.

**Comment by eregon** [comment]
If it doesn't have a shebang then it's not a gem executable, right?
Then probably we can't even assume it's a Ruby file, so those cases seem rare.

Not sure what happens on Windows (I think those gem stubs are still the same + an extra `.bat`).

**Comment by headius** [comment]
> If it doesn't have a shebang then it's not a gem executable, right?

That's a fair point... `bundle exec` seems to be searching for executables only, and if a script has an executable bit it would need to have an appropriate shebang line. So for the cases where we *can* execute a script in-process, it may be that it's already doing so.

I suppose it would still fail to work if the shebang line did not match expectations, but that might be rare for executable Ruby scripts. There's only so many ways you can locate a Ruby to run.

**Comment by eregon** [comment]
Related issue on the MRI tracker: https://bugs.ruby-lang.org/issues/16744

@headius Do you want to keep this issue open or you think the existing logic in Bundler is already good enough?

**Comment by deivid-rodriguez** [comment]
I'm going to close this given that there was no feedback. If it needs to stay open, go ahead a reopen @headius.
