### ISSUE TITLE
Feature request enable bundler to install specific gems into specified directories.

### ISSUE THREAD

**Issue by timuckun** [rubygems/rubygems#3247]
I would like to put some gems into my vendor/bundle but not others.   Ideally this would be similar to the path directive where I can specify

```ruby
gem 'blah', destination: 'vendor/bundle'
```

or

```ruby
destination 'vendor/bundle' do
   gem 'blah'
end
```

**Comment by deivid-rodriguez** [comment]
I agree this would be quite complicated to introduce and maintain, but I also don't see the use case. What's the use case?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
