### ISSUE TITLE
Using binstubs for all gems with the deprecated --binstubs

### ISSUE THREAD

**Issue by DannyBen** [rubygems/rubygems#3251]
I am trying to figure out how to properly set up bundler in Github actions, and bumped into what seems to be a missing or at least confusing functionality.

### `bundle install --binstubs` is deprecated

```
$ bundle install --binstubs ./bin
[DEPRECATED] The --binstubs option will be removed in favor of `bundle binstubs`
```

### `bundle binstubs` does not have a way to stub all gems

And, in addition it points to the deprecated `--binstubs` flag, which I am guessing is a documentation issue.

```
$ bundle binstubs --help
SYNOPSIS
       bundle binstubs GEM_NAME [--force] [--path PATH] [--standalone]

# ... snip ...

BUNDLE INSTALL --BINSTUBS
       To  create  binstubs  for  all  the  gems in the bundle you can use the
       --binstubs flag in bundle install(1) bundle-install.1.html.
```

So - what is the proper way to binstub all gems?

---

To add some context: When using a vendor path for the bundle (for caching), then any installed gem that comes with a binary, is not found in the path. This is why I started looking at this binstubs feature (which I never used before).

I would much rather **avoid creating these binstubs**, and instead, just add the `vendor/bundle/.../bin` folder to the path, but I was unable to find the proper command to obtain this path - as it seems to differ from system to system.

I was hoping there is some `bundler env get bin_path` or similar so I can do this in GitHub Actions:

```yaml
- name: Bundle install
  run: |
    gem install bundler
    bundle config path vendor/bundle
    bundle install --jobs 4 --retry 3
    echo "::add-path::$(bundle env get bin_path)"   
```

**Comment by ErikHumphrey** [comment]
It looks like the [original card](https://trello.com/c/1pBNHD98/99-remove-binstubs-option-document-using-the-bundle-binstubs-command-instead) for this issue mentioned an `--all` option, but it didn't make it in.

**Comment by deivid-rodriguez** [comment]
Actually `bundle binstubs --all` [is implemented](https://github.com/rubygems/bundler/pull/6450), and works!

We need to fix both the documentation and the deprecation message.

**Comment by nateww** [comment]
FYI, the docs on the bundle website still don't document the `--all` flags.

See https://bundler.io/v2.1/man/bundle-binstubs.1.html

**Comment by deivid-rodriguez** [comment]
Right, these docs will be present in bundler 2.2 docs.

**Comment by deivid-rodriguez** [comment]
Docs are live now: https://bundler.io/v2.2/man/bundle-binstubs.1.html.

**Comment by nateww** [comment]
Thanks
