### ISSUE TITLE
Default to --keep-file-descriptors

### ISSUE THREAD

**Issue by ioquatix** [rubygems/rubygems#3254]
It seems to me that `bundle exec --keep-file-descriptors` should be the default behaviour.

**Comment by deivid-rodriguez** [comment]
I also believe this should be the default. Bundler should preserve the exec'ed environment as closely as possible. Also, I don't think this will create any compatibility issues? I can see the opposite change (from not closing, to closing) creating issues, but this direction seems safe and would make bundler "just work" in more cases.
