### ISSUE TITLE
bundler 2.1.4 issue

### ISSUE THREAD

**Issue by caponecicero** [rubygems/rubygems#3257]
I did a

`gem update`

The bundler gem got updated from 2.1.4 from 2.1.2 (which was installed with ruby 2.7.0).  I did a 

`bundle update --all`

on my project after *removing* the **Gemfile.lock**.  Everything proceeded normally.  I started getting warnings that look like this when I run the executable in that project:

```
Warning: the running version of Bundler (2.1.2) is older than the version that created the lockfile
(2.1.4). We suggest you to upgrade to the version that created the lockfile by running 'gem install
bundler:2.1.4'.
```

After doing the above again, I noticed the following in the list of gems installed into the bundle:

```
...
Using opener 0.1.0
Using binman 5.1.0
Using bundler 2.1.2   <<< ?!?
Using color 1.8
Using parslet 1.8.2
...
```

I uninstalled *bundler-2.1.4* and re-build the project bundle and everything is back to normal.

I've done this a million times...  What did I miss this time?

**Comment by codemicky** [comment]
I am having same issue. Any update here?

**Comment by MicMicMon** [comment]
Same here, `bundler 2.1.2` seems pinned in the system, even though a more recent version is installed:
```sh
$ gem list bundler
*** LOCAL GEMS ***
bundler (2.1.4, default: 2.1.2)

$ gem update bundler --default
Updating installed gems
Nothing to update

$ gem uninstall bundler:2.1.2
Gem bundler-2.1.2 cannot be uninstalled because it is a default gem
```

Any clue on how to remove 2.1.2 and leave only 2.1.4? Under ruby 2.7.0 if it matters.

**Comment by caponecicero** [comment]
You can remove 2.1.2 with some judicious removal of files (at least so `gem list` doesn't report it being there)...however, once you do that, and bundle with 2.1.4, your project will crash because there's some part of the `ruby 2.7.0` installation that always references 2.1.2.

Just remove 2.1.4 instead.  Believe me, you don't need the aggravation...

-- sw

**Comment by deivid-rodriguez** [comment]
Hi everyone, can someone provide repro steps so I can take a look? Thanks!

**Comment by caponecicero** [comment]
See above...  I've provided at least two -- one on 24 Jan and another on 7 Mar.

**Comment by martinsp** [comment]
@deivid-rodriguez this reproduces the error for me: https://github.com/martinsp/bundler-3257

Uncommenting line 5 in the run.rb fixes the warning.

**Comment by deivid-rodriguez** [comment]
@caponecicero Those are not reproductions. A reproduction is a set of commands to be run by anyone so that the error is reliably reproduced. You mentioned `bundle update --all` which works without warnings in many many cases, so a bit more than that is needed.

Thanks @martinsp. Unfortunately, I cloned the app and `ruby run.rb` runs on my system without any warnings, assuming `ruby run.rb` is what I need to run.

Ideally I'd need a `Dockerfile` reproducing your exact environment (ruby version manager, ruby version, rubygems version, list of gems installed, and son on) where the command produces the warning.

I also tried on a pristine Rails application using `spring`, since that has been mentioned too, but I couldn't reproduce the warning either :(

**Comment by deivid-rodriguez** [comment]
@caponecicero I'm seeing the .txt log that you provided but that includes paths in your netlify server and folders in your system. I need something that I can run on my system to reliably reproduce the error for myself.

**Comment by martinsp** [comment]
@david-rodriguez sorry about incomplete details. I have updated the repository with a Dockerfile.

I can reproduce the issue by runing `docker build -t bundler-3257 .`

<details>
<summary>Here is the output I got:</summary>

docker build -t bundler-3257 . 
Sending build context to Docker daemon  65.02kB
Step 1/6 : FROM ruby:2.7.0-buster
 ---> 556e761e192c
Step 2/6 : COPY bundler-3257 /bundler-3257
 ---> d37436eee42d
Step 3/6 : RUN ruby -v
 ---> Running in 4d0bc6f1d2eb
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-linux]
Removing intermediate container 4d0bc6f1d2eb
 ---> c0021479f575
Step 4/6 : RUN gem update bundler
 ---> Running in fdfe7831991d
Updating installed gems
Updating bundler
Successfully installed bundler-2.1.4
Gems updated: bundler
Removing intermediate container fdfe7831991d
 ---> 9528b91f704c
Step 5/6 : RUN gem list bundler
 ---> Running in 7a301e912fb5
bundler (2.1.4, default: 2.1.2)
Removing intermediate container 7a301e912fb5
 ---> e5dca7f2f132
Step 6/6 : RUN   cd /bundler-3257   && ruby ./run.rb
 ---> Running in b2ac65bbd27f
Warning: the running version of Bundler (2.1.2) is older than the version that created the lockfile (2.1.4). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.1.4`.
Removing intermediate container b2ac65bbd27f
 ---> e8759d3ab20d
Successfully built e8759d3ab20d
Successfully tagged bundler-3257:latest
</details>

**Comment by deivid-rodriguez** [comment]
Thanks @martinsp!! I can repro now!

I'll investigate why the warning only reproduces on some environments and see what to do about it. :+1:

**Comment by caponecicero** [comment]
> @caponecicero I'm seeing the .txt log that you provided but that includes paths in your netlify server and folders in your system. I need something that I can run on my system to reliably reproduce the error for myself.

Here you go:

[bundle.zip](https://github.com/rubygems/rubygems/files/4399297/bundle.zip)

Make sure bundler:2.1.4 is what you get when you run `bundle`:

```
stevewi:~/projects/bundle $ gem list

*** LOCAL GEMS ***

benchmark (default: 0.1.0)
bigdecimal (default: 2.0.0)
binman (5.1.0)
bundler (2.1.4, default: 2.1.2)
byebug (11.1.1)
...

stevewi:~/projects/bundle $ ruby --version
ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin19]
stevewi:~/projects/bundle $ bundle update --all
Fetching gem metadata from https://rubygems.org/.............
Resolving dependencies...
Using bundler 2.1.4
Using sqlite3 1.4.2
Bundle updated!
stevewi:~/projects/bundle $ ./testsqlite
Warning: the running version of Bundler (2.1.2) is older than the version that created the lockfile (2.1.4). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.1.4`.
["one", 1]
["two", 2]
["Jane", "me@janedoe.com", "A", "http://blog.janedoe.com"]
```
Now, uninstall `bundler:2.1.4`.  Remove `Gemfile.lock` & `test.db` & rinse/repeat:

```
stevewi:~/projects/bundle $ bundle update --all
Fetching gem metadata from https://rubygems.org/.............
Resolving dependencies...
Using bundler 2.1.4
Using sqlite3 1.4.2
Bundle updated!
stevewi:~/projects/bundle $ ./testsqlite
["one", 1]
["two", 2]
["Jane", "me@janedoe.com", "A", "http://blog.janedoe.com"]
```

**Comment by deivid-rodriguez** [comment]
Not necessary anymore @caponecicero, but thanks!

Ok, so this is a bug in the default bundler gemspec that I introduced in ruby 2.7.0. I was actually aware of this bug, but forgot about it. My apologies :grimacing:.

I'll work and propose a fix to ruby-core either later today or tomorrow so that it can be shipped with ruby 2.7.1.

For now, the workaround is to force reinstallation of the default bundler gemspec. You can do that by downgrading rubygems, and then upgrading it again: `gem update --system 3.0.8 && gem update --system`.

**Comment by deivid-rodriguez** [comment]
So even if the change in bundler's default gemspec in ruby 2.7.0 uncovered this issue, the actual issue is a bug in rubygems. I'm fixing it here: https://github.com/rubygems/rubygems/pull/3458.

For now I think the workaround given (downgrade and upgrade back rubygems) should work, because that will result in bundler specification being installed as a gemspec with the "new style", which doesn't suffer from the bug.

**Comment by deepkum** [comment]
> For me I would see this warning in Spring-enabled Rails apps on Ruby 2.7.0.
> 
> ```
> $ bin/rails console
> Warning: the running version of Bundler (2.1.2) is older than the version that created the lockfile (2.1.4). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.1.4`.
> ```
> 
> My workaround is to modify `bin/spring` as follows:
> 
> ```diff
> diff --git bin/spring bin/spring
> index d89ee49..8bf446f 100755
> --- bin/spring
> +++ bin/spring
> @@ -4,6 +4,7 @@
>  # It gets overwritten when you run the `spring binstub` command.
>  
>  unless defined?(Spring)
> +  gem 'bundler', '2.1.4' # Match BUNDLED WITH in Gemfile.lock
>    require 'rubygems'
>    require 'bundler'
> ```
> 
> `bin/rails` now activates the correct version of Bundler and doesn't print a warning.

This works, it stooped getting warning :)

**Comment by mikhailgurevich** [comment]
> For me I would see this warning in Spring-enabled Rails apps on Ruby 2.7.0.
> 
> ```
> $ bin/rails console
> Warning: the running version of Bundler (2.1.2) is older than the version that created the lockfile (2.1.4). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.1.4`.
> ```
> 
> My workaround is to modify `bin/spring` as follows:
> 
> ```diff
> diff --git bin/spring bin/spring
> index d89ee49..8bf446f 100755
> --- bin/spring
> +++ bin/spring
> @@ -4,6 +4,7 @@
>  # It gets overwritten when you run the `spring binstub` command.
>  
>  unless defined?(Spring)
> +  gem 'bundler', '2.1.4' # Match BUNDLED WITH in Gemfile.lock
>    require 'rubygems'
>    require 'bundler'
> ```
> 
> `bin/rails` now activates the correct version of Bundler and doesn't print a warning.

This is the solution right here.

**Comment by deivid-rodriguez** [comment]
The right solution should be released with rubygems 3.1.3 soon, and will just work without any user intervention. That is a good workaround though :)

**Comment by RaminMammadzada** [comment]
> For me installing th newest version (3.1.2) of RubyGems solved this issue. 👍
> `gem update --system`

This also worked for me!

**Comment by remy727** [comment]
It worked. 👍 
```
gem update --system
```
