### ISSUE TITLE
Ignore Ruby version in Gemfile

### ISSUE THREAD

**Issue by fzakaria** [rubygems/rubygems#3263]
I have a Gemfile that specifically lists a Ruby version & engine.

i.e.
```ruby
ruby '2.3.3', engine: 'jruby', engine_version: 9.1.17.0
```

I know this gem however works with non-JRuby and I'd like to test it on MRI.
However when I execute `bundle` it gives me the error:
```
Your Ruby engine is ruby, but your Gemfile specified jruby
```

It would be great if there's a switch to control this.

If you are wondering then why are we specifying JRuby if I know it works on MRI ?
Well we want to avoid people accidentally writing MRI specific gems (that might use C-extensions) & also make sure we are testing each gem with the version of Ruby (JRuby) we use in our production environment.

**Comment by deivid-rodriguez** [comment]
My question here is: why is the `Gemfile` specifying `jruby` if the `Gemfile` is targeted or at least works on other platforms too? I think removing either the `jruby` part would work? I can see how having to remove it manually can be annoying but I'm not sure if it warrants a new feature. Are you the owner of the `Gemfile`? If not, can you ping the author to update it? Note that removing it won't add any "non-determinism" as long as you have a lockfile where the different platforms are locked.

**Comment by fzakaria** [comment]
The original rationale was that we want to pin to our implementation of Ruby (i.e. JRuby), along with the ENGINE_VERSION.
We’ve done this for gems that could even be “technically” run on any engine; since in practice we’ve found differences in practice with how files are loaded (require) for JRuby for instance (due to the nature of multiple threads).

The idea here was to give developers the support to “break glass”.
Happy to continue the conversation if there’s other idiomatic approaches — perhaps your idea is correct and we should just remove it but I was seeing if there’s something that allows us to keep our determinism still on what we formally test it with.

**Comment by deivid-rodriguez** [comment]
I see.

Normally what you do to make sure a gem works against a specific version of an implementation, is to test against that version. So you would need to remove the `jruby` part from the `Gemfile` and add `jruby-9.1.17.0` or whatever to your CI matrix.

I understand wanting to do this in another way, but I don't think it warrants a new feature inside bundler.

**Comment by deivid-rodriguez** [comment]
I'll close this for now.
