### ISSUE TITLE
Error while executing jruby -S bundle install

### ISSUE THREAD

**Issue by SangeethKabilan25** [rubygems/rubygems#3267]
when i try to execute bundle install with jruby i am getting below error. Kindly help me in fixing this.

https://github.com/bundler/bundler/search?q=Unable+to+find+a+spec+satisfying+sqlite3+%28%3D+1.3.10%29+in+the+set.+Perhaps+the+lockfile+is+corrupted%3F&type=Issues

I am using windows 10

**Comment by deivid-rodriguez** [comment]
Ping @SangeethKabilan25

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
