### ISSUE TITLE
`reverse_rubygems_kernel_mixin` breaks `require`-extending libs

### ISSUE THREAD

**Issue by Aquaj** [rubygems/rubygems#3270]
Hi !

While working on a Rails app (with its new autoloader Zeitwerk), I've encountered an issue where after Zeitwerk has redefined `require`, Bundle comes along and rewrites it to be the original `require` again, in an attempt to undo Rubygem's extension.
Basically:
- Rubygems modifies `Kernel#require`
- Zeitwerk modifies `Kernel#require` on top of Rubygem's modification
- Bundler resets `Kernel#require` to pre-Rubygem state
This prevents Zeitwerk from working properly and just crashes the program with a LoadError.

I figure this could possibly happen to other libraries than Zeitwerk too, even if I haven't really figured out a solution yet.

**Comment by deivid-rodriguez** [comment]
Hello! :wave: :wave:

I investigated this a bit today. I found that this line is the culprit:

https://github.com/rubygems/rubygems/blob/214fefcdafd660ec031505608ef43ac202614a30/bundler/lib/bundler/cli.rb#L60

Removing it fixes the issue, but breaks 2 other specs. So I will need to do some more digging to figure this out. But hey, this is some progress :)

**Comment by deivid-rodriguez** [comment]
Hello again! I looped back to this and I now have a proper fix (I think). Can you try [this patch](https://github.com/rubygems/rubygems/compare/zeitwerk)?

**Comment by Aquaj** [comment]
Wow ! Didn't see your comment on Oct 2 so that was a surprise!

Yeah, I just tried to patch Bundler with your suggestion and it fixed the issue in both the minimal reproducing app and the original project I encountered this on. 🎉
As I mentioned this wasn't a blocking issue for us, but I'll be glad to remove the workaround whenever the PR gets merged. Thanks for looking into it 👍

**Comment by deivid-rodriguez** [comment]
That's gret to know, I'll try to wrap up the PR with a spec and merge it.

**Comment by deivid-rodriguez** [comment]
I was tricky to wrap the spec, but it should be ready now I think :)

**Comment by Aquaj** [comment]
Great to hear! 🎉 
Thanks for your work on this David 👌

**Comment by deivid-rodriguez** [comment]
No problem! :+1:
