### ISSUE TITLE
Newest version breaks build - 'Cleaning all the gems on your system is dangerous!'

### ISSUE THREAD

**Issue by FireFart** [rubygems/rubygems#3271]
Currently we have set
```text
bundle config set clean 'true'
```
in our dockerfile to keep the images small but with the latest version of bundler the build fails with
```text
Use `bundle info [gemname]` to see where a bundled gem is installed.
Cleaning all the gems on your system is dangerous! If you're sure you want to
remove every system gem not in this bundle, run `bundle clean --force`.
```

This is because this message returns a non zero return code. How to set the `--force` flag with `bundle config set ...`?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
