### ISSUE TITLE
ArgumentError: bad argument (expected URI object or URI string) in bundler-audit

### ISSUE THREAD

**Issue by olegantonyan** [rubygems/rubygems#3278]
Original issue https://github.com/rubysec/bundler-audit/issues/235
In version 2.1.2 `Bundler::LockfileParser` returns remotes' URIs as `Bundler::URI::HTTP`, but previous versions use `URI::HTTP`. This breaks bundler-audit.

Steps to reproduce:
1. install latest bundler (2.1.2 at this moment)
2. open a rails console in any rails project and run ```::Bundler::LockfileParser.new(File.read('Gemfile.lock')).sources.each { |s| s.is_a?(Bundler::Source::Rubygems) ? (s.remotes.each {|r| pp r.class}) : nil }; nil```
3. uninstall 2.1.2 and install 2.0.2 and repeat.
4. in the first case you'll get `Bundler::URI::HTTP`, and in the second - `URI::HTTP`

**Comment by deivid-rodriguez** [comment]
I didn't expect to break `bundler-audit` when vendoring `URI`, but in any case they adapted to our code and released that change, so closing!
