### ISSUE TITLE
Bundler 2.1.0 doesn't work properly with private gem sources when Basic Auth is set in bundle config

### ISSUE THREAD

**Issue by hrabiel** [rubygems/rubygems#3282]
My project uses private gem storage which can be accessed with Basic Auth.
With the new version of Bundler (2.1.0) I'm not able to install any gems from this source because of authorization error.
Seems that this issue is CGI-encoding related.

Let's assume that my auth username is `user@example.com`, password is `pass` and the storage origin is `gems.example.com`. I have my config set as
```
$ bundle config gems.example.com user%40example.com:pass
```

When I run `bundle install` and have the source defined in the `Gemfile` (`source 'https://gems.example.com'`), I get an error:
```
Retrying download gem from https://user%40example.com:pass@gems.example.com/ due to error (2/4): Gem::RemoteFetcher::FetchError bad response Unauthorized 401 (https://user%2540example.com:REDACTED@gems.example.com/rake-12.3.3.gem)

```

Might be worth looking at `%40` code turned to `%2540` in the error message.
It looks like Bundler performs redundant escaping of auth credentials.

Some additional notes:
* Downgrading to `2.0.2` fixed the issue.
* Specifying the source right in the command line like this 
```bundle install --source "https://user%40example.com:pass@gems.example.com/ "``` 
_do_ work in 2.1.0
* When I set the config with unescaped credentials (`$ bundle config gems.example.com user@example.com:pass`) i get an error on `bundle install`:
```Please CGI escape your usernames and passwords before setting them for authentication.```

**Comment by dogaoz** [comment]
I have the same problem. Is there a workaround or fix?

**Comment by deivid-rodriguez** [comment]
We never identified the culprit, but this is working on the latest versions of both bundler and rubygems, so closing!
