### ISSUE TITLE
Bundler 2.1.0 breaks bundle install in projects with Gemfile.lock or older Rubies

### ISSUE THREAD

**Issue by stefanhorning** [rubygems/rubygems#3283]
The new version of bundler released yesterday, seems to break `bundle install` all over the place at our company.
This seems to be the case when there is a pre-existing `Gemfile.lock` in the project that has a `BUNDLED WITH` section. In our case the version in the Gemfile.lock `1.17.3` in most cases. Which leads to the error:

```
/lib/ruby/site_ruby/2.5.0/rubygems.rb:275:in `find_spec_for_exe': Could not find 'bundler' (1.17.3) required by your /vagrant/mpx-db-stats/Gemfile.lock. (Gem::GemNotFoundException)
To update to the latest version installed on your system, run `bundle update --bundler`.
To install the missing version, run `gem install bundler:1.17.3
```

The problem can be solved by installing either 1.17.3 with `gem install bundler:1.17.3`, or by removing Gemfile.lock (but not really a good option in some projects).

Also some Travis builds started failing because it uses ruby 2.5.3 by default. Somehow those can be fixed by updating to 2.5.7. However that only helps if Gemfile.lock is already at 2.0.2 I think, as we still had problems with deploys that already build on ruby 2.5.7.

Sorry for this confusing report, but s.th. is weird with this new version and I can't really put my finger on it yet.

**Comment by deivid-rodriguez** [comment]
This will bite us again once we release the next major version of bundler. Since now we're implementing automatically installing and using the `BUNDLED WITH` version inside bundler (see #4076), I think we should completely remove this error from RubyGems.
