### ISSUE TITLE
Guard Clause in git_source Block Ignores Gem

### ISSUE THREAD

**Issue by tubbo** [rubygems/rubygems#3285]
I have a Gemfile with a `git_source` block that uses a conditional, primarily for installing the gems within GitHub Actions CI. 

Originally, I had written it as:

```ruby
git_source :github do |repo|
  if ENV["GITHUB_ACCESS_TOKEN"].nil?
    "https://github.com/#{repo}.git"
  else
    "https://x-access-token:#{ENV['GITHUB_ACCESS_TOKEN']}@github.com/#{repo}.git"
  end
end
```

And when I installed a gem from my private GitHub org, like `gem 'my_private_gem', github: 'my-private-org/my-private-gem'`, everything went smoothly.

Then I ran `rubocop --auto-correct` on the file, which automatically changed the definition of the `git_source :github` block to:

```ruby
git_source :github do |repo|
  return "https://github.com/#{repo}.git" if ENV["GITHUB_ACCESS_TOKEN"].nil?

  "https://x-access-token:#{ENV['GITHUB_ACCESS_TOKEN']}@github.com/#{repo}.git"
end
```

...and this is where the problem started.

When I ran `bundle`, I never saw it fetching the Git remote. Additionally, the gem never installs. Bundler just ignores this gem entirely as if it was never in my Gemfile.

I'm not sure whether this is a bug or if it's expected behavior.

Here's a full example that's possible to copy-and-paste:

```ruby
source "https://rubygems.org"

# change this to a conditional to make things work
git_source :github do |repo|
  return "https://github.com/#{repo}.git" if ENV["GITHUB_ACCESS_TOKEN"].nil?

  "https://x-access-token:#{ENV['GITHUB_ACCESS_TOKEN']}@github.com/#{repo}.git"
end

gem 'net-sftp'
gem 'rn', github: 'tubbo/rn' # change this to a gem you control to see it download
```

**Comment by deivid-rodriguez** [comment]
@tubbo Can you reproduce with the latest rubocop? This correction might've been a false positive.

**Comment by tubbo** [comment]
@deivid-rodriguez you are correct, RuboCop v0.87.1 doesn't seem to try and auto-correct this anymore. I guess this is fine to close, but it's still super weird that a `return` in this block just totally prevents the Gemfile from being installed...

**Comment by deivid-rodriguez** [comment]
Well, since we're not inside a method, that's essentially a top-level return, right? So... since that's usually at the begining of the `Gemfile`, it makes sense to me that nothing gets installed.

**Comment by tubbo** [comment]
yeah, I forgot about the whole block scoping rules of Ruby for a sec.
