### ISSUE TITLE
Include auto-categorizing and sorting after install || update gems in Gemfile

### ISSUE THREAD

**Issue by deHelden** [rubygems/rubygems#3289]
At my current project we have about 350 gems. It's not so much but it's how it is..
Basically when somebody add new gem it's added to bottom of Gemfile. Without categorization and alphabetic order it's painfully hard to read for new people. 

Could you please somehow integrate with https://github.com/nikolalsvk/ordinare.
It would be really awesome to have pre-installed ability not to think about all this stuff.

I would really appreciate any callback for `ordinare` after running `bundle install || update`

**Comment by deivid-rodriguez** [comment]
I'll close this since we never received further feedback about this.
