### ISSUE TITLE
Still getting 'You must use Bundler 2.0 on this gemfile.lock' 

### ISSUE THREAD

**Issue by dsound-zz** [rubygems/rubygems#3300]
I seem to be going in circles with this one. I try all the fixes suggested in other issue submissions and on stackoverflow  but to no avail. I've tried uninstalling/reinstalling bundler, running bundle install after deleting gemfile.lock, `gem update --system` and sometimes it gets fixed for a while and then comes back. It's also preventing me from deploying anything to Heroku. Is there a permanent fix for this yet? I'm using Ruby 2.6.3. and Rails 5.2.2.

Thanks

**Comment by deivid-rodriguez** [comment]
We never got any further feedback from @dsound-zz, so I'll assume this was fixed!
