### ISSUE TITLE
Gem::Specification.find_by_name does not find installed gems when program is executed with bundle execute

### ISSUE THREAD

**Issue by nhh** [rubygems/rubygems#3303]
There is a ruby program which executes `Gem::Specification.find_by_name "alpha"` to verify a gem is being installed correctly.

The gem is installed during runtime via `Gem::Commands::InstallCommand.new.install_gem "/path/to/my.gem"`.
(Which runs without errors)

When running the program with bundler: `bundle exec my_program.rb` the Code throws a `Gem::MissingSpecError`.

When running the program without bundler, it shows the corrensponding Gemspec.

`gem info "alpha"` works as expected.

Am i missing something? Can i programmatically "reload" the bundler environment?

**Comment by deivid-rodriguez** [comment]
Calling `Gem::Specification.reset` should probably fix things for you.

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
