### ISSUE TITLE
Bundler uses absolute paths for plugin index file

### ISSUE THREAD

**Issue by thomas07vt** [rubygems/rubygems#3304]
I was trying to use the https://github.com/Shopify/bootboot plugin on an app that is deployed to Heroku and had issues deploying when this plugin was referenced in the Gemfile:

[!] There was an error parsing `Gemfile`: cannot load such file -- /tmp/build_25b8cdeb02479da83b01e637852d01b3/vendor/bundle/ruby/2.6.0/gems/bootboot-0.1.2/plugins.rb. Bundler cannot continue.

I reached out to Heroku and eventually @schneems found out that the .bundle/plugin/index  file had absolute paths instead of relative ones.

I think it makes sense to use relative paths for bundler plugins right?

**Comment by deivid-rodriguez** [comment]
This is the same issue as https://github.com/rubygems/rubygems/issues/3340, and the proposed solution is the same, so I'll close this ticket in favour of that one.
