### ISSUE TITLE
`bundler lock` doesn't take --gemfile flag

### ISSUE THREAD

**Issue by lilyball** [rubygems/rubygems#3320]
The `bundler lock` command doesn't take a `--gemfile=PATH` flag, even though it does take a `--lockfile=PATH` flag. It appears to respect the `BUNDLE_GEMFILE` environment variable, but it would be a lot more convenient and discoverable to take a `--gemfile=PATH` flag like `bundler install` does.

**Comment by deivid-rodriguez** [comment]
Released [with bundler 2.1](https://github.com/rubygems/bundler/commit/5bd3ef0901a053b8266026d0bc47ae66b4a9d8d9).
