### ISSUE TITLE
Error "An error occurred while installing" does not have clean command

### ISSUE THREAD

**Issue by fulldecent** [rubygems/rubygems#3321]
I ran the command `bundle install --path vendor/bundle` and somewhere inside it had an error. 

Then Bundler helpfully isolated the package that was failing:

> An error occurred while installing http_parser.rb (0.6.0), and Bundler cannot continue.
> Make sure that `gem install http_parser.rb -v '0.6.0' --source 'https://rubygems.org/'` succeeds before bundling.

However the copy-paste command `gem install http_parser.rb -v '0.6.0' --source 'https://rubygems.org/'` will install in a different way (requiring `sudo`) than Bundler was using (from `--path vendor/bundle`).

This error message could be improved if Bundler will output a more comparable command to what it was actually attempting to run.

**Comment by deivid-rodriguez** [comment]
I think we should definitely improve this :+1:. If `BUNDLE_PATH` is configured, we should add a proper `--install-dir` to the suggested command.

**Comment by vinicius0197** [comment]
Hello @deivid-rodriguez , I'm looking forwards to start contributinging to rubygems and would love to get started with this issue :)

**Comment by deivid-rodriguez** [comment]
Hello @vinicius0197, please go ahead! :+1:

**Comment by vinicius0197** [comment]
@deivid-rodriguez Took a long time to start working on this, but I've been digging on the codebase lately and found that those error messages are generated by the `gem_install_message` method [here](https://github.com/rubygems/rubygems/blob/a969c0f16aa56cdb69e2a051f2b093427010e1d9/bundler/lib/bundler/installer/gem_installer.rb#L48-L57). I'm trying to run my local repository of RubyGems with `bundle install --path vendor/bundle` to find out how to access `BUNDLE_PATH`.

As the `CONTRIBUTING` documentation suggests, I'm using `ruby -Ilib bin/gem install` to run commands from the repo, but I'm still trying to figure out how to debug the code better. My first idea was to write a test case and start from there. I imagine the [path_spec.rb](https://github.com/rubygems/rubygems/blob/c92a93b318af52c9760cbde5fdee3f23531bce19/bundler/spec/install/path_spec.rb) file would be te right place to put this test, right? From there I could try to figure out how to find out if `BUNDLE_PATH` is configured and customize the error message.

**Comment by deivid-rodriguez** [comment]
Hi @vinicius0197!

I was recently thinking that I'm not sure printing this command is helpful. Even if we fix this issue, it's a different command possibly run on a different context, so we will never be able to guarantee that the command will led to the same error. And even if it was correct, it's just going to print the same error than `bundle install`.

I think I would remove this recommendation altogether, as long as it's still clear which gem failed to install and the error that was raised.

Not sure what others think.

**Comment by vinicius0197** [comment]
@deivid-rodriguez Hm, got it. So we would omit the `Make sure that gem install .... succeeds before bundling.` message from the bundler output altogether?

**Comment by deivid-rodriguez** [comment]
Yes, in my option we should omit that message from the output, and also print the backtrace unconditionally by removing the `if Bundler.ui.debug?` from https://github.com/rubygems/rubygems/blob/a969c0f16aa56cdb69e2a051f2b093427010e1d9/bundler/lib/bundler/installer/gem_installer.rb#L34.

@simi How do you feel about that?

**Comment by vinicius0197** [comment]
@deivid-rodriguez All right. To conform with the contributing guideline, I'm trying to write some tests for my changes, but I'm still a bit confused about how tests work on the RubyGems repo. How would I go about running a single test file on `bundler/spec` ? Running `rspec path/to/file` just gives me lots of errors. Don't know if there's some Rake command that I should use instead?

**Comment by deivid-rodriguez** [comment]
Hei @vinicius0197, right now you need to switch to the `bundler` folder to run bundler specs. We can probably improve this so that you don't need to swich folders and you can run rspec directly from the root of the repository like you tried. But for now, `cd bundler`, and then `bin/rspec path/to/file`.
