### ISSUE TITLE
Bundler should not require that the user grant write permissions to paths in /var/folders/

### ISSUE THREAD

**Issue by castdin** [rubygems/rubygems#3324]
When I run the following,

```
bundle gem my-gem
cd my-gem
bundle
```

I get the following error:
```
There was an error while trying to write to `/var/folders/04/42312kk53v37n0w58p857gfw0hh8c4/T/bundler-compact-index-20190403-88495-1hv2d9b/versions`. It is likely that you need
to grant write permissions for that path.
```

Why do I need to grant write permissions to a path that changes every time I `bundle`?

**Comment by reyesm93** [comment]
This is an odd solution but it worked for me:

I moved the bundle/cache directory in Finder to desktop (or any other folder, just make sure you have a copy of it) so I left the bundle directory empty. Then moved it back again and I was asked to authenticate with my user password. I re-tried the operation in the terminal and it asked to authenticate again. Then I was able to write on it.

**Comment by apinstein** [comment]
Wow ok so I had the same problem and simply did `rm -rf ~/.bundle` to start over from scratch and it worked... hopefully that will save someone else hours of pain.

**Comment by deivid-rodriguez** [comment]
We have recently shipped many improvements regarding permission issues, and I'm pretty sure this one is fixed now. Let me close this, but feel free to reopen if you're still experiencing this with the latest Bundler & RubyGems versions.
