### ISSUE TITLE
`bundle viz` deprecation path

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#3333]
I'm reviewing the `bundle viz` deprecation path, and it needs quite a bit of work.

* Current deprecation message says 

    > [DEPRECATED] The `viz` command has been moved to the `bundle-viz` gem, see https://github.com/bundler/bundler-viz.

    but that repo doesn't exist. We should either move https://github.com/kerrizor/bundler-dependency_graph to the bundler organization, or change the message to point to the alternative repo. The former sounds better.

* The deprecation message does not give any information about how to migrate to the plugin. We should change the message to something like:

    > [DEPRECATED] The `viz` command has been moved to a bundler plugin, see https://github.com/bundler/bundler-viz. In order to use the new plugin, run `bundle plugin install bundler-dependency_graph`. After that, you can run `bundle graph` instead of `bundle viz` to get a dependency graph for your application.

* The status of the new repo should be reviewed. Currently the plugin seems to work, although it prints the message

    > Currently unimplented; use `bundle viz` to generate your graphs for now.

    That, plus the list of issues in the repo, makes it sound like it's still a WIP.

How do we proceed?

**Comment by duckinator** [comment]
I just tried out @fatkodima's repo and it works very well.

@fatkodima are you interested in maintaining that going forward, or would you prefer to hand it off to the RubyGems/Bundler team?

@deivid-rodriguez @colby-swandale I feel that @fatkodima's work is a good starting point. Just a matter of figuring out where the repo will be and who will maintain it. If it's handed off to the RubyGems/Bundler team (see my question to @fatkodima above), I'm okay taking the lead on getting it to the point it can be released.

**Comment by fatkodima** [comment]
> or would you prefer to hand it off to the RubyGems/Bundler team?

this

**Comment by hsbt** [comment]
At least, We keep the commit history for separating the repository.

I think we will create the `rubygems/bundler-viz`, after that it may transfer the another maintainer.

**Comment by duckinator** [comment]
Okay. I don't have permissions to create/manage repos on the RubyGems organization. If someone who does have that ability creates an empty `rubygems/bundler-viz` repository and lets me know, I can take over working on it.

**Comment by duckinator** [comment]
And I'll be sure to keep the existing commit history from @fatkodima's repo. :+1:

**Comment by duckinator** [comment]
I created https://github.com/duckinator/bundler-viz based on @fatkodima's repo, and have it pretty much ready to go.

Unfortunately I don't have permission to transfer repos into the RubyGems org. I'll try to coordinate with on Slack with someone on getting it migrated.

**Comment by duckinator** [comment]
(Copying this over from Slack for context.)

I believe the relevant files are bundler/lib/bundler/cli.rb and bundler/lib/bundler/cli/viz.rb.

Unfortunately, `git subtree split` only works on directories (so it'd pull in the entirety of `bundler/cli/*`). And using `git log` to generate patches involving those files and applying them to an empty repo results in multiple hundreds of pacthes that don't apply.

I'm going to try `git filter-branch` next week, at the suggestion of @hsbt.

**Comment by duckinator** [comment]
If nothing else, I know it can be reduced to at most 790 commits -- every commit involving those files + an initial commit that's just importing the codebase prior to those files existing -- which is significantly less than the 22,542 commits in the entire repo.

**Comment by duckinator** [comment]
Alright, I took longer than planned to look at this, but took a look today and made some progress!

Looks like `git filter-branch` is no longer recommended, and `git filter-repo` is the new alternative the git devs recommend.

After a while of poking at things, I came up with these commands:

```
git clone https://github.com/rubygems/rubygems.git bundle-viz/ && \
cd bundle-viz/ && \
git tag -d $(git tag -l) && \
git filter-repo --path bundler/lib/bundler/cli.rb --path bundler/lib/bundler/cli/viz.rb --force && \
git branch -D $(git branch | grep -v '* master' | cut -d ' ' -f 3)
```

This combination narrows it down to the two relevant files. It inherently includes a lot of unrelated stuff, since any commit touching `bundler/lib/bundler/cli.rb` is included, but it has 944 commits instead of the 29,000+ in the original repo.

**Comment by duckinator** [comment]
Given the differences between the code I have and what's in the Bundler codebase, I'm honestly not sure how to get from https://github.com/duckinator/bundle-viz-wip (what I extracted today) to https://github.com/duckinator/bundler-viz (the version ready to release).

@hsbt what're your thoughts? I'm wondering if it's worth the effort at this point, honestly. Even after >4 hours of learning what seems to be the most flexible tool for this + working on it, all I've gotten is a separate history + the new code, with no real path between the two aside from redoing all of the work again.

**Comment by hsbt** [comment]
> https://github.com/duckinator/bundle-viz-wip

It seems fine to me. It's better to use it for publishing the standalone gem same as https://github.com/duckinator/bundler-viz. Maybe you only copy the current code to `bundle-viz-wip`.

**Comment by ybiquitous** [comment]
Hi, I found <https://github.com/bundler/bundler-viz> is 404 not found in the deprecation warning message with bundler 2.2.3:

https://github.com/rubygems/rubygems/blob/cf06c729453f34b5778866a072abb093584d3c6d/bundler/lib/bundler/cli.rb#L574

**Comment by deivid-rodriguez** [comment]
Thanks for bringing this up @ybiquitous.

Can we get an agreement of what do to here, @hsbt and @duckinator? As far as I understand, code was extracted to kerrizor's fork, then updated by @fatkodima, and then adapted again by @duckinator. Keeping the history of these changes sounds like a nightmare. How about using a section in the readme of the new repo to explain the history of the different repositories and give the proper attribution to contributors there?

**Comment by hsbt** [comment]
It's good to transfer https://github.com/duckinator/bundle-viz-wip to rubygems/bundler-vis repo. And re-create the skelton template for gem release. 

@duckinator Can you try it? If you don't have a permission for this. you can transfer to me like hsbt/bundler-vis-wip. After that, I rename and transfer rubygems org.

**Comment by duckinator** [comment]
@hsbt I transferred duckinator/bundler-viz-wip to you.

(As an aside, I'm going to be mostly-unavailable until around 2021-01-11 &mdash; focusing on finding a new apartment.)

**Comment by hsbt** [comment]
Thanks! I also transferred it to https://github.com/rubygems/bundler-viz.

**Comment by deivid-rodriguez** [comment]
Thanks, although I don't quite get the plan... :thinking:. That repo has a single folder, I think it should include more stuff like a gemspec, and a `plugins.rb` file. Will you just copy those from https://github.com/duckinator/bundler-viz? Isn't it simpler to transfer https://github.com/duckinator/bundler-viz directly?

**Comment by deivid-rodriguez** [comment]
The alternative plugin is now provided at https://github.com/rubygems/bundler-graph. Closing!

**Comment by duckinator** [comment]
As a note: @tnir pointed out that https://github.com/duckinator/bundler-viz is one of the top results for "bundler viz", even though it's not the correct thing. I updated it to only contain a README that points to https://github.com/rubygems/bundler-graph , and then archived the repo. Hopefully when Google picks up that change it'll start pointing people in the right direction.

**Comment by vahidcopz** [comment]
source "https://main_source"

gem "dependency1"

source "https://another_source" do
  gem "dependency2"
end
