### ISSUE TITLE
Specification.all isn't all

### ISSUE THREAD

**Issue by zenspider** [rubygems/rubygems#335]
As discovered in jbarnette/isolate#47, 7d43f14 makes Specification._all respond with a list of specifications minus redundant specs instead of all specs. If it is called all, I think it should be all. If we want unique specs, then we should add api for that.

**Comment by duckinator** [comment]
@zenspider, is this still a valid issue when using current versions of rubygems?

As a note:

`Gem::Specification.all` [issues a deprecation warning](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/specification.rb#L926-L930), and [the current documentation for `.all`](http://ruby-doc.org/stdlib-2.2.3/libdoc/rubygems/rdoc/Gem/Specification.html#method-c-all) recommends using Enumerable methods.

From that, my understanding is that the current equivalent of this which uses actually-documented methods would be `Gem::Specification.each.to_a` or similar. However: `.each` [ultimately winds up calling `._all`](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/specification.rb#L995-L1005), which appears to be a direct descendant of the old `.all`, but I don't know enough about this codebase to tell if it is _functionally equivalent_ to the old `.all`.
