### ISSUE TITLE
[Windows test failure] rspec ./spec/bundler/cli_spec.rb:16 # bundle executable looks for a binary and executes it if it's named bundler-<task>

### ISSUE THREAD

**Issue by janpio** [rubygems/rubygems#3354]
As described in https://github.com/bundler/bundler/issues/6868#issuecomment-451418573 currently 665 out of 2509 tests of bundler are failing on my Windows environment. I am working on fixing this.

---

Next failing test is this one:

```
C:\Projects\bundler (windows -> origin)
λ ruby bin/rspec spec/bundler/cli_spec.rb:16
Run options:
  include {:locations=>{"./spec/bundler/cli_spec.rb"=>[16]}}
  exclude {:ruby_repo=>false, :bundler=>"=< 2.0", :rubygems_master=>true, :git=>"=< 2.20.1", :rubygems=>"=< 2.6.14.1", :ruby=>"=< 2.4.4", :realworld=>true, :sudo=>true}

bundle executable
$ C:/Ruby24-x64/bin/ruby.exe -IC:/Projects/bundler/lib\;C:/Projects/bundler/spec -rsupport/hax \
  -rC:/Projects/bundler/spec/support/artifice/fail C:/Projects/bundler/exe/bundle testtasks
Could not find command "testtasks".
# $? => 15
  looks for a binary and executes it if it's named bundler-<task> (FAILED - 1)


Retried examples: 0

Failures:

  1) bundle executable looks for a binary and executes it if it's named bundler-<task>
     Failure/Error: expect(exitstatus).to be_zero if exitstatus

       expected `15.zero?` to return true, got false

       Commands:
       $ C:/Ruby24-x64/bin/ruby.exe -IC:/Projects/bundler/lib\;C:/Projects/bundler/spec -rsupport/hax \
         -rC:/Projects/bundler/spec/support/artifice/fail C:/Projects/bundler/exe/bundle testtasks
       Could not find command "testtasks".
       # $? => 15
     # ./spec/bundler/cli_spec.rb:27:in `block (2 levels) in <top (required)>'
     # ./spec/spec_helper.rb:122:in `block (2 levels) in <top (required)>'

Finished in 7.62 seconds (files took 2.17 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/bundler/cli_spec.rb:16 # bundle executable looks for a binary and executes it if it's named bundler-<task>
```

Test definition is here:
https://github.com/janpio/bundler/blob/b97a280c33607a0db12ee33dbb9104f735a3a527/spec/bundler/cli_spec.rb#L16-L28

This is creating a file in `tmp`, adding `tmp` to the `PATH` and then this script should get executed with `Kernel.exec` (https://github.com/janpio/bundler/blob/d3627ae62438eb4dd56af1ec843cb1d8e9616b95/lib/bundler/cli.rb#L129-L137). Problem is that on Windows the shebang doesn't work, so this file is not executed with ruby.

---

If I prefix the command with `ruby ` it also works on Windows. Is this a valid fix here or will this cause its own problems on Mac/Linux? Any other ideas?

---

(From my googling an alternative would be to add `.rb` to the filename and make Windows execute `.rb` files with Ruby - but of course this is dependent on the environment configuration. I also don't really understand what the real, non-test tasks are called - so this might not even work for the real tasks).

**Comment by deivid-rodriguez** [comment]
I believe this will also be fixed by #3381, so I'm also closing this ticket in favor of that one.
