### ISSUE TITLE
Could not detect rake tasks (LanguagePack::Helpers::RakeRunner::CannotLoadRakefileError)

### ISSUE THREAD

**Issue by apextemple** [rubygems/rubygems#3356]
Hi, @indirect, thanks for fixing the issue with s3! I'm currently facing the issue that the rake tasks are not detected. I tried everything on my end to make it work, but couldn't find any solution.

The error appears after all gems are installed, the it suddenly throws an error when it tries to detect the rake tasks. I tried 'bundle exec rake -P' and everything works fine.

I think this is the relevant part of the error:

```
remote: /app/tmp/buildpacks/19b20846a186a4065aa6710b809d0c465ff7a2235264402d06b5038f9562c56867a32c308dd2410d96108925a9f9fed74b5ef871dd6514a3a3a5485da3f442cf/lib/language_pack/helpers/rake_runner.rb:106:in `load_rake_tasks!': Could not detect rake tasks (LanguagePack::Helpers::RakeRunner::CannotLoadRakefileError)
remote: ensure you can run `$ bundle exec rake -P` against your app
remote: and using the production group of your Gemfile.
remote: rake aborted!
remote: LoadError: cannot load such file -- polyamorous/activerecord_5.2.2_ruby_2/join_association
```

**Comment by bronzdoc** [comment]
Closing since it's fixed in  2.0.2 otherwise please let us know
