### ISSUE TITLE
"`/` is not writable" message emitted on read-only bundle invocations

### ISSUE THREAD

**Issue by Roguelazer** [rubygems/rubygems#3358]
If bundler is run in a production environment (i.e., on an immutable filesystem and with `$HOME` unset), it helpfully prints out the following warning on every invocation (even those like `bundle exec` which should never write to the filesystem)

```
`/` is not writable.
Bundler will use `/tmp/bundler/home/username' as your home directory temporarily.
```

Setting `$HOME` to point to a writable temporary directory suppresses the message. I verified (using `strace`) that nothing is ever opened in that temporary directory.

I have two issues with this log message:

   1. Warning that `/` isn't writable on an action that will never write seems extraneous.
   2. Errors should be printed to stderr instead of stdout. There is never an acceptable care to print errors to stdout. Yes, I'm aware that I can export `$BUNDLE_ERROR_ON_STDERR` but does that really need to be opt-in for relatively-new warnings? Nobody could possibly have been relying on the broken behavior of writing errors to stdout for a warning that didn't even exist two minor versions ago.

This looks closely related to rubygems/bundler#5371 (which was closed but only for the case where $HOME is unset) and to have been proximally caused by rubygems/bundler#5385.

It would be swell if bundler (a) would not attempt to write when running `bundle exec`, and (b) would write this warning to stderr if it really feels the need to emit it.

```
% bundle version
Bundler version 1.16.3 (2018-07-17 commit 12e73cab7)
% bundle exec ruby --version
ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-linux-gnu]
```

Let me know if you'd prefer that I re-open rubygems/bundler#5371 in favor of opening a new issue

**Comment by billyabm** [comment]
You can set BUNDLE_PATH (env var) and this will be fixed you can see the configuration on the [bundle documentation](https://bundler.io/man/bundle-config.1.html)

**Comment by deviant** [comment]
I am working around this by creating a temporary directory to serve as `$HOME`. It would be nice if this could be removed, because it's not actually used for anything AFAICT and is cluttering up my logs.

**Comment by deivid-rodriguez** [comment]
I can repro this issue, I'll try to fix it.

**Comment by deivid-rodriguez** [comment]
#4724 should fix this!
