### ISSUE TITLE
bundle update --patch or --minor updates nothing

### ISSUE THREAD

**Issue by attenzione** [rubygems/rubygems#3360]
I have `Bundler version 1.16.2`
When I run `update/outdated` command with `--patch` option, however result is "everything is up to date"
```
$ bundle outdated
...
Outdated gems included in the bundle:
  * bourbon (newest 5.0.1, installed 5.0.0) in groups "default"
  * cocaine (newest 0.6.0, installed 0.5.8)
  * connection_pool (newest 2.2.2, installed 2.2.1)
```
This is part of command output, I have a lot more gems to update, more than 20, including major, minor and patch levels.

And when I run command with `--patch` or `--minor` option:
```
$ bundle outdated --patch
...
Bundle up to date!
```

same result for `update` command
same issue with `bundler version 1.15.4`

**Comment by deivid-rodriguez** [comment]
Hello! Can someone send an up to date reproduction? The repository in the original repo does not exist anymore.

**Comment by attenzione** [comment]
> Hello! Can someone send an up to date reproduction? The repository in the original repro does not exist anymore.

add any gem to `Gemfile` with `source:` to github

**Comment by deivid-rodriguez** [comment]
I did read this issue and tried that, but did not observe any particular unexpected behavior, that's why I'm asking for help.

**Comment by attenzione** [comment]
I tried to reproduce it now and it works as expected with `Bundler 2.3.4`

**Comment by deivid-rodriguez** [comment]
Alright, I will close this then. If someone is still seeing issues, please post a reproduction and I will reopen!

**Comment by AAAkkk00** [comment]
各位詐騙集團
