### ISSUE TITLE
Could not find gem SOME_GEM in any of the gem sources listed in your Gemfile

### ISSUE THREAD

**Issue by bbozo** [rubygems/rubygems#3362]
The Gemfile:

``` ruby
source 'http://rubygems.org'

ruby '2.3.3', :engine => 'jruby', :engine_version => '9.1.16.0'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '=4.2.10'

# Puma
gem 'puma'
gem 'thread_safe'
gem 'dalli' # memcache

# OpenSSL
gem 'manticore'
gem 'jruby-openssl'

# ...
```

so when I do `bundle` I get

```
Could not find gem 'manticore' in any of the gem sources listed in your Gemfile
or in gems cached in vendor/cache.
```

if I comment out the manticore gem, an ancient version of `jruby-openssl` comes:

``` ruby
    jruby-openssl (0.9.4)
      bouncy-castle-java (>= 1.5.0147)
```

and if I try to force a newer version, the error is:

```
Could not find gem 'jruby-openssl (~> 0.9.18)' in any of the gem sources listed
in your Gemfile or in gems cached in vendor/cache.
```

Yet both work via gem install:

```
$ gem install jruby-openssl -v '~> 0.9.18'
Fetching: jruby-openssl-0.9.21-java.gem (100%)
Successfully installed jruby-openssl-0.9.21-java
1 gem installed

$ gem install manticore
Successfully installed manticore-0.6.3-java
1 gem installed
```

This is `bundle/.config` of the project - it uses , I tried both with and without it:

```
BUNDLE_CACHE_ALL: "true"
BUNDLE_CLEAN: "true"
```

0. I went through and applied possible fixes from bundler issues that I found, including the similarly named one
1. I checked both gems that they're indeed available on rubygems - they are
2. I tried `bundle --full-index` 
3. I tried removing all local gems and bundling again
4. I tried different jruby versions (examples are with `jruby 9.1.16.0 (2.3.3)`)
5. I tried using an ancient bundler (don't know the version) and the last one (1.16.2)
6. I tried removing `.bundle/config` & `~/.bundle/cache` (`~/.bundle/config` is basically empty, the project-specific one is in the text above)
7. I tried `rm -rf vendor/bundle/` & `rm -rf vendor/cache`

Quick workaround for now is to use `:github` & `:tag`.

**Comment by deivid-rodriguez** [comment]
I tried reproducing this issue by running `bundle install` on the original Gemfile (using bundler 1.17.3, since one of the dependencies, rails 4.2, does not support a newer bundler), and everything went fine.

So I'll tentatively close this ticket. If you can provide a repro, feel free to reopen or open a new ticket. Thanks!
