### ISSUE TITLE
Provide a way to programmatically update dependency version constraints in the Gemfile

### ISSUE THREAD

**Issue by thisismydesign** [rubygems/rubygems#3364]
I see people torn between [pessimistic and optimistic](https://guides.rubygems.org/patterns/#declaring-dependencies) declaration of dependencies with semantic versioned gems (i.e. `~> 1.1` vs `>= 1.1`) because the former does not allow tools to automatically update dependencies to their newest versions (e.g. a tool that uses bundler to automatically open PRs with dependency updates).

It would be great to have a feature that can update dependency version constraints in the Gemfile so people can take advantage of both being able to programatically update dependencies and pessimistic version constraints.

**Comment by deivid-rodriguez** [comment]
I think we ended up rejecting this at https://github.com/rubygems/rubygems/issues/3282. Reason: we have too many features, I think this would be a good idea for a plugin.

**Comment by thisismydesign** [comment]
Thanks for explaining.

**Comment by deivid-rodriguez** [comment]
No problem. For what it's worth, the link I posted was wrong. It's this one the one I meant to post: https://github.com/rubygems/bundler/pull/6597.
