### ISSUE TITLE
Add proxy support from SSH

### ISSUE THREAD

**Issue by wmorgue** [rubygems/rubygems#3370]
I use network connection from SSH tunnel as proxy.

I have a problem:  bundle can't install gem from `Gemfile` because i think him don't understand UNIX socket, e.g. local variable: `export {http,https,ftp}_proxy="socks5://127.0.0.1:3050"`
from `ssh -D 3050 bundle_user@ip_address`

Did you add proxy support like a `bundle -p socks5://IP:PORT` ?

**Comment by LooTKinGz** [comment]
File updates
