### ISSUE TITLE
Update documentation around checking in the Gemfile.lock

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems#3372]
When Bundler first shipped, we gitignored the Gemfile.lock inside gems, following the advice given in [this blog post](http://yehudakatz.com/2010/12/16/clarifying-the-roles-of-the-gemspec-and-gemfile/).

Over time, however, it became clear that this practice forces the pain of broken dependencies onto new contributors, while leaving existing contributors potentially unaware of the problem. As a result, we have revised our guidance for gem authors to now [recommend checking in the lock for gems](http://bundler.io/v1.15/guides/creating_gem.html#testing-our-gem). We have also [removed Gemfile.lock from the gitignore file generated in new gems](https://github.com/bundler/bundler/pull/5822#issuecomment-316530749).

This is a tracking ticket for any further documentation changes needed to support gem developers in this new pattern of checking in `Gemfile.lock` to support new contributors, while continuing to run at least one CI build against the newest version of all dependencies, resolved from scratch at the time of the CI run.

**Comment by deivid-rodriguez** [comment]
Linked PR was merged in the documentation site, so I'll close this!

**Comment by pboling** [comment]
This issue is now being relitigated.
Context:
- https://github.com/ruby/rexml/issues/278#issuecomment-3076478058
- https://github.com/rubygems/bundler-site/issues/1533
