### ISSUE TITLE
S3 source support

### ISSUE THREAD

**Issue by coilysiren** [rubygems/rubygems#3382]
From: https://github.com/bundler/bundler-features/issues/46

The plugin system is mentioned in that issue, which is likely once next feature release the changes 1.12 are stable. Issues for the plugin system are here https://github.com/bundler/bundler/issues?utf8=%E2%9C%93&q=milestone%3A%221.X+--+Plugin+System%22

**Comment by rubyFeedback** [comment]
Is there an update to this? From tmaier I see that rubygems has support. Can bundler use that? If not is there some blocker?

**Comment by webandtech** [comment]
Thought I would note it is possible to use http auth from Bundler to load gems from S3. Create a CloudFront distribution, secure with basic auth if desired using Lambda. Plenty to find on Google but I posted some instructions on the wiki for this gem which I created to provide rake tasks for S3 private gem hosting. [s3_gem_host](https://github.com/webandtech/s3_gem_host) to make host

**Comment by deivid-rodriguez** [comment]
Since there's a plugin implementing this, should we close this issue?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.

**Comment by tmaier** [comment]
@deivid-rodriguez I would like to reopen this. The the solution posted by @webandtech was a different approach and not about using S3 natively or in a similar/consistent way like https://guides.rubygems.org/using-s3-source/

**Comment by deivid-rodriguez** [comment]
Hei @tmaier, this project has undergone significant changes in the last few months: most of the previous repository owners were unilaterally removed and as a result I'm no longer involved. I recommend to figure out who is maintaining this repo now and ping them instead, or alternatively open a new issue. Cheers!
