### ISSUE TITLE
Bundler: Calculate checksum during "rake build"

### ISSUE THREAD

**Issue by svoop** [rubygems/rubygems#3386]
I'm referring to the [Rubygems security guide](https://guides.rubygems.org/security/#include-checksum-of-released-gems-in-your-repository).

How about calculating the checksum as part of the `rake build` task?

I currently add the following `rake build:checksum` task to all my gems, but in order to promote checksums, it might be better to implement this on Bundler:

```ruby
namespace :build do
  desc "Build checksums of all gems in pkg directory"
  task :checksum do
    require 'digest/sha2'
    Dir.mkdir('checksum') unless Dir.exist?('checksum')
    Dir.glob('*.gem', base: 'pkg').each do |gem|
      checksum = Digest::SHA512.new.hexdigest(File.read("pkg/#{gem}"))
      File.open("checksum/#{gem}.sha512", 'w') { |f| f.write(checksum) }
    end
  end
end
```

**Comment by deivid-rodriguez** [comment]
Maybe not as a default part of `rake build`, at least for now for backwards compatibility. But I'm happy to start by providing `rake build:checksum`. What do others think?

**Comment by LuiGiovanni** [comment]
Hello, @svoop @deivid-rodriguez I would love to contribute, I haven't done an issue here before so I feel this would be perfect for me!

**Comment by deivid-rodriguez** [comment]
Thank you @LuiGiovanni, your help will be greatly appreciated :smile:

**Comment by svoop** [comment]
Cool, dig in @LuiGiovanni !
