### ISSUE TITLE
I uninstall and remove rvm everywhere, but 'gem environment' still references rvm

### ISSUE THREAD

**Issue by lovefamilychildrenhappiness** [rubygems/rubygems#3453]
I'm having a problem or would like to suggest a feature.

My current problem is: I uninstalled rvm from my machine. I removed all traces of it from any shell initialization scripts and any hidden rvm directories. Yet when I run 'gem environment', I still notice RVM references in INSTALLATION DIRECTORY and EXECUTABLE DIRECTORY and GEM PATHS. Check out what it returns:

```
$ gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.1
  - RUBY VERSION: 2.6.0 (2018-12-25 patchlevel 0) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/myuser/.rvm/gems/ruby-2.6.0
  - USER INSTALLATION DIRECTORY: /home/myuser/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /home/myuser/.rbenv/versions/2.6.0/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /home/myuser/.rvm/gems/ruby-2.6.0/bin
  - SPEC CACHE DIRECTORY: /home/myuser/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/myuser/.rbenv/versions/2.6.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/myuser/.rvm/gems/ruby-2.6.0
     - /home/myuser/.rvm/gems/ruby-2.6.0@global
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/myuser/.rbenv/versions/2.6.0/bin
     - /home/myuser/.rbenv/libexec
     - /home/myuser/.rbenv/plugins/ruby-build/bin
     - /home/myuser/.rbenv/shims
     - /home/myuser/.rbenv/bin
     - /home/myuser/.rvm/gems/ruby-2.6.0/bin
     - /home/myuser/.rvm/gems/ruby-2.6.0@global/bin
     - /usr/share/rvm/rubies/ruby-2.6.0/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /snap/bin
     - /usr/share/rvm/bin

```
Here are my current environment details:

```
$ gem env version
3.0.1

```
Now if I run gem install bundler (I am using rbenv), then it actually recreates the .rvm directory (that I already deleted). How can I make ruby gems forget about rvm?

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Did you reload your shell?

**Comment by lovefamilychildrenhappiness** [comment]
> Did you reload your shell?

Yes I reloaded the shell. And still I see references to rvm.

**Comment by lovefamilychildrenhappiness** [comment]
After a system reboot, the I no longer see references rvm. However, when I opened a new shell, it still hadn't been registered with ruby gems. Did the ruby gems binary have to be restarted somehow? And if so, what is this ruby gems binary? Obviously, with a reboot everything was restarted by linux init process and so it worked. But I want to be able to refresh without system restart.

**Comment by bronzdoc** [comment]
> it still hadn't been registered with ruby gems.
I don't understand this, what you mean?

**Comment by lovefamilychildrenhappiness** [comment]
@bronzdoc yesterday I completed removed rvm and then ran 'gem environment'. Yet it still showed references to rvm (as I showed in original question). I opened a new shell in a different window. And still in that new shell, there were references to rvm. Then I shutdown the computer. Today, I turned on the computer (and linux kernel boots, runs its init processes, which includes any ruby processes run on start up) and now there is no reference to rvm:

```
$ gem environment
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.1
  - RUBY VERSION: 2.6.0 (2018-12-25 patchlevel 0) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/myuser/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0
  - USER INSTALLATION DIRECTORY: /home/myuser/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /home/myuser/.rbenv/versions/2.6.0/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /home/myuser/.rbenv/versions/2.6.0/bin
  - SPEC CACHE DIRECTORY: /home/myuser/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/myuser/.rbenv/versions/2.6.0/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/myuser/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0
     - /home/myuser/.gem/ruby/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/myuser/.rbenv/versions/2.6.0/bin
     - /home/myuser/.rbenv/libexec
     - /home/myuser/.rbenv/plugins/ruby-build/bin
     - /home/myuser/.rbenv/shims
     - /home/myuser/.rbenv/bin
     - /home/myuser/.rbenv/shims
     - /home/myuser/.rbenv/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /snap/bin

```
Why did it take a reboot? My presumption is that some ruby process had to be restarted for the change to take effect. Maybe I am wrong. But then what else would explain the occurrence?

**Comment by lovefamilychildrenhappiness** [comment]
If you do not mind me asking, what is the difference between INSTALLATION DIRECTORY and  GEM PATHS?

**Comment by lovefamilychildrenhappiness** [comment]
Evaluating the below two lines, it seems to suggest that ruby gems looks for gems in two separate directories, Installation Directory and User Installation Directory:

```
- INSTALLATION DIRECTORY: /home/myuser/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0
- USER INSTALLATION DIRECTORY: /home/myuser/.gem/ruby/2.6.0
```

Based on that, GEM PATHS is just reaffirming the above two directories: 

```
  - /home/myuser/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0
  - /home/myuser/.gem/ruby/2.6.0
```

```
$ cd .rbenv/versions/2.6.0/lib/ruby/gems/2.6.0
$ cd gems 
$ ls
$ pwd
/home/dan/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems
$ ls
bundler-1.17.2      irb-1.0.0        net-telnet-0.2.0    rake-12.3.2  test-unit-3.2.9
did_you_mean-1.3.0  minitest-5.11.3  power_assert-1.1.3  rdoc-6.1.0   xmlrpc-0.3.0
```

Although the User Installation Directory ( and hence the second path ) does not exist for me:

```
$ cd $HOME/.gem/ruby/2.6.0
-bash: cd: /home/dan/.gem/ruby/2.6.0: No such file or directory
 ```

In other words, with a fresh rbenv installation and the refrehsing of ruby gems lookup path algorithm to reflect the rbenv installation, it appears that, by default, the installation directory (and lookup path) of gems installed would be:

```
$HOME/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems
```

**Comment by lovefamilychildrenhappiness** [comment]
I confirm that the INSTALLATION DIRECTORY is /home/myuser/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0:

$ gem install gem-path 
$ cd $HOME/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0/gems
$ ls -l | grep gem-path
drwxr-xr-x 5 myuser myuser 4096 Mar 28 17:02 gem-path-0.6.2
$ gem list | grep bigdecimal # one of the gems always bundled with ruby
$ gem path bigdecimal
/home/myuser/.rbenv/versions/2.6.0/lib/ruby/2.6.0/bigdecimal.rb

And notice the directory of the bigdecimal gem is /home/myuser/.rbenv/versions/2.6.0/lib/ruby/2.6.0, whereas when I install gems, it is: /home/myuser/.rbenv/versions/2.6.0/lib/ruby/gems/2.6.0. That's because bigdecimal is packaged with ruby and always installed in any 2.6.0 ruby installation. When we install gems, they should not go in the same directory as default ruby gems.

**Comment by bronzdoc** [comment]
@lovefamilychildrenhappiness 

The Rubygems cli(`gem`) runs on demand, It set the values for it's environment by reading a configuration file `.gemrc`, setting command line flags or reading environment variables, i.e "GEM_HOME", "GEM_PATH" if these two things are not present it would set the defaults by reading the ` Ruby Configuration`(`RbConfig::CONFIG`) which is generated by ruby itself.

Maybe in the transition from rvm to rbenv there was still some rvm scrips that where modifying any of the things I mentioned? who knows, but i'm glad you solved your problem.
