### ISSUE TITLE
bundle gem always uses RSpec, even if configured for minitest

### ISSUE THREAD

**Issue by mperham** [rubygems/rubygems#3454]
Hi, I'm creating a new gem with Bundler 2.1.4:

```
# From bundle-gem man page:
# Note that these options can also be specified via Bundler's global configuration file using the
# following names:
#       o   gem.test

$ bundle config gem.test minitest
$ bundle config gem.test
Settings for `gem.test` in order of priority. The top value will be used
Set for the current user (/Users/mikeperham/.bundle/config): "minitest"
$ bundle gem somegem -t
Creating gem 'somegem'...
      [elided]
      create  somegem/.rspec
      create  somegem/spec/spec_helper.rb
      create  somegem/spec/somegem_spec.rb
```

Bundler creates an RSpec test suite for me, rather than using minitest as configured.

**Comment by deivid-rodriguez** [comment]
Interesting. I can reproduce.

It happens when, even if you have configured `gem.test`, you specify the `-t` option. So the bug is that the `-t` option without a value always defaults to `RSpec` instead of respecting the `gem.test` setting.

The workaround is better than the problematic command, though. SInce you have already configured your preference, don't pass the `-t` option and use `bundle gem somegem` instead. :smile:

**Comment by deivid-rodriguez** [comment]
Actually, after reading `bundle gem --help`

>     -t, --test=minitest, --test=rspec
>          Specify the test framework that Bundler should use when generating the project. Acceptable values are minitest and rspec. The GEM_NAME.gemspec will be configured and a skeleton test/spec directory will be created based
>          on this option. If this option is unspecified, an interactive prompt will be displayed and the answer will be saved in Bundler´s global config for future bundle gem use. If no option is specified, the  default  testing
>          framework is RSpec.

I think the current behavior is exactly what's documented :thinking:.

Except maybe "If no option is specified, the default testing framework is RSpec" could be clarified to "If no value is given for the option, the default testing framework is RSpec".

**Comment by mperham** [comment]
From my POV, it makes no sense for -t to ignore the gem.test config. That’s literally why I didn’t give a value, because I had globally config’d it.

**Comment by deivid-rodriguez** [comment]
I mean, I don't necessarily disagree with you, I'm just saying that the current behavior is expected and documented. But we can change it.

The way it currently works is:
 
| command line | result |
| ---| --- |
| No `-t` option given | Use whatever is configured or prompt and configure if nothing configured |
| `-t` option given without a value | Use RSpec |
| `-t` option given with a value | Use the value |

What you are suggesting would be something like:

| command line | result |
| ---| --- |
| No `-t` option given | Use whatever is configured or prompt and configure if nothing configured |
| `-t` option given without a value | Use whatever is configured or RSpec if nothing configured |
| `-t` option given with a value | Use the value |

Or maybe we could even fully drop the RSpec default and make it:

| command line | result |
| ---| --- |
| No `-t` option given | Use whatever is configured or prompt and configure if nothing configured |
| `-t` option given without a value | Use whatever is configured or prompt and configure if nothing configured |
| `-t` option given with a value | Use the value |

**Comment by deivid-rodriguez** [comment]
I think the last option is the least surprising and shows no preference for any testing framework (although I do strongly prefer `RSpec` :sweat_smile:).

**Comment by mperham** [comment]
PoLS FTW!

**Comment by deivid-rodriguez** [comment]
Although...

What if I configure `bundler` to not create tests for my gems (`bundle config gem.test false`), but then I pass `-t` to a specific `bundle gem` invokation because I _do_ want to add tests to that gem skeleton. I think it would be suprising that my `false` default is applied in that case.

With that in mind, I don't think none of the alternatives I proposed is actually good. Perhaps we could ignore the `false` configuration in the "`-t` without a value" case, but still, why explictly pass `-t` if you have configured `bundler` to always add tests to you gem skeletons?

:thinking:

**Comment by mperham** [comment]
I was under the impression that Bundler would not add tests unless I passed -t. If one does pass -t, I would expect it to ask if false is the global setting.

**Comment by deivid-rodriguez** [comment]
> I was under the impression that Bundler would not add tests unless I passed -t

So perhaps we need to improve the documentation and CLI messages. I think the default `bundle gem` behaviour with nothing configured is not bad although perhaps it could clarified that the "none" choice is also sticky:

```
 $ bundle gem sadfsdsadasd
Creating gem 'sadfsdsadasd'...
Do you want to generate tests with your gem?
Type 'rspec' or 'minitest' to generate those test files now and in the future. rspec/minitest/(none): minitest
MIT License enabled in config
Code of conduct enabled in config
      create  sadfsdsadasd/Gemfile
      create  sadfsdsadasd/lib/sadfsdsadasd.rb
      create  sadfsdsadasd/lib/sadfsdsadasd/version.rb
      create  sadfsdsadasd/sadfsdsadasd.gemspec
      create  sadfsdsadasd/Rakefile
      create  sadfsdsadasd/README.md
      create  sadfsdsadasd/bin/console
      create  sadfsdsadasd/bin/setup
      create  sadfsdsadasd/.gitignore
      create  sadfsdsadasd/.travis.yml
      create  sadfsdsadasd/test/test_helper.rb
      create  sadfsdsadasd/test/sadfsdsadasd_test.rb
      create  sadfsdsadasd/LICENSE.txt
      create  sadfsdsadasd/CODE_OF_CONDUCT.md
Initializing git repo in /home/deivid/Code/playground/sadfsdsadasd
Gem 'sadfsdsadasd' was successfully created. For more information on making a RubyGem visit https://bundler.io/guides/creating_gem.html
```
> If one does pass -t, I would expect it to ask if false is the global setting.

What exactly would you expect, sorry?

**Comment by mperham** [comment]
If (-t is passed && gem.test == false) then ask.

**Comment by deivid-rodriguez** [comment]
Oh, I see. That makes sense to me, yeah.

**Comment by bronzdoc** [comment]
@deivid-rodriguez are you working on this? I'll like to work on it if not

**Comment by deivid-rodriguez** [comment]
No, please go ahead.

**Comment by FTLam11** [comment]
Hey @bronzdoc, mind if I try tackling this one? Let me know what you'd like to do, I'll defer the decision making to you.

There is a lazy default being set [here](https://github.com/rubygems/rubygems/blob/master/bundler/lib/bundler/cli.rb#L573):

 ```ruby
method_option :test, :type => :string, :lazy_default => "rspec", :aliases => "-t", :banner =>"rspec"
```

**Comment by bronzdoc** [comment]
@FTLam11 go ahead! :)
