### ISSUE TITLE
binstub error: rails has no executables, but you may want one from a gem it depends on.

### ISSUE THREAD

**Issue by lovefamilychildrenhappiness** [rubygems/rubygems#3456]
I have a repo demonstrating the issue:

https://github.com/lovefamilychildrenhappiness/RbenvRubyGemsBundlerTest

The bundle.sh script works perfectly:

https://github.com/lovefamilychildrenhappiness/RbenvRubyGemsBundlerTest/blob/master/bundle.sh

But the bundle2.sh does not:

https://github.com/lovefamilychildrenhappiness/RbenvRubyGemsBundlerTest/blob/master/bundle2.sh

I don't want to use 

```
bundle exec rails s
```

to start a rails server.

Instead I simply want to do:

```
rails s
```

Since rails is a command executed from terminal, it requires a binstub. But when I try to create a binstub inside the project with bundler, I get the following error:

```
$ bundle binstub rails
rails has no executables, but you may want one from a gem it depends on.
  railties has: rails
  bundler has: bundle, bundler
```

So I try the railties binstub:

```
$ bundle binstub railties
Skipped rails since it already exists.
If you want to overwrite skipped stubs, use --force.
```

As you can see, no binstub is created. All I would like to do is run 'rails s' instead of 'bundle exec rails s', while also having the advantage of installing the gems local to the project via --path=vendor/bundle (which is equivalent to --deployment). Why does it produce these errors? I provided a demo project reproducing the error.

**Comment by colby-swandale** [comment]
You're instructing Bundler to install your gems into `vendor/bundle` - which will generate the binstub into `vendor/bundle/ruby/<ruby-version-abi>/bin`.

If you want a binstub that you can use without Bundler, you need to install Rails with `gem install rails` or don't use the `--path` option in Bundler.

**Comment by bronzdoc** [comment]
I'm going to close this since I think Colby's answer explains the behavior, let us know if you have a other question @lovefamilychildrenhappiness

**Comment by indirect** [comment]
@colby The `bundle binstub` command is completely different from the bin stubs that Bundler generates when installing gems. Here's a tiny example:

```
❯ bundle init
Writing new Gemfile to /Users/andre/src/indirect/testcases/binstubs/Gemfile
❯ bundle add rack                                                                                                                            
Fetching gem metadata from https://rubygems.org/...............                                                                              
Resolving dependencies...                                             
Fetching gem metadata from https://rubygems.org/...............
Resolving dependencies...
Using bundler 2.1.4                                                   
Fetching rack 2.2.2                                                   
Installing rack 2.2.2
❯ bundle info --path rack
/Users/andre/.gem/ruby/2.7.0/gems/rack-2.2.2
❯ which rackup
/Users/andre/.gem/ruby/2.7.0/bin/rackup
❯ bundle binstub rack
❯ tree
.
├── Gemfile
├── Gemfile.lock
└── bin
    └── rackup

1 directory, 3 files
❯ ./bin/rackup -h
Usage: rackup [ruby options] [rack options] [rackup config]
[...]
```

@lovefamilychildrenhappiness the Rails team has decided that the standalone `rails` command from the Railties gem is for generating new Rails apps, and not for running Rails servers. Both Rails and Bundler create a binstub for the `rails` command in the directory `bin/`. That means you need to run `bin/rails s` instead.
