### ISSUE TITLE
Bundler merge with rubygems

### ISSUE THREAD

**Issue by RDIL** [rubygems/rubygems#3472]
Hi,
I'm just wondering if somebody could link more information, I didn't realize bundler and rubygems are the same thing until now and I have a lot of questions.
Thanks in advance :)

**Comment by deivid-rodriguez** [comment]
Nothing have changed from an end user point of view, we have just became a monorepo in terms of development.

**Comment by RDIL** [comment]
So I'm assuming this means less duplicated code.

One question I have is whether you guys have plans to start including bundler with rubygems so you never really need to `gem install bundler`?

**Comment by simi** [comment]
Bundler is part of default ruby installation starting from 2.6 AFAIK.

**Comment by RDIL** [comment]
Right but in the future will updating my rubygems version also update bundler?
