### ISSUE TITLE
gem fetch a specific prerelease version 

### ISSUE THREAD

**Issue by asbjornu** [rubygems/rubygems#3474]
I'm experiencing the same problem as [this 10 year old bug](https://help.rubygems.org/discussions/questions/38-gem-fetch-a-specific-prerelease-version) where `gem fetch <gem-name> --prerelease --version <pre-release-version-number>` doesn't work. I would think a 10 year old bug should be fixed, so this problem may be with the GitHub Package Registry I'm using and not with RubyGems, but I need assistance in figuring out which it is.

The command I'm running is:

```
gem fetch kramdown-plantuml --quiet --prerelease --source https://asbjornu:REDACTED@https://rubygems.pkg.github.com/SwedbankPay --version 1.1.0.pre.PullRequest0017.pre.0032
```

The command fails with the following error:

```
ERROR:  Could not find a valid gem 'kramdown-plantuml' (= 1.1.0.pre.PullRequest0017.pre.0032), here is why:
          Unable to download data from https://asbjornu:REDACTED@https//rubygems.pkg.github.com/SwedbankPay/ - no such name (https://asbjornu:REDACTED@https//rubygems.pkg.github.com/SwedbankPay/specs.4.8.gz)
ERROR:  Possible alternatives: kramdown-plantuml
```

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.1.2
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by simi** [comment]
seems fixed, I was able to download rails prerelase with no troubles

```
gem fetch rails --prerelease --version 7.1.0.beta1
Fetching rails-7.1.0.beta1.gem
Downloaded rails-7.1.0.beta1
```

If there is problem with GitHub Packages, feel free to ping their support.
