### ISSUE TITLE
`bundle info` does not indicate a gem which has been deleted, unlike `bundle show`

### ISSUE THREAD

**Issue by shalvah** [rubygems/rubygems#3493]
(Sorry, I didn't follow the template because this is pretty straightforward...)

## To reproduce:
1. Install a gem by adding it to your Gemfile/gemspec and running `bundle install` (I installed the `logstash-core-plugin-api` gem)
2. Locate the gems installation path (on my machine it is `C:/jruby-9.2.11.1/lib/ruby/gems/shared/gems/`) and delete the folder containing the installed gem (on mine, it is `logstash-core-plugin-api-2.1.28-java`)
3. Run `bundle info <gem>`

## Actual output:

```bash
> bundle info logstash-core-plugin-api
  * logstash-core-plugin-api (2.1.28)
        Summary: Define the plugin API that the plugin need to follow.
        Homepage: http://www.elastic.co/guide/en/logstash/current/index.html
        Path: C:/jruby-9.2.11.1/lib/ruby/gems/shared/gems/logstash-core-plugin-api-2.1.28-java
```

## What's wrong:
The output does not indicate that the folder has been removed. Compare this to the output of `bundle show`, which is now deprecated:

```bash
> bundle show logstash-core-plugin-api
[DEPRECATED] use `bundle info logstash-core-plugin-api` instead of `bundle show logstash-core-plugin-api`
The gem logstash-core-plugin-api has been deleted. It was installed at: C:/jruby-9.2.11.1/lib/ruby/gems/shared/gems/logstash-core-plugin-api-2.1.28-java
```

**Comment by deivid-rodriguez** [comment]
Thanks for reporting! This bit was probably left behind when moving the implementation.
