### ISSUE TITLE
Make bundler --standalone setup.rb paths absolute

### ISSUE THREAD

**Issue by bjfish** [rubygems/rubygems#3505]
**Do you have a reproduction script?**
Using any project:
`bundle install --standalone`

**What were you expecting to happen?**
The generated `setup.rb` does not contain relative path operators.
E.g.
```
$:.unshift "#{path}/#{ruby_engine}/#{ruby_version}/gems/rake-13.0.1/lib"
```

**What actually happened?**
The generated paths contain `/../` relative path operators.
```
path = File.expand_path('..', __FILE__)
$:.unshift "#{path}/../#{ruby_engine}/#{ruby_version}/gems/rake-13.0.1/lib"
```

**Background**
I believe the generated file should not append relative paths to the `$LOAD_PATH` for a few reasons:
* It may affect other code which inspects the `$LOAD_PATH` not expecting relative entries.
* Relative paths will need to be expanded before load path lookup.
* In this case, the path already appears absolute so making the path relative appears unnecessary.

**Ideas**
```
path = File.expand_path('../..', __FILE__)
$:.unshift "#{path}/#{ruby_engine}/#{ruby_version}/gems/rake-13.0.1/lib"
```

```
$:.unshift File.expand_path("#{path}/../#{ruby_engine}/#{ruby_version}/gems/rake-13.0.1/lib")
```

**Reference**
The `setup.rb` generation code appears here:
https://github.com/rubygems/rubygems/blob/7f5d3cf3cbd2822eb281ac8836abbd61ef4a9671/bundler/lib/bundler/installer/standalone.rb#L13-L21

**Environment**
Bundler version 2.1.4

**Comment by eregon** [comment]
A bug triggered by this is that code in the FFI gem then fails to find itself in $LOAD_PATH:
https://github.com/ffi/ffi/blob/1a6cbfce4df148f1ff2b23c77a05395781034580/lib/ffi.rb#L17-L18

**Comment by deivid-rodriguez** [comment]
Thanks for the report and also for the realworld problem caused by it.

Yep, I fully agree that we should use canonical absolute paths instead of unresolved ones with relative path segments like here.

I guess the first idea would work just fine!

**Comment by eregon** [comment]
FWIW for this specific case I think an expanded path would be enough, no need for a realpath.
:+1: on the first idea as well

**Comment by bjfish** [comment]
The PR to resolve this resulted in generating this style:
```
$:.unshift File.expand_path("#{path}/../#{ruby_engine}/#{ruby_version}/gems/rake-13.0.1/lib")
```
The other idea mentioned above ran into issues because the `setup.rb` could be generated anywhere based on the `--path` parameter and needs to refer to both gem paths and the current project path, E.g.:
```
$:.unshift "#{path}/#{ruby_engine}/#{ruby_version}/bundler/gems/rspec-mocks-11ecaedaaf76/lib"
$:.unshift "#{path}/../../rspec/lib"
```
