### ISSUE TITLE
bundle update gem produces: Git error: command `git reset --hard 3dc03656abed171d587cf7366e698da30e4502f7` in directory

### ISSUE THREAD

**Issue by lovefamilychildrenhappiness** [rubygems/rubygems#3511]
I have a gem stored in my git repo. In order to pull in the latest commits, I run the following commands:

```
$ bundle show medical_plus
$ bundle update medical_plus
```

And it usually works. But now when I run the update I get this:

```
Git error: command `git reset --hard 3dc03656abed171d587cf7366e698da30e4502f7` in directory
/home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems/medical-plus-3dc03656abed has failed.
If this error persists you could try removing the cache directory
'/home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/cache/bundler/git/medical-plus-a081725469ab40c6b73f7e8e3dd93c92b8da44e0
```
If I remove the cache, I get this:

```
Retrying `git clone 'https://github.com/MyUser/medical-plus' "/home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/cache/bundler/git/medical-plus-a081725469ab40c6b73f7e8e3dd93c92b8da44e0" --bare --no-hardlinks --quiet` due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone 'https://github.com/MyUser/medical-plus' "/home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/cache/bundler/git/medical-plus-a081725469ab40c6b73f7e8e3dd93c92b8da44e0" --bare --no-hardlinks --quiet` in directory /var/www/html/medical has failed.
```

Bundler version 1.16.1
rbenv 1.1.2-26-gc6324ff
ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-linux]
RubyGems Environment:
  - RUBYGEMS VERSION: 2.6.11

What is this error I am getting?

**Comment by deivid-rodriguez** [comment]
Hi @lovefamilychildrenhappiness!

You're using very old versions of both bundler, ruby and rubygems. Could you upgrade rubygems and bundler and report back? To upgrade, run:

```
$ gem update --system
$ gem install bundler
$ bundle update --bundler
```

**Comment by lovefamilychildrenhappiness** [comment]
@deivid-rodriguez the problem is that the ec2 instance ran out of disk space. But I know why the ec2 ran out of disk space! It's because I have a private gem in my git repo. And every time I run 'bundle update my-gem', it creates a new instance of the gem in the following directory:

/home/ubuntu/.rbenv/versions/2.4.1/lib/ruby/gems/2.4.0/bundler/gems

Now I have dozens of the same gem in this directory. Why is this happening? It's eating up the disk space on my virtual machine.

**Comment by deivid-rodriguez** [comment]
I'm sorry I never replied to this. Does running `bundle clean` remove all this stuff? If yes, can you try setting the `BUNDLE_AUTO_CLEAN_WITHOUT_PATH` environment variable to see if that fixes your problem permanently?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
