### ISSUE TITLE
Restore `Gem::Deprecate` to the way it worked in the previous release

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#3512]
We changed `Gem::Deprecate` recently to consider versions instead of dates & months when deprecating stuff.

I think this is a better way of deprecating things, but unfortunately, libraries out there extend their classes with `Gem::Deprecate` and use it to deprecate methods this way.

So we should probably restore `Gem::Deprecate` to work in the same way as before, and add our new _private_ mechanism for deprecating rubygems things using version horizons instead of dates.

_Originally found by @simi in https://github.com/rubygems/rubygems/pull/3414#issuecomment-612507160_

**Comment by simi** [comment]
Seems like release blocker for me, is there any label for this kind of problem?

**Comment by deivid-rodriguez** [comment]
I added it to the next minor's milestone, so that we don't release it without closing this ticket first. Sounds good?

**Comment by deivid-rodriguez** [comment]
We don't have such a label, but I guess we could add it as a new `type: release blocker` :shrug:

**Comment by simi** [comment]
> Sounds good?

Yes!

**Comment by bronzdoc** [comment]
Ah bummer 😒

**Comment by bronzdoc** [comment]
I guess we will have to put deprecations in our deprecation method 😄

**Comment by simi** [comment]
@bronzdoc or accept fact what has happened with `Gem::Deprecate` over time and keep it as is and roll internal deprecation for internal usage. IMHO we need to rollback this change back an prepare proper (maybe RFC based) approach how to change/deprecate `Gem::Deprecate` over the time.

**Comment by simi** [comment]
:information_source: just got into this trouble again today using `rqrcode_core` gem. Should I prepare rollback for now and can we discuss the other part later in separated case? We can also sync on Slack if needed.

**Comment by bronzdoc** [comment]
I'll submit a PR soon @simi
