### ISSUE TITLE
bundler doesn't install to /var/lib/gems/2.X.X/gems/ system gems directory

### ISSUE THREAD

**Issue by xetum** [rubygems/rubygems#3513]
with a `Gemfile`:

    source "https://rubygems.org/"
    gem 'i2c-lcd', git: 'https://github.com/daisukesuzuki/i2c-lcd'

`bundle install` installs `i2c` dependency gem to `/var/lib/gems/2.X.X/gems/` but `i2c-lcd` gets istalled as `~/.bundle/ruby/2.X.X/i2c-lcd-2346731402fe`. What should I do to install it to `/var/lib/gems/2.X.X/gems/` like `i2c`? Thanks

**Comment by deivid-rodriguez** [comment]
Hi @xetum. I need more information about your environment to at least try to help you.

Could you please post the result of running `bundle env` and `gem env` in your environment?

Thanks!

**Comment by xetum** [comment]
francesc@francesc:/tmp$ bundle env
    ## Environment
    
    ```
    Bundler       2.1.4
      Platforms   ruby, x86-linux
    Ruby          2.3.1p112 (2016-04-26 revision 0) [i386-linux-gnu]
      Full Path   /usr/bin/ruby2.3
      Config Dir  /etc
    RubyGems      2.5.2.1
      Gem Home    /var/lib/gems/2.3.0
      Gem Path    /home/francesc/.gem/ruby/2.3.0:/var/lib/gems/2.3.0:/usr/lib/i386-linux-gnu/rubygems-integration/2.3.0:/usr/share/rubygems-integration/2.3.0:/usr/share/rubygems-integration/all
      User Home   /home/francesc
      User Path   /home/francesc/.gem/ruby/2.3.0
      Bin Dir     /usr/local/bin
    Tools         
      Git         2.7.4
      RVM         not installed
      rbenv       not installed
      chruby      not installed
    ```
    
    ## Bundler Build Metadata
    
    ```
    Built At          2020-01-05
    Git SHA           32a4159325
    Released Version  true
    ```
    
    ## Gemfile
    
    ### Gemfile
    
    ```ruby
    source "https://rubygems.org/"
    gem 'i2c-lcd', git: 'https://github.com/daisukesuzuki/i2c-lcd'
    ```
    
    ### Gemfile.lock
    
    ```
    <No /tmp/Gemfile.lock found>
    ```
    francesc@francesc:/tmp$ gem env
    /usr/lib/ruby/2.3.0/rubygems/commands/environment_command.rb:154: warning: Insecure world writable dir /tmp/ in PATH, mode 041777
    RubyGems Environment:
      - RUBYGEMS VERSION: 2.5.2.1
      - RUBY VERSION: 2.3.1 (2016-04-26 patchlevel 112) [i386-linux-gnu]
      - INSTALLATION DIRECTORY: /var/lib/gems/2.3.0
      - USER INSTALLATION DIRECTORY: /home/francesc/.gem/ruby/2.3.0
      - RUBY EXECUTABLE: /usr/bin/ruby2.3
      - EXECUTABLE DIRECTORY: /usr/local/bin
      - SPEC CACHE DIRECTORY: /home/francesc/.gem/specs
      - SYSTEM CONFIGURATION DIRECTORY: /etc
      - RUBYGEMS PLATFORMS:
        - ruby
        - x86-linux
      - GEM PATHS:
         - /var/lib/gems/2.3.0
         - /home/francesc/.gem/ruby/2.3.0
         - /usr/lib/i386-linux-gnu/rubygems-integration/2.3.0
         - /usr/share/rubygems-integration/2.3.0
         - /usr/share/rubygems-integration/all
      - GEM CONFIGURATION:
         - :update_sources => true
         - :verbose => true
         - :backtrace => false
         - :bulk_threshold => 1000
      - REMOTE SOURCES:
         - https://rubygems.org/
      - SHELL PATH:
         - /home/francesc/.sdkman/candidates/kotlin/current/bin
         - /home/francesc/.cargo/bin
         - 
         - /home/francesc/.composer/vendor/bin
         - /home/francesc/bin
         - /opt/rust/bin
         - /opt/android-studio/bin
         - /opt/android-studio/gradle/gradle-2.8/bin
         - /usr/local/MATLAB/R2011a/bin
         - /usr/local/CodeSourcery/Sourcery_CodeBench_Lite_for_ARM_EABI/bin
         - /usr/local/go/bin
         - /home/francesc/local/scala-2.12.2/bin
         - /home/francesc/netbeans-8.0.2/bin
         - /home/francesc/.shoes/walkabout
         - /usr/local/sbin
         - /usr/local/bin
         - /usr/sbin
         - /usr/bin
         - /sbin
         - /bin
         - /usr/local/games
         - /usr/games
         - /snap/bin

**Comment by deivid-rodriguez** [comment]
Unfortunately I cannot reproduce the issue.

I think it's related to the fact that you're using debian's ruby and all the related stack instead of a ruby version manager like rbenv or similar.

So if you can create a debian docker image where the issue can reproduced, I'm happy to have a look!

**Comment by xetum** [comment]
I've tried with a different box, and different gem with dependencies. The point is that when trying to install from git, the gem gets installed to `$HOME/.bundle/ruby/2.5.0/`, not its dependencies, which get installed to `$GEM_HOME`. This is consistent with `bundle install` documentation:

> Of these three, the first two could theoretically be performed by chowning the resulting files to $SUDO_USER. The third, however, can only be performed by invoking the git command as the current user. Therefore, git gems are downloaded and installed into ~/.bundle rather than $GEM_HOME or $BUNDLE_PATH.

It's a pity, because I was just trying to use `bundle` instead of `gem` because of its capability to install git gems

**Comment by deivid-rodriguez** [comment]
Yeah, I understood your issue.

Thanks for the pointer to the docs. Let me check this again, because when I tried this, it seemed to me that everything was getting installed to the same location as you expect.

I'll get back.
