### ISSUE TITLE
required_ruby_version should be mandatory

### ISSUE THREAD

**Issue by marcandre** [rubygems/rubygems#3515]
My current problem is that many gems are not publishing their `required_ruby_version`.

This means that a Gemfile/gemspec must know what is the maximum version of a gem for a given version of Ruby, instead of bundler figuring it out for us.

It takes about one minute for the gem author to add the line. When the author doesn't, everyone that uses the gem, directly or indirectly, may have to figure out the maximum version and specify it in their own gemfiles.

Note that there is currently no good way to correct this mistake. Once it is done, the only option [is to yank the gem](https://github.com/rubygems/rubygems/issues/1506#issuecomment-188472423) which is typically not what one wants to do.

`required_ruby_version` is currently in the "Optional" section of [the spec](https://guides.rubygems.org/specification-reference/). It's not even in the "Recommended" section!

It should be mandatory and enforced.

**Comment by simi** [comment]
This would be good candidate for [rfc](https://github.com/rubygems/rfcs).

Moving to `Recommended` section could be done immediately IMHO (https://github.com/rubygems/guides/blob/1c2082109faad00bf004196fe40819e724791d0e/specification-reference.md#recommended-gemspec-attributes).

**Comment by marcandre** [comment]
Created https://github.com/rubygems/rfcs/pull/26
