### ISSUE TITLE
[Discuss] Is there exist a correct why to remove a gem from bundler but not touch Gemfile.

### ISSUE THREAD

**Issue by zw963** [rubygems/rubygems#3529]
Maybe describe my pain point is the easist way to explain this issue.

I use pry for ruby development debug, it work quite well for me, with pry-nav and several others useful plugin, day and day, in fact, because those tools so useful, so,  instead of add those gem into bundler for each of my project, i save those gem into one folder, and then add this folder to $LOAD_PATH ($RUBYLIB ENV), it work quite well too for me.

until oneday, one guy on our team add a new gem into bundler,  pry-byebug. (yes, i know this gem author @deivid-rodriguez  is the maintainer of rubygems too, :laughing: ), it change pry some common default behavior, for simple describe here, it always add break point next **the line of binding.pry** and make code like "binding.of_caller(2).pry" not working.

so, my issue is:

1. I can't remove pry-byebug gem in my Gemfile, because it used by my others team member.
2. But i want silent pry-byebug gem (remove it from $LOAD_PATH) for my local development laptop.(sorry again @deivid-rodriguez)

is there a more easy why to do this? maybe there exists a hook for bundler, i can handle remove pry-buybug from $LOAD_PATH there, 
i don't know anyway, for now, i have to use a dirty solution, i copy a **EMPTY** version pry-byebug to my local folder,  and require it before bundler, it working, but, i just want to know if there is a easy solution for **REMOVE a gem from bundler but not touch Gemfile**

**Comment by simi** [comment]
Hello.

AFAIK there's no direct support in RubyGems or Bundler for this. Good practice is to make team decision about shared dev-tools. It could be possible to specify `require: false` in Gemfile and let this gem load when needed only during development.

:thinking: Maybe it would be possible for you to use https://bundler.io/man/bundle-config.1.html#LOCAL-GIT-REPOS and just make the locally cloned gem dummy. But I have never tried that.

**Comment by zw963** [comment]
>  Maybe it would be possible for you to use https://bundler.io/man/bundle-config.1.html#LOCAL-GIT-REPOS and just make the locally cloned gem dummy. But I have never tried that.

Thank you,  i read it, but this solution still need change Gemfile anyway, and need run `bundle config` for each project too,  so, i consider it was not a ideal solution.

**Comment by deivid-rodriguez** [comment]
Another thing I've seen out there is to use `eval_gemfile(Gemfile.local)` where each developer can customize her local gems in there. With this approach you have to be careful of not committing the local lockfile changes to source control, but you might find it acceptable. Also, your workaround is pretty smart :)

Anyways, we don't intend to support anything like this so you'll need to leave with the workaround that works best for you.

My personal advice is the same @simi gave you: make team decisions about shared dev tools.

**Comment by zw963** [comment]
> My personal advice is the same @simi gave you: make team decisions about shared dev tools.

Thank you, that not easy, because we are remote team.

> Also, your workaround is pretty smart :)

Yes, it is working, and no need change anythings on my projects, anyway,  thank all guys help, i will close it.
