### ISSUE TITLE
Deprecate `Gem::Deprecate`

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#3539]
We would like to deprecate this module, because we don't like the way it's implemented (date based), and because we don't think rubygems should provide this kind of functionality.

Deprecating this, however, is tricky, because we shouldn't bother end users using deprecated methods. They are responsible for updating their code to not use deprecated stuff directly, but they are not responsible for the deprecation system used to show the deprecation message to them.

Deprecation messages about `Gem::Deprecate` should only be displayed to library authors, but not to end users.

An raw idea that came to my mind was to detect whether we are in a library context by looking for a `*.gemspec` file from the CWD and up. I think that would properly detect _most_ of the cases for library development, since most gem authors commit the `.gemspec` file to source control.

References: https://github.com/rubygems/rubygems/pull/3536.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by simi** [comment]
Maybe we can scan gem `rb` files with simple regexp for extending `Gem::Deprecate` during gem build (as an another specification validation). I think that would catch every problem I have spotted recently.

**Comment by deivid-rodriguez** [comment]
Yeah, I thought of that too, but doing static analysis on code via regexps is very error prone... I'm not sure I want to go that way.

Would do you think of my proposal? Do you forsee additional issues other that not showing the deprecation to gems not committing their `.gemspec` file?

Also, we should use https://github.com/akr/gem-codesearch to see how frequent this usage is currently.

**Comment by hsbt** [comment]
How notice/announce the methods deprecation to library users after this?

Like https://github.com/rubygems/rubygems/pull/3412 is not only gemspec and end-users.

**Comment by deivid-rodriguez** [comment]
Sorry @hsbt. I couldn't understand your message well, can you try to make it more clear?

My point is that library users don't need to know about this deprecation, because they're not using `Gem::Deprecate` directly. Library authors migrating from `Gem::Deprecate` to a separate deprecation system should be transparent to end users.

**Comment by hsbt** [comment]
My concerns are

1. Ex. https://github.com/stripe/stripe-ruby/blob/master/lib/stripe/resources/account.rb#L5 uses `Gem::Deprecate` directly. I could find over the 100+ gems still use it with gem-codesearch. How to care these gems?
2. After deprecation, How to deprecate the public API of RubyGems?(Maybe, https://github.com/rubygems/rubygems/issues/3539#issuecomment-617688803 is the answer of this)

**Comment by deivid-rodriguez** [comment]
> Ex. https://github.com/stripe/stripe-ruby/blob/master/lib/stripe/resources/account.rb#L5 uses Gem::Deprecate directly. I could find over the 100+ gems still use it with gem-codesearch. How to care these gems?

This is what this issue is about. How to notify `stripe-ruby` authors about this, without bothering all the users of `stripe-ruby` with deprecation messages they cannot fix or care about.

**Comment by hsbt** [comment]
I'm not sure what you said the problem. If the maintainer of strippe-ruby marked the some of methods as deprecated, the end user should stop to use it.

What's the problem about this use-case?

**Comment by deivid-rodriguez** [comment]
Say `stripe-ruby` maintainer is using `Gem::Deprecate` to deprecate method `foo` in favour of method `bar`.

Then we want end users to see the following when they use method `foo`:

> INFO: Calling `foo` is deprecated, please use `bar`.

But we don't want end users to see the following when using method `foo`:

> INFO: Using `Gem::Deprecate` is deprecated, use a different deprecation system.
> INFO: Calling `foo` is deprecated, please use `bar`.

Because they don't care about the first message.

**Comment by simi** [comment]
:thinking: around, what's the problem with `Gem::Deprecate` actually? Why we would like to remove it?

**Comment by deivid-rodriguez** [comment]
I personally don't like it because it's based on dates on it's hard for us to predict dates. It hasn't really worked for us historically, and it's been showing confusing messages to users about thing being removed in way past dates.

That said, I agree that at this point, if many people is still finding it useful, it's simpler to just leave it there.

**Comment by hsbt** [comment]
Finally, I understood the problem since https://github.com/rubygems/rubygems/pull/3414/

@deivid-rodriguez Thanks, I also understood the problem. We should notice the **only** build time to the gem maintainer about the old `Gem::Deprecate#deprecate` method with EOL date. Right?

**Comment by simi** [comment]
Yes. But how to do that?

Dne st 22. 4. 2020 13:01 uživatel Hiroshi SHIBATA <notifications@github.com>
napsal:

**Comment by deivid-rodriguez** [comment]
I think deprecating `Gem::Deprecate` should be low priority for us. We can soft-deprecate it via source code comments and `# :nodoc:`, and reevaluate at some other future time

**Comment by deivid-rodriguez** [comment]
I don't see us deprecating this, it seems too disrupting for little benefit, so I'll close this.

**Comment by sandstrom** [comment]
Just to chime in, I was recently investigating how to properly inform users of my gem about a deprecation, and found this code:

https://docs.ruby-lang.org/en/3.3/Gem/Deprecate.html

But I find it very confusing, it's not obvious that it's an internal library, on the other hand the method names makes it weird to use for end-user facing deprecation (like stripe has, per the thread above).

Maybe there is a common mechanism to communicate deprecations to end-users in Ruby, but I haven't found anything.

Rails has a solution for it, but for my Gem I'm not planning to bring in all of ActiveSupport only to get that functionality:

https://api.rubyonrails.org/classes/ActiveSupport/Deprecation.html

I for one wouldn't mind deprecating this as @deivid-rodriguez had planned initially, but if doing so, it also wouldn't hurt if Ruby had introduced some standardised tooling around this (similar to what Rails has built perhaps?).

The way I see it, a good deprecation toolset should have:

- Some intelligence around figuring out and printing the source of the message (gem + file + linenumber).
- Ability to communicate a replacement (I think text is enough, having a symbol pointing to another method like `Gem::Deprecate` does it seem overkill).
- Optionally communicate in which future version the method is planned to be removed (but also something that can be handled in a free-form text argument about the replacement, i.e. the preceding point).
- Some global ability to silence all or some deprecations, so ideally every deprecation should be required to provide a 'key', and the full key used for silencing would be `{gem}/{key}`. That way someone who isn't planning to remove the deprecated code right away can still silence the message. 
- The ability to turn deprecations into raises. Rails has this, and it's quite need to avoid regression into using a deprecated method after it's already been cleaned out. Useful in large teams.

**Comment by deivid-rodriguez** [comment]
Valid points @sandstrom. I think we could for starters hide `Gem::Deprecate` documentation, and also maybe open a feature request to ruby-core since I'm not sure if there's any builtin tool in Ruby (I'd say no).
