### ISSUE TITLE
ERROR:  Could not find a valid gem 'cocoapods' (>= 0)

### ISSUE THREAD

**Issue by Yamine1** [rubygems/rubygems#3541]
I tried to install cocoapods with the command - sudo gem install cocoapods

I got an error - ERROR:  Could not find a valid gem 'cocoapods' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server hello A (https://rubygems.org/specs.4.8.gz)

And in order to evaluate if its an SSL error, I used the command - ruby -ropen-uri -e 'eval open("https://git.io/vQhWq").read'

And I got this result - 
\Traceback (most recent call last):
	13: from -e:1:in `<main>'
	12: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:35:in `open'
	11: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:736:in `open'
	10: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:165:in `open_uri'
	 9: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:224:in `open_loop'
	 8: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:224:in `catch'
	 7: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:226:in `block in open_loop'
	 6: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:756:in `buffer_open'
	 5: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/open-uri.rb:337:in `open_http'
	 4: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:919:in `start'
	 3: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
	 2: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/http.rb:996:in `connect'
	 1: from /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server hello A (OpenSSL::SSL::SSLError)

Help me fix this.

**Comment by simi** [comment]
please check https://bundler.io/guides/rubygems_tls_ssl_troubleshooting_guide.html#why-am-i-seeing-read-server-hello-a

**Comment by Yamine1** [comment]
I did check the link and tried the troubleshooting process. This is the result I got. 

 Unable to download data from https://rubygems.org/ - SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server hello A (https://rubygems.org/specs.4.8.gz)

**Comment by simi** [comment]
Can you post output of ssl check script mentioned at https://bundler.io/guides/rubygems_tls_ssl_troubleshooting_guide.html#troubleshooting-protocol-errors?

**Comment by Yamine1** [comment]
I just fixed it.  - Unable to download data from https://rubygems.org/ - SSL_connect SYSCALL returned=5 errno=0 state=SSLv3 read server hello A (https://rubygems.org/specs.4.8.gz) This was the error I got. Restarting my computer worked.

**Comment by djberg96** [comment]
Looks like rubygems went cuckoo for cocoapods.
