### ISSUE TITLE
Bundler is installed as `jbundler` on `jruby` by rubygems installer

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#3564]
My current problem is that if you run rubygems installer (`gem update --system`) on `jruby`, it installs the `bundler` executable as `jbundler`, not as `bundler`. That means `bundler` is not accessible in the usual way via `bundle` and you need to run `jbundle` instead. This is unexpected, because when you run `gem install bundler`, this does not happen and a `bundle` binstub is installed, so `jruby` users are used to running `bundle`, just like they run `ruby` or `gem`, instead of `jruby` or `jgem`.

Note that this is only a problem since https://github.com/rubygems/rubygems/pull/2766 (shipped with rubygems 3.1), because previously no `:format_executable` option would be passed to the default `bundler` installer. So the behaviour in previous rubygems versions is the expected.

The behaviour has been always unexpected for the `gem` binstub (`jgem` is always installed). However, `jruby` workarounds the issue by [providing a `gem` binstub that delegates to `jgem`](https://github.com/jruby/jruby/blob/248a1d32cfacf59e9834a4bd0071c5ed46524b36/bin/gem).

The `:format_executable` makes sense for operating systems so that they can have several rubies installed at that same time, and executables for each of them installed as, for example, `gem27`, `bundler27`, and so on. So we don't want to revert https://github.com/rubygems/rubygems/pull/2766.

The question is, what should we do, then? There's some options:

* Change [the `setup` command default value to the `:format_executable`](https://github.com/rubygems/rubygems/blob/84e32f8c0c7e90a485c93cd61e8f11f7daf7a182/lib/rubygems/commands/setup_command.rb#L19) to `false`. That would match [the default value for the option in the `install` command](https://github.com/rubygems/rubygems/blob/84e32f8c0c7e90a485c93cd61e8f11f7daf7a182/lib/rubygems/commands/install_command.rb#L24) and it seems like a clean solution. However:
  - ~Since `jruby` already provides a "workaround binstub", changing this would mean overwriting this binstub on `gem update --system`, and rubygems will normally refuse to do that unless you pass the `--force` option.~ EDIT: The `--force` option is `true` by default for the `setup` command, so this shouldn't be a problem in principle.
  - Operating systems are most likely already configuring `install: --format-executable` in their `gemrc` files (or in the `operating_system.rb` script), but since `true` is the default for the `setup` command, they might not be doing the same thing for the `setup` command, and this change could break things.

* Do nothing and wait for `jruby` to provide a similar binstub for `jbundler` or to configure the proper `--format-executable` option for the setup command. 

In my opinion, the former option is cleaner and makes more sense, but requires more careful coordination with OS packagers and the `jruby` team. The latter option is obviously easier for us since it requires no changes on our side. So... :man_shrugging:.

Pinging @enebo from `jruby`, @terceiro from Debian, and @voxik from Fedora to gather some opinions.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by voxik** [comment]
From Fedora point of view, I would never ever suggest to use `gem update --system` to anybody. They should do `dnf update` instead and RubyGems would be updated from system repositories.

In ideal world, the RubyGems in Fedora would be independent of Ruby or JRuby and would be shared by both. In ideal world, the gems would be shared by both. In ideal world, there would be even StdLib shared by both.

To choose between Ruby/JRuby on Fedora, we have [rubypick](https://github.com/fedora-ruby/rubypick) and it would mostly work automatically, unless there was explicitly enforced some implementation

**Comment by deivid-rodriguez** [comment]
True, I missed that! So `gem update --system` is not something distro packages would recommend, and changing the `setup` command shouldn't really affect distro packages at all, right? That would make this change easier :)

**Comment by hsbt** [comment]
also ping @headius

**Comment by terceiro** [comment]
> True, I missed that! So `gem update --system` is not something distro packages would recommend, and changing the `setup` command shouldn't really affect distro packages at all, right? That would make this change easier :)

even though it's not recommended, people will still do it. so you want it to do the right thing. FWIW, your PR makes sense to me.

**Comment by deivid-rodriguez** [comment]
Thanks @terceiro.

You're right, people will still do it, and I believe even more in Debian since there's currently no "OS way" of upgrading rubygems if I recall correctly?

By my PR, you mean my proposal of changing the default value of `:format_executable` for `gem update --system` to `false`, right?

**Comment by terceiro** [comment]
> You're right, people will still do it, and I believe even more in Debian since there's currently no "OS way" of upgrading rubygems if I recall correctly?

yeah well, even if there is a way to upgrade rubygems separately from ruby, there won't be the latest and greatest rubygems available for stable the OS releases so people might still do it.

> By my PR, you mean my proposal of changing the default value of `:format_executable` for `gem update --system` to `false`, right?

yes

**Comment by deivid-rodriguez** [comment]
I opened #3811 to fix this.
