### ISSUE TITLE
Bundler ignores BUNDLE_HOME, BUNDLE_CACHE_PATH

### ISSUE THREAD

**Issue by envygeeks** [rubygems/rubygems#3572]
Thank you for contributing to the [rubygems](https://github.com/rubygems/rubygems) repository, and specifically to the [Bundler](https://bundler.io/) gem.

Before processing your issue please confirm that:

- [x] You checked all the following documents and couldn't find a solution for your issue:

Please answer the following questions so we can process your issue as fast as possible:

1. 

```sh
gem install jekyll
jekyll new test_jekyll
cd test_jekyll

docker run --rm --volume="$PWD:/srv/jekyll" \
  -it jekyll/jekyll:4.0.0 jekyll build
```

2. What are you trying to accomplish? It to respect BUNDLE_HOME, or at least BUNDLE_CACHE_PATH

3. What command did you run?

```
bundle install
```

4. What were you expecting to happen?

It to work like it did in previous versions of bundler. Though I'm not quite sure this isn't related to Alpine in some way so I'll also be creating a ticket on their tracker since it only recently showed up and the last release for bundler was a while ago.

6. Is there an exception backtrace? If so, please copy it below.

No, there is a generic error though

```
There was an error while trying to write to `/usr/gem/cache/bundler/git`. It is likely that you need to grant write permissions for that path.
```

7. Please run `bundle env` and paste the output below:

## Environment

```
Bundler       2.1.4
  Platforms   ruby, x86_64-linux-musl
Ruby          2.7.1p83 (2020-03-31 revision a0c7c23c9cec0d0ffcba012279cd652d28ad5bf3) [x86_64-linux-musl]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.1.2
  Gem Home    /usr/gem
  Gem Path    /home/jekyll/.gem/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/gem
  User Home   /home/jekyll
  User Path   /home/jekyll/.gem/ruby/2.7.0
  Bin Dir     /usr/gem/bin
Tools
  Git         2.24.3
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2020-01-05
Git SHA           32a4159325
Released Version  true
```

## Bundler settings

```
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
disable_platform_warnings
  Set via BUNDLE_DISABLE_PLATFORM_WARNINGS: true
home
  Set via BUNDLE_HOME: "/usr/local/bundle"
bin
  Set via BUNDLE_BIN: "/usr/local/bundle/bin"
cache_path
  Set via BUNDLE_CACHE_PATH: "/usr/local/bundle/cache"
```

**Comment by envygeeks** [comment]
I should note the image uses `ruby:alpine` and is switching to `ruby:2.7-alpine3.11`

**Comment by deivid-rodriguez** [comment]
Where did you find about `BUNDLE_HOME`? I don't think that environment variable has any special behaviour? :thinking:

Regarding `BUNDLE_CACHE_PATH`, I recall some recent fixes about that. Maybe this is fixed on recent versions.

Can you still repro this?

**Comment by envygeeks** [comment]
Not worth the effort, we've since worked around all of these issues
