### ISSUE TITLE
Improve error message if `rake` is not found when building a "Rakefile" extension

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#3578]
If one of the dependencies uses `rake` to compile its extension, but doesn't declare `rake` as a dependency, one get an error like the one in https://github.com/rubygems/rubygems/pull/2326.

We could probably improve the error message to suggest potential remediation steps.

**Comment by simi** [comment]
Should we maybe warn on build time when `Rakefile` extension is provided, but `rake` is not added as a dependency?

**Comment by deivid-rodriguez** [comment]
I think that's a very nice idea.
