### ISSUE TITLE
Bundler::GemHelper#build_gem does not work when `base` is not an absolute path

### ISSUE THREAD

**Issue by haines** [rubygems/rubygems#3585]
1. Do you have a reproduction script? It would be really helpful for us if you provide one. 

    https://github.com/haines/bundler-monorepo-gem-build-issue

2. What are you trying to accomplish?

    I am trying to use the Bundler gem tasks to build a gem that is located in a different directory to my Rakefile.

   ```ruby 
   Bundler::GemHelper.install_tasks dir: 'my_gem'
   ```

3. What command did you run?

    ```console
   $ bin/rake
   ```

4. What were you expecting to happen?

    The gem builds successfully.

5. What actually happened?

    Rake exits with an error:

   ```
   ERROR:  Gemspec file not found: my_gem/my_gem.gemspec.gemspec
   ```

   The shell command executed by `Bundler::GemHelper#build_gem` was

   ```ruby
   ["gem", "build", "-V", "my_gem/my_gem.gemspec"]
   ```

   but this is executed after `cd`-ing into `my_gem/` [here](https://github.com/rubygems/rubygems/blob/9cfc95d9d9eeede71884a25ade8851b7ab722011/bundler/lib/bundler/gem_helper.rb#L196), so the gemspec path should not include that directory.

6. Is there an exception backtrace? If so, please copy it below.

    ```
   gems/bundler-2.1.4/lib/bundler/gem_helper.rb:189:in `sh'
   gems/bundler-2.1.4/lib/bundler/gem_helper.rb:76:in `build_gem'
   gems/bundler-2.1.4/lib/bundler/gem_helper.rb:40:in `block in install'
   ```

7. Please run `bundle env` and paste the output below:

<details>
  <summary>Click to expand!</summary>
## Environment

```
Bundler       2.1.4
  Platforms   ruby, x86_64-darwin-19
Ruby          2.7.1p83 (2020-03-31 revision a0c7c23c9cec0d0ffcba012279cd652d28ad5bf3) [x86_64-darwin19]
  Full Path   /Users/andrew/.rubies/ruby-2.7.1/bin/ruby
  Config Dir  /Users/andrew/.rubies/ruby-2.7.1/etc
RubyGems      3.1.2
  Gem Home    /Users/andrew/.gem/ruby/2.7.1
  Gem Path    /Users/andrew/.gem/ruby/2.7.1:/Users/andrew/.rubies/ruby-2.7.1/lib/ruby/gems/2.7.0
  User Home   /Users/andrew
  User Path   /Users/andrew/.gem/ruby/2.7.0
  Bin Dir     /Users/andrew/.gem/ruby/2.7.1/bin
Tools         
  Git         2.26.0
  RVM         not installed
  rbenv       not installed
  chruby      0.3.9
```

## Bundler Build Metadata

```
Built At          2020-01-05
Git SHA           32a4159325
Released Version  true
```

## Bundler settings

```
gem.test
  Set for the current user (/Users/andrew/.bundle/config): "minitest"
gem.mit
  Set for the current user (/Users/andrew/.bundle/config): true
gem.coc
  Set for the current user (/Users/andrew/.bundle/config): true
```

### Gemfile

```ruby
source 'https://rubygems.org'

gemspec path: 'my_gem'

gem 'rake'
```

### Gemfile.lock

```
PATH
  remote: my_gem
  specs:
    my_gem (0.0.1)

GEM
  remote: https://rubygems.org/
  specs:
    rake (13.0.1)

PLATFORMS
  ruby

DEPENDENCIES
  my_gem!
  rake

BUNDLED WITH
   2.1.4
```

### my_gem.gemspec

```ruby
Gem::Specification.new do |spec|
  spec.name = 'my_gem'
  spec.version = '0.0.1'
  spec.author = 'Andrew Haines'
  spec.summary = 'One of many gems in a monorepo'

  spec.files = Dir.chdir __dir__ do
    `git ls-files -z`.split("\x0")
  end
end
```
</details>

**Comment by deivid-rodriguez** [comment]
Thanks @haines! I didn't know about the `:dir` parameter, today I learnt!

Based on your helpful investigation, this should be easy to fix by passing only the basename of the gemspec to the build command.

PR welcome! :)

**Comment by haines** [comment]
Working on a PR now 😄

**Comment by haines** [comment]
Opened #3586 to ensure that `base` is an absolute path by calling `File.expand_path` in the constructor, which ended up being simpler than passing the basename to the command - the subsequent juggling to move the built gem into `pkg/` also didn't work with relative paths!
