### ISSUE TITLE
Issue with authentication with proxy

### ISSUE THREAD

**Issue by tysonite** [rubygems/rubygems#360]
It seems I incorrectly fills previous issue https://github.com/rubygems/rubygems.org/issues/391 in other project.
Hope, this one is correct or if it is fixed, please, let me know.

I try to authenticate on proxy using the following method:

```
export http_proxy='http://DOMAIN\login:password@192.168.205.2:8080'
```

and it doesn't work with the following message:

```
[root@host]# gem update
Updating installed gems
ERROR: While executing gem ... (URI::InvalidURIError)
bad URI(is not URI?): http://DOMAIN\login:password@192.168.205.2:8080
```

However, if I exclude "DOMAIN\" string from http_proxy variable it tries to authenticate, but fails (because proxy requires domain name to be included for the user):

```
[root@host]# export http_proxy='http://login:password@192.168.205.2:8080'

[root@host]# gem update
Updating installed gems
ERROR: While executing gem ... (Gem::RemoteFetcher::FetchError)
bad response Proxy Authentication Required 407 (http://rubygems.org/latest_specs.4.8.gz)
```

I guess that proxy settings parser should be extended to understand domain name.

rubygems version is

```
[root@host]# gem -v
1.8.15
```

**Comment by ken-sands** [comment]
it works if you url encode the backslash between the domain and username, ie

http://mydomain%5Cmyusername:password@proxy:port

for years I've been downloading packages at home and brining them into work on cd's!

**Comment by simo11093** [comment]
> Same here.
> 
> Using Debian, and almost every net utilities (wget, curl) works with my current http_proxy env variable, except rubygems... my http_proxy looks like
> 
> ```
> http_proxy=http://user:password@host:port
> ```
> 
> I've tried using cntlm (http://cntlm.sourceforge.net/) and use it as a proxy for rubygems (gem install --http-proxy ...), without success. I'm not sure if I really need to pass the domain to the proxy, because other applications can connect without it...
> 
> My rubies was installed with rvm... its very strange that only rubygems refuse to use my proxy credentials.
> 
> Any clues?

just remove "@" from your password
