### ISSUE TITLE
Note CLI deprecations in man pages

### ISSUE THREAD

**Issue by sonicdoe** [rubygems/rubygems#3600]
There are quite a few upcoming changes to the command-line interface in Bundler 3 which are detailed in [`UPGRADING.md`](https://github.com/rubygems/rubygems/blob/2d989434dfbf769cb42110cc3df767195b87813e/bundler/UPGRADING.md#cli-deprecations). These deprecations are now also printed by default in Bundler 2.1.

For example, the `--clean` option to `bundle install` is deprecated. However, [looking at the man page](https://github.com/rubygems/rubygems/blob/2d989434dfbf769cb42110cc3df767195b87813e/bundler/man/bundle-install.ronn), it’s not clear that this option is deprecated and which command should be used instead.

It would be helpful if such deprecations are also marked in the man pages.

**Comment by rubyFeedback** [comment]
I think that would be nice, perhaps even some small icon if it is shown via the browser/web-page (I rarely use commandline means to look up any documentation myself, so most of the information comes from using the browser).
