### ISSUE TITLE
Can bundler conditionally specify a version of a gem?

### ISSUE THREAD

**Issue by AlexEvanczuk** [rubygems/rubygems#3607]
I am using `sorbet`, a type checker for ruby. I'm creating a gem which I want to use the `sorbet-runtime` gem, but I want to use a sorbet runtime shim if the client of the gem does not have `sorbet-runtime`.

One solution to this is in the gem doing this:
```
begin
  require 'sorbet-runtime'
  # If sorbet-runtime exists but the versions are not compatible with the dev dependency version of sorbet-runtime, then error out here
rescue
  require 'sorbet-shim'
end
```

However, what I'd like is in the gemspec to do this:
```
spec.lock_dependency 'sorbet-runtime', '~> 0.5.5369', 
```

This would mean that IF the client has sorbet-runtime, require it to be this version. Otherwise, do not install the runtime (since our application code chooses to install the shim otherwise. I'd like the gem to ensure that the shim is compatible with the consuming application's runtime, since the actual production code needs to work with both the shim and the runtime.

Does bundler have anything to support this, or does anyone have any suggestions?

**Comment by simi** [comment]
Would something like this in your code work?

```ruby
begin
  gem 'sorbet-runtime', "~> 0.5.5369"
  require 'sorbet-runtime'
rescue Gem::LoadError
  require 'sorbet-shim'
end
```

**Comment by AlexEvanczuk** [comment]
It looks like this would actually be trying to install `sorbet-runtime` (possibly after the code loads?). Is that the intention? What happens when you call the `gem` DSL method outside of the `Gemfile`? What happens to the consumer if they have (and contrary-wise, if they have not) specified `sorbet-runtime` as one of their own dependencies?

**Comment by simi** [comment]
Ahh, sorry, this is not meant to be in Gemfile, but in your application code. For example rails does that to ensure only supported db gems are loaded.

https://github.com/rails/rails/blob/master/activerecord/lib/active_record/connection_adapters/postgresql_adapter.rb#L3-L4

**Comment by AlexEvanczuk** [comment]
Interesting -- do you have more documentation on this? Does it work by making an HTTP call to rubygems to pull the gem in? What happens if the client decides to include `sorbet-runtime` in their `Gemfile`?

I don't think this fits our needs, because it's not that we want to include `sorbet-runtime` conditionally, but rather we want bundler to reconcile the versions of `sorbet-runtime` *only if* the client has `sorbet-runtime` installed. If they don't have `sorbet-runtime` installed, we don't want to install it in the gemspec, but rather we want to load the shim.

**Comment by simi** [comment]
It works locally, nothing is installed. It will try to load gem with that version constraint if not successful, it will raise an exception. You need to somehow install this gem, usually by adding it Gemfile. More at docs - https://github.com/rubygems/rubygems/blob/4d5367da6daa0eeb5ec6e68882d805425825e301/lib/rubygems/core_ext/kernel_gem.rb#L10.

If you're looking for optional dependency, there's already opened issue - https://github.com/rubygems/rubygems/issues/1811.

**Comment by AlexEvanczuk** [comment]
Thanks, your suggestion is a great one. This is my implementation that loads the gem conditionally. This would be removed if the optional dependency feature suggested in that issue is implemented.

```ruby
require_relative './sorbet_runtime_version'

begin
  gem 'sorbet-runtime', SORBET_RUNTIME_VERSION
  require 'sorbet-runtime'
rescue Gem::LoadError => e
  # If we enter this, then we've failed to load sorbet-runtime.

  # In this case, he client did install it in their gemfile, but the versions were not compatible.
  # The error message is: `can't activate sorbet-runtime (~> 0.5.5369.0), already activated sorbet-runtime-0.5.5585. Make sure all dependencies are added to Gemfile.`
  # We do not want to load the shim, which would stub out sorbet-runtime for the consumer in production. Instead we error.
  if e.message.include?('already activated sorbet-runtime')
    error_message = <<~ERROR
      OurSpecialGem uses `sorbet-runtime` #{SORBET_RUNTIME_VERSION}

      Please either:
      A) Change the gem consumer's Gemfile to use the same version of `sorbet-runtime`
      or
      B) Bump OurSpecialGem `SORBET_RUNTIME_VERSION` and `SORBET_RUNTIME_STUB_VERSION` to the latest versions.
    ERROR
    raise error_message
  # In this case, the client did not install sorbet-runtime in their Gemfile.
  # The error message is: `sorbet-runtime is not part of the bundle. Add it to your Gemfile.`
  # Here load the shim, which ensures that during runtime, T::Sig, and all of its methods (such as `sig`) are defined.
  elsif e.message.include?('sorbet-runtime is not part of the bundle')
    require 'sorbet-runtime-stub'
  else
    # Some other load error -- we continue to raise as we do not know what to expect from this load error
    raise
  end
end
```

**Comment by simi** [comment]
:handshake:
