### ISSUE TITLE
Unique URIs and Funding URIs

### ISSUE THREAD

**Issue by ioquatix** [rubygems/rubygems#3616]
Sorry for adding to the noise of the issue tracker for what is a relatively superficial issue. However...

I have a project, here is the homepage and other metadata in the gemspec:

https://github.com/socketry/utopia-project/blob/ba21621e4af44e71b4f76c6bac36f20d7c2ef94b/utopia-project.gemspec#L9-L17

Firstly, on the sidebar:

<img width="202" alt="image" src="https://user-images.githubusercontent.com/30030/81500552-f8c63100-9326-11ea-8b08-e50b498417c7.png">

I don't see any funding URI. Is this live yet?

Also, I see "Homepage" and "Source Code" both point to the same thing.

1/ I wonder if we should display the full URI somewhere - e.g. under the link in `<small>` or something.
2/ Are we adding the funding URI? Is this still WIP?
3/ Can we skip showing the "Homepage" link if it's in one of the more specific links?

Because, I feel like it's nicer to have "Source Code" and "Documentation" links.

Or maybe I should just remove the "documentation_uri" metadata.

Some guidance would be appreciated.

**Comment by bronzdoc** [comment]
@ioquatix 

Re funding uri:
That gemspec field is already in master but not yet released https://github.com/rubygems/rubygems/pull/3060

Regarding the layout changes in  rubygems.org, can you open the this issue in https://github.com/rubygems/rubygems.org ? thanks!

**Comment by ioquatix** [comment]
Should we close this issue?
