### ISSUE TITLE
The current master branch was broken with the ruby repository

### ISSUE THREAD

**Issue by hsbt** [rubygems/rubygems#3618]
The current master branch was broken with the ruby core repository. The ruby core repository uses the different test suite with the rubygems repo.

See https://github.com/ruby/ruby/runs/655168183

I'm not sure why that are happend. But after reverting the following commits, I got the success of test results.

* https://github.com/ruby/ruby/pull/3092/commits/b514041faae51aaa8d7dddac34a58c54a31bf14d
* https://github.com/ruby/ruby/pull/3092/commits/829363b2df3ba9abdc54b980d73a6a0eb8438b7e
* https://github.com/ruby/ruby/pull/3092/commits/4c09dc5efb0954e8ff6f19f06e7d39bdec209c37

We should resolve this issues before releasing RubyGems 3.2.

----

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Thanks @hsbt, next on my list :+1:.

**Comment by deivid-rodriguez** [comment]
@hsbt Have you tried reapplying these changes after https://github.com/rubygems/rubygems/pull/3694? I have a hunch that PR might've fixed it?

**Comment by deivid-rodriguez** [comment]
Yes, I managed to reproduce the issues of reverting the three commits, and I verified that believe it's the same issue! :tada:

I will make a PR to ruby-core to reintroduce the three reverted commits, and #3694.

**Comment by Janedoe682** [comment]
So how can I resolve this?

janedoe682
