### ISSUE TITLE
Question regarding RubyGems

### ISSUE THREAD

**Issue by RDIL** [rubygems/rubygems#3625]
I am wondering if RubyGems has functionality to handle alpha releases of gems?  I have a new version of a gem I maintain but I don't know if I should push it or not since it is an alpha release.  

Thanks in advance!

**Comment by simi** [comment]
:pray: please check at least guides and documentation before asking questions on tracker, which is intended for reporting problems or suggesting a features.

https://guides.rubygems.org/patterns/#prerelease-gems

**Comment by RDIL** [comment]
Thanks @simi
