### ISSUE TITLE
Gem.load_yaml: psych: `<class:Parser>': superclass mismatch for class Mark (TypeError)

### ISSUE THREAD

**Issue by junaruga** [rubygems/rubygems#3629]
I'm having a problem.

My current problem is the following Ruby script shows the following `TypeError` with non-default gem: psych.

```
$ cat test.rb 
require 'psych'
Gem.load_yaml # <= The error happens.
```

```
$ ruby test.rb
/usr/lib64/gems/ruby/psych-3.1.0/psych.so: warning: already initialized constant Psych::Parser::ANY
...
/usr/share/gems/gems/psych-3.1.0/lib/psych/parser.rb:34:in `<class:Parser>': superclass mismatch for class Mark (TypeError)
```

I prepared the reproducer script here with Travis CI. The 3 cases that have the issue.

https://github.com/junaruga/report-rubygems-load-yaml
https://travis-ci.org/github/junaruga/report-rubygems-load-yaml

The issue comes from [this ticket in Fedora project](https://bugzilla.redhat.com/show_bug.cgi?id=1835836). And it is related to https://github.com/rubygems/rubygems/issues/3131 and https://github.com/ruby/psych/issues/386 .
I want to see that `Gem.load_yaml` will be fixed for now, for example by removing `gem 'psych', '>= 2.0.0'` part that I mentioned [here](https://bugzilla.redhat.com/show_bug.cgi?id=1835836#c5).

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

Here are my current environment details:

```
$ gem env version
3.1.2
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Does https://github.com/rubygems/rubygems/pull/3429 fix the issue?

**Comment by junaruga** [comment]
Thanks for the info. Let me check it.

**Comment by junaruga** [comment]
I will check it on Monday 18th May.

**Comment by junaruga** [comment]
> Does #3429 fix the issue?

It does not work on Fedora rawhide. It's a same error with the case without the patch.
I confirmed `test_activate_via_require_respects_loaded_default_from_default_gems` passes.

I applied #3429 patch like [this](https://github.com/junaruga/report-rubygems-load-yaml/blob/master/patch_rawhide.sh) with Travis CI. "Fedora rawhide Ruby 2.7 with patch" is the case.

One concern is the rubygems installed in the environment is not the HEAD of master. Do we need more patches?

**Comment by deivid-rodriguez** [comment]
I have no idea... :shrug:

I think your suggestion is fine and we shouldn't explicitly activate `psych` but let it go through `require` instead. But still, if there's an already activated `psych` version, I believe `gem "psych", ">= 2.0.0"` should respect it, so I don't know what's going on.

I can have a closer look since you have provided a nice repro, but I guess the first thing we could try is removing the whole explicit `psych` gem activation and see if any tests fail.

**Comment by junaruga** [comment]
> I guess the first thing we could try is removing the whole explicit psych gem activation and see if any tests fail.

Sure. I think currently there are 2 parts about the explicit psych gem.

```
bundler/lib/bundler/psyched_yaml.rb:  gem "psych"
lib/rubygems.rb:        gem 'psych', '>= 2.0.0'
```

**Comment by deivid-rodriguez** [comment]
> I think your suggestion is fine and we shouldn't explicitly activate psych but let it go through require instead. But still, if there's an already activated psych version, I believe gem "psych", ">= 2.0.0" should respect it, so I don't know what's going on.

Actually, without #3429, if `psych` was required before `rubygems`, the loaded version won't be respected. So it makes sense that removing the explicit activation fixes you issue. What doesn't make sense to me is that applying the patch does not fix the issue. I'll double check if it needs more patches. On top of which rubygems version are you applying it?

**Comment by deivid-rodriguez** [comment]
> Sure. I think currently there are 2 parts about the explicit psych gem.

I would try only `rubygems` for now, since removing that seems to fix your issue.

**Comment by junaruga** [comment]
> On top of which rubygems version are you applying #3429?

The rubygems is based on the one used in Ruby 2.7.1 https://github.com/ruby/ruby/tree/v2_7_1 + some patch files (*.patch) [here](https://src.fedoraproject.org/fork/jaruga/rpms/ruby/tree/wip/rubygems-require-respects-default-gems).

**Comment by deivid-rodriguez** [comment]
Ok, thanks! I'll double check this.

**Comment by junaruga** [comment]
Thanks!

As one more note, [the following file](https://src.fedoraproject.org/fork/jaruga/rpms/ruby/blob/wip/rubygems-require-respects-default-gems/f/operating_system.rb) is used.

```
/usr/share/rubygems/rubygems/defaults/operating_system.rb
```

**Comment by junaruga** [comment]
I noticed the following line's `loaded` is `nil` when running above `test.rb` in the Fedora.

/usr/share/rubygems/rubygems/core_ext/kernel_gem.rb

```
  def gem(gem_name, *requirements) # :doc:
...
    loaded = Gem.loaded_specs[gem_name] # <= loaded is nil
...
```

The following script `test2.rb` shows like this on the Ruby 2.7.1 built from the source code.

```
$ cat test2.rb
require 'psych'
p Gem.loaded_specs.keys
```

```
$ command -v ruby
/usr/local/ruby-2.7.1/bin/ruby

$ ruby test2.rb
["did_you_mean", "psych", "stringio", "strscan"]
```

But The RPM ruby in Fedora rawhide shows 

The following script `test2.rb` shows like this on the Ruby 2.7.1 RPM on Fedora rawhide.

```
$ command -v ruby
/usr/bin/ruby

$ ruby test2.rb 
["did_you_mean", "stringio", "strscan"]
```

2nd case's `Gem.loaded_specs.keys` does not include `"psych"`.

**Comment by junaruga** [comment]
The following situation is the reason?

* 1st one Ruby 2.7.1 built from the source code: there is default gem psych gemspec: `/usr/local/ruby-2.7.1/lib/ruby/gems/2.7.0/specifications/default/psych-3.1.0.gemspec`.
* 2nd one Ruby 2.7.1 RPM on Fedora rawhide: there is no default gem psych gemspec: `/usr/share/gems/specifications/default/psych-*.gemspec`.

**Comment by deivid-rodriguez** [comment]
I'm looking at this right now and observed the same thing. Let me keep digging.

**Comment by deivid-rodriguez** [comment]
Ok, so the reason for this is essentially what you pointed out.

Gem "auto-activation", i.e., the rubygems feature where you can just `require "your_gem"` and your gem will get automatically activated (added to the `$LOAD_PATH` on the fly) depends on either:

* A file with the same name not being present on the default `$LOAD_PATH`.
* A file with the same name being present in the default `$LOAD_PATH`, but having a corresponding default gem specification installed.

In your case, you have a `psych.rb` file installed in the default `$LOAD_PATH` with a default specification, and also a regular `psych` gem installed.

Unfortunately, `rubygems` auto-activation feature relies on either early detecting that a default gem is being required, or rescuing the `LoadError` produced by the standard require otherwise in order to try to discover the file on `GEM_PATH` entries.

So there's not much we can do here, my recommendation is that you ship a default specification for the default `psych` and remove the "regular" gem.

**Comment by junaruga** [comment]
Thank you for the investigation.

> So there's not much we can do here, my recommendation is that you ship a default specification for the default psych and remove the "regular" gem.

While I agree that shipping the default specification for the default psych and moving the "regular" gem is the ideal way, I need to negotiate it with people in Fedora Ruby RPM, because it is relatively a bigger change in the RPM Ruby's recipe file (`ruby.spec`). And I may have to release the minimum patched version of the Ruby to fix this issue.

> Actually, without #3429, if psych was required before rubygems, the loaded version won't be respected. So it makes sense that removing the explicit activation fixes your issue.

So, I would like to know the alternative way to fix the issue too without shipping the default specification file, by just patching `*.rb` files.

Back to the following topic, We can not remove the line?

```
lib/rubygems.rb:        gem 'psych', '>= 2.0.0'
```

**Comment by deivid-rodriguez** [comment]
Oh, sorry, yeah, I forgot about the other part! :sweat_smile:

Yes, I believe we can remove that and it makes sense that it fixes your issue since that way, your `psych.rb` will be the one used and `psych` will never be activated as a gem. Let me open a PR and see what CI says.

**Comment by junaruga** [comment]
@deivid-rodriguez Thanks for your help! I am so happy your PR was merged.

Now for the following part, the part makes same error. Can we remove the line too just in case?

```
bundler/lib/bundler/psyched_yaml.rb:  gem "psych"
```


```
$ cat test3.rb 
require 'psych'
require 'bundler/psyched_yaml' # <= The error happens.
```

```
$ ruby test3.rb
/usr/lib64/gems/ruby/psych-3.1.0/psych.so: warning: already initialized constant Psych::Parser::ANY
...
/usr/share/gems/gems/psych-3.1.0/lib/psych/parser.rb:34:in `<class:Parser>': superclass mismatch for class Mark (TypeError)
```

**Comment by deivid-rodriguez** [comment]
That one would sound harmless to me too. We have explictly tests to make sure that end users can choose their `psych` version through the `Gemfile`, so should be fine. Feel free to propose a PR :)

**Comment by junaruga** [comment]
> Feel free to propose a PR :)

I open the PR here. Let's see what CI says.
https://github.com/rubygems/rubygems/pull/3638
