### ISSUE TITLE
Rubygems 3.1.x performance regression due to #1868

### ISSUE THREAD

**Issue by lamont-granquist** [rubygems/rubygems#3631]
#1868 introduced code to scan through the $LOAD_PATH to test for the presence of files in the -I args of the ruby cli.

What I think was missed there is that the the $LOAD_PATH includes the lib directories of all of the activated gems:

e.g. from some debugging output of `puts $LOAD_PATH[0...load_path_insert_index]`:

```
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/test-kitchen-2.5.0/bin/../lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/i18n-1.8.2/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/thread_safe-0.3.6/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/tzinfo-1.2.7/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/minitest-5.14.0/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.2/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/public_suffix-4.0.5/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/addressable-2.7.0/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.0.9/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/mixlib-cli-2.1.6/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/appbundler-0.13.2/lib
[...]
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/pry-byebug-3.9.0/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/slop-3.6.0/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/pry-remote-0.1.8/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/pry-stack_explorer-0.4.9.3/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/rexml-3.2.4/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/ruby-prof-1.3.2/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/ruby-prof-1.3.2
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/ruby-shadow-2.5.0/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/ruby-shadow-2.5.0
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/stove-7.1.6/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/yard-0.9.25/lib
```

It looks like what is happening is this is now an extra scan through every single activated gem, times the three suffixes which every require call has to go through in addition to all the processing that was there in rubygems 2.x

The difference is fairly substantial, this is rubygems 3.1.2 performance:

```
# time /opt/chef-workstation/bin/kitchen list
/opt/chef-workstation/bin/kitchen list  13.02s user 5.64s system 49% cpu 37.690 total
```

versus commenting out the code block from that PR (in its current form):

```
# time /opt/chef-workstation/bin/kitchen list
/opt/chef-workstation/bin/kitchen list  2.42s user 0.61s system 48% cpu 6.256 total
```

I think that if the file to be required is an internal gem that it is particularly badly performant because it has to fail this loop first going through all the gems, then it has to go through all the same logic as before until finally falling back to scanning through the internal ruby gems.

One solution might be to delete the now-duplicate second scan of activated gems, but it also seems like this loop is particularly slow for some reason (the 600% speedup after deleting it suggests something else is going on).

Another solution would be to tweak the loop so that it was only looping through the command line -I flags (as I think was intended, but I don't know enough about how rubygems handles the $LOAD_PATH).

Additionally, this is on ruby 2.7.1 so the UNTAINT call should be hitting the empty-proc side of that, so it shouldn't be untainting all the strings.

**Comment by deivid-rodriguez** [comment]
> Another solution would be to tweak the loop so that it was only looping through the command line -I flags (as I think was intended, but I don't know enough about how rubygems handles the $LOAD_PATH).

Yes, that's what was intended :grimacing:

Can you try this patch and see if it fixes the regression?

```diff
-        $LOAD_PATH[0...load_path_insert_index].each do |lp|
+        rubyopt_rubylib_load_path_index = load_path_insert_index - Gem.loaded_specs.values.count {|s| !s.default_gem? }
+
+        $LOAD_PATH[0...rubyopt_rubylib_load_path_index].each do |lp|

```

**Comment by deivid-rodriguez** [comment]
This is just a candidate that can be speed up further to not look into all loaded specs every time, but I think this initial version should already make things much faster for you?

**Comment by lamont-granquist** [comment]
I'm pretty sure I can make that fail because the user can twiddle manually with the $LOAD_PATH and even without that, in testing yesterday I managed to get a binstubs library path first in the $LOAD_PATH with the -I flags after it, and then all the rest of the gems coming later.

**Comment by lamont-granquist** [comment]
(think i may have more for you on Monday though because this is $DAYJOB on the weekend for me, and I need a solid break...)

**Comment by deivid-rodriguez** [comment]
> I'm pretty sure I can make that fail because the user can twiddle manually with the $LOAD_PATH and even without that, in testing yesterday I managed to get a binstubs library path first in the $LOAD_PATH with the -I flags after it, and then all the rest of the gems coming later.

I think it would work for both manually prepending (path overrides default gems) and appending (path does not override default gems) entries to the `$LOAD_PATH`. For other `$LOAD_PATH` manipulations the behaviour would be as undefined as it is right now.

But I might be missing something.

**Comment by lamont-granquist** [comment]
That code works and is much faster, but its still not quite accurate.

I threw some debugging in there and I'm still seeing the loop going through this bit of my $LOAD_PATH:

```
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/chef-bin-16.1.0/bin/../lib
/foo/bar
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/concurrent-ruby-1.1.6/lib/concurrent-ruby
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/i18n-1.8.2/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/thread_safe-0.3.6/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/tzinfo-1.2.7/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/activesupport-5.2.4.2/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/public_suffix-4.0.5/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/addressable-2.7.0/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/mixlib-shellout-3.0.9/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/mixlib-cli-2.1.6/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/appbundler-0.13.2/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/artifactory-3.0.13/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/ast-2.4.0/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/aws-eventstream-1.1.0/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/aws-partitions-1.316.0/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/jmespath-1.4.0/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/aws-sigv4-1.1.3/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/aws-sdk-core-3.96.0/lib
```

First line is the binstub itself, second like is from an `-I/foo/bar` I threw in the binstub, then there's a few very non-default gems that shouldn't be in that list.  That isn't truncated so there's only 17 extras coming from somewhere.

I tried just `Gem.loaded_specs.values.count` without removing the default gems and that ultimately counted more gems than in Gem.load_path_insert_index and ultimately produced `[0...-1]` ranges.

I suspect that you may be missing that stuff like native gems have at last two entries in the LOAD_PATH?

```
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/nokogiri-1.11.0.rc2/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/extensions/x86_64-linux/2.7.0/nokogiri-1.11.0.rc2
```

**Comment by lamont-granquist** [comment]
Yeah there's 15 `extensions` directories, plus this one:

```
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/google-api-client-0.34.1/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/google-api-client-0.34.1/generated
```
And must be one more that I'm missing.

**Comment by lamont-granquist** [comment]
yeah this one:

```
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-cloud-3.0.1/lib
/opt/chef-workstation/embedded/lib/ruby/gems/2.7.0/gems/knife-cloud-3.0.1/spec
```

that's one of ours, i'm going to have to fix that one, that's terrible.

**Comment by deivid-rodriguez** [comment]
Wow, thanks for the investigation!

So I was indeed missing something: the fact that some gems add more than one path to the `$LOAD_PATH` when they get activated.

But it should be fixable, I'll give it a try tomorrow! :+1:

**Comment by lamont-granquist** [comment]
So yeah the only other thing is that binstub line that comes first, that's duplicated with the active gem later.  That seems correct to me though.  That is technically "manually" added to the LOAD_PATH by the binstub, and should be loaded at a higher priority than the `-I` flags, and higher priority than any rubygems or internal gems (i think).

**Comment by deivid-rodriguez** [comment]
I pushed an initial attempt here: https://github.com/rubygems/rubygems/compare/require_perf_regression, in case you want to give it a try. Will look into adding a test for it, but if you can double check the patch I appreciate it.

**Comment by deivid-rodriguez** [comment]
FInal PR is #3639!
