### ISSUE TITLE
Could not find a valid gem 'bundler' (= 2.1.4), here is why: Unable to download data from https://rubygems.org/ - timed out (https://rubygems.org/specs.4.8.gz)

### ISSUE THREAD

**Issue by andrewlynch** [rubygems/rubygems#3641]
I'm having a problem 

My current problem is that I can't deploy a rails app into production with Docker on AWS.
Sometimes half of the gems will install but, with other builds, it's not even possible to install bundler. 

`Could not find a valid gem 'bundler' (= 2.1.4), here is why: Unable to download data from https://rubygems.org/ - timed out (https://rubygems.org/specs.4.8.gz)`

`Gem::RemoteFetcher::UnknownHostError timed out (https://rubygems.org/gems/rake-13.0.1.gem)
`

`bridge-nf-call-iptables is disabled` which I assume would overcome any of the IPV6 issues that I have been reading about. 

This issue is related to:

  - [x] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

```
$ gem env version
3.0.3
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by paulriddle** [comment]
It is possible the problem is on your end. Take a look at https://github.com/rubygems/rubygems/issues/3006. I've just run into the same issue and restarting router has helped. Something was wrong with estabilishing IPv6 connections. Perhaps there is a way to force IPv4 via some `gem` option?

**Comment by deivid-rodriguez** [comment]
We have an open PR to implement our own version of [happy eyeballs](https://en.wikipedia.org/wiki/Happy_Eyeballs) to make `rubygems` use whatever protocol performs better. That should hopefully fix this and other ipv6 related tickets.

**Comment by sonalkr132** [comment]
> I can't deploy a rails app into production with Docker on AWS.

We have verified all of the AWS regions which have Ipv6 support to make sure that IPv6 connection is not an issue on any of them. You can verify if you have this issue by running the following commands on your host:
```
$ wget -6 www.rubygems.org # fails
$ wget -6 www.google.com # will work. if this fails as well, check your ipv6 routes.
```

> wget https://rubygems.org/specs.4.8.gz

does this work when you are getting the timeout from `gem` cli?

**Comment by deivid-rodriguez** [comment]
I'll close this due to lack of feedback now.

@andrewlynch If you're still having this issue and and you're able to perform @sonalkr132 troubleshoot steps, feel free to reopen if you still think this is a rubygems issue :+1:.
