### ISSUE TITLE
Certificates expiring

### ISSUE THREAD

**Issue by da-development-id** [rubygems/rubygems#3644]
I'm having a problem or would like to suggest a feature.

My current problem is some of your certificates in the package are expiring.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ X ] Other

Some of the certificates are expiring:
AddTrustExternalCARoot.pem

**Comment by MSP-Greg** [comment]
Yes, it does expire at May 30 10:48:38 2020 GMT, but I can't find anywhere that it's used?

One commit to it (see [history](https://github.com/rubygems/rubygems/commits/master/lib/rubygems/ssl_certs/rubygems.org/AddTrustExternalCARoot.pem)), https://github.com/rubygems/rubygems/commit/e2c71b2, from Apr 16, 2016, and it was renamed with no changes to other lib or test files.

Maybe delete the file?  Note, I renamed it and ran `curl -Lks 'https://git.io/rg-ssl' | ruby`, and all passed...

**Comment by gokulkarthick** [comment]
I'm too facing the same issue from May 30 10:48:38 2020 GMT, 

But curl -Lks 'https://git.io/rg-ssl' | ruby  - passed, 

Still am getting OpenSSL::SSL::SSLError (SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired))

**Comment by morgant** [comment]
I am running into this as well. The aforementioned SSL check script passes, but I'm getting OpenSSL "certificate verify failed" errors.

**Comment by MSP-Greg** [comment]
@gokulkarthick @morgant

It would be helpful if you posted the output...  Not a lot to go on without it.

**Comment by gokulkarthick** [comment]
I have updated the new CA SSL Certificate and everything is working fine @MSP-Greg

**Comment by deivid-rodriguez** [comment]
Given the latest feedback in this issue, I guess this can be closed?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
