### ISSUE TITLE
Gem is installed for wrong platform when declared only in the gemspec

### ISSUE THREAD

**Issue by camertron** [rubygems/rubygems#3646]
1. Do you have a reproduction script?

See the result of `bundle env` below.

2. What are you trying to accomplish?

I'm trying to install a platform-specific gem, `helm-rb`, via a gemspec on my Mac.

3. What command did you run?

`bundle install`

4. What were you expecting to happen?

I expected bundler to install helm-rb-0.1.0-x86_64-darwin.

5. What actually happened?

Bundler installed helm-rb-0.1.0-arm-linux. If I instead declare the helm-rb dependency in my Gemfile, the correct platform-specific version is installed. It also works as expected if I declare helm-rb in _both_ my Gemfile _and_ .gemspec. Running `gem install helm-rb` installs the correct platform-specific version as well. The issue appears only when helm-rb is declared in the .gemspec and not the Gemfile.

6. Is there an exception backtrace? If so, please copy it below.

No exception.

7. Please run `bundle env` and paste the output below:

## Environment

```
Bundler       2.1.4
  Platforms   ruby, x86_64-darwin-17
Ruby          2.5.6p201 (2019-08-28 revision 67796) [x86_64-darwin17]
  Full Path   /Users/cameron/.rbenv/versions/2.5.6/bin/ruby
  Config Dir  /Users/cameron/.rbenv/versions/2.5.6/etc
RubyGems      3.0.6
  Gem Home    /Users/cameron/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0
  Gem Path    /Users/cameron/.gem/ruby/2.5.0:/Users/cameron/.rbenv/versions/2.5.6/lib/ruby/gems/2.5.0
  User Home   /Users/cameron
  User Path   /Users/cameron/.gem/ruby/2.5.0
  Bin Dir     /Users/cameron/.rbenv/versions/2.5.6/bin
Tools
  Git         2.14.2
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2020-01-05
Git SHA           32a4159325
Released Version  true
```

## Bundler settings

```
specific_platform
  Set for the current user (/Users/cameron/.bundle/config): true
```

### Gemfile

```ruby
source 'https://rubygems.org'

gemspec

group :development do
  gem 'rake'
end

group :test do
  gem 'rspec'
end
```

### Gemfile.lock

```
<No /Users/cameron/workspace/kuby-app/lib/helm-cli/Gemfile.lock found>
```

### helm-cli.gemspec

```ruby
$:.unshift File.join(File.dirname(__FILE__), 'lib')
require 'helm-cli/version'

Gem::Specification.new do |s|
  s.name     = 'helm-cli'
  s.version  = ::HelmCLI::VERSION
  s.authors  = ['Cameron Dutro']
  s.email    = ['camertron@gmail.com']
  s.homepage = 'http://github.com/getkuby/helm-cli'
  s.license  = 'MIT'

  s.description = s.summary = 'Ruby wrapper around the Helm CLI.'

  s.add_dependency 'helm-rb', '~> 0.1'

  s.require_path = 'lib'
  s.files = Dir['{lib,spec,vendor}/**/*', 'Gemfile', 'CHANGELOG.md', 'README.md', 'Rakefile', 'helm-cli.gemspec']
end
```

**Comment by deivid-rodriguez** [comment]
@camertron Can you repro this with bundler 2.2.0.rc.2? I expect us to have fixed this.

**Comment by deivid-rodriguez** [comment]
I don't have a Mac to verify this there, but it seems fixed in Linux. With the given `Gemfile`, I get the following using rubygems & bundler default branch:

```
root@b4ad2eefd533:/helm# rm Gemfile.lock && bundle config unset specific_platform && bundle lock && grep helm-rb Gemfile.lock 
Fetching gem metadata from https://rubygems.org/...
Resolving dependencies...
Writing lockfile to /helm/Gemfile.lock
      helm-rb (~> 0.1)
    helm-rb (0.1.0-arm-linux)

root@b4ad2eefd533:/helm# rm Gemfile.lock && bundle config set specific_platform true && bundle lock && grep helm-rb Gemfile.lock 
Fetching gem metadata from https://rubygems.org/...
Resolving dependencies...
Writing lockfile to /helm/Gemfile.lock
      helm-rb (~> 0.1)
    helm-rb (0.1.0-x86_64-linux)
```

So I'll go ahead and close this as fixed. Feel free to reopen if this is not really fixed.

**Comment by deivid-rodriguez** [comment]
@camertron Just to make sure, you should try latest master, not the latest prerelease. You need to clone the repo, and run either `ruby setup.rb` (which will install the latest development code of both `rubygems` & `bundler`) or `cd bundler && rake install` (which will only install the latest development code of `bundler`).
