### ISSUE TITLE
`require` changes behavior comparing to plain Ruby

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#3647]
~~~
$ for psych in psych{1..3}; do mkdir $psych; echo "puts '$psych'" > $psych/psych.rb; done

$ find .
.
./psych2
./psych2/psych.rb
./psych1
./psych1/psych.rb
./psych3
./psych3/psych.rb

$ ruby -e '(1..3).each {|psych| $:.unshift("psych#{psych}"); require "psych" }'
psych1
psych2
psych3

$ ruby --disable-gems -e '(1..3).each {|psych| $:.unshift("psych#{psych}"); require "psych" }'
psych1
~~~

I have mentioned this test first time in \[[1]\] and this might be very well duplicate or resolved by #3131 or #3491. I just think this is nice and clean example which would be worth of its test case, because RubyGems should not modify the behavior of original Ruby `require` method in this way.

[1]: https://bugs.ruby-lang.org/issues/16904#note-8

**Comment by deivid-rodriguez** [comment]
Thanks! I confirm this is still an issue even with #3639 applied, so I'll have a look at it.

**Comment by RoMi67** [comment]
Idk
