### ISSUE TITLE
Making require "rubygems/package" work reliably

### ISSUE THREAD

**Issue by eregon** [rubygems/rubygems#3650]
```
$ gem env version
3.0.3
```

On Ruby 2.6.6:
```
$ ruby -v --disable-gems -e 'require "rubygems/package"' |& cat
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
/home/eregon/.rubies/ruby-2.6.6/lib/ruby/2.6.0/rubygems/deprecate.rb:24:in `<top (required)>': uninitialized constant Gem (NameError)
	from /home/eregon/.rubies/ruby-2.6.6/lib/ruby/2.6.0/rubygems/exceptions.rb:7:in `require'
	from /home/eregon/.rubies/ruby-2.6.6/lib/ruby/2.6.0/rubygems/exceptions.rb:7:in `<top (required)>'
	from /home/eregon/.rubies/ruby-2.6.6/lib/ruby/2.6.0/rubygems/security.rb:8:in `require'
	from /home/eregon/.rubies/ruby-2.6.6/lib/ruby/2.6.0/rubygems/security.rb:8:in `<top (required)>'
	from /home/eregon/.rubies/ruby-2.6.6/lib/ruby/2.6.0/rubygems/package.rb:44:in `require'
	from /home/eregon/.rubies/ruby-2.6.6/lib/ruby/2.6.0/rubygems/package.rb:44:in `<top (required)>'
	from -e:1:in `require'
	from -e:1:in `<main>'
```
Same on 2.7.1 (RubyGems 3.1.2).

Some few gems directly `require "rubygems/package"` (~78 gems with `csearch 'require "rubygems/package"' | wc -l`).
For example https://github.com/appsignal/appsignal-ruby/blob/v2.3.4/ext/extconf.rb

This works on MRI without the `--disable-gems` flag by "luck" due to MRI defining an empty `Gem` module as a way to remember "I should `require 'rubygems'` at startup".

To support this correctly, I think we should do this:
```ruby
module Gem; end
```

In every such file that can be required directly,
or alternatively always require first a common file (which would define `Gem`) in all such files.
(We could also use nesting definitions like `module Gem; module Deprecate; everything indented 2 spaces more`, but that would change a lot of lines, and cause many conflicts)

This causes an issue for TruffleRuby since that error happens even without `--disable-gems`:
https://github.com/oracle/truffleruby/issues/2014
And mimicking the MRI approach in TruffleRuby doesn't seem easy in this case (plus really it's "luck" and not a robust solution).

Thoughts? Any opinion on which of the two way to define it is preferable?

Do we have a list of "entry points" files that can be required directly like that?
Should we just add `module Gem; end` to all files under `lib` to be sure?

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by eregon** [comment]
FWIW I found a workaround in TruffleRuby by always ensuring `require "rubygems"` is done before `require "rubygems/deprecation"`. So this is not urgent. But it sounds good to address.

**Comment by deivid-rodriguez** [comment]
@eregon I'm good with your proposal. We don't have a list of allowed entrypoints, so I'd rather fix this only for `rubygems/package` to not give the false impression that everything can be required directly.
