### ISSUE TITLE
Improve `SharedHelpers.major_deprecation`

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#3662]
We currently use this helper for deprecation messages. You pass a major version and a deprecation message to it and it will display the deprecation warning if running that major version. That works well.

For example.

```
Bundler::SharedHelpers.major_deprecation 2, "The --binstubs option will be removed in favor of `bundle binstubs`"
```

will print the warning

> [DEPRECATED] The --binstubs option will be removed in favor of `bundle binstubs`.

when running bundler 2.

However, the helper will also _fail_ with the same message when running higher versions of bundler. For example, if running bundler 3 it will fail hard with the error

> [REMOVED] The --binstubs option will be removed in favor of `bundle binstubs`.

This last "mode" reads not great in my opinion, because deprecation messages don't work for "removals", since they talk in future tense instead of present tense, and sometimes hard errors need to be worded differently from deprecations.

I believe we should improve this.

**Comment by nevinera** [comment]
@deivid-rodriguez - my instinct here is that we should add an optional `removed` keyword argument that is used for the third case, and then update most of the call-sites to supply it.

If it seems safe enough, I could drop the positional arguments entirely and go with three _required_ kwargs, `version`, `deprecated`, and `removed`, and update _all_ the call-sites, but I'm not sure how much merge-churn to expect - I'd prefer you made that call? I'll draft up the first version to start.

**Comment by deivid-rodriguez** [comment]
I agree with the approach you chose of adding a removed `:keyword` parameter. Thanks for working on this, I'll try to review the PR later today.
