### ISSUE TITLE
Clarify proprietary gemspec license guidance

### ISSUE THREAD

**Issue by hlascelles** [rubygems/rubygems#3665]
I would like to get a brief clarification on what license should be applied to internal gems. This came out of this investigation: https://github.com/rubygems/rubygems/issues/3664. I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

We have a large monorepo with dozens of private gems. Each has a gemspec. Everything is closed source (though we are trying to extract things :slightly_smiling_face:). Root projects refer to the internal gems by using the `path` attribute in the Gemfiles.

This all works very well indeed (I am a monorepo fan).

The [gemspec guidelines](https://guides.rubygems.org/specification-reference/#license=) say that "Not specifying a license means all rights are reserved; others have no rights to use the code for any purpose."

However, I have also seen (in some [historic message boards](https://web.archive.org/web/20140515151157/http://rubyforge.org/pipermail/rubygems-developers/2011-October/006852.html)) talk of using `Proprietary`. I also know that `Nonstandard` is [in the codebase](https://github.com/rubygems/rubygems/blob/82a440aea93909f0d191e4256486589aa946414b/lib/rubygems/util/licenses.rb#L8), but I think that refers to Open Source. I also suspect we should not be specifying `MIT` or similar for internal gems.

So, here is the question, and the answer to this may be a one liner: If we have internal closed source gems, with gemspecs, which we are *not* publishing, even to a private gems directory, what license should they specify?

**Comment by deivid-rodriguez** [comment]
In my opinion, what the gemspec guidelines say seems sensible and unless that poses problems for you, not specifying a license should work.

**Comment by hlascelles** [comment]
Good stuff, thanks!
