### ISSUE TITLE
Warn duplicated dependency specifications

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#3676]
I believe we should show a warning when building gems with duplicated dependency specifications, such as

```
spec.add_runtime_dependency "rails", "~> 3.0", "~> 3.0"
```

Because they might indicate a typo.

Also, although probably trickier to fix in general, we could also warn redundant dependency specifications, such as

```
spec.add_runtime_dependency "rails", "> 0", ">= 3.0.0"
```

**Comment by utkarsh2102** [comment]
I'm not sure but I think this is much easier to do this as a part of RuboCop instead?

**Comment by simi** [comment]
@deivid-rodriguez should we do that again only during build time?

**Comment by deivid-rodriguez** [comment]
Yeah, this idea is meant as a tool for gem authors to avoid bugs in their dependency requirements.

@utkarsh2102 It could be made a `rubocop` rule indeed. The difference would be that not everybody would benefit from it by default, but it's an interesting idea... :thinking:
