### ISSUE TITLE
Using Bundler.setup with groups to control the load path not working?

### ISSUE THREAD

**Issue by joehorsnell** [rubygems/rubygems#3683]
I confirm the following:

- [x] You checked all the following documents and couldn't find a solution for your issue:

1. Do you have a reproduction script?

Inline below.

2. What are you trying to accomplish?

To control the gems that Bundler makes available on the load path by passing arguments to `Bundler.setup`, as described in the docs on [groups](https://bundler.io/v2.0/guides/groups.html) and [`Bundler.setup`](https://bundler.io/v2.0/guides/bundler_setup.html)

3. What command did you run?

```
$ cat ./bundler_setup_with_groups.rb
# frozen_string_literal: true

puts "$LOAD_PATH before:"
puts $LOAD_PATH

Bundler.setup(:default, :bar)

puts "$LOAD_PATH after:"
puts $LOAD_PATH

puts "Expect require of thor to work (default group)"
require "thor"

puts "Expect require of zip to fail (group foo not setup)"
require "zip"

$ bundle exec ruby ./bundler_setup_with_groups.rb
$LOAD_PATH before:
.
.
/Users/joe/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/thor-1.0.1/lib
/Users/joe/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/rubyzip-2.3.0/lib
.
.

$LOAD_PATH after:
# Identical to output above

Expect require of thor to work (default group)
Expect require of zip to fail (group foo not setup)
```

4. What were you expecting to happen?

I'm expecting `Bundler.setup(:default, :bar)` to exclude gem `rubyzip` from the load path as it's in the `foo` group. 

5. What actually happened?

The load path is already setup before the call to `Bundler.setup` in the script happens, and since subsequent calls are a [no-op](https://github.com/rubygems/rubygems/blob/master/bundler/lib/bundler.rb#L141), it does nothing. I've debugged through Bundler/rubygems locally and can see that `bundler/setup` is being required from _somewhere_ before the script even runs, so my call to `Bundler.setup` with the groups is then ignored. What am I missing?

6. Is there an exception backtrace? If so, please copy it below.

No exception is raised.

7. Please run `bundle env` and paste the output below:

## Environment

```
Bundler       2.1.4
  Platforms   ruby, x86_64-darwin-18
Ruby          2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin18]
  Full Path   /Users/joe/.rbenv/versions/2.6.6/bin/ruby
  Config Dir  /Users/joe/.rbenv/versions/2.6.6/etc
RubyGems      3.0.3
  Gem Home    /Users/joe/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0
  Gem Path    /Users/joe/.gem/ruby/2.6.0:/Users/joe/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0
  User Home   /Users/joe
  User Path   /Users/joe/.gem/ruby/2.6.0
  Bin Dir     /Users/joe/.rbenv/versions/2.6.6/bin
Tools
  Git         2.26.2
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2020-01-05
Git SHA           32a4159325
Released Version  true
```

## Bundler settings

```
build.libxml-ruby
  Set for the current user (/Users/joe/.bundle/config): "--with-xml2-config=/usr/local/opt/libxml2/bin/xml2-config"
gem.test
  Set for the current user (/Users/joe/.bundle/config): "rspec"
gem.mit
  Set for the current user (/Users/joe/.bundle/config): false
gem.coc
  Set for the current user (/Users/joe/.bundle/config): false
list_command
  Set for the current user (/Users/joe/.bundle/config): "true"
jobs
  Set for your local app (/Users/joe/code/gh/bambooengineering/umbrella/gems/gem_test/.bundle/config): 12
```

### Gemfile

```ruby
source "https://rubygems.org"

gem "thor"

group :foo do
  gem "rubyzip"
end
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    rubyzip (2.3.0)
    thor (1.0.1)

PLATFORMS
  ruby

DEPENDENCIES
  rubyzip
  thor

BUNDLED WITH
   2.1.4
```
For more information please check [Filing Issues: a guide](https://github.com/rubygems/rubygems/blob/master/bundler/doc/contributing/ISSUES.md).

Apologies if I'm missing something completely obvious!

Thank you!

**Comment by joehorsnell** [comment]
Please let me know if there's any further information you need me to provide - thanks.

**Comment by deivid-rodriguez** [comment]
Hi @joehorsnell!

When you `bundle exec` to a script, `bundler/setup` is getting required under the hood. `bundle exec` essentially means "setup my `$LOAD_PATH` and everything else needed so that I can use them gems specificied in my `Gemfile{,.lock}`, and then `exec` the script".

Since `bundler/setup` will make all the gems in your `Gemfile` requirable by default, and subsequent calls to it do nothing, your `Bundler.setup` calls are doing nothing.

The simplest solution would be to make sure `bundler/setup` is not required, by not using `bundle exec`. So running `ruby bundler_setup_with_groups.rb` should do the trick (well your script is also missing `require "bundler"` at the top so that you can use `Bundler.setup`).

Let me know!

**Comment by joehorsnell** [comment]
Hi @deivid-rodriguez, many thanks for responding.

Yes, this is now obvious in hindsight 🤦‍♂️😳! Thanks.

I understand your suggestion about running ruby directly, but what if you want to run a command, say `rspec`, with the version (and its dependencies) controlled by Bundler, but also control which groups in the Gemfile are made available? That seems like a chicken and egg situation, or is there a way to do this?

I guess if `bundle exec` accepted a `--groups` argument that worked like `with`/`without` does for install, it could call `Bundler.setup` passing in those groups, limiting the available gems accordingly? And/or `bundle exec` could be made to respect the existing `BUNDLE_WITH`/`BUNDLE_WITHOUT` env vars used by `bundle install`, or have its own?

Can you please:
1. Advise on my question above (the chicken and egg one!)
2. Let me know if you think the `bundle exec --groups` idea has merit and if so, would you consider accepting a PR for it?
3. Let me know if you'd accept a PR to the Bundler docs (that I linked to above) to clarify this behaviour?

Thanks again.

**Comment by indirect** [comment]
FWIW, the easiest way to get the outcome you're describing is to generate a binstub and then modify it for your needs. For example, `bundle binstubs rspec-core` will generate a `bin/rspec` file that you can then modify to require only the groups you want before rspec is invoked.

**Comment by joehorsnell** [comment]
> FWIW, the easiest way to get the outcome you're describing is to generate a binstub and then modify it for your needs. For example, `bundle binstubs rspec-core` will generate a `bin/rspec` file that you can then modify to require only the groups you want before rspec is invoked.

Of course, great suggestion. Thanks @indirect.

Out of interest, did you have an opinion on the `--groups` option for `bundle exec` and the other q?

**Comment by indirect** [comment]
I haven't looked into it for quite a while, so this could all be wrong, but: my understanding is that `bundle exec` already respects the existing configured with/without groups, because that is how `bundle/setup` works. So if you use `bundle config without` or BUNDLE_WITHOUT, I _think_ it will let you control what gets put into the load path?

But to be clear, this is not a traditional use-case for Bundler users—we want to optimize for people who want to install their entire bundle, and then add their entire bundle to the load path. We're not opposed to trying to support other use-cases (like this one!) but if they conflict, the other one is going to win.

Thanks for the feedback!

**Comment by joehorsnell** [comment]
Ok, I’ll give that a try. Thanks again 👍

**Comment by joehorsnell** [comment]
> I haven't looked into it for quite a while, so this could all be wrong, but: my understanding is that `bundle exec` already respects the existing configured with/without groups, because that is how `bundle/setup` works. So if you use `bundle config without` or BUNDLE_WITHOUT, I _think_ it will let you control what gets put into the load path?
> 

Ok, thanks. I’ll give that a try 👍.

I guess this must be the mechanism you rely on to ensure, for example, that gems in the test group, like say RSpec, can’t be required in production, accidentally or otherwise?

> 
> But to be clear, this is not a traditional use-case for Bundler users—we want to optimize for people who want to install their entire bundle, and then add their entire bundle to the load path. We're not opposed to trying to support other use-cases (like this one!) but if they conflict, the other one is going to win.
> 
> 
> 
> Thanks for the feedback!

👍

**Comment by deivid-rodriguez** [comment]
@indirect Even if you haven't looked into this for a while, all of your suggestions and comments still make total sense :)

@joehorsnell I believe `bundle config without` or setting the `BUNDLE_WITHOUT` environment variable should indeed do the trick for you!

> I guess this must be the mechanism you rely on to ensure, for example, that gems in the test group, like say RSpec, can’t be required in production, accidentally or otherwise?

Yeah, for example.

**Comment by joehorsnell** [comment]
Ok, thanks @deivid-rodriguez and @indirect for your help, much appreciated (as are your efforts in general with Bundler!).

I still feel like maybe the Bundler docs, specifically on [groups](https://bundler.io/v2.0/guides/groups.html), [`Bundler.setup`](https://bundler.io/v2.0/guides/bundler_setup.html) or maybe [`exec](https://bundler.io/v2.0/man/bundle-exec.1.html), might benefit from some clarifications around how this works (eg the fact that `BUNDLE_WITHOUT` is respected)?

I don't want to waste my time, obviously, but happy to do a PR to [rubygems/bundler-site](https://github.com/rubygems/bundler-site) for this, unless you disagree. If you could let me know, that would be great, then happy to close this issue.

**Comment by deivid-rodriguez** [comment]
Absolutely, super happy to take PRs making our docs better. I had a quickly look at the links you pointed to and they definitely could use clarification. And besides that, they're using deprecated flags, like `--with`, `--without`, or `--binstubs`, which are deprecated in favor or `bundle config set --local with`, `bundle config set --local without`, `bundle binstubs`, respectively.
