### ISSUE TITLE
bundler fails to install dependencies due to broken(?) requirements in an old version of ffi

### ISSUE THREAD

**Issue by p-mongo** [rubygems/rubygems#3690]
Our ruby-head builds just now started failing with the following error:

<pre>
There was an error parsing the metadata for the gem ffi (1.9.16): Gem::Requirement::BadRequirementError
Illformed requirement ["< 2.5&>= 2.0"]
The metadata was [["checksum", ["944535ac60044c04ea8c06f64e2beaa1addf69b26df957c8c359ff231f57ce71"]], ["ruby", ["< 2.5&>= 2.0"]]]
</pre>

Full log with --verbose: https://gist.github.com/p-mongo/1102b0a8339d8ab75d0581a7ff5ddf51

We declare a dependency on ffi [without version constraints](https://github.com/mongodb/mongo-ruby-driver/blob/master/gemfiles/standard.rb#L3).

My guess as to what is happening is there are some malformed version specifications (?) in an old version of ffi (1.9.16, current is 1.13) that bundler is choking on.

Since I am not intending to install this version, I would like bundler to use the current version of ffi and continue with installation.

1. Do you have a reproduction script?

Build [this dockerfile](https://github.com/p-mongo/tests/blob/master/bundler-ffi/Dockerfile).

Result: https://gist.github.com/p-mongo/717a83f119286988b27eab6366eb03e3

2. What are you trying to accomplish?

`bundle install` successfully when I use `ffi` as a dependency.

3. What command did you run?

`bundle install`

4. What were you expecting to happen?

Successful installation

5. What actually happened?

Quoted error

6. Is there an exception backtrace? If so, please copy it below.

No backtrace

7. Please run `bundle env` and paste the output below:

Output from dockerfile:

<pre>
Step 9/9 : run bundle env
 ---> Running in 9fba4c6cf0ad
## Environment

```
Bundler             2.2.0.dev
  Platforms         ruby, x86_64-linux
Ruby                2.8.0p-1 (2020-06-04 revision 047471c52960e32146025fab064487d25f92a141) [x86_64-linux]
  Full Path         /ruby-head/bin/ruby
  Config Dir        /etc
RubyGems            3.2.0.pre1
  Gem Home          /ruby-head/lib/ruby/gems/2.8.0
  Gem Path          /root/.local/share/gem/ruby/2.8.0:/ruby-head/lib/ruby/gems/2.8.0
  User Home         /root
  User Path         /root/.local/share/gem/ruby/2.8.0
  Bin Dir           /ruby-head/bin
Tools               
  Git               2.7.4
  RVM               not installed
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2020-06-05
Git SHA           unknown
Released Version  false
```

### Gemfile

```ruby
source 'https://rubygems.org'

gem 'ffi'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    ffi (1.13.0)

PLATFORMS
  ruby

DEPENDENCIES
  ffi

BUNDLED WITH
   2.2.0.dev
```
</pre>

**Comment by p-mongo** [comment]
Also affected: [ZenTest](https://ci.appveyor.com/project/p-mongo/bson-ruby/builds/33329096/job/evmuou6jtrwpnmgb)

**Comment by indirect** [comment]
Thank you for reporting this! We are in the process of a coordinated change to both RubyGems.org and Bundler/RubyGems at the same time. The exception you mention has been fixed in https://github.com/rubygems/rubygems/pull/3663, which is merged to the Bundler/RubyGems master branch, but not yet merged into ruby-head.

Once ruby-head pulls the latest from rubygems/rubygems, everything should be functional again. 👍
