### ISSUE TITLE
Gem's operations from code

### ISSUE THREAD

**Issue by DonPiotr** [rubygems/rubygems#3691]
Hi!

My current problem is:
I want to uninstall/install gem directly from ruby code.
In particular from Rakefile.

My code is:
task :my_task do
  sh "rm mygem-\*.gem"
  sh "gem uninstall mygem"
  sh "gem build"
  sh "gem install mygem-\*.gem"
end

Can I do it by calling some RubyGems method from ruby code directly without sh?

This issue is related to:
  - [X] Other

**Comment by hsbt** [comment]
You can invoke install command like:

```ruby
require "rubygems/commands/install_command"

cmd = Gem::Commands::InstallCommand.new
cmd.options[:args] = ["rails"]
cmd.execute
```

Other commands are same usage.
