### ISSUE TITLE
bundle install (with path) - handling of default vs bundled gems

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#3693]
Working with several repos using Bundler in their CI, I was reminded of some behavior that seems based on Ruby builds' layout from a long time ago, when 'bundled' gems did not exist.

When running `bundle install` with a `path` specified, if a required gem matches a default gem, it is not installed.  If a required gem matches a bundled gem, it is duplicated in the specified path.

Why the duplication with bundled gems?

**Comment by deivid-rodriguez** [comment]
What is it exactly that you are suggesting here? If a path is configured for `bundle install`, should we not install to that path? :thinking:

**Comment by MSP-Greg** [comment]
See #3905

Seems to also be about the difference in behavior re bundled vs default?

**Comment by deivid-rodriguez** [comment]
That one sounds like a bug. What is this one about, could you clarify?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
