### ISSUE TITLE
Remove Eric Hodel as a maintainer and a member due to violating CoC

### ISSUE THREAD

**Issue by deepj** [rubygems/rubygems#3695]
Eric Hodel publicly attacked and was very hostile against Bozhidar Batsov on Twitter:

https://twitter.com/bbatsov/status/1269490401054019584

I do not think this person would represent Ruby community and would be removed from rubygems organization.

As an autistic person and non-western person I don't feel being welcome and safe with person like Eric Holder in Ruby community.

**Comment by hsbt** [comment]
Calm down, Please.
