### ISSUE TITLE
3.2.0.pre1 - Gem.user_dir change?

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#3707]
```
RG Vers      Gem.user_dir
3.1.4        C:/Users/runneradmin/.gem/ruby/2.7.0
3.2.0.pre1   C:/Users/runneradmin/.local/share/gem/ruby/2.8.0
```

Is this considered a beneficial change?  XDG related?

When 3.2.0 is released, anyone updating to it will see their user installed gems 'disappear'?

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
No, RG 3.2 will fallback `C:/Users/runneradmin/.gem/ruby/2.7.0` if it's exists.

**Comment by MSP-Greg** [comment]
I did notice that and I was about to look thru the code.  The above is from Actions, but locally it falls back. But, I do have the 'user bin' folder in path, so I wasn't sure...  Thanks.

Is the change XDG related?

**Comment by hsbt** [comment]
> Is the change XDG related?

Yes.

**Comment by simi** [comment]
I can confirm it fallbacks to old directory if exists.
