### ISSUE TITLE
Bundler config adds trailing backslash to build options, causing builds to fail

### ISSUE THREAD

**Issue by earksiinni** [rubygems/rubygems#3727]
Thank you for contributing to the [rubygems](https://github.com/rubygems/rubygems) repository, and specifically to the [Bundler](https://bundler.io/) gem.

Before processing your issue please confirm that:

- [x] You checked all the following documents and couldn't find a solution for your issue:

- [Troubleshooting common issues](https://github.com/rubygems/rubygems/blob/master/bundler/doc/TROUBLESHOOTING.md)
- [Bundler documentation site](https://bundler.io/)
- [Bundler man pages](https://bundler.io/man/bundle.1.html)
- [Bundler command line reference](https://bundler.io/v2.0/commands.html)

If you haven't done that, please do it before creating a new issue.

Please answer the following questions so we can process your issue as fast as possible:

1. Do you have a reproduction script? It would be really helpful for us if you provide one. Examples: [Sample repro script for Bundler issues](https://gist.github.com/xaviershay/6207550), [Another sample repro script for Bundler issues](https://gist.github.com/xaviershay/6295889).

I don't have a repro script, sorry, but I have been able to reproduce the issue on my local machine with these steps:

- `cd` into a new Rails project.
- `brew install libxml2 libxslt libiconv`
- `bundle config build.nokogiri --use-system-libraries --with-xml2-dir=/usr/local/opt/libxml2 --with-xslt-dir=/usr/local/opt/libxslt --with-iconv-dir=/usr/local/opt/libiconv`
- `bundle install`

2. What are you trying to accomplish?

    Your answer: getting the native extensions for [Nokogiri](https://github.com/sparklemotion/nokogiri), a dependency of my Rails project, to compile properly on my macOS host by setting the build options using `bundle config`.

3. What command did you run?

    Your answer: `bundle config build.nokogiri --use-system-libraries --with-xml2-dir=/usr/local/opt/libxml2 --with-xslt-dir=/usr/local/opt/libxslt --with-iconv-dir=/usr/local/opt/libiconv` and `bundle install`

4. What were you expecting to happen?

    Your answer: that the native extensions should compile and Nokogiri should finish installing. Running `gem install -- --use-system-libraries --with-xml2-dir=/usr/local/opt/libxml2 --with-xslt-dir=/usr/local/opt/libxslt --with-iconv-dir=/usr/local/opt/libiconv` succeeds, but the equivalent using `bundle config build.nokogiri ...` and `bundle install` fails.

5. What actually happened?

    Your answer: the installation complains about a missing `iconv.h` header file, which is what the `--use-system-libraries` and `--with-iconv-dir` options are supposed to solve. Upon closer examination of the build code, Nokogiri [parses the passed options to find `--use-system-libraries` inside `extconf.rb`](https://github.com/sparklemotion/nokogiri/blob/v1.10.9/ext/nokogiri/extconf.rb#L381) with the help of [`MakeMakefile#arg_config`](https://www.rubydoc.info/stdlib/mkmf/MakeMakefile:arg_config). This method is able to parse the options that get passed when I manually run `gem install nokogiri -- ...` with the appropriate options. However, Bundler adds a trailing slash to each option, which messes up the parsing (see backtrace below).

6. Is there an exception backtrace? If so, please copy it below.

    Your answer:

Relevant part is `/nix/store/wwfmgwa9fkbvj51yjbb3rdnanv80pafa-ruby-2.6.6/bin/ruby -I /nix/store/wwfmgwa9fkbvj51yjbb3rdnanv80pafa-ruby-2.6.6/lib/ruby/2.6.0 -r ./siteconf20200615-25300-1x3yehs.rb extconf.rb --use-system-libraries\ --with-xml2-dir\=/usr/local/opt/libxml2\
--with-xslt-dir\=/usr/local/opt/libxslt\ --with-iconv-dir\=/usr/local/opt/libiconv`. Note the trailing backslashes (e.g., `---use-system-libraries\`).

```
$ bundle install
Warning: the running version of Bundler (1.17.2) is older than the version that created the lockfile (1.17.3). We suggest you upgrade to the latest version of Bundler by running `gem install bundler`.
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
Fetching gem metadata from https://rubygems.org/.......
Using rake 13.0.1
Using concurrent-ruby 1.1.6
Using aasm 5.0.6
Using i18n 1.8.2
Using minitest 5.14.0
Using thread_safe 0.3.6
Using tzinfo 1.2.6
Using activesupport 5.2.4.2
Using builder 3.2.4
Using erubi 1.9.0
Using mini_portile2 2.4.0
Fetching nokogiri 1.10.9
Installing nokogiri 1.10.9 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: /Users/ersin/projects/gamacy/.direnv/ruby/gems/nokogiri-1.10.9/ext/nokogiri
/nix/store/wwfmgwa9fkbvj51yjbb3rdnanv80pafa-ruby-2.6.6/bin/ruby -I /nix/store/wwfmgwa9fkbvj51yjbb3rdnanv80pafa-ruby-2.6.6/lib/ruby/2.6.0 -r ./siteconf20200615-25300-1x3yehs.rb extconf.rb --use-system-libraries\ --with-xml2-dir\=/usr/local/opt/libxml2\
--with-xslt-dir\=/usr/local/opt/libxslt\ --with-iconv-dir\=/usr/local/opt/libiconv
checking if the C compiler accepts  -I /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/include/libxml2... yes
checking if the C compiler accepts -Wno-error=unused-command-line-argument-hard-error-in-future... no
Building nokogiri using packaged libraries.
Using mini_portile version 2.4.0
checking for iconv.h... no
-----
The file "iconv.h" is missing in your build environment,
which means you haven't installed Xcode Command Line Tools properly.

To install Command Line Tools, try running `xcode-select --install` on
terminal and follow the instructions.  If it fails, open Xcode.app,
select from the menu "Xcode" - "Open Developer Tool" - "More Developer
Tools" to open the developer site, download the installer for your OS
version and run it.
-----
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/nix/store/wwfmgwa9fkbvj51yjbb3rdnanv80pafa-ruby-2.6.6/bin/$(RUBY_BASE_NAME)
	--help
	--clean
	--use-system-libraries
	--enable-static
	--disable-static
	--with-zlib-dir
	--without-zlib-dir
	--with-zlib-include
	--without-zlib-include=${zlib-dir}/include
	--with-zlib-lib
	--without-zlib-lib=${zlib-dir}/lib
	--enable-cross-build
	--disable-cross-build

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Users/ersin/projects/gamacy/.direnv/ruby/extensions/x86_64-darwin-17/2.6.0/nokogiri-1.10.9/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Users/ersin/projects/gamacy/.direnv/ruby/gems/nokogiri-1.10.9 for inspection.
Results logged to /Users/ersin/projects/gamacy/.direnv/ruby/extensions/x86_64-darwin-17/2.6.0/nokogiri-1.10.9/gem_make.out

An error occurred while installing nokogiri (1.10.9), and Bundler cannot continue.
Make sure that `gem install nokogiri -v '1.10.9' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  administrate-field-jsonb was resolved to 0.4.1, which depends on
    rails was resolved to 5.2.4.2, which depends on
      actioncable was resolved to 5.2.4.2, which depends on
        actionpack was resolved to 5.2.4.2, which depends on
          actionview was resolved to 5.2.4.2, which depends on
            rails-dom-testing was resolved to 2.0.3, which depends on
              nokogiri
```

7. Please run `bundle env` and paste the output below:

    Your answer:

## Environment

```
Bundler       1.17.2
  Platforms   ruby, x86_64-darwin-17
Ruby          2.6.6p146 (2020-03-31 revision 0) [x86_64-darwin17]
  Full Path   /nix/store/wwfmgwa9fkbvj51yjbb3rdnanv80pafa-ruby-2.6.6/bin/ruby
  Config Dir  /nix/store/wwfmgwa9fkbvj51yjbb3rdnanv80pafa-ruby-2.6.6/etc
RubyGems      3.1.2
  Gem Home    /Users/ersin/projects/gamacy/.direnv/ruby
  Gem Path    /nix/store/wwfmgwa9fkbvj51yjbb3rdnanv80pafa-ruby-2.6.6/lib/ruby/gems/2.6.0:/nix/store/wwfmgwa9fkbvj51yjbb3rdnanv80pafa-ruby-2.6.6/lib/ruby/gems/2.6.0
  User Path   /Users/ersin/.gem/ruby/2.6.0
  Bin Dir     /Users/ersin/projects/gamacy/.direnv/ruby/bin
Tools         
  Git         2.27.0
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2018-12-19
Git SHA           3fc4de72b
Released Version  false
```

## Bundler settings

```
build.nokogiri
  Set for the current user (/Users/ersin/.bundle/config): "--use-system-libraries --with-xml2-dir=/usr/local/opt/libxml2 --with-xslt-dir=/usr/local/opt/libxslt --with-iconv-dir=/usr/local/opt/libiconv"
bin
  Set via BUNDLE_BIN: "/Users/ersin/projects/gamacy/.direnv/bin"
```

For more information please check [Filing Issues: a guide](https://github.com/rubygems/rubygems/blob/master/bundler/doc/contributing/ISSUES.md).

Thank you!

**Comment by deivid-rodriguez** [comment]
Did you try the latest bundler version? I believe we fixed something similar recently.

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.

**Comment by stanhu** [comment]
Yes, this was fixed in https://github.com/rubygems/bundler/pull/7023.
