### ISSUE TITLE
Bundle parses Gemfile and installs dependencies without throwing error or warning for invalid ones.

### ISSUE THREAD

**Issue by Kadaaran** [rubygems/rubygems#3734]
### Context
This is more a question than a bug report. In my Gemfile lies this line:
`gem 'webpacker', '~> 4.x'`

If I run `bundle i` the dependencies are installed and `webpacker (4.2.2)` is installed. 
The bundle output does not return any errors or warning for the `x` which is invalid but still install a valid version.

Running `gem install webpacker -v 4.x` however throws an error and install the last version:
```
gem install webpacker -v 4.x
ERROR:  Could not find a valid gem 'webpacker' (= 4.x) in any repository
ERROR:  Possible alternatives: webpacker
```  

**Question**: What do you think about having a warning that the version is not found and that one got installed instead ? 

### Informations

1. Do you have a reproduction script? 

    Script URL: https://gist.github.com/Kadaaran/6c0db03e8a5e6eb91622f149e9252458

2. What are you trying to accomplish?

    Your answer: Check if a warning was thrown when trying to install a dependency with an invalid version number.

3. What command did you run?

    Your answer: `bundle i`

4. What were you expecting to happen?

    Your answer: A warning or an error regarding the line `gem 'webpacker', '~> 4.x'`

5. What actually happened?

    Your answer: Dependencies install, but when running independently `gem install webpacker 4.x` it throws an error as expected.

6. Is there an exception backtrace?
     No.

7. Please run `bundle env` and paste the output below:

## Environment

```
Bundler       2.0.2
  Platforms   ruby, x86_64-darwin-17
Ruby          2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin17]
  Full Path   /Users/kassandre/.rbenv/versions/2.6.2/bin/ruby
  Config Dir  /Users/kassandre/.rbenv/versions/2.6.2/etc
RubyGems      3.0.3
  Gem Home    /Users/kassandre/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0
  Gem Path    /Users/kassandre/.gem/ruby/2.6.0:/Users/kassandre/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0
  User Path   /Users/kassandre/.gem/ruby/2.6.0
  Bin Dir     /Users/kassandre/.rbenv/versions/2.6.2/bin
Tools
  Git         2.18.0
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2019-06-13
Git SHA           496bca538
Released Version  true
```

## Bundler settings

```
gem.test
  Set for the current user (/Users/kassandre/.bundle/config): "minitest"
gem.mit
  Set for the current user (/Users/kassandre/.bundle/config): true
gem.coc
  Set for the current user (/Users/kassandre/.bundle/config): false
build.mysql2
  Set for the current user (/Users/kassandre/.bundle/config): "--with-opt-dir=/usr/local/opt/openssl@1.1"
```

### Gemfile

```ruby
git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

ruby '2.6.2'
source 'https://rubygems.org'

gem 'bundler', '2.0.2'
gem 'webpacker', '~> 4.x'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actionpack (6.0.3.1)
      actionview (= 6.0.3.1)
      activesupport (= 6.0.3.1)
      rack (~> 2.0, >= 2.0.8)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.2.0)
    actionview (6.0.3.1)
      activesupport (= 6.0.3.1)
      builder (~> 3.1)
      erubi (~> 1.4)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.1, >= 1.2.0)
    activesupport (6.0.3.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
      zeitwerk (~> 2.2, >= 2.2.2)
    builder (3.2.4)
    concurrent-ruby (1.1.6)
    crass (1.0.6)
    erubi (1.9.0)
    i18n (1.8.2)
      concurrent-ruby (~> 1.0)
    loofah (2.5.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    method_source (0.9.2)
    mini_portile2 (2.4.0)
    minitest (5.14.1)
    nokogiri (1.10.9)
      mini_portile2 (~> 2.4.0)
    rack (2.2.3)
    rack-proxy (0.6.5)
      rack
    rack-test (1.1.0)
      rack (>= 1.0, < 3)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.3.0)
      loofah (~> 2.3)
    railties (6.0.3.1)
      actionpack (= 6.0.3.1)
      activesupport (= 6.0.3.1)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.20.3, < 2.0)
    rake (13.0.1)
    thor (0.20.3)
    thread_safe (0.3.6)
    tzinfo (1.2.7)
      thread_safe (~> 0.1)
    webpacker (4.2.2)
      activesupport (>= 4.2)
      rack-proxy (>= 0.6.1)
      railties (>= 4.2)
    zeitwerk (2.3.0)

PLATFORMS
  ruby

DEPENDENCIES
  bundler (= 2.0.2)
  webpacker (~> 4.x)

RUBY VERSION
   ruby 2.6.2p47

BUNDLED WITH
   2.0.2
```

**Comment by deivid-rodriguez** [comment]
Hi @Kadaaran!

The `bundler` behavior is correct, and `~> 4.x` actually has a meaning. Whenever a version specification in rubygems includes a letter, like "x", it means that prereleases should be considered. So in this case, `~> 4.x` means install any version or prerelease version higher than `4.x`. In the case of prereleases, lexicographical order is used, so it would mean that version `4.0.0.zoo` matches the requirement, but `4.0.0.foo` does not. Normally, when you want to allow all prereleases you specific `~> 4.a`, because the ".a" prerelease is the first possibly prerelease in lexicographical order.

I learnt about all this by reading the docs in the `version.rb` file:

https://github.com/rubygems/rubygems/blob/86bf6719c654821407880ce401c909d56beb582f/lib/rubygems/version.rb#L1-L151

Regarding the rubygems behavior, I'm not seeing what you're seeing. When I run `gem install webpacker -v 4.x`, I get an error and nothing gets installed, because there's no version named "4.x". If I specify `gem install webpacker:'~> 4.x'`, then the latest version gets installed because it's the best match for the `~> 4.x` requirement.

Let me know if this makes sense.

**Comment by Kadaaran** [comment]
Hey @deivid-rodriguez !

Thank you so much for your answer, regarding the behaviour I agree and I was not questioning it. I was curious about the warning situation.
I got caught up between versions and that a letter was specified. Thanks to your explanation, it is all clear now.

Sorry to have open this issue for this matter I'm closing it right away. Thank you again 🙏

**Comment by deivid-rodriguez** [comment]
No problem at all, thanks for your question! The "prerelease letters" are a bit weird when you first encounter them.

Good luck :)
