### ISSUE TITLE
GitHub Actions jobs - filter by path?

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#3735]
Actions allows filtering jobs by path.  See:
https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths

There are an awful lot of jobs being run, and the workflows don't seem to indicate that all RG jobs need to run for a Bundler change, and vice versa.

So, I see three types of jobs:
1. Jobs that only need to run with a RubyGems change
2. Jobs that only need to run with a Bundler change
3. Jobs that need to run with any change

With some reorganization, this could be corrected.  It may require splitting jobs in workflows, or adding additional workflows, but it would quicken CI time quite a bit...

Thoughts?

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
I'd rather keep running everything for now. The line between bundler and rubygems is very thin now and sometimes changing one does affect the other, so I wouldn't spend any time on this.

If we want to improve CI time, we should figure out why Windows tests are so slow and how to speed them up, since that's the bottleneck at the moment with a lot of difference.

**Comment by MSP-Greg** [comment]
The PR I just did ran 57 jobs.  All those jobs may be free, but they still have a cost, whether that be to MSFT/GH, other Actions users waiting for a finite amount of runners, or even society (energy, recycling, etc)

> The line between bundler and rubygems is very thin now

Yes, but as I mentioned, there appear to be many jobs that are not using both the RubyGems and Bundler code contained in master.

> why Windows tests are so slow

Not sure, I noticed it a long time ago.  Whether it's the specs, Bundler/RubyGems, Ruby itself, or Windows, I'm not sure.  The observation of the problem (slow tests) is simple, but the actual cause (and possible fix) maybe difficult to find.  In Ruby core, test-all takes about 4 times longer on Windows that on Ubuntu, and Ubuntu is running more tests (things like fork, UNIXSockets, etc)...

**Comment by deivid-rodriguez** [comment]
Ok, if you want to work on this, you can try this optimization:

If only rubygems code changes, only entries in `bundler` workflows with `RGV=..` need to run.

**Comment by MSP-Greg** [comment]
Don't hold your breath.

I haven't worked that much with path filtering, what I'll probably do is create a branch in my fork with the workflow changes, then rebase & push several times over a few days to double check what jobs run.

There may be repo changes that are to difficult to filter for, in which case I'll run those jobs all the time. An example might to changing the actual workflows, etc.  Not sure...

I forgot to mention, I need to look at how updates to RG 2.x and Bundler 1.x are handled.  Are fixes (security or otherwise) still be applied to them?

**Comment by deivid-rodriguez** [comment]
We haven't backported any stuff to either of those for a long time, don't worry about them.

**Comment by MSP-Greg** [comment]
I've got this done and tested with a Bundler change.  All the Bundler workflows ran, along with install.yml, ruby-core, & ubuntu-lint.yml.  Two Bundler workflows test against RubyGems master, so those jobs needed to be placed in separate workflows.  Filtering is by workflow file, not by job code.

So how do you want the commits?  One for the ten changed files, and one for the two additions?  The ten files share similar changes, so grouping them together makes sense.  The two additions are identical to the 'body' of the two they were split from...

**Comment by deivid-rodriguez** [comment]
Can't see your code yet, but from what you explain that makes sense I guess?

**Comment by MSP-Greg** [comment]
Actually, the new files are identical with the main code of the two existing, except for the filtering and one line of the matrix, so I thought one commit would be fine?

I'm going to test a RG commit in my fork just to be sure.

Also, I changed the push section to:
```yml
  push:
    branches:
      - master
      - "pr-**"
```

That should allow contributors (like me) to run CI in their forks if the branch starts with 'pr-'.  I believe that once the branch is pushed for a PR, it won't double run the CI.

With the current filtering, one can't run CI in a fork unless it's on the master branch, and removing the filtering means anyone doing a PR based on a branch here (into master) would have double CI.  

Make sense?  It's something that was never an issue in AppVeyyor or Travis, but the way Actions is set up, it is...

**Comment by simi** [comment]
@deivid-rodriguez https://github.com/rubygems/rubygems/compare/master...MSP-Greg:pr-win-bundle-exec-load

**Comment by MSP-Greg** [comment]
@simi  That's not quite it, I'm using that for testing.  About to push a PR.  It works for both Rubygems & Bundler...

**Comment by deivid-rodriguez** [comment]
> Make sense? It's something that was never an issue in AppVeyyor or Travis, but the way Actions is set up, it is...

[We already talked about this](https://github.com/rubygems/rubygems/issues/2451). I'm happy with the current way.
