### ISSUE TITLE
bundle exec and Windows - Bundler::CLI::Exec#run always uses #kernel_exec

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#3741]
This means Windows `bundle exec` is often starting another Ruby process, where it seems that other OS's are using `#kernel_load`.

This may be causing slower test times.  Haven't had a chance to think about a fix yet.

**Comment by MSP-Greg** [comment]
I've got a fix for this, need to work with it more.  It does not make a noticeable difference in test times.

With `bash`, every command is a file/executable.  So, with `bash`, `echo` is an executable.  On Windows, there are native or intrinsic commands that are part of cmd.exe, and `echo` is one.  Hence, one can't determine if the command is valid before running `exec`.  I assume the main use of `bundle exec` is running ruby scripts with a shebang line that are in `"#{Bundler.bundle_path}/bin"`, so that will always call `load`.

Anyway, moving on to trying to fix `commands/exec_spec.rb` so fewer specs need to be skipped.  Also, since so many specs shell out, and that runs in a cmd shell, I will work on getting the specs to run from a cmd shell, instead of the current bash.

JFYI, when running Ruby from bash, I've tried to get it to shell out with bash, and can't get it to work.

**Comment by deivid-rodriguez** [comment]
> I assume the main use of bundle exec is running ruby scripts with a shebang line that are in "#{Bundler.bundle_path}/bin", so that will always call load.

If I'm following, I believe it's the other way around? If people are maintaining project binstubs inside their project, they will most likely not be using `bundle exec` for those, since being able to skip that is part of the point of creating the binstubs, right?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
