### ISSUE TITLE
`bundle clean --force` removes default gem executables

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#3757]
Thank you for contributing to the [rubygems](https://github.com/rubygems/rubygems) repository, and specifically to the [Bundler](https://bundler.io/) gem.

### Please describe the problem as clearly as you can

We have a `bundle clean --force` command that removes every gem not in the current bundle from your system. This command goes too far and removes executables from default gems.

### Please post system independent reproduction steps

On any application, and on ruby 2.7, run

```
$ irb --version
irb 1.2.3 (2020-02-15)
$ bundle clean --force
Removing irb (1.2.3)
$ irb --version
Traceback (most recent call last):
	1: from /home/deivid/.rbenv/versions/2.7.1/bin/irb:23:in `<main>'
/home/deivid/.rbenv/versions/2.7.1/bin/irb:23:in `load': cannot load such file -- /home/deivid/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/irb-1.2.3/exe/irb (LoadError)
```

### What command did you run?

    bundle clean --force

### What were you expecting to happen?

All gems are removed, but not executables from default gems, because default gems should be always available.

### What actually happened?

IRB is gone.

NOTE: I experimented with a better issue report template in this issue, will open a PR for it :)

**Comment by rubyFeedback** [comment]
Hehe the template is quite funny since it looks as if you are almost talking to yourself there,
in particular with the "Thank you for contributing to the rubygems repository" intro. I mean
you are not exactly a newcomer to rubygems ...  ;)

**Comment by deivid-rodriguez** [comment]
Hehehe, yeah.

In https://github.com/rubygems/rubygems/pull/3784 I put that appreciation message inside `<!-- ... -->`, so that the OP gets the appreciation, but it doesn't show up by default in the reported issue.
