### ISSUE TITLE
gem fails to update openssl from 2.1.2 to 2.2.0

### ISSUE THREAD

**Issue by rgoldberg** [rubygems/rubygems#3760]
I'm having a problem.

My current problem is gem fails to update openssl from 2.1.2 to 2.2.0.

```bash
sudo -H gem update -n /usr/local/bin openssl
```

Outputs:

```bash
Updating installed gems
Updating openssl
Building native extensions. This could take a while...
ERROR:  Error installing openssl:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.6.0/gems/openssl-2.2.0/ext/openssl
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby -I /Library/Ruby/Site/2.6.0 -r ./siteconf20200625-86744-1hc440r.rb extconf.rb
checking for t_open() in -lnsl... no
checking for socket() in -lsocket... no
checking for openssl/ssl.h... no
*** extconf.rb failed ***
Could not create Makefile due to some reason, probably lack of necessary
libraries and/or headers.  Check the mkmf.log file for more details.  You may
need configuration options.

Provided configuration options:
	--with-opt-dir
	--without-opt-dir
	--with-opt-include
	--without-opt-include=${opt-dir}/include
	--with-opt-lib
	--without-opt-lib=${opt-dir}/lib
	--with-make-prog
	--without-make-prog
	--srcdir=.
	--curdir
	--ruby=/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/$(RUBY_BASE_NAME)
	--with-openssl-dir
	--with-openssl-include
	--without-openssl-include=${openssl-dir}/include
	--with-openssl-lib
	--without-openssl-lib=${openssl-dir}/lib
	--with-kerberos-dir
	--without-kerberos-dir
	--with-kerberos-include
	--without-kerberos-include=${kerberos-dir}/include
	--with-kerberos-lib
	--without-kerberos-lib=${kerberos-dir}/lib
	--with-debug
	--without-debug
	--enable-debug
	--disable-debug
	--with-nsllib
	--without-nsllib
	--with-socketlib
	--without-socketlib
	--with-openssl-config
	--without-openssl-config
	--with-pkg-config
	--without-pkg-config
extconf.rb:99:in `<main>': OpenSSL library could not be found. You might want to use --with-openssl-dir=<dir> option to specify the prefix where OpenSSL is installed. (RuntimeError)

To see why this extension failed to compile, please check the mkmf.log which can be found here:

  /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/openssl-2.2.0/mkmf.log

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.6.0/gems/openssl-2.2.0 for inspection.
Results logged to /Library/Ruby/Gems/2.6.0/extensions/universal-darwin-19/2.6.0/openssl-2.2.0/gem_make.out
Gems updated: openssl
```

Logs are attached.

[gem_make.out.txt](https://github.com/rubygems/rubygems/files/4831923/gem_make.out.txt)
[mkmf.log](https://github.com/rubygems/rubygems/files/4831924/mkmf.log)

I am running macOS 10.15.5 with the latest stable XCode.  All other gems are up to date, and the rest of my software should be the latest stable or newer.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [X] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.0.6
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
It seems that rubygems is failing to find the `openssl/ssl.h` header in your system, needed to install the gem. I'm not sure why it's happening, but I think it's due to some trouble with your ruby installation.

If you look at the log you posted, note how the very first check the openssl extension does, namely, this one:

https://github.com/ruby/openssl/blob/93213b2730a45fe997b8e581c64c42e13cd9abde/ext/openssl/extconf.rb#L30

is already having issues:

```
=== OpenSSL for Ruby configurator ===
=== Checking for system dependent stuff... ===
have_library: checking for t_open() in -lnsl... -------------------- no

"xcrun clang -o conftest -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/universal-darwin19 -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0/ruby/backward -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/include/ruby-2.6.0 -I. -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.Internal.sdk/usr/local/libressl/include -D_XOPEN_SOURCE -D_DARWIN_C_SOURCE -D_DARWIN_UNLIMITED_SELECT -D_REENTRANT    -g -Os -pipe -DHAVE_GCC_ATOMIC_BUILTINS conftest.c  -L. -L/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.Internal.sdk/usr/local/libressl/lib -L. -L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.Internal.sdk/usr/local/lib   -arch x86_64   -lruby.2.6   "
ld: warning: directory not found for option '-L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.Internal.sdk/usr/local/libressl/lib'
ld: warning: directory not found for option '-L/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.Internal.sdk/usr/local/lib'
checked program was:
/* begin */
1: #include "ruby.h"
2: 
3: int main(int argc, char **argv)
4: {
5:   return 0;
6: }
/* end */
```

The command to check for the library presence is being passed a folder, `/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.Internal.sdk/usr/local/libressl/lib', which doesn't exist. And this folder might be where your openssl files should be.

Unfortunately I know little about MacOS, so I can't really help further. I presume reinstalling your ruby should do the trick.

**Comment by rgoldberg** [comment]
`/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.Internal.sdk` doesn't exist.

`MacOSX10.15.sdk` exists in the parent of the nonexistent `MacOSX10.15.Internal.sdk`.

`MacOSX10.15.sdk` is a link to `MacOSX.sdk` in the same directory.

`usr/local/libressl/lib` doesn't exist in that directory because, while `usr` exists, it doesn't contain `local`.

Running `find . -iname '*libressl*'` in `MacOSX10.15.sdk` does not find any matching paths.

Running `find . -iname '*ssl.h*'` returns:

```
./usr/include/apache2/mod_ssl_openssl.h
./usr/include/apache2/mod_ssl.h
```

This directory seems to be a macOS SDK, not a Ruby SDK.

I'm using the Ruby supplied by macOS 10.15.5. I don't directly use Ruby myself, but I try to update all existing software on my system so I can get security patches, bug fixes, performance improvements, etc.

**Comment by MSP-Greg** [comment]
You're not having a problem with RubyGems.   You need OpenSSL installed, probably something like:
```
brew install openssl@1.1
```

After that, I'm not sure what you need to do for Ruby OpenSSL to find it, as it compiles with it...

**Comment by rgoldberg** [comment]
`openssl@1.1` is already installed via brew.  It is located at `/usr/local/Cellar/openssl@1.1/1.1.1g`.

I imagine that the `openssl` gem doesn't work with XCode 11.5, since the path to the `libressl/lib` doesn't exist under `/Applications/Xcode.app`.

Has anyone else successfully installed version 2.2.0 of the `openssl` gem on macOS 10.15.5 with XCode 11.5?

**Comment by deivid-rodriguez** [comment]
Apparently the openssl version that comes with macOS 10.15.5 is broken (as in, does not include the proper headers).

Maybe try setting the environment variables mentioned here: https://github.com/rbenv/ruby-build/issues/1431 so that you homebrew openssl installation is properly picked up.

**Comment by MSP-Greg** [comment]
As @deivid-rodriguez mentioned, or possibly add the following to your gem command:
```
-- --with-openssl-dir /usr/local/Cellar/openssl@1.1/1.1.1g
```

**Comment by rgoldberg** [comment]
@MSP-Greg That worked.

@deivid-rodriguez Has anyone notified Apple to fix openssl?  Is there any web page to track the progress?

Thanks for the help.

**Comment by deivid-rodriguez** [comment]
No idea, sorry. I found about this in the ruby-build project, which has [a shell function called `has_broken_mac_openssl`](https://github.com/rbenv/ruby-build/blob/157c719e3f432874119d34c4645d1da869ee180c/bin/ruby-build#L1033-L1039) :rofl:: Maybe you can follow up on this issue in that repo.

Closing, happy you got this sorted out!

**Comment by MSP-Greg** [comment]
@rgoldberg

Locally I'm a Windows type, so I'm not that familiar with macOS.  The following outputs the OpenSSL version that Ruby OpenSSL was compiled with, then the version of OpenSSL that Ruby OpenSSL is using at runtime.  They should be the same.
```
ruby -ropenssl -e "puts OpenSSL::OPENSSL_VERSION, OpenSSL::OPENSSL_LIBRARY_VERSION"
```

**Comment by hsbt** [comment]
The Ruby interpriter provided by macOS is blackbox for us. We can't care its configuration and related libraries.

**Comment by rgoldberg** [comment]
Would it make sense to add an instructive error message about how to get around this error? I would imagine that many might run into this problem on recent macOS versions.

Or, better yet, are the openssl headers available under any other standard path in recent versions of macOS? (without having to install them separately)

**Comment by MSP-Greg** [comment]
As mentioned above, this isn't a RubyGems issue.  From the OpenSSL gemspec or the RubyGems.org website (search for OpenSSL), the source code for OpenSSL is at:

https://github.com/ruby/openssl

An issue there to discuss the problem would be more appropriate.

**Comment by itsmelion** [comment]
> As @deivid-rodriguez mentioned, or possibly add the following to your gem command:
> 
> ```
> -- --with-openssl-dir=/usr/local/Cellar/openssl@1.1/1.1.1g
> ```

**Legit!**
Only needed a tweak in the command, to map to the actual folder in my OS _(currently MacOS12.0-beta)_ which was:
`--with-openssl-dir=/usr/local/Cellar/openssl@1.1/1.1.1l`

So, if those not work, just look the /usr/local/Cellar/... until the openssl you actually have.

> I've carrying on with this noise in my terminal for a couple of years already. until I got tired of it, and decided to search for a fix.
