### ISSUE TITLE
I am trying to install Discourse on mac using this guide https://meta.discourse.org/t/beginners-guide-to-install-discourse-on-macos-for-development/15772. When running the command "bundle install" I get the following error:  Fetching gem metadata from https://rubygems.org/.........        zeitwerk-2.3.1 requires ruby version >= 2.4.4, which is incompatible with the current version, ruby 2.3.0p0.           How would I be able to update to resolve this issue.

### ISSUE THREAD

**Issue by ArslanM786** [rubygems/rubygems#3768]
Thank you for contributing to the [rubygems](https://github.com/rubygems/rubygems) repository, and specifically to the [Bundler](https://bundler.io/) gem.

Before processing your issue please confirm that:

- [x] You checked all the following documents and couldn't find a solution for your issue:

- [Troubleshooting common issues](https://github.com/rubygems/rubygems/blob/master/bundler/doc/TROUBLESHOOTING.md)
- [Bundler documentation site](https://bundler.io/)
- [Bundler man pages](https://bundler.io/man/bundle.1.html)
- [Bundler command line reference](https://bundler.io/v2.0/commands.html)

If you haven't done that, please do it before creating a new issue.

Please answer the following questions so we can process your issue as fast as possible:

1. Do you have a reproduction script? It would be really helpful for us if you provide one. Examples: [Sample repro script for Bundler issues](https://gist.github.com/xaviershay/6207550), [Another sample repro script for Bundler issues](https://gist.github.com/xaviershay/6295889).

    Script URL: 

2. What are you trying to accomplish?

    Your answer:

3. What command did you run?

    Your answer:

4. What were you expecting to happen?

    Your answer:

5. What actually happened?

    Your answer:

6. Is there an exception backtrace? If so, please copy it below.

    Your answer:

7. Please run `bundle env` and paste the output below:

    Your answer:

For more information please check [Filing Issues: a guide](https://github.com/rubygems/rubygems/blob/master/bundler/doc/contributing/ISSUES.md).

Thank you!

**Comment by deivid-rodriguez** [comment]
Hi!

The linked guide starts with a step called "Install discourse dependencies", which includes installing the latest ruby stable release (2.7.1). However, you're using ruby 2.3.0.

As the error message states, one of the dependencies needs at least ruby 2.4.4. So you need to install at least that ruby, or better, the latest stable.

Make sure you rerun the steps in the guide from scratch and that you have a newer ruby before retrying `bundle install`.

Good luck!
