### ISSUE TITLE
When using jruby-head, bundle inline fails when Gemfile.lock exists at the same directory

### ISSUE THREAD

**Issue by yahonda** [rubygems/rubygems#3796]
### Describe the problem as clearly as you can

When `Gemfile.lock` exists at the same directory, bundle inline fails with jruby-head.

### Post system independent steps to reproduce the problem

Because I do not know how to install JRuby head in my environment, It reproduces using GitHub Actions and Travis CI.

* Repository
https://github.com/yahonda/rake_on_jruby_head/

* GitHub Actions
https://github.com/yahonda/rake_on_jruby_head/actions/runs/160529252

* Travis CI
https://travis-ci.org/github/yahonda/rake_on_jruby_head/builds/705736332

### Which command did you run?

Both GitHub Actions and Travis CI runs 

* Gemfile
```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gem 'rails', github: 'rails/rails'
```
* test.rb
```ruby
source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }
gem 'rails', github: 'rails/rails'
```

```ruby
$ bundle install
$ ruby test.rb
```

### What were you expecting to happen?

bundle inline should pass as other Ruby versions do.

### What actually happened?

```ruby
In Gemfile:
  rails was resolved to 6.1.0.alpha, which depends on
    railties was resolved to 6.1.0.alpha, which depends on
      rake

         handle_error at /home/runner/.rubies/jruby-head/lib/ruby/stdlib/bundler/installer/parallel_installer.rb:201
                 call at /home/runner/.rubies/jruby-head/lib/ruby/stdlib/bundler/installer/parallel_installer.rb:106
                 call at /home/runner/.rubies/jruby-head/lib/ruby/stdlib/bundler/installer/parallel_installer.rb:78
  install_in_parallel at /home/runner/.rubies/jruby-head/lib/ruby/stdlib/bundler/installer.rb:289
              install at /home/runner/.rubies/jruby-head/lib/ruby/stdlib/bundler/installer.rb:197
                  run at /home/runner/.rubies/jruby-head/lib/ruby/stdlib/bundler/installer.rb:92
                 lock at /home/runner/.rubies/jruby-head/lib/ruby/stdlib/bundler/process_lock.rb:12
                 open at org/jruby/RubyIO.java:1158
                 lock at /home/runner/.rubies/jruby-head/lib/ruby/stdlib/bundler/process_lock.rb:9
                  run at /home/runner/.rubies/jruby-head/lib/ruby/stdlib/bundler/installer.rb:73
              install at /home/runner/.rubies/jruby-head/lib/ruby/stdlib/bundler/installer.rb:25
              gemfile at /home/runner/.rubies/jruby-head/lib/ruby/stdlib/bundler/inline.rb:62
            temporary at /home/runner/.rubies/jruby-head/lib/ruby/stdlib/bundler/settings.rb:143
              gemfile at /home/runner/.rubies/jruby-head/lib/ruby/stdlib/bundler/inline.rb:61
               <main> at test.rb:3
```

## Environment

```
Bundler       2.1.4
  Platforms   ruby, universal-java-1.8
Ruby          2.6.5p0 (2020-07-01 revision 67812) [java]
  Full Path   /home/runner/.rubies/jruby-head/bin/jruby
  Config Dir  /home/runner/.rubies/jruby-head/etc
RubyGems      3.0.6
  Gem Home    /home/runner/.rubies/jruby-head/lib/ruby/gems/shared
  Gem Path    /home/runner/.gem/jruby/2.6.0:/home/runner/.rubies/jruby-head/lib/ruby/gems/shared
  User Home   /home/runner
  User Path   /home/runner/.gem/jruby/2.6.0
  Bin Dir     /home/runner/.rubies/jruby-head/bin
Tools         
  Git         2.27.0
  RVM         not installed
  rbenv       not installed
  chruby      not installed
Gem.ruby      /home/runner/.rubies/jruby-head/bin/jruby
bundle #!     /usr/bin/env jruby

**Comment by yahonda** [comment]
A simple workaround is `rm Gemfile.lock` before running `ruby test.rb`.

**Comment by deivid-rodriguez** [comment]
Could you try using `bundler-2.2.0.rc.1` and also upgrading rubygems? Just to make sure if this is a bug in the latest and greatest versions or is something that we have fixed already.

**Comment by yahonda** [comment]
Bump bundler and RubyGems version as suggested, this issue does not reproduce anymore.
```
$ bundler -v
Bundler version 2.2.0.rc.1
```

```
$ gem -v
3.1.4
```

**Comment by deivid-rodriguez** [comment]
Could you upgrade _only_ bundler to double check? I believe the fix for this should've happened in `bundler` and it should still work on older rubygems.

**Comment by yahonda** [comment]
Upgrading bundler only and leave RubyGems version as it is, it reproduces the error.

```
$ bundler -v
Bundler version 2.2.0.rc.1
```

```
$ gem -v
3.0.6
```

https://github.com/yahonda/rake_on_jruby_head/runs/845386088?check_suite_focus=true

**Comment by deivid-rodriguez** [comment]
Interesting. I guess we could properly bisect this, but since this is a head version, and it seems to work fine with the latest release I think it's not worth the effort.

**Comment by yahonda** [comment]
Somehow, this issue reproduces with RubyGems 3.0.6, 3.0.7. Fixed with RubyGems 3.0.8.

**Comment by yahonda** [comment]
I have confirmed that this issue has been resolved with the latest versions of Bundler and RubyGems. Closing this issue. Thank you for the support!

**Comment by deivid-rodriguez** [comment]
Great! Thanks to your for reporting this issue!
