### ISSUE TITLE
Bundler: allow to suppress post-install messages for bundle install

### ISSUE THREAD

**Issue by jhass** [rubygems/rubygems#3801]
Bundler is used not just as developer tool, it's also used as a setup tool by users, for example by installing a self hosted ruby project on their servers.

A lot of gems put all kinds of warnings, upgrade instructions and so on into their post install messages. These don't concern those users but only the developers of those projects. Worse, sometimes users get confused by them and rerun already done migration steps, or otherwise destructive commands.

It would be good if installation instructions for such projects could just give a `bundle install` command that suppresses these messages, greatly reducing confusion among end users.

**Comment by indirect** [comment]
https://bundler.io/v1.10/whats_new.html#ignore-messages

**Comment by jhass** [comment]
Ah, thank you. I always forget the `bundle config` options. A CLI option to include into commands users copy paste, would still be nice for this IMO though.
