### ISSUE TITLE
undefined method `rubyforge_project=' for class `Gem::Specification' (NameError)

### ISSUE THREAD

**Issue by utkarsh2102** [rubygems/rubygems#3831]
Whilst trying to install rubygems manually, I tried running `ruby setup.rb`, as suggested in the README.md file.
Upon doing so, I got:

```
➜  rubygems git:(master) ruby setup.rb
Traceback (most recent call last):
	5: from setup.rb:23:in `<main>'
	4: from setup.rb:23:in `require'
	3: from /home/utkarsh/debian/ruby-team/rubygems/rubygems/lib/rubygems.rb:1347:in `<top (required)>'
	2: from /home/utkarsh/debian/ruby-team/rubygems/rubygems/lib/rubygems.rb:1347:in `require'
	1: from /usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:90:in `<top (required)>'
/usr/lib/ruby/vendor_ruby/rubygems/defaults/operating_system.rb:91:in `<class:Specification>': undefined method `rubyforge_project=' for class `Gem::Specification' (NameError)
```

I believe this has been deprecated and shouldn't really be used :thinking: 
Am I missing something or is it really a bug!?

**Comment by simi** [comment]
@utkarsh2102 you do mix system and custom ruby installations. It is not supported. Please install ruby manually (not by system package, for example by ruby-install or rbenv) and update rubygems manually or keep your ruby updated by system (not manually).

@deivid-rodriguez `operating_system.rb` seems really dangerous place actually. what about to rescue all errors during requiring and next to the stack-trace report user friendly message explaining that there are some problems at rubygems distributor side.

**Comment by utkarsh2102** [comment]
Hi @simi,

> you do mix system and custom ruby installations. It is not supported. Please install ruby manually (not by system package, for example by ruby-install or rbenv) and update rubygems manually or keep your ruby updated by system (not manually).

Gah, I see. Thanks for the tip :+1: 
(we're working on packaging rubygems, btw)

**Comment by simi** [comment]
@utkarsh2102 yeah, I know. This exact problem should be already fixed at https://salsa.debian.org/ruby-team/rubygems-integration/-/commit/39d3a082f568ec0b6c9acd10e54a4a31a08bd8b5.

**Comment by utkarsh2102** [comment]
Aha, I see. Thanks \o/

**Comment by hsbt** [comment]
Duplicate with https://github.com/rubygems/rubygems/issues/3068

**Comment by deivid-rodriguez** [comment]
> @deivid-rodriguez operating_system.rb seems really dangerous place actually. What about to rescue all errors during requiring and next to the stack-trace report user friendly message explaining that there are some problems at rubygems distributor side.

@simi This is a very good idea in my opinion :+1:.
