### ISSUE TITLE
`bundle install` fails when optional group contains version conflict.

### ISSUE THREAD

**Issue by ioquatix** [rubygems/rubygems#3837]
I have a slightly tricky setup, testing multiple gem sets with falcon, to ensure it works with Rack v1, v2 (default) and v3 (master).

I have gemfiles here which are used for separate test runs:

https://github.com/socketry/falcon/tree/d9d517401fb5f0917d46aaffe74acb123537da47/gems

Those gemfiles include the main `gems.rb` file:

https://github.com/socketry/falcon/blob/d9d517401fb5f0917d46aaffe74acb123537da47/gems.rb

This gemfile has an optional group which is not installed as part of the tests, but it still reports version conflicts.

```
Fetching gem metadata from https://rubygems.org/.......
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Bundler could not find compatible versions for gem "rack":
  In rack1.gemfile:
    rack (~> 1.0)

    utopia-project was resolved to 0.12.1, which depends on
      utopia (~> 2.14) was resolved to 2.18.0, which depends on
        rack (~> 2.2)
```

Gems which are in an optional group, such that the optional group is not included during bundle install, should *not* take part in the dependency resolution process (i.e. they should be ignored).

**Comment by indirect** [comment]
Sorry, that's not how optional groups work (although it's very understandable to expect otherwise).

Optional means they might not be installed, but Bundler only supports one single dependency resolution per Gemfile. That means that every gem has to resolve successfully, whether it will be installed at this exact moment or not.

You might be able to get what you're after by having separate Gemfiles and using the BUNDLE_GEMFILE env var to switch between them.

**Comment by colby-swandale** [comment]
👋 What you're describing goes against the core of what Bundler provides to users. Every dependency, even those in optional groups, go through the Dependency Resolution process and gets computed into a compatible set of dependencies & version requirements that Bundler can guarantee meets all gem's requirements. If a specific set of gems or gem's requirements are incompatible, Bundler will report the error to the the user and won't update the Gemfile.lock. The user can then fix the dependency error, and if Bundler successfully resolves, will update the Gemfile.lock. With the given Gemfile.lock, Bundler then guarantees that the user can use run `bundle install` with the given Gemfile and successfully install, start their application etc with the resolved set of gems.

Not including optional groups in the resolution process could easily introduce an incompatible dependency tree a have a Gemfile/Gemfile.lock not be compatible, causing confusion for users and Bundler being unable to provide those same guarantees anymore.

**Comment by ioquatix** [comment]
Okay, so a solution would be to write something like:

```
# in gemfile
if ENV['WITH_WHATEVER']
  gem "whatever"
end
```

???
