### ISSUE TITLE
Sync ruby/ruby? - master fixes failure there

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#3851]
ruby/ruby is currently (and consistently) failing with MinGW builds.  Same thing is happening with all ruby-loco builds.  Testing using RG master solved the problem.  See:

Issue https://github.com/rubygems/rubygems/issues/3140
Commit https://github.com/rubygems/rubygems/commit/a516b49a0a

Any binary file should always be opened as such, as on Windows, depending on the phase of the moon, etc, line ending may be converted if a file is read 'non-binary'.

Hence, a sync (or the above commit) in ruby master will fix the issue.

@deivid-rodriguez

Re Windows, feel free to ping me.  I watch RG, but, depending on what I'm currently working on, I may not get past the subject line.  And, thanks for the fix.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by hsbt** [comment]
See https://github.com/ruby/ruby/pull/3379

**Comment by MSP-Greg** [comment]
Thank you.
