### ISSUE TITLE
Account Lost crédentiel

### ISSUE THREAD

**Issue by grogyroger** [rubygems/rubygems#3859]
Hello,

I'm having a problem with a rubygem account access.

My current problem is can't log has owner on project https://rubygems.org/gems/lrc_handler

This project was created by a former employee of the company, pierre deprey wich mail was p.deprey@linkbynet.com, i have access to his mail accont so i try the process forget your password with this mail adresse and with team-chef@linkbynet.com too, but i never receive mail de reset password.

We have to push a  new version of this gem, is it possible someone help me ?

Regard's
Grégory Roger

**Comment by hsbt** [comment]
@grogyroger Can you file it to https://help.rubygems.org/ ? This repository is the issue-tracker for CLI.
