### ISSUE TITLE
dry-run options

### ISSUE THREAD

**Issue by nobu** [rubygems/rubygems#3866]
I'm surprised a little by the followings.

```sh
$ gem check --dryrun
ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --dryrun
Did you mean?  dry-run

$ gem cleanup --dry-run
ERROR:  While executing gem ... (OptionParser::InvalidOption)
    invalid option: --dry-run
Did you mean?  dryrun
```

Why are these different?

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.2.0.pre1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by duckinator** [comment]
I think it would be best to change `gem check` to use `--dry-run`, since in both RubyGems and Bundler that's the only time that option shows up without the hyphen. The current `--dryrun` can be added as an alias for `--dry-run`, to preserve backwards compatibility.

**Comment by austinpray** [comment]
+1 for `--dry-run`. I would not expect `--dryrun`. `git clean --dry-run ...` for instance.
