### ISSUE TITLE
Feature: Install namespaced different versions of the same gem

### ISSUE THREAD

**Issue by ryanwjackson** [rubygems/rubygems#3878]
# Preface

This may not be a RubyGems issue and more a Bundler issue. Perhaps I missed it, but I did not find this in existing issues. I started to dig into the code, but I figured it may be faster to have someone more knowledgable shoot me down or point me in the right direction for making the change.

# Problem

Let's assume I have a project (rails, another gem, anything using bundler) that requires the following gems:

- `Gem1`
- `Gem2`

Now, let's assume that both `Gem1` and `Gem2` require `Gem3`.  `Gem1` requires `Gem3` with version `<1.0.0` while `Gem2` requires `Gem3` with version `>2.0.0`.

The problem is I have a conflict and cannot use `Gem1` and `Gem2` together.

# Solution

While I know this is somewhat of a bandaid request, often this prevents you from using some gems (usually based on importance, not age, aka you aren't just ignoring the old one).  Would it be possible to have an argument that can force a gem installed to scope its gem requirements?

So when `Gem1` calls `Gem3::*` it uses the version it needs and the same for `Gem2` using `Gem3::*`.

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by colby-swandale** [comment]
Bundler/Ruby cannot namespace gems by their version, any code that's loaded from a `require` is defined in the same global namespace as your application. If you were to `require` multiple versions of the same gem, they would essentially be overwriting each other's classes, modules, methods, etc - and causing all sorts of bugs to happen.

**Comment by ryanwjackson** [comment]
@colby-swandale Makes sense.  Obviously best practice is to just update the gems to use newer versions, but sometimes forking them and "updating" them is just patching them in an unscalable way.

I was just trying to think if there was some clever way around this without necessitating changes to any of the gems in this example, only how you include/use them.  I'm not a deep ruby-ist, but I assume there's no way to change the namespace of require or a different way to require?  So if you were to have `gem 'Gem1', require: false` and then where you needed it, you "required" it there without conflict.

**Comment by colby-swandale** [comment]
There is no cleaver way to work around this issue. Bundler will only allow you install/load a single version of a gem for a given Gemfile.lock. You will need to try and find a version of Gem1 and Gem2 that meets their dependency requirements.
