### ISSUE TITLE
Bundler 1.17.3 installs with ENV Vars are different than with flags

### ISSUE THREAD

**Issue by schneems** [rubygems/rubygems#3890]
Due to the deprecations in Bundler 2, i'm working to remove the invocation arguments to bundler:

```
Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
[DEPRECATED] The `--deployment` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set deployment 'true'`, and stop using this flag
[DEPRECATED] The `--path` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set path 'vendor/bundle'`, and stop using this flag
[DEPRECATED] The `--without` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set without 'development:test'`, and stop using this flag
[DEPRECATED] The --binstubs option will be removed in favor of `bundle binstubs`
```

This work is tracked in https://github.com/heroku/heroku-buildpack-ruby/issues/943

To avoid extra calls to `bundle config` it was decided to instead use environment variables. This work is tracked in https://github.com/heroku/heroku-buildpack-ruby/pull/1039

The final command ends up being:

```
$ BUNDLE_WITHOUT=development:test BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 bundle install -j4
```

The problem is that gems installed with with the two methods appear to be installed in different directories. This causes slug/install size to balloon and caused ticket/incident https://github.com/heroku/heroku-buildpack-ruby/issues/1046 when I merged that patch in.

We have to support Bundler 1.x due to the version/error behavior introduced in Bundler 2 that raises an exception based off of the `BUNDLED WITH` version in the Gemfile.lock

### Post system independent steps to reproduce the problem

Open a docker shell:

```
docker run -it --rm ruby:2.5 bash
```

Create a Gemfile, install bundler

```
gem install bundler -v 1.17.3

cat << EOM > Gemfile
source 'https://rubygems.org'

gem 'explain_shell'
EOM

cat << EOM > Gemfile.lock
GEM
  remote: https://rubygems.org/
  specs:
    explain_shell (1.0.2)

PLATFORMS
  ruby

DEPENDENCIES
  explain_shell

EOM
```

Install with flags:

```
bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment
bundle show explain_shell
# => /vendor/bundle/ruby/2.5.0/gems/explain_shell-1.0.2
```

Install with env vars:

```
rm /usr/local/bundle/config
export BUNDLE_WITHOUT=development:test BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 
bundle install -j4
bundle show explain_shell
# => /vendor/bundle/gems/explain_shell-1.0.2
```

> Notice that the two paths are different. I could not get this same example to fail with bundler 2.1.4, only with Bundler 1.17.3

### Which command did you run?

```
rm /usr/local/bundle/config
export BUNDLE_WITHOUT=development:test BUNDLE_PATH=vendor/bundle BUNDLE_BIN=vendor/bundle/bin BUNDLE_DEPLOYMENT=1 
bundle install -j4
bundle show explain_shell
```

### What were you expecting to happen?

```
# => /vendor/bundle/ruby/2.5.0/gems/explain_shell-1.0.2
```

### What actually happened?

```
# => /vendor/bundle/gems/explain_shell-1.0.2
```

### If not included with the output of your command, run `bundle env` and paste the output below

<details>
<summary>bundle env</summary>
## Environment

```
Bundler       1.17.3
  Platforms   ruby, x86_64-linux
Ruby          2.5.8p224 (2020-03-31 revision 67882) [x86_64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.0.3
  Gem Home    /usr/local/bundle
  Gem Path    /root/.gem/ruby/2.5.0
  User Path   /root/.gem/ruby/2.5.0
  Bin Dir     /usr/local/bundle/bin
Tools
  Git         2.20.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2019-03-04
Git SHA           d7089abb6
Released Version  false
```

## Bundler settings

```
frozen
  Set for your local app (/usr/local/bundle/config): true
jobs
  Set for your local app (/usr/local/bundle/config): 4
without
  Set for your local app (/usr/local/bundle/config): [:development, :test]
  Set via BUNDLE_WITHOUT: [:development, :test]
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
deployment
  Set via BUNDLE_DEPLOYMENT: true
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
bin
  Set via BUNDLE_BIN: "vendor/bundle/bin"
path
  Set via BUNDLE_PATH: "vendor/bundle"
```

### Gemfile

```ruby
source 'https://rubygems.org'

gem 'explain_shell'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    explain_shell (1.0.2)

PLATFORMS
  ruby

DEPENDENCIES
  explain_shell
```
</details>

**Comment by schneems** [comment]
It's worth noting that I can reproduce this with bundler 2.0.2. So it looks like it must have been fixed in t he 2.x branch, but not backported.

**Comment by deivid-rodriguez** [comment]
As discussed in slack, this is fixed in bundler 2.1.4.

Also, as @colby-swandale said, you can opt-in to the fix using the `BUNDLE_GLOBAL_PATH_APPENDS_RUBY_SCOPE` environment variable.

Is that enough to close this ticket?

**Comment by schneems** [comment]
Related:

- https://github.com/rubygems/bundler/issues/3552
- https://github.com/rubygems/bundler/pull/6628

> Is that enough to close this ticket?

It looks like I can conditionally add this env var to systems using bundler 1.17.3. I believe that meets my needs. Thanks for the response!

**Comment by deivid-rodriguez** [comment]
No problem, thanks for reporting this!
