### ISSUE TITLE
gem outdated - FileUtils missing

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#3894]
Using Ruby master (`ruby 2.8.0dev (2020-08-22T05:12:12Z master 2ddc67ffb6) [x64-mingw32]`), and also using it with RG master copied into it, when running `gem outdated` shows the following:
```
ERROR:  While executing gem ... (NameError)
    uninitialized constant Gem::Source::FileUtils
```

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
3.2.0.rc.1
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Thanks for the report. https://github.com/rubygems/rubygems/pull/3911 should fix this.

**Comment by MSP-Greg** [comment]
@deivid-rodriguez 

Thanks for the quick fix.
