### ISSUE TITLE
On Windows, 'gem generate_index' doesn't populate '<repo>/quick' directory on non-system partitions

### ISSUE THREAD

**Issue by elrubio** [rubygems/rubygems#392]
# Observation
When running **'gem generate_index'** on Windows **on a different partition other than the system partition C:**, it fails to populate the **\<gem-repo\>\quick** directory. It stays empty, but shows no warning or errors:

**Initial state: One gem, no index yet:**
```
d:\gem-repo>dir /s /b
d:\gem-repo\gems
d:\gem-repo\gems\mygem-0.1.1.gem
```

**Creating index:**
```
d:\gem-repo>gem generate_index -d .
Generating Marshal quick index gemspecs for 1 gems
.
Complete
Generated Marshal quick index gemspecs: 0.000s
Generating Marshal master index
Generated Marshal master index: 0.000s
Generating specs index
Generated specs index: 0.000s
Generating latest specs index
Generated latest specs index: 0.000s
Generating prerelease specs index
Generated prerelease specs index: 0.000s
Compressing indicies
Compressed indicies: 0.000s
```

**After index creation: quick dir is empty:**
```
d:\gem-repo>dir quick
11/08/2012  06:07 PM    <DIR>          .
11/08/2012  06:07 PM    <DIR>          ..
               0 File(s)              0 bytes
               2 Dir(s)  162,105,065,472 bytes free
```

# Reason
When using the verbose switch, among dozens of exceptions I see a permission error when trying to move the Marshal directory from its temporary (on partition C) to its final location (on partition D):
```
[...]
mv -f C:/Users/ADMINI~1/AppData/Local/Temp/2/gem_generate_index_5444/quick/Marshal.4.8 D:/gem-repo/quick/Marshal.4.8
Exception `Errno::ENOENT' at c:/Ruby/current/lib/ruby/1.9.1/fileutils.rb:1210 - No such file or directory - D:/gem-repo/quick/Marshal.4.8
Exception `Errno::EACCES' at c:/Ruby/current/lib/ruby/1.9.1/fileutils.rb:515 - Permission denied - (C:/Users/ADMINI~1/AppData/Local/Temp/2/gem_generate_index_5444/quick/Marshal.4.8, D:/gem-repo/quick/Marshal.4.8) 
[...]
```
But it's not a permission thing. The underlying issue seems to be that **FileUtils.move** is unable to move a directory from one partition to another (at least on my machines). Contrary to the [documentation](http://www.ruby-doc.org/stdlib-1.9.3/libdoc/fileutils/rdoc/FileUtils.html#method-i-mv), it does not seem to fall back to *copy* in this case:

**Move on same partition**
```
irb(main):001:0> require 'fileutils'
=> true
irb(main):002:0> FileUtils.mv('c:/source-dir', 'c:/target-dir/source-dir')
=> 0
```
**Move to another partition** (fails with misleading error type: this is *not* a permission issue)
```
irb(main):001:0> require 'fileutils'
=> true
irb(main):002:0> FileUtils.mv('c:/source-dir', 'd:/target-dir/source-dir')
Errno::EACCES: Permission denied - (c:/source-dir, d:/target-dir/source-dir)
        from c:/Ruby/current/lib/ruby/1.9.1/fileutils.rb:519:in `rename'
        from c:/Ruby/current/lib/ruby/1.9.1/fileutils.rb:519:in `block in mv'
        from c:/Ruby/current/lib/ruby/1.9.1/fileutils.rb:1515:in `block in fu_each_src_dest'
        from c:/Ruby/current/lib/ruby/1.9.1/fileutils.rb:1531:in `fu_each_src_dest0'
        from c:/Ruby/current/lib/ruby/1.9.1/fileutils.rb:1513:in `fu_each_src_dest'
        from c:/Ruby/current/lib/ruby/1.9.1/fileutils.rb:508:in `mv'
        from (irb):7
        from c:/Ruby/current/bin/irb:12:in `<main>'
```

# Fix
Fix that works for me: copy the directory instead of moving it. The temp directory will be deleted anyways after completion:

```diff
diff --git a/indexer.rb b/indexer.rb
index e87e5a3..7b1980d 100644
--- a/indexer.rb
+++ b/indexer.rb
@@ -487,8 +487,8 @@ class Gem::Indexer
 
       FileUtils.rm_rf dst_name, :verbose => verbose
-      FileUtils.mv(@quick_marshal_dir, dst_name,
-                   :verbose => verbose, :force => true)
+      FileUtils.cp_r(@quick_marshal_dir, dst_name,
+                   :verbose => verbose)
     end
```

Diff applies to https://github.com/rubygems/rubygems/blob/1.8/lib/rubygems/indexer.rb#L490

# System
+  OS: Windows 7 x64, Windows Server 2008 x64
+ Ruby: ruby 1.9.2p136 (2010-12-25 revision 30365) [i386-mswin32], ruby 1.9.3p194 (2012-04-20) [i386-mingw32]
+ Rubygems: 1.8.24

**Comment by djberg96** [comment]
Looks like FileUtils was fixed in https://bugs.ruby-lang.org/issues/8109. Closing.
