### ISSUE TITLE
When a gem is yanked, bundler does not always show the correct error message

### ISSUE THREAD

**Issue by halfbyte** [rubygems/rubygems#3935]
### Describe the problem as clearly as you can

If the lockfile during a bundler run is in "unlocked" state, bundler resolves all gems from scratch. This leads to an interesting edge case where a yanked gem can have dependencies that can not be resolved from the index, as all non-yanked versions of the gem do not contain said dependencies.

The compact index implementation looks up all dependencies from all available versions and puts them into the index, so if older, yanked versions contain additional dependencies, these are absent from the index used to do the resolution.

In this specific case, all old versions of `codecov` that depended on `url` have been yanked.

This does lead to confusing error messages as the wrong gem is reported as yanked. In our case (Depfu) this leads to us being unable to provide a resolution for our clients, as we cannot detect the actual gem that's been yanked and thus try to update the wrong gem. This may be a very specific usecase but this does also affect bundler end users as the resolution to this error message is obvious.

I realise that this bug is hard to fix, as it would probably mean to also put yanked gem specs in the index and then somehow make sure these yanked versions are only used for dependency resolution and not for actual installation. Nevertheless, this is a real bug that happened to a handful of our customers and so I think it is worth to report it.

### Post system independent steps to reproduce the problem

I've created a minimal repro at [halfbyte/yank_bundler_bug_repro](https://github.com/halfbyte/yank_bundler_bug_repro), the README contains instructions.

### Which command did you run?

`bundle update json`

### What were you expecting to happen?

Bundler reports that `codecov` in the specified version is not available anymore.

`Your bundle is locked to codecov (0.1.9), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of codecov (0.1.9) has removed it. You'll need to update your bundle to a version other than codecov (0.1.9) that hasn't been removed in order to install.`

### What actually happened?

bundler reports that url in the specified version is not available anymore (which is wrong)

`Your bundle is locked to url (0.3.2), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of url (0.3.2) has removed it. You'll need to update your bundle to a version other than url (0.3.2) that hasn't been removed in order to install.`

### If not included with the output of your command, run `bundle env` and paste the output below

```
Bundler       2.1.4
  Platforms   ruby, x86_64-linux
Ruby          2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
  Full Path   /home/jan/.asdf/installs/ruby/2.6.6/bin/ruby
  Config Dir  /home/jan/.asdf/installs/ruby/2.6.6/etc
RubyGems      3.0.3
  Gem Home    /home/jan/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0
  Gem Path    /home/jan/.gem/ruby/2.6.0:/home/jan/.asdf/installs/ruby/2.6.6/lib/ruby/gems/2.6.0
  User Home   /home/jan
  User Path   /home/jan/.gem/ruby/2.6.0
  Bin Dir     /home/jan/.asdf/installs/ruby/2.6.6/bin
Tools
  Git         2.25.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2020-01-05
Git SHA           32a4159325
Released Version  true
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem 'codecov'
gem 'json'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    codecov (0.1.9)
      json
      simplecov
      url
    docile (1.3.2)
    json (2.3.1)
    simplecov (0.19.0)
      docile (~> 1.1)
      simplecov-html (~> 0.11)
    simplecov-html (0.12.2)
    url (0.3.2)

PLATFORMS
  ruby

DEPENDENCIES
  codecov
  json

BUNDLED WITH
   2.1.4
```

**Comment by deivid-rodriguez** [comment]
Thanks @halfbyte! Looks definitely like a bug, and definitely hard to fix. But I will try to find some time to at least have a look at it and see what we can do.

**Comment by deivid-rodriguez** [comment]
I checked this and, while it indeed reproduced with Bundler 2.1.4, it seems fixed in later versions. So closing!
