### ISSUE TITLE
selenium install (404 Not Found)

### ISSUE THREAD

**Issue by ksiv** [rubygems/rubygems#3943]
I'm trying to run selenium-webdriver 4.0.0.alpha6 so upgrading everything and I m stuck on selenium. 
I think it's jar -wrapper. Not even sure if I need it in my task but I think issue is always nice to report

This issue is related to:

  - [ ] Installing a library
**1. Step** 
C:\path2\selenium>gem install selenium
Fetching selenium-0.2.11.gem
Fetching zip-2.0.2.gem
Fetching jar_wrapper-0.1.8.gem
Successfully installed zip-2.0.2
Successfully installed jar_wrapper-0.1.8

      -------------------------------------------------------------------------------

      Please now run:

        $ selenium install

      NB. This will download jars that this gem needs to run from the internet.
      It will put them into ~/.selenium/assets.

      -------------------------------------------------------------------------------
Successfully installed selenium-0.2.11
Parsing documentation for zip-2.0.2
Installing ri documentation for zip-2.0.2
Parsing documentation for jar_wrapper-0.1.8
Installing ri documentation for jar_wrapper-0.1.8
Parsing documentation for selenium-0.2.11
Installing ri documentation for selenium-0.2.11
Done installing documentation for zip, jar_wrapper, selenium after 0 seconds
3 gems installed

**2. Step**
as requested I do 
selenium install
 downloading http://selenium.googlecode.com/files/selenium-server-2.37.0.zip... Traceback (most recent call last):
        15: from C:/Ruby26-x64/bin/selenium:23:in `<main>'
        14: from C:/Ruby26-x64/bin/selenium:23:in `load'
        13: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-0.2.11/bin/selenium:7:in `<top (required)>'
        12: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/selenium-0.2.11/lib/selenium/starter.rb:33:in `run'
        11: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jar_wrapper-0.1.8/lib/jar_wrapper/runner.rb:17:in `install'
        10: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jar_wrapper-0.1.8/lib/jar_wrapper/runner.rb:124:in `download_file_to'
         9: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jar_wrapper-0.1.8/lib/jar_wrapper/runner.rb:124:in `open'
         8: from C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/jar_wrapper-0.1.8/lib/jar_wrapper/runner.rb:125:in `block in download_file_to'
         7: from C:/Ruby26-x64/lib/ruby/2.6.0/open-uri.rb:35:in `open'
         6: from C:/Ruby26-x64/lib/ruby/2.6.0/open-uri.rb:736:in `open'
         5: from C:/Ruby26-x64/lib/ruby/2.6.0/open-uri.rb:165:in `open_uri'
         4: from C:/Ruby26-x64/lib/ruby/2.6.0/open-uri.rb:224:in `open_loop'
         3: from C:/Ruby26-x64/lib/ruby/2.6.0/open-uri.rb:224:in `catch'
         2: from C:/Ruby26-x64/lib/ruby/2.6.0/open-uri.rb:226:in `block in open_loop'
         1: from C:/Ruby26-x64/lib/ruby/2.6.0/open-uri.rb:756:in `buffer_open'
C:/Ruby26-x64/lib/ruby/2.6.0/open-uri.rb:378:in `open_http': 404 Not Found (OpenURI::HTTPError)

Here are my current environment details:

```
$ gem env version
3.0.3
```
 I have no proxy , used direct connection and VPN one - same result

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by MSP-Greg** [comment]
@ksiv

`selenium install` is downloading http://selenium.googlecode.com/files/selenium-server-2.37.0.zip, which doesn't exist.

Hence, this isn't a RubyGems issue, but I'm sure not where the issue is. Maybe start with the gem repo?

**Comment by ksiv** [comment]
Sorry not a big ruby-coder myself, I ll close it. 
Cause: Wrong GitHub project

**Comment by ksiv** [comment]
Was mislead by 
#
# This file was generated by RubyGems.
#
# The application 'selenium' is installed as part of a gem, and
# this file is here to facilitate running it.
#
Issue link: [https://github.com/shvets/selenium/issues/2](url)
