### ISSUE TITLE
Output message to console when building extension gems

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#3944]
Some extension gems have build dependencies that are not required.  I would like to output a message if a dependency is not installed.  I tried STDOUT & STDERR...

Is there any way to do this?

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:

```
NA
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by simi** [comment]
@MSP-Greg can you share steps to get to this state? It will be easier (at least for me) to understand the problem and take a look for possible solutions.

**Comment by MSP-Greg** [comment]
@simi

Sorry.  Several extension gems that operate on sockets compile with OpenSSL.  A gem I'm working with compiles with OpenSSL, but will also compile fine if 'openssl dev' isn't installed.  If a user doesn't have 'openssl dev' installed, we'd like to output a message to the console.  At present, all output is collected and placed in `gem_make.out`.

So, when installing an extension gem, how do I output to the console from `extconf.rb`?

**Comment by MSP-Greg** [comment]
I looked at the code, and (as I assumed), building is done within an Open3 call, so console output is difficult.

Closing.

**Comment by simi** [comment]
Ahh, I do understand now, thanks for info. I did the same and indeed open3 is used. I got an idea to somehow modify gemspec post install message or use `Gem.post_install` hook.

**Comment by deivid-rodriguez** [comment]
In general, I think the current behavior is fine (only display "compilation output" in case of errors). Given gems are installed in parallel, allowing compilation output to be printed might get quite confusing?

**Comment by MSP-Greg** [comment]
> Given gems are installed in parallel, allowing compilation output \.\.\. quite confusing

Good point.  Kind of like parallel test output...
