### ISSUE TITLE
Running specs doesn't work on systems without `ps -p`

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#3949]
### Describe the problem as clearly as you can

If a system has a `ps` program that's not POSIX compliant and doesn't implement the `-p` flag, specs fail. This is the case on @duckinator's busybox.

### Which command did you run?

Specs.

### What were you expecting to happen?

They pass.

### What actually happened?

The ones using `ps` fail.

I think if we could detect this situation and skip the specs in this case? Maybe run `ps -p` and check the exit code?

**Comment by duckinator** [comment]
Skipping if `ps -p #{Process.pid}` returns a non-zero exit code should be sufficient.

**Comment by deivid-rodriguez** [comment]
In retrospective, I don't think this needs a tracking ticket. If you're a Bundler developer and run into this, go ahead and fix it directly!

**Comment by duckinator** [comment]
I believe I encountered this back when I was using a Docker container for running tests locally, and I solved it by not using busybox.

And now I just run the test suite directly on FreeBSD or Windows. So I've not encountered this problem in ages.

So unless someone else encounters it, it's a nonissue.
