### ISSUE TITLE
The `gem build -C` does not work as expected

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#3953]
This is followup of #2587 and I am not really sure what is the purpose of this code:

https://github.com/rubygems/rubygems/blob/8fd5dee8fcfdda7db74c579616fb5a718c287e6d/lib/rubygems/commands/build_command.rb#L87-L89

If I specify the `-C` option, why the `Dir.chdir` does not use the specified path? I think the current code is clumsy. It tries to do guess everything, but nothing is done properly. For example, I don't understand why it tries to used `gem_name` and then tries also the `"#{gem_name}.gemspec"` when this behavior is not documented. Is the .gemspec file expected to be located in the current directory or is the path expected?

This is specifically behavior I complain about:

~~~
$ ls | grep gemspec
abrt.gemspec

$ mkdir ci

$ cd ci

$ gem build *.gemspec -C ..
ERROR:  Gemspec file not found: *.gemspec.gemspec

$ # Hmmm, what is this ^^ error. The *.gemspec.gemspec is confusing. I have not asked for anything like this.

$ cp ../abrt.gemspec .

$ gem build abrt.gemspec -C ..
abrt.gemspec
WARNING:  See https://guides.rubygems.org/specification-reference/ for help
ERROR:  While executing gem ... (Gem::InvalidSpecificationException)
    ["LICENSE.txt", "README.md", "Rakefile"] are not files

$ # But why this ^^ does not work?

$ gem build ../*.gemspec -C ..
  Successfully built RubyGem
  Name: abrt
  Version: 0.4.0
  File: abrt-0.4.0.gem

$ ll
total 4
-rw-rw-r--. 1 vondruch vondruch 817 Sep 17 14:36 abrt.gemspec

$ # But where is my package? :(
~~~

**Comment by deivid-rodriguez** [comment]
It seems like a bug. PR appreciated.

**Comment by voxik** [comment]
To start with, it is not clear to me what are the specifications.

Looking at history, first the `GEMSPEC_FILE` used to be whatever path. Then with #1454, the first assumptions came. Since that moment, the path and path with the `.gemspec` extension were tried. I think that at that moment, it was forgotten that `GEMSPEC_FILE` is not just file but full path. Then there was introduced the `-C` option as part of #2587. And later the #2887 proposed to use `gem build` without arguments.

I think the most problematic assumption is that the .gemspec file is part of the repository. That was never necessarily true.

**Comment by deivid-rodriguez** [comment]
The specification for the `-C` flag is what you expect in my opinion. It sounds like the implementation is buggy, that's all.

If you want to help fixing it, that's great. Otherwise, I don't think this issue needs anything else rather than a fix.
