### ISSUE TITLE
"Permission denied" error when running Bundler specs

### ISSUE THREAD

**Issue by duckinator** [rubygems/rubygems#3957]
**EDIT (2021-04-21):** A better workaround is to use `ruby-install` and `chruby`, which handles `GEM_HOME` for you. Other ruby managers (RVM, rbenv, etc) likely work, but I've not tested them.
**EDIT (2020-09-25):** A workaround is to set the `GEM_HOME` environment variable to a user-writeable directory.

### Describe the problem as clearly as you can

When attempting to run Bundler specs with a fresh clone of the RubyGems repository, at the `bin/rake spec:deps` step I get an error about the inability to access a certain path ending with `.../bundler.lock`.

The path varies slightly based on the operating system configuration &mdash; I've seen at least `/usr/share/gems/bundler.lock` and `/var/lib/gems/2.7.0/bundler.lock`.

### Post system independent steps to reproduce the problem

On an Ubuntu 20.04 or Fedora 31 system with git + Ruby installed, run:

```
git clone https://github.com/rubygems/rubygems.git && cd rubygems/bundler && bin/rake spec:deps
```

You can also use this Dockerfile:

```Dockerfile
FROM ubuntu:20.04

RUN apt update && apt install -y git ruby && useradd -m -s /bin/bash test
USER test
RUN git clone https://github.com/rubygems/rubygems.git /home/test/rubygems/
WORKDIR /home/test/rubygems/bundler

CMD ["bash", "-c", "bin/rake spec:deps"]
```

### Which command did you run?

`bin/rake spec:deps`, from the `bundler/` directory.

### What were you expecting to happen?

The command would avoid accessing files in `/usr` or `/var` if required, so it can actually run.

### What actually happened?

The output before the error and the file paths vary, but it always seems to end with this "Caused by" message:

```
Caused by:                                                                                                             
Errno::EACCES: Permission denied @ rb_sysopen - /var/lib/gems/2.7.0/bundler.lock                                       
/home/test/rubygems/bundler/lib/bundler/process_lock.rb:9:in `initialize'                                              
/home/test/rubygems/bundler/lib/bundler/process_lock.rb:9:in `open'
/home/test/rubygems/bundler/lib/bundler/process_lock.rb:9:in `lock'
/home/test/rubygems/bundler/lib/bundler/installer.rb:73:in `run'
/home/test/rubygems/bundler/lib/bundler/installer.rb:25:in `install'
/home/test/rubygems/bundler/spec/support/rubygems_ext.rb:107:in `install_gems'
/home/test/rubygems/bundler/spec/support/rubygems_ext.rb:12:in `dev_setup'
/home/test/rubygems/bundler/Rakefile:13:in `block (2 levels) in <top (required)>'
/usr/share/rubygems-integration/all/gems/rake-13.0.1/exe/rake:27:in `<top (required)>'
/home/test/rubygems/bundler/spec/support/rubygems_ext.rb:90:in `load'
/home/test/rubygems/bundler/spec/support/rubygems_ext.rb:90:in `gem_load_and_activate'
/home/test/rubygems/bundler/spec/support/rubygems_ext.rb:18:in `gem_load'
Tasks: TOP => spec:deps => dev:deps
(See full trace by running task with --trace)
```

Full output: https://gist.github.com/duckinator/e957d3b574a87c5e65ec98dd4c608adb

### If not included with the output of your command, run `bundle env` and paste the output below

<details>
<summary>Output of `bundle env`</summary>

#### Environment        
                             
```
Bundler       2.1.4
  Platforms   ruby, x86_64-linux
Ruby          2.7.0p0 (2019-12-25 revision 647ee6f091eafcce70ffb75ddf7e121e192ab217) [x86_64-linux-gnu]
  Full Path   /usr/bin/ruby2.7
  Config Dir  /etc                                                                                                     
RubyGems      3.1.2
  Gem Home    /var/lib/gems/2.7.0     
  Gem Path    /home/test/.gem/ruby/2.7.0:/var/lib/gems/2.7.0:/usr/lib/ruby/gems/2.7.0:/usr/share/rubygems-integration/2
.7.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/2.7.0
  User Home   /home/test
  User Path   /home/test/.gem/ruby/2.7.0
  Bin Dir     /usr/local/bin
Tools         
  Git         2.25.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

#### Bundler Build Metadata

```
Built At          2020-01-05
Git SHA           32a4159325
Released Version  true
```

#### Bundler settings

```
path.system
  Set for your local app (/home/test/rubygems/.bundle/config): true
```

</details>

**Comment by duckinator** [comment]
This may be a configuration problem, but I've encountered variants of it (the exact paths change a bit) on at least Fedora and Ubuntu, so it would be nice to be able to at least document how to work around it even if we can't properly fix it.

**Comment by deivid-rodriguez** [comment]
Nice report @duckinator!

The reason for this error is that the current user does not have write permissions to the default path where gems are to be installed. You can reproduce it with the `Dockerfile` you provided by installing any gem, without involving bundler at all. For example, running `gem install test-unit`, I get:

```bash
$ gem install test-unit
Fetching test-unit-3.3.6.gem
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.7.0 directory.
```

For the next major version of `bundler`, we're planning to change the default path to install gems to be a `.bundle` folder local to the CWD, similar to `npm`'s `node_modules`. I think a way to improve this would be to automatically opting-in to this change if the current user does not have write permissions on the "system gems folder". That would also have the added benefit of getting more people to test bundler's future behavior.

**Comment by duckinator** [comment]
@deivid-rodriguez ah, okay! that makes sense. The way I would expect to fix this is to put `gem: --user-install` in `~/.gemrc`, which fixes `gem install`.

<details>
<summary>Logs showing `gem install` working after adding `.gemrc`</summary>

```
test@991dafdbfacc:~/rubygems/bundler$ gem install test-unit
Fetching test-unit-3.3.6.gem
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /var/lib/gems/2.7.0 directory.
test@991dafdbfacc:~/rubygems/bundler$ echo 'gem: --user-install' > ~/.gemrc
test@991dafdbfacc:~/rubygems/bundler$ gem install test-unit
WARNING:  You don't have /home/test/.gem/ruby/2.7.0/bin in your PATH,
          gem executables will not run.
Successfully installed test-unit-3.3.6
Parsing documentation for test-unit-3.3.6
Installing ri documentation for test-unit-3.3.6
Done installing documentation for test-unit after 1 seconds
1 gem installed
test@991dafdbfacc:~/rubygems/bundler$
```

</details>

However, `bin/rake spec:deps` seems to be overriding that, and trying to install it globally anyway:

```
test@991dafdbfacc:~/rubygems/bundler$ bin/rake spec:deps
Fetching gem metadata from https://rubygems.org/.........
Using bundler 2.2.0.rc.2
Using json 2.3.0
Using webrick 1.6.0
rake aborted!
Bundler::InstallError: Bundler::PermissionError: There was an error while trying to write to `/var/lib/gems/2.7.0/cache`. It is likely that you need to grant write permissions for that path.
An error occurred while installing ast (2.4.0), and Bundler cannot continue.
Make sure that `gem install ast -v '2.4.0' --source 'https://rubygems.org/'` succeeds before bundling.
```

This behavior would explain why I can't run this command locally (outside of docker), as well &mdash; most things work by virtue of `--user-install`, but the Bundler specs are ignoring that!

**Comment by deivid-rodriguez** [comment]
Yeah, I don't think ` bundler` has ever respected `--user-install`. I guess we can also fix that :+1:.

**Comment by deivid-rodriguez** [comment]
Basically, we have finally figured out the `--user-install` issue none of us could reporoduce? :laughing:

**Comment by duckinator** [comment]
Yes, and I did some more digging. So far I've determined:

1. It isn't failing in `bin/rake spec:deps` itself, it's failing in a dependency of that &mdash; `bin/rake dev:deps`
2. `bin/rake dev:deps` ultimately calls `Spec::RubyGems#dev_setup` (from [`bundler/spec/support/rubygems_ext.rb`](https://github.com/rubygems/rubygems/blob/ff86ba/bundler/spec/support/rubygems_ext.rb)).
3. That ultimately calls `Spec::RubyGems#install_gems`.
4. This is calling `Bundler::Installer.install(Path.source_root, definition, :path => ENV["GEM_HOME"])`

And what this all means is that setting **`$GEM_HOME`** will override it. Given that `--user-install` explicitly _avoids_ using `$GEM_HOME`, I can see why this wasn't behaving as expected.

I confirmed that setting GEM_HOME to a user-accessible path in the Dockerfile allows getting farther in the process _and_ setting it locally causes everything to break in new and exciting ways. So we have a workaround. Only took over a year to figure out. :joy:

**Comment by deivid-rodriguez** [comment]
Actually, can you try https://github.com/rubygems/rubygems/pull/3795? Because I'm removing all that code in that PR :sweat_smile:. Maybe it fixes the issue.

**Comment by duckinator** [comment]
@deivid-rodriguez I'm about to go grab some food; will try to remember to try it in a bit. :stuck_out_tongue:

**Comment by duckinator** [comment]
@deivid-rodriguez it looks like on that branch I still have to set `$GEM_HOME` in order for `bin/rake dev:deps` to work, although I'm not sure why that's the case.

I've found a set of steps that seems to work at least enough to _start_ running the specs in Docker, though:

1. set GEM_HOME and GEM_PATH to point to the same directory.
2. install rake manually (since we can't rely on the system-provided one anymore)
3. Run `bin/rake spec:deps`

I've converted those to a Dockerfile which I am currently testing.

Interestingly, `setup_test_paths` in `rubygems_ext.rb` does basically the same thing:

```
      ENV["GEM_HOME"] = ENV["GEM_PATH"] = Path.base_system_gems.to_s
```

And, notably, that line runs after the part that fails without setting `GEM_HOME`/`GEM_PATH` manually.

**Comment by duckinator** [comment]
Updated Dockerfile:

```
FROM ubuntu:20.04

RUN apt update && apt install -y git ruby ruby-dev build-essential && useradd -m -s /bin/bash test
USER test
RUN git clone https://github.com/rubygems/rubygems.git /home/test/rubygems/
WORKDIR /home/test/rubygems/bundler

ENV GEM_HOME=/home/test/.bundle/gems
ENV GEM_PATH=/home/test/.bundle/gems
# Install things that we can't rely on having globally.
RUN gem install rake

CMD ["bash", "-c", "bin/rake spec:deps"]
```

Using this Dockerfile, I get 22 failures:

```
Finished in 50 minutes 5 seconds (files took 1.04 seconds to load)                
2891 examples, 22 failures, 7 pending  
```

Some of them are errors related to Ubuntu's Docker container ["minimizing" certain packages](https://wiki.ubuntu.com/Minimal).

Some are conflicts between two copies of the URI library, e.g.:

```
        /usr/lib/ruby/2.7.0/bundler/vendor/uri/lib/uri/version.rb:3: warning: already initialized constant Bundler::URI
::VERSION_CODE                                                                                                         
        /home/test/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.2.0.rc.2/lib/bundler/vendor/uri/lib/uri/version.rb
:3: warning: previous definition of VERSION_CODE was here    
```

(As an aside, I have similar conflicts on my local system with Psych.)

**Comment by duckinator** [comment]
Spent an hour on this again, because every time I take a break from working on RubyGems + Bundler, this is the problem that I run into first when I come back.

It looks like most of the problems I encountered are gone if I use `ruby-install` + `chruby`.

The remaining 7 failed tests are _all_ due to the Parser gem being at version 3.0.0.0 while Ruby 2.7.3 is only supported with 3.0.1.0.

I think this means if I switch to Ruby 2.7.2 it'll work.

**Comment by duckinator** [comment]
Using `ruby-install` + `chruby`, Ruby 2.7.2, Fedora 32. This is pretty significant progress.

RubyGems:

```
Finished in 82.687915s, 27.1624 runs/s, 85.8892 assertions/s.

2246 runs, 7102 assertions, 0 failures, 0 errors, 1 skips
```

Bundler:

```
bin/rspec
Run options: exclude {:truffleruby=>true, :jruby=>true, :readline=>false, :permissions=>false, :no_color_tty=>false, :ruby_repo=>false, :bundler=>"!= 2", :git=>"!= 2.26.3", :realworld=>true, :sudo=>true}

Randomized with seed 42615

<...>

  1) The library itself ships the correct set of files                                                                 
     Failure/Error: expect(git_list.sort).to eq(gem_list.sort)                                                         
                                                                                                                       
                                                                                                                       
       Commands:                                                                                                       
       $ git ls-files -z -- lib exe CHANGELOG.md LICENSE.md README.md bundler.gemspec  
<...>
       # $? => 0                                                                                                       
                                                                                                                       
       expected: ["CHANGELOG.md", "LICENSE.md", "README.md", "bundler.gemspec", "exe/bundle", "exe/bundler", "lib/bund.
..ersion_ranges.rb", "lib/bundler/vlad.rb", "lib/bundler/worker.rb", "lib/bundler/yaml_serializer.rb"]                 
            got: ["CHANGELOG.md", "LICENSE.md", "README.md", "bundler.gemspec", "exe/bundle", "exe/bundler", "lib/bund.
..ersion_ranges.rb", "lib/bundler/vlad.rb", "lib/bundler/worker.rb", "lib/bundler/yaml_serializer.rb"]
       (compared using ==)                                                                                             
     # ./spec/quality_spec.rb:222:in `block (2 levels) in <top (required)>'                                            
     # ./spec/spec_helper.rb:98:in `block (4 levels) in <top (required)>'                                              
     # ./spec/spec_helper.rb:98:in `block (3 levels) in <top (required)>'
     # ./spec/support/helpers.rb:350:in `block in with_gem_path_as'
     # ./spec/support/helpers.rb:364:in `without_env_side_effects'
     # ./spec/support/helpers.rb:346:in `with_gem_path_as'
     # ./spec/spec_helper.rb:97:in `block (2 levels) in <top (required)>'
     # ./spec/support/rubygems_ext.rb:99:in `load'
     # ./spec/support/rubygems_ext.rb:99:in `gem_load_and_activate'
     # ./spec/support/rubygems_ext.rb:18:in `gem_load'

Finished in 39 minutes 1 second (files took 0.89897 seconds to load)
3104 examples, 1 failure, 9 pending

Failed examples:

rspec ./spec/quality_spec.rb:217 # The library itself ships the correct set of files

Randomized with seed 42615

rake aborted!
Command failed with status (1): [bin/rspec...]
/home/puppy/dev/ruby/duckinator/rubygems/bundler/Rakefile:7:in `block in <top (required)>'
/home/puppy/dev/ruby/duckinator/rubygems/bundler/spec/support/rubygems_ext.rb:99:in `load'
/home/puppy/dev/ruby/duckinator/rubygems/bundler/spec/support/rubygems_ext.rb:99:in `gem_load_and_activate'
/home/puppy/dev/ruby/duckinator/rubygems/bundler/spec/support/rubygems_ext.rb:18:in `gem_load'
Tasks: TOP => spec
(See full trace by running task with --trace)
```

**Comment by duckinator** [comment]
Looks like I had some `.rb~` files from when I was working in vim, and that spec doesn't ignore them. Removing them and running `bin/rspec --only-failures` passed.

I'll re-run the whole test suite again in the background while I go do non-RubyGems/Bundler stuff for a bit to double-check that everything's good.

**Comment by duckinator** [comment]
Yup, using `ruby-install` + `chruby` works, now. I'm gonna go ahead and close this.

**Comment by deivid-rodriguez** [comment]
@duckinator Yes, any version manager should work. I'm sorry I never suggested it to you before. I completely missed that this was a real blocker to you, but instead thought that you simply wanted your less common setup to also work. Happy you got it sorted out, using a version manager is _definitely_ better supported.

**Comment by duckinator** [comment]
@deivid-rodriguez I'd previously tried a version manager and still had test failures (just different ones), but it looks things have changed enough over the last few years that the problem is resolved by just using a version manager. ^^
