### ISSUE TITLE
`rake generate_changelog` is not idempotent

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#3962]
Currently if you run `rake generate_changelog` several times, it will keep adding duplicated changelog entries for the specified release on top of the changelog. It'd be nicer if it detected if the changelog had already been generated and updated the proper section.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
Also... should we be allowed to run `rake generate_changelog` without a version? I noticed it generates a changelog without a version title I guess that is something that we never want?

i.e: 
```
===  / 2020-09-29

Minor enhancements:
* Add `--force` option to `gem sources` command. Pull request #3956 by
....
```

**Comment by deivid-rodriguez** [comment]
Definitely, propably the easiest way would be to bump the left-most number in the current version by one and use that?
