### ISSUE TITLE
Global vs block gem server source priority doesn't work as expected

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#3982]
In a situation like the following:

```ruby
# my-private-gem.gemspec
# ...
gem.dependency("my-another-private-gem")

# Gemfile
source 'https://my-private-server' do
  gem 'my-private-gem'
end
```

Bundler should try to resolve using the private source for my-private-gem and all of its indirect dependencies. Only if a valid resolution is not found, it should also consider `rubygems.org` for those dependencies.

Insted, Bundle will still install `my-another-private-gem` from rubygems.org if the gem exists there. We should probably search first in the same source as `my-private-gem` before falling back.

_Originally posted by @rafaelfranca in https://github.com/rubygems/rubygems/issues/3948#issuecomment-692920465_

**Comment by sonalkr132** [comment]
Can confirm this issue exists. [bundler doc says](https://bundler.io/man/gemfile.5.html#SOURCE-PRIORITY):

> For implicit gems (dependencies of explicit gems), any source, git, or path repository declared on the parent. This results in bundler prioritizing the ActiveSupport gem from the Rails git repository over ones from rubygems.org

which is the expected behavior as per the issue but not observed.

**Comment by deivid-rodriguez** [comment]
https://github.com/rubygems/rubygems/pull/4609 should fix this and make bundler behave as documented.

Note that the solution slightly differs from what I originally proposed in the sense that if a scoped source includes _any version_ of `my-private-gem`, the gem will be picked up from there. Falling back to the default source would only happen if the name does not exist at all in the scoped source.

As I originally proposed it, the fallback would also happen if the scoped source includes `my-private-gem` but not a version that matches all requirements. With this solution, bundler will fail to resolve claiming that it couldn't find a compatible version of `my-private-gem` in `https://my-private-server`. I can't make the original proposal work since my approach is to resolve sources for each involved gem name beforehand before resolution even starts.

I think this solution matches the documentation exactly, and it's what users intuitively expect, so seems fine to me.
