### ISSUE TITLE
query command deprecation clarification

### ISSUE THREAD

**Issue by hurricup** [rubygems/rubygems#3984]
I'm having a problem or would like to suggest feature. (more like request for clarification)

My current problem is deprecation of `query` command without describing alternative.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.2.0.rc.1
```

We have a deprecation warning for the query command, but [documentation](https://guides.rubygems.org/command-reference/#gem-query) does not say anything about deprecation or discouraging using it. Also, warning provides no information about what to use instead.

**Comment by deivid-rodriguez** [comment]
You're right!

We deprecated the `query` command in favour of either `gem search` or `gem list`, dependending on whether you're looking for remote gems, or gems installed on your system. There was an old note in `gem query` that said:

> You should really use the list and search commands instead.  This command is too hard to use.

And we decided the note made sense and deprecated it.

We should:

* Add a note to `guides.rubygems.org` mentioning that the command was deprecated (and in which version).
* Improve the deprecation message to point to the alternatives.
