### ISSUE TITLE
learn and ruby gems issue

### ISSUE THREAD

**Issue by Veenie** [rubygems/rubygems#4005]
I'm having a problem or would like to suggest a feature.

My current problem is no connection to ruby gems
![ruby error](https://user-images.githubusercontent.com/64918918/95413610-b0fd0300-08e0-11eb-9de3-12fd7254dc5a.png)
![ruby error 2](https://user-images.githubusercontent.com/64918918/95413645-c8d48700-08e0-11eb-8742-18654d3cb0ba.png)

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ X] Other

Here are my current environment details:

```
$ gem env version
PASTE HERE
3.0.8
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Hi @Veenie! Are you [using ipv6](https://test-ipv6.com/)? This seems similar to some ipv6 issues we've been having over time.

**Comment by Veenie** [comment]
How do I check that? Is there some command, it's possible that might be it.

**Comment by hsbt** [comment]
I didn't find any issue of rubygems. It's your environment or `learn` gem. https://stackoverflow.com/ may helps you.

**Comment by deivid-rodriguez** [comment]
> How do I check that? Is there some command, it's possible that might be it.

If you go to the website I linked to, https://test-ipv6.com/, that should test your ipv6 connection.
