### ISSUE TITLE
v3.2.0.rc.2 - gem sources --force option not appearing in help

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#4007]
Using v3.2.0.rc.2, I ran `rake command_guide` from the `rubygems_guides` repo and didn't see the `--force` option for `gem sources`.  When running `gem sources --help`, it also does not appear.

**EDIT:** It was also mentioned that a `--platform` option was added to `gem build`.  That is appearing in both.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.2.0.rc.2   (copied into master)
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Sorry, this is a problem with the release changelog.

I use a new workflow for releasing bundler, which handles backporting PRs and generating the changelog automatically from PR labels. This workflow is now partly used by rubygems as well for generating the changelog, but not yet for pull request backporting, which is still done manually. So even if the changelog says this change was backported, it wasn't. Sorry about that.

I'll correct the changelog now, and work on a unified workflow to prevent these discrepancies from happening again in the future :+1:.
