### ISSUE TITLE
Using main branch as default I get that Revision master does not exist

### ISSUE THREAD

**Issue by thiaguerd** [rubygems/rubygems#4009]
Hi 👋

I have a personal gem at my_repo that a default branch is a main.
And I need specify a branch to works.
Using like that does't works

```ruby
gem 'my_gem', git: 'my_repo'
```

Works fine if I specify a branch

```ruby
gem 'my_gem', git: 'my_repo', branch: :main
```

Branch main not should be checked too?

`Bundler version 2.1.4`

**Comment by hsbt** [comment]
bundler only support "master" ref.

https://github.com/rubygems/rubygems/blob/master/bundler/lib/bundler/source/git.rb#L25

**Comment by deivid-rodriguez** [comment]
Definitely! We should try to use the repository's default branch rather than hardcoding master.
