### ISSUE TITLE
Consider delaying the change to resolve against all `Gemfile` platforms by default

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#4018]
### Describe the problem as clearly as you can

In bundler 2.2.0, as per https://github.com/rubygems/bundler/pull/7580, bundler will start resolving against all platforms directly specified in the `Gemfile`. See https://github.com/rubygems/bundler/pull/7580 for the rationale behind it.

This change will have some consequences:

* It will make `bundle install` fail in some cases that were previously not failing.

* It will make resolution less slower for gemfiles including platforms different than that currently running platform, because it will resolve all platforms by default and not just the current platform.

An example of the former is if you're developing a gem with both jruby & C-extensions, using the same `gemspec` for both, running `bundle install` under `jruby` and having a `Gemfile` with a gem specific to a platform different than jruby.

This happens in https://github.com/mongodb/bson-ruby (that has both java and C-extensions, and includes `gem "byebug", platform: :mri` in its `Gemfile`). In such a case, `bundler` will try to resolve against all platforms, and for each of them it will try to use the same gemspec (because of `gemspec` DSL in the `Gemfile`). It will eventually fail because the gemspec picks the currently running platform but will fail to be found for other platforms.

The solution would involve maintaining several gemspecs for each supported platform, but I think most gems like this don't do that, and the error given doesn't make it clear that this is a solution (or what the culprit is).
  
### Post steps to reproduce the problem

```shell
git clone https://github.com/mongodb/bson-ruby
cd bson-ruby
rbenv shell jruby
gem install bundler:2.2.0.rc.2
bundle install
```

### What were you expecting to happen?

No failure, lockfile generated.

### What actually happened?

```
$ bundle install
[bson] Warning: No private key present, creating unsigned gem.
Fetching gem metadata from https://rubygems.org/........
Could not find gem 'bson' in source at `.`.
The source contains 'bson' at: 4.10.0 java
```

### Proposed "solution"

After looking back, the initial reason to start doing this was to "fix" the annoying warning `bundler` prints in this situation:

> The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform mingw, mswin, x64_mingw, jruby`.

This warning, whatever we end up doing here, doesn't make sense to me. If your `Gemfile` uses platform specific dependencies, it's expected that sometimes the dependency will be used, and sometimes it won't. No need to warn that.

As long as we keep not showing the warning I think it's fine to keep the previous behaviour by default, which doesn't have any of the above issues. More on the rationale for reverting:

* Our multiplatform support is still very new so it might have issues. Re-resolving for all platforms by default might make those issues arise too loudly in situations where people don't really care.

* Re-reresolving against all platforms by default has a resolution performance penalty for many `Gemfile`'s. We can try to improve the resolver performance first before enabling this by default.

* People not committing their lockfile don't care about deterministic resolutions not even for their own platform. They just want any valid resolution. So it's reasonable to assume that they won't care either about determinism for all platforms, and they will be _definitely_ be unhappy about this change breaking their previously working `bundle install`.

* People committing their lockfile might care about this (I do :smiley:), so if we revert we should still provide a way to opt in to recording all resolutions for all platforms in the lockfile, so that all users of the `Gemfile`, no matter which platform they use, will get _the same_ set of gems installed on their system. Currently, there's some ways to achieve this:
  * Run `bundle install` independently on each target platform and commit each intermediate lockfile.
  * Run `bundle lock --add-platform <platform>` for each platform that you want to support.

I propose to introduce an easier better way to do this: `bundle install --all-platforms`, `bundle update --all-platforms`, `bundle lock --all-platforms`, but keep the previous default behaviour.

I still like the idea of resolving all platforms by default but I'd like to give all the new multiplatform improvements the chance to get battle tested first, and maybe our resolver to be improved first, before making that change.

**Comment by larskanis** [comment]
Adding proper multiplatform support but keeping the current behavior of resolving the current platform only is the best solution for now. Thank you so much @deivid-rodriguez !
