### ISSUE TITLE
Bundler and RubyGems install directory mismatch

### ISSUE THREAD

**Issue by felipec** [rubygems/rubygems#4027]
Many people don't install to the default directory, but to the user directory (--user-install), in fact, it's the default on many distributions.

Unfortunately this causes a mismatch between bundler and gem, since bundler doesn't read `gemrc` configuration files.

This problem has been explored in many issues: rubygems/bundler#710, rubygems/bundler#2565, rubygems/bundler#2667, chef/chef-dk#148. No satisfactory resolution from the development team.

I took the time to develop a simply and easy solution myself that should absolutely work for everyone, an environment variable: GEM_USER_INSTALL, which just works ™. And thus I am creating yet another issue ticket.

**Comment by hsbt** [comment]
> Many people don't install to the default directory, but to the user directory (--user-install), in fact, it's the default on many distributions.

I don't think so. The users who are using the default package provided many of Linux distributions are minority. also see https://rails-hosting.com/2020/#ruby-rails-version-updates

I'm Ruby programmer over the 20+ years. I and my company also didn't use it. We use the custom runtime build by like ruby-build.

> No satisfactory resolution from the development team.

This comment is a little offensive.

**Comment by felipec** [comment]
@hsbt 

> I don't think so. The users who are using the default package provided many of Linux distributions are minority.

Really? Is that why 64% of Arch Linux users have [installed ruby gems](https://pkgstats.archlinux.de/packages#query=rubygems)? Is that also why Debian packages rubygems directly into the `ruby` package?

> https://rails-hosting.com/2020/#ruby-rails-version-updates

Rails developers != Ruby users.

> This comment is a little offensive.

You think reality is offensive?

**Comment by deivid-rodriguez** [comment]
Whatever the popularity of Linux distributions is, I agree we could do better here. What about honouring `--user-install` if bundler is installing to system gems (i.e., no custom `BUNDLE_PATH` configuration is given). I think it's reasonable to respect whatever rubygems considers as the preferred location to install system gems.

**Comment by felipec** [comment]
@deivid-rodriguez I also created a patch for that, but it's so ugly it seems like a hack. Basically we would need to parse `Gem.configuration` and find the `--user-install` string. I did it only for `gem`, but the same has to be checked for `install`.

```
--- a/bundler/lib/bundler/rubygems_integration.rb
+++ b/bundler/lib/bundler/rubygems_integration.rb
@@ -163,6 +163,8 @@ def sources
     end
 
     def gem_dir
+      user_install = Gem.configuration[:gem]&.split(' ')&.include?('--user-install')
+      return Gem.user_dir if user_install
       Gem.dir
     end
 

```

**Comment by deivid-rodriguez** [comment]
Right, it _does_ feel like a hack, since these `gemrc` options are meant as permanent flags to the `gem` CLI commands. Not sure what the best solution is, need to think about it, but I don't like adding yet another environment variable.

**Comment by felipec** [comment]
@deivid-rodriguez I've thought about it and tried many things. The environment variable is the only clean solution I see.

I don't think the configurations of `gem` and `bundler` were thought through.

**Comment by deivid-rodriguez** [comment]
Thanks for your feedback, I guess? :man_shrugging:

I tend to disagree and I currently believe it's might be better to add the ugly code and make this just work without the need for setting yet another environment variable. We could also deprecate the `--user-install` flag and move this to a global configuration to make the code cleaner, since I believe people don't just want `--user-install` for single CLI invocations but for changing the location to install gems to a user location permanently.

**Comment by deivid-rodriguez** [comment]
I'd like to hear @duckinator's opinion since I'm aware she's a user of the `--user-install` flag and also a maintainer with better context :)

**Comment by deivid-rodriguez** [comment]
> I don't think the configurations of `gem` and `bundler` were thought through.

These libraries are like 15 years old. While I work on improving them I try to not make any judgement on past decisions, because te context at the time was completely different from the context now. To give you an example, when `--user-install` was added, maybe `bundler` didn't exist yet. Statements like the above feel quite arrogant to me, to be honest.

**Comment by felipec** [comment]
The concept of users was known 15 years ago. If you had asked me 15 years ago what should have been the way gems were installed I could have told you then; make user installations the default. The system installation is the special case, which could have been enabled with `--system`.

There's no reason to have `Gem.user_dir`. Only two concepts are needed: 1. the location where gems are installed to, 2. the paths to look for gems (which includes `Gem.default_dir`).

It's **that simple**.

My statement may look arrogant to you, yet it's still true.

**Comment by hsbt** [comment]
This is final notice. Do honest, respectable, and collaborative.

**Comment by felipec** [comment]
> Be honest, respectable, and collaborative.

I am.

- Honest: I am speaking the truth, that's called **honesty**.
- Respectable: I am not **disrespecting** anybody. Ideas on the other hand don't have feelings and are meant to be criticized.
- Collaborative: I've sent multiple patches and addressed the feedback on those patches. That is called **collaboration**.

> This is the final notice.

Or what? You are going to willingly harm the users of rubygems that have been reporting these issues for more than **ten years**?

What you do is up to you. If you fix this, great, if not, I will take this ticket as evidence and suggest a hacky solution downstream to my distribution maintainers, since you leave us no other choice.

What you are doing is called [tone policing](https://en.wikipedia.org/wiki/Tone_policing), and it distracts from the issue at hand. It would be much more productive if you concentrated on **the bug**, rather than my tone, but that's your choice.

**Comment by deivid-rodriguez** [comment]
Let's have a fresh discussion about this at https://github.com/rubygems/rubygems/issues/4031.
