### ISSUE TITLE
Ability to install only some gem groups (a subset of everything in the Gemfile)

### ISSUE THREAD

**Issue by sandstrom** [rubygems/rubygems#4048]
### Describe the problem as clearly as you can

The `--with` flag, or some other mechanism, such as an `--only` flag, should allow installing only specified groups.

The use-case for me is that when running Github actions I only want to install a few gems and installing all of them for every CI run costs time and money.

Doing negative selection (`--without=default,development`) doesn't feel like an elegant solution, since it stops working if more groups are added.

### Post steps to reproduce the problem

1. Create this Gemfile

```ruby
# Gemfile
source 'https://rubygems.org'

gem 'bcrypt', '~> 3.1'
gem 'excon', '~> 0.75'

group :development do
  gem 'spring', '~> 1.4'
end

group :development, :linting do
  gem 'rubocop', :require => false
  gem 'brakeman', :require => false
end
```

2. Run `bundle install --with=linting`

### What were you expecting to happen?

I expected `bundle install --with=linting` to only install `rubocop` and `brakeman`.

### What actually happened?

All gems were installed.

## Prior Art

This PR (with quite a lot of activity and upvotes) is basically about the same thing: https://github.com/rubygems/bundler/pull/4907

It contains a bunch of arguments for and against this functionality.

**Comment by deivid-rodriguez** [comment]
Hi!

In general, I tend to think these situations are better solved with a separate `Gemfile`. Let me try to explain. Normally lint tools run separate executables to analyze your code statically (they don't need to actually run your code, as opposed to, for example, your tests). So, it seems to me that a good fit for these situations is to split the "linting" group to a separate `Gemfile`, say, `Gemfile.lint` and then make sure your project binstubs for `rubocop`  and `brakeman` always use that alternative `Gemfile` (add `BUNDLE_GEMFILE=Gemfile.lint` on top of them).

This has the advantage that your `Gemfile` is restricted to stuff that your app needs to work, and that "lint only dependencies" won't hold your application dependencies behind (let's say, one of your lint tools depended on `activesupport ~> 5.2`.  In that case, that "lint only dependency" would unnecessarily prevent you from upgrading to Rails 6). 

That said, I have to say a `BUNDLE_ONLY` configuration doesn't seem too much maintenance overhead, so I wouldn't mind if we decide to add it. But I don't currently feel it's necessary.

**Comment by sandstrom** [comment]
@deivid-rodriguez Thanks for an extensive reply!

What you say makes a lot of sense. We'll try to modify our workflow to use a separate gemfile for linting. Thanks! 🙏🏻 

That said, when making changes for the next major version of bundler, a possible breaking change could be to change the behavior of the `--with` flag (assuming its not going away, and that you agree with what I'm suggesting).

**Comment by deivid-rodriguez** [comment]
@sandstrom No problem! I did a "lint Gemfile extraction" with the idea I'm suggesting at https://github.com/deivid-rodriguez/bythisebug/pull/756, in case it helps.

Regarding changing `--with` behaviour, I think it's too much trouble. What `--with` currently does seems useful (for example, include "production" gems together with the rest of "default" gems in my Gemfile), so I don't want to introduce breaking changes unnecessarily.

I do think that there's a set of challenges on integrating & maintaining a secondary Gemfile for linting situations (even if it still feels better to me) and that some people might prefer to use a single Gemfile and a `BUNDLE_ONLY` configuration, so I'm still open to introducing it.

Let me know how modifying your workflow in this direction goes and we can see what to do from there.

**Comment by sandstrom** [comment]
Alright, that makes sense!

It probably a bad idea to make changes to bundler only based on a single person (me). However, there were quite some comments in the earlier issue (https://github.com/rubygems/bundler/pull/4907). Some of them are a few years old, but my guess would be that the "CI use-case" that most people mentioned is still valid.

Could loop them in here and see if their use-case remain, or gather feedback via some other channel (or just wait and see).

Either way, thanks for your work on bundler and for taking your time replying here! 🏅

**Comment by deivid-rodriguez** [comment]
Sure! I think looping people in the related PR here is a good idea. I read the comments there and most people seemed to be in a similar situation where I think a separate Gemfile could work. But I did face a few challenges when adding that to my library so I'd like some feedback on how that fits people's workflows.

**Comment by rubyFeedback** [comment]
I think there is a use case for that; for example, I see this more as independent from bundler, and
more generally as a "ruby ecosystem", e. g. a user who says "ruby, just install all gems that have
something to do with games, as a tag". Something like that might be useful. (Not sure how important
it is though.)

Part of this problem relates from bundler allowing more fine-tuned control whereas rubygems follows
the simpler oldschool "gem install bla", install dependencies, end of story. The latter approach has
one HUGE advantage: it is really super-simple! I love that. This is also a reason why I don't use
bundler, I just love simplicity. This should be considered too when making changes. But aside from
that, I think more control for those who NEED it, may be useful too - I just am not sure how many
people really need that.

On a side note, my personal workflow does not involve any Gemfiles (I started with ruby in the
pre-bundler time and am too lazy to ever switch to anything else that is not as simple ;) ), so 
no change is likely going to affect me personally. Ultimately this should be for those who use
Gemfiles. Just don't forget us non-Gemfile folks!!

**Comment by Andrewngabriel** [comment]
I've ran into this exact issue that @sandstrom mentioned regarding installing gems in a linting job running in github actions. While I haven't tried the approach of using a separate Gemfile specifically for linting, I was hoping there would be a way to modify the behavior of `--with` while not introducing breaking changes. I'm open to contributing to add this but just need some guidance about which files I would need to look into specifically

**Comment by ojab** [comment]
This also pollutes docker images with development/test gems, I just noticed that image with `bundle config --local with production` has all the development/test stuff.
And `bundler clean` doesn't cleanup this gems, will fill a separate issue for that.

**Comment by SolaWing** [comment]
I paste following snippet at end of Gemfile to implement only feature:

```ruby
# use BUNDLE_ONLY=<group> to only load the specified group.
if only = Bundler.settings[:only] and only = only.split(":").map(&:to_sym) and !only.empty?
  @optional_groups = dependencies.map(&:groups).flatten.uniq - only
end
```
this convert all group except only group to optional groups. so only the `only group` will be required
