### ISSUE TITLE
Reopen issue #88

### ISSUE THREAD

**Issue by iboB** [rubygems/rubygems#4051]
Issue #88 has been closed for a long time and thus doesn't get the needed attention, but there are legitimate use cases for it. 

If the issue is open, then at least we'll have some way of gauging community support for it (which I think there will be)

It should probably also be renamed to "Support packaging of non-ruby executables"

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Please comment directly on the closed issue if you want it reopen.
