### ISSUE TITLE
Promote `-C` to a global flag

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#4058]
I noticed that the `-C` flag, currently only usable with `gem build`, could probably be useful as a global flag. For example, it could be helpful for `gem install` too as per [#448 (comment)](https://github.com/rubygems/rubygems/issues/448#issuecomment-716509271).

I propose to promote it to a global flag that can be used for any command.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bronzdoc** [comment]
What other commands could benefit from the `-C` flag besides the `install` command?

**Comment by deivid-rodriguez** [comment]
I think a global `-C` flag can be useful in general for scripting, but I don't have specific ideas of other commands that could use it. I you don't think this is useful globally, we can then add `-C` for `gem install` only. I don't have a very strong opinion, really.

**Comment by deivid-rodriguez** [comment]
Let's add it for `gem install` only to fix the referenced issue.
