### ISSUE TITLE
How to prevent 'Fails with Gem::Ext::BuildError: ERROR: Failed to build gem native extension' on cloud Mac?

### ISSUE THREAD

**Issue by joegoodall1** [rubygems/rubygems#4073]
We've installed GitLab Runner on a remote Mac and configured it to our .gitlab-ci.yml file to build an iOS app via fastlane.

All the gems install fine until it reaches here

`Installing unf_ext 0.0.7.6 with native extensions
`

where it fails with

```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
 current directory:
 /Users/cloud-mac/builds/prJ_GqMs/0/mobile/our_app/vendor/bundle/ruby/2.6.0/gems/unf_ext-0.0.7.6/ext/unf_ext
```
It works fine locally on my Mac. Any idea why it's having this issue on the cloud Mac? Any help would be greatly appreciated.

**Comment by MSP-Greg** [comment]
The error you're seeing is normally due to missing build tools and/or dependencies.  Have you tried any other extension gems?  Maybe JSON, OpenSSL, Nio4r, Puma, etc?

**Comment by joegoodall1** [comment]
Thanks for your reply @MSP-Greg 

Info from this post resolved the issue https://forum.gitlab.com/t/gitlab-runner-environment-different-than-the-users/31536
