### ISSUE TITLE
A more general discussion about DOCUMENTATION for rubygems

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems#4078]
Hey folks,

I already wrote a similar issue on rubygems.org, but perhaps it may be better to write it here as well,
adapted.

Since it is not good to keep open issues, I propose to have a maximum time for this issue of 3 months.
Aka in 3 months from now on just close this please. Or, if you want to, just close it earlier; my main
point is trying to get people to understand the problem at hand.

Problem at hand:

I was checking on the documentation of one of my gems:

https://www.rubydoc.info/gems/dictionaries/0.2.178

It reads right now:

"Error 503 Service Unavailable

Service Unavailable"

Well, I had this in the past, ok. It tends to work in a few days.

But ... I find this inacceptable. These are just autogenerated
static files. What is so hard about that?

In fact: I could autogenerate them locally, then upload them
when I do a "gem push", right? So why do I depend on this
website? Why is that website detached from rubygems.org
either?

If I publish at github, the README.md is rendered instantly
without such problems. If people want to read documentation
for my gems, they can not do so BECAUSE THEY RUN INTO
THIS 503 ERROR. In the year 2020 and past, is this 
acceptable for ruby? How can ruby compete with python
if such simple problems exist and are not resolved?

To be fair: I don't want to be critical of https://www.rubydoc.info/
per se. I don't think it happens on purpose - but it happens
now and then. And WHEN it happens it is annoying. 

In oldschool FTP days, I would just auto-upload via ruby
from the commandline. It's a static file. People can instantly
see it when I ftp-uploaded it (via ruby code). In 2020 we
depend on some half-broken service that doesn't work
50% of the time or so ... 

All the rendering I could do before "gem push" is done.

Can we get some workflow where we no longer depend on
rubydoc.info? This could be space-limited. For example,
rubygems.org already hosts the gems. Gems can be
quite large too. I tend to only maintain the last actively
maintained gem for my projects, with a few exceptions.
So I keep the space need small. :D

Would it be possible to also upload these documentations
on rubygems.org, and have it work? I only need THAT
functionality for the last active gem. But I don't think it
is acceptable that documentation does not work, whereas
on github-based hosting it just works without a problem.

My aim here is mostly to get a discussion going, to raise
awareness for people to understand that things really
should not be so bad. Of course we could also assume
that rubydoc.info becomes better, but I don't have much
hope for that because this issue keeps on re-appearing
again and again. And at that point, it may be better for
people to then indeed use github (which I rather not
want to do because it means Microsoft controls part of
the ecosystem, which I also dislike a LOT; rubygems.org
does not have the same problem as github has in regards
to WHO controls it).

**Comment by deivid-rodriguez** [comment]
Hi @rubyFeedback.

So, you said you opened an issue at rubygems.org and that got closed or something? I guess the feature you're asking for was rejected? I completely fail to see how this could be related to rubygems (the client)?

I made some research and I think the source for the rubydoc.info site is https://github.com/docmeta/rubydoc.info. Could you please open an issue there with whatever issues you're having?

Thanks!

**Comment by duckinator** [comment]
Nothing is forcing anyone to use rubydoc.info for their documentation. It's a free service provided by different people than RubyGems.

Just talk to _the people who actually maintain it_ about the problems you're having, or host your documentation elsewhere.

**Comment by duckinator** [comment]
It looks like this may be how you can change what URL the "Documentation" link on the rubygems.org page would link to, but I've not confirmed that: https://guides.rubygems.org/specification-reference/#metadata

**Comment by deivid-rodriguez** [comment]
No response, so closing. It doesn't seem like a problem in rubygems.
