### ISSUE TITLE
new gems should have a default Github Action and no Travis.yml

### ISSUE THREAD

**Issue by marcandre** [rubygems/rubygems#4080]
For most OSS projects, travis is now unnaccessible. Github actions seems like the de-facto standard (and is faster than travis for me).

**Comment by indirect** [comment]
I think this is a good idea. Does someone want to send a pull request? Might be a good first-time contribution.

**Comment by deivid-rodriguez** [comment]
Agreed too!

**Comment by hsbt** [comment]
👍 I also agreed to change it.

**Comment by simi** [comment]
@marcandre please can you provide some details for this statement?

> For most OSS projects, travis is now unnaccessible

_PS: I'm not against this._

**Comment by deivid-rodriguez** [comment]
Probably some issue related to [this](https://travis-ci.community/t/builds-hang-in-queued-state/10250/26)? I've seen it too.

**Comment by simi** [comment]
So is it related to 1000 minutes limit at travis-ci.com and "deprecation" of travis-ci.org? And instead of migrating by default to travis-ci.com, it is considered better update to github actions directly?

**Comment by deivid-rodriguez** [comment]
Actually, after a second thought, I don't think we have a default CI service at the moment?

If a CI service is configured, that service is used, otherwise `bundle gem` will ask for a preferred CI service. So there's nothing actionable here, I think. Well, probably changing any links from travis-ci.org to travis-ci.com.

**Comment by marcandre** [comment]
> If a CI service is configured

Ah! I see in `bundle help gem` that there's a recent `--ci` switch & config, since #3667.
I wasn't aware of the config option.

It doesn't seem to work, but that's a different issue.
