### ISSUE TITLE
[feature-suggestion] Allow rubygem plugins to register custom command aliases

### ISSUE THREAD

**Issue by postmodern** [rubygems/rubygems#4090]
If rubygem plugins can register their own commands, it would also be useful to register command aliases. Unfortunately the current RubyGems [CommandManager API](https://rubydoc.info/gems/rubygems-update/Gem/CommandManager) does not provide the ability to register aliases and the `ALIAS_COMMANDS` hash is frozen.

**Comment by simi** [comment]
Is it possible to just register one command twice using two names?

**Comment by duckinator** [comment]
I don't have a strong opinion either way on adding this feature, but looking at the code, it does seem like registering one command twice should be a workaround for it. If that's not the case, lmk what issue(s) you run into and I can dig into it some more.

**Comment by deivid-rodriguez** [comment]
I'll close since we received no further feedback, happy to reopen and keep the discussion open if we do though :+1:.
