### ISSUE TITLE
S3 Source Provider for instance_profile assumes that instance profile and role name are identical

### ISSUE THREAD

**Issue by phene** [rubygems/rubygems#4094]
I'm having a problem getting an s3 source to work when using the instance_profile provider in my ~/.gemrc

The current mechanism for looking up credentials using the instance_profile metadata currently assumes that the instance profile and role name associated with the instance profile are identical.

If I have an instance profile called "foo" that reference a role called "bar", then the lookup will not work.

The aws metadata endpoint for `http://169.254.169.254/latest/meta-data/iam/info` provides the ARN of the instance profile, which refers to `foo`, but `http://169.254.169.254/latest/meta-data/iam/security-credentials/` requires the role name to fetch credentials, thereby expecting `bar` rather than `foo.

A clearer path to getting the role name is to skip the `http://169.254.169.254/latest/meta-data/iam/info` lookup and just query 
`http://169.254.169.254/latest/meta-data/iam/security-credentials/`, which returns the role name associated with the instance profile. If it returns `foo`, then you query `http://169.254.169.254/latest/meta-data/iam/security-credentials/foo` to get the credentials.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by phene** [comment]
This [comment](https://github.com/rubygems/rubygems/pull/2894/commits/9a401646e1725dec471e6b22b4670ebcb3191c0d#diff-f783227fd53e00e4b8e090ab582c1442682b08ea10b280063a1ab4fdcea936efR154) is just incorrect.

**Comment by deivid-rodriguez** [comment]
@bronzdoc I think you handled introducing this feature. Could you have a look at this if/when you get some time?

**Comment by bronzdoc** [comment]
I will take a look @deivid-rodriguez!

**Comment by jeromedalbert** [comment]
@phene Can you confirm this still an issue?

**Comment by deivid-rodriguez** [comment]
Closing given there was no further feedback.
