### ISSUE TITLE
Conservative updating for gemspec dependencies

### ISSUE THREAD

**Issue by ayanko** [rubygems/rubygems#4098]
### Describe the problem as clearly as you can

Bundler aggressively updates dependencies when gemspec is changed.
For example when new unrelated gem is added to gemspec.

This is connected with issue https://github.com/rubygems/bundler/pull/7143 that stated as fixed.
But it's not...

### Post steps to reproduce the problem

* create Gemfile file
* create gemspec file
* add `gemspec` to `Gemfile`
* add to gemspec gem `foo1` that has as dependency `foo2`
* assume current max version of `foo2` is `1.1.6`
* run `bundle install`
* check that correct lock file is created and `foo2` is locked to `1.1.6` (max version that is allowed in `foo1`)
* assume `foo2` is released with `1.1.7`
* add to gemspec any gem `foo3`. It does not matter if it has own dependencies or not.
* run `bundle install`
* Expected:  `foo2` gem version remains the same (1.1.6)
* Actual:  `foo2` gem version UPGRADED to  newest possible (1.1.7) which is NOT expected.

Note: If you do the same without gemspec (just define dependencies as gems in Gemfile) it works as expected.

Here is simple repo that describes detailed STR and has examples for three cases
* without `gemspec` or `path` options
* with `gemspec` option
* with `path` option

https://github.com/ayanko/bundler-gemspec-issue

### Which command did you run?

```bundle install```

### What were you expecting to happen?

https://bundler.io/man/bundle-install.1.html#CONSERVATIVE-UPDATING

> When you make a change to the Gemfile(5) and then run bundle install, Bundler will update only the gems that you modified.
>
> In other words, if a gem that you did not modify worked before you called bundle install, it will continue to use the exact same versions of all dependencies as it used before the update.

### What actually happened?

Bundler updated dependencies to newest versions.

### Environment
```
Bundler       2.1.4
  Platforms   ruby, x86_64-darwin-19
Ruby          2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin19]
  Full Path   /Users/ayanko/.rbenv/versions/2.6.2/bin/ruby
  Config Dir  /Users/ayanko/.rbenv/versions/2.6.2/etc
RubyGems      3.1.4
  Gem Home    /Users/ayanko/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0
  Gem Path    /Users/ayanko/.gem/ruby/2.6.0:/Users/ayanko/.rbenv/versions/2.6.2/lib/ruby/gems/2.6.0
  User Home   /Users/ayanko
  User Path   /Users/ayanko/.gem/ruby/2.6.0
  Bin Dir     /Users/ayanko/.rbenv/versions/2.6.2/bin
Tools
  Git         2.29.2
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed
```

### Bundler Build Metadata

```
Built At          2020-01-05
Git SHA           32a4159325
Released Version  true
```

### Bundler settings

```
gem.coc
  Set for the current user (/Users/ayanko/.bundle/config): false
gem.mit
  Set for the current user (/Users/ayanko/.bundle/config): false
gem.test
  Set for the current user (/Users/ayanko/.bundle/config): "rspec"
tools/"
console
  Set for the current user (/Users/ayanko/.bundle/config): "pry"
```

**Comment by deivid-rodriguez** [comment]
Hi @ayanko, thanks for the report. It looks like a bug to me!

**Comment by ayanko** [comment]
Is it planned to be fixed?

It's pretty painful to revert manually changes each time.
Especially when you have big rails project that use a lot rails engines....

**Comment by deivid-rodriguez** [comment]
Yes. When? :man_shrugging: I'm currently stuck with other things.

@mtsmfm just pinging you so that you are aware, maybe it's an easy one for you since you fixed the previous issue. If you're just not interested or don't have the time, please ignore me and sorry for the ping :pray:.

**Comment by mtsmfm** [comment]
I'll have a look at it

**Comment by mtsmfm** [comment]
@deivid-rodriguez cc @ayanko 

I sent a PR.

https://github.com/rubygems/rubygems/pull/4293

I've confirmed the PR fixes this issue but may cause another problem.
Please review it carefully. Thanks.

**Comment by ayanko** [comment]
@mtsmfm Thx. Works for me.

**Comment by ayanko** [comment]
Thx for fix!
When I should expect new bundler release?

**Comment by deivid-rodriguez** [comment]
Today or tomorrow.

**Comment by ayanko** [comment]
👍

**Comment by ayanko** [comment]
@deivid-rodriguez release postponed?

**Comment by mtsmfm** [comment]
@ayanko already released

https://github.com/rubygems/rubygems/releases/tag/bundler-v2.2.6

**Comment by ayanko** [comment]
@mtsmfm @deivid-rodriguez Could you backport this fix to `1.17.x`?

**Comment by deivid-rodriguez** [comment]
No, sorry, 1.17 is no longer maintained.

**Comment by ayanko** [comment]
Heh. 1.7 is not maintained and 2.2 has performance and multiplatform (mac/linux) deploy issues. Kind of trap 😉
