### ISSUE TITLE
Test failures when ENV['BUNDLER_VERSION'] is set

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#4107]
The Action for installing Ruby (ruby/setup-ruby) recently started setting `ENV['BUNDLER_VERSION']`.  The handling of it may change there, but regardless, the setting of this variable caused failures in the RubyGems tests in ruby/ruby.

Maybe clearing this variable should be added to TestCase or elsewhere?

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [x] Other

Here are my current environment details:
RG Master

**Comment by deivid-rodriguez** [comment]
Yes, since rubygems tests always run against the local bundler, that makes sense.

**Comment by MSP-Greg** [comment]
I wasn't sure where/how to patch it, the failures are below:

```
test_gem.rb:341             TestGem#test_activate_bin_path_gives_proper_error_for_bundler

test_gem_dependency.rb:353  TestGemDependency#test_to_specs_respects_bundler_version

test_kernel.rb:115          TestKernel#test_gem_bundler
```

**Comment by deivid-rodriguez** [comment]
I think in the main setup hook of `Gem::TestCase` we reset some environment variables, maybe there?

**Comment by MSP-Greg** [comment]
Ok, I can do that, but not **right** now.

I have no idea about a test?  I assume there is some testing in the Bundler tests?

**Comment by deivid-rodriguez** [comment]
You mean adding a test for your change? There's no need, as long as it fixes your test failures, it should be good.
