### ISSUE TITLE
bundler show: please follow shell convention of separating standard output and standard error messages

### ISSUE THREAD

**Issue by brandondrew** [rubygems/rubygems#4111]
### Describe the problem as clearly as you can

If I ask bundler where a certain gem is installed, it is impossible to parse the output because of unexpected messages that appear, and which are not placed in `STDERR` to allow them to be ignored.  

Although from the point of view of Bundler [it is not an error, and can be ignored](https://github.com/tzinfo/tzinfo-data/issues/12#issuecomment-279554001), from the point of view of the shell, it's the sort of thing that belongs in STDERR and not STDOUT, and it cannot be easily ignored because it has been mixed in with the expected output—which is a path and _only_ a path.  Any shell function or utility intended to parse the output and use it will be broken.

### Which command did you run?

```
bundle show some_gem 2> /dev/null
```

### What actually happened?

```
💻  bundle show some_gem 2> /dev/null
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
/Users/brandon/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/some_gem-4.0.3
➲➲💻  bundle show some_gem 1> /dev/null

```

### What were you expecting to happen?

```
💻  bundle show some_gem 2> /dev/null
/Users/brandon/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0/gems/some_gem-4.0.3
➲➲💻  bundle show some_gem 1> /dev/null
The dependency tzinfo-data (>= 0) will be unused by any of the platforms Bundler is installing for. Bundler is installing for ruby but the dependency is only for x86-mingw32, x86-mswin32, x64-mingw32, java. To add those platforms to the bundle, run `bundle lock --add-platform x86-mingw32 x86-mswin32 x64-mingw32 java`.
```

There is, of course, no such thing as STDWARN in the shell.  For purposes of the shell, this is an error message and Bundler would be more usable and would be a better shell citizen if this message could be treated as one.  The message isn't part of the path, which in this case is the only thing we expect to appear in STDOUT.

**Comment by deivid-rodriguez** [comment]
Hi, thanks for the issue.

This warning has been removed from bundler 2.2.0 which will be released this week, so I'll close this ticket so this is no longer an issue.

We might be unintentionally printing other warnings to STDOUT, but let's get that reported separately if it's actually happening.
