### ISSUE TITLE
Bundler 2.2.0 installs a gem then "Could not find ... in any of the sources"

### ISSUE THREAD

**Issue by MaxLap** [rubygems/rubygems#4131]
### Describe the problem as clearly as you can

There seems to be a problem in the interaction of the configs for `gemfile` and `path`.

Right now, I `bundle install`, then use `bundle exec rake test` and I get told that `Could not find tzinfo-1.2.8 in any of the sources`.

If I scroll up, I can see that this exact version of the gem just got installed.

The specific gem is not always the same one when I try to reproduce from scratch. Sometimes its rake, tzinfo, zeitwerk, parallel.

You can see the result in the build of this github actions: 
https://github.com/MaxLap/activerecord_where_assoc/runs/1542607139?check_suite_focus=true

To clarify, the tests passed the last few weeks and I did no changes since, this is a build that runs every weekend to detect problems early. Lower ruby versions which can't use bundler 2 also still pass.

The failing gem is different if you look at rails >=6, versus rails < 6. And locally, I get a different result right now (tzinfo, but I also got rake).

### Post steps to reproduce the problem

Making sure you have bundler 2.2.0 installed, using a modern ruby (ex: 2.6)

```
git clone https://github.com/MaxLap/activerecord_where_assoc.git ar_wa
cd ar_wa
bundle config --local gemfile gemfiles/rails_5_2.gemfile
bundle config --local path vendor/bundle
bundle install
bundle exec rake test
```

Tested this on Ubuntu 16.04 with `ruby 2.6.3`, and a friend tested on Mac with `ruby 2.7.2p137` and `ruby 3.0.0dev (2020-12-10T09:55:03Z master 658b4ff609) [x86_64-darwin18]`)

### What were you expecting to happen?

The tests should run, or at last, fail because you didn't setup an entire environment for them, not just fail to find a gem.

### What actually happened?
```
$ bundle exec rake test
Could not find tzinfo-1.2.8 in any of the sources
Run `bundle install` to install missing gems.
```

## Environment

```
Bundler             2.2.0
  Platforms         ruby, x86_64-linux
Ruby                2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
  Full Path         /home/max/.rvm/rubies/ruby-2.6.3/bin/ruby
  Config Dir        /etc
RubyGems            3.0.3
  Gem Home          /home/max/.rvm/gems/ruby-2.6.3
  Gem Path          /home/max/.rvm/gems/ruby-2.6.3:/home/max/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0
  User Home         /home/max
  User Path         /home/max/.gem/ruby/2.6.0
  Bin Dir           /home/max/.rvm/gems/ruby-2.6.3/bin
Tools               
  Git               2.28.0
  RVM               1.29.4 (master)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2020-12-10
Git SHA           d3628e5019
Released Version  true
```

## Bundler settings

```
gem.test
  Set for the current user (/home/max/.bundle/config): "minitest"
gem.mit
  Set for the current user (/home/max/.bundle/config): true
gem.coc
  Set for the current user (/home/max/.bundle/config): true
build.nokogiri
  Set for the current user (/home/max/.bundle/config): "--use-system-libraries"
gemfile
  Set for your local app (/home/max/semi/gems/ar_wa/.bundle/config): "gemfiles/rails_5_2.gemfile"
  Set via BUNDLE_GEMFILE: "/home/max/semi/gems/ar_wa/gemfiles/rails_5_2.gemfile"
path
  Set for your local app (/home/max/semi/gems/ar_wa/.bundle/config): "vendor/bundle"
```

### gemfiles/rails_5_2.gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

gem "activerecord", "~> 5.2.0"
gem "sqlite3", "~> 1.3.6"

gemspec path: "../"
```

### gemfiles/rails_5_2.gemfile.lock

```
PATH
  remote: .
  specs:
    activerecord_where_assoc (1.1.1)
      activerecord (>= 4.1.0)

GEM
  remote: https://rubygems.org/
  specs:
    activemodel (5.2.4.4)
      activesupport (= 5.2.4.4)
    activerecord (5.2.4.4)
      activemodel (= 5.2.4.4)
      activesupport (= 5.2.4.4)
      arel (>= 9.0)
    activesupport (5.2.4.4)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    arel (9.0.0)
    ast (2.4.1)
    backports (3.18.2)
    binding_of_caller (0.8.0)
      debug_inspector (>= 0.0.1)
    coderay (1.1.3)
    concurrent-ruby (1.1.7)
    debug_inspector (0.0.3)
    deep-cover (1.0.0)
      deep-cover-core (= 1.0.0)
      highline
      thor (>= 0.20.3)
      with_progress
    deep-cover-core (1.0.0)
      backports (>= 3.11.0)
      binding_of_caller
      parser (>= 2.5)
      pry
      term-ansicolor
      terminal-table
    docile (1.3.2)
    highline (2.0.3)
    i18n (1.8.5)
      concurrent-ruby (~> 1.0)
    method_source (1.0.0)
    minitest (5.14.2)
    niceql (0.1.25)
    parallel (1.20.1)
    parser (2.7.2.0)
      ast (~> 2.4.1)
    powerpack (0.1.3)
    pry (0.13.1)
      coderay (~> 1.1)
      method_source (~> 1.0)
    rainbow (3.0.0)
    rake (13.0.1)
    rubocop (0.54.0)
      parallel (~> 1.10)
      parser (>= 2.5)
      powerpack (~> 0.1)
      rainbow (>= 2.2.2, < 4.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (~> 1.0, >= 1.0.1)
    ruby-progressbar (1.10.1)
    simplecov (0.20.0)
      docile (~> 1.1)
      simplecov-html (~> 0.11)
      simplecov_json_formatter (~> 0.1)
    simplecov-html (0.12.3)
    simplecov_json_formatter (0.1.2)
    sqlite3 (1.3.13)
    sync (0.5.0)
    term-ansicolor (1.7.1)
      tins (~> 1.0)
    terminal-table (2.0.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    thor (1.0.1)
    thread_safe (0.3.6)
    tins (1.26.0)
      sync
    tzinfo (1.2.8)
      thread_safe (~> 0.1)
    unicode-display_width (1.7.0)
    with_progress (1.0.1)
      ruby-progressbar (~> 1.4)

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  activerecord (~> 5.2.0)
  activerecord_where_assoc!
  bundler (>= 1.15)
  deep-cover
  minitest (~> 5.0)
  niceql (>= 0.1.23)
  pry
  rake (>= 10.0)
  rubocop (= 0.54.0)
  simplecov
  sqlite3 (~> 1.3.6)

BUNDLED WITH
   2.2.0
```

### activerecord_where_assoc.gemspec

```ruby
# frozen_string_literal: true

require_relative "lib/active_record_where_assoc/version"

Gem::Specification.new do |spec|
  spec.name          = "activerecord_where_assoc"
  spec.version       = ActiveRecordWhereAssoc::VERSION
  spec.authors       = ["Maxime Handfield Lapointe"]
  spec.email         = ["maxhlap@gmail.com"]

  spec.summary       = "Make ActiveRecord do conditions on your associations"
  spec.description   = "Adds various #where_assoc_* methods to ActiveRecord to make it easy to do correct" \
                       " conditions on the associations of the model being queried."
  spec.homepage      = "https://github.com/MaxLap/activerecord_where_assoc"
  spec.license       = "MIT"

  lib_files = `git ls-files -z lib`.split("\x0")
  spec.files = [*lib_files, "CHANGELOG.md", "EXAMPLES.md", "LICENSE.txt", "README.md"]

  spec.add_dependency "activerecord", ">= 4.1.0"

  spec.add_development_dependency "bundler", ">= 1.15"
  spec.add_development_dependency "minitest", "~> 5.0"
  spec.add_development_dependency "pry"
  spec.add_development_dependency "rake", ">= 10.0"

  spec.add_development_dependency "deep-cover"
  spec.add_development_dependency "rubocop", "0.54.0"
  spec.add_development_dependency "simplecov"

  # Useful for the examples
  spec.add_development_dependency "niceql", ">= 0.1.23"

  # Normally, testing with sqlite3 is good enough
  spec.add_development_dependency "sqlite3"

  # Travis-CI takes care of the other ones
  # Using conditions because someone might not even be able to install the gems
  spec.add_development_dependency "mysql2", "~> 0.4.0" if ENV["CI"] || ENV["ALL_DB"] || ENV["DB"] == "mysql"
  spec.add_development_dependency "pg", "< 1.0.0" if ENV["CI"] || ENV["ALL_DB"] || ["pg", "postgres", "postgresql"].include?(ENV["DB"])
end
```

**Comment by simi** [comment]
@MaxLap hello. I tried to follow your script to reproduce this locally, but without luck. Can you reproduce that constantly?

**Comment by MaxLap** [comment]
Yes, everytime, unless I remove one of the two config that are set in the code. I just delete the directory and run the whole thing and get the problem.

I wonder if there is a problem where it is actually looking inside a different directory for the gems. Maybe try a different ruby which you wouldn't have any gems installed?

**Comment by simi** [comment]
@MaxLap I have tried to uninstall all gems on Ruby 2.6. Still not able to reproduce. :thinking:

**Comment by MaxLap** [comment]
Really can't say... I use rvm, my friend on Mac uses rbenv... Other than saying "Are you sure you are using bundle 2.2.0 and have no other versions installed, I don't know. 

Hopefully someone else can manage to reproduce?

**Comment by marcandre** [comment]
I get "Could not find rake-13.0.1 in any of the sources", both in `ruby 2.7.2p137` and `ruby 3.0.0dev (2020-12-10T09:55:03Z master 658b4ff609) [x86_64-darwin18]`. Both are pretty fresh installs (just switched to rbenv) and all gems had to be installed (including rake-13.0.1). Sorry I don't have time to investigate this weekend

**Comment by simi** [comment]
I'm using ruby-install + chruby. I'll take a additional look.

**Comment by deivid-rodriguez** [comment]
Hei! I looked at this and I'm completely lost since I can't seem to find a way to repro locally :(

Some feedback I have is that the `gemfile` configuration setting is know to have issues. As a matter of fact, I'm really surprised it's working for you. The reason is that the location of configuration is inferred from the Gemfile, so inferring the location of the Gemfile from the configuration can lead to chicken and egg issues. There's this issue about it: https://github.com/rubygems/rubygems/issues/3363, and an old PR to fix it that I should rebase at some point: https://github.com/rubygems/rubygems/pull/3963.

I recommend that you switch those `bundle config` lines to specify them through `env:`

```yaml
     env:
       BUNDLE_GEMFILE: ${{ matrix.gemfile }}
       BUNDLE_PATH: vendor/bundle
```

And things should work fine.

In any case, I'm happy to have a closer look if I can get a docker repro or something.

**Comment by MaxLap** [comment]
I wonder if you guys have some default bundler config in your home directory which are changing the behavior. I'm not familiar with Docker, so I'm sorry but I don't feel like investing hours into it just to provide a bug report.

About using the variables, indeed, using 
```
export BUNDLE_GEMFILE=gemfiles/rails_5_2.gemfile
export BUNDLE_PATH=vendor/bundle
```
makes the tests pass locally, and I could setup my github actions to use those instead.

I just noticed something:

Bundler 2.1 using env vars -> Gems are installed in gemfiles/vendor/bundle
Bundler 2.1 using configs -> Gems are installed in gemfiles/vendor/bundle
Bundler 2.2 using env vars -> Gems are installed in gemfiles/vendor/bundle
Bundler 2.2 using configs -> Gems are installed in vendor/bundle

Personally, the placing them in `gemfiles/` was confusing to me when I was trying to setup caching, I didn't notice that being mentioned in the documentation.

**Comment by deivid-rodriguez** [comment]
Yes, it's super confusing and it's a behaviour I'm aiming to change, this is the bug & pull request I linked to before.

**Comment by deivid-rodriguez** [comment]
Actually, it's not the exact same issue but a similar confusion. Base location for things given relatively should be inferred from the current directory, not from the directory of the current Gemfile.

**Comment by deivid-rodriguez** [comment]
I can repro now, will keep you posted!

**Comment by deivid-rodriguez** [comment]
I created https://github.com/rubygems/rubygems/pull/4140 to fix this regression.
