### ISSUE TITLE
I can't create new rails website

### ISSUE THREAD

**Issue by velisahin** [rubygems/rubygems#4136]
I'm having a problem or would like to suggest a feature.

I wanna create new rails website with `rails new myblog` but i always see error

`Fetching source index from https://rubygems.org/

Retrying fetcher due to error (2/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rubygems.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Retrying fetcher due to error (3/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rubygems.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Retrying fetcher due to error (4/4): Bundler::Fetcher::CertificateFailureError Could not verify the SSL certificate for https://rubygems.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for verification. For information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect without using SSL, edit your Gemfile sources and change 'https' to 'http'.
Could not verify the SSL certificate for https://rubygems.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most
likely your system doesn't have the CA certificates needed for verification. For
information about OpenSSL certificates, see http://bit.ly/ruby-ssl. To connect
without using SSL, edit your Gemfile sources and change 'https' to 'http'.`

and ı wanted to update gems but ı couldn't be successful. 

ı did that  `gem install rails` and `gem update rails`

ı saw a error again.

that error

`ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)`

how ı solve a problem? 

My current problem is _________

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
PASTE HERE
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by velisahin** [comment]
Please help me

**Comment by deivid-rodriguez** [comment]
You could run `gem update --system` and try again see if that fixes things for you.

**Comment by velisahin** [comment]
> You could run `gem update --system` and try again see if that fixes things for you.

I run that  but ı saw the error again

`ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=error: certificate verify failed (https://api.rubygems.org/specs.4.8.gz)`

**Comment by simi** [comment]
@velisahin have you seen https://guides.rubygems.org/ssl-certificate-update/?

**Comment by deivid-rodriguez** [comment]
Closing since we got no further feedback here.

**Comment by rbjarnason** [comment]
@deivid-rodriguez Not the first time that I have this problem happen at random and now spent hours not getting it to work until I found this. https://medium.com/@chr.nonato/retrying-fetcher-due-to-error-bundler-httperror-558315f45612 and https://stackoverflow.com/questions/49800432/gem-cannot-access-rubygems-org/50349235#50349235

So as hard it is to believe then just adding the below to my /etc/hosts makes everything work and no more SSL errors!
151.101.192.70  rubygems.org
