### ISSUE TITLE
Force user installation under a specific path

### ISSUE THREAD

**Issue by pyrr** [rubygems/rubygems#4148]
Hello. I would like to have everything which is locally installed be installed under a directory I specify. Is there any way I can do this ?
For example in ${HOME}/ruby

Allow me to expand a little on this.
By default "gem install" installs gems locally so I can't use: "gem install --install-dir". Even after configuring the GEM_HOME and GEM_PATH environment variables there is are still files being put into ${HOME}/.gem . I can see the output of "gem environment" but it's not entirely clear how I can change the other varibles.

**Comment by simi** [comment]
Hello @pyrr. Can you share which files are still in `~/.gem` after setting GEM_HOME and GEM_PATH?

You can see source of various paths used (as you mentioned) using `gem env`. Unfortunately there is no clear documentation on all env. variables useful for this.

Source of `gem env` [command](https://github.com/rubygems/rubygems/blob/0e2a52c943749fa5f717a8aa1b95937bd3ba2ed0/lib/rubygems/commands/environment_command.rb#L102-L156) could help you to trace how those paths are found. You can try to change `GEM_SPEC_CACHE` and also `XDG_*` [ones](https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html#variables) [used](https://github.com/rubygems/rubygems/blob/4a76ff8029effb6172d8c0327565d9d2b7aa50ff/lib/rubygems/defaults.rb#L128).

**Comment by simi** [comment]
```bash
$ rm -rf ~/.gem
$ GEM_HOME=/home/retro/.gem3 GEM_PATH=/home/retro/.gem3 GEM_SPEC_CACHE=/home/retro/.gem3 gem install ABO
$ stat ~/.gem
stat: cannot stat '/home/retro/.gem': No such file or directory #=> actually success
```

**Comment by pyrr** [comment]
Here is the command I executed.
`GEM_HOME=/home/pun/dl GEM_PATH=/home/pun/dl GEM_SPEC_CACHE=/home/pun/dl gem install solargraph`
And here's what's inside ${HOME}/.gem
http://sprunge.us/tyFSDm
and in /home/pun/dl
http://sprunge.us/ehWOEe

**Comment by simi** [comment]
@pyrr running the same command as you did will not affect my `~/.gem` directory. Can you reproduce that in some isolated environment?

For example using docker:

```
$ docker run -it --rm ruby:2.7.2 /bin/bash
root@aafc0ec9abda:/# GEM_HOME=/tmp/.gem GEM_PATH=/tmp/.gem GEM_SPEC_CACHE=/tmp/.gem gem install solargrap
root@aafc0ec9abda:/# stat ~/.gem
stat: cannot stat '/root/.gem': No such file or directory
```

Nothing is installed in ~/.gem (or any other gem path listed in `gem env`).

**Comment by pyrr** [comment]
You're right.
It's probably this isn't it ?
https://github.com/archlinux/svntogit-packages/blob/packages/rubygems/trunk/gemrc

**Comment by pyrr** [comment]
Ok so I removed the /etc/gemrc file. I still cannot install locally.

`
#!/bin/bash

ge() {
        local NIX_GEM="/home/pun/.nix/gem"
        mkdir -p "$NIX_GEM"
        local GEM_HOME="$NIX_GEM"
        local GEM_PATH="$NIX_GEM"
        local GEM_SPEC_CACHE="$NIX_GEM"
        OPT=$1
        shift
        case $OPT in
        install)
                echo $GEM_HOME
                echo $GEM_PATH
                echo $GEM_SPEC_CACHE
                exec /usr/bin/gem install "$@" --no-document --no-user-install
                ;;
        *)
                exec /usr/bin/gem "$@"
                ;;

        esac
}
ge "$@"
`
This is in path before the actual gem binary.
I get 
`
gem install solargraph
/home/pun/.nix/gem
/home/pun/.nix/gem
/home/pun/.nix/gem
Fetching backport-1.1.2.gem
Fetching bundler-2.2.2.gem
Fetching e2mmap-0.1.0.gem
Fetching kramdown-2.3.0.gem
Fetching kramdown-parser-gfm-1.1.0.gem
Fetching jaro_winkler-1.5.4.gem
Fetching ast-2.4.1.gem
Fetching parser-2.7.2.0.gem
Fetching mini_portile2-2.4.0.gem
Fetching reverse_markdown-2.0.0.gem
Fetching parallel-1.20.1.gem
Fetching rainbow-3.0.0.gem
Fetching regexp_parser-2.0.0.gem
Fetching rubocop-ast-1.3.0.gem
Fetching ruby-progressbar-1.10.1.gem
Fetching nokogiri-1.10.10.gem
Fetching unicode-display_width-1.7.0.gem
Fetching solargraph-0.40.0.gem
Fetching rubocop-1.6.1.gem
Fetching thor-1.0.1.gem
Fetching tilt-2.0.10.gem
Fetching yard-0.9.25.gem
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/lib/ruby/gems/2.7.0 directory.

`

**Comment by deivid-rodriguez** [comment]
Can you rerun with `--backtrace` and `--verbose` flags?

**Comment by pyrr** [comment]
Ran: 
`gem install solargraph --backtrace --verbose
`
http://sprunge.us/FFPKHK + 
```
ERROR:  While executing gem ... (Gem::FilePermissionError)
    You don't have write permissions for the /usr/lib/ruby/gems/2.7.0 directory.
        /usr/lib/ruby/2.7.0/rubygems/installer.rb:735:in `verify_gem_home'
        /usr/lib/ruby/2.7.0/rubygems/installer.rb:908:in `pre_install_checks'
        /usr/lib/ruby/2.7.0/rubygems/installer.rb:301:in `install'
        /usr/lib/ruby/2.7.0/rubygems/resolver/specification.rb:93:in `install'
        /usr/lib/ruby/2.7.0/rubygems/request_set.rb:195:in `block in install'
        /usr/lib/ruby/2.7.0/rubygems/request_set.rb:183:in `each'
        /usr/lib/ruby/2.7.0/rubygems/request_set.rb:183:in `install'
        /usr/lib/ruby/2.7.0/rubygems/commands/install_command.rb:208:in `install_gem'
        /usr/lib/ruby/2.7.0/rubygems/commands/install_command.rb:224:in `block in install_gems'
        /usr/lib/ruby/2.7.0/rubygems/commands/install_command.rb:217:in `each'
        /usr/lib/ruby/2.7.0/rubygems/commands/install_command.rb:217:in `install_gems'
        /usr/lib/ruby/2.7.0/rubygems/commands/install_command.rb:165:in `execute'
        /usr/lib/ruby/2.7.0/rubygems/command.rb:325:in `invoke_with_build_args'
        /usr/lib/ruby/2.7.0/rubygems/command_manager.rb:178:in `process_args'
        /usr/lib/ruby/2.7.0/rubygems/command_manager.rb:148:in `run'
        /usr/lib/ruby/2.7.0/rubygems/gem_runner.rb:59:in `run'
        /usr/bin/gem:15:in `<main>'

```

**Comment by deivid-rodriguez** [comment]
Sorry, but don't you need to export environment variables so that they are inherited by `exec`? :thinking:

**Comment by pyrr** [comment]
You're right. Thank you. I was honestly unsure. Thanks for all the help.

**Comment by deivid-rodriguez** [comment]
No problem @pyrr, I'm glad we sorted it out :)
