### ISSUE TITLE
Install Gem As It Was At Particular Point in Time

### ISSUE THREAD

**Issue by Wardrop** [rubygems/rubygems#415]
I know rubygem's allow you to install a particular version of a gem, but this has a major limitation, which is that normally the latest versions of the gems dependancies are installed, so it doesn't effectively recreate the conditions that would have been true when that version of gem was actually published.

Being able to install a gem as it would have been at a particular point in time would be very handy when dealing with bugs introduced in more recent versions of dependant gems. It'd be handy for troubleshooting, and handy for working around the introduced bug until it's fixed.

I don't imagine this would be a difficult thing to implement. Every gem has a date associated with it, so it'd be easy enough to filter gems based on that time.

Thoughts?

**Comment by djberg96** [comment]
I see no reason to leave this open.
