### ISSUE TITLE
/Library/Ruby/Site/2.6.0/rubygems.rb:281:in `find_spec_for_exe':

### ISSUE THREAD

**Issue by kirtigiripunje** [rubygems/rubygems#4160]
I need to uninstall ruby from Mac but I am not able to do that so please help me for same I got following error like

/Library/Ruby/Site/2.6.0/rubygems.rb:281:in `find_spec_for_exe': can't find gem twine (>= 0.a) with executable twine (Gem::GemNotFoundException)
	from /Library/Ruby/Site/2.6.0/rubygems.rb:300:in `activate_bin_path'
	from /usr/local/bin/twine:23:in `<main>'

**Comment by deivid-rodriguez** [comment]
@kirtigiripunje Could you at least say the command you're running? It's very hard to help you with such a poor bug report.

**Comment by bronzdoc** [comment]
Closing due to lack of response, but will reopen if you provide steps to reproduce @kirtigiripunje. Thanks
