### ISSUE TITLE
Bundler 2.2.1, multiple platforms and bundle install --frozen

### ISSUE THREAD

**Issue by knu** [rubygems/rubygems#4166]
### Describe the problem as clearly as you can

Bundler 2.2+ started to output platform-specific gem entries to Gemfile.lock, and it seems `bundle install --frozen` installs gems for the specified platform regardless of the running platform, if the lock file does not include entries for their variants appropriate for the running platform.

We have a project targeted to x86_64 Linux where the majority of developers are on macOS.  We have been sharing a single Gemfile.lock in the repository for both development and deployment.  Here's our development workflow that may suffer from the new behavior:

1. A developer adds a new gem or upgrades an existing gem on macOS and creates a pull request.  The gem has a binary variant for macOS, thus Gemfile.lock includes an entry that goes `some-gem (x.y.z-universal-darwin)` and none for `x86_86-linux`.
2. CI and deployment on Linux fail because Gems are installed with `bundle install --frozen` for strict integrity there.  The command runs and exits successfully, but the `some-gem` installed by Bundler is for macOS (`universal-darwin`), so the test suite and application fail to load the gem and do not work.

Disabling the frozen option may be an option (in exchange for a strict integrity check), but still, we cannot easily maintain a universal Gemfile.lock across platforms.  This may be another story, though.

### Post steps to reproduce the problem

1. Create a Gemfile.lock containing a binary gem entry targeted for a specific platform, run `bundle` there, and check in Gemfile.lock.
2. Check out Gemfile and Gemfile.lock on another platform and run `bundle install --frozen`.
3. See from the output that it has only installed gems for the first platform.  Or run `bundle exec gem list`.

### Which command did you run?

`bundle install --frozen` (`bundle config set --local frozen true && bundle`)

### What were you expecting to happen?

It should refuse to install gems for other (incompatible) platforms, and exit with a non-zero status code.

### What actually happened?

It installed alien binary gems that wouldn't load or work, without an error.

### If not included with the output of your command, run `bundle env` and paste the output below

```
Bundler       2.2.1
  Platforms   ruby, x86_64-darwin
Ruby          2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin]
  Full Path   /Users/knu/arch/darwin/mach/x86_64/rbenv/versions/2.6.6/bin/ruby
  Config Dir  /Users/knu/arch/darwin/mach/x86_64/rbenv/versions/2.6.6/etc
RubyGems      3.1.2
  Gem Home    /Users/knu/arch/darwin/mach/x86_64/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0
  Gem Path    /Users/knu/.gem/ruby/2.6.0:/Users/knu/arch/darwin/mach/x86_64/rbenv/versions/2.6.6/lib/ruby/gems/2.6.0
  User Home   /Users/knu
  User Path   /Users/knu/.gem/ruby/2.6.0
  Bin Dir     /Users/knu/arch/darwin/mach/x86_64/rbenv/versions/2.6.6/bin
Tools
  Git         2.29.2
  RVM         not installed
  rbenv       rbenv 1.1.2-40-g62d7798
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2020-12-14
Git SHA           b98d6b2035
Released Version  true
```

(snipped)

**Comment by deivid-rodriguez** [comment]
Hello @knu! :wave: :wave: 

Your expectation is the same as mine, and that's how I thought bundler behaved, actually. I'll try to fix it and throw an error in this situation :+1:.

Something I didn't understand though is this:

> Disabling the frozen option may be an option (in exchange for a strict integrity check), but still, we cannot easily maintain a universal Gemfile.lock across platforms. This may be another story, though.

Does this mean that running `bundle lock --add-platform x86_64-linux` and committing the resulting lock file is not an option for you?

**Comment by knu** [comment]
Great, and thanks for the nice piece of information!  I’ll see if it works for our workflow and report back.

**Comment by deivid-rodriguez** [comment]
@knu I still need to add a spec, but #4172 should fix this!

**Comment by knu** [comment]
@deivid-rodriguez Thanks for working hard on this!

I tried `bundle lock --add-platform` and it almost did the trick, and I got a relatively minor issue.

I ran `bundle add libv8 && bundle lock --add-flatform x86_64-linux universal-darwin x86_64-darwin`, and I got the following entries for the [libv8](https://rubygems.org/gems/libv8/versions) gem:

```
libv8 (8.4.255.0-universal-darwin-15)
libv8 (8.4.255.0-x86_64-darwin-15)
libv8 (8.4.255.0-x86_64-linux)
```

So, bundler seems to only pick the least matching version (15) when there are binary gems up to *-darwin-20.
Is this expected, I mean, would it be too much to include all matching platforms?  As for the said project, I can live with this by adding necessary versions because it is developed and used by a limited number of people/platforms, but for a product used by various platforms using this kind of gem, it could be a burden to keep the platform list up-to-date by hand.

Thanks!

**Comment by deivid-rodriguez** [comment]
Hi @knu! That seems unexpected, right? Maybe yet another bug :rofl:. Oh god. I'll have a look.

**Comment by deivid-rodriguez** [comment]
Hi @knu!

I created #4179 that I think should fix your issue. Now the lockfile generated for you should look like this:

```
GEM
  remote: https://rubygems.org/
  specs:
    libv8 (8.4.255.0-universal-darwin-15)
    libv8 (8.4.255.0-universal-darwin-16)
    libv8 (8.4.255.0-universal-darwin-17)
    libv8 (8.4.255.0-universal-darwin-18)
    libv8 (8.4.255.0-universal-darwin-19)
    libv8 (8.4.255.0-universal-darwin-20)
    libv8 (8.4.255.0-x86_64-darwin-15)
    libv8 (8.4.255.0-x86_64-darwin-16)
    libv8 (8.4.255.0-x86_64-darwin-17)
    libv8 (8.4.255.0-x86_64-darwin-18)
    libv8 (8.4.255.0-x86_64-darwin-19)
    libv8 (8.4.255.0-x86_64-darwin-20)
    libv8 (8.4.255.0-x86_64-linux)

PLATFORMS
  universal-darwin
  x86_64-darwin
  x86_64-linux

DEPENDENCIES
  libv8

BUNDLED WITH
   2.3.0.dev
```

And when each developer uses it on here specific platform, they should get no source control changes whatsoever, and the best variant for their platform should get installed.

Note that technically unless you lock all the specific platforms that you want to support, you're still subject to eventually running into the same issue that led us to locking the specific platform in the first place, namely, different variants of the same gem having different dependencies.

However, I concluded that:

* If you have a working lockfile, you're most likely not running into that issue, so keeping the previous behaviour seemed the best option to me.

* While I have seen examples of the RUBY variant having different dependencies from the platform specific variants, I have never seen different variants of the same platform having different dependencies. That means most people won't need to keep the whole list of specific platforms in their lockfile, and you should be just fine with `x86_64-linux`, `universal-darwin`, `x86_64-darwin`.

If you're able to try the PR or have any feedback let me know!

**Comment by knu** [comment]
@deivid-rodriguez Unfortunately I have no idea how to test 2.3.0.dev, but I totally agree with your points and the result seems to be what I exactly wanted.  Thanks for all the hard work!

**Comment by deivid-rodriguez** [comment]
@knu You can clone the repository, and running `ruby setup.rb` from the root of the repo will install the latest rubygems & bundler. To "undo" the change after your tests, you can run `gem update --system <previous_rubygems_version>` to revert everything back to the previous state.
