### ISSUE TITLE
[Regression] bundle 2.2.x fails to install dependencies from Git on JRuby + Windows

### ISSUE THREAD

**Issue by slonopotamus** [rubygems/rubygems#4195]
### Describe the problem as clearly as you can

If user tries to `bundle install` on a Gemfile that has Git-repository dependency, bundler fails with `The source does not contain any versions of '<dependency>'`:

### Steps to reproduce the problem

Assuming that you use Windows, have JRuby as default Ruby and have Bundler 2.2.x (2.2.3 still has this bug):

1. Create an empty project with the following `Gemfile`:

```
source "https://rubygems.org"

gem 'prawn-table', git: 'https://github.com/prawnpdf/prawn-table', ref: '515f2db294866a343b05d15f94e5fb417a32f6ff'
```

2. Run `bundle install`

### Expected

Bundler happily installs dependencies

### Actual

```
Fetching https://github.com/prawnpdf/prawn-table
Could not find gem 'prawn-table' in https://github.com/prawnpdf/prawn-table (at
Fetching gem metadata from https://rubygems.org/
515f2db@515f2db).
The source does not contain any versions of 'prawn-table'
Error: Process completed with exit code 1.
```

Bug is **NOT** present in Bundler 2.1.4.

### Additional notes

For your convenience, I've created an minimal testcase repository: https://github.com/slonopotamus/bundler-git-dep

Also, here's GitHub Actions workflow run that reproduces described scenario: https://github.com/slonopotamus/bundler-git-dep/runs/1605766634?check_suite_focus=true

You can clearly see that only Windows+JRuby is affected, other platforms do not exhibit this bug.

**Comment by deivid-rodriguez** [comment]
Thanks for the report and the repro! I made a few experiments and it seems #4196 fixes this. I will make sure to add some coverage before merging.

**Comment by slonopotamus** [comment]
BTW, error message `Could not find gem 'prawn-table' in https://github.com/prawnpdf/prawn-table (at` looks like it is missing some letters at the end?

**Comment by deivid-rodriguez** [comment]
Yeah, I've seen that issue in the past. It's a multithread output sync issue specific to Windows, but I don't know the root cause. I thought it didn't happen when using a single thread, but it sounds like it can happen too with a single thread.
