### ISSUE TITLE
Error in installing metasplate in Termux 

### ISSUE THREAD

**Issue by mosab3482** [rubygems/rubygems#4214]
dpkg: error processing package metasploit (--configure):                                             installed metasploit package post-installation script subprocess returned error exit status 1      Errors were encountered while processing:          metasploit                                       E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)                  Reading package lists... Done
Building dependency tree                          Reading state information... Done                 unstable-repo is already the newest version (4.1).0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.                                      1 not fully installed or removed.                 After this operation, 0 B of additional disk space will be used.

**Comment by mosab3482** [comment]
curl: (56) OpenSSL SSL_read: Software caused connection abort, errno 103
dpkg: error processing package metasploit (--configure):
 installed metasploit package post-installation script subprocess returned error exit status 56
Errors were encountered while processing:          metasploit
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
Reading package lists... Done                     Building dependency tree                          Reading state information... Done
metasploit is already the newest version (6.0.20-2).                                                0 upgraded, 0 newly installed, 0 to remove and 0 not upgraded.                                      1 not fully installed or removed.                 After this operation, 0 B of additional disk space will be used.

**Comment by deivid-rodriguez** [comment]
Sorry @mosab3482 but from the information you have given I'm unable to spot any problems in rubygems or bundler. Feel free to follow up if you can offer more information :+1:.

**Comment by mosab3482** [comment]
Welcome to Termux!

Wiki:            https://wiki.termux.com
Community forum: https://termux.com/community
Gitter chat:     https://gitter.im/termux/termux
IRC channel:     #termux on freenode

Working with packages:

 * Search packages:   pkg search <query>
 * Install a package: pkg install <package>
 * Upgrade packages:  pkg upgrade

Subscribing to additional repositories:

 * Root:     pkg install root-repo
 * Unstable: pkg install unstable-repo
 * X11:      pkg install x11-repo

Report issues at https://termux.com/issues

$ ls
IPGeoLocation        lazymux.conf
Lazymux              metasploit.sh
SpamCal              postgresql_ctl.sh
Termux-Kali-apktool  start-kali.sh
database.yml         wifiphisher
kali-binds           zeroeye
kali-fs
$ ./start-kali.sh
./start-kali.sh: line 30: exec: proot: not found
$ start-kali.sh
start-kali.sh: command not found
$ bash start-kali.s
bash: start-kali.s: No such file or directory
$ cd start-kali.s
bash: cd: start-kali.s: No such file or directory
$ ./start-kali.sh
./start-kali.sh: line 30: exec: proot: not found
$ pkg install wget openssl-tool proot -y && hash -r && wget https://raw.githubusercontent.com/EXALAB/AnLinux-Resources/master/Scripts/Installer/Kali/kali.sh && bash kali.sh
Checking availability of current mirror: bad
Testing the available mirrors:
[*] https://termux.org/packages: bad
[*] https://termux.mentality.rip/termux-packages-24: ok
[*] https://grimler.se/termux-packages-24: ok
[*] https://main.termux-mirror.ml: ok
Picking mirror: https://main.termux-mirror.ml
Ign:1 https://main.termux-mirror.ml stable InRelease
Ign:2 https://dl.bintray.com/grimler/game-packages-24 games InRelease
Ign:3 https://dl.bintray.com/grimler/science-packages-24 science InRelease
Ign:4 https://dl.bintray.com/xeffyr/unstable-packages unstable InRelease
Get:5 https://main.termux-mirror.ml stable Release [8255 B]
Get:6 https://dl.bintray.com/grimler/game-packages-24 games Release [5344 B]
Get:7 https://dl.bintray.com/grimler/science-packages-24 science Release [6191 B]
Get:8 https://main.termux-mirror.ml stable Release.gpg [821 B]
Get:9 https://dl.bintray.com/xeffyr/unstable-packages unstable Release [6065 B]
Get:12 https://main.termux-mirror.ml stable/main arm Packages [124 kB]
Fetched 151 kB in 2min 10s (1156 B/s)
Reading package lists... Done
Building dependency tree
Reading state information... Done
All packages are up to date.
Reading package lists... Done
Building dependency tree
Reading state information... Done
wget is already the newest version (1.20.3-3).
The following NEW packages will be installed:
  libtalloc openssl-tool proot
0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.
1 not fully installed or removed.
Need to get 296 kB of archives.
After this operation, 877 kB of additional disk space will be used.
Get:1 https://main.termux-mirror.ml stable/main arm libtalloc arm 2.3.1 [33.9 kB]
Get:2 https://main.termux-mirror.ml stable/main arm openssl-tool arm 1.1.1i [185 kB]
Get:3 https://main.termux-mirror.ml stable/main arm proot arm 5.1.107-35 [77.3 kB]
Fetched 296 kB in 3s (96.8 kB/s)
Selecting previously unselected package libtalloc.
(Reading database ... 21654 files and directories currently installed.)
Preparing to unpack .../libtalloc_2.3.1_arm.deb ...
Unpacking libtalloc (2.3.1) ...
Selecting previously unselected package openssl-tool.
Preparing to unpack .../openssl-tool_1.1.1i_arm.deb ...
Unpacking openssl-tool (1.1.1i) ...
Selecting previously unselected package proot.
Preparing to unpack .../proot_5.1.107-35_arm.deb ...
Unpacking proot (5.1.107-35) ...
Setting up openssl-tool (1.1.1i) ...
Setting up metasploit (6.0.20-2) ...

======= TERMUX METASPLOIT DISCLAIMER =======

Metasploit Framework and its dependencies
are being sideloaded.  That solution makes
package potentially unstable.  We do not
guarantee compatibility of installed Ruby
modules with our Ruby interpreter version
and general compatibility with Android OS.

It is highly recommended to have a stable
Internet connection and clean Termux
environment with up-to-date packages before
installing Metasploit.

Package is intended to be used by
experienced users.  Do not ask Termux
developers about how to use Metasploit, we
won't do so and generally are not helping
anyone with topics related to hacking.

Installation will be started in 10 seconds,
thanks for attention.

============================================

[*] Downloading Metasploit Framework...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:-  0     0    0     0    0     0      0      0 --:-  0     0    0     0    0     0      0      0 --:-  0     0    0     0    0     0      0      0 --:-  0     0    0     0    0     0      0      0 --:-  0     0    0     0    0     0      0      0 --:-  0     0    0     0    0     0      0      0 --:-100   135  100   135    0     0     22      0  0:00:06  0:00:06 --:--:--    33
  0     0    0     0    0     0      0      0 --:-  0     0    0     0    0     0      0      0 --:-  0     0    0     0    0     0      0      0 --:-  0     0    0     0    0     0      0      0 --:-  0     0    0     0    0     0      0      0 --:-  0 62.6M    0  110k    0     0   9204      0  1:5  0 62.6M    0  220k    0     0  17427      0  1:0  0 62.6M    0  319k    0     0  23247      0  0:4  0 62.6M    0  391k    0     0  25925      0  0:4  0 62.6M    0  391k    0     0  24344      0  0:4  0 62.6M    0  391k    0     0  22948      0  0:4  0 62.6M    0  391k    0     0  21703      0  0:5  0 62.6M    0  391k    0     0  20586      0  0:5  0 62.6M    0  391k    0     0  19578      0  0:5  0 62.6M    0  391k    0     0  18662      0  0:5  0 62.6M    0  391k    0     0  17830      0  1:0  0 62.6M    0  391k    0     0  17070      0  1:0  0 62.6M    0  391k    0     0  16371      0  1:0  0 62.6M    0  391k    0     0  15727      0  1:0  0 62.6M    0  391k    0     0  15132      0  1:1  0 62.6M    0  391k    0     0  14581      0  1:1  0 62.6M    0  391k    0     0  14068      0  1:1  0 62.6M    0  391k    0     0  13590      0  1:2  0 62.6M    0  391k    0     0  13144      0  1:2  0 62.6M    0  391k    0     0  12725      0  1:2  0 62.6M    0  391k    0     0  12333      0  1:2  0 62.6M    0  391k    0     0  11963      0  1:3  0 62.6M    0  391k    0     0  11615      0  1:3  0 62.6M    0  391k    0     0  11288      0  1:3  0 62.6M    0  391k    0     0  11224      0  1:37:34  0:00:35  1:36:59     0
curl: (56) OpenSSL SSL_read: Software caused connection abort, errno 103
dpkg: error processing package metasploit (--configure):
 installed metasploit package post-installation script subprocess returned error exit status 56
Setting up libtalloc (2.3.1) ...
Setting up proot (5.1.107-35) ...
Errors were encountered while processing:
 metasploit
E: Sub-process /data/data/com.termux/files/usr/bin/dpkg returned an error code (1)
$
