### ISSUE TITLE
Git checkout fails when using older versions of git

### ISSUE THREAD

**Issue by jmartin-r7** [rubygems/rubygems#4229]
Version 2.2.4 release fails git checkout if system has an older version of `git`.   This looks to have been introduced by #4196.

```
$ bundle install
Fetching gem metadata from https://rubygems.org/.........
Unknown option: -C
usage: git [--version] [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           [-c name=value] [--help]
           <command> [<args>]
```

### Post steps to reproduce the problem

install a git version prior to `1.8.5`

In this case:
`git version 1.7.10.4`

setup a project with following spec and gemfile
foo.gemspec:
```
# frozen_string_literal: true

require_relative "lib/foo/version"

Gem::Specification.new do |spec|
  spec.name          = "foo"
  spec.version       = Foo::VERSION
  spec.authors       = ["Omnibus Packager"]
  spec.email         = ["packager@example.com"]

  spec.summary       = "test"
  spec.description   = "test"
  spec.homepage      = "https://test.com"
  spec.license       = "MIT"
  spec.required_ruby_version = Gem::Requirement.new(">= 2.3.0")

  # Specify which files should be added to the gem when it is released.
  # The `git ls-files -z` loads the files in the RubyGem that have been added into git.
  spec.files = Dir.chdir(File.expand_path(__dir__)) do
    `git ls-files -z`.split("\x0").reject { |f| f.match(%r{\A(?:test|spec|features)/}) }
  end
  spec.bindir        = "exe"
  spec.executables   = spec.files.grep(%r{\Aexe/}) { |f| File.basename(f) }
  spec.require_paths = ["lib"]

  # Uncomment to register a new dependency of your gem
  # spec.add_dependency "example-gem", "~> 1.0"

  # For more information and examples about making a new gem, checkout our
  # guide at: https://bundler.io/guides/creating_gem.html
end
```

Gemfile:
```
# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in foo.gemspec
gemspec

gem "rake", "~> 13.0"
gem "omnibus", git: 'https://github.com/chef/omnibus', branch: 'v3.2.0'
```

Attempt to `bundle install`

### Which command did you run?

`bundle install` && `bundle env` fail.

### What were you expecting to happen?

```
Bundle complete!
```

### What actually happened?

```
~/foo$ bundle install
Fetching https://github.com/chef/omnibus
Unknown option: -C
usage: git [--version] [--exec-path[=<path>]] [--html-path] [--man-path] [--info-path]
           [-p|--paginate|--no-pager] [--no-replace-objects] [--bare]
           [--git-dir=<path>] [--work-tree=<path>] [--namespace=<name>]
           [-c name=value] [--help]
           <command> [<args>]

Retrying `git -C /home/jenkins/foo clone https://github.com/chef/omnibus /home/jenkins/.rvm/gems/ruby-2.6.5/cache/bundler/git/omnibus-9f5fa7bc2a324f758eec6fd3b58e28b027e3b553 --bare --no-hardlinks --quiet` due to error (2/4): Bundler::Source::Git::GitCommandError Git error: command `git clone https://github.com/chef/omnibus /home/jenkins/.rvm/gems/ruby-2.6.5/cache/bundler/git/omnibus-9f5fa7bc2a324f758eec6fd3b58e28b027e3b553 --bare --no-hardlinks --quiet` in directory /home/jenkins/foo has failed.

Retrying `git -C /home/jenkins/foo clone https://github.com/chef/omnibus /home/jenkins/.rvm/gems/ruby-2.6.5/cache/bundler/git/omnibus-9f5fa7bc2a324f758eec6fd3b58e28b027e3b553 --bare --no-hardlinks --quiet` due to error (3/4): Bundler::Source::Git::GitCommandError Git error: command `git clone https://github.com/chef/omnibus /home/jenkins/.rvm/gems/ruby-2.6.5/cache/bundler/git/omnibus-9f5fa7bc2a324f758eec6fd3b58e28b027e3b553 --bare --no-hardlinks --quiet` in directory /home/jenkins/foo has failed.

Retrying `git -C /home/jenkins/foo clone https://github.com/chef/omnibus /home/jenkins/.rvm/gems/ruby-2.6.5/cache/bundler/git/omnibus-9f5fa7bc2a324f758eec6fd3b58e28b027e3b553 --bare --no-hardlinks --quiet` due to error (4/4): Bundler::Source::Git::GitCommandError Git error: command `git clone https://github.com/chef/omnibus /home/jenkins/.rvm/gems/ruby-2.6.5/cache/bundler/git/omnibus-9f5fa7bc2a324f758eec6fd3b58e28b027e3b553 --bare --no-hardlinks --quiet` in directory /home/jenkins/foo has failed.

Git error: command `git clone https://github.com/chef/omnibus /home/jenkins/.rvm/gems/ruby-2.6.5/cache/bundler/git/omnibus-9f5fa7bc2a324f758eec6fd3b58e28b027e3b553 --bare --no-hardlinks --quiet` in directory /home/jenkins/foo has failed.
```

### If not included with the output of your command, run `bundle env` and paste the output below

`bundle env` also fails attempting to execute `git` with `-C` option.

**Comment by deivid-rodriguez** [comment]
Hi! Yeah, sorry.

I honestly thought this flag was added to git ages ago and nobody would notice this. More than 7 years is a long time, but not as long as I thought.

I guess I'll restore the previous way for old gits, and schedule dropping support for ancient gits for the next major.

**Comment by simi** [comment]
@jmartin-r7 what is the reason for you to use that old git?

**Comment by jmartin-r7** [comment]
@deivid-rodriguez, that sounds good, the primary concern is related to this creating a breaking change on a `patch` version.

@simi, this was identified due to usage of purposely older docker containers to compile some gems against an older version of glibc. Updating the `git` version on the container is possible and will likely be implemented.

The primary issue is a `patch` version changing the supported underlying options required by `git`. A change in the dependencies for `git` checkout based gems in `bundler` to function is not backwards compatible and is better reserved for a `major` release.

**Comment by hsbt** [comment]
I'm not sure RubyGems/Bundler have a responsibility to support the old platform. In my understanding, We don't have a supported version of `git` and OS platform like CentOS, Ubuntu. 

So, It's out of scope for SemVer policy.

**Comment by evgeni** [comment]
FWIW, this also happens on CentOS 7 which has git-1.8.3.1.

**Comment by deivid-rodriguez** [comment]
@jmartin-r7 I fixed this because it was easy and because I really thought this flag was introduced much longer ago.

However I agree with @hsbt that we have no responsibility in supporting 7 year old versions of git. The fact that bundler worked when used with very old dependent software doesn't mean it's supported. We had no tests whatsoever testing old git versions and we have never claimed that we support those, so I think it would've been perfectly fine to leave this broken, and its semver compatibility is debatable. After all, every change you make in a piece of software is a breaking change for people relying on the unchanged behaviour, so this is terribly subject to interpretation.

Anyways, in bundler 3 we will have a more clear and explicit lower bound for the git versions that we support :+1:.

**Comment by simi** [comment]
On the other side I have seen more projects to support CentOS 7 (even legacy) library versions since it is widely used system in production conservative environments.

for example https://github.com/brianmario/mysql2/blob/e2503dc6e8ad02f8c2f4fc71006f9840694e319c/.travis.yml#L80-L84

_:pray: for Bundler 3 and faster release, deprecation cycles._

**Comment by deivid-rodriguez** [comment]
@simi Are you suggesting that we add a deprecation warning for old git?

**Comment by simi** [comment]
IMHO think it is not needed for now. Supporting CentOS 7 is nice to have without deprecations.
