### ISSUE TITLE
new plugins support broken when using buildroot

### ISSUE THREAD

**Issue by darix** [rubygems/rubygems#4261]
using the following install commandline

```
install cmdline: ["/usr/bin/gem.ruby3.0", "install", "--verbose", "--local", "--build-root", "/home/abuild/rpmbuild/BUILDROOT/rubygem-yard-0.9.26-0.x86_64", "-f", "--no-document", "/home/abuild/rpmbuild/SOURCES/yard-0.9.26.gem"]
```

leads to

```
abuild@09c1149cc7cf:~/rpmbuild/BUILDROOT/rubygem-yard-0.9.26-0.x86_64> cat ./usr/lib64/ruby/gems/3.0.0/plugins/yard_plugin.rb
require '/home/abuild/rpmbuild/BUILDROOT/rubygem-yard-0.9.26-0.x86_64/usr/lib64/ruby/gems/3.0.0/gems/yard-0.9.26/lib/rubygems_plugin.rb'
```

The generated file should not contain the buildroot.

```
$ gem env version
gem.ruby3.0 env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.2.3
  - RUBY VERSION: 3.0.0 (2020-12-25 patchlevel 0) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /usr/lib64/ruby/gems/3.0.0
  - USER INSTALLATION DIRECTORY: /home/abuild/.local/share/gem/ruby/3.0.0
  - RUBY EXECUTABLE: /usr/bin/ruby.ruby3.0
  - GIT EXECUTABLE: 
  - EXECUTABLE DIRECTORY: /usr/bin
  - SPEC CACHE DIRECTORY: /home/abuild/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /usr/lib64/ruby/gems/3.0.0
     - /home/abuild/.local/share/gem/ruby/3.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
     - :benchmark => false
     - :install => "--format-executable --no-user-install"
     - "install" => "--format-executable --no-user-install"
     - :format_executable => true
     - :update => "--format-executable --no-user-install"
     - "update" => "--format-executable --no-user-install"
     - :sources => ["https://rubygems.org"]
  - REMOTE SOURCES:
     - https://rubygems.org
  - SHELL PATH:
     - /usr/local/bin
     - /usr/bin
     - /bin
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Thanks for the report @darix, PR appreciated!

**Comment by darix** [comment]
in a related note ... for other directories `Gem::Specification` had methods to query the paths like extensions dir. there is no such thing for plugins_dir.  was that intentional or an oversight?

what happens if you install multiple versions of the same gem. which version will be required in the generated file? this might affect how we have to handle the files in packaging for distros.

**Comment by deivid-rodriguez** [comment]
> in a related note ... for other directories Gem::Specification had methods to query the paths like extensions dir. there is no such thing for plugins_dir. was that intentional or an oversight?

I'm not sure I understand your question. What do you need exactly? I assume `Gem.plugindir` is not enough?

> what happens if you install multiple versions of the same gem. which version will be required in the generated file? this might affect how we have to handle the files in packaging for distros.

Only the latest version of each gem with plugins will be kept there.

**Comment by deivid-rodriguez** [comment]
Hi again @darix. I was quickly looking at this issue and I'm not sure what the expectation is. You would like that generated file to include a relative require instead?

**Comment by darix** [comment]
the path can be absolute but it should not contain the buildroot parameter.

**Comment by deivid-rodriguez** [comment]
Ok, so stripping off the buildroot parameter from the beginning of the path if `--build-root` was passed as an option would be ok, right? Altough maybe a relative path would be simpler. I'll have a look.

**Comment by deivid-rodriguez** [comment]
@darix Could you try #4317?

**Comment by darix** [comment]
So hacking on the last bits of the integration with our gem2rpm fork.

```ruby
spec=Gem::Package.new('yard-0.9.26.gem').spec
spec.plugins
=> []
```

what is the correct way to find out if the current gem has a plugin?

**Comment by deivid-rodriguez** [comment]
Plugins are not registered in the gem specification explicitly, you need to look for requirable files named `rubygems_plugin.rb`.

**Comment by darix** [comment]
so why is plugins filled in your PR?

**Comment by deivid-rodriguez** [comment]
Right! I added this helper to `Gem::BasicSpecification`

https://github.com/rubygems/rubygems/blob/b5a113c040a1820a9f0fdd9a11965e695939e2be/lib/rubygems/basic_specification.rb#L278-L285

But I think it only works if the specification is installed.

**Comment by deivid-rodriguez** [comment]
I guess that could be fixed though.

**Comment by darix** [comment]
it would really be helpful :)

**Comment by darix** [comment]
```ruby
spec.files.select {|filename| filename =~ Gem.plugin_suffix_regexp }
```

would that be a good enough workaround?

**Comment by deivid-rodriguez** [comment]
I think you want 

```ruby
spec.files.select {|filename| filename =~ /rubygems_plugin#{Gem.suffix_pattern}\z/ }
```

Otherwise you might mistake any file ending with `_plugin.rb` as a rubygems plugin.

**Comment by darix** [comment]
you probably mean?

```ruby
spec.files.select {|filename| filename =~ /rubygems_plugin#{Gem.suffix_regexp}\z/ }
```

**Comment by deivid-rodriguez** [comment]
Yes, that.

**Comment by darix** [comment]
as an unrelated note ... has_rdoc should have been gone since a whilte ... maybe the expiry should be merged with has_rdoc? (FWIW: one of the 2 functions is really helpful for packaging tools like gem2rpm.) has_plugins? would also be a nice way. but we can hack that in easily.

**Comment by deivid-rodriguez** [comment]
> as an unrelated note ... has_rdoc should have been gone since a whilte ... maybe the expiry should be merged with has_rdoc? (FWIW: one of the 2 functions is really helpful for packaging tools like gem2rpm.) 

Is one of them not deprecated or something? How are those helpful to you? Note that as far as I understand, this attribute doesn't mean that the gem includes docs, but that could potentially include them, so it's always true these days.

**Comment by darix** [comment]
has_rdoc says it should have been removed in 2018 :D

and we took them as indicator that it has documentation and the we create a subpackage for documentation. it might be we put the wrong assumptions when we started using those functions.

**Comment by deivid-rodriguez** [comment]
> has_rdoc says it should have been removed in 2018 :D

I think fixed that a while ago, now it should say that it will be removed in rubygems 4.

> and we took them as indicator that it has documentation and the we create a subpackage for documentation. it might be we put the wrong assumptions when we started using those functions.

I see, yeah, that might be a wrong assumption, I think it's better to look for documentation files inside the gem.

**Comment by darix** [comment]
just curious what is the procedure for making sure that this PR will be also moved to 3.0.1?

**Comment by deivid-rodriguez** [comment]
That's up to @hsbt. I'm not sure if this PR will make it though since I think we're quite close to ruby 3.0.1.

**Comment by darix** [comment]
our package already has your PR as a patch inside. so I am quite happy. and the code in our rubygems automation is done as well so now i just need all ruby packages in the distro to be 3.0 ready to drop 2.7 :D
