### ISSUE TITLE
Feature: `bundle install --bundler` to install version required by Gemfile.lock/gems.locked

### ISSUE THREAD

**Issue by svoop** [rubygems/rubygems#4264]
Dockerizing my pet project apps on top of Ruby images, I'm often seeing this while building images:

> Warning: the running version of Bundler (2.1.4) is older than the version that created the lockfile (2.2.4). We suggest you to upgrade to the version that created the lockfile by running `gem install bundler:2.2.4`.

This mostly is no big deal, at least if the Ruby image is based on the same Ruby version as where the gems.locked/Gemfile.lock was created. However, it would be nice to install the correct version of Bundler before the actual bundle.

Currently, the Bundler version has to be extracted from gems.locked/Gemfile.lock by use of external commands which the image must feature:

```
RUN bundle config set without 'development test' && \
  version=$(grep -iA1 "bundled with" gems.locked | tail -n 1 | awk '{$1=$1};1') && \
  (if [ -n "$version" ]; then gem install bundler:$version; fi) && \
  bundle install --jobs 20 --retry 5
```

How about teaching Bundler a new trick to do the same?

```
RUN bundle config set without 'development test' && \
  bundle install --bundler && \
  bundle install --jobs 20 --retry 5
```

What are the chances for such an enhancement to be merged?

**Comment by deivid-rodriguez** [comment]
Hello @svoop! Thanks for the suggestion.

In few words, that's how I think `bundle install` should work by default, I don't think we even need a special flag.

I plan to get this and other related issues sorted out for the next minor bundler release. For the moment we have this WIP PR: https://github.com/rubygems/rubygems/pull/4076.

**Comment by deivid-rodriguez** [comment]
I'll close this since we plan to do this, but by default, and I got no further feedback here.
