### ISSUE TITLE
在进行bundle install时出现以下错误

### ISSUE THREAD

**Issue by crunh** [rubygems/rubygems#4265]
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=undefined+method+%60size%27+for+nil+NilClass&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/rubygems/rubygems/issues/new?labels=Bundler

**Comment by deivid-rodriguez** [comment]
Hi @crunh.

We need better information in order to be able to provide any help. Please reopen a separate issue properly filling up the questions our bug report template.

Thanks!
