### ISSUE TITLE
bundle package argument as keyword parameters deprecated

### ISSUE THREAD

**Issue by marlinpierce** [rubygems/rubygems#4283]
The "bundle package" command for bundler 2.1.4 gives a deprecation warning using ruby 2.7.

/usr/local/lib/ruby/site_ruby/2.7/rubygems/package.rb:509: warning: Using the last argument as keyword parameters is deprecated

**Comment by simi** [comment]
Can you provide more info about your environment, for example output of `bundle env`?

**Comment by simi** [comment]
I tried with bundler 2.1.4 and I got some deprecation warning (different ones), but all seems to be fixed with latest bundler (2.2.5). Can you check with latest bundler as well @marlinpierce?

You can use following commands to get current bundler and ensure it is running the package command.

```bash
gem install bundler:2.2.5
bundle _2.2.5_ package
```

**Comment by deivid-rodriguez** [comment]
Closing since this is fixed in recent versions and there was no further feedback.
