### ISSUE TITLE
bundle package gives last argument as keyword parameters is deprecated

### ISSUE THREAD

**Issue by marlinpierce** [rubygems/rubygems#4284]
The "bundle package" command for bundler 2.1.4 gives a deprecation warning using ruby 2.7.

/usr/local/lib/ruby/site_ruby/2.7/rubygems/package.rb:509: warning: Using the last argument as keyword parameters is deprecated

**Comment by simi** [comment]
seems like dupe of https://github.com/rubygems/rubygems/issues/4284, let's discuss in there
