### ISSUE TITLE
Bundle standalone should un-monkey patch Kernel.require

### ISSUE THREAD

**Issue by aaronjensen** [rubygems/rubygems#4294]
### Describe the problem as clearly as you can

When using `bundle --standalone` you get a `setup.rb` that sets your load path with all of the gems you need in it, similar to `Bundler.setup`. 

It does not, however reverse the rubygems Kernel require mixin ([like `Bunder.setup` does](https://github.com/rubygems/rubygems/blob/8db564d88af0081e1bd7f9f9a063646b75e863fd/bundler/lib/bundler/rubygems_integration.rb#L282-L290)), which causes require to search the gem paths and makes requiring files much slower than it would otherwise be.

Ideally, the generated `setup.rb` generated would include code to remove the monkey patch. We've been using this:

```
if Kernel.private_method_defined?(:gem_original_require)
  Kernel.alias_method(:require, :gem_original_require)
end
```

I couldn't say why the one in `Bundler::RubyGemsIntegration#reverse_rubygems_kernel_mixin` is so much more elaborate, but if that's required for some reason, perhaps that should be emitted.

### Post steps to reproduce the problem

Use `bundle --standalone`

### Which command did you run?

`bundle install --standalone --path=./gems`

### What were you expecting to happen?

See description

### What actually happened?

See description

### If not included with the output of your command, run `bundle env` and paste the output below

```
Bundler       2.1.4
  Platforms   ruby, x86_64-darwin-19
Ruby          2.7.2p137 (2020-10-01 revision 5445e0435260b449decf2ac16f9d09bae3cafe72) [x86_64-darwin19]
  Full Path   /Users/user/.asdf/installs/ruby/2.7.2/bin/ruby
  Config Dir  /Users/user/.asdf/installs/ruby/2.7.2/etc
RubyGems      3.1.4
  Gem Home    /Users/user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0
  Gem Path    /Users/user/.gem/ruby/2.7.0:/Users/user/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0
  User Home   /Users/user
  User Path   /Users/user/.gem/ruby/2.7.0
  Bin Dir     /Users/user/.asdf/installs/ruby/2.7.2/bin
Tools
  Git         2.28.0
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

**Comment by deivid-rodriguez** [comment]
I agree @aaronjensen, feel free to send us a PR!

**Comment by aaronjensen** [comment]
@deivid-rodriguez okay, submitted #4299
