### ISSUE TITLE
Regression - Bundler v2.2.3 and above ignores target platform

### ISSUE THREAD

**Issue by LiranLast** [rubygems/rubygems#4296]
### Describe the problem as clearly as you can

When using Bundler version 2.2.3 and above the platform setting is ignored.

For our specific use-case, this happened when installing the Rookout gem using bundler on the Alpine Linux operating system, but we have seen similar behaviors in other envioremnts.

### Post steps to reproduce the problem

0. Create a proper runtime environment (optional) :
```
docker run -it ruby:2.6-alpine /bin/sh
apk add make gcc musl-dev git
```

1. Create an empty directory and place the following `Gemfile` in it:
```
source "https://rubygems.org"

gem "rookout"
```

2. Set the target platform:
```
bundle config force_ruby_platform true
```

3. Execute bundle install from the relevant version:
```
gem install bundler -v 2.2.3
bundle _2.2.3_ install
```

As a single Dockerfile:
```
FROM ruby:2.7.1-alpine3.12
RUN apk add make gcc musl-dev git

RUN mkdir test
WORKDIR test

RUN echo $'source "https://rubygems.org"\n\ngem "rookout"\n' >> Gemfile

RUN gem install bundler -v 2.2.3
RUN bundle config force_ruby_platform true
RUN bundle _2.2.3_ install
```

### Which command did you run?

bundle config force_ruby_platform true
bundle install

### What were you expecting to happen?

I was expecting the Google Protobuf gem to be fetched using the `Ruby` platform and for the native extensions to be built locally.

![image](https://user-images.githubusercontent.com/19842903/104892911-6d07a880-597b-11eb-9115-0751e389b8b6.png)

### What actually happened?

The Google Protobuf gem was fetched with the prebuilt binaries.

![image](https://user-images.githubusercontent.com/19842903/104892388-c91dfd00-597a-11eb-9757-a2ca121e1023.png)

## Environment

```
Bundler       2.2.3
  Platforms   ruby, x86_64-linux-musl
Ruby          2.7.1p83 (2020-03-31 revision a0c7c23c9cec0d0ffcba012279cd652d28ad5bf3) [x86_64-linux-musl]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.1.2
  Gem Home    /usr/local/bundle
  Gem Path    /root/.gem/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/local/bundle
  User Home   /root
  User Path   /root/.gem/ruby/2.7.0
  Bin Dir     /usr/local/bundle/bin
Tools
  Git         2.26.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2020-12-22
Git SHA           29dc3c8398
Released Version  true
```

## Bundler settings

```
force_ruby_platform
  Set for the current user (/root/.bundle/config): true
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```

### Gemfile

```ruby
source "https://rubygems.org"

gem "rookout"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    binding_of_caller (1.0.0)
      debug_inspector (>= 0.0.1)
    concurrent-ruby (1.1.7)
    debug_inspector (1.0.0)
    event_emitter (0.2.6)
    google-protobuf (3.9.2)
    rookout (0.1.18)
      binding_of_caller (>= 0.7)
      concurrent-ruby (>= 1.1)
      event_emitter (>= 0.2.6)
      google-protobuf (= 3.9.2)
      websocket-driver (>= 0.5.0)
    websocket-driver (0.7.3)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)

PLATFORMS
  ruby

DEPENDENCIES
  rookout

BUNDLED WITH
   2.2.3
```

**Comment by deivid-rodriguez** [comment]
Ugg, sorry, I think I messed something with target platforms in the last releases since we have received several reports about it. I'll have a look in the next days.

**Comment by deivid-rodriguez** [comment]
I created #4302 to fix this.
