### ISSUE TITLE
Opt-in descriptive error messages

### ISSUE THREAD

**Issue by dogweather** [rubygems/rubygems#4306]
I'd like to suggest a feature. **I'm happy to submit a PR.** Is the project open to the idea?

### Use Case

As a developer switching among the many versions of Ruby I have installed, I want to make sure my [Sorbet](https://sorbet.org/) and Rubocop gems are the latest versions. I use their CLI apps outside of projects, and so in this case I use the `gem` CLI, not `bundle`.

### Current Behavior

Sorbet's CLI is named `srb`, so I first naively tried this:

```
$ gem update rubocop srb
Updating installed gems
Nothing to update
```

Now, I **knew** that Sorbet was installed, but wasn't not sure about Rubocop. I had to issue more commands to figure out that Rubocop wasn't installed. It also turns out that Sorbet's gem name is `sorbet`. I think the above output means `gem` took no action,  but it (1) doesn't tell me why. It also doesn't help me (2) detect my human errors, or (3) suggest how to correct them. Finally, it (4) doesn't explicitly say that it made no changes.

`--verbose` doesn't change the output. The `--explain` flag gives even less output and IMO is more cryptic:

```
$ gem update --explain rubocop srb
Gems to update:
```
### Proposal

I propose output that remedies the four issues:

```
$ gem update rubocop srb
Updating installed gems...

  - rubocop: Not installed; taking no action.
  - srb:     Not installed; did you mean "sorbet"? Taking no action.

Two updates requested, zero performed.
```

This feature could be opt-in via the unused `--verbose` flag if the current behavior is important to preserve.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.2.6
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by rubyFeedback** [comment]
I think it's a fine suggestion, but we need to keep in mind that users may prefer
a less verbose variant at all times. So perhaps the --verbose and --explain
output should be improved. If I understand you suggested for --verbose to
provide more information by default, yes? If that is the case I think this seems
to make sense; I assume the messages are sparse because whoever wrote
them doesn't like writing too long messages. ;-)

**Comment by simi** [comment]
@dogweather hello. Any improvement on UX side is more than welcome. I like your proposal. I would just suggest to not use "numbers as words".

original

> Two updates requested, zero performed.

suggested

> 2 updates requested, 0 updated

Also it is subject of discussing to make this output default, since it seems more user-friendly than the current one.

**Comment by dogweather** [comment]
@simi Excellent - I like working on UX improvements like this. I'll get started.

> not use "numbers as words"

Makes perfect sense.

**Comment by deivid-rodriguez** [comment]
In my opinion, everything in this proposal is better than the current error so I'd say let's replace the old output with the new output, no opt-in, no opt-out.

**Comment by ttilberg** [comment]
I encourage changing the default output to the suggested output. The existing output is surprisingly misleading given the reporter’s example above. Meanwhile, the suggested output is still extremely concise, but informative. Subjectively, I don’t think it’s anywhere near verbose. I think this is a very Ruby thing to do: least surprise, and developer friendly.
