### ISSUE TITLE
rubygems

### ISSUE THREAD

**Issue by Fumiya2116** [rubygems/rubygems#4312]
the terminal in my mac PC(M1) could not find gem "rails(6.1.1)" in any of the gem sources listed in my Gemfile even if i have already installed rails. And I want to know what gemfile is.

**Comment by deivid-rodriguez** [comment]
Hi @Fumiya2116!

Unfortunately this issue doesn't provide enough information for us to be able to help you.

Please reopen a new issue explaining the problem you are having, you didn't even say the command you're trying to run! Make sure you read the tips that appear in the text box when you try to open an issue.
