### ISSUE TITLE
Error "Could not find gem" for --without group dependency with 3.1.6

### ISSUE THREAD

**Issue by owst** [rubygems/rubygems#4325]
Running `bundle install --without development test` and then `bundle exec rake` fails due to a missing dependency of a gem in a group that was excluded by `--without`.

With these versions:

Ruby 2.7.2
rubygems 3.1.6
bundler 1.17.3

and this simplified directory structure:

```
.
├── app
│   ├── Gemfile
│   └── Rakefile
└── gems
    └── gem_one
        └── gem_one.gemspec
```

Where `app/Gemfile` contains:
```ruby
source 'https://rubygems.org'

group :test, :development do
  gem 'gem_one', path: '../gems'
end

gem 'rake'
```
`app/Rakefile` is trivial:
```ruby
desc "it's the default"
task :default
```

and `gems/gem_one/gem_one.gemspec` contains:

```ruby
Gem::Specification.new do |s|
  s.name = 'gem_one'
  s.version = '0.1.0'
  s.authors = ['']
  s.summary = ''
  s.require_paths = ['.']

  s.add_dependency 'aws-sdk-s3', ['<= 1.51.0', '~> 1']
end
```

Installing inside `app` appears to work as expected:
```
$ bundle _1.17.3_ install --without development test
Fetching gem metadata from https://rubygems.org/.....
Resolving dependencies...
Fetching rake 13.0.3
Installing rake 13.0.3
Using bundler 1.17.3
Bundle complete! 2 Gemfile dependencies, 2 gems now installed.
Gems in the groups development and test were not installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

but then we get an error when trying to run `rake`:
```
$ bundle exec rake -T
Bundler could not find compatible versions for gem "aws-sdk-s3":
  In Gemfile:
    gem_one was resolved to 0.1.0, which depends on
      aws-sdk-s3 (<= 1.51.0, ~> 1)

Could not find gem 'aws-sdk-s3 (<= 1.51.0, ~> 1)', which is required by gem 'gem_one', in any of the sources.
```

To reproduce this, something like the following seems to work, using docker:
```bash
$ docker run --rm -it ruby:2.7.2-slim bash
# We should now have an interactive bash session in the container, paste/execute all following lines...

gem update --system 3.1.6
gem install bundler:1.17.3

cd /tmp
mkdir -p repro/app repro/gems/gem_one
cd repro

cat <<EOF > app/Gemfile
source 'https://rubygems.org'

group :test, :development do
  gem 'gem_one', path: '../gems'
end

gem 'rake'
EOF

cat <<EOF > gems/gem_one/gem_one.gemspec
Gem::Specification.new do |s|
  s.name = 'gem_one'
  s.version = '0.1.0'
  s.authors = ['']
  s.summary = ''
  s.require_paths = ['.']

  s.add_dependency 'aws-sdk-s3', ['<= 1.51.0', '~> 1']
end
EOF

cat <<EOF > app/Rakefile
desc "it's the default"
task :default
EOF

cd app

bundle _1.17.3_ install --without development test
bundle exec rake -T
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by tommeier** [comment]
Getting this also - with bundler 2.2.7 and rubygems 3.1.6 - originally thought it was bundler related till seeing this issue - thanks 🙏

**Comment by owst** [comment]
I tried a few version combinations:

 | Ruby  | rubygems | bundler | outcome               | 
 | ----- | -------- | ------- | --------------------- |
  | 2.6.6 | 3.0.9    | 1.17.3  | ✅ no failure         | 
 | 2.7.2 | 3.0.9    | 1.17.3  | ❌ fails, deadlock, recursive locking on `bundle install` |
 | 2.6.6 | 3.1.6    | 1.17.3  | ❌ fails, Could not find gem | 
  | 2.7.2 | 3.1.6    | 1.17.3  | ❌ fails, Could not find gem, as reported | 
 | 2.6.6 | 3.2.7    | 1.17.3  | ✅ no failure |
  | 2.7.2 | 3.2.7    | 1.17.3  | ✅ no failure |

So it looks like whatever the problem is may have been fixed in `3.2.X`? Since 3.1.6 was only released a few days ago (judging by https://rubygems.org/gems/rubygems-update/versions) it is presumably still supported, so maybe a fix can be backported from 3.2 to 3.1?

**Comment by deivid-rodriguez** [comment]
Maintenance of older series is done by @hsbt on a best effort basis, but there's no guarantee whatsoever that anything will be backported to 3.1.x, and my recommendation is to upgrade to the latest version if you're having issues. That said, you're free to pinpoint the exact change that fixed this, knowing what to backport certainly increases the chances of it being backported.

In any case, closing since it seems like it's fixed!

**Comment by deivid-rodriguez** [comment]
Thanks for your always easy to repro reports, by the way!

**Comment by hsbt** [comment]
I also recommend to not downgrade rubygems and bundler versions from bundled versions of Ruby 2.7.

**Comment by owst** [comment]
Thanks for the quick responses. 

It's definitely not ideal that we're using old versions! We're in the process of upgrading from Ruby 2.6, rubygems 3.0 and Bundler 1.17 right now (hence my two recent rubygems issue reports) - we fix the various versions for consistency across our team. I was hoping to not have to do an "all in one" upgrade of the three versions just to minimise the number and size of the changes.

It _seems_ that I might be able to upgrade to Ruby 2.7 and rubygems 3.2.7 whilst staying on bundler 1.17.3 and _then_ look to upgrade to bundler 2.1/2.2.

Thanks again
