### ISSUE TITLE
`gem help` doesn't list `gem push` as one of the available commands

### ISSUE THREAD

**Issue by vfonic** [rubygems/rubygems#4329]
I was trying to publish a new gem to rubygems. I ran `gem help` and didn't get any relevant documentation printed.

I also tried `gem publish`, but that didn't work as it doesn't exist.

This issue is related to:

  - [x] Publishing a library

Here are my current environment details:

```
$ gem env version
3.2.3
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
I think gem publishing is important enough so that at least the list of examples `gem help` gives includes it :+1:. Or, alternative, show an exhaustive list of commands when `gem help` is run.

The current output includes:

```
Further help:
  gem help commands            list all 'gem' commands
```

and if you run that, you'll get `gem push` documented there.

But not everybody will read this as proved by this issue, so there's definitely room for improvement here.

**Comment by vfonic** [comment]
I totally missed that. :) 

Now I just ran `<command> help` or `<command> --help` for all of these: `heroku`, `npm`, `yarn`, `brew`, `foreman`.

`heroku`, `npm`, `yarn`, and `foreman` list all available commands, while `brew` does something similar to `gem`.

Here's what both of them output for comparison:

<details>

<summary>
`brew help` output
</summary>

```
> brew help
Example usage:
  brew search [TEXT|/REGEX/]
  brew info [FORMULA...]
  brew install FORMULA...
  brew update
  brew upgrade [FORMULA...]
  brew uninstall FORMULA...
  brew list [FORMULA...]

Troubleshooting:
  brew config
  brew doctor
  brew install --verbose --debug FORMULA

Contributing:
  brew create [URL [--no-fetch]]
  brew edit [FORMULA...]

Further help:
  brew commands
  brew help [COMMAND]
  man brew
  https://docs.brew.sh
```

</details>


<details>

<summary>
`gem help` output
</summary>

```
> gem help
RubyGems is a package manager for Ruby.

  Usage:
    gem -h/--help
    gem -v/--version
    gem command [arguments...] [options...]

  Examples:
    gem install rake
    gem list --local
    gem build package.gemspec
    gem help install

  Further help:
    gem help commands            list all 'gem' commands
    gem help examples            show some examples of usage
    gem help gem_dependencies    gem dependencies file guide
    gem help platforms           gem platforms guide
    gem help <COMMAND>           show help on COMMAND
                                   (e.g. 'gem help install')
    gem server                   present a web page at
                                 http://localhost:8808/
                                 with info about installed gems
  Further information:
    https://guides.rubygems.org
```
</details>


I like how RubyGems write what it is when outputting help:
> RubyGems is a package manager for Ruby.
:)

I'd just add `gem push ...` to the list of `Examples`.

**Comment by deivid-rodriguez** [comment]
Yeah, and it also doesn't require a whole rework of the `gem help` output :+1:
