### ISSUE TITLE
Bundler 2.2.7 seems to generate a broken `bundler/setup.rb` when installed with `--standalone`

### ISSUE THREAD

**Issue by nerdrew** [rubygems/rubygems#4331]
### Describe the problem as clearly as you can

`bundle install --standalone` seems to generate a broken `bundler/setup.rb` file.

### Post steps to reproduce the problem

Repo that shows the issue: https://github.com/nerdrew/bundler-require-bug

### Which command did you run?

```shell
% bundle --standalone
% ruby -rbundler -Ibundle -rbundler/setup -e 'Bundler.require'
```

### What were you expecting to happen?

The `bundle/bundler/setup.rb` file shouldn't break `Bundler.require`.

### What actually happened?

```shell
% ruby -rbundler -Ibundle -rbundler/setup -e 'Bundler.require'
Traceback (most recent call last):
	6: from -e:1:in `<main>'
	5: from ~/.rvm/gems/ruby-2.6.6/gems/bundler-2.2.7/lib/bundler.rb:173:in `require'
	4: from ~/.rvm/gems/ruby-2.6.6/gems/bundler-2.2.7/lib/bundler/runtime.rb:50:in `require'
	3: from ~/.rvm/gems/ruby-2.6.6/gems/bundler-2.2.7/lib/bundler/runtime.rb:50:in `each'
	2: from ~/.rvm/gems/ruby-2.6.6/gems/bundler-2.2.7/lib/bundler/runtime.rb:61:in `block in require'
	1: from ~/.rvm/gems/ruby-2.6.6/gems/bundler-2.2.7/lib/bundler/runtime.rb:61:in `each'
~/.rvm/gems/ruby-2.6.6/gems/bundler-2.2.7/lib/bundler/runtime.rb:66:in `block (2 levels) in require': private method `require' called for Kernel:Module (NoMethodError)
```

### If not included with the output of your command, run `bundle env` and paste the output below

```
Bundler             2.2.7
  Platforms         ruby, x86_64-darwin-18
Ruby                2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin18]
  Full Path         ~/.rvm/rubies/ruby-2.6.6/bin/ruby
  Config Dir       ~/.rvm/rubies/ruby-2.6.6/etc
RubyGems            3.0.8
  Gem Home         ~/.rvm/gems/ruby-2.6.6
  Gem Path          ~/.rvm/gems/ruby-2.6.6:/Users/lazarus/.rvm/rubies/ruby-2.6.6/lib/ruby/gems/2.6.0
  User Home         ~
  User Path         ~/.gem/ruby/2.6.0
  Bin Dir          ~/.rvm/gems/ruby-2.6.6/bin
Tools               
  Git               2.30.0
  RVM               1.29.9 (latest)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

cc @cheister

**Comment by cheister** [comment]
Seems to be caused by https://github.com/rubygems/rubygems/pull/4299

**Comment by deivid-rodriguez** [comment]
Right, I completely missed that the PR set the wrong visibility for `require`. @aaronjensen would you be able to fix this?

**Comment by aaronjensen** [comment]
I couldn't figure out why the original code was written to be uncertain of method visibility, but it seems that the module method and the instance method have two different visibilities. I didn't catch this because I don't use `Bundler.require` with standalone.

Fixed: https://github.com/rubygems/rubygems/pull/4337

**Comment by deivid-rodriguez** [comment]
Thanks @aaronjensen!

I think this code is overly complicated. It's coded as a generic tool to monkeypatch methods where in reality it's only meant to be used as a hack to monkeypatch 2 or 3 rubygems methods. I think a more explicit approach would've avoided this bug, so I'll refactor it to do just that after I merge your fix.

Thanks so much for your work :muscle:.

**Comment by aaronjensen** [comment]
Refactor away. It was based on `Bundler::RubygemsIntegration` which is even more complicated. The version we used in our codebase was just:

```
  if Kernel.private_method_defined?(:gem_original_require)
    Kernel.alias_method(:require, :gem_original_require)
  end
```

That gives warnings though. I think you need all the steps. As I believe I said before, it'd be nice for rubygems to expose a method to undo its monkey patches. That way `Bundler::RubygemsIntegration` and this could use that.

**Comment by deivid-rodriguez** [comment]
Yes, I meant the `RubygemsIntegration` code that's too complicated. I know you based your code on that, that why I believe if that code had been more straightforward, the issue probably wouldn't have happened.

> That gives warnings though. I think you need all the steps. As I believe I said before, it'd be nice for rubygems to expose a method to undo its monkey patches. That way Bundler::RubygemsIntegration and this could use that.

Agreed, but we also need bundler to backport the code so that bundler works with all rubygems versions, so in the end we may end up with more duplicated code :grimacing:. Worth a try though.

**Comment by aaronjensen** [comment]
> Agreed, but we also need bundler to backport the code so that bundler works with all rubygems versions

Ah, good point, though eventually you'd be able to get rid of the duplicate code. In any case, good luck w/ the refactor.
