### ISSUE TITLE
Unexpected error, Bundler cannot continue

### ISSUE THREAD

**Issue by isabellecochrane** [rubygems/rubygems#4339]
When trying to run 
$ rails new blog 
it tells me there 
$ conflict  .gitignore

Then continues to run but this error stops it
Could not find gem 'sqlite3 (~> 1.4)' in any of the gem sources listed in your Gemfile.

I have got sqlite 2.24.0

**Comment by deivid-rodriguez** [comment]
Hi @isabellecochrane!

Unfortunately we need more information to be able to help you. Could you copy the full logs of the error since the moment you run `rails new blog`? Use [markdown](https://guides.github.com/features/mastering-markdown/) to format it so it's easier for us to read.

Thanks!

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
