### ISSUE TITLE
Use lazy gem activation everywhere?

### ISSUE THREAD

**Issue by carsomyr** [rubygems/rubygems#434]
I recently got an error [like this one](http://stackoverflow.com/questions/5774621/phusion-passenger-error-you-have-activated-rack-1-2-1-but-your-gemfile-require). The reason: `passenger` depends on `rack >= 0` in the gemspec, and it activated a version that conflicted with the one Bundler resolved.

In my case, the version that Bundler resolved for was `1.5.0`, while the activated version was `1.4.4`. Here's where it gets hairy: `passenger` tries its best to not require `rack`. After some triage and searching, I learned about RubyGems lazy activation. The problem is, if you have just one version of `rack` installed, RubyGems will eagerly activate it. This is the matrix of situations that work and situations that don't (remember that Bundler wants version `1.5.0`).

```
1.4.4, 1.5.0 | works
1.5.0        | works
1.4.0, 1.4.4 | works
1.4.4        | breaks
```

The above would strongly suggest that lazy loading is to blame: The laziness kicks in when there are two versions of `rack`, and those versions don't matter. If there is only one version of `rack`, it will get eagerly loaded, and it must be version `1.5.0` to match what Bundler wants. That leaves the situation where only version `1.4.4` is installed and loaded eagerly, resulting in my problem.

Would you be willing to consider making all loading lazy? That would prevent situation 4.

**Comment by copiousfreetime** [comment]
I'm going to close this one as most likely no longer relevant.  If that is not the case, please reopen.
