### ISSUE TITLE
Gem triggers a Kernel Panic in macOS Catalina or Big Sur, up to 11.2.

### ISSUE THREAD

**Issue by infa-jowoods** [rubygems/rubygems#4341]
I'm having a **problem**.

My current problem is I can trigger a Kernel Panic in macOS Catalina or Big Sur, up to 11.2, only after using gem and then *rebooting*.

i.e.

1) Boot macOS 11.2
2) Install Ruby via hombrew and run a gem command like `gem update`
3) reboot and see Kernel Panic.
4) Occurs on Intel and ARM64 (Apple Silicon)

I reported here: https://apple.stackexchange.com/questions/412584/m1-mac-kernel-panic-on-reboot-no-checkins-from-watchdogd

But others see it too: https://apple.stackexchange.com/questions/372183/catalina-crashing-at-shutdown-watchdog-timeout-no-checkins-from-watchdogd

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

Any recent version of Ruby, but specifically the latest on hombrew: https://formulae.brew.sh/api/formula/ruby.json

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Hei @infa-jowoods, I'm sorry you're having issues :(

We got another [MacOS specific issue reported](https://github.com/rubygems/rubygems/issues/4234), not sure if it could be related. I'd say no because it only happens with system ruby as far as I recall and nobody has reported your symptoms.

Anyways, hopefully other contributors can shed some light, I don't have a MacOS machine available and have no idea whatsoever how rubygems could cause such issue. Sorry.

**Comment by deivid-rodriguez** [comment]
I read some follow up you made on the apple.stackexchange issues you mentioned and it seems that now you think that ruby itself is causing the issues? Could you report your findings to https://bugs.ruby-lang.org/projects/ruby-master if that's the case?

**Comment by deivid-rodriguez** [comment]
It seems most likely unrelated to rubygems as per the above comment and also further reading the tickets, it seems that there's a number of ways to reproduce the issue without even involving ruby.

So, based on that and given the lack of feedback, I'm closing this.

**Comment by johnalanwoods** [comment]
Sorry for the delay @deivid-rodriguez  - I've all but confirmed this is a bug in macOS. Check my post here: https://github.com/Homebrew/discussions/discussions/920
