### ISSUE TITLE
Unique SSL issue "unexpected message"

### ISSUE THREAD

**Issue by bfeller** [rubygems/rubygems#4349]
My current problem is when I try to install gems I get:
```
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=error: unexpected message (https://rubygems.org/api/v1/dependencies?gems=bundler)
```

I was able to make it work with a brew install ruby. But when I try to use a ruby manager (I tried RVM and rbenv) I get the error.

I've also tried the whole LibreSSL thing
```
export LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"
export CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"
export PKG_CONFIG_PATH="/usr/local/opt/openssl@1.1/lib/pkgconfig"
```

I guess the most confusing part of all this is the "unexpected message" part. I can't find any other reference to that besides the StackOverflow I created.

This issue is related to:

  - [ ] Network problems
  - [X] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:
I have a brand new iMac (Retina 5K, 27-inch, 2020) with macOS 11.2 Big Sur.

Totally fresh install, this computer is meant to be a development computer and setting up my ruby environments was one of the first things I was doing.

Installed Chrome
Installed Atom
Installed Github Desktop
Installed iTerm
Installed homebrew
installed rvm
brought in my rails project and then I got the message

```
$ gem env version
3.0.9
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by bfeller** [comment]
Here's the SSL checker response if that helps:
```
$ curl -Lks 'https://git.io/rg-ssl' | ruby
Here's your Ruby and OpenSSL environment:

Ruby:           2.5.8p224 (2020-03-31 revision 67882) [x86_64-darwin20]
RubyGems:       3.0.9
Bundler:        1.17.3
Compiled with:  OpenSSL 1.1.1i  8 Dec 2020
Loaded version: OpenSSL 1.1.1i  8 Dec 2020
SSL_CERT_FILE:  /usr/local/etc/openssl@1.1/cert.pem
SSL_CERT_DIR:   /usr/local/etc/openssl@1.1/certs

With that out of the way, let's see if you can connect to rubygems.org...

Bundler connection to rubygems.org:       failed  ❌  (SSL_connect returned=1 errno=0 state=error: unexpected message)
RubyGems connection to rubygems.org:      failed  ❌  (SSL_connect returned=1 errno=0 state=error: unexpected message (https://rubygems.org))
Ruby net/http connection to rubygems.org: failed  ❌

Unfortunately, this Ruby can't connect to rubygems.org. 😡
Even worse, we're not sure why. 😕

Here's the full error information:
OpenSSL::SSL::SSLError: SSL_connect returned=1 errno=0 state=error: unexpected message
  /Users/bryanfeller/.rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/net/protocol.rb:44:in `connect_nonblock'
  /Users/bryanfeller/.rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/net/protocol.rb:44:in `ssl_socket_connect'
  /Users/bryanfeller/.rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/net/http.rb:985:in `connect'
  /Users/bryanfeller/.rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/net/http.rb:920:in `do_start'
  /Users/bryanfeller/.rvm/rubies/ruby-2.5.8/lib/ruby/2.5.0/net/http.rb:915:in `start'
  -:101:in `<main>'

You might have more luck using Mislav's SSL doctor.rb script. You can get it here:
https://github.com/mislav/ssl-tools/blob/8b3dec4/doctor.rb
Read more about the script and how to use it in this blog post:
https://mislav.net/2013/07/ruby-openssl/
```

**Comment by simi** [comment]
@bfeller I remember there were some tweaks done recently in RG. Can you try to update to latest RubyGems (`gem update --system`) and run the ssl check again?

**Comment by bfeller** [comment]
@simi It doesn't work:
```
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=error: unexpected message (https://rubygems.org/api/v1/dependencies?gems=rubygems-update)
```

**Comment by MSP-Greg** [comment]
@bfeller

I believe that the line (and the code behind it):
```
Ruby net/http connection to rubygems.org: failed  ❌
```
indicates that Ruby cannot establish an ssl connection to RubyGems.org, and that's only using code from net/http.  So, something is amiss with the Ruby install, but I'm not sure what...

Dos the following code run?
```ruby
#!/usr/bin/env ruby

require 'uri'
require 'net/http'
begin
  uri_name = ARGV[0] || 'google.com'
  uri = URI "https://#{uri_name}"
  Net::HTTP.new(uri.host, uri.port).tap do |http|
    http.use_ssl = true
  end.start
rescue => e
  puts "Error: #{e.message}"
else
  puts "SSL connection to #{uri_name} successful!"
end
```

**Comment by bfeller** [comment]
@MSP-Greg It sure does
```
SSL connection to google.com successful!
```

**Comment by MSP-Greg** [comment]
Ok.  Ruby is probably ok.  What happens if you run the above with rubygems.org as an argument?

**Comment by bfeller** [comment]
@MSP-Greg 
```
Error: SSL_connect returned=1 errno=0 state=error: unexpected message
```

Well like I said above, it has something to do with the way the ruby managers work because if I remove RVM and use a ruby version from something like

```
brew install ruby
```

That will work.
So I initially thought it was something to do with RVM so I switched to rbenv which should be using the brew openssl instead having its own thing like RVM. But I got the same error with rbenv.

**Comment by bfeller** [comment]
I've also done this setup more than a few times before, it's not my first rodeo. So my suspicion lies with potentially the LibreSSL or the latest version of OSX. I've upgraded other machines to this version on OSX but I've never done a clean setup on this version.

**Comment by MSP-Greg** [comment]
@bfeller

Sorry, I focused on the OpenSSL error.  I think RubyGems/Bundler loads some additional certs, but net/http just uses the system certs.  RG 3.0.9 is kind of old.  I'm not much help on particulars of macOS, rvm, certs, etc...

**Comment by bfeller** [comment]
Is there a way to manually grab the new rubygems version?

**Comment by MSP-Greg** [comment]
Yes.  Download it from the RubyGems web site with your browser, the newest version is:
https://rubygems.org/downloads/rubygems-update-3.2.8.gem

Use `gem install <path-to-download>`, then run the bin file `update_rubygems`.

I think...

**Comment by bfeller** [comment]
Whoa, the plot thickens...
```
$ gem install ~/Downloads/rubygems-3.2.8.zip

ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=error: unexpected message (https://rubygems.org/api/v1/dependencies?gems=/Users/bryanfeller/Downloads/rubygems-3.2.8.zip)
```

**Comment by simi** [comment]
@bfeller you need to download https://rubygems.org/downloads/rubygems-update-3.2.8.gem and keep the name "rubygems-update-3.2.8.gem" (it should have gem extension).

**Comment by bfeller** [comment]
@simi
oof, derrr, but also still
```
gem install ~/Downloads/rubygems-update-3.2.8.gem
ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=error: unexpected message (https://rubygems.org/api/v1/dependencies?gems=rubygems-update)
```

**Comment by simi** [comment]
@bfeller I'm not sure what's wrong, but it should not do any request. Can you try to specify full path to the file? You can also try using `--local` flag (`gem instal --local rubygems-update-3.2.8.gem`).

**Comment by bfeller** [comment]
adding the --local flag seemed to work


```
$ gem install --local rubygems-update-3.2.8.gem

Successfully installed rubygems-update-3.2.8
Parsing documentation for rubygems-update-3.2.8
Installing ri documentation for rubygems-update-3.2.8
Done installing documentation for rubygems-update after 108 seconds
1 gem installed
```

but then... 

```
$ gem env version
3.0.9
```

and also the original error persists when trying to install gems...

This is hurting my brain.

I didn't change directories.. 

Thank you guys so much for your help with this, I know that its weird and may or may not even be rubygems.

**Comment by simi** [comment]
you need to run `update_rubygems` after installation

**Comment by simi** [comment]
Also you can do really manual installation as described at https://rubygems.org/pages/download if that doesn't work as well.

**Comment by bfeller** [comment]
Okay, things are fixed now:

I had done the manual installation before from [https://rubygems.org/pages/download](https://rubygems.org/pages/download) but manually downloading the gem and installing it with:

```
gem install --local rubygems-update-3.2.8.gem
```
and then running the ```update_rubygems``` file fixed the issue.

Everything works now and it must've been some horrible issue between 3.0.9 and Big Sur, or I did something silly along the way.

thanks for all your help!

**Comment by simi** [comment]
@bfeller glad this is fixed now. It would be great to update guide at https://guides.rubygems.org/ssl-certificate-update/ somehow, with steps to manually update to latest gem at least.
