### ISSUE TITLE
JRuby use of gemspec fails

### ISSUE THREAD

**Issue by CodingAnarchy** [rubygems/rubygems#4352]
### Describe the problem as clearly as you can

When trying to run tests on a gem we are building in-house, we discovered that the platform order we run `bundle install` on matters.

If we use local development in JRuby (setting the platform to `java` in the gemspec), `bundle install` produces this output for our local gem:

```ruby
PATH
  remote: .
  specs:
    foo_gem (1.0.0-java)
      activesupport (>= 5.2, < 6.2)
      jrjackson
```

But if we run `bundle install` on the MRI-based platform, the output is this:

```ruby
PATH
  remote: .
  specs:
    foo_gem (1.0.0)
      activesupport (>= 5.2, < 6.2)
```

This is to be expected, but due to the way bundler operates, while we can run `bundle install` on the JRuby-based `Gemfile.lock` just fine in MRI platforms, _the reverse is not true_. Specifically, if you run `bundle install` on JRuby with the MRI-based `Gemfile.lock`, you will get this error:

```
Could not find gem 'foo_gem' in source at `.`.
The source contains the following versions of 'foo_gem':
1.0.0 java
```

This makes our testing really brittle, as which environment the developer last used `bundle install` in can break half our tests from even getting set up.

### Post steps to reproduce the problem

1. Have a gem in development that has an MRI and JRuby variant
1. Use `bundle install` on MRI Ruby, generating a `Gemfile.lock` file
1. Attempt to use `bundle install` on JRuby with lock file from previous step
1. See error

### Which command did you run?

`bundle install` on JRuby

### What were you expecting to happen?

Bundler fails to find the MRI-specific gem (as we are building from source with the JRuby gemspec), and instead used the JRuby platform variant.

### What actually happened?

```
Could not find gem 'foo_gem' in source at `.`.
The source contains the following versions of 'foo_gem':
1.0.0 java
```

## Environment

```
Bundler       2.2.8
  Platforms   ruby, universal-java-11
Ruby          2.5.7p0 (2020-08-03 revision 67816) [java]
  Full Path   /Users/mtanous/.asdf/installs/ruby/jruby-9.2.13.0/bin/jruby
  Config Dir  /Users/mtanous/.asdf/installs/ruby/jruby-9.2.13.0/etc
RubyGems      3.2.8
  Gem Home    /Users/mtanous/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared
  Gem Path    /Users/mtanous/.gem/jruby/2.5.0:/Users/mtanous/.asdf/installs/ruby/jruby-9.2.13.0/lib/ruby/gems/shared
  User Home   /Users/mtanous
  User Path   /Users/mtanous/.gem/jruby/2.5.0
  Bin Dir     /Users/mtanous/.asdf/installs/ruby/jruby-9.2.13.0/bin
Tools
  Git         2.30.0
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-02-02
Git SHA           4015e550dc
Released Version  true
```

## Bundler settings

```
specific_platform
  Set for the current user (/Users/mtanous/.bundle/config): "true"
```

### Gemfile

```ruby
source 'https://rubygems.org'

gemspec

gem 'pry-nav'
gem 'dotenv'
gem 'rake', '~> 13.0'

group :test do
  gem 'rspec', '~> 3.0'
  gem 'rspec_junit_formatter'
  gem 'simplecov', require: false
end
```

### Gemfile.lock

This is the Java-based on that works. The MRI-based one leaves off the `-java` terms, and fails to load the gem under development as described above.

```
PATH
  remote: .
  specs:
    foo_gem(1.0.0-java)
      activesupport (>= 5.2, < 6.2)
      jrjackson

GEM
  remote: https://rubygems.org/
  specs:
    activesupport (6.1.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    coderay (1.1.3)
    concurrent-ruby (1.1.8)
    diff-lcs (1.4.4)
    docile (1.3.5)
    dotenv (2.7.6)
    ffi (1.14.2-java)
    i18n (1.8.8)
      concurrent-ruby (~> 1.0)
    jrjackson (0.4.14-java)
    method_source (0.9.2)
    minitest (5.14.3)
    pry (0.12.2-java)
      coderay (~> 1.1.0)
      method_source (~> 0.9.0)
      spoon (~> 0.0)
    pry-nav (0.3.0)
      pry (>= 0.9.10, < 0.13.0)
    rake (13.0.3)
    rspec (3.10.0)
      rspec-core (~> 3.10.0)
      rspec-expectations (~> 3.10.0)
      rspec-mocks (~> 3.10.0)
    rspec-core (3.10.1)
      rspec-support (~> 3.10.0)
    rspec-expectations (3.10.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.10.0)
    rspec-mocks (3.10.2)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.10.0)
    rspec-support (3.10.2)
    rspec_junit_formatter (0.4.1)
      rspec-core (>= 2, < 4, != 2.12.0)
    simplecov (0.21.2)
      docile (~> 1.1)
      simplecov-html (~> 0.11)
      simplecov_json_formatter (~> 0.1)
    simplecov-html (0.12.3)
    simplecov_json_formatter (0.1.2)
    spoon (0.0.6)
      ffi
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    zeitwerk (2.4.2)

PLATFORMS
  universal-java-11

DEPENDENCIES
  dotenv
  pry-nav
  rake (~> 13.0)
  rspec (~> 3.0)
  rspec_junit_formatter
  simplecov
  standardized_activity_models!

BUNDLED WITH
   2.2.8
```

### foo_gem.gemspec

```ruby
require_relative 'lib/foo_gem/version'

is_java = (RUBY_PLATFORM == 'java')

# Describe your gem and declare its dependencies:
Gem::Specification.new do |spec|
  spec.name = 'foo_gem'
  spec.version = Models::VERSION
  spec.platform = 'java' if is_java

  spec.files = Dir['{lib,models}/**/*', 'Readme.md']
  spec.test_files = Dir['spec/**/*']
  spec.require_paths = ['lib']

  spec.required_ruby_version = Gem::Requirement.new(">= 2.5.0")

  # for present? blank? etc
  spec.add_dependency 'activesupport', '>= 5.2', '< 6.2'

  if is_java
    # for faster json conversions
    spec.add_dependency 'jrjackson'
  end
end
```

**Comment by deivid-rodriguez** [comment]
Hello @CodingAnarchy :wave:!

This is essentially a duplicate of https://github.com/rubygems/rubygems/issues/3231, which as you can see in the last message, I was hoping to fix exactly as you expect, but I completely forgot :sweat_smile:.

In any case, even if I manage to fix this, you'll still get source control changes in the lockfile depending on where you bundle. This is obviously much better than failures, but the solution I recommend is to keep to unfold your gemspec into two different files, so that they can both be recorded in the lockfile and things always work, for everyone, without source control changes in the lockfile.

So, have:


### foo_gem.gemspec

```ruby
require_relative 'lib/foo_gem/version'

# Describe your gem and declare its dependencies:
Gem::Specification.new do |spec|
  spec.name = 'foo_gem'
  spec.version = Models::VERSION

  spec.files = Dir['{lib,models}/**/*', 'Readme.md']
  spec.test_files = Dir['spec/**/*']
  spec.require_paths = ['lib']

  spec.required_ruby_version = Gem::Requirement.new(">= 2.5.0")

  # for present? blank? etc
  spec.add_dependency 'activesupport', '>= 5.2', '< 6.2'
end
```

and

### foo_gem-java.gemspec

```ruby
require_relative 'lib/foo_gem/version'

# Describe your gem and declare its dependencies:
Gem::Specification.new do |spec|
  spec.name = 'foo_gem'
  spec.version = Models::VERSION
  spec.platform = 'java'

  spec.files = Dir['{lib,models}/**/*', 'Readme.md']
  spec.test_files = Dir['spec/**/*']
  spec.require_paths = ['lib']

  spec.required_ruby_version = Gem::Requirement.new(">= 2.5.0")

  # for present? blank? etc
  spec.add_dependency 'activesupport', '>= 5.2', '< 6.2'

  # for faster json conversions
  spec.add_dependency 'jrjackson'
end
```

**Comment by CodingAnarchy** [comment]
@deivid-rodriguez Thanks for the suggestion. Can you clarify if I would need to change the `Gemfile` for that to work?

**Comment by deivid-rodriguez** [comment]
No, I don't think you need to change your Gemfile, since the `path:` source automatically globs for `.gemspec` files in the target directory.

**Comment by CodingAnarchy** [comment]
Thanks a lot! I will go ahead and close this as the root issue is already identified in #3231, and the multiple gemspec files seems to have solved the problem we are facing. Thanks again!

**Comment by deivid-rodriguez** [comment]
Great, thanks!
