### ISSUE TITLE
Gemfile.lock with PLATFORMS set to java does not install java gems for JRuby 

### ISSUE THREAD

**Issue by cheister** [rubygems/rubygems#4354]
### Describe the problem as clearly as you can

With bundler 2.2.8 if you use a Gemfile.lock with a PLATFORMS set to `java` then bundler will try to install the C Ruby gems.  

### Post steps to reproduce the problem

With the following Gemfile
```
source 'https://rubygems.org'

gem 'zookeeper'
```

and Gemfile.lock
```
GEM
  remote: https://rubygems.org/
  specs:
    slyphon-log4j (1.2.15)
    slyphon-zookeeper_jar (3.3.5-java)
    zookeeper (1.4.11)
    zookeeper (1.4.11-java)
      slyphon-log4j (= 1.2.15)
      slyphon-zookeeper_jar (= 3.3.5)

PLATFORMS
  java
  ruby

DEPENDENCIES
  zookeeper

BUNDLED WITH
   2.1.4
```
And using JRuby 9.2.14.0.
```
> ruby --version
jruby 9.2.14.0 (2.5.7) 2020-12-08 ebe64bafb9 OpenJDK 64-Bit Server VM 11.0.9+11 on 11.0.9+11 [darwin-x86_64]
```

With bundler 2.1.4 you get
```
>  bundle _2.1.4_ install
Using bundler 2.1.4
Using slyphon-log4j 1.2.15
Using slyphon-zookeeper_jar 3.3.5 (java)
Using zookeeper 1.4.11 (java)
Bundle complete! 1 Gemfile dependency, 4 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

and with bundler 2.2.8 you get
```
>  bundle _2.2.8_ install
Fetching gem metadata from https://rubygems.org/......
Resolving dependencies...
Using bundler 2.2.8
Fetching zookeeper 1.4.11
Installing zookeeper 1.4.11 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
...
```

You can fix this by updating the PLATFORMS in the Gemfile.lock to something like `universal-java-11` instead of `java` but I expected bundler work with the old `java` PLATFORMS specification.   

I'm not sure if this was an intentional backwards incompatible change or if bundler 2.2.8 should work correctly with older Gemfile.lock files?

**Comment by deivid-rodriguez** [comment]
Hi @cheister!

We did create several unintentional backwards incompatibility issues with the 2.2.0 release, but we've been adding fixes to play nice with old lockfiles. It seems like we're still missing some cases.

I'll have a look at this, thanks for reporting!

**Comment by ThomasKoppensteiner** [comment]
I had a similar issue. Installing the dependencies worked with version `2.2.6`, but failed with `2.2.9`. Bundler tried to install the MRI/Ruby version not the JRuby/Java version of a gems dependency.

**Comment by deivid-rodriguez** [comment]
I'm working on a fix now :+1:

**Comment by ThomasKoppensteiner** [comment]
@deivid-rodriguez can you give us an outlook, when you fix will be released?

**Comment by deivid-rodriguez** [comment]
Today.
