### ISSUE TITLE
rubygems.org resolves to non-responsive IPv6 addresses 

### ISSUE THREAD

**Issue by ddfreyne** [rubygems/rubygems#4357]
`gem update` fails over IPv6:

```
% gem update
ERROR:  While executing gem ... (Gem::RemoteFetcher::UnknownHostError)
    timed out (https://rubygems.org/specs.4.8.gz)
```

The `curl -6 rubygems.org` command times out, e.g.

```
% curl -6 rubygems.org
curl: (7) Failed to connect to rubygems.org port 80: Operation timed out
```

The AAAA records for rubygems.org are as follows:

```
rubygems.org.		43	IN	AAAA	2a04:4e42:200::644
rubygems.org.		43	IN	AAAA	2a04:4e42::644
rubygems.org.		43	IN	AAAA	2a04:4e42:600::644
rubygems.org.		43	IN	AAAA	2a04:4e42:400::644
```

Any of these IP addresses fails to connect (timeout):

```
% curl http://[2a04:4e42::644]
curl: (7) Failed to connect to 2a04:4e42::644 port 80: Operation timed out

% curl http://[2a04:4e42:200::644]
curl: (7) Failed to connect to 2a04:4e42:200::644 port 80: Operation timed out

% curl http://[2a04:4e42:400::644]
curl: (7) Failed to connect to 2a04:4e42:400::644 port 80: Operation timed out

% curl http://[2a04:4e42:600::644]
curl: (7) Failed to connect to 2a04:4e42:600::644 port 80: Operation timed out
```

This issue is related to:

  - [x] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.2.7
```

```
$ ruby --version
ruby 3.0.0p0 (2020-12-25 revision 95aff21468) [x86_64-darwin20]
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by simi** [comment]
```
❤ curl -I -6 https://rubygems.org
HTTP/2 200 
content-type: text/html; charset=utf-8
x-frame-options: SAMEORIGIN
x-xss-protection: 1; mode=block
x-content-type-options: nosniff
x-download-options: noopen
x-permitted-cross-domain-policies: none
referrer-policy: strict-origin-when-cross-origin
cache-control: max-age=0, private, must-revalidate
content-security-policy: default-src 'self'; font-src 'self' https://fonts.gstatic.com; img-src 'self' https://secure.gaug.es https://gravatar.com https://secure.gravatar.com https://*.fastly-insights.com; object-src 'none'; script-src 'self' https://secure.gaug.es https://www.fastly-insights.com; style-src 'self' https://fonts.googleapis.com; connect-src 'self' https://s3-us-west-2.amazonaws.com/rubygems-dumps/ https://*.fastly-insights.com https://fastly-insights.com https://api.github.com
set-cookie: ...
x-request-id: 82a36f59-6072-4b2d-9436-58ea11ca52af
x-runtime: 0.009974
strict-transport-security: max-age=31536000
x-backend: F_Rails 52.26.69.39:443
accept-ranges: bytes
date: Sun, 07 Feb 2021 11:37:43 GMT
via: 1.1 varnish
x-served-by: cache-fra19181-FRA
x-cache: MISS
x-cache-hits: 0
x-timer: S1612697863.066686,VS0,VE174
vary: Accept,Accept-Encoding,Fastly-SSL
etag: "9db2b17974c567acd013816e50422986"
server: RubyGems.org
```

```
❤ ping6 rubygems.org
PING rubygems.org(2a04:4e42::644 (2a04:4e42::644)) 56 data bytes
64 bytes from 2a04:4e42::644 (2a04:4e42::644): icmp_seq=1 ttl=57 time=30.5 ms
64 bytes from 2a04:4e42::644 (2a04:4e42::644): icmp_seq=2 ttl=57 time=26.3 ms
```

It works well here. Can you provide more info? Can you reach it by IPv4? Anything strange in `traceroute6` output?

**Comment by ddfreyne** [comment]
Looks like the entirety of Fastly (which rubygems.org uses) is inaccessible to me. Yikes. The problem might be with my ISP (Deutsche Telekom), which wouldn’t surprise me as it has continuously been having connectivity problems.

**Comment by deivid-rodriguez** [comment]
Hi @ddfreyne!

We've actually been looking for someone with ipv6 setup, but having connectivity issues, in order to try out #2662 in real life. Basically that PR implements a friendly fallback behaviour, so that we don't timeout at all as long as either one of ipv4 or ipv6 works fine. It sounds like the fix for this might happen inside ruby itself in the end, but I still believe it would be valuable for us if we verify that the approach in that PR fixes the issue.

**Comment by ddfreyne** [comment]
@deivid-rodriguez It looks like my IPv6 connectivity breaks once in a while. Right now, I’m getting the same error (wrapped in a Bundler error, but probably same thing: `Bundler::HTTPError Could not fetch specs from https://rubygems.org/ due to underlying error <timed out (https://rubygems.org/specs.4.8.gz)>`).

How can I test out #2662 on my machine? I’ve attempted to clone @sonalkr132’s `ipv6-fallback` branch and run `ruby setup.rb` there, but then afterwards, there does not appear to be an IPv6 fallback:

```
% gem update
ERROR:  While executing gem ... (Gem::RemoteFetcher::UnknownHostError)
    timed out (https://rubygems.org/specs.4.8.gz)

% gem --version
3.2.0.rc.1
```

**Comment by deivid-rodriguez** [comment]
I'd say that means that the proposed solution is not working as expected, which confirms a separate report of another user who also tried it and reported the same thing. This one is tough :(

**Comment by deivid-rodriguez** [comment]
Thanks for trying it, though. I'd suggest you run `gem update --system` now to upgrade to the latest released version, which doesn't fix this issue but should be more stable :)

**Comment by sonalkr132** [comment]
>  clone @sonalkr132’s ipv6-fallback branch and run ruby setup.rb there

I hope you also added `:ipv4_fallback_enabled: true` to ~/.gemrc or env `IPV4_FALLBACK_ENABLED='true`. Another certain way to enforcing IPv4 is running following on your host:
```
sudo sysctl -w net.ipv6.conf.all.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.default.disable_ipv6=1
sudo sysctl -w net.ipv6.conf.lo.disable_ipv6=1
```

If any of these work, please do reach out to us through support@rubygems.org, we will try to loop in Fastly support.

**Comment by ddfreyne** [comment]
My IPv6 connectivity is back to normal so I can’t test this (for now). I’ll revisit this once it breaks again!

**Comment by deivid-rodriguez** [comment]
Oh right @sonalkr132! Both here and in the other case when someone tested this in real life I forgot to point out that this is opt-in and needs to be explicitly enabled :disappointed:.

**Comment by ddfreyne** [comment]
I got the opportunity to test this out: https://github.com/rubygems/rubygems/pull/2662#issuecomment-779730989
