### ISSUE TITLE
bundle cache --all-platforms removes other platform versions of gems from lockfile and does not cache them

### ISSUE THREAD

**Issue by aaronjensen** [rubygems/rubygems#4358]
### Describe the problem as clearly as you can

`bundle cache --all-platforms` removes other platform versions of gems from lockfile and does not cache them

**As an aside:** Asking people to include their `bundle env` is insanely dangerous. It can have credentials in it. I'll open a separate issue for this.

### Post steps to reproduce the problem

Clone this repo:

https://github.com/aaronjensen/bundle-cache-bug-repro

Run `bundle cache --all-platforms`

### What were you expecting to happen?

- `Gemfile.lock` is not modified
- `vendor/cache` includes linux versions

### What actually happened?

- `Gemfile.lock` is modified, with linux versions removed
- `vendor/cache` does not include linux versions

## Environment

```
Bundler       2.2.8
  Platforms   ruby, x86_64-darwin-19
Ruby          2.7.2p137 (2020-10-01 revision 5445e0435260b449decf2ac16f9d09bae3cafe72) [x86_64-darwin19]
  Full Path   /Users/aaronjensen/.asdf/installs/ruby/2.7.2/bin/ruby
  Config Dir  /Users/aaronjensen/.asdf/installs/ruby/2.7.2/etc
RubyGems      3.2.8
  Gem Home    /Users/aaronjensen/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0
  Gem Path    /Users/aaronjensen/.gem/ruby/2.7.0:/Users/aaronjensen/.asdf/installs/ruby/2.7.2/lib/ruby/gems/2.7.0
  User Home   /Users/aaronjensen
  User Path   /Users/aaronjensen/.gem/ruby/2.7.0
  Bin Dir     /Users/aaronjensen/.asdf/installs/ruby/2.7.2/bin
Tools
  Git         2.28.0
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

**Comment by deivid-rodriguez** [comment]
Hi @aaronjensen, thanks for the report.

I'm not sure how or where that lockfile was generated, but I don't think `x86_86-linux` is a valid platform? In any case, when I run you repro application, I get the expected behavior: bundler adds my current platform (x86_64-linux) to the lockfile and includes linux versions in the cache.

**Comment by aaronjensen** [comment]
Ugh, I apparently ran `bundle lock --add-platform x86_86-linux`. No idea where I copy/pasted that from or if I just brainfarted while typing it. In any case, when I use `bundle lock --add-platform x86_64-linux` it works as expected. Sorry for the noise.

**Comment by deivid-rodriguez** [comment]
No problem!
