### ISSUE TITLE
Confusing error messages with new security fixes

### ISSUE THREAD

**Issue by Fryguy** [rubygems/rubygems#4380]
### Describe the problem as clearly as you can

In our project we have some custom gems that are locked down to our custom gemserver using a `:source` directly in the Gemfile.  If I understand correctly, the new security fix now prefers that custom gem source for transient dependencies, and if there is an ambiguity across multiple gem sources for those transient dependencies, then bundling fails.  Where I am confused is when there _isn't_ an ambiguity and bundler still fails.  It may just be a confusing error message, but it's hard to tell.

The project is [ManageIQ](https://github.com/manageiq/manageiq), which has a custom public gemserver at https://rubygems.manageiq.org.  One of the offending gems seems to be our fork of handsoap, which is locked down [here](https://github.com/ManageIQ/manageiq/blob/323843e31a8a3c69c4e019f78580e671096a33cf/Gemfile#L86).  handsoap depends on nokogiri and yields the following error:

```text
The gem 'nokogiri' was found in multiple relevant sources.
  * rubygems repository https://rubygems.manageiq.org/ or installed locally
  * rubygems repository https://rubygems.org/ or installed locally
You must add this gem to the source block for the source you wish it to be installed from.
```

However, what's confusing is that nokogiri doesn't exist on https://rubygems.manageiq.org/ at all.  There is no ambiguity.  Even more confusing is what happens when you try to reproduce this error.

### Post steps to reproduce the problem

I was trying to reduce this, and I think this is as close as I can get.  I started with the following Gemfile, which "works":

```ruby
source "https://rubygems.org"
gem "handsoap", "=0.2.5.5", :source => "https://rubygems.manageiq.org"
```

I can't understand why that works, though, because both nokogiri and racc are not on https://rubygems.manageiq.org, but the Gemfile.lock is showing something completely different:

```text
GEM
  remote: https://rubygems.manageiq.org/
  specs:
    handsoap (0.2.5.5)
      nokogiri (>= 1.2.3)
    nokogiri (1.11.1-x86_64-darwin)
      racc (~> 1.4)
    racc (1.5.2)

GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  x86_64-darwin-19

DEPENDENCIES
  handsoap (= 0.2.5.5)!

BUNDLED WITH
   2.2.10
```

Even so, if I then add nokogiri

```ruby
source "https://rubygems.org"
gem "handsoap", "=0.2.5.5", :source => "https://rubygems.manageiq.org"
gem "nokogiri"
```

I get the following error

```text
The gem 'racc' was found in multiple relevant sources.
  * rubygems repository https://rubygems.manageiq.org/ or installed locally
  * rubygems repository https://rubygems.org/ or installed locally
You must add this gem to the source block for the source you wish it to be installed from.
```

Which, similar to the error I mentioned way above in the first section, is confusing because racc doesn't exist at all on https://rubygems.manageiq.org, and the fact that it passed the first time is even more confusing.

### Which command did you run?

bundle update

### What were you expecting to happen?

See above

### What actually happened?

See above

### If not included with the output of your command, run `bundle env` and paste the output below

<details>
<summary>bundle env</summary>

## Environment

```
Bundler       2.2.10
  Platforms   ruby, x86_64-darwin-19
Ruby          2.6.6p146 (2020-03-31 revision 67876) [x86_64-darwin19]
  Full Path   /Users/jfrey/.rubies/ruby-2.6.6/bin/ruby
  Config Dir  /Users/jfrey/.rubies/ruby-2.6.6/etc
RubyGems      3.0.3
  Gem Home    /Users/jfrey/.gem/ruby/2.6.6
  Gem Path    /Users/jfrey/.gem/ruby/2.6.6:/Users/jfrey/.rubies/ruby-2.6.6/lib/ruby/gems/2.6.0
  User Home   /Users/jfrey
  User Path   /Users/jfrey/.gem/ruby/2.6.0
  Bin Dir     /Users/jfrey/.gem/ruby/2.6.6/bin
Tools
  Git         2.26.1
  RVM         not installed
  rbenv       not installed
  chruby      0.3.9
```

## Bundler Build Metadata

```
Built At          2021-02-15
Git SHA           cc7c333721
Released Version  true
```

## Bundler settings

```
gem.test
  Set for the current user (/Users/jfrey/.bundle/config): "rspec"
gem.mit
  Set for the current user (/Users/jfrey/.bundle/config): true
gem.coc
  Set for the current user (/Users/jfrey/.bundle/config): true
```

### Gemfile

```ruby
source "https://rubygems.org"
gem "handsoap", "=0.2.5.5", :source => "https://rubygems.manageiq.org"
gem "nokogiri"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.manageiq.org/
  specs:
    handsoap (0.2.5.5)
      nokogiri (>= 1.2.3)
    nokogiri (1.11.1-x86_64-darwin)
      racc (~> 1.4)
    racc (1.5.2)

GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  x86_64-darwin-19

DEPENDENCIES
  handsoap (= 0.2.5.5)!

BUNDLED WITH
   2.2.10
```

</details>

**Comment by deivid-rodriguez** [comment]
Thanks for the ticket @Fryguy, we've been also reported a similar issue on Slack. There's something wrong here, I'll investigate.

**Comment by Fryguy** [comment]
@deivid-rodriguez  Thanks.  I'm happy to help where needed.  Feel free to use https://rubygems.manageiq.org if it would help

**Comment by deivid-rodriguez** [comment]
The fact that the first example works is expected to me. The way I approached this is to not fallback to the "block source" for direct and transitive dependencies that are present there, but if they are not present, pick them up from the global source. But the lockfile is just wrong.

**Comment by Fryguy** [comment]
Yes, I agree that the first one working makes sense.  I think I worded that incorrectly.  I wasn't surprised it worked, I was more surprised that it worked given the lockfile is wrong.

**Comment by Fryguy** [comment]
If it helps, playing with this a little more, if I continue and add racc to the Gemfile it "works" AND the Gemfile.lock is correct

```ruby
source "https://rubygems.org"
gem "handsoap", "=0.2.5.5", :source => "https://rubygems.manageiq.org"
gem "nokogiri"
gem "racc"
```

```text
GEM
  remote: https://rubygems.manageiq.org/
  specs:
    handsoap (0.2.5.5)
      nokogiri (>= 1.2.3)

GEM
  remote: https://rubygems.org/
  specs:
    nokogiri (1.11.1-x86_64-darwin)
      racc (~> 1.4)
    racc (1.5.2)

PLATFORMS
  x86_64-darwin-19

DEPENDENCIES
  handsoap (= 0.2.5.5)!
  nokogiri
  racc

BUNDLED WITH
   2.2.10
```

**Comment by deivid-rodriguez** [comment]
Oh, I see the issue now. Rubygems sources have this "or installed locally" fallback that's messing things up if you already have the gems installed.

**Comment by Fryguy** [comment]
@deivid-rodriguez  That's interesting, if I do a `gem uninstall nokogiri racc handsoap` before each of the 3 iterations above, each one now works AND all of the Gemfile.locks are correct.  I think you're onto something.

**Comment by deivid-rodriguez** [comment]
Yeah, I think it shouldn't be hard to fix, I'll work on it and try to push a fixed version tomorrow.

**Comment by deivid-rodriguez** [comment]
Hello everyone, sorry for this issue :pray:.

Can you try #4381 and verify whether it fixes your issues? Thanks!

**Comment by ThomasKoppensteiner** [comment]
Hey, with version `2.3.0.dev` i now can bundle again our service.

What I have noticed is, that the "specs" section for `remote: http://gems.runtastic.com/` is included twice in the `Gemfile.lock`. This happens for existing `Gemfile.lock` files as well as for new created ones.

```
GEM
  remote: http://gems.example.com/
  specs:
    ...

GEM
  remote: https://rubygems.org/
  specs:
    activemodel (5.2.4.5)
      activesupport (= 5.2.4.5)
   ...
    webmock (1.24.6)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
      hashdiff

GEM
  remote: https://rubygems.org/
  specs:
    activemodel (5.2.4.5)
      activesupport (= 5.2.4.5)
   ...
    webmock (1.24.6)
      addressable (>= 2.3.6)
      crack (>= 0.3.2)
      hashdiff
```

**Comment by deivid-rodriguez** [comment]
Thanks for trying that out @ThomasKoppensteiner!  So the sections are exactly the same right? That's definitely unexpected, I'll try to figure out now. I guess if I can't figure it out soon I'll still release the fix today and keep working on it after that, since it's a way smaller issue.

Any other confirmations that the fix works for usages out there are appreciated.

**Comment by deivid-rodriguez** [comment]
Just to make sure, you're not specifying `rubygems.org` both as a global and as a block source, right? Can you show the main source layout of the Gemfile?

**Comment by deivid-rodriguez** [comment]
Does this patch fix your issue @ThomasKoppensteiner?

```diff
diff --git a/bundler/lib/bundler/source_list.rb b/bundler/lib/bundler/source_list.rb
index 4ba6415448..15e7c5ce9b 100644
--- a/bundler/lib/bundler/source_list.rb
+++ b/bundler/lib/bundler/source_list.rb
@@ -89,7 +89,7 @@ def get(source)
     def lock_sources
       lock_sources = (path_sources + git_sources + plugin_sources).sort_by(&:to_s)
       if disable_multisource?
-        lock_sources + rubygems_sources.sort_by(&:to_s)
+        lock_sources + rubygems_sources.sort_by(&:to_s).uniq
       else
         lock_sources << combine_rubygems_sources
       end
```

**Comment by ThomasKoppensteiner** [comment]
Yes, the sections are exactly the same.

You are right `rubygems.org` is used twice in the `Gemfile`.

```
source "https://rubygems.org"

group :test, :ci, :development do
  ...
  gem "rubocop_runner", require: false, source: "https://rubygems.org"
end
```

When I remove the `"rubocop_runner"` line from the test group, the section is only include once.

**Comment by sliiser** [comment]
> Any other confirmations that the fix works for usages out there are appreciated.

Had an issue with gem 'connection_pool' and sidekiq pro. Broken on 2.3.0.dev master. Works on 2.3.0.dev fix_regression_in_source_priority.

Regular bundle install did update a lot of gems though (patch version). Not sure that's intended with an existing Gemfile.lock.

**Comment by ThomasKoppensteiner** [comment]
@deivid-rodriguez the patch would fix it.

Changing the `Gemfile` as below also fixes the duplicate sections for me:
```
source "https://rubygems.org"

gem "rubocop_runner", require: false,  group: %i[test ci development]
```

**Comment by ThomasKoppensteiner** [comment]
> Regular bundle install did update a lot of gems though as if I ran a bundle update. Probably not intended with an existing Gemfile.lock.
Same for me

**Comment by deivid-rodriguez** [comment]
That's great to hear @sliiser!

@ThomasKoppensteiner Alright! I'm unsure whether I should patch the duplication thing. It doesn't seem to create any issues and it did point out an unnecessary duplication in yout Gemfile, so I tend to believe it's better to leave as is? Maybe we could improve it to auto-fix things and print a warning, but it doesn't seem urgent.

Regarding  the unnecessary updates, it seems like an issue with source unlocking, probably was always there but was surfaced by the recent change. Can you try it with the `BUNDLE_UNLOCK_SOURCE_UNLOCKS_SPEC=false` environment variable?

**Comment by ThomasKoppensteiner** [comment]
Using `BUNDLE_UNLOCK_SOURCE_UNLOCKS_SPEC=false` has no effect for me. I still see the gem updates.

**Comment by deivid-rodriguez** [comment]
Too bad. I'll see if I can figure that out too, but won't block this fix either of course.

**Comment by sliiser** [comment]
> Using `BUNDLE_UNLOCK_SOURCE_UNLOCKS_SPEC=false` has no effect for me. I still see the gem updates.

Same here

**Comment by pirj** [comment]
Do you think it would be possible to yank 3.2.10 from RubyGems to fix everyone's CI failures (3.2.9 will be used as the latest)?
The problem could be addressed in a less heated mode then.

**Comment by deivid-rodriguez** [comment]
I don't want to yank things, I'll just release a new version. People locking their versions didn't hit the issue, and people not locking their versions will get it automatically fixed when I release. Planning to release in a couple of hours approx.

**Comment by deivid-rodriguez** [comment]
I'm sorry for the delay, it won't be two hours in the end since our CI found some issues and I'll have to leave the computer for a few hours now. But I'll get back to it as soon as I'm back and release as soon as I'm done.

**Comment by Envek** [comment]
One more use case that is broken in 2.2.10: testing against head versions of multiple gems in single source (like rails):

```ruby
git "https://github.com/rails/rails.git" do
  gem "rails"
  gem "activerecord"
end
```

In 2.2.10 it will fail with following error:
```
The gem 'activesupport' was found in multiple relevant sources.
  * https://github.com/rails/rails.git (at main@0f09dfc)
  * rubygems repository https://rubygems.org/ or installed locally
You must add this gem to the source block for the source you wish it to be installed from.
```

I tested #4381 and it fixes this issue for me, so I'm waiting for it to be released.

**Comment by deivid-rodriguez** [comment]
Thanks for testing #4381 @Envek, I'm currently fixing some issues with it but it should be ready soon.

**Comment by Sunakujira1** [comment]
We were facing a similar issue with the latest bundler and confirmed downgrading to the previous patch version fixed the issue. Temp fix until it is addressed into new version:
```
gem install bundler -v 2.2.9
```

**Comment by deivid-rodriguez** [comment]
Quick update from my side. I'm back in front of the computer now but it's 11pm where I live and I'm quite tired. New issues have been raised with my proposed fix. I'll have a look at it tomorrow and try to find a satisfactory solution for those issues. If I can't figure out quickly, I'll revert the PR. So either way, I'm aiming at releasing a new version tomorrow that restores a sane behaviour.

I apologize for the inconveniences caused. Mistakes happen unfortunately.

**Comment by deivid-rodriguez** [comment]
I ended up reverting the pull request that broke things and released it as 2.2.11. I'll try to reintroduce the more secure mode I wanted to introduce without breaking things in future releases.

**Comment by deivid-rodriguez** [comment]
I'm planning to start shipping some fixes regarding this in the next days. I added coverage for the issues raised with 2.2.10 but extra testing never hurts, so if someone wants to check that https://github.com/rubygems/rubygems/pull/4418 doesn't break anything, I appreciate that.

**Comment by Fryguy** [comment]
Thanks @deivid-rodriguez ...I'll take a look

**Comment by Fryguy** [comment]
@deivid-rodriguez I did a quick `bundle install`, `bundle update`, `bundle exec`, and everything seems to be working good.

Note that ManageIQ may not be fully representative, because we intentionally have different version numbers in rubygems.manageiq.org than rubygems.org, and in our app we use "=" to ensure we only pull that version.  For example, we have `gem "handsoap", "=0.2.5.5", :source => "https://rubygems.manageiq.org"` and 0.2.5.5 _only_ exists in our gem repository.  For completeness, there should be a test where a gem with the same version appears in multiple repositories.

**Comment by deivid-rodriguez** [comment]
Yep, we have tests for that.

We test the case with the exact same version in multiple repositories (which currently passes, pulling the dependency from the most specific source), and the case with a higher version in the outermost source (which currently does the wrong thing, but I hope to fix soon).

**Comment by ThomasKoppensteiner** [comment]
@deivid-rodriguez the version from #4418 works for me. Thank you.

**Comment by Envek** [comment]
I tested [this](https://github.com/rubygems/rubygems/issues/4380#issuecomment-779848411) case (with some of rails gems installed from git) with the version from #4418 and it looks like it works! Thanks! :tada:

**Comment by deivid-rodriguez** [comment]
Wow, thanks everyone for stepping in and early testing this. It gives me hope and confidence :)

**Comment by deivid-rodriguez** [comment]
Ok, 2.2.13 is out, hopefully I didn't break everything this time :pray:.

I have a second improvement in source priority that I'd appreciate if you could try: https://github.com/rubygems/rubygems/pull/4381. Note that if you have an existing lockfile, you should get a warning and you'll need to run `bundle update` or generate it from scratch to get the more secure behaviour.

**Comment by deivid-rodriguez** [comment]
Hello again everyone! I finally managed to propose a general fix for this issue, so hopefully next week we'll have another release fixing "indirect dependency confusions". If anyone here would like to give it a try before that to make sure everything is fine with your Gemfiles & lockfiles, you're more than welcome. PR is here: #4609.
