### ISSUE TITLE
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

### ISSUE THREAD

**Issue by DanielDayZero** [rubygems/rubygems#4398]
I received this error: 
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=Permission+denied+%40+dir_s_mkdir+-+%2FUsers%2Fdanieldianati%2F.rbenv%2Fversions%2F3.0.0%2Flib%2Fruby%2Fgems%2F3.0.0%2Fextensions%2Fx86_64-darwin-20%2F3.0.0%2Fbindex-0.8.1&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/rubygems/rubygems/issues/new?labels=Bundler
         run  bundle binstubs bundler
Could not find gem 'sqlite3 (~> 1.4)' in any of the gem sources listed in your Gemfile.
       rails  webpacker:install
Could not find gem 'sqlite3 (~> 1.4)' in any of the gem sources listed in your Gemfile.

**Comment by deivid-rodriguez** [comment]
Unfortunately this issue doesn't include helpful information for us to help you. It should for example include a backtrace which you didn't copy here.

Feel free to include more relevant information so that we can help you and reopen the ticket.

Thanks!

**Comment by aflaco** [comment]
I have same problem.
I don't know how it solve?

**Comment by deivid-rodriguez** [comment]
Feel free to open a new ticket, but please include as much information as possible so that we can reproduce the problem in our machines, otherwise it's very unlikely that we can help you.
