### ISSUE TITLE
CVE for Bundler 2.2.10 because it installs wrong versions?

### ISSUE THREAD

**Issue by ghbren** [rubygems/rubygems#4405]
Would you be able to file a CVE for bundler 2.2.10 because it installs wrong gem versions? https://github.com/rubygems/rubygems/issues/4383

That way, this issue can be added to ruby-advisory-db and then bundle audit will flag bundler 2.2.10 uses.

Thank you.

**Comment by deivid-rodriguez** [comment]
Hi, thanks for the report. I'm personally against considering that bug a security issue. The effects of it are similar to not using a lockfile at all, and while we strongly recommend that, we have never claimed that not using a lockfile is a security issue.

**Comment by hsbt** [comment]
I also against to assign CVE number. Because the attack surface of this issue is a limited environment and condition.
