### ISSUE TITLE
Usability change: when "Enter your RubyGems.org credentials." is asked to the user, and the user types in Email and Password, store these persistently the moment the user has finished typing this.

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems#4420]
Hey there rubygems devs,

Before I describe my proposed change to "gem" functionality, allow me to first describe the
problem.

My current openssl installation is borked, or rather, the ruby wrapper around it.

Example:

/home/Programs/Ruby/2.7.2/bin/ruby: symbol lookup error: /home/Programs/Ruby/2.7.2/lib/ruby/2.7.0/x86_64-linux/openssl.so: undefined symbol: SSL_CTX_get_options

Now, I am investigating this and may solve it. But this issue is not primarily
about that problem.

I have just tried to publish a new gem, but the above error prevents me from
publishing the .gem.

Note: the issue here is also NOT about that part.

The issue is a small usability problem.

Right now, when the above error hits, I have to type in my email, and my
password. So the second time I hit this error, it again does not store my
data, and instead asks me again the next time (since I can not resolve
the openssl problem right now).

This is not a big deal but still annoying, because the program asks me
to provide information which I ALREADY provided just a minute ago.

I suppose I can simply back up an old credentials file, but I still think
it would be more elegant if the current behaviour could be adapted
a bit.

The change that would be required is that after the user did input
these two strings (I assume they are stored as strings internally),
this will be persistently stored.

I am not sure whether "gem" itself does something behind the
scene which would require the user to have openssl available
in order to store email and login-password, but that would not
make sense to me, IMO, so it would be better to just save this
information before the above error can hit. After all the user
already DID try to provide that information and it would be
stored somewhere normally anyway, so this is really about
the USER having to input this information more than once.

Here is the full output:

Enter your RubyGems.org credentials.
Don't have an account yet? Create one at https://rubygems.org/sign_up
   Email:   EMAIL_WENT_HERE@gmail.com
Password:   

/home/Programs/Ruby/2.7.2/bin/ruby: symbol lookup error: /home/Programs/Ruby/2.7.2/lib/ruby/2.7.0/x86_64-linux/openssl.so: undefined symbol: SSL_CTX_get_options

**Comment by deivid-rodriguez** [comment]
Problem is, as far as I understand, we use your credentials to fetch your API key for the operation you're trying to attempt from rubygems.org (or create a new one if you don't yet have one), and what's saved to local storage is your scoped API key, not your full rubygems.org crredentials. Fixing this issue would mean storing your full credentials, which I don't believe we want to do. So I don't see any solution for this.

@sonalkr132 may have more insights.
