### ISSUE TITLE
bundler 2.2.13 causes gdk_pixbuf2-3.4.3/dependency-check to fail on linux

### ISSUE THREAD

**Issue by briantoth** [rubygems/rubygems#4427]
### Describe the problem as clearly as you can

Could not find "rake2.7".

```
Installing gdk_pixbuf2 3.4.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory:
/builds/briantoth/testing-bundler/vendor/bundle/ruby/2.7.0/gems/gdk_pixbuf2-3.4.3/dependency-check
rake2.7
RUBYARCHDIR\=/builds/briantoth/testing-bundler/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/gdk_pixbuf2-3.4.3
RUBYLIBDIR\=/builds/briantoth/testing-bundler/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/gdk_pixbuf2-3.4.3
rake failedNo such file or directory - rake2.7
Gem files will remain installed in
```

### Post steps to reproduce the problem

I've created a fairly [minimal repro](https://gitlab.com/briantoth/testing-bundler/-/tree/master).  

A passing job can be found [here](https://gitlab.com/briantoth/testing-bundler/-/jobs/1071921309).

A failing job can be found [here](https://gitlab.com/briantoth/testing-bundler/-/jobs/1071926699).

### Which command did you run?

`bundle install --without development --path vendor/bundle`

### What were you expecting to happen?

success

### What actually happened?

```
Installing gdk_pixbuf2 3.4.3 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
current directory:
/builds/briantoth/testing-bundler/vendor/bundle/ruby/2.7.0/gems/gdk_pixbuf2-3.4.3/dependency-check
rake2.7
RUBYARCHDIR\=/builds/briantoth/testing-bundler/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/gdk_pixbuf2-3.4.3
RUBYLIBDIR\=/builds/briantoth/testing-bundler/vendor/bundle/ruby/2.7.0/extensions/x86_64-linux/2.7.0/gdk_pixbuf2-3.4.3
rake failedNo such file or directory - rake2.7
Gem files will remain installed in
```

### If not included with the output of your command, run `bundle env` and paste the output below

My local environment is windows and does not have this issue.

**Comment by deivid-rodriguez** [comment]
I think this is a regression of https://github.com/rubygems/rubygems/pull/4409. In that PR I made the assumption that specs don't need to be made immediately available during `bundle install`. That's true in general but I missed the one and only exception: `rake`. In the case of `rake`, it needs to always be installed first (bundler already special cases `rake` to do this), and be made available immediately so that gems with `rake` extensions can use it to install themselves.

I'll try to fix this.

**Comment by deivid-rodriguez** [comment]
#4428 should fix this!

**Comment by briantoth** [comment]
Thanks for the quick turnaround!
