### ISSUE TITLE
Allow to execute the test suite from the content of release tarball.

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#4430]
I'd appreciate, if the content of release tarball was complete, so the included test suite can be executed. Currently, trying to execute the test suite from the tarball, it fails:

~~~
$ rake
rake aborted!
LoadError: cannot load such file -- util/automatiek.rake
~~~

Alternatively, please make sure the test suite is executable via command as simple as:

~~~
$ ruby -e 'Dir.glob "./test/**/test_*.rb", &method(:require)'
~~~

Then the tarball could stay in its current from and not all content required by Rake would be necessary.

**Comment by deivid-rodriguez** [comment]
Feel free to submit a pull request :+1:.
