### ISSUE TITLE
bundler 2.2.13 cannot install a specific Gemfile involving a :git source, where earlier Bundlers can install same gemfile

### ISSUE THREAD

**Issue by jrochkind** [rubygems/rubygems#4439]
### Describe the problem as clearly as you can

This is a Gemfile that bundler 2.2.12 and prior can install just fine, but Bundler 2.2.13 cannot. 

```
gem "rails", git: "https://github.com/rails/rails.git", branch: "main"
gem 'railties'
```

That's it, just those two lines.  I know this is an odd Gemfile because railties is already a dependency of rails and we aren't specifying any additional version or anything; but despite being odd, it still ought to work. This is a minimal reproduction. 

I don't believe these are relevant, but for completeness: ruby 2.7.1, rubygems 3.1.2. 

### Post steps to reproduce the problem

Create that Gemfile. Make sure you have **no existing Gemfile.lock**. With an existing Gemfile.lock, the bug might *not* reproduce, but it does reliably with no `Gemfile.lock` present. 

#### With bundler 2.2.12:

```
jrochkind-chf gemfiletest  $ bundle -v
Bundler version 2.2.12

jrochkind-chf gemfiletest  $ cat Gemfile
gem "rails", git: "https://github.com/rails/rails.git", branch: "main"
gem 'railties'

jrochkind-chf gemfiletest  $ rm Gemfile.lock
rm: Gemfile.lock: No such file or directory

jrochkind-chf gemfiletest  $ bundle install
Fetching https://github.com/rails/rails.git
Resolving dependencies...
Using rake 13.0.3
Using concurrent-ruby 1.1.8
Using minitest 5.14.4
Using zeitwerk 2.4.2
Using builder 3.2.4
Using rack 2.2.3
Using racc 1.5.2
Using websocket-extensions 0.1.5
Using erubi 1.10.0
Using mini_mime 1.0.2
Using nio4r 2.5.7
Using bundler 2.2.12
Using method_source 1.0.0
Using thor 1.1.0
Using tzinfo 2.0.4
Using i18n 1.8.9
Using rack-test 1.1.0
Using crass 1.0.6
Using sprockets 4.0.2
Using mail 2.7.1
Using mimemagic 0.3.5
Using activesupport 7.0.0.alpha from https://github.com/rails/rails.git (at main@43a7f68)
Using marcel 0.3.3
Using nokogiri 1.11.1 (x86_64-darwin)
Using websocket-driver 0.7.3
Using loofah 2.9.0
Using rails-html-sanitizer 1.3.0
Using rails-dom-testing 2.0.3
Using globalid 0.4.2
Using actionview 7.0.0.alpha from https://github.com/rails/rails.git (at main@43a7f68)
Using activejob 7.0.0.alpha from https://github.com/rails/rails.git (at main@43a7f68)
Using activemodel 7.0.0.alpha from https://github.com/rails/rails.git (at main@43a7f68)
Using actionpack 7.0.0.alpha from https://github.com/rails/rails.git (at main@43a7f68)
Using activerecord 7.0.0.alpha from https://github.com/rails/rails.git (at main@43a7f68)
Using actioncable 7.0.0.alpha from https://github.com/rails/rails.git (at main@43a7f68)
Using activestorage 7.0.0.alpha from https://github.com/rails/rails.git (at main@43a7f68)
Using railties 7.0.0.alpha from https://github.com/rails/rails.git (at main@43a7f68)
Using sprockets-rails 3.2.2
Using actiontext 7.0.0.alpha from https://github.com/rails/rails.git (at main@43a7f68)
Using actionmailbox 7.0.0.alpha from https://github.com/rails/rails.git (at main@43a7f68)
Using actionmailer 7.0.0.alpha from https://github.com/rails/rails.git (at main@43a7f68)
Using rails 7.0.0.alpha from https://github.com/rails/rails.git (at main@43a7f68)
Bundle complete! 2 Gemfile dependencies, 42 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

#### With bundler 2.2.13

```
jrochkind-chf gemfiletest  $ bundle -v
Bundler version 2.2.13

jrochkind-chf gemfiletest  $ cat Gemfile
gem "rails", git: "https://github.com/rails/rails.git", branch: "main"
gem 'railties'

jrochkind-chf gemfiletest  $ rm Gemfile.lock

jrochkind-chf gemfiletest  $ bundle install
Fetching https://github.com/rails/rails.git
Resolving dependencies...
Your Gemfile has no gem server sources. If you need gems that are not already on your machine, add a line like this to your Gemfile:
source 'https://rubygems.org'
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    railties

    rails was resolved to 7.0.0.alpha, which depends on
      railties (= 7.0.0.alpha)

Could not find gem 'railties (= 7.0.0.alpha)', which is required by gem 'rails', in any of the relevant sources:
  locally installed gems

```

I expect bundler 2.2.13 to be able to install that Gemfile same as 2.2.12 did. Don't expect backwards-breaking changes in a patch release.

**Comment by deivid-rodriguez** [comment]
Yes, this is due to https://github.com/rubygems/rubygems/pull/4418, which I consider a bug fix, that's why we shipped it in a patch release.

 In your `Gemfile`, you're explicitly stating that you want to pull `railties` from your global source, and since you didn't specificy any global source at all, that means " "locally installed gems".

Previously bundler would accidentally "work" by pulling this dependency from the "https://github.com/rails/rails.git" (or actually, from any other source which has that dependency, in a non deterministic manner).

Any bug fix can be seen as a breaking change if you rely on the buggy behavior :man_shrugging:. Please fix your Gemfile.

**Comment by jrochkind** [comment]
@deivid-rodriguez Sorry, it still reproduces if I specify a global source, my mistake in not realizing that was possibly relevant in distinguishing between bug and not bug. 

With this Gemfile:

```
source 'https://rubygems.org'

gem "rails", git: "https://github.com/rails/rails.git", branch: "main"
gem 'railties'
```

It still installs with 2.2.12, but fails with 2.2.13. 

It does have a very slightly different error message in 2.2.13 then the one I reported. Sorry for going too far in paring down the reproduction, I should have included the "source" line in reproduction:

```
Bundler could not find compatible versions for gem "railties":
  In Gemfile:
    railties

    rails was resolved to 7.0.0.alpha, which depends on
      railties (= 7.0.0.alpha)

Could not find gem 'railties (= 7.0.0.alpha)', which is required by gem 'rails', in any of the relevant sources:
  rubygems repository https://rubygems.org/ or installed locally
```

The diagnosis is still the same though, i was accidentally relying on buggy behavior before?

OK! I did not realize I was relying on buggy behavior before, but it happens!

**Comment by deivid-rodriguez** [comment]
It's still a bug.

The meaning of this Gemfile is "I want to pull rails and its dependencies from `https://github.com/rails/rails.git`, but `railties` from `https://rubygems.org`. This is impossible because the git source contains `rails-7.0.0.alpha`, which has an exact dependency on `railties-7.0.0.alpha`. However, `railties-7.0.0.alpha` does not exist on `https://rubygems.org`, which you explicitly stated you wanted to pull `railties` from.

Bundler 2.2.12 would mistakenly ignore the correct source for `railties` and pick it up from `https://github.com/rails/rails.git` instead. Bundler 2.2.13 correctly prints a resolution error about not being able to find the necessary version of `railties` in the source specified for it.

You can fix your Gemfile by removing the direct dependency on `railties` if you want it to be pulled from `https://github.com/rails/rails.git`.

**Comment by jrochkind** [comment]
Aha, I get it, thanks!

Specifying the same source for both also works. 

```
gem "rails", git: "https://github.com/rails/rails.git", branch: "main"
gem 'railties', git: "https://github.com/rails/rails.git", branch: "main"
```

**Comment by deivid-rodriguez** [comment]
No problem!

You can also specify

```ruby
git "https://github.com/rails/rails.git", branch: "main" do
  gem 'rails'
  gem 'railties'
end
```

for a bit of extra DRYness.

And since recent versions, `git: "https://github.com/rails/rails.git"` should just work without having to specify the branch explicitly.
