### ISSUE TITLE
Allow `bundle install --standalone` to work with `--local` option

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#4445]
This is followup to rubygems/rfcs/issues/32. I am trying to use `bundle install --standalone --local` to reuse system installed packages, but it does not work:

~~~
$ gem list erubi

*** LOCAL GEMS ***

erubi (1.10.0)

$ bundle install --local 
Resolving dependencies...
Using bundler 2.2.3
Using erubi 1.10.0
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.

$ bundle install --local --standalone
Could not find erubi-1.10.0 in any of the sources
~~~

**Comment by voxik** [comment]
Sorry, I should have provide also the `Gemfile`:

~~~
$ cat Gemfile
source 'https://rubygems.org'

gem 'erubi'
~~~

**Comment by deivid-rodriguez** [comment]
I suspect this could be related to https://github.com/rubygems/rubygems/issues/4088 or https://github.com/rubygems/rubygems/issues/3262.

**Comment by deivid-rodriguez** [comment]
@voxik I made this work at #5762. I think there's room for improvement but at least now it does something useful I believe. Feel free to check it out.
