### ISSUE TITLE
Duplicate Sections in Gemfile.lock

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [rubygems/rubygems#4448]
Bundler version `2.2.14` duplicates the "GEM remote: https://rubygems.org/" section in the Gemfile.lock, if it is specified twice in the `Gemfile`. This doesn't happen for Bundler version `2.2.13`.

I create a [this repository](https://github.com/ThomasKoppensteiner/bundler_duplicate_sections) containing some minimum working examples.

A similar behavior was discussed [here](https://github.com/rubygems/rubygems/issues/4380#issuecomment-779698508). 

I'm not sure if this causes any problems, but the `Gemfile.lock` becomes unnecessarily large and harder to review.

**Comment by deivid-rodriguez** [comment]
It should be fixed by #4456, thanks for the report!
