### ISSUE TITLE
bundle install - world-writable warnings while running in Jenkins-Agent /tmp/workspace folder

### ISSUE THREAD

**Issue by tbugfinder** [rubygems/rubygems#4466]
### Describe the problem as clearly as you can

While executing bundle install within a Jenkins Agent there is a warning message about world-writable /tmp for each gem being installed.
https://github.com/rubygems/rubygems/blob/6ebda1df79f660d5e4ed4269b362c229a8770667/bundler/lib/bundler/vendor/tmpdir/lib/tmpdir.rb#L33

As the /tmp location is used by design and permissions are also given by the base image, I'm wondering how to get rid of this message easily - as it doesn't make sense in this context (for me).

### Which command did you run?

bundle config --local path ./vendor/bundle # in /tmp/workspace/<project>
bundle install --jobs=8

### What were you expecting to happen?

less warnings or even none

### What actually happened?

Getting warning messages about permissions of /tmp (2777).

**Comment by deivid-rodriguez** [comment]
This code is actually part of https://github.com/ruby/tmpdir, which we vendor inside `bundler`.

However, it is true that it was me who requested this feature, due to losing a lot of time debugging a case where a user had `ENV["TMP"]` set, but to a folder with incorrect permissions, so `tmpdir` was silently ignoring it. I figured warning that `Dir.tmpdir` is refusing to use the directory you have set would be a good idea. However, I think the warning message should probably also inform about the directory being used instead.

In your case, I think `Dir.tmpdir` is falling back to `.` as a last resort folder to use for temporary files. If that behaviour works for you, you can avoid the warning by explicitly setting `ENV["TMPDIR"]` to the current folder.

**Comment by tbugfinder** [comment]
I need another few days to verify. Thank you very much.

**Comment by deivid-rodriguez** [comment]
Closing for now. If you're still having issues when you get to verify this, let us know!

**Comment by AlexWayfer** [comment]
> Closing for now. If you're still having issues when you get to verify this, let us know!

I have the same with Cirrus CI, for example: https://cirrus-ci.com/task/6159541332082688?logs=bundle_install#L2

BTW, they have related issue: https://github.com/cirruslabs/cirrus-ci-docs/issues/814

**Comment by deivid-rodriguez** [comment]
Did you try to change TMPDIR to the CWD as suggested? I mean, it should be Cirrus CI that should change this, so that end users don't need to change it to avoid the warnings, but it'd be nice if someone tried it to verify my assumption of what's going on.

**Comment by AlexWayfer** [comment]
I didn't, but I have plans to. Anyway, the expected result from this issue is "less warnings or even none", and I can agree with the less, because warning is OK, maybe 2 or 3, but dozens of them look like a flood. But, as you wish, of course.

**Comment by deivid-rodriguez** [comment]
I see. Changing TMPDIR to the CWD should eliminate all warnings.

I totally understand wanting this warning as few times as possible, I think the `tmpdir` library can be changed to do that. It's a bit tricky because the `ENV` variables involved and the CWD can change at any time. So, even if the resolved temp folder is memoized/cached, that cache needs to be invalidated when these inputs change. It seems like it can be done, though. I'll try to propose this to `tmpdir` and maybe implement it myself.

**Comment by AlexWayfer** [comment]
How can I do this dynamically (for unspecific dynamic CWD, for example) in CI (without execution for ENV value) for `bundle install`? 🤔 I could do this in Ruby code, but in the shell…

---

OK, fortunately, there is `CIRRUS_WORKING_DIR` variable and this change helped: https://github.com/filewatcher/filewatcher/pull/178

**Comment by Fryguy** [comment]
@deivid-rodriguez I know this is an old issue, but recently we upgraded our app to Ruby 3.0 and the output is painful, particularly in containers.  I assume it's because /tmp is mounted by docker as world writable, or perhaps this is specific to ubi?

Here's an example Dockerfile that only bundle installs a single gem:

```dockerfile
FROM registry.access.redhat.com/ubi8/ubi-minimal:latest

RUN microdnf module enable ruby:3.0 && \
    microdnf install -y ruby

RUN gem install bundler

RUN echo "source 'https://rubygems.org'" > /Gemfile
RUN echo "gem 'omg'" >> /Gemfile

CMD ["bundle"]
```

```bash
$ docker build . -t test
```

and here's the output

```
$ docker run --rm -it test
Don't run Bundler as root. Bundler can ask for sudo if it is needed, and installing your bundle as root will break this application for all non-root users on this machine.
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
Fetching gem metadata from https://rubygems.org/.system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
.system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
.system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
.system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
.system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
.system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
.system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
.system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
.system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp
.system temporary path is world-writable: /tmp
/tmp is world-writable: /tmp

Resolving dependencies...
Using bundler 2.3.25
Fetching omg 0.0.6
Installing omg 0.0.6
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

**Comment by Fryguy** [comment]
One last followup here - The "fix" for the ubi8/ubi9 container issue is to just add `RUN chmod +t /tmp` to your Dockerfile until such time as Red Hat fixes it.
