### ISSUE TITLE
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

### ISSUE THREAD

**Issue by Hassaangithub** [rubygems/rubygems#4468]
First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=Permission+denied+%40+dir_s_mkdir+-+%2FUsers%2Fmymac%2F.rbenv%2Fversions%2F3.0.0%2Flib%2Fruby%2Fgems%2F3.0.0%2Fextensions%2Fx86_64-darwin-19%2F3.0.0%2Fbindex-0.8.1&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/rubygems/rubygems/issues/new?labels=Bundler

**Comment by deivid-rodriguez** [comment]
Please copy the full output of the error. Thanks!

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
