### ISSUE TITLE
`bundle env` description/requirement for filling new issue is dangerous

### ISSUE THREAD

**Issue by ojab** [rubygems/rubygems#4479]
### Describe the problem as clearly as you can

`bundle env` output may contain credentials for http auth, so blindly pasting `bundle env` output into the issue will leak said credentials.

### Which command did you run?

```
bundle config --local github.com username:token
bundle env
```

**Comment by deivid-rodriguez** [comment]
We explicitly warn about this in the issue template, and plan to [redact credentials](https://github.com/rubygems/rubygems/issues/4414) from `bundle env`. So closing in favour of that issue.
