### ISSUE TITLE
Spurious warning: Your Gemfile lists the gem my-private-gem (>= 0) more than once

### ISSUE THREAD

**Issue by aaronjensen** [rubygems/rubygems#4481]
### Describe the problem as clearly as you can

If you have a gem that only exists in a non-default source in your gemspec listed as a development dependency, it does not appear to be possible to add it to your `Gemfile` without this warning appearing:

```
Your Gemfile lists the gem my-private-gem (>= 0) more than once.
You should probably keep only one of them.
Remove any duplicate entries and specify the gem only once.
While it's not a problem now, it could cause errors if you change the version of one of them later.
```

### Post steps to reproduce the problem

Clone and run bundle install:

https://github.com/aaronjensen/private-development-gem-warning-repro

### Which command did you run?

`bundle install`

### What were you expecting to happen?
No warning

### What actually happened?

Warning

### If not included with the output of your command, run `bundle env` and paste the output below

Bundler 2.2.15

**Comment by deivid-rodriguez** [comment]
@aaronjensen I'll have a look at this issue anyways, but I think removing `add_development_dependency` from the gemspec should do the trick? The `add_development_dependency` method is something legacy from a pre-bundler world, but if you use `bundler`, you don't really need it. We even considered deprecating it, but we haven't gone as far yet.

**Comment by aaronjensen** [comment]
Ah, ok. I had wondered about its value. I’ll remove it in our Gemfiles, thanks.

**Comment by deivid-rodriguez** [comment]
No problem! Just to make sure, you should remove it from your `gemspec`s and add it to your `Gemfile`s.
