### ISSUE TITLE
2.2.15 incompatible with elasticsearch 6 on Circle CI

### ISSUE THREAD

**Issue by iamwhil** [rubygems/rubygems#4483]
### Describe the problem as clearly as you can

With bundler 2.2.15 on Circle CI if you're installing a dockerized elasticsearch v6 image and then utilizing bundler 2.2.15 a memory leak occurs.  The docker image is going to run out of memory and exit with code 137.

**Comment by deivid-rodriguez** [comment]
@iamwhil I believe it's unlikely that this is an issue with `bundler`, so I'm going to close this. I could perfectly be wrong, so feel free to reopen this providing a sample CircleCI setup that fails with bundler 2.2.15 and works with bundler 2.2.14. Thanks!
