### ISSUE TITLE
Enhancement Request: DSL Method for Chef Cookbooks' dependency management for Gems

### ISSUE THREAD

**Issue by jamietanna** [rubygems/rubygems#4486]
# Reasoning

When working with the [Chef configuration management tool](https://www.chef.io/), there is the ability to add Ruby Gem dependencies to the cookbook.

These are configured using Chef's [`metadata.rb`](https://docs.chef.io/config_rb_metadata/), and if folks want to perform local testing, they need to install these gems separately using Bundler, which requires duplication of potentially many gems.

# Enhancement Requested

Provide an enhancement to [`Bundler::Dsl`](https://ruby-doc.org/stdlib-2.7.0/libdoc/bundler/rdoc/Bundler/Dsl.html), which allows for `chef_metadata` as a means to perform this automagically, similar to `gemspec`.

# Alternatives

- As noted [in my blog post](https://www.jvt.me/posts/2021/03/24/chef-cookbook-gem-metadata/), is to update our `Gemfile` to perform the insertion of these gems ourselves, although less pretty than a handy DSL.
- Monkey patching `Bundler::Dsl` before bundler is run to install gem dependencies for local development

# Considerations

I realise this would tie the Bundler project to Chef, and depending on how this is done, may lead to unnecessary dependencies, and overhead for maintenance.

**Comment by deivid-rodriguez** [comment]
@jamietanna Unfortunately, I think your last comment is completely right. This ties `bundler` to `chef` and adds additional maintenance burden for us.

I think what you did in your blog post is pretty simple and should work just fine!

**Comment by jamietanna** [comment]
Thanks for the super speedy reply! Shall I keep this issue open, in case things change, or shall I close? ☺

(Originally published at: https://www.jvt.me/mf2/2021/03/9yexn/)

**Comment by deivid-rodriguez** [comment]
I don't think we'll be implementing this, we already have too many features to maintain, sorry :pray:. So yeah please close it!
