### ISSUE TITLE
ERROR:  Could not find a valid gem '1.17.3' (>= 0) in any repository

### ISSUE THREAD

**Issue by prabhavathi2210** [rubygems/rubygems#4489]
RUN gem install bundler $(tail -n 1 Gemfile.lock | xargs) && \
    install bundle. #on redhat image
----------------------------------------------------------------------------------------------------

I AM TRYING TO EXCUTE THIS CODE INSIDE DOCKERFILE. Can anyone please help me on this 

=> ERROR [10/9] RUN gem install bundler $(tail -n 1 Gemfile.lock | xargs) &&     install bundle                                                                                        82.1s 
------                                                                                                                                                                                        
 > [10/9] RUN gem install bundler $(tail -n 1 Gemfile.lock | xargs) &&     install bundle:
#15 53.84 ERROR:  Could not find a valid gem '1.17.3' (>= 0) in any repository
#15 82.00 Successfully installed bundler-2.2.15
#15 82.00 Parsing documentation for bundler-2.2.15
#15 82.00 Installing ri documentation for bundler-2.2.15
#15 82.00 Done installing documentation for bundler after 3 seconds
#15 82.00 1 gem installed
------
executor failed running [/bin/sh -c gem install bundler $(tail -n 1 Gemfile.lock | xargs) &&     install bundle]: exit code: 2

**Comment by deivid-rodriguez** [comment]
You need to make sure you end up running either `gem install bundler:<version>`, or `gem install bundler -v <version>`, but you seem to be running `gem install bundler <version>` which interprets the version as a gem name.

**Comment by prabhavathi2210** [comment]
thanks.
Stil i am facing issues: 

#16 44.80 Your bundle is locked to mimemagic (0.3.4), but that version could not be found
#16 44.80 in any of the sources listed in your Gemfile. If you haven't changed sources,
#16 44.80 that means the author of mimemagic (0.3.4) has removed it. You'll need to update
#16 44.80 your bundle to a version other than mimemagic (0.3.4) that hasn't been removed
#16 44.80 in order to install.
------
executor failed running [/bin/sh -c gem install bundler -v $(tail -n 1 Gemfile.lock | xargs) &&     bundle install]: exit code: 7

**Comment by deivid-rodriguez** [comment]
Your bundle is locked to mimemagic (0.3.4), but that version could not be found in any of the sources listed in your Gemfile. If you haven't changed sources, that means the author of mimemagic (0.3.4) has removed it. You'll need to update your bundle to a version other than mimemagic (0.3.4) that hasn't been removed in order to install.

**Comment by prabhavathi2210** [comment]
Thanks a lot.. issue got resolved
