### ISSUE TITLE
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

### ISSUE THREAD

**Issue by Piero-art** [rubygems/rubygems#4520]
How can i fix this error? i use ruby 2.5.0
![image](https://user-images.githubusercontent.com/68265268/114257698-56278f80-9987-11eb-907e-2b3566f0a4ed.png)

**Comment by deivid-rodriguez** [comment]
Unfortunately this screenshot doesn't include enough information for us to be able to help you. Feel free to reopen this making sure you fill out the issue template including all relevant information so that we can help you!
