### ISSUE TITLE
[Unrelated to rubygems] ruby bug tracker requiring two-factor authentication?

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems#4527]
Hey folks,

Sorry for opening this issue here - it is NOT related to rubygems, but instead the official ruby bug tracker.

Today I tried to log in and comment on an issue and I got this message, without warning, after login:

"The administrator requires you to enable two-factor authentication."

Now there may be reasons as to why that was necessary. I have no idea.

The problem is, for various reasons, I can't use two-factor authentication.
I don't own a smartphone or any special device other than an oldschool
computer really. (It would also mean that if rubygems.org were to make
it mandatory, all my gems would be gone since I could no longer use it.
It's a little bit awkward to be able to use github.org and publish the same
code there without 2FA ...)

This change at the ruby bug tracker effectively means that I can no longer participate
in the ruby bug tracker since the 2FA wall effectively locks me out now. And that has
not been the case a few days before, so perhaps it was a recent change.

My question is: does this happen to other users of the bug tracker as well?

Because if it were to specifically target me (aka "you must use 2FA") then I would stop
using ruby altogether due to targeted harassment.

However had I assume it does NOT specifically target me, and is instead a general change,
which would mean that others are affected by this as well. This is what I am trying to find
out right now. I should have sent an email, but I am notoriously awful at using emails, so
the github tracker is really much more convenient to use.

Feel free to close this issue at any moment in time, but if someone does, could you also
please confirm either which way whether this is indeed a new change for everyone that
will remain active for the official bug tracker?

That way I can adjust and e. g. no longer visit the bug tracker (I tend to open all ruby-related
links via the commandline when I wake up, so if I can not use something anymore, I'd get
rid of it from my workflow.)

Thanks!

**Comment by deivid-rodriguez** [comment]
Please use https://github.com/ruby/b.r-l.o which I believe is the source repository of the tracker. Thanks!
