### ISSUE TITLE
Gem respects POSIXLY_CORRECT but that is not mentioned anywhere

### ISSUE THREAD

**Issue by graywolf-at-work** [rubygems/rubygems#4538]
I'm having a problem or would like to suggest a feature.

My current problem is when POSIXLY_CORRECT env variable is set, gem install
does not follow its own help message.

```
+root@13d23e3307b4:/# gem help install | head -n1
Usage: gem install GEMNAME [GEMNAME ...] [options] -- --build-flags [options]
```

Usage suggests that correct command is:

```
gem install bundler --conservative --user -N --version '~> 1.17'
```

However, when executed with POSIXLY_CORRECT:

```
+root@13d23e3307b4:/# POSIXLY_CORRECT=1 gem install bundler --conservative --user -N --version '~> 1.17'
Fetching bundler-2.2.16.gem
Successfully installed bundler-2.2.16
Parsing documentation for bundler-2.2.16
Installing ri documentation for bundler-2.2.16
Done installing documentation for bundler after 3 seconds
ERROR:  Could not find a valid gem '~> 1.17' (>= 0) in any repository
1 gem installed
+root@13d23e3307b4:/# echo $?
2
```

Not exactly what I would expect. This is not mentioned in the help message as far as I can tell:

```
+root@13d23e3307b4:/# gem help install | grep POSIXLY || echo NOTHING
NOTHING
```

Putting the gem name to the end makes it work:

```
+root@13d23e3307b4:/# POSIXLY_CORRECT=1 gem install --conservative --user -N --version '~> 1.17' bundler
Fetching bundler-1.17.3.gem
WARNING:  You don't have /root/.gem/ruby/2.7.0/bin in your PATH,
          gem executables will not run.
Successfully installed bundler-1.17.3
1 gem installed
```

I'm not sure what the correct solution is, but the current state seems broken.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
+root@13d23e3307b4:/# gem env version
3.1.2
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md) (did not read).

**Comment by deivid-rodriguez** [comment]
So, if we correct the help it should be ok? Or is respecting posix mode something bad or too strict that should be "fixed"?

**Comment by graywolf-at-work** [comment]
For me personal just changing the usage to

```
gem install [options] GEMNAME [GEMNAME ...] -- --build-flags [options]
```

would suffice. I like the POSIX mode (well, that is why I have it enabled),
it was just surprising and took a bit to find the cause.

**Comment by deivid-rodriguez** [comment]
Ok! Would you be willing to create a PR to fix the help usage?

**Comment by graywolf-at-work** [comment]
On 2021-04-16 05:18:26 -0700, David Rodríguez wrote:
> Ok! Would you be willing to create a PR to fix the help usage?

I'll look into it next week.

-- 
There are only two hard things in Computer Science:
cache invalidation, naming things and off-by-one errors.
