### ISSUE TITLE
bundle install attempts to write to system directory

### ISSUE THREAD

**Issue by slonopotamus** [rubygems/rubygems#4542]
### Describe the problem as clearly as you can

`bundle install` attempts to write to system (root-owned) directories and fails

### Post steps to reproduce the problem

OS: Gentoo Linux

```
$ ruby --version
ruby 2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]

$ bundle --version
Bundler version 2.1.4
```
Neither `~/.gems` nor `~/.bundle` exist before running commands.

1. `git clone https://github.com/asciidoctor/asciidoctor-epub3.git`
2. `cd asciidoctor-epub3`
3. `bundle install`

### What were you expecting to happen?

Bundler happily installs gems to `~/.gems` and doesn't touch any system directories.

This worked properly in the past (Ruby 2.5.x, Bundler 2.0.x), though I'm not sure I can remember exact versions when it did. This was just a couple of months ago.

### What actually happened?

```
$ bundle update
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Fetching rake 13.0.3
Errno::EACCES: Permission denied @ rb_file_s_rename - (/home/irina/.gem/ruby/2.6.0/cache/rake-13.0.3.gem, /usr/lib64/ruby/gems/2.6.0/cache/rake-13.0.3.gem)
An error occurred while installing rake (13.0.3), and Bundler cannot continue.
Make sure that `gem install rake -v '13.0.3' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  rake
```

### If not included with the output of your command, run `bundle env` and paste the output below

$ bundle env
## Environment

```
Bundler       2.1.4
  Platforms   ruby, x86_64-linux
Ruby          2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
  Full Path   /usr/bin/ruby26
  Config Dir  /etc
RubyGems      3.0.9
  Gem Home    /usr/lib64/ruby/gems/2.6.0
  Gem Path    /home/irina/.gem/ruby/2.6.0:/usr/lib64/ruby/gems/2.6.0:/usr/local/lib64/ruby/gems/2.6.0
  User Home   /home/irina
  User Path   /home/irina/.gem/ruby/2.6.0
  Bin Dir     /usr/bin
Tools         
  Git         2.26.3
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2020-01-05
Git SHA           32a4159325
Released Version  true
```

### Gemfile

```ruby
# frozen_string_literal: true

source 'https://rubygems.org'

# Look in asciidoctor-epub3.gemspec for runtime and development dependencies.
gemspec

if ENV.key? 'ASCIIDOCTOR_VERSION'
  gem 'asciidoctor', ENV['ASCIIDOCTOR_VERSION'], require: false
  # Newer asciidoctor-diagram 1.5.x require asciidoctor >=1.5.7
  gem 'asciidoctor-diagram', '1.5.16', require: false if Gem::Version.new(ENV['ASCIIDOCTOR_VERSION']) < Gem::Version.new('2.0.0')
end

group :optional do
  # epubcheck-ruby might be safe to be converted into runtime dependency, but could have issues when packaged into asciidoctorj-epub3
  gem 'epubcheck-ruby', '~> 4.2.4.0'
end
```

### Gemfile.lock

```
<No /home/irina/marat/asciidoctor-epub3/Gemfile.lock found>
```

### asciidoctor-epub3.gemspec

```ruby
# frozen_string_literal: true

require_relative 'lib/asciidoctor-epub3/version'
require 'open3' unless defined? Open3

Gem::Specification.new do |s|
  s.name = 'asciidoctor-epub3'
  s.version = Asciidoctor::Epub3::VERSION

  s.summary = 'Converts AsciiDoc documents to EPUB3 and KF8/MOBI (Kindle) e-book formats'
  s.description = <<-EOS
An extension for Asciidoctor that converts AsciiDoc documents to EPUB3 and KF8/MOBI (Kindle) e-book archives.
  EOS

  s.authors = ['Dan Allen', 'Sarah White']
  s.email = 'dan@opendevise.com'
  s.homepage = 'https://github.com/asciidoctor/asciidoctor-epub3'
  s.license = 'MIT'

  s.required_ruby_version = '>= 2.3.0'

  files = begin
    (result = Open3.popen3('git ls-files -z') {|_, out| out.read }.split %(\0)).empty? ? Dir['**/*'] : result
  rescue
    Dir['**/*']
  end
  s.files = files.grep %r/^(?:(?:data\/(?:fonts|images|styles)|lib)\/.+|Gemfile|Rakefile|LICENSE|(?:CHANGELOG|NOTICE|README)\.adoc|\.yardopts|#{s.name}\.gemspec)$/
  s.executables = %w(asciidoctor-epub3 adb-push-ebook)
  s.test_files = s.files.grep(/^(?:test|spec|feature)\/.*$/)

  s.require_paths = ['lib']

  s.add_development_dependency 'asciidoctor-diagram', '>= 1.5.0', '< 3.0.0'
  s.add_development_dependency 'asciimath', '~> 2.0'
  s.add_development_dependency 'coderay', '~> 1.1.0'
  s.add_development_dependency 'pygments.rb', '~> 2.2.0'
  s.add_development_dependency 'rake', '~> 13.0.0'
  s.add_development_dependency 'rouge', '~> 3.0'
  s.add_development_dependency 'rspec', '~> 3.10.0'
  s.add_development_dependency 'rubocop', '~> 0.81.0'
  s.add_development_dependency 'rubocop-rspec', '~> 1.38.0'

  s.add_runtime_dependency 'asciidoctor', '>= 1.5.6', '< 3.0.0'
  s.add_runtime_dependency 'gepub', '~> 1.0.0'
  s.add_runtime_dependency 'mime-types', '~> 3.0'
end
```

**Comment by deivid-rodriguez** [comment]
I suspect you can get this error fixed by upgrading rubygems, but you need to request that to the OS package, we cannot influence their upgrade schedule. As workarounds, you can use a ruby version manager, or configure bundler to install to a local path: `bundle config set --local path foo`.

**Comment by slonopotamus** [comment]
So, this is a known bug in Rubygems version I'm using? I failed to find any similar bugreports.

Will try upgrading, there are [plenty of never versions available](https://packages.gentoo.org/packages/dev-ruby/rubygems) and update this issue with my discoverings.

**Comment by deivid-rodriguez** [comment]
Not sure, I just suspect it could have been fixed. Normally `bundler` should ask you for sudo permissions in this case, not fail like that (asking for sudo is something we will probably change in favour of falling back to a writable folder, but it's how things work now)

Anwyays, yes, please always upgrade to the latest versions if available before reporting issues, so that we can automatically rule out that the issue has not already been fixed.

**Comment by slonopotamus** [comment]
So. This bug:

1. *Occurs* with Rubygems 3.0.9
2. *Occurs* with Rubygems 3.1.6
3. *Occurs* with Rubygems 3.2.14
4. *Does NOT occur* with Rubygems 3.0.3

I was unable to test Rubygems 3.2.15 but given that nothing in its changelog is even remotely related to the issue I'm seeing, it is safe to assume that it is also affected.

So, we have data that says that something has changed between 3.0.3 and 3.0.9.

Why newer Rubygems tries to copy from user cache to system cache directory at all?

**Comment by slonopotamus** [comment]
Additional info: I am *not* reproducing this issue via `gem install --pre asciidoctor-epub3`. So we can't take out Bundler of of the equation.

**Comment by deivid-rodriguez** [comment]
Alright. If you can further bisect the change or at least the release that caused this, that'd be great. Also, if you can provide a repro that uses the latest bundler release instead of the bundler version packaged by your OS, that would also be very helpful. Thanks!

**Comment by slonopotamus** [comment]
I am also reproducing this using Rubygems 3.2.14 + Bundler 2.2.17.

So, current state is:

1. Any Bundler version + Rubygems 3.0.3: WORKS
2. Any Bundler version + any Rubygems >= 3.0.9: NOT WORKS

I created an bugreport in Gentoo Linux bugtracker because not sure whether this is generic Bundler/Rubygems issue or something Gentoo-specific: https://bugs.gentoo.org/789957

**Comment by slonopotamus** [comment]
I found something.

This is output of `bundle env` with Rubygems 3.2.14 (broken):

## Environment

```
Bundler       2.2.17
  Platforms   ruby, x86_64-linux
Ruby          2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
  Full Path   /usr/bin/ruby26
  Config Dir  /etc
RubyGems      3.2.14
  Gem Home    /usr/lib64/ruby/gems/2.6.0 <---------------------
  Gem Path    /home/irina/.gem/ruby/2.6.0:/usr/lib64/ruby/gems/2.6.0:/usr/local/lib64/ruby/gems/2.6.0
  User Home   /home/irina
  User Path   /home/irina/.gem/ruby/2.6.0
  Bin Dir     /usr/bin <---------------------
Tools         
  Git         2.26.3
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

And this is output of `bundle env` with Rubygems 3.0.3 (working)

## Environment

```
Bundler       2.2.17
  Platforms   ruby, x86_64-linux
Ruby          2.6.6p146 (2020-03-31 revision 67876) [x86_64-linux]
  Full Path   /usr/bin/ruby26
  Config Dir  /etc
RubyGems      3.0.3
  Gem Home    /home/irina/.gem/ruby/2.6.0 <---------------------
  Gem Path    /home/irina/.gem/ruby/2.6.0:/usr/local/lib64/ruby/gems/2.6.0:/usr/lib64/ruby/gems/2.6.0
  User Home   /home/irina
  User Path   /home/irina/.gem/ruby/2.6.0
  Bin Dir     /home/irina/.gem/ruby/2.6.0/bin <---------------------
Tools         
  Git         2.26.3
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

Note that for some reason "Gem Home" and "Bin Dir" have different values. On 3.0.3 it installs gems to user dir while on 3.2.4 it tries to install to /usr

**Comment by slonopotamus** [comment]
And that is most likely caused by the fact that Rubygems 3.0.3 uses [files/gentoo-defaults.rb](https://github.com/gentoo/gentoo/blob/master/dev-ruby/rubygems/files/gentoo-defaults.rb) while Rubygems 3.0.9 uses [files/gentoo-defaults-3.rb](https://github.com/gentoo/gentoo/blame/master/dev-ruby/rubygems/files/gentoo-defaults-3.rb).

In files/gentoo-defaults.rb, there is:

    def default_dir
      Process.euid == 0 ? local_dir : user_dir
    end

While in files/gentoo-defaults-3.rb, there's something different going on.

This is related to https://bugs.gentoo.org/676946#c2

So, I'm becoming even more confident that this issue is Gentoo-specific and Gentoo bugtracker is a proper place to discuss it. Do you want me to close this bugreport?

**Comment by deivid-rodriguez** [comment]
Yes, it definitely seems Gentoo-specific. Yes, please close the issue :+1:.

**Comment by slonopotamus** [comment]
Thanks for your efforts to help anyway!
