### ISSUE TITLE
SSL_connect returned=1 errno=0 state=error: certificate verify failed (self signed certificate) (OpenSSL::SSL::SSLError)

### ISSUE THREAD

**Issue by chirazbenhassine** [rubygems/rubygems#4548]
I can't fix this error, please any help, i try to execute file.rb 

![Capture](https://user-images.githubusercontent.com/76632477/115436597-766b1000-a20b-11eb-91ca-ffd6304c675d.JPG)

**Comment by pirj** [comment]
Also affects [Ruby 1.9.2 buildss on GHA](https://github.com/rspec/rspec-core/pull/2886/checks?check_run_id=2395099300):
```
Retrying download gem from https://rubygems.org/ due to error (2/4): Gem::RemoteFetcher::FetchError hostname was not match with the server certificate (https://rubygems.org/gems/rake-10.5.0.gem)
```
[Ruby 1.8.7 builds](https://github.com/rspec/rspec-core/pull/2886/checks?check_run_id=2395099317):
```
Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Could not fetch specs from https://rubygems.org/
Error: Process completed with exit code 17.
```

**Comment by pirj** [comment]
@chirazbenhassine It would be very helpful to tell what the contents of `file2.rb` is, especially line 11, and how it relates to Rubygems specifically.

**Comment by chirazbenhassine** [comment]
> @chirazbenhassine It would be very helpful to tell what the contents of `file2.rb` is, especially line 11, and how it relates to Rubygems specifically.

![2](https://user-images.githubusercontent.com/76632477/115470854-46d1fd00-a237-11eb-8d1e-d5056f3f9778.JPG)

**Comment by pirj** [comment]
Your case seems to have nothing to do with Rubygems and is an expected behaviour.
Check https://letsencrypt.org/docs/certificates-for-localhost/#making-and-trusting-your-own-certificates on how to trust your self-signed certificates.

**Comment by deivid-rodriguez** [comment]
Yeah, nothing seems to suggest that this is a rubygems issue. I'll close this. Thanks @pirj for troubleshooting this!
