### ISSUE TITLE
Apparent certificate errors when accessed by older Ruby versions from GHA

### ISSUE THREAD

**Issue by pirj** [rubygems/rubygems#4549]
[Ruby 1.9.2 buildss on GHA](https://github.com/rspec/rspec-core/pull/2886/checks?check_run_id=2395099300):
```
Retrying download gem from https://rubygems.org/ due to error (2/4): Gem::RemoteFetcher::FetchError hostname was not match with the server certificate (https://rubygems.org/gems/rake-10.5.0.gem)
```
[Ruby 1.8.7 builds](https://github.com/rspec/rspec-core/pull/2886/checks?check_run_id=2395099317):
```
Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Could not fetch specs from https://rubygems.org/
Error: Process completed with exit code 17.
```

**Comment by sonalkr132** [comment]
Hi, this is a known issue for ruby older than 1.9.3. Please check [this comment](https://github.com/rubygems/rubygems/issues/4228#issuecomment-760802106) for workarounds and subscribe for updates. 
We are hopeful that it will be resolved by this weekend.

**Comment by pirj** [comment]
Thanks for the heads-up 👍
