### ISSUE TITLE
Rescue errors when loading `operating_system.rb` and tell users to report the problem to the OS

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#4585]
My current problem is that we keep getting issues that we can't really fix, because they happen inside `operating_system.rb`, which is not under our control, but on the OS packager's side.

Let's at least rescue any errors inside `operating_system.rb` and display a message making it clear where the problem is and where it should be reported, as suggested by @simi at https://github.com/rubygems/rubygems/issues/3831#issuecomment-658382577, so that at least we can save people some time.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by duckinator** [comment]
As a note, the relevant `require` is currently at [line 1,348 of `lib/rubygems.rb`](https://github.com/rubygems/rubygems/blob/d486393/lib/rubygems.rb#L1343-L1350).
