### ISSUE TITLE
Bundle error

### ISSUE THREAD

**Issue by mustafakurt07** [rubygems/rubygems#4591]
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=Permission+denied+%40+rb_sysopen+-+%2FUsers%2Fnevovi%2F.rbenv%2Fversions%2F3.0.0%2Flib%2Fruby%2Fgems%2F3.0.0%2Fgems%2Frails-6.1.3.1%2FREADME.md&type=Issues

If there aren't any reports for this error yet, please create copy and paste the report template above into a new issue. Don't forget to anonymize any private data! The new issue form is located at:
https://github.com/rubygems/rubygems/issues/new?labels=Bundler

**Comment by deivid-rodriguez** [comment]
Please make sure you fill in all the sections in https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md and report a separate issue. Thanks!
