### ISSUE TITLE
Bundler authentication hint about env var includes full URL, not just host

### ISSUE THREAD

**Issue by ianfixes** [rubygems/rubygems#4601]
### Describe the problem as clearly as you can

Code added by #4565 [introduces a helpful message](https://github.com/rubygems/rubygems/pull/4565/files#diff-828acea145b306f0a63d5e01a096fa2fcd7d97aceeeb0f8922120e661c30c338R47-R51) about the option to submit gem server credentials via an environment variable.

```diff
        remote_uri = filter_uri(remote_uri)
        super "Authentication is required for #{remote_uri}.\n" \
          "Please supply credentials for this source. You can do this by running:\n" \
-         " bundle config set --global #{remote_uri} username:password"
+         "`bundle config set --global #{remote_uri} username:password`\n" \
+         "or by storing the credentials in the `#{Settings.key_for(remote_uri)}` environment variable"
```

But `Settings.key_for(remote_uri)`  string isn't producing the correct environment variable name -- it contains portions of the entire source URL, not just the host.

### Post steps to reproduce the problem

`Dockerfile.bundler`
```dockerfile
FROM ruby:2.7

RUN echo "gem 'private-gem', '~> 1.0', source: 'https://gem.fury.io/my-account'" > Gemfile

RUN true \
  && gem install bundler -v 2.2.17 \
  && bundle env \
  && bundle install
```

```console
$ docker build -f Dockerfile.bundler .
  [snip]
    > [3/3] RUN true   && gem install bundler   && bundle env   && bundle install:
    Successfully installed bundler-2.2.17
    1 gem installed
    ## Environment
   
    ```
    Bundler       2.2.17
      Platforms   ruby, x86_64-linux
    Ruby          2.7.3p183 (2021-04-05 revision 6847ee089d7655b2a0eea4fee3133aeacd4cc7cc) [x86_64-linux]
      Full Path   /usr/local/bin/ruby
      Config Dir  /usr/local/etc
    RubyGems      3.1.6
      Gem Home    /usr/local/bundle
      Gem Path    /root/.gem/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/local/bundle
      User Home   /root
      User Path   /root/.gem/ruby/2.7.0
      Bin Dir     /usr/local/bundle/bin
    Tools
      Git         2.20.1
      RVM         not installed
      rbenv       not installed
      chruby      not installed
    ```
   
    ## Bundler Build Metadata
   
    ```
    Built At          2021-05-05
    Git SHA           69cbd6e10e
    Released Version  true
    ```
   
    ## Bundler settings
   
    ```
    app_config
      Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
    silence_root_warning
      Set via BUNDLE_SILENCE_ROOT_WARNING: true
    ```
   
    ## Gemfile
   
    ### Gemfile
   
    ```ruby
    gem 'private-gem', '~> 1.0', source: 'https://gem.fury.io/my-account'
    ```
   
    ### Gemfile.lock
   
    ```
    <No /Gemfile.lock found>
    ```
    Fetching gem metadata from https://gem.fury.io/my-account/.Retrying dependency api due to error (2/4): Bundler::HTTPError Net::HTTPForbidden: Forbidden
   
   
    Retrying dependency api due to error (3/4): Bundler::HTTPError Net::HTTPForbidden: Forbidden
    Retrying dependency api due to error (4/4): Bundler::HTTPError Net::HTTPForbidden: Forbidden
   
   
   
   
    Authentication is required for https://gem.fury.io/my-account/.
    Please supply credentials for this source. You can do this by running:
    `bundle config set --global https://gem.fury.io/my-account/ username:password`
    or by storing the credentials in the
    `BUNDLE_HTTPS://GEM__FURY__IO/MY___ACCOUNT/` environment variable

```

Note that not only is `BUNDLE_HTTPS://GEM__FURY__IO/MY___ACCOUNT/` incorrect (it should be `BUNDLE_GEM__FURY__IO`), the `:` and `/` are not valid in environment variable names!

### The change that needs to be made

```diff
    Authentication is required for https://gem.fury.io/my-account/.
    Please supply credentials for this source. You can do this by running:
    `bundle config set --global https://gem.fury.io/my-account/ username:password`
    or by storing the credentials in the
-   `BUNDLE_HTTPS://GEM__FURY__IO/MY___ACCOUNT/` environment variable
+   `BUNDLE_GEM__FURY__IO` environment variable
```

**Comment by deivid-rodriguez** [comment]
Hi @ianfixes, sorry for the delay. I can't repro the issue with your Dockerfile, I get the expected behavior... Not sure if I'm doing something wrong, if the issue is fixed, or if the repro is missing something.

**Comment by ianfixes** [comment]
Can't reproduce this now either.  The only variable here would be the exact sha1 for the `ruby:2.7` image... but digging into build logs on my CI system, I see that on may 10th it was `ruby@sha256:e57b8922ec57a9116cdd8295c041a6cbf84ce7a8baf5e521e845e3bd0bae9127`... and trying to reproduce the issue with that base image also shows the correct behavior.  I'm at a loss to say what I observed here.

**Comment by deivid-rodriguez** [comment]
Weird, but good news :)

Thanks for double checking @ianfixes!
