### ISSUE TITLE
Facing issues with bundle install on Windows

### ISSUE THREAD

**Issue by Jassi10000** [rubygems/rubygems#4608]
### Describe the problem as clearly as you can
Am facing follwing issue with the <code>bundle install</code> command

### Which command did you run?
<code>bundle install</code>

### What were you expecting to happen?

I was expecting that the command will install all the associated dependencies or packages with it 

### What actually happened?
But what happened actually is 

![image](https://user-images.githubusercontent.com/64856348/118718369-c5c15200-b844-11eb-80a7-7da94dd249b3.png)

**Comment by deivid-rodriguez** [comment]
I'm pretty sure that issue is solved on recent rubygems versions. Please run `gem update --system` and try again.

**Comment by Jassi10000** [comment]
okayyy , leme try

**Comment by deivid-rodriguez** [comment]
I'm pretty sure this has been fixed on recent rubygems, so I'll close it. If you can reproduce it with the latest rubygems, please reopen.
