### ISSUE TITLE
Bundler 2.2.18 gem takes forever to install docs

### ISSUE THREAD

**Issue by headius** [rubygems/rubygems#4626]
We discovered yesterday that the Bundler 2.2.18 release, when installed on JRuby with `gem install bundler`, takes a tremendous amount of time to generate docs. This caused all of our Travis builds to start failing, as the gem does not install within 10 minutes.

```
$ gem install bundler -v 2.2.17
Fetching bundler-2.2.17.gem
Successfully installed bundler-2.2.17
Parsing documentation for bundler-2.2.17
Installing ri documentation for bundler-2.2.17
Done installing documentation for bundler after 11 seconds
1 gem installed

$ gem install bundler -v 2.2.18
Fetching bundler-2.2.18.gem
Successfully installed bundler-2.2.18
Parsing documentation for bundler-2.2.18
Installing ri documentation for bundler-2.2.18
Done installing documentation for bundler after 409 seconds
1 gem installed
```

I have no theories as to why this is the case and a quick review of changes in 2.2.18 was not fruitful.

**Comment by deivid-rodriguez** [comment]
There's a change in the gemspec: https://github.com/rubygems/rubygems/pull/4537. Could that be affecting jruby somehow? :grimacing:

**Comment by enebo** [comment]
I see lots and lots of calls in generated _RawLine to get_byte.  Did something change in grammar for markdown parser?

**Comment by deivid-rodriguez** [comment]
Actually I just run it and I'm getting the same thing, it does not seem jruby specific.

**Comment by enebo** [comment]
Oh I suppose that would go back into our stdlib...so no to that last question.

**Comment by deivid-rodriguez** [comment]
I guess it's the `extra_rdoc_files` change in the gemspec that's hard for the markdown parser.

**Comment by deivid-rodriguez** [comment]
I guess this list needs to hold files in rdoc format, and if you give it markdown format it has trouble? I always thought it was fine to feed md files there, and it was just a bad name.

**Comment by deivid-rodriguez** [comment]
Yeah, confirmed. I rebuilt the package without the `extra_rdoc_files` line and it installed quickly again. I'll revert that change.

**Comment by deivid-rodriguez** [comment]
I guess it's this: https://github.com/ruby/rdoc/issues/216.

**Comment by headius** [comment]
PEGs are notoriously slow, and apparently in Ruby they're REALLY slow.

**Comment by headius** [comment]
Thank you for the fix @deivid-rodriguez!
