### ISSUE TITLE
No such file or directory @ dir_s_mkdir - C:/Users/hyrious/.local/share/gem

### ISSUE THREAD

**Issue by hyrious** [rubygems/rubygems#4654]
I was publishing an old gem with a newly installed ruby. The `gem push` raises such issue:

```
C:\Users\hyrious\Documents\GitHub\undll32>rake release
undll32 0.3.4 built to pkg/undll32-0.3.4.gem.
Tag v0.3.4 has already been created.
Enter your RubyGems.org credentials.
Don't have an account yet? Create one at https://rubygems.org/sign_up
   Email:   hyrious@outlook.com
Password:

Signed in with API key: <hidden>
ERROR:  While executing gem ... (Errno::ENOENT)
    No such file or directory @ dir_s_mkdir - C:/Users/hyrious/.local/share/gem
```

After navigating the source code I'm sure it was caused by this line:

https://github.com/rubygems/rubygems/blob/64168ebceb6d99b27c189ad7ec4819c9da69f502/lib/rubygems/config_file.rb#L323

It is because on Windows there's no pre-created `~/.local/share` folder.

It will be fine if I manually create that folder and run `gem push` again. But I have a better idea: use `%AppData%` folder on windows for user's "data home", which is defined here:

https://github.com/rubygems/rubygems/blob/64168ebceb6d99b27c189ad7ec4819c9da69f502/lib/rubygems/defaults.rb#L160-L162

- - -

Beside this issue, you may notice some other directories listed in `defaults.rb`: `~/.config`, `~/.cache`. Luckily these folders are created before on my PC by other tools like `aria2` and `scoop`. I'm not sure if you have to deal with them too.

**Comment by deivid-rodriguez** [comment]
Thanks for the report @hyrious!

I'm not sure what's best. Using `%AppData%` on Windows might be less surprising for end users, but following the XDG specification strictly should be easier for us maintainers. I tend to prefer to automatically create the `~/.local/share` folder when necessary but I'd like to hear more opinions.

**Comment by rubyFeedback** [comment]
I also can not say how to best fix this, but I believe that even aside from AppData, the behaviour seems wrong. It asks the user for some login data, where the user provides it (and invests time), and then it fails because it assumed that a directory should exist which should not exist. Perhaps the whole logic could be moved forward, or it may create the directory. (I do not know which assumption the author made when that code was written. Perhaps it was a linux dev who could not test on windows. :D )

**Comment by rubyFeedback** [comment]
> It will be fine if I manually create that folder

Actually as a quick fix this could be done, and then worry about AppData or any better designed solution.

**Comment by deivid-rodriguez** [comment]
https://github.com/rubygems/rubygems/pull/4665 should fix this.
