### ISSUE TITLE
rubygems.org 503 Service Unavailable

### ISSUE THREAD

**Issue by chadliu23** [rubygems/rubygems#4659]
I'm having a problem or would like to suggest a feature.

My current problem is _________

 https://rubygems.org/

Error 503 Service Unavailable

```
Install missing gems with `bundle install`
Could not fetch specs from https://rubygems.org/
```

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version

gem -v 3.0.3
bundler version 1.17.3 
ruby version 2.5.7p206

```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Please subscribe to https://status.rubygems.org/ and the underlying Fastly issue :+1:.
