### ISSUE TITLE
Could not find a valid gem 'bundler' (= 2.1.2)

### ISSUE THREAD

**Issue by simona-iuliana** [rubygems/rubygems#4661]
hi, I receive this error in Bitrise:
ERROR:  Could not find a valid gem 'bundler' (= 2.1.2), here is why:
          Unable to download data from https://rubygems.org/ - bad response Service Not Found 500 (https://rubygems.org/specs.4.8.gz)
any help?

**Comment by deivid-rodriguez** [comment]
Rubygems.org was down for a while due to a third party issue with Fastly (see https://status.rubygems.org/).

But it should be ok now!
