### ISSUE TITLE
Unable to Extract Gem from StringIO

### ISSUE THREAD

**Issue by drcapulet** [rubygems/rubygems#4664]
I've got some code that looks like:

```ruby
Gem::Package.new(StringIO.new("contents of gem file")).extract_files(gem_dir)
```

Unfortunately, this doesn't work since the IO object is read to the end in this call to [`Gem::Package#verify`](https://github.com/rubygems/rubygems/blob/v3.2.19/lib/rubygems/package.rb#L374). In the resulting call to [`Gem::Package::TarReader#each`](https://github.com/rubygems/rubygems/blob/v3.2.19/lib/rubygems/package.rb#L381), the reader is tripped up [here](https://github.com/rubygems/rubygems/blob/v3.2.19/lib/rubygems/package/tar_reader.rb#L58).

I've come up with a few solutions, but didn't know if y'all had a preferred way of addressing this:

1. In [`Gem::Package::IOSource#with_read_io`](https://github.com/rubygems/rubygems/blob/v3.2.19/lib/rubygems/package/io_source.rb#L33-L35), rewind after:
  ```ruby
  def with_read_io
    yield io
  ensure
    io.rewind
  end
```

2. In [`Gem::Package::TarReader#each`](https://github.com/rubygems/rubygems/blob/v3.2.19/lib/rubygems/package/tar_reader.rb#L58), rewind at the beginning:
  ```ruby
  def each
    ...

    @io.rewind

    until @io.eof? do
      ...
  ```

3. In `Gem::Package`, rewind anytime reading happens.

Option 1 is my favorite since `Gem::Package::IOSource` already expects to start at the [beginning of the stream](https://github.com/rubygems/rubygems/blob/v3.2.19/lib/rubygems/package/io_source.rb#L19-L21) and matches the behavior of [`Gem::Package::FileSource`](https://github.com/rubygems/rubygems/blob/v3.2.19/lib/rubygems/package/file_source.rb#L28-L30) (since a new IO object is created each time).

**Comment by djberg96** [comment]
Not sure if you're just trying to get a list of spec files. You can do that like so:

```ruby
spec = Gem::Specification.load('some_gem.spec')
p spec.files
```

If not, can you tell us what your ultimate goal is exactly?

**Comment by drcapulet** [comment]
@djberg96 I need the actual source files & currently monekypatching option 1.

**Comment by deivid-rodriguez** [comment]
@drcapulet I'm happy to get a PR with your suggestion.
