### ISSUE TITLE
unable to Download data from https:rubygems.org/ 

### ISSUE THREAD

**Issue by zencharcoal** [rubygems/rubygems#4674]
I'm having a problem

My current problem is cannot connect to rubygems.org. A variety of researched methods have been attempted without success. It seems that ruby is not request the ssl certificates and is instead failing to connect. 

This issue is related to:

  - [ x] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [ x] The command line `gem`
  - [ ] Other

Here are my current environment details:
Kali Linux
```
$ gem env version
3.2.20

```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

First image: This happens with every gem install that I have attempted, except for those locally downloaded and stored.

![image](https://user-images.githubusercontent.com/63509228/122010602-42364a80-cd89-11eb-96dd-523ed9d47c4a.png)

![image](https://user-images.githubusercontent.com/63509228/122010723-6134dc80-cd89-11eb-869a-9cf7bdc307c7.png)

![image](https://user-images.githubusercontent.com/63509228/122010829-7b6eba80-cd89-11eb-9561-8d6f3ddf5210.png)

I have also tried the variety of recommendations from https://bundler.io/v2.0/guides/rubygems_tls_ssl_troubleshooting_guide.html#troubleshooting-certificate-errors 

Please advise the best way to resolve this issue. 

Thank you!

**Comment by deivid-rodriguez** [comment]
Hi!

Can you first try upgrading bundler & rubyems, as suggested in that guide you're linking to? https://bundler.io/v2.2/guides/rubygems_tls_ssl_troubleshooting_guide.html#updating-bundler.

Ideally, you should also upgrade to ruby 3.0.1, but that's not strictly necessary and I don't think it should make a difference.

After that the script should report:

> Rubygems: 3.2.20
> Bundler: 2.2.20

Once you're done, if you're still getting the error, could you try the following? https://stackoverflow.com/a/64797119/143243

**Comment by zencharcoal** [comment]
Thank you,

I found it best to reinstall everything from source...and then, apparently disabling ipv6 is necessary. Doesn't make sense to me, but you can close this.

**Comment by deivid-rodriguez** [comment]
@zencharcoal I linked to an incorrect answer, sorry about that :grimacing:. The one I wanted to link to is https://stackoverflow.com/questions/49800432/gem-cannot-access-rubygems-org/66388201#66388201. Disabling ipv6 globally on your system shouldn't be necessary if you follow that answer.
