### ISSUE TITLE
Remote metadata is fetched during `bundle install --local` when cache_all_platforms is true

### ISSUE THREAD

**Issue by kjg** [rubygems/rubygems#4675]
### Describe the problem as clearly as you can

I expect `bundle install --local` to not attempt any remote communication. However when I have the `cache_all_platforms` setting set to true, and I run `bundle install --local` Bundler says it is fetching gem metadata from remote sources

```bash
-- $ bundle install --local
Using bundler 2.2.20
Using racc 1.5.2
Using nokogiri 1.11.7 (x86_64-darwin)
Updating files in vendor/cache
Fetching gem metadata from https://rubygems.org/
Fetching gem metadata from https://rubygems.org/.......
Bundle complete! 1 Gemfile dependency, 3 gems now installed.
Bundled gems are installed into `./vendor/gems`
```

### Post steps to reproduce the problem

- Have a bundle config like so:

```
---
BUNDLE_CACHE_ALL: "true"
BUNDLE_CACHE_ALL_PLATFORMS: "true"
BUNDLE_PATH: "vendor/gems"
BUNDLE_SPECIFIC_PLATFORM: "true"
```

- Have a Gemfile like so:

```
source 'https://rubygems.org'

gem "nokogiri"
```

- Have a Gemfile.lock like so:

```
GEM
  remote: https://rubygems.org/
  specs:
    nokogiri (1.11.7-x86_64-darwin)
      racc (~> 1.4)
    nokogiri (1.11.7-x86_64-linux)
      racc (~> 1.4)
    racc (1.5.2)

PLATFORMS
  x86_64-darwin-19
  x86_64-linux

DEPENDENCIES
  nokogiri

BUNDLED WITH
   2.2.20
```

### Which command did you run?

`bundle install --local`

### What were you expecting to happen?

Gems are installed without any remote communication

### What actually happened?

Gem metadata was fetched from a remote location

## Environment

```
Bundler       2.2.20
  Platforms   ruby, x86_64-darwin-19
Ruby          3.0.1p64 (2021-04-05 revision 0fb782ee38ea37fd5fe8b1f775f8ad866a82a3f0) [x86_64-darwin19]
  Full Path   /Users/kjg/.rbenv/versions/3.0.1/bin/ruby
  Config Dir  /Users/kjg/.rbenv/versions/3.0.1/etc
RubyGems      3.2.20
  Gem Home    /Users/kjg/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0
  Gem Path    /Users/kjg/.gem/ruby/3.0.0:/Users/kjg/.rbenv/versions/3.0.1/lib/ruby/gems/3.0.0
  User Home   /Users/kjg
  User Path   /Users/kjg/.gem/ruby/3.0.0
  Bin Dir     /Users/kjg/.rbenv/versions/3.0.1/bin
Tools         
  Git         2.32.0
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-06-11
Git SHA           4c510a34a4
Released Version  true
```

## Bundler settings

```
cache_all
  Set for your local app (/Users/kjg/proj/local-test/.bundle/config): true
cache_all_platforms
  Set for your local app (/Users/kjg/proj/local-test/.bundle/config): true
path
  Set for your local app (/Users/kjg/proj/local-test/.bundle/config): "vendor/gems"
specific_platform
  Set for your local app (/Users/kjg/proj/local-test/.bundle/config): "true"
```

### Gemfile

```ruby
source 'https://rubygems.org'

gem "nokogiri"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    nokogiri (1.11.7-x86_64-darwin)
      racc (~> 1.4)
    nokogiri (1.11.7-x86_64-linux)
      racc (~> 1.4)
    racc (1.5.2)

PLATFORMS
  x86_64-darwin-19
  x86_64-linux

DEPENDENCIES
  nokogiri

BUNDLED WITH
   2.2

**Comment by deivid-rodriguez** [comment]
Thanks for reporting! https://github.com/rubygems/rubygems/pull/4677 should fix this.

**Comment by kjg** [comment]
Thanks! That was fast. The fix makes sense to me, it looks like during install we temporarily set `cache_all_platforms` to false if the `local` option is true.

Does `Bundle.load.cache` need to get called at all during install if `local` is set?

**Comment by deivid-rodriguez** [comment]
I was thinking the same, but I guessed yeah in case, for example, you removed a gem from the `Gemfile` and run `bundle install --local` (because you already have everything installed), then the cache should be pruned too.

**Comment by deivid-rodriguez** [comment]
>  The fix makes sense to me, it looks like during install we temporarily set cache_all_platforms to false if the local option is true.

Yeah, the `--local` CLI flag, and the `cache_all_platforms` setting are somewhat contradictory, because the former disallows remote operations whereas the latter requires them (because gemspecs and gem packages for platforms other than the local platform are guaranteed to not be there locally). So the approach follows the principle of "direct CLI flag always beats configuration".
