### ISSUE TITLE
Update TODO for Gem::Security

### ISSUE THREAD

**Issue by NathanZook** [rubygems/rubygems#4682]
I got a bit of a shock reading
https://github.com/rubygems/rubygems/blob/2fc1f7bfb7c7b76525d77492334d72256ffbb677/lib/rubygems/security.rb#L320

over at ruby-doc.org.  I'm glad to know that dual signing with SHA-512 is happening--it would be nice for that to be clarified.

**Comment by simi** [comment]
@NathanZook can you provide pull request?

**Comment by indirect** [comment]
Please do not take gem signatures to imply any level of security guarantees. As far as I know, the signing system has never undergone review by security professionals, and it was possible to silently bypass gem signing _for over a decade_ without anyone noticing.

The comment is worrying, but accurately reflects the expected security being provided by the gem signature system, which is currently more or less none.

**Comment by NathanZook** [comment]
> @NathanZook can you provide pull request?

In theory, but with no history with this project, I'm hardly in a position to know what ought to be updated in that TODO list.  The fact that this one particular line is outdated suggests to me that someone in leadership ought to audit the list.

**Comment by NathanZook** [comment]
> The comment is worrying, but accurately reflects the expected security being provided by the gem signature system, which is currently more or less none.

I was doing some nosing around this evening, and saw quit a bit of activity---in 2013.  So.  Yeah.

**Comment by deivid-rodriguez** [comment]
I'm closing this ticket since the TODO seems accurate, so I guess we'll leave it there until we can improve the situation!

**Comment by indirect** [comment]
my current vote for improving the situation is to remove signing entirely, unless we can find some security experts to help overhaul the design. happy to help with finding and/or recruiting someone, though :)
