### ISSUE TITLE
Remove hard dependency on RDoc

### ISSUE THREAD

**Issue by btdmaster** [rubygems/rubygems#4690]
`gem uninstall` does not run if `rdoc` is not installed, leading to a `NameError`.

This is in theory a duplicate of #2483, however the issue is in a different piece of code. I have found that commenting out [this line in uninstaller.rb](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/uninstaller.rb#L264) fixes the issue and allows for `gem uninstall` to work without RDoc.

However, to support both use cases of removing documentation and not having any documentation at all it would be preferable to run line 264 in a rescue block instead, keeping RDoc optional but still useful.

This issue is related to:
  - [X] The command line `gem`

```
$ gem env version
3.2.19
```

**Comment by deivid-rodriguez** [comment]
Pull request welcome!
