### ISSUE TITLE
Gem should differentiate between system and user installed.

### ISSUE THREAD

**Issue by envygeeks** [rubygems/rubygems#470]
```
gem uninstall minitest -v4.3.2
ERROR:  While executing gem ... (Gem::InstallError)
    gem "minitest" cannot be uninstalled because it is a default gem
```

When doing `gem list` I think it would be great if Gem would let a user know if a Gem is a system gem so it doesn't lead to confusion when they try to backtrack and uninstall an older version of a Gem.  Maybe something like `gem (0.0.2, system: 0.0.1)`.

**Comment by copiousfreetime** [comment]
To summarize:
* The suggestion is that the output of `gem list` should indicate whether a gem is a `default` gem or a installed gem.
* The code that should be updated to implement this is `Gem::Commands::QueryCommand#entry_versions`. Updating `#entry_versions` will change what is displayed between the `(...)` in the output of the `gem list` command.
