### ISSUE TITLE
gem push confused

### ISSUE THREAD

**Issue by thoran** [rubygems/rubygems#4705]
I'm having a problem or would like to suggest a feature.

My current problem is that I can't re-push monotonic.rb-0.6.3 to the rubygems.org server. I had the date wrong in the gemspec, have corrected that, re-built the gem, yanked the old one, but can't re-push.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [x] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:
```
$ gem env version
3.2.3
```

**Comment by hsbt** [comment]
It's expected behavior. You can't push the same version after yanking gem.

**Comment by thoran** [comment]
I'd like to change that behaviour. How do I do that?

**Comment by deivid-rodriguez** [comment]
It's not possible to change that behaviour. Releases should be immutable. It sounds like version 0.6.3 of your software had a mistake (all software has mistakes :sweat_smile:). The solution is to correct the mistake and push a new version, for example, 0.6.4.

**Comment by adam12** [comment]
> date wrong in the gemspec

You should remove the date from your gemspec and allow Rubygems to set it for you. Setting a date has been [deprecated for a while](https://github.com/rubygems/rubygems/issues/1232#issuecomment-97253757).

I [removed this instruction from the guides](https://github.com/rubygems/guides/pull/276) a while back, but if you are following another guide or tutorial you should recommend them to do the same.

**Comment by deivid-rodriguez** [comment]
We should probably print a `gem build` warning when date is explicitly set.

**Comment by deivid-rodriguez** [comment]
Rubocop and its community are awesome: https://docs.rubocop.org/rubocop/cops_gemspec.html#gemspecdateassignment :smile:
