### ISSUE TITLE
gem push confused response to already closed ticket

### ISSUE THREAD

**Issue by thoran** [rubygems/rubygems#4706]
I'm having a problem or would like to suggest a feature.

My current problem is that I can't re-push monotonic.rb-0.6.3 to the rubygems.org server. I had the date wrong in the gemspec, have corrected that, re-built the gem, yanked the old one, but can't re-push.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [x] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:
```
$ gem env version
3.2.3
```
Thank you for your earlier response. I responded, but the issue didn't reopen.  So, I created a new one. I'd like to change that behaviour. How do I do that?

**Comment by deivid-rodriguez** [comment]
Please, don't open duplicated issues when your issue gets closed. If you have further questions, you can still comment on the closed ticket. Thanks!

**Comment by hsbt** [comment]
@thoran You should push `monotonic.rb-0.6.3.1` or `monotonic.rb-0.6.4`. We have no plan to change the current behavior.
