### ISSUE TITLE
`Gem::Requirement#==` by `OrderIndependentComparison` raising `NoMethodError` on RubyGems < 3.2.0

### ISSUE THREAD

**Issue by junaruga** [rubygems/rubygems#4714]
I'm having a problem.

My current problem is

I am trying to run Ruby 2.7.3 (RubyGems vesion is 3.1.6)'s tests (`test/rubygems/test_gem_requirement.rb`) with manually backported Bundler 2.2.20 from Bundler 2.1.4 to find a possibility to fix a security issue related to Bundler. On the RubyGems 3.1.6 (< RubyGems 3.2.0.rc.2), in the following code, `Gem::Requirement::OrderIndependentComparison` is loaded, and `Gem::Requirement#==` is overridden.

test/rubygems/test_gem_requirement.rb

https://github.com/rubygems/rubygems/blob/f88fa556d68988e478c2a7881682871b58e62643/test/rubygems/test_gem_requirement.rb#L31

bundler/lib/bundler/rubygems_ext.rb

https://github.com/rubygems/rubygems/blob/f88fa556d68988e478c2a7881682871b58e62643/bundler/lib/bundler/rubygems_ext.rb#L132-L159

This logic was added by https://github.com/rubygems/rubygems/commit/c33914fe2b8c0ebba1f0b4b72f04152e640254c5 .

Then running the test in ruby/ruby, as `Object.new` (`other` object) doen't have `_requirements_sorted` method, I see the following `NoMethodError` error by the above assertion line in `test/rubygems/test_gem_requirement.rb` and `other._requirements_sorted?` in `bundler/lib/bundler/rubygems_ext.rb`.

```
  2) Error:
TestGemRequirement#test_equals2:
NoMethodError: undefined method `_requirements_sorted?' for #<Object:0x0000562bc2858330>
    /builddir/build/BUILD/ruby-2.7.3/lib/bundler/rubygems_ext.rb:137:in `=='
```

To simply the issue, actually this issue can be reproduced on the latest rubygems repo too.

On the latest rubygems master commit `f88fa556d68988e478c2a7881682871b58e62643`, 

```
$ ruby -v
ruby 3.0.1p64 (2021-04-05 revision 0fb782ee38) [x86_64-linux]

$ rake setup
```

Comment out the condition `unless ...` logic to emulate RubyGems < 3.2.0.

```
$ vi bundler/lib/bundler/rubygems_ext.rb

$ git diff
diff --git a/bundler/lib/bundler/rubygems_ext.rb b/bundler/lib/bundler/rubygems_ext.rb
index c95664965c..cd4306aabf 100644
--- a/bundler/lib/bundler/rubygems_ext.rb
+++ b/bundler/lib/bundler/rubygems_ext.rb
@@ -130,7 +130,7 @@ def to_lock
   end
 
   # comparison is done order independently since rubygems 3.2.0.rc.2
-  unless Gem::Requirement.new("> 1", "< 2") == Gem::Requirement.new("< 2", "> 1")
+  # unless Gem::Requirement.new("> 1", "< 2") == Gem::Requirement.new("< 2", "> 1")
     class Requirement
       module OrderIndependentComparison
         def ==(other)
@@ -156,7 +156,7 @@ def _with_sorted_requirements
 
       prepend OrderIndependentComparison
     end
-  end
+  # end
 
   if Gem::Requirement.new("~> 2.0").hash == Gem::Requirement.new("~> 2.0.0").hash
     class Requirement
```

Then run the target test method.

```
$ ruby -Ilib:test test/rubygems/test_gem_requirement.rb -n /test_equals2/
Loaded suite test/rubygems/test_gem_requirement
Started
E
========================================================================================================
Error: test_equals2(TestGemRequirement): NoMethodError: undefined method `_requirements_sorted?' for #<Object:0x00000000015334b8>
/home/jaruga/var/git/rubygems/bundler/lib/bundler/rubygems_ext.rb:137:in `=='
test/rubygems/test_gem_requirement.rb:31:in `test_equals2'
========================================================================================================

Finished in 0.023809665 seconds.
--------------------------------------------------------------------------------------------------------
1 tests, 11 assertions, 0 failures, 1 errors, 0 pendings, 0 omissions, 0 notifications
0% passed
--------------------------------------------------------------------------------------------------------
42.00 tests/s, 462.00 assertions/s
Coverage report generated for Unit Tests to /home/jaruga/var/git/rubygems/coverage. 1085 / 3578 LOC (30.32%) covered.
```

My question is 

The test `test/rubygems/test_gem_requirement.rb` `refute_equal req("= 1.2"), Object.new ` could be modified or `rubygems/bundler/lib/bundler/rubygems_ext.rb` `Gem::Requirement::OrderIndependentComparison` `==` method could be modified?

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

Here are my current environment details:

```
$ gem env version
3.1.6
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by junaruga** [comment]
I was able to pass the test `TestGemRequirement#test_equals2` with Ruby 2.7.3 (RubyGems vesion is 3.1.6) and Bundler 2.2.20 by removing the `==` method in `OrderIndependentComparison` module in `rubygems/bundler/lib/bundler/rubygems_ext.rb`. But I am not sure if this is the right solution.

**Comment by deivid-rodriguez** [comment]
Removing the `==` method is not the right solution since overriding it is the whole point :sweat_smile:. I guess we need to add a `return unless Gem::Requirement == other` guard line as the first line of the method.

**Comment by junaruga** [comment]
OK, not to remove the overriden `==` method. but the suggested line `return unless Gem::Requirement == other` might not be correct. I was able to pass the test adding the `return unless other.class == Gem::Requirement` guard line at the first line of the `==` method.

My environment on `ruby/ruby` is here again.

```
<mock-chroot> sh-5.1$ ruby -v
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]
<mock-chroot> sh-5.1$ gem env version
3.1.6
<mock-chroot> sh-5.1$ gem -v
3.1.6
<mock-chroot> sh-5.1$ bundle -v
Bundler version 2.2.20
```

With your suggested patch,

```
<mock-chroot> sh-5.1$ diff -u lib/bundler/rubygems_ext.rb.org lib/bundler/rubygems_ext.rb
--- lib/bundler/rubygems_ext.rb.org	2021-06-11 13:25:04.000000000 +0200
+++ lib/bundler/rubygems_ext.rb	2021-07-01 23:09:55.722897998 +0200
@@ -134,6 +134,7 @@
     class Requirement
       module OrderIndependentComparison
         def ==(other)
+          return unless Gem::Requirement == other
           if _requirements_sorted? && other._requirements_sorted?
             super
           else
```

The test still fails.

```
<mock-chroot> sh-5.1$ make test-all V=1 TESTS="-v test/rubygems/test_gem_requirement.rb -n TestGemRequirement#test_equals2"
: > revision.tmp
./tool/ifchange "--timestamp=.revision.time" "./revision.h" revision.tmp
./revision.h unchanged
# rm -f revision.h
# : > revision.h || : > revision.h
exec ./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems "./test/runner.rb" --ruby="./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems" --excludes-dir=./test/excludes --name=!/memory_leak/  -v test/rubygems/test_gem_requirement.rb -n TestGemRequirement#test_equals2
Run options: "--ruby=./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems" --excludes-dir=./test/excludes --name=!/memory_leak/ -v -n TestGemRequirement#test_equals2

# Running tests:

[1/0] TestGemRequirement#test_equals2 = 0.02 s

  1) Failure:
TestGemRequirement#test_equals2 [/builddir/build/BUILD/ruby-2.7.3/test/rubygems/test_gem_requirement.rb:17]:
No visible difference in the Gem::Requirement#inspect output.
You should look at the implementation of #== on Gem::Requirement or its members.
Gem::Requirement.new(["= 1.2"])

Finished tests in 0.038007s, 26.3107 tests/s, 26.3107 assertions/s.
1 tests, 1 assertions, 1 failures, 0 errors, 0 skips

ruby -v: ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]
make: *** [uncommon.mk:783: yes-test-all] Error 1
```

Here is the patch I suggest.

```
<mock-chroot> sh-5.1$ diff -u lib/bundler/rubygems_ext.rb.org lib/bundler/rubygems_ext.rb
--- lib/bundler/rubygems_ext.rb.org	2021-06-11 13:25:04.000000000 +0200
+++ lib/bundler/rubygems_ext.rb	2021-07-01 22:59:33.123926006 +0200
@@ -134,6 +134,7 @@
     class Requirement
       module OrderIndependentComparison
         def ==(other)
+          return unless other.class == Gem::Requirement
           if _requirements_sorted? && other._requirements_sorted?
             super
           else
```

The test passed. 😄 

```
<mock-chroot> sh-5.1$ make test-all V=1 TESTS="-v test/rubygems/test_gem_requirement.rb -n TestGemRequirement#test_equals2"
: > revision.tmp
./tool/ifchange "--timestamp=.revision.time" "./revision.h" revision.tmp
./revision.h unchanged
# rm -f revision.h
# : > revision.h || : > revision.h
exec ./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems "./test/runner.rb" --ruby="./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems" --excludes-dir=./test/excludes --name=!/memory_leak/  -v test/rubygems/test_gem_requirement.rb -n TestGemRequirement#test_equals2
Run options: "--ruby=./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems" --excludes-dir=./test/excludes --name=!/memory_leak/ -v -n TestGemRequirement#test_equals2

# Running tests:

[1/0] TestGemRequirement#test_equals2 = 0.02 s
Finished tests in 0.034637s, 28.8708 tests/s, 288.7084 assertions/s.
1 tests, 10 assertions, 0 failures, 0 errors, 0 skips

ruby -v: ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]
```

**Comment by junaruga** [comment]
I also confirmed the test works with the added line `return unless other.class == Gem::Requirement` in the ruybgems repo too.

```
diff --git a/bundler/lib/bundler/rubygems_ext.rb b/bundler/lib/bundler/rubygems_ext.rb
index c95664965c..16d5bb4214 100644
--- a/bundler/lib/bundler/rubygems_ext.rb
+++ b/bundler/lib/bundler/rubygems_ext.rb
@@ -130,10 +130,11 @@ def to_lock
   end
 
   # comparison is done order independently since rubygems 3.2.0.rc.2
-  unless Gem::Requirement.new("> 1", "< 2") == Gem::Requirement.new("< 2", "> 1")
+  # unless Gem::Requirement.new("> 1", "< 2") == Gem::Requirement.new("< 2", "> 1")
     class Requirement
       module OrderIndependentComparison
         def ==(other)
+          return unless other.class == Gem::Requirement
           if _requirements_sorted? && other._requirements_sorted?
             super
           else
@@ -156,7 +157,7 @@ def _with_sorted_requirements
 
       prepend OrderIndependentComparison
     end
-  end
+  # end
 
   if Gem::Requirement.new("~> 2.0").hash == Gem::Requirement.new("~> 2.0.0").hash
     class Requirement
```

```
$ ruby -Ilib:test test/rubygems/test_gem_requirement.rb -n /test_equals2/
Loaded suite test/rubygems/test_gem_requirement
Started
.
Finished in 0.018902168 seconds.
--------------------------------------------------------------------------------------------------------
1 tests, 11 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
--------------------------------------------------------------------------------------------------------
52.90 tests/s, 581.94 assertions/s
Coverage report generated for Unit Tests to /home/jaruga/var/git/rubygems/coverage. 1085 / 3578 LOC (30.32%) covered.
```

**Comment by junaruga** [comment]
For the `other.class` in `return unless other.class == Gem::Requirement`, does the `other.class` always return `NilClass` without raising an error, not depending on Ruby version?

I just confirmed the `nil.class` on Ruby 3.0.1. But I am not sure about old Rubies.

```
$ irb
irb(main):001:0> nil.class
=> NilClass
```

**Comment by deivid-rodriguez** [comment]
@junaruga Sorry, I made a typo in my suggestion! I meant to backport this line from the original method (note the triple equality operator) so that the monkeypatch preserves the property of handling non requirement objects:

https://github.com/rubygems/rubygems/blob/f88fa556d68988e478c2a7881682871b58e62643/lib/rubygems/requirement.rb#L270-L271

**Comment by junaruga** [comment]
Ah okay. I confirmed the ` return unless Gem::Requirement === other` works on the this repo and my patched `ruby/ruby`!

```
$ git diff
diff --git a/bundler/lib/bundler/rubygems_ext.rb b/bundler/lib/bundler/rubygems_ext.rb
index c95664965c..b7342cf98b 100644
--- a/bundler/lib/bundler/rubygems_ext.rb
+++ b/bundler/lib/bundler/rubygems_ext.rb
@@ -130,10 +130,12 @@ def to_lock
   end
 
   # comparison is done order independently since rubygems 3.2.0.rc.2
-  unless Gem::Requirement.new("> 1", "< 2") == Gem::Requirement.new("< 2", "> 1")
+  # unless Gem::Requirement.new("> 1", "< 2") == Gem::Requirement.new("< 2", "> 1")
     class Requirement
       module OrderIndependentComparison
         def ==(other)
+          return unless Gem::Requirement === other
+
           if _requirements_sorted? && other._requirements_sorted?
             super
           else
@@ -156,7 +158,7 @@ def _with_sorted_requirements
 
       prepend OrderIndependentComparison
     end
-  end
+  # end
 
   if Gem::Requirement.new("~> 2.0").hash == Gem::Requirement.new("~> 2.0.0").hash
     class Requirement
```

```
$ ruby -Ilib:test test/rubygems/test_gem_requirement.rb -n /test_equals2/
Loaded suite test/rubygems/test_gem_requirement
Started
.
Finished in 0.018891496 seconds.
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
1 tests, 11 assertions, 0 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
100% passed
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
52.93 tests/s, 582.27 assertions/s
Coverage report generated for Unit Tests to /home/jaruga/var/git/rubygems/coverage. 1085 / 3578 LOC (30.32%) covered.
```

```
```

**Comment by deivid-rodriguez** [comment]
Feel free to provide a PR :+1:.

**Comment by junaruga** [comment]
Okay. Thank you. I will send PR. I am curious why the current GitHub Actions could not find this failure. The case: Ruby 2.7.3 (RubyGems vesion is 3.1.6) + Bundler on master branch. Do you know why? Which GitHub Actions yaml config file should cover this case? If it doesn't cover the case currently, I would like to add the case to the CI too.

**Comment by junaruga** [comment]
Should this file `.github/workflows/bundler.yml` [Bundler 2 on Ubuntu (ruby-2.7)](https://github.com/rubygems/rubygems/pull/4713/checks?check_run_id=2966356101) cover the case? But it passes on master branch right now.

**Comment by deivid-rodriguez** [comment]
Yeah, the line between rubygems and bundler is currently fuzzy at best...

Normally rubygems tests should run without the bundler monkeypatches in `bundler/lib/bundler/rubygems_ext.rb` loaded. However, `bundler` _is actually_ loaded during a rubygems test run, so the `rubygems` code that gets actually tested is "rubygems + the bundler monkeypatches". This could be considered unexpected, but it works fine because the monkeypatches in the local version of bundler (the one in the `bundler/` subfolder) are always compatible with the rubygems code in the root of the repo.

In this case, however, you want to test an old rubygems version 3.1.6 against the monkeypatches included with bundler 2.20.0, and that's what triggered this issue.

Normally, we wouldn't make any changes here, and I would just tell the reporter to upgrade rubygems to get past the issue. But it is true that `bundler` could get installed on top of any supported `rubygems` version, and that without this patch it would be changing the `Gem::Requirement` behaviour of that rubygems version, which seems unexpected.

The cover this change with a test you could add something like this to `.github/workflows/older_rubygems_bundler.yml`

```diff
diff --git a/.github/workflows/older-rubygems-bundler.yml b/.github/workflows/older-rubygems-bundler.yml
index b222644fea..320a222cb8 100644
--- a/.github/workflows/older-rubygems-bundler.yml
+++ b/.github/workflows/older-rubygems-bundler.yml
@@ -61,4 +61,9 @@ jobs:
         run: |
           bin/rake spec:all
         working-directory: ./bundler
+      - name: Run Rubygems Requirement tests against local bundler, to make sure bundler monkeypatches preserve the behaviour
+        run: |
+          RUBYLIB=../../lib rake TEST=test/rubygems/test_gem_requirement.rb
+        working-directory: ./bundler/tmp/rubygems
+
     timeout-minutes: 60
```

But that might trigger other issues on other rubygems versions, not really sure. Alternatively we could write custom test for bundler itself.

**Comment by junaruga** [comment]
Here is [the GitHub Actions results on my forked repo](https://github.com/junaruga/rubygems/runs/2972211589?check_suite_focus=true). I added [2 commits](https://github.com/junaruga/rubygems/commits/wip/rubygems-less-than-3.2-gem-requirement-equal) that are a commit to enable GitHub Actions on a forked repo and a commit to add a test case on the CI mentioned above. It's great if you check the failed results, and give me an advice to fix it. Thanks.

**Comment by deivid-rodriguez** [comment]
From looking at the errors (something with `rake` and/or `hoe`), I would try to run the tests directly without going through `rake`.

**Comment by junaruga** [comment]
Thanks. I am debugging the errors too now. What is the `bin/rake` used in `.github/workflows/older-rubygems-bundler.yml`? Who installs the `bin/rake`?

**Comment by junaruga** [comment]
> What is the bin/rake used in .github/workflows/older-rubygems-bundler.yml? What installs the bin/rake?

I found it. It is the `bundler/bin/rake` managed on this repo.

**Comment by junaruga** [comment]
I am running the following test with `../../bin/rake`. And I got the same result with `rake` on GitHub Actions. But Which directory's `Rakefile` is executed? Because I think the `./bundler/tmp/rubygems` is a created new directory. And there is no `Rakefile` on the directory, right?

```
diff --git a/.github/workflows/older-rubygems-bundler.yml b/.github/workflows/older-rubygems-bundler.yml
index cc5a680095..d48fa82dbe 100644
--- a/.github/workflows/older-rubygems-bundler.yml
+++ b/.github/workflows/older-rubygems-bundler.yml
@@ -61,4 +61,8 @@ jobs:
         run: |
           bin/rake spec:all
         working-directory: ./bundler
+      - name: Run Rubygems Requirement tests against local bundler, to make sure bundler monkeypatches preserve the behaviour
+        run: |
+          RUBYLIB=../../lib ../../bin/rake TEST=test/rubygems/test_gem_requirement.rb
+        working-directory: ./bundler/tmp/rubygems
     timeout-minutes: 60
```

**Comment by junaruga** [comment]
It seems when emulating the CI job on my local, the `rake` command tries to execute `rubygems/bundler/Rakefile` unlike GitHub Actions.

```
$ ruby -v
ruby 2.7.3p183 (2021-04-05 revision 6847ee089d) [x86_64-linux]

$ cd bundler

$ bin/rake spec:parallel_deps

$ bin/rake spec:all

$ mkdir tmp/rubygems

$ cd tmp/rubygems

$ RUBYLIB=../../lib ../../bin/rake -T
(in /home/jaruga/var/git/rubygems/bundler)
rake build                                # Build bundler-2.3.0.dev.gem into the pkg directory
rake build:checksum                       # Generate SHA512 checksum if bundler-2.3.0.dev.gem into the checksums directory
...

$ RUBYLIB=../../lib ../../bin/rake --verbose TEST=test/rubygems/test_gem_requirement.rb
(in /home/jaruga/var/git/rubygems/bundler)
bin/rspec
Run options: exclude {:truffleruby=>true, :jruby=>true, :readline=>false, :permissions=>false, :no_color_tty=>false, :ruby_repo=>false, :bundler=>"!= 2", :git=>"!= 2.31.1", :realworld=>true, :sudo=>true}

Randomized with seed 51973
...
```

**Comment by deivid-rodriguez** [comment]
Sorry @junaruga, my suggestion was too vague. I meant, since `rake` seems to be giving some trouble, run the test directly without `rake`, like:

    ruby -I../../lib:lib:test test/rubygems/test_gem_requirement.rb

**Comment by junaruga** [comment]
OK. Thank you. I will try it. Is the following command to run every tests problem instead of the command you suggested?

```
$ ruby -I../../lib:lib:test -e 'Dir.glob "./test/**/test_*.rb", &method(:require)'
```

I noticed the `./bundler/tmp/rubygems` directory is created by the `bin/rake spec:parallel_deps` in GitHub Actions, while the command complains on my local like this. That's way there was a difference between GitHub Actions and my local.

```
$ pwd
/home/jaruga/var/git/rubygems/bundler

$ bin/rake spec:parallel_deps
Following files may not be writable, so sudo is needed:
  /usr/local/ruby-2.7.3/bin
  /usr/local/ruby-2.7.3/lib/ruby/gems/2.7.0
  /usr/local/ruby-2.7.3/lib/ruby/gems/2.7.0/build_info
  /usr/local/ruby-2.7.3/lib/ruby/gems/2.7.0/cache
  /usr/local/ruby-2.7.3/lib/ruby/gems/2.7.0/doc
  /usr/local/ruby-2.7.3/lib/ruby/gems/2.7.0/extensions
  /usr/local/ruby-2.7.3/lib/ruby/gems/2.7.0/gems
  /usr/local/ruby-2.7.3/lib/ruby/gems/2.7.0/plugins
  /usr/local/ruby-2.7.3/lib/ruby/gems/2.7.0/specifications
```

**Comment by junaruga** [comment]
I was able to reproduce [the error](https://github.com/junaruga/rubygems/runs/2983310897?check_suite_focus=true
) on GitHub Actions on my forked repo.
