### ISSUE TITLE
Contradictory output when trying to uninstall a default gem

### ISSUE THREAD

**Issue by jaredbeck** [rubygems/rubygems#4733]
This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
3.2.22
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

# Observed behavior

```
gem uninstall bundler
Gem bundler-2.2.22 cannot be uninstalled because it is a default gem
...
Successfully uninstalled bundler-2.2.22
```

These two statements are contradictory.

Also, it is unclear what state the system has been left in.

# Expected behavior

`gem` should not print contradictory statements.

# Full output

```
gem uninstall bundler
Gem bundler-2.2.22 cannot be uninstalled because it is a default gem

You have requested to uninstall the gem:
	bundler-2.2.22

bundler-audit-0.8.0 depends on bundler (>= 1.2.0, < 3)
libyear-bundler-0.5.3 depends on bundler (>= 1.14, < 3)
rails-6.0.4 depends on bundler (>= 1.3.0)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  y
Remove executables:
	bundle, bundler

in addition to the gem? [Yn]  Y
Removing bundle
Removing bundler
Successfully uninstalled bundler-2.2.22
gem uninstall bundler
Gem bundler-2.2.22 cannot be uninstalled because it is a default gem

**Comment by deivid-rodriguez** [comment]
Indeed...

Can you show the result of `gem list bundler` before and after running the command? I tried to reproduce it but I got the expected behaviour, namely, only

> Gem bundler-2.2.22 cannot be uninstalled because it is a default gem

was printed and nothing was uninstalled.

**Comment by jaredbeck** [comment]
Thanks for the quick reply David.

> Can you show the result of gem list bundler before and after running the command?

# Before

```plain
gem list bundler

*** LOCAL GEMS ***

bundler (2.2.22)
bundler-audit (0.8.0)
libyear-bundler (0.5.3)
```

# Command

```plain
gem uninstall bundler
Gem bundler-2.2.22 cannot be uninstalled because it is a default gem
# ... see "Full Output" above
Removing bundler
Successfully uninstalled bundler-2.2.22
```

# After

```plain
gem list bundler

*** LOCAL GEMS ***

bundler (default: 2.2.22)
bundler-audit (0.8.0)
libyear-bundler (0.5.3)
```

**Comment by jaredbeck** [comment]
Critical diff:

```diff
- bundler (2.2.22)
+ bundler (default: 2.2.22)
```

It seems possible to have two copies of the same version installed, i.e. the "default copy" and the "non-default" copy.

**Comment by deivid-rodriguez** [comment]
I see... I can repro now.

I guess what's going on is correct, we just have to explain that we're removing the regular copy, but will still leave the default gem that the regular gem was shadowing.

Alternatively, we could prevent installing a gem as a regular gem if the same version is a default gem, but I have a vague recollection about that ability being useful for some people... :thinking:

**Comment by jaredbeck** [comment]
> I guess what's going on is correct, we just have to explain that we're removing the regular copy, but will still leave the default gem that the regular gem was shadowing.

Yeah, simply improving the message is probably the safest way (most compatible). I can take a stab at that if you want.

**Comment by deivid-rodriguez** [comment]
Sure!
