### ISSUE TITLE
`bundle add` for `github:` and `ref:`?

### ISSUE THREAD

**Issue by JohnRDOrazio** [rubygems/rubygems#4740]
Continuing an issue that was opened for adding `git:` and `branch:` options to `bundle add` (see here: https://github.com/rubygems/bundler/issues/6841), it would be likewise neat to have `github:` and `ref:` options for `bundle add`.

So I can get a result like this:
```bash
gem 'webpacker', github: 'rails/webpacker', ref: 'b6c2180'
```

By issuing something like this:
```bash
$ bundle add webpacker --github 'rails/webpacker' --ref 'b6c2180'
```

[PR #7127](https://github.com/rubygems/bundler/pull/7127) added the `--git` and `--branch` switches, perhaps it wouldn't be too difficult to add `--github` and `--ref` switches?

**Comment by deivid-rodriguez** [comment]
Ok from my side.
