### ISSUE TITLE
Tests failing after upgrading to 2.2.23: gem being removed after `bundler install` 

### ISSUE THREAD

**Issue by luizkowalski** [rubygems/rubygems#4748]
### Describe the problem as clearly as you can
I noticed that after upgrading to 2.2.23, my actions started to fail. It appears that bundler removes `sqlite3` gem after installing it.

This was before: https://github.com/luizkowalski/concurrent_rails/runs/3026767718?check_suite_focus=true
you can see that it warns me that `sqlite3` is listed twice but doesn't do anything. 

Now, on 2.2.23. it doesn't trigger any warnings, it simply deletes the gem:
https://github.com/luizkowalski/concurrent_rails/runs/3031035949?check_suite_focus=true

### Post steps to reproduce the problem
Shown above

### Which command did you run?
Shown above

I didn't fill the other sections because I believe the gh action log contains everything

**Comment by deivid-rodriguez** [comment]
Oooooops, seems a regression of https://github.com/rubygems/rubygems/pull/4732. I'll have a look, thanks for the report.

**Comment by deivid-rodriguez** [comment]
By the way, to workaround the issue, and also get rid of the warning at the same time, you can completely remove the `add_development_dependency "sqlite", "~> 1.4"`, and make sure all gemfiles include the dependency.

**Comment by luizkowalski** [comment]
yep, that fixed the issue: https://github.com/luizkowalski/concurrent_rails/pull/8

**Comment by mojavelinux** [comment]
My projects are also being affected by this, but for a slightly different reason. The gemspec declares the dependency version that the gem ships with, whereas the Gemfile is used to override the dependency to test against an older version. After the upgrade to bundler 2.2.23, the gem isn't installed at all (thus resulting in the tests failing).

**Comment by deivid-rodriguez** [comment]
The workaround should work for you too I believe @mojavelinux? Anyways, I'm planning to look at this soon.

**Comment by mojavelinux** [comment]
In some cases, I have to have the gem listed in both places, with the Gemfile overriding the gemspec. My understanding was that this was a perfectly legitimate use case. It's especially useful for CI. So no, the workaround doesn't work in all cases. And it's a pretty significant change for it to have happened in a patch release, so my hope is that it will be reverted.

**Comment by deivid-rodriguez** [comment]
I didn't say I'm not going to fix this, I have acknowledged this is a regression, and I said I will look at it.

I'm just saying that `add_development_dependency` is completely unnecessary these days, and you can just remove it in favour of specifying your development dependencies in your Gemfile. It's just some remanent from a pre-bundler that has been completely obsoleted now.

Are you broken repositories public? I'd like to understand what is it that doesn't work for your case.

**Comment by mojavelinux** [comment]
I didn't mean to suggest you weren't going to fix it or trying to be accusatory. I was just being clear about my case and how I view this issue.

You can find one example here:

* https://github.com/asciidoctor/asciidoctor-pdf/blob/main/asciidoctor-pdf.gemspec#L38-L39
* https://github.com/asciidoctor/asciidoctor-pdf/blob/main/Gemfile#L14

In this case, I'm not overriding a development dependency. I'm overriding a runtime one. (I do override development dependencies in other cases, but the workaround would apply for those).

> I'm just saying that add_development_dependency is completely unnecessary these days, and you can just remove it in favour of specifying your development dependencies in your Gemfile. 

That's not entirely true. rubygems.org reports development dependencies from the gemspec but not from the Gemfile. So there is an important difference. I'm not saying that we have to have development dependencies listed on rubygems.org, but it's still a pretty major change if we are moving away from putting them in the gemspec.

**Comment by deivid-rodriguez** [comment]
> I didn't mean to suggest you weren't going to fix it or trying to be accusatory. I was just being clear about my case and how I view this issue.

Ok.

> In this case, I'm not overriding a development dependency. I'm overriding a runtime one. (I do override development dependencies in other cases, but the workaround would apply for those).

Oh, wait, so did something break related to runtime dependencies? I thought the problem only affected overriding development dependencies :fearful:.

> That's not entirely true. rubygems.org reports development dependencies from the gemspec but not from the Gemfile. So there is an important difference. I'm not saying that we have to have development dependencies listed on rubygems.org, but it's still a pretty major change if we are moving away from putting them in the gemspec.

That's a good point, although that's currently quite misleading because it only lists development dependencies listed in the gemspec. I think it'd be fine to remove this information from rubygems.org, the place to know what you need to install to contribute and how should be the upstream repo, but it's something to definitely consider if/when we decide to deprecate it.

**Comment by mojavelinux** [comment]
> I thought the problem only affected overriding development dependencies

I just checked and you are correct. Since I had issues with the development dependencies, I had assumed it was the same for runtime dependencies. That was not a correct assumption.

**Comment by deivid-rodriguez** [comment]
https://github.com/rubygems/rubygems/pull/4751 should fix this!
