### ISSUE TITLE
Spurious Bundler.ui.debug message appearing in output stream.

### ISSUE THREAD

**Issue by caponecicero** [rubygems/rubygems#4752]
### Describe the problem as clearly as you can

I have a simple test driver program.  It uses a number of gems installed using bundler.  I run the test driver using **bats** as follows:
```
@test "pathtest sender $MAILBOX" {
	run $pathtest sender $MAILBOX
	echo ${lines[0]} >&3
	echo ${lines[1]} >&3
	[ $status -eq 0 ]
	[ "${lines[0]}" = "/srv/mail/var/domain/bar.com/foo/~mt" ]
}
```
`$pathtest` is the name of the program: `/srv/mail/lib/tools/tag/test/bin/pathtest`.  `$MAILBOX` is an email address...`foo@bar.com`.  The ruby program file has the following shebang line: `#!/usr/bin/env -S ruby -W0`.

When I run the program from bash, it works as expected.  When I run the program from this test setup, I get the following in `$lines`:

`${lines[0]`:  **_Found no changes, using resolution from the lockfile_**  (this is a *Bundler.ui.debug* message)
`${lines[1]`:  **_/srv/mail/var/domain/bar.com/foo/~mt_**  (the expected program output)

`${lines[0]` is supposed to be the program output.  The program is pretty simple.  It transforms the email address `foo@bar.com` into the file system path `/srv/mail/var/domain/bar.com/foo/~mt`.

Why am I getting the debug message?  It's causing a bunch of tests to fail (the `run` command runs the program with the arguments given and preserves stdout/stderr in `$lines` and the program exit status in `$status`.

* How your ruby is setup (OS package, from source, using a version manager).

ruby v.3.0.2/bundler 2.2.23.  ruby/bundler (2.2.22) are built from source.

* How bundler & rubygems are configured.

 bundler was subsequently updated with `gem` to 2.2.23.

* The version of each involved piece of software that you are using.

The OS is FreeBSD 13.0.  **bats** is 1.3.0.  **bash** is 5.1.8.

I don't expect that you'll be able to reproduce this.  I'm just hoping that someone can give me a pointer on how to suppress Bundler.ui.debug messages and/or help me understand why I'm seeing it in the first place.

Thank you...

**Comment by deivid-rodriguez** [comment]
Hi @caponecicero. Bundler's debug output is enabled if there's a `DEBUG` environment variable set. Hopefully that helps you track down the issue!

**Comment by caponecicero** [comment]
I found it.  Thank you.
