### ISSUE TITLE
Help broken for `bundle plugin install`

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems#4753]
### Describe the problem as clearly as you can

The `--help` / `-h` flag does not work for the subcommand `bundle plugin install`.

### Which command did you run?

Run `bundle plugin install -h`.

### What were you expecting to happen?

I was expecting to see help for `bundle plugin install`, something like the output as you get when you run `bundle plugin help install`.

### What actually happened?

Instead, I got the manpage for `bundle install`, a completely different command. The same as if I had simply run `bundle install -h`.

### If not included with the output of your command, run `bundle env` and paste the output below

```
❯ bundle env
Bundler       2.2.23
  Platforms   ruby, arm64-darwin-20
Ruby          3.0.1p64 (2021-04-05 revision 0fb782ee38ea37fd5fe8b1f775f8ad866a82a3f0) [arm64-darwin20]
  Full Path   /Users/andre/.rubies/ruby-3.0.1/bin/ruby
  Config Dir  /Users/andre/.rubies/ruby-3.0.1/etc
RubyGems      3.2.15
  Gem Home    /Users/andre/.gem/ruby/3.0.1
  Gem Path    /Users/andre/.gem/ruby/3.0.1:/Users/andre/.rubies/ruby-3.0.1/lib/ruby/gems/3.0.0
  User Home   /Users/andre
  User Path   /Users/andre/.gem/ruby/3.0.0
  Bin Dir     /Users/andre/.gem/ruby/3.0.1/bin
Tools         
  Git         2.30.1
  RVM         not installed
  rbenv       not installed
  chruby      0.3.9
```

**Comment by deivid-rodriguez** [comment]
Nice find, https://github.com/rubygems/rubygems/pull/4756 should fix it!
