### ISSUE TITLE
Generated `Gemfile.lock` does not correctly list remote for indirect dependencies of private gems

### ISSUE THREAD

**Issue by Maimer** [rubygems/rubygems#4757]
### Describe the problem as clearly as you can

When generating a `Gemfile.lock` that contains public gems from `https://rubygems.org` and private gems from `https://rubygems.pkg.github.com/`, the generated file does not correctly list the remote for public gems that are dependencies of private gems. Instead, it lists those dependencies with no remote and it results in an error when trying to install from that `Gemfile.lock` due to not being able to find those gems locally on a machine that does not already have those gems installed.

### Post steps to reproduce the problem

As the gems that cause the issue are private gems on Github Packages, I am not sure there is an easy way to provide a way to reproduce outside of a general example.

Gemfile:

```ruby
source 'https://rubygems.pkg.github.com/organization' do
  # for this example's purpose we will say this gem depends on a gem called "another_public_gem" from https://rubygems.org
  gem 'private_gem'
end

source 'https://rubygems.org' do
  gem 'public_gem'
end
``` 

When running `bundle install` this will generate a `Gemfile.lock` that looks like this:

```ruby
GEM
  specs:
    another_public_gem (1.0.0)

GEM
  remote: https://rubygems.org/
  specs:
    public_gem (1.0.0)

GEM
  remote: https://rubygems.pkg.github.com/organization/
  specs:
    private_gem (1.0.0)
      another_public_gem (1.0.0)

PLATFORMS
  ruby

DEPENDENCIES
  another_public_gem (= 1.0.0)
  public_gem (= 1.0.0)
  private_gem (= 1.0.0)

BUNDLED WITH
   2.2.23
```

Then when running the command `bundle install` on a machine without these gems installed it fails with this error:

```
Fetching gem metadata from https://rubygems.org/
Fetching gem metadata from https://rubygems.org/.........
Fetching gem metadata from https://rubygems.pkg.github.com/organization/.
Fetching gem metadata from https://rubygems.pkg.github.com/organization/.....
Your bundle is locked to another_public_gem (1.0.0) from locally installed gems, but
that version can no longer be found in that source. That means the author of
another_public_gem (1.0.0) has removed it. You'll need to update your bundle to a
version other than another_public_gem (1.0.0) that hasn't been removed in order to
install.
```

### Which command did you run?

I am running `bundle install` to generate a `Gemfile.lock`

### What were you expecting to happen?

I would expect the dependencies of gems to correctly be listed under their respective remote sources. I am not sure if this is a failure on behalf of bundler or if Github Packages does not return the correct dependency tree when installing gems from that source.

### What actually happened?

Public dependencies of private gems from the Github Packages source are incorrectly listed in the `Gemfile.lock` without a remote.

### If not included with the output of your command, run `bundle env` and paste the output below

```
Bundler             2.2.23
  Platforms         ruby, x86_64-darwin-19
Ruby                2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]
  Full Path         /Users/user/.rvm/rubies/ruby-2.6.3/bin/ruby
  Config Dir        /Users/user/.rvm/rubies/ruby-2.6.3/etc
RubyGems            3.0.6
  Gem Home          /Users/user/.rvm/gems/ruby-2.6.3
  Gem Path          /Users/user/.rvm/gems/ruby-2.6.3:/Users/user/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0
  User Home         /Users/user
  User Path         /Users/user/.gem/ruby/2.6.0
  Bin Dir           /Users/user/.rvm/gems/ruby-2.6.3/bin
Tools
  Git               2.32.0
  RVM               1.29.12 (latest)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

**Comment by deivid-rodriguez** [comment]
This has come up before, and I agree it's confusing but I had to keep this behaviour for backwards compatibility.

In the Gemfile you posted, the public dependencies from the gem `private_gem` should be picked up from the global source. Since there's no explicit global source, bundler uses an implicit global source, which includes only public gems. So the reason why bundler is locking `another_public_gem` under this remoteless source is most likely because you already have it installed. If you uninstall it with `gem uninstall another_public_gem`, and then rerun `bundle install` again, `bundler` show now give you an error about not being able to find `another_public_gem` in locally installed gems.

As I said, I agree this is confusing behaviour, but I had to keep it there for backwards compatibility. So:

* _What you can do on your side_. Make sure you always specify a global source, so change your `Gemfile` to the following, so that both dependencies of globally specified gems, and dependencies of gems under block sources are picked up from `https://rubygems.org`.

```
source 'https://rubygems.org'

gem 'public_gem'

source 'https://rubygems.pkg.github.com/organization' do
  # for this example's purpose we will say this gem depends on a gem called "another_public_gem" from https://rubygems.org
  gem 'private_gem'
end
```

* _What we can do on our side_. Deprecate the implicit global source that picks up gems from the local system, since they are really confusing and almost always not want you want.

**Comment by deivid-rodriguez** [comment]
Closing in favour of #4759, but let me know if I missed something.

**Comment by Maimer** [comment]
Thanks for the quick response! I tried using the global source as you recommended, but it only seems to work if the dependencies of my dependencies all come from that same global source. In my workflow I have private gems that depend on both public gems and other private gems. So if I define a global source of `https://rubygems.org` then it incorrectly tries to get the private gem dependencies from that incorrect global source.

Consider this scenario: We have a `private_gem` that depends on a public gem and another private gem. How can I define a global source(s) so that gets each gem from the appropriate source? I tried adding this to my `Gemfile`:

```
source 'https://rubygems.org'
source 'https://rubygems.pkg.github.com/organization'
```

However, the results were now 3 separate `GEM` sections and none of them having the correct list of gems.

I see my current two options as either: use the old style of the `Gemfile.lock` where all remotes are listed for all gems, or I manually edit the `Gemfile.lock` to move the gems without an explicit source into their respective remotes.

**Comment by deivid-rodriguez** [comment]
> In my workflow I have private gems that depend on both public gems and other private gems. So if I define a global source of https://rubygems.org then it incorrectly tries to get the private gem dependencies from that incorrect global source.

As long as you properly scope your private source, this should work as expected. Private gems that are present in that source will be picked up from there, and anything else will be picked up from rubygems.org.

**Comment by Maimer** [comment]
> > In my workflow I have private gems that depend on both public gems and other private gems. So if I define a global source of https://rubygems.org then it incorrectly tries to get the private gem dependencies from that incorrect global source.
> 
> As long as you properly scope your private source, this should work as expected. Private gem dependencies that are present in that source will be picked up from there, and anything else will be picked up from rubygems.org.

I must have been doing something incorrect when I was trying it before. I tried it once again and it worked this time, thanks for all the help and your work on bundler!
