### ISSUE TITLE
incorrect paths in `setup.rb` when using `bundle install --standalone` and filesystem gems

### ISSUE THREAD

**Issue by citrusmoose** [rubygems/rubygems#4758]
### Describe the problem as clearly as you can

When using `bundle install --standalone`, the `setup.rb` file produced adds relative paths to `setup.rb` into `$:`.  This is fine for installed gems, but this breaks for filesystem gems outside the project (e.g. `gem 'minitest', '5.13.0', path: '/usr/local/lib/ruby/gems/2.7.0/gems/minitest-5.13.0/lib'`) when the packaged bundle is deployed to a different directory level than originally installed.

### Post steps to reproduce the problem

`Dockerfile`

```Dockerfile
FROM ruby:2.7.4

RUN gem install bundler -v 2.2.23

WORKDIR /app

RUN true \
  && echo "gem 'minitest', '5.13.0', path: '/usr/local/lib/ruby/gems/2.7.0/gems/minitest-5.13.0/lib'" >Gemfile \
  && bundle lock \
  && bundle env \
  && BUNDLE_DEPLOYMENT=true bundle install --standalone

WORKDIR /pkgs

RUN tar -C /app -cf my_app.tgz .

WORKDIR /a/diff/dir/level

RUN tar -xf /pkgs/my_app.tgz
RUN ruby -r './vendor/bundle/bundler/setup' -e "pp $:; require 'minitest'"
```

### What were you expecting to happen?

I expected to see `require 'minitest'` to succeed.

### What actually happened?

`require 'minitest'` fails because the load path to the `minitest` gem is incorrect.  It's prefixed with install directory rather than the absolute path provided in the `Gemfile`.

`$ docker build .`

    Sending build context to Docker daemon   2.56kB
    Step 1/9 : FROM ruby:2.7.4
     ---> 1faa5f2f8ca3
    Step 2/9 : RUN gem install bundler -v 2.2.23
     ---> Running in 8dc53c1b3994
    Successfully installed bundler-2.2.23
    1 gem installed
    Removing intermediate container 8dc53c1b3994
     ---> 7045ecc3faad
    Step 3/9 : WORKDIR /app
     ---> Running in 92943be13d58
    Removing intermediate container 92943be13d58
     ---> f3cabb0eaea0
    Step 4/9 : RUN true   && echo "gem 'minitest', '5.13.0', path: '/usr/local/lib/ruby/gems/2.7.0/gems/minitest-5.13.0/lib'" >Gemfile   && bundle lock   && bundle env   && BUNDLE_DEPLOYMENT=true bundle install --standalone
     ---> Running in aee5b152f981
    Resolving dependencies...
    Writing lockfile to /app/Gemfile.lock
    ## Environment
    
    ```
    Bundler       2.2.23
      Platforms   ruby, x86_64-linux
    Ruby          2.7.4p191 (2021-07-07 revision a21a3b7d23704a01d34bd79d09dc37897e00922a) [x86_64-linux]
      Full Path   /usr/local/bin/ruby
      Config Dir  /usr/local/etc
    RubyGems      3.1.6
      Gem Home    /usr/local/bundle
      Gem Path    /root/.gem/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/local/bundle
      User Home   /root
      User Path   /root/.gem/ruby/2.7.0
      Bin Dir     /usr/local/bundle/bin
    Tools
      Git         2.20.1
      RVM         not installed
      rbenv       not installed
      chruby      not installed
    ```
    
    ## Bundler Build Metadata
    
    ```
    Built At          2021-07-09
    Git SHA           e863a3905d
    Released Version  true
    ```
    
    ## Bundler settings
    
    ```
    app_config
      Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
    silence_root_warning
      Set via BUNDLE_SILENCE_ROOT_WARNING: true
    ```
    
    ## Gemfile
    
    ### Gemfile
    
    ```ruby
    gem 'minitest', '5.13.0', path: '/usr/local/lib/ruby/gems/2.7.0/gems/minitest-5.13.0/lib'
    ```
    
    ### Gemfile.lock
    
    ```
    PATH
      remote: /usr/local/lib/ruby/gems/2.7.0/gems/minitest-5.13.0/lib
      specs:
        minitest (5.13.0)
    
    GEM
      specs:
    
    PLATFORMS
      x86_64-linux
    
    DEPENDENCIES
      minitest (= 5.13.0)!
    
    BUNDLED WITH
       2.2.23
    ```
    Using bundler 2.2.23
    Using minitest 5.13.0 from source at `/usr/local/lib/ruby/gems/2.7.0/gems/minitest-5.13.0/lib`
    Bundle complete! 1 Gemfile dependency, 2 gems now installed.
    Bundled gems are installed into `./vendor/bundle`
    Removing intermediate container aee5b152f981
     ---> c0e85d8f85cd
    Step 5/9 : WORKDIR /pkgs
     ---> Running in 689f3377d582
    Removing intermediate container 689f3377d582
     ---> 3966ad1f9d99
    Step 6/9 : RUN tar -C /app -cf my_app.tgz .
     ---> Running in 9ac491af7a5d
    Removing intermediate container 9ac491af7a5d
     ---> 7306b8adaaa6
    Step 7/9 : WORKDIR /a/diff/dir/level
     ---> Running in b0b146437f5b
    Removing intermediate container b0b146437f5b
     ---> 3428fc925a85
    Step 8/9 : RUN tar -xf /pkgs/my_app.tgz
     ---> Running in 6a4311b43248
    Removing intermediate container 6a4311b43248
     ---> 998e32e4b71c
    Step 9/9 : RUN ruby -r './vendor/bundle/bundler/setup' -e "pp $:; require 'minitest'"
     ---> Running in 879314ab301d
    -e:1:in `require': cannot load such file -- minitest (LoadError)
      from -e:1:in `<main>'
    ["/a/diff/dir/usr/local/lib/ruby/gems/2.7.0/gems/minitest-5.13.0/lib/lib",
     "/a/diff/dir/level/vendor/bundle/bundler",
     "/usr/local/lib/ruby/site_ruby/2.7.0",
     "/usr/local/lib/ruby/site_ruby/2.7.0/x86_64-linux",
     "/usr/local/lib/ruby/site_ruby",
     "/usr/local/lib/ruby/vendor_ruby/2.7.0",
     "/usr/local/lib/ruby/vendor_ruby/2.7.0/x86_64-linux",
     "/usr/local/lib/ruby/vendor_ruby",
     "/usr/local/lib/ruby/2.7.0",
     "/usr/local/lib/ruby/2.7.0/x86_64-linux"]
    The command '/bin/sh -c ruby -r './vendor/bundle/bundler/setup' -e "pp $:; require 'minitest'"' returned a non-zero code: 1

**Comment by intuxicated** [comment]
Hi @citrusmoose,

I'm looking into this issue. If you are blocked, you may be able to achieve what you need by doing the following:

- Replace `/usr/local/lib/ruby/gems/2.7.0/gems/minitest-5.13.0/lib` with `/usr/local/lib/ruby/gems/2.7.0/gems/minitest-5.13.0/`
  `lib` will be added automatically so you can omit that.
- Add `bundle config set --local path /a/diff/dir/level`
- run `./bundler/setup.rb` instead of `./vendor/bundle/bundler/setup`

```diff
   FROM ruby:2.7.4
 
   RUN gem install bundler -v 2.2.23
 
   WORKDIR /app
 
   RUN true \
-    && echo "gem 'minitest', '5.13.0', path: '/usr/local/lib/ruby/gems/2.7.0/gems/minitest-5.13.0/lib'" >Gemfile \
+    && echo "gem 'minitest', '5.13.0', path: '/usr/local/lib/ruby/gems/2.7.0/gems/minitest-5.13.0'" >Gemfile \
+    && bundle config set --local path /a/diff/dir/level \
     && bundle lock \
     && bundle env \
     && BUNDLE_DEPLOYMENT=true bundle install --standalone
 
   WORKDIR /pkgs
 
   RUN tar -C /app -cf my_app.tgz .
 
   WORKDIR /a/diff/dir/level
 
   RUN tar -xf /pkgs/my_app.tgz
-  RUN ruby -r './vendor/bundle/bundler/setup' -e "pp $:; require 'minitest'"
+  RUN ruby -r './bundler/setup.rb' -e "pp $:; require 'minitest'"

```

Hope this helps.

**Comment by deivid-rodriguez** [comment]
Hi @citrusmoose!

As @intuxicated points out, a `path` source should not point to the target `lib` folder, but to the root of the repository. Bundler deals with require paths inside the repo for you.

With that change in place, I think this patch should fix your issue: https://github.com/rubygems/rubygems/compare/standalone_and_path_sources.

Please give it a try and let me know and I'll add some specs and propose a PR.

**Comment by citrusmoose** [comment]
Thanks @deivid-rodriguez, this change worked perfectly!

**Comment by deivid-rodriguez** [comment]
Awesome, I will prepare a pull request tomorrow.
