### ISSUE TITLE
`SharedHelpers.trap` assumes the prior handler for the signal is callable

### ISSUE THREAD

**Issue by haines** [rubygems/rubygems#4764]
### Describe the problem as clearly as you can

`SharedHelpers.trap` attempts to preserve any existing handler for a signal by invoking `call` on it.

https://github.com/rubygems/rubygems/blob/e7bf6b42cae52e4c6f400dd346659711dfb2c31c/bundler/lib/bundler/shared_helpers.rb#L148-L153

However, `prior` can be a string, resulting in 

```
NoMethodError: undefined method `call' for "DEFAULT":String
```

### Post steps to reproduce the problem

Run this script:

```ruby
# frozen_string_literal: true

require 'bundler/inline'

gemfile true do # force installation so that SharedHelpers.trap('INT') is called in Bundler::Worker#initialize
  source 'https://rubygems.org'
  gem 'rake'
end

Process.kill 'INT', Process.pid
# => bundler/shared_helpers.rb:158:in `block in trap': undefined method `call' for "DEFAULT":String (NoMethodError)
```

### Which command did you run?

`bundler/inline`

### What were you expecting to happen?

I get the standard Ruby `Interrupt` exception when I interrupt the script

### What actually happened?

If Bundler installed any gems, I get `NoMethodError`. If Bundler did not install any gems (and therefore did not trap SIGINT) then I get the correct `Interrupt`.

### If not included with the output of your command, run `bundle env` and paste the output below

```
Bundler       2.2.23
  Platforms   ruby, x86_64-darwin-20
Ruby          2.7.3p183 (2021-04-05 revision 6847ee089d7655b2a0eea4fee3133aeacd4cc7cc) [x86_64-darwin20]
  Full Path   /Users/andrew/.rubies/ruby-2.7.3/bin/ruby
  Config Dir  /Users/andrew/.rubies/ruby-2.7.3/etc
RubyGems      3.2.23
  Gem Home    /Users/andrew/.gem/ruby/2.7.3
  Gem Path    /Users/andrew/.gem/ruby/2.7.3:/Users/andrew/.rubies/ruby-2.7.3/lib/ruby/gems/2.7.0
  User Home   /Users/andrew
  User Path   /Users/andrew/.gem/ruby/2.7.0
  Bin Dir     /Users/andrew/.gem/ruby/2.7.3/bin
Tools         
  Git         2.32.0
  RVM         not installed
  rbenv       not installed
  chruby      0.3.9
```

**Comment by deivid-rodriguez** [comment]
Thanks for the report. Can you send us a patch?
