### ISSUE TITLE
Strange error message when load errors occur in gemspec

### ISSUE THREAD

**Issue by searls** [rubygems/rubygems#4769]
I had `require`d a file from a misnamed directory in my gemspec and noticed this sort of strange error ([source](https://github.com/rubygems/rubygems/blob/6a5a1a4af23526e24f21b558517bb8948a6e4ff5/bundler/lib/bundler.rb#L657)):

> Does it try to require a relative path? That's been removed in Ruby 1.9. Bundler cannot continue.

Since it was actually a `require_relative` call that had been generated by `bundle gem`, I had to do a double-take before realizing that this error was referencing old 1.8 load path behavior and figured that the message could probably be updated (or allowed to fall back to whatever the built-in load error message is), since the root cause is more likely to be a non-existent file path.

Thoughts?

**Comment by deivid-rodriguez** [comment]
Definitely, we should at least remove that part of the error message since it's misleading.
