### ISSUE TITLE
`bundle binstubs --all` generates a binstub for `bundle` that invokes the wrong version of Bundler

### ISSUE THREAD

**Issue by ShadSterling** [rubygems/rubygems#4774]
### Describe the problem as clearly as you can

The generated binstub `bin/bundle` correctly finds the bundler version from the Gemfile, but then intentionally approximates the requirement, then resolves that requirement to an incompatible newer version of bundler

This causes errors like
```
Bundler could not find compatible versions for gem "bundler":
  In Gemfile:
    bundler (= 2.2.22)

  Current Bundler version:
    bundler (2.2.24)

Your bundle requires a different version of Bundler than the one you're running.
Install the necessary version with `gem install bundler:2.2.22` and rerun bundler using `bundle _2.2.22_ update`
```

### Post steps to reproduce the problem

See https://github.com/ShadSterling/BugReport-Bundler-Binstub

In short,
```
export BUNDLER_VERSION="2.2.22"  ##  Matching Gemfile, version supported by deployment target
rbenv install -s "2.7.3"         ##  Matching Gemfile, version supported by deployment target
gem update --system
gem install bundler -v "$BUNDLER_VERSION"
bundle cache  ##  uses BUNDLER_VERSION
bundle binstubs --all  ##  --all to avoid "Sorry, Bundler can only be run via RubyGems"
bin/bundle update  ## binstub invokes 2.2.24 and fails
```
(I made a corrected binstub [here](https://github.com/ShadSterling/BugReport-Bundler-Binstub/blob/master/bin/bundle_corrected), but didn't look in to how the binstub is generated to propose a patch for that)

### Which command did you run?

`bundle`, when rbenv is configured to use the binstubs

(It's not an `rbenv` bug; as shown above and in my [repro repo](https://github.com/ShadSterling/BugReport-Bundler-Binstub), invoking the binstub explicitly still invokes the wrong version of Bundler)

### What were you expecting to happen?

I expected the binstub for `bundle` to invoke the version given in the `Gemfile` and work correctly

### What actually happened?

The binstub for `bundle` invoked a different version and failed

## Environment

```
Bundler       2.2.24
  Platforms   ruby, x86_64-darwin-20
Ruby          2.7.3p183 (2021-04-05 revision 6847ee089d7655b2a0eea4fee3133aeacd4cc7cc) [x86_64-darwin20]
  Full Path   /Users/sxs5ith/.rbenv/versions/2.7.3/bin/ruby
  Config Dir  /Users/sxs5ith/.rbenv/versions/2.7.3/etc
RubyGems      3.2.24
  Gem Home    /Users/sxs5ith/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0
  Gem Path    /Users/sxs5ith/.gem/ruby/2.7.0:/Users/sxs5ith/.rbenv/versions/2.7.3/lib/ruby/gems/2.7.0
  User Home   /Users/sxs5ith
  User Path   /Users/sxs5ith/.gem/ruby/2.7.0
  Bin Dir     /Users/sxs5ith/.rbenv/versions/2.7.3/bin
Tools         
  Git         2.24.3 (Apple Git-128)
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-07-15
Git SHA           d78b1ee235
Released Version  true
```

## Bundler settings

```
cache_all
  Set for your local app (/Users/sxs5ith/Documents/Repositories/BugReport-Bundler-Binstub/.bundle/config): true
cache_all_platforms
  Set for your local app (/Users/sxs5ith/Documents/Repositories/BugReport-Bundler-Binstub/.bundle/config): true
gemfile
  Set via BUNDLE_GEMFILE: "/Users/sxs5ith/Documents/Repositories/BugReport-Bundler-Binstub/Gemfile"
path
  Set for your local app (/Users/sxs5ith/Documents/Repositories/BugReport-Bundler-Binstub/.bundle/config): "vendor/bundle"
```

### Gemfile

```ruby
ruby "2.7.3"

source "https://rubygems.org/"

gem "bundler", "2.2.22"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  x86_64-darwin-20

DEPENDENCIES
  bundler (= 2.2.22)

RUBY VERSION
   ruby 2.7.3p183

BUNDLED WITH
   2.2.22
```

**Comment by deivid-rodriguez** [comment]
@ShadSterling Thanks for the report, #4775 should fix this.

Note thought that we'll probably deprecate and stop generating binstubs for bundler itself in the future, because rubygems already includes the same version selection logic built-in, so running `bundle update` instead of `bin/bundle update` should get you the exact same behaviour anyways.
