### ISSUE TITLE
`bundle update <gem_list>` hangs sometimes since bundler 2.2.22

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#4776]
Something in the 2.2.22 release caused some `bundle update` invocations with selected gems start hanging.

It could be a regression of https://github.com/rubygems/rubygems/pull/4652 (which actually fixed a similar issue, but might've introduced this one) or https://github.com/rubygems/rubygems/pull/4692.

Originally reported by @ashkulz in https://github.com/rubygems/rubygems/issues/4539#issuecomment-884780135.

**Comment by ashkulz** [comment]
Using the following command to build bundler from git:
```
cd bundler && gem uninstall bundler -v 2.2.21 && gem build bundler.gemspec && gem install -N bundler-2.2.21.gem && cd ..
```
and doing git bisect gives the result
```
e793520d1e10b6c22534f3db0591edc2c42a3c0c is the first bad commit
commit e793520d1e10b6c22534f3db0591edc2c42a3c0c
Author: David Rodríguez <deivid.rodriguez@riseup.net>
Date:   Sat Jul 3 09:58:33 2021 +0200

    Merge pull request #4713 from rubygems/dont_downgrade_indirect_dependencies_unless_necessary
    
    Never downgrade indirect dependencies when running `bundle update`
    
    (cherry picked from commit e17127b11e23b7f6b6613c92cff29fa0fba69618)

 bundler/lib/bundler/definition.rb    |  9 ++--
 bundler/spec/commands/update_spec.rb | 88 ++++++++++++++++++++++++++++++++++++
 2 files changed, 91 insertions(+), 6 deletions(-)
```
```

**Comment by deivid-rodriguez** [comment]
Awesome, that almost fully isolates the culprit. That PR has three commits, and only 2 of them touch non-test code. Can you confirm whether it's https://github.com/rubygems/rubygems/pull/4713/commits/fe962aca68a459968ab1712927ce3dbd0fb80e86 or https://github.com/rubygems/rubygems/pull/4713/commits/aa08c42f3ace3530c9d91faf2025b97cbf508fd4 that created the issue?

**Comment by deivid-rodriguez** [comment]
It should be https://github.com/rubygems/rubygems/pull/4713/commits/aa08c42f3ace3530c9d91faf2025b97cbf508fd4 but it doesn't hurt to double check.

**Comment by ashkulz** [comment]
You're right, it takes 60 seconds with fe962aca68a459968ab1712927ce3dbd0fb80e86 and hangs with aa08c42f3ace3530c9d91faf2025b97cbf508fd4. I'm willing to test out any patch you might have :slightly_smiling_face:

**Comment by deivid-rodriguez** [comment]
Sorry @ashkulz, I don't really have any patches since even if we now what broke this, I still don't know why it's hanging. I do need a reproducible test case.

**Comment by duckinator** [comment]
When looking at this, I noticed that the removal of `next requirements unless dependency` actually changes the behavior fairly significantly. I suspect that was the _goal_, but I figured I'd explain what the change in behavior is in case it helps:

- Before aa08c42, any time `dependencies_by_name[name]` returns nil, the loop would go to the next item immediately.
- After aa08c42, any time `dependencies_by_name[name]` returns nil, it will only go to the next item immediately if `@locked_gems.dependencies[name]` is _not_ also nil.

This basically means it's doing a lot more work than it used to. It could be that the old shortcut (skipping anything where `dependencies_by_name[name]` is nil) was a bit too aggressive, but a shortcut of some sort may still be needed to avoid the run-time exploding like this.

**Comment by BrianHawley** [comment]
This is affecting me as well, though in simple `bundle update` or `bundle outdated` calls, for every bundler version since 2.2.22. I'm a little concerned that this might block Ruby updates for us.

@duckinator is there an automated test for that goal you mentioned, a code pattern that requires that nil check to be removed? I'd like to make a PR to fix the issue reported here, but in a way that doesn't break the original goal of removing that nil check.

**Comment by duckinator** [comment]
@BrianHawley honestly I have a lot of trouble understanding this part of the codebase. I'm not sure what the point of removing the nil check was, nor what the implications (aside from broadening the search space) are.

@deivid-rodriguez it's been a bit since you made those commits, but do you by chance recall why you removed the `next requirements unless dependency` check?

**Comment by deivid-rodriguez** [comment]
Hi. aa08c42 included a regression test which I think shows the intention.

It was reported to us that `bundle update`, even when not achieving to upgrade any direct dependencies, would bump some indirect dependencies and downgrade others, and that was unintended. We avoid downgrading dependencies by passing some extra requirements to the resolver (`>= <currently_locked_version>` for dependencies in the lockfile), that's what this `additional_base_requirements_for_resolve` method do. However, before it was done only for top level dependencies, and with aa08c42 we started doing it for all locked dependencies.

@BrianHawley If you were able to provide us with a way to reproduce the issue, I can try figuring out what's going wrong here.

**Comment by deivid-rodriguez** [comment]
Could you folks give #5078 a try? I created it to fix a different issue, but I suspect it might also fix this one.

**Comment by ashkulz** [comment]
@deivid-rodriguez nope, doesn't fix it. I'll try to see if I can create a reproducible test case sometime this weekend.

Funnily enough, this doesn't affect us anymore -- earlier we were pre-Rails 5.2, now we're on Rails 5.2 :man_shrugging:

**Comment by deivid-rodriguez** [comment]
Oh, that's disappointing, I was quite hopeful :(

A repro will be greatly appreciated, thanks a lot for trying this!

**Comment by ashkulz** [comment]
@deivid-rodriguez the following command takes a few seconds with 2.2.21 (_running on Linux_) and fails to complete with later versions:
```
DEPENDENCIES_NEXT=1 bundle _2.2.22_ update rails actionmailer actionpack actionview activejob activemodel activerecord activesupport railties --conservative --strict --major
```
### `Gemfile`
```ruby
source 'https://rubygems.org'

gem 'rails', ENV['DEPENDENCIES_NEXT'] ? '~> 5.2' : '~> 5.0.7.2'
gem 'factory_bot_rails', '~> 5.0', '>= 5.0.2'
```
### `Gemfile.lock`
```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (5.0.7.2)
      actionpack (= 5.0.7.2)
      nio4r (>= 1.2, < 3.0)
      websocket-driver (~> 0.6.1)
    actionmailer (5.0.7.2)
      actionpack (= 5.0.7.2)
      actionview (= 5.0.7.2)
      activejob (= 5.0.7.2)
      mail (~> 2.5, >= 2.5.4)
      rails-dom-testing (~> 2.0)
    actionpack (5.0.7.2)
      actionview (= 5.0.7.2)
      activesupport (= 5.0.7.2)
      rack (~> 2.0)
      rack-test (~> 0.6.3)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.2)
    actionview (5.0.7.2)
      activesupport (= 5.0.7.2)
      builder (~> 3.1)
      erubis (~> 2.7.0)
      rails-dom-testing (~> 2.0)
      rails-html-sanitizer (~> 1.0, >= 1.0.3)
    activejob (5.0.7.2)
      activesupport (= 5.0.7.2)
      globalid (>= 0.3.6)
    activemodel (5.0.7.2)
      activesupport (= 5.0.7.2)
    activerecord (5.0.7.2)
      activemodel (= 5.0.7.2)
      activesupport (= 5.0.7.2)
      arel (~> 7.0)
    activesupport (5.0.7.2)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 0.7, < 2)
      minitest (~> 5.1)
      tzinfo (~> 1.1)
    arel (7.1.4)
    builder (3.2.4)
    concurrent-ruby (1.1.8)
    crass (1.0.6)
    erubis (2.7.0)
    factory_bot (5.2.0)
      activesupport (>= 4.2.0)
    factory_bot_rails (5.2.0)
      factory_bot (~> 5.2.0)
      railties (>= 4.2.0)
    globalid (0.4.2)
      activesupport (>= 4.2.0)
    i18n (1.8.7)
      concurrent-ruby (~> 1.0)
    loofah (2.8.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.5.9)
    mail (2.7.1)
      mini_mime (>= 0.1.1)
    method_source (0.9.2)
    mini_mime (1.0.2)
    mini_portile2 (2.5.1)
    minitest (5.10.3)
    nio4r (2.5.4)
    nokogiri (1.11.5)
      mini_portile2 (~> 2.5.0)
      racc (~> 1.4)
    nokogiri (1.11.5-x86_64-darwin)
      racc (~> 1.4)
    nokogiri (1.11.5-x86_64-linux)
      racc (~> 1.4)
    racc (1.5.2)
    rack (2.2.3)
    rack-test (0.6.3)
      rack (>= 1.0)
    rails (5.0.7.2)
      actioncable (= 5.0.7.2)
      actionmailer (= 5.0.7.2)
      actionpack (= 5.0.7.2)
      actionview (= 5.0.7.2)
      activejob (= 5.0.7.2)
      activemodel (= 5.0.7.2)
      activerecord (= 5.0.7.2)
      activesupport (= 5.0.7.2)
      bundler (>= 1.3.0)
      railties (= 5.0.7.2)
      sprockets-rails (>= 2.0.0)
    rails-dom-testing (2.0.3)
      activesupport (>= 4.2.0)
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.3.0)
      loofah (~> 2.3)
    railties (5.0.7.2)
      actionpack (= 5.0.7.2)
      activesupport (= 5.0.7.2)
      method_source
      rake (>= 0.8.7)
      thor (>= 0.18.1, < 2.0)
    rake (13.0.3)
    sprockets (3.7.2)
      concurrent-ruby (~> 1.0)
      rack (> 1, < 3)
    sprockets-rails (3.2.1)
      actionpack (>= 4.0)
      activesupport (>= 4.0)
      sprockets (>= 3.0.0)
    thor (1.0.1)
    thread_safe (0.3.6)
    tzinfo (1.2.9)
      thread_safe (~> 0.1)
    websocket-driver (0.6.5)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)

PLATFORMS
  ruby
  x86_64-darwin-18
  x86_64-darwin-19
  x86_64-darwin-20
  x86_64-linux

DEPENDENCIES
  factory_bot_rails (~> 5.0, >= 5.0.2)
  rails (~> 5.0.7.2)

BUNDLED WITH
   2.2.24
```

**Comment by deivid-rodriguez** [comment]
@ashkulz Which platform are you using, what's the result of `bundle platform`?

On `arm64-darwin20`, I can't seem to repro this hang on any version. All versions seem to resolve just fine. Normally resolution takes a while although with #5078, it's instant 😄.

**Comment by ashkulz** [comment]
Like I said earlier, this is on Linux (Ubuntu 20.04). I suspect it's the platforms, as removing them makes it fast.

**Comment by deivid-rodriguez** [comment]
I'm sorry, I missed that you had specified the platform, will try on Linux now.

**Comment by deivid-rodriguez** [comment]
I tried on Linux and I still can't repro the issue. I tried with bundler 2.2.22, 2.2.31, and with #5078. Time taken to resolve is as follow (which makes me proud of #5078 :smile:)

| version | time taken |
|---------|----------|
| 2.2.22 | 53.71 |
| 2.2.31 | 63.64 |
| #5078 | 2.80 |

Can you push your reproducible test case to a public repository, and setup github actions to reproduce the hang? That way I'll hopefully be able to figure out what's making this hang for you and not hang for me.

**Comment by deivid-rodriguez** [comment]
Alright, I finally managed to reproduce it! I figured the ruby version used was related, so I tried not only on Ruby 3, but on 2.7, 2.6 and finally 2.5 where the hang finally reproduced. So I guess you're using ruby 2.5?

Now that we have a repro I'll try to figure out what's going on!

**Comment by ashkulz** [comment]
I didn't think it'd matter, but yeah you're right ... at that point we were on Ruby 2.5

**Comment by deivid-rodriguez** [comment]
Alright, so good news. Yesterday I did make sure that the issue reproduced on ruby 2.5, but I didn't test #5078 on ruby 2.5. It does fix the issue! Can you please double check against the current master branch, it should really fix it and resolve very fast.

**Comment by deivid-rodriguez** [comment]
My results:

```
➜  hangs git:(main) ✗ time DEPENDENCIES_NEXT=1 bundle _2.2.31_ update rails actionmailer actionpack actionview activejob activemodel activerecord activesupport railties --conservative --strict --major
Fetching gem metadata from https://rubygems.org/............
Resolving dependencies....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................^C
DEPENDENCIES_NEXT=1 bundle _2.2.31_ update rails actionmailer actionpack       95,95s user 0,89s system 99% cpu 1:37,26 total

➜  hangs git:(main) ✗ time DEPENDENCIES_NEXT=1 bundle _2.3.0.dev_ update rails actionmailer actionpack actionview activejob activemodel activerecord activesupport railties --conservative --strict --major
Fetching gem metadata from https://rubygems.org/............
Resolving dependencies.............
Using rake 13.0.3
Using concurrent-ruby 1.1.8
Using minitest 5.10.3
Using rack 2.2.3
Using builder 3.2.4
Using websocket-extensions 0.1.5
Using mini_mime 1.1.2 (was 1.0.2)
Using racc 1.5.2
Using bundler 2.3.0.dev
Using thread_safe 0.3.6
Using method_source 0.9.2
Using thor 1.0.1
Using i18n 1.8.7
Using mini_portile2 2.5.1
Using erubi 1.10.0
Using crass 1.0.6
Using mail 2.7.1
Fetching nokogiri 1.11.5
Using websocket-driver 0.7.5 (was 0.6.5)
Using rack-test 0.6.3
Using sprockets 4.0.2 (was 3.7.2)
Using marcel 1.0.2
Using nio4r 2.5.8 (was 2.5.4)
Using tzinfo 1.2.9
Using arel 9.0.0 (was 7.1.4)
Using activesupport 5.2.6 (was 5.0.7.2)
Using globalid 0.5.2 (was 0.4.2)
Using activemodel 5.2.6 (was 5.0.7.2)
Using factory_bot 5.2.0
Using activejob 5.2.6 (was 5.0.7.2)
Using activerecord 5.2.6 (was 5.0.7.2)
Installing nokogiri 1.11.5 with native extensions
Fetching loofah 2.8.0
Fetching rails-dom-testing 2.0.3
Installing rails-dom-testing 2.0.3
Installing loofah 2.8.0
Fetching rails-html-sanitizer 1.3.0
Installing rails-html-sanitizer 1.3.0
Fetching actionview 5.2.6 (was 5.0.7.2)
Installing actionview 5.2.6 (was 5.0.7.2)
Fetching actionpack 5.2.6 (was 5.0.7.2)
Installing actionpack 5.2.6 (was 5.0.7.2)
Fetching actioncable 5.2.6 (was 5.0.7.2)
Fetching actionmailer 5.2.6 (was 5.0.7.2)
Fetching activestorage 5.2.6
Fetching railties 5.2.6 (was 5.0.7.2)
Fetching sprockets-rails 3.4.0 (was 3.2.1)
Installing sprockets-rails 3.4.0 (was 3.2.1)
Installing actionmailer 5.2.6 (was 5.0.7.2)
Installing actioncable 5.2.6 (was 5.0.7.2)
Installing activestorage 5.2.6
Installing railties 5.2.6 (was 5.0.7.2)
Fetching factory_bot_rails 5.2.0
Fetching rails 5.2.6 (was 5.0.7.2)
Installing rails 5.2.6 (was 5.0.7.2)
Installing factory_bot_rails 5.2.0
Bundle updated!
DEPENDENCIES_NEXT=1 bundle _2.3.0.dev_ update rails actionmailer actionpack    32,83s user 9,32s system 92% cpu 45,419 total
```

**Comment by deivid-rodriguez** [comment]
I'm tentatively closing this since I believe it's fixed, but please reopen if you are still experiencing this and can post a sample repository to GitHub Actions so that I can have a look. Thanks!

**Comment by ashkulz** [comment]
I'll check a bit later (family emergency), my repro was tuned to getting it minimal but didn't check with master so it's possible that a different test case would trigger this.

Either way, if it's 2.5 only not sure it makes sense to fix considering it's EOL.

**Comment by deivid-rodriguez** [comment]
Sure, thanks!

Well, the problem happens on Ruby 2.5 in this particular case, but it's not related to Ruby 2.5 per se. It's just a resolution issue, it could also reproduce on other rubies in other cases. Since gems can set requirements on the ruby version, with `s.required_ruby_version` in the gemspec, resolution is different per ruby version and this problems can be reproduce only on some rubies.

**Comment by ashkulz** [comment]
@deivid-rodriguez we were hit by this in our CI yesterday after we did some gem upgrades (_using Ruby 2.6_), and I checked with bundler 2.2.32 and it seems to have done the trick -- #5078 works and fixes this issue for us :tada:

**Comment by deivid-rodriguez** [comment]
Awesome, that's great to hear 🎉

**Comment by shaunakv1** [comment]
This now breaks with version 2.3.9 ? I just ran a bundle update to go from rails 5.1 to 5.2 and bundler is stuck on resolving dependencies forever

**Comment by deivid-rodriguez** [comment]
Hi, I don't think we regressed here, it may be a similar issue. Does removing the lockfile and running bundle install work?

**Comment by deivid-rodriguez** [comment]
Also, can you try with 2.3.14 (the latest version)?

**Comment by deivid-rodriguez** [comment]
One last thing. Can you explain confirm whether you changed the `Gemfile` before running `bundle update`, and if yes, does it work if you run `bundle install` instead of `bundle update` after changing the `Gemfile`?
