### ISSUE TITLE
gem which command fails on packages like actioncable

### ISSUE THREAD

**Issue by yuriShafet** [rubygems/rubygems#4787]
Example:
```
root@492b0e9b43dc:/gem_install/rubygems# gem which actioncable
ERROR:  Can't find Ruby library file or shared library actioncable
```

The reason this is happening is because "entry" file of the package is not `actioncable.rb` but `action_cable.rb`. This can be confirmed by running:
```
root@492b0e9b43dc:/gem_install/rubygems# gem which action_cable
/usr/local/bundle/gems/actioncable-5.0.1/lib/action_cable.rb
```

However, gem list command returns package name `actioncable` and not `action_cable`.

```
root@492b0e9b43dc:/gem_install/rubygems# gem list

*** LOCAL GEMS ***

actioncable (5.0.1)
actionmailer (5.0.1)

```

One of the possible solutions is to modify [have_file?](https://github.com/rubygems/rubygems/blob/96e5cff3df491c4d943186804c6d03b57fcb459b/lib/rubygems/basic_specification.rb#L332) so "entry" files with "_" will also be considered.

**Comment by deivid-rodriguez** [comment]
Thanks for the report @yuriShafet, can you provide a PR to fix it?

**Comment by yuriShafet** [comment]
@deivid-rodriguez will do

**Comment by yuriShafet** [comment]
#4789
