### ISSUE TITLE
Bundler v2.2.23+ no longer respects `BUNDLE_USER_*` environment variables

### ISSUE THREAD

**Issue by tomstuart** [rubygems/rubygems#4793]
### Describe the problem as clearly as you can

Since 1dac7e00ca3bb900085074b957d17870b2f2b650 in #4724 (shipped in v2.2.23), Bundler no longer uses the values of the `BUNDLE_USER_HOME`, `BUNDLE_USER_CACHE`, `BUNDLE_USER_CONFIG` and `BUNDLE_USER_PLUGIN` environment variables.

@ChrisBr first [reported](https://github.com/rubygems/rubygems/pull/4724/commits/1dac7e00ca3bb900085074b957d17870b2f2b650#r668867331) this on the PR. @deivid-rodriguez [replied](https://github.com/rubygems/rubygems/pull/4724/commits/1dac7e00ca3bb900085074b957d17870b2f2b650#r668907471):

> I checked these environment variables but I thought they were mostly related to caches and missed they also served to the change configuration's root (specially since we also have `BUNDLE_CONFIG` to change the configuration location...).

### Post steps to reproduce the problem

```
% mkdir -p ~/.config/bundler
% export BUNDLE_USER_CONFIG=~/.config/bundler/config
% bundle _2.2.22_ config set path vendor
% bundle _2.2.22_ config get path     
Settings for `path` in order of priority. The top value will be used
Set for the current user (/Users/tom/.config/bundler/config): "vendor"
% bundle _2.2.23_ config get path
Settings for `path` in order of priority. The top value will be used
You have not configured a value for `path`
```

### Which command did you run?

`bundle config get path`

### What were you expecting to happen?

See the value of `path` from the Bundler configuration file whose path is in the `BUNDLE_USER_CONFIG` environment variable.

### What actually happened?

Bundler cannot find a configured value for `path`.

## Environment

```
Bundler       2.2.23
  Platforms   ruby, x86_64-darwin-20
Ruby          3.0.0p0 (2020-12-25 revision 95aff214687a5e12c3eb57d056665741e734c188) [x86_64-darwin20]
  Full Path   /Users/tom/.rubies/ruby-3.0.0/bin/ruby
  Config Dir  /Users/tom/.rubies/ruby-3.0.0/etc
RubyGems      3.2.3
  Gem Home    /Users/tom/.gem/ruby/3.0.0
  Gem Path    /Users/tom/.gem/ruby/3.0.0:/Users/tom/.rubies/ruby-3.0.0/lib/ruby/gems/3.0.0
  User Home   /Users/tom
  User Path   /Users/tom/.gem/ruby/3.0.0
  Bin Dir     /Users/tom/.gem/ruby/3.0.0/bin
Tools         
  Git         2.31.0
  RVM         not installed
  rbenv       not installed
  chruby      0.3.9
```

## Bundler Build Metadata

```
Built At          2021-07-09
Git SHA           e863a3905d
Released Version  true
```

**Comment by deivid-rodriguez** [comment]
https://github.com/rubygems/rubygems/pull/4797 should fix this!

**Comment by ChrisBr** [comment]
Awesome, thank you! Any plan to release a new version soon?

**Comment by deivid-rodriguez** [comment]
Yes, I'll try today.

**Comment by ChrisBr** [comment]
Awesome. Thank you so much 🙏

**Comment by aryeh-looker** [comment]
It looks like `$BUNDLE_CONFIG_HOME` is also broken on `2.2.23+`.

**Comment by deivid-rodriguez** [comment]
No idea what `BUNDLE_CONFIG_HOME` is. In any case, whatever issue you're having, please report it as a separate issue with repro steps. Thanks!

**Comment by aryeh-looker** [comment]
Sorry about that, I meant `BUNDLE_USER_HOME`. This ticket mentions `BUNDLE_USER_*` -- should it not just be re-opened? Glad to also provide a repro.

**Comment by deivid-rodriguez** [comment]
Other `BUNDLE_USER_*` variable usages might not have been broken by the change that caused this issue. So I'd rather get a specific case that's currently broken reported as a separate issue.

**Comment by aryeh-looker** [comment]
https://github.com/rubygems/rubygems/issues/4826
