### ISSUE TITLE
Installing mysql2 gem

### ISSUE THREAD

**Issue by victorleflore** [rubygems/rubygems#4795]
I'm trying to switch a Rails app from sqlite3 to mysql but I'm running into issues

I ran 

`rails db:system:change --to=mysql`

which worked prefect, but when I try to run a rails server I get

`Puma caught this error: Error loading the 'mysql2' Active Record adapter. Missing a gem it depends on? mysql2 is not part of the bundle. Add it to your Gemfile. (LoadError)`

After that I tried to install the mysql2 0.5.3 gem in the gem file with 

gem 'mysql2', '~> 0.5.3'

and in the terminal with 

`gem install mysql2`

but it fails every time and I have no idea why

**Comment by deivid-rodriguez** [comment]
Hi @victorleflore, did you run `bundle install` after adding `gem "mysql2", "~> 0.5.3"` to your `Gemfile`?

**Comment by victorleflore** [comment]
I found the solution here 
https://github.com/brianmario/mysql2/issues/1175
