### ISSUE TITLE
Sometimes `require 'bundler/setup'` attempts to modify `Gemfile.lock`

### ISSUE THREAD

**Issue by jagthedrummer** [rubygems/rubygems#4796]
### Describe the problem as clearly as you can

I'm trying to deploy a small ruby application to AWS Lambda and the app runs on a read-only filesystem. With a simple `Gemfile` and `Gemfile.lock` I can call `require 'bundler/setup'` and everything works as expected. All the gems are loaded and available to my application.

When I include a particular private gem (installed via Gemfury, and which has _many_ dependencies) calling `require 'bundler/setup'` will cause Bundler to attempt to modify `Gemfile.lock` for some reason, but since the app lives on a read-only filesystem it raises an error.

At first I thought the problem had to do with the gem being private, but so far I'm having trouble reproducing the issue in a smaller more targeted bundle.

Is there a way to have bundler tell me _why_ it's trying to modify `Gemfile.lock`? Or a way to tell it not to do that when/before I do `require 'bundler/setup'`?

### Post steps to reproduce the problem

I'm still trying to determine reproduction steps and construct a `Dockerfile` to illustrate the problem.

### Which command did you run?

The problem happens when I call `require 'bundler/setup'` via code.

### What were you expecting to happen?

I'd expect Bundler to load all the gems in the `Gemfile` from the appropriate path without attempting to modify `Gemfile.lock`.

### What actually happened?

At runtime Bundler tries to modify `Gemfile.lock` which fails due to a read-only filesystem.

```
{
    "errorMessage": "There was an error accessing `/var/task/Gemfile.lock`.\nThe underlying system error is Errno::EROFS: Read-only file system @ rb_sysopen - /var/task/Gemfile.lock",
    "errorType": "Init<Bundler::GenericSystemCallError>",
    "stackTrace": [
        "/var/runtime/gems/bundler-2.2.21/lib/bundler/shared_helpers.rb:117:in `rescue in filesystem_access'",
        "/var/runtime/gems/bundler-2.2.21/lib/bundler/shared_helpers.rb:102:in `filesystem_access'",
        "/var/runtime/gems/bundler-2.2.21/lib/bundler/definition.rb:330:in `lock'",
        "/var/runtime/gems/bundler-2.2.21/lib/bundler/runtime.rb:104:in `lock'",
        "/var/runtime/gems/bundler-2.2.21/lib/bundler/runtime.rb:41:in `setup'",
        "/var/runtime/gems/bundler-2.2.21/lib/bundler.rb:149:in `setup'",
        "/var/runtime/gems/bundler-2.2.21/lib/bundler/setup.rb:20:in `block in <top (required)>'",
        "/var/runtime/gems/bundler-2.2.21/lib/bundler/ui/shell.rb:136:in `with_level'",
        "/var/runtime/gems/bundler-2.2.21/lib/bundler/ui/shell.rb:88:in `silence'",
        "/var/runtime/gems/bundler-2.2.21/lib/bundler/setup.rb:20:in `<top (required)>'",
        "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'",
        "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'",
        "/var/task/config/boot.rb:3:in `<top (required)>'",
        "/var/task/funktor_config/boot.rb:5:in `require_relative'",
        "/var/task/funktor_config/boot.rb:5:in `<top (required)>'",
        "/var/task/lambda_event_handlers/incoming_job_handler.rb:1:in `require_relative'",
        "/var/task/lambda_event_handlers/incoming_job_handler.rb:1:in `<top (required)>'",
        "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'",
        "/var/lang/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:85:in `require'"
    ]
}
```

### If not included with the output of your command, run `bundle env` and paste the output below

N/A? (If there's something else I can provide instead I'd be happy to.)

**Comment by deivid-rodriguez** [comment]
Hi @jagthedrummer!

Yes, sometimes requiring `bundler/setup` can create `Gemfile.lock` modifications. If the bundle is "incomplete", but bundler can still additional thing it needs in the local filesystem, it proceeds happily and updates the lockfile with whatever was missing. Normally you can figure out what's missing by inspecting the `Gemfile.lock` modifications themselves. My guess is that bundler might be automatically the platform where it's being run to the lockfile, and any platform specific gems that might be missing.

Since you're running bundler on a read-only filesystem, you almost 100% want to configure bundler in frozen mode (with the `BUNDLE_FROZEN` environment variable or an equivalent `bundle config` alternative). That will disallow any lockfile modifications at all, and will very likely give you a better error on what the problem is.

**Comment by jagthedrummer** [comment]
Thanks for pointing me at `BUNDLE_FROZEN` @deivid-rodriguez! I had seen it in the docs previously but I think I misread/misunderstood the description of what it does. (The docs seemed to be saying that it was more of a `bundle install`-time option and I didn't realize that it could come into play at runtime.)

After setting `ENV['BUNDLE_FROZEN']='true'` everything is working just fine. `require 'bundler/setup` does it's thing, loads all the gems, and no additional errors are reported, so I guess whatever it is that bundler was trying to do wasn't that important.

Thanks again!
