### ISSUE TITLE
Running bundle install --local hits remote URLs

### ISSUE THREAD

**Issue by nickcharlton** [rubygems/rubygems#4799]
In [Appraisal][], we have a test which calls `bundle install --local`. Our example Gemfile has some non-existent domains, which leave us with this error when running it:

```
Could not reach host other-rubygems.org. Check your network connection and try again.
```

In https://github.com/thoughtbot/appraisal/issues/185, it was reported that this problem seemed to start after https://github.com/rubygems/rubygems/commit/d8b59a1777ccbd548b14d46aab19e47df83f0676 was merged, but we're not sure what in there would be causing this.

(I also saw https://github.com/rubygems/rubygems/pull/4677, but this relates to another configuration option I'm not aware we're using anywhere …I'm not locally, for sure.)

I've done my best to isolate this away from Appraisal, but it's also possible we're doing something very old that needs updating too!

[Appraisal]: https://github.com/thoughtbot/appraisal

### Steps to Reproduce

[`spec/acceptance/appraisals_file_bundler_dsl_compatibility_spec.rb`](https://github.com/thoughtbot/appraisal/blob/a89cc38d94ff6c6926d8b9c62791beaf6a8b0e6e/spec/acceptance/appraisals_file_bundler_dsl_compatibility_spec.rb#L4) in Appraisal might be the best example of this.

Our Gemfile looks like this:

```ruby
source 'https://rubygems.org'
git_source(:custom_git_source) { |repo| "../gems/\#{repo}" }
ruby RUBY_VERSION

gem 'bagel'
gem "croissant", :custom_git_source => "croissant"

git '../gems/egg' do
  gem 'egg'
end

path '../gems/waffle' do
  gem 'waffle'
end

group :breakfast do
  gem 'orange_juice'
  gem "omelette", :custom_git_source => "omelette"
  gem 'rotten_egg'
end

platforms :ruby, :jruby do
  gem 'milk'

  group :lunch do
    gem "coffee"
  end
end

source "https://other-rubygems.org" do
  gem "sausage"
end

gem 'appraisal', :path => #{PROJECT_ROOT.inspect}
```

### Which command did you run?

```sh
bundler install --local
```

### What were you expecting to happen?

Bundler shouldn't try and hit these non-existent domains (and our test should pass).

### What actually happened?

```sh
$ rspec spec/acceptance/appraisals_file_bundler_dsl_compatibility_spec.rb:4
Run options: include {:locations=>{"./spec/acceptance/appraisals_file_bundler_dsl_compatibility_spec.rb"=>[4]}}
[DEPRECATED] The --binstubs option will be removed in favor of `bundle binstubs --all`
Could not reach host other-rubygems.org. Check your network connection and try again.
F

Failures:

  1) Appraisals file Bundler DSL compatibility supports all Bundler DSL in Appraisals file
     Failure/Error:
       raise RuntimeError, <<-error_message.strip_heredoc
         Command #{command.inspect} exited with status #{exitstatus}. Output:
         #{output.gsub(/^/, '  ')}
       error_message

     RuntimeError:
                 Command "bundle install --local" exited with status 17. Output:
                   Fetching ../gems/croissant
       Fetching ../gems/egg
       Fetching ../gems/omelette
     # ./spec/support/acceptance_test_helpers.rb:162:in `block (2 levels) in run'
     # <internal:kernel>:90:in `tap'
     # ./spec/support/acceptance_test_helpers.rb:154:in `block in run'
     # ./spec/support/acceptance_test_helpers.rb:149:in `chdir'
     # ./spec/support/acceptance_test_helpers.rb:149:in `in_test_directory'
     # ./spec/support/acceptance_test_helpers.rb:153:in `run'
     # ./spec/acceptance/appraisals_file_bundler_dsl_compatibility_spec.rb:84:in `block (2 levels) in <top (required)>'

Finished in 12.99 seconds (files took 0.16346 seconds to load)
1 example, 1 failure

Failed examples:

rspec ./spec/acceptance/appraisals_file_bundler_dsl_compatibility_spec.rb:4 # Appraisals file Bundler DSL compatibility supports all Bundler DSL in Appraisals file
```

<details>
  <summary>bundle env (from within the test environment)</summary>
## Environment

```
Bundler       2.2.24
  Platforms   ruby, x86_64-darwin-19
Ruby          3.0.0p0 (2020-12-25 revision 95aff214687a5e12c3eb57d056665741e734c188) [x86_64-darwin19]
  Full Path   /Users/nickcharlton/.rubies/ruby-3.0.0/bin/ruby
  Config Dir  /Users/nickcharlton/.rubies/ruby-3.0.0/etc
RubyGems      3.2.3
  Gem Home    /Users/nickcharlton/projects/thoughtbot/appraisal/tmp/gems
  Gem Path    /Users/nickcharlton/.gem/ruby/3.0.0:/Users/nickcharlton/.rubies/ruby-3.0.0/lib/ruby/gems/3.0.0:/Users/nickcharlton/projects/thoughtbot/appraisal/tmp/gems
  User Home   /Users/nickcharlton
  User Path   /Users/nickcharlton/.gem/ruby/3.0.0
  Bin Dir     /Users/nickcharlton/projects/thoughtbot/appraisal/tmp/gems/bin
Tools
  Git         2.32.0
  RVM         not installed
  rbenv       not installed
  chruby      0.3.9
```

## Bundler Build Metadata

```
Built At          2021-07-15
Git SHA           d78b1ee235
Released Version  true
```

## Bundler settings

```
bin
  Set for your local app (/Users/nickcharlton/projects/thoughtbot/appraisal/tmp/stage/.bundle/config): "bin"
gemfile
  Set via BUNDLE_GEMFILE: "/Users/nickcharlton/projects/thoughtbot/appraisal/tmp/stage/Gemfile"
```

### Gemfile

```ruby
source 'https://rubygems.org'
git_source(:custom_git_source) { |repo| "../gems/#{repo}" }
ruby RUBY_VERSION

gem 'bagel'
gem "croissant", :custom_git_source => "croissant"

git '../gems/egg' do
  gem 'egg'
end

path '../gems/waffle' do
  gem 'waffle'
end

group :breakfast do
  gem 'orange_juice'
  gem "omelette", :custom_git_source => "omelette"
  gem 'rotten_egg'
end

platforms :ruby, :jruby do
  gem 'milk'

  group :lunch do
    gem "coffee"
  end
end

source "https://other-rubygems.org" do
  gem "sausage"
end

gem 'appraisal', :path => "/Users/nickcharlton/projects/thoughtbot/appraisal"
```

### Gemfile.lock

```
PATH
  remote: /Users/nickcharlton/projects/thoughtbot/appraisal
  specs:
    appraisal (2.4.1)
      bundler
      rake
      thor (>= 0.14.0)

GEM
  remote: https://rubygems.org/
  specs:
    rake (13.0.6)
    thor (1.1.0)

PLATFORMS
  x86_64-darwin-19

DEPENDENCIES
  appraisal!

BUNDLED WITH
   2.2.4
```
</details>

**Comment by deivid-rodriguez** [comment]
Thanks @nickcharlton. There's chances that https://github.com/rubygems/rubygems/pull/4782/commits/706fd28681bb7f643e0206cc6fae5ddd579fbdea might've fixed this. If you can verify this against the latest master branch, that'd be awesome, but I'm planning to released 2.2.25 soon anwyays including that change.

**Comment by deivid-rodriguez** [comment]
Nah, it doesn't fix this.

So, what would be the expected behaviour here? That `bundler`  completely ignores all sources in the `Gemfile` and just considers local gems for resolution, right? It makes sense that this broke when we fixed dependency confusion security issues, because before `bundler` wold merge all rubygems sources into a single source that would fallback to locally installed gems.

**Comment by nickcharlton** [comment]
Thanks for replying so fast! And then again …I was just getting a local clone ready to test that other potential fix 😅.

Yeah, I think that's the expected behaviour: Our test has been relying on Bundler not going out to fetch from those sources and only use the local gems.

**Comment by deivid-rodriguez** [comment]
@nickcharlton #4805 should fix this! You can finish setting up your clone to verify it :)

**Comment by nickcharlton** [comment]
Nice one, thanks! I can confirm that #4803 did indeed resolve our problem.

**Comment by samof76** [comment]
@nickcharlton looks like you have wrongly tagged a different issue here.

**Comment by nickcharlton** [comment]
Oops! Thanks. I updated it.
