### ISSUE TITLE
bundle install fails for gpgme gem

### ISSUE THREAD

**Issue by djberg96** [rubygems/rubygems#4804]
Ruby 2.6.6, 3.0.2
rubygems 3.2.24
bundler 2.2.24

The `bundle install` command fails for the gpgme gem. It appears to be looking for it locally despite removing the Gemfile.lock file, but I am not entirely certain.

Note that this does NOT happen with bundler 2.2.15, which works as expected.

```
>bundle install --verbose
Running `bundle install --verbose` with bundler 2.2.24
Found no changes, using resolution from the lockfile
The definition is missing ["gpgme-2.0.20"]
HTTP GET https://index.rubygems.org/versions
HTTP 304 Not Modified https://index.rubygems.org/versions
Fetching gem metadata from https://rubygems.org/
Double checking for ["rake", "rspec", "fakefs", "rspec-core", "rspec-expectations", "rspec-mocks", "rspec-support", "diff-lcs"] in rubygems repository https://rubygems.org/ or installed locally
Fetching gem metadata from https://rubygems.org/
Looking up gems ["rake", "rspec", "fakefs", "rspec-core", "rspec-expectations", "rspec-mocks", "rspec-support", "diff-lcs"]
Your bundle is locked to gpgme (2.0.20) from locally installed gems, but that version can no longer be found in
that source. That means the author of gpgme (2.0.20) has removed it. You'll need to update your bundle to a
version other than gpgme (2.0.20) that hasn't been removed in order to install.
Bundler::GemNotFound: Your bundle is locked to gpgme (2.0.20) from locally installed gems, but that version can no longer be found in that source. That means the author of gpgme (2.0.20) has removed it. You'll need to update your bundle to a version other than gpgme (2.0.20) that hasn't been removed in order to install.
/Users/dberger/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.24/lib/bundler/definition.rb:193:in `rescue in specs'
  /Users/dberger/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.24/lib/bundler/definition.rb:187:in `specs'
  /Users/dberger/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.24/lib/bundler/installer.rb:247:in `ensure_specs_are_compatible!'
  /Users/dberger/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.24/lib/bundler/installer.rb:84:in `block in run'
  /Users/dberger/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.24/lib/bundler/process_lock.rb:12:in `block in lock'
  /Users/dberger/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.24/lib/bundler/process_lock.rb:9:in `open'
  /Users/dberger/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.24/lib/bundler/process_lock.rb:9:in `lock'
  /Users/dberger/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.24/lib/bundler/installer.rb:72:in `run'
  /Users/dberger/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.24/lib/bundler/installer.rb:24:in `install'
  /Users/dberger/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.24/lib/bundler/cli/install.rb:60:in `run'
  /Users/dberger/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.24/lib/bundler/cli.rb:260:in `block in install'
  /Users/dberger/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.24/lib/bundler/settings.rb:131:in `temporary'
  /Users/dberger/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.24/lib/bundler/cli.rb:259:in `install'
  /Users/dberger/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/dberger/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/dberger/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/dberger/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.24/lib/bundler/cli.rb:31:in `dispatch'
  /Users/dberger/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.24/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/dberger/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.24/lib/bundler/cli.rb:25:in `start'
  /Users/dberger/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.24/exe/bundle:49:in `block in <top (required)>'
  /Users/dberger/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.24/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
  /Users/dberger/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0/gems/bundler-2.2.24/exe/bundle:37:in `<top (required)>'
  /Users/dberger/.rbenv/versions/2.6.6/bin/bundle:23:in `load'
  /Users/dberger/.rbenv/versions/2.6.6/bin/bundle:23:in `<main>'
```

To reproduce this just add 'gpgme' as a dependency to any Gemfile or sourced gemspec and run `bundle install`.

Here's my `bundle env` output:

```
>bundle env
## Environment

Bundler       2.2.24
  Platforms   ruby, x86_64-darwin-20
Ruby          3.0.2p107 (2021-07-07 revision 0db68f023372b634603c74fca94588b457be084c) [x86_64-darwin20]
  Full Path   /Users/dberger/.rbenv/versions/3.0.2/bin/ruby
  Config Dir  /Users/dberger/.rbenv/versions/3.0.2/etc
RubyGems      3.2.24
  Gem Home    /Users/dberger/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0
  Gem Path    /Users/dberger/.gem/ruby/3.0.0:/Users/dberger/.rbenv/versions/3.0.2/lib/ruby/gems/3.0.0
  User Home   /Users/dberger
  User Path   /Users/dberger/.gem/ruby/3.0.0
  Bin Dir     /Users/dberger/.rbenv/versions/3.0.2/bin
Tools         
  Git         2.28.0
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed

## Bundler Build Metadata

Built At          2021-07-15
Git SHA           d78b1ee235
Released Version  true

## Bundler settings

gem.test
  Set for the current user (/Users/dberger/.bundle/config): "rspec"
specific_platform
  Set for the current user (/Users/dberger/.bundle/config): "true"

### Gemfile

source 'https://rubygems.org' do
  gemspec
end

### Gemfile.lock

<No /Users/dberger/Dev/dbi-dbrc/Gemfile.lock found>

## Gemspecs

### dbi-dbrc.gemspec

require 'rubygems'

Gem::Specification.new do |spec|
  spec.name       = 'dbi-dbrc'
  spec.version    = '1.7.0'
  spec.author     = 'Daniel Berger'
  spec.email      = 'djberg96@gmail.com'
  spec.license    = 'Apache-2.0'
  spec.summary    = 'A simple way to avoid hard-coding passwords with DBI'
  spec.homepage   = 'https://github.com/djberg96/dbi-dbrc'
  spec.files      = Dir['**/*'].reject{ |f| f.include?('git') }
  spec.test_files = Dir['test/test*.rb']
  spec.cert_chain = Dir['certs/*']

  spec.add_dependency('gpgme', '~> 2.0')
  spec.add_dependency('rexml', '~> 3.2')

  spec.add_development_dependency('rake')
  spec.add_development_dependency('rspec', '~> 3.9')
  spec.add_development_dependency('fakefs', '~> 1.3')

  spec.metadata = {
    'homepage_uri'      => 'https://github.com/djberg96/dbi-dbrc',
    'bug_tracker_uri'   => 'https://github.com/djberg96/dbi-dbrc/issues',
    'changelog_uri'     => 'https://github.com/djberg96/dbi-dbrc/blob/main/CHANGES.md',
    'documentation_uri' => 'https://github.com/djberg96/dbi-dbrc/wiki',
    'source_code_uri'   => 'https://github.com/djberg96/dbi-dbrc',
    'wiki_uri'          => 'https://github.com/djberg96/dbi-dbrc/wiki'
  }

  if File::ALT_SEPARATOR
    spec.add_dependency('sys-admin')
    spec.add_dependency('win32-file-attributes')
    spec.add_dependency('win32-dir')
    spec.add_dependency('win32-process')
    spec.platform = Gem::Platform::CURRENT
    spec.platform.cpu = 'universal'
  end

  spec.description = <<-EOF
    The dbi-dbrc library provides an interface for storing database
    connection information, including passwords, in a locally secure
    file only accessible by you, or root. This allows you to avoid
    hard coding login and password information in your programs
    that require such information.

    This library can also be used to store login and password information
    for logins on remote hosts, not just databases.
  EOF
end
```

**Comment by deivid-rodriguez** [comment]
I just tried and it installed just fine for me. Could be a MacOS specific issue, so I can try on MacOS next. Something I don't understand is why `bundle env` won't list your `Gemfile`. Or did you skip it on purpose?

**Comment by deivid-rodriguez** [comment]
Also your logs imply that there's a lockfile, but you said it doesn't work without a lockfile either. Can you copy the error without a lockifle?

**Comment by djberg96** [comment]
> Also your logs imply that there's a lockfile, but you said it doesn't work without a lockfile either. Can you copy the error without a lockifle?

What I pasted is actually the error I'm seeing without a Gemfile.lock.

**Comment by djberg96** [comment]
>  Something I don't understand is why bundle env won't list your Gemfile. Or did you skip it on purpose?

Updated. The specific library is https://github.com/djberg96/dbi-dbrc.

**Comment by deivid-rodriguez** [comment]
> What I pasted is actually the error I'm seeing without a Gemfile.lock.

That doesn't make sense, since the output says "Found no changes, using resolution from the lockfile"... :thinking:

**Comment by deivid-rodriguez** [comment]
Something to be noted is that your gem does not specify an explicit global source, which is something we're deprecating in the next version, because it creates all kind of issues. Does it work if you change the `Gemfile` to

```ruby
source "https://rubygems.org"

gemspec
```

**Comment by djberg96** [comment]
> That doesn't make sense, since the output says "Found no changes, using resolution from the lockfile"

Indeed.

But sure enough, switching from the block form to the global form fixed it. Hopefully that's a clue. And here I thought I was doing it the preferred way...

**Comment by djberg96** [comment]
Alright, now I'm getting really confused. After a successful `bundle install`, I deleted the Gemfile.lock, restored the original Gemfile, and ran `bundle install` again. And this time it was successful.

I feel like it's being cached somewhere...

**Comment by djberg96** [comment]
One thing I didn't mention - I'm using zsh, if that matters.

**Comment by deivid-rodriguez** [comment]
> Disregard that, it looks like the gem got installed globally as part of the bundle install (???)

That's expected, no? `bundle install` will install the dependencies of your gem, and use your gem from source.

Not sure how to reproduce your issue, sorry. If switching to the global form fixes things, I'd lean towards closing this and reopen if we find a reliable way to reproduce the issue.

**Comment by djberg96** [comment]
> That's expected, no? bundle install will install the dependencies of your gem, and use your gem from source.

I was thinking they were vendored, but I guess that's not the default.

> Not sure how to reproduce your issue, sorry. 

I just duplicated this with a fresh Ubuntu 20 install. Same software - Ruby 3.0.2, bundler 2.2.25, rubygems 3.2.25. Bash shell + rbenv.

**Comment by deivid-rodriguez** [comment]
That's great. Can you provide a Dockerfile that reproduces the issue, then?

**Comment by deivid-rodriguez** [comment]
Forget about it, I can repro now. I'll see if I can do something about it, but in any case, please change your `Gemfile` to include a global source, since we deprecated no global sources since bundler 2.2.25.

**Comment by deivid-rodriguez** [comment]
I understand the reason for this issue now, but I don't have a good solution. With the deprecation of not using global sources, it shouldn't be a problem in practice though.

The problem is, when you specify this:

```ruby
source "https://rubygems.org" do
  gemspec
end
```

that's essentially (ignoring development dependencies) equivalent to

```ruby
source "https://rubygems.org" do
  gem "dbi-dbrc", path: "."
end
```

and that's equivalent to

```ruby
source "https://rubygems.org" do
  path "." do
    gem "dbi-dbrc"
  end
end
```

Now, in order to figure out which source each dependency should be pulled from, `bundler` uses the following criteria for indirect dependencies: they should be pulled from the same source as their direct dependant, or from the default source otherwise. So, in this case `gpgme` is first looked in the `path` source at `.`. But there we only find `dbi-dbrc`, so as a fallback the default source is used. Since there's no default source, bundler uses "locally installed gems" as a fallback.

So to sum up, `bundler` never tries `https://rubygems.org` as a potential source for `gpgme`.

As I said, I don't have a good solution for this, and given that we have already deprecated `Gemfile`'s without a global source, I'm leaning towards tagging this as "Won't fix".

**Comment by deivid-rodriguez** [comment]
Another observation is that

```ruby
source "https://rubygems.org" do
  gem "dbi-dbrc", path: "."
end
```

is also equivalent to

```ruby
source "https://rubygems.org" do
  path "." do
    gem "dbi-dbrc"
  end
end
```

We could also deprecate nesting scoped sources like this, because they don't really work as expected (the outermost source is ignored).

**Comment by djberg96** [comment]
@deivid-rodriguez Just curious, why were Gemfiles without global sources deprecated?

**Comment by deivid-rodriguez** [comment]
Because we keep getting issue where Gemfiiles without them don't behave as expected. For example, this one.

**Comment by deivid-rodriguez** [comment]
They work inconsistently depending on the gems the running system has installed, that's why we had so much trouble reproducing this.

**Comment by deivid-rodriguez** [comment]
To be more concrete. Say you have `gpgme` installed on your system, and you have your original `Gemfile` without a global source in your `dbi-dbrc` gem.

```
$ cat Gemfile 
source 'https://rubygems.org' do
  gemspec
end

$ gem list gpgme

*** LOCAL GEMS ***

gpgme (2.0.20)
```

Then `bundle install` will just work for you:

```
$ bundle 
[DEPRECATED] This Gemfile does not include an explicit global source. Not using an explicit global source may result in a different lockfile being generated depending on the gems you have installed locally before bundler is run.Instead, define a global source in your Gemfile like this: source "https://rubygems.org".
Fetching gem metadata from https://rubygems.org/...
Resolving dependencies...
Using rake 13.0.6
Using bundler 2.2.25
Using mini_portile2 2.6.1
Using rexml 3.2.5
Using gpgme 2.0.20
Using fakefs 1.3.2
Using dbi-dbrc 1.7.0 from source at `.`
Using diff-lcs 1.4.4
Using rspec-support 3.10.2
Using rspec-core 3.10.1
Using rspec-expectations 3.10.1
Using rspec-mocks 3.10.2
Using rspec 3.10.0
Bundle complete! 4 Gemfile dependencies, 13 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

But say one of your contributors who doesn't have `gpgme` installed clones your gem, and runs `bundle install`. The she will get an error:

```
$ bundle 
[DEPRECATED] This Gemfile does not include an explicit global source. Not using an explicit global source may result in a different lockfile being generated depending on the gems you have installed locally before bundler is run.Instead, define a global source in your Gemfile like this: source "https://rubygems.org".
Fetching gem metadata from https://rubygems.org/...
Resolving dependencies...
Bundler could not find compatible versions for gem "gpgme":
  In Gemfile:
    dbi-dbrc was resolved to 1.7.0, which depends on
      gpgme (~> 2.0)

Could not find gem 'gpgme (~> 2.0)', which is required by gem 'dbi-dbrc', in locally installed gems.
```

The error message is pretty good and manually installing `gpgme` should get things back to working. But having to install gems manually through `gem install` somewhat defeats the whole purpose of `bundler`.

**Comment by djberg96** [comment]
@deivid-rodriguez How did it work in earlier versions?

My assumption was that the behavior of the block form would be to use a local gem if found, otherwise fetch it from the declared source. That seemed to be how it worked before. At least I though it did.

I'm trying to remember why I did this to begin with. I think one of our many 3rd party linting type tools suggested it on another project I was working on, so I thought I was doing things the right way. Guess not.

**Comment by deivid-rodriguez** [comment]
The way it worked before was that `bundler` would find all gem sources present in the `Gemfile`, plus local gems, and merge everything into a single aggregated source. I was that was making this case accidentally work but was vulnerable to dependency confusion issues because it wasn't deterministic which source each gem should be pulled from.

> I'm trying to remember why I did this to begin with. I think one of our many 3rd party linting type tools suggested it on another project I was working on, so I thought I was doing things the right way. Guess not.

I also tend to recall some resource also recommending not using global sources at all. I _believe_it might've been bundler's documentation site, but we fixed that a while ago now. If we find other resources recommending this, they should be updated.

**Comment by deivid-rodriguez** [comment]
Closing in favour of https://github.com/rubygems/rubygems/issues/4817.
