### ISSUE TITLE
`undefined method 'add_dependency_names' for nil:NilClass` when using Bundler 2.2.5 on Windows

### ISSUE THREAD

**Issue by koic** [rubygems/rubygems#4811]
### Describe the problem as clearly as you can

Bundler 2.2.5 on Windows now cause errors.

```console
     Failure/Error: @parser = lockfile ? Bundler::LockfileParser.new(lockfile) : nil

     NoMethodError:
       undefined method `add_dependency_names' for nil:NilClass
      # ./lib/rubocop/lockfile.rb:35:in `new'
      # ./lib/rubocop/lockfile.rb:35:in `parser'
      # ./lib/rubocop/lockfile.rb:17:in `gems'
```

https://github.com/rubocop/rubocop/blob/v1.18.4/lib/rubocop/lockfile.rb#L35

No error occurs until Bundler 2.2.4.

It may be affected by the following Bundler's PR https://github.com/rubygems/rubygems/pull/4782 changes.

bundler/lib/bundler/lockfile_parser.rb:

```diff
        platform = platform ? Gem::Platform.new(platform) :
        Gem::Platform::RUBY
        @current_spec = LazySpecification.new(name, version, platform)
        @current_spec.source = @current_source
+       @current_source.add_dependency_names(name)

        @specs[@current_spec.identifier] = @current_spec
      elsif spaces.size == 6
```

### Post steps to reproduce the problem

I encountered the error in RuboCop's CI build error.
https://github.com/rubocop/rubocop/pull/9971

(I don't have a Windows environment...)

### Which command did you run?

Running spec/rubocop/lockfile_spec.rb on Windows will reproduce it.
https://github.com/rubocop/rubocop/blob/v1.18.4/spec/rubocop/lockfile_spec.rb

### What were you expecting to happen?

No errors.

### What actually happened?

The following error occurs:

```console
     Bundler::LockfileParser.new(lockfile) : nil

     NoMethodError:
       undefined method `add_dependency_names' for nil:NilClass
```

**Comment by deivid-rodriguez** [comment]
I _think_ the reason is rubocop specs are trying to parse an invalid lockfile.

I'll wait for CI on https://github.com/rubocop/rubocop/pull/9972, and if it passes, I'll close this.

**Comment by deivid-rodriguez** [comment]
Windows CI seems green at https://github.com/rubocop/rubocop/pull/9972, so closing.

**Comment by koic** [comment]
@deivid-rodriguez Thank you for solving it super early!

**Comment by deivid-rodriguez** [comment]
No problem @koic!
