### ISSUE TITLE
Gemfile.lock becomes dirty after `exec`, `show` or `check` since v2.2.21 if there are multiple gem sources

### ISSUE THREAD

**Issue by gyfelton** [rubygems/rubygems#4830]
### Describe the problem as clearly as you can

Prior to v2.2.21, we don't get Gemfile.lock changed after non-install/update operations such as `bundle exec`, `bundle show` or `bundle check`. This behaviour changes since v2.2.21 for us as our Gemfile contains multiple gem sources and it broke our CI pipeline.

### Post steps to reproduce the problem

* How your ruby is setup (OS package, from source, using a version manager).
OS version: Mac OS Big Sur, using standard rvm as version manager
* How bundler & rubygems are configured.
First we do `bundle _2.1.4_ install` with Gemfile:
```
source "https://rubygems.org"

gem "addressable"

source 'http://localhost:9292' do
  gem 'json'
  gem 'obstinately'
end
```
Note that we are running a local gem stash [instance](https://github.com/rubygems/gemstash) to simulate the multiple sources situation.
What is shown in `Gemfile.lock`:
```
GEM
  remote: https://rubygems.org/
  remote: http://localhost:9292/
  specs:
    claide (1.0.3)
    json (2.5.1)
    obstinately (0.1.0)
      claide (~> 1.0)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    public_suffix (4.0.6)

PLATFORMS
  ruby

DEPENDENCIES
  addressable
  json!
  obstinately!

BUNDLED WITH
   2.1.4
```
After this step, check in the files in git. Then do `bundle _2.2.21_ show`. The Gemfile.lock is changed to:
```
GEM
  remote: http://localhost:9292/
  specs:
    claide (1.0.3)
    json (2.5.1)
    obstinately (0.1.0)
      claide (~> 1.0)

GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    public_suffix (4.0.6)

PLATFORMS
  ruby

DEPENDENCIES
  addressable
  json!
  obstinately!

BUNDLED WITH
   2.2.21
```
You won't get the Gemfile.lock updated if you ran `bundle _2.1.5_ show`.

One possibility is that bundler updates Gemfile.lock only when content changes, even if current bundler version is higher than what's indicated inside the Gemfile.lock.

### Which command did you run?

bundle _<some_higher_version>_ show

### What were you expecting to happen?

No change on Gemfile.lock

### What actually happened?

As stated above, it changed.

### If not included with the output of your command, run `bundle env` and paste the output below

```
## Environment

Bundler             2.2.22
  Platforms         ruby, x86_64-darwin-19
Ruby                2.7.2p137 (2020-10-01 revision 5445e0435260b449decf2ac16f9d09bae3cafe72) [x86_64-darwin19]
  Full Path         ~/.rvm/rubies/ruby-2.7.2/bin/ruby
  Config Dir        ~/.rvm/rubies/ruby-2.7.2/etc
RubyGems            3.1.4
  Gem Home         ~/.rvm/gems/ruby-2.7.2
  Gem Path         ~/.rvm/gems/ruby-2.7.2:/Users/yuanfeng/.rvm/rubies/ruby-2.7.2/lib/ruby/gems/2.7.0
  User Home         ~
  User Path         ~/.gem/ruby/2.7.0
  Bin Dir           ~/.rvm/gems/ruby-2.7.2/bin
Tools
  Git               2.24.3 (Apple Git-128)
  RVM               1.29.9 (latest)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)

## Bundler Build Metadata

Built At          2021-07-06
Git SHA           0bdd3e8e71
Released Version  true


## Bundler settings

build.eventmachine
  Set for the current user "--with-opt-dir=/usr/local/opt/openssl"
build.puma
  Set for the current user"--with-opt-dir=/usr/local/opt/openssl"
gem.push_key
  Set for the current user "[REDACTED]"
remove
  Set for the current user "debug_vscode"
rwithout
  Set for the current user : "debug_vscode"
with
  Set for your local app [:debug_vscode]
  Set for the current user (): [:debug_vscode]

```

After all, maybe it's expected that bundle show/bundle check should update Gemfile.lock. We also have `frozen` config to ensure no update of Gemfile.lock as well.

**Comment by deivid-rodriguez** [comment]
Hello!

Yeah, in general, it's not expected that bundler updates the lockfile like that for non install/update operations. However, we made one exception in this case because the lockfile you have could be vulnerable to [dependency confusion](https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610) issues, since it doesn't unambiguously indicate which source each dependency should be pulled from. So when bundler encounters such a lockfile, it automatically updates it to a secure version.

So, yeah, sorry if it was inconvenient, but we did this trying to make things secure.

What's not expected to me is that this is happening in `frozen` mode. In that case, `bundler` should only print a warning but still use the insecure version of the lockfile.

**Comment by deivid-rodriguez** [comment]
After some more thought, I'm not really sure what the best behaviour is for each of the situations you mention in presence of an insecure lockfile. For bundle install/update, auto-updating the format seems definitely the way to go, but for other operations I'm not 100% clear. I _think_ `bundle exec` in particular might be back to working the way you expect after https://github.com/rubygems/rubygems/pull/4805, since it completely ignores any Gemfile sources and just uses locally installed specs. Can you try it?

**Comment by deivid-rodriguez** [comment]
I released bundler 2.2.26 with the mentioned fix.

Since I got no feedback here, and that change should improve the situation, I will close this.

**Comment by timsutton** [comment]
I just did a test for this issue in 2.2.26, by doing the following test, bundle exec-ing the `pod` (via cocoapods) I have in a similar Gemfile with public/private sources:

```
# bundle exec
bundle _2.2.26_ exec pod -h

# bundle check
bundle _2.2.26_ check
```

..but this still mutated the lockfile in both cases.

I think there may have been some confusion re: `frozen` earlier, though. When `frozen` is set, it doesn't update the lockfile. I think @gyfelton may have meant in "We also have frozen config to ensure no update of Gemfile.lock as well," that setting `frozen` was implemented as a result of encountering this issue.

**Comment by deivid-rodriguez** [comment]
Ah, ok, that makes sense.

Then I think this is all expected here. As I said before, this is not something `bundler` does in general, but something quite unique to this particular situation (presence of a vulnerable lockfile), where `bundler` chooses to rewrite the lockfile to be secure.

I recommend that you update to the secure format and move on, but if for some reason you want to stick format to the previous format, you can indeed set frozen mode. It's likely that the next major version of `bundler` won't be able to read the previous format, though.
