### ISSUE TITLE
Ruby 2.5 with rubygems 2.7.6.3: bundler_version_finder.rb:89:in `untaint': can't modify frozen String (FrozenError)

### ISSUE THREAD

**Issue by olleolleolle** [rubygems/rubygems#4837]
I experienced a frozen String issue in bundler_version_finder.rb in a CI job which targeted EOL'd 2.5.

The output was:

```
/opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/bundler_version_finder.rb:89:in `untaint': can't modify frozen String (FrozenError)
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/bundler_version_finder.rb:89:in `lockfile_contents'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/bundler_version_finder.rb:65:in `lockfile_version'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/bundler_version_finder.rb:19:in `bundler_version_with_reason'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/bundler_version_finder.rb:4:in `bundler_version'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/bundler_version_finder.rb:42:in `filter!'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems/dependency.rb:283:in `matching_specs'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems.rb:273:in `find_spec_for_exe'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/lib/ruby/2.5.0/rubygems.rb:303:in `activate_bin_path'
	from /opt/hostedtoolcache/Ruby/2.5.9/x64/bin/bundle:23:in `<main>'
```

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.6.3
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
I guess this was fixed by https://github.com/rubygems/rubygems/pull/2115, which was released as rubygems 2.7.7. You need to update to at least that version. If it was a newer ruby, you could probably request a backport and it would be accepted, but ruby 2.5 reached its end of life [last april](https://www.ruby-lang.org/en/news/2021/04/05/ruby-2-5-9-released/), so you're out of luck.

Anyways, I'll close this since it's an issue that should've been fixed a while ago!

**Comment by olleolleolle** [comment]
Thanks for the path forward!

**Comment by olleolleolle** [comment]
@deivid-rodriguez I used such a version, and it worked well.
