### ISSUE TITLE
Proposal: S> "semantic safe" requirement operator

### ISSUE THREAD

**Issue by nevir** [rubygems/rubygems#484]
Or `$>`, or `%>`, or just `$`, or something.

[`~> 1.2.3` is rarely the correct requirement to express if the target gem is following semantic versioning](https://coderwall.com/p/wbljca).  What we really need, imo, is a "semantic safe" requirement.

Something along the lines of `$> 1.2.3` which maps to `>= 1.2.3`, `< 2.0.0`

**Comment by copiousfreetime** [comment]
I think this is adequately resolved with the [Rubygems Patterns Guide](http://guides.rubygems.org/patterns/). It details the proper usage of the pessimistic operator and its relation to semantic versioning.
