### ISSUE TITLE
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

### ISSUE THREAD

**Issue by sagar-cogoport** [rubygems/rubygems#4840]
Gem::Package::FormatError: package is corrupt, exception while verifying: uninitialized constant Gem::Specification
Did you mean?  Gem::Specification
       Gem::StubSpecification (NameError) in /Users/sagarbankar/.rvm/gems/jruby-9.2.9.0/cache/rgeo-2.3.0.gem
  /Users/sagarbankar/.rvm/rubies/jruby-9.2.9.0/lib/ruby/stdlib/rubygems/package.rb:620:in `verify_entry'
  /Users/sagarbankar/.rvm/rubies/jruby-9.2.9.0/lib/ruby/stdlib/rubygems/package.rb:628:in `block in verify_files'
  /Users/sagarbankar/.rvm/rubies/jruby-9.2.9.0/lib/ruby/stdlib/rubygems/package/tar_reader.rb:65:in `each'
  /Users/sagarbankar/.rvm/rubies/jruby-9.2.9.0/lib/ruby/stdlib/rubygems/package.rb:627:in `verify_files'
  /Users/sagarbankar/.rvm/rubies/jruby-9.2.9.0/lib/ruby/stdlib/rubygems/package.rb:557:in `block in verify'
  /Users/sagarbankar/.rvm/rubies/jruby-9.2.9.0/lib/ruby/stdlib/rubygems/package/tar_reader.rb:29:in `new'
  /Users/sagarbankar/.rvm/rubies/jruby-9.2.9.0/lib/ruby/stdlib/rubygems/package.rb:554:in `block in verify'
  org/jruby/RubyIO.java:1160:in `open'
  /Users/sagarbankar/.rvm/rubies/jruby-9.2.9.0/lib/ruby/stdlib/rubygems/package/file_source.rb:30:in `with_read_io'
  /Users/sagarbankar/.rvm/rubies/jruby-9.2.9.0/lib/ruby/stdlib/rubygems/package.rb:553:in `verify'
  /Users/sagarbankar/.rvm/rubies/jruby-9.2.9.0/lib/ruby/stdlib/rubygems/package.rb:534:in `spec'
  /Users/sagarbankar/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.2.25/lib/bundler/rubygems_integration.rb:252:in `spec_from_gem'
  /Users/sagarbankar/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.2.25/lib/bundler/source/rubygems.rb:150:in `install'
  /Users/sagarbankar/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.2.25/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Users/sagarbankar/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.2.25/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Users/sagarbankar/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.2.25/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /Users/sagarbankar/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.2.25/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /Users/sagarbankar/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.2.25/lib/bundler/worker.rb:62:in `apply_func'
  /Users/sagarbankar/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.2.25/lib/bundler/worker.rb:57:in `block in process_queue'
  org/jruby/RubyKernel.java:1446:in `loop'
  /Users/sagarbankar/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.2.25/lib/bundler/worker.rb:54:in `process_queue'
  /Users/sagarbankar/.rvm/rubies/jruby-9.2.9.0/lib/ruby/gems/shared/gems/bundler-2.2.25/lib/bundler/worker.rb:91:in `block in create_threads'
```

**Comment by deivid-rodriguez** [comment]
Upgrading rubygems and jruby should fix your issue.
