### ISSUE TITLE
Old bundler version tags mixed in with original rubygems version tags

### ISSUE THREAD

**Issue by markdascher** [rubygems/rubygems#4844]
### Describe the problem as clearly as you can

After the work in #3157 and #3166 to combine bundler and rubygems into a single repository, some of the old bundler tags were copied over too. This makes it confusing when researching rubygems history, since the list of tags looks something like this:

```
…
v1.9.1
v1.9.0
v1.8.30
v1.8.29
…
```

But some of those tags are just old bundler versions, completely separate from the main rubygems history.

### Post steps to reproduce the problem

* Go to https://github.com/rubygems/rubygems
* Switch to the [v1.8.30](https://github.com/rubygems/rubygems/tree/v1.8.30) tag. This is rubygems.
* Switch to the [v1.9.0](https://github.com/rubygems/rubygems/tree/v1.9.0) tag. This is bundler. Hilarity ensues when you try to find `lib/rubygems.rb`

### What were you expecting to happen?

Ideally I would've expected to go to the old [bundler](https://github.com/rubygems/bundler) repo in order to see those old bundler version tags, like `v1.9.0`. Not have them show up in this repo.

Another possibility would be to keep the tags from bundler, but rename them so they're more obvious. Like `bundler-v1.9.0` , `bundler-v1.9.1`, etc. Looks like there's some of this already, but only for `bundler-v2.2.0` through `bundler-v2.2.25`

It's not the end of the world now that I know what's going on. So if it's too risky to fix, it could be OK to leave it alone. Figured it was at least worth mentioning in an issue.

### What actually happened?

Some of the old bundler version tags have been copied into this repo. However, not all of them. When both bundler and rubygems has a version with the same tag (e.g. `v1.8.0`), the existing rubygems tag (thankfully) seems to take precedence.

**Comment by deivid-rodriguez** [comment]
Uggh... I think renaming the tags to prefix `bundler-` would be the right thing to do. Can you find out the list of tags that would need to be updated?

**Comment by hsbt** [comment]
I agreed to rename them. After listing the targeted tags, I will do that.

**Comment by markdascher** [comment]
```sh
for tag in $(git tag)
do
    git merge-base --is-ancestor 421d1 $tag || echo $tag
done
```

Gave me a [list of 243 tags](https://github.com/rubygems/rubygems/files/6994040/is_not_rubygems.txt). Looking more closely, it seems like the bundler repo already had three separate initial commits: 392296c, 0df5eb4, and the current a8de418.

Disclaimer: No guarantees on the accuracy of that list, or that the command I used actually does what I think it does. 😄

**Comment by deivid-rodriguez** [comment]
The list makes sense to me in principle. I don't fully understand the command though, where does 421d1 come from?

**Comment by markdascher** [comment]
> The list makes sense to me in principle. I don't fully understand the command though, where does 421d1 come from?

Ah that's just the initial commit id of the master branch. It's the first one listed by running `git log --reverse master`: 421d175

**Comment by deivid-rodriguez** [comment]
Aaah ok, I was confused by the fact that https://github.com/rubygems/bundler/commit/421d1 is a 404, whereas https://github.com/rubygems/bundler/commit/421d1 pointed to a change that made no sense to me.

**Comment by hsbt** [comment]
I organized tags by the following script.

```
`git tag`.split.each do |tag|
  tag = `git merge-base --is-ancestor 421d1 #{tag} || echo #{tag}`.chomp
  unless tag.empty?
    `git tag bundler-#{tag} #{tag}`
    `git tag -d #{tag}`
    `git push origin :#{tag}`
  end
end
```

and backup  is here: https://gist.github.com/hsbt/f245e0bcc3350205040dc13d462b669f
