### ISSUE TITLE
Gem::DependencyError although dependencies could be resolved

### ISSUE THREAD

**Issue by zinga666** [rubygems/rubygems#485]
Hi,

when trying to install a self-made Gem (from a local Gem server) with

```
$ gem install my_gem_name
I get the following dependency error:

ERROR:  While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: vagrant requires net-ssh (~> 2.2.2); rye requires net-ssh (>= 2.0.13); net-scp requires net-ssh (>= 1.99.1)
```

In my opinion this should be resolvable though (i.e. _net-ssh_ 2.2.2 should meet the requirements).

Note:

```
$ gem install vagrant my_gem_name
works, i.e. installs the Gems and deps.

$ gem --version
1.8.23
```

**Comment by ch8090** [comment]
While executing gem ... (Gem::DependencyError)
    Unable to resolve dependencies: cocoapods requires cocoapods-core (= 1.2.0), cocoapods-downloader (< 2.0, >= 1.1.3), cocoapods-trunk (< 2.0, >= 1.1.2), molinillo (~> 0.5.5), xcodeproj (< 2.0, >= 1.4.1), colored (~> 1.2), escape (~> 0.0.4), fourflusher (~> 2.0.1), gh_inspector (~> 1.0), nap (~> 1.0), ruby-macho (~> 0.2.5); activesupport requires i18n (~> 0.7), tzinfo (~> 1.1), minitest (~> 5.1), thread_safe (>= 0.3.4, ~> 0.3); cocoapods-plugins requires nap (>= 0)
