### ISSUE TITLE
 uninitialized constant Gem::KERNEL_WARN_IGNORES_INTERNAL_ENTRIES (NameError)

### ISSUE THREAD

**Issue by lyf571321556** [rubygems/rubygems#4857]
Mac M1:

gem env version:
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/version.rb:157: warning: already initialized constant Gem::Version::VERSION_PATTERN
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/version.rb:158: warning: previous definition of VERSION_PATTERN was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/version.rb:158: warning: already initialized constant Gem::Version::ANCHORED_VERSION_PATTERN
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/version.rb:159: warning: previous definition of ANCHORED_VERSION_PATTERN was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/requirement.rb:12: warning: already initialized constant Gem::Requirement::OPS
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/requirement.rb:14: warning: previous definition of OPS was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/requirement.rb:22: warning: already initialized constant Gem::Requirement::SOURCE_SET_REQUIREMENT
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/requirement.rb:24: warning: previous definition of SOURCE_SET_REQUIREMENT was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/requirement.rb:25: warning: already initialized constant Gem::Requirement::PATTERN_RAW
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/requirement.rb:27: warning: previous definition of PATTERN_RAW was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/requirement.rb:30: warning: already initialized constant Gem::Requirement::PATTERN
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/requirement.rb:32: warning: previous definition of PATTERN was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/requirement.rb:35: warning: already initialized constant Gem::Requirement::DefaultRequirement
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/requirement.rb:37: warning: previous definition of DefaultRequirement was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/requirement.rb:40: warning: already initialized constant Gem::Requirement::DefaultPrereleaseRequirement
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/requirement.rb:42: warning: previous definition of DefaultPrereleaseRequirement was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/requirement.rb:292: warning: already initialized constant Gem::Version::Requirement
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/platform.rb:204: warning: already initialized constant Gem::Platform::RUBY
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/platform.rb:198: warning: previous definition of RUBY was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/platform.rb:210: warning: already initialized constant Gem::Platform::CURRENT
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/platform.rb:204: warning: previous definition of CURRENT was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:47: warning: already initialized constant Gem::Specification::NONEXISTENT_SPECIFICATION_VERSION
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:51: warning: previous definition of NONEXISTENT_SPECIFICATION_VERSION was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:70: warning: already initialized constant Gem::Specification::CURRENT_SPECIFICATION_VERSION
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:74: warning: previous definition of CURRENT_SPECIFICATION_VERSION was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:76: warning: already initialized constant Gem::Specification::SPECIFICATION_VERSION_HISTORY
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:80: warning: previous definition of SPECIFICATION_VERSION_HISTORY was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:94: warning: already initialized constant Gem::Specification::MARSHAL_FIELDS
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:98: warning: previous definition of MARSHAL_FIELDS was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:103: warning: already initialized constant Gem::Specification::TODAY
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:107: warning: previous definition of TODAY was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:106: warning: already initialized constant Gem::Specification::LOAD_CACHE
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:110: warning: previous definition of LOAD_CACHE was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:108: warning: already initialized constant Gem::Specification::LOAD_CACHE_MUTEX
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:112: warning: previous definition of LOAD_CACHE_MUTEX was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:112: warning: already initialized constant Gem::Specification::VALID_NAME_PATTERN
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:116: warning: previous definition of VALID_NAME_PATTERN was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:163: warning: already initialized constant Gem::Specification::INITIALIZE_CODE_FOR_DEFAULTS
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:167: warning: previous definition of INITIALIZE_CODE_FOR_DEFAULTS was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:189: warning: already initialized constant Gem::Specification::NOT_FOUND
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:192: warning: previous definition of NOT_FOUND was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:194: warning: already initialized constant Gem::Specification::REMOVED_METHODS
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:197: warning: previous definition of REMOVED_METHODS was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:1669: warning: already initialized constant Gem::Specification::DateLike
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:1671: warning: previous definition of DateLike was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:1674: warning: already initialized constant Gem::Specification::DateTimeFormat
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:1676: warning: previous definition of DateTimeFormat was here
Traceback (most recent call last):
        5: from <internal:gem_prelude>:1:in `<internal:gem_prelude>'
        4: from <internal:gem_prelude>:1:in `require'
        3: from /Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems.rb:1444:in `<top (required)>'
        2: from /Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems.rb:1444:in `require'
        1: from /Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:10:in `<top (required)>'
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:20:in `<module:Kernel>': uninitialized constant Gem::KERNEL_WARN_IGNORES_INTERNAL_ENTRIES (NameError)

Here are my current environment details:

```
$ gem env version
PASTE HERE
```
gem env version
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/version.rb:157: warning: already initialized constant Gem::Version::VERSION_PATTERN
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/version.rb:158: warning: previous definition of VERSION_PATTERN was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/version.rb:158: warning: already initialized constant Gem::Version::ANCHORED_VERSION_PATTERN
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/version.rb:159: warning: previous definition of ANCHORED_VERSION_PATTERN was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/requirement.rb:12: warning: already initialized constant Gem::Requirement::OPS
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/requirement.rb:14: warning: previous definition of OPS was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/requirement.rb:22: warning: already initialized constant Gem::Requirement::SOURCE_SET_REQUIREMENT
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/requirement.rb:24: warning: previous definition of SOURCE_SET_REQUIREMENT was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/requirement.rb:25: warning: already initialized constant Gem::Requirement::PATTERN_RAW
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/requirement.rb:27: warning: previous definition of PATTERN_RAW was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/requirement.rb:30: warning: already initialized constant Gem::Requirement::PATTERN
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/requirement.rb:32: warning: previous definition of PATTERN was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/requirement.rb:35: warning: already initialized constant Gem::Requirement::DefaultRequirement
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/requirement.rb:37: warning: previous definition of DefaultRequirement was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/requirement.rb:40: warning: already initialized constant Gem::Requirement::DefaultPrereleaseRequirement
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/requirement.rb:42: warning: previous definition of DefaultPrereleaseRequirement was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/requirement.rb:292: warning: already initialized constant Gem::Version::Requirement
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/platform.rb:204: warning: already initialized constant Gem::Platform::RUBY
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/platform.rb:198: warning: previous definition of RUBY was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/platform.rb:210: warning: already initialized constant Gem::Platform::CURRENT
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/platform.rb:204: warning: previous definition of CURRENT was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:47: warning: already initialized constant Gem::Specification::NONEXISTENT_SPECIFICATION_VERSION
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:51: warning: previous definition of NONEXISTENT_SPECIFICATION_VERSION was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:70: warning: already initialized constant Gem::Specification::CURRENT_SPECIFICATION_VERSION
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:74: warning: previous definition of CURRENT_SPECIFICATION_VERSION was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:76: warning: already initialized constant Gem::Specification::SPECIFICATION_VERSION_HISTORY
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:80: warning: previous definition of SPECIFICATION_VERSION_HISTORY was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:94: warning: already initialized constant Gem::Specification::MARSHAL_FIELDS
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:98: warning: previous definition of MARSHAL_FIELDS was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:103: warning: already initialized constant Gem::Specification::TODAY
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:107: warning: previous definition of TODAY was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:106: warning: already initialized constant Gem::Specification::LOAD_CACHE
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:110: warning: previous definition of LOAD_CACHE was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:108: warning: already initialized constant Gem::Specification::LOAD_CACHE_MUTEX
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:112: warning: previous definition of LOAD_CACHE_MUTEX was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:112: warning: already initialized constant Gem::Specification::VALID_NAME_PATTERN
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:116: warning: previous definition of VALID_NAME_PATTERN was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:163: warning: already initialized constant Gem::Specification::INITIALIZE_CODE_FOR_DEFAULTS
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:167: warning: previous definition of INITIALIZE_CODE_FOR_DEFAULTS was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:189: warning: already initialized constant Gem::Specification::NOT_FOUND
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:192: warning: previous definition of NOT_FOUND was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:194: warning: already initialized constant Gem::Specification::REMOVED_METHODS
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:197: warning: previous definition of REMOVED_METHODS was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:1669: warning: already initialized constant Gem::Specification::DateLike
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:1671: warning: previous definition of DateLike was here
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/specification.rb:1674: warning: already initialized constant Gem::Specification::DateTimeFormat
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/specification.rb:1676: warning: previous definition of DateTimeFormat was here
Traceback (most recent call last):
	5: from <internal:gem_prelude>:1:in `<internal:gem_prelude>'
	4: from <internal:gem_prelude>:1:in `require'
	3: from /Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems.rb:1444:in `<top (required)>'
	2: from /Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems.rb:1444:in `require'
	1: from /Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:10:in `<top (required)>'
/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/site_ruby/2.7.0/rubygems/core_ext/kernel_require.rb:20:in `<module:Kernel>': uninitialized constant Gem::KERNEL_WARN_IGNORES_INTERNAL_ENTRIES (NameError)

**Comment by deivid-rodriguez** [comment]
Wow, I have no idea how this is happening.

Do you have a file named `/Users/ones/.rvm/rubies/ruby-2.7.3/lib/ruby/2.7.0/rubygems/core_ext/kernel_require.rb`?
