### ISSUE TITLE
Installing aws-sdk-resources omnibus package takes a very long time

### ISSUE THREAD

**Issue by matthew-hollick** [rubygems/rubygems#4860]
I'm having a problem

My current problem is that running gem install aws-sdk-resources takes about 2 hours. It appears that the number of dependencies exceeds a threshold and a very slow process starts where a dep file for each version of each file is fetched from rubygems.org.

To recreate the issue:
```
gem install aws-sdk-resources --verbose
```

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env version
2.7.6.2
$ ruby --version
2.5.8
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
You're using a very old version of rubygems. Please upgrade with `gem update --system` and if you still have issues, feel free to reopen this ticket.
