### ISSUE TITLE
Bundler update not retrieving transitive dependencies from the correct source

### ISSUE THREAD

**Issue by JohnVincentFinn** [rubygems/rubygems#4870]
I'm using private gem servers and when I modify my Gemfile to get a gem from a branch the gems that gem depends on are not being retrieved properly. The error message seems to indicate that they are not being retrieved from the private gem server and instead are defaulting to the global source for gems. My goal here is to be able to get a development version of a gem installed and get the gems that gem depends on updated/installed as well.

I've modified my Gemfile to get a specific gem from a Git repo at a specific branch like so:
```
source 'https://gem-proxy.chime.com'

source 'https://gem.fury.io/chime/' do
  gem "MY-GEM", git:"https://github.com/1debit/MY-GEM", branch: "some_branch"
end
```

When "bundle update MY-GEM --conservative" is run

```
Fetching https://github.com/1debit/MY-GEM
Fetching gem metadata from https://gem.fury.io/chime/...
Fetching gem metadata from https://gem-proxy.chime.com/...........
Resolving dependencies.............
Bundler could not find compatible versions for gem "MY-GEM":
  In Gemfile:
    MY-GEM

Bundler could not find compatible versions for gem "fog-core":
  In Gemfile:
    MY-GEM was resolved to 39.20210818.165844, which depends on
      fog-core (= 1.31.0)

    MY-GEM was resolved to 39.20210818.165844, which depends on
      fog (= 1.31.0) was resolved to 1.31.0, which depends on
        fog-core (~> 1.30)

    MY-GEM was resolved to 39.20210818.165844, which depends on
      fog-google (= 0.0.9) was resolved to 0.0.9, which depends on
        fog-core

Bundler could not find compatible versions for gem "fog-google":
  In Gemfile:
    MY-GEM was resolved to 39.20210818.165844, which depends on
      fog-google (= 0.0.9)

    MY-GEM was resolved to 39.20210818.165844, which depends on
      fog (= 1.31.0) was resolved to 1.31.0, which depends on
        fog-google (>= 0.0.2)

Bundler could not find compatible versions for gem "PRIVATE-GEM":
  In Gemfile:
    MY-GEM was resolved to 39.20210818.165844, which depends on
      PRIVATE-GEM (~> 1.33.0)

Could not find gem 'PRIVATE-GEM (~> 1.33.0)', which is required by gem
'MY-GEM', in rubygems repository https://gem-proxy.chime.com/ or installed
locally.
```

That gem that cannot be found does not exist in the gem-proxy.chime.com source and is instead in the private 'https://gem.fury.io/chime/' gem source.

### Post steps to reproduce the problem

bundle remove your-gem
bundle add your-gem --git https://github.com/1debit/your-gem --branch main

Where your-gem is a gem that depends on a gem from a private gem source.

### Which command did you run?

bundle update MY-GEM --conservative

### What were you expecting to happen?

For the gem to update itself and transitive dependencies properly.

### What actually happened?

Described above.

## Environment

```
Bundler       2.2.19
  Platforms   ruby, x86_64-linux
Ruby          2.7.3p183 (2021-04-05 revision 6847ee089d7655b2a0eea4fee3133aeacd4cc7cc) [x86_64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.2.16
  Gem Home    /usr/local/bundle
  Gem Path    /root/.local/share/gem/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/local/bundle
  User Home   /root
  User Path   /root/.local/share/gem/ruby/2.7.0
  Bin Dir     /usr/local/bundle/bin
Tools
  Git         2.17.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-05-31
Git SHA           43f80b12c0
Released Version  true
```

## Bundler settings

```
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
path
  Set via BUNDLE_PATH: "/usr/local/bundle"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```

### Gemfile

```ruby
# frozen_string_literal: true

source 'https://gem-proxy.chime.com'

source 'https://gem.fury.io/chime/' do
  gem 'MY-GEM', git:"https://github.com/1debit/MY-GEM", branch: "some_dev_branch"
end

end
```

### Gemfile.lock

```
GEM
  remote: https://gem-proxy.chime.com/
  specs:
    other-gems

GEM
  remote: https://gem.fury.io/chime/
  specs:
    MY-GEM (39.20210823.234636)
      fog (= 1.31.0)
      fog-core (= 1.31.0)
      fog-google (= 0.0.9)
      PRIVATE-GEM (~> 1.34.0)
      <there are other gems, but I've removed gems that don't seem relevant for clarity>
    PRIVATE-GEM (1.34.20210824082131)
      other-gems

PLATFORMS
  x86_64-darwin-20
  x86_64-linux

DEPENDENCIES
  MY-GEM!

BUNDLED WITH
   2.2.20
```

**Comment by deivid-rodriguez** [comment]
Hi @JohnVincentFinn!

Yeah, unfortunately this is a known issue since 2.2.18 when we fixed [dependency confusion vulnerabilities](https://medium.com/@alex.birsan/dependency-confusion-4a5d60fec610).

The current source priority is really basic: pick gems from the innermost source that includes them, otherwise pick them from the global source. That means nested sources are not really supported at the moment, and in your case the `https://gem.fury.io/chime/` source is being ignored.

As a workaround, you can list the dependencies you want to be pulled from `https://gem.fury.io/chime/` explicitly under that source. I know it's not ideal but it's the only workaround I can think of until the issue is fixed.

I'm closing this in favor of #4817, feel free to subscribe to that ticket!
