### ISSUE TITLE
.gemspec.rz endpoint misses the license attribute

### ISSUE THREAD

**Issue by Nakilon** [rubygems/rubygems#4898]
Someone has noticed that the `gem specification` does not show the license attribute while the gem web page does.

```none
$ curl -s https://rubygems.org/api/v2/rubygems/bundler/versions/2.2.27.json | jq . | grep -A2 licen
  "licenses": [
    "MIT"
  ],
```
```none
$ gem specification -r bundler | grep licen
licenses: []
```

I've investigated it a bit and it looks like the `https://rubygems.org/quick/Marshal.4.8/bundler-2.2.27.gemspec.rz` endpoint returns the marshal data without the license.

![image](https://user-images.githubusercontent.com/2870363/132109338-2f57adb8-8e30-4244-b2e0-f391612ca313.png)

**This issue is related to:**
  - [x] The command line `gem`

**Here are my current environment details:**

```
$ rbenv -v
rbenv 1.1.2
```

The issue is seen for any gem and when using either ruby 2.3.8 or 3.0.1, since they all fetch the same rubygems endpoint.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Pretty sure this was fixed by #7975, closing!
