### ISSUE TITLE
Error 401 when installing gem from private repo (REDACTED creds)

### ISSUE THREAD

**Issue by sergei-fedorov** [rubygems/rubygems#4906]
My current problem is: after update to rubygems 3.2.27 `gem install bundler --source https://user@gems.private.com` fails with 
```
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://REDACTED@gems.private.com/ - bad response Unauthorized 401 
```

This issue is related to:

  - [ ] Network problems
  - [x] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.2.27
  - RUBY VERSION: 2.3.3 (2016-11-21 patchlevel 222) [x86_64-linux]
  - INSTALLATION DIRECTORY: /root/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0
  - USER INSTALLATION DIRECTORY: /root/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /root/.rbenv/versions/2.3.3/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /root/.rbenv/versions/2.3.3/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /root/.rbenv/versions/2.3.3/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /root/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0
     - /root/.gem/ruby/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://user@gems.private.com/"]
  - REMOTE SOURCES:
     - https://user@gems.private.com/
  - SHELL PATH:
     - /root/.rbenv/versions/2.3.3/bin
     - /usr/lib/rbenv/libexec
     - /root/.rbenv/shims
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/local/go1.10/bin
     - /opt/mssql-tools/bin
     - /opt/hostedtoolcache/Ruby/2.5.1/x64/bin
```

Output of gem install with --verbose --debug:
```
root@agent:~# gem install bundler --verbose --debug
NOTE:  Debugging mode prints all exceptions even when rescued
HEAD https://REDACTED@gems.private.com/
200 OK
GET https://REDACTED@gems.private.com/info/bundler
401 Unauthorized
Exception `Gem::RemoteFetcher::FetchError' at /root/.rbenv/versions/2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/remote_fetcher.rb:232 - bad response Unauthorized 401 (https://REDACTED@gems.private.com/info/bundler)
Exception `Errno::EEXIST' at /root/.rbenv/versions/2.3.3/lib/ruby/2.3.0/fileutils.rb:253 - File exists @ dir_s_mkdir - /root/.gem/specs/gems.private.com%443
GET https://REDACTED@gems.private.com/prerelease_specs.4.8.gz
401 Unauthorized
Exception `Gem::RemoteFetcher::FetchError' at /root/.rbenv/versions/2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/remote_fetcher.rb:232 - bad response Unauthorized 401 (https://REDACTED@gems.private.com/prerelease_specs.4.8.gz)
Exception `Errno::EEXIST' at /root/.rbenv/versions/2.3.3/lib/ruby/2.3.0/fileutils.rb:253 - File exists @ dir_s_mkdir - /root/.gem/specs/gems.private.com%443
GET https://REDACTED@gems.private.com/specs.4.8.gz
401 Unauthorized
Exception `Gem::RemoteFetcher::FetchError' at /root/.rbenv/versions/2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/remote_fetcher.rb:232 - bad response Unauthorized 401 (https://REDACTED@gems.private.com/specs.4.8.gz)
Exception `Gem::RemoteFetcher::FetchError' at /root/.rbenv/versions/2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/spec_fetcher.rb:258 - bad response Unauthorized 401 (https://REDACTED@gems.private.com/specs.4.8.gz)
Exception `Gem::UnsatisfiableDependencyError' at /root/.rbenv/versions/2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/resolver.rb:233 - Unable to resolve dependency: user requested 'bundler (>= 0)'
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://REDACTED@gems.private.com/ - bad response Unauthorized 401 (https://REDACTED@gems.private.com/specs.4.8.gz)
Exception `Errno::EEXIST' at /root/.rbenv/versions/2.3.3/lib/ruby/2.3.0/fileutils.rb:253 - File exists @ dir_s_mkdir - /root/.gem/specs/gems.private.com%443
GET https://REDACTED@gems.private.com/latest_specs.4.8.gz
200 OK
ERROR:  Possible alternatives: appbundler, asset_bundler, atd-asset_bundler, bake-bundler, bonnie_bundler, bowline-bundler, bundle_rc, bundle_requests, bundler, bundler-add
```

When rolled back to 3.2.26:
```
root@agent:~# gem install bundler --verbose --debug
NOTE:  Debugging mode prints all exceptions even when rescued
HEAD https://user@gems.private.com/
200 OK
GET https://user@gems.private.com/info/bundler
404 Not Found
Exception `Gem::RemoteFetcher::FetchError' at /root/.rbenv/versions/2.3.3/lib/ruby/site_ruby/2.3.0/rubygems/remote_fetcher.rb:238 - bad response Not Found 404 (https://user@gems.private.com/info/bundler)
Exception `Errno::EEXIST' at /root/.rbenv/versions/2.3.3/lib/ruby/2.3.0/fileutils.rb:253 - File exists @ dir_s_mkdir - /root/.gem/specs/gems.private.com%443
GET https://user@gems.private.com/prerelease_specs.4.8.gz
200 OK
Exception `Errno::EEXIST' at /root/.rbenv/versions/2.3.3/lib/ruby/2.3.0/fileutils.rb:253 - File exists @ dir_s_mkdir - /root/.gem/specs/gems.private.com%443
GET https://user@gems.private.com/specs.4.8.gz
200 OK
Exception `Errno::EEXIST' at /root/.rbenv/versions/2.3.3/lib/ruby/2.3.0/fileutils.rb:253 - File exists @ dir_s_mkdir - /root/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0
Exception `Errno::ENOENT' at /root/.rbenv/versions/2.3.3/lib/ruby/2.3.0/fileutils.rb:1451 - No such file or directory @ unlink_internal - /root/.rbenv/versions/2.3.3/lib/ruby/gems/2.3.0/specifications/bundler-2.2.27.gemspec
... many similar exceptions ...
Successfully installed bundler-2.2.27
Parsing documentation for bundler-2.2.27
Parsing sources...
100% [205/205]  lib/bundler/yaml_serializer.rb
Done installing documentation for bundler after 6 seconds
1 gem installed
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by ruionwriting** [comment]
I'm chasing an issue like this but I suspect is related to some Artifactory changes in package resolution. I'll update as soon I know more details.

**Comment by ruionwriting** [comment]
I can confirm I can replicate the issue with `2.2.27`.

**Comment by ruionwriting** [comment]
After a bunch of testing I've wrote a small script to find out what versions things working or not since we've knew `3.1.4` was a good version. I'm doing more tests before rushing into conclusions here as I'm getting some slow responses that might causing the results to skew.

**Comment by ruionwriting** [comment]
## Investigation

For my use case looks that only my private packages are being affected. Anyway, I've run a bunch of automated tests against our Artifactory instance, and here are the conclusions so far:

- Only versions `3.2.1` and `3.2.2` got all the runs successful
- Versions `3.2.0`, `3.2.4`, `3.2.6`, `3.2.10` and `3.2.20` failed 1/7, I can assume fairly stable
- Versions `3.2.13`, `3.2.15-19`,`3.2.21` and `3.2.23` are very unstable
- Latest `3.2.27` failed 100% of the test runs

## Full picture

![image](https://user-images.githubusercontent.com/1220067/132360283-f02b4bb9-1223-4573-b2da-ec99c7eb8a30.png)

## Questions

- Why can some versions perform worst against the Artifactory instance in question?
- Could this be the clients reaching some sort of failure due to server response times and wrong response codes causing a miss-interpretation of the results?
- Can someone help with this?

**Comment by ruionwriting** [comment]
> I'm chasing an issue like this but I suspect is related to some Artifactory changes in package resolution. I'll update as soon I know more details.

To be fair to the vendor, I'm not sure this is a package resolution issue based on the learnings today but I don't want to exclude anything at this point.

**Comment by intuxicated** [comment]
@ruionwriting Thanks for sharing your investigation.

At first, I thought this is an edge case failure that we didn't cover but now with what you have provided, it seems to be a kind of random failure.
I'm curious to know what kind of gem server are you using? because that could be the actual problem. 

If you or @sergei-fedorov could help us find a way to reproduce the error, it would be awesome.

**Comment by ruionwriting** [comment]
I'm using JFrog Artifactory cloud instance. Anyone can register for a free test to get the same setup as me. 

My repo layout where I have the issue in hands:

- `gems-local` where we push internal gens
- `gems-remote` the public RubyGems.org
- `gems` is virtual repo that my users use as the endpoint. Package resolution is 1st from `gems-local` then `gems-remote`

In Artifactory world a `virtual` can serve (not limited to these):

- local
- remotes

And we can configure resolution priority.

**Comment by avivbl** [comment]
@intuxicated , I added a proxy (Charles) between the client and Artifactory and found that the client sent this as the authentication header:
`Authorization Basic YWRtaW46UkVEQUNURUQ=`
YWRtaW46UkVEQUNURUQ= equals "admin:REDACTED"
For some reason, the client changes the password (which is "password") to "REDACTED" and send it as the password, therefore the 401s:

![Screen Shot 2021-09-07 at 10 23 31](https://user-images.githubusercontent.com/24430975/132386796-e85ceb67-31f0-450a-ac3a-37fac8f80536.png)

**Comment by ruionwriting** [comment]
Important to add:

- If you using Ruby `2.7.x` pretty much any RubyGems version can be installed, logically the most stable ones like `3.2.2`
- If you using Ruby `3.0.x` then you need to use `> 3.2.3`, I've found `3.2.10` the only viable option base on my experiments and also for local use

**Comment by sergei-fedorov** [comment]
@intuxicated 
> I'm curious to know what kind of gem server are you using? because that could be the actual problem.

I'm using geminabox

**Comment by sergei-fedorov** [comment]
https://github.com/rubygems/rubygems/issues/4908 https://github.com/rubygems/rubygems/pull/4910 look related.

**Comment by jdliss** [comment]
@avivbl I was able to reproduce that behavior with charles as well.  Digging deeper I think I've found the culprit, I added a PR which should fix the issue https://github.com/rubygems/rubygems/pull/4919
