### ISSUE TITLE
The wordy function in SourceFetchProblem will change the password of source

### ISSUE THREAD

**Issue by Huangxiaodui** [rubygems/rubygems#4908]
I'm having a problem or would like to suggest a feature.

My current problem is when I was reviewing the code, I found that in the **errors.rb** file, the **wordy** function of class**SourceFetchProblem** is used to anonymizes **uri.password**. However, the value of **source** is assigned to @source during initialization. When the value of **@source.uri.password** is changed to **REDACTED**, the password of the **source** is also changed.
I know what's in the current code doesn't have any practical impact, but I think this usage leaves a risk for future evolution. For developers who are not familiar with the content, if the password in the **source** is processed after the **sourceFetchProblem.wordy** is invoked, for example, password verification, and the password is reset to REDACTED, security risks may exist.
Therefore, I suggest modifying the current anonymization implementation and using **@source = Marshal.load(Marshal.dump(source))** to assign values to reduce risks.

This is my test code:
```
  require 'rubygems/remote_fetcher'
  
  source = Gem::Source.new 'https://username:secret@gemsource.com'
  uri = 'https://user:secret@gemsource.org'
  error = Gem::RemoteFetcher::FetchError.new('There was an error fetching', uri)
  print("error：", error, "\n")
  print("用户密码(SourceFetchProblem处理前):", source.uri.password, "\n")
  sf = Gem::SourceFetchProblem.new source, error
  print("用户密码(SourceFetchProblem处理后):", source.uri.password, "\n")
  print("error：", error, "\n")
  print("sf.error：", error, "\n")
  print("wordy输出：", sf.wordy, "\n")
  print("source.uri(SourceFetchProblem处理后):", source.uri, "\n")
```

![image](https://user-images.githubusercontent.com/28924664/132640346-4cf4339b-31f8-4731-a9a8-ac1b7253d51f.png)

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X ] Other

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
I understand the potential issue, but for the fix we should use our `Gem::Uri` class, in particular the `redacted` method, which creates a copy of the URI  with credentials redacted.
