### ISSUE TITLE
Potentially dangerous URL in Gem creation code generator

### ISSUE THREAD

**Issue by sixtyfive** [rubygems/rubygems#4917]
All y'all might want to change the code generator that creates the `.gemspec` upon running `bundle gem foobar` (as is given in the newbie instructions at https://bundler.io/guides/creating_gem.html): `foobar.gemspec` contains the example URL `https://mygemserver.com` which has apparently been domaingrabbed and which looks sort of shady. A good alternative choice might be [example.com](https://example.com). Okay, that's it, thanks for an awesome piece of software, bye!

**Comment by indirect** [comment]
Phew, yeah, what a shady website. Thanks for letting us know!
