### ISSUE TITLE
rubygems tests failing with customized environment variable "make"

### ISSUE THREAD

**Issue by junaruga** [rubygems/rubygems#4921]
I'm having a problem. When I was working with defined `make` environment variable, I faced this issue. In ruby/ruby, it is used in the following part.
https://github.com/ruby/ruby/blob/9770bf23b7a273246b9a6b084e79a8fb6fc1af11/.github/workflows/compilers.yml#L184

My current problem is 

On the latest master branch `3387dbf66d3721f1a25ea60d6bab8fddaf257f74`, the following tests fail with the defined `make` environment variable.

Here is the reproducer. I am using Fedora 34.

```
$ ruby -v
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]

$ export make='make -j2'

$ rake setup

$ ruby -Ilib:test test/rubygems/test_gem_ext_configure_builder.rb
Loaded suite test/rubygems/test_gem_ext_configure_builder
Started
F
========================================================================================================
Failure: test_self_build(TestGemExtConfigureBuilder): Expected make command "make -j2": make -j2 DESTDIR\=
/home/jaruga/var/git/rubygems/test/rubygems/helper.rb:299:in `assert_contains_make_command'
test/rubygems/test_gem_ext_configure_builder.rb:37:in `test_self_build'
========================================================================================================
.F
========================================================================================================
Failure: test_self_build_has_makefile(TestGemExtConfigureBuilder): Expected make command "make -j2": make -j2 DESTDIR\=
/home/jaruga/var/git/rubygems/test/rubygems/helper.rb:299:in `assert_contains_make_command'
test/rubygems/test_gem_ext_configure_builder.rb:76:in `test_self_build_has_makefile'
========================================================================================================

Finished in 0.050182784 seconds.
--------------------------------------------------------------------------------------------------------
3 tests, 16 assertions, 2 failures, 0 errors, 0 pendings, 0 omissions, 0 notifications
33.3333% passed
--------------------------------------------------------------------------------------------------------
59.78 tests/s, 318.83 assertions/s
Coverage report generated for Unit Tests to /home/jaruga/var/git/rubygems/coverage. 1142 / 3755 LOC (30.41%) covered.
```

The reason of the failures are at test/rubygems/test_gem_ext_configure_builder.rb:37:in `test_self_build', the called `assert_contains_make_command` with 1st argument: `''` has a bug.

test/rubygems/test_gem_ext_configure_builder.rb:37

```
assert_contains_make_command '', output.shift
```

The used make command is to get from `MAKE` or `make` if it is defined according to `lib/rubygems/ext/builder.rb` method `make`.

```
  def self.make(dest_path, results, make_dir = Dir.pwd)
    ...
    make_program = ENV['MAKE'] || ENV['make'] || $1
    ...
```

Then in the testing method `assert_contains_make_command`, here is a logic to set empty string to make the `assert_contains_make_command` return true even when the 1st argument is empty string. However if the `make` environment variable has argument such as `-j2`,  the targets is not empty, therefore the `targets` array does not has empty string `''`, and the assertion fails. 

test/rubygems/helper.rb

```
  def parse_make_command_line(line)
    ...
        targets << '' if targets.empty?
    ...
```

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [X] Other

Here are my current environment details:

```
$ gem env
PASTE HERE
```

The `gem` command is not used in this case. I tested this issue on the latest master branch `3387dbf66d3721f1a25ea60d6bab8fddaf257f74`.

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by junaruga** [comment]
CC: @shyouhei , I found [the defined `make` environment variable used in ruby/ruby `compilers.yml`](https://github.com/ruby/ruby/blob/9770bf23b7a273246b9a6b084e79a8fb6fc1af11/.github/workflows/compilers.yml#L184
) can trigger test failures by `make test-all`.

**Comment by deivid-rodriguez** [comment]
@junaruga Can you submit a fix?

**Comment by deivid-rodriguez** [comment]
As far as I understand, this is just a "test fix"? If that's the case, I don't need we don't need any test case to cover that?

**Comment by junaruga** [comment]
Yeah, maybe only the "test fix". As this issue happens on the env `make="make -<any option>"`, I wanted to set the env to a CI. But I am okay to just fix the test.

**Comment by deivid-rodriguez** [comment]
Right, I can see why you would want the fix covered by exercising the proper ENV in CI. Feel free to go with either fixing just the test or also adding something to the CI to verify it. The `install-rubygems.yml` worlkflow is kind of a file used for this kind of misc high level tests, so feel free to use that, ideally something as minimal as possible to cover this.
