### ISSUE TITLE
Improve "only check if description starts with FIXME/TODO" fix

### ISSUE THREAD

**Issue by duckinator** [rubygems/rubygems#4926]
As @nobu pointed out in <https://github.com/rubygems/rubygems/commit/7890c98415e829c94d383e17c4ca88af40ea0391>, #4841 &mdash; my fix for #4808 &mdash; would make more sense using `\A` (to match the beginning of the string) instead of `^` (match the beginning of each line).

I'm not on a system where I can do development right now, and don't want it to get forgotten, so I'm opening an issue.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [x] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

N/A

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by duckinator** [comment]
When working on this, it would make sense to add tests for having a TODO/FIXME on the second-or-later line of the description.

**Comment by deivid-rodriguez** [comment]
Indeed, good catch!

**Comment by duckinator** [comment]
Resolved by #4937.
