### ISSUE TITLE
Bundle package gives argument as keyword parameters is deprecated warning.

### ISSUE THREAD

**Issue by marlinpierce** [rubygems/rubygems#4959]
### Describe the problem as clearly as you can

Calling `bundle package` generates a ruby deprecation warning:

    > bundle package
    /usr/local/lib/ruby/site_ruby/2.7/rubygems/package.rb:509: warning: Using the last argument as keyword parameters is deprecated

Line 509:

    Zlib::GzipReader.wrap(*args) do |gzio|

Calls wrap by splatting an array.  However, keyword arguments will no longer be passable via splatting and array and must be double splatted separately.  As in the following:

    Zlib::GzipReader.wrap(*args, **{}) do |gzio|

### Post steps to reproduce the problem

OS Version: `FreeBSD 13.0-RELEASE-p4`
Ruby version `2.7.3` installed by FreeBSD package: `ruby-2.7.3_2,1`
Gem version `3.0.8` installed by FreeBSD package: `ruby27-gems-3.0.8`
Bundler version `2.2.19` installed by FreeBSD package `rubygem-bundler-2.2.19,1`

### Which command did you run?

    bundle package

### What were you expecting to happen?

Packaging worked as expected but with the deprecation warning for ruby 3.x syntax.

### What actually happened?

Deprecation warning appeared.

    /usr/local/lib/ruby/site_ruby/2.7/rubygems/package.rb:509: warning: Using the last argument as keyword parameters is deprecated

### If not included with the output of your command, run `bundle env` and paste the output below

[bundle.env.txt](https://github.com/rubygems/rubygems/files/7280783/bundle.env.txt)

**Comment by marlinpierce** [comment]
Also happens just running `bundle`.

**Comment by deivid-rodriguez** [comment]
It sounds like this is your problem: https://forums.freebsd.org/threads/2021q1-rubygems-deprecation-warnings.78333/. Most likely a packaging issue. If this can be reproduced against the latest rubygems version, feel free to reopen! Thanks!
