### ISSUE TITLE
Define what the pessimistic operator (~>) does for pre release gems.

### ISSUE THREAD

**Issue by y8** [rubygems/rubygems#497]
Hey. While I'm little busy at work to jump into #454, I've found questionable behaviour in rubygems, regarding how "pre-release" versions are treated in dependecies.

Story: we are using "git-flow" like model for release management. So we have different versions of gems for each "flow". For example for "develop" branch we have `x.y.z.dev%build%`, for "pre-release" `x.y.z.rc%build%` and for releases just "x.y.z". We call this "dev", "rc" strings "tags"

What's wrong: rubygems don't give a single yellow duck about tags. 

Here my test bench: 

Gems:
- baz
  - baz-1.0.0.a.1 (add_dependency "~> 1.0.0.a")
  - baz-1.0.0.b.1  (add_dependency "~> 1.0.0.b")
- bar
  - bar-1.0.0.a.1
  - bar-1.0.0.b.1

What I expect in my universe of pink unicorns and butterflies: 

`gem install baz --pre --v 1.0.0.a.1` gives me
- bar-1.0.0.a.1
- baz-1.0.0.a.1

What happens in grumpy reality:

`gem install baz --pre --v 1.0.0.a.1` gives me
- bar-1.0.0.b.1
- baz-1.0.0.a.1

This is not seems right, since `gem.add_dependency "bar", "> 1.0.0.c", "< 1.0.0.cz"` works as expected. 

Am I missing something?

You can play with this stuff by yourself. I've pushed this dummy gems to rubygems.org.

**Comment by copiousfreetime** [comment]
I've validated that the behavior indicated by @y8 still exists today

**Comment by bronzdoc** [comment]
Like @drbrain metioned 4 years ago `A patch to discuss would be instrumental in helping move this forward` meanwhile i'm going to close it
