### ISSUE TITLE
Dead link on Bundler::Fetcher::CertificateFailureError error message

### ISSUE THREAD

**Issue by yakschuss** [rubygems/rubygems#4984]
Hi, I'm getting `Bundler::Fetcher::CertificateFailureError` when dealing with a specific `bundle install` (not the subject of this issue.)

The bit.ly link [bit.ly/ruby-ssl](http://bit.ly/ruby-ssl) leads to https://railsapps.github.com/openssl-certificate-verify-failed.html, but the suffix has been changed from .com to .io.

Can't edit the bit.ly myself, or I'd try that first :) 

Link to error/link https://github.com/rubygems/rubygems/blob/23e18557ac7e8e31fb93724329c4ef83f4793453/bundler/lib/bundler/fetcher.rb#L31

**Comment by simi** [comment]
closed by https://github.com/rubygems/rubygems/pull/4987
