### ISSUE TITLE
Wrongly parsed path for lib if the name contains -

### ISSUE THREAD

**Issue by Secreto31126** [rubygems/rubygems#5000]
### Describe the problem as clearly as you can

Running `bundle gem name`, where name is any text with high dashes (-) makes the lib folder go mad: Every word between a dash creates a new sub-folder, instead of getting a .rb file with the name.

For example, running `bundle gem hello-world-v2` generates the following folders structure:

```
- hello-world-v2
   - ...
   - lib
      - hello
         - world
            - v2.rb
            - v2
               - version.rb
   - ...
```

If I had to guess, I would say there's a parsing error somewhere. I would also like to point out that adding "" to the name didn't change the output.

### Did you try upgrading rubygems & bundler?

Yes, I first encountered the error in bundler v2.2.22, and it's still present in v2.2.29

### Post steps to reproduce the problem

Run `bundle gem` with any name that contains -

### Which command did you run?

`bundle gem super-long-name-with-high-dashes-to-prove-my-point`

Output: `C:\Users\myname\Documents\Ruby\super-long-name-with-high-dashes-to-prove-my-point\lib\super\long\name\with\high\dashes\to\prove\my\point.rb`

### What were you expecting to happen?

To get a single folder inside lib

For example, with `bundle gem hello-world-v2` I expected the following structure:

```
- hello-world-v2
   - ...
   - lib
      - hello-world-v2.rb
      - hello-world-v2
         - version.rb
   - ...
```

### What actually happened?

I got a nasty nested bunch of folders.

```
- hello-world-v2
   - ...
   - lib
      - hello
         - world
            - v2.rb
            - v2
               - version.rb
   - ...
```

## Environment

```
Bundler       2.2.29
  Platforms   ruby, x64-mingw32
Ruby          3.0.2p107 (2021-07-07 revision 0db68f023372b634603c74fca94588b457be084c) [x64-mingw32]
  Full Path   C:/Ruby30-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.2.29
  Gem Home    C:/Ruby30-x64/lib/ruby/gems/3.0.0
  Gem Path    C:/Users/myname/.local/share/gem/ruby/3.0.0;C:/Ruby30-x64/lib/ruby/gems/3.0.0
  User Home   C:/Users/myname
  User Path   C:/Users/myname/.local/share/gem/ruby/3.0.0
  Bin Dir     C:/Ruby30-x64/bin
Tools
  Git         2.32.0.windows.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-10-08
Git SHA           4440b035ef
Released Version  true
```

## Bundler settings

```
gem.changelog
  Set for the current user (C:/Users/myname/.bundle/config): true
gem.ci
  Set for the current user (C:/Users/myname/.bundle/config): "github"
gem.coc
  Set for the current user (C:/Users/myname/.bundle/config): true
gem.mit
  Set for the current user (C:/Users/myname/.bundle/config): true
gem.rubocop
  Set for the current user (C:/Users/myname/.bundle/config): "true"
gem.test
  Set for the current user (C:/Users/myname/.bundle/config): false
```

**Comment by Secreto31126** [comment]
Ohh, I'm sorry, I didn't know about the naming structure.

My bad 😄

**Comment by deivid-rodriguez** [comment]
No problem!
