### ISSUE TITLE
Feature request: Set `require` parameter in `bundle add`

### ISSUE THREAD

**Issue by boardfish** [rubygems/rubygems#5017]
### Describe the problem as clearly as you can

When calling `bundle add`, there's no option to set the `require` parameter. For example, when adding `view_component` to a project, it's best to declare it in the Gemfile as `gem 'view_component', require: 'view_component/engine'`. For the majority of cases, it may also be ideal to set `require` to `false`.

### Did you try upgrading rubygems & bundler?

Yes.

**Comment by rmacklin** [comment]
> For example, when adding `view_component` to a project, it's best to declare it in the Gemfile as `gem 'view_component', require: 'view_component/engine'`

Just for posterity in case anyone lands on this issue, the above is no longer true since https://github.com/github/view_component/pull/1117
