### ISSUE TITLE
Bundler incorrectly sets MANPATH when a gem contains a man/ directory

### ISSUE THREAD

**Issue by postmodern** [rubygems/rubygems#5038]
I noticed that when I had the [kramdown](https://github.com/gettalong/kramdown) gem in my `Gemfile`, `man` commands would mysteriously not be able to find system man pages (ex: `system("man ls")` or `IO.popen("man ls")`). 

## Steps To Reproduce

Control to make sure there's a man page for the `ls` command:

```shell
$ man ls
```

Without Bundler or kramdown (note: `command` bypasses any shell aliases):

```shell
$ command ruby -e 'system("man ls")'
```

With Bundler and kramdown loaded:

```shell
$ bundle exec ruby -e 'system("man ls")'
```

### Gemfile:

```ruby
source 'https://rubygems.org/'

gem 'kramdown', '2.3.1'
```

## Actual Output

Without Bundler or kramdown:

```
*opens the man page for ls*
```

With Bundler and kramdown loaded:

```
No manual entry for ls
```

## Expected Output

The commands should display the man page for `ls`.

## Versions

* ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
* rubygems 3.2.22
* Bundler version 2.2.24

Reproducible on ruby 2.x as well.

## Additional Information

On a hunch, I decided to test whether `$MANPATH` was being overrode:

```shell
$ command ruby -e 'system("echo $MANPATH")'

$ bundle exec ruby -e 'system("echo $MANPATH")'
/home/postmodern/test/ruby/bundler/vendor/bundle/ruby/3.0.0/gems/kramdown-2.3.1/man
```

It appears that because the kramdown gem contains a top-level `man/` directory, bundler is adding the directory to `MANPATH`. Since `MANPATH` is not set, this actually overrides the `MANPATH` causing the `man` command to not search `/usr/share/man` or `/usr/local/share/man`, thus preventing any Ruby code from opening or reading man pages installed on the system.

**Comment by deivid-rodriguez** [comment]
Nice catch, #5039 should fix this!
