### ISSUE TITLE
TestGemRemoteFetcher test failures testing against OpenSSL 3.x

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#5046]
Trying to backport ruby/openssl/pull/399 for Ruby 3.0.2, I am facing the following test failures (initially noted as part of #4986):

~~~
$ ./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems ./test/runner.rb test/rubygems/test_gem_remote_fetcher.rb 
Run options: 
  --seed=65177

# Running tests:

[ 4/61] TestGemRemoteFetcher#test_do_not_allow_invalid_client_cert_auth_connection = 0.13 s         
  1) Failure:
TestGemRemoteFetcher#test_do_not_allow_invalid_client_cert_auth_connection [/builddir/build/BUILD/ruby-3.0.2/test/rubygems/test_gem_remote_fetcher.rb:954]:
[Gem::RemoteFetcher::FetchError] exception expected, not #<OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key>.

[58/61] TestGemRemoteFetcher#test_ssl_client_cert_auth_connection = 0.13 s                           
  2) Error:
TestGemRemoteFetcher#test_ssl_client_cert_auth_connection:
OpenSSL::PKey::RSAError: Neither PUB key nor PRIV key
    /builddir/build/BUILD/ruby-3.0.2/.ext/common/openssl/pkey.rb:318:in `initialize'
    /builddir/build/BUILD/ruby-3.0.2/.ext/common/openssl/pkey.rb:318:in `new'
    /builddir/build/BUILD/ruby-3.0.2/.ext/common/openssl/pkey.rb:318:in `new'
    /builddir/build/BUILD/ruby-3.0.2/lib/rubygems/request.rb:57:in `configure_connection_for_https'
    /builddir/build/BUILD/ruby-3.0.2/lib/rubygems/request/https_pool.rb:6:in `setup_connection'
    /builddir/build/BUILD/ruby-3.0.2/lib/rubygems/request/http_pool.rb:39:in `make_connection'
    /builddir/build/BUILD/ruby-3.0.2/lib/rubygems/request/http_pool.rb:20:in `checkout'
    /builddir/build/BUILD/ruby-3.0.2/lib/rubygems/request.rb:127:in `connection_for'
    /builddir/build/BUILD/ruby-3.0.2/lib/rubygems/request.rb:186:in `perform_request'
    /builddir/build/BUILD/ruby-3.0.2/lib/rubygems/request.rb:152:in `fetch'
    /builddir/build/BUILD/ruby-3.0.2/lib/rubygems/remote_fetcher.rb:316:in `request'
    /builddir/build/BUILD/ruby-3.0.2/lib/rubygems/remote_fetcher.rb:216:in `fetch_http'
    /builddir/build/BUILD/ruby-3.0.2/lib/rubygems/remote_fetcher.rb:255:in `fetch_path'
    /builddir/build/BUILD/ruby-3.0.2/test/rubygems/test_gem_remote_fetcher.rb:939:in `block in test_ssl_client_cert_auth_connection'
    /builddir/build/BUILD/ruby-3.0.2/test/rubygems/test_gem_remote_fetcher.rb:1011:in `with_configured_fetcher'
    /builddir/build/BUILD/ruby-3.0.2/test/rubygems/test_gem_remote_fetcher.rb:936:in `test_ssl_client_cert_auth_connection'

Finished tests in 1.790847s, 34.0621 tests/s, 169.7521 assertions/s.                 
61 tests, 304 assertions, 1 failures, 1 errors, 0 skips

ruby -v: ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux]
~~~

It seems the reason for this failure is that the key as well as certificate are stored in single file. I can fix the issue by this naive workaround:

~~~
diff --git a/lib/rubygems/request.rb b/lib/rubygems/request.rb
index d6100c914b..6643ef9c43 100644
--- a/lib/rubygems/request.rb
+++ b/lib/rubygems/request.rb
@@ -1,6 +1,6 @@
 # frozen_string_literal: true
 require 'net/http'
-require_relative 'user_interaction'
+require 'rubygems/user_interaction'
 
 class Gem::Request
   extend Gem::UserInteraction
@@ -53,8 +53,8 @@ def self.configure_connection_for_https(connection, cert_files)
 
     if Gem.configuration.ssl_client_cert
       pem = File.read Gem.configuration.ssl_client_cert
-      connection.cert = OpenSSL::X509::Certificate.new pem
-      connection.key = OpenSSL::PKey::RSA.new pem
+      connection.cert = OpenSSL::X509::Certificate.new pem[/.*-----END CERTIFICATE-----/m]
+      connection.key = OpenSSL::PKey::RSA.new pem[/-----BEGIN RSA PRIVATE KEY-----.*/m]
     end
 
     store.set_default_paths
~~~

Of course this might be issue on my side, doing mistake in the backport, or it might be issue of the ruby/openssl/pull/399. Nevertheless, I wonder what is the reason to have the key and cert in single file? I was looking at history but from the fb65080c28b2ea is not clear what was the design choice. @kenoir any comment please?

**Comment by deivid-rodriguez** [comment]
I have no idea either, but not sure it's worth changing now. I guess this used some hidden feature of openssl that has now been removed. If this is the case, your workaround seems fine.

**Comment by voxik** [comment]
I am afraid that my workaround won't be flexible enough to handle different formats of the file which could have been supported. But I dunno. Anyway, lets wait for @rhenium in the ruby/openssl/pull/399 and thx for the feedback :+1:

**Comment by voxik** [comment]
> I am afraid that my workaround won't be flexible enough to handle different formats of the file which could have been supported.

OTOH, there are no test cases for such "different formats", so they are not supported, right? :) But I guess that also different order of the certificate and key in the file would be originally supported by OpenSSL which are probably not supported now.

**Comment by rhenium** [comment]
`OpenSSL::PKey::RSA.new` should ignore any unknown PEM blocks contained in the string. The behavior is not specific to ruby/openssl, but can be seen in many applications using OpenSSL such as Apache.

It's an issue in https://github.com/ruby/openssl/pull/399. Apparently there was no test case for the behavior and I failed to catch it. I will fix it in the PR later. (Please note that the ruby/openssl PR is still unfinished at the moment.)

I think this issue on rubygems repo can be closed.

**Comment by deivid-rodriguez** [comment]
Great, thanks @rhenium!

**Comment by voxik** [comment]
> `OpenSSL::PKey::RSA.new` should ignore any unknown PEM blocks contained in the string. The behavior is not specific to ruby/openssl, but can be seen in many applications using OpenSSL such as Apache.

Thx for confirmation, I appreciate that!

> Please note that the ruby/openssl PR is still unfinished at the moment

I am aware of that, no worries.
