### ISSUE TITLE
`bundle lock --update` and  `bundle update` cannot be used to downgrade a dependency since 2.2.22

### ISSUE THREAD

**Issue by haines** [rubygems/rubygems#5066]
I want to change the version requirement in my gemfile to downgrade to a previous version. I don't want to change the versions of unrelated gems (so running `bundle update` to update everything is not an option).

In Bundler ≤2.2.21, I can do that by altering the requirement and running `bundle lock --update <gem name>` or `bundle update <gem name>`.

In Bundler ≥2.2.22, I get an error because the gem's dependencies are not downgraded to match.

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

gem "activerecord", ENV.fetch("ACTIVERECORD_VERSION")
```

### Commands to run

```console
$ ACTIVERECORD_VERSION="~> 6.1.0" bundle install
$ ACTIVERECORD_VERSION="~> 6.0.0" bundle lock --update activerecord
```

(alternatively run `bundle update` rather than `bundle lock --update` in the second command)

### Expected result (Bundler ≤2.2.21)

Gemfile.lock is updated with activerecord downgraded to version 6.0.4.1. For `bundle update` only,  Bundler prints a warning:

```
Note: activerecord version regressed from 6.1.4.1 to 6.0.4.1
```

### Actual result (Bundler ≥2.2.22)

Gemfile.lock is not updated, and Bundler fails with an error:

```
Bundler could not find compatible versions for gem "activesupport":
  In snapshot (Gemfile.lock):
    activesupport (>= 6.1.4.1)

  In Gemfile:
    activerecord (~> 6.0.0) was resolved to 6.0.1.rc1, which depends on
      activesupport (= 6.0.1.rc1)
```

Apart from the failure, it's also weird that it's saying that `~> 6.0.0` was resolved to `6.0.1.rc1` rather than `6.0.4.1` - as well as not being the latest version, I don't think that `6.0.1.rc1` should match the version requirement at all?

### Environment

```
Bundler       2.2.31
  Platforms   ruby, x86_64-darwin-20
Ruby          3.0.2p107 (2021-07-07 revision 0db68f023372b634603c74fca94588b457be084c) [x86_64-darwin20]
  Full Path   /Users/andrew/.rubies/ruby-3.0.2/bin/ruby
  Config Dir  /Users/andrew/.rubies/ruby-3.0.2/etc
RubyGems      3.2.31
  Gem Home    /Users/andrew/.gem/ruby/3.0.2
  Gem Path    /Users/andrew/.gem/ruby/3.0.2:/Users/andrew/.rubies/ruby-3.0.2/lib/ruby/gems/3.0.0
  User Home   /Users/andrew
  User Path   /Users/andrew/.gem/ruby/3.0.0
  Bin Dir     /Users/andrew/.gem/ruby/3.0.2/bin
Tools         
  Git         2.33.1
  RVM         not installed
  rbenv       not installed
  chruby      0.3.9
```

### Bundler Build Metadata

```
Built At          2021-11-08
Git SHA           2505ef8972
Released Version  true
```

**Comment by deivid-rodriguez** [comment]
#5078 should fix this!

**Comment by haines** [comment]
Thanks @deivid-rodriguez!

**Comment by deivid-rodriguez** [comment]
Thanks to you for the report!
