### ISSUE TITLE
gem update --system on JRuby wipes out entire lib/ruby/shared dir

### ISSUE THREAD

**Issue by headius** [rubygems/rubygems#507]
Here's a link to a repository that has only installed RubyGems 2.0 using update --system. You can see it ends up deleting files that have nothing to do with RubyGems.

https://github.com/jruby/jruby/compare/master...rubygems_202

Our shared dir is here: https://github.com/jruby/jruby/tree/master/lib/ruby/shared

We do specify some defaults here: https://github.com/jruby/jruby/blob/master/lib/ruby/shared/rubygems/defaults/jruby.rb

We override the default install location in that file, at this line: https://github.com/jruby/jruby/blob/master/lib/ruby/shared/rubygems/defaults/jruby.rb#L37

It seems like RG is clearing out the target directory completely before installing.

**Comment by jjgh** [comment]
Excuse me for asking here but what is the correct method of updating Rubygems in JRuby?
Is it  `jruby -S gem update --system` or 
```
jruby -S gem install pkg/rubygems-update-2.0.2.gem
jruby -S update_rubygems
```
I couldn't find it explicitely stated anywhere else..
