### ISSUE TITLE
Additional Slashes in paths breaks gem installation

### ISSUE THREAD

**Issue by dekz** [rubygems/rubygems#508]
When install an gem into `/a/b//c/gems` Gem complains and [fails this condition](https://github.com/rubygems/rubygems/blob/master/lib/rubygems/package.rb#L374) all is well if the path is changed to `/a/b/c/gems`. This is an annoyance when using tools like RVM which may have an entire environment setup with a double slashed path.

`destination` is correct `/a/b/c/gems` whereas `destination_dir` is `/a/b//c/gems`. As it seems ruby takes into account double slashed paths in either `File.join` or `File.expand_path`

**Comment by copiousfreetime** [comment]
This appears to be fixed with d3ac81a and 1.8.7 is no longer supported.
