### ISSUE TITLE
Difficulties to install due to malicious code gen[TRJ]  in / decidim-dev/lib/decidim/dev/assets/malicious.jpg

### ISSUE THREAD

**Issue by joax01** [rubygems/rubygems#5080]
2) There were an malicous file in you repo. 
https://github.com/decidim/decidim/find/develop
Plese check. I have the message from AVAST. 
I had to manually clone and download a copy without malicous code.
Your repo is infected. See message from Avast security attached. Malware 
gen[TRJ] in file: 
decidim / decidim-dev/lib/decidim/dev/assets/malicious.jpg

**Comment by deivid-rodriguez** [comment]
You didn't answer any of the questions. Please, edit the issue to answer the questions. It will take you some time and effort, but that's what we require in exchange for helping you. Thanks.

**Comment by joax01** [comment]
I have updated:

Which command did you run?
The Github Code button and then download as ZIP.
https://github.com/decidim/decidim
Please note: Avast needs to be installed in the computer used for download.
AVAST FREE ANTIVIRUS, Programversion:21.9.2494. Virusdefinition 211119-8 UI Version1.0.672

What were you expecting to happen?
Successfull download in web browser

What actually happened?
Download blocked by antivirusprogam.
Information message from AVAST Security : Infected file: Other:Malware-gen[]Trj]
The Infected file is:
decidim / decidim-dev/lib/decidim/dev/assets/malicious.jpg

**Comment by joax01** [comment]
I updated ..

Which command did you run?
gem install --user-install decidim

What were you expecting to happen?
gem installed

What actually happened?
Problem
ERROR: Error installing decidim:
The last version of pg (~> 1.1.4, < 2) to support your Ruby & RubyGems was 1.1.4. Try installing it with gem install pg -v 1.1.4 and then running the current command again
pg requires Ruby version >= 2.2, < 2.7.dev. The current ruby version is 2.7.4.191.

ERROR: Error installing decidim:
There are no versions of decidim-api (= 0.25.0) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for?
decidim-api requires Ruby version >= 2.7. The current ruby version is 2.6.8.205.
