### ISSUE TITLE
Download blocked by antivirusprogam

### ISSUE THREAD

**Issue by joax01** [rubygems/rubygems#5081]
### Which command did you run?

The Github Code button and then download as ZIP.
https://github.com/decidim/decidim
Please note: Avast needs to be installed in the computer used for download. 
AVAST FREE ANTIVIRUS, Programversion:21.9.2494. Virusdefinition 211119-8 UI Version1.0.672

### What were you expecting to happen?

Successfull download in web browser

### What actually happened?
Download blocked by antivirusprogam.
Information message from AVAST Security : Infected file: Other:Malware-gen[]Trj]
The Infected file is:
decidim / decidim-dev/lib/decidim/dev/assets/malicious.jpg

**Comment by deivid-rodriguez** [comment]
Ok, please report this to the decidim project: https://github.com/decidim/decidim. I has nothing to do with our project. Thanks!

**Comment by joax01** [comment]
OK, I updated:

Problem to install Decidem due to ruby dependency issue #8532
