### ISSUE TITLE
`find_spec_for_exe': can't find gem rms_web_service (>= 0.a) with executable rails (Gem::GemNotFoundException)

### ISSUE THREAD

**Issue by YanKyawMinSonicmoov** [rubygems/rubygems#5094]
I'm new to ruby and rvm version manager. I managed to install ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-darwin19.6.0]  from rvm.

- Bundler version 1.17.3
- gem version 3.0.9
- Rails 4.0.8

After bundle install, I run the `rails server ` cmd. I got the following error:
`
/Users/user/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems.rb:284:in `find_spec_for_exe': can't find gem rms_web_service (>= 0.a) with executable rails (Gem::GemNotFoundException)
        from /Users/user/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems.rb:303:in `activate_bin_path'
        from /Users/user/.rvm/gems/ruby-2.0.0-p353/bin/rails:23:in `<main>'
`

And then, when I run again bundle install or bundle, this error will show.
Here is the full trace:
`
$ echo $SHELL
/bin/zsh

$ rbenv versions
* system

$ rvm -v
rvm 1.29.12-next (master) by Michal Papis, Piotr Kuczynski, Wayne E. Seguin [https://rvm.io]

$ ruby -v
ruby 2.0.0p353 (2013-11-22 revision 43784) [x86_64-darwin19.6.0]

$ bundler --version
Bundler version 1.17.3

$ gem list rubygems-bundler
YAML safe loading is not available. Please upgrade psych to a version that supports safe loading (>= 2.0).

*** LOCAL GEMS ***

rubygems-bundler (1.4.5)

$ which ruby
/Users/user/.rvm/rubies/ruby-2.0.0-p353/bin/ruby

$ which bundler
/Users/user/.rvm/gems/ruby-2.0.0-p353/bin/bundler

$ gem env
YAML safe loading is not available. Please upgrade psych to a version that supports safe loading (>= 2.0).
RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.9
  - RUBY VERSION: 2.0.0 (2013-11-22 patchlevel 353) [x86_64-darwin19.6.0]
  - INSTALLATION DIRECTORY: /Users/user/.rvm/gems/ruby-2.0.0-p353
  - USER INSTALLATION DIRECTORY: /Users/user/.gem/ruby/2.0.0
  - RUBY EXECUTABLE: /Users/user/.rvm/rubies/ruby-2.0.0-p353/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /Users/user/.rvm/gems/ruby-2.0.0-p353/bin
  - SPEC CACHE DIRECTORY: /Users/user/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/user/.rvm/rubies/ruby-2.0.0-p353/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-darwin-19
  - GEM PATHS:
     - /Users/user/.rvm/gems/ruby-2.0.0-p353
     - /Users/user/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/gems/2.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/user/.rvm/gems/ruby-2.0.0-p353/bin
     - /Users/user/.rvm/gems/ruby-2.0.0-p353@global/bin
     - /Users/user/.rvm/rubies/ruby-2.0.0-p353/bin
     - /usr/local/sbin
     - /usr/local/opt/php@7.3/sbin
     - /usr/local/opt/php@7.3/bin
     - /Users/user/.pyenv/shims
     - /Users/user/.pyenv/bin
     - /opt/local/bin
     - /opt/local/sbin
     - /Users/user/.nodebrew/current/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Library/Apple/usr/bin
     - /Users/user/.rvm/gems/ruby-2.0.0-p353/bin
     - /Users/user/.rvm/gems/ruby-2.0.0-p353@global/bin
     - /Users/user/.rvm/rubies/ruby-2.0.0-p353/bin
     - /usr/local/sbin
     - /usr/local/opt/php@7.3/sbin
     - /usr/local/opt/php@7.3/bin
     - /Users/user/.pyenv/shims
     - /Users/user/.pyenv/bin
     - /opt/local/bin
     - /opt/local/sbin
     - /Users/user/.nodebrew/current/bin
     - /Applications/Visual Studio Code.app/Contents/Resources/app/bin
     - /Users/user/go/bin
     - /usr/local/opt/go/libexec/bin
     - /Users/user/.rvm/bin
     - /Applications/Visual Studio Code.app/Contents/Resources/app/bin
     - /Users/user/go/bin
     - /usr/local/opt/go/libexec/bin

$ gem list
YAML safe loading is not available. Please upgrade psych to a version that supports safe loading (>= 2.0).

*** LOCAL GEMS ***

actionmailer (4.0.8)
actionpack (4.0.8)
active_scaffold (3.5.5, 3.4.27)
activemodel (4.0.8)
activerecord (4.0.8)
activerecord-deprecated_finders (1.0.4)
activerecord-session_store (1.1.3, 0.1.1)
activesupport (4.0.8)
addressable (2.8.0)
airbrussh (1.4.0)
akami (1.3.1)
arel (4.0.2)
autoprefixer-rails (9.8.6, 6.3.7)
bcrypt (3.1.16, 3.1.10)
bigdecimal (default: 1.2.0)
bootstrap-sass (3.3.5)
builder (3.1.4)
bundler (1.17.3, default: 1.7.10)
capistrano (3.4.0)
capistrano-bundler (1.1.4)
capistrano-passenger (0.1.1)
capistrano-rails (1.1.3)
capistrano-rbenv (2.0.3)
coderay (1.1.0)
coffee-rails (4.0.1)
coffee-script (2.4.1)
coffee-script-source (1.9.1.1)
colorize (0.7.7)
concurrent-ruby (1.1.9)
coveralls (0.8.2)
debase (0.2.4.1, 0.2.1)
debase-ruby_core_source (0.10.13, 0.7.10)
devise (3.5.2)
diff-lcs (1.2.5)
docile (1.1.5)
domain_name (0.5.24)
double-bag-ftps (0.1.2)
erubis (2.7.0)
excon (0.45.4)
execjs (2.8.1, 2.6.0)
executable-hooks (1.6.1)
faraday (0.9.1)
ffi (1.12.2, 1.9.10, 1.9.6)
formatador (0.2.5)
gem-wrappers (1.4.0)
guard (2.13.0)
guard-compat (1.2.1)
guard-rspec (4.6.4)
gyoku (1.3.1)
hashie (3.4.2)
hike (1.2.3)
http-cookie (1.0.2)
httpclient (2.6.0.1)
httpi (2.4.1)
i18n (0.9.5, 0.7.0)
ice_nine (0.11.2)
image_size (1.4.1)
io-console (default: 0.4.2)
jbuilder (1.5.3)
jeff (1.5.1)
jquery-rails (3.1.4)
json (1.8.3, default: 1.7.7)
jwt (1.5.1)
libv8 (3.16.14.19)
listen (3.0.3)
lumberjack (1.0.9)
mail (2.5.5, 2.5.4)
method_source (0.8.2)
migration_comments (0.3.2)
mime-types (1.25.1)
mini_portile (0.6.2)
mini_portile2 (2.6.1, 2.1.0)
minitest (4.7.5, default: 4.3.2)
multi_json (1.15.0, 1.11.2)
multi_xml (0.5.5)
multipart-post (2.0.0)
nenv (0.2.0)
net-scp (3.0.0, 1.2.1)
net-ssh (4.2.0, 3.0.1)
netrc (0.10.3)
nokogiri (1.6.8.1, 1.6.6.2)
nori (2.6.0)
notiffany (0.0.8)
oauth2 (1.0.0)
omniauth (1.2.2)
omniauth-oauth2 (1.3.1)
omniauth-yconnect (0.0.4.1)
orm_adapter (0.5.0)
pg (0.18.3)
polyglot (0.3.5)
pry (0.10.1)
psych (default: 2.0.0)
public_suffix (2.0.5)
rack (1.5.5)
rack-test (0.6.3)
rails (4.0.8)
railties (4.0.8)
rake (10.5.0, 10.4.2, default: 0.9.6)
rb-fsevent (0.9.6)
rb-inotify (0.9.5)
rdoc (4.2.0, default: 4.0.0)
ref (2.0.0)
responders (1.1.2)
rest-client (1.8.0)
rms_web_service (0.1.5)
rspec (3.3.0)
rspec-core (3.3.2)
rspec-expectations (3.3.1)
rspec-mocks (3.3.2)
rspec-support (3.3.0)
ruby-debug-ide (0.6.0)
rubygems-bundler (1.4.5)
rubyzip (1.1.7)
rvm (1.11.3.9)
sass (3.2.19)
sass-rails (4.0.5)
savon (2.11.1)
sdoc (0.4.1)
shellany (0.0.1)
simplecov (0.10.0)
simplecov-html (0.10.0)
slop (3.6.0)
sprockets (2.12.5, 2.12.4)
sprockets-rails (2.3.3)
sshkit (1.21.2, 1.7.1)
term-ansicolor (1.3.2)
test-unit (default: 2.0.0.0)
therubyracer (0.12.3)
thor (1.1.0, 0.19.1)
thread_safe (0.3.6, 0.3.5)
tilt (1.4.1)
tins (1.6.0)
treetop (1.4.15)
tzinfo (0.3.60, 0.3.44)
uglifier (2.7.2)
unf (0.1.4)
unf_ext (0.0.7.1)
warden (1.2.3)
wasabi (3.5.0)

$ bundle install --without production
/Users/user/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems.rb:284:in `find_spec_for_exe': can't find gem rms_web_service (>= 0.a) with executable bundle (Gem::GemNotFoundException)
        from /Users/user/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems.rb:303:in `activate_bin_path'
        from /Users/user/.rvm/gems/ruby-2.0.0-p353/bin/bundle:23:in `<main>'

$ rails server
/Users/user/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems.rb:284:in `find_spec_for_exe': can't find gem rms_web_service (>= 0.a) with executable rails (Gem::GemNotFoundException)
        from /Users/user/.rvm/rubies/ruby-2.0.0-p353/lib/ruby/site_ruby/2.0.0/rubygems.rb:303:in `activate_bin_path'
        from /Users/user/.rvm/gems/ruby-2.0.0-p353/bin/rails:23:in `<main>'
`
How to fix this issue?

Note: I'm using MacOS Catelina v(10.15.7).

**Comment by deivid-rodriguez** [comment]
Hi @YanKyawMinSonicmoov, you're using very old versions of ruby, rubygems, and bundler. In particular, your ruby version is from 10 years ago! Make sure you upgrade the mentioned and if you are still having issues feel free to open a new issue. Thanks!

**Comment by YanKyawMinSonicmoov** [comment]
Right!
I got this project for maintenance. Can you help me something.

**Comment by deivid-rodriguez** [comment]
Sorry, we don't provide that kind of help here, good luck.
