### ISSUE TITLE
Add Rubygem version to Gemfile.lock

### ISSUE THREAD

**Issue by ngan** [rubygems/rubygems#5096]
### Describe the problem as clearly as you can

Currently, the version of Bundler you're using is set in `Gemfile.lock`. This is very useful as we use this to ensure all of our dev's environment auto-updates/installs that same version of Bundler. Ruby, of course, has the `ruby` directive in `Gemfile`.

The only thing that's missing is the Rubygems version (`gem --version`). There's nothing to keep track of this...and it's preferable for everyone to be on the same version.

**Comment by deivid-rodriguez** [comment]
Yeah, I understand this request and we want to eventually accomplish this by merging rubygems into bundler into the same piece of software, so that the "BUNDLED WITH" section alone will be enough. I'll close this since even if the issue will be fixed, we won't be taking the suggested path.

**Comment by ngan** [comment]
Hey @deivid-rodriguez sorry to resurrect such an old issue but I'd like to revisit this topic/request. I'm not sure what the status is with "merging rubygems into bundler into the same piece of software," but even while it's not merged, I think it's still valuable information to store in the lockfile. Bundler can even use it to warn people when they're using a rubygems version that doesn't match. Maybe not. But right now, there's no place to simply store this information so that other tooling can perhaps pick up the slack. Wdyt?

**Comment by simi** [comment]
@ngan how to handle the limitation of one RubyGems can be installed at the same time for given Ruby installation? There is no simple way (known to me) to switch RubyGems (other than globally reinstall using gem update --system x.y).

**Comment by ngan** [comment]
Yeah I get that. FWIW, I'm totally ok with not solving that problem now either. We don't even have to present a warning message or anything. All I'm looking forward is a record of what Rubygems version is used. I'd like to use this as a source of truth when setting up CI or the deployed docker image. Right now, we store it separately in `.config/rubygems/VERSION`.
