### ISSUE TITLE
Force use specific dependency (ignore some dependencies)

### ISSUE THREAD

**Issue by slayer** [rubygems/rubygems#5100]
Hi there.

We all know how `bundler` says on update:

```
Bundler could not find compatible versions for gem "xxxx":
  In snapshot (Gemfile.lock):
    xxxx (= 1.12.5)

  In Gemfile:
    xxxx (~> 1.12.5)

    yyyy (~> 0.3.1) was resolved to 0.3.1, which depends on
      xxxx (~> 1.10.3)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

Also we know, we can't force author of gem `yyyy` update dependencies.
Is there way to avoid a mess with gem forking to update just 1 line to make bundler happy?

I believe it will be great to have an option to force bundler ignore some dependencies.

**Comment by deivid-rodriguez** [comment]
There's https://github.com/rubygems/rubygems/pull/4178 that proposes something like that, and [a related rfc with discussion](https://github.com/rubygems/rfcs/pull/13). I'll close this to keep the discussion of the request and implementation at a single place. To sum up the situation, the current maintainers are not big fans of the feature, that doesn't mean it won't be added in the future, but it's not something planned at the moment.

Also, if you're just annoyed by bundler printing an error in this situation, note that bundler 2.2.32 should not longer error here. Instead, it should happily ignore the locked `xxx 1.12.5` version and pickup another version compatible with the `xxx (~> 1.10.3)` requirement, as per #5068.

**Comment by slayer** [comment]
Thanks, @deivid-rodriguez 

I believe many developers will be happy if the problem will get off the ground.


> Also, if you're just annoyed by bundler printing an error in this situation, note that bundler 2.2.32 should not longer error here. Instead, it should happily ignore the locked `xxx 1.12.5` version and pickup another version compatible with the `xxx (~> 1.10.3)` requirement, as per #5068.
My problem that is `xxx 1.10.3` has security vulnerabilities and `yyy` hold it to update. `yyy` hasn't been updated for a long time :(

**Comment by deivid-rodriguez** [comment]
Ok, I was suspecting you had the standard request regarding this issue ("I want to force a gem version without going through the fork, patch, point to git process"), but since you mentioned the specific error message, I thought it was worth mentioning that now bundler always finds a resolution.
