### ISSUE TITLE
NoMethodError: undefined method `metadata' for nil:NilClass since bundler 2.2.32

### ISSUE THREAD

**Issue by mtsmfm** [rubygems/rubygems#5113]
### Describe the problem as clearly as you can

```
gem "testgem", path: "."
```

with `bundle` command raises an error.
It seems it generates broken Gemfile.lock.

### Did you try upgrading rubygems & bundler?

I use the latest rubygems & bundler.
Bundler 2.2.31 doesn't reproduce this problem.

### Post steps to reproduce the problem

```
$ git clone https://gist.github.com/mtsmfm/28e60587643c8fad6031b01c98b0b8cb
$ cd 28e60587643c8fad6031b01c98b0b8cb
$ bundle
$ bundle
```

### What were you expecting to happen?

Both `bundle` finishes successfully

### What actually happened?

Error occurs.
https://gist.github.com/mtsmfm/28e60587643c8fad6031b01c98b0b8cb#file-log-txt

**Comment by deivid-rodriguez** [comment]
Since the version in your example is 0.0.0.dev, I think this might be the same as #5095. I'll get to this now.

**Comment by deivid-rodriguez** [comment]
https://github.com/rubygems/rubygems/pull/5116 should fix this!
