### ISSUE TITLE
<class:Wrapper>': uninitialized constant Gem (NameError)

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#5119]
I use this snippet [[1]] during build of Ruby for Fedora to check the version of bundled net-http-persistent. Unfortunately, testing Ruby 3.1.0, this is broken, very likely since #5112:

~~~
$ make runruby 'TESTRUN_SCRIPT=-e "   module Bundler; module Persistent; module Net; module HTTP;   end; end; end; end;   require '\''bundler/vendor/net-http-persistent/lib/net/http/persistent'\'';   puts Bundler::Persistent::Net::HTTP::Persistent::VERSION"'
./revision.h unchanged
RUBY_ON_BUG='gdb -x ./.gdbinit -p' ./miniruby -I./lib -I. -I.ext/common  ./tool/runruby.rb --extout=.ext  -- --disable-gems  -e "   module Bundler; module Persistent; module Net; module HTTP;   end; end; end; end;   require 'bundler/vendor/net-http-persistent/lib/net/http/persistent';   puts Bundler::Persistent::Net::HTTP::Persistent::VERSION" 
/builddir/build/BUILD/ruby-3.1.0-a84dc9d80d/lib/bundler/vendor/connection_pool/lib/connection_pool/wrapper.rb:35:in `<class:Wrapper>': uninitialized constant Gem (NameError)
	from /builddir/build/BUILD/ruby-3.1.0-a84dc9d80d/lib/bundler/vendor/connection_pool/lib/connection_pool/wrapper.rb:2:in `<class:ConnectionPool>'
	from /builddir/build/BUILD/ruby-3.1.0-a84dc9d80d/lib/bundler/vendor/connection_pool/lib/connection_pool/wrapper.rb:1:in `<top (required)>'
	from /builddir/build/BUILD/ruby-3.1.0-a84dc9d80d/lib/bundler/vendor/connection_pool/lib/connection_pool.rb:126:in `require_relative'
	from /builddir/build/BUILD/ruby-3.1.0-a84dc9d80d/lib/bundler/vendor/connection_pool/lib/connection_pool.rb:126:in `<top (required)>'
	from /builddir/build/BUILD/ruby-3.1.0-a84dc9d80d/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:4:in `require_relative'
	from /builddir/build/BUILD/ruby-3.1.0-a84dc9d80d/lib/bundler/vendor/net-http-persistent/lib/net/http/persistent.rb:4:in `<top (required)>'
	from -e:1:in `require'
	from -e:1:in `<main>'
make: *** [uncommon.mk:1248: runruby] Error 1
~~~

Generally, I believe that introducing RubyGems dependencies into any code is anti-pattern and should be prohibited at all cost.

[1]: https://src.fedoraproject.org/rpms/ruby/blob/d584a5bfb39b8c0aad7d644ac85d9e48e3bcc814/f/ruby.spec#_931

**Comment by deivid-rodriguez** [comment]
I wouldn't mind an explicit require of `rubygems` before using the `Gem` constant (although I don't mind if that's rejected either). Feel free to propose it upstream and we'll pick it up when we next synchronize with it. If that's not accepted, you'll have to drop the `--disable-gems` flag for this check.

Anyways, I'll close this because the change that was made seems fine to me.

**Comment by voxik** [comment]
Most of the Ruby code used to be spoiled by `requires 'rubygems'` at some point and there are still articles around explaining the reasons. The same applies for usage of `Gem` constant and similar.

While I am glad that RubyGems/Bundler are around, I'd also appreciated if there was alternative solutions. I quite dislike cementing the RubyGems/Bundler usage by means such as this. I don't want to imply this was done on purpose, but I'd like to point this out and I'd like this to be considered in the future. While I have considering to report this to connection_pool, I have reported this here first, because this is broader topic.

> you'll have to drop the --disable-gems flag for this check.

Please note that this is not me who is using `--disable-gems` flag, this is how the `runruby` helper is designed. But thanks for mentioning that, because adding `-rrubygems` should be probably better workaround then disabling the test case ;)

**Comment by deivid-rodriguez** [comment]
So your suggestion is that every code that needs to compare gem versions should implement gem version comparison from scratch so that it doesn't depend on rubygems?

**Comment by voxik** [comment]
1) As far as I can tell, it does not compare Gem versions but Ruby versions.
2) Maybe the version comparison should be generalized and provided by Ruby (StdLib), so even RubyGems can benefit, I don't know. Why should RubyGems provide functionality such as `::Gem.ruby_version` anyway?

**Comment by deivid-rodriguez** [comment]
> Please note that this is not me who is using --disable-gems flag, this is how the runruby helper is designed. But thanks for mentioning that, because adding -rrubygems should be probably better workaround then disabling the test case ;)

Yeah, or add `require "rubygems"` to the snippet inside `-e`.

**Comment by deivid-rodriguez** [comment]
> As far as I can tell, it does not compare Gem versions but Ruby versions.

It compares versions, in general, sometimes it will be the version of ruby, other times it can be the version of some particular gem. Either way, `rubygems` seems like the appropriate software to deal with this kind of thing.

> Maybe the version comparison should be generalized and provided by Ruby (StdLib), so even RubyGems can benefit, I don't know. Why should RubyGems provide functionality such as ::Gem.ruby_version anyway?

I disagree, rubygems feels a proper place to me to deal with versions. `Gem.ruby_version` is `RUBY_VERSION` as a `Gem::Version` instance. Anyways, it seems out of topic, I could've written `Gem::Version.new(RUBY_VERSION)` and you'd still be against, correct?
