### ISSUE TITLE
Can't uninstall default gem

### ISSUE THREAD

**Issue by jedrekdomanski** [rubygems/rubygems#5122]
I'm having a problem.

My current problem is

1. Can't uninstall default gem and there is no way to unset a gem as default so a default gem cannot be uninstalled
```
gem uninstall bundler 1.17.3
Gem '1.17.3' is not installed
ERROR:  While executing gem ... (Gem::InstallError)
    gem "bundler" cannot be uninstalled because it is a default gem
```
```
gem info bundler                    

*** LOCAL GEMS ***

bundler (2.2.32)
    Authors: André Arko, Samuel Giddins, Colby Swandale, Hiroshi
    Shibata, David Rodríguez, Grey Baker, Stephanie Morillo, Chris
    Morris, James Wen, Tim Moore, André Medeiros, Jessica Lynn Suttles,
    Terence Lee, Carl Lerche, Yehuda Katz
    Homepage: https://bundler.io
    License: MIT
    Installed at (default): /home/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0
```
This issue is related to:

  - [X] Installing a library
  - [X] The command line `gem`
Here are my current environment details:

```
$ gem env
gem env                                         
RubyGems Environment:
  - RUBYGEMS VERSION: 3.2.32
  - RUBY VERSION: 2.6.5 (2019-10-01 patchlevel 114) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/jedrek/.rvm/gems/ruby-2.6.5
  - USER INSTALLATION DIRECTORY: /home/jedrek/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /home/jedrek/.rvm/rubies/ruby-2.6.5/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /home/jedrek/.rvm/gems/ruby-2.6.5/bin
  - SPEC CACHE DIRECTORY: /home/jedrek/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /home/jedrek/.rvm/gems/ruby-2.6.5
     - /home/jedrek/.rvm/rubies/ruby-2.6.5/lib/ruby/gems/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/jedrek/.rvm/gems/ruby-2.6.5/bin
     - /home/jedrek/.rvm/gems/ruby-2.6.5@global/bin
     - /home/jedrek/.rvm/rubies/ruby-2.6.5/bin
     - /home/jedrek/.rvm/bin
     - /usr/local/kafka/kafka_2.13-2.8.0/bin
     - /usr/local/confluent/confluent-7.0.0/bin
     - /home/jedrek/.nvm/versions/node/v17.1.0/bin
     - /home/jedrek/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /snap/bin
```
gem --version
3.2.32
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Hello. Correct, this is intentional. Default gems are part of the ruby installation and cannot be uninstalled.

Why do you want to uninstall default gems, in any case?

**Comment by jedrekdomanski** [comment]
Why can I not uninstall a gem when it is set as default? I can uninstall a gem that is not default so why would I not be able to uninstall a gem that I marked as default?

**Comment by deivid-rodriguez** [comment]
The code of default gems is a core part of a ruby installation, and you're not expected to be able to remove it, just like you can't remove other features of ruby. For example, on a rbenv 3.0.3 installation of code, their code lives at `/Users/deivid/.rbenv/versions/3.0.3/lib/ruby/3.0.0`, not at `/Users/deivid/.rbenv/versions/3.0.3/lib/ruby/gems/3.0.0`. While rubygems owns the latter folder, rubygems should never change anything in the former folder, because that's just part of ruby. In other words, this functionality should always be available, no matter what.

If you consider that some functionality is not important enough to be forcefully available on any ruby, you're free to report this to ruby-core tracker and request that it's removed or moved to a standard gem that can be removed.

**Comment by deivid-rodriguez** [comment]
> I'm talking about the gems that I installed and marked as default not the standard gems.

Oh, ok, I see. That's our fault and it's basically the same as #5124. The `--default` flag is a historical flag that has never worked as expected and that we should remove. And that can cause trouble like the one you mentioned.
