### ISSUE TITLE
Installing bundler raises an error

### ISSUE THREAD

**Issue by jedrekdomanski** [rubygems/rubygems#5129]
I'm having a problem or would like to suggest a feature.

My current problem is
I install bundler and use it and I get an error:
```
gem install bundler -v bundler 2.2.30 --default
gem info bundler
*** LOCAL GEMS ***

bundler (2.2.30)
    Authors: André Arko, Samuel Giddins, Colby Swandale, Hiroshi
    Shibata, David Rodríguez, Grey Baker, Stephanie Morillo, Chris
    Morris, James Wen, Tim Moore, André Medeiros, Jessica Lynn Suttles,
    Terence Lee, Carl Lerche, Yehuda Katz
    Homepage: https://bundler.io
    License: MIT
    Installed at (default): /home/jedrek/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0

bundle install
Traceback (most recent call last):
	3: from /home/jedrek/.rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `<main>'
	2: from /home/jedrek/.rvm/gems/ruby-2.7.4/bin/ruby_executable_hooks:22:in `eval'
	1: from /home/jedrek/.rvm/gems/ruby-2.7.4/bin/bundle:23:in `<main>'
/home/jedrek/.rvm/gems/ruby-2.7.4/bin/bundle:23:in `load': cannot load such file -- /home/jedrek/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0/gems/bundler-2.2.30/exe/bundle (LoadError)
```

This issue is related to:

  - [ ] Installing a library

Here are my current environment details:

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.1.6
  - RUBY VERSION: 2.7.4 (2021-07-07 patchlevel 191) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/jedrek/.rvm/gems/ruby-2.7.4
  - USER INSTALLATION DIRECTORY: /home/jedrek/.gem/ruby/2.7.0
  - RUBY EXECUTABLE: /home/jedrek/.rvm/rubies/ruby-2.7.4/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /home/jedrek/.rvm/gems/ruby-2.7.4/bin
  - SPEC CACHE DIRECTORY: /home/jedrek/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86_64-linux
  - GEM PATHS:
     - /home/jedrek/.rvm/gems/ruby-2.7.4
     - /home/jedrek/.rvm/rubies/ruby-2.7.4/lib/ruby/gems/2.7.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/jedrek/.rvm/gems/ruby-2.7.4/bin
     - /home/jedrek/.rvm/gems/ruby-2.7.4@global/bin
     - /home/jedrek/.rvm/rubies/ruby-2.7.4/bin
     - /home/jedrek/.rvm/bin
     - /usr/local/confluent/confluent-7.0.0/bin
     - /home/jedrek/.nvm/versions/node/v17.1.0/bin
     - /home/jedrek/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /snap/bin
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Can you please upgrade rubygems first, and then try again? Also, can you uninstall the `ruby_executable_hooks` gem? I recall that gem giving trouble in the past. If you can still repro this after doing that, please reopen.

**Comment by jedrekdomanski** [comment]
Why do you close issues before they are resolved? Is that how your customer service looks? Just say "Don't bother me, goodbye!"?

**Comment by deivid-rodriguez** [comment]
I close issues that don't follow the issue template, which asks you to upgrade rubygems before reporting issues. I did try to help you anyways, though, why are you so aggressive?

**Comment by deivid-rodriguez** [comment]
The reason I close issues that are reported using old versions of our software is that many times have already been fixed. In your case, it might also be an issue in a different software than RubyGems. The fact that I close issues doesn't mean that I don't try to help people who report them.

**Comment by jedrekdomanski** [comment]
I'm not aggressive. Closing an issue before it is solved means you screw people who have issues using your software an that's how I felt. Anyway, upgrading rubygems helped. Thanks.

**Comment by deivid-rodriguez** [comment]
You were perceived by me as aggressive, and this was the second time you were perceived by me as unkind. So please try harder. And obviously I'm not screwing you when I helped you by telling you the solution to your problem (which was also written in the issue template that you didn't read or follow, by the way).

I won't continue discussing anything with you for now because you set me in a really bad mood. Please take this as a warning, I will apply our code of conduct as I see fit if you continue with the same attitude.
