### ISSUE TITLE
Bundle shebang config setting not honored

### ISSUE THREAD

**Issue by caramcc** [rubygems/rubygems#5132]
### Describe the problem as clearly as you can

The shebang at the beginning of gem bin files generated during `bundle install` does not use the configured value.

### Did you try upgrading rubygems & bundler?

Yes — however most of my testing occurred on bundler 2.20.0

### Post steps to reproduce the problem

For any ruby project with a Gemfile, using `vendor/bundle` as the bundle path:

```
$ rm -rf vendor/bundle
$ bundle configure --local shebang "/usr/bin/env my-arbitrary-ruby"
$ bundle config list
Settings are listed in order of priority. The top value will be used.
path
Set via BUNDLE_PATH: "vendor/bundle"

shebang
Set for your local app (my_project_path_here/.bundle/config): "/usr/bin/env my-arbitrary-ruby"

$ bundle install
$ head -n 7 vendor/bundle/ruby/2.6.0/bin/rails 
#!/usr/bin/env ruby
#
# This file was generated by RubyGems.
#
# The application 'railties' is installed as part of a gem, and
# this file is here to facilitate running it.
#
```

### Which command did you run?

I tried setting this via `bundle config --local shebang /usr/bin/env my-arbitrary-ruby`, via the env variable `BUNDLE_SHEBANG`, and via the deprecated `bundle install --shebang  "/usr/bin/env my-arbitrary-ruby"`

### What were you expecting to happen?

The shebang at the beginning of gem bin files should be `#!/usr/bin/env my-arbitrary-ruby`

### What actually happened?

The shebang used what appears to be some system-dependent default:

 * `#!/usr/bin/env ruby` on macos, both within and outside of a nix-shell, and within a nix-shell on an ubuntu 20.04 ec2 instance with no system ruby installed
 * `#!/usr/bin/env ruby2.6` in an ubuntu 20.04 docker container with system-wide ruby 2.6 (installed via the brightbox/ruby-ng ppa)

### If not included with the output of your command, run `bundle env` and paste the output below

Happy to provide this for any of the above configurations if it would be helpful!

**Comment by deivid-rodriguez** [comment]
Hi, maybe this needs clarification but the `shebang` setting is for bundler generated binstubs. These binstubs are generated by `bundle binstubs` and live inside your application, at `<app_rootr>/bin/rails`, for example.

To customize the shebang for the standard rubygems binstubs, I think you can use the `:custom_shebang` setting in your `~/.config/gem/gemrc` or `~/.gemrc` file.

**Comment by caramcc** [comment]
Ah, I understand, thank you for clarifying.

Is there any documentation on the `~/.gemrc` file and the available settings for it that you know of? I haven't had much luck searching for it, but it's possible I'm not looking in the right places.

**Comment by simi** [comment]
@caramcc something is at https://ruby-doc.org/stdlib-3.0.2/libdoc/rubygems/rdoc/Gem/ConfigFile.html

**Comment by deivid-rodriguez** [comment]
This is an area that definitely lacks documentation, I always look for available settings directly in the sources, which shows how bad our docs for this are. I think we could probably add a "Configuring rubygems" section at https://guides.rubygems.org?

**Comment by deivid-rodriguez** [comment]
@simi's link won't load for me (ruby-doc.org doesn't work very well), but this one works fine: https://rubyapi.org/3.0/o/gem/configfile. However, the `:custom_shebang` setting is not documented there either, so that's something else to improve.

**Comment by caramcc** [comment]
Great, that answers my questions — improved documentation would be useful, I'll check through the sources and the config file docs in the meantime. Thank you the help!
