### ISSUE TITLE
could not locate gem file

### ISSUE THREAD

**Issue by Pedagogia-Abdelmaleknezzal** [rubygems/rubygems#5149]
Hi, 

## Issue with Updating bundler

On MacBook Pro Montery M1 , version 12.01 
I wanted to update ruby gem ;
- mac@MacBook-Pro ~ % gem update --system
- Bundler 2.2.33 installed

When I wanted to update bundler
- mac@MacBook-Pro ~ % bundle update --bundler
I have this answer:
- Could not locate Gemfile

Thank you for any help.

**Comment by hsbt** [comment]
`gem update --system` also update `bundler`. `bundle update --bundler` is the different feature for updating bundler. 

see https://bundler.io/man/bundle-update.1.html
