### ISSUE TITLE
Errno::ENOENT: No such file or directory @ apply2files 

### ISSUE THREAD

**Issue by msuhovec** [rubygems/rubygems#5150]
CI test for this repo fail: https://github.com/ndlib/sipity

Example of failure. https://github.com/ndlib/sipity/actions/runs/1551270087

Ruby 2.6.6
Bundler 2.2.32

Errno::ENOENT: No such file or directory @ apply2files - /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/libv8-node-16.10.0.0-x86_64-linux/vendor/v8/x86_64-linux-musl/libv8/obj/libv8_monolith.a
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/fileutils.rb:1321:in `chmod'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/fileutils.rb:1321:in `chmod'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/fileutils.rb:997:in `block in chmod'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/fileutils.rb:996:in `each'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/fileutils.rb:996:in `chmod'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems/package.rb:410:in `block (3 levels) in extract_tar_gz'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems/package.rb:408:in `open'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems/package.rb:408:in `block (2 levels) in extract_tar_gz'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems/package/tar_reader.rb:65:in `each'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems/package.rb:389:in `block in extract_tar_gz'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems/package.rb:522:in `block in open_tar_gz'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems/package.rb:519:in `wrap'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems/package.rb:519:in `open_tar_gz'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems/package.rb:388:in `extract_tar_gz'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems/package.rb:368:in `block (2 levels) in extract_files'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems/package/tar_reader.rb:65:in `each'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems/package.rb:365:in `block in extract_files'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems/package/file_source.rb:30:in `open'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems/package/file_source.rb:30:in `with_read_io'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems/package.rb:362:in `extract_files'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/2.6.0/rubygems/installer.rb:851:in `extract_files'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.32/lib/bundler/rubygems_gem_installer.rb:26:in `install'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.32/lib/bundler/source/rubygems.rb:200:in `install'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.32/lib/bundler/installer/gem_installer.rb:54:in `install'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.32/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.32/lib/bundler/installer/parallel_installer.rb:186:in `do_install'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.32/lib/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.32/lib/bundler/worker.rb:62:in `apply_func'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.32/lib/bundler/worker.rb:57:in `block in process_queue'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.32/lib/bundler/worker.rb:54:in `loop'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.32/lib/bundler/worker.rb:54:in `process_queue'
  /opt/hostedtoolcache/Ruby/2.6.6/x64/lib/ruby/gems/2.6.0/gems/bundler-2.2.32/lib/bundler/worker.rb:91:in `block (2 levels) in create_threads'

**Comment by deivid-rodriguez** [comment]
Thanks for your report! Does it also happen with bundler 2.2.33? If it does, can you add a `gem update --system` before `bundle install` in your CI configuration to see if it also happens with the latest Rubygems version?

**Comment by deivid-rodriguez** [comment]
Hello! I managed to reproduce this and confirmed that upgrading rubygems fixes the issue. So make sure you add `gem update --system` to your CI configuration.

I bisected the fix to https://github.com/rubygems/rubygems/pull/2922, which was released with rubygems 3.1.0. So alternatively, you can upgrade ruby from 2.6 to 2.7 which should ship with a new enough rubygems version by default.

Let me know if you have any issues!

**Comment by msuhovec** [comment]
Thanks for the quick response,  investigation,  and solution David- I will
try applying this today.

Mark
