### ISSUE TITLE
Bundler cannot continue when installing Jekyll.

### ISSUE THREAD

**Issue by Nezzal** [rubygems/rubygems#5151]
Hi, 
I'm installing Jekyll with visual studio code in terminal on macbook pro with MacOs Montery version 12.0.1
# Jekyll Installation failed 
mac@MacBook-Pro myblog % bundle init
Writing new Gemfile to /Users/mac/Documents/repos/myblog/Gemfile
mac@MacBook-Pro myblog % bundle config set --local path 'vendor/bundle'
mac@MacBook-Pro myblog % bundle add jekyll
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using bundler 2.2.33
Fetching concurrent-ruby 1.1.9
Fetching eventmachine 1.2.7
Fetching http_parser.rb 0.8.0
Fetching ffi 1.15.4
Fetching forwardable-extended 2.6.0
Fetching rb-fsevent 0.11.0
Fetching public_suffix 4.0.6
Fetching colorator 1.1.0
Installing rb-fsevent 0.11.0
Fetching rexml 3.2.5
Installing eventmachine 1.2.7 with native extensions
Installing public_suffix 4.0.6
Fetching liquid 4.0.3
Installing colorator 1.1.0
Fetching mercenary 0.4.0
Installing forwardable-extended 2.6.0
Fetching rouge 3.26.1
Installing http_parser.rb 0.8.0 with native extensions
Installing concurrent-ruby 1.1.9
Installing mercenary 0.4.0
Fetching safe_yaml 1.0.5
Fetching unicode-display_width 1.8.0
Installing ffi 1.15.4 with native extensions
Installing rexml 3.2.5
Fetching addressable 2.8.0
Installing liquid 4.0.3
Fetching pathutil 0.16.2
Fetching i18n 1.8.11
Installing unicode-display_width 1.8.0
mac@MacBook-Pro myblog % bundle exec jekyll new --force --blank --skip-bundle .
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Gem::GemNotFoundException: can't find gem bundler (= 2.2.33) with executable bundle
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/rubygems.rb:278:in `find_spec_for_exe'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/rubygems.rb:255:in `bin_path'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/rubygems_integration.rb:207:in `bin_path'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/shared_helpers.rb:290:in `set_bundle_variables'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/cli/exec.rb:20:in `run'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:479:in `exec'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:31:in `dispatch'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/cli.rb:25:in `start'
  /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/exe/bundle:49:in `block in <top (required)>'
  /opt/homebrew/lib/ruby/site_ruby/3.0.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/gems/3.0.0/gems/bundler-2.2.32/exe/bundle:37:in `<top (required)>'
  /Users/mac/.gem/ruby/3.0.0/bin/bundle:23:in `load'
  /Users/mac/.gem/ruby/3.0.0/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       2.2.33
  Platforms   ruby, arm64-darwin-21
Ruby          3.0.3p157 (2021-11-24 revision 3fb7d2cadc18472ec107b14234933b017a33c14d) [arm64-darwin21]
  Full Path   /opt/homebrew/opt/ruby/bin/ruby
  Config Dir  /opt/homebrew/Cellar/ruby/3.0.3/etc
RubyGems      3.2.33
  Gem Home    /opt/homebrew/lib/ruby/gems/3.0.0
  Gem Path    /Users/mac/.gem/ruby/3.0.0:/opt/homebrew/lib/ruby/gems/3.0.0:/opt/homebrew/Cellar/ruby/3.0.3/lib/ruby/gems/3.0.0
  User Home   /Users/mac
  User Path   /Users/mac/.gem/ruby/3.0.0
  Bin Dir     /opt/homebrew/lib/ruby/gems/3.0.0/bin
Tools         
  Git         2.30.1 (Apple Git-130)
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-12-07
Git SHA           9b5e2a350b
Released Version  true
```

## Bundler settings

```
path
  Set for your local app (/Users/mac/Documents/repos/myblog/.bundle/config): "vendor/bundle"
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

# gem "rails"

gem "jekyll", "~> 4.2"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    colorator (1.1.0)
    concurrent-ruby (1.1.9)
    em-websocket (0.5.3)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0)
    eventmachine (1.2.7)
    ffi (1.15.4)
    forwardable-extended (2.6.0)
    http_parser.rb (0.8.0)
    i18n (1.8.11)
      concurrent-ruby (~> 1.0)
    jekyll (4.2.1)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 1.0)
      jekyll-sass-converter (~> 2.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 2.3)
      kramdown-parser-gfm (~> 1.0)
      liquid (~> 4.0)
      mercenary (~> 0.4.0)
      pathutil (~> 0.9)
      rouge (~> 3.0)
      safe_yaml (~> 1.0)
      terminal-table (~> 2.0)
    jekyll-sass-converter (2.1.0)
      sassc (> 2.0.1, < 3.0)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    kramdown (2.3.1)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    liquid (4.0.3)
    listen (3.7.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    mercenary (0.4.0)
    pathutil (0.16.2)
      forwardable-extended (~> 2.6)
    public_suffix (4.0.6)
    rb-fsevent (0.11.0)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rexml (3.2.5)
    rouge (3.26.1)
    safe_yaml (1.0.5)
    sassc (2.4.0)
      ffi (~> 1.9)
    terminal-table (2.0.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    unicode-display_width (1.8.0)

PLATFORMS
  arm64-darwin-21

DEPENDENCIES
  jekyll (~> 4.2)

BUNDLED WITH
   2.2.33
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=can%27t+find+gem+bundler+%28%3D+2.2.33%29+with+executable+bundle&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.

# Can you help me Thanks :)

**Comment by deivid-rodriguez** [comment]
Thanks for your report. It seems like a problem related to Homebrew ruby, I will investigate.

**Comment by deivid-rodriguez** [comment]
In the mean time, you can try installing ruby through a more bulletproof method like [rbenv](https://github.com/rbenv/rbenv) + [ruby-build](https://github.com/rbenv/ruby-build).

**Comment by deivid-rodriguez** [comment]
Ok, I managed to reproduce this and think this is an issue in Homebrew's ruby formula. Will keep digging.

**Comment by deivid-rodriguez** [comment]
After a bit more investigation, I think this might actually be our fault and caused by #5044 😬. Will keep digging tomorrow.

**Comment by Nezzal** [comment]
Thank you for your efforts to solve this problem😀

Nezzal Abdelmalek

**Comment by Brin-o** [comment]
Hi, having a similar issue on an M1 mac. My ruby has also been installed through homebrew.

**Comment by deivid-rodriguez** [comment]
I'll try to release the fix soon, since it's affecting quite a few people.

**Comment by cramdoulfa** [comment]
I see this has been fixed (🙏 🙌 ) but I also still have the bug, when will be the next release?

**Comment by deivid-rodriguez** [comment]
I'm aiming at releasing this around Friday.

**Comment by koraktor** [comment]
Is there a quick workaround?

**Comment by deivid-rodriguez** [comment]
Downgrade to rubygems 3.2.31 (`gem update --system 3.2.31`), or wait a couple days.

**Comment by koraktor** [comment]
> Downgrade to rubygems 3.2.31 (`gem update --system 3.2.31`), or wait a couple days.

3.2.30 worked, 3.2.31 has the same problem.

**Comment by deivid-rodriguez** [comment]
Really? According to our changelog this bug was introduced with 3.2.32, so you left me superconfused 👀.

**Comment by koraktor** [comment]
Just double checked:
Updating from 3.2.30 to 3.2.31 reintroduces the bug for me.

**Comment by deivid-rodriguez** [comment]
Oh wow, I'll try to find some time to figure out what's going on here because I'm terribly puzzled now.

**Comment by deivid-rodriguez** [comment]
Thanks for letting me know!

**Comment by Pedagogia-Abdelmaleknezzal** [comment]
Hi Deivid Rodriguez, :)
### **I've uninstalled and reinstalled, updated all : ruby, bindle, binder, Jek### yll , Xcode, visual studio ...**
mac@MacBook-Pro ~ % git --version
git version 2.34.1
mac@MacBook-Pro ~ % ruby -v
ruby 3.0.3p157 (2021-11-24 revision 3fb7d2cadc) [arm64-darwin21]
mac@MacBook-Pro ~ % gem -v
3.2.33
mac@MacBook-Pro ~ % jekyll -v
jekyll 4.2.1

### **And THEN I installed Jekyll  on visual studio all is running well:**

mac@MacBook-Pro myblog-1 % bundle init
Writing new Gemfile to /Users/mac/Sites/Myrepos/myblog-1/Gemfile
mac@MacBook-Pro myblog-1 % bundle config set --local path 'vendor/bundle'
mac@MacBook-Pro myblog-1 % bundle add jekyll
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using bundler 2.2.33
Fetching concurrent-ruby 1.1.9
Fetching eventmachine 1.2.7
Fetching http_parser.rb 0.8.0
Fetching ffi 1.15.4
Fetching public_suffix 4.0.6
Fetching colorator 1.1.0
Fetching forwardable-extended 2.6.0
Fetching rb-fsevent 0.11.0
Installing public_suffix 4.0.6
Installing http_parser.rb 0.8.0 with native extensions
Installing rb-fsevent 0.11.0
Fetching rexml 3.2.5
Fetching liquid 4.0.3
Installing eventmachine 1.2.7 with native extensions
Installing colorator 1.1.0
Installing forwardable-extended 2.6.0
Fetching mercenary 0.4.0
Fetching rouge 3.27.0
Installing concurrent-ruby 1.1.9
Installing mercenary 0.4.0
Installing liquid 4.0.3
Installing rexml 3.2.5
Fetching safe_yaml 1.0.5
Fetching unicode-display_width 1.8.0
Fetching addressable 2.8.0
Fetching pathutil 0.16.2
Installing safe_yaml 1.0.5
Installing unicode-display_width 1.8.0
Fetching kramdown 2.3.1
Fetching i18n 1.8.11
Installing addressable 2.8.0
Installing rouge 3.27.0
Fetching terminal-table 2.0.0
Installing i18n 1.8.11
Installing terminal-table 2.0.0
Installing kramdown 2.3.1
Fetching kramdown-parser-gfm 1.1.0
Installing kramdown-parser-gfm 1.1.0
Installing pathutil 0.16.2
Installing ffi 1.15.4 with native extensions
Fetching sassc 2.4.0
Fetching rb-inotify 0.10.1
Installing rb-inotify 0.10.1
Fetching listen 3.7.0
Installing sassc 2.4.0 with native extensions
Installing listen 3.7.0
Fetching jekyll-watch 2.2.1
Installing jekyll-watch 2.2.1
Fetching em-websocket 0.5.3
Installing em-websocket 0.5.3
Fetching jekyll-sass-converter 2.1.0
Installing jekyll-sass-converter 2.1.0
Fetching jekyll 4.2.1
Installing jekyll 4.2.1
mac@MacBook-Pro myblog-1 % bundle exec jekyll new --force --blank --skip-bundle .
New jekyll site installed in /Users/mac/Sites/Myrepos/myblog-1. 
Bundle install skipped. 
mac@MacBook-Pro myblog-1 % bundle install
Using public_suffix 4.0.6
Using addressable 2.8.0
Using bundler 2.2.33
Using colorator 1.1.0
Using concurrent-ruby 1.1.9
Using eventmachine 1.2.7
Using http_parser.rb 0.8.0
Using em-websocket 0.5.3
Using ffi 1.15.4
Using forwardable-extended 2.6.0
Using i18n 1.8.11
Using sassc 2.4.0
Using jekyll-sass-converter 2.1.0
Using rb-fsevent 0.11.0
Using rb-inotify 0.10.1
Using listen 3.7.0
Using jekyll-watch 2.2.1
Using rexml 3.2.5
Using kramdown 2.3.1
Using kramdown-parser-gfm 1.1.0
Using liquid 4.0.3
Using mercenary 0.4.0
Using pathutil 0.16.2
Using rouge 3.27.0
Using safe_yaml 1.0.5
Using unicode-display_width 1.8.0
Using terminal-table 2.0.0
Using jekyll 4.2.1
Bundle complete! 1 Gemfile dependency, 28 gems now installed.
Bundled gems are installed into `./vendor/bundle`
mac@MacBook-Pro myblog-1 % bundle update
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Using bundler 2.2.33
Using colorator 1.1.0
Using rexml 3.2.5
Using liquid 4.0.3
Using mercenary 0.4.0
Using rouge 3.27.0
Using safe_yaml 1.0.5
Using concurrent-ruby 1.1.9
Using eventmachine 1.2.7
Using ffi 1.15.4
Using forwardable-extended 2.6.0
Using http_parser.rb 0.8.0
Using rb-fsevent 0.11.0
Using public_suffix 4.0.6
Using em-websocket 0.5.3
Using i18n 1.8.11
Using unicode-display_width 1.8.0
Using rb-inotify 0.10.1
Using kramdown 2.3.1
Using terminal-table 2.0.0
Using pathutil 0.16.2
Using listen 3.7.0
Using kramdown-parser-gfm 1.1.0
Using addressable 2.8.0
Using sassc 2.4.0
Using jekyll-sass-converter 2.1.0
Using jekyll-watch 2.2.1
Using jekyll 4.2.1
Bundle updated!
mac@MacBook-Pro myblog-1 % bundle exec jekyll serve
Configuration file: /Users/mac/Sites/Myrepos/myblog-1/_config.yml
            Source: /Users/mac/Sites/Myrepos/myblog-1
       Destination: /Users/mac/Sites/Myrepos/myblog-1/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.029 seconds.
 Auto-regeneration: enabled for '/Users/mac/Sites/Myrepos/myblog-1'
                    ------------------------------------------------
      Jekyll 4.2.1   Please append `--trace` to the `serve` command 
                     for any additional information or backtrace. 
                    ------------------------------------------------
/Users/mac/Sites/Myrepos/myblog-1/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve/servlet.rb:3:in `require': cannot load such file -- webrick (LoadError)
        from /Users/mac/Sites/Myrepos/myblog-1/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve/servlet.rb:3:in `<top (required)>'
        from /Users/mac/Sites/Myrepos/myblog-1/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:179:in `require_relative'
        from /Users/mac/Sites/Myrepos/myblog-1/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:179:in `setup'
        from /Users/mac/Sites/Myrepos/myblog-1/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:100:in `process'
        from /Users/mac/Sites/Myrepos/myblog-1/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `block in process_with_graceful_fail'
        from /Users/mac/Sites/Myrepos/myblog-1/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `each'
        from /Users/mac/Sites/Myrepos/myblog-1/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/command.rb:91:in `process_with_graceful_fail'
        from /Users/mac/Sites/Myrepos/myblog-1/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/lib/jekyll/commands/serve.rb:86:in `block (2 levels) in init_with_program'
        from /Users/mac/Sites/Myrepos/myblog-1/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `block in execute'
        from /Users/mac/Sites/Myrepos/myblog-1/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `each'
        from /Users/mac/Sites/Myrepos/myblog-1/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/command.rb:221:in `execute'
        from /Users/mac/Sites/Myrepos/myblog-1/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary/program.rb:44:in `go'
        from /Users/mac/Sites/Myrepos/myblog-1/vendor/bundle/ruby/3.0.0/gems/mercenary-0.4.0/lib/mercenary.rb:21:in `program'
        from /Users/mac/Sites/Myrepos/myblog-1/vendor/bundle/ruby/3.0.0/gems/jekyll-4.2.1/exe/jekyll:15:in `<top (required)>'
        from /Users/mac/Sites/Myrepos/myblog-1/vendor/bundle/ruby/3.0.0/bin/jekyll:25:in `load'
        from /Users/mac/Sites/Myrepos/myblog-1/vendor/bundle/ruby/3.0.0/bin/jekyll:25:in `<top (required)>'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `load'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:58:in `kernel_load'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/cli/exec.rb:23:in `run'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/cli.rb:479:in `exec'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/cli.rb:31:in `dispatch'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/cli.rb:25:in `start'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/exe/bundle:49:in `block in <top (required)>'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
        from /opt/homebrew/lib/ruby/gems/3.0.0/gems/bundler-2.2.33/exe/bundle:37:in `<top (required)>'
        from /Users/mac/.gem/ruby/3.0.0/bin/bundle:23:in `load'
        from /Users/mac/.gem/ruby/3.0.0/bin/bundle:23:in `<main>'
mac@MacBook-Pro myblog-1 % bundle add webrick
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Using public_suffix 4.0.6
Using bundler 2.2.33
Using eventmachine 1.2.7
Using http_parser.rb 0.8.0
Using ffi 1.15.4
Using rexml 3.2.5
Using liquid 4.0.3
Using mercenary 0.4.0
Using rouge 3.27.0
Using safe_yaml 1.0.5
Using unicode-display_width 1.8.0
Fetching webrick 1.7.0
Using colorator 1.1.0
Using addressable 2.8.0
Using em-websocket 0.5.3
Using concurrent-ruby 1.1.9
Using rb-inotify 0.10.1
Using kramdown 2.3.1
Using forwardable-extended 2.6.0
Using rb-fsevent 0.11.0
Using sassc 2.4.0
Using i18n 1.8.11
Using listen 3.7.0
Using kramdown-parser-gfm 1.1.0
Using terminal-table 2.0.0
Using jekyll-sass-converter 2.1.0
Using pathutil 0.16.2
Using jekyll-watch 2.2.1
Using jekyll 4.2.1
Installing webrick 1.7.0
mac@MacBook-Pro myblog-1 % bundle exec jekyll serve
Configuration file: /Users/mac/Sites/Myrepos/myblog-1/_config.yml
            Source: /Users/mac/Sites/Myrepos/myblog-1
       Destination: /Users/mac/Sites/Myrepos/myblog-1/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
                    done in 0.016 seconds.
 Auto-regeneration: enabled for '/Users/mac/Sites/Myrepos/myblog-1'
    Server address: http://127.0.0.1:4000/
  Server running... press ctrl-c to stop.
^C%                                                                                                                                                         
mac@MacBook-Pro myblog-1 % 

### Thanks for all your efforts. 👍

**Comment by simi** [comment]
@Pedagogia-Abdelmaleknezzal see https://github.com/jekyll/jekyll/issues/8523 and https://github.com/jekyll/jekyll/pull/8524, but not released yet probably.
