### ISSUE TITLE
Rubygems v3.2.33 raise `Encoding::UndefinedConversionError` for sample project (v3.2.32 does not)

### ISSUE THREAD

**Issue by ShockwaveNN** [rubygems/rubygems#5160]
Steps to reproduce:
1. Create simple project with two files: `Gemfile` and `Dockerfile`

`Gemfile`:
```
# frozen_string_literal: true

Encoding.default_external = Encoding::UTF_8
Encoding.default_internal = Encoding::UTF_8

source 'https://rubygems.org'
gem 'rake'
```

`Dockerfile`:
```
FROM ruby:3.0
RUN gem update --system
ADD . /rubygems-issue
WORKDIR /rubygems-issue
RUN gem install bundler
RUN gem --version
RUN bundle --version
RUN bundler install

```

2. Run `docker build .`

With those sample project we got:
```
Step 6/8 : RUN gem --version
 ---> Running in 9854daeac931
3.2.33
Removing intermediate container 9854daeac931
 ---> ded8a59298f8
Step 7/8 : RUN bundle --version
 ---> Running in 416003ebc1dc
Bundler version 2.2.33
Removing intermediate container 416003ebc1dc
 ---> 3f7b310a09df
Step 8/8 : RUN bundler install
 ---> Running in 8b072eff9a29
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Fetching rake 13.0.6

Retrying download gem from https://rubygems.org/ due to error (2/4): Encoding::UndefinedConversionError "\x8B" from ASCII-8BIT to UTF-8 
----
Long metadata about sending issue to rubygems
----
```

But if I remove `gem update --system` from my dockerfile - everything is fine:
`Dockerfile`
```
FROM ruby:3.0
# RUN gem update --system
ADD . /rubygems-issue
WORKDIR /rubygems-issue
RUN gem install bundler
RUN gem --version
RUN bundle --version
RUN bundler install

```

Result is:
```
Step 5/7 : RUN gem --version
 ---> Running in 4acdf62c6073
3.2.32
Removing intermediate container 4acdf62c6073
 ---> cf6ab253f222
Step 6/7 : RUN bundle --version
 ---> Running in 168be20fdb56
Bundler version 2.2.33
Removing intermediate container 168be20fdb56
 ---> 30480942398a
Step 7/7 : RUN bundler install
 ---> Running in 2b48bdcb13b3
Fetching gem metadata from https://rubygems.org/.
Resolving dependencies...
Fetching rake 13.0.6
Installing rake 13.0.6
Using bundler 2.2.33
Bundle complete! 1 Gemfile dependency, 2 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is inst
Removing intermediate container 2b48bdcb13b3
 ---> fcad447e43c4
Successfully built fcad447e43c4
```

So judging by this I can assume that rubygems v2.2.33 broke something

Personally I don't remember why we've needed lines about encoding in my Gemfile, but we got and we got not troubles with it before

**Comment by deivid-rodriguez** [comment]
Thanks for reporting this @ShockwaveNN and sorry for the trouble. For a quick look, the culprit seems https://github.com/rubygems/rubygems/pull/4408/commits/a672e7555c1d04abfd07d896fcd90b147d4aa984. In that commit, while my intention was to use an exclusive lock when opening the file for writing, I unintentionally also started writing files binarily 😭.

**Comment by deivid-rodriguez** [comment]
I'll fix this.

**Comment by ShockwaveNN** [comment]
Oh, it's ok. Seems that removing `Encoding.default_external` fix that, and we found out that actually we do not need those lines

So it's about `reporting a bug`, not about `it's a trouble for me`

Thank you for your response )

**Comment by ShockwaveNN** [comment]
@deivid-rodriguez Maybe post some issue on ruby bug tracker? Because by context the are look like they should work similar

**Comment by deivid-rodriguez** [comment]
Yep, I was thinking of doing that 👍.

**Comment by deivid-rodriguez** [comment]
I reported it at https://bugs.ruby-lang.org/issues/18407.

**Comment by ShockwaveNN** [comment]
I think in any resolution of this bug new version of `rubgyems` with fix is required, am I right?

**Comment by deivid-rodriguez** [comment]
Sure, yes. I'm going to revert to the previous implementation of `Gem.write_binary`, specially since the regression test that I included with https://github.com/rubygems/rubygems/commit/a672e7555c1d04abfd07d896fcd90b147d4aa984 still passes without that part of that patch.

**Comment by deivid-rodriguez** [comment]
#5162 will fix this!
