### ISSUE TITLE
Installing msgpack, yajl-ruby, fluentd gems on Solaris 10 with error message: "ERROR: Failed to build gem native extension"

### ISSUE THREAD

**Issue by dmitriklein** [rubygems/rubygems#5206]
I'm having a problem or would like to suggest a feature.

My current problem is Installing msgpack, yajl-ruby, fluentd gems on Solaris 10 with error message: "ERROR: Failed to build gem native extension"_________

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x ] The command line `gem`
  - [x ] Other

Here are my current environment details:

```
$ gem env
# gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.0.14
  - RUBY VERSION: 2.0.0 (2014-11-13 patchlevel 598) [i386-solaris2.10]
  - INSTALLATION DIRECTORY: /opt/csw/lib/ruby/gems/2.0.0
  - RUBY EXECUTABLE: /opt/csw/bin/ruby2.0
  - EXECUTABLE DIRECTORY: /opt/csw/bin
  - RUBYGEMS PLATFORMS:
    - ruby
    - x86-solaris-2.10
  - GEM PATHS:
     - /opt/csw/lib/ruby/gems/2.0.0
     - /.gem/ruby/2.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
# 

```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

Log file:

# gem install msgpack-1.3.3.gem
Building native extensions.  This could take a while...
ERROR:  Error installing msgpack-1.3.3.gem:
        ERROR: Failed to build gem native extension.

    /opt/csw/bin/ruby2.0 extconf.rb
checking for ruby/st.h... yes
checking for st.h... yes
checking for rb_str_replace() in ruby.h... yes
checking for rb_intern_str() in ruby.h... yes
checking for rb_sym2str() in ruby.h... no
checking for rb_str_intern() in ruby.h... yes
checking for rb_block_lambda() in ruby.h... yes
checking for rb_hash_dup() in ruby.h... yes
checking for rb_hash_clear() in ruby.h... yes
creating Makefile

make "DESTDIR="
compiling buffer.c
cc: -W option with unknown program all
*** Error code 1
The following command caused the error:
/opt/SUNWspro/bin/cc -I. -I/opt/csw/include/ruby-2.0.0/i386-solaris2.10 -I/opt/csw/include/ruby-2.0.0/ruby/backward -I/opt/csw/include/ruby-2.0.0 -I. -DHAVE_RUBY_ST_H -DHAVE_ST_H -DHAVE_RB_STR_REPLACE -DHAVE_RB_INTERN_STR -DHAVE_RB_STR_INTERN -DHAVE_RB_BLOCK_LAMBDA -DHAVE_RB_HASH_DUP -DHAVE_RB_HASH_CLEAR -I/opt/csw/include -D_FILE_OFFSET_BITS=64  -KPIC -xO3 -xarch=pentium_pro -xchip=pentium_pro  -KPIC -I.. -Wall -O3 -g -std=gnu99 -m32 -o buffer.o -c buffer.c
make: Fatal error: Command failed for target `buffer.o'

Gem files will remain installed in /opt/csw/lib/ruby/gems/2.0.0/gems/msgpack-1.3.3 for inspection.
Results logged to /opt/csw/lib/ruby/gems/2.0.0/gems/msgpack-1.3.3/ext/msgpack/gem_make.out
# 

Debug Log file:
...
Exception `NoMethodError' at /opt/csw/lib/ruby/2.0.0/rubygems/package.rb:396 - undefined method `readpartial' for #<Gem::Package::TarReader::Entry:0x85fd8ec>
...
Exception `Errno::ENOENT' at /opt/csw/lib/ruby/2.0.0/fileutils.rb:1439 - No such file or directory - /opt/csw/lib/ruby/gems/2.0.0/gems/yajl-ruby-1.4.1/tasks/compile.rake
...

**Comment by deivid-rodriguez** [comment]
Hello @dmitriklein. I'm sorry but your Ruby and RubyGems versions are too old, we no longer support them. I'm not sure how you can install newer versions in Solaris, but that's what you'd need to do. You could try to compile ruby from source I guess.

**Comment by dmitriklein** [comment]
I have tried to install all available newer versions from source, and always had an error generated by make: 

"./include/ruby/internal/fl_type.h", line 205: Warning: Identifier expected instead of "}".
"internal.h", line 16: Error: #error not for C++.
*** Error code 2
The following command caused the error:
/opt/SUNWspro/bin/CC  -g   -DRUBY_EXPORT -I. -I.ext/include/i386-solaris2.10 -I./include -I. -I./enc/unicode/12.1.0 -D_XOPEN_SOURCE=500    -o vm.o -c vm.c
make: Fatal error: Command failed for target `vm.o'

**Comment by deivid-rodriguez** [comment]
You can try opening a ticket at bugs.ruby-lang.org to get some help.

**Comment by dmitriklein** [comment]
Thank you. Can you confirm the oldest supporting Ruby version for Solaris, please? Recommended one for fluentd (https://docs.fluentd.org/v/0.12/articles/install-by-gem) is >=1.9.3. And thus we use 2.0.0. 
# ruby --version
ruby 2.0.0p598 (2014-11-13 revision 48408) [i386-solaris2.10]
is it wrong?
Many thanks!

**Comment by indirect** [comment]
This is the RubyGems bug tracker, not the Ruby bug tracker. For information about supported Ruby versions, please see ruby-lang.org. If you have questions about Ruby supporting Solaris, we cannot answer them, and you should open a ticket at https://bugs.ruby-lang.org.
