### ISSUE TITLE
Bundle update a prerelease version without specifying a prerelease version in the Gemfile

### ISSUE THREAD

**Issue by siegfault** [rubygems/rubygems#5207]
### Describe the problem as clearly as you can

Hello all and happy holidays!

I've been digging a bit into the fact that `bundle update` doesn't support a `--pre` flag.

I've found multiple issues that are vaguely related, though they generally fall into two categories that aren't quite what I'm looking for:
* ones related to the `--pre` flag to the `gem` command: https://github.com/rubygems/bundler/issues/1198, https://github.com/rubygems/rubygems/issues/129, https://github.com/rubygems/rubygems/issues/3474
* ones related to specifying version in the gemfile: https://github.com/rubygems/bundler/issues/2938 & https://guides.rubygems.org/patterns/#prerelease-gems

I see the general sentiment is that if you pass `--pre` to `gem install`, you are taking matters into your own hands a bit. There doesn't seem to be a way to do so for a bundled gemfile though without specifying a version.

I'm most curious if there was a discussion/issue/rejected PR that I missed or if this is something y'all would be open to. If it is a feature that sounds appealing, I'd be happy to take a stab at it, but didn't want to dig in too far if the idea has already been discussed.

### Did you try upgrading rubygems & bundler?

Yes

### Post steps to reproduce the problem

Reproduction of `bundle update --pre gem_name` is easy since the flag isn't supported and thus errors, though I'm struggling to find a public gem that whose latest version is a pre-release gem that has non-pre-release versions as well. Then, I'd expect to be able to reproduce by running
```sh
$ bundle add gem_name
$ bundle update --pre gem_name
```
. If this more complete reproduction step is desired, I'm happy to dig in more next week!

### Which command did you run?

`$ bundle update --pre gem_name`

### What were you expecting to happen?

I expected bundler to update the version to the latest version, either only looking at pre-release versions or ignoring the release status of a version. I'm okay with either outcome, but let me know what y'all think it should behave like. The first would make it act more like the SEMVER flags, but the second is a bit more flexible and maybe more intuitive?

### What actually happened?

```sh
$ bundle update --pre gem_name
Unknown switches "--pre"
```

### If not included with the output of your command, run `bundle env` and paste the output below

<details><summary>Probably not super relevant, but details under the fold</summary>

## Environment

```
Bundler       2.3.1
  Platforms   ruby, x86_64-linux
Ruby          2.6.3p62 (2019-04-16 revision 67580) [x86_64-linux]
  Full Path   /home/siggy/.rbenv/versions/2.6.3/bin/ruby
  Config Dir  /home/siggy/.rbenv/versions/2.6.3/etc
RubyGems      3.3.1
  Gem Home    /home/siggy/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0
  Gem Path    /home/siggy/.gem/ruby/2.6.0:/home/siggy/.rbenv/versions/2.6.3/lib/ruby/gems/2.6.0
  User Home   /home/siggy
  User Path   /home/siggy/.gem/ruby/2.6.0
  Bin Dir     /home/siggy/.rbenv/versions/2.6.3/bin
Tools         
  Git         2.34.1
  RVM         not installed
  rbenv       rbenv 1.1.1
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-12-22
Git SHA           7b38ca2f84
Released Version  true
```

## Bundler settings

```
github.com
  Set for your local app (/home/siggy/.bundle/config): "siegfault:[REDACTED]"
  Set for the current user (/home/siggy/.bundle/config): "siegfault:[REDACTED]"
```
</details>

**Comment by deivid-rodriguez** [comment]
I like it and I think it could be useful to opt-in into some specific prerelease, without having to change the requirement in the`Gemfile` and thus opt in to prereleases "forever".
