### ISSUE TITLE
Install 'locked' bundler version messes up 'deployment' option

### ISSUE THREAD

**Issue by ivailop** [rubygems/rubygems#5215]
### Describe the problem as clearly as you can

Since the new bundler `2.3.x` been released we started getting a strange error when building our application's Dockerfile.

It appears that failure to install 'locked' bundler version messes up 'deployment' option - gems are being installed on a `global` vs `local` environment.

### Did you try upgrading rubygems & bundler?

Yes.

### Post steps to reproduce the problem

I guess the issue could be reproduced other ways but since we have seen in a Dockerfile, here is approximately what we do:
```
...
# Have user 'appuser' created 

# Set app home directory
WORKDIR $HOME/app

# update system gems (e.g. bundler)
RUN gem update --system

# do local deployment with a specific user
RUN setuser appuser bundle config set --local without 'development test'
RUN setuser appuser bundle config set --local deployment 'true'
RUN setuser appuser bundle check || setuser appuser bundle install
...
```

where, on `bundle install` there are errors:
* error installing locked bundler
```
Install missing gems with `bundle install`
Bundler 2.3.1 is running, but your lockfile was generated with 2.2.22. Installing Bundler 2.2.22 and restarting using that version.
There was an error installing the locked bundler version (2.2.22), rerun with the `--verbose` flag for more details. Going on using bundler 2.3.1.
```
* `Bundler::PermissionError` on some gems (but not all from the Gemfile.lock)
```
Bundler::PermissionError: There was an error while trying to create
`/usr/local/rvm/gems/ruby-2.7.5/gems/concurrent-ruby-1.1.9`. It is likely that
you need to grant executable permissions for all parent directories and write
permissions for `/usr/local/rvm/gems/ruby-2.7.5/gems`.
/usr/local/rvm/rubies/ruby-2.7.5/lib/ruby/site_ruby/2.7.0/bundler/shared_helpers.rb:105:in
`rescue in filesystem_access'
...
``` 

I guess, the first failure (i.e. on installing the locked bundler) messes up the `deployment` option and any subsequent gem install is done `globally` (see `/usr/local/rvm/gems/ruby-2.7.5/gems` in the error) instead of `locally` (i.e. `$HOME/app/vendor/bundle/ruby/2.7.0/gems`).

### Which command did you run?

See above.

### What were you expecting to happen?

App's gems installation to proceed `locally`.

### What actually happened?

Gems are installed `globally`.

### If not included with the output of your command, run `bundle env` and paste the output below

See above

**Comment by deivid-rodriguez** [comment]
Can you rerun with `--verbose` flag to see the underlying error? I wasn't expecting that error to affect the rest of the run 🤔.

Also, can you provide an exact `Dockerfile` that shows the problem?

**Comment by simi** [comment]
Can you install needed bundler first (the same way you install gem update --system)? `gem install bundler:2.2.22` You're missing this locked bundler installed and `setuser appuser bundle install` most likely has not permissions to write to gem folder.

**Comment by ivailop** [comment]
The Dockerfile is pretty much what I described above, basically:
```
FROM phusion/passenger-ruby27:latest AS base

# Set correct environment variables.
ENV HOME /root
ENV APP_HOME /home/app/testspace
ENV RAILS_ENV production

# Enable Nginx and Passenger
RUN rm -f /etc/service/nginx/down

# Remove the default site
RUN rm /etc/nginx/sites-enabled/default

RUN apt-get update -qq && apt-get install -y tzdata netcat

# Create app home
RUN mkdir $APP_HOME
WORKDIR $APP_HOME

# Add the project source code but respect .dockerignore
# which ignores the vendor/ directory, if present.
COPY testspace $APP_HOME
RUN chown -R app:app $APP_HOME

# update system gems (e.g. bundler)
RUN gem update --system

RUN setuser app bundle config set --local without 'development test'
RUN setuser app bundle config set --local deployment 'true'
RUN setuser app bundle check || setuser app bundle install --verbose

...
# the rest does no matter as the error occurs at the last command above
```

where:
*  `testspace` is our App
* `app` is the user created by the base image - see https://github.com/phusion/passenger-docker#app_user

Here is the bundle's verbose output:
[bundle-verbose-output.txt](https://github.com/rubygems/rubygems/files/7772433/bundle-verbose-output.txt)

Just to clarify, this all has been working for a very long time. We build an image every day. Without any changes (to the Gemfile.lock) on our side or the base image (i.e. passenger-ruby27), it has been failing for 3 days now - since the new bundler `2.3.x` was released.

**Comment by deivid-rodriguez** [comment]
I was able to repro now. I will push a fix.
