### ISSUE TITLE
`bundle install --local` tries to hit the network if locked bundler is not installed

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#5227]
### Describe the problem as clearly as you can

The `bundle install --local` command is supposed to never touch the network. However, we broke this assumption with the addition of the feature to auto installed the locked bundler version.

Currently bundler handles this in a decent manner by showing a warning like

> There was an error installing the locked bundler version (2.3.2), rerun with the `--verbose` flag for more details. Going on using bundler 2.4.0.dev.

and moving on.

However, since we know about this error, we should handle things fine and don't show the warning at all.

### Post steps to reproduce the problem

Disconnect your network and run `bundle install --local` on a Gemfile.lock with a locked bundler version not present in your system. See the above warning.

### Which command did you run?

`bundle install --local`.

### What were you expecting to happen?

No warning.

### What actually happened?

Warning.

**Comment by Satrio21** [comment]
Unknown switches "--local."
Did you mean?  "--local"

**Comment by simi** [comment]
@Satrio21 that's just typo in the issue description, the problem is indeed related to `--local`.
