### ISSUE TITLE
Gem install w/ native ext fails when install path contains spaces

### ISSUE THREAD

**Issue by mislav** [rubygems/rubygems#523]
```sh
export GEM_HOME="/tmp/has space"
export GEM_PATH="$GEM_HOME"
gem install bcrypt-ruby -v 3.0.1
#=> ERROR: Failed to build gem native extension.
```

Yes, the typical usage of GEM_HOME/GEM_PATH shouldn't include spaces, but this bug is especially harmful because it affects Bundler isolated installs as well. Therefore if someone has a project in a path containing spaces and uses `bundle install --path vendor/bundle`, they will have a bad time.

RubyGems 2.0.3, Ruby 2.0.0p0 on OS X

Related: #117, references sstephenson/rbenv#364

**Comment by djberg96** [comment]
Looks like it was fixed. Closing.
