### ISSUE TITLE
Some bundler specs are failing with `No such plugin: ruby` if `asdf` version manager is used

### ISSUE THREAD

**Issue by alexeevit** [rubygems/rubygems#5240]
### Describe the problem as clearly as you can

In specs, there are executions of bundle install with specific environment variables. Somehow, it writes `No such plugin: ruby` to the STDERR. However, if I run the same command manually in the terminal (I pause the spec to have the `bundle` binary), STDERR is empty.

### Did you try upgrading rubygems & bundler?

I use the master version

### Which command did you run?

`bin/rspec spec/install/gemspecs_spec.rb:11`

### What were you expecting to happen?

Successfully passed test

### What actually happened?

The test failed with the next error:
```
     Failure/Error: expect(err).to be_empty


       Commands:
       $ gem generate_index
       Generating Marshal quick index gemspecs for 48 gems
       ................................................
       Complete
       Generated Marshal quick index gemspecs: 0.007s
       Generating specs index
       Generated specs index: 0.000s
       Generating latest specs index
       Generated latest specs index: 0.000s
       Generating prerelease specs index
       Generated prerelease specs index: 0.000s
       Compressing indices
       Compressed indices: 0.000s
       # $? => 0

       $ /Users/vyacheslav/.asdf/installs/ruby/2.7.4/bin/ruby -I/Users/vyacheslav/dev/hobby/rubygems/bundler/spec -r/Users/vyacheslav/dev/hobby/rubygems/bundler/spec/support/artifice/fail.rb -r/Users/vyacheslav/dev/hobby/rubygems/bundler/spec/support/hax.rb /Users/vyacheslav/dev/hobby/rubygems/bundler/tmp/1/gems/system/bin/bundle install
       Fetching source index from file:///Users/vyacheslav/dev/hobby/rubygems/bundler/tmp/1/gems/remote2/
       Resolving dependencies...
       Using bundler 2.3.0.dev
       Fetching yaml_spec 1.0
       Installing yaml_spec 1.0
       Bundle complete! 1 Gemfile dependency, 2 gems now installed.
       Use `bundle info [gemname]` to see where a bundled gem is installed.
       No such plugin: ruby
       # $? => 0
       expected `"No such plugin: ruby".empty?` to be truthy, got false
     # ./spec/install/gemspecs_spec.rb:17:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:100:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:100:in `block (3 levels) in <top (required)>'
     # ./spec/support/helpers.rb:352:in `block in with_gem_path_as'
     # ./spec/support/helpers.rb:366:in `without_env_side_effects'
     # ./spec/support/helpers.rb:348:in `with_gem_path_as'
     # ./spec/spec_helper.rb:99:in `block (2 levels) in <top (required)>'
     # ./spec/support/rubygems_ext.rb:99:in `load'
     # ./spec/support/rubygems_ext.rb:99:in `gem_load_and_activate'
     # ./spec/support/rubygems_ext.rb:18:in `gem_load'
```

**Comment by deivid-rodriguez** [comment]
#5557 should fix this! @alexeevit Can you try it?

**Comment by alexeevit** [comment]
Sure, I'll check it soon. I stopped using asdf because of this error so I need to reproduce the environment :)

**Comment by deivid-rodriguez** [comment]
@alexeevit Any news? I think I will probably merge it since it's a test only change and it worked under my testing.

**Comment by alexeevit** [comment]
@deivid-rodriguez sorry for that, I checked, everything seems to be fine now. Thanks for your efforts!

**Comment by deivid-rodriguez** [comment]
@alexeevit Unfortunately I had to revert the fix because it broke some tests when ported to the ruby repo. I will keep this closed for now though because I'm unsure where the fix for this should be implemented, but I'll investigate anyways. By the way, I recommend to use asdf in combination with direnv with https://github.com/asdf-community/asdf-direnv. I doesn't use shims so it's not affected by this issue :)
