### ISSUE TITLE
[RFE] Do not ship `bin/{setup,console}` by default

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#5255]
Packaging Ruby 3.1, the linter on RPM package reports issues such as:

~~~
ruby-bundled-gems.x86_64: E: non-executable-script /usr/share/gems/gems/debug-1.4.0/bin/console 644 /usr/bin/env ruby
ruby-bundled-gems.x86_64: E: non-executable-script /usr/share/gems/gems/debug-1.4.0/bin/gentest 644 /usr/bin/env ruby
~~~

There were already multiple similar issues reported previously, such as:

https://github.com/ruby/power_assert/issues/35
https://github.com/ruby/rake/issues/385
https://github.com/ruby/rbs/issues/673

Part of the issue is also that Ruby's rbinstall does not respect the file permissions:

https://bugs.ruby-lang.org/issues/17840

This leads me to the `$SUBJECT`, which could be reworded as _"is it worth of shipping the `bin` directory"_, which is the least useful directory for gem runtime?

But checking the situation, e.g.:

https://github.com/ruby/debug/blob/97bf5a0704da9a015825909a7456cebfcbc782a2/debug.gemspec#L20-L24

https://github.com/ruby/net-ftp/blob/7dc2312860c80508ad2e74fe62c19c177862b5ac/net-ftp.gemspec#L27-L29

Maybe the original request could be extended, because I wonder if the whole concept of the listing files isn't bit obsolete? Shouldn't the file list be automatically populated by conventions, which were IMO established during the years? Or at minimum, shouldn't there be some helper method(s), which could be used to populate the file list without the cryptic RegExes?

**Comment by simi** [comment]
:thinking: What is RFE? For actual RFC you can open one at https://github.com/rubygems/rfcs.

**Comment by voxik** [comment]
> thinking What is RFE?

Request For Enhancement

**Comment by simi** [comment]
Is there any difference? This request fits our RFC repo IMHO.

**Comment by voxik** [comment]
@hsbt the #5259 is actually good start :+1:  thx!
