### ISSUE TITLE
`bundle platform` command is a bit confusing

### ISSUE THREAD

**Issue by ngan** [rubygems/rubygems#5264]
### Describe the problem as clearly as you can

When I run the `bundle platform` command, I get something like this:

```
Your platform is: arm64-darwin21

Your app has gems that work on these platforms:
* arm64-darwin-20
* arm64-darwin-21
* ruby
* x86_64-darwin-20
* x86_64-linux

Your Gemfile specifies a Ruby version requirement:
* ruby 2.7.5p203

Your current platform satisfies the Ruby version requirement.
```

As you can see my platform is `arm64-darwin21` but it's not actually one of the strings in the list. I can somewhat deduce that it's `arm64-darwin-21` but for someone who doesn't understand anything about how bundler handles platforms this can be a bit confusing. I was helping a coworker debug their environment and this came up. I thought I had made a mistake, but when I ran `bundle lock --add-platform arm64-darwin21`, nothing changed in the lockfile.

### Did you try upgrading rubygems & bundler?

I'm on the latest: Bundler version 2.3.4

### Which command did you run?

`bundle platform`

### What were you expecting to happen?

I would expect `Your platform is: arm64-darwin21` to be `Your platform is: arm64-darwin-21` to match the list of platforms.

**Comment by deivid-rodriguez** [comment]
Interesting. Yeah, definitely confusing, we should normalize this. Not sure where that deviation comes from, though.

**Comment by ngan** [comment]
@deivid-rodriguez do you know which format is the correct one? I can take a crack at this issue.

**Comment by deivid-rodriguez** [comment]
The deviation seems the following:

```
$ irb              
irb(main):001:0> Gem::Platform.local.to_s
=> "arm64-darwin-21"
irb(main):002:0> RUBY_PLATFORM
=> "arm64-darwin21"
```

We should use `Gem::Platform.local` for the current platform, since it's the format RubyGems and Bundler understand.
