### ISSUE TITLE
private registry credentials are written to the logs when `bundle install` fails due to `Bundler::PermissionError` error

### ISSUE THREAD

**Issue by samisalamiws** [rubygems/rubygems#5281]
### Describe the problem as clearly as you can

username and password of a private registry that was configured as an environment variable like `BUNDLE_GITHUB__COM` are visible when the `bundle install` command have errors:
```
Command result error lines for "bundle install":
Read error line #1: [DEPRECATED] Your Gemfile contains multiple primary sources. Using `source` more than once without a block is a security risk, and may result in installing unexpected gems. To resolve this warning, use a block to indicate which gems should come from the secondary source.
Read error line #2: Retrying download gem from https://sami:notmyrealpassword@example.com due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/local/ruby/2.7.5/lib/ruby/gems/2.7.0/cache/faraday-em_synchrony-1.0.0.gem`. It is likely that you need to grant write permissions for that path.
Read error line #3: Retrying download gem from https://sami:notmyrealpassword@example.com due to error (2/4): Bundler::PermissionError There was an error while trying to write to `/usr/local/ruby/2.7.5/lib/ruby/gems/2.7.0/cache/faraday-em_http-1.0.0.gem`. It is likely that you need to grant write permissions for that path.
```

### Did you try upgrading rubygems & bundler?

yes, using bundler 2.3.4 and ruby 2.7.5

### Post steps to reproduce the problem

install `bundler` with root permissions.
Configure environment variable for holding the credentials information, such that: `export BUNDLE_EXAMPLE__COM=username:password`
Then add a dependency to a private registry and include it in your Gemfile with multiple sources:
 ```
source 'https://rubygems.org'
source 'https://private.example.com'
gem 'private_gem', '~> 1.0.0'
```
run `bundle install` (not in root)

### Which command did you run?

`bundle install`

### What were you expecting to happen?

The logs will not present the real password

### What actually happened?

We can see the real password of the private registry login credentials printed on the logs.

**Comment by deivid-rodriguez** [comment]
Great, thanks!
