### ISSUE TITLE
bundler-2.3.5: undefined method `satisfied_by?' for nil:NilClass

### ISSUE THREAD

**Issue by Fryguy** [rubygems/rubygems#5290]
### Describe the problem as clearly as you can

On bundler 2.3.5, in my linux docker container, I see the following error report.  The Gemfile is below and as you can see it uses a single gem, from a third-party gem server.  I've been trying to dig in, and one of the dependencies (pdf-writer) seems to create this nil reference error.  I can't make this happen in my normal Mac environment though, so I don't really understand it beyond this.  There's a Dockerfile down beyond to make it simpler to recreate. If you need to me to try anything else, feel free to suggest things.

Might be related to #4877 

```
NoMethodError: undefined method `satisfied_by?' for nil:NilClass
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/lazy_specification.rb:95:in `block in __materialize__'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/lazy_specification.rb:92:in `select'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/lazy_specification.rb:92:in `__materialize__'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/spec_set.rb:75:in `block in materialize'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/spec_set.rb:72:in `map!'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/spec_set.rb:72:in `materialize'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/definition.rb:468:in `materialize'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/definition.rb:190:in `specs'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/installer.rb:243:in `ensure_specs_are_compatible!'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/installer.rb:83:in `block in run'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/process_lock.rb:12:in `block in lock'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/process_lock.rb:9:in `open'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/process_lock.rb:9:in `lock'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/installer.rb:71:in `run'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/installer.rb:23:in `install'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/cli/install.rb:62:in `run'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/cli.rb:255:in `block in install'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/settings.rb:131:in `temporary'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/cli.rb:254:in `install'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/cli.rb:31:in `dispatch'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/cli.rb:25:in `start'
  /usr/share/gems/gems/bundler-2.3.5/exe/bundle:48:in `block in <top (required)>'
  /usr/share/gems/gems/bundler-2.3.5/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /usr/share/gems/gems/bundler-2.3.5/exe/bundle:36:in `<top (required)>'
  /usr/bin/bundle:23:in `load'
  /usr/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       2.3.5
  Platforms   ruby, x86_64-linux
Ruby          2.7.4p191 (2021-07-07 revision a21a3b7d23704a01d34bd79d09dc37897e00922a) [x86_64-linux]
  Full Path   /usr/bin/ruby
  Config Dir  /etc
RubyGems      3.1.6
  Gem Home    /usr/share/gems
  Gem Path    /root/.gem/ruby:/usr/share/gems:/usr/local/share/gems
  User Home   /root
  User Path   /root/.gem/ruby
  Bin Dir     /usr/bin
OpenSSL
  Compiled    OpenSSL 1.1.1g FIPS  21 Apr 2020
  Loaded      OpenSSL 1.1.1k  FIPS 25 Mar 2021
  Cert File   /etc/pki/tls/cert.pem
  Cert Dir    /etc/pki/tls/certs
Tools
  Git         2.31.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-01-12
Git SHA           a13d015fcb
Released Version  true
```

### Gemfile

```ruby
source "https://rubygems.org"

gem "ruport", "=1.7.0.3", :source => "https://rubygems.manageiq.org"
```

### Gemfile.lock

```
<No /test/Gemfile.lock found>
```

### Did you try upgrading rubygems & bundler?

This uses the latest version of bundler 2.3.5, and rubygems 3.1.6.  I can't seem to update rubygems because `gem update --system` seems to just hang forever.

Note that bundler 2.3.4 works fine.

### Post steps to reproduce the problem

This Dockerfile is the simplest reproducer I could get.  It will fail on the `bundle install` line when you try to `docker build` it.  If you comment out that line, it will drop you into a bash prompt where you can type `bundle install` manually.  You can also change the version of bundler to 2.3.4 to see that it works correctly.

```dockerfile
FROM registry.access.redhat.com/ubi8/ubi:8.4

RUN dnf -y module enable ruby:2.7 && dnf -y install ruby-devel
RUN gem install bundler:2.3.5

WORKDIR "test"

RUN echo -e 'source "https://rubygems.org"\n\n\
gem "ruport", "=1.7.0.3", :source => "https://rubygems.manageiq.org"'\
> Gemfile

RUN bundle install

ENTRYPOINT ["/bin/bash"]
```

### Which command did you run?

`bundle install`

### What were you expecting to happen?

Not to blow up

### What actually happened?

It blew up

**Comment by deivid-rodriguez** [comment]
Thanks for the nice report, I'll have a look.

**Comment by Fryguy** [comment]
WOO! I got it to fail on my Mac too...problem was I had pdf-writer already installed locally.  Steps to reproduce locally are:

Using the Gemfile above

```sh
gem uninstall pdf-writer
bundle install
```

**Comment by Fryguy** [comment]
Interestingly, I can do `gem install ruport:1.7.0.3 --source https://rubygems.manageiq.org` just fine and that installs all of the expected gems.

**Comment by deivid-rodriguez** [comment]
Thanks for the extra information. This is a regression from https://github.com/rubygems/rubygems/commit/ab0a1c16c9e92e175e50e2e386105725a5c7cc87, which assumes that all specifications from the old index have non nil `required_rubygems_version`, which is not true. We already had the same regression in the past in rubygems (https://github.com/rubygems/rubygems/commit/64e7238431e58e47d8f04918467e5af3e70e77d4), but I forgot about it and regressed again in Bundler 😭.

I'll fix it!

**Comment by deivid-rodriguez** [comment]
#5291 should fix this. Thanks for your report, really helpful!

**Comment by deivid-rodriguez** [comment]
Thanks @hosamaly. Unfortunately without a way to reproduce it's hard for me to look into it. If you can provide me with some repro steps, even if they only fail 5% of the times, that's definitely a great start.

**Comment by ddufordithaka2** [comment]
I have stumbled across this error using Bundler 2.3.7, It does happen consistency for me and I am downgrading Bundler to get past it, but that is only a temporary fix.  Unfortunately I am not really able to give step to reproduce as of yet, but let me know any more information you would like and I will see what I can get.
`^^^^^^^^^^^^^^
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/lazy_specification.rb:95:in `block in __materialize__'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/lazy_specification.rb:92:in `select'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/lazy_specification.rb:92:in `__materialize__'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/spec_set.rb:75:in `block in materialize'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/spec_set.rb:72:in `map!'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/spec_set.rb:72:in `materialize'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/definition.rb:468:in `materialize'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/definition.rb:190:in `specs'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/installer.rb:243:in `ensure_specs_are_compatible!'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/installer.rb:83:in `block in run'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/process_lock.rb:12:in `block in lock'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/process_lock.rb:9:in `open'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/process_lock.rb:9:in `lock'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/installer.rb:71:in `run'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/installer.rb:23:in `install'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli/update.rb:78:in `run'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli.rb:303:in `block in update'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/settings.rb:131:in `temporary'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli.rb:302:in `update'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli.rb:31:in `dispatch'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/cli.rb:25:in `start'
  /usr/local/bundle/gems/bundler-2.3.7/exe/bundle:48:in `block in <top (required)>'
  /usr/local/bundle/gems/bundler-2.3.7/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /usr/local/bundle/gems/bundler-2.3.7/exe/bundle:36:in `<top (required)>'
  /usr/local/bundle/bin/bundle:25:in `load'
  /usr/local/bundle/bin/bundle:25:in `<main>'
```
## Environment
```
Bundler       2.3.7
  Platforms   ruby, x86_64-linux-musl
Ruby          3.1.1p18 (2022-02-18 revision 53f5fc[42](https://gitlab.com/capstan/platform-apps/qa-team/qa-gems/-/jobs/2184070435#L42)36a754ddf94b20dbb70ab63bd5109b18) [x86_64-linux-musl]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.3.7
  Gem Home    /usr/local/bundle
  Gem Path    /root/.gem/ruby/3.1.0:/usr/local/lib/ruby/gems/3.1.0:/usr/local/bundle
  User Home   /root
  User Path   /root/.gem/ruby/3.1.0
  Bin Dir     /usr/local/bundle/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1l  24 Aug 2021
  Loaded      OpenSSL 1.1.1l  24 Aug 2021
  Cert File   /etc/ssl1.1/cert.pem
  Cert Dir    /etc/ssl1.1/certs
Tools         
  Git         2.34.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```
## Bundler Build Metadata
```
Built At          2022-02-09
Git SHA           bafe[43](https://gitlab.com/capstan/platform-apps/qa-team/qa-gems/-/jobs/2184070435#L43)c[59](https://gitlab.com/capstan/platform-apps/qa-team/qa-gems/-/jobs/2184070435#L59)3
Released Version  true
```
## Bundler settings
```
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```
## Gemfile
### Gemfile
```ruby`

**Comment by deivid-rodriguez** [comment]
I see this is under an alpine docker image? I guess that should make it easier to reproduce. Can you try upgrading to bundler 2.3.9 just in case?

**Comment by ddufordithaka2** [comment]
Ok Bundler 2.3.9 does not seem to other a solution.

^^^^^^^^^^^^^^
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/lazy_specification.rb:95:in `block in __materialize__'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/lazy_specification.rb:92:in `select'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/lazy_specification.rb:92:in `__materialize__'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/spec_set.rb:75:in `block in materialize'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/spec_set.rb:72:in `map!'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/spec_set.rb:72:in `materialize'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/definition.rb:468:in `materialize'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/definition.rb:190:in `specs'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/installer.rb:243:in `ensure_specs_are_compatible!'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/installer.rb:83:in `block in run'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/process_lock.rb:12:in `block in lock'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/process_lock.rb:9:in `open'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/process_lock.rb:9:in `lock'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/installer.rb:71:in `run'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/installer.rb:23:in `install'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/cli/update.rb:78:in `run'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/cli.rb:303:in `block in update'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/settings.rb:131:in `temporary'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/cli.rb:302:in `update'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/cli.rb:31:in `dispatch'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/cli.rb:25:in `start'
  /usr/local/bundle/gems/bundler-2.3.9/exe/bundle:48:in `block in <top (required)>'
  /usr/local/bundle/gems/bundler-2.3.9/lib/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /usr/local/bundle/gems/bundler-2.3.9/exe/bundle:36:in `<top (required)>'
  /usr/local/bundle/bin/bundle:25:in `load'
  /usr/local/bundle/bin/bundle:25:in `<main>'
```
## Environment
```
Bundler       2.3.9
  Platforms   ruby, x86_64-linux-musl
Ruby          3.1.1p18 (2022-02-18 revision 53f5fc4236a754ddf94b20dbb70ab63bd[51](https://gitlab.com/capstan/platform-apps/qa-team/qa-gems/-/jobs/2184145253#L51)09b18) [x86_[64](https://gitlab.com/capstan/platform-apps/qa-team/qa-gems/-/jobs/2184145253#L64)-linux-musl]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.3.7
  Gem Home    /usr/local/bundle
  Gem Path    /root/.gem/ruby/3.1.0:/usr/local/lib/ruby/gems/3.1.0:/usr/local/bundle
  User Home   /root
  User Path   /root/.gem/ruby/3.1.0
  Bin Dir     /usr/local/bundle/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1l  24 Aug 2021
  Loaded      OpenSSL 1.1.1l  24 Aug 2021
  Cert File   /etc/ssl1.1/cert.pem
  Cert Dir    /etc/ssl1.1/certs
Tools         
  Git         2.34.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```
## Bundler Build Metadata
```
Built At          2022-03-09
Git SHA           7f90c00[83](https://gitlab.com/capstan/platform-apps/qa-team/qa-gems/-/jobs/2184145253#L83)a
Released Version  true
```
## Bundler settings
```
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```
## Gemfile
### Gemfile
```ruby

**Comment by deivid-rodriguez** [comment]
Ok, then as I replied to the previous person that run into this, I'd need a way to reproduce the issue in order to help. At least now we know that this is still happening with the latest Ruby, RubyGems and Bundler, which is something we didn't know before.

**Comment by hosamaly** [comment]
I noticed something that may be related: I got this error message before today's failure:
```
Retrying fetcher due to error (4/4): Bundler::HTTPError
  Could not fetch specs from https://repo.fury.io/<myrepo>/ due to underlying error
    <bad response Service Unavailable 503 (https://repo.fury.io/<myrepo>/specs.4.8.gz)>
```

**Comment by markusekblad** [comment]
Had this error trying to get an old React Native (0.63.3) project running and got past it (and onto other errors) simply by adding a
.ruby-version
file with 2.7.5 specified. Perhaps it'll help somebody. (Upgrading cocoapods in the gemfile fixed the next round of issues I had)
