### ISSUE TITLE
 recovery code use up

### ISSUE THREAD

**Issue by xiayuanquan** [rubygems/rubygems#5312]
I don't have my recovery code (use up), but I had enabled multiple authentication to log in. I can't log in now. How can I get my account back ? hurry up....

**Comment by xiayuanquan** [comment]
![image](https://user-images.githubusercontent.com/17963973/151133454-34adb2bf-cb2f-4a28-a0ca-b0f7c2dea135.png)

**Comment by hsbt** [comment]
@xiayuanquan Sorry, This repository is rubygems client code, not support site. So, we should discuss on https://github.com/rubygems/rubygems.org/issues/2939

**Comment by xiayuanquan** [comment]
> @xiayuanquan Sorry, This repository is rubygems client code, not support site. So, we should discuss on [rubygems/rubygems.org#2939](https://github.com/rubygems/rubygems.org/issues/2939)

so, I need how to do ?

**Comment by xiayuanquan** [comment]
> @xiayuanquan Sorry, This repository is rubygems client code, not support site. So, we should discuss on [rubygems/rubygems.org#2939](https://github.com/rubygems/rubygems.org/issues/2939)

ok, I reply with you on rubygems/rubygems.org#2939。
