### ISSUE TITLE
uninitialized constant Errno::ENOTSUP

### ISSUE THREAD

**Issue by sushilrai** [rubygems/rubygems#5323]
### Describe the problem as clearly as you can

Running rspec tests with jRUBY RVM and getting below error
/home/jenkins/.rvm/rubies/jruby-9.1.17.0/lib/ruby/stdlib/rubygems.rb:171: warning: toplevel constant Mutex referenced by Thread::Mutex

/home/jenkins/.rvm/rubies/jruby-9.1.17.0/lib/ruby/stdlib/rubygems/specification.rb:107: warning: toplevel constant Mutex referenced by Thread::Mutex

/home/jenkins/.rvm/rubies/jruby-9.1.17.0/lib/ruby/stdlib/rubygems/user_interaction.rb:546: warning: toplevel constant Mutex referenced by Thread::Mutex

/home/jenkins/.rvm/rubies/jruby-9.1.17.0/lib/ruby/stdlib/rubygems/defaults/jruby.rb:35: warning: constant Gem::ConfigMap is deprecated

/home/jenkins/.rvm/gems/jruby-9.1.17.0/gems/bundler-2.3.6/lib/bundler.rb:40: warning: toplevel constant Mutex referenced by Thread::Mutex

NameError: uninitialized constant Errno::ENOTSUP

Did you mean?  Errno::ENOTEMPTY

             const_missing at org/jruby/RubyModule.java:3370

         filesystem_access at /home/jenkins/.rvm/gems/jruby-9.1.17.0/gems/bundler-2.3.6/lib/bundler/shared_helpers.rb:103

                 read_file at /home/jenkins/.rvm/gems/jruby-9.1.17.0/gems/bundler-2.3.6/lib/bundler.rb:557

                 read_file at /home/jenkins/.rvm/gems/jruby-9.1.17.0/gems/bundler-2.3.6/lib/bundler/env.rb:64

                    report at /home/jenkins/.rvm/gems/jruby-9.1.17.0/gems/bundler-2.3.6/lib/bundler/env.rb:48

  request_issue_report_for at /home/jenkins/.rvm/gems/jruby-9.1.17.0/gems/bundler-2.3.6/lib/bundler/friendly_errors.rb:72

                 log_error at /home/jenkins/.rvm/gems/jruby-9.1.17.0/gems/bundler-2.3.6/lib/bundler/friendly_errors.rb:50

      with_friendly_errors at /home/jenkins/.rvm/gems/jruby-9.1.17.0/gems/bundler-2.3.6/lib/bundler/friendly_errors.rb:109

                    <main> at /home/jenkins/.rvm/gems/jruby-9.1.17.0/gems/bundler-2.3.6/exe/bundle:36

                      load at org/jruby/RubyKernel.java:974

                    <main> at /home/jenkins/.rvm/gems/jruby-9.1.17.0/bin/bundle:25

/home/jenkins/.rvm/rubies/jruby-9.1.17.0/lib/ruby/stdlib/rubygems.rb:171: warning: toplevel constant Mutex referenced by Thread::Mutex

### Which command did you run?

Running below snippet 
sh  '''#!/bin/bash --login
                   export BUNDLE_GEMFILE=${WORKSPACE}/Gemfile
                   export PATH=$PATH

                   rm -f Gemfile.lock

                   rvm use jruby-9.1.17.0 --install --binary --fuzzy
                   rvm gemset empty --force
                   gem update --system
                   gem install bundler
                   bundle install
                   bundle exec rake
              '''
Gemfile

source "https://rubygems.org"
gemspec

Gem::Specification.new do |s|
  s.name        = "internal-util"
 
  s.add_dependency "aescrypt"
  s.add_dependency "hashie"
  s.add_dependency "i18n"
  s.add_dependency "net-ssh"
  s.add_dependency "nokogiri"
  s.add_dependency "pry"
  s.add_dependency "rest-client"
  s.add_dependency "simplecov"
  s.add_dependency "trollop"

  s.add_development_dependency "coveralls" if Integer(RUBY_VERSION.split(".").first) > 1
  s.add_development_dependency "guard-shell"
  s.add_development_dependency "json_pure"
  s.add_development_dependency "kramdown"
  s.add_development_dependency "listen"
  s.add_development_dependency "logger-colors"
  s.add_development_dependency "mocha"
  s.add_development_dependency "puppet"
  s.add_development_dependency "puppetlabs_spec_helper", "0.4.1"
  s.add_development_dependency "rainbow"
  s.add_development_dependency "rake"
  s.add_development_dependency "rspec"
  s.add_development_dependency "rubocop", "0.65.0"
  s.add_development_dependency "yard"

  s.executables << "wsman_shell.rb"

  s.files        = Dir.glob("lib/**/*")
  s.require_path = "lib"
end

**Comment by deivid-rodriguez** [comment]
This is unfortunate. It seems like some incompatibility between JRuby 9.1 and the CRuby version it tracks (Ruby 2.3). We didn't detect this because we only test the latest JRuby. Since we run very few specs on JRuby at the moment, it wouldn't be too costly to run the same thing against the oldest JRuby supporting our older supported CRuby. I guess we should do something about this since we don't prevent installing bundler 2.3 on JRuby 9.1.

In any case, the easiest fix here on your side would be to upgrade JRuby or downgrade Bundler.
