### ISSUE TITLE
bundle install ignore config 'with' option

### ISSUE THREAD

**Issue by izenk** [rubygems/rubygems#5343]
### Describe the problem as clearly as you can

```
bundle --version
Bundler version 2.3.0
```

```
bundle config
Settings are listed in order of priority. The top value will be used.
app_config
Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"

jobs
Set for your local app (/usr/local/bundle/config): 3

path
Set for the current user (/home/app/.bundle/config): "vendor/bundle"

silence_root_warning
Set via BUNDLE_SILENCE_ROOT_WARNING: true

with
Set for your local app (/usr/local/bundle/config): [:production]
Set for the current user (/home/app/.bundle/config): [:production]
```

'bundle install' - installs all gems from Gemfile from all groups, ignoring 'with' setting.
If I set 'without' setting, e.g.
```
bundle config without development test
```
and then run bundle install - only gems from production group will be installed as expected

**Comment by deivid-rodriguez** [comment]
Hello @izenk. This might be surprising, but works as designed.

Bundler installs all groups, except for optional groups by default. Optional groups can be specified with the `:optional` parameter to the `group` DSL. For example,

```ruby
group :production, optional: true do
  # production gems
end
```

The `with` option makes Bundler also install selected optional groups, while the `without` option makes Bundler skip installing selected non optional groups.

Hopes this clarifies things!
