### ISSUE TITLE
Potentially cache `resolve`

### ISSUE THREAD

**Issue by ngan** [rubygems/rubygems#5345]
### Describe the problem as clearly as you can

I work in a very large monolith with many gems (about 292 direct dependencies and 587 gems). I've been tinkering around the idea of loading a subtree of those dependencies. As in, I'd like to load a handful of those direct dependencies and have bundler resolve whatever other indirect dependencies it needs. The only way I found to do this given what bundler has is using groups. But I don't want to pollute/manage a bunch of groups in my Gemfile so I'm doing it dynamically. So something like...

```ruby
require "bundler"
gems_i_need = %w(sidekiq foobar)
Bundler.definition.dependencies.each { |dep| dep.groups << :temporary if gems_i_need.include?(dep.name) }
Bundler.require(:temporary)
```
This works pretty well! Do please let me know if there's a blessed way to do this. Also think it'd be cool if Bundler provided something like this (or dynamic grouping) out of the box. But this isn't what this ticket is about...read on 😄 

The problem I realized is that the Bundler setup phase, consistently takes 2.5 seconds for us because of our large gem set. I've traced it down to the [`resolve` method](https://github.com/rubygems/rubygems/blob/master/bundler/lib/bundler/definition.rb#L257-L273). I get that this method is doing a lot of work but this method seems cacheable based on the digest of Gemfile and lockfile (and/or something else?).

If there's a potential here, I'd be happy to explore it with some guidance. Just wanted to start the discussion.

**Comment by deivid-rodriguez** [comment]
Closed by https://github.com/rubygems/rubygems/pull/5503.
