### ISSUE TITLE
Update TROUBLESHOOTING link to avoid 404

### ISSUE THREAD

**Issue by luilver** [rubygems/rubygems#5347]
### Describe the problem as clearly as you can

TROUBLESHOOTING link is getting a 404 page.

### Did you try upgrading rubygems & bundler?

N/A

### Post steps to reproduce the problem

Open a new issue -> Copy TROUBLESHOOTING link -> Paste it in a new tab -> Enjoy 404

### Which command did you run?
N/A

### What were you expecting to happen?

Getting this link instead: https://github.com/rubygems/rubygems/blob/master/bundler/doc/TROUBLESHOOTING.md

**Comment by simi** [comment]
@luilver Thanks for the report. Indeed nobody is enjoying 404s. Would you mind to contribute this change? If I understand it well this file should be changed.

https://github.com/rubygems/rubygems/blob/dac8c02b37ff077aa66ba0e218058146d02dfea5/.github/ISSUE_TEMPLATE/bundler-related-issue.md?plain=1#L18

**Comment by luilver** [comment]
Yes, you're right; I will make a PR with that. Thanks @simi.

**Comment by luilver** [comment]
It is done: https://github.com/rubygems/rubygems/pull/5348
