### ISSUE TITLE
Construction error reporting

### ISSUE THREAD

**Issue by zh1-hust** [rubygems/rubygems#5349]
(base) ➜  thrift-0.15.0 make
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
Making all in compiler/cpp
Making all in src
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
make[4]: Nothing to be done for `all-am'.
Making all in .
make[3]: Nothing to be done for `all-am'.
Making all in test
make[3]: Nothing to be done for `all'.
Making all in lib
Making all in json
make[4]: Nothing to be done for `all-am'.
Making all in xml
make[4]: Nothing to be done for `all-am'.
Making all in c_glib
Making all in .
make[4]: Nothing to be done for `all-am'.
Making all in test
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-recursive
make[6]: Nothing to be done for `all-am'.
Making all in py
/opt/miniconda3/bin/python setup.py build
running build
running build_py
running build_ext
/opt/miniconda3/bin/python setup.py build
running build
running build_py
running build_ext
/Users/zhang/workdir/multicodegenerate/thrift-0.15.0/compiler/cpp/thrift --gen py test/test_thrift_file/TestServer.thrift
Making all in rb
/usr/bin/bundle install
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/universal-darwin19/rbconfig.rb:229: warning: Insecure world writable dir /Users/zhang/workdir/java/mvnd-0.7.1-darwin-amd64 in PATH, mode 040777
NOTE: Gem::Specification#has_rdoc= is deprecated with no replacement. It will be removed in Rubygems 4
Gem::Specification#has_rdoc= called from /Users/zhang/workdir/multicodegenerate/thrift-0.15.0/lib/rb/thrift.gemspec:15.
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Errno::EROFS: Read-only file system @ rb_sysopen - /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0/bundler.lock
  /Library/Ruby/Site/2.6.0/bundler/process_lock.rb:9:in `initialize'
  /Library/Ruby/Site/2.6.0/bundler/process_lock.rb:9:in `open'
  /Library/Ruby/Site/2.6.0/bundler/process_lock.rb:9:in `lock'
  /Library/Ruby/Site/2.6.0/bundler/installer.rb:71:in `run'
  /Library/Ruby/Site/2.6.0/bundler/installer.rb:23:in `install'
  /Library/Ruby/Site/2.6.0/bundler/cli/install.rb:62:in `run'
  /Library/Ruby/Site/2.6.0/bundler/cli.rb:255:in `block in install'
  /Library/Ruby/Site/2.6.0/bundler/settings.rb:131:in `temporary'
  /Library/Ruby/Site/2.6.0/bundler/cli.rb:254:in `install'
  /Library/Ruby/Site/2.6.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Library/Ruby/Site/2.6.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Library/Ruby/Site/2.6.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Library/Ruby/Site/2.6.0/bundler/cli.rb:31:in `dispatch'
  /Library/Ruby/Site/2.6.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Library/Ruby/Site/2.6.0/bundler/cli.rb:25:in `start'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0/gems/bundler-2.3.6/exe/bundle:48:in `block in <top (required)>'
  /Library/Ruby/Site/2.6.0/bundler/friendly_errors.rb:103:in `with_friendly_errors'
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0/gems/bundler-2.3.6/exe/bundle:36:in `<top (required)>'
  /usr/bin/bundle:23:in `load'
  /usr/bin/bundle:23:in `<main>'
```

## Environment

```
Bundler       2.3.6
  Platforms   ruby, universal-darwin-19
Ruby          2.6.3p62 (2019-04-16 revision 67580) [universal-darwin-19]
  Full Path   /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
  Config Dir  /Library/Ruby/Site
RubyGems      3.3.6
  Gem Home    /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
  Gem Path    /Users/zhang/.gem/ruby/2.6.0:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
  User Home   /Users/zhang
  User Path   /Users/zhang/.gem/ruby/2.6.0
  Bin Dir     /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin
OpenSSL
  Compiled    LibreSSL 2.8.3
  Loaded      LibreSSL 2.8.3
  Cert File   /private/etc/ssl/cert.pem
  Cert Dir    /private/etc/ssl/certs
Tools
  Git         2.24.3 (Apple Git-128)
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

**Comment by deivid-rodriguez** [comment]
#5580 should fix this!
