### ISSUE TITLE
Issue with "bundle config" change in Bundler 2.3.7

### ISSUE THREAD

**Issue by jordan-brough** [rubygems/rubygems#5350]
@deivid-rodriguez this is maybe just a point of feedback, but the change in https://github.com/rubygems/rubygems/pull/4152 (I think) caused problems for us.

We're using Docker and in our Dockerfile we're using multi-stage builds to first compile dependencies and then copy those dependencies into the final target stage.

In our build stage we did something like this: (simplified)
```Dockerfile
RUN bundle config set ...
COPY Gemfile /app
RUN bundle install
```
We then later copy `/usr/local/bundle/` into our target stage.

In bundler <= 2.3.6, the `config set` ends up in `/usr/local/bundle/config`.
In bundler 2.3.7 it does not.

So with bundler 2.3.7 we stopped getting the config that we needed when we copied over `/usr/local/bundle/` from the build stage to the final stage.

(This was also made harder to debug for us because we're doing `gem install bundler` as part of our Dockerfile, and the updated 2.3.7 version of bundler would only be grabbed if we had a docker cache miss.  That's on us and I think we'll be changing the blind `install bundler` command to instead reference a specific version of bundler 🙂.)

We've got a few things there that need to be improved on our end, but it feels like this maybe is something that deserved more than just a patch level bump in the version number?

From #4152:

> ...usual app specific configurations (without, path) are no generally desired to be applied to all the apps of a user
> ...
> The potential incompatibilities are very low here, since this is the behavior everybody expects

I'd just note that expectations (or at least implications) are maybe a bit different in Docker-land where usually there is only a single app per global container space.

Again, I'm not arguing against the change nor am I saying we did thing the correct way, but just that maybe in the future that changes in behavior like this might be worth more than a minor version bump?

In any case, thanks for all you do for the Ruby community with Bundler!

------------------------

Here's a simplified repro in case that's helpful:
<details><summary>Click to show</summary>

With this `Dockerfile`:
```Dockerfile
FROM ruby:3.0.3-slim AS build-env
WORKDIR /app

RUN gem install bundler -v 2.3.7

# ***********************************
# ** Swapping the order of these 2 lines causes the container CMD to fail when running **
# ***********************************
RUN echo 'source "https://rubygems.org"\ngroup(:development) { gem "rack" }' > Gemfile
RUN bundle config set without "development test"

RUN bundle install

##############################

FROM ruby:3.0.3-slim
WORKDIR /app

COPY --from=build-env /usr/local/bundle/ /usr/local/bundle/
COPY --from=build-env /app/Gemfile /app/Gemfile.lock /app/

CMD exec bundle exec ruby -e 'puts "hello"'
```

Run this command:
```sh
docker build . --tag config-test && docker run --rm config-test
```
It will succeed.

Then **swap the two lines highlighted in the Dockerfile** and it will fail with:
```
Could not find rack-2.2.3 in any of the sources
```

If you run:
```sh
docker build . --target build-env --tag config-test-build-env && docker run --rm config-test-build-env bundle config
```
it'll show that the `without` config is stored in `/root/.bundle/config` instead of `/usr/local/bundle/config` in the `build-env` stage.
</details>

**Comment by deivid-rodriguez** [comment]
Yes, this is a side effect of fixing these bugs, I'm sorry it caught you. We normally release one minor version per year, perhaps I should've waited till that to fix this, but I didn't want to hold the fix anymore and decided to go ahead.

Normally you will run `bundle config`, in particular, `bundle config set without <groups>` when you have some `Gemfile` with some groups. But in your case you were running it before actually having a `Gemfile` defined. That means in the general case that you are not inside an application, so bundler interprets that you want to configure that globally, for all your apps.

I think the above fits everyone's expectation, but due to the bug fixed by #5335 you had not noticed that the lines in your Dockerfile where in an incorrect order.

Again, I'm sorry about this and thanks for your feedback.
