### ISSUE TITLE
Bundler 2.3.7 crashes for unexplained reason

### ISSUE THREAD

**Issue by caponecicero** [rubygems/rubygems#5368]
I have 3 or 4 apps that use some combination of these gems.  However, this is the only one where the target of the `bundle install` is a symlink to another location.  If I run `bundle install` again right after this failure (changing nothing), it works as expected.

### Which command did you run?

bundle install

### What were you expecting to happen?

bundle would run normally and complete successfully.

### What actually happened?
Error - '/usr/local/bin/bundle install' returns 1.
Fetching ssh://stevewi@niteflyte.net/var/archive/git/rubydoc.git
Fetching ssh://stevewi@niteflyte.net/var/archive/git/rubylib.git
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Fetching rake 13.0.6
Installing rake 13.0.6
Using abbrev 0.1.0
Using base64 0.1.1
Using benchmark 0.2.0
Fetching Ascii85 1.1.0
Fetching afm 0.2.2
Fetching bigdecimal 3.1.2
Fetching opener 0.1.0
Installing Ascii85 1.1.0
Using bundler 2.3.7
Using cgi 0.3.1
Fetching color 1.8
Installing afm 0.2.2
Installing bigdecimal 3.1.2 with native extensions
Using csv 3.2.2
Using date 3.2.2
Using io-console 0.5.11
Using delegate 0.2.0
Using did_you_mean 1.6.1
Using digest 3.1.0
Using ruby2_keywords 0.0.5
Using english 0.7.1
Using error_highlight 0.3.0
Fetching escape 0.0.4
Installing opener 0.1.0
Using etc 1.3.0
Using fcntl 1.0.1
Using fiddle 1.1.0
Fetching filesize 0.2.0
Installing color 1.8
Using fileutils 1.6.0
Using find 0.1.1
Using forwardable 1.3.2
Using getoptlong 0.1.1
Fetching hashery 2.1.2
Installing escape 0.0.4
Using io-nonblock 0.1.0
Using io-wait 0.2.1
Using ipaddr 1.2.4
Using json 2.6.1
Using logger 1.5.0
Fetching mini_mime 1.1.2
Installing filesize 0.2.0
Fetching matrix 0.4.2
Installing hashery 2.1.2
Installing mini_mime 1.1.2
Fetching redcarpet 3.5.1
Fetching rouge 3.28.0
Installing matrix 0.4.2
Fetching mini_portile2 2.7.1
Installing mini_portile2 2.7.1
Installing redcarpet 3.5.1 with native extensions
Fetching minitest 5.15.0
Installing rouge 3.28.0
Using mutex_m 0.1.1
Using timeout 0.2.0
Using uri 0.11.0
Using strscan 3.0.1
Using nkf 0.1.1
Using racc 1.6.0
Using observer 0.1.1
Using stringio 3.0.1
Using open3 0.1.1
Using openssl 3.0.0
Using optparse 0.2.0
Fetching ostruct 0.5.3
Installing minitest 5.15.0
Using pathname 0.2.0
Fetching ruby-rc4 0.1.5
Installing ostruct 0.5.3
Fetching ttfunk 1.0.3
Installing ruby-rc4 0.1.5
Fetching transaction-simple 1.4.0.2
Installing transaction-simple 1.4.0.2
Fetching power_assert 2.0.1
Installing power_assert 2.0.1
Using prettyprint 0.1.1
Using singleton 0.1.1
Using pstore 0.1.1
Fetching rbs 2.1.0
Installing ttfunk 1.0.3
Fetching rbtree 0.4.5
Installing rbs 2.1.0 with native extensions
Installing rbtree 0.4.5 with native extensions
Using readline-ext 0.1.4
Using resolv 0.2.1
Fetching rexml 3.2.5
Installing rexml 3.2.5
Fetching rfc2047 0.3
Fetching rley 0.8.09
Installing rfc2047 0.3
Using securerandom 0.1.1
Fetching sequel 5.53.0
Installing rley 0.8.09
Using set 1.0.2
Using shellwords 0.1.0
Fetching sqlite3 1.4.2
Using syslog 0.1.0
Using tempfile 0.1.2
Fetching thor 1.2.1
Installing sequel 5.53.0
Installing sqlite3 1.4.2 with native extensions
Installing thor 1.2.1
Using tsort 0.1.0
Using un 0.2.0
Fetching unix-crypt 1.3.0
Using yaml 0.2.0
Using zlib 2.1.1
Using erb 2.2.3
Using time 0.2.0
Fetching reline 0.3.1
Installing unix-crypt 1.3.0
Using weakref 0.1.1
Using drb 2.1.0
Fetching binman 5.1.0
Installing reline 0.3.1
Using tmpdir 0.1.2
Fetching mail 2.7.1
Installing binman 5.1.0
Using net-protocol 0.1.2
Fetching nokogiri 1.13.1
Installing mail 2.7.1
Using psych 4.0.3
Fetching pdf-writer 1.1.8
Installing pdf-writer 1.1.8
Fetching test-unit 3.5.3
Installing nokogiri 1.13.1 with native extensions
Installing test-unit 3.5.3
Using pp 0.3.0
Fetching prime 0.1.2
Installing prime 0.1.2
Fetching pdf-reader 2.9.1
Installing pdf-reader 2.9.1
Using resolv-replace 0.1.0
Fetching rss 0.2.9
Installing rss 0.2.9
Fetching srl_ruby 0.4.10
Installing srl_ruby 0.4.10
Fetching sorted_set 1.0.3
Installing sorted_set 1.0.3
Fetching typeprof 0.21.2
Installing typeprof 0.21.2
Using open-uri 0.2.0
Using rinda 0.1.1
Using irb 1.4.1
Using readline 0.0.3
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Gem::Package::SymlinkError: installing symlink 'man/man0/README.markdown' pointing to parent path /usr/home/stevewi/srv/mail/lib/tools/.vendor/ruby/3.1.0/gems/binman-5.1.0/README.markdown of /srv/mail/lib/tools/.vendor/ruby/3.1.0/gems/binman-5.1.0 is not allowed
  /usr/local/lib/ruby/3.1.0/rubygems/package.rb:421:in `block (2 levels) in extract_tar_gz'
  /usr/local/lib/ruby/3.1.0/rubygems/package/tar_reader.rb:65:in `each'
  /usr/local/lib/ruby/3.1.0/rubygems/package.rb:412:in `block in extract_tar_gz'
  /usr/local/lib/ruby/3.1.0/rubygems/package.rb:524:in `block in open_tar_gz'
  /usr/local/lib/ruby/3.1.0/rubygems/package.rb:521:in `wrap'
  /usr/local/lib/ruby/3.1.0/rubygems/package.rb:521:in `open_tar_gz'
  /usr/local/lib/ruby/3.1.0/rubygems/package.rb:411:in `extract_tar_gz'
  /usr/local/lib/ruby/3.1.0/rubygems/package.rb:391:in `block (2 levels) in extract_files'
  /usr/local/lib/ruby/3.1.0/rubygems/package/tar_reader.rb:65:in `each'
  /usr/local/lib/ruby/3.1.0/rubygems/package.rb:388:in `block in extract_files'
  /usr/local/lib/ruby/3.1.0/rubygems/package/file_source.rb:29:in `open'
  /usr/local/lib/ruby/3.1.0/rubygems/package/file_source.rb:29:in `with_read_io'
  /usr/local/lib/ruby/3.1.0/rubygems/package.rb:385:in `extract_files'
  /usr/local/lib/ruby/3.1.0/rubygems/installer.rb:862:in `extract_files'
  /usr/local/lib/ruby/3.1.0/bundler/rubygems_gem_installer.rb:26:in `install'
  /usr/local/lib/ruby/3.1.0/bundler/source/rubygems.rb:204:in `install'
  /usr/local/lib/ruby/3.1.0/bundler/installer/gem_installer.rb:54:in `install'
  /usr/local/lib/ruby/3.1.0/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /usr/local/lib/ruby/3.1.0/bundler/installer/parallel_installer.rb:186:in `do_install'
  /usr/local/lib/ruby/3.1.0/bundler/installer/parallel_installer.rb:177:in `block in worker_pool'
  /usr/local/lib/ruby/3.1.0/bundler/worker.rb:62:in `apply_func'
  /usr/local/lib/ruby/3.1.0/bundler/worker.rb:57:in `block in process_queue'
  /usr/local/lib/ruby/3.1.0/bundler/worker.rb:54:in `loop'
  /usr/local/lib/ruby/3.1.0/bundler/worker.rb:54:in `process_queue'
  /usr/local/lib/ruby/3.1.0/bundler/worker.rb:91:in `block (2 levels) in create_threads'
```

## Environment

```
Bundler       2.3.7
  Platforms   ruby, x86_64-freebsd-13
Ruby          3.1.1p18 (2022-02-18 revision 53f5fc4236a754ddf94b20dbb70ab63bd5109b18) [x86_64-freebsd-13]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.3.7
  Gem Home    /srv/mail/lib/tools/.vendor/ruby/3.1.0
  Gem Path    /srv/mail/lib/tools/.vendor/ruby/3.1.0
  User Home   /home/stevewi
  User Path   /home/stevewi/.local/share/gem/ruby/3.1.0
  Bin Dir     /srv/mail/lib/tools/.vendor/ruby/3.1.0/bin
OpenSSL       
  Compiled    OpenSSL 1.1.1m  14 Dec 2021
  Loaded      OpenSSL 1.1.1m  14 Dec 2021
  Cert File   /usr/local/openssl/cert.pem
  Cert Dir    /usr/local/openssl/certs
Tools         
  Git         2.35.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-02-19
Git SHA           unknown
Released Version  false
```

## Bundler settings

```
mailhome
  Set for your local app (/usr/home/stevewi/srv/mail/lib/tools/.bundle/config): "/srv/mail"
path
  Set for your local app (/usr/home/stevewi/srv/mail/lib/tools/.bundle/config): "/srv/mail/lib/tools/.vendor"
```

### Gemfile

```ruby
source "https://rubygems.org"
gem "rubylib", :git => 'ssh://stevewi@niteflyte.net:/var/archive/git/rubylib.git'
gem "rubydoc", :git => 'ssh://stevewi@niteflyte.net:/var/archive/git/rubydoc.git'
gem "thor"
gem "sqlite3"
gem "mail"
gem "rfc2047"
gem "sequel"
gem "filesize"
gem "unix-crypt"
gem "nokogiri"
gem "srl_ruby"
gem "ruport"
gem "sorted_set"
#
gem "abbrev", "0.1.0"
gem "base64", "0.1.1"
gem "benchmark", "0.2.0"
gem "bigdecimal", "3.1.2"
gem "bundler", "2.3.7"
gem "cgi", "0.3.1"
gem "csv", "3.2.2"
gem "date", "3.2.2"
gem "debug", "1.4.0"
gem "delegate", "0.2.0"
gem "did_you_mean", "1.6.1"
gem "digest", "3.1.0"
gem "drb", "2.1.0"
gem "english", "0.7.1"
gem "erb", "2.2.3"
gem "error_highlight", "0.3.0"
gem "etc", "1.3.0"
gem "fcntl", "1.0.1"
gem "fiddle", "1.1.0"
gem "fileutils", "1.6.0"
gem "find", "0.1.1"
gem "forwardable", "1.3.2"
gem "getoptlong", "0.1.1"
gem "io-console", "0.5.11"
gem "io-nonblock", "0.1.0"
gem "io-wait", "0.2.1"
gem "ipaddr", "1.2.4"
gem "irb", "1.4.1"
gem "json", "2.6.1"
gem "logger", "1.5.0"
gem "matrix", "0.4.2"
gem "minitest", "5.15.0"
gem "mutex_m", "0.1.1"
gem "net-ftp", "0.1.3"
gem "net-http", "0.2.0"
gem "net-imap", "0.2.3"
gem "net-pop", "0.1.1"
gem "net-protocol", "0.1.2"
gem "net-smtp", "0.3.1"
gem "nkf", "0.1.1"
gem "observer", "0.1.1"
gem "open-uri", "0.2.0"
gem "open3", "0.1.1"
gem "openssl", "3.0.0"
gem "optparse", "0.2.0"
gem "ostruct", "0.5.3"
gem "pathname", "0.2.0"
gem "power_assert", "2.0.1"
gem "pp", "0.3.0"
gem "prettyprint", "0.1.1"
gem "prime", "0.1.2"
gem "pstore", "0.1.1"
gem "psych", "4.0.3"
gem "racc", "1.6.0"
gem "rake", "13.0.6"
gem "rbs", "2.1.0"
gem "rdoc", "6.4.0"
gem "readline", "0.0.3"
gem "readline-ext", "0.1.4"
gem "reline", "0.3.1"
gem "resolv", "0.2.1"
gem "resolv-replace", "0.1.0"
gem "rexml", "3.2.5"
gem "rinda", "0.1.1"
gem "rss", "0.2.9"
gem "ruby2_keywords", "0.0.5"
gem "securerandom", "0.1.1"
gem "set", "1.0.2"
gem "shellwords", "0.1.0"
gem "singleton", "0.1.1"
gem "stringio", "3.0.1"
gem "strscan", "3.0.1"
gem "syslog", "0.1.0"
gem "tempfile", "0.1.2"
gem "test-unit", "3.5.3"
gem "time", "0.2.0"
gem "timeout", "0.2.0"
gem "tmpdir", "0.1.2"
gem "tsort", "0.1.0"
gem "typeprof", "0.21.2"
gem "un", "0.2.0"
gem "uri", "0.11.0"
gem "weakref", "0.1.1"
gem "yaml", "0.2.0"
gem "zlib", "2.1.1"
```

### Gemfile.lock

```
<No /usr/home/stevewi/srv/mail/lib/tools/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=installing+symlink+%27man%2Fman0%2FREADME.markdown%27+pointing+to+parent+path+%2Fusr%2Fhome%2Fstevewi%2Fsrv%2Fmail%2Flib%2Ftools%2F.vendor%2Fruby%2F3.1.0%2Fgems%2Fbinman-5.1.0%2FREADME.markdown+of+%2Fsrv%2Fmail%2Flib%2Ftools%2F.vendor%2Fruby%2F3.1.0%2Fgems%2Fbinman-5.1.0+is+not+allowed&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.

## Environment

```
Bundler       2.3.7
  Platforms   ruby, x86_64-freebsd-13
Ruby          3.1.1p18 (2022-02-18 revision 53f5fc4236a754ddf94b20dbb70ab63bd5109b18) [x86_64-freebsd-13]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.3.7
  Gem Home    /home/stevewi/.gems
  Gem Path    /usr/local/lib/ruby/gems/3.1.0:/home/stevewi/.gems
  User Home   /home/stevewi
  User Path   /home/stevewi/.local/share/gem/ruby/3.1.0
  Bin Dir     /home/stevewi/.gems/bin
Tools         
  Git         2.35.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-02-19
Git SHA           unknown
Released Version  false
```

**Comment by deivid-rodriguez** [comment]
#5570 should fix this!
