### ISSUE TITLE
SHA256 checksum mismatch with Ruby 3.2 and RubyGems master

### ISSUE THREAD

**Issue by hsbt** [rubygems/rubygems#5369]
I'm not sure what is the root cause of this issue. 

I always faced `SHA256 checksum mismatch` when I invoked `gem i [gemname]` with Ruby master and RubyGems master. like this.

```
$ gem i sinatra
Fetching sinatra-2.2.0.gem
Fetching mustermann-1.1.1.gem
ERROR:  Error installing sinatra:
        invalid gem: SHA256 checksum mismatch for data.tar.gz in /Users/hsbt/.local/share/gem/cache/mustermann-1.1.1.gem
$ ruby -v
ruby 3.2.0dev (2022-02-21) +MJIT [arm64-darwin21]
```

This issue may happen with M1 Apple Silicon. Does anyone happen same issue?

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
@hsbt I've been using M1 Apple Silicon and never saw this error. Maybe something specific to your environment. Did you dig further into this? Should we close it?

**Comment by hsbt** [comment]
@deivid-rodriguez Thanks for your remind. I tried this with the current master branch of `ruby/ruby` and macOS 12.4. But I couldn't repro this.

So, I close this.
