### ISSUE TITLE
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

### ISSUE THREAD

**Issue by haristudent2021** [rubygems/rubygems#5370]
current directory: /var/canvas/vendor/bundle/ruby/2.6.0/gems/pg-1.2.3/ext
/usr/bin/ruby2.6 -I /usr/local/lib/site_ruby/2.6.0 -r ./siteconf20220221-8781-kkhq4w.rb extconf.rb

Gem files will remain installed in /var/canvas/vendor/bundle/ruby/2.6.0/gems/pg-1.2.3 for inspection.
Results logged to /var/canvas/vendor/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0/pg-1.2.3/gem_make.out

An error occurred while installing pg (1.2.3), and Bundler cannot continue.
Make sure that `gem install pg -v '1.2.3' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  canvas_partman was resolved to 2.0.0, which depends on
    pg

**Comment by simi** [comment]
Can you check what's in the `/var/canvas/vendor/bundle/ruby/2.6.0/extensions/x86_64-linux/2.6.0/pg-1.2.3/gem_make.out`? You're most likely missing some of the gem dependency which could be installed using system package manager (like apt, dnf, pacman, brew, ...).

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
