### ISSUE TITLE
RubyGems mutates RbConfig and sets it to incorrect values

### ISSUE THREAD

**Issue by eregon** [rubygems/rubygems#5371]
RubyGems [mutates](https://github.com/rubygems/rubygems/blob/4b0d970cd31a7a34016bb6668f9756466070d6aa/lib/rubygems/ext/ext_conf_builder.rb#L30-L31) RbConfig `sitearchdir` and `sitelibdir` when building a C extension gem.

RbConfig should never be mutated, as it can lead to various issues.
One of them is actually RubyGems no longer being able to find where to insert in `$LOAD_PATH`: 
https://github.com/rubygems/rubygems/blob/c98464e8e859157375177d2b88d9ee01c1355d3f/lib/rubygems.rb#L573-L581

This issue was made more obvious as rake-compiler copied this logic:
https://github.com/rake-compiler/rake-compiler/issues/202

Could these global mutations be avoided by RubyGems?
Maybe ` make install sitearchdir=...` or so would work instead?

This might also come up as an issue as loading RubyGems is made more lazy (https://bugs.ruby-lang.org/issues/18568).

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
I tried the approach suggested at https://github.com/rake-compiler/rake-compiler/issues/202 and it seems to work and make things simpler, so I'm good with doing this.

**Comment by eregon** [comment]
Great!
