### ISSUE TITLE
Get error "undefined method `tags' for nil:NilClass (NoMethodError)" on ubuntu when run command:cucumber BROWSER='chrome-desktop-headless'

### ISSUE THREAD

**Issue by IrisLiu001** [rubygems/rubygems#5376]
Hi there,
I use cucumber-ruby setup my automation, and the command: cucumber BROWSER='chrome-desktop-headless'  
runs well on my local terminal. 
But the command keeps get error when run on ubuntu.
![image](https://user-images.githubusercontent.com/89027578/155471359-9819f71f-cc02-41e8-9c8a-ce2a4c420bdc.png)

Gemfile of the versions:
gem 'allure-cucumber', '2.13.6'
gem 'allure-ruby-commons'
gem 'browser'
gem 'cucumber', '4.0.0'
gem 'httplog', '~> 1.1', '>= 1.1.1'
gem 'parallel_tests',          '~> 2.29.0'
gem 'rake'
gem 'require_all'
gem 'rspec'
gem 'rspec-expectations', '~> 3.3.0'
gem 'rubocop'
gem 'sauce_whisk',             '0.2.2'
gem 'selenium-webdriver',         '3.141'
gem 'selenium_remote_control',    '~> 1.0', '>= 1.0.4'
gem 'webdriver-user-agent'
gem 'rest-client',                '~> 2.0'
gem 'net-http-persistent',        '~> 3.0'
gem 'faker',    '2.11'
gem 'cuke_modeler', '3.0.0'
gem 'prawn', '1.2.1'
gem 'prawn-table', '0.1.0'

**Comment by hsbt** [comment]
It seems not RubyGems/Bundler issues. So, `tags` means your DOM objects created by Cucumber.

**Comment by IrisLiu001** [comment]
so this should be a cucumber issue?
This command runs good on my local terminal. Guess the cucumber-ruby related package installed on ubuntu missing something.

**Comment by hsbt** [comment]
At least, It's not RubyGems issues. It may tty or headless environment problem. You should ask it to cucumber or https://stackoverflow.com/
