### ISSUE TITLE
Bundler fetches gemspec for every version of every private gem when using github as a source as of 2.3.5

### ISSUE THREAD

**Issue by aaronjensen** [rubygems/rubygems#5385]
### Describe the problem as clearly as you can

Bundler fetches gemspec for every valid version of gem that uses github has a source as of bundler 2.3.5. Version 2.3.4 does not exhibit this problem.

### Did you try upgrading rubygems & bundler?

Yes

### Post steps to reproduce the problem

Ruby 3.1.1
Bundler 2.3.8

```rb
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

source "https://rubygems.pkg.github.com/my-org" do
  gem "some-gem", require: false
end
```

### Which command did you run?

```sh
bundle config set --local path ./gems
bundle install
```

### What were you expecting to happen?

Gems are installed relatively quickly

### What actually happened?

Gems take an incredibly long time to install and they show gemspec fetches for every version of every private gem when running in verbose. If I specify a version constraint, it limits the gemspecs fetched, but we don't specify constraints typically so this is a non-starter for us.

See redacted log:

[log.txt](https://github.com/rubygems/rubygems/files/8197368/log.txt)

## Environment

```
Bundler       2.3.8
  Platforms   ruby, arm64-darwin-21
Ruby          3.1.1p18 (2022-02-18 revision 53f5fc4236a754ddf94b20dbb70ab63bd5109b18) [arm64-darwin-21]
  Full Path   /Users/username/.asdf/installs/ruby/3.1.1/bin/ruby
  Config Dir  /Users/username/.asdf/installs/ruby/3.1.1/etc
RubyGems      3.3.8
  Gem Home    /Users/username/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0
  Gem Path    /Users/username/.gem/ruby/3.1.0:/Users/username/.asdf/installs/ruby/3.1.1/lib/ruby/gems/3.1.0
  User Home   /Users/username
  User Path   /Users/username/.gem/ruby/3.1.0
  Bin Dir     /Users/username/.asdf/installs/ruby/3.1.1/bin
Tools         
  Git         2.35.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-02-23
Git SHA           4e812b9ca5
Released Version  true
```

## Bundler settings

```
disable_local_branch_check
  Set for the current user (/Users/username/.bundle/config): true
gem.coc
  Set for the current user (/Users/username/.bundle/config): false
gem.mit
  Set for the current user (/Users/username/.bundle/config): false
gem.test
  Set for the current user (/Users/username/.bundle/config): false
https://rubygems.pkg.github.com/my-org/
  Set for the current user (/Users/username/.bundle/config): "username:[REDACTED]"
jobs
  Set for the current user (/Users/username/.bundle/config): 8
path
  Set for your local app (/Users/username/Source/project/api/.bundle/config): "./gems"
rubygems.pkg.github.com
  Set for the current user (/Users/username/.bundle/config): "username:[REDACTED]"
```

### Gemfile

```ruby
source "https://rubygems.org"
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

source "https://rubygems.pkg.github.com/my-org" do
  gem "some-gem", require: false
end
```

### Gemfile.lock

```
<No /Users/username/Source/project/api/Gemfile.lock found>
```

**Comment by aaronjensen** [comment]
This looks like it could be the cause: https://github.com/rubygems/rubygems/pull/5256

**Comment by deivid-rodriguez** [comment]
Oh, that's right.. ;(

In order to fix the related issue and have a correct resolution in general in these cases, we made things slower.

I see no good solution here other than custom servers like gemstash or geminabox implementing the latest dependency API which includes providing `required_ruby_version` and `required_rubygems_version` information (I have no idea what GitHub packages use under the hood). Geminabox already has a proposed implementation here: https://github.com/geminabox/geminabox/pull/353, but it's not getting much attention.

**Comment by aaronjensen** [comment]
@deivid-rodriguez that is very unfortunate. It essentially makes these versions of bundler unusable for us. We delete Gemfile.lock every time we install and do not pin unless we must. In one of our projects it takes about 5 minutes to bundle install. 

Is it possible to make this configurable in some way or get the versions one at a time (latest first) and only get older versions if resolution cant happen with the latest? I realize that change may be massive.

**Comment by deivid-rodriguez** [comment]
I would personally prefer things to move forward in the way I suggested: custom servers implementing the proper APIs to get correct and fast resolution. I would rather put dedicate effort to that over anything else, the new API has been there for a long time and it's very well established now, so it should be implemented by custom servers.

In the mean time, I would suggest to stick to older Bundler for now if it's working for you, or stop deleting your Gemfile.lock file every time.

**Comment by aaronjensen** [comment]
I opened a support ticket against GitHub since it's the only one that matter to us at the moment. 

I won't get into why we delete Gemfile.lock, but even if we didn't, we'd still have the initial slow install and every upgrade we do would be impacted (we do this several times a day often).

Do you know how I can prefer an old version of bundler even when the newer is installed as a default gem (as it is in Ruby 3.1.1)?

**Comment by aaronjensen** [comment]
Found it: `gem update --system 3.3.4`

**Comment by deivid-rodriguez** [comment]
If you used a `Gemfile.lock` file, Bundler would respect automatically the version you have under the `BUNDLED WITH` section there. Since you don't, you can run `bundle _<desired_version>_ <command>`.

**Comment by deivid-rodriguez** [comment]
> Found it: gem update --system 3.3.4

Yep, that will downgrade both RubyGems and Bundler and do the trick too.

Keep us posted on GitHub's response, it would be great that they implemented this, or at least know more about their infrastructure so that we know where we need to focus our effort to move this forward.

> I won't get into why we delete Gemfile.lock, but even if we didn't, we'd still have the initial slow install and every upgrade we do would be impacted (we do this several times a day often).

Sure, I was only mentioning that because you mentioning it in the first place :) depending on how you do upgrades, sometimes it wouldn't affect you. If you always update all gems together through `bundle update` (or removing the lockfile and running `bundle install`) then yes. If you run finer grained updates via `bundle update <specific_gem>`, then only updates involving GitHub gems would be affected.



Another alternative is to keep a gemspec cache across your build

**Comment by aaronjensen** [comment]
Will do, thank you.

**Comment by aaronjensen** [comment]
From GitHub:

> Thanks for bringing this to our attention. I've been able to reproduce this here.
> https://github.com/jcansdale-test/rubygems-install-bundler/runs/5495118749?check_suite_focus=true
> 
> I can see that using bundler 2.3.5 is considerably slower than 2.3.4! I've going to open an escalation so the packages team know about this.

**Comment by deivid-rodriguez** [comment]
That's great, thanks!

**Comment by deivid-rodriguez** [comment]
Performance should be now restored in master. We should encourage custom server migrating to the compact index API, but we're not there yet. Happily I think I managed to restore performance and keep the resolution cases fixed earlier still working.

**Comment by aaronjensen** [comment]
That’s great, thank you!

**Comment by bjones** [comment]
I've used the following to generate index files for running an internal gem repository for many years.  

gem generate_index 

Has the required change to generate a different index been pushed to rubygems?  Is it compatible with static files hosted in a CDN?
