### ISSUE TITLE
Regression in bundler v2.3.9 with local installation

### ISSUE THREAD

**Issue by lstrojny** [rubygems/rubygems#5391]
Installing dependencies like this too keep things local:

```
export GEM_HOME=build/gems
export PATH=${GEM_HOME}/bin:${PATH}
gem install bundler
bundler install
```

With v2.3.8 this works just fine, with v2.3.8 we get this:

```
 /usr/local/lib/ruby/2.5.0/rubygems.rb:289:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundler (Gem::GemNotFoundException)
 	from /usr/local/lib/ruby/2.5.0/rubygems.rb:308:in `activate_bin_path'
 	from build/gems/bin/bundler:23:in `<main>'
```

Skimming through the diff I suspect https://github.com/rubygems/rubygems/pull/5386 but I could of course be wrong.

**Comment by deivid-rodriguez** [comment]
Oh no, did I mess this up again 🙈?? I can't imagine anything other than #5386 to be the cause. If you change bundler sources to revert https://github.com/rubygems/rubygems/pull/5386/commits/690f2d54c5c884ebd0608e76d0174003aeaf9ae0, does it work again?

**Comment by deivid-rodriguez** [comment]
I'm also really at loss. The diff between versions is very small: https://github.com/rubygems/rubygems/compare/v3.3.8...v3.3.9, I can't think of anything else that could affect this.

Let me know if you find the culprit.

**Comment by lstrojny** [comment]
Closing this, I am too much of a noob. So turns out my rubygems version is so old, that it still requires the bundler version in  the Gemfile.lock to match the bundler version installed. That’s the culprit, so basically what is described [here](https://bundler.io/blog/2019/05/14/solutions-for-cant-find-gem-bundler-with-executable-bundle.html). 

Closing this.

**Comment by deivid-rodriguez** [comment]
Oh, right, I'm glad you sorted it out!
