### ISSUE TITLE
Avoid partial matches when updating Gems

### ISSUE THREAD

**Issue by leejarvis** [rubygems/rubygems#540]
I just ran a `gem update rails` and expected.. well, for the rails gem to be updated. Instead, over 15 gems were updated. I also had no idea (until I was told by @apeiros) that you could do `gem update '^rails$'`. It seems to me like this should be the default behaviour, and doing partial matches should be possible with an extra flag of some sort.

Would you consider this change?

**Comment by copiousfreetime** [comment]
Is this feature request no longer needed with the existence of the `--conservative` and `--minimal-deps` ?

**Comment by LynnCo** [comment]
I tested `gem update rails` and it only updates the rails gem, not `^.*rails.*$` (which is I believe is what it was doing before)

On the contrary... it looks like `gem update '^rails$'` isn't working anymore (in 2.6.3), but that's a different issue. This one can be closed

**Comment by copiousfreetime** [comment]
Z,,z*zzzz,zzzas
