### ISSUE TITLE
Operation not permitted - getcwd (Errno::EPERM)

### ISSUE THREAD

**Issue by julio336** [rubygems/rubygems#5407]
I'm having a problem or would like to suggest a feature.

My current problem is _________

After trying to configure a simple cron job with the Whenever Gem, I get this error:

Users/<username>/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/bundler_version_finder.rb:54:in `pwd': Operation not permitted - getcwd (Errno::EPERM)
    from /Users/<username>/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/bundler_version_finder.rb:54:in `lockfile_contents'
    from /Users/<username>/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/bundler_version_finder.rb:41:in `lockfile_version'
    from /Users/<username>/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/bundler_version_finder.rb:10:in `bundler_version'
    from /Users/<username>/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/bundler_version_finder.rb:17:in `block in prioritize!'
    from /Users/<username>/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/bundler_version_finder.rb:17:in `find_index'
    from /Users/<username>/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/bundler_version_finder.rb:17:in `prioritize!'
    from /Users/<username>/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems/dependency.rb:280:in `matching_specs'
    from /Users/<username>/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems.rb:257:in `find_spec_for_exe'
    from /Users/<username>/.rvm/rubies/ruby-3.0.0/lib/ruby/site_ruby/3.0.0/rubygems.rb:284:in `activate_bin_path'
    from /Users/<username>/.rvm/gems/ruby-3.0.0/bin/bundle:23:in `<main>'

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.9
  - RUBY VERSION: 3.1.0 (2021-12-25 patchlevel 0) [arm64-darwin21]
  - INSTALLATION DIRECTORY: /Users/julioahuactzin/.rvm/gems/ruby-3.1.0
  - USER INSTALLATION DIRECTORY: /Users/julioahuactzin/.gem/ruby/3.1.0
  - RUBY EXECUTABLE: /Users/julioahuactzin/.rvm/rubies/ruby-3.1.0/bin/ruby
  - GIT EXECUTABLE: /opt/homebrew/bin/git
  - EXECUTABLE DIRECTORY: /Users/julioahuactzin/.rvm/gems/ruby-3.1.0/bin
  - SPEC CACHE DIRECTORY: /Users/julioahuactzin/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/julioahuactzin/.rvm/rubies/ruby-3.1.0/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - arm64-darwin-21
  - GEM PATHS:
     - /Users/julioahuactzin/.rvm/gems/ruby-3.1.0
     - /Users/julioahuactzin/.rvm/rubies/ruby-3.1.0/lib/ruby/gems/3.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/julioahuactzin/.rvm/gems/ruby-3.1.0/bin
     - /Users/julioahuactzin/.rvm/gems/ruby-3.1.0@global/bin
     - /Users/julioahuactzin/.rvm/rubies/ruby-3.1.0/bin
     - /Users/julioahuactzin/.rvm/bin
     - /Library/Frameworks/Python.framework/Versions/3.10/bin
     - /opt/homebrew/bin
     - /opt/homebrew/sbin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Library/Apple/usr/bin
     - /Library/Frameworks/Python.framework/Versions/3.10/bin
     - /opt/homebrew/bin
     - /opt/homebrew/sbin```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Ni idea what's going on here. Can you reproduce this consistently?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
