### ISSUE TITLE
How completely uninstall Rails gem ?

### ISSUE THREAD

**Issue by Sega100500** [rubygems/rubygems#542]
1. gem update
2. rails 4.0.0.beta1 installed
3. rails -v : shows: Rails 4.0.0.beta1
4. gem uninstall rails -v 4.0.0.beta1 ( gem uninstall rails -v=4.0.0.beta1)
5. BUT STILL:

rails -v

Rails 4.0.0.beta1

How I can completely remove rails version ?

**Comment by retrospective5** [comment]
@ryanjm: Thanks!

I have rbenv and rails5 beta3 so had to do:
```
rails uninstall gem
rails uninstall railties
rbenv rehash
rails -v
```

**Comment by ctngln** [comment]
> @ryanjm: Thanks!
> 
> I have rbenv and rails5 beta3 so had to do:
> 
> ```
> rails uninstall gem
> rails uninstall railties
> rbenv rehash
> rails -v
> ```

Just tweaking this a bit to:

gem uninstall rails
gem uninstall railties
rbenv rehash
rails -v

... which worked great for me.

**Comment by sunwei415** [comment]
`rails` CLI maps to `railties`.
This is a misleading design!

**Comment by deivid-rodriguez** [comment]
Feel free to reach out to the Rails project so that they impovel their documentation for uninstalling Rails. I don't think there's anything we can do about it ourselves. The `rails` executable is provided by the `railties` gem and that's a choice of the gem author that rubygems should respect.
