### ISSUE TITLE
misleading error message regarding the listen gem

### ISSUE THREAD

**Issue by dvodvo** [rubygems/rubygems#5449]
This issue was raised first with `listen` gem and discussed here:

https://github.com/guard/listen/issues/530

It points to an imporvement in error messaging for this particular instance.

**Comment by deivid-rodriguez** [comment]
This is not an error raised by Bundler, but by Rails. It was removed at https://github.com/rails/rails/pull/36163, released with Rails 6.1. So updating Rails will probably give you a better (or at least different :)) error.

Closing!
