### ISSUE TITLE
Unnecessary Warning about a Gem Listed More than Once

### ISSUE THREAD

**Issue by ThomasKoppensteiner** [rubygems/rubygems#5450]
### Describe the problem as clearly as you can

Bundler shows an unnecessary warning about a gem listed more than once.

> Your Gemfile lists the gem custom_gem_b (>= 0) more than once.
You should probably keep only one of them.
Remove any duplicate entries and specify the gem only once.
While it's not a problem now, it could cause errors if you change the version of one of them later.

### Did you try upgrading rubygems & bundler?

```
$ bundler -v
Bundler version 2.3.10
```

### Post steps to reproduce the problem

I'm working on an internal gem `custom_gem_a` which depends on another internal gem `custom_gem_b`.

*Gemfile*
```
# frozen_string_literal: true

source "https://rubygems.org"

source "http://gems.example.com" do
  gem "custom_gem_b"
end

# Specify your gem's dependencies in custom_gem_a.gemspec
gemspec
```
**Case 1: Using add_development_dependency**
*custom_gem_a.gemspec*
```
  ...
  spec.add_runtime_dependency "activesupport", ">= 6"
  
  spec.add_development_dependency "custom_gem_b", "~> 1.2"
  ...
```

**Case 2: Using add_runtime_dependency**
*custom_gem_a.gemspec*
```
  ...
  spec.add_runtime_dependency "activesupport", ">= 6"
  
  spec.add_runtime_dependency "custom_gem_b", "~> 1.2"
  ...
```

### Which command did you run?

```
$ bundle
```

### What were you expecting to happen?

I expected not to see this warning in both cases.

### What actually happened?

When using `add_development_dependency` for custom gems (Case 1), the warning is printed.
When using `add_runtime_dependency` for custom gems (Case 2), the warning is not printed (what I expected).

**Comment by deivid-rodriguez** [comment]
#5587 should fix this!
