### ISSUE TITLE
bundler update stuck in `Resolving dependencies`

### ISSUE THREAD

**Issue by grosser** [rubygems/rubygems#5461]
```
Bundler version 2.3.11
ruby 3.1.0p0
rubygems 3.3.11
```

already ran with `--verbose` but there is nothing showing, just endless dots
(normally bundling takes ~9s)

there needs to be some `--debug` flag or `hey I'm going to look at 1 million combinations now` or maybe some loop detection, but the current state is not debuggable without having to open up bundler source code :(

my current loop was caused by having `gem 'rails', '~> 7.0.0'` and `gem 'minitest-rails'` (which has `railties ~> 6.1.0`)

other examples:
- https://stackoverflow.com/questions/56890732/what-do-dots-after-resolving-dependencies-from-bundle-install-or-bundle-updat
- https://help.rubygems.org/discussions/problems/38518-resolving-dependencies-never-finish

**Comment by deivid-rodriguez** [comment]
We should definitely fix this, and your feedback about logging is noticed. Let me centralize this issue at https://github.com/rubygems/rubygems/issues/4539 if you don't mind, since they seem duplicates.
