### ISSUE TITLE
Support client-certificates when connecting to gem server

### ISSUE THREAD

**Issue by tomyan** [rubygems/rubygems#547]
I'm looking to run a gem server authenticated by SSL client certificate (accessed by clients in our existing PKI). It seems that this isn't currently supported by the client, although there are instructions to monkey patch it here:

http://opensourcetester.co.uk/2011/09/13/rubygems-over-ssl-clientcert/

It would be great if this could be supported natively. Happy to work on a pull request if this would be useful.

Thanks

Tom

**Comment by copiousfreetime** [comment]
Closing since #550 is accepted and merged.
