### ISSUE TITLE
'gem install json' failed

### ISSUE THREAD

**Issue by briteming** [rubygems/rubygems#5476]
I'm having a problem or would like to suggest a feature.
My current problem is:

yudeMacBook-Air:asciidoctor ym$ sudo gem install json -v '2.6.1' --source 'https://rubygems.org/'
Password:
Building native extensions.  This could take a while...
ERROR:  Error installing json:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/json-2.6.1/ext/json/ext/generator
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20220418-17989-1xdyv8z.rb extconf.rb
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/json-2.6.1 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-16/2.3.0/json-2.6.1/gem_make.out
yudeMacBook-Air:asciidoctor ym$ 

This issue is related to:

  - [ ] Network problems
  - [x ] Installing a library
  - [ ] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 2.5.2.3
  - RUBY VERSION: 2.3.7 (2018-03-28 patchlevel 456) [universal.x86_64-darwin16]
  - INSTALLATION DIRECTORY: /Library/Ruby/Gems/2.3.0
  - USER INSTALLATION DIRECTORY: /Users/ym/.gem/ruby/2.3.0
  - RUBY EXECUTABLE: /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /Users/ym/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Library/Ruby/Site
  - RUBYGEMS PLATFORMS:
    - ruby
    - universal-darwin-16
  - GEM PATHS:
     - /Library/Ruby/Gems/2.3.0
     - /Users/ym/.gem/ruby/2.3.0
     - /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/gems/2.3.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "http_proxy" => "http://localhost:7777"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/ym/.cargo/bin
     - /usr/local/opt/openssl@1.1/bin
     - /Users/ym/.nami/bin
     - /usr/local/opt/openssl@1.1/bin
     - /usr/local/opt/python@3.8/bin
     - /Users/ym/.opam/default/bin
     - /usr/local/opt/ruby/bin
     - /usr/local/opt/qt/bin
     - /usr/local/opt/llvm/bin
     - /Users/ym/Downloads/google-cloud-sdk/bin
     - /opt/local/bin
     - /opt/local/sbin
     - /usr/local/opt/gettext/bin
     - /Users/ym/.nix-profile/bin
     - /Users/ym/.nix-profile/lib/kde4/libexec
     - /nix/var/nix/profiles/default/bin
     - /nix/var/nix/profiles/default
     - /nix/var/nix/profiles/default/lib/kde4/libexec
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /opt/X11/bin
     - /usr/local/share/dotnet
     - /usr/local/go/bin
     - /Users/ym/go1.16.3/go/bin
     - /Users/ym/go1.16.3/go/gopath/bin
     - /Users/ym/.tools/otp_src_17.1/bin/
     - /Users/ym/.tools/rebar/
     - /Users/ym/.local/bin/
     - /Users/ym/slitheen/phantomjs-2.1.1-macosx/bin
     - /Users/ym/lightning/build/bin
     - /Users/ym/gradle-7.0/gradle-7.0/bin
     - /Users/ym/maven-3.1.1/apache-maven-3.1.1/bin
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

how to fix it?

**Comment by deivid-rodriguez** [comment]
Hello! 👋 

This is not a Bundler issue, but an issue with your Ruby installation. You can check Stackoverflow to try fix it: https://stackoverflow.com/questions/46377667/docker-for-mac-mkmf-rb-cant-find-header-files-for-ruby.

Good luck!
