### ISSUE TITLE
Doesn't installed 

### ISSUE THREAD

**Issue by Abid0987** [rubygems/rubygems#5482]
Bundler 2.3.12 is running, but your lockfile was generated with 2.1.4. Installing Bundler 2.1.4 and restarting using that version.
Fetching gem metadata from https://rubygems.org/.
Fetching bundler 2.1.4
Installing bundler 2.1.4
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.

How to solve this error?? 
Please help me

**Comment by hsbt** [comment]
It's not an error, only warnings. You can ignore it with `bundle update --bundler` maybe.

**Comment by Abid0987** [comment]
This is not a problem?
