### ISSUE TITLE
Dose not installed 

### ISSUE THREAD

**Issue by Abid0987** [rubygems/rubygems#5483]
The gemspec at
/data/data/com.termux/files/home/metasploit-framework/metasploit-framework.gemspec is
not valid. Please fix this gemspec.
The validation error was 'duplicate dependency on net-smtp (>= 0), (>= 0) use:
    add_runtime_dependency 'net-smtp', '>= 0', '>= 0'
'
Fetching gem metadata from https://rubygems.org/.

You have one or more invalid gemspecs that need to be fixed.
The gemspec at
/data/data/com.termux/files/home/metasploit-framework/metasploit-framework.gemspec is
not valid. Please fix this gemspec.
The validation error was 'duplicate dependency on net-smtp (>= 0), (>= 0) use:
    add_runtime_dependency 'net-smtp', '>= 0', '>= 0'
'
open("/data/data/com.termux/files/usr/lib/ruby/gems/*/gems/pg-*/lib/pg_ext.so"): No such file or directory

How to solve this error? please help me!

**Comment by duckinator** [comment]
If it you did not edit the file directly, information about which operating system (including version) you're using would be helpful.

**Comment by cachilo22** [comment]
Ayuda por favor , intento instalar framework y me sale esto
![Screenshot_20240505-101849](https://github.com/rubygems/rubygems/assets/138717200/d96b1ca2-7a88-4688-93d6-f7adfb739c28)
