### ISSUE TITLE
Bundler should adhere to Semantic Versioning

### ISSUE THREAD

**Issue by tjchambers** [rubygems/rubygems#5484]
### Describe the problem as clearly as you can

Given that Rubygems recommends that gem owners follow Semantic Versioning guidelines, Bundler should be a good OSS citizen and follow those same guidelines.

### Did you try upgrading rubygems & bundler?

Yes - which led to failures due to public API methods removed in a PATCH release.

### Post steps to reproduce the problem

- install the `bootboot` plugin from Shopify/bootboot
- Run `bundle install --full-index` against same Gemfile.

### Which command did you run?

bundle install --full-index

### What were you expecting to happen?

A successful bundling of the Gemfile into Gemfile.lock

### What actually happened?

```
#13 22.03 NoMethodError: undefined method `to_gem_version_with_patchlevel' for #<Bundler::RubyVersion:0x000055afa9ddda70>
#13 22.03   /usr/local/bundle/plugin/gems/bootboot-0.2.0/lib/bootboot/ruby_source.rb:29:in `block in specs'
#13 22.03   /usr/local/lib/ruby/site_ruby/2.4.0/bundler/index.rb:9:in `build'
#13 22.03   /usr/local/bundle/plugin/gems/bootboot-0.2.0/lib/bootboot/ruby_source.rb:20:in `specs'
#13 22.03   /usr/local/lib/ruby/site_ruby/2.4.0/bundler/resolver.rb:167:in `index_for'
#13 22.03   /usr/local/lib/ruby/site_ruby/2.4.0/bundler/resolver.rb:175:in `results_for'
#13 22.03   /usr/local/lib/ruby/site_ruby/2.4.0/bundler/resolver.rb:112:in `search_for'



#13 22.03 ## Environment
#13 22.03 
#13 22.03 ```
#13 22.03 Bundler       2.3.12
#13 22.03   Platforms   ruby, x86_64-linux
#13 22.03 Ruby          2.4.10p364 (2020-03-31 revision 67879) [x86_64-linux]
#13 22.03   Full Path   /usr/local/bin/ruby
#13 22.03   Config Dir  /usr/local/etc
#13 22.03 RubyGems      3.3.12
#13 22.03   Gem Home    /usr/local/bundle
#13 22.03   Gem Path    /root/.gem/ruby/2.4.0:/usr/local/lib/ruby/gems/2.4.0:/usr/local/bundle
#13 22.03   User Home   /root
#13 22.03   User Path   /root/.gem/ruby/2.4.0
#13 22.03   Bin Dir     /usr/local/bundle/bin
#13 22.03 OpenSSL       
#13 22.03   Compiled    OpenSSL 1.1.1d  10 Sep 2019
#13 22.03   Loaded      OpenSSL 1.1.1d  10 Sep 2019
#13 22.03   Cert File   /usr/lib/ssl/cert.pem
#13 22.03   Cert Dir    /usr/lib/ssl/certs
#13 22.03 Tools         
#13 22.03   Git         2.20.1
#13 22.03   RVM         not installed
#13 22.03   rbenv       not installed
#13 22.03   chruby      not installed
#13 22.03 ```
#13 22.03 
#13 22.03 ## Bundler Build Metadata
#13 22.03 
#13 22.03 ```
#13 22.03 Built At          2022-04-20
#13 22.03 Git SHA           75031e03f4
#13 22.03 Released Version  true
#13 22.03 ```
#13 22.03 
#13 22.03 ## Bundler settings
#13 22.03 
#13 22.03 ```
#13 22.03 app_config
#13 22.03   Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
#13 22.03 silence_root_warning
#13 22.03   Set via BUNDLE_SILENCE_ROOT_WARNING: true
#13 22.03 ```
#13 22.03 

```

In https://github.com/rubygems/rubygems/pull/5472 the public method `to_gem_version_with_patchlevel` documented in the RubyDocs and used by outside sources was removed in a PATCH version (2.3.12) of bundler. This was done without any forewarning of deprecation. If I understand the guidelines around Semantic Versioning advocated by rubygems any breaking changes should necessitate a MAJOR version update. Obviously NOT removing that method (regardless of deciding not to use it internally) is an option.

**Comment by deivid-rodriguez** [comment]
Sorry I didn't consider the `RubyVersion` class as a public API.

Basically I only consider the CLI (flags, commands, etc), documented methods in the `Bundler` namespace like `Bundler.with_original_env` and things like that, and actual APIs meant to be used by other libraries (like the plugin API) as official as public API. Internal classes and their methods (public or private) are not considered public API.

There are hundreds of third parties using Bundler internals in the most complicated ways, it happens that as we change things sometimes things break.

I wouldn't mind to reintroduce this method if you need it, but I rather change `bootboot` at this point.

**Comment by tjchambers** [comment]
I don't personally maintain `bootboot` but have put an issue in there to capture the impact. Note: https://github.com/Shopify/bootboot/issues/40

IMHO it should be clear (either by coding as private or documentation indicating privacy what is subject to change without notice or adherence to Semantic Versioning. In this case it was unclear to me looking at docs and code. 

I would prefer bootboot to not use it as well, but right now version 2.3.12 - the latest which is fetched and installed by `gem system update` is not usable under all conditions .  That is just the current state - good or not good.

**Comment by deivid-rodriguez** [comment]
Thanks for the feedback, we should make things more clear in this regard, and note that any method not explicitly documented as public API is not public API. I will provide a PR to bootboot to fix this and will try to be more careful with this in the future in any case.
