### ISSUE TITLE
Introduce the concept of subbundles

### ISSUE THREAD

**Issue by ngan** [rubygems/rubygems#5499]
We have a very large monolith with 600-ish gem dependencies in our lockfile. Running a binstub to run commands that don't require the entire bundle (eg `rubocop`) takes a considerable amount of time. (I'm on a fast Macbook Pro M1)

```
$ time bin/rubocop --version
bin/rubocop --version  2.62s user 0.37s system 97% cpu 3.063 total
```

I created a concept of a "subbundle" wherein my binstub only loads a part of my entire bundle. I've written a gem that does this and we are using it to great effect:
https://github.com/bigrails/subbundle

I thought about polishing the gem a bit more but wanted to see if Bundler would be interested in adopting something like this straight into Bundler. The [implementation is fairly simple](https://github.com/bigrails/subbundle/blob/main/lib/subbundle.rb#L7-L21), and I bet there's room for improvement (I was trying to be as noninvasive as possible).

Here's the after benchmarks:
```
$ time bin/rubocop --version
bin/rubocop --version  0.51s user 0.16s system 92% cpu 0.720 total
```

**4.25x boot time improvement!**

The binstub looks like this:

`bin/rubocop`
```ruby
# Load the subbundle binstub first.
load File.expand_path("subbundle", __dir__)
# Setup the subbundle.
Subbundle.setup("rubocop")

# Execute the binary.
load Gem.bin_path("rubocop", "rubocop")
```

The `subbundle` binstub concept was [copied from Spring](https://github.com/rails/spring/blob/main/lib/spring/client/binstub.rb#L20-L35). Of course, this would go away if Bundler were to support subbundles out of the box.

`bin/subbundle`
```ruby
# This file loads Subbundle without using loading other gems in the Gemfile, in order to be fast.
# It gets overwritten when you run the `subbundle binstub` command.

unless defined?(Subbundle)
  require "bundler"

  Bundler.locked_gems.specs.find { |spec| spec.name == "subbundle" }&.tap do |subbundle|
    Gem.use_paths Gem.dir, Bundler.bundle_path.to_s, *Gem.path
    gem "subbundle", subbundle.version
    require "subbundle"
  end
end
```

I'd be happy to work on this if y'all think it makes sense. cc @deivid-rodriguez

**Comment by deivid-rodriguez** [comment]
Hei! I think the [`--only` feature request](https://github.com/rubygems/rubygems/issues/4048) satisfies this request. It'd be a matter of putting the gems that you want isolated into their own group, and then set `BUNDLE_ONLY=<group_name>` in the binstub.

I proposed other alternatives in that issue but they are more complicated. I tend to think we should accept adding `--only`.

**Comment by ngan** [comment]
So I think there is a difference between what's proposed in this PR and what I'm trying to do here (please correct me if I'm wrong). The problem is that in a large Gemfile(.lock), the mere act of resolving the bundle (ie `Bundle.setup`) is time consuming. We're not even talking about requiring gems, just resolving and adding to load paths.

```
➜  git:(development) ✗ irb
irb(main):001:0> require 'bundler'; require 'benchmark'; puts Benchmark.realtime { Bundler.setup }; true
2.4271109998226166
```

The performance gains comes from not resolving all the dependencies in the bundle.

> So, it seems to me that a good fit for these situations is to split the "linting" group to a separate Gemfile, say, Gemfile.lint

I thought about doing this but came to the conclusion that it would be a nightmare to maintain. We'd like all of our gems to be on the same version within our project and having multiple Gemfiles and making sure their locked versions are all the same oof...

**Comment by deivid-rodriguez** [comment]
I see, but I don't understand why you need to re-resolve every time. The `Gemfile.lock` is essentially a cached resolve, so you shouldn't be having to resolve every time if you use a `Gemfile.lock` file.

**Comment by ngan** [comment]
I don’t think it’s doing a full resolve every time. I think the time comes from `last_resolve = converge_locked_spec` that’s called inside the resolve method. That’s why I suggested caching that (in the [other issue](https://github.com/rubygems/rubygems/issues/5345)).

Let me know if you need something on my end to reproduce this. Like I mentioned, we have 570ish gems in our lockfile. 😅

**Comment by deivid-rodriguez** [comment]
@ngan If that's where most of the time comes from, can you try applying this patch and setting `BUNDLE_FROZEN` at the beginning of your binstub, and post the results?

```diff
diff --git a/bundler/lib/bundler/definition.rb b/bundler/lib/bundler/definition.rb
index c1d865d049..8877d2661e 100644
--- a/bundler/lib/bundler/definition.rb
+++ b/bundler/lib/bundler/definition.rb
@@ -256,14 +256,14 @@ def dependencies_for(groups)
     # @return [SpecSet] resolved dependencies
     def resolve
       @resolve ||= begin
-        last_resolve = converge_locked_specs
         if Bundler.frozen_bundle?
           Bundler.ui.debug "Frozen, using resolution from the lockfile"
-          last_resolve
+          @locked_specs
         elsif !unlocking? && nothing_changed?
           Bundler.ui.debug("Found no changes, using resolution from the lockfile")
-          last_resolve
+          converge_locked_specs
         else
+          last_resolve = converge_locked_specs
           # Run a resolve against the locally available gems
           Bundler.ui.debug("Found changes from the lockfile, re-resolving dependencies because #{change_reason}")
           expanded_dependencies = expand_dependencies(dependencies + metadata_dependencies, true)
@@ -693,7 +693,7 @@ def converge_specs(specs)
         # Replace the locked dependency's source with the equivalent source from the Gemfile
         dep = @dependencies.find {|d| s.satisfies?(d) }
 
-        s.source = (dep && dep.source) || sources.get(s.source) || sources.default_source unless Bundler.frozen_bundle?
+        s.source = (dep && dep.source) || sources.get(s.source) || sources.default_source
 
         next if @unlock[:sources].include?(s.source.name)
 
```

**Comment by deivid-rodriguez** [comment]
I proposed a similar patch at #5503 that should hopefully give you similar speed up without having to set `BUNDLE_FROZEN`. It's not going to match the speed up of your approach but it should hopefully improve things!

**Comment by indirect** [comment]
I am a big fan of the idea of upstreaming this, or something like it. I noticed that subbundle errors if the gem is a dependency of one of your gems, and we probably need a solution of some kind for that: https://github.com/bigrails/subbundle/issues/2. 

If we put subbundle inside the `bin/bundle` shared binstub, maybe the solution is to tell people they need to add the gem to their gemfile directly to create a binstub?

Anyway, excellent work everyone here making Bundler faster, keep it up!

**Comment by technicalpickles** [comment]
> I see, but I don't understand why you need to re-resolve every time. The Gemfile.lock is essentially a cached resolve, so you shouldn't be having to resolve every time if you use a Gemfile.lock file.

@ngan and I paired a bit on this yesterday, including benchmarking and looking at flamegraphs. I shared how I was generating this, and an example flamegraph over on https://github.com/rubygems/rubygems/pull/5534#issuecomment-1126045896

We found that `SpecSet#for` was the span in the graph, so is the place to start looking. I stuck a `binding.pry` in there, and found out that it seems to be called 4 times:

- with 0 specs
- with 292 specs
- with 1460 specs
- and again with 292 specs

I used `show-stack` to see where the calls are happening, but hadn't gotten further. Output below:

```
# 0 specs
(looks like I lost track of this one)

# 292 specs
=> #0  for <Bundler::SpecSet#for(dependencies, check=?, match_current_platform=?)>
   #1 [method]  initialize <Bundler::Definition#initialize(lockfile, dependencies, sources, unlock, ruby_version=?, optional_groups=?, gemfiles=?)>
   #2 [method]  to_definition <Bundler::Dsl#to_definition(lockfile, unlock)>
   #3 [method]  evaluate <Bundler::Dsl.evaluate(gemfile, lockfile, unlock)>
   #4 [method]  build <Bundler::Definition.build(gemfile, lockfile, unlock)>
   #5 [method]  definition <Bundler.definition(unlock=?)>
   #6 [method]  setup <Bundler.setup(*groups)>
   #7 [block]   block in <top (required)> 
   #8 [method]  with_level <Bundler::UI::Shell#with_level(level)>
   #9 [method]  silence <Bundler::UI::Shell#silence(&blk)>
   #10 [top]     <top (required)> 
   #11 [method]  require <Kernel#require(path)>
   #12 [block]   block (2 levels) in <main> 
   #13 [block]   block in <main> 
   #14 [method]  measure <Benchmark.measure(label=?)>
   #15 [main]    <main> 

# 1460 specs
=> #0  for <Bundler::SpecSet#for(dependencies, check=?, match_current_platform=?)>
   #1 [method]  filter_specs <Bundler::Definition#filter_specs(specs, deps)>
   #2 [method]  resolve <Bundler::Definition#resolve()>
   #3 [method]  materialize <Bundler::Definition#materialize(dependencies)>
   #4 [method]  specs <Bundler::Definition#specs()>
   #5 [method]  specs_for <Bundler::Definition#specs_for(groups)>
   #6 [method]  setup <Bundler::Runtime#setup(*groups)>
   #7 [method]  setup <Bundler.setup(*groups)>
   #8 [block]   block in <top (required)> 
   #9 [method]  with_level <Bundler::UI::Shell#with_level(level)>
   #10 [method]  silence <Bundler::UI::Shell#silence(&blk)>
   #11 [top]     <top (required)> 
   #12 [method]  require <Kernel#require(path)>
   #13 [block]   block (2 levels) in <main> 
   #14 [block]   block in <main> 
   #15 [method]  measure <Benchmark.measure(label=?)>
   #16 [main]    <main> 

# 292 specs again
=> #0  for <Bundler::SpecSet#for(dependencies, check=?, match_current_platform=?)>
   #1 [method]  materialize <Bundler::SpecSet#materialize(deps)>
   #2 [method]  materialize <Bundler::Definition#materialize(dependencies)>
   #3 [method]  specs <Bundler::Definition#specs()>
   #4 [method]  specs_for <Bundler::Definition#specs_for(groups)>
   #5 [method]  setup <Bundler::Runtime#setup(*groups)>
   #6 [method]  setup <Bundler.setup(*groups)>
   #7 [block]   block in <top (required)> 
   #8 [method]  with_level <Bundler::UI::Shell#with_level(level)>
   #9 [method]  silence <Bundler::UI::Shell#silence(&blk)>
   #10 [top]     <top (required)> 
   #11 [method]  require <Kernel#require(path)>
   #12 [block]   block (2 levels) in <main> 
   #13 [block]   block in <main> 
   #14 [method]  measure <Benchmark.measure(label=?)>
   #15 [main]    <main> 
```

**Comment by deivid-rodriguez** [comment]
Thanks! Yeah, indeed, my further work on this involves reducing `SpecSet#for` calls at `bundler/setup` time to 1 or 2.

**Comment by ngan** [comment]
Closing this out because after all the improvements made, we’re seeing very fast `require ‘bundler/setup’` time now! 🎉 Great work, @deivid-rodriguez and @technicalpickles! I’ve archived `subbundle`.

**Comment by deivid-rodriguez** [comment]
That's great to hear!! 🎉
