### ISSUE TITLE
Undefined method: 'full_name' for nil:NilClass

### ISSUE THREAD

**Issue by alvigilegner** [rubygems/rubygems#5515]
I am running this command under Ubuntu on a Windows 11 laptop

bundle update --conservative ohai --conservative commonmarker --conservative nokogiri --conservative ruby-magic --conservative tanuki_emoji --conservative gitlab-labkit --conservative letter_opener_web --conservative gitlab-styles --conservative gitlab-experiment

Below is the Error Template:

[Error Template.txt](https://github.com/rubygems/rubygems/files/8636582/Error.Template.txt)

and this is the gem environment:

[GemEnv.txt](https://github.com/rubygems/rubygems/files/8636583/GemEnv.txt)

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Could you please upgrade to Bundler 2.3.13 and try again?

**Comment by Schwad** [comment]
Hello from September 2022: @deivid-rodriguez that fix worked for me. Thank you! ❤️

**Comment by shifat-aivalabs** [comment]
Same issue for bundler 2.3.23

**Comment by deivid-rodriguez** [comment]
Please report a new issue with instructions to reproduce the problem. Thank you!
