### ISSUE TITLE
Small error: "Must provide a directory path here." - could the message be improved?

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems#5517]
I just had this failure:

"gem build *.gemspec

Invalid gemspec in [multimedia_paradise.gemspec]: Must provide a directory path here.
ERROR:  Error loading gemspec. Aborting."

I found out why; I was using another gem, and somehow I conflicted with Gem::Specification.
But this report is not so much about my problem, but more with this message here:

"Must provide a directory path here."

Would it be possible to add what exactly "here" refers to? I spent almost 10 minutes
trying to figure out what was wrong in the .gemspec file, until I realized the problem
was caused because I pulled in other helper-files that fill in data into that .gemspec.

If the "here" would be replaced like this:

"Must provide a directory path to the entry XYZ."

Then I think it may have been easier for me to find the error quickly. The "here"
part really confused me.

I tried to grep for the error message in rubygems source, but I could not find
it. In fact, I grepped for "Must" and I did not find where that is used, so now
I am even more confused. Is the error message not coming from gem itself?

Either way I am just reporting this - whoever has written the error message
should have done better, but now I am not even certain it is part of gem
itself. But I got this from the commandline so I am confused....

**Comment by deivid-rodriguez** [comment]
@rubyFeedback Can you share steps to reproduce the error? Right now we're just logging the original exception when loading the gemspec, which is indeed not very informative. If I can reproduce the error, I can look into how to make this kind of situation better.

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback, feel free to reopen if still interested.
