### ISSUE TITLE
Bundler is treating a "~> 1" constraint like "~> 1.0"

### ISSUE THREAD

**Issue by BrianHawley** [rubygems/rubygems#5526]
### Describe the problem as clearly as you can

I have a gem indirect dependency, which declares this dependency: `faraday (~> 1)`

According to all the documented rules about `~>` that should include any version after 1.0.0, because it doesn't specify any point value in the spec. However, it doesn't allow faraday to be updated to 2.x, and I would expect that it would.

### Did you try upgrading rubygems & bundler?

Tested with bundler 2.3.7 included in Ruby 3.1.2, and with rubygems 3.3.13 / bundler 2.3.13.

### Post steps to reproduce the problem

Ruby 3.1.2 installed from rvm master, on macOS 10.15.7. There is no indication that this is platform-specific, and all gems involved are pure Ruby with no native extensions.

This Gemfile is sufficient to demonstrate the problem:
```ruby
source "https://rubygems.org"

gem "faraday", "~> 2"
gem "opensearch-transport", "~> 1.0.0"
```

### Which command did you run?

`bundle`

### What were you expecting to happen?

It should have bundled, and faraday 2.3.0 should have been in the lock file.

### What actually happened?

I get this error:
```
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
Bundler could not find compatible versions for gem "faraday":
  In Gemfile:
    faraday (~> 2)

    opensearch-transport (~> 1.0.0) was resolved to 1.0.0, which depends on
      faraday (~> 1)
```

## Environment

```
Bundler             2.3.13
  Platforms         ruby, x86_64-darwin-19
Ruby                3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x86_64-darwin-19]
  Full Path         /Users/.../.rvm/rubies/ruby-3.1.2/bin/ruby
  Config Dir        /Users/.../.rvm/rubies/ruby-3.1.2/etc
RubyGems            3.3.13
  Gem Home          /Users/.../.rvm/gems/ruby-3.1.2@deluxe
  Gem Path          /Users/.../.rvm/gems/ruby-3.1.2@deluxe:/Users/bhawley/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0
  User Home         /Users/...
  User Path         /Users/.../.gem/ruby/3.1.0
  Bin Dir           /Users/.../.rvm/gems/ruby-3.1.2@deluxe/bin
Tools
  Git               2.24.3 (Apple Git-128)
  RVM               1.29.12-next (master)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2022-05-04
Git SHA           b20be5a433
Released Version  true
```

## Bundler settings

```
gem.coc
  Set for the current user (/Users/.../.bundle/config): false
gem.mit
  Set for the current user (/Users/.../.bundle/config): false
gem.test
  Set for the current user (/Users/.../.bundle/config): "rspec"
```

### Gemfile

```ruby
source "https://rubygems.org"

gem "faraday", "~> 2"
gem "opensearch-transport", "~> 1.0.0"
```

### Gemfile.lock

```
<No /.../Gemfile.lock found>
```

**Comment by BrianHawley** [comment]
Also tested with ruby 3.0.3, bundler 2.2.32, same result.

**Comment by deivid-rodriguez** [comment]
Hi @BrianHawley, where did you read this documentation you are mentioning?

The `~>` operator is somewhat undefined for single digit version specifications, since it's definition to figure out the exclusive upper bound would be something like "omit the last version segment and bump the previous to last segment by one". So `~> x.y.z` would mean `< x.y+1`, and `~> x.y` would mean `< x+1`, but it's unclear what `~> x` should mean.

The current meaning has existed since the operator was introduced, and it's actually documented at https://guides.rubygems.org/patterns/#declaring-dependencies, where the following is explained:

> It’s also important to know that if you specify a major version only, like this:
>
>   ```ruby
>   # gemspec
>   spec.add_runtime_dependency 'library', '~> 2'
>   ```
>
> It will only use the latest version from the 2.x series – so 2.3.0 – and not 3.0.0. This behaviour may surprise some people, but automatically allowing any major version past version 2 is more surprising behaviour.

**Comment by BrianHawley** [comment]
Well, I've seen many gems that seem to expect the same behavior I do, so it came as a surprise to me.

In any case, I'll make a PR to opensearch-transport to relax its restriction.

**Comment by deivid-rodriguez** [comment]
To be honest, I was also surprised by this the first time I found about it. On a fresh new world, I would choose our initial  interpretation. But I'm not sure this is worth changing now.

It's also documented here: https://docs.ruby-lang.org/en/3.1/Gem/Version.html#class-Gem::Version-label-Preventing+Version+Catastrophe-3A.

**Comment by BrianHawley** [comment]
It's a "feature" I guess.

**Comment by deivid-rodriguez** [comment]
Yes, definitely, the person who implemented this originally thought of this as a feature.
