### ISSUE TITLE
Unable to bundle install from scratch on bundler >= 2.3.13

### ISSUE THREAD

**Issue by ngan** [rubygems/rubygems#5538]
### Describe the problem as clearly as you can

As mentioned [here](https://github.com/rubygems/rubygems/pull/5532#issuecomment-1126099133), we are no longer able to bundle install from scratch on bundler 2.3.13. My hunch is that this is from the [performance changes](https://github.com/rubygems/rubygems/pull/5503).

### Post steps to reproduce the problem

Our very large Gemfile.lock (550+ gems). We're unable to bundle from scratch (nor `bundle/setup` for that matter) on Bundler 2.3.13:
<img width="403" alt="image" src="https://user-images.githubusercontent.com/16579/168401695-6dae598d-ea61-4a05-8ec2-df02d7d30795.png">

Something that stuck out to me was the `using timeout 0.2.0` (see screenshot). We are _not_ seeing this on bundler 2.3.11. (We're not able to use 2.3.12 due to the [regression](https://github.com/rubygems/rubygems/pull/5486)).

**Comment by ngan** [comment]
@deivid-rodriguez actually, I misspoke. Bundle install is fine. However, we’re unable to boot the bundle for rails or even do a simple bundle clean command:

```
bundle clean --force
Could not find timeout-0.2.0, date-3.2.2 in any of the sources
```

Still, something is weird about the “Using timeout” to me (in description). Could this be a side affect from the expand_dependencies change?

**Comment by deivid-rodriguez** [comment]
This is strange, I don't see how this could be related to the performance improvements. What output do you see with Bundler 2.3.11? The problem seems that somehow Bundler is failing to find default gems for some reason, not sure why, and most confusingly, why now. Maybe some release of some default gem could be influencing this.

**Comment by ngan** [comment]
Whoops! The problem was on our end. We were using an old version of rubygems.
