### ISSUE TITLE
Rubygems gem command very slow on Windows Ruby 3.1 x64-mingw-ucrt

### ISSUE THREAD

**Issue by johnnyshields** [rubygems/rubygems#5540]
I am running Ruby 3.1 on x64-mingw-ucrt using RubyInstaller 3.1.1-1. (Note that x64-mingw-ucrt is the new platform which is now the standard for Windows as of Ruby 3.1.)

Running `gem install` is drastically slower than on Ruby 3.0 and other versions; it takes several minutes before any log lines print at all. It does eventually work correctly, i.e. installs the gems.

Doing `gem update --system` doesn't make any difference.

I am not noticing slowness in any other aspect of Ruby 3.1; I've run various code benchmarks on irb and there wasn't a major performance difference.

I've filed an issue with RubyInstaller as well: https://github.com/oneclick/rubyinstaller2/issues/264

**Comment by deivid-rodriguez** [comment]
I'd definitely like to figure this one out, although it seems something to do with Ruby/RubyInstaller rather than RubyGems, since we don't really have code specific to any rubies.

Would you be able to run some benchmarks to figure out where RubyGems updater is spending the most time? Also, is it equally slow if you use `--no-document`?

**Comment by johnnyshields** [comment]
OK, I've determined that its due to HTTPS being slow. Added comment on https://github.com/oneclick/rubyinstaller2/issues/264. I think this is not related to Rubygems itself, so closing issue.

**Comment by deivid-rodriguez** [comment]
I'll subscribe to that ticket!

**Comment by deivid-rodriguez** [comment]
By the way, I doubt it's related to ipv6, but you may want to try setting the `IPV4_FALLBACK_ENABLED` environment variable just in case!

**Comment by deivid-rodriguez** [comment]
So, was it indeed an ipv6 related issue that `IPV4_FALLBACK_ENABLED` did not fix?

**Comment by johnnyshields** [comment]
IPV4_FALLBACK_ENABLED didn't seem to fix it. Issue is still open on RubyInstaller side.

**Comment by deivid-rodriguez** [comment]
Ok!
