### ISSUE TITLE
require 'bundler/setup' slow for large Gemfile (600ish gems)

### ISSUE THREAD

**Issue by technicalpickles** [rubygems/rubygems#5545]
### Describe the problem as clearly as you can

@ngan described the problem over in https://github.com/rubygems/rubygems/issues/5499

> We have a very large monolith with 600-ish gem dependencies in our lockfile. Running a binstub to run commands that don't require the entire bundle (eg `rubocop`) takes a considerable amount of time. (I'm on a fast Macbook Pro M1)
> 
> ```
> $ time bin/rubocop --version
> bin/rubocop --version  2.62s user 0.37s system 97% cpu 3.063 total
> ```

@ngan, @deivid-rodriguez and myself have made a handful of PRs to try to address this, but wanted to describe the problem in a central spot instead of spread out across PRs.

- https://github.com/rubygems/rubygems/pull/5503
- https://github.com/rubygems/rubygems/pull/5532
- https://github.com/rubygems/rubygems/pull/5534
- https://github.com/rubygems/rubygems/pull/5536
- https://github.com/rubygems/rubygems/pull/5537

### Did you try upgrading rubygems & bundler?

Yes

### Post steps to reproduce the problem

@indirect asked for this over in  https://github.com/rubygems/rubygems/pull/5536#issuecomment-1126524813

> Can you provide a repro script that others can use to verify/see the performance improvements? Ideally using a benchmarking tool like `hyperfine` to reduce outliers. 🙏🏻

I made a repo that has a scrubbed Gemfile & Gemfile.lock based on our monolith https://github.com/technicalpickles/big-gemfile

You can benchmark it with:

```shell
# use latest bundler avaailable
hyperfine "ruby run.rb"

# use specific 
hyperfine "ruby run.rb 2.3.9"
hyperfine "ruby run.rb 2.3.11"
hyperfine "ruby run.rb 2.4.0.dev" # this is the version you get when you `rake install` in a rubygems checkout

# use another project's Gemfile instead of the one provided
cd path/to/some-app/
ruby path/to/big-gemfile/run.rb
hyperfine "ruby path/to/big-gemfile/run.rb"
```

#### Here's what it looks like

In big-gemfile:

```
❯ ruby run.rb
Bundler 2.3.11 on arm64-darwin21 with 393 gems

❯ hyperfine "ruby run.rb" 
Benchmark 1: ruby run.rb
  Time (mean ± σ):     817.1 ms ±  55.6 ms    [User: 616.0 ms, System: 127.3 ms]
  Range (min … max):   750.1 ms … 916.2 ms    10 runs
 ```

In our app:

```
❯ ruby ~/workspace/big-gemfile/run.rb
Bundler 2.3.13 on arm64-darwin21 with 579 gems

❯ hyperfine 'ruby ~/workspace/big-gemfile/run.rb' --warmup 5
Benchmark 1: ruby ~/workspace/big-gemfile/run.rb
  Time (mean ± σ):      1.248 s ±  0.023 s    [User: 1.029 s, System: 0.170 s]
  Range (min … max):    1.224 s …  1.297 s    10 runs
```

**Comment by technicalpickles** [comment]
I was chatting with @ngan about why we saw a difference between our monolith and the big-gemfile, and the main difference we could figure was one of the removed parts was:

```ruby
path "gems" do
  # some 30 gems
end
```

And @ngan tracked this down: 

https://github.com/rubygems/rubygems/blob/773fc2b9287ef06b5674dcac9b704aaba73481d6/bundler/lib/bundler/source/path.rb#L68-L70

This is quite a few objects just to hash. I think that is the reason we see such a notable improvement over in  https://github.com/rubygems/rubygems/pull/5537

**Comment by deivid-rodriguez** [comment]
Thnaks for opening this @technicalpickles 👍. I can't access your sample repository though.

**Comment by technicalpickles** [comment]
@deivid-rodriguez oops, forgot to hit submit on making it public 🤦🏻‍♂️

**Comment by ngan** [comment]
One other slight performance hit for us is that path’d gems load the gemspec file and we currently us Dir globbing to set the `files` directive. Since we’re not publishing the gem, this was unnecessary. I’m going to put up a PR to remove them.

**Comment by deivid-rodriguez** [comment]
All relevant PRs have been either merged or close. I still have further speed ups coming up, but I think this one can be closed now anyways!

**Comment by technicalpickles** [comment]
Agreed! Wanted to let y'all know we were able to remove the `subbundle` gem we made over in https://github.com/rubygems/rubygems/issues/5499 

> After tons of performance improvements to Bundler, we can remove this gem because the added complexity is no longer worth it. This gem boots `bin/rubocop` in .3 seconds and plain ol' `bundler/setup` now boots in .5 seconds (it use to take 2.5 seconds).

**Comment by deivid-rodriguez** [comment]
Great to hear! Hopefully we'll make things even faster 💪
