### ISSUE TITLE
`bundle update` suggests running `bundle update` to resolve dependency conflict

### ISSUE THREAD

**Issue by Tschrock** [rubygems/rubygems#5555]
### Describe the problem as clearly as you can

I had some dependency issues, and `bundle update` suggests running `bundle update` to fix them.

> Running `bundle update` will rebuild your snapshot from scratch, using only the gems in your Gemfile, which may resolve the conflict.

Obviously this won't fix them since that's what I just ran...

I don't know enough about bundler to know if the update command should have fixed the dependency issues or not, but deleting `Gemfile.lock` does fix the issue. The output seems to indicate that `update` will ignore the lock file, so something might be amiss there?

### Post steps to reproduce the problem

<details><summary>Click to expand</summary>

Starting with a jekyll gemfile:
```rb
source "https://rubygems.org"

gem "jekyll", "~> 4.2.2"
# gem "github-pages", "~> 226", group: :jekyll_plugins
gem "minima", "~> 2.5"
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end
```

Installing:
```
$ bundle install
...
Bundle complete! 3 Gemfile dependencies, 101 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

Then swapping to github-pages in the gemfile:
```rb
source "https://rubygems.org"

# gem "jekyll", "~> 4.2.2"
gem "github-pages", "~> 226", group: :jekyll_plugins
gem "minima", "~> 2.5"
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end
```

Trying to install:
```
$ bundle install
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Bundler could not find compatible versions for gem "jekyll-feed":
  In snapshot (Gemfile.lock):
    jekyll-feed (>= 0.16.0)

  In Gemfile:
    jekyll-feed (~> 0.12)

    github-pages (~> 226) was resolved to 226, which depends on
      jekyll-feed (= 0.15.1)

    minima (~> 2.5) was resolved to 2.5.1, which depends on
      jekyll-feed (~> 0.9)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

Trying to update as suggested:
```
$ bundle update
<same output as bundle install>
```

Manually removing Gemfile.lock and reinstalling works:
```
$ rm Gemfile.lock
$ bundle install
...
Bundle complete! 3 Gemfile dependencies, 101 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

</details>

### Which command did you run?

`bundle update`

### What were you expecting to happen?

- Either the dependency issues should be resolved
- Or the output shouldn't recommend using the command I just used.

### What actually happened?

I got an error about dependency resolution and a recommendation to run the `bundle update` command.

### If not included with the output of your command, run `bundle env` and paste the output below

<details><summary>Click to expand</summary>

## Environment

```
Bundler       2.3.14
  Platforms   ruby, x86_64-linux
Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x86_64-linux]
  Full Path   /home/cyber/.rbenv/versions/3.1.2/bin/ruby
  Config Dir  /home/cyber/.rbenv/versions/3.1.2/etc
RubyGems      3.3.14
  Gem Home    /home/cyber/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0
  Gem Path    /home/cyber/.gem/ruby/3.1.0:/home/cyber/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0
  User Home   /home/cyber
  User Path   /home/cyber/.gem/ruby/3.1.0
  Bin Dir     /home/cyber/.rbenv/versions/3.1.2/bin
Tools         
  Git         2.34.1
  RVM         not installed
  rbenv       rbenv 1.2.0-14-gc6cc0a1
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-05-18
Git SHA           467ad58a7c
Released Version  true
```

### Gemfile

```ruby
source "https://rubygems.org"

# gem "jekyll", "~> 4.2.2"
gem "github-pages", "~> 226", group: :jekyll_plugins
gem "minima", "~> 2.5"
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    colorator (1.1.0)
    concurrent-ruby (1.1.10)
    em-websocket (0.5.3)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0)
    eventmachine (1.2.7)
    ffi (1.15.5)
    forwardable-extended (2.6.0)
    http_parser.rb (0.8.0)
    i18n (1.10.0)
      concurrent-ruby (~> 1.0)
    jekyll (4.2.2)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 1.0)
      jekyll-sass-converter (~> 2.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 2.3)
      kramdown-parser-gfm (~> 1.0)
      liquid (~> 4.0)
      mercenary (~> 0.4.0)
      pathutil (~> 0.9)
      rouge (~> 3.0)
      safe_yaml (~> 1.0)
      terminal-table (~> 2.0)
    jekyll-feed (0.16.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-sass-converter (2.2.0)
      sassc (> 2.0.1, < 3.0)
    jekyll-seo-tag (2.8.0)
      jekyll (>= 3.8, < 5.0)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    kramdown (2.4.0)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    liquid (4.0.3)
    listen (3.7.1)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    mercenary (0.4.0)
    minima (2.5.1)
      jekyll (>= 3.5, < 5.0)
      jekyll-feed (~> 0.9)
      jekyll-seo-tag (~> 2.1)
    pathutil (0.16.2)
      forwardable-extended (~> 2.6)
    public_suffix (4.0.7)
    rb-fsevent (0.11.1)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rexml (3.2.5)
    rouge (3.28.0)
    safe_yaml (1.0.5)
    sassc (2.4.0)
      ffi (~> 1.9)
    terminal-table (2.0.0)
      unicode-display_width (~> 1.1, >= 1.1.1)
    unicode-display_width (1.8.0)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  jekyll (~> 4.2.2)
  jekyll-feed (~> 0.12)
  minima (~> 2.5)

BUNDLED WITH
   2.3.14
```

</details>

**Comment by deivid-rodriguez** [comment]
Yes, the message should definitely be ignored when running `bundle update` itself.

And also, yes, the message is not fully accurate anyways, since `bundle update` does not fully ignore the lockfile, it still sets some lower bound requirements on the versions in the lockfile, to avoid actually downgrading any dependencies, so the conflicts might be coming from there. This is why `bundle install` works by (I guess) downgrading `jekyll-feed` to `0.15.1`.

Another improvement we could make is to make `bundle update` not put any lower bound requirements if resolution with those lower bound requirements fails, like in this case.

**Comment by zofrex** [comment]
Should `bundle update` emit a warning if "updating" ends up downgrading some dependencies to resolve conflicts? That seems like a counter-intuitive result that's possibly worth mentioning to the user.

**Comment by deivid-rodriguez** [comment]
Yes, it already prints a note like this when it happens:

> Note: <foo> version regressed from <locked_version> to <new_version>

But it currently only ever does that with indirect dependencies.

My proposal would be to also allow it as a last resort for direct dependencies too when:

* Running `bundle install` after a change in the `Gemfile`, like here.
* Running `bundle update <specific_dependency>`.

I don't think it makes sense to allow it for `bundle update` without explicit dependency targets, because upgrading some dependencies and downgrading others seems useless and not really a more up to date overall result.

**Comment by deivid-rodriguez** [comment]
#5581 will fix this!
