### ISSUE TITLE
WARNING:  Error fetching data: Errno::ETIMEDOUT: Connection timed out - connect(2) (http://rubygems.org/latest_specs.4.8.gz)

### ISSUE THREAD

**Issue by onknows** [rubygems/rubygems#557]
Suddenly gem install stopped working. No gem install gets thru anymore. All gems fail to install by timeout.

On Ubuntu 12.04. Using rvm. Ruby 1.9.3.

Strange thing is that I have a server on same network where it works. Gem install without problems. Ubuntu 12.04.1 LTS.

Also I have a virtual machine with Ubuntu. There it also works. 

It used to work fine on my laptop but something must have changed.

Anyway suggestions on how to fix this?

ostraaten@io:~$ gem install rspec
WARNING:  Error fetching data: Errno::ETIMEDOUT: Connection timed out - connect(2) (http://rubygems.org/latest_specs.4.8.gz)
ERROR:  Could not find a valid gem 'rspec' (>= 0) in any repository
ERROR:  Possible alternatives: rspec
ostraaten@io:~$

**Comment by vivek2007** [comment]
gem update --system
WARNING:  Error fetching data: Errno::ETIMEDOUT: Connection timed out - connect(2) (http://rubygems.org/latest_specs.4.8.gz)
Updating rubygems-update
WARNING:  Error fetching data: Errno::ETIMEDOUT: Connection timed out - connect(2) (http://rubygems.org/specs.4.8.gz)

**Comment by powerriegel** [comment]
Problem still up to date on current Ubuntu 19.10

```
user@thinkpad:~/Downloads/rubygems-3.0.6$ gem update --system
ERROR:  While executing gem ... (Gem::RemoteFetcher::UnknownHostError)
    **timed out (https://rubygems.org/specs.4.8.gz)**
user
3.0.6
uer@thinkpad:~/Downloads/rubygems-3.0.6$ ruby -v
ruby 2.5.5p157 (2019-03-15 revision 67260) [x86_64-linux-gnu]
```

In my browser it works fine so it's a `gem` related problem.
