### ISSUE TITLE
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

### ISSUE THREAD

**Issue by norikokono** [rubygems/rubygems#5599]
We couldn’t find any issues matching 'No space left on device @ rb_sysopen - /usr/share/rvm/gems/ruby-3.0.1/bundler.lock' in [rubygems/rubygems](https://github.com/rubygems/rubygems)
You could [search all of GitHub](https://github.com/search?q=No+space+left+on+device+%40+rb_sysopen+-+%2Fusr%2Fshare%2Frvm%2Fgems%2Fruby-3.0.1%2Fbundler.lock) or try an [advanced search](https://github.com/search/advanced?q=No+space+left+on+device+%40+rb_sysopen+-+%2Fusr%2Fshare%2Frvm%2Fgems%2Fruby-3.0.1%2Fbundler.lock).

https://github.com/rubygems/rubygems/search?q=No+space+left+on+device+%40+rb_sysopen+-+%2Fusr%2Fshare%2Frvm%2Fgems%2Fruby-3.0.1%2Fbundler.lock&type=Issues

**Comment by indirect** [comment]
Your hard drive is out of space.

**Comment by norikokono** [comment]
Hello indirect, Thank you so much for your quick response. I found somehow I created another copy file inside of the file. This was my learning material when I was attending Bootcamp last year. I was trying to fix the security issue of repos today and I tried to fix the wrong file. I didn't know I made such a disorganized error. Thank you so much for your time and for offering me your input.
