### ISSUE TITLE
Gentoo ebuild error

### ISSUE THREAD

**Issue by prismz** [rubygems/rubygems#5600]
The Gentoo ebuild seems to call "rdoc" instead of "rdoc-2", and doesn't register `dev-ruby/rdoc` as a dependency. After installing `dev-ruby/rdoc` and creating a shell script in `/usr/local/bin` (effectively aliasing rdoc as rdoc-2), the package builds as normal.

**Comment by deivid-rodriguez** [comment]
This seems like a gentoo specific issue to me. Can you report this at https://bugs.gentoo.org/?

I'll close this but let me know if this is not correct.
