### ISSUE TITLE
`bundle install' fails on 2.3.15; succeeds on 2.3.13

### ISSUE THREAD

**Issue by slondr** [rubygems/rubygems#5605]
### Describe the problem as clearly as you can

I ran `bundle install` in my project which has a dependency on mini_racer 0.6.2. It failed with an error saying that it couldn't find an archive file in a directory referencing musl (my system uses glibc), followed by a series of errors about missing symbols (presumably defined in that archive).

It's the exact same error someone else posted here: https://github.com/rubyjs/mini_racer/issues/234

### Did you try upgrading rubygems & bundler?

Updating bundler caused the error. Downgrading to bundler 2.3.13 and re-running `bundle install` resulted in a successful installation.

### Post steps to reproduce the problem

I'm using Ruby 2.7.5 installed via RVM.

### Which command did you run?

`bundle install`

### What were you expecting to happen?

Dependencies install successfully.

### What actually happened?

Compilation errors; see link I posted above.

**Comment by deivid-rodriguez** [comment]
Thanks for the report @slondr. So this is reproducible with a `Gemfile` including only `mini_racer-0.6.2` on Linux, or does it need something more complicated? Also, can you bisect the exact change that caused this? Thanks!

**Comment by slondr** [comment]
Yeah, I can reproduce this in a fresh ruby-2.7 docker image with the following gemfile:
```ruby
source "https://rubygems.org"
ruby "2.7.5"
gem "mini_racer", "0.6.2"
```

Running `bundle install` fails as it tries to install musl dependencies instead of glibc dependencies

**Comment by deivid-rodriguez** [comment]
I tried with official ruby:2.7.5 docker image and the `Gemfile` you posted and everything worked correctly. Can you share docker commands and/or Dockerfiles to reproduce this? Thanks!

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
