### ISSUE TITLE
export `bundler/setup` as method in `bundler` to allow customizing groups

### ISSUE THREAD

**Issue by DocX** [rubygems/rubygems#5617]
### Describe the problem as clearly as you can

Using

```rb
require "bundler/setup"
```

gives the nice UI when any dependency is missing.

However it is hardcoded to setup all groups.

If I want to setup only `:default` group but keep the nice UI for the bundler errors, I would need to rip-off the code from `bundler/setup` file:

```rb
require "bundler"
begin
  Bundler.ui.silence { Bundler.setup(:default) }
rescue Bundler::BundlerError => e
  Bundler.ui.error e.message
  Bundler.ui.warn e.backtrace.join("\n") if ENV["DEBUG"]
  if e.is_a?(Bundler::GemNotFound)
    Bundler.ui.warn "Run `bundle install` to install missing gems."
  end
  exit e.status_code
end
```

Could we export the `bundler/setup` code to e.g. `Bundler.friendly_setup(*groups)`. So it would be possible to just have this code:
```rb
require "bundler"
Bundler.friendly_setup(:default)
```

Alternatively, should `bundler/setup` respect `BUNDLER_WITH` / `BUNDLER_WITHOUT` environment variables?

**Comment by simi** [comment]
I'm not sure about the method name, but I do agree we can wrap all `bundle/setup` logic into method on `Bundler` and call it with `:default` group in there also exposing `Bundler.some_name_setup(groups)` for custom usage.

Would you mind to contribute this @DocX?

**Comment by DocX** [comment]
Let me try

**Comment by simi** [comment]
@DocX feel free to join us at bundler slack if help is needed.

**Comment by DocX** [comment]
> I thought this worked already... 🤔.

From my experiment it does not. I was trying to look at the code and I also could not find where would it read the ENV var. The `Bundler.setup` indirectly calls this in the `Runtime`:

https://github.com/rubygems/rubygems/blob/2491b5905776979ad407b0922302a6966530d4a2/bundler/lib/bundler/definition.rb#L239

where the `groups` is passed from `Bundler.setup` arguments. So if I read it correctly, it is hardcoded that without calling groups in arguments it always gets all gems?

**Comment by deivid-rodriguez** [comment]
You're totally right, I think we should fix it.

**Comment by DocX** [comment]
It does not look to work properly 🤔 


With this code:

```rb
require "bundler"
puts "Bundler.settings[:without]: #{Bundler.settings[:without]}"
puts "Bundler.definition.send(:requested_groups): #{Bundler.definition.send(:requested_groups)}"
```

Running
```
BUNDLE_WITHOUT=development bin/my_command
```

Prints
```
Bundler.settings[:without]: [:development]
Bundler.definition.send(:requested_groups): [:default, :development]
```

**Comment by deivid-rodriguez** [comment]
Closing since there was no answer and the related PR was closed.
