### ISSUE TITLE
Bundle install is okay, but it always showed install missing gems

### ISSUE THREAD

**Issue by ARIEnergy** [rubygems/rubygems#5633]
### Did you try upgrading rubygems & bundler?
Nope , I use the latest bundler and then run it on Mac 

### Which command did you run?

bundle exec pod install

### What were you expecting to happen?
I truly hope it worked well 

### What actually happened?
It failed, showed missing gem 

## Environment

```
Bundler       1.17.2
  Platforms   ruby, universal-darwin-21
Ruby          2.6.8p205 (2021-07-07 revision 67951) [universal.arm64e-darwin21]
  Full Path   /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
  Config Dir  /Library/Ruby/Site
RubyGems      3.0.3.1
  Gem Home    /Library/Ruby/Gems/2.6.0
  Gem Path    /Users/marczhao/.gem/ruby/2.6.0:/Library/Ruby/Gems/2.6.0:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
  User Path   /Users/marczhao/.gem/ruby/2.6.0
  Bin Dir     /usr/local/bin
Tools
  Git         2.35.1
  RVM         1.29.12 (latest)
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2018-12-19
Git SHA           3fc4de72b
Released Version  false
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem 'cocoapods', '1.11.3'
gem 'cocoapods-pod-merge', :path => '../'
```

### Gemfile.lock

```
PATH
  remote: ..
  specs:
    cocoapods-pod-merge (0.0.4)

GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (3.0.5)
      rexml
    activesupport (6.1.5)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
      zeitwerk (~> 2.3)
    addressable (2.8.0)
      public_suffix (>= 2.0.2, < 5.0)
    algoliasearch (1.27.5)
      httpclient (~> 2.8, >= 2.8.3)
      json (>= 1.5.1)
    atomos (0.1.3)
    claide (1.1.0)
    cocoapods (1.11.3)
      addressable (~> 2.8)
      claide (>= 1.0.2, < 2.0)
      cocoapods-core (= 1.11.3)
      cocoapods-deintegrate (>= 1.0.3, < 2.0)
      cocoapods-downloader (>= 1.4.0, < 2.0)
      cocoapods-plugins (>= 1.0.0, < 2.0)
      cocoapods-search (>= 1.0.0, < 2.0)
      cocoapods-trunk (>= 1.4.0, < 2.0)
      cocoapods-try (>= 1.1.0, < 2.0)
      colored2 (~> 3.1)
      escape (~> 0.0.4)
      fourflusher (>= 2.3.0, < 3.0)
      gh_inspector (~> 1.0)
      molinillo (~> 0.8.0)
      nap (~> 1.0)
      ruby-macho (>= 1.0, < 3.0)
      xcodeproj (>= 1.21.0, < 2.0)
    cocoapods-core (1.11.3)
      activesupport (>= 5.0, < 7)
      addressable (~> 2.8)
      algoliasearch (~> 1.0)
      concurrent-ruby (~> 1.1)
      fuzzy_match (~> 2.0.4)
      nap (~> 1.0)
      netrc (~> 0.11)
      public_suffix (~> 4.0)
      typhoeus (~> 1.0)
    cocoapods-deintegrate (1.0.5)
    cocoapods-downloader (1.6.3)
    cocoapods-plugins (1.0.0)
      nap
    cocoapods-search (1.0.1)
    cocoapods-trunk (1.6.0)
      nap (>= 0.8, < 2.0)
      netrc (~> 0.11)
    cocoapods-try (1.2.0)
    colored2 (3.1.2)
    concurrent-ruby (1.1.10)
    escape (0.0.4)
    ethon (0.15.0)
      ffi (>= 1.15.0)
    ffi (1.15.5)
    fourflusher (2.3.1)
    fuzzy_match (2.0.4)
    gh_inspector (1.1.3)
    httpclient (2.8.3)
    i18n (1.10.0)
      concurrent-ruby (~> 1.0)
    json (2.6.1)
    minitest (5.15.0)
    molinillo (0.8.0)
    nanaimo (0.3.0)
    nap (1.1.0)
    netrc (0.11.0)
    public_suffix (4.0.7)
    rexml (3.2.5)
    ruby-macho (2.5.1)
    typhoeus (1.4.0)
      ethon (>= 0.9.0)
    tzinfo (2.0.4)
      concurrent-ruby (~> 1.0)
    xcodeproj (1.21.0)
      CFPropertyList (>= 2.3.3, < 4.0)
      atomos (~> 0.1.3)
      claide (>= 1.0.2, < 2.0)
      colored2 (~> 3.1)
      nanaimo (~> 0.3.0)
      rexml (~> 3.2.4)
    zeitwerk (2.5.4)

PLATFORMS
  ruby

DEPENDENCIES
  cocoapods (= 1.11.3)
  cocoapods-pod-merge!

BUNDLED WITH
   1.17.3
```

**Comment by ARIEnergy** [comment]
@hsbt  Why close this issue? It has relationship with bundle , so hope you can check it ,thank you so much!

**Comment by hsbt** [comment]
@ARIEnergy Sorry, I didn't fill out the issue report when you opened this. We always faced the empty report.

**Comment by ARIEnergy** [comment]
`Could not find fastlane-2.206.2, cocoapods-pod-merge-0.0.4, artifactory-3.0.15, aws-sdk-s3-1.114.0, babosa-1.0.4, colored-1.2, commander-4.6.0, dotenv-2.7.6, emoji_regex-3.2.3, excon-0.92.3, faraday-1.10.0, faraday-cookie_jar-0.0.7, faraday_middleware-1.2.0, fastimage-2.2.6, google-apis-androidpublisher_v3-0.22.0, google-apis-playcustomapp_v1-0.8.0, google-cloud-storage-1.36.2, highline-2.0.3, json-2.6.2, jwt-2.4.1, mini_magick-4.11.0, multipart-post-2.0.0, naturally-2.2.1, optparse-0.1.1, plist-3.6.0, rubyzip-2.3.2, security-0.1.3, simctl-1.6.8, terminal-notifier-2.0.0, terminal-table-1.8.0, tty-screen-0.8.1, tty-spinner-0.9.3, word_wrap-1.0.0, xcpretty-0.3.0, xcpretty-travis-formatter-1.0.1, public_suffix-4.0.7, aws-sdk-core-3.131.1, aws-sdk-kms-1.57.0, aws-sigv4-1.5.0, faraday-em_http-1.0.0, faraday-em_synchrony-1.0.0, faraday-excon-1.1.0, faraday-httpclient-1.0.1, faraday-multipart-1.0.4, faraday-net_http-1.0.1, faraday-net_http_persistent-1.2.0, faraday-patron-1.0.0, faraday-rack-1.0.0, faraday-retry-1.0.3, http-cookie-1.0.5, google-apis-core-0.6.0, digest-crc-0.6.4, google-apis-iamcredentials_v1-0.11.0, google-apis-storage_v1-0.15.0, google-cloud-core-1.6.0, googleauth-1.1.3, mini_mime-1.1.2, unicode-display_width-1.8.0, tty-cursor-0.7.1, rouge-2.0.7, aws-eventstream-1.2.0, aws-partitions-1.598.0, jmespath-1.6.1, domain_name-0.5.20190701, representable-3.2.0, retriable-3.1.2, webrick-1.7.0, google-cloud-env-1.6.0, google-cloud-errors-1.2.0, memoist-0.16.2, multi_json-1.15.0, os-1.1.4, signet-0.16.1, unf-0.1.4, declarative-0.0.20, trailblazer-option-0.1.2, uber-0.1.0, unf_ext-0.0.8.2 in any of the sources
Run `bundle install` to install missing gems.`

**Comment by deivid-rodriguez** [comment]
@ARIEnergy Please make sure you upgrade Bundler and RubyGems. Latest version of Bundler is 2.3.16 but you are using 1.17.2. Similarly, latest version of RubyGems is 3.3.16, but you are using 3.0.3.1. It's likely that this has been fixed in the latest versions. If you are still experiencing this issue after upgrading, please reopen this ticket posting the new output of the error and the result of `bundle env`. Thanks!
