### ISSUE TITLE
pacman is locked if multiple packages need to be installed

### ISSUE THREAD

**Issue by hurricup** [rubygems/rubygems#5634]
- OS: Windows 10
- Ruby: 2.4. (most recent)
- Bundler: 2.3.15

Scenario: 
- rails app created with `--database=sqlite3 --skip-bundle`
- then run `bundle install`

In the bundler verbose log i can see:
```
...
10:25:06,218 stdout: Fetching puma 3.12.6
10:25:06,358 stdout: Installing puma 3.12.6 with native extensions
10:25:06,417 stdout: Installing required msys2 packages: mingw-w64-x86_64-openssl
10:25:13,798 stdout: 0:  byebug (11.1.3) from C:/Users/builduser/.local/share/gem/ruby/2.4.0/specifications/byebug-11.1.3.gemspec
10:25:13,798 stdout: Fetching rb-fsevent 0.11.1
10:25:13,918 stdout: Installing rb-fsevent 0.11.1
10:25:13,965 stdout: 0:  rb-fsevent (0.11.1) from C:/Users/builduser/.local/share/gem/ruby/2.4.0/specifications/rb-fsevent-0.11.1.gemspec
10:25:13,965 stdout: Fetching rubyzip 2.3.2
10:25:14,055 stdout: Installing rubyzip 2.3.2
10:25:14,129 stdout: RubyZip 3.0 is coming!
10:25:14,129 stdout: **********************
10:25:14,129 stdout: 
10:25:14,129 stdout: The public API of some Rubyzip classes has been modernized to use named
10:25:14,129 stdout: parameters for optional arguments. Please check your usage of the
10:25:14,129 stdout: following classes:
10:25:14,129 stdout: * `Zip::File`
10:25:14,129 stdout: * `Zip::Entry`
10:25:14,129 stdout: * `Zip::InputStream`
10:25:14,129 stdout: * `Zip::OutputStream`
10:25:14,129 stdout: 
10:25:14,129 stdout: Please ensure that your Gemfiles and .gemspecs are suitably restrictive
10:25:14,129 stdout: to avoid an unexpected breakage when 3.0 is released (e.g. ~> 2.3.0).
10:25:14,129 stdout: See https://github.com/rubyzip/rubyzip for details. The Changelog also
10:25:14,129 stdout: lists other enhancements and bugfixes that have been implemented since
10:25:14,129 stdout: version 2.3.0.
10:25:14,129 stdout: 0:  rubyzip (2.3.2) from C:/Users/builduser/.local/share/gem/ruby/2.4.0/specifications/rubyzip-2.3.2.gemspec
10:25:14,129 stdout: Fetching tilt 2.0.10
10:25:14,223 stdout: Installing tilt 2.0.10
10:25:14,298 stdout: 0:  tilt (2.0.10) from C:/Users/builduser/.local/share/gem/ruby/2.4.0/specifications/tilt-2.0.10.gemspec
10:25:14,298 stdout: Fetching sqlite3 1.4.4
10:25:14,383 stdout: Installing sqlite3 1.4.4 with native extensions
10:25:14,443 stdout: Installing required msys2 packages: mingw-w64-x86_64-sqlite3
10:25:15,586 stderr: error: failed to init transaction (unable to lock database)
10:25:15,586 stderr: error: could not lock database: File exists
10:25:15,586 stderr: if you're sure a package manager is not already
10:25:15,586 stderr: running, you can remove /var/lib/pacman/db.lck
10:25:15,590 stdout: pacman failed with the following output:
10:25:15,718 stdout: Building native extensions. This could take a while...
10:25:18,653 stdout: Fetching turbolinks-source 5.2.0
...
```

As in most cases, happens every time on CI. And looks like first installation didn't finish (at all or correctly). 
Unfortunately there is no additional information in the log from `pacman` invocations.

This looks like a race between pacman invocations or bad error handling of first invocation, if it failed left locked database. 

Will try to reproduce this locally.

**Comment by hurricup** [comment]
I can't remove openssl package in my msys2, because of tons of reverse dependencies :)

**Comment by MSP-Greg** [comment]
@hurricup

> As in most cases, happens every time on CI

What CI is being used?  You may need to update MSYS2 before `bundle install`.  Also, Windows Ruby 2.4.x builds use OpenSSL 1.0.2, and the current MSYS2 package is OpenSSL 1.1.1 (discussions have started about updating to OpenSSL 3.0.x).  The current MSYS2 MinGW64 build tools have gone thru several version updates, and may cause issues.

So, if you have to use Ruby 2.4, you'll need to load OpenSSL 1.0.2 by downloading and installing the package.  The package exists in a few releases on GitHub.  I've archived it at https://github.com/MSP-Greg/ruby-loco/releases/tag/old-ruby.

Finally, current versions of puma & sqlite3 are tested against Ruby 2.4.

This really isn't a Bundler/RubyGems issue...

**Comment by hurricup** [comment]
@MSP-Greg i disagree. We have no compilation error or missing library error.
We have a pacman locked error. This means:

1. `openssl` installation failed and was not properly reported by the bundler so user could perform appropriate action to fix it.
2. `openssl` installation was not finished when bundler attempted to install another msys2 package.

Maybe `rubygems` responsible for some of theese, I can't be sure, but still. There is no question like `how to install/run rails on ruby 2.4`

**Comment by MSP-Greg** [comment]
@hurricup

Bundler and/or RubyGems do not install packages needed to compile extension gems.  All the code that is causing the issue is contained in the RubyInstaller2 runtime.

The reason the packages are being installed is due to the gemspec metadata key `msys2_mingw_dependencies`, which exists in the two extension gems (puma & sqlite3) that being installed.  The metadata key `msys2_mingw_dependencies` was added as a convenience, it was not meant to fix an outdated package management system.

Given that you're using an old EOL Ruby and old gems, and just like on an *nix or macOS system, you need to get the packages installed before you run 'bundle install`...

**Comment by MSP-Greg** [comment]
There have been many changes in the last year with MSYS2, including the download servers and signing keys.  Also, zst packages are now being used, previously they were 7z.

If your MSYS2 install is as old as Ruby 2.4, it may need a full update.

**Comment by hurricup** [comment]
@MSP-Greg oh, thank you for the clarification. May be I should address this issue to the rubyinstaller2 then.

I believe it's up to date. We have all rubies 2.4+ installed on  the system with the same msys installation. 

Anyway, i can install `sqlite3` with `gem install` from the command line without any problems. will try with puma and see what will happen.

**Comment by hurricup** [comment]
Yes, that was my initial assumption:
> This looks like a race between pacman invocations or bad error handling of first invocation, if it failed left locked database.

Would be nice if `bundler` wrote in `verbose` log how many workers are used. Is there way to check how many of them and why? I was thinking it should be explicitly configured somewhere.

**Comment by deivid-rodriguez** [comment]
Bundler defaults to using as many workers as available processors (`Etc.nprocessors`) _unless_ jobs is explicitly configured.

**Comment by deivid-rodriguez** [comment]
> Would be nice if bundler wrote in verbose log how many workers are used

I'm fine with adding this information in verbose mode 👍.

**Comment by hurricup** [comment]
> Bundler defaults to using as many workers as available processors (Etc.nprocessors) unless jobs is explicitly configured.

Then I'm sure that's it. And because of this case, probably it's not so good idea for Windows (irr this auto-dependencies installation works only for windows, for others we have just  compilation error)

Or this `pacman` lock error could be handled somehow , with like helpful message (if `bundler` have an access to it). 

As usual - thank for your help!!!

**Comment by MSP-Greg** [comment]
Re Puma, I don't think it will work.  If you don't need ssl connections, set ENV['DISABLE_SSL'], which will compile Puma without OpenSSL support.

If you do need ssl connections, you need to upgrade to Ruby 2.5 or later.  From the log, you're compiling with OpenSSL 1.1.1, but Ruby's OpenSSL is compiled with 1.0.2, and 1.0.2 dll's are included in its install.  Bad idea, with unknown consequences...

JFYI, I watch rubygems, but I'm also familiar with Puma, OpenSSL, MSYS2, etc.

**Comment by deivid-rodriguez** [comment]
> Then I'm sure that's it. And because of this case, probably it's not so good idea for Windows (irr this auto-dependencies installation works only for windows, for others we have just compilation error)

I just recalled that we skipped this behaviour on Windows for a while because it was causing other issues, but we ended up enabling it in the end: https://github.com/rubygems/rubygems/pull/4822. Maybe that was premature after all.

**Comment by hurricup** [comment]
Well, if it is a first report in almost a year and for ancient ruby version, guess it's just fine.
These old rubies always giving a headache with something.

**Comment by deivid-rodriguez** [comment]
Yeah, but I did see the flaky CI failure that I thought was fixed again. Although just a couple of times in a very long time, and end users have not reported anything (apart from this one issue).

**Comment by hurricup** [comment]
Well, now we found at least one case and it's symptom :D

**Comment by MSP-Greg** [comment]
> build is not failing to prevent such consequences

The complexity blows up quick with extension gems, std-lib extensions, etc.  Build/compile dependencies (like the mingw64 packages) vary quite a bit in how they're handled by various OS's.  Old gems/Rubies may have been released before current package versions existed.

For instance, with MSYS2, there can only be one install of OpenSSL.  Other OS's allow one to install (and link to) multiple OpenSSL installs.  But, it's tricky, and easy to make a mess of things.  For a while, I had both OpenSSL 3.0.x and 1.1.1 installed on Ubuntu 20.04, and I screwed it up now and then.  I yanked 3.0.x when I installed Ubuntu 22.04.

**Comment by deivid-rodriguez** [comment]
Is this still an issue?

**Comment by hurricup** [comment]
can't say for sure. we have some workarounds on the ci with custom pacman installations. Can check if you need.

**Comment by deivid-rodriguez** [comment]
Sure, if you can check I appreciate it!

**Comment by hurricup** [comment]
I can't reproduce this anymore. Feel free to close it. Will get back if happens again. Thanks!
