### ISSUE TITLE
Running gem generate_index --update does not clean up temporary directories

### ISSUE THREAD

**Issue by graywolf-at-work** [rubygems/rubygems#5635]
I'm having a problem or would like to suggest a feature.

My current problem is that running gem generate_index --update does not clean up temporary directories after itself.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [ ] Publishing a library
  - [x] The command line `gem`
  - [ ] Other

Here are my current environment details:

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.7
  - RUBY VERSION: 3.1.2 (2022-04-12 patchlevel 20) [x86_64-linux-musl]
  - INSTALLATION DIRECTORY: /usr/lib/ruby/gems/3.1.0
  - USER INSTALLATION DIRECTORY: XXXXXXXXXXXXXXXXXXXX
  - RUBY EXECUTABLE: /usr/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/bin
  - SPEC CACHE DIRECTORY: XXXXXXXXXXXXXXXXXXXXXXXXXX
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /usr/lib/ruby/gems/3.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /bin
     - /usr/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /sbin
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by deivid-rodriguez** [comment]
Thank you!

**Comment by deivid-rodriguez** [comment]
@graywolf-at-work Interestingly, I can't reproduce the issue running the commands you posted on my system. Can you provide a `Dockerfile` that reproduces this independently? Also, can you try upgrading RubyGems just in case? I don't recall any fixes related to this, but just in case.

**Comment by deivid-rodriguez** [comment]
Thanks @graywolf-at-work!

I couldn't repro the issue because my system has a different default temp folder that's not `/tmp`. Anyways, I think you're right. I think you can double check by manually adding the rescue clause to `update_index` and see if that fixes the issue. If yes, I'm happy to take a PR :)

**Comment by deivid-rodriguez** [comment]
You don't explicitly need to sign any CLA. By contributing you implicitly agree to our license, code of conduct, and so on. Is that ok for you?
