### ISSUE TITLE
Invisible gems?

### ISSUE THREAD

**Issue by pboling** [rubygems/rubygems#5636]
I published a new gem via the cli, but it is not found by bundler, and is not listed on rubygems.org.

This issue is related to:

  - [ ] Network problems
  - [ ] Installing a library
  - [x] Publishing a library
  - [ ] The command line `gem`
  - [ ] Other

I can't understand how this is possible, as other gems are being published.

The gem source is at https://github.com/pboling/gem_ver.

The gem name is `gem_ver`.

I have published multiple versions "successfully", yet the gem can't be found by direct URL access, by search, by `gem install` or `bundle install`.

`gem search gem_ver` gives:

```
$ gem search gem_ver

*** REMOTE GEMS ***

bundler-gem_version_tasks (0.2.1)
gem_version (0.0.6)
gem_version_check (0.5.2)
gem_version_trainer (1.0.0)
gem_version_wrapper (1.0.0)
```

Here are my current environment details:

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.16
  - RUBY VERSION: 3.1.2 (2022-04-12 patchlevel 20) [arm64-darwin21]
  - INSTALLATION DIRECTORY: /Users/pboling/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0
  - USER INSTALLATION DIRECTORY: /Users/pboling/.gem/ruby/3.1.0
  - RUBY EXECUTABLE: /Users/pboling/.asdf/installs/ruby/3.1.2/bin/ruby
  - GIT EXECUTABLE: /opt/homebrew/opt/git/bin/git
  - EXECUTABLE DIRECTORY: /Users/pboling/.asdf/installs/ruby/3.1.2/bin
  - SPEC CACHE DIRECTORY: /Users/pboling/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/pboling/.asdf/installs/ruby/3.1.2/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - arm64-darwin-21
  - GEM PATHS:
     - /Users/pboling/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0
     - /Users/pboling/.gem/ruby/3.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :benchmark => false
     - :sources => ["http://rubygems.org"]
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - http://rubygems.org
  - SHELL PATH:
     - /Users/pboling/.asdf/installs/ruby/3.1.2/bin
     - /Users/pboling/.asdf/shims
     - /opt/homebrew/opt/asdf/libexec/bin
     - /usr/local/heroku/bin
     - /Users/pboling/.yarn/bin
     - /Users/pboling/.config/yarn/global/node_modules/.bin
     - /bin
     - /Library/Java/JavaVirtualMachines/jdk-13.0.2.jdk/Contents/Home/bin
     - /opt/homebrew/opt/icu4c/sbin
     - /opt/homebrew/opt/icu4c/bin
     - /Users/pboling/.cargo/bin
     - /opt/homebrew/opt/git/bin/
     - /opt/homebrew/bin
     - /opt/homebrew/sbin
     - /Users/pboling/bin
     - /Users/pboling/.bin
     - /Users/pboling/.local/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Applications/VMware Fusion Tech Preview.app/Contents/Public
     - /usr/local/MacGPG2/bin
     - /opt/X11/bin
     - /Library/Apple/usr/bin
     - /Users/pboling/.ec2/tools/bin
     - /Users/pboling/go/bin
     - /opt/homebrew/opt/go/libexec/bin
```

I will abide by the [code of conduct](https://github.com/rubygems/rubygems/blob/master/CODE_OF_CONDUCT.md).

**Comment by simi** [comment]
@pboling hello. I have seen your support request as well. Let's continue in here. Are you 100% sure you have pushed this to rubygems.org? Can you paste the push output (please redact any private info in there).

**Comment by pboling** [comment]
Aha!  I did get an error.
```
There was a problem saving your gem: Name 'gem_ver' is too similar to an existing gem named 'gemver'
```
I use the gem `gem-release` to bump / release / tag, and it didn't surface the issue in a way that I noticed, so that is a bug.  I guess I will have to rename my project. :(

**Comment by pboling** [comment]
@simi Separately - it is interesting that the search did not return the gem that actually caused the "name conflict".
```
$ gem search gem_ver

*** REMOTE GEMS ***

bundler-gem_version_tasks (0.2.1)
gem_version (0.0.6)
gem_version_check (0.5.2)
gem_version_trainer (1.0.0)
gem_version_wrapper (1.0.0)
```

It doesn't show `gem_ver`.  I think if it had it would have helped me discover the problem on my own.  I realize it is no longer a simple text match search if you start including "sounds like"-type results, so that may be a non-starter, but interesting nonetheless.

**Comment by simi** [comment]
@pboling that's actually good idea. If I remember well the logic lives at https://github.com/rubygems/rubygems.org/blob/master/app/models/gem_typo.rb. We can use similar patterns to search for gems.
