### ISSUE TITLE
The --format-executable option doesn't seem to work

### ISSUE THREAD

**Issue by djberg96** [rubygems/rubygems#5637]
* ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [x86_64-darwin21]
* rbenv 1.2.0

Quick backstory, we have a minor conflict between the `tilt` gem (which installs a `tilt` executable) and the unrelated `tilt` microservices command line tool (https://docs.tilt.dev/cli/tilt.html). To work around it, I thought I would use the `--format-executable` option so that it installed the gem exectuable as `tilt311`.

Either I don't understand the option, or something is broke:

`gem install tilt --format-executable`

What I expect: a `tilt311` executable to be installed.
What I got: a plain `tilt` executable installed.

`>which tilt -> /Users/dberger/.rbenv/shims/tilt`

In addition, when I chose to `gem uninstall tilt`, it refused to remove the executable, even after selecting 'Y':

```
>gem uninstall tilt

You have requested to uninstall the gem:
	tilt-2.0.10

sass-rails-5.1.0 depends on tilt (>= 1.1, < 3)
sinatra-2.1.0 depends on tilt (~> 2.0)
sinatra-contrib-2.1.0 depends on tilt (~> 2.0)
If you remove this gem, these dependencies will not be met.
Continue with Uninstall? [yN]  y
Remove executables:
	tilt

in addition to the gem? [Yn]  y
Removing tilt
Successfully uninstalled tilt-2.0.10

# And yet...
>which tilt -> /Users/dberger/.rbenv/shims/tilt
```

Output of `gem env`:

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.16
  - RUBY VERSION: 3.1.1 (2022-02-18 patchlevel 18) [x86_64-darwin21]
  - INSTALLATION DIRECTORY: /Users/dberger/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0
  - USER INSTALLATION DIRECTORY: /Users/dberger/.gem/ruby/3.1.0
  - RUBY EXECUTABLE: /Users/dberger/.rbenv/versions/3.1.1/bin/ruby
  - GIT EXECUTABLE: /usr/local/bin/git
  - EXECUTABLE DIRECTORY: /Users/dberger/.rbenv/versions/3.1.1/bin
  - SPEC CACHE DIRECTORY: /Users/dberger/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/dberger/.rbenv/versions/3.1.1/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-darwin-21
  - GEM PATHS:
     - /Users/dberger/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0
     - /Users/dberger/.gem/ruby/3.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :benchmark => false
     - :install => "-b --conservative --minimal-deps --env-shebang"
     - :sources => ["https://rubygems.org/"]
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/dberger/.rbenv/versions/3.1.1/bin
     - /usr/local/Cellar/rbenv/1.2.0/libexec
     - /usr/local/opt/llvm/bin
     - /Users/dberger/.rbenv/shims
     - /usr/local/opt/icu4c/bin
     - /usr/local/opt/icu4c/sbin
     - /usr/local/opt/postgresql@13/bin
     - /usr/local/sbin
     - /Users/dberger/.rbenv/bin
     - /usr/local/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /Applications/VMware Fusion.app/Contents/Public
     - /Library/TeX/texbin
     - /Library/Apple/usr/bin
     - /Applications/Wireshark.app/Contents/MacOS
     - /usr/local/opt/icu4c/bin
     - /usr/local/opt/icu4c/sbin
     - /usr/local/opt/postgresql@13/bin
     - /usr/local/sbin
     - /Users/dberger/.rbenv/bin
     - /Users/dberger/golang/bin
     - /usr/local/opt/go@1.16/libexec/bin
     - /Users/dberger/golang/bin
     - /usr/local/opt/go@1.16/libexec/bin
```

**Comment by deivid-rodriguez** [comment]
@djberg96 `--format-executable` makes RubyGems respect the format in `RbConfig::CONFIG["ruby_install_name"]`. So if your ruby was installed as `ruby3.1`, then executables installed by RubyGems will match that convention and get installed as `tilt3.1`. But it sounds like you Ruby installation is standard and your Ruby executable is named just `ruby`, so your idea is not going to work I'm afraid. I'm not sure how this options behaves in presence of Rbenv shims anyways.

**Comment by djberg96** [comment]
@deivid-rodriguez Hm, how would you feel about falling back to appending a stringified `RbConfig::CONFIG['ruby_version']` if there's no digit found in `RbConfig::CONFIG['ruby_install_name']`?

Maybe as a subcommand option? Something like:

`gem install --format-executable --force-version tilt`

Another idea I had was to disallow installing rubygem executables completely.

`gem install --no-executables tilt`

How often do folks need rubygem executables in a production deployment. I would think it would be pretty rare. Or is this possible already via rubygems and/or bundler?

**Comment by deivid-rodriguez** [comment]
From the suggestions you propose, I guess I'd go with `--no-executables`? I don't want to change `--format-executables`  behavior because the current one makes sense to me and I could image people depending on it.

**Comment by djberg96** [comment]
@deivid-rodriguez Ok, I like the --no-executables option.

I'm wondering if this could be done as a plugin. Can you strip out spec contents in a `Gem.pre_install`?

**Comment by djberg96** [comment]
@deivid-rodriguez Oh, forgot to ask, is the fact that it's not uninstalling the executable when I do `gem uninstall` a bug? Or am I not understanding something there as well?

**Comment by deivid-rodriguez** [comment]
> Can you strip out spec contents in a Gem.pre_install?

Not sure.

> Oh, forgot to ask, is the fact that it's not uninstalling the executable when I do gem uninstall a bug? Or am I not understanding something there as well?

I think that would be a Rbenv issue, that's not rehashing shims after `gem uninstall`. I think you could workaround it by running `rbenv rehash` manually.

**Comment by djberg96** [comment]
> I think that would be a Rbenv issue, that's not rehashing shims after gem uninstall. I think you could workaround it by running rbenv rehash manually.

Oh, wow, you're right: https://github.com/rbenv/rbenv/issues/548.

In my case I had a `tilt` install in a different version of Ruby that I had installed, so it repointed to that, yikes. I don't like that behavior, but at least now I know what's happening.

Alright, closing this one one since the first issue is expected behavior, and the second is an rbenv issue. Thanks for your time!

**Comment by djberg96** [comment]
For anyone following, this one-liner seems to do the trick. You can put this directly in your Gemfile:

```ruby
Gem.pre_install{ |installer| installer.spec.executables = [] }
```
