### ISSUE TITLE
Push bundler-v2.0.2 and bundler-v2.1.4 tags to GitHub

### ISSUE THREAD

**Issue by tnir** [rubygems/rubygems#5646]
### Describe the problem as clearly as you can

We cannot find bundler-v2.0.2 and bundler-v2.1.4 tags in https://github.com/rubygems/rubygems/tags unlike [bundler-v2.2.33](https://github.com/rubygems/rubygems/releases/tag/bundler-v2.2.33) (and later) and [bundler-v1.17.3](https://github.com/rubygems/rubygems/releases/tag/bundler-v1.17.3) (and earlier).

Full list of missing version tag on Git repo follows:

- [2.1.4](https://rubygems.org/gems/bundler/versions/2.1.4) - January 05, 2020 (388KB)
- [2.1.3](https://rubygems.org/gems/bundler/versions/2.1.3) - January 02, 2020 (388KB)
- [2.1.2](https://rubygems.org/gems/bundler/versions/2.1.2) - December 20, 2019 (388KB)
- [2.1.1](https://rubygems.org/gems/bundler/versions/2.1.1) - December 18, 2019 (388KB)
- [2.1.0](https://rubygems.org/gems/bundler/versions/2.1.0) - December 15, 2019 (387KB)
- [2.0.2](https://rubygems.org/gems/bundler/versions/2.0.2) - June 13, 2019 (358KB)
- [2.0.1](https://rubygems.org/gems/bundler/versions/2.0.1) - January 04, 2019 (356KB)
- [2.0.0](https://rubygems.org/gems/bundler/versions/2.0.0) - January 03, 2019 (356KB)

This loosely blocks https://github.com/rubygems/bundler-site/pull/615.

**Comment by deivid-rodriguez** [comment]
The Bundler tags have been" migrated" from the old repository, but I don't really know how this migration was done, and I'm not even sure they are correct. If somewhere we need to point to old tags, we should use the ones in https://github.com/rubygems/bundler. If anything, I would remove old `bundler-v*` tags from this repository.

**Comment by tnir** [comment]
Yes, the migration looks perfect to me except for these missing tags only in 2.0.x and 2.1.x. As my use case is "editable" as shown in https://github.com/rubygems/bundler-site/pull/615, links to archived repo is nonsense to me.

**Comment by deivid-rodriguez** [comment]
I replied over at https://github.com/rubygems/bundler-site/pull/615. Since tags are not editable either, it's not useful to push these tags for your use case either.

The only reason to fix this would be for consistency, and in my opinion it's best to delete old tags from this repository, because the real source of truth of these old tags is the old repository.

**Comment by tnir** [comment]
Per https://github.com/rubygems/bundler-site/pull/615, I got it.

As an end-user of Bundler, the code origin of gem looks important to me. For example, ruby/ruby has stable branches https://github.com/ruby/ruby/branches.
The Bundler project can follow it to have 2.1, 2.2, 2.3 branches instead of deleting **tags** in rubygems/rubygems repo apart from RubyGems. I would be more reasonable if the Bundler team release version 2.y in 12-month cadence as per discussion at https://github.com/rubygems/rubygems/issues/5647#issuecomment-1164126332.

**Comment by deivid-rodriguez** [comment]
Yes, absolutely, but note that, for example, the code origin for Bundler 1.17.3 is NOT https://github.com/rubygems/rubygems/tree/bundler-v1.17.3, it's https://github.com/rubygems/bundler/tree/v1.17.3. The former tag was created a long time after Bundler 1.17.3 was released.

The RubyGems & Bundler project has stable branches. The currently maintained stable branch is https://github.com/rubygems/rubygems/tree/3.3. That's where RubyGems 3.3.x & Bundler 2.3.x releases are cut from, and where changes from master than we want to release as patch versions are back ported to.

**Comment by tnir** [comment]
> [...] the code origin for Bundler 1.17.3 is NOT https://github.com/rubygems/rubygems/tree/bundler-v1.17.3, it's https://github.com/rubygems/bundler/tree/v1.17.3. The former tag was created a long time after Bundler 1.17.3 was released.

Incorrect. Both are the identical on GitHub, that is `rubygems/rubygems@bundler-v1.17.3` = rubygems/rubygems@d7089abb6a3c922bfe74199c103e745bb11bd46f = rubygems/bundler@d7089abb6a3c922bfe74199c103e745bb11bd46f = `rubygems/bundler@v1.17.3`. I think with care you pushed all tags from rubygems/bundler to rubygems/rubygems for all Git history to work perfectly!

---

And even if both RubyGems and Bundler has the same stable branches, you can tag RubyGems and Bundler respectively 🤔

**Comment by deivid-rodriguez** [comment]
I'm not saying they don't have the same contents, I'm saying the real tag that was created when Bundler 1.17.3 was released is https://github.com/rubygems/bundler/tree/v1.17.3.

I think there might be a reason why the migration did not work for the missing tags, and the benefit of investigating and potentially fixing it seems very small to me. In any case, you're free to investigate whatever you want :)

> And even if both RubyGems and Bundler has the same stable branches, you can tag RubyGems and Bundler respectively 🤔

Yes, we release both from the same stable branch and at the same time. We tag "twice" to make this more clear, although I know it's still confusing. It will get better in the future.

**Comment by tnir** [comment]
Thanks for explanation. As I found Bundler 2.0 and 2.1 look like obsolete just now, let me close this 🙏
