### ISSUE TITLE
Update Bundler Policies (as Bundler 1.x, 2.1, and 2.2 are not supported)

### ISSUE THREAD

**Issue by tnir** [rubygems/rubygems#5647]
[Bundler Policies](https://github.com/rubygems/rubygems/blob/master/bundler/doc/POLICIES.md) says:

> For example, when Bundler 4.x is the current version, Bundler 4 will be eligible for new features and bugfixes. Bundler 3 will be eligible for bugfixes only. Bundler 2 will be eligible for security bugfixes only. Bundler 1 will be unsupported.

I would read Bundler 1 is eligible for bugfixes only as Bundler 2 is the current version as of writing (2022-06).

Does the team support all 1.x versions (including 1.0) or only 1.17 and 1.16?

Permalink: https://github.com/rubygems/rubygems/blob/e77e18d7b7662788cb28d68a1d873e886827c0dc/bundler/doc/POLICIES.md

**Comment by deivid-rodriguez** [comment]
No, not at all.

The current policy is actually some plan for the future, but it doesn't apply retroactively to old major releases. In practice, we only support the latest 2.x series at a given time, and release one new 2.y every year, at which point that becomes the supported series.

I think once we release Bundler 3 we'll be able to start applying that policy and keep supporting the latest 2.x series for bug fixes, but for the time being this is where we are.

I think we should update the POLICIES document to clarify this.

**Comment by tnir** [comment]
@deivid-rodriguez Would you say the maintainers maintain Bundler 2.2.x now?

The latest Bundler 2.2.x release was on December 07, 2021: https://rubygems.org/gems/bundler/versions/2.2.33

**Comment by deivid-rodriguez** [comment]
No, we may backport some fix exceptionally to v2.2 if requested (@hsbt has done something like this in the past, but it's not guaranteed at all).

**Comment by hsbt** [comment]
I only request or backport the critical security issues for Bundler 2.2 and 2.1. They are bundled at Ruby 3.0 and Ruby 2.7.

Bundler 2.3 is compatible with Ruby 3.0 and 2.7. I think the users can upgrade bundler easily with `gem update` when the vulnerability was discovered.

**Comment by deivid-rodriguez** [comment]
That makes sense. We can also mention that in the updated policy.
