### ISSUE TITLE
gem install octokit

### ISSUE THREAD

**Issue by appuraj-philips** [rubygems/rubygems#5664]
ERROR:  SSL verification error at depth 2: unable to get local issuer certificate (20)
ERROR:  You must add /O=Cisco/CN=Cisco Umbrella Root CA to your local trusted store
ERROR:  SSL verification error at depth 2: unable to get local issuer certificate (20)
ERROR:  You must add /O=Cisco/CN=Cisco Umbrella Root CA to your local trusted store
ERROR:  SSL verification error at depth 2: unable to get local issuer certificate (20)
ERROR:  You must add /O=Cisco/CN=Cisco Umbrella Root CA to your local trusted store
ERROR:  Could not find a valid gem 'octokit' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 peeraddr=146.212.255.50:443 state=error: certificate verify failed (unable to get local issuer certificate) (https://rubygems.org/specs.4.8.gz)
ERROR:  SSL verification error at depth 2: unable to get local issuer certificate (20)
ERROR:  You must add /O=Cisco/CN=Cisco Umbrella Root CA to your local trusted store
ERROR:  SSL verification error at depth 2: unable to get local issuer certificate (20)
ERROR:  You must add /O=Cisco/CN=Cisco Umbrella Root CA to your local trusted store

**Comment by deivid-rodriguez** [comment]
Usually @sonalkr132 is able to triage this kind of issue better than me. @sonalkr132 can you help if you are not too busy?

**Comment by appuraj-philips** [comment]
@sonalkr132 can you please help me on this

**Comment by simi** [comment]
@appuraj-philips please ensure you're running latest rubygems (https://rubygems.org/pages/download) and follow https://bundler.io/v2.3/guides/rubygems_tls_ssl_troubleshooting_guide.html first.

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.

**Comment by sonalkr132** [comment]
Sorry, didn't notice this sooner.
> ERROR: You must add /O=Cisco/CN=Cisco Umbrella Root CA to your local trusted store

This is not the correct certificate info for rubygems.org. most likely you are using a proxy to access rubygems.org or your network has override the dns resolution of rubygems.org. you can use openssl s_client connect command from the network you are having the issue and an unrelated network (with no proxy), you will get different certificates.
As of how to fix this..you can added the root ca of the cert you are using to your trusted ca store if you know what you are doing. If not, please talk to your network administrator. By passing or overriding our TLS certificate is not recommended and will have security implementation.
