### ISSUE TITLE
im not able to run the rails server command. it's tell me that permission denied

### ISSUE THREAD

**Issue by benidias** [rubygems/rubygems#5665]

**Comment by benidias** [comment]
<img width="1440" alt="Capture d’écran, le 2022-06-28 à 09 31 52" src="https://user-images.githubusercontent.com/106104759/176191470-11ef4c16-99f7-4a40-b2da-cb02dfc0b2cc.png">

**Comment by deivid-rodriguez** [comment]
I'll close this because it doesn't include enough information, a screenshot where we can't even see the full content of the error is not enough.

Please follow the bug report template if you want your issue to be looked at.
