### ISSUE TITLE
Add ability to sort `gem list` by date (from gemspec)

### ISSUE THREAD

**Issue by patcon** [rubygems/rubygems#567]
Not sure whether this is a common use-case, but often, I look for new vagrant plugin development by searching `gem list -rd vagrant-`. Since all the related gems follow the `vagrant-*` format, this is a good place to peruse for new developments.

Would be great if we could sort the results by date, making it simpler to track updates surrounding out favourite pluggable gems :)

**Comment by copiousfreetime** [comment]
At the current time, the list command uses the `modern` index to list remote gems. This is a list of tuples containing only the gem name, version and platform of the gem. The date the gem was created is not part of this data, so unfortunately this is not possible to implement at this time.
