### ISSUE TITLE
Bundler 2.3.17 installs precompiled CRuby gems on TruffleRuby

### ISSUE THREAD

**Issue by eregon** [rubygems/rubygems#5691]
### Describe the problem as clearly as you can

```ruby
source 'https://rubygems.org'

gem 'nokogiri'
```

With the latest truffleruby-dev (from ruby-build):
```
$ bundle
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
Using bundler 2.3.17
Using racc 1.6.0
Using mini_portile2 2.8.0
Using nokogiri 1.13.6 (x86_64-linux)
Bundle complete! 1 Gemfile dependency, 4 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```
That is incorrect, it must not be `Using nokogiri 1.13.6 (x86_64-linux)`, it must be `Installing nokogiri 1.13.6 with native extensions` (i.e., compiling from source).
Trying to use it results in errors (expected since it's using the CRuby-precompiled gem):
```
$ ruby -rnokogiri -e0
<internal:core> core/kernel.rb:293:in `require_relative': /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/nokogiri-1.13.6-x86_64-linux/lib/nokogiri/3.0/nokogiri.so: undefined symbol: rb_eTypeError (RuntimeError)
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/nokogiri-1.13.6-x86_64-linux/lib/nokogiri/extension.rb:7:in `<top (required)>'
	from <internal:core> core/kernel.rb:293:in `require_relative'
	from /home/eregon/.rubies/truffleruby-dev/lib/gems/gems/nokogiri-1.13.6-x86_64-linux/lib/nokogiri.rb:10:in `<top (required)>'
	from <internal:core> core/kernel.rb:234:in `gem_original_require'
	from <internal:/home/eregon/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb>:160:in `require'
	from <internal:core> core/unbound_method.rb:18:in `bind_call'
	from <internal:core> core/kernel.rb:272:in `require'
<internal:core> core/kernel.rb:236:in `gem_original_require': cannot load such file -- nokogiri (LoadError)
	from <internal:/home/eregon/.rubies/truffleruby-dev/lib/mri/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:core> core/unbound_method.rb:18:in `bind_call'
	from <internal:core> core/kernel.rb:272:in `require'
```

2.3.16 and 2.2.32 work fine (after cleaning up/reinstalling truffleruby-dev to remove the bad precompiled nokogiri gem):
```
$ bundle   
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
Using bundler 2.3.16
Using racc 1.6.0
Using mini_portile2 2.8.0
Installing nokogiri 1.13.6 with native extensions
Bundle complete! 1 Gemfile dependency, 4 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

### Did you try upgrading rubygems & bundler?

Yes, that's what causes the problem.

## Environment

```
Bundler       2.3.16
  Platforms   ruby
Ruby          3.0.3p0 (2022-07-05 revision be96ee562944f863e7e72ed750f336b939e5d9c3) [x86_64-linux]
  Full Path   /home/eregon/.rubies/truffleruby-dev/bin/ruby
  Config Dir  /home/runner/work/truffleruby-dev-builder/truffleruby-dev-builder/etc
RubyGems      3.2.32
  Gem Home    /home/eregon/.rubies/truffleruby-dev/lib/gems
  Gem Path    /home/eregon/.gem/truffleruby/3.0.3.7:/home/eregon/.rubies/truffleruby-dev/lib/gems
  User Home   /home/eregon
  User Path   /home/eregon/.gem/truffleruby/3.0.3.7
  Bin Dir     /home/eregon/.rubies/truffleruby-dev/bin
Tools         
  Git         2.35.3
  RVM         not installed
  rbenv       not installed
  chruby      0.3.9
```

## Bundler Build Metadata

```
Built At          2022-06-15
Git SHA           324ee6e542
Released Version  true
```

I thought this could relate to https://github.com/rubygems/rubygems/pull/4049 but that's not released yet, right @deivid-rodriguez?
cc @andrykonchin who first saw this issue.

**Comment by eregon** [comment]
FWIW the `Gem Path` shown by `bundle env` seems incorrect, compare it to `gem env`:
```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.2.32
  - RUBY VERSION: 3.0.3 (2022-07-05 patchlevel 0) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/eregon/.rubies/truffleruby-dev/lib/gems
  - USER INSTALLATION DIRECTORY: /home/eregon/.gem/truffleruby/3.0.3.7
  - RUBY EXECUTABLE: /home/eregon/.rubies/truffleruby-dev/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /home/eregon/.rubies/truffleruby-dev/bin
  - SPEC CACHE DIRECTORY: /home/eregon/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/runner/work/truffleruby-dev-builder/truffleruby-dev-builder/etc
  - RUBYGEMS PLATFORMS:
     - ruby
  - GEM PATHS:
     - /home/eregon/.rubies/truffleruby-dev/lib/gems
     - /home/eregon/.gem/truffleruby/3.0.3.7
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/eregon/.rubies/truffleruby-dev/bin
     - /home/eregon/bin
     - /usr/share/Modules/bin
     - /usr/local/bin
     - /usr/local/sbin
     - /usr/bin
     - /usr/sbin
     - /home/eregon/code/mx
     - /home/eregon/code/mspec/bin
     - /opt/crystal/bin
     - /home/eregon/.cargo/bin
```

**Comment by eregon** [comment]
I'd guess it's caused by https://github.com/rubygems/rubygems/pull/5495 from the release notes of 2.3.17: https://github.com/rubygems/rubygems/releases/tag/bundler-v2.3.17

**Comment by deivid-rodriguez** [comment]
Yes, I was figuring that's the culprit too. I'll have a look.

**Comment by deivid-rodriguez** [comment]
Ok, so this particular case works again after #4049, so this will be fixed in 2.3.18.

**Comment by eregon** [comment]
Great, looking forward to that release.
Do you have an ETA? I'd prefer not have to workaround Bundler 2.3.17 e.g. in setup-ruby.

I think we should probably try a similar integration for RubyGems, changing `Gem.platforms` has its own problems and notably I noticed I couldn't `gem uninstall nokogiri` when it installed the wrong CRuby-precompiled version, which might be caused by that.

**Comment by deivid-rodriguez** [comment]
Next Wednesday.

**Comment by eregon** [comment]
This is still an error with Bundler 2.3.18.
Found in https://github.com/sinatra/sinatra/issues/1798#issuecomment-1190013828

To repro:
```
git clone https://github.com/sinatra/sinatra.git 
cd sinatra
chruby truffleruby-dev
gem install bundler
bundle install
...
Fetching nokogiri 1.13.7 (x86_64-linux)
...
Installing nokogiri 1.13.7 (x86_64-linux)
```

Could you reopen and investigate @deivid-rodriguez ?

**Comment by eregon** [comment]
And my simple reproduction in the description also reproduces the error:
```
$ chruby truffleruby-dev
$ gem install bundler
$ bundle install
Fetching gem metadata from https://rubygems.org/.......
Resolving dependencies...
Using bundler 2.3.18
Fetching mini_portile2 2.8.0
Fetching racc 1.6.0
Installing mini_portile2 2.8.0
Installing racc 1.6.0 with native extensions
Fetching nokogiri 1.13.7 (x86_64-linux)
Installing nokogiri 1.13.7 (x86_64-linux)
Bundle complete! 1 Gemfile dependency, 4 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

**Comment by MrWormHole** [comment]
can confirm still happening with 2.3.17 and 2.3.18, had to install 2.3.16 to be able to run my poor rails 7 new app command

**Comment by deivid-rodriguez** [comment]
Bundler is part of official Ruby! Anyways, the fix for this will be released in a couple of days.

**Comment by MrWormHole** [comment]
bundler 2.3.19 fixed nokogiri native installation but the same issue persists with pg installation now

![image](https://user-images.githubusercontent.com/22800416/182025862-fd5f9a3f-990a-455c-8fd6-a0351c1f85a2.png)

**Comment by deivid-rodriguez** [comment]
That screen capture suggests that Bundler is trying to build fully extensions for the `pg` gem, which is fully expected on TruffleRuby.

**Comment by MrWormHole** [comment]
no it is not, why would I need Ruby MRI pre-compiled binary?

**Comment by deivid-rodriguez** [comment]
As you can observe at https://rubygems.org/gems/pg/versions/1.4.2, pg-1.4.2 does not have any precompiled versions, except for Windows. So, except for Windows, Bundler never tries to install a precompiled gem, it always tries to compile it at installation time for you current platform.

**Comment by MrWormHole** [comment]
ok, makes sense now, installing postgresql-devel solved it. Got confused with nokogiri error that we had before where it was using ruby MRI in its native extensions. pg is working with native extensions since it doesn't have the same issue
