### ISSUE TITLE
Do not consider platform gems as candidates when `required_ruby_version` is incompatible

### ISSUE THREAD

**Issue by ianks** [rubygems/rubygems#5715]
### Describe the problem as clearly as you can

When selecting a spec to use when a platform spec is available, currently Bundler will choose the platform matching gem even when it is not compatible with the `required_ruby_version`.

The consequences of this means that it's impossible to publish precompiled gems that fallback to compiling from source code on newer Ruby versions. At Shopify, this makes it so we have to use a bunch of hacks to test gems against `ruby-head`.

Here's a more concrete example of the issue:

```ruby
it "can fallback to a source gem when platform gems are incompatible with current ruby version" do
  setup_multiplatform_gem_with_source_gem

  source = file_uri_for(gem_repo2)

  gemfile <<~G
    source "#{source}"

    gem "my-precompiled-gem"
  G

  # simulate lockfile which includes both a precompiled gem with:
  # - Gem the current platform (with imcompatible ruby version)
  # - A source gem with compatible ruby version
  lockfile <<-L
    GEM
      remote: #{source}/
      specs:
        my-precompiled-gem (3.0.0)
        my-precompiled-gem (3.0.0-#{Bundler.local_platform})

    PLATFORMS
      ruby
      #{Bundler.local_platform}

    DEPENDENCIES
      my-precompiled-gem

    BUNDLED WITH
        #{Bundler::VERSION}
  L

  expect { install_gemfile(gemfile) }.to_not raise_error
end

def setup_multiplatform_gem_with_source_gem
  build_repo2 do
    build_gem("my-precompiled-gem", "3.0.0")
    build_gem("my-precompiled-gem", "3.0.0") do |s| 
      s.platform = Bundler.local_platform

      # purposely unresolvable
      s.required_ruby_version = ">= 1000.0.0"
    end
  end
end
```

In the above test, Bundler should choose `my-precompiled-gem (3.0.0)`. Today, it will pick `my-precompiled-gem (3.0.0-#{Bundler.local_platform})` and simply raise an error in `ensure_specs_are_compatible!`.

cc: @flavorjones

**Comment by deivid-rodriguez** [comment]
Right, yeah. I'll fix this.

**Comment by flavorjones** [comment]
Some prior context on related/same issue: https://github.com/rubygems/rubygems/issues/4012

**Comment by deivid-rodriguez** [comment]
Yes, I believe they are very similar issues but in that case it was a "resolution from scratch" issue, while in this case it's a "lockfile issue".

**Comment by deivid-rodriguez** [comment]
#5784 should fix this!

**Comment by ianks** [comment]
@deivid-rodriguez thank you so much! when do you think this patch will make it in a release?

**Comment by deivid-rodriguez** [comment]
No problem, next week!
