### ISSUE TITLE
outdated --strict is not filtering results

### ISSUE THREAD

**Issue by DaveEOS** [rubygems/rubygems#5717]
### Describe the problem as clearly as you can

The --strict option for the outdated command does not restrict the results to only those allowed by the Gemfile. It returns the same set as without it.

### Did you try upgrading rubygems & bundler?

Yes, to rubygems 3.3.17 and bundler 2.3.17.

### Post steps to reproduce the problem

You can probably try this on any available project, but here's the long way:

1. Install current rails 6 and 7. `gem install rails -v 6.1.6.1 & gem install rails -v 7.0.3.1`
1. Create a new Rails 6 project. `rails _6.1.6.1_ new example`
1. `cd example`
1. Edit Gemfile and change line 7 to `gem 'rails', '~> 6.1.6.1'`

Results:
For both `bundle outdated` and `bundle outdated --strict` the results are this:

```
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...

Gem                 Current  Latest   Requested             Groups
actioncable         6.1.6.1  7.0.3.1
actionmailbox       6.1.6.1  7.0.3.1
actionmailer        6.1.6.1  7.0.3.1
actionpack          6.1.6.1  7.0.3.1
actiontext          6.1.6.1  7.0.3.1
actionview          6.1.6.1  7.0.3.1
activejob           6.1.6.1  7.0.3.1
activemodel         6.1.6.1  7.0.3.1
activerecord        6.1.6.1  7.0.3.1
activestorage       6.1.6.1  7.0.3.1
activesupport       6.1.6.1  7.0.3.1
rack-mini-profiler  2.3.4    3.0.0    ~> 2.0                development
rails               6.1.6.1  7.0.3.1  ~> 6.1.6, >= 6.1.6.1  default
railties            6.1.6.1  7.0.3.1
```

### Possible clue
In the output, the "Requested" column is blank. I would expect the action/active... gems to have `= 6.1.6.1` in them per Gemfile.lock.

**Comment by deivid-rodriguez** [comment]
#5798 should fix this!
