### ISSUE TITLE
`force_ruby_platform` option in Gemfile breaks Bundler auto-updating, sort of

### ISSUE THREAD

**Issue by ngan** [rubygems/rubygems#5725]
### Describe the problem as clearly as you can

After bundler 2.3.18 was released, we made use of the new `force_ruby_platform` option for `gem`:
https://github.com/rubygems/rubygems/pull/4049

However, a problem arises if you have a version of `Bundler` installed that is below 2.3.18. Recent versions of bundler normally attempts to upgrade Bundler for you to the version specified in the lockfile automatically. However, this process doesn't even get a chance to run because an error is thrown parsing the `Gemfile`. It errs because Bundler doesn't recognize the `force_ruby_platform` on old versions.

**Comment by ngan** [comment]
Nevermind! We're only see this problem when bundle is locked.

**Comment by deivid-rodriguez** [comment]
Oooops, really? I was expecting it to just work, because when don't do normal Gemfile/lokfile parsing for this, just look at `BUNDLED WITH` directly.

**Comment by deivid-rodriguez** [comment]
> Nevermind! We're only see this problem when bundle is locked.

You mean frozen? Still unexpected to me...

**Comment by ngan** [comment]
Hey @deivid-rodriguez sorry for the confusion.

I believe the error surfaces for `require 'bundler/setup'` and not from any of the `bundle` CLI commands. Which...I think makes sense?

**Comment by deivid-rodriguez** [comment]
Oh, I see. Yes, you'd need to run `bundle install` first so that the locked version gets installed. Otherwise it will indeed run into an error, yes. But I think it's pretty much expected that you need to run `bundle install` after changing your `Gemfile`.

**Comment by ngan** [comment]
Agree. Sorry for the noise!
