### ISSUE TITLE
RubyGems 3.3.18 removes default bundler gemspec on system update (behavior change)

### ISSUE THREAD

**Issue by kk-ds-000** [rubygems/rubygems#5727]
### Describe the problem as clearly as you can

RubyGems 3.3.18 removes the default bundler gemspec from `/usr/lib/ruby/gems/2.6.0/specifications/default/` when running `gem update --system`, which causes the `bundle` command to fail.

RubyGems 3.3.17 does not exhibit the same behavior.

### Did you try upgrading RubyGems?
Yes, the issue started happening with the latest version (3.3.18).

### Post steps to reproduce the problem

```dockerfile
FROM --platform=linux/amd64 ubuntu:focal-20220531
USER root

RUN apt-get update \
    && apt-get install -y software-properties-common \
    && apt-add-repository ppa:brightbox/ruby-ng \
    && apt-get update \
    && apt-get install -y ruby2.6 \
    && gem update --no-document --system 3.3.18
```

If you build the above image and run the resulting container, you'll get this environment:

```bash
$ ls /usr/lib/ruby/gems/2.6.0/specifications/default/bundler*
ls: cannot access '/usr/lib/ruby/gems/2.6.0/specifications/default/bundler*': No such file or directory

$ bundle --version
Traceback (most recent call last):
	2: from /usr/bin/bundle:25:in `<main>'
	1: from /usr/local/lib/site_ruby/2.6.0/rubygems.rb:284:in `activate_bin_path'
/usr/local/lib/site_ruby/2.6.0/rubygems.rb:265:in `find_spec_for_exe': can't find gem bundler (>= 0.a) with executable bundle (Gem::GemNotFoundException)
```

If you change `gem update --no-document --system 3.3.18` to ` gem update --no-document --system 3.3.17` and rebuild, you'll get this environment:

```
$ ls /usr/lib/ruby/gems/2.6.0/specifications/default/bundler*
/usr/lib/ruby/gems/2.6.0/specifications/default/bundler-1.17.2.gemspec

$ bundle --version
Bundler version 2.3.17
```

Is this behavior change expected?

The `README` seems to warn against upgrading the system RubyGems like this (it's an existing codebase), but I thought I'd file an issue in case this is an unexpected regression.  Thanks!

### Run `gem env` and paste the output below

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.18
  - RUBY VERSION: 2.6.6 (2020-03-31 patchlevel 146) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /var/lib/gems/2.6.0
  - USER INSTALLATION DIRECTORY: /root/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /usr/bin/ruby2.6
  - GIT EXECUTABLE: 
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /root/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /var/lib/gems/2.6.0
     - /root/.gem/ruby/2.6.0
     - /usr/lib/ruby/gems/2.6.0
     - /usr/share/rubygems-integration/2.6.0
     - /usr/share/rubygems-integration/all
     - /usr/lib/x86_64-linux-gnu/rubygems-integration/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
```

**Comment by deivid-rodriguez** [comment]
As you mentioned, what you are doing is NOT supported. If you're using a Ruby installation provided by your OS, then you should also let the OS package manager manage the RubyGems installation. Some distributions now explicitly prevent doing this.

However, fixing this is not hard, and allows to simplify some code for us (and also let me discover some other issues which I'll be fixing next), so #5728 will close this.

In addtion to fixing the problem, it also makes things less weird in the upgraded environment because even if this worked until 3.3.17, it still gave some information that should raise some flags:

#### Until 3.3.17, after upgrading like you did

```
$ gem list bundler

*** LOCAL GEMS ***

bundler (default: 1.17.2)

$ bundle -v
Bundler version 2.3.17
```

#### After #5728 

```
$ gem list bundler

*** LOCAL GEMS ***

bundler (default: 2.4.0.dev)

$ bundle -v
Bundler version 2.4.0.dev
```
