### ISSUE TITLE
Large rubygems-update in package file size since 2.6.5

### ISSUE THREAD

**Issue by tnir** [rubygems/rubygems#5734]
### Describe the problem as clearly as you can

`rubygems-update` in gem package file size has been 250 to 400kB larger since 2.6.5 compared with RubyGems 2.6.4 or earlier.

> - [2.6.5](https://rubygems.org/gems/rubygems-update/versions/2.6.5) - June 22, 2016 (710KB)
> - [2.6.4](https://rubygems.org/gems/rubygems-update/versions/2.6.4) - April 27, 2016 (467KB)

from https://rubygems.org/gems/rubygems-update/versions

### Did you try upgrading RubyGems?

n/a

### Post steps to reproduce the problem

Take a look at https://rubygems.org/gems/rubygems-update/versions.

### Which command did you run?

n/a. Maybe GitHub Actions builds and releases the gem.

### What were you expecting to happen?

`rubygems-update` should be smaller as possible by not including `bundler/**` files.

### What actually happened?

`rubygems-update` should be 400kB larger by including `bundler/**` files.

---

It looks like #1650 added these files in `Manifest.txt`.

**Comment by hsbt** [comment]
It's intentional changes. see https://github.com/rubygems/rubygems/blob/master/lib/rubygems/commands/setup_command.rb#L362

We need to install bundler as the default gems with `gem update --system`.
