### ISSUE TITLE
bundle exec omnibus build <project> gets certificate verify failed

### ISSUE THREAD

**Issue by ubisoft-gne** [rubygems/rubygems#5745]
### Describe the problem as clearly as you can

When I ran command 'bundle exec omnibus build myproject' to create a .rpm package, but the command always returns:

`[root@60dbbeb15a34 omnibus-cmdbci-agent]# bundle exec omnibus build cmdbci-agent
                    [CLI] I | 2022-07-20T08:49:09+00:00 | Using config from 'omnibus.rb'
[2022-07-20T08:49:09+00:00] WARN: Plugin Network: unable to detect ipaddress
Building cmdbci-agent ...
  [Software: preparation] I | 2022-07-20T08:49:11+00:00 | Resolving manifest entry for preparation
[NullFetcher: preparation] I | 2022-07-20T08:49:11+00:00 | Fetching `preparation' (nothing to fetch)
         [Software: zlib] I | 2022-07-20T08:49:11+00:00 | Resolving manifest entry for zlib
      [Software: libedit] I | 2022-07-20T08:49:11+00:00 | Resolving manifest entry for libedit
      [Software: ncurses] I | 2022-07-20T08:49:11+00:00 | Resolving manifest entry for ncurses
    [NetFetcher: libedit] I | 2022-07-20T08:49:11+00:00 | Downloading from `http://www.thrysoee.dk/editline/libedit-20120601-3.0.tar.gz'
    [NetFetcher: ncurses] I | 2022-07-20T08:49:11+00:00 | Downloading from `http://ftp.gnu.org/gnu/ncurses/ncurses-5.9.tar.gz'
      [Software: libyaml] I | 2022-07-20T08:49:11+00:00 | Resolving manifest entry for libyaml                                                                                  0% (0 KB/sec)
    [NetFetcher: libyaml] I | 2022-07-20T08:49:11+00:00 | Downloading from `http://pyyaml.org/download/libyaml/yaml-0.1.6.tar.gz'
#<Thread:0x0000000003c9de68@/root/omnibus-cmdbci-agent/vendor/bundle/ruby/2.6.0/gems/omnibus-6.0.30/lib/omnibus/thread_pool.rb:57 run> terminated with exception (report_on_exception is true):
Traceback (most recent call last):
        23: from /root/omnibus-cmdbci-agent/vendor/bundle/ruby/2.6.0/gems/omnibus-6.0.30/lib/omnibus/thread_pool.rb:61:in `block (2 levels) in initialize'
        22: from /root/omnibus-cmdbci-agent/vendor/bundle/ruby/2.6.0/gems/omnibus-6.0.30/lib/omnibus/thread_pool.rb:61:in `catch'
        21: from /root/omnibus-cmdbci-agent/vendor/bundle/ruby/2.6.0/gems/omnibus-6.0.30/lib/omnibus/thread_pool.rb:62:in `block (3 levels) in initialize'
        20: from /root/omnibus-cmdbci-agent/vendor/bundle/ruby/2.6.0/gems/omnibus-6.0.30/lib/omnibus/thread_pool.rb:62:in `loop'
        19: from /root/omnibus-cmdbci-agent/vendor/bundle/ruby/2.6.0/gems/omnibus-6.0.30/lib/omnibus/thread_pool.rb:64:in `block (4 levels) in initialize'
        18: from /root/omnibus-cmdbci-agent/vendor/bundle/ruby/2.6.0/gems/omnibus-6.0.30/lib/omnibus/project.rb:1066:in `block (3 levels) in download'
        17: from /root/omnibus-cmdbci-agent/vendor/bundle/ruby/2.6.0/gems/omnibus-6.0.30/lib/omnibus/software.rb:885:in `fetch'
        16: from /root/omnibus-cmdbci-agent/vendor/bundle/ruby/2.6.0/gems/omnibus-6.0.30/lib/omnibus/fetchers/net_fetcher.rb:86:in `fetch'
        15: from /root/omnibus-cmdbci-agent/vendor/bundle/ruby/2.6.0/gems/omnibus-6.0.30/lib/omnibus/fetchers/net_fetcher.rb:176:in `download'
        14: from /root/omnibus-cmdbci-agent/vendor/bundle/ruby/2.6.0/gems/omnibus-6.0.30/lib/omnibus/download_helpers.rb:80:in `download_file!'
        13: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/open-uri.rb:35:in `open'
        12: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/open-uri.rb:736:in `open'
        11: from /root/omnibus-cmdbci-agent/vendor/bundle/ruby/2.6.0/gems/omnibus-6.0.30/lib/omnibus/core_extensions/open_uri.rb:51:in `open_uri'
        10: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/open-uri.rb:165:in `open_uri'
         9: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/open-uri.rb:224:in `open_loop'
         8: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/open-uri.rb:224:in `catch'
         7: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/open-uri.rb:226:in `block in open_loop'
         6: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/open-uri.rb:756:in `buffer_open'
         5: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/open-uri.rb:337:in `open_http'
         4: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/http.rb:919:in `start'
         3: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
         2: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/http.rb:996:in `connect'
         1: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired) (OpenSSL::SSL::SSLError)
Traceback (most recent call last):
        23: from /root/omnibus-cmdbci-agent/vendor/bundle/ruby/2.6.0/gems/omnibus-6.0.30/lib/omnibus/thread_pool.rb:61:in `block (2 levels) in initialize'
        22: from /root/omnibus-cmdbci-agent/vendor/bundle/ruby/2.6.0/gems/omnibus-6.0.30/lib/omnibus/thread_pool.rb:61:in `catch'
        21: from /root/omnibus-cmdbci-agent/vendor/bundle/ruby/2.6.0/gems/omnibus-6.0.30/lib/omnibus/thread_pool.rb:62:in `block (3 levels) in initialize'
        20: from /root/omnibus-cmdbci-agent/vendor/bundle/ruby/2.6.0/gems/omnibus-6.0.30/lib/omnibus/thread_pool.rb:62:in `loop'
        19: from /root/omnibus-cmdbci-agent/vendor/bundle/ruby/2.6.0/gems/omnibus-6.0.30/lib/omnibus/thread_pool.rb:64:in `block (4 levels) in initialize'
        18: from /root/omnibus-cmdbci-agent/vendor/bundle/ruby/2.6.0/gems/omnibus-6.0.30/lib/omnibus/project.rb:1066:in `block (3 levels) in download'
        17: from /root/omnibus-cmdbci-agent/vendor/bundle/ruby/2.6.0/gems/omnibus-6.0.30/lib/omnibus/software.rb:885:in `fetch'
        16: from /root/omnibus-cmdbci-agent/vendor/bundle/ruby/2.6.0/gems/omnibus-6.0.30/lib/omnibus/fetchers/net_fetcher.rb:86:in `fetch'
        15: from /root/omnibus-cmdbci-agent/vendor/bundle/ruby/2.6.0/gems/omnibus-6.0.30/lib/omnibus/fetchers/net_fetcher.rb:176:in `download'
        14: from /root/omnibus-cmdbci-agent/vendor/bundle/ruby/2.6.0/gems/omnibus-6.0.30/lib/omnibus/download_helpers.rb:80:in `download_file!'
        13: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/open-uri.rb:35:in `open'
        12: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/open-uri.rb:736:in `open'
        11: from /root/omnibus-cmdbci-agent/vendor/bundle/ruby/2.6.0/gems/omnibus-6.0.30/lib/omnibus/core_extensions/open_uri.rb:51:in `open_uri'
        10: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/open-uri.rb:165:in `open_uri'
         9: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/open-uri.rb:224:in `open_loop'
         8: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/open-uri.rb:224:in `catch'
         7: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/open-uri.rb:226:in `block in open_loop'
         6: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/open-uri.rb:756:in `buffer_open'
         5: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/open-uri.rb:337:in `open_http'
         4: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/http.rb:919:in `start'
         3: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/http.rb:930:in `do_start'
         2: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/http.rb:996:in `connect'
         1: from /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/protocol.rb:44:in `ssl_socket_connect'
/usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/2.6.0/net/protocol.rb:44:in `connect_nonblock': SSL_connect returned=1 errno=0 state=error: certificate verify failed (certificate has expired) (OpenSSL::SSL::SSLError)`

### Did you try upgrading rubygems & bundler?
Yes, I did. But in config/software/, I need to checkout one application from internal website using git command.

In order to let bundle to trust or ignore my self-certificate, I did:
1. bundle config --global ssl_verify_mode false 
2. bundle config ssl_verify_mode false
3. copy my self CA to system pki directory, and run update-ca-trust force-enable, update-ca-trust
4. even copied my self CA as AddTrustExternalCARoot.pem into /usr/local/rvm/rubies/ruby-2.6.5/lib/ruby/site_ruby/2.6.0/ssl_cert/rubygems.org/

all of them don't work.

ssl check my self website:
```
openssl s_client -showcerts -connect my-selfwebsite:https
...
...
<truncated>
    Key-Arg   : None
    Krb5 Principal: None
    PSK identity: None
    PSK identity hint: None
    Start Time: 1658307885
    Timeout   : 300 (sec)
    Verify return code: 0 (ok)
```

Do you have any ideas on it? 
Thanks in advance

**Comment by deivid-rodriguez** [comment]
Hello!

This command is indeed using Bundler though `bundle exec`, but `bundle exec` simply delegates to the `omnibus` command and there's nothing in the error suggesting that this is a Bundler bug I believe. Why do you think this is a Bundler issue?
