### ISSUE TITLE
gem info don't work with flag version

### ISSUE THREAD

**Issue by 7dr1v3** [rubygems/rubygems#5755]
RUBYGEMS VERSION: 3.3.7

I trying to get information from rubygems about author license etc. 

```
$ gem info rails --remote --version '7.0.2.2'

*** REMOTE GEMS ***

rails (7.0.3.1)
    Author: David Heinemeier Hansson
    Homepage: https://rubyonrails.org

    Full-stack web application framework.
```

why 7.0.3.1? where are the information about 7.0.2.2 ?

**Comment by deivid-rodriguez** [comment]
> why 7.0.3.1? where are the information about 7.0.2.2 ?

I don't know, it seems like a bug. Want to try fix it? :)

**Comment by 7dr1v3** [comment]
I don't know too. Maybe bug with version format or etc.

**Comment by tonyaraujop** [comment]
Hey @deivid-rodriguez can I try to fix it? I'm happy to contribute.

**Comment by deivid-rodriguez** [comment]
Of course!

**Comment by tonyaraujop** [comment]
Hey @deivid-rodriguez is there any way to debug tests? I looked on the contribution page but didn't find any information related to this. I still haven't been able to identify the source of the problem, I believe it is in the `version_option.rb` file, but I would like to debug it to know which values ​​are being used. Also, I tried to use `pry`, but it doesn't work =/

**Comment by deivid-rodriguez** [comment]
You can try using `irb`, or `puts`, but better ask this kind of things on Slack!

**Comment by deivid-rodriguez** [comment]
I meant Slack for questions like "how to debug tests?", but for questions specific to PRs or issues, GitHub is fine, sorry for confusing you 😅. Can you open a WIP PR with what you've tried so far, so that we can also see the errors you're getting?

**Comment by tonyaraujop** [comment]
Sorry for that. I used `puts` to see if the version and it seems that there are nothing wrong with the `version_option.rb`. So far, I'm trying to reproduce this bug in the test, but I'm not getting anywhere =/ this is the test:

```rb
  def test_execute_remote_version
    spec_fetcher do |fetcher|
      fetcher.spec "coolgem", "4.1.2"
    end
    
    @cmd.handle_options %w[info coolgem --remote --version 4.1.2]

    use_ui @stub_ui do
      @cmd.execute
    end

    expected = <<-EOF

  *** REMOTE GEMS ***

  coolgem (4.1.2)
      EOF

    assert_equal expected, @stub_ui.output
  end
  ```
  and this is the diff I'm getting:
  
![image](https://user-images.githubusercontent.com/92229784/186496521-93a64861-7930-41fa-9147-5b465cf7ead8.png)

**Comment by deivid-rodriguez** [comment]
I think you may need to create a different version that you don't want displayed (like 7.0.3.1 in the issue body) to potentially confuse `gem info`?

**Comment by tonyaraujop** [comment]
Yes, I tried something like that.

```rb
  def test_execute_remote_version
    spec_fetcher do |fetcher|
      #fetcher.spec "coolgem", "4.1.3"
      fetcher.spec "coolgem", "4.1.2"
      fetcher.spec "coolgem", "4.1.1"
    end
    
    @cmd.handle_options %w[info coolgem --remote --version 4.1.3]

    use_ui @stub_ui do
      @cmd.execute
    end

    expected = <<-EOF

  *** REMOTE GEMS ***

  coolgem (4.1.2)
      EOF

    assert_equal expected, @stub_ui.output
  end
  ```
  
The output the version `4.1.2`, but if uncomment the line with the version `4.1.3` the output would be that version (4.1.3).

**Comment by deivid-rodriguez** [comment]
There you go, you now have a failing test to start with!

Ok, so you have one failing test there. If 4.1.3 does not exist, the command should show an error, not show 4.1.2 information instead. How about if you pass `--version 4.1.1`, does it show it properly?

**Comment by tonyaraujop** [comment]
No...it expect version `4.2.2`

**Comment by deivid-rodriguez** [comment]
Ok, so you have two failing tests now that your fix should get green :)

**Comment by tonyaraujop** [comment]
Hey @deivid-rodriguez I used `puts` to see the @options that are being used in the `handle_options` method and I've noticed this: 
```console
{:domain=>:remote, :details=>false, :versions=>true, :installed=>nil, :version=>#<Gem::Requirement:0x00007f3d9ea81e10 @requirements=[["=", #<Gem::Version "4.1.3">]]>, :explicit_prerelease=>false, :prerelease=>false, :args=>["info", "coolgem"]}
```
Also, the @options[:version] is the one that is being used which is what I expected, what do you think, this make sense?

**Comment by deivid-rodriguez** [comment]
That means that the CLI flag with the version is being correctly passed to the command. So the fact that it's being ignored lives in the command logic. 

Looking at the command, it's logic must be shared with some other command, because it all lives in the `QueryUtils` mixin.

https://github.com/rubygems/rubygems/blob/e5d979d31409a35443a24bf57ac9d1b438aa0f35/lib/rubygems/commands/info_command.rb#L7

So you probably want to check the `#execute` method defined there.

**Comment by deivid-rodriguez** [comment]
By the way, be careful to add quotes when you write instance variables like `@options`, otherwise you're mentioning random people at GitHub 😆.

**Comment by tonyaraujop** [comment]
> By the way, be careful to add quotes when you write instance variables like `@options`, otherwise you're mentioning random people at GitHub laughing.

OMG I miss that.

**Comment by tonyaraujop** [comment]
> That means that the CLI flag with the version is being correctly passed to the command. So the fact that it's being ignored lives in the command logic.
> 
> Looking at the command, it's logic must be shared with some other command, because it all lives in the `QueryUtils` mixin.
> 
> https://github.com/rubygems/rubygems/blob/e5d979d31409a35443a24bf57ac9d1b438aa0f35/lib/rubygems/commands/info_command.rb#L7
> 
> So you probably want to check the `#execute` method defined there.

Ok, I'm working on it

**Comment by tonyaraujop** [comment]
Hey @deivid-rodriguez I've noticed that the method `spec_type` looks for `options[:all]`, but the key `[:all]` doesn't exist in the `options` hash, as I showed early, so always will return `:latest`, ignoring the version that are being passed. This key is generated by something else?

**Comment by deivid-rodriguez** [comment]
Aha! So you may need to start returning complete indexes at

https://github.com/rubygems/rubygems/blob/e5d979d31409a35443a24bf57ac9d1b438aa0f35/lib/rubygems/query_utils.rb#L161-L173

when `--version` is passed too, but then you'll need to do further filtering, of course!

**Comment by tonyaraujop** [comment]
I will open a draft PR, so we can discuss.
