### ISSUE TITLE
Funding message can not be disabled

### ISSUE THREAD

**Issue by m-o-e** [rubygems/rubygems#5764]
### Describe the problem as clearly as you can

Bundler prints this after each run:
```
1 installed gem you directly depend on is looking for funding.
  Run `bundle fund` for details
```

There seems to be no way to disable it.
In npm the message can be suppressed by
putting `fund=false` in `~/.npmrc`, bundler
should have an equivalent option.

### Did you try upgrading rubygems & bundler?

Yes.

```
Bundler version 2.3.18
```

### Post steps to reproduce the problem

1. Run `bundle`

### Which command did you run?

`bundle`

### What were you expecting to happen?

To not see any messages printed to my screen that are
unrelated to the operation I invoked.

### What actually happened?

I get extra lines in my local and CI output that I don't want to see.

**Comment by simi** [comment]
In theory you can open `bundle fund` and fund the project, so it will not be looking for funding anymore and the message will disappear within next version. :smile: 

Alternatively feel free to submit PR with bundle config for this output.

We can return early (similar to post install messages)

https://github.com/rubygems/rubygems/blob/773fc2b9287ef06b5674dcac9b704aaba73481d6/bundler/lib/bundler/cli/common.rb#L5-L10

in output_fund_metadata_summary method:

https://github.com/rubygems/rubygems/blob/773fc2b9287ef06b5674dcac9b704aaba73481d6/bundler/lib/bundler/cli/common.rb#L17-L29

**Comment by deivid-rodriguez** [comment]
> In theory you can open bundle fund and fund the project, so it will not be looking for funding anymore and the message will disappear within next version. 😄

Hahaha fantastic, that's a great fix for this issue 🤣.

**Comment by m-o-e** [comment]
> In theory you can open bundle fund and fund the project,
> so it will not be looking for funding anymore and the message will disappear within next version. 😄

Unfortunately in practice that won't make the message go away.

But thanks a lot for the code pointers!
I've tried a PR here: https://github.com/rubygems/rubygems/pull/5767
