### ISSUE TITLE
While running gradle build

### ISSUE THREAD

**Issue by Dhruva23** [rubygems/rubygems#5770]
Bundler::GemNotFound

Your RubyGems version (2.6.14.4)) has a bug that prevents `required_ruby_version` from working for Bundler. Any scripts that use `gem install bundler` will break as soon as Bundler drops support for your Ruby version. Please upgrade RubyGems to avoid future breakage and silence this warning by running `gem update --system 3.2.3`

**Comment by deivid-rodriguez** [comment]
Please follow the issue template if you want your issue looked at. Thanks!
