### ISSUE TITLE
Bundle command should be able to display messages from gem server

### ISSUE THREAD

**Issue by hut8** [rubygems/rubygems#5791]
### Describe the problem as clearly as you can

I maintain rails-assets.org, which is a gem server that serves gems generated from bower packages (obviously, this is a legacy service, but a lot of people still use it). We need a way to display messages to the user that are similar to those which can already be displayed for "post-install" or "funding", but those are gem-specific and are not displayed every time that bundler is run.

A couple of use cases for that feature are:

- Planned maintenance
- Begging for money for rails-assets.org itself, not for a particular gem.
- Some users set up rails-assets in their gemfile in such a way that they will try to request *all* of their gems from rails-assets.org, instead of the ones that are specific to our service. If rails-assets.org were compromised, this opens up a bigger attack surface, although any compromise is bad. We would like to add instructions on how to fix this using a `source` block if users do this.
- Warn users about gems that have security flaws. There are a *lot* of users who currently are served flawed gems; it would be nice to warn them sometimes.

Some of those use cases are applicable to any gem server, including rubygems.org.

On the Bundler slack I asked if there was such functionality, and @deivid-rodriguez replied that there was not as far as he knew. I also dug through the code and could not find anything.

Right now, error messages are displayed when gems cannot be fetched, but I want to be able to display an error on the client when the gems *can* be fetched.

**Comment by deivid-rodriguez** [comment]
@hut8 Since the discussion at Slack indicates that there are probably better alternatives, let me close this for the time being. We can always reopen if a different conclusion is reached in the end.

**Comment by hut8** [comment]
I concur, @deivid-rodriguez . Thanks for the guidance 🙇🏻
