### ISSUE TITLE
Fix gem specification undefined method `prerelease?' for nil class

### ISSUE THREAD

**Issue by bkuhlmann** [rubygems/rubygems#5792]
## Steps to Reproduce

Run the following code to reproduce in IRB:

``` ruby
Gem::Specification.new.version = nil
```

## Expected Behavior

This behavior is surprising because a setter shouldn't error when a `nil` value is given. I believe the setter should gracefully handle `nil` as a value or raise a more informative error.

## Current Behavior

Running the above code will result in a no method error:

``` 
`version=': undefined method `prerelease?' for nil:NilClass (NoMethodError)
```

## Possible Solution

I think the handling of `nil` should be handled gracefully or a more informed exception should be raised.

## Environment

- **Ruby**: ruby 3.1.2p20 (2022-04-12 revision 4491bb740a) [arm64-darwin21.4.0]
- **RubyGems**: 3.3.19

**Comment by deivid-rodriguez** [comment]
https://github.com/rubygems/rubygems/pull/5794 should fix this!

**Comment by bkuhlmann** [comment]
Thanks! :bow:
