### ISSUE TITLE
bundle-version: Prints Bundler's version information

### ISSUE THREAD

**Issue by tnir** [rubygems/rubygems#5806]
```suggestion
description: Prints Bundler's version information
```

How about this? Or, does the wording "the bundler" convey anything else than "Bundler itself"?

_Originally posted by @olleolleolle in https://github.com/rubygems/bundler-site/pull/840#discussion_r934760841_

This wording is used in the help text of Bundler itself, too, so this is now a Bundler issue report.

**Comment by deivid-rodriguez** [comment]
We now have exactly what @olleolleolle suggested in `bundle version` man page, so this is no longer an issue!
