### ISSUE TITLE
Prompt the user to review extconf.rb when installing

### ISSUE THREAD

**Issue by charliesome** [rubygems/rubygems#581]
RubyGems should prompt the user to review `extconf.rb` (and perhaps other files that are executed when configuring native extensions) with `$EDITOR` before executing it.

This should be on by default, with a switch to turn it off (for example, if installation of trusted gems is being scripted).

For an example of this sort of thing being done elsewhere, check out `yaourt` - a client for the AUR. This is what it says when installing an AUR package:

```
# yaourt -S minecraft

==> Downloading minecraft PKGBUILD from AUR...
x PKGBUILD
x minecraft
x minecraft.desktop
x minecraft.png
x minecraft.install

....snip.....

minecraft latest-18  (Thu Aug  5 16:24:52 UTC 2010)
( Unsupported package: Potentially dangerous ! )
==> Edit PKGBUILD ? [Y/n] ("A" to abort)
==> ------------------------------------
==>
```

**Comment by copiousfreetime** [comment]
Checking in on the interest in this issue. 

The question is, adding a `--review-extconf` or similar flag to gem installation so that those users who wish can review the `extconf.rb` file can do so. It looks like to implement it should be done in `Gem::Ext::Builder#build_extension`

**Comment by bronzdoc** [comment]
is this specific for extconf.rb or any oher files should be reviewed?  people could edit this files?

**Comment by bronzdoc** [comment]
closing due to lack of response and interest
