### ISSUE TITLE
Discrepancy between paths used by bundle install and bundle exec

### ISSUE THREAD

**Issue by varungandhi-src** [rubygems/rubygems#5838]
### Describe the problem as clearly as you can

If I add a binary dependency (e.g. `sorbet`), running `bundle exec` after `bundle install` fails. This is because the path fragment added by `bundle exec` is incorrect. See [repo with minimal reproduction](https://github.com/varungandhi-src/bundle_exec_bug).

I've copied the information from the README here to fit the template.

### Did you try upgrading rubygems & bundler?

- Yes, this is using the latest version of `bundler` `v2.30.0` using `gem update bundler`.
- I did not run `gem update --system` because that seems to (I think as a bug) modify the environment so that `bundler` starts installing gems literally system-wide (under `/Library/Ruby`), instead of into the standalone (local) Ruby installation. I've created a local sandbox precisely because I do not want to install anything under `/Library/Ruby`.

### Post steps to reproduce the problem

```
git clone https://github.com/varungandhi-src/bundle_exec_bug.git
git checkout f6155dcd701a4a133400452bcb08b2e4254885b0
cd bundle_exec_bug

# Copied from README in repo

# -- Setup --
RBENV_ROOT=local-ruby-2.7.6 MAKE_OPTS="-j 10" rbenv install 2.7.6

# Backup install directory before fiddling to avoid rebuilding.
tar -czf local-ruby-2.7.6-backup.tgz local-ruby-2.7.6

# Ruby 2.7.6 uses bundler 2.1.4, which is nearly 2yo. Update that
./local-ruby-2.7.6/versions/2.7.6/bin/gem update bundler

# -- Problem --
# Try to run `bundle install` + `bundle exec`:
bash -c "env - PATH='/usr/local/bin:/usr/sbin:/usr/bin:/bin' _RUBY_ROOT=./local-ruby-2.7.6 _BUNDLE=./local-ruby-2.7.6/versions/2.7.6/bin/bundle ./run.sh"
```

### Which command did you run?

`bundle exec which srb` (see the `run.sh` file to details)

### What were you expecting to happen?

This should print the path to `srb` binary which was installed earlier.

### What actually happened?

The `bundle exec` call fails, because the `PATH` entry added by it is:

```
local-ruby-2.7.6/versions/2.7.6/lib/ruby/gems/2.7.0/bin
```

However, `srb` can be found under:

```
local-ruby-2.7.6/versions/2.7.6/bin/srb
local-ruby-2.7.6/versions/2.7.6/lib/ruby/gems/2.7.0/gems/sorbet-0.5.10324/bin/srb
```

So there is a mismatch.

I can't tell if the problem is that `bundle install` didn't instead `srb` in the right place,
or if that `bundle exec` is adding the wrong entry to the `PATH`.

### If not included with the output of your command, run `bundle env` and paste the output below

<details>

<summary>bundle env output (click to expand)</summary>

## Environment

```
Bundler       2.3.20
  Platforms   ruby, arm64-darwin-21
Ruby          2.7.6p219 (2022-04-12 revision c9c2245c0a25176072e02db9254f0e0c84c805cd) [arm64-darwin-21]
  Full Path   /Users/varun/Code/play/bundle_exec_bug/local-ruby-2.7.6/versions/2.7.6/bin/ruby
  Config Dir  /Users/varun/Code/play/bundle_exec_bug/local-ruby-2.7.6/versions/2.7.6/etc
RubyGems      3.1.6
  Gem Home    /Users/varun/Code/play/bundle_exec_bug/local-ruby-2.7.6/versions/2.7.6/lib/ruby/gems/2.7.0
  Gem Path    /Users/varun/.gem/ruby/2.7.0:/Users/varun/Code/play/bundle_exec_bug/local-ruby-2.7.6/versions/2.7.6/lib/ruby/gems/2.7.0
  User Home   /Users/varun
  User Path   /Users/varun/.gem/ruby/2.7.0
  Bin Dir     /Users/varun/Code/play/bundle_exec_bug/local-ruby-2.7.6/versions/2.7.6/bin
Tools         
  Git         2.37.1
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-08-10
Git SHA           4fd2813f54
Released Version  true
```

## Bundler settings

```
gem.coc
  Set for the current user (/Users/varun/.bundle/config): false
gem.mit
  Set for the current user (/Users/varun/.bundle/config): false
gem.test
  Set for the current user (/Users/varun/.bundle/config): false
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

git_source(:github) {|repo_name| "https://github.com/#{repo_name}" }

gem "sorbet", "~> 0.5.10324"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    sorbet (0.5.10324)
      sorbet-static (= 0.5.10324)
    sorbet-static (0.5.10324-universal-darwin-21)

PLATFORMS
  arm64-darwin-21

DEPENDENCIES
  sorbet (~> 0.5.10324)

BUNDLED WITH
   2.3.20
```

</details>

**Comment by deivid-rodriguez** [comment]
Sorry for getting back so late.

I just tried your repro steps and everything worked fine. Are you still having this issue?

**Comment by deivid-rodriguez** [comment]
Oh, sorry! I missed that `bundle exec which srb` line and since the repo didn't run into any errors, I thought it had worked.

I think the problem here is that you are misusing `rbenv`. Rbenv [needs to be setup](https://github.com/rbenv/rbenv#installation) at shell initialization. That in particular will add a shims directory that will redirect executables to the currently activated ruby. It will also add [a hook](https://github.com/rbenv/rbenv/blob/61747c06d42a4ef094fcc498eefcd93d5d9d7016/rbenv.d/exec/gem-rehash/rubygems_plugin.rb) that will install the proper shim for `srb` right after `bundle install` is run.

I haven't used Rbenv for a long time so I can't help more, but I believe the problem does not lie in RubyGems or Bundler.

**Comment by deivid-rodriguez** [comment]
Closing this since I don't think this is a problem in RubyGems or Bundler, and I didn't receive more replies here. Feel free to comment again though if you think there's something for us to improve!
