### ISSUE TITLE
bundler update --conservative downgrades gem from 1.0.19 to 0.1.9

### ISSUE THREAD

**Issue by superscott** [rubygems/rubygems#5842]
### Describe the problem as clearly as you can

We had [`quickbooks-ruby`](https://github.com/ruckus/quickbooks-ruby) installed at `1.0.19` without the version pinned, I ran `bundle update --conservative` which changed the version to be used to `0.1.19`, which is an extraordinarily old version.

So while I understand this might be an extremely specific use-case, the fact that this is something that could happen to somebody else is why I wanted to create this issue. The possibility that specifically `bundle update --conservative`  could ever rollback/downgrade a gem version is completely unexpected behavior. 

This bug does not happen without the `--conservative` flag, and `bundle update` causes the quickbooks-ruby gem to update correctly.

This bug only appears when the [`oauth2`](https://github.com/oauth-xx/oauth2) gem is also included in the Gemfile, but just these two gems alone can trigger the behavior. 
I expect this is probably something happening with the interactions of these two gem's dependencies, but hopefully it can give some insight about how to code around this issue, and preventing this from happening in the future. 

### Did you try upgrading rubygems & bundler?

Yes, I am on the latest versions of both, and the issue happened on previous versions as well.
```
┌─[scott] [ruby-3.0.4] [~/projects/example_bundler] [2022-08-15 09:43:11]
└─[0] <git:(master 90acde4✱) > gem --version
3.3.20
```
```
┌─[scott] [ruby-3.0.4] [~/projects/example_bundler] [2022-08-15 09:52:01]
└─[0] <git:(master 90acde4✱) > bundler --version
Bundler version 2.3.20
```

### Post steps to reproduce the problem

- Given only these [two gems in my Gemfile :: `oauth2` and `quickbooks-ruby`](https://gist.github.com/superscott/8fa29655b44800f4eb32e02c82916826#file-init-gemfile) 
- And having both gems installed, i.e. [`bundle install` against the init-Gemfile](https://gist.github.com/superscott/8fa29655b44800f4eb32e02c82916826#file-init-gemfile), which allows for an upgrade path for `quickbooks-ruby` (1.0.19 to 1.0.21) 
- [`quickbooks-ruby` should be installed at 1.0.19](https://gist.github.com/superscott/8fa29655b44800f4eb32e02c82916826#file-init-gemfile-lock-L34)
- Remove the [pinned version number](https://gist.github.com/superscott/8fa29655b44800f4eb32e02c82916826#file-after-gemfile-L6)
- Running `bundle update --conservative` [against the after-Gemfile](https://gist.github.com/superscott/8fa29655b44800f4eb32e02c82916826#file-after-gemfile) causes the `quickbooks-ruby` to [downgrade itself from 1.0.19 to 0.1.9](https://gist.github.com/superscott/8fa29655b44800f4eb32e02c82916826#file-after-gemfile-lock-L32)

### Which command did you run?
`bundler update --conservative`

### What were you expecting to happen?
That my gems were updated conservatively :D

### What actually happened?
The `quickbooks-ruby` gem version went from 1.0.19 to 0.1.19

## Environment

```
Bundler             2.3.20
  Platforms         ruby, x86_64-linux
Ruby                3.0.4p208 (2022-04-12 revision 3fa771ddedac25560be57f4055f1767e6c810f58) [x86_64-linux]
  Full Path         /home/scott/.rvm/rubies/ruby-3.0.4/bin/ruby
  Config Dir        /home/scott/.rvm/rubies/ruby-3.0.4/etc
RubyGems            3.3.20
  Gem Home          /home/scott/.rvm/gems/ruby-3.0.4
  Gem Path          /home/scott/.rvm/gems/ruby-3.0.4:/home/scott/.rvm/rubies/ruby-3.0.4/lib/ruby/gems/3.0.0
  User Home         /home/scott
  User Path         /home/scott/.gem/ruby/3.0.0
  Bin Dir           /home/scott/.rvm/gems/ruby-3.0.4/bin
Tools               
  Git               2.34.1
  RVM               1.29.12 (latest)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2022-08-10
Git SHA           4fd2813f54
Released Version  true
```

## Bundler settings

```
my_sidekiq_info :)
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"
gem 'quickbooks-ruby'
gem 'oauth2'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    activemodel (7.0.3.1)
      activesupport (= 7.0.3.1)
    activesupport (7.0.3.1)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    concurrent-ruby (1.1.10)
    connection_pool (2.2.5)
    faraday (2.5.2)
      faraday-net_http (>= 2.0, < 3.1)
      ruby2_keywords (>= 0.0.4)
    faraday-net_http (3.0.0)
    i18n (1.12.0)
      concurrent-ruby (~> 1.0)
    jwt (2.4.1)
    minitest (5.16.2)
    multi_json (1.15.0)
    multi_xml (0.6.0)
    multipart-post (2.2.3)
    net-http-persistent (4.0.1)
      connection_pool (~> 2.2)
    nokogiri (1.13.8-x86_64-linux)
      racc (~> 1.4)
    oauth2 (1.4.10)
      faraday (>= 0.17.3, < 3.0)
      jwt (>= 1.0, < 3.0)
      multi_json (~> 1.3)
      multi_xml (~> 0.5)
      rack (>= 1.2, < 3)
    quickbooks-ruby (1.0.19)
      activemodel (> 4.0)
      multipart-post
      net-http-persistent
      nokogiri
      oauth2 (~> 1.4)
      roxml (~> 4.2)
    racc (1.6.0)
    rack (2.2.4)
    roxml (4.2.0)
      activesupport (>= 4.0)
      nokogiri (>= 1.3.3)
    ruby2_keywords (0.0.5)
    tzinfo (2.0.5)
      concurrent-ruby (~> 1.0)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  oauth2
  quickbooks-ruby

BUNDLED WITH
   2.3.20
```

**Comment by deivid-rodriguez** [comment]
Reproduced, except that plain `bundle update` does not work for me either because it leaves all gems untouched (no updates). This is a simple but tricky case, so it's a very good example to use to try fix things. I'll investigate this, thanks!

**Comment by deivid-rodriguez** [comment]
#5847 should fix this!
