### ISSUE TITLE
bundle plugin accepts two exclusive options --branch and --ref

### ISSUE THREAD

**Issue by tnir** [rubygems/rubygems#5845]
### Describe the problem as clearly as you can

`bundle plugin` sub-command accepts two exclusive options `--branch` and `--ref`, but the last `--ref` value is applied.

_Originally posted by @tnir in https://github.com/rubygems/bundler-site/pull/860#discussion_r949482257_

### Post steps to reproduce the problem

1. `bundle plugin install --local_git https://github.com/rubygems/bundler-graph.git bundler-graph --ref v0.1.0 --branch v0.2.0`
2. `bundle plugin install --local_git https://github.com/rubygems/bundler-graph.git bundler-graph --branch v0.2.0 --ref v0.1.0`

### Which command did you run?

1. `bundle plugin install --local_git https://github.com/rubygems/bundler-graph.git bundler-graph --ref v0.1.0 --branch v0.2.0`
2. `bundle plugin install --local_git https://github.com/rubygems/bundler-graph.git bundler-graph --branch v0.2.0 --ref v0.1.0`

### What were you expecting to happen?

Both commands should be warned or cause errors.

### What actually happened?

v0.1.0 was installed with either command.

### Note
Not sure if we really need to use two different options.

`git-clone -b` supports for arbitrary `rev` value.
https://git-scm.com/docs/git-clone#Documentation/git-clone.txt--bltnamegt

> -b \<name\>
> --branch \<name\>
> Instead of pointing the newly created HEAD to the branch pointed to by the cloned repository’s HEAD, point to `<name>` branch instead. In a non-bare repository, this is the branch that will be checked out. `--branch` can also take tags and detaches the HEAD at that commit in the resulting repository.

**Comment by deivid-rodriguez** [comment]
So, you're saying we could unify everything into the `--ref` argument that can take a revision, a branch, or a tag? That sounds good to me!

**Comment by tnir** [comment]
Yes, my proposal looks more natural to me. Or we can disallow commit-ish value for `--branch` and branch for `--ref` instead. Anyway while I found this in bundle plugin, we should consider it for [`git:` option in Gemfile](https://bundler.io/guides/git.html) and [bundle-add](https://bundler.io/v2.3/man/bundle-add.1.html), shouldn't we?

For starters, should we simply prohibit users from specifying (1) both `--ref` and `--branch` at the same time, (2) more than one `--ref`s, or (3) more than one `--branch`s in (A) `bundle-plugin`, (B) `bundle-add`, and maybe (C) a `gem` entry in Gemfile?

**Comment by deivid-rodriguez** [comment]
That sounds like a good start, yeah!

**Comment by tnir** [comment]
An issue allowing users to specify `--branch` (or `--ref`) twice is deferred to #5863.
