### ISSUE TITLE
bundle plugin install accepts --branch twice or more

### ISSUE THREAD

**Issue by tnir** [rubygems/rubygems#5863]
### Describe the problem as clearly as you can

`bundle plugin install` command allows users to pass `--branch` (or `--ref`) twice or more as below:

```sh
bundle plugin install --git https://github.com/rubygems/bundler-graph.git bundler-graph --branch v0.2.0 --branch v0.2.1
```

### Which command did you run?

1. `bundle plugin install --git https://github.com/rubygems/bundler-graph.git bundler-graph --branch v0.2.0 --branch v0.2.1`
1. Same thing with `--ref`: `bundle plugin install --git https://github.com/rubygems/bundler-graph.git bundler-graph --ref v0.2.0 --ref v0.2.1`

### What were you expecting to happen?

Warns if multiple `--branch` options are specified. Or exit as an error without installing plugin(s).

### What actually happened?

Installs bundler-graph @ v0.2.1 without any warning or error.

```
Fetching https://github.com/rubygems/bundler-graph.git
Resolving dependencies...
Using bundler 2.4.0.dev
Using bundler-graph 0.2.1 from https://github.com/rubygems/bundler-graph.git (at v0.2.1@4fb866b)
Installed plugin bundler-graph
```

### If not included with the output of your command, run `bundle env` and paste the output below

````txt
$ exe/bundle env
## Environment

```
Bundler             2.4.0.dev
  Platforms         ruby, x86_64-linux
Ruby                3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x86_64-linux]
  Full Path         /home/gitpod/.rvm/rubies/ruby-3.1.2/bin/ruby
  Config Dir        /etc
RubyGems            3.3.7
  Gem Home          /home/gitpod/.rvm/gems/ruby-3.1.2
  Gem Path          /home/gitpod/.rvm/gems/ruby-3.1.2:/home/gitpod/.rvm/rubies/ruby-3.1.2/lib/ruby/gems/3.1.0
  User Home         /home/gitpod
  User Path         /home/gitpod/.local/share/gem/ruby/3.1.0
  Bin Dir           /home/gitpod/.rvm/gems/ruby-3.1.2/bin
Tools               
  Git               2.37.1
  RVM               1.29.12 (latest)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2022-08-23
Git SHA           73b5cf9bd
Released Version  false
```

## Bundler settings

```
path.system
  Set for your local app (/workspace/rubygems/.bundle/config): true
```
````

Derived from #5845

**Comment by jeromedalbert** [comment]
Allowing the same option multiple times can be useful if you need to override the previous option.

For example, if you use a wrapper program/script/alias that does something like this:

```bash
bundle-plugin-install() {
  bundle plugin install --branch main "$@"
}
```

The current Rubygems behavior allows you to override the branch like so:

```
bundle-plugin-install bundler-graph --branch master
```

---

More generally speaking, overriding a CLI flag is not unique to Rubygems.

For example `rails new` behaves similarly where the last provided value overrides any previous one:

```bash
rails new myapp -d postgresql -d mysql # mysql overrides other values
```

So it seems like this behavior is not specific to Rubygems, and in any case I think this is expected behavior.

**Comment by deivid-rodriguez** [comment]
Let's call this a non issue for now.
