### ISSUE TITLE
Bundler 2.3.X does not respect BUNDLED WITH in Gemfile.lock

### ISSUE THREAD

**Issue by takashiatzendesk** [rubygems/rubygems#5887]
### Describe the problem as clearly as you can

According to https://bundler.io/blog/2022/01/23/bundler-v2-3.html, bundler 2.3.X should respect the BUNDLED WITH section of Gemfile.lock, but it does not.

> In Bundler 2.3 and up (if you also have RubyGems 3.3 or higher), running bundle install will use the exact version from the BUNDLED WITH section of the lockfile. If that version is not installed before you run bundle install, the running version of Bundler will install the locked version, and then run your original command using the newly-installed locked version.

### Did you try upgrading rubygems & bundler?

Yes. 

### Post steps to reproduce the problem

My Gemfile does not pin the bundler version, so it looks like this:

```Gemfile
gem 'bundler',                          '~> 2.0'
```

To replicate the issue, I used bundler 2.3.21, and I did `bundle install` with bundler 2.3.21 to set the BUNDLED WITH in my `Gemfile.lock`:

```sh
$ cat Gemfile.lock | tail -n 3
BUNDLED WITH
   2.3.21
```

Now, when I downgrade my version of bundler to 2.3.20:

```sh
$ bundler --version 
Bundler version 2.3.20
```

And then run `bundle install`, bundler does not respect the `BUNDLED WITH` section of the Gemfile, as it is overwritten by the new bundler version, instead of downloading `2.3.21` and running `bundle install`.

```Gemfile
$ cat Gemfile.lock | tail -n 3
BUNDLED WITH
   2.3.20
```

### Which command did you run?

`bundle install`

### What were you expecting to happen?

I was expecting bundler to respect the `BUNDLED WITH` in Gemfile.lock, and install bundler 2.3.21 before `bundle install`ing. 

### What actually happened?

Bundler does not respect the `BUNDLED WITH` in Gemfile.lock, and happily uses the currently active bundler.

**Comment by deivid-rodriguez** [comment]
What's your RubyGems version, can you show the result of `gem env`?

**Comment by deivid-rodriguez** [comment]
As you can read in the excerpt of the blog post you copied, you need at least RubyGems 3.3 for this feature to work as advertised, and you're using RubyGems 3.0. Upgrade Rubygems with `gem update --system` and it should work after that.

Thanks!

**Comment by takashiatzendesk** [comment]
Works as advertised after the rubygems upgrade, thank you!

**Comment by zenspider** [comment]
I'm using rubygems 3.3.3 with bundler 2.3.20 and it still doesn't work. Please reopen.

**Comment by deivid-rodriguez** [comment]
H @zenspider! Please open a separate issue with reproducible steps, thanks!

**Comment by zenspider** [comment]
Literally exact same codebase and same scenario...
