### ISSUE TITLE
Bundler::BuildMetadata test filures

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#5926]
Trying to update Bundler package for Fedora and running the test suite during build, I observe two test failures:

~~~
$ rspec -rspec_helper spec/bundler/build_metadata_spec.rb
Run options: exclude {:man=>false, :truffleruby_only=>true, :jruby_only=>true, :readline=>false, :permissions=>false, :no_color_tty=>false, :ruby_repo=>true, :rubygems=>"!= 3.3.7", :bundler=>"!= 2", :git=>"!= 2.37.3", :realworld=>true, :sudo=>true}
.F.F

Failures:

  1) Bundler::BuildMetadata#release? returns false as default
     Failure/Error: expect(Bundler::BuildMetadata.release?).to be_falsey
     
       expected: falsey value
            got: true
     # ./spec/bundler/build_metadata_spec.rb:20:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:103:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:103:in `block (3 levels) in <top (required)>'
     # ./spec/support/helpers.rb:350:in `block in with_gem_path_as'
     # ./spec/support/helpers.rb:364:in `without_env_side_effects'
     # ./spec/support/helpers.rb:345:in `with_gem_path_as'
     # ./spec/spec_helper.rb:102:in `block (2 levels) in <top (required)>'

  2) Bundler::BuildMetadata#to_h returns a hash includes Built At, Git SHA and Released Version
     Failure/Error: expect(subject["Released Version"]).to be_falsey
     
       expected: falsey value
            got: true
     # ./spec/bundler/build_metadata_spec.rb:46:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:103:in `block (4 levels) in <top (required)>'
     # ./spec/spec_helper.rb:103:in `block (3 levels) in <top (required)>'
     # ./spec/support/helpers.rb:350:in `block in with_gem_path_as'
     # ./spec/support/helpers.rb:364:in `without_env_side_effects'
     # ./spec/support/helpers.rb:345:in `with_gem_path_as'
     # ./spec/spec_helper.rb:102:in `block (2 levels) in <top (required)>'

Finished in 0.78052 seconds (files took 0.14217 seconds to load)
4 examples, 2 failures

Failed examples:

rspec ./spec/bundler/build_metadata_spec.rb:19 # Bundler::BuildMetadata#release? returns false as default
rspec ./spec/bundler/build_metadata_spec.rb:43 # Bundler::BuildMetadata#to_h returns a hash includes Built At, Git SHA and Released Version
~~~

I was trying to wrap my head around just to finally realize, that the released file has different content then the upstream code:

~~~diff
--- a/build_metadata.rb
+++ b/build_metadata.rb
@@ -4,7 +4,9 @@
   # Represents metadata from when the Bundler gem was built.
   module BuildMetadata
     # begin ivars
-    @release = false
+    @built_at = "2022-09-07".freeze
+    @git_commit_sha = "44fb4c9ef5".freeze
+    @release = true
     # end ivars
 
     # A hash representation of the build metadata.
~~~

And now I wonder, is there a chance to make this less surprising? E.g. use some filter for the test. Or even don't make such code changes by release script.

Since I understand the issue now, I'm just going to apply some local medicine to the issue. So it is not really big deal if this is not addressed upstream. I just thought I'll ask, since it took me some time to understand what is going on.

**Comment by deivid-rodriguez** [comment]
Maybe a better spec failure error message would suffice?

**Comment by voxik** [comment]
> Maybe a better spec failure error message would suffice?

Funny. Looking at the issue again and trying to remember what was it about, from the understandability POV, wouldn't it be better to have different description of the first failed test case? But better error message would help as well.

BTW this is the workaround I applied to make the test suite pass:

https://src.fedoraproject.org/rpms/rubygem-bundler/blob/7f2af6f9a9a21dd739e70fc3b1ed5f498cecef02/f/rubygem-bundler.spec#_184-186

**Comment by deivid-rodriguez** [comment]
> wouldn't it be better to have different description of the first failed test case?

That would probably help too, what would you suggest? These changes are easy changes, so let's do it.

**Comment by deivid-rodriguez** [comment]
I don't this kind of issue needs a tracking ticket, since it's unlikely that maintainers will ever work on this. Please open a PR directly if you have improvements to propose here 👍.
