### ISSUE TITLE
Exponential growth in bundle resolution steps 

### ISSUE THREAD

**Issue by soulcutter** [rubygems/rubygems#5930]
### Describe the problem as clearly as you can

Ran into a strange issue at work where resolving gems in a bundle (not installing) was taking 3-5 minutes. It was not always this way, and it's unclear what is going on, but we did find a way to fix it that you'd never expect!

```
BUNDLER: Finished resolution (98145 steps) (Took 212.483564 seconds) (2022-09-15 13:48:59 -0400)
```

this was a gem, and had a dev dependency on rack AND a non-dev dependency on rails. Seems like rails will include rack anyway. Removing `s.add_development_dependency('rack')` changed the behavior like so:

```
BUNDLER: Finished resolution (289 steps) (Took 1.206765 seconds) (2022-09-15 14:11:36 -0400)
```

#### Theory

rack 3.0.0 was released Sept 6th 2022 (today is Sept 15). This may be causing dependency resolution dead end from libraries that have not-yet been updated. Still, the explosion looks exponential and not what I would expect.

Removing the `rack` dependency drastically reduces the resolution steps.
Pinning it to `'< 3.0.0'` also drastically reduces resolution steps.

I think this behavior is not a linear multiplier, but rather exponential based on my (unsharable) work project taking 100k steps (vs 250 steps without `rack`). This sample reproduction only hits 800 steps (vs 100 steps without `rack`).

I feel like this could be a pathological behavior that you'd be unlikely to encounter except that `rack` is a common dependency and there must be a combo of projects that are permissive and pinned to `< 3.0.0`. In other words: this may or may not be acceptable behavior

### Did you try upgrading rubygems & bundler?

This same behavior has been verified on bundler versions `2.3.11` and `2.3.22`
I saw this on Mac OSX and Alpine Linux (via CircleCI)

### Post steps to reproduce the problem

I created a repo with instructions to reproduce (not docker, sorry): https://github.com/soulcutter/resolution_explosion

### Which command did you run?

```
DEBUG_RESOLVER=1 bundle lock --print | grep "Finished resolution"
```

### What were you expecting to happen?

Bundle resolution to complete quickly and with a reasonable number of steps

### What actually happened?

Bundle resolution to completing slowly with many more steps.

In my private project:
```
BUNDLER: Finished resolution (98145 steps) (Took 212.483564 seconds) (2022-09-15 13:48:59 -0400)
```

in my public reproduction repository:
```
BUNDLER: Finished resolution (816 steps) (Took 2.0365 seconds) (2022-09-15 17:18:16 -0400)
```

NOTE: I expect these numbers to change over time as more projects accept `rack` 3.0.0

## Environment

```
Bundler       2.3.22
  Platforms   ruby, x86_64-darwin-21
Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x86_64-darwin-21]
  Full Path   /Users/bradleyschaefer/.asdf/installs/ruby/3.1.2/bin/ruby
  Config Dir  /Users/bradleyschaefer/.asdf/installs/ruby/3.1.2/etc
RubyGems      3.3.7
  Gem Home    /Users/bradleyschaefer/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0
  Gem Path    /Users/bradleyschaefer/.gem/ruby/3.1.0:/Users/bradleyschaefer/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0
  User Home   /Users/bradleyschaefer
  User Path   /Users/bradleyschaefer/.gem/ruby/3.1.0
  Bin Dir     /Users/bradleyschaefer/.asdf/installs/ruby/3.1.2/bin
Tools         
  Git         2.37.3
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-09-07
Git SHA           44fb4c9ef5
Released Version  true
```

## Bundler settings

```
gem.changelog
  Set for the current user (/Users/bradleyschaefer/.bundle/config): false
gem.ci
  Set for the current user (/Users/bradleyschaefer/.bundle/config): "github"
gem.coc
  Set for the current user (/Users/bradleyschaefer/.bundle/config): false
gem.linter
  Set for the current user (/Users/bradleyschaefer/.bundle/config): false
gem.mit
  Set for the current user (/Users/bradleyschaefer/.bundle/config): false
gem.test
  Set for the current user (/Users/bradleyschaefer/.bundle/config): "rspec"
https://gem.fury.io/me/
  Set for the current user (/Users/bradleyschaefer/.bundle/config): "[REDACTED]"
jobs
  Set for the current user (/Users/bradleyschaefer/.bundle/config): 8
[REDACTED].jfrog.io
  Set for the current user (/Users/bradleyschaefer/.bundle/config): "[REDACTED]"
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

# Specify your gem's dependencies in resolution_explosion.gemspec
gemspec

gem "rake", "~> 13.0"

gem "rspec", "~> 3.0"
```

### Gemfile.lock

```
<No /Users/bradleyschaefer/Projects/resolution_explosion/Gemfile.lock found>
```

### resolution_explosion.gemspec

```ruby
# frozen_string_literal: true

require_relative "lib/resolution_explosion/version"

Gem::Specification.new do |spec|
  spec.name = "resolution_explosion"
  spec.version = ResolutionExplosion::VERSION
  spec.authors = ["Bradley Schaefer"]
  spec.email = ["bradley.schaefer@gmail.com"]

  spec.summary = "Write a short summary, because RubyGems requires one."
  spec.description = "Write a longer description or delete this line."
  spec.homepage = "https://soulcutter.com"
  spec.required_ruby_version = ">= 2.6.0"

  #spec.metadata["allowed_push_host"] = "TODO: Set to your gem server 'https://example.com'"

  spec.metadata["homepage_uri"] = spec.homepage
  #spec.metadata["source_code_uri"] = "TODO: Put your gem's public repo URL here."
  #spec.metadata["changelog_uri"] = "TODO: Put your gem's CHANGELOG.md URL here."

  # Specify which files should be added to the gem when it is released.
  # The `git ls-files -z` loads the files in the RubyGem that have been added into git.
  spec.files = Dir.chdir(__dir__) do
    `git ls-files -z`.split("\x0").reject do |f|
      (f == __FILE__) || f.match(%r{\A(?:(?:bin|test|spec|features)/|\.(?:git|travis|circleci)|appveyor)})
    end
  end
  spec.bindir = "exe"
  spec.executables = spec.files.grep(%r{\Aexe/}) { |f| File.basename(f) }
  spec.require_paths = ["lib"]

  # Uncomment to register a new dependency of your gem
  # spec.add_dependency "example-gem", "~> 1.0"
  spec.add_dependency "concurrent-ruby"
  spec.add_dependency('faraday', '>= 1.0')
  spec.add_dependency "rails"
  #spec.add_development_dependency "rack"
  spec.add_development_dependency('climate_control')
  spec.add_development_dependency('derailed_benchmarks')
  spec.add_development_dependency('memory_profiler')
  spec.add_development_dependency('resque')
  spec.add_development_dependency('rspec')
  spec.add_development_dependency('rspec_junit_formatter')

  # For more information and examples about making a new gem, check out our
  # guide at: https://bundler.io/guides/creating_gem.html
end
```

**Comment by soulcutter** [comment]
I notice https://github.com/rubygems/rubygems/issues/5843 has similarity. In my case a valid set of gems was resolved, but it was doing a LOT of work to get there, with many of the same debug messages about unmet stuff and unwinding resolution.

**Comment by deivid-rodriguez** [comment]
Thanks for reporting this @soulcutter. Coincidentally I've been working recently on migrating our resolver internally to PubGrub which is a better resolution engine that does not have these issues. [This branch](https://github.com/rubygems/rubygems/tree/pub_grub) is still in beta state, but should fix this problem, can you try it?

**Comment by soulcutter** [comment]
It was better. The debug output was not available via that `DEBUG_RESOLVER=1` flag, so I ran it with `time`:

```
DEBUG_RESOLVER=1 ruby ../rubygems/bundler/spec/support/bundle.rb lock --print  15.17s user 1.11s system 72% cpu 22.523 total
```
