### ISSUE TITLE
Man page for `--keep-file-descriptors` flag of `bundle exec` is not clear

### ISSUE THREAD

**Issue by beatak** [rubygems/rubygems#5932]
### Describe the problem as clearly as you can

It seems this PR https://github.com/rubygems/rubygems/pull/4812 made `--keep-file-descriptors` as default `true`. According to [CHANGELOG](https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md#2226-august-17-2021), with `bundler` version `2.2.26` and forward, `bundle exec` keeps file descriptors, but it doesn't say that on the man document.

I think this should be clearly stated on the man page (and the web) so that many of us don't have to type 23 long characters anymore.

**Comment by deivid-rodriguez** [comment]
Hi, indeed!

Could you open a pull request clarifying this?

**Comment by manuraj17** [comment]
@deivid-rodriguez Is this still relevant? Looking at the man file for exec we still don't mention it's by default `true`, so I could update that but, I was looking at https://github.com/rubygems/bundler-site/issues/930 and couldn't figure the validity of this task. 🙏🏽

**Comment by deivid-rodriguez** [comment]
I this it's still valid, yes.

We should update the man page explaining that the default is true, and that setting it to false is deprecated.
