### ISSUE TITLE
`arm-linux` gem platform no longer matches `arm-linux-*` runtimes

### ISSUE THREAD

**Issue by flavorjones** [rubygems/rubygems#5940]
### Describe the problem as clearly as you can

In Rubygems 3.3.20 and earlier, a gem with platform "arm-linux" would match a runtime platform "arm-linux-eabi" (and others). In Rubygems 3.3.21 and later, it does not.

```ruby
#! /usr/bin/env ruby

Gem::VERSION # => "3.3.20"

x86_64_linux = Gem::Platform.new("x86_64-linux")
x86_64_linux_musl = Gem::Platform.new("x86_64-linux-musl")

x86_64_linux === x86_64_linux_musl # => true

arm_linux = Gem::Platform.new("arm-linux")
arm_linux_eabi = Gem::Platform.new("arm-linux-eabi")
arm_linux_eabihf = Gem::Platform.new("arm-linux-eabihf")

arm_linux === arm_linux_eabi # => true
arm_linux === arm_linux_eabihf # => true
```

vs

```ruby
#! /usr/bin/env ruby

Gem::VERSION # => "3.3.21"

x86_64_linux = Gem::Platform.new("x86_64-linux")
x86_64_linux_musl = Gem::Platform.new("x86_64-linux-musl")

x86_64_linux === x86_64_linux_musl # => true

arm_linux = Gem::Platform.new("arm-linux")
arm_linux_eabi = Gem::Platform.new("arm-linux-eabi")
arm_linux_eabihf = Gem::Platform.new("arm-linux-eabihf")

arm_linux === arm_linux_eabi # => false
arm_linux === arm_linux_eabihf # => false
```

As a result, `gem install nokogiri` on an arm system does not select the `arm-linux` platform gem. With rubygems < 3.3.21 this command will select the `arm-linux` platform gem.

I believe this is the desired behavior, in the form of an addition to the test suite:

```patch
diff --git a/test/rubygems/test_gem_platform.rb b/test/rubygems/test_gem_platform.rb
index f683204..99395b4 100644
--- a/test/rubygems/test_gem_platform.rb
+++ b/test/rubygems/test_gem_platform.rb
@@ -306,6 +306,7 @@ def test_nil_version_is_stricter_for_linux_os
   end
 
   def test_eabi_version_is_stricter_for_linux_os
+    arm_linux = Gem::Platform.new "arm-linux"
     arm_linux_eabi = Gem::Platform.new "arm-linux-eabi"
     arm_linux_gnueabi = Gem::Platform.new "arm-linux-gnueabi"
     arm_linux_musleabi = Gem::Platform.new "arm-linux-musleabi"
@@ -331,6 +332,12 @@ def test_eabi_version_is_stricter_for_linux_os
     # other libc are not glibc compatible
     refute(arm_linux_eabi === arm_linux_uclibceabi, "linux-eabi =~ linux-uclibceabi")
     refute(arm_linux_uclibceabi === arm_linux_eabi, "linux-uclibceabi =~ linux-eabi")
+
+    # gems with platform "arm-linux" should match any of these
+    assert(arm_linux === arm_linux_eabi, "arm_linux === arm_linux_eabi")
+    assert(arm_linux === arm_linux_gnueabi, "arm_linux === arm_linux_gnueabi")
+    assert(arm_linux === arm_linux_musleabi, "arm_linux === arm_linux_musleabi")
+    assert(arm_linux === arm_linux_uclibceabi, "arm_linux === arm_linux_uclibceabi")
   end
 
   def test_equals3_cpu_arm
```

### Did you try upgrading RubyGems?

Issue introduced by #5852 and present on `master` and in 3.3.22

### Post steps to reproduce the problem

In the `ruby:3.1` docker image with platform `linux/arm/v7` (runtime platform string is `arm-linux-eabihf`), running `gem install nokogiri` should select Nokogiri's `arm-linux` gem platform.

### What were you expecting to happen?

`arm-linux` gems should match `arm-linux-eabi` (and other libc versions) the same way that `x86_64-linux` matches `x86_64-linux-musl`.

**Comment by indirect** [comment]
Are you proposing that RubyGems ought to accept `arm-linux-eabi` gems on `arm-linux` machines, even though it is not acceptable for `x86_64-linux-musl` to install onto `x86_64-linux` machines? Or is your point that it should try for the most specific option and fail back to a less specific option if a more specific one is not available?

Phrased a different way, what do you think should actually happen here, and why? A bug report for a deliberate change with no explanation isn't going to help us get things working correctly.

**Comment by flavorjones** [comment]
No, I'm saying that a `arm-linux` gem should be acceptable on `arm-linux-eabi` machines. This is what previously was matched and gems like nokogiri are relying on that behavior for precompiled native gems.

**Comment by flavorjones** [comment]
If I am on a `arm-linux-eabi` machine, then `gem install nokogiri` should select the `arm-linux` gem as in all version prior to rubygems 3.3.21.

> A bug report for a deliberate change, with no explanation about why we should change things back, isn't going to help us get things working correctly.

First, I'm filing this bug under the belief that this was not a deliberate change, but an oversight.

I've filed a series of bugs and submitted a few fixes around the precompiled native gem platform support and I was hoping that we all had some shared context and that I had earned a little bit of trust in doing so.

**Comment by flavorjones** [comment]
cc @deivid-rodriguez who I've been working with on these issues.

**Comment by indirect** [comment]
You have my trust! But David is on vacation, and I don't have enough immediate context available to know what you want changed, and how, and why. I also want to make sure that we don't break things for the musl folks at the same time.

**Comment by flavorjones** [comment]
Got it. I don't think this is urgent -- the behavior changed a few weeks ago and nobody has complained (yet), this is something that started happening in CI, and the fallback behavior is to build from source (which although slow, will still work for most folks).

**Comment by flavorjones** [comment]
I've updated the description with a bit more description concrete impact of this behavior (i.e., precompiled native gems).

**Comment by flavorjones** [comment]
And I've added the specific assertions (in the form of a patch) that I believe reflect the intended behavior post-#5852.

**Comment by deivid-rodriguez** [comment]
I'm back now, I'll have a look at this tomorrow! 👍

**Comment by deivid-rodriguez** [comment]
#5957 should fix this!

@flavorjones Note that from the tests you proposed, for the last one (uclibc) my PR expects actually the opposite. It's true that things worked differently before 3.3.21, but I think that particular case was an intentional change.

#5852 introduced the following assertion:

```ruby
# other libc are not glibc compatible
refute(x86_linux === x86_linux_uclibc, "linux =~ linux-uclibc")
```

Then #5889 introduced:

```ruby
# other libc are not glibc compatible
refute(arm_linux_eabi === arm_linux_uclibceabi, "linux-eabi =~ linux-uclibceabi")
```

So expecting the arm-linux-uclibceabi runtime platform to NOT match generic arm-linux gems either seems like the right thing to do here to me.

**Comment by flavorjones** [comment]
I've posted a question at #5957 about the expected behavior on systems that use `arm-linux-eabihf`.
