### ISSUE TITLE
google-cloud-text_to_speech gem is not supported in ruby 2.5

### ISSUE THREAD

**Issue by Gauravpurohit409** [rubygems/rubygems#5966]
### Describe the problem as clearly as you can

google-cloud-text_to_speech gem describes RUBY VERSION: >= 2.5 in https://rubygems.org/gems/google-cloud-text_to_speech/versions/1.2.2 but when I tried to install it, there is one dependent gem gRPC which requires ruby version >= 2.6 

### Did you try upgrading RubyGems?

yes

The system setup is as follows:
-  MAC OS, 
-  Ruby 2.5,
-  Rails 6.0.3.6

### Which command did you run?

- gem install google-cloud-text_to_speech -v 1.2.2

### What were you expecting to happen?
- To install the google-cloud-text_to_speech gem

### What actually happened?

- Throw an error stating :
     ` grpc-1.49.1-x86_64-darwin requires ruby version >= 2.6, < [3.2.dev](http://3.2.dev/), which is incompatible with the current version, ruby 2.5.3p105
`

**Comment by simi** [comment]
Hello, please report to https://github.com/googleapis/google-cloud-ruby. Anyway Ruby 2.5 is EOL and is not supported anymore.
