### ISSUE TITLE
bundle config build.<gem> can't pass multiple arguments to `--with-ldflags` delimited by a space

### ISSUE THREAD

**Issue by stanhu** [rubygems/rubygems#5972]
### Describe the problem as clearly as you can

I have one instance where I'd like to configure `--with-ldflags` with multiple arguments delimited by a space. For example:

```shell
bundle config build.grpc --with-ldflags='-Wl,--no-as-needed -latomic'
```

However, due to the use of `Shellwords.shellsplit` here:

https://github.com/rubygems/rubygems/blob/629e08d34d14f60fe3398e40fc72f4f171ffc582/bundler/lib/bundler/installer/gem_installer.rb#L49

...the space between `-Wl,--no-as-needed` and `-latomic` is always broken up, and `extconf.rb` doesn't appear to be passed any custom `LDFLAGS`. I can't find a way to escape it.

I believe the use of `Shellwords.shellsplit` was used in order to handle multiple arguments properly (https://github.com/rubygems/bundler/issues/6940).

### Did you try upgrading rubygems & bundler?

Yes.

### Post steps to reproduce the problem

Use this `Gemfile`:

```ruby
source 'https://rubygems.org'

gem 'grpc', '1.49.1'
```

```shell
bundle config path vendor
bundle config build.grpc --with-ldflags='-Wl,--no-as-needed -latomic'
BUNDLE_FORCE_RUBY_PLATFORM=1 bundle install
```

### What were you expecting to happen?

The resulting `./vendor/ruby/2.7.0/gems/grpc-1.49.1/src/ruby/lib/grpc/grpc_c.so` should have a link to `libatomic`, but it does not:

```
$ ldd ./vendor/ruby/2.7.0/gems/grpc-1.49.1/src/ruby/lib/grpc/grpc_c.so
        linux-vdso.so.1 (0x00007ffdb92f1000)
        libruby.so.2.7 => /home/stanhu/.rbenv/versions/2.7.5/lib/libruby.so.2.7 (0x00007f4c925d3000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4c92484000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4c92292000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4c930d3000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4c9226f000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f4c92253000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f4c92247000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4c92241000)
        libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f4c92206000)
```

However, I can workaround the problem by using `--with-dldflags` in addition to `--with-ldflags`:

```
bundle config build.grpc --with-ldflags=-Wl,--no-as-needed --with-dldflags=-latomic
```

The resulting `grpc_c.so` now has this:

```
$ ldd ./vendor/ruby/2.7.0/gems/grpc-1.49.1/src/ruby/lib/grpc/grpc_c.so
        linux-vdso.so.1 (0x00007ffdb92f1000)
        libatomic.so.1 => /usr/lib/x86_64-linux-gnu/libatomic.so.1 (0x00007f4c9292e000)
        libruby.so.2.7 => /home/stanhu/.rbenv/versions/2.7.5/lib/libruby.so.2.7 (0x00007f4c925d3000)
        libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f4c92484000)
        libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f4c92292000)
        /lib64/ld-linux-x86-64.so.2 (0x00007f4c930d3000)
        libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f4c9226f000)
        libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f4c92253000)
        librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f4c92247000)
        libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f4c92241000)
        libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f4c92206000)
```

**Comment by deivid-rodriguez** [comment]
If you change the contents of `.bundle/config` and add quotes at the proper place, does it work?

**Comment by stanhu** [comment]
Yes, it does. 

Actually, it seems that I need to escape the quotes like so:

```
bundle config build.grpc --with-ldflags=\'-Wl,--no-as-needed -latomic\'
```

I thought I tried various different combinations, but I guess I didn't try them all.
