### ISSUE TITLE
Incorrect candidate resolution for prerelease gems when using `required_ruby_version` in v3.3.24

### ISSUE THREAD

**Issue by ianks** [rubygems/rubygems#6005]
When specifying a `required_ruby_version` range for a gem, Rubygems does not account for pre-releases in the gem range.

```
$ gem install wasmtime-rb-0.1.0-arm64-darwin.gem
wasmtime-rb-0.1.0-arm64-darwin requires Ruby version >= 3.0, < 3.1.dev. The current ruby version is 3.1.2.
```

This gem was precompiled using `rake-compiler`, [which sets the end range to be `< X.X.dev`](https://github.com/rake-compiler/rake-compiler/blob/31a2b8f325001c8aa55c078e85eb054b3bff649b/lib/rake/extensiontask.rb#L284).

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.3.24
  - RUBY VERSION: 3.1.2 (2022-04-12 patchlevel 20) [arm64-darwin21]
```

**Comment by flavorjones** [comment]
@ianks I'm not sure I understand -- this seems to be working as designed. "< 3.1.dev" does not include 3.1 prereleases as well as 3.1.0, 3.1.1, 3.1.2 ...

You can test this with Ruby code. Will the Ruby version "3.1.2" match the constraint "< 3.1.dev"?

```ruby
Gem::Requirement.new("< 3.1.dev").satisfied_by?(Gem::Version.new("3.1.2"))
# => false
```

**Comment by ianks** [comment]
I get the intention now. The semantics confused me a bit with the patch version not being included. Sorry for the noise!

**Comment by ianks** [comment]
For more context, the issue stemmed from [this PR](https://github.com/bytecodealliance/wasmtime-rb/pull/1/files). Wondering now if the order of `RUBY_CC_VERSION` threw RCD off? I'll let you know!
