### ISSUE TITLE
`bundle init` should respect `BUNDLE_GEMFILE`

### ISSUE THREAD

**Issue by dentarg** [rubygems/rubygems#6016]
### Describe the problem as clearly as you can

```
$ bundle -v
Bundler version 2.3.24

$ BUNDLE_GEMFILE=foo bundle init
Writing new Gemfile to /tmp/Gemfile
```

I was expecting `/tmp/foo` to be created as `bundle config --help` says this about `BUNDLE_GEMFILE`

>The name of the file that bundler should use as the Gemfile. This location of this file also sets the root of the project, which is used to resolverelative paths in the Gemfile, among other things. By default, bundler will search up from the current working directory until it finds a Gemfile.

**Comment by gustavothecoder** [comment]
Can I try to resolve this problem?

**Comment by dentarg** [comment]
Feel free :)

**Comment by manuraj17** [comment]
Can this issue be considered as closed with this PR https://github.com/rubygems/rubygems/pull/6046 @deivid-rodriguez @dentarg ?

**Comment by deivid-rodriguez** [comment]
Indeed, thanks for noticing @manuraj17!
