### ISSUE TITLE
Consolidate ENV list for CI detection

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#6038]
We currently have two different list of environment variables for CI detection. One used by Bundler to include the CI where it's running with request headers, so that we can later on extract metrics. Another one introduced in RubyGems to be able to avoid needless call for updates messages on CI environments.

Since these lists are used for the same thing (detecting whether we are running on a CI environment), we should probably unify them and keep them in the same place.

**Comment by nevinera** [comment]
Some of this data is pretty out of date too. BuildKite deprecated their BUILDBOX envs a year ago, and Snap CI went under in 2017. I'll document the provenance of each of the envs while I'm in here.
