### ISSUE TITLE
rubygems-server was warned to be removed in RubyGems 4 but is already missing in RubyGems 3.3.7

### ISSUE THREAD

**Issue by eregon** [rubygems/rubygems#6044]
rubygems-server was warned to be removed in RubyGems 4:
```
$ chruby 3.0.3                   
$ gem --version
3.2.32                                                   
$ gem server --help
WARNING:  server command is deprecated. It will be removed in Rubygems 4.
```
but is already missing in RubyGems 3.3.7:
```
$ chruby 3.1.2        
$ gem --version          
3.3.7                                  
$ gem server -p 0 -d gems
ERROR:  While executing gem ... (Gem::OptionParser::InvalidOption)
    invalid option: -p
```
Any reason? It's rather confusing.

Note: it was removed in RubyGems 3.3.0: https://github.com/rubygems/rubygems/blob/master/CHANGELOG.md#330--2021-12-21

Also the rubygems-server gem works OK on 3.1.2 but is kind of broken on 3.0.2:
```
$ chruby 3.0.3       
$ gem install rubygems-server
$ gem server --help      
/home/eregon/.rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/server.rb:36: warning: already initialized constant Gem::Server::SEARCH
/home/eregon/.rubies/ruby-3.0.3/lib/ruby/gems/3.0.0/gems/rubygems-server-0.2.0/lib/rubygems/server.rb:36: warning: previous definition of SEARCH was here
/home/eregon/.rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/server.rb:46: warning: already initialized constant Gem::Server::DOC_TEMPLATE
/home/eregon/.rubies/ruby-3.0.3/lib/ruby/gems/3.0.0/gems/rubygems-server-0.2.0/lib/rubygems/server.rb:46: warning: previous definition of DOC_TEMPLATE was here
/home/eregon/.rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/server.rb:130: warning: already initialized constant Gem::Server::RDOC_CSS
/home/eregon/.rubies/ruby-3.0.3/lib/ruby/gems/3.0.0/gems/rubygems-server-0.2.0/lib/rubygems/server.rb:130: warning: previous definition of RDOC_CSS was here
/home/eregon/.rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/server.rb:340: warning: already initialized constant Gem::Server::RDOC_NO_DOCUMENTATION
/home/eregon/.rubies/ruby-3.0.3/lib/ruby/gems/3.0.0/gems/rubygems-server-0.2.0/lib/rubygems/server.rb:340: warning: previous definition of RDOC_NO_DOCUMENTATION was here
/home/eregon/.rubies/ruby-3.0.3/lib/ruby/3.0.0/rubygems/server.rb:374: warning: already initialized constant Gem::Server::RDOC_SEARCH_TEMPLATE
/home/eregon/.rubies/ruby-3.0.3/lib/ruby/gems/3.0.0/gems/rubygems-server-0.2.0/lib/rubygems/server.rb:374: warning: previous definition of RDOC_SEARCH_TEMPLATE was here
WARNING:  server command is deprecated. It will be removed in Rubygems 4.
```

**Comment by deivid-rodriguez** [comment]
Yeah, I guess we missed the deprecation horizon when this was removed.

We could fix the deprecation message and backport it to old RubyGems, or restore the command. Both options seem a bit overkill to me given that nobody has cared much about this.

**Comment by eregon** [comment]
One thing which is particularly confusing is `gem server -p 0 -d gems` fails with `invalid option: -p` (see above) and not "use rubygems-server" and also there seems to have never been a message telling to use gemstash as a replacement, like discussed in https://github.com/rubygems/rubygems/pull/3868.
So basically it looks like a RubyGems bug instead of telling users what to use instead.

`gem server --help` only mentions rubygems-server:
```
$ gem server --help                                     
Usage: gem server [options]


  Common Options:
    -h, --help                       Get help on this command
    -V, --[no-]verbose               Set the verbose level of output
    -q, --quiet                      Silence command progress meter
        --silent                     Silence RubyGems output
        --config-file FILE           Use this config file instead of default
        --backtrace                  Show stack backtrace on errors
        --debug                      Turn on Ruby debugging
        --norc                       Avoid loading any .gemrc file


  Summary:
    Starts up a web server that hosts the RDoc (requires rubygems-server)

  Description:
    The server command has been moved to the rubygems-server gem.
```
Since it was removed for security concerns, telling users to use the same code, but even less maintained seems not ideal.

**Comment by eregon** [comment]
And https://github.com/rubygems/rubygems-server doesn't say anything about being deprecated or unmaintained or development-only or so, and no link to gemstash either.

**Comment by eregon** [comment]
> Both options seem a bit overkill to me given that nobody has cared much about this.

Indeed. I think we should fix the error in latest RubyGems (and link to gemstash) and make it clear what's the purpose of this separate gem and what should be used instead.

**Comment by deivid-rodriguez** [comment]
Agree, even if we don't restore the command, we could print a better error.

**Comment by hsbt** [comment]
I update `required_ruby_version` of rubygems-server and [update README](https://github.com/rubygems/rubygems-server/commit/55a910c18412213e960c385642f2a7dc6a98f36d).

**Comment by hsbt** [comment]
I will release RubyGems 3.2.34 with correct deprecation warnings at https://github.com/rubygems/rubygems/pull/6027 before releasing the final stable version of Ruby 3.0 series.

**Comment by hsbt** [comment]
I released https://github.com/rubygems/rubygems/releases/tag/v3.2.34 and It will be backport to next version of Ruby 3.0 at https://github.com/ruby/ruby/pull/7251
