### ISSUE TITLE
gem task/spec.to_ruby uses current platform, not spec.platform

### ISSUE THREAD

**Issue by byteit101** [rubygems/rubygems#6056]
### Describe the problem as clearly as you can

This seems similar to https://github.com/rubygems/rubygems/issues/147 in that @platform and @original_platform differ, and original_platform is being used for spec.to_ruby. 

When building with something that calls `spec.to_ruby`, the original platform is kept, and a gem with the suffix of the new platform is generated, but the manifest lists the incorrect platform

### Did you try upgrading RubyGems?

Yes

### Post steps to reproduce the problem

 * `bundler gem examplegem`
 * Add ` spec.platform=Gem::Platform.local` (and fix the TODO's) in the gemspec
 * Change the rakefile to the below
 * `rake doit && tar xfO pkg/examplegem-0.1.0-java.gem metadata.gz | zcat | grep platform; rm -rf pkg`

Note the output of the "java" gem: `platform: x86_64-linux`. This is incorrect

#### Rakefile
```rb
require 'rubygems/package_task'
require 'bundler'
task :doit do
	spec = Gem::Specification::load("examplegem.gemspec").dup
	spec.platform = Gem::Platform.new("java")
	#p spec.to_ruby
	task = Gem::PackageTask.new(spec)
	task.define
	task(:gem).invoke()
end
```

### Workaround

Modifying the Rakefile to set the undocumented original_platform `spec.original_platform = spec.platform = Gem::Platform.new("java")` outputs the correct result:

```
platform: java
```

**Comment by deivid-rodriguez** [comment]
@byteit101 Thanks for reporting this! It seems that you digged quite a bit into this. Amazed how we can still get connections to issues from 2011 😲.

Do you have any suggestions to fix this, or even better, would you be willing to give it a try yourself?

**Comment by deivid-rodriguez** [comment]
Actually, is this as simple as changing `Gem::Specification#to_ruby` to use `#original_platform` instead of `#platform`?

**Comment by byteit101** [comment]
I would have thought it was the reverse, as it uses original_platform today: https://github.com/rubygems/rubygems/blob/5e5aa1d6da6d1375ec2af87dadb99e23a28cba6f/lib/rubygems/specification.rb#L2478

**Comment by jeromedalbert** [comment]
I can reproduce the issue and submitted a possible PR to fix it: https://github.com/rubygems/rubygems/pull/8194
