### ISSUE TITLE
[proposal] don't inherit package's filesystem permissions when building a package

### ISSUE THREAD

**Issue by 0x1eef** [rubygems/rubygems#6078]
Hello !

I would like to propose that the files belonging to a gem are created with the permissions 0644 (or 0744 for executables) rather than inheriting the permissions from a file as it exists on the packager's filesystem. The motivating reason is described [in this comment](https://github.com/rubygems/rubygems/pull/1041#issuecomment-1327114649) - in a loosely related issue.  My proposal is slightly different to that issue because I propose that rather than solving the problem at install time, it could be solved when building a package.

I deicded to open this issue to start a discussion on the topic. 
I made a naive RubyGems patch locally, but it seems to achieve what I am hoping for:

```ruby
--- a/lib/rubygems/package.rb
+++ b/lib/rubygems/package.rb
@@ -265,7 +265,7 @@ def add_files(tar) # :nodoc:
 
       next unless stat.file?
 
-      tar.add_file_simple file, stat.mode, stat.size do |dst_io|
+      tar.add_file_simple file, 0644, stat.size do |dst_io|
         File.open file, "rb" do |src_io|
           dst_io.write src_io.read 16384 until src_io.eof?
         end
```

Could this at least be configurable ? As mentioned in https://github.com/rubygems/rubygems/pull/1041#issuecomment-1327114649 , the permissions on my local filesystem are not what I want to ship with the gem I build.

Thanks for your time!

**Comment by duckinator** [comment]
I agree that having RubyGems store the files with an appropriate (or at least predictable + known good) file permission is a good option.

However, it is worth noting that `gem push` can push a gem file created by anything (not just RubyGems itself), so having it correct it on install would still be a good idea.

In terms of specific permissions, I think this is what we would want:

- non-executable files: `0644` (`rw-r--r--`; owner read+write, everyone else can only read)
- executables and directories: `0755` (`rwxr-xr-x`; owner read + write + execute, everyone else can only read + execute)

I do not know if marking directories as executable on Windows or macOS will cause problems.

<details>
<summary>explanation of why directories need to be marked executable</summary>

On Unix/Unix-like systems (e.g. Linux and the BSDs), the execute permission (`x`) determines whether you can access the contents of the directory. I don't know the exact details of why, but [section 3.4 of the FreeBSD handbook](https://docs.freebsd.org/en/books/handbook/basics/#permissions) explains the behavior well.

```
puppy@orthrus.fox:~/test$ ls -l
total 1
drwxr-xr-x  2 puppy  puppy  3 Dec 31 20:09 demo/
puppy@orthrus.fox:~/test$ ls -l demo
total 1
-rw-r--r--  1 puppy  puppy  0 Dec 31 20:08 example.txt
puppy@orthrus.fox:~/test$ chmod -x demo
puppy@orthrus.fox:~/test$ ls -l
total 1
drw-r--r--  2 puppy  puppy  3 Dec 31 20:09 demo/
puppy@orthrus.fox:~/test$ ls -l demo
ls: example.txt: Permission denied
total 0
puppy@orthrus.fox:~/test$ 
```

</details>

**Comment by 0x1eef** [comment]
> so having it correct it on install would still be a good idea regardless of if this is done. 

I agree. It would be better to do it at install time. I think not having a standard set of permissions could potentially cause a wide range of issues from suid binaries to permissions that are so loose (eg 777) that they could pose a risk if an account that doesn't manage gems became compromised. I remember that "bundle install" can overwrite the executables of other gems as well.
 
When you put it altogether, it doesn't sound good but I haven't done much testing on this, beyond confirming that permissions are inherited from the user's system when a gem is being built.

**Comment by deivid-rodriguez** [comment]
>  I remember that "bundle install" can overwrite the executables of other gems as well.

Can you expand on this a bit, to make sure there's not some other issue that we need to fix?

**Comment by 0x1eef** [comment]
That comment comes from a much older issue I reported ( & closed): https://github.com/rubygems/rubygems/issues/3312

**Comment by 0x1eef** [comment]
Hey :wave: I'm cleaning up my issue list. I'm going to close this one. And looks like there's been some improvements since this issue was opened. IIRC I now see a warning for files that are not globally readable during `gem build`.
