### ISSUE TITLE
breaking change to bundler on Xmas Eve :( 

### ISSUE THREAD

**Issue by danbf** [rubygems/rubygems#6193]
### Describe the problem as clearly as you can

```
ERROR:  Error installing bundler:
	The last version of bundler (>= 0) to support your Ruby & RubyGems was 2.3.26. Try installing it with `gem install bundler -v 2.3.26`
	bundler requires Ruby version >= 2.6.0. The current ruby version is 2.5.0.
```

### Which command did you run?

run `/home/nmapi/.rbenv/versions/2.5.1/bin/gem install --no-rdoc --no-ri bundler -v 2.3.26` on a `ruby version is 2.5.0` machine on Xmas Eve

### What were you expecting to happen?

Eat Xmas Eve lunch with the kids and open presents

### What actually happened?

Debugged things for 2 hours with my co-workers.

**Comment by deivid-rodriguez** [comment]
Sorry @danbf.

There does not seem to be anything actionable for us here. This is documented in the changelog and we decided to do it to be able to move on. Please update your Ruby, and RubyGems versions, just like you want to upgrade Bundler.

Have a happy Christmas!

**Comment by danbf** [comment]
Our fault for not pinning, but in our defense this was inherited code.

Happy Holidays.

**Comment by simi** [comment]
@danbf Indeed. If there's anything I can help you to move to non-EOL Ruby, let me know.

Happy Holidays.
