### ISSUE TITLE
Bundler update should update things, or explain why it didn't

### ISSUE THREAD

**Issue by fulldecent** [rubygems/rubygems#6211]
The command `bundle update && bundle outdated` should either fail on the first step or have no findings in the second.

### Describe the problem as clearly as you can

I ran the command `bundle update` and it ran and ended with a green line of encouragement.

<img width="521" alt="Screenshot 2022-12-28 at 12 34 26" src="https://user-images.githubusercontent.com/382183/209850813-67b7078a-f5b4-46e6-83a6-02c9fe0d5252.png">
<img width="522" alt="Screenshot 2022-12-28 at 12 35 26" src="https://user-images.githubusercontent.com/382183/209850819-81445f45-2b0d-4048-a8e7-d82ab044ee60.png">

Then afterwards I ran `bundle outdated`

<img width="581" alt="Screenshot 2022-12-28 at 12 34 20" src="https://user-images.githubusercontent.com/382183/209850873-ecf0e1d6-0d9b-4b04-b003-7bd7be221bb4.png">

And it says things were not updated.

I don't know why. And I don't care why. If I can speak loosely, this is a contradiction. Or, more correctly, this program output is unhelpful such that anybody reading those two things back-to-back is not going to be happy.

### Did you try upgrading rubygems & bundler?

Yes. But this didn't work

<img width="540" alt="Screenshot 2022-12-28 at 12 34 55" src="https://user-images.githubusercontent.com/382183/209851065-68cfe916-c0ae-426a-bb24-acc3f1c71ec0.png">

Also I don't have root access.

### Post steps to reproduce the problem

Using image 

<img width="572" alt="Screenshot 2022-12-28 at 12 39 00" src="https://user-images.githubusercontent.com/382183/209851148-6b609f01-2abc-4158-89db-2c708ce52107.png">

With Gemfile

<img width="332" alt="Screenshot 2022-12-28 at 12 34 33" src="https://user-images.githubusercontent.com/382183/209851110-1751badc-9b76-4b62-a003-c2281951eb7e.png">

### Which command did you run?

As above

### What were you expecting to happen?

Maybe the `bundle update` command will finish and say in yellow (NOT GREEN), some gems were not updated because... and it will have a return status of non-zero.

Or the `bundle outdated` command will output as it did above but also add a helpful note like "in order to get these new versions you need to ......., just running bundle update won't work because ......"

### What actually happened?

I kept running these two commands back to back a few times and then felt like green does not accurately reflect my sentiment.

### If not included with the output of your command, run `bundle env` and paste the output below

```
## Environment

```
Bundler       2.3.26
  Platforms   ruby, aarch64-linux
Ruby          2.7.7p221 (2022-11-24 revision 168ec2b1e5ad0e4688e963d9de019557c78feed9) [aarch64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.1.6
  Gem Home    /usr/local/rvm/gems/default
  Gem Path    /usr/local/rvm/gems/default:/usr/local/rvm/gems/default@global
  User Home   /home/vscode
  User Path   /home/vscode/.gem/ruby/2.7.0
  Bin Dir     /usr/local/rvm/gems/default/bin
Tools         
  Git         2.39.0
  RVM         1.29.12 (latest)
  rbenv       rbenv 1.2.0
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-11-17
Git SHA           23ec5b8501
Released Version  true
```

## Bundler settings

```
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
path
  Set for your local app (/usr/local/bundle/config): "/home/vscode/.gem"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```

## Gemfile

### Gemfile

```ruby
source 'https://rubygems.org'

gem 'jekyll'
gem 'lightning_sites'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.8.1)
      public_suffix (>= 2.0.2, < 6.0)
    colorator (1.1.0)
    colorize (0.8.1)
    concurrent-ruby (1.1.10)
    domain_name (0.5.20190701)
      unf (>= 0.0.5, < 1.0.0)
    em-websocket (0.5.3)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0)
    ethon (0.16.0)
      ffi (>= 1.15.0)
    eventmachine (1.2.7)
    ffi (1.15.5)
    forwardable-extended (2.6.0)
    google-protobuf (3.21.12)
    html-proofer (3.19.4)
      addressable (~> 2.3)
      mercenary (~> 0.3)
      nokogiri (~> 1.13)
      parallel (~> 1.10)
      rainbow (~> 3.0)
      typhoeus (~> 1.3)
      yell (~> 2.0)
    html-proofer-mailto_awesome (1.0.3)
      html-proofer (~> 3.0, >= 3.15.0)
    http (2.2.2)
      addressable (~> 2.3)
      http-cookie (~> 1.0)
      http-form_data (~> 1.0.1)
      http_parser.rb (~> 0.6.0)
    http-cookie (1.0.5)
      domain_name (~> 0.5)
    http-form_data (1.0.3)
    http_parser.rb (0.6.0)
    i18n (1.12.0)
      concurrent-ruby (~> 1.0)
    jekyll (4.3.1)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 1.0)
      jekyll-sass-converter (>= 2.0, < 4.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 2.3, >= 2.3.1)
      kramdown-parser-gfm (~> 1.0)
      liquid (~> 4.0)
      mercenary (>= 0.3.6, < 0.5)
      pathutil (~> 0.9)
      rouge (>= 3.0, < 5.0)
      safe_yaml (~> 1.0)
      terminal-table (>= 1.8, < 4.0)
      webrick (~> 1.7)
    jekyll-sass-converter (3.0.0)
      sass-embedded (~> 1.54)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    json (2.6.3)
    json-schema (2.8.1)
      addressable (>= 2.4)
    kramdown (2.4.0)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    lightning_sites (1.4.17)
      colorize (>= 0.8)
      html-proofer (>= 3.19.1)
      html-proofer-mailto_awesome (>= 1.0.1)
      nokogiri (>= 1.11.4)
      rake (>= 12.3.1)
      w3c_validators (>= 1.3.4)
      web-puc (>= 0.4.1)
      webrick (>= 1.7.0)
    liquid (4.0.3)
    listen (3.7.1)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    mercenary (0.4.0)
    nokogiri (1.13.10-aarch64-linux)
      racc (~> 1.4)
    parallel (1.22.1)
    pathutil (0.16.2)
      forwardable-extended (~> 2.6)
    public_suffix (5.0.1)
    racc (1.6.2)
    rainbow (3.1.1)
    rake (12.3.3)
    rb-fsevent (0.11.2)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rexml (3.2.5)
    rouge (4.0.1)
    safe-enum (0.3.1)
    safe_yaml (1.0.5)
    sass-embedded (1.57.1)
      google-protobuf (~> 3.21)
      rake (>= 10.0.0)
    structured-acceptance-test (0.0.6)
      colorize (~> 0.8, >= 0.8.1)
      json-schema (~> 2.8, >= 2.8.0)
      safe-enum (~> 0.3, >= 0.3.0)
    terminal-table (3.0.2)
      unicode-display_width (>= 1.1.1, < 3)
    typhoeus (1.4.0)
      ethon (>= 0.9.0)
    unf (0.1.4)
      unf_ext
    unf_ext (0.0.8.2)
    unicode-display_width (2.3.0)
    w3c_validators (1.3.7)
      json (>= 1.8)
      nokogiri (~> 1.6)
      rexml (~> 3.2)
    web-puc (0.4.1)
      http (~> 2.2)
      rake (~> 12)
      structured-acceptance-test (~> 0.0.6)
    webrick (1.7.0)
    yell (2.2.2)

PLATFORMS
  aarch64-linux

DEPENDENCIES
  jekyll
  lightning_sites

BUNDLED WITH
   2.3.26
```

**Comment by deivid-rodriguez** [comment]
Hi @fulldecent, totally agree with you, thanks for reporting this to us!

We should enhance `bundle update` output to explain when there's a more recent version but it's unable to update due to another gem locking the dependency or whatever.

This ticket is very similar to https://github.com/rubygems/rubygems/issues/3290. I think it probably makes sense to close this issue in favor of that one. I'll add a note that what's suggested there also applies to a full `bundle update`, not only to updating a specific gem.

**Comment by deivid-rodriguez** [comment]
Closing in favor of #3290, but let me know if you disagree and think we should keep this one opened separately!

**Comment by fulldecent** [comment]
Thank you, yes, this is a generalization of that issue. Good to proceed there.
