### ISSUE TITLE
Can't fetch GitHub gem with pull request URL starting with 2.4.0

### ISSUE THREAD

**Issue by etiennebarrie** [rubygems/rubygems#6239]
### Describe the problem as clearly as you can

Starting with 2.4.0, gems that use the provided `:github` source with a pull request URL (#5126) are not able to be fetched anymore.

### Did you try upgrading rubygems & bundler?

Yes, I ran  `gem update --system` and `bundle update --bundler` and that failed on my repo, then I bisected by running `bundle _2.3.24_ update --bundler` (the version used in that repo) and `bundle _2.4.0_ update --bundler` started failing.

### Post steps to reproduce the problem

You can use this repro script:

```ruby
# bug.rb
gem "bundler", ARGV.first != "bug" ? "2.3.26" : "2.4.0"
require "bundler/inline"

gemfile do
  source "https://rubygems.org"

  gem "reline", github: "https://github.com/ruby/reline/pull/488"
end
```

Running `gem install bundler:2.3.26 bundler:2.4.0` then `ruby bug.rb` works (using 2.3.26), but not `ruby bug.rb bug` (using 2.4.0).

### Which command did you run?

Originally it was a simple `bundle install`, running in a clean environment where the repo wasn't already fetched. If the Git repo is already fetched and cached, installing with 2.4.0 works fine.

### What were you expecting to happen?

Even if the PR is closed, we should be able to fetch its ref.

### What actually happened?

The remote ref couldn't be fetched.

**Comment by simi** [comment]
It seems that branch doesn't exist anymore (was deleted) and thanks to that it is not possible to fetch it anymore. There were some changes to pull only minimal git repo for bundler purpose which could be related, but if I understand it well, the outcome is simple -> don't point to deleted branch. It would not work before 2.4.0 as well in most of the cases (for example in clean bundle with git repo not cloned yet).

**Comment by etiennebarrie** [comment]
> It seems that branch doesn't exist anymore (was deleted) and thanks to that it is not possible to fetch it anymore.

GitHub keeps the pr refs (`refs/pull/:number/head`) even if the branch is deleted.

> There were some changes to pull only minimal git repo for bundler purpose which could be related,

Yes that's it. https://github.com/rubygems/rubygems/pull/4475 added the `--branch` param which doesn't work with one of those non-usual refs.

---

> Turns out this is actually broken for any PR, closed or open. #6241 should fix it!

Indeed even an open PR fails. 😄 Thanks for the quick turn-around, it does indeed fix my issue. I can see the Gemfile.lock being updated:

```diff
- branch: refs/pull/123/head
+ ref: refs/pull/123/head
```

**Comment by simi** [comment]
> GitHub keeps the pr refs (refs/pull/:number/head) even if the branch is deleted.

Ahh, thanks for the info. I had no idea.
