### ISSUE TITLE
[RFE] install/build dependency

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#624]
Recent version of nokogiri introduces runtime dependency on mini_portile. However, this is actually not a runtime dependency, but install time dependency, which is needed just for build of nokogiri's binary extension.

Would it be possible to get rid of such (non)runtime dependency? It is of any use for Windows users, since they get nokogiri precompiled and it is of any use for Fedora users, since they install precompiled rubygem-nokogiri as well. I believe this apply also for other distributions.

Thanks for considering.

**Comment by copiousfreetime** [comment]
I believe this issue is effectively proposing a new dependency type for the rubygems. A `build_dependency` that would need to be resolved by the installer and is used during the installation of a primary gem. After the primary gem is installed, the `build_dependency` gem would be removed and its `.gem` file left in the local cache.

**Comment by flavorjones** [comment]
I'm pleased and surprised to see this issue getting attention again. Let me know how I can support.

**Comment by voxik** [comment]
I am not saying it have to be removed after installation. I just don't need it for runtime. This is useful for Fedora packages, since we install the build dependency just during the build of the package. When our user installs the package, there is no need to have the build time package installed anymore

**Comment by copiousfreetime** [comment]
@voxik thanks for the clarification, it would definitely make things easier if we just left build dependencies installed. Maybe there could be an `uninstall --builddeps` or similar option that just uninstalled gems that were only build dependencies for those that want to minimize.

**Comment by copiousfreetime** [comment]
@flavorjones best way to support would be a pull request with a sample implementation with tests :smile:.

**Comment by flavorjones** [comment]
I've said in the past on this thread and the Nokogiri thread that I still don't understand the compelling reason to implement this. I get that it seems unclean, but having one additional gem installed on one's system doesn't seem to be that big of a deal.

Can someone explain to me what the pain point is, and provide enough detail for me to empathize with the amount of pain you're in?

@copiousfreetime I'm likely not qualified to operate on Rubygems, but understanding why this is important to people might help motivate me.

**Comment by copiousfreetime** [comment]
@flavorjones I'm going through all the rubygems issues attempting to gauge interest and understand them so we can prioritize and figure out what to work on. So clarifying the problems and making notes on potential approaches to solutions are what I'm doing right now. 

Whether or not a pull request will result from this issue, that's another question.
