### ISSUE TITLE
Allow to disable `gem update` reminded

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#6260]
Installing some gem, at the end, I am reminded to update RubyGems:

~~~
A new release of RubyGems is available: 3.4.1 → 3.4.3!
Run `gem update --system 3.4.3` to update your installation.
~~~

However, it is not nice to make such suggestion to distribution users, because e.g. Fedora users will get the installation via system updates. Suggesting `gem update` might even be harmful, because if nothing else, this is not tested on Fedora.

So is there chance:

1) To drop this, because I fail to see the utility of the banner.
2) Allow to disable this banner via configuration (e.g. via operating_sytem.rb). If that is already possible, then sorry for the noise and thx in advance for guidance.

**Comment by deivid-rodriguez** [comment]
Please have a look at the PR where this banner was introduced to see available options for disabling it. Thanks!

**Comment by simi** [comment]
> To drop this, because I fail to see the utility of the banner.

:trollface: 

---

@voxik please, if possible (I think I have recommended this already few times), implement `Gem.disable_system_update_message` in Fedora. You can inspire at https://salsa.debian.org/ruby-team/rubygems-integration/-/blob/master/lib/rubygems/defaults/operating_system.rb#L7-14. It will prevent this message as well.

**Comment by voxik** [comment]
Thanks for pointers
