### ISSUE TITLE
Platform locked Gemfile.lock not changed correctly by bundle install

### ISSUE THREAD

**Issue by owst** [rubygems/rubygems#6263]
### Describe the problem as clearly as you can

A Gemfile.lock that is locked to certain (versionless) platforms is updated in an unexpected way by `bundle install`. 

Given the following Gemfile.lock (that I think is malformed/incomplete - it's missing a load of GEM specs for other darwin versions, I'm not sure how this was arrived at, probably an older `bundler` version):
```
GEM
  remote: https://rubygems.org/
  specs:
    sorbet (0.5.10549)
      sorbet-static (= 0.5.10549)
    sorbet-static (0.5.10549-universal-darwin-20)
    sorbet-static (0.5.10549-x86_64-linux)

PLATFORMS
  arm64-darwin
  x86_64-darwin
  x86_64-linux

DEPENDENCIES
  sorbet (= 0.5.10549)

BUNDLED WITH
   2.4.3
```
and simple `Gemfile`:
```
source "https://rubygems.org"

gem "sorbet", "= 0.5.10549"
```
when on platform `x86_64-darwin-21`, running `bundle install` gives this diff:
```diff
diff --git a/Gemfile.lock b/Gemfile.lock
index ec8dea1..e2f125c 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -3,8 +3,7 @@ GEM
   specs:
     sorbet (0.5.10549)
       sorbet-static (= 0.5.10549)
-    sorbet-static (0.5.10549-universal-darwin-20)
-    sorbet-static (0.5.10549-x86_64-linux)
+    sorbet-static (0.5.10549-universal-darwin-21)
 
 PLATFORMS
   arm64-darwin
```
which is surprising - we've removed the Linux spec and swapped out darwin-20 for darwin-21 (the current platform).

If instead of `bundle install` we run `bundle update --conservative sorbet-static` (which should be a no-op due to our version pin) we end up with this diff:
```diff
diff --git a/Gemfile.lock b/Gemfile.lock
index ec8dea1..6da2848 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -3,7 +3,15 @@ GEM
   specs:
     sorbet (0.5.10549)
       sorbet-static (= 0.5.10549)
+    sorbet-static (0.5.10549-universal-darwin-14)
+    sorbet-static (0.5.10549-universal-darwin-15)
+    sorbet-static (0.5.10549-universal-darwin-16)
+    sorbet-static (0.5.10549-universal-darwin-17)
+    sorbet-static (0.5.10549-universal-darwin-18)
+    sorbet-static (0.5.10549-universal-darwin-19)
     sorbet-static (0.5.10549-universal-darwin-20)
+    sorbet-static (0.5.10549-universal-darwin-21)
+    sorbet-static (0.5.10549-universal-darwin-22)
     sorbet-static (0.5.10549-x86_64-linux)
 
 PLATFORMS
```
which looks correct to me (I think the "incomplete/wrong" existing specs have been corrected to add all darwin versions). I wonder why this is different to the behaviour of `bundle install`?

### Did you try upgrading rubygems & bundler?

Already on the latest version.

### Post steps to reproduce the problem

As above.

### Which command did you run?

`bundle install`

### What were you expecting to happen?

The `Gemfile.lock` changes to be the same as for the ("no-op") `bundle update` command.

### What actually happened?

The output was different/wrong.

### If not included with the output of your command, run `bundle env` and paste the output below

```
Bundler       2.4.3
  Platforms   ruby, x86_64-darwin-21
Ruby          2.7.6p219 (2022-04-12 revision c9c2245c0a25176072e02db9254f0e0c84c805cd) [x86_64-darwin-21]
RubyGems      3.4.3
```

**Comment by deivid-rodriguez** [comment]
Thanks for the report @owst. I will have a look.

**Comment by deivid-rodriguez** [comment]
#6266 should fix this!

**Comment by owst** [comment]
Great, thanks @deivid-rodriguez for the speedy response as always!

**Comment by owst** [comment]
Actually, @deivid-rodriguez I've just looked at the test in that PR:
```ruby
      expect(lockfile).to eq <<~L
        GEM
          remote: #{file_uri_for(gem_repo4)}/
          specs:
            sorbet-static (0.5.10549-universal-darwin-20)
            sorbet-static (0.5.10549-universal-darwin-21)
        PLATFORMS
          x86_64-darwin
```
should we expect that all versions of that gem are added to the lock file (so `darwin-22`, `darwin-19`, etc.)? I wonder if it's also worth including the `x86_64-linux` platform to ensure that different platforms are handled properly.

**Comment by deivid-rodriguez** [comment]
Yes, all versions matching any platforms included under PLATFORMS.

The bug ended up being related, not to the specific set of platforms locked under PLATFORMS, but to whether the gem was previously installed or not (you can verify this by running `gem uninstall sorbet sorbet-static` before running you repro `bundle install` command). If gems are not already installed before running `bundle install` then things work as expected and all platforms are added.

In an effort to write a minimal test case that reproduces the issue, I limit the locked platforms to a single one, and the matching versions to two, just to make sure both are added and the current platform does not just replace what's already in the lockfile.

**Comment by owst** [comment]
Aha yes, I'd missed the test setup limiting the versions - that all makes sense, thanks for the explanation! 👍 And just to confirm that uninstalling gems before `bundle install` does indeed make things work as expected
