### ISSUE TITLE
Platform specific dependencies

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#628]
On Fedora, it happens quite often, that we need different dependencies then other platform does. Typically, it makes no sense for us to ship platform specific code for some gems, or install gems such as backports, when we are running the most recent version of Ruby. This would allow to properly solve issues such as https://github.com/guard/listen/issues/83 without unnecessary disputes. Thanks.

**Comment by copiousfreetime** [comment]
Checking to see if there is any additional feedback on this, otherwise I will close it.

As a real world example of leveraging the platform to change the dependency, see [launchy](https://rubygems.org/gems/launchy) gem, which has a java platform gem, but there is is no code difference. The java platform is there because on java the `spoon` gem is necessary. 

In this case I could see a need for the ability in a gem specification to dictate different runtime dependencies based upon the platform. Platform specific dependencies would add some complexity to the resolver.

**Comment by voxik** [comment]
@copiousfreetime Actually you are right that this might be solution, i.e. to release specific version of gem for each of x86-mingw32, x86_64-linux, amd64-freebsd-10, etc platform. But the only difference is the dependency, so why to do that? I am not sure I can convince the authors of such gems to release so many versions, since that would be  maintenance burden.

**Comment by copiousfreetime** [comment]
@voxik very true, I put launchy in there to demonstrate an example solution with existing functionality. I agree, it is a maintenance burden releasing multiple `.gem` files for different platforms when the only difference is the dependency graph.

**Comment by copiousfreetime** [comment]
To be specific about this proposal:

## Problem

A gem `X` depends on functionality that is provided by gem `Y` on platform `1` and provided by gem `Z` on platform `2`. 

Currently the solution is for the author of gem `X` to release to gems, one for each platform with different dependencies. This causes a maintenance / release burden.

## Proposal

Add some sort of platform dependency to the gem specification that allows for a gem author to designate dependencies based upon `RUBY_PLATFORM`.

At the moment, this is open for discussion and pull requests.

**Comment by segiddins** [comment]
The tricky thing with this (as CocoaPods supports it) is that dependencies for _all_ platforms need to be resolved, and then the dependency graph pruned recursively for the current platform.

**Comment by deivid-rodriguez** [comment]
At the moment I'm not sure how we should support this, and releasing different platform specific variants with the proper dependencies seems to be working fine in general. So I'd rather work on improving the existing tooling for making this "multi gem release workflows" easier?

Also, maybe this could fall into the "optional dependencies" feature and doesn't need a separate feature?

**Comment by deivid-rodriguez** [comment]
I'll close this for now since releasing platform variants with the proper dependencies seems to be working fine for the gems falling into this situation. We can consider this situation as well though when/if there's movement around optional dependencies.
