### ISSUE TITLE
DNS-Error on system update

### ISSUE THREAD

**Issue by kaese77** [rubygems/rubygems#6286]
Hello,

trying to install and update on Ubuntu 18.04.

Is the SRV-Record lost or is this not working any more?

root@1df1faaaedf7:~# gem update --system 3.4.4 -V
GET https://api.rubygems.org/specs.4.8.gz
304 Not Modified
Updating rubygems-update
HEAD https://api.rubygems.org/api/v1/dependencies
200 OK
GET https://api.rubygems.org/api/v1/dependencies?gems=rubygems-update
200 OK
Getting SRV record failed: DNS result has no information for _rubygems._tcp.api.rubygems.org
ERROR:  While executing gem ... (ArgumentError)
    wrong number of arguments (given 1, expected 0)

root@1df1faaaedf7:~# gem --version
2.5.0

root@1df1faaaedf7:~# host -t srv _rubygems._tcp.api.rubygems.org ns2.dnsimple.com
Using domain server:
Name: ns2.dnsimple.com
Address: 2400:cb00:2049:1::a29f:1904#53
Aliases: 

Host _rubygems._tcp.api.rubygems.org not found: 3(NXDOMAIN)

**Comment by indirect** [comment]
RubyGems 2.5.0 was released on 03 Nov 2015. It is no longer supported. Feel free to install a newer package, or download the `rubygems-update` gem yourself and install it manually.

**Comment by kaese77** [comment]
Thank you very much.
