### ISSUE TITLE
Gem commands fail if Windows user have a white space when installed for all users.

### ISSUE THREAD

**Issue by HatsuMora** [rubygems/rubygems#6288]
### Describe the problem as clearly as you can
After upgrading from rubygems (gem) from 3.3.3 to 3.4.4 I could not install any gem or run several gem-related commands. 
For example `gem env`.

ERROR:  While executing gem ... (Gem::CommandLineError)
    Unknown environment option [Rincón] 

or `gem install rails`: 
ERROR:  While executing gem ... (URI::InvalidURIError)
    URI must be ascii only "Rinc\u00F3n".

I tried to investigate the issue myself and find out that there is value.split(" ")  on `C:\langs\Ruby32-x64\lib\ruby\3.2.0\rubygems\command.rb:79` that will split arguments by white space therefore my user name is being splitter and miss interpreted. This extra arg is set by `lib\ruby\3.2.0\rubygems\defaults\operating_system.rb:11`. Operating system is setting a default --install-dir and --bindir based on Gem.user_dir. 

As a workaround for myself, I added wrapped both paths on `'` in operating_system.rb and change the split to` @extra_args = value.split(/\s+(?=([^']*"[^']*')*[^']*$)/)` in command.rb (split by white spaces that are not between single quotes). 

### Did you try upgrading RubyGems?
Yes, I upgraded from 3.4.1 (affected) to 3.4.4(also affected).

### Post steps to reproduce the problem

1. Create a windows user that contains a white space on the user path.
2. Install [Ruby+Devkit 3.2.0-1 (x64)](https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-3.2.0-1/rubyinstaller-devkit-3.2.0-1-x64.exe) from Ruby Installer.
3. When asked, install for all users. (Requires elevation)
4. run `gem env` or `gem install rails`

### Which command did you run?

1.  `gem env` 
2.  `gem install rails`

### What were you expecting to happen?

1. Display the environment.
2. Install rails gem.

### What actually happened?
Commands did not run successfully.

### Run `gem env` and paste the output below
The command does not run.

**Comment by deivid-rodriguez** [comment]
Thanks for reporting this!

It seems recent changes at https://github.com/oneclick/rubyinstaller2/commits/master/resources/files/operating_system.rb made this issue surface.

> As a workaround for myself, I added wrapped both paths on ' in operating_system.rb and change the split to @extra_args = value.split(/\s+(?=([^']*"[^']*')*[^']*$)/) in command.rb (split by white spaces that are not between single quotes).

That seems like a way of fixing this, yeah! We could use `.shellsplit` instead but not sure if we can/should add a dependency on `shellwords` here, so maybe a patch like yours is good enough.

Can you open an issue at rubyinstaller2 referring this issue to see what they think?

**Comment by HatsuMora** [comment]
Hi Deivid, 

Thank you for your quick reply, I was so puzzled why I couldn't find operating_system.rb on this repo. 

I will open an issue on at the rubyinstaller2 to get their opinion.

**Comment by deivid-rodriguez** [comment]
Awesome, thanks for the notice!
