### ISSUE TITLE
You don't have write permissions for the /usr/local/bin directory.

### ISSUE THREAD

**Issue by albertonieto** [rubygems/rubygems#6290]
I am trying to execute `bundle install` and I get the error below. Before that, I had to run `sudo gem install bundler -n /usr/local/bin` to bypass the `You don't have write permissions for the /usr/local/bin directory.` error.

Here is the error template:

```
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Gem::FilePermissionError: You don't have write permissions for the /usr/local/bin directory.
  /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/installer.rb:489:in `generate_bin'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/rubygems_gem_installer.rb:32:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/source/rubygems.rb:200:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/installer/gem_installer.rb:54:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/installer/parallel_installer.rb:155:in `do_install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/installer/parallel_installer.rb:84:in `call'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/installer/parallel_installer.rb:67:in `call'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/installer.rb:244:in `install_in_parallel'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/installer.rb:201:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/installer.rb:89:in `block in run'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/process_lock.rb:12:in `block in lock'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/process_lock.rb:9:in `open'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/process_lock.rb:9:in `lock'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/installer.rb:71:in `run'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/installer.rb:23:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/cli/install.rb:62:in `run'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/cli.rb:260:in `block in install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/settings.rb:131:in `temporary'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/cli.rb:259:in `install'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/cli.rb:34:in `dispatch'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/cli.rb:28:in `start'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/exe/bundle:45:in `block in <top (required)>'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /Library/Ruby/Gems/2.6.0/gems/bundler-2.4.4/exe/bundle:33:in `<top (required)>'
  /usr/local/bin/bundle:23:in `load'
  /usr/local/bin/bundle:23:in `<main>'

```

## Environment

```
Bundler       2.4.4
  Platforms   ruby, arm64-darwin-22
Ruby          2.6.10p210 (2022-04-12 revision 67958) [arm64-darwin-22]
  Full Path   /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
  Config Dir  /Library/Ruby/Site
RubyGems      3.0.3.1
  Gem Home    /Library/Ruby/Gems/2.6.0
  Gem Path    /Users/c02fv0rnq6lr/.gem/ruby/2.6.0:/Library/Ruby/Gems/2.6.0:/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/gems/2.6.0
  User Home   /Users/c02fv0rnq6lr
  User Path   /Users/c02fv0rnq6lr/.gem/ruby/2.6.0
  Bin Dir     /usr/local/bin
OpenSSL       
  Compiled    LibreSSL 2.8.3
  Loaded      LibreSSL 2.8.3
  Cert File   /private/etc/ssl/cert.pem
  Cert Dir    /private/etc/ssl/certs
Tools         
  Git         2.39.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-01-16
Git SHA           e1c0b50e84
Released Version  true
```

## Gemfile

### Gemfile

```ruby
source 'https://rubygems.org'

gem "dotenv"
gem 'capistrano', '~> 3.16.0'
gem 'capistrano-wpcli', '~> 0.1.5'
gem 'capistrano-composer', '~> 0.0.6'
gem 'capistrano-scm-gitcopy', '~> 0.1.5'
gem 'capistrano-dotenv-tasks', '~> 0.1.5'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    airbrussh (1.4.0)
      sshkit (>= 1.6.1, != 1.7.0)
    capistrano (3.16.0)
      airbrussh (>= 1.0.0)
      i18n
      rake (>= 10.0.0)
      sshkit (>= 1.9.0)
    capistrano-composer (0.0.6)
      capistrano (>= 3.0.0.pre)
    capistrano-dotenv-tasks (0.1.5)
      capistrano (~> 3.0)
    capistrano-scm-gitcopy (0.1.5)
      capistrano (~> 3.0)
    capistrano-wpcli (0.1.5)
      capistrano (~> 3.6)
      sshkit (~> 1.11)
    concurrent-ruby (1.1.9)
    dotenv (2.7.6)
    i18n (1.8.11)
      concurrent-ruby (~> 1.0)
    net-scp (3.0.0)
      net-ssh (>= 2.6.5, < 7.0.0)
    net-ssh (6.1.0)
    rake (13.0.6)
    sshkit (1.21.2)
      net-scp (>= 1.1.2)
      net-ssh (>= 2.8.0)

PLATFORMS
  arm64-darwin-22
  universal-darwin-21
  x86_64-darwin-20

DEPENDENCIES
  capistrano (~> 3.16.0)
  capistrano-composer (~> 0.0.6)
  capistrano-dotenv-tasks (~> 0.1.5)
  capistrano-scm-gitcopy (~> 0.1.5)
  capistrano-wpcli (~> 0.1.5)
  dotenv

BUNDLED WITH
   2.3.4
```

--- TEMPLATE END ----------------------------------------------------------------
```

**Comment by deivid-rodriguez** [comment]
This is expected.

If you want Bundler to install to a restricted location, you'll need to either run Bundler with `sudo`, change the permissions of the location where Bundler wants to write to be writable by the user running Bundler, or change the location where Bundler wants to write to a location that the user running Bundler can write to (`bundle config path <writable_path>`).

Let me know if any of those work!

**Comment by rgaufman** [comment]
My bundle config path is blank and bundle tries to write to /usr/local/bin - how do I get it to write to the current directory by default as I would expect bundle --local install to write locally? - it always has before, I'm not sure why this suddenly started happening.

```
$ bundle config path
Settings for `path` in order of priority. The top value will be used
You have not configured a value for `path`
```

**Comment by AnkitC07** [comment]
i am having same issue here is error,
── external error ────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Error coming from `bundle install`

Command failed with exit code 1: bundle install
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Gem::FilePermissionError: You don't have write permissions for the /usr/local/bin directory.
  /usr/local/lib/site_ruby/3.0.0/rubygems/installer.rb:961:in `ensure_writable_dir'
  /usr/local/lib/site_ruby/3.0.0/rubygems/installer.rb:488:in `generate_bin'
  /var/lib/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/rubygems_gem_installer.rb:32:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/source/rubygems.rb:200:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/installer/gem_installer.rb:54:in `install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
  /var/lib/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/installer/parallel_installer.rb:156:in `do_install'
  /var/lib/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/installer/parallel_installer.rb:147:in `block in worker_pool'
  /var/lib/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/worker.rb:62:in `apply_func'
  /var/lib/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/worker.rb:57:in `block in process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/worker.rb:54:in `loop'
  /var/lib/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/worker.rb:54:in `process_queue'
  /var/lib/gems/3.0.0/gems/bundler-2.4.10/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

```

## Environment

```
Bundler       2.4.10
  Platforms   ruby, x86_64-linux-gnu
Ruby          3.0.2p107 (2021-07-07 revision 0db68f023372b634603c74fca94588b457be084c) [x86_64-linux-gnu]
  Full Path   /usr/bin/ruby3.0
  Config Dir  /etc
RubyGems      3.4.10
  Gem Home    /var/lib/gems/3.0.0
  Gem Path    /home/tis-34/.local/share/gem/ruby/3.0.0:/var/lib/gems/3.0.0:/usr/local/lib/ruby/gems/3.0.0:/usr/lib/ruby/gems/3.0.0:/usr/lib/x86_64-linux-gnu/ruby/gems/3.0.0:/usr/share/rubygems-integrat
ion/3.0.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/3.0.0
  User Home   /home/tis-34
  User Path   /home/tis-34/.local/share/gem/ruby/3.0.0
  Bin Dir     /usr/local/bin
OpenSSL
  Compiled    OpenSSL 3.0.2 15 Mar 2022
  Loaded      OpenSSL 3.0.2 15 Mar 2022
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools
  Git         2.34.1
  RVM         1.29.12 (manual)
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-03-27
Git SHA           7ffdec80d0
Released Version  true
```

## Gemfile

### Gemfile

```ruby
# NOTE: These are development-only dependencies
source "https://rubygems.org"

gem "bugsnag", "~> 6.22"
gem "listen", "~> 3.7.0"
gem "theme-check", "~> 1.14.0"

# None of these can actually be used in a development copy of dev
# They are all for CI and tests
# `dev` uses no gems
group :development, :test do
  gem "pry-byebug"
  gem "byebug"
  gem "rubocop-shopify", require: false
  gem "rubocop-minitest", require: false
  gem "rubocop-rake", require: false
  gem "iniparse", "~> 1.5"
  gem "colorize", "~> 0.8.1"
  gem "octokit", "~> 4.0"
  gem "bundler", ">= 2.3.11"
  gem "rake", "~> 12.3", ">= 12.3.3"
  gem "minitest", "~> 5.0"
end

group :test do
  gem "mocha", require: false
  gem "minitest-reporters", require: false
  gem "minitest-fail-fast", require: false
  gem "fakefs", ">= 1.0", require: false
  gem "webmock", require: false
  gem "timecop", require: false
  gem "rack", require: false
  gem "cucumber", "~> 7.0", require: false
end
```

### Gemfile.lock

```
<No /home/tis-34/Desktop/techAnkit/Erik/erik_custom_block/node_modules/@shopify/cli-kit/assets/cli-ruby/Gemfile.lock found>
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=You+don%27t+have+write+permissions+for+the+%2Fusr%2Flocal%2Fbin+directory.&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy
and paste the report template above in there.
Fetching gem metadata from https://rubygems.org/..........
Resolving dependencies...
Using rake 12.3.3
Using public_suffix 5.0.1
Using ansi 1.5.0
Using ast 2.4.2
Using concurrent-ruby 1.2.2
Using builder 3.2.4
Using bundler 2.4.10
Using colorize 0.8.1
Using ffi 1.15.5
Using cucumber-cucumber-expressions 14.0.0
Using rexml 3.2.5
Using cucumber-messages 17.1.1
Using cucumber-tag-expressions 4.1.0
Using mime-types-data 3.2023.0218.1
Using multi_test 0.1.2
Using fakefs 2.4.0
Using iniparse 1.5.0
Using json 2.6.3
Using liquid 5.4.0
Using faraday-net_http 3.0.2
Using ruby2_keywords 0.0.5
Using hashdiff 1.0.1
Using rb-fsevent 0.11.2
Using minitest 5.18.0
Using method_source 1.0.0
Using ruby-progressbar 1.13.0
Using racc 1.6.2
Using parallel 1.22.1
Using rainbow 3.1.1
Using regexp_parser 2.7.0
Using unicode-display_width 2.4.2
Using timecop 0.9.6
Using addressable 2.8.3
Using crack 0.4.5
Using sys-uname 1.2.2
Using rack 3.0.7
Using rb-inotify 0.10.1
Using mime-types 3.4.1
Using minitest-fail-fast 0.1.0
Fetching webmock 3.18.1
Using cucumber-create-meta 6.0.4
Using bugsnag 6.25.2
Using listen 3.7.1
Using mocha 2.0.2
Using faraday 2.7.4
Using minitest-reporters 1.6.0
Using nokogiri 1.14.2 (x86_64-linux)
Fetching sawyer 0.9.2
Installing cucumber-gherkin 22.0.0
Installing diff-lcs 1.5.0
Installing coderay 1.1.3
Installing byebug 11.1.3 with native extensions
Installing cucumber-html-formatter 17.0.0
Installing parser 3.2.2.0
Installing sawyer 0.9.2
Installing webmock 3.18.1

**Comment by FelipeJuarezJr** [comment]
" sudo /bin/ruby /usr/local/bin/bundle install --without production " worked for me, thanks!

**Comment by marlonjames71** [comment]
> " sudo /bin/ruby /usr/local/bin/bundle install --without production " worked for me, thanks!

What does "--without production" do?

**Comment by martinemde** [comment]
`--without production` would _not_ install any gems within a block starting with `group :production do`. I don't think it's a solution to this specific error, but it may have worked because it avoided installing whatever gem was missing.

The real solution here is like @deivid-rodriguez mentioned. Set a path or use sudo.

If you are not developing a ruby or rails app, but instead using a tool that asking you to run `bundle install`, then I suggest using `sudo bundle install` since this will just use your system ruby gems location.

If you don't want to do that, next I would suggest setting a path in your local dir to install gems. For instance `bundle config path vendor`, then make the `vendor` dir.

**Comment by marlonjames71** [comment]
Thanks, @martinemde. I was able to run `sudo bundle install`, but I'm running into issues when trying to run `sudo bundle exec fastlane add_plugin appcenter`. I'm getting issues when trying to install the appcenter plugin for Fastlane.

**Comment by martinemde** [comment]
It looks to be like fastlane just wants you to run `fastlane add_plugin appcenter` (I have never used it myself, but this makes sense from the perspective of how rubygems work.) You shouldn't need sudo at this point.

**Comment by Kawaljeet-AUI** [comment]
@marlonjames71 Did it work for you? Is yes, can you kindly share the workflow job that worked.

**Comment by marlonjames71** [comment]
@Kawaljeet-AUI I'm pretty sure I did what @martinemde suggested which was just running `fastlane add_plugin appcenter` and that's what worked.

**Comment by jamesnottidge** [comment]
thank you! @martinemde
