### ISSUE TITLE
Shopify CLI v3.x execution stalls on Bundler steps(Windows 10) 

### ISSUE THREAD

**Issue by gkrauthamer** [rubygems/rubygems#6313]
I am trying to follow the documentation and recommended tools and install process for the Shopify CLI on Windows at https://shopify.dev/themes/tools/cli/install

I am showing in my CMD prompt that I have:
Node: 18.12.1
NPM: 9.4.0
Ruby: 3.1.3p185
Bundler: 2.4.5
Shopify CLI: 3.37.0

Some of my Shopify CLI commands work as expected, but others such as `shopify theme dev` seem to stall without giving an error. Running in verbose mode, I see that all of the stalling occurs around "bundle exec" lines in the script, for example:

Command:

`shopify theme pull -d --verbose`

Result: Execution stalls at

```
2023-01-26T23:32:58.863Z:
Running system process:
  · Command: bundle exec shopify theme pull c:/xampp/htdocs/mydir --development
  · Working directory: c:\xampp\htdocs\mydir
 

```
and 

 

Command:

`shopify theme dev -t mytheme --verbose
` 

Result: Execution stalls on:

```
2023-01-26T23:36:28.378Z:
Running system process:
  · Command: bundle exec shopify theme serve . --theme mytheme --live-reload hot-reload
  · Working directory: c:\xampp\htdocs\mydir
```

Would there be a way to troubleshoot this issue and expose additional errors returned from Bundler?

**Comment by duckinator** [comment]
I don't see any documentation about a `shopify theme serve` command, so let's try to figure out the `shopify theme pull` command first.

In CMD, can you change to the `c:\xampp\htdocs\mydir` directory and try this command? (passes the `--verbose` flag to `shopify theme pull`)

```
bundle exec -- shopify theme pull c:/xampp/htdocs/mydir --development --verbose
```

As well as this one? (passes `--verbose` to `bundle exec`, but _not_ to `shopify theme pull`)

```
bundle exec --verbose -- shopify theme pull c:/xampp/htdocs/mydir --development
```

Hopefully one or both of those can help provide some insight.

**Comment by gkrauthamer** [comment]
Thanks for the help. I was able to resolve the issues after uninstalling/reinstalling Ruby for Windows, and setting up my Shopify theme in a new directory. It also appears that the install steps in the Getting Started section of https://bundler.io/ may not have been necessary and may have created some of the issues, as my newer installs have worked without these steps, and I see that "bundle install" is executed automatically by the Shopify theme scripts.
