### ISSUE TITLE
Bundler: Could not find compatible versions for standalone_migrations + rack combo

### ISSUE THREAD

**Issue by radar** [rubygems/rubygems#6328]
### Describe the problem as clearly as you can

Gemfile of:

```
# frozen_string_literal: true

source "https://rubygems.org"

gem "rack", "~> 3.0"
gem "standalone_migrations"
```

Running:

```
bundle install
```

Shows:

```
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Could not find compatible versions

Because standalone_migrations >= 0 depends on itself
  and Gemfile depends on standalone_migrations >= 0,
  version solving has failed.
```

### Did you try upgrading rubygems & bundler?

RubyGems: 3.3.16
Bundler: 2.4.6

### Post steps to reproduce the problem

As above.

### Which command did you run?

As above.

### What were you expecting to happen?

Installation to find latest versions of strong_migrations + Rails gems that fufil the criteria.

### What actually happened?

```
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Could not find compatible versions

Because standalone_migrations >= 0 depends on itself
  and Gemfile depends on standalone_migrations >= 0,
  version solving has failed.
```

## Environment

```
Bundler       2.4.6
  Platforms   ruby, arm64-darwin-21
Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [arm64-darwin-21]
  Full Path   /Users/ryan.bigg/.asdf/installs/ruby/3.1.2/bin/ruby
  Config Dir  /Users/ryan.bigg/.asdf/installs/ruby/3.1.2/etc
RubyGems      3.3.16
  Gem Home    /Users/ryan.bigg/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0
  Gem Path    /Users/ryan.bigg/.gem/ruby/3.1.0:/Users/ryan.bigg/.asdf/installs/ruby/3.1.2/lib/ruby/gems/3.1.0
  User Home   /Users/ryan.bigg
  User Path   /Users/ryan.bigg/.gem/ruby/3.1.0
  Bin Dir     /Users/ryan.bigg/.asdf/installs/ruby/3.1.2/bin
Tools         
  Git         2.37.1 (Apple Git-137.1)
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-01-31
Git SHA           598c04d54a
Released Version  true
```

## Bundler settings

```
gem.changelog
  Set for the current user (/Users/ryan.bigg/.bundle/config): false
gem.ci
  Set for the current user (/Users/ryan.bigg/.bundle/config): false
gem.coc
  Set for the current user (/Users/ryan.bigg/.bundle/config): false
gem.linter
  Set for the current user (/Users/ryan.bigg/.bundle/config): false
gem.mit
  Set for the current user (/Users/ryan.bigg/.bundle/config): false
gem.test
  Set for the current user (/Users/ryan.bigg/.bundle/config): false
local.fat_zebra_models
  Set for the current user (/Users/ryan.bigg/.bundle/config): "/Users/ryan.bigg/code/fz/fat-zebra-models"
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

gem "rack", "~> 3.0"
gem "standalone_migrations"
```

### Gemfile.lock

```
<No /Users/ryan.bigg/code/playground/bundler-24/Gemfile.lock found>
```

**Comment by skipkayhil** [comment]
Just to make sure, are you trying to use `strong_migrations` or `standalone_migrations`? It looks like you reference both in the issue

> Installation to find latest versions of strong_migrations + Rails gems that fufil the criteria.

There isn't a released version of Rails that supports Rack 3, so I think Bundler being unable to resolve this is expected

**Comment by radar** [comment]
Sorry, as per the Gemfile, it's `standalone_migrations`.

**Comment by simi** [comment]
The message seems confusing, but isn't the problem that `standalone_migrations` depends on `railties` and that depends on `actionpack` and there is no `rack ~> 3.0` compatible release yet?

I got some info using `DEBUG_RESOLVER=1 bundle`.

**Comment by deivid-rodriguez** [comment]
[Standalone migrations 2.0.4](https://rubygems.org/gems/standalone_migrations/versions/2.0.4) depends on itself, and that's making the resolver print this (definitely unhelpful) message. But if I revert a8348d271dd38e00437d5ab8200d4883928f2c21, we get a runtime crash which seems worse.

**Comment by deivid-rodriguez** [comment]
I wrote [a patch](https://github.com/rubygems/rubygems/pull/6330) with an alternative approach to deal with "self-referencing versions": ignore them. With that patch, this resolution succeeds by going all the way back to [standalone_migrations 1.0.13 from 2012](https://rubygems.org/gems/standalone_migrations/versions/1.0.13). Most likely not what you want, but a correct resolution after all.

**Comment by deivid-rodriguez** [comment]
Technically, even if 2.0.4 depends on itself, the dependency is still satisfiable, so I tweaked the approach in #6330 and now it will resolve to [standalone_migrations-2.0.4](https://rubygems.org/gems/standalone_migrations/versions/2.0.4) (a bit more modern but still probably not what you expected, you probably want to pin to rack 2, or wait for rack 3 support in Rails).
