### ISSUE TITLE
Random test failures on Ruby 3.2 + Windows

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#6332]
### Describe the problem as clearly as you can

We've been getting fairly frequent test failures on Ruby 3.2 + Windows.

For example: https://github.com/rubygems/rubygems/actions/runs/4062873677/jobs/6994436213. Copying logs here:

```
1) [TEST_ENV_NUMBER=1] bundle update with --force shows a deprecation when single flag passed
    Failure/Error:
              raise <<~ERROR
      
                Invoking `#{cmd}` failed with output:
                ----------------------------------------------------------------------
                #{command_execution.stdboth}
                ----------------------------------------------------------------------
              ERROR

    RuntimeError:

      Invoking `C:/hostedtoolcache/windows/Ruby/3.2.0/x64/bin/ruby.exe -ID:/a/rubygems/rubygems/bundler/spec -rD:/a/rubygems/rubygems/bundler/spec/support/artifice/fail.rb -rD:/a/rubygems/rubygems/bundler/spec/support/hax.rb D:/a/rubygems/rubygems/bundler/tmp/1/gems/system/bin/bundle install` failed with output:
      ----------------------------------------------------------------------
      --- ERROR REPORT TEMPLATE -------------------------------------------------------

      ```
      Errno::ENOENT: No such file or directory @ dir_s_mkdir - D:/a/rubygems/rubygems/bundler/tmp/1/home/AppData/Local/Microsoft/WindowsApps
        D:/a/rubygems/rubygems/lib/rubygems/installer.rb:956:in `mkdir'
        D:/a/rubygems/rubygems/lib/rubygems/installer.rb:956:in `ensure_writable_dir'
        D:/a/rubygems/rubygems/lib/rubygems/installer.rb:488:in `generate_bin'
        D:/a/rubygems/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.5.0.dev/lib/bundler/rubygems_gem_installer.rb:32:in `install'
        D:/a/rubygems/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.5.0.dev/lib/bundler/source/rubygems.rb:200:in `install'
        D:/a/rubygems/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.5.0.dev/lib/bundler/installer/gem_installer.rb:54:in `install'
        D:/a/rubygems/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.5.0.dev/lib/bundler/installer/gem_installer.rb:16:in `install_from_spec'
        D:/a/rubygems/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.5.0.dev/lib/bundler/installer/parallel_installer.rb:155:in `do_install'
        D:/a/rubygems/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.5.0.dev/lib/bundler/installer/parallel_installer.rb:146:in `block in worker_pool'
        D:/a/rubygems/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.5.0.dev/lib/bundler/worker.rb:62:in `apply_func'
        D:/a/rubygems/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.5.0.dev/lib/bundler/worker.rb:57:in `block in process_queue'
        D:/a/rubygems/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.5.0.dev/lib/bundler/worker.rb:54:in `loop'
        D:/a/rubygems/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.5.0.dev/lib/bundler/worker.rb:54:in `process_queue'
        D:/a/rubygems/rubygems/bundler/tmp/1/gems/system/gems/bundler-2.5.0.dev/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'

      ```

      ## Environment

      ```
      Bundler       2.5.0.dev
        Platforms   ruby, x64-mingw-ucrt
      Ruby          3.2.0p0 (2022-12-25 revision a528908271c678360d2d8ca232c178e7cdd340b4) [x64-mingw-ucrt]
        Full Path   C:/hostedtoolcache/windows/Ruby/3.2.0/x64/bin/ruby.exe
        Config Dir  C:/ProgramData
      RubyGems      3.5.0.dev
        Gem Home    D:/a/rubygems/rubygems/bundler/tmp/1/home/.local/share/gem/ruby/3.2.0
        Gem Path    D:/a/rubygems/rubygems/bundler/tmp/1/gems/system;D:/a/rubygems/rubygems/bundler/tmp/1/home/.local/share/gem/ruby/3.2.0
        User Home   D:/a/rubygems/rubygems/bundler/tmp/1/home
        User Path   D:/a/rubygems/rubygems/bundler/tmp/1/home/.local/share/gem/ruby/3.2.0
        Bin Dir     D:/a/rubygems/rubygems/bundler/tmp/1/home/.local/share/gem/ruby/3.2.0/bin
      OpenSSL       
        Compiled    OpenSSL 3.0.7 1 Nov 2022
        Loaded      OpenSSL 3.0.7 1 Nov 2022
        Cert File   C:/hostedtoolcache/windows/Ruby/3.2.0/x64/ssl/cert.pem
        Cert Dir    C:/hostedtoolcache/windows/Ruby/3.2.0/x64/ssl/certs
      Tools         
        Git         2.39.1.windows.1
        RVM         not installed
        rbenv       not installed
        chruby      not installed
      ```

      ## Bundler Build Metadata

      ```
      Built At          2023-02-01
      Git SHA           ae9ec38
      Released Version  true
      ```

      ## Bundler settings

      ```
      system_bindir
        Set via BUNDLE_SYSTEM_BINDIR: "D:/a/rubygems/rubygems/bundler/tmp/1/home/AppData/Local/Microsoft/WindowsApps"
      ```

      ## Gemfile

      ### Gemfile

      ```ruby
      source "file:///D:/a/rubygems/rubygems/bundler/tmp/1/gems/remote1"
      gem "rack"
      ```

      ### Gemfile.lock

      ```
      <No D:/a/rubygems/rubygems/bundler/tmp/1/bundled_app/Gemfile.lock found>
      ```

      --- TEMPLATE END ----------------------------------------------------------------

      Unfortunately, an unexpected error occurred, and Bundler cannot continue.

      First, try this link to see if there are any existing issue reports for this error:
      https://github.com/rubygems/rubygems/search?q=No+such+file+or+directory+%40+dir_s_mkdir+-+D+%2Fa%2Frubygems%2Frubygems%2Fbundler%2Ftmp%2F1%2Fhome%2FAppData%2FLocal%2FMicrosoft%2FWindowsApps&type=Issues

      If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
      Fetching source index from file:///D:/a/rubygems/rubygems/bundler/tmp/1/gems/remote1/
      Resolving dependencies...
      Using bundler 2.5.0.dev
      Fetching rack 1.0.0
      Installing rack 1.0.0
      ----------------------------------------------------------------------
    # ./spec/support/helpers.rb:202:in `sys_exec'
    # ./spec/support/helpers.rb:121:in `bundle'
    # ./spec/support/helpers.rb:272:in `install_gemfile'
    # ./spec/update/redownload_spec.rb:5:in `block (2 levels) in <top (required)>'
    # ./spec/spec_helper.rb:102:in `block (4 levels) in <top (required)>'
    # ./spec/spec_helper.rb:102:in `block (3 levels) in <top (required)>'
    # ./spec/support/helpers.rb:345:in `block in with_gem_path_as'
    # ./spec/support/helpers.rb:359:in `without_env_side_effects'
    # ./spec/support/helpers.rb:340:in `with_gem_path_as'
    # ./spec/spec_helper.rb:101:in `block (2 levels) in <top (required)>'
    # ./spec/support/rubygems_ext.rb:103:in `load'
    # ./spec/support/rubygems_ext.rb:103:in `gem_load_and_activate'
    # ./spec/support/rubygems_ext.rb:18:in `gem_load'
```

Since they are specific to Ruby 3.2 + Windows, and looking at the `BUNDLE_SYSTEM_BINDIR` setting and the name of the directory failing to be created, they seem related to upstream changes in RubyInstaller2, like https://github.com/oneclick/rubyinstaller2/commit/388f7d1a509cc9538e61fbf151aa741db697c17b.

I suspect changing the failing `Dir.mkdir` to `FileUtils.mkdir_p` would fix the problem, and that this is just that we don't support setting bindir to a deeply nested folder where several intermediate directories don't already exist. But not sure why it only fails sometimes.

Summoning @larskanis, just in case you have any ideas or this could signal some issue in RubyInstaller2.
 
### Did you try upgrading rubygems & bundler?

Yes, it's our own CI.

### Post steps to reproduce the problem

Not reproducible (so far)

### Which command did you run?

It seems mostly random, not sure.

### What were you expecting to happen?

No crash.

### What actually happened?

Crash like above.

**Comment by larskanis** [comment]
I don't have a good idea why this issue happens sometimes and sometimes not. Nevertheless I changed the code in rubyinstaller to set `BUNDLE_SYSTEM_BINDIR` only if the directory is present. This should prevent issues with the failing test case where a dummy home directory like `D:/a/rubygems/rubygems/bundler/tmp/1/home` is used without a subdirectory `AppData/Local/Microsoft/WindowsApps`, which a normal Windows user home should have.

The commit is https://github.com/oneclick/rubyinstaller2/commit/7a900268d1631d4004e660aa4a658bd575f480b6 . It will be in RubyInstaller-3.2.1-1.

**Comment by deivid-rodriguez** [comment]
Thank you!
