### ISSUE TITLE
Could not find gem 'rubocop

### ISSUE THREAD

**Issue by drjeon92** [rubygems/rubygems#6340]
in docker

Could not find gem 'rubocop (~> 1.44.0)' with platform 'x86_64-linux' in locally installed gems.

The source contains the following gems matching 'rubocop (~> 1.44.0)':
  * rubocop-1.44.0
  * rubocop-1.44.1

When I install the bundle, the above message appears.
I installed 1.44.1 as per the error message, but the message continues to appear. What should I do?

environment
ruby 3.1.3p185 (2022-11-24 revision 1a6b16756e) [x86_64-linux]

**Comment by deivid-rodriguez** [comment]
Hello @drjeon92! Thanks for the report, but we need more information to be able to help you. Could you fill-in a new issue answering all the questions in the bug report template? Thanks a lot!
