### ISSUE TITLE
Uninstalling multiple gems with versions

### ISSUE THREAD

**Issue by hurricup** [rubygems/rubygems#6345]
At the moment, `gem help uninstall` shows that we can uninstall multiple gems by specifying additional names. 
```
Usage: gem uninstall GEMNAME [GEMNAME ...] [options]
```
But, we may have multiple gems with multiple versions and the only way I see to specify the version is to use an option `-v` which is unclear how to use with multiple gems.

Would be nice to be able to make bulk uninstallation with something like:
```
gem uninstall gem1@verstion1 gem2@version2 ....
```

This could be mostly useful for CI and other automated things with complex environments.

**Comment by composerinteralia** [comment]
It looks like this feature might already exist, but with `:` as the separator rather than `@`.

See the end of this error message, for example:

```sh
$ gem uninstall a b --version 1
ERROR:  Can't use --version with multiple gems. You can specify multiple gems with version requirements using `gem uninstall 'my_gem:1.0.0' 'my_other_gem:~>2.0.0'`
```

**Comment by hurricup** [comment]
Oh my, thank you!!! Would be nice to add this to the `gem help uninstall`.

**Comment by hurricup** [comment]
Installing works as well :D neat!

**Comment by deivid-rodriguez** [comment]
Closing, since feature is already there! Thanks @composerinteralia for noticing it!

**Comment by deivid-rodriguez** [comment]
@hurricup Can you send us a PR to mention this on `gem uninstall` help?

**Comment by hurricup** [comment]
@deivid-rodriguez I wouldn't trust my English :)

**Comment by simi** [comment]
> @deivid-rodriguez I wouldn't trust my English :)

There is no need to be afraid to open initial PR. :pray: We can tweak the text all together in there.

**Comment by hurricup** [comment]
Is this `gem_name:gem_version` fromat supported for every command? 

![image](https://user-images.githubusercontent.com/2811330/222721160-0cb3f598-7fac-41e0-bcd6-26d4d0bbcc7a.png)

**Comment by deivid-rodriguez** [comment]
I'm not sure, I think at least `gem fetch`, `gem install`, and `gem uninstall` support it.

**Comment by hurricup** [comment]
This probably need to be reopened. 
Specification works fine, installation as well, but uninstallation can't handle several versions of the same gem.

## Installing
```
$ gem install simplecov:0.19.0 simplecov:0.22.0
Fetching simplecov-0.19.0.gem
Successfully installed simplecov-0.19.0
Parsing documentation for simplecov-0.19.0
Installing ri documentation for simplecov-0.19.0
Done installing documentation for simplecov after 0 seconds
Fetching simplecov-0.22.0.gem
Successfully installed simplecov-0.22.0
Parsing documentation for simplecov-0.22.0
Installing ri documentation for simplecov-0.22.0
Done installing documentation for simplecov after 0 seconds
2 gems installed
```

## Uninstalling after
```
~$ gem uninstall simplecov:0.19.0 simplecov:0.22.0
Successfully uninstalled simplecov-0.22.0
~$ gem uninstall simplecov:0.19.0 simplecov:0.22.0
Gem 'simplecov' is not installed
Successfully uninstalled simplecov-0.19.0
```

Looks like it is uniqued by name at some point
