### ISSUE TITLE
Expand SafeMarshal to cover all loading of marshaled data in RubyGems and Bundler

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems#6353]
In https://github.com/rubygems/rubygems/pull/6141, we landed a `SafeMarshal` class to deserialize data returned from the dependency API. Let's expand use of `SafeMarshal` to include every place in RubyGems and Bundler where we load marshaled files, to remove the possibility of an attack by a malicious server.

**Comment by simi** [comment]
@arletterocks are you interested in implementing this?

**Comment by arletterocks** [comment]
@simi Yeah, thank you — @indirect suggested it as something I could pick up!

**Comment by simi** [comment]
Cool, feel free to ping me if any help would be needed.

**Comment by indirect** [comment]
Done in #6384.
