### ISSUE TITLE
gem should not try HTTPS if non-HTTPS has been requested via "gem install --source".

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems#6367]
### Describe the problem as clearly as you can

Right now I can not download .gem files. My openssl is somehow messed up. Solving this
is not trivial.

While googling I found this example to try:

    gem install libui --source http://rubygems.org

This failed. But here is what is interesting:

    ERROR:  Could not find a valid gem 'libui' (>= 0), here is why:
     Unable to download data from https://rubygems.org/ - Net::OpenTimeout: Failed to open TCP connection to rubygems.org:443 (execution expired) (https://rubygems.org/specs.4.8.gz)
     Unable to download data from http://rubygems.org/ - Net::OpenTimeout: Failed to open TCP connection to rubygems.org:80 (execution expired) (http://rubygems.org/specs.4.8.gz)

I am using latest ruby and rubygems right now.

    ruby 3.2.1 (2023-02-08 revision 31819e82c8) [x86_64-linux]
    gem version: 3.4.6

What I find strange is that https://rubygems.org is tried. So I get almost the same error message but
twice. The variant where http:// is tried is correct. I specified this. But why is the https variant also
tried? I didn't request that on the command, and it would fail anyway, so why is gem doing this?

I think the variant of trying https://rubygems.org should not happen if we specify via
-source + URL here a non-HTTPS source specifically.

**Comment by indirect** [comment]
This is not a bug. The servers at rubygems.org no longer provide access over HTTP. If you attempt to reach them via HTTP, they will simply return a redirect to HTTPS. What you are seeing is the client respecting the redirect sent by the server, and trying to use HTTPS.
