### ISSUE TITLE
Possible issue with default gems?

### ISSUE THREAD

**Issue by zzak** [rubygems/rubygems#6386]
I'm not sure exactly the issue here, so apologies if this report is somewhat vague.

I discovered the Rails CI was failing due to this message (which occurred _after_ timeout 0.3.2 was released), I believe:

```
You have already activated timeout 0.3.1, but your Gemfile requires timeout 0.3.2. Since timeout is a default gem, you can either remove your dependency on it or try updating to a newer version of bundler that supports timeout as a default gem.
```

You can see the failing build here:
https://buildkite.com/rails/rails/builds/93873#018657ce-2c40-4dcb-8f38-dd1dd0af6279

And the PR that fixes it: rails/rails#47411

**Comment by hsbt** [comment]
It's activated at following locations:

```
lib/rubygems/command_manager.rb:    require "timeout"
bundler/lib/bundler/vendor/connection_pool/lib/connection_pool.rb:require "timeout"
```

**Comment by yahonda** [comment]
This issue is already known, and these pull requests should address it.
https://github.com/rubygems/rubygems/pull/5529
https://github.com/rubygems/rubygems/pull/5535
