### ISSUE TITLE
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

### ISSUE THREAD

**Issue by MuIbrahim23** [rubygems/rubygems#6401]
### Which command did you run?

bundle install

### What actually happened?

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

**Comment by simi** [comment]
@MuIbrahim23 can you provide more info? There should be error template printed out you can just copy in here.

**Comment by MuIbrahim23** [comment]
Permission denied @ dir_s_mkdir - /usr/local/lib/ruby/gems/2.7.0/extensions/x86_64-darwin-20/2.7.0/json-2.6.2

**Comment by simi** [comment]
@MuIbrahim23 it seems you're installing gems using system installed Ruby. Have you tried `sudo bundle install` to get system directories permissions to store extracted gems?

**Comment by MuIbrahim23** [comment]
Thank you very much. It is working now
