### ISSUE TITLE
github registry - please re-open

### ISSUE THREAD

**Issue by dsisnero** [rubygems/rubygems#6406]
### Unexpected source requirement when using github registry.
[github registry docs](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-rubygems-registry)
The docs say to type this:
`bundle config https://rubygems.pkg.github.com/NAMESPACE USERNAME:TOKEN`

when I do that I expect to have the following in gemfile to get it to work

  ```
 gem 'gemname_at_rubygems'
   source 'https://rubygems.pkg.github.com/NAMESPACE' do
     gem 'gemname'
     gem 'gemname2'
   end
```

What I had to do:

  ```
 gem 'gemname_at_rubygemsi'
   source 'https://USERNAME:TOKEN@rubygems.pkg.github.com/NAMESPACE' do
     gem 'gemname'
     gem 'gemname2'
   end

```

when 

### Did you try upgrading rubygems & bundler?
yes

### Post steps to reproduce the problem
add a personal access token

**Comment by duckinator** [comment]
@dsisnero can you please provide the output of `bundle env`? It includes information that greatly assists with reproducing problems like this.

**Comment by dsisnero** [comment]
[bundle env](https://gist.github.com/dsisnero/c18672c0eb9d03bbb4bcebfe2caf0abe)

**Comment by deivid-rodriguez** [comment]
@dsisnero I think this may be a Windows specific problem due to double slash escaping, because I just tried the instructions outside of Windows and they worked just fine. Can you copy the contents of `f:\windows_home\.config\bundle\config` (token redacted, of course).

**Comment by dsisnero** [comment]
---
BUNDLE_BUILD__NOKOGIRI: "--use-system-libraries"
BUNDLE_RUBYGEMS__PKG__GITHUB__COM: "dsisnero:TOKEN"
BUNDLE_GEM__TEST: "minitest"
BUNDLE_GEM__CI: "github"
BUNDLE_GEM__MIT: "true"
BUNDLE_GEM__COC: "true"
BUNDLE_GEM__CHANGELOG: "true"
BUNDLE_GEM__LINTER: "standard"
BUNDLE_HTTPS://RUBYGEMS__PKG__GITHUB__COM/DSISNERO/: "dsisnero:TOKEN"

**Comment by deivid-rodriguez** [comment]
Ok. Also, which shell are you using? Can you try in powershell to see if it's something shell-specific? And more importantly, can you copy the error you're getting?

**Comment by deivid-rodriguez** [comment]
Also, what happens if you remove the last line from the configuration file, does it still not work?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.

**Comment by dsisnero** [comment]
I am using cmd shell.  Still not working.  Please re-open.  The last line of f:\windows_home\.config\bundle\config is the one with the token.

**Comment by deivid-rodriguez** [comment]
> The last line of f:\windows_home.config\bundle\config is the one with the token.

Yep, but there's also another one with the TOKEN a few lines above too and that one should not create any "slash issues".

**Comment by deivid-rodriguez** [comment]
Also, can you answer the other questions I asked above, please?

> Can you try in powershell to see if it's something shell-specific? And more importantly, can you copy the error you're getting?

**Comment by dsisnero** [comment]
f:\windows\work\projects\nexcom\dominic\TVY_RTR\transmittal>powershell
Windows PowerShell
Copyright (C) Microsoft Corporation. All rights reserved.

Try the new cross-platform PowerShell https://aka.ms/pscore6

PS F:\windows\work\projects\nexcom\dominic\TVY_RTR\transmittal> rake -T
rake aborted!
Bundler::Fetcher::AuthenticationRequiredError: Authentication is required for rubygems.pkg.github.com.
Please supply credentials for this source. You can do this by running:
`bundle config set --global rubygems.pkg.github.com username:password`
or by storing the credentials in the `BUNDLE_RUBYGEMS__PKG__GITHUB__COM` environment variable
F:/windows/work/projects/nexcom/dominic/TVY_RTR/transmittal/Rakefile:4:in `<top (required)>'
(See full trace by running task with --trace)
PS F:\windows\work\projects\nexcom\dominic\TVY_RTR\transmittal>

**Comment by dsisnero** [comment]
PS F:\windows\work\projects\nexcom\dominic\TVY_RTR\transmittal> cat Rakefile
# -*- ruby -*-
require 'bundler/inline'

 gemfile do
   source 'https://rubygems.org'
   gem 'acrobat', '~>0.1'
   gem 'asciidoctor-pdf', path: './vendor/asciidoctor-pdf-2.0.0.dev'
   gem 'debug'
   gem 'hexapdf'
   gem 'matrix'
   gem 'microstation'
   gem 'prawn-svg', '~> 0.32'
   gem 'pry'
   gem 'pry-byebug'
   gem 'psych', '~> 4.0'
   gem 'rake'
   gem 'win32api'
   source 'https://rubygems.pkg.github.com/dsisnero' do
     gem 'faa-asciidoctor-extension'
     gem 'faa-cost_estimate'
     gem 'nexcom-srf'
   end
 end
require 'rake/clean'
require 'pathname'
require 'tempfile'
require "rubygems"
require 'pry'
require 'pry-byebug'
require 'faa/asciidoctor/extension'
require 'asciidoctor'
require 'asciidoctor-pdf'
require 'acrobat'
require 'faa/cost_estimate'
......................................... more stuff

**Comment by dsisnero** [comment]
deleted last line in bundle config file - got same error

BUNDLE_BUILD__NOKOGIRI: "--use-system-libraries"
BUNDLE_RUBYGEMS__PKG__GITHUB__COM: "dsisnero:TOKEN"
BUNDLE_GEM__TEST: "minitest"
BUNDLE_GEM__CI: "github"
BUNDLE_GEM__MIT: "true"
BUNDLE_GEM__COC: "true"
BUNDLE_GEM__CHANGELOG: "true"
BUNDLE_GEM__LINTER: "standard"

**Comment by deivid-rodriguez** [comment]
Right, the fact that you using a "inline gemfile" instead of a standard Gemfile could be related I guess. Does it work if you move the contents of the `gemfile do; ...; end` block to a separate `Gemfile` file, and run `bundle install` on it?

**Comment by huix11** [comment]
ok👍

**Comment by deivid-rodriguez** [comment]
Sorry I never got time to look into this. Is it still an issue for you?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
