### ISSUE TITLE
Gem.state_home memoizes using @data_home

### ISSUE THREAD

**Issue by nevans** [rubygems/rubygems#6418]
### Describe the problem as clearly as you can

While debugging an unrelated configuration issue of my own, I noticed the following:

https://github.com/rubygems/rubygems/blob/0f3d7db4580d839ec7f142adc0d5e0a681eee0a1/lib/rubygems/defaults.rb#L160-L162

It seems to me that `@data_home` here *must* be a mistake, right?  And, looking at the commit that created that method (0fbc4ace8a) and at the tests:
https://github.com/rubygems/rubygems/blob/0f3d7db4580d839ec7f142adc0d5e0a681eee0a1/test/rubygems/helper.rb#L366
both seem to confirm that `@state_home` was intended.

### Did you try upgrading RubyGems?

This is visible on the current `master` branch.

### Post steps to reproduce the problem

I attempted to use a codespace so I could submit a new failing test along with simply changing `@data_home` to `@state_home`.  After `rake setup`, `rake test` gave a number of unrelated errors.  This may be an incompatibility issue in my dotfiles.  Unfortunately, I don't have time to dive deeper into why that wasn't working right now, so I gave up on that for today.  Sorry about that... I'll try to figure out my issue before I submit any PRs, but I'm hoping this might be a simple fix for someone who already has a working dev env.

### What were you expecting to happen?

`def state_home = @state_home ||= (xdg_state_env || xdg_state_default)`

### What actually happened?

`def state_home = @data_home ||= (xdg_state_env || xdg_state_default)`

**Comment by simi** [comment]
Yup, that's mistake. And what's even worse, it is my mistake at https://github.com/rubygems/rubygems/commit/0fbc4ace8a664649e76bf616895a41a86e0710f8. I'll open PR. Thanks for the info.

**Comment by nevans** [comment]
I had an almost identical XDG_DATA vs XDG_CACHE copy/paste bug in one of my config files (IIRC: bashrc or vimrc or maybe both) for months before I discovered it, and cache vs data is even worse than state vs data.  So you'll receive no judgement from me! 😉

**Comment by simi** [comment]
feel free to review @nevans https://github.com/rubygems/rubygems/pull/6420 :pray:
