### ISSUE TITLE
`bundle remove` fails due to Gemfile syntax?

### ISSUE THREAD

**Issue by andyw8** [rubygems/rubygems#6424]
### Describe the problem as clearly as you can

If you specify a gem with parentheses and `require: false`, then `bundle remove` fails to remove that gem.

### Did you try upgrading rubygems & bundler?

Yes:

```
% ruby -v
ruby 3.1.1p18 (2022-02-18 revision 53f5fc4236) [arm64-darwin21]
% gem --version
3.4.7
% bundle --version
Bundler version 2.4.7
```

### Post steps to reproduce the problem

Create the following Gemfile:
```
source "https://rubygems.org"

gem("a", require: false)
gem "b", require: false
gem "c"
```

and run `bundle remove a b c`

It results in:

```
a could not be removed.
b was removed.
c was removed.
```

**Comment by deivid-rodriguez** [comment]
Thanks for reporting! Yeah, not surprised this fails, as far as I recall `bundle remove` uses simple regexps to remove the gem, and that style is quite uncommon, so was probably not considered.

**Comment by andyw8** [comment]
Thanks for quick response.

([this](https://github.com/Shopify/tapioca/blob/main/Gemfile) was the Gemfile I encountered it on).

**Comment by paracycle** [comment]
> as far as I recall `bundle remove` uses simple regexps to remove the gem, and that style is quite uncommon, so was probably not considered.

Would you be open to a PR making that implementation more robust?

**Comment by deivid-rodriguez** [comment]
Absolutely!

**Comment by jeromedalbert** [comment]
I opened a PR for a possible fix: https://github.com/rubygems/rubygems/issues/6424
