### ISSUE TITLE
bundler 2.4.0 and later, on truffleruby, when using `gemspec`, misses gems

### ISSUE THREAD

**Issue by flavorjones** [rubygems/rubygems#6435]
### Describe the problem as clearly as you can

When the following conditions apply:
- my `Gemfile` uses `gemspec` to declare dependencies
- using TruffleRuby
- using Bundler 2.4.0 or later

then it generates an invalid resolution that is missing gems.

This doesn't appear to happen with non-truffleruby rubies, or with older versions of bundler (`< 2.4.0`), or if the exact same dependency is declared in the `Gemfile` (and not in the gemspec).

### Did you try upgrading rubygems & bundler?

This happens with the latest bundler version (2.4.7) and the latest rubygems version (3.4.7).

### Post steps to reproduce the problem

```ruby
# Gemfile
source "https://rubygems.org"
gemspec
```

```ruby
# foo.gemspec

Gem::Specification.new do |spec|
  spec.name = "foo"
  spec.version = "1.0.0"
  spec.homepage = "https://example.com/"
  spec.summary = "foo"
  spec.description = "foo"
  spec.authors = "foo"
  spec.license = "foo"

  spec.add_runtime_dependency("nokogiri", "~> 1.14.0")
end
```

Ruby, `truffleruby-dev` installed via ruby-build:
- `truffleruby 23.0.0-dev-671182fb, like ruby 3.1.3, GraalVM CE Native [x86_64-linux]`

When I run `bundle lock`, the generated file is:

```
PATH
  remote: .
  specs:
    foo (1.0.0)
      nokogiri (~> 1.14.0)

GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  x86_64-linux

DEPENDENCIES
  foo!

BUNDLED WITH
   2.4.7
```

which of course will fail during `bundle install` because:

```
Your lockfile doesn't include a valid resolution.
You can fix this by regenerating your lockfile or manually editing the bad locked gems to a version that satisfies all dependencies.
The unmet dependencies are:
* nokogiri (~> 1.14.0), dependency of foo-1.0.0 but missing from lockfile
```

### Which command did you run?

`bundle lock`

### What were you expecting to happen?

With other rubies, or other versions of bundler, or if I declare the `nokogiri` dependency in the Gemfile directly, this resolves correctly to a lockfile that includes Nokogiri.

### What actually happened?

See above

## Environment

```
Bundler       2.4.7
  Platforms   ruby
Ruby          3.1.3p0 (2023-03-03 revision 671182fbbafef472c11e3e54df3c58303e5a44be) [x86_64-linux]
  Full Path   /home/flavorjones/.rbenv/versions/truffleruby-dev/bin/ruby
  Config Dir  /home/runner/work/truffleruby-dev-builder/truffleruby-dev-builder/etc
RubyGems      3.4.7
  Gem Home    /home/flavorjones/.rbenv/versions/truffleruby-dev/lib/gems
  Gem Path    /home/flavorjones/.gem/truffleruby/3.1.3.3:/home/flavorjones/.rbenv/versions/truffleruby-dev/lib/gems
  User Home   /home/flavorjones
  User Path   /home/flavorjones/.gem/truffleruby/3.1.3.3
  Bin Dir     /home/flavorjones/.rbenv/versions/truffleruby-dev/bin
Tools         
  Git         2.31.0
  RVM         not installed
  rbenv       rbenv 1.2.0-16-gc4395e58
  chruby      
```

## Bundler Build Metadata

```
Built At          2023-02-15
Git SHA           5d717a27e0
Released Version  true
```

## Bundler settings

```
gem.changelog
  Set for the current user (/home/flavorjones/.bundle/config): false
gem.ci
  Set for the current user (/home/flavorjones/.bundle/config): false
gem.coc
  Set for the current user (/home/flavorjones/.bundle/config): true
gem.linter
  Set for the current user (/home/flavorjones/.bundle/config): "rubocop"
gem.mit
  Set for the current user (/home/flavorjones/.bundle/config): true
gem.test
  Set for the current user (/home/flavorjones/.bundle/config): "rspec"
jobs
  Set for the current user (/home/flavorjones/.bundle/config): 4
```

### Gemfile

```ruby
source "https://rubygems.org"
gemspec
```

### Gemfile.lock

```
PATH
  remote: .
  specs:
    foo (1.0.0)
      nokogiri (~> 1.14.0)

GEM
  remote: https://rubygems.org/
  specs:

PLATFORMS
  x86_64-linux

DEPENDENCIES
  foo!

BUNDLED WITH
   2.4.7
```

### foo.gemspec

```ruby
# coding: utf-8
# frozen_string_literal: true

Gem::Specification.new do |spec|
  spec.name = "foo"
  spec.version = "1.0.0"
  spec.homepage = "https://example.com/"
  spec.summary = "foo"
  spec.description = "foo"
  spec.authors = "foo"
  spec.license = "foo"

  spec.add_runtime_dependency("nokogiri", "~> 1.14.0")
end
```

**Comment by flavorjones** [comment]
cc @eregon in case he understands why this might only happen on truffleruby

**Comment by eregon** [comment]
I would guess it only happens on truffleruby because truffleruby has `Gem.platforms = [Gem::Platform::RUBY]` while other Rubies have 2 platforms, which likely makes this problem not appear.
Maybe it also happens on CRuby with Bundler's `force_ruby_platform`?

**Comment by eregon** [comment]
This also happened in https://github.com/zzak/sdoc/actions/runs/4339206734/jobs/7576576496, it would nice to have a fix for this soon.

**Comment by eregon** [comment]
Thank you for the fix!
