### ISSUE TITLE
Gemfile Issue

### ISSUE THREAD

**Issue by jeff1796** [rubygems/rubygems#6465]
### Describe the problem as clearly as you can
I've been getting these issues  plus other ones all having to do with installation errors when trying to install beef. I cannot get past this. Please help!!!

Bundler::GemNotFound: Could not find ansi-1.5.0.gem for installation

An error occurred while installing ansi (1.5.0), and Bundler cannot
continue.  

An error occurred while installing http_parser.rb (0.6.0), and
Bundler cannot continue.                                                     

In Gemfile:
  em-websocket was resolved to 0.5.3, which depends on
    http_parser.rb

An error occurred while installing simple_oauth (0.3.1), and Bundler
cannot continue.

In Gemfile:
  twitter was resolved to 7.0.0, which depends on
    simple_oauth

### Did you try upgrading RubyGems?
I dont know how to since I'm a bit new to this. This is what I get .

### Which command did you run?
sudo ./install

**Comment by xenonVS** [comment]
This is what I get by gem env :
RubyGems Environment:
  - RUBYGEMS VERSION: 3.4.8
  - RUBY VERSION: 3.0.2 (2021-07-07 patchlevel 107) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /var/lib/gems/3.0.0
  - USER INSTALLATION DIRECTORY: /home/xenondev/.local/share/gem/ruby/3.0.0
  - RUBY EXECUTABLE: /usr/bin/ruby3.0
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /home/xenondev/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux-gnu
  - GEM PATHS:
     - /var/lib/gems/3.0.0
     - /home/xenondev/.local/share/gem/ruby/3.0.0
     - /usr/local/lib/ruby/gems/3.0.0
     - /usr/lib/ruby/gems/3.0.0
     - /usr/lib/x86_64-linux-gnu/ruby/gems/3.0.0
     - /usr/share/rubygems-integration/3.0.0
     - /usr/share/rubygems-integration/all
     - /usr/lib/x86_64-linux-gnu/rubygems-integration/3.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /home/xenondev/.local/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /snap/bin
     - /snap/bin
