### ISSUE TITLE
bundler install shebang

### ISSUE THREAD

**Issue by cdenneen** [rubygems/rubygems#6478]
When installing gems via `gem install` the resulting binstubs have a shebang line with `#!/path/to/embedded/bin/ruby` but when doing via `bundle install` it creates as `#!/usr/bin/env ruby`.

Bundler doesn't have a `--no-env-shebang` option like `gem install` does and I tried to specify `bundle config set BUNDLE_SHEBANG /path/to/embedded/bin/ruby` but the installed gems are still with the `env ruby` shebang.

How can I get the `bundler install` to use the full path and not the shebang?

I'd expect both `gem install` and `bundle install` of the same gems to behave the same.
Currently the default for `gem install` provides the full path to the interpreter in the shebang whereas `bundle install` defaults to the `/usr/bin/env ruby` option.

I would expect the behavior to be the same as well as option to disable that option in both. (like `--[no-]env-shebang`)

**Comment by cdenneen** [comment]
@deivid-rodriguez  yes I tried to set as `bundle config set` and also as `BUNDLE_SHEBANG=/path bundle install` neither worked

**Comment by deivid-rodriguez** [comment]
Yeah, I see that `env_shebang: true` is indeed hardcoded for RubyGems binstubs https://github.com/rubygems/rubygems/blob/696264fd07876ca8afc2c89272433daa003e66a4/bundler/lib/bundler/source/rubygems.rb#L175.

I think it would make sense for us to take a PR to make it respect the `shebang` setting!

**Comment by cdenneen** [comment]
@deivid-rodriguez I wouldn't even know where to start to turn that into a parameter vs a hardcoded setting. maybe this is a good first PR for someone to try?

**Comment by deivid-rodriguez** [comment]
Yeah. You can try replacing `:env_shebang => true` with `Bundler.settings[:shebang]` and see what gets generated then.

**Comment by cdenneen** [comment]
@deivid-rodriguez hopefully that PR helps.

**Comment by deivid-rodriguez** [comment]
Thanks, so that did the trick for you?

**Comment by cdenneen** [comment]
@deivid-rodriguez Sorry I don't know how to run that change locally but I was able to create the PR. Hopefully the spec testing can tell if it works or not.

**Comment by deivid-rodriguez** [comment]
Instead of the command you were  previously running, `bundle install`, you can run `/path/to/your/clone/of/rubygems/bundler/exe/bundle install`.

**Comment by cdenneen** [comment]
Ok so with this PR it would make it the ruby path of my executable... and that was without setting anything for shebang in bundle config (config file or ENV var).
So not sure how to set the SHEBANG so it would do the `/usr/bin/env ruby` again with this current PR.
By default gem install doesn't do the `/usr/bin/env ruby` so now with this PR it would be consistent but with that you can set `--env-shebang` (`-E`) so not sure how to do that with `BUNDLE_SHEBANG` since that is supposed to be a value of ruby path not true/false

**Comment by cdenneen** [comment]
Actually that worked... with this PR setting `BUNDLE_SHEBANG=true` will create as `/usr/bin/env ruby` and (`BUNDLE_SHEBANG=false` which is the default) it creates as path to ruby.
So this seems to be working but if I recall isn't what all the examples and docs I've seen mention. 
All references I've found online are to be `BUNDLE_SHEBANG=/opt/path/to/ruby` which doesn't seem to be accurate based on how this `boolean` is working.

At least we know the PR works. Not sure about best way to educate that the config setting has been misleading all along?

**Comment by cdenneen** [comment]
Honestly right now with the value hardcoded to `true` all these references to setting `BUNDLE_SHEBANG` to some `ruby path` seem inaccurate and less likely that this PR would "break" anything since it wasn't doing anything anyway.

However I can see possibly that someone might be running with `/path/to/rubyA` bundle install and with `BUNDLE_SHEBANG=/path/to/rubyB bundle install` they would expect the bang line to be set as such but "any" value causes the setting to evaluate to `True` and therefore results in `#!/usr/bin/env ruby` 

So is there a way to modify the setting to if `true` set to `/usr/bin/env ruby` if set to a `String` (/usr/bin/path/to/rubyB) then literally use that value... if set to False (or missing) set to the path of the ruby that ran `bundle`?

**Comment by deivid-rodriguez** [comment]
I will review your messages and the status of the current setting as soon as I can, thanks for caring for backwards compatibility and investigating what the setting does now! :)

My understanding is that the current setting was used for "Bundler binstubs", which are project specific binstubs generated by `bundle binstubs`. Not sure if it makes sense to share the setting between them, or maybe we should look at rubygems configuration (`--env-shebang` at `~/.gemrc`) or something. Need to look into it closer.

**Comment by MSP-Greg** [comment]
@cdenneen

In the associated PR, I see:
```
C:/Program Files/Puppet Labs/Puppet/puppet/bin/ruby.exe
```

I'd like to look at their build.  I thought you mentioned it was Ruby 2.5, do they have more versions available?  How does one install/download it?

**Comment by cdenneen** [comment]
Their latest build includes newer embedded Ruby but current version I'm stuck on is a 2019.8.12 release:
https://www.puppet.com/releases/2019.8.12
Windows x64 build: https://pm.puppetlabs.com/puppet-agent/2019.8.12/6.28.0/repos/windows/puppet-agent-6.28.0-x64.msi

**Comment by huix11** [comment]
👍

**Comment by zacheryph** [comment]
So... Making assumptions...
* `gem` is typically installing bin[stubs] at the "system" (or user _on_ the system) level.
* `bundle` is typically installing binstubs at the project level `${PROJECT_ROOT}/bin`

For ruby gems installed at the system level this makes sense. They were installed for X.Y version, they should ensure to run (and any native extensions) on that version. As well as ensuring [itself and] any and all of its dependencies that were installed are loadable.

For projects however, they typically don't have a single "home", they reside in production? docker containers? But also, and the simplest example for this, developer machines. Maybe _lots_ of developer machines. With _lots_ of differing setups. Some might be using system Ruby, some chruby, rbenv, rvm, asdf... you get the idea. The point is you have _no_ idea where Ruby is.

I'm not sure it would make a lot of sense to completely get rid of the `env` for bundler [project specific] binstubs? Or shall I say... not having `env` for project specific binstubs seems like a very niche requirement / feature?

If you do `bundle install --binstubs=bin --shebang JRUBY` you do get a _proper_ shebang of `#!/usr/bin/env JRUBY`.
Like wise, if you do `env BUNDLE_SHEBANG=JRUBY bundle install --binstubs=bin` you get the aformentioned shebang line (as long as BUNDLE_SHEBANG is not present in `.bundle/config`.)

**Comment by cdenneen** [comment]
@zacheryph not sure there is anything niche since these are plenty of projects shipped like Puppet Enterprise that ship with embedded ruby.

**Comment by jeromedalbert** [comment]
👋 I can have a look at this issue @cdenneen if you are still interested. It seems that the conversation about what the right solution should be has moved to https://github.com/rubygems/rubygems/pull/6488, so I will comment there to try and move this issue forward.

**Comment by deivid-rodriguez** [comment]
Let's close this in favor of #7849. @cdenneen please do follow up in there if still interested!

**Comment by deivid-rodriguez** [comment]
Ooops, I meant to close #6488 instead.

**Comment by deivid-rodriguez** [comment]
I'm going to close this since we haven't heard from @cdenneen. If you're still having issues, fell free to reopen. We went back and forth a bit and we didn't find a clear path forward, plus we were not sure about the issues you were running into on Windows, so I'll close for now. Thanks!
