### ISSUE TITLE
`bundle` removing `ruby` platform (redux)

### ISSUE THREAD

**Issue by pgib** [rubygems/rubygems#6536]
### Describe the problem as clearly as you can

#5830 raised an issue whereby the `ruby` platform is replaced by that of the platform on which bundler is run. It was fixed in #5832, but seems to have come back as of Bundler 2.4.8.

### Did you try upgrading rubygems & bundler?

Yes

### Post steps to reproduce the problem

I have created a repo to easily demonstrate the issue: https://github.com/pgib/bundler-platform-issue

It creates three Docker images all with Ruby 3.0.5 but differing in Bundler versions, showing the expected behaviour in 2.4.7, and then the regression in 2.4.8 and 2.4.9.

### Which command did you run?

`bundle`

### What were you expecting to happen?

I was expecting the listed platform to not change.

### What actually happened?

The listed platform changed. Output from my testing:

```
===============================================================

Building Docker image for Rubygems 3.4.7...
Doing initial bundle...
PLATFORMS
  ruby

Doing second bundle after adding gem...
PLATFORMS
  ruby

===============================================================

Building Docker image for Rubygems 3.4.8...
Doing initial bundle...
PLATFORMS
  ruby

Doing second bundle after adding gem...
PLATFORMS
  aarch64-linux

===============================================================

Building Docker image for Rubygems 3.4.9...
Doing initial bundle...
PLATFORMS
  ruby

Doing second bundle after adding gem...
PLATFORMS
  aarch64-linux
```

### If not included with the output of your command, run `bundle env` and paste the output below

Included output from 2.4.9 container, though virtually identical in all.

## Environment

```
Bundler       2.4.9
  Platforms   ruby, aarch64-linux
Ruby          3.0.5p211 (2022-11-24 revision ba5cf0f7c52d4d35cc6a173c89eda98ceffa2dcf) [aarch64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.4.9
  Gem Home    /usr/local/bundle
  Gem Path    /root/.local/share/gem/ruby/3.0.0:/usr/local/lib/ruby/gems/3.0.0:/usr/local/bundle
  User Home   /root
  User Path   /root/.local/share/gem/ruby/3.0.0
  Bin Dir     /usr/local/bundle/bin
Tools
  Git         2.30.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-03-20
Git SHA           6f8e92bcc6
Released Version  true
```

## Bundler settings

```
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
gem 'tzinfo'
gem 'rack'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    concurrent-ruby (1.2.2)
    rack (3.0.7)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)

PLATFORMS
  aarch64-linux

DEPENDENCIES
  rack
  tzinfo

BUNDLED WITH
   2.4.9
```

**Comment by deivid-rodriguez** [comment]
Thanks for the nice report, #6540 fixes this!

**Comment by pgib** [comment]
@deivid-rodriguez Sweet! Thank you so much. 🙏
