### ISSUE TITLE
Semantic version issue

### ISSUE THREAD

**Issue by vpereira** [rubygems/rubygems#6551]
ruby version: from ruby 2.7.6 to 3.2

Based on the semantic version specification: https://semver.org/ i was expecting a different behavior of what I'm getting:

```
# it should be true 
2.7.6 :003 > Gem::Version.new("6.0.12-25.10") >= Gem::Version.new("6.0")
 => true 

# If the above result is true, then it should be true too
2.7.6 :002 > Gem::Version.new("6.0.12-25.10") >= Gem::Version.new("6.01")
 => false 
2.7.6 :003 > 

# schrödigers cat: Based on both results, I'm not sure. 
2.7.6 :004 > Gem::Version.new("6.0.12-25.10") >= Gem::Version.new("6.0.12")
 => false 
2.7.6 :005 > 
```

if I understood correctly, the version "6.0.12-25.10" is a pre version from 6.0.12 and therefore it should be smaller than the 6.0.12  as described in https://semver.org/#spec-item-9, no?  But the first two cases looks somehow contradictory?

**Comment by deivid-rodriguez** [comment]
I'm confused, aren't the results you expect the same as what the examples are showing? 🤔

**Comment by vpereira** [comment]
Hi @deivid-rodriguez !

> I'm confused, aren't the results you expect the same as what the examples are showing? 

I forgot one example.. which was the source of confusion for me.. updated.

**Comment by vpereira** [comment]
Hi @deivid-rodriguez !

> I'm confused, aren't the results you expect the same as what the examples are showing? 

I forgot one example.. which was the source of confusion for me.. updated.

**Comment by deivid-rodriguez** [comment]
Still confused @vpereira... All three updated examples are expected too. `6.01` is the same as `6.1`, since leading zeros on an integer component are ignored, maybe that's the source of confusion?

Other than that, for a prerelease version `x` of `6.0.12`, it's expected that

```
6.0 < x < 6.0.12 < 6.1 == 6.01
```

**Comment by vpereira** [comment]
Ok @deivid-rodriguez thank you for reply (sorry the delay, noise, github was kind of dead to me today) :+1:

**Comment by deivid-rodriguez** [comment]
No problem, if there's anything we can explain better in our docs or whatever let us know. Prereleases are always tricky and we do have some weirdness around them, like https://github.com/rubygems/rubygems/issues/3086.
