### ISSUE TITLE
uninitialized constant Gem::Ext::Builder::Shellwords

### ISSUE THREAD

**Issue by ioquatix** [rubygems/rubygems#6568]
Not every usage of `Shellwords` is prepended by `require 'shellwords'`.

```
Exception `Gem::Ext::BuildError' at /home/samuel/.rubies/ruby-3.2.1/lib/ruby/site_ruby/3.2.0/rubygems/ext/builder.rb:172 - ERROR: Failed to build gem native extension.

    uninitialized constant Gem::Ext::Builder::Shellwords
```

Do we want to add more "require 'shellwords'` in that file? Or do we want to use some kind of autoload? Or remove it completely? (avoid using shellwords).

Shellwords generally feels like a hack to me. Better to use proper array of arguments.

**Comment by simi** [comment]
Any hint how to reproduce?

I guess it is missing before this call.

https://github.com/rubygems/rubygems/blob/f8ead4f5f0ea48c7a5ab2947167f66d3c3c2b1fe/lib/rubygems/ext/builder.rb#L30

**Comment by ioquatix** [comment]
I can't remember how it was caused, but any case where we have `Shellwords` without an immediately preceeding `require 'shellwords'` is probably suspect given the current mechanism we are using. Maybe better just to have a top level autoload?

**Comment by deivid-rodriguez** [comment]
Any of the suggested solutions sounds good to me.

**Comment by ioquatix** [comment]
@deivid-rodriguez your original PR here only made it lazy for a subset of usage: https://github.com/rubygems/rubygems/pull/4783

Was that deliberate? What about other files? `require "shellwords"` is at the top of lots of files in `rubygems` project.

**Comment by deivid-rodriguez** [comment]
No, I was probably just focused on fixing the particular issue I was seeing, and didn't audit every usage.

**Comment by ioquatix** [comment]
Okay, I made a PR, hopefully that is helpful.
