### ISSUE TITLE
An error occurred while installing unicode-display_width

### ISSUE THREAD

**Issue by bruceyou1990** [rubygems/rubygems#6587]
Bundler: An error occurred while installing unicode-display_width (2.4.2), and Bundler
  Bundler: cannot continue.
  Bundler: 
  Bundler: In Gemfile:
  Bundler: minima was resolved to 2.5.1, which depends on
  Bundler: jekyll-feed was resolved to 0.17.0, which depends on
  Bundler: jekyll was resolved to 4.3.2, which depends on
  Bundler: terminal-table was resolved to 3.0.2, which depends on
  Bundler: unicode-display_width

**Comment by simi** [comment]
Hello! Can you provide more info? Can you share your Gemfile? It seems combination of your gems and versions is not possible to be resolved.

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
