### ISSUE TITLE
Option to disable "is running, but your lockfile was generated with 2.2.28. Installing Bundler 2.2.28 and restarting using that version"

### ISSUE THREAD

**Issue by mjobin-mdsol** [rubygems/rubygems#6613]
### Describe the problem as clearly as you can

I understand this functionality is to prevent some issues on deployed environment. And it's probably a safe thing to do...
But on my local, I don't really care to install an older version of bundler just because the Gemfile.lock of a random app is outdated.

We work with many apps and I hope it would only try to fetch newer versions, not older ones.

### Did you try upgrading rubygems & bundler?

Yes Always but ... N/A

### Post steps to reproduce the problem

Download an app with an old version of bundler listed in the Gemfile.lock

### Which command did you run?

`bundle install`

### What were you expecting to happen?

Don't install older version, (behavior could be configurable)

### What actually happened?

bundler automatically downgraded itself.

Thanks

**Comment by simi** [comment]
Hello @mjobin-mdsol! Per my understanding there is currently no way to disable this behaviour. The original idea behind this is to keep it consistent. This feature actually doesn't downgrade installed bundler, just install bundler locked in Gemfile.lock and use that one for predictable result of bundler behaviour according to the lockfile.

In theory it could be possible to add config to disable this by modifying following method. But I'm not sure that change would be welcomed.

https://github.com/rubygems/rubygems/blob/51d407c2bf6af941b63a2413469b4a69a8fdd391/bundler/lib/bundler/self_manager.rb#L85-L90

**Comment by deivid-rodriguez** [comment]
For what it's worth, I think this has been requested enough time, so I won't block making it configurable. Or maybe support to give `BUNDLE_VERSION` a requirement instead of an exact version.

**Comment by duckinator** [comment]
I'm also okay with making it configurable.

**Workaround:** Run `bundle --version`, take the version number from that, and use `bundle _VERSION_ ...`.

(Using `bundle _VERSION_ ...` to override the version used was existing functionality, and we made sure to respect it when adding this.)

E.g.,

```console
puppy@orthrus.fox:~/dev/duckinator/okay$ tail -n 2 Gemfile.lock 
BUNDLED WITH
   2.2.15
puppy@orthrus.fox:~/dev/duckinator/okay$ bundle --version
Bundler version 2.5.0.dev
puppy@orthrus.fox:~/dev/duckinator/okay$ bundle _2.5.0.dev_ install
Fetching gem metadata from https://rubygems.org/.
Fetching rake 12.3.3
Installing rake 12.3.3
Using bundler 2.5.0.dev
Fetching rspec-support 3.10.2
Fetching cacert 0.6.0
Fetching diff-lcs 1.4.4
Installing diff-lcs 1.4.4
Installing rspec-support 3.10.2
Fetching rspec-core 3.10.1
Fetching rspec-expectations 3.10.1
Fetching rspec-mocks 3.10.2
Installing cacert 0.6.0
Using okay 12.0.1 from source at `.`
Installing rspec-expectations 3.10.1
Installing rspec-core 3.10.1
Installing rspec-mocks 3.10.2
Fetching rspec 3.10.0
Installing rspec 3.10.0
Bundle complete! 4 Gemfile dependencies, 10 gems now installed.
Bundled gems are installed into `./.bundle/gems`
puppy@orthrus.fox:~/dev/duckinator/okay$ bundle install
Bundler 2.5.0.dev is running, but your lockfile was generated with 2.2.15. Installing Bundler 2.2.15 and restarting using that version.
Fetching gem metadata from https://rubygems.org/.
Fetching bundler 2.2.15
Installing bundler 2.2.15
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
Using rake 12.3.3
Using bundler 2.2.15
Using cacert 0.6.0
Using diff-lcs 1.4.4
Using okay 12.0.1 from source at `.`
Using rspec-support 3.10.2
Using rspec-core 3.10.1
Using rspec-expectations 3.10.1
Using rspec-mocks 3.10.2
Using rspec 3.10.0
Bundle complete! 4 Gemfile dependencies, 10 gems now installed.
Bundled gems are installed into `./.bundle/gems`
puppy@orthrus.fox:~/dev/duckinator/okay$
```

**Comment by duckinator** [comment]
#6405 is related.
