### ISSUE TITLE
Feature request: Pass options to `::Bundler::LockfileParser::initialize` that include setting the `Gemfile` path.

### ISSUE THREAD

**Issue by Skenvy** [rubygems/rubygems#6671]
### Describe the problem as clearly as you can

Besides the option of setting the environment variable `BUNDLE_GEMFILE`, there appears to be no _path_ to trickle down an optional input to [`::Bundler::LockfileParser::initialize`](https://github.com/rubygems/rubygems/blob/bundler-v2.4.12/bundler/lib/bundler/lockfile_parser.rb#L59C16-L94) to set the optional parameter `custom_path` on [`::Bundler::app_cache`](https://github.com/rubygems/rubygems/blob/bundler-v2.4.12/bundler/lib/bundler.rb#L329-L332) -- which means initialising an instance of `::Bundler::LockfileParser` will attempt to use [`::Bundler::root`](https://github.com/rubygems/rubygems/blob/bundler-v2.4.12/bundler/lib/bundler.rb#L305C12-L313) and eventually hit [`::Bundler::SharedHelpers::find_gemfile`](https://github.com/rubygems/rubygems/blob/bundler-v2.4.12/bundler/lib/bundler/shared_helpers.rb#L214-L218), which, without setting `BUNDLE_GEMFILE`, expects the `Gemfile` to be in the directory the command is run from.

### Did you try upgrading rubygems & bundler?

Yes. This is present in `bundler-v2.4.12`.

### Post steps to reproduce the problem

This arises from the way another gem, `dependabot-bundler`, uses `::Bundler::LockfileParser`. A reproduction can be seen in [this workflow](https://github.com/CloutKhan/dependabot-bundler/blob/main/.github/workflows/GemfileNotFound.yml) -- which includes two entries that will run from outside of the directory containing the `Gemfile` and yield the stacktrace described in [this README](https://github.com/CloutKhan/dependabot-bundler/blob/main/README.md). Here are the [most recent logs](https://github.com/CloutKhan/dependabot-bundler/actions/runs/4936415679/jobs/8823907478).

Although a workaround does exist it would be nice if there was a way to pass the option through the call stack rather than affecting env vars.

### Which command did you run?

`Bundler::LockfileParser.new(lockfile_content)`

### What were you expecting to happen?

As there is already a way provided by the `Bundler` gem to circumvent this by setting the environment variable `BUNDLE_GEMFILE`, this is a feature request and not a bug. External to bundler, I was expecting the dependabot-bundler gem to fetch the bundler related files when targeting a directory with a `Gemfile.lock` that was not the current working directory, before investigating and seeing this is not unintended behavious on `Bundler`'s part -- making this a feature request.

### What actually happened?

`Bundler::GemfileNotFound`

#### Environment

```
Bundler       2.4.12
  Platforms   ruby, x86_64-linux
Ruby          3.1.0p0 (2021-12-2[5](https://github.com/CloutKhan/dependabot-bundler/actions/runs/4936415679/jobs/8823907478#step:6:6) revision fb4df44d1[6](https://github.com/CloutKhan/dependabot-bundler/actions/runs/4936415679/jobs/8823907478#step:6:7)[7](https://github.com/CloutKhan/dependabot-bundler/actions/runs/4936415679/jobs/8823907478#step:6:8)0e9d25aef6b235a72[8](https://github.com/CloutKhan/dependabot-bundler/actions/runs/4936415679/jobs/8823907478#step:6:9)11[9](https://github.com/CloutKhan/dependabot-bundler/actions/runs/4936415679/jobs/8823907478#step:6:10)9a177edb) [x86_64-linux]
  Full Path   /opt/hostedtoolcache/Ruby/3.1.0/x64/bin/ruby
  Config Dir  /opt/hostedtoolcache/Ruby/3.1.0/x64/etc
RubyGems      3.4.12
  Gem Home    /opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0
  Gem Path    /home/runner/.local/share/gem/ruby/3.1.0:/opt/hostedtoolcache/Ruby/3.1.0/x64/lib/ruby/gems/3.1.0
  User Home   /home/runner
  User Path   /home/runner/.local/share/gem/ruby/3.1.0
  Bin Dir     /opt/hostedtoolcache/Ruby/3.1.0/x64/bin
Tools         
  Git         2.40.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

#### Bundler Build Metadata

```
Built At          2023-04-[11](https://github.com/CloutKhan/dependabot-bundler/actions/runs/4936415679/jobs/8823907478#step:6:12)
Git SHA           e2cf[27](https://github.com/CloutKhan/dependabot-bundler/actions/runs/4936415679/jobs/8823907478#step:6:28)8db1
Released Version  true
```

**Comment by deivid-rodriguez** [comment]
@Skenvy Can you verify whether #6694 fixes your issue?

**Comment by Skenvy** [comment]
Hey, looks like that does solve it -- the two examples that https://github.com/CloutKhan/dependabot-bundler/actions/runs/5124737192/workflow was expecting to fail due to the error are passing now.

**Comment by deivid-rodriguez** [comment]
Thanks for verifying it!
