### ISSUE TITLE
feature request: gracefully handle the MSVCRT/UCRT windows platform discontinuity

### ISSUE THREAD

**Issue by flavorjones** [rubygems/rubygems#6690]
### Summary

Having both `x64-mingw32` and `x64-mingw-ucrt` platforms in a lockfile causes Bundler to never resolve to native gems. However, given these two platforms are mutually exclusive on windows hardware, can we add edge-case handling to resolve?

If you'd be open to such a feature I'd be happy to submit a PR for review.

### Describe the problem as clearly as you can

RubyInstaller 3.1.0 [shipped a platform change for windows](https://rubyinstaller.org/2021/12/31/rubyinstaller-3.1.0-1-released.html), changing the C runtime from MSVCRT to UCRT. As a result, on the same hardware, Ruby 3.0 (and earlier) will report a platform string of "x64-mingw32" but Ruby 3.1 (and later) will report "x64-mingw-ucrt".

Native gems need to handle this by shipping two gem packages:

- a "x64-mingw32" gem with `required_ruby_version = "< 3.1.dev"` (or similar)
- a "x64-mingw-ucrt" gem with `required_ruby_version = ">= 3.1"`

For an example of this in the wild, see the sqlite3 gem:

- https://rubygems.org/gems/sqlite3/versions/1.6.3-x64-mingw32 has ">= 2.7, < 3.1.DEV"
- https://rubygems.org/gems/sqlite3/versions/1.6.3-x64-mingw-ucrt has ">= 3.1, < 3.3.DEV"

What this unfortunately means is that, if my lockfile has a PLATFORMS section with both "x64-mingw32" and "x64-mingw-ucrt", there is no possible way that the lockfile will resolve to a native gem:

```
$ gem env | fgrep -A2 PLATFORM
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux

$ cat Gemfile
source "https://rubygems.org"
gem "sqlite3", "1.6.3"

$ bundle lock
Fetching gem metadata from https://rubygems.org/.....
Resolving dependencies...
Writing lockfile to /home/flavorjones/tmp/bundler-issue-with-windows/Gemfile.lock

$ bundle lock --add-platform=x64-mingw32
Fetching gem metadata from https://rubygems.org/.....
Resolving dependencies...
Writing lockfile to /home/flavorjones/tmp/bundler-issue-with-windows/Gemfile.lock

$ bundle lock --add-platform=x64-mingw-ucrt
Fetching gem metadata from https://rubygems.org/....
Resolving dependencies...
Writing lockfile to /home/flavorjones/tmp/bundler-issue-with-windows/Gemfile.lock

$ cat Gemfile.lock 
GEM
  remote: https://rubygems.org/
  specs:
    mini_portile2 (2.8.2)
    sqlite3 (1.6.3)
      mini_portile2 (~> 2.8.0)

PLATFORMS
  x64-mingw-ucrt
  x64-mingw32
  x86_64-linux

DEPENDENCIES
  sqlite3 (= 1.6.3)

BUNDLED WITH
   2.4.12
```

However, in reality, there is always a solution that would allow selection of a native gem. In table form:

| ruby version | mingw32 | mingw-ucrt |
| -- | -- | -- |
| 2.7 | yes | no |
| 3.0 | yes | no |
| 3.1 | no | yes |
| 3.2 | no | yes |

Would the bundler maintainers be open to a PR to improve the solution detection to allow for the _union_ of the sets of `mingw32` and `mingw-ucrt` to be used?

### Post steps to reproduce the problem

Posted above.

### What were you expecting to happen?

To be clear, I think bundler is working as designed here. I'm hoping, though, that a feature can be added to allow the solution to accommodate the two disjunct sets of "mingw32" and "mingw-ucrt", so that the emitted lockfile will look like:

```
GEM
  remote: https://rubygems.org/
  specs:
    sqlite3 (1.6.3-x64-mingw32)
    sqlite3 (1.6.3-x64-mingw-ucrt)
    sqlite3 (1.6.3-x86_64-linux)

PLATFORMS
  x64-mingw32
  x64-mingw-ucrt
  x86_64-linux

DEPENDENCIES
  sqlite3 (= 1.6.3)

BUNDLED WITH
   2.4.12
```

**Comment by flavorjones** [comment]
@deivid-rodriguez Would you be open to a PR that patched over the discontinuity of windows platforms as suggested? I didn't want to start without some indication of whether it might be a hard "no", because it's definitely a weird idea.

**Comment by deivid-rodriguez** [comment]
Yeah, normally Bundler resolves to a set of gems that are _all_ compatible with the running Ruby version, so this is expected. But I understand how it gets in the middle here.

I guess if it only affected the Windows platform discontinuity but does not change anything else, and can be removed once Ruby 3.0 support is dropped, it could be acceptable. But it may not be trivial to handle the special case and may open a can of worms.

At some point I was thinking of supporting multi-ruby lockfiles, just like we support multi-platform lockfiles, probably that kind of feature would help here? But it seems tricky and multi-platform lockfiles have been hard to get right & maintain from the beginning, so I'd be hesitant to go that way.

**Comment by flavorjones** [comment]
So, given Ruby 3.0 (the final windows ruby version that uses MSVCRT) is now EOL, I think the value that could be delivered here is lower and I'm going to close it.
