### ISSUE TITLE
Bundle gem should be 'least surprise' ish.  I.e generate and just be able to build straight away.

### ISSUE THREAD

**Issue by emilebosch** [rubygems/rubygems#6695]
### Describe the problem as clearly as you can

I create a lot of gems, many gems not even intended to be published, just for internal purposes. There are two things that can be improved when using `bundle gem` and it really goes against my notion of [Principle of Least Surprise](https://rubyonrails.org/doctrine):

1. The standard ` bundle gem --ext=rust hello_rust` (rust is an example here) invokes a tutorial that asks questions. This is annoying. The tutorial takes more time with questions then editing the gemspec afterwards. I know new beginners would maybe like it. But maybe bundle `gem --interactive` or` bundle gem --tutorial` would be better. After they've learned they probably just go straight to editing the gemspec anyway. I know its fancy, but 99.9% of the times i dont need it.
2. When after walking the tutorial i can still not  `gem build` it because it tells me i need to replace the todos and the home page urls. Just removing those things  completely make it work fine.  

### Did you try upgrading rubygems & bundler?

N/A

### Post steps to reproduce the problem

N/A

### Which command did you run?

` bundle gem --ext=rust hello_rust`

### What were you expecting to happen?

Just generate a gem, maybe with the curent directory as name.

### What actually happened?

Tons of questions, the result is still not `gem build` able.

### If not included with the output of your command, run `bundle env` and paste the output below

N/A

**Comment by emilebosch** [comment]
Hahah @deivid-rodriguez i see now that i've also been commenting on your comment in the past :) Guess we're still annoyed 2 years later by the same thing

**Comment by gl-yziquel** [comment]
I guess the issue I just raised is a continuation of the current one.

https://github.com/rubygems/rubygems/issues/7693

Even if you fix all the TODO and set the urls, you still can't properly install the gem out of the box.

**Comment by deivid-rodriguez** [comment]
This was fixed by #7699 (`bundle install` issues). `gem build` issues can be skipped with `gem build --force`. So I'll close this. Thanks!
