### ISSUE TITLE
--prefer-local should install a lower matching version too (not just newer versions)

### ISSUE THREAD

**Issue by pravi** [rubygems/rubygems#6705]
While testing the --prefer-local option introduced in https://github.com/rubygems/rubygems/issues/5657 I noticed it does not install an older version when specifically locked in Gemfile.

### Describe the problem as clearly as you can

```
(debian-sid)pravi@mahishi:/tmp$ cat Gemfile 
source 'https://rubygems.org'

gem 'ipaddr', '1.2.2'

```

This is locked to an older version due issues in gitlab - https://gitlab.com/gitlab-org/gitlab/-/issues/376417

```
bundle install --prefer-local
Could not find gem 'ipaddr (= 1.2.2)' in locally installed gems.

The source contains the following gems matching 'ipaddr':
  * ipaddr-1.2.4
```

So in case the locally installed version cannot satisfy the specified constraint, this should get installed from rubygems.org

### Did you try upgrading rubygems & bundler?

Using bundler 2.3.20

### Post steps to reproduce the problem

Sample Gemfile is provided above and system has a newer ipaddr via ruby.

### Which command did you run?

bundle install --prefer-local

### What were you expecting to happen?

I was expecting bundler to install ipaddr 1.2.2 from rubygems.org as locally available version 1.2.4 is not satisfying the constraint specified in Gemfile, ie, '1.2.2'

### What actually happened?

It failed to install the required version.

### If not included with the output of your command, run `bundle env` and paste the output below

(debian-sid)pravi@mahishi:/tmp$ bundle env
## Environment

```
Bundler       2.3.20
  Platforms   ruby, x86_64-linux
Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x86_64-linux]
  Full Path   /usr/bin/ruby3.1
  Config Dir  /etc
RubyGems      3.3.15
  Gem Home    /var/lib/gems/3.1.0
  Gem Path    /home/pravi/.gem/ruby/3.1.0:/var/lib/gems/3.1.0:/usr/local/lib/ruby/gems/3.1.0:/usr/lib/ruby/gems/3.1.0:/usr/lib/x86_64-linux-gnu/ruby/gems/3.1.0:/usr/share/rubygems-integration/3.1.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/3.1.0
  User Home   /home/pravi
  User Path   /home/pravi/.gem/ruby/3.1.0
  Bin Dir     /usr/local/bin
Tools         
  Git         2.40.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2022-08-10
Git SHA           4fd2813f54
Released Version  true
```

### Gemfile

```ruby
source 'https://rubygems.org'

gem 'ipaddr', '1.2.2'
```

### Gemfile.lock

```
<No /tmp/Gemfile.lock found>
```

**Comment by deivid-rodriguez** [comment]
It took me so long to get to this, but I think I found a good approach to fix this problem. See #7951!

**Comment by deivid-rodriguez** [comment]
@pravi 2.5.18 is out, so you could now upgrade and remove the patches introduced in https://salsa.debian.org/ruby-team/rubygems/-/commit/f55a7e3d360341fd84f9ae357004639e3251c8c5.

**Comment by pravi** [comment]
@deivid-rodriguez thanks. There is one test failure though, so can't upload yet.
```

===============================================================================
Error: test_execute_system_when_latest_does_not_support_your_ruby_but_previous_one_does(TestGemCommandsUpdateCommand): Gem::MockGemUi::TermError: 1
/<<PKGBUILDDIR>>/test/rubygems/mock_gem_ui.rb:83:in `terminate_interaction'
/<<PKGBUILDDIR>>/lib/rubygems/user_interaction.rb:157:in `terminate_interaction'
/<<PKGBUILDDIR>>/lib/rubygems/commands/update_command.rb:272:in `update_rubygems'
/<<PKGBUILDDIR>>/lib/rubygems/commands/update_command.rb:99:in `execute'
/<<PKGBUILDDIR>>/test/rubygems/test_gem_commands_update_command.rb:149:in `block in test_execute_system_when_latest_does_not_support_your_ruby_but_previous_one_does'
     146:     @cmd.options[:system]        = true
     147: 
     148:     use_ui @ui do
  => 149:       @cmd.execute
     150:     end
     151: 
     152:     err = @ui.error.split "\n"
/<<PKGBUILDDIR>>/lib/rubygems/user_interaction.rb:46:in `use_ui'
/<<PKGBUILDDIR>>/lib/rubygems/user_interaction.rb:69:in `use_ui'
/<<PKGBUILDDIR>>/test/rubygems/test_gem_commands_update_command.rb:148:in `test_execute_system_when_latest_does_not_support_your_ruby_but_previous_one_does'

```

**Comment by deivid-rodriguez** [comment]
Oh, that was close! I'd like to help, what happens if you swallow that error by wrapping lines 148-150 with an `assert_raise Gem::MockGemUi::TermError do` block. That should allow you to see the actual error ext RubyGems is printing and that might help figuring this out.

**Comment by pravi** [comment]
@deivid-rodriguez Antonio uploaded a new rubygems version (the test was only failing when running directly on local, but was working fine in a clean chroot).
