### ISSUE TITLE
Bundler prints secret key in URI when retrying download

### ISSUE THREAD

**Issue by bkabrda** [rubygems/rubygems#6714]
### Describe the problem as clearly as you can

When providing bundler with a custom URI for Gem download which includes a secret key, the key is printed when bundler retries Gem download. For example:

```
Retrying download gem from https://username:ACTUAL_KEY_GETS_PRINTED_HERE@myserver.com/ due to error (2/4): Gem::RemoteFetcher::FetchError bad response Bad Gateway 502 (https://username:REDACTED@myserver.com/some.gem)
```

I believe that this is because the URI printed because of the [retry line](https://github.com/rubygems/rubygems/blob/4076391fce5847689bf2ec402b17133fe4e32285/bundler/lib/bundler/rubygems_integration.rb#L474) is not yet sanitized by the `Gem::Uri` functionality. I think wrapping [this line](https://github.com/rubygems/rubygems/blob/4076391fce5847689bf2ec402b17133fe4e32285/bundler/lib/bundler/rubygems_integration.rb#L471) with `Gem::Uri` would basically do the trick, but the class has only been added in https://github.com/rubygems/rubygems/pull/4868/files and so is probably not in all rubygems versions that you want to keep compability with (not sure about this though).

### Did you try upgrading rubygems & bundler?

Yes, didn't help. I'm seeing this on the latest bundler.

### Post steps to reproduce the problem

* Create a simple Gemfile, e.g.
```
source 'http://rubygems.org'
gem 'sqlite3'
```
* Define `BUNDLE_MIRROR__RUBYGEMS__ORG` to contain a secret key, but make sure that the referenced server returns 5** HTTP code when the artifact download is attempted.
* Run `bundle install`, observe the retry mechanism printing the secret key.

Reproduces on latest bundler (2.4.13) and any version of rubygems.

### Which command did you run?

`bundle install`

### What were you expecting to happen?

Secret key being redacted in output.

### What actually happened?

Secret key not being redacted in the retry messages.

### If not included with the output of your command, run `bundle env` and paste the output below

See below. FWIW, while doing this, bundler also didn't redact the secret key, so I guess that's another place to fix.

## Environment

```
Bundler       2.4.13
  Platforms   ruby, x86_64-linux
Ruby          2.7.1p83 (2020-03-31 revision a0c7c23c9cec0d0ffcba012279cd652d28ad5bf3) [x86_64-linux]
  Full Path   /home/slavek.kabrda/.rbenv/versions/2.7.1/bin/ruby
  Config Dir  /home/slavek.kabrda/.rbenv/versions/2.7.1/etc
RubyGems      3.1.2
  Gem Home    /home/slavek.kabrda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0
  Gem Path    /home/slavek.kabrda/.gem/ruby/2.7.0:/home/slavek.kabrda/.rbenv/versions/2.7.1/lib/ruby/gems/2.7.0
  User Home   /home/slavek.kabrda
  User Path   /home/slavek.kabrda/.gem/ruby/2.7.0
  Bin Dir     /home/slavek.kabrda/.rbenv/versions/2.7.1/bin
Tools         
  Git         2.34.1
  RVM         not installed
  rbenv       rbenv 1.1.2
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-05-10
Git SHA           26eb456c6c
Released Version  true
```

## Bundler Build Metadata

```
Built At          2023-01-31
Git SHA           598c04d54a
Released Version  true
```

## Bundler settings

```
mirror.rubygems.org
  Set via BUNDLE_MIRROR__RUBYGEMS__ORG: "https://username:ACTUAL_KEY_GETS_PRINTED_HERE@myserver.com/"
```

### Gemfile

```ruby
source 'http://rubygems.org'

gem 'sqlite3'
```

### Gemfile.lock

```
GEM
  remote: http://rubygems.org/
  specs:
    sqlite3 (1.6.3-x86_64-linux)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  sqlite3

BUNDLED WITH
   2.4.13
```

**Comment by deivid-rodriguez** [comment]
Thanks for reporting, we should fix this!

Actually, a fix has been started at https://github.com/rubygems/rubygems/pull/5292, it was just never finished. Could you take over that PR?

Ideally we would fix this for every RubyGems version, but just fixing it for RubyGems versions with `Gem::Uri#redacted` would go a long way.

**Comment by deivid-rodriguez** [comment]
I will close this in favor of https://github.com/rubygems/rubygems/issues/5281, please subscribe to that other issue!
