### ISSUE TITLE
Bundler ignores Ruby bundled gems

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#6732]
Very recently racc was converted to being a bundled gem in Ruby master.  This breaks anyone using Rubocop with Ruby master and Bundler.

I realize people can update and delete bundled gems.  It would be helpful if Bundler could use bundled gems, as it would reduce traffic at rubygems.org and speed up CI.

**Comment by hsbt** [comment]
I considered inject bundled gems into `LOAD_PATH` without `Gemfile` at https://github.com/ruby/ruby/pull/7436/files#diff-dc0b326fd9cd06656b0e5013c8dd605aaeddd491351f4f57de3e186203459fbcR360.

**Comment by deivid-rodriguez** [comment]
Can you elaborate on this? Bundled gems are just gems, nothing special. Why should we treat them specially?

**Comment by MSP-Greg** [comment]
My original post was lacking one detail.  I almost always use `BUNDLE_PATH`.

Unless I have a reason to do otherwise, I use Ruby master.  So, for any repo using minitest in its bundle, I've got minitest installed in both the Ruby bundled gem location and in the `BUNDLE_PATH` location.  There are copies of the *.gem file in both cache directories also.

If I recall correctly, when 'bundled gems' were added to Ruby, there were no bundled extension gems, only 'pure' Ruby gems.
Now, there are three bundled extension gems, and that number may increase.

Somewhat off topic, but there is `Gem.default_spec_cache_dir`.  Couldn't there also a `Gem.default_gem_cache_dir`?

**Comment by deivid-rodriguez** [comment]
I'm still confused.

If your goal is to save disk space, why use `BUNDLE_PATH` in the first place? Installing gems for all your repos to the same place would be more efficient.

If your goal is to have more isolated bundles, then default gems becoming full blown gems and getting installed to your `BUNDLE_PATH` seems like a good thing?

I think our goal in Bundler is more inline with better isolation rather than saving disk space, that's why the default install location will be changed in the future to be local to applications.

**Comment by MSP-Greg** [comment]
> save disk space

Not a concern

> Installing gems for all your repos to the same place would be more efficient.

True, but occasionally I may want to test a fresh install of a repo.  Also, and somewhat unique to Windows, I may be working with both ucrt and mswin builds.  I seem to recall a setting in RG that changed the default location for all platform specific files (eg, for MRI, *.so files) to the `extensions` folder.  By chance, do you recall that code?

For me, it just seems odd that files that are considered part of a Ruby build/install are re-installed.  I need to re-read the Ruby issue that @hsbt opened (linked to above).

> I think our goal in Bundler is more inline with better isolation

I agree with that.  But using gems that are part of Ruby doesn't really violate that?  Right now, Bundler will use Ruby's openssl files (a default gem), and it will also allow installing a different version.  But with bundled gems, it will not a gem installed wit Ruby.

Anyway, I'll close this, as it's complex.  My bouncing between platforms and Ruby versions is also not typical.
