### ISSUE TITLE
Add file support to `ruby` method in Gemfile

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems#6742]
I use the `.ruby-version` file standard/convention to track the ruby version of my applications, since that file is respected by many version managers and other tools. Unfortunately, a different set of tools (mostly Heroku, buildpacks, and anything descended from that tradition) uses the Gemfile method `ruby` to track the Ruby version instead. This means I have to update the ruby version string in two places, and I am constantly missing one or the other.

To solve this today, I use this line in my Gemfile:

```ruby
ruby Pathname.new(__dir__).join(".ruby-version").read.strip
```

That technically works, but is pretty ugly. I have to think about what is happening every time I read it, and I would like to instead understand instantly "oh the ruby version is coming from .ruby-version". To improve that situation I propose adding an (optional) `file:` argument to the `ruby` method:

```ruby
ruby file: ".ruby-version"
```

How does that sound to everyone else?

**Comment by deivid-rodriguez** [comment]
@indirect I think that'd be useful and more readable than the above hack indeed!

**Comment by hsbt** [comment]
I'm also +1 for this. How about like this?

```
ruby :version_file # => handle `.ruby-version`, `.tool-version` and `.rbenv-version` or something.
```

We may prevent to pass arbitrary filename.

**Comment by indirect** [comment]
Can you say more about how it helps us to prevent arbitrary filenames? I feel like we tried something similar with `source :rubygems` but had to change to strings because users needed to choose http or https. So if there is a future new file, we would have to edit the Bundler source.

I would like to be able to see which file to look in based on reading the Gemfile--if I see `ruby :version_file` I don't know what file to open, so if we limit arbitrary values maybe we could keep a string but have a list of allowed filenames?

**Comment by clairity** [comment]
to add to the discussion, here's my version of using `.ruby-version` as the canonical ruby version declaration:

```ruby
# Gemfile
ruby File.read('.ruby-version').strip rescue '~>3.2.0'
```

which i learned from https://andycroll.com/ruby/read-ruby-version-in-your-gemfile/, and modified to add a good-enough guard clause in case the file gets deleted for some reason.

**Comment by hsbt** [comment]
>Can you say more about how it helps us to prevent arbitrary filenames? 

In security team of Ruby core, we will handle implicitly code evaluation on like configuration file or dependency list file. I didn't consider the attack surface and vector for `file: '.ruby-version'` yet.

Maybe I worry too much. `:verson_file` symbol is not strong opinion.

**Comment by duckinator** [comment]
I'm in favor of adding `ruby file: '.ruby-version'`. 👍 

@hsbt given that the current approach is to write code that reads a file, I don't think it changes the security implications at all. It's at least no worse than what's already in the wild.
