### ISSUE TITLE
Git sources sorting isn't stable

### ISSUE THREAD

**Issue by etiennebarrie** [rubygems/rubygems#6743]
### Describe the problem as clearly as you can

After running `bundle`, I sometimes get a change in Gemfile.lock that disappears after running `bundle` again.

### Did you try upgrading rubygems & bundler?

Yes

### Post steps to reproduce the problem

The Gemfile looks like this:
```ruby
source "https://rubygems.org"

gem "test", git: "https://gist.github.com/etiennebarrie/3b7b4fc63af236b44d0856cd35ffc6de"
gem "other", ref: "4e67dee93c5b9fb9180c402181486477c7c3bd74", git: "https://gist.github.com/etiennebarrie/3b7b4fc63af236b44d0856cd35ffc6de"
```

```sh-session
git clone https://gist.github.com/etiennebarrie/20eaaee9344bc940d9a66b62bc91560c
cd 20eaaee9344bc940d9a66b62bc91560c
bundle
git diff --name-only
# Gemfile.lock
bundle
git diff --name-only
# nothing
```

To reproduce again past the first time, you can use `bundle update` for example:

```sh-session
bundle update test
git diff --name-only
# Gemfile.lock
bundle
git diff --name-only
# nothing
```

I can also repro with main:

```
$ bundle _2.5.0.dev_ update test >/dev/null && git diff --stat
 Gemfile.lock | 14 +++++++-------
 1 file changed, 7 insertions(+), 7 deletions(-)
$ bundle _2.5.0.dev_  >/dev/null && git diff --stat
 Gemfile.lock | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)
```

---

So I looked into it, and the reason is that Bundler sort sources by their identifier:
https://github.com/rubygems/rubygems/blob/7a7b234721c375874b7e22b1c5b14925b943f04e/bundler/lib/bundler/lockfile_generator.rb#L31
https://github.com/rubygems/rubygems/blob/7a7b234721c375874b7e22b1c5b14925b943f04e/bundler/lib/bundler/source_list.rb#L108-L114
The identifier is defined as a string that includes a few things including a ref (branch, revision, tag):
https://github.com/rubygems/rubygems/blob/7a7b234721c375874b7e22b1c5b14925b943f04e/bundler/lib/bundler/source.rb#L69-L71
https://github.com/rubygems/rubygems/blob/7a7b234721c375874b7e22b1c5b14925b943f04e/bundler/lib/bundler/source/git.rb#L64-L78

Since the Git source doesn't have any of branch, ref, tag, it tries to find the current branch, but there's a flag that prevent Git operations in some cases:
https://github.com/rubygems/rubygems/blob/7a7b234721c375874b7e22b1c5b14925b943f04e/bundler/lib/bundler/source/git/git_proxy.rb#L69-L73
https://github.com/rubygems/rubygems/blob/7a7b234721c375874b7e22b1c5b14925b943f04e/bundler/lib/bundler/source/git/git_proxy.rb#L327-L330
https://github.com/rubygems/rubygems/blob/7a7b234721c375874b7e22b1c5b14925b943f04e/bundler/lib/bundler/source/git/git_proxy.rb#L314-L315

**Comment by duckinator** [comment]
<details>
<summary>Reproduced using your testcase</summary>

(If I wasn't on FreeBSD, the last `git diff` would've been empty -- so despite the different output, it confirms the problem.)

```shellsession
puppy@orthrus:~/dev/rubygems$ git clone https://gist.github.com/etiennebarrie/20eaaee9344bc940d9a66b62bc91560c rg6743
Cloning into 'rg6743'...
remote: Enumerating objects: 4, done.
remote: Total 4 (delta 0), reused 0 (delta 0), pack-reused 4
Receiving objects: 100% (4/4), done.
Resolving deltas: 100% (1/1), done.                                                                                                           puppy@orthrus.fox:~/dev/rubygems$ cd rg6743/
puppy@orthrus.fox:~/dev/rubygems/rg6743 main+ bundle
Bundler 2.4.12 is running, but your lockfile was generated with 2.4.14. Installing Bundler 2.4.14 and restarting using that version.
Fetching gem metadata from https://rubygems.org/.
Fetching bundler 2.4.14
Installing bundler 2.4.14
Fetching https://gist.github.com/etiennebarrie/3b7b4fc63af236b44d0856cd35ffc6de
Resolving dependencies...
Using other 0.0.0 from https://gist.github.com/etiennebarrie/3b7b4fc63af236b44d0856cd35ffc6de (at 4e67dee@4e67dee)
Using test 0.0.0 from https://gist.github.com/etiennebarrie/3b7b4fc63af236b44d0856cd35ffc6de (at main@4e67dee)
Using bundler 2.4.14
Bundle complete! 2 Gemfile dependencies, 3 gems now installed.
Bundled gems are installed into `./.bundle/gems`
puppy@orthrus:~/dev/rubygems/rg6743$ git diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 22c6e01..3eac31d 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -1,15 +1,15 @@                                                                                                                              GIT                                                                                                                                             remote: https://gist.github.com/etiennebarrie/3b7b4fc63af236b44d0856cd35ffc6de
   revision: 4e67dee93c5b9fb9180c402181486477c7c3bd74
+  ref: 4e67dee93c5b9fb9180c402181486477c7c3bd74
   specs:
-    test (0.0.0)
+    other (0.0.0)

 GIT
   remote: https://gist.github.com/etiennebarrie/3b7b4fc63af236b44d0856cd35ffc6de
   revision: 4e67dee93c5b9fb9180c402181486477c7c3bd74
-  ref: 4e67dee93c5b9fb9180c402181486477c7c3bd74
   specs:
-    other (0.0.0)
+    test (0.0.0)

 GEM
   remote: https://rubygems.org/
@@ -17,6 +17,7 @@ GEM

 PLATFORMS
   arm64-darwin-22
+  x86_64-freebsd-13

 DEPENDENCIES
   other!
puppy@orthrus:~/dev/rubygems/rg6743$ bundle
Using bundler 2.4.14
Using other 0.0.0 from https://gist.github.com/etiennebarrie/3b7b4fc63af236b44d0856cd35ffc6de (at 4e67dee@4e67dee)
Using test 0.0.0 from https://gist.github.com/etiennebarrie/3b7b4fc63af236b44d0856cd35ffc6de
Bundle complete! 2 Gemfile dependencies, 3 gems now installed.
Bundled gems are installed into `./.bundle/gems`
puppy@orthrus:~/dev/rubygems/rg6743$ git diff
diff --git a/Gemfile.lock b/Gemfile.lock
index 22c6e01..71fc149 100644
--- a/Gemfile.lock
+++ b/Gemfile.lock
@@ -17,6 +17,7 @@ GEM

 PLATFORMS
   arm64-darwin-22
+  x86_64-freebsd-13

 DEPENDENCIES
   other!
puppy@orthrus:~/dev/rubygems/rg6743$ 
```

</details>

**Comment by duckinator** [comment]
**Workaround:** Specifying `ref:` or `branch:` is enough to make it work consistently. For a gist the default branch appears to be `main`.

Specifying `tag:` would probably avoid the problem, but I haven't tested that.

**Comment by deivid-rodriguez** [comment]
Wait. I was playing around with this a bit more and I actually don't see the issue.

Bundler sorting seems stable, it's just that this particular lockfile is sorted in a different way to how Bundler sorts. In other words, repro steps here are precisely showing that Bundler consistently generates the same lockfile, right?

If Bundler is generating the lockfile in that gist, then that would be an issue, but this issue does not show how to reproduce that. The lockfile could've been reordered by manual edits, and in that case Bundler would be behaving just fine here and fixing the lockfile.

**Comment by etiennebarrie** [comment]
> Bundler sorting seems stable, it's just that this particular lockfile is sorted in a different way to how Bundler sorts. In other words, repro steps here are precisely showing that Bundler consistently generates the same lockfile, right?

The `git diff --name-only` commands shows that it doesn't generate the same lockfile. The gist starts with the stable version (the one you get after running `bundle` multiple times), so the first time, you get the "alternate" version, the diff shows it's changed, you run `bundle` again, you get the stable version again.


> If Bundler is generating the lockfile in that gist, then that would be an issue, but this issue does not show how to reproduce that. The lockfile could've been reordered by manual edits, and in that case Bundler would be behaving just fine here and fixing the lockfile.

The lockfile was generated by bundler, I did not edit it manually, I did however ran `bundle` again to get the stable version. If you remove the Gemfile.lock, and run `bundle _2.4.14_ install`, you get the alternate version of the lockfile, that version is not stable, you run `bundle` and you get a different version (the one committed), that one is stable.

**Comment by deivid-rodriguez** [comment]
Sorry @etiennebarrie, you're right. I think I need more coffee. Let me look into this again.

**Comment by duckinator** [comment]
@etiennebarrie whenever #6786 is included in a release, it should fix this issue. It may change your lockfile _once_, but it won't go back and forth like it does now. 🙂
