### ISSUE TITLE
Package gems with local dependencies

### ISSUE THREAD

**Issue by igbanam** [rubygems/rubygems#6754]
### Describe the problem as clearly as you can

> **tl;dr** I am experimenting with Polylith for Ruby. I spent the better part of this afternoon playing with the idea to package composed gems. It was a good experiment, but it didn't pan out the way I expected. Allowing gems to be "deep-built" or "packaged with locally specified gems" should help fix this

The new version of Bundler (> 2.3.22) allows you "compose" gems using `--path`. However, there's a catch to this. One can only compose gems needed for development; to compose gems into a production unit the gem needs to be built; not just specified. Let me explain.

The case that works with Bundler is this: assume I have a `parent` gem and two children gems: `child-a` and `child-e`. If the parent gem needs the children gem to develop itself, you can add these gems to the parent like we discussed earlier. This adds both gems to the parent's `Gemfile` like so

```ruby
gem "child-x", "<VERSION>", "/path/to/child-x"
```

Since the `parent` does not need any of the children at runtime, adding these to the `Gemfile` is fine. Gems in the `Gemfile` are built into the bundle for the parent gem. However, if the parent needs any of the children at runtime, Bundler chokes.

The case that **does not** work is thus: assume I have a `parent` gem and two children gems: `child-b` and `child-c`. The `parent` vends an executable which — somewhere down the proverbial line — calls a method in `child-c`. i.e. the parent gem needs the child gem at runtime. This means `child-c` should be part of the `parent.gemspec` so it can get built into the parent gem. We'd should add child-c like so

```ruby
spec.add_dependency "child-c", "<VERSION>", path: "/path/to/child-c"
```

While this intuitive, it doesn't work as expected

```
$ ./bin/setup && rake install:local

bundle install
+ bundle install
 
[!] There was an error parsing `Gemfile`:
[!] There was an error while loading `parent.gemspec`: Illformed requirement [{:path=>"path/to/child-c"}]. Bundler cannot continue.

 #  from /path/to/parent/parent.gemspec:34
 #  -------------------------------------------
 #    spec.add_dependency "thor", "~> 1.2.2"
 >    spec.add_dependency "child-c", "~> 0.1.0", path: "path/to/child-c"
 #
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /path/to/parent/Gemfile:6
 #  -------------------------------------------
 #  # Specify your gem's dependencies in parent.gemspec
 >  gemspec
 #
 #  -------------------------------------------
```

From my [experiment proving Polylith can be possible in Ruby][1], there's a workaround to this. I needed to tell Bundler where to find the local gem. Ideally, this should be the repository. So…

```
bundle config set local.child-c /path/to/child-c
```

Yet when I try to install and again, I'm greeted with the same error above.

  [1]: https://gist.github.com/igbanam/483c9471e8bb16ba4ff92e9045ddb8b8

### Did you try upgrading RubyGems?

Yes. Both Rubygems and Bundler are at their tips.

```
$ bundle -v
Bundler version 2.4.14

$ gem -v
3.4.14
```

### Post steps to reproduce the problem

These steps are a list representation of the explanation up tops.

- Create a `parent` gem
- Create a `child` gem — could be anywhere on disk
- In the `parent.gemspec`, link the `parent` to the `child`
  - `spec.add_dependency 'child', 'path: /path/to/child'`
- Build the `parent`

### Which command did you run?

To setup the gems, I used `bundle gem`

```
bundle gem parent
```

```
bundle gem child
```

### What were you expecting to happen?

I expected the commands to install the gem locally

```
$ ./bin/setup && rake install:local
```

…should package the `parent` gem, and install the `child` gem from the path specified. `child-c` should be packaged into `parent` so parent has access to `child-c` modules at runtime.

If we add the gem using the `bundle add --path ...` the gem is added to the bundle, not packaged with the parent. This may look like it's working if the `parent` is run from within its bundle; but breaks when some other gem requires the parent in its gemspec.

```
  *~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~*
  }                               v
+---------+     +---------+     +-----------+
| product | --> | service | --> | component |
+---------+     +---------+     +-----------+
```

The squiggly line should not exist. The `product` should not know about the `component`. The `component` should be embedded in the `service`, and accessible when the `service` is run from the `product` namespace — something like this.

### What actually happened?

The build fails. `--path` is not allowed in `Gem::Specification`. So `rubygems` does not know how to build dependencies from source.

### Run `gem env` and paste the output below

```
$ gem env
RubyGems Environment:
  - RUBYGEMS VERSION: 3.4.14
  - RUBY VERSION: 3.0.3 (2021-11-24 patchlevel 157) [arm64-darwin21]
  - INSTALLATION DIRECTORY: /Users/igbanam/.rvm/gems/ruby-3.0.3
  - USER INSTALLATION DIRECTORY: /Users/igbanam/.gem/ruby/3.0.0
  - RUBY EXECUTABLE: /Users/igbanam/.rvm/rubies/ruby-3.0.3/bin/ruby
  - GIT EXECUTABLE: /opt/homebrew/bin/git
  - EXECUTABLE DIRECTORY: /Users/igbanam/.rvm/gems/ruby-3.0.3/bin
  - SPEC CACHE DIRECTORY: /Users/igbanam/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/igbanam/.rvm/rubies/ruby-3.0.3/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - arm64-darwin-21
  - GEM PATHS:
     - /Users/igbanam/.rvm/gems/ruby-3.0.3
     - /Users/igbanam/.rvm/rubies/ruby-3.0.3/lib/ruby/gems/3.0.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
     - :sources => ["https://rubygems.org/"]
     - :concurrent_downloads => 8
  - REMOTE SOURCES:
     - https://rubygems.org/
```

**Comment by deivid-rodriguez** [comment]
So, you want your gem (`parent`) to depend on a fixed version of `child-x` that lives at a certain path. It sounds like `child-x` is a "private dependency" of `parent` and what you want is to vendor `child-x` inside `parent`.

Nothing stops you from doing that, just drop the files there and use them as you need. You don't need to declare this dependency in any way.

Does that sound like what you're looking for?

**Comment by igbanam** [comment]
Thanks for responding here, David.

Yes, this _somewhat_ describes the problem; only difference is "fixed version" assumes it never changes. If it never changes, then just copying the files are fine. But it does change.

There are two change cases

1. Immediate
    - `child-x` could go from `0.1.0` to `0.2.0`
    - `parent` immediately depends on `child-x@0.2.0` 
2. Deferred
    - `child-x` could go from `0.1.0` to `0.2.0`
    - `parent` can choose if and when to bump its dependencies

Ideally, we want the deferred approach; but starting with the immediate is fine.

In both cases however — with your proposed solution — when you something changes in `child-x`, `child-x` needs to be re-vendored into the parent. Is there a better way to do this?

Crystal Shards does this by symlink-ing the dependency if the dependency is defined as a path. — something like this can work for the "immediate" use case.

**Comment by deivid-rodriguez** [comment]
Sorry I never answered. There's no better way at the moment. I don't think we'd want to provide this feature because when you load a library in Ruby, it pollutes the global namespace anyways. There's no way to require a library "privately" so it doesn't affect the rest of the Ruby process.

Given lack of proper support in Ruby for vendoring, I don't think it makes sense to add features in RubyGems/Bundler for that.

I recommend to follow ruby-core issues treating this issue like https://bugs.ruby-lang.org/issues/19744. I there's ever progress there, we can reconsider adding features to make vendoring easier 👍.
