### ISSUE TITLE
Catch-22 with Gemfile.lock vs BUNDLE_ONLY

### ISSUE THREAD

**Issue by riddley** [rubygems/rubygems#6757]
### Describe the problem as clearly as you can

I'm trying to create a Dockerfile that installs only the gems needed to run my application by setting `BUNDLE_ONLY=production` and during the install this seems to work great.

It's my understanding that including Gemfile.lock in your repo is the suggested best practice, so I've done so. This Gemfile.lock includes the development dependencies.

With the Gemfile.lock in place my app won't start because the development dependencies aren't there, so I'm not sure what BUNDLE_ONLY is for unless I'm just completely wrong about including a Gemfile.lock. If I am completely wrong about that, how do I control the exact versions of the gems that are included in my image?

```
source "https://rubygems.org"

group :production do
  gem "sinatra"
  gem "sinatra-contrib"
  gem "slim"
end

group :development do
  gem "rerun"
  gem "pry"
end
```

I'm trying to avoid having `rerun` and `pry` installed in the image. I know that I can provide version hints in the Gemfile, but I'd like to be able to pin the dependencies as well without tracking them manually.

### Did you try upgrading rubygems & bundler?

Yes.

### Post steps to reproduce the problem

The gems are installing correctly, so I'm not sure that this is a "reproduce" problem rather than just a "the way it works" problem. If I'm wrong about that, I'm happy to provide steps.

### Which command did you run?

I've tried just using:

* just the ENV var
* bundle config set only production
* bundle config set without 'development test'

### What were you expecting to happen?

It seems like `bundle exec` should honor `BUNDLE_ONLY` (or the other methods for setting that.)

### What actually happened?

`bundle exec` complained that I didn't have gems installed that I didn't want installed.

### If not included with the output of your command, run `bundle env` and paste the output below

 bundle env
Calling `DidYouMean::SPELL_CHECKERS.merge!(error_name => spell_checker)' has been deprecated. Please call `DidYouMean.correct_error(error_name, spell_checker)' instead.
## Environment

```
Bundler       2.2.5
  Platforms   ruby, x86_64-linux-musl
Ruby          3.2.2p53 (2023-03-30 revision e51014f9c05aa65cbf203442d37fef7c12390015) [x86_64-linux-musl]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.4.10
  Gem Home    /app/vendor/bundle/ruby/3.2.0
  Gem Path    /app/vendor/bundle/ruby/3.2.0
  User Home   /app
  User Path   /app/.local/share/gem/ruby/3.2.0
  Bin Dir     /app/vendor/bundle/ruby/3.2.0/bin
Tools
  Git         not installed
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2021-01-11
Git SHA           ba867aed7f
Released Version  true
```

## Bundler settings

```
path
  Set via BUNDLE_PATH: "/app/vendor/bundle"
  Set for the current user (/app/.bundle/config): "vendor/bundle"
bin
  Set for the current user (/app/.bundle/config): "bin"
only
  Set via BUNDLE_ONLY: "production"
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```

### Gemfile

```ruby
source "https://rubygems.org"

group :production do
  gem "sinatra"
  gem "sinatra-contrib"
  gem "slim"
  gem "sequel"
  gem "sqlite3"
  gem "pg"
  gem "sassc"
  gem "excon"
  gem "puma"
end

group :development do
  gem "rerun"
  gem "pry"
end
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    coderay (1.1.3)
    excon (0.100.0)
    ffi (1.15.5)
    listen (3.8.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    method_source (1.0.0)
    multi_json (1.15.0)
    mustermann (3.0.0)
      ruby2_keywords (~> 0.0.1)
    nio4r (2.5.9)
    pg (1.5.3)
    pry (0.14.2)
      coderay (~> 1.1)
      method_source (~> 1.0)
    puma (6.3.0)
      nio4r (~> 2.0)
    rack (2.2.7)
    rack-protection (3.0.6)
      rack
    rb-fsevent (0.11.2)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rerun (0.14.0)
      listen (~> 3.0)
    ruby2_keywords (0.0.5)
    sassc (2.4.0)
      ffi (~> 1.9)
    sequel (5.69.0)
    sinatra (3.0.6)
      mustermann (~> 3.0)
      rack (~> 2.2, >= 2.2.4)
      rack-protection (= 3.0.6)
      tilt (~> 2.0)
    sinatra-contrib (3.0.6)
      multi_json
      mustermann (~> 3.0)
      rack-protection (= 3.0.6)
      sinatra (= 3.0.6)
      tilt (~> 2.0)
    slim (5.1.1)
      temple (~> 0.10.0)
      tilt (>= 2.1.0)
    sqlite3 (1.6.3-x86_64-linux)
    temple (0.10.2)
    tilt (2.2.0)

PLATFORMS
  x86_64-linux

DEPENDENCIES
  excon
  pg
  pry
  puma
  rerun
  sassc
  sequel
  sinatra
  sinatra-contrib
  slim
  sqlite3

BUNDLED WITH
   2.2.5
```

**Comment by deivid-rodriguez** [comment]
Hei! You seem to be using Bundler 2.2.5, while BUNDLE_ONLY is only available since Bundler 2.3.19. Upgrade Bundler through `bundle update --bundler` and you should be fine!
