### ISSUE TITLE
bundler install --new-flag. (for any green / Bundler.ui.confirm output)

### ISSUE THREAD

**Issue by professor** [rubygems/rubygems#6796]
I'd love for `bundle install --new-flag` to print out only the green text of a `bundle install`
I'm on a large rails project that has many gems. We're routinely updating a few of them on a daily basis. When I pull my team's source code, I always run `bundle install`, but I feel overwhelmed by the output of the tool. I know that I could use `bundle install --quiet`, but I do like knowing what just changed in my system. 

a) I'd like to know if this would be a welcomed feature
b) I'd like to discuss the name of the flag (e.g. --almost-quiet =) 

Note to self. Look for `Bundler.ui.confirm` in the codebase.

**Comment by indirect** [comment]
IMO this should be the default output, and we should only print the current output when —verbose is passed.

**Comment by simi** [comment]
Alternatively some "interactive" output with progress bars could be default (similar to `yarn`).

- update happened
```
$ yarn
yarn install v1.22.17      
[1/4] Resolving packages...
[2/4] Fetching packages...                  
[3/4] Linking dependencies...
warning " > eslint-plugin-prettier@4.2.1" has unmet peer dependency "prettier@>=2.0.0".
warning " > shakapacker@7.0.2" has unmet peer dependency "@babel/runtime@^7.17.9".
[4/4] Building fresh packages...

warning Your current version of Yarn is out of date. The latest version is "1.22.19", while you're on "1.22.17".
info To upgrade, run the following command:
$ curl --compressed -o- -L https://yarnpkg.com/install.sh | bash
Done in 8.25s.

```

- no changes
```
$ yarn
yarn install v1.22.17
[1/4] Resolving packages...
success Already up-to-date.
Done in 0.42s.
```

**Comment by deivid-rodriguez** [comment]
We have a feature flag (set to be enabled by default on Bundler 3) called `suppress_install_using_messages` that I think does just this. Should we go ahead and enable it by default?

**Comment by deivid-rodriguez** [comment]
> I like this solution. Since it's a breaking change to the tool's output, I like that it's introduced in version 3.x.x

I've never considered breaking changes to the tools output as a major version change, only when they change commands expected to be parsable, like `bundle outdated --parseable`. So my suggestion was to ship it with a regular non major release.

**Comment by indirect** [comment]
I am also happy to ship that change—it was originally set for Bundler 3 when we thought Bundler 3 would ship a long time before now.

**Comment by deivid-rodriguez** [comment]
#6804 implements this!

**Comment by professor** [comment]
@deivid-rodriguez Thank you for shipping this feature. We went from ~641 lines of output down to ~23 lines of output. And what bundler is now printing is useful information. Thanks for improving the signal to noise ratio. It's through the roof!
