### ISSUE TITLE
gem 'wkhtmltopdf-binary'

### ISSUE THREAD

**Issue by ahs2** [rubygems/rubygems#6798]
Hi, when i want install wkhtmltopdf , i have this error

------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=undefined+method+%60size%27+for+nil+NilClass&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
