### ISSUE TITLE
Feature: Tolerate empty BUNDLE_APP_CONFIG

### ISSUE THREAD

**Issue by svoop** [rubygems/rubygems#6803]
BUNDLE_APP_CONFIG is set by official Ruby Docker images which kills deployments with `.bundle/config` checked into the repo – see [this issue](https://github.com/docker-library/ruby/issues/129).

In Docker, there's not way to really unset an ENV variable if it has been set by a previous layer. The somewhat official workaround is to set such an unwanted environment variable with an empty string:

```
ENV BUNDLE_APP_CONFIG=
```

However, Bundler doesn't like this and errors rather spectacularly. This said, I'd like to suggest a tiny modification to have Bundler treat an empty BUNDLE_APP_CONFIG as if it were not set at all.

The [actual code](https://github.com/rubygems/rubygems/blob/master/bundler/lib/bundler.rb#L308) would get slightly more verbose, something along the lines of:

```ruby
# from:
if app_config = ENV["BUNDLE_APP_CONFIG"]

# to:
unless (app_config = ENV["BUNDLE_APP_CONFIG"]).to_s.empty?
```

(Actually, better keep it an `if` and swap the code blocks – for readability.)

I understand that this looks a little hackish... which is why I don't jump into the matter with a PR but would like to ask beforehand whether this stands any chance at all to be merged.

**Comment by deivid-rodriguez** [comment]
Can you instead override it to `BUNDLE_APP_CONFIG=.bundle`, so that configuration is picked from the location that you desire?

**Comment by svoop** [comment]
@deivid-rodriguez Ah, my bad, I tried this with `BUNDLE_APP_CONFIG=.bundle/config` not knowing that the env var (despite its name) doesn't reference the config, but the dir containing it. Thanks for the hint!
