### ISSUE TITLE
gem install is sloooow

### ISSUE THREAD

**Issue by jsirex** [rubygems/rubygems#6807]
### Describe the problem as clearly as you can

I have use-case with only locally available gem, which depends on some public gems.
I built gem locally (e.g. pkg/my-private-gem-0.1.0.gem)
When I try to install it via `gem install pkg/my-private-gem-0.1.0.gem` it takes really long time and consumes lots of CPU.

After debugging I noticed, that when gem is not found, it tries to re-download whole specs.4.8.gz and parses it each time.
I tried to reproduce it with local gem:

```bash
time gem install --debug --verbose my-private-gem-0.3.0.gem 
NOTE:  Debugging mode prints all exceptions even when rescued
HEAD https://index.rubygems.org/
200 OK
GET https://index.rubygems.org/info/my-private-gem
404 Not Found
Exception `Gem::RemoteFetcher::FetchError' at /usr/local/lib/site_ruby/3.1.0/rubygems/remote_fetcher.rb:232 - bad response Not Found 404 (https://index.rubygems.org/info/my-private-gem)
GET https://index.rubygems.org/prerelease_specs.4.8.gz
304 Not Modified
GET https://index.rubygems.org/specs.4.8.gz
304 Not Modified
# >>>>>>> HANG HERE <<<<<<<<
....
1 gem installed

real    0m54.307s
user    0m51.660s
sys     0m1.390s
```
or with just non-exist gem:

```bash
time sudo gem install --debug --verbose pony-gem
NOTE:  Debugging mode prints all exceptions even when rescued
HEAD https://index.rubygems.org/
200 OK
GET https://index.rubygems.org/info/pony-gem
404 Not Found
Exception `Gem::RemoteFetcher::FetchError' at /usr/local/lib/site_ruby/3.1.0/rubygems/remote_fetcher.rb:232 - bad response Not Found 404 (https://index.rubygems.org/info/pony-gem)
GET https://index.rubygems.org/prerelease_specs.4.8.gz
200 OK
GET https://index.rubygems.org/specs.4.8.gz
200 OK
# >>>>>>>>>>> IT HANGS HERE FOR A MINUTE <<<<<<<<<<<<
Exception `Gem::UnsatisfiableDependencyError' at /usr/local/lib/site_ruby/3.1.0/rubygems/resolver/installer_set.rb:82 - Unable to resolve dependency: user requested 'pony-gem (>= 0)'
ERROR:  Could not find a valid gem 'pony-gem' (>= 0) in any repository
GET https://rubygems.org/latest_specs.4.8.gz
200 OK
ERROR:  Possible alternatives: donsgem, moneygem, poc_gem, pokegem, pry-gem, tinygem

real    1m15.133s
user    0m0.010s
sys     0m0.021s
```

So, for locally installed gem I expected it does not check it on rubygems...

### Did you try upgrading RubyGems?

yes

### Run `gem env` and paste the output below

RubyGems Environment:
  - RUBYGEMS VERSION: 3.4.15
  - RUBY VERSION: 3.1.2 (2022-04-12 patchlevel 20) [x86_64-linux-gnu]
  - INSTALLATION DIRECTORY: /var/lib/gems/3.1.0
  - USER INSTALLATION DIRECTORY: /root/.local/share/gem/ruby/3.1.0
  - RUBY EXECUTABLE: /usr/bin/ruby3.1
  - GIT EXECUTABLE: 
  - EXECUTABLE DIRECTORY: /usr/local/bin
  - SPEC CACHE DIRECTORY: /root/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux-gnu
  - GEM PATHS:
     - /var/lib/gems/3.1.0
     - /root/.local/share/gem/ruby/3.1.0
     - /usr/local/lib/ruby/gems/3.1.0
     - /usr/lib/ruby/gems/3.1.0
     - /usr/lib/x86_64-linux-gnu/ruby/gems/3.1.0
     - /usr/share/rubygems-integration/3.1.0
     - /usr/share/rubygems-integration/all
     - /usr/lib/x86_64-linux-gnu/rubygems-integration/3.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin

**Comment by deivid-rodriguez** [comment]
Hei @jsirex!

This seem like two separate (and both valid) issues to me:

* If installing a local package, there's no need to look for the local package at all remotely, we only need to look for its dependencies.

* If a package is not found on the CompactIndex API, but the Compact Compact API is actually available, we should not fallback to the full index, but directly fail.

**Comment by deivid-rodriguez** [comment]
https://github.com/rubygems/rubygems/pull/6810 should fix bullet point `#1`.

**Comment by deivid-rodriguez** [comment]
This should've been fixed now. Please upgrade RubyGems and try again!

**Comment by deivid-rodriguez** [comment]
Great! I'll close this and reticket the slowness when typing a gem that does not exist.

**Comment by deivid-rodriguez** [comment]
Reticketed as https://github.com/rubygems/rubygems/issues/6821.
