### ISSUE TITLE
Consider to set `category: :deprecated` to warn bundled gems candidates

### ISSUE THREAD

**Issue by yahonda** [rubygems/rubygems#6836]
### Describe the problem as clearly as you can

https://github.com/rubygems/rubygems/pull/6831 introduces raising warnings for bundled gem candidates. I would like Bundler have some option to disable warnings by setting `RUBYOPT=-W:deprecated`, not only adding these candidates (base64, mutex_m) to the Gemfile.

### Did you try upgrading rubygems & bundler?
No, however I install `ruby 3.3.0dev` that should install the developed version of Rubygems like `3.5.0.dev`.

```
$ ruby -v
ruby 3.3.0dev (2023-07-26T19:59:59Z master 9bdd485972) [x86_64-linux]
$ gem -v
3.5.0.dev
$ bundler -v
Bundler version 2.4.4
```

### Which command did you run?

```ruby
git clone https://github.com/rails/rails
cd rails
rm Gemfile.lock
bundle install
bin/test test/application/bin_setup_test.rb:30
```

### What were you expecting to happen?

It should pass.

### What actually happened?

It fails because this test does not expect these warning messages.

```ruby
$ rm ../Gemfile.lock ; bundle ; RUBYOPT=-W:deprecated bin/test test/application/bin_setup_test.rb:30
Fetching https://github.com/github/trilogy.git
Fetching https://github.com/matthewd/websocket-client-simple.git
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Bundle complete! 81 Gemfile dependencies, 215 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
mutex_m is not part of the default gems since Ruby 3.4.0. Add it to your Gemfile.
drb is not part of the default gems since Ruby 3.4.0. Add it to your Gemfile.
base64 is not part of the default gems since Ruby 3.4.0. Add it to your Gemfile.
base64 is not part of the default gems since Ruby 3.4.0. Add it to your Gemfile.
mutex_m is not part of the default gems since Ruby 3.4.0. Add it to your Gemfile.
Run options: --seed 1511

# Running:

F

Failure:
ApplicationTests::BinSetupTest#test_bin_setup_output [/home/yahonda/src/github.com/rails/rails/railties/test/application/bin_setup_test.rb:51]:
--- expected
+++ actual
@@ -2,10 +2,16 @@
 The Gemfile's dependencies are satisfied

 == Preparing database ==
+mutex_m is not part of the default gems since Ruby 3.4.0. Add it to your Gemfile.
+base64 is not part of the default gems since Ruby 3.4.0. Add it to your Gemfile.
 Created database 'app_development'
 Created database 'app_test'

 == Removing old logs and tempfiles ==
+mutex_m is not part of the default gems since Ruby 3.4.0. Add it to your Gemfile.
+base64 is not part of the default gems since Ruby 3.4.0. Add it to your Gemfile.

 == Restarting application server ==
+mutex_m is not part of the default gems since Ruby 3.4.0. Add it to your Gemfile.
+base64 is not part of the default gems since Ruby 3.4.0. Add it to your Gemfile.
 "



bin/test test/application/bin_setup_test.rb:30



Finished in 5.598662s, 0.1786 runs/s, 0.1786 assertions/s.
1 runs, 1 assertions, 1 failures, 0 errors, 0 skips
```

**Comment by yahonda** [comment]
This commit demonstrates what I want. https://github.com/rubygems/rubygems/compare/master...yahonda:rubygems:add_category_deprecated_for_bundled_gems

**Comment by hsbt** [comment]
I understood your concern.

`Warning[:deprecated]` is default `false`. So, no one see deprecated message of bundled gems with default. I'm considering better solution for disabling warnings.

On the other hand, can you add warning gems to gemspec of rails? I added Ruby 2.7 support to drb at https://github.com/ruby/drb/pull/20. So, `drb`, `base64` and `mutex_m` are working with Ruby 2.7 and Rails 7.0. 

I try to make this better message for users.

**Comment by yahonda** [comment]
https://github.com/rails/rails/commit/350d272d6cd6fbbb127133773c79c3c17e4216f0

**Comment by yahonda** [comment]
https://github.com/rails/rails/pull/48907 has been merged into the Rails main branch.

**Comment by yahonda** [comment]
I'm closing this issue because https://github.com/rails/rails/pull/48907 has been merged to the Rails main branch. Once Rails 7.1 is released include this change, Users will not see these warnings.

If users run Rails 7.0.z or lower using Ruby 3.3, these warnings will appear and they will need to add these gems to their applications Gemfile manually. Because Rails 7.0.z only accepts bug fixes and addressing these warnings are out of scopes of bug fixes.

I'll add some comments to https://bugs.ruby-lang.org/issues/19776 if necessary.
