### ISSUE TITLE
Default to no docs generation during `gem update --system`?

### ISSUE THREAD

**Issue by indirect** [rubygems/rubygems#6860]
Upgrading RubyGems is very slow compared to upgrading Bundler:

```
❯ gem update --system
Updating rubygems-update
Fetching rubygems-update-3.4.18.gem
Successfully installed rubygems-update-3.4.18
Parsing documentation for rubygems-update-3.4.18
Installing ri documentation for rubygems-update-3.4.18
Done installing documentation for rubygems-update after 28 seconds
Parsing documentation for rubygems-update-3.4.18
Done installing documentation for rubygems-update after 0 seconds
Installing RubyGems 3.4.18
  Successfully built RubyGem
  Name: bundler
  Version: 2.4.18
  File: bundler-2.4.18.gem
Bundler 2.4.18 installed
RubyGems 3.4.18 installed
Regenerating binstubs
Regenerating plugins
Parsing documentation for rubygems-3.4.18
Installing ri documentation for rubygems-3.4.18
```

It's pretty frustrating to have to wait 30 seconds for a RubyGems upgrade when upgrading Bundler by itself is basically instantaneous.

I noticed that `gem update --system` generates rdoc and ri documentation for the rubygems-update gem. Since we don't actually use that gem for anything, could we skip that step to speed up upgrading rubygems itself, even if we continue to generate documentation for other gems by default?

**Comment by deivid-rodriguez** [comment]
Uggh, this is indeed so slow... I've had `gem: --no-document` in my `.gemrc` file for a long time, so I didn't suffer from this recently.

Totally in favor of making this the default for `gem update --system`, although we could possibly also dig into why this is so slow!
