### ISSUE TITLE
bundle list --name-only: "Unknown switches"

### ISSUE THREAD

**Issue by navels** [rubygems/rubygems#6894]
Super confused here and surprised I don't see an existing issue for this . . . 

```
> bundle list --name-only
Unknown switches '--name-only'
```

but meanwhile

```
> bundle list --help
NAME
       bundle-list - List all the gems in the bundle

SYNOPSIS
       bundle list [--name-only] [--paths] [--without-group=GROUP] [--only-group=GROUP]
```

My setup:

## Environment

```
Bundler       1.17.3
  Platforms   ruby, aarch64-linux
Ruby          2.7.8p225 (2023-03-30 revision 1f4d4558484b370999954f3ede7e3aa3a3a01ef3) [aarch64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.4.17
  Gem Home    /usr/local/bundle
  Gem Path    /home/lee.nave/.local/share/gem/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0:/usr/local/bundle
  User Path   /home/lee.nave/.local/share/gem/ruby/2.7.0
  Bin Dir     /usr/local/bundle/bin
Tools
  Git         2.30.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

**Comment by deivid-rodriguez** [comment]
Hei, Bundler 1.17.3 was released 5 years ago. Latest version is Bundler 2.4.19. Please upgrade to the latest version, thanks!

**Comment by navels** [comment]
Not an option for us at the moment.

**Comment by gurrenPizza** [comment]
@deivid-rodriguez I'm running into this issue when trying to setup the VSCode Rubocop extension, and just like @navels , upgrading bundler isn't really possible currently.

However, I do would like to perform this upgrade in the future. Would you know at which version of bundler this --name-only flag was introduced so we can plan our upgrade schedule towards at least that version?

**Comment by deivid-rodriguez** [comment]
According to documentation site, every Bundler version has this flag, including 1.17. So I guess this was just a bug. I tried Bundler 2.1 and it seems to work, but I'd suggest to upgrade to the latest version anyways.

**Comment by gurrenPizza** [comment]
Hmm, that's weird. Maybe I'll see if the extension has a repo I can an open an issue to, then.

Thanks for the heads up anyway, @deivid-rodriguez !
