### ISSUE TITLE
RubyGems should not accept deprecated SPDX licenses

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#6912]
SPDX not just introduces new license identifiers, but also deprecates some. Outstanding example might be `GPL-2.0` identifier. I think that for new projects, RubyGems should disallow the identifiers with `isDeprecatedLicenseId: true` JSON field.

**Comment by indirect** [comment]
I am fine with printing a warning during build for gems that are assigning a license that SPDX has explicitly deprecated. Why do you think we should reject those gems, when we allow any license?

**Comment by voxik** [comment]
_disallow_ was maybe too strong. Warning sounds fine. I actually don't if RubyGems allows other then SPDX identifiers neither I know what are the SPDX recommendations with regard to deprecated identifiers. I just know that the deprecated identifiers are not recognized by Fedora and that is where I come from.

**Comment by hsbt** [comment]
FYI:

* https://github.com/rubygems/rubygems/issues/2153
* https://github.com/rubygems/rubygems/pull/2259

**Comment by voxik** [comment]
Thx for pointers. This certainly duplicates #2153
