### ISSUE TITLE
`bundle lock --minor --update` doesn't add new dependencies at their latest version

### ISSUE THREAD

**Issue by DawidJanczak** [rubygems/rubygems#6952]
### Describe the problem as clearly as you can

I have a question about the way `bundle lock --minor --strict --update` works. When dealing with the actual dependency it works just fine and it upgrades it to the latest possible minor version. I noticed a weird issue when dealing with that dependency's dependencies though: it seems when a dependency needs to be **added** it doesn't get added on latest version, but on what seems to be _latest minor of the initial release_.

I noticed this when upgrading the `sequel` gem to latest: https://rubygems.org/gems/sequel/versions/5.72.0 A `bigdecimal` dependency was added there with a `>= 0` constraint. Now if I do `bundle lock --update sequel` then `bigdecimal` gets added as latest version (3.1.4). If I do `bundle lock --minor --update sequel` though I end up with version 1.4.4. That version doesn't seem to work with the newest Ruby version (3.2.2 to be exact). I was wondering if that logic for dependency handling makes sense, is there a reason for this logic?

### Did you try upgrading rubygems & bundler?

Yes, both at latest.

### Post steps to reproduce the problem

Add a `Gemfile` with `sequel` gem, `Gemfile.lock` can look like this:
```
GEM
  remote: https://rubygems.org/
  specs:
    sequel (5.71.0)

PLATFORMS
  ruby

DEPENDENCIES

BUNDLED WITH
   2.4.19
```

Run `bundler lock --minor --update sequel` - notice bigdecimal library added at 1.4.4 instead of 3.1.4.

### Which command did you run?

`bundler lock --minor --update sequel`

### What were you expecting to happen?

I was expecting sequel gem's _dependencies_ to get added at latest possible version.

### What actually happened?

Sequel gem's dependencies were added at the latest possible minor _of the first major release that matches_.

### If not included with the output of your command, run `bundle env` and paste the output below
```
## Environment

Bundler       2.4.19
  Platforms   ruby, x86_64-linux
Ruby          3.2.2p53 (2023-03-30 revision e51014f9c05aa65cbf203442d37fef7c12390015) [x86_64-linux]
  Full Path   /home/gat/.rbenv/versions/3.2.2/bin/ruby
  Config Dir  /home/gat/.rbenv/versions/3.2.2/etc
RubyGems      3.4.19
  Gem Home    /home/gat/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0
  Gem Path    /home/gat/.gem/ruby/3.2.0:/home/gat/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0
  User Home   /home/gat
  User Path   /home/gat/.gem/ruby/3.2.0
  Bin Dir     /home/gat/.rbenv/versions/3.2.2/bin
Tools
  Git         2.41.0
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      not installed
```

**Comment by deivid-rodriguez** [comment]
Thanks for reporting @DawidJanczak!

It seems like a bug to me, let me look into it!

**Comment by deivid-rodriguez** [comment]
#6992 fixes this!

**Comment by DawidJanczak** [comment]
Thank you @deivid-rodriguez!
