### ISSUE TITLE
`bundle plugin uninstall` wipes out your code if using a path

### ISSUE THREAD

**Issue by ccutrer** [rubygems/rubygems#6953]
### Describe the problem as clearly as you can

In my Gemfile, I have something like

`plugin "my_plugin", path: "../my_plugin"`

I was testing some installation behavior of my plugin, and so needed to re-install it. First I ran `bundle plugin uninstall my_plugin` to clean it out of the plugin index. Then to my horror, I realized that the entire my_plugin directory was gone!

### Did you try upgrading rubygems & bundler?

Yes. I'm on rubygems 3.4.19, and bundler 2.4.19.

### What were you expecting to happen?

Because it's a `path:` reference in the gemfile, I expected it to only get removed from .bundle/plugins/index, but the actual plugin (which is not cached in .bundle) would remain untouched.

### What actually happened?

My local code was removed!

## Environment

```
Bundler       2.4.19
  Platforms   ruby, arm64-darwin-21
Ruby          3.1.3p185 (2022-11-24 revision 1a6b16756e0ba6b95ab71a441357ed5484e33498) [arm64-darwin-21]
  Full Path   /Users/cody/.rubies/ruby-3.1.3/bin/ruby
  Config Dir  /Users/cody/.rubies/ruby-3.1.3/etc
RubyGems      3.4.19
  Gem Home    /Users/cody/.gem/ruby/3.1.3
  Gem Path    /Users/cody/.gem/ruby/3.1.3:/Users/cody/.rubies/ruby-3.1.3/lib/ruby/gems/3.1.0
  User Home   /Users/cody
  User Path   /Users/cody/.gem/ruby/3.1.0
  Bin Dir     /Users/cody/.gem/ruby/3.1.3/bin
Tools         
  Git         2.39.2 (Apple Git-143)
  RVM         not installed
  rbenv       not installed
  chruby      0.3.9
```

## Bundler Build Metadata

```
Built At          2023-08-17
Git SHA           86f98098e3
Released Version  true
```

## Bundler settings

```
gem.changelog
  Set for the current user (/Users/cody/.bundle/config): false
gem.ci
  Set for the current user (/Users/cody/.bundle/config): false
gem.coc
  Set for the current user (/Users/cody/.bundle/config): false
gem.linter
  Set for the current user (/Users/cody/.bundle/config): "rubocop"
gem.mit
  Set for the current user (/Users/cody/.bundle/config): false
gem.test
  Set for the current user (/Users/cody/.bundle/config): false
gemfile
  Set via BUNDLE_GEMFILE: "/Users/cody/src/canvas-lms/Gemfile"
unset
  Set for the current user (/Users/cody/.bundle/config): "frozen"
```

## Gemfile

```
<snip>
```

**Comment by simi** [comment]
I'm super sad to see your work was unexpectedly removed :( I left some comments at #7001.

**Comment by kstevens715** [comment]
This happened to me the other day as well. I only lost about 15 minutes of work, but it was a bummer.
