### ISSUE TITLE
[DOC] Broken links in documentation

### ISSUE THREAD

**Issue by BurdetteLamar** [rubygems/rubygems#6986]
Broken links in the documentation:

- On https://docs.ruby-lang.org/en/master/Gem.html:
  - Text:  `ENV`.
  - Href:  `RUBYLIB`.
- On https://docs.ruby-lang.org/en/master/Gem/Ext/CargoBuilder.html:
  - Text:  `RbConfig::CONFIG`.
  - Href:  `'SOEXT'`.
- On https://docs.ruby-lang.org/en/master/Gem/Resolver/APISpecification.html:
  - Text:  `guides.rubygems.org/rubygems-org-api/#misc_methods`.
  - Href:  `https://guides.rubygems.org/rubygems-org-api/#misc_methods` (fragment should have hyphen, not underscore).
- On https://docs.ruby-lang.org/en/master/Gem/Resolver/Molinillo/Resolver/Resolution.html:
  - Text:  `String,Nil=>`.
  - Href:  `Object`.
- On https://docs.ruby-lang.org/en/master/Gem/Version.html:
  - Text:  `blog.zenspider.com/2008/10/rubygems-howto-preventing-cata.html`.
  - Href:  `http://blog.zenspider.com/2008/10/rubygems-howto-preventing-cata.html`.

**Comment by simi** [comment]
Thanks for report @BurdetteLamar, I have [fixed](https://github.com/rubygems/rubygems/pull/7008) everything except `Molinillo` one, since that needs to be fixed at [upstream](https://github.com/CocoaPods/Molinillo). I'll check and open PR in there as well.
