### ISSUE TITLE
Better checking on running Ruby binary in tests

### ISSUE THREAD

**Issue by strzibny** [rubygems/rubygems#703]
Hi,

the test suite fails for us due to the expectation that `Gem.ruby` as the path for running Ruby is also an actual binary file running it, which is not the case in recent Fedoras (and might not be true for other environments as well).

```
1) Failure:
TestGemExtBuilder#test_build_extensions_extconf_bad [/home/mtasaka/rpmbuild/fedora-SCM/rubygems/master/rubygems-2.1.9/test/rubygems/test_gem_ext_builder.rb:94]:
Expected /\/usr\/bin\/ruby: No such file/ to match "/usr/bin/ruby extconf.rb \n/usr/bin/ruby-mri: No such file or directory -- extconf.rb (LoadError)\n".
```

In Fedora we want to implement more Ruby implementations and this is done by running appropriate implementation (using `exec`) in `/usr/bin/ruby` (so we can keep the same shebangs). That's why the error on the missing extconf.rb will be returned by `/usr/bin/ruby-mri` and not file represented by `Gem.ruby`.

I cannot find a better way how to return this information then runinng[1] :

```
puts `ls -al /proc/#{$$}/exe`.split(" ")[-1]
```

Which is definitely not as nice as Python's `sys.executable`. Therefore I am not sending a pull request yet, but want to hear your ideas.

[1] http://stackoverflow.com/questions/1536602/what-is-rubys-equivalent-of-pythons-sys-executable

**Comment by eregon** [comment]
FWIW, `Gem.ruby` could be a symlink, and there isn't really a guarantee what the OS puts in `argv[0]`.
So the right thing is to relax the test here, and just check that RubyGems calls the right Ruby, but don't expect the error message to include `Gem.ruby`.

So
```ruby
assert_match %r{#{Regexp.escape Gem.ruby} .* extconf\.rb}, File.read(gem_make_out)
assert_match %r{: No such file}, File.read(gem_make_out)
```
is enough (and needed for TruffleRuby & JRuby which don't have access to `argv[0]`).
