### ISSUE TITLE
Bundler cannot load psych under JRuby when loading the gemspec (JRuby however can load psych outside of bundler)

### ISSUE THREAD

**Issue by postmodern** [rubygems/rubygems#7073]
I noticed that bundler refuses to load `psych` under JRuby when loading a local `test.gemspec` file in a "clean environment". To ensure that this is not a JRuby issue, **I confirmed that JRuby can load `psych` outside of or without bundler**. The `psych` library should be considered part of stdlib, and thus should not be excluded by bundler's "clean environment" when it attempts to load the gemspec, before any other gem dependencies have been activated. I first noticed the behavior in the last week when my [GitHub Actions started failing with the below error message only under JRuby](https://github.com/ronin-rb/ronin-db-activerecord/actions/runs/6519373480/job/17705783580), implying it is a recent change to bundler (or possibly JRuby).

## Steps To Reproduce

1. Double check that we are using JRuby: `ruby -v`
2. Create a `test.gemspec` file that also happens to load `yaml`:
```ruby
# frozen_string_literal: true

# Note: some gems may use YAML to load gemspec metadata from a gemspec.yml file.
require 'yaml'

Gem::Specification.new do |spec|
  spec.name = "test"
  spec.version = '0.0.1'
  spec.authors = ["Test"]
  spec.email = ["test@example.com"]

  spec.summary = "Test gem"
  spec.description = "This is a test gem. Do not release."

  spec.metadata["homepage_uri"] = 'https://example.com'

  # Specify which files should be added to the gem when it is released.
  # The `git ls-files -z` loads the files in the RubyGem that have been added into git.
  spec.files = Dir.chdir(__dir__) do
    `git ls-files -z`.split("\x0").reject do |f|
      (File.expand_path(f) == __FILE__) ||
        f.start_with?(*%w[bin/ test/ spec/ features/ .git .circleci appveyor Gemfile])
    end
  end
  spec.require_paths = ["lib"]
end
```
3. Create a `Gemfile`
```ruby
# frozen_string_literal: true

source "https://rubygems.org"

gemspec
```
4. `bundle install`
5. Double check that JRuby can load `psych` without/outside of bundler: `ruby -r psych -e 'p Psych'`

### Expected Results

The `.gemspec` file can load `yaml` and `psych`.

### Actual Result

```
$ ruby -v
jruby 9.4.3.0 (3.1.4) 2023-06-07 3086960792 OpenJDK 64-Bit Server VM 17.0.8+7 on 17.0.8+7 +jit [x86_64-linux]
$ bundle i

[!] There was an error parsing `Gemfile`: 
[!] There was an error while loading `test.gemspec`: cannot load (ext) (org.jruby.ext.psych.PsychLibrary). Bundler cannot continue.

 #  from /home/postmodern/test/ruby/bundler/test.gemspec:3
 #  -------------------------------------------
 #  
 >  require 'yaml'
 #  
 #  -------------------------------------------
. Bundler cannot continue.

 #  from /home/postmodern/test/ruby/bundler/Gemfile:3
 #  -------------------------------------------
 #  
 >  gemspec
 #  -------------------------------------------
$ ruby -r psych -e 'p Psych'
Psych
```

## Additional Information

* `jruby 9.4.3.0 (3.1.4) 2023-06-07 3086960792 OpenJDK 64-Bit Server VM 17.0.8+7 on 17.0.8+7 +jit [x86_64-linux]`
* `Bundler version 2.4.20`
* `psych (default: 5.1.0 java` (from `gem list psych`)

**Comment by indirect** [comment]
Huh. I'm surprised this works on CRuby, since by definition Bundler must be able to load the Gemfile and exec without requiring psych for it to be possible to specify a psych version in the Gemfile. How do you think it should it work, if a gemspec requires psych but then the Gemfile lists a different version of psych than the default one?

**Comment by postmodern** [comment]
> How do you think it should it work, if a gemspec requires psych but then the Gemfile lists a different version of psych than the default one?

When loading the `Gemfile` it should implicitly allow using what is considered to be stdlib (aka actual stdlib + bundled ruby gems). If the `Gemfile` or `gemspec` lists a dependency for a specific version of `psych`, then it should add that dependency to the resulting `Gemfile.lock`. Once we have a `Gemfile.lock`, it's gem versions can be activated without loading the `Gemfile`/`gemspec`.

I think it might be too extreme to try to prevent `psych` from being loaded, as rubygems itself uses YAML/psych internally.

FWIW, CRuby + bundler can handle loading `yaml` in the `gemspec` *and* specifying an explicit `psych` dependency in the `Gemfile`:

```ruby
source 'https://rubygems.org/'

gemspec

gem 'psych', '5.1.0'
```

```
$ bundle i
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Fetching stringio 3.0.8
Installing stringio 3.0.8 with native extensions
Fetching psych 5.1.0
Installing psych 5.1.0 with native extensions
Bundle complete! 2 Gemfile dependencies, 4 gems now installed.
Bundled gems are installed into `./vendor/bundle`
```

```
PATH
  remote: .
  specs:
    test (0.0.1)

GEM
  remote: https://rubygems.org/
  specs:
    jar-dependencies (0.4.1)
    psych (5.1.0)
      stringio
    psych (5.1.0-java)
      jar-dependencies (>= 0.1.7)
    stringio (3.0.8)

PLATFORMS
  universal-java-17
  x86_64-linux

DEPENDENCIES
  psych (= 5.1.0)
  test!

BUNDLED WITH
   2.4.20
```

**Comment by postmodern** [comment]
@indirect I discovered the root cause. Another version of psych was previously installed into `vendor/bundle`, which causes bundler to attempt to activate it before loading the `.gemspec`.

I can reproduce this by adding `gem 'psych', '5.1.1'` to the `Gemfile`, running `bundle install`, then running `bundle install` again.

Not sure if this is such a niche edge-case that it warrants fixing or whether this could be closed as Wont Fix?

**Comment by andrehjr** [comment]
https://github.com/ruby/psych/issues/655

Psych 5.1.1 was broken on jruby. v5.1.1.1 was released to fix that. Maybe it's related to this issue?

**Comment by postmodern** [comment]
@andrehjr you are correct. Switching to `psych` `5.1.1.1` fixes the issue. Closing this now.
