### ISSUE TITLE
Ability to provide custom error message from private gem server

### ISSUE THREAD

**Issue by adrianthedev** [rubygems/rubygems#7105]
### Describe the problem as clearly as you can

I run a private rubygems server (https://packager.dev) to serve private gems of [my product](https://avohq.io).

For my product, I have two license keys. One for the rubygems server and one for a runtime check.
Users often get those mixed and try to use the runtime key instead of the gems key. 
They get the standard 403 message which most of the time doesn't help them very much.
Can I add a custom message to that response? 
If that's not possible, would you be open to a PR with this addition?

**Comment by duckinator** [comment]
I went ahead and added a title to this issue. Can you provide some example output of what the current error looks like? I'm mainly hoping it mentions a class name (e.g. `Bundler::HTTPError`), because that'll narrow down the relevant part of the codebase quite a bit.

**Comment by adrianthedev** [comment]
The response looks like this.
We'd love to be able to respond with a URL to an article or something that will help the user understand what's happening and how they can get self-help.

![CleanShot 2023-10-30 at 21 22 33@2x](https://github.com/rubygems/rubygems/assets/1334409/b78e9e4a-6a7c-44f4-9537-a94e26223b62)

**Comment by duckinator** [comment]
Looks like this is from `‎Bundler::RubygemsIntegration#download_gem‎`.

https://github.com/rubygems/rubygems/blob/b6fe6dd386dbfc3b0b009b10987e74650ff15232/bundler/lib/bundler/rubygems_integration.rb#L491-L520

**Comment by duckinator** [comment]
Closed by #7148.
