### ISSUE TITLE
React Native Error While installing the project 0.72.6

### ISSUE THREAD

**Issue by Prabhat1933** [rubygems/rubygems#7108]
debug We couldn't find a package.json in your project. Are you sure you are running it inside a React Native project?
debug Failed to load configuration of your project. Only a subset of commands will be available.
debug Initializing new project
                                                          
               ######                ######               
             ###     ####        ####     ###             
            ##          ###    ###          ##            
            ##             ####             ##            
            ##             ####             ##            
            ##           ##    ##           ##            
            ##         ###      ###         ##            
             ##  ########################  ##             
          ######    ###            ###    ######          
      ###     ##    ##              ##    ##     ###      
   ###         ## ###      ####      ### ##         ###   
  ##           ####      ########      ####           ##  
 ##             ###     ##########     ###             ## 
  ##           ####      ########      ####           ##  
   ###         ## ###      ####      ### ##         ###   
      ###     ##    ##              ##    ##     ###      
          ######    ###            ###    ######          
             ##  ########################  ##             
            ##         ###      ###         ##            
            ##           ##    ##           ##            
            ##             ####             ##            
            ##             ####             ##            
            ##          ###    ###          ##            
             ###     ####        ####     ###             
               ######                ######               
                                                          

                  Welcome to React Native!                
                 Learn once, write anywhere               

debug Installing template from react-native@latest
Wrote to /private/var/folders/q0/5rtwddr13j72khp6w91sc6mr0000gq/T/rncli-init-template-2R6zbr/package.json:

{
  "name": "rncli-init-template-2r6zbr",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}

npm WARN deprecated @babel/plugin-proposal-optional-catch-binding@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
npm WARN deprecated @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0

added 705 packages, and audited 706 packages in 53s

42 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
debug Getting config from /var/folders/q0/5rtwddr13j72khp6w91sc6mr0000gq/T/rncli-init-template-2R6zbr/node_modules/react-native/template.config.js
debug Copying template from /var/folders/q0/5rtwddr13j72khp6w91sc6mr0000gq/T/rncli-init-template-2R6zbr/node_modules/react-native/template
debug Changing HelloWorld for MyAwesomeProject in template
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/tsconfig.json
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/tsconfig.json
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/package.json
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/package.json
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/metro.config.js
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/metro.config.js
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/jest.config.js
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/jest.config.js
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/_xcode.env
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/_xcode.env
debug Renaming /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/_xcode.env -> file:/Users/user/Documents/GOLDEN/MyAwesomeProject/ios/.xcode.env
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/Podfile
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/Podfile
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorldTests/Info.plist
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorldTests/Info.plist
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorldTests/HelloWorldTests.m
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorldTests/HelloWorldTests.m
debug Renaming /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorldTests/HelloWorldTests.m -> file:/Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorldTests/MyAwesomeProjectTests.m
debug Renaming /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorldTests -> file:/Users/user/Documents/GOLDEN/MyAwesomeProject/ios/MyAwesomeProjectTests
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorld.xcodeproj/xcshareddata/xcschemes/HelloWorld.xcscheme
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorld.xcodeproj/xcshareddata/xcschemes/HelloWorld.xcscheme
debug Renaming /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorld.xcodeproj/xcshareddata/xcschemes/HelloWorld.xcscheme -> file:/Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorld.xcodeproj/xcshareddata/xcschemes/MyAwesomeProject.xcscheme
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorld.xcodeproj/project.pbxproj
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorld.xcodeproj/project.pbxproj
debug Renaming /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorld.xcodeproj -> file:/Users/user/Documents/GOLDEN/MyAwesomeProject/ios/MyAwesomeProject.xcodeproj
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorld/main.m
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorld/main.m
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorld/LaunchScreen.storyboard
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorld/LaunchScreen.storyboard
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorld/Info.plist
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorld/Info.plist
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorld/Images.xcassets/Contents.json
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorld/Images.xcassets/Contents.json
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorld/Images.xcassets/AppIcon.appiconset/Contents.json
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorld/Images.xcassets/AppIcon.appiconset/Contents.json
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorld/AppDelegate.mm
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorld/AppDelegate.mm
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorld/AppDelegate.h
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorld/AppDelegate.h
debug Renaming /Users/user/Documents/GOLDEN/MyAwesomeProject/ios/HelloWorld -> file:/Users/user/Documents/GOLDEN/MyAwesomeProject/ios/MyAwesomeProject
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/index.js
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/index.js
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/babel.config.js
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/babel.config.js
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/app.json
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/app.json
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/settings.gradle
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/settings.gradle
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/gradlew.bat
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/gradlew.bat
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/gradlew
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/gradlew
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/gradle.properties
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/gradle.properties
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/gradle/wrapper/gradle-wrapper.properties
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/gradle/wrapper/gradle-wrapper.properties
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/gradle/wrapper/gradle-wrapper.jar
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/gradle/wrapper/gradle-wrapper.jar
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/build.gradle
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/build.gradle
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/release/java/com/helloworld/ReactNativeFlipper.java
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/release/java/com/helloworld/ReactNativeFlipper.java
debug Renaming /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/release/java/com/helloworld -> file:/Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/release/java/com/myawesomeproject
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/values/styles.xml
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/values/styles.xml
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/values/strings.xml
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/values/strings.xml
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/mipmap-mdpi/ic_launcher.png
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/mipmap-hdpi/ic_launcher.png
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/drawable/rn_edit_text_material.xml
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/res/drawable/rn_edit_text_material.xml
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/java/com/helloworld/MainApplication.java
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/java/com/helloworld/MainApplication.java
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/java/com/helloworld/MainActivity.java
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/java/com/helloworld/MainActivity.java
debug Renaming /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/java/com/helloworld -> file:/Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/java/com/myawesomeproject
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/AndroidManifest.xml
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/main/AndroidManifest.xml
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/debug/java/com/helloworld/ReactNativeFlipper.java
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/debug/java/com/helloworld/ReactNativeFlipper.java
debug Renaming /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/debug/java/com/helloworld -> file:/Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/debug/java/com/myawesomeproject
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/debug/AndroidManifest.xml
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/src/debug/AndroidManifest.xml
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/proguard-rules.pro
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/proguard-rules.pro
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/debug.keystore
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/debug.keystore
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/build.gradle
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/android/app/build.gradle
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/_watchmanconfig
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/_watchmanconfig
debug Renaming /Users/user/Documents/GOLDEN/MyAwesomeProject/_watchmanconfig -> file:/Users/user/Documents/GOLDEN/MyAwesomeProject/.watchmanconfig
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/_prettierrc.js
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/_prettierrc.js
debug Renaming /Users/user/Documents/GOLDEN/MyAwesomeProject/_prettierrc.js -> file:/Users/user/Documents/GOLDEN/MyAwesomeProject/.prettierrc.js
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/_gitignore
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/_gitignore
debug Renaming /Users/user/Documents/GOLDEN/MyAwesomeProject/_gitignore -> file:/Users/user/Documents/GOLDEN/MyAwesomeProject/.gitignore
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/_eslintrc.js
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/_eslintrc.js
debug Renaming /Users/user/Documents/GOLDEN/MyAwesomeProject/_eslintrc.js -> file:/Users/user/Documents/GOLDEN/MyAwesomeProject/.eslintrc.js
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/_bundle/config
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/_bundle/config
debug Renaming /Users/user/Documents/GOLDEN/MyAwesomeProject/_bundle/config -> file:/Users/user/Documents/GOLDEN/MyAwesomeProject/_bundle/config
debug Renaming /Users/user/Documents/GOLDEN/MyAwesomeProject/_bundle -> file:/Users/user/Documents/GOLDEN/MyAwesomeProject/.bundle
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/__tests__/App.test.tsx
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/__tests__/App.test.tsx
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/README.md
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/README.md
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/Gemfile
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/Gemfile
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/App.tsx
debug Replacing in /Users/user/Documents/GOLDEN/MyAwesomeProject/App.tsx
npm WARN deprecated @babel/plugin-proposal-numeric-separator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-numeric-separator instead.
npm WARN deprecated @babel/plugin-proposal-optional-catch-binding@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-catch-binding instead.
npm WARN deprecated @babel/plugin-proposal-nullish-coalescing-operator@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-nullish-coalescing-operator instead.
npm WARN deprecated @babel/plugin-proposal-class-properties@7.18.6: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-class-properties instead.
npm WARN deprecated @babel/plugin-proposal-async-generator-functions@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-async-generator-functions instead.
npm WARN deprecated @babel/plugin-proposal-optional-chaining@7.21.0: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-optional-chaining instead.
npm WARN deprecated @babel/plugin-proposal-object-rest-spread@7.20.7: This proposal has been merged to the ECMAScript standard and thus this plugin is no longer maintained. Please use @babel/plugin-transform-object-rest-spread instead.
npm WARN deprecated uglify-es@3.3.9: support for ECMAScript is superseded by `uglify-js` as of v3.13.0

added 1125 packages, and audited 1126 packages in 33s

138 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
error --- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Gem::GemNotFoundException: can't find gem bundler (= 2.4.21) with executable bundle
  /Users/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems.rb:264:in `find_spec_for_exe'
  /Users/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/rubygems.rb:244:in `bin_path'
  /Users/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/rubygems_integration.rb:178:in `bin_path'
  /Users/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/shared_helpers.rb:297:in `set_bundle_variables'
  /Users/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/shared_helpers.rb:76:in `set_bundle_environment'
  /Users/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli/exec.rb:20:in `run'
  /Users/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:492:in `exec'
  /Users/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /Users/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /Users/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /Users/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
  /Users/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /Users/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/cli.rb:28:in `start'
  /Users/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:45:in `block in <top (required)>'
  /Users/user/.rbenv/versions/3.2.2/lib/ruby/site_ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /Users/user/.rbenv/versions/3.2.2/lib/ruby/gems/3.2.0/gems/bundler-2.4.10/libexec/bundle:33:in `<top (required)>'
  /Users/user/.rbenv/versions/3.2.2/bin/bundle:25:in `load'
  /Users/user/.rbenv/versions/3.2.2/bin/bundle:25:in `<main>'

```

## Environment

```
Bundler       2.4.21
  Platforms   ruby, x86_64-darwin-22
Ruby          3.2.2p53 (2023-03-30 revision e51014f9c05aa65cbf203442d37fef7c12390015) [x86_64-darwin-22]
  Full Path   /Users/user/.rbenv/versions/3.2.2/bin/ruby
  Config Dir  /Users/user/.rbenv/versions/3.2.2/etc
RubyGems      3.4.21
  Gem Home    /Users/user/.gem/ruby/3.2.2
  Gem Path    /Users/user/.gem/ruby/3.2.2:/opt/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0
  User Home   /Users/user
  User Path   /Users/user/.gem/ruby/3.2.0
  Bin Dir     /Users/user/.gem/ruby/3.2.2/bin
Tools         
  Git         2.39.2 (Apple Git-143)
  RVM         not installed
  rbenv       rbenv 1.2.0
  chruby      0.3.9
```

## Bundler Build Metadata

```
Built At          2023-10-17
Git SHA           d10b46bd15
Released Version  true
```

## Bundler settings

```
force_ruby_platform
  Set for your local app (/Users/user/Documents/GOLDEN/MyAwesomeProject/.bundle/config): true
path
  Set for your local app (/Users/user/Documents/GOLDEN/MyAwesomeProject/.bundle/config): "vendor/bundle"
```

### ../Gemfile

```ruby
source 'https://rubygems.org'

# You may use http://rbenv.org/ or https://rvm.io/ to install and use this version
ruby ">= 2.6.10"

gem 'cocoapods', '~> 1.13'
gem 'activesupport', '>= 6.1.7.3', '< 7.1.0'
```

### ../Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    CFPropertyList (3.0.6)
      rexml
    activesupport (7.0.8)
      concurrent-ruby (~> 1.0, >= 1.0.2)
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      tzinfo (~> 2.0)
    addressable (2.8.5)
      public_suffix (>= 2.0.2, < 6.0)
    algoliasearch (1.27.5)
      httpclient (~> 2.8, >= 2.8.3)
      json (>= 1.5.1)
    atomos (0.1.3)
    claide (1.1.0)
    cocoapods (1.13.0)
      addressable (~> 2.8)
      claide (>= 1.0.2, < 2.0)
      cocoapods-core (= 1.13.0)
      cocoapods-deintegrate (>= 1.0.3, < 2.0)
      cocoapods-downloader (>= 1.6.0, < 2.0)
      cocoapods-plugins (>= 1.0.0, < 2.0)
      cocoapods-search (>= 1.0.0, < 2.0)
      cocoapods-trunk (>= 1.6.0, < 2.0)
      cocoapods-try (>= 1.1.0, < 2.0)
      colored2 (~> 3.1)
      escape (~> 0.0.4)
      fourflusher (>= 2.3.0, < 3.0)
      gh_inspector (~> 1.0)
      molinillo (~> 0.8.0)
      nap (~> 1.0)
      ruby-macho (>= 2.3.0, < 3.0)
      xcodeproj (>= 1.23.0, < 2.0)
    cocoapods-core (1.13.0)
      activesupport (>= 5.0, < 8)
      addressable (~> 2.8)
      algoliasearch (~> 1.0)
      concurrent-ruby (~> 1.1)
      fuzzy_match (~> 2.0.4)
      nap (~> 1.0)
      netrc (~> 0.11)
      public_suffix (~> 4.0)
      typhoeus (~> 1.0)
    cocoapods-deintegrate (1.0.5)
    cocoapods-downloader (1.6.3)
    cocoapods-plugins (1.0.0)
      nap
    cocoapods-search (1.0.1)
    cocoapods-trunk (1.6.0)
      nap (>= 0.8, < 2.0)
      netrc (~> 0.11)
    cocoapods-try (1.2.0)
    colored2 (3.1.2)
    concurrent-ruby (1.2.2)
    escape (0.0.4)
    ethon (0.16.0)
      ffi (>= 1.15.0)
    ffi (1.16.3)
    fourflusher (2.3.1)
    fuzzy_match (2.0.4)
    gh_inspector (1.1.3)
    httpclient (2.8.3)
    i18n (1.14.1)
      concurrent-ruby (~> 1.0)
    json (2.6.3)
    minitest (5.20.0)
    molinillo (0.8.0)
    nanaimo (0.3.0)
    nap (1.1.0)
    netrc (0.11.0)
    public_suffix (4.0.7)
    rexml (3.2.6)
    ruby-macho (2.5.1)
    typhoeus (1.4.0)
      ethon (>= 0.9.0)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    xcodeproj (1.23.0)
      CFPropertyList (>= 2.3.3, < 4.0)
      atomos (~> 0.1.3)
      claide (>= 1.0.2, < 2.0)
      colored2 (~> 3.1)
      nanaimo (~> 0.3.0)
      rexml (~> 3.2.4)

PLATFORMS
  ruby

DEPENDENCIES
  activesupport (>= 6.1.7.3, < 7.1.0)
  cocoapods (~> 1.13)

RUBY VERSION
   ruby 3.2.2p53

BUNDLED WITH
   2.4.21
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=can%27t+find+gem+bundler+%28%3D+2.4.21%29+with+executable+bundle&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.
error Looks like your iOS environment is not properly set. Please go to https://reactnative.dev/docs/environment-setup?os=macos&platform=android and follow the React Native CLI QuickStart guide for macOS and iOS.

**Comment by hsbt** [comment]
It's not related RubyGems or Bundler.
