### ISSUE TITLE
Ability for `bundle exec` to fall back to locally installed gem via `--fall-back` option

### ISSUE THREAD

**Issue by djpowers** [rubygems/rubygems#7118]
### Describe the problem as clearly as you can

There are certain circumstances where you may want to prioritize using a bundled version of a gem, and if that bundled gem is not present, fall back to a version available in the path (if available).

For example, various text editors allow you to include a command to run as part of LSP formatting/linting. The [RuboCop docs suggest calling the bundled version](https://docs.rubocop.org/rubocop/usage/lsp.html#examples-of-lsp-client). This works great for projects bundling RuboCop, but does not cover cases where a project or file does not have RuboCop bundled, or if there is no Gemfile at all.

Calling `rubocop` instead will work in the above scenario, but that would require changing your editor config depending on what project you are editing. Ideally a command would be available to work in both situations.

### Post steps to reproduce the problem

1. Install a gem such as RuboCop on your system via `gem install rubocop`
2. Open your text editor that has been configured to run `bundle exec rubocop` on file changes.
3. Make changes that will violate a RuboCop rule.

### What were you expecting to happen?

Ideally, bundler could be configured to attempt rerunning the command without `bundle exec`.

My thought is that a `--fall-back` flag could be provided (optional, defaulted to false) which would first try executing the command as normal, and if the gem is not found in the locally installed gems (`gem info rubocop` says "Could not find..."), the command would then be run without `bundle exec` prepended.

#### Example usage
Bundled gem available:
- `bundle exec rubocop --lsp --fall-back`
- `bundle exec rubocop --lsp` runs successfully

No bundled gem available:
- `bundle exec rubocop --lsp --fall-back`
- `rubocop --lsp` is run instead, as bundler cannot find "rubocop"

This would help in scenarios where a gem may be installed both directly and via bundler, and users would not have to worry about whether they are calling the correct version. (It assumes the bundled version should be prioritized.)

### What actually happened?

The command in the editor silently fails, as bundler cannot find the missing gem (correctly).

**Comment by indirect** [comment]
Can I interest you in our prototype command that allows running gems inside the existing bundle on the fly, without modifying the Gemfile? https://github.com/segiddins/bundler-compose. We'd love to get feedback on how to make that as useful as possible for real-world use cases.
