### ISSUE TITLE
give bundler lock an option to force touching Gemfile.lock

### ISSUE THREAD

**Issue by hadmut** [rubygems/rubygems#7120]
Hi, 

that's a little, but strong wish: 

bundler lock 
creates the Gemfile.lock from Gemfile. But it doesn't touch Gemfile.lock if there's nothing to do, thus not updating the file mod time of the Gemfile.lock. 

That comes with a problem. If there is a Makefile or Rakefile, where Gemfile.lock depends from Gemfile and calls bundler lock to recreate Gemfile.lock once Gemfile has been changed (i.e. newer than Gemfile.lock), it calls bundler lock with every run again and again and again, since Gemfile.lock never becomes newer than Gemfile if there's nothing new to do. 

Not even a bundler lock --update  would update the file if there's nothing new (e.g. because of just minor changes in Gemfile such as whitespace and comments)

Would be nice if bundler lock would always (or at least with a given option) touch the Gemfile.lock to have the file date reflect the time of the last run of bundler lock, and be make/rake-friendly

regards

**Comment by kbrock** [comment]
Great request.

As a temporary hack, you may want to try (or probably already do this so a share for other people):

```Makefile
Gemfile.lock: Gemfile
  bundle update
  @touch Gemfile.lock
```

**Comment by deivid-rodriguez** [comment]
I guess this would be fine? Would it cause issues if we did this by default? 🤔

**Comment by martinemde** [comment]
Doing this by default makes sense to me. Seems harmless and it's consistent with make's expectations.
