### ISSUE TITLE
Source credentials present in both configuration and the Gemfile are removed when writing the lock file

### ISSUE THREAD

**Issue by tt** [rubygems/rubygems#7185]
### Describe the problem as clearly as you can

If you have a Gemfile with a `source` block or a `:source` option and that remote contains credentials, having the same credentials set in your Bundler configuration file will cause `bundle install` to remove the credentials from the lock file which will then prevent `bundle exec` from finding the gem.

Turning on `allow_deployment_source_credential_changes` can be used as a workaround but as far as I interpret the documentation, that is not its intended behavior. (I'm not running in deployment mode and credentials are removed rather than added.)

### Did you try upgrading rubygems & bundler?

Yes. I'm using the latest versions and have tried other versions to check for recent regressions.

### Post steps to reproduce the problem

I'm running Ruby 3.2.2 built with ruby-install on macOS 14.1.1. I'm using Bundler 2.4.22.

As the reproduction requires access to a protected gem server, I can't share complete instructions.

Any Gemfile with a block like below should allow reproducing the bug:

```ruby
source "https://username:password@example.com" do
  gem "gem"
end
```

You then need to set the credentials in your configuration file with `bundle config https://example.com username:password`.

Running `bundle install` will then cause the lock file to contain the following lines (notice the missing credentials):

```
GEM
  remote: https://example.com/
  specs:
    ...
```

### Which command did you run?

`bundle install --quiet && bundle exec irb`

### What were you expecting to happen?

I expected `irb` to launch.

I think there are two different approaches for how to solve this:

- `bundle install` could write credentials in the lock file if the credentials are present in the Gemfile even if they're also present in the Bundler configuration.
- `bundle exec` could remove configured credentials from sources before comparing them.

The first option seems best to me because it also prevents changes to the lock file.

### What actually happened?

`bundle exec` told me I had to first run `bundle install` which I had done and which completed successfully:

```shell
$ bundle install --quiet && bundle exec irb
Could not find gem '<gem>' in locally installed gems
Run `bundle install` to install missing gems.
```

This happens due to the code in `Bundler::Source::Rubygems#suppress_configured_credentials`:

https://github.com/rubygems/rubygems/blob/f0e8dacdecaa39aaee0b43450d92cc08f5b84d4c/bundler/lib/bundler/source/rubygems.rb#L358-L365

`remote` is the URL from the Gemfile but when the credentials are identical, it's treated as if they were found in the configuration file even though they're not. (Credentials from the configuration seems to only be retrieved in `Bundler::Source::Rubygems::Remote` so I'm unsure why there's code to remove them in the first place.)

The issue with `bundle exec` is raised in the code below:

https://github.com/rubygems/rubygems/blob/4ce66c41a2fcf45a517f995a8f743ed7273b37e1/bundler/lib/bundler/definition.rb#L935-L941

The gem is added to `@specs_that_changed_sources` on the following line:

https://github.com/rubygems/rubygems/blob/4ce66c41a2fcf45a517f995a8f743ed7273b37e1/bundler/lib/bundler/definition.rb#L848

That checks fail because the `lockfile_source` doesn't include credentials whereas `gemfile_source` (`dep.source`) does.

**Comment by deivid-rodriguez** [comment]
Hello! Thanks for reporting, this is indeed inconsistent.

We got reports in the past suggesting that Bundler should never include credentials in lockfiles for security. I agree with that, but never got around fixing it.

Fixing that will also fix this inconsistency, since lockfile credentials will never be included in the first place, regardless of whether configuration is set or not.

I'm implementing this at #7560.
