### ISSUE TITLE
`ruby "3.3.0-preview3"` fails

### ISSUE THREAD

**Issue by harshalbhakta** [rubygems/rubygems#7186]
### Describe the problem as clearly as you can

I got below error when using a `3.3.0-preview3` version of Ruby in `.ruby-version` file. 

#### `bundle install` error

````ruby
Your Ruby version is 3.3.0.dev, but your Gemfile specified 3.3.0.preview3
````

#### .ruby-version

````ruby
3.3.0-preview3
````

#### Gemfile

````ruby

ruby file: '.ruby-version'

# or 

ruby "3.3.0-preview3"

````

### Did you try upgrading rubygems & bundler?

Yes. Using the latest version of rubygems and bundler.

### Post steps to reproduce the problem

Use 3.3.0-preview3 in .ruby-version file with rbenv

### Which command did you run?

`bundle install`

### What were you expecting to happen?

`bundle install` should have executed without any error

### What actually happened?

Got below error

````shell
Your Ruby version is 3.3.0.dev, but your Gemfile specified 3.3.0.preview3
````

## Environment

```
Bundler       2.4.22
  Platforms   ruby, x86_64-darwin-23
Ruby          3.3.0p-1 (2023-11-12 revision 60e19a0b5fc9c067ee88751192dc56da618f5060) [x86_64-darwin-23]
  Full Path   /Users/harshal/.rbenv/versions/3.3.0-preview3/bin/ruby
  Config Dir  /Users/harshal/.rbenv/versions/3.3.0-preview3/etc
RubyGems      3.5.0.dev
  Gem Home    /Users/harshal/.rbenv/versions/3.3.0-preview3/lib/ruby/gems/3.3.0+0
  Gem Path    /Users/harshal/.local/share/gem/ruby/3.3.0+0:/Users/harshal/.rbenv/versions/3.3.0-preview3/lib/ruby/gems/3.3.0+0
  User Home   /Users/harshal
  User Path   /Users/harshal/.local/share/gem/ruby/3.3.0+0
  Bin Dir     /Users/harshal/.rbenv/versions/3.3.0-preview3/bin
Tools         
  Git         2.43.0
  RVM         not installed
  rbenv       rbenv 1.2.0-17-ga8ecfc7
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-11-09
Git SHA           ec2089640
Released Version  true
```

Also tried using bundler version `2.5.0.dev`

## Environment

```
Bundler       2.5.0.dev
  Platforms   ruby, x86_64-darwin-23
Ruby          3.3.0p-1 (2023-11-12 revision 60e19a0b5fc9c067ee88751192dc56da618f5060) [x86_64-darwin-23]
  Full Path   /Users/harshal/.rbenv/versions/3.3.0-preview3/bin/ruby
  Config Dir  /Users/harshal/.rbenv/versions/3.3.0-preview3/etc
RubyGems      3.5.0.dev
  Gem Home    /Users/harshal/.rbenv/versions/3.3.0-preview3/lib/ruby/gems/3.3.0+0
  Gem Path    /Users/harshal/.local/share/gem/ruby/3.3.0+0:/Users/harshal/.rbenv/versions/3.3.0-preview3/lib/ruby/gems/3.3.0+0
  User Home   /Users/harshal
  User Path   /Users/harshal/.local/share/gem/ruby/3.3.0+0
  Bin Dir     /Users/harshal/.rbenv/versions/3.3.0-preview3/bin
Tools         
  Git         2.43.0
  RVM         not installed
  rbenv       rbenv 1.2.0-17-ga8ecfc7
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-11-22
Git SHA           unknown
Released Version  false
```

**Comment by harshalbhakta** [comment]
I think below changes in Ruby might be causing this problem. Will dig deeper when I have more time.

* https://github.com/ruby/ruby/commit/f6e2f32a962c2c19a0418dfd2020c8c9ab32c8b0
* https://github.com/ruby/ruby/commit/68df43788dc237a1071f02b2d82768f844696315
* https://github.com/ruby/ruby/pull/8578/files
* https://github.com/ruby/ruby/pull/8905/files

**Comment by hsbt** [comment]
Yes, It's Ruby package issue.

There is no way to resolve by Bundler. You never specify `preview3` with `ruby` DSL of Gemfile. Stay tuned for next preview or final release.
