### ISSUE TITLE
`file` option in Gemfile needs to be resolved relative to Gemfile's location

### ISSUE THREAD

**Issue by janklimo** [rubygems/rubygems#7219]
### Describe the problem as clearly as you can

As outlined in [this issue](https://github.com/Shopify/vscode-ruby-lsp/issues/922), when the Gemfile defines Ruby version as follows:

```ruby
ruby file: '.ruby-version' # or .tool-versions
```

... and it's evaluated from another folder, as is the case with `ruby-lsp`, Bundler will attempt to find the provided `.ruby-version` file in the current directory and crash. See the issue above for the error trace.

### Post steps to reproduce the problem

The way I stumbled upon this was using the [Ruby LSP extension](https://marketplace.visualstudio.com/items?itemName=Shopify.ruby-lsp) in VS Code together with a Gemfile with Ruby definition as shown above. However, this should be relatively easy to replicate in a spec.

**Comment by martinemde** [comment]
@janklimo I'm closing this for now, since this should already be fixed. If you find that you're still having a problem after updating to the newest bundler, please reopen this ticket.

**Comment by janklimo** [comment]
@martinemde I updated Bundler and did some debugging since the issue remains. It appears that `#normalize_ruby_file` will still look for the file in the current folder:

```ruby
# adding a debug comment in #normalize_ruby_file when starting up VS Code
p Bundler.root.join(filename)
# => #<Pathname:/Users/jan/Work/something/.ruby-lsp/.ruby-version>
```
Just wanted to add some context, not sure if this can be fixed and in what repo.
