### ISSUE TITLE
gem login api scopes is confusing and difficult as `show_dashboard` permission invalidates the rest

### ISSUE THREAD

**Issue by schneems** [rubygems/rubygems#7238]
## Experience

When logging in to a new machine to push a rubygem I ran `gem login`. You can see the redacted output here:

```
$ gem login
Enter your RubyGems.org credentials.
Don't have an account yet? Create one at https://rubygems.org/sign_up
   Email:   <redacted>
Password:

API Key name [<redacted>]:
Please select scopes you want to enable for the API key (y/n)
index_rubygems [yN]  y
push_rubygem [yN]  y
yank_rubygem [yN]  y
add_owner [yN]  y
remove_owner [yN]  y
access_webhooks [yN]  y
show_dashboard [yN]  y

You have enabled multi-factor authentication. Please enter OTP code.
Code:   <redacted>
Show dashboard scope must be enabled exclusively
$
```
I didn't know up front that saying yes to `show_dashboard` would cause the whole process to fail and I'll have to restart. It's also the last scope on the list, so if you're saying "y" to all the rest, it's easy to accidentally press "y" too many times.

It's confusing that if you say yes to the last option that the whole process will fail. You have to repeat the whole process, and when I did this I found I accidentally made the same error. This was time consuming and annoying.

In addition I wasn't sure what the default would be for these scopes (does it default to yes or no?).

## Sketch

Possibly ask the user "Do you want to customize scopes" followed by a "Here are the scope access we will use, press "y" to continue, "n" to abort, any other input will repeat this message.

If they say they want to edit the scopes, then when `show_dashboard` is enabled, automatically disable all other scopes, preventing the user from entering in an invalid state. Possibly show them a message when they do this that explains why, ideally with a URL that we could update over time (as people will use older rubygems for a long time).

## System

```
$ gem -v
3.4.22
$ ruby -v
ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [arm64-darwin22]
```

**Comment by martinemde** [comment]
I completely agree.

**Comment by williantenfen** [comment]
I can try doing a PR for this if you don't mind...
So, after entering the API key name instead of displaying "Please select scopes you want to enable for the API key (y/n)" we should:

```
Here are the default scope access we will use:
  index_rubygems  y
  push_rubygem  n
   ...
Do you want to customize scopes? [yN] y
show_dashboard [yN] y
Show dashboard is an exclusively scope all other scopes were set to false.

You have enabled multi-factor authentication. Please enter OTP code.
Code:   <redacted>


``` 

any idea which scopes should be default enabled?

**Comment by martinemde** [comment]
Improved in #7342.
