### ISSUE TITLE
Please move vendored libraries into single directory

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#7259]
This time, I don't want to argue if bundling is the right choice. But it would be helpful, if all the bundled libraries resides in single location. In Fedora, we have to mark such bundled libraries for security reasons. But since they are not easy to distinguish, it is not easy to mark them.

**Comment by deivid-rodriguez** [comment]
We already do this for Bundler, I don't see any reason to not do it for RubyGems as well 👍.

**Comment by deivid-rodriguez** [comment]
This was recently fixed by @hsbt!
