### ISSUE TITLE
Please fix the license of the project to include information about bundled libraries

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#7260]
As far as I can tell, there is LICENSE.txt file, which claims the project to be licensed under MIT or Ruby. There is also MIT.txt. That would be reasonable.

But recently, there was bundled e.g. timeout gem and as far as I can tell, it is licensed under [BSD-2-Clause license](https://github.com/ruby/timeout/blob/master/LICENSE.txt). But this information is not provided anywhere. Maybe the [PR](https://github.com/rubygems/rubygems/pull/6793/commits/cfc5018c54ecc2e0c771ec12baded5e3f7bf5fd5#diff-ee98e028c59b193d58fde56ab4daf54d43c486ae674e63d50ddf300b07943e0fR216) was done just carelessly, because there actually is something like `subsublib.license_path = "License.txt"`. But I'm not really sure about purpose of this construct.

In any case, I don't think the license information of the project is precise anymore and therefore it should be updated. This is unfortunately one danger of bundling.

**Comment by voxik** [comment]
BTW maybe even Ruby [LEGAL](https://github.com/ruby/ruby/blob/master/LEGAL?plain=1#L873-L932) file should be updated due to this.

**Comment by deivid-rodriguez** [comment]
Maybe it was my mistake. That construct is supposed to pull the license from the vendored gem and pull it in too. I will check.

I don't know if Ruby LEGAL should be updated since this code is already vendored with Ruby. We have not ever updated it, even if we have been vendoring libraries for a while.

**Comment by voxik** [comment]
> Maybe it was my mistake. That construct is supposed to pull the license from the vendored gem and pull it in too. I will check.

Thx for the PR. Unfortunately, it does not look that the license files contain the complete information. I have opened tickets such as [this](https://github.com/ruby/uri/issues/96) all around the place.

@hsbt for the context of my tickets

Once they are resolved, there might be more action needed, depending what will be their resolution.

> I don't know if Ruby LEGAL should be updated since this code is already vendored with Ruby. We have not ever updated it, even if we have been vendoring libraries for a while.

Checking once again, it seems that in the case of Bundler, there are explicitly covered only the 3rd party dependencies, so there is probably no action needed after all. Thx for the feedback.
