### ISSUE TITLE
Different way to specify the dependencies for Automatiek

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#7262]
Trying to make sure the versions and the license information of vendored libraries is correct on Fedora side, I can't see any super easy and straight forward way to obtain the list of such libraries. The issue is that in the Rakefile, the dependencies are declared by two methods:

~~~
Automatiek::RakeTask.new("net-http-persistent") do |lib|
~~~

and the nested are specified as follows:

~~~
lib.dependency("connection_pool") do |sublib|
~~~

Would you be open to accept PR, which would replace the nested dependencies by construct such as:

~~~
lib.dependencies << Automatiek::RakeTask.new("connection_pool") do |lib|
~~~

This is what the `dependency` method does if I am not mistaken. It might be a bit wordier, OTOH I could easily grep the Rakefile for `Automatiek::RakeTask.new` and get full list of the dependencies.

**Comment by deivid-rodriguez** [comment]
I don't mind changing this in any way that helps you, as long as it keeps being helpful for us too!

**Comment by voxik** [comment]
Thx.

Looking more closely, that would need more cycles than I thought initially. I'll defer this for another day.
