### ISSUE TITLE
Bundler 2.5.0-dev installs an already-available default gem and fails to recognize it on CI

### ISSUE THREAD

**Issue by k0kubun** [rubygems/rubygems#7271]
### Describe the problem as clearly as you can

`bundle exec ruby` fails to recognize openssl.gem while `bundle installs` doesn't complain.

```
$ bundle install
Don't run Bundler as root. Installing your bundle as root will break this application for all non-root users on this machine.
Bundle complete! 7 Gemfile dependencies, 36 gems now installed.
Bundled gems are installed into `/tmp/bundle`

$ bundle exec ruby -e "require 'openssl'"
Could not find openssl-3.2.0 in locally installed gems
Run `bundle install` to install missing gems.
```

### Did you try upgrading rubygems & bundler?

Yes. We use the default gem bundler (`2.5.0-dev`) as of https://github.com/ruby/ruby/commit/a3b48ac9ad8a5d4eb7ae6c3d4fe9d040361daa7a, which is today's revision.

### Post steps to reproduce the problem

On Buildkite,

1. Prepare a Gemfile that has openssl.gem (e.g. `source "https://rubygems.org/"; gem "openssl", [">= 3.0", "< 3.3"]`)
2. `bundle config set --local path /tmp/bundle`
3. `bundle install`
    * ```
      Fetching gem metadata from https://rubygems.org/...
      Fetching openssl 3.2.0
      Installing openssl 3.2.0 with native extensions
      Bundle complete! 1 Gemfile dependency, 2 gems now installed.
      Bundled gems are installed into `/tmp/bundle
      ```
4. As of this moment, `bundle exec ruby` can find openssl.gem correctly.
5. Buildkite saves the cache of `/tmp/bundle`, which has:
    * ```
      /tmp/bundle
      /tmp/bundle/ruby
      /tmp/bundle/ruby/3.3.0+0
      /tmp/bundle/ruby/3.3.0+0/extensions
      /tmp/bundle/ruby/3.3.0+0/extensions/x86_64-linux
      /tmp/bundle/ruby/3.3.0+0/extensions/x86_64-linux/3.3.0+0-static
      /tmp/bundle/ruby/3.3.0+0/extensions/x86_64-linux/3.3.0+0-static/openssl-3.2.0
      /tmp/bundle/ruby/3.3.0+0/extensions/x86_64-linux/3.3.0+0-static/openssl-3.2.0/gem.build_complete
      /tmp/bundle/ruby/3.3.0+0/extensions/x86_64-linux/3.3.0+0-static/openssl-3.2.0/openssl.so
      /tmp/bundle/ruby/3.3.0+0/plugins
      /tmp/bundle/ruby/3.3.0+0/gems
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/LICENSE.txt
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/README.md
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/BSDL
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl/buffering.rb
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl/version.rb
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl/cipher.rb
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl/digest.rb
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl/marshal.rb
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl/ssl.rb
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl/x509.rb
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl/pkcs5.rb
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl/hmac.rb
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl/pkey.rb
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl/bn.rb
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl.rb
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl.so
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/CONTRIBUTING.md
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/ext
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/ext/openssl
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/ext/openssl/Makefile
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/ext/openssl/extconf.rb
      /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/History.md
      /tmp/bundle/ruby/3.3.0+0/build_info
      /tmp/bundle/ruby/3.3.0+0/doc
      /tmp/bundle/ruby/3.3.0+0/specifications
      /tmp/bundle/ruby/3.3.0+0/specifications/openssl-3.2.0.gemspec
      /tmp/bundle/Gemfile.lock
      /tmp/bundle/Gemfile.checksum
       ```
6. Trigger another job with this cache, do some setup (sorry, investigating which exact step is causing this problem, but it's an in-house wrapper of Bundler) which leaves:
      * ```
        /tmp/bundle
        /tmp/bundle/Gemfile.checksum
        /tmp/bundle/ruby
        /tmp/bundle/ruby/3.3.0+0
        /tmp/bundle/ruby/3.3.0+0/extensions
        /tmp/bundle/ruby/3.3.0+0/extensions/x86_64-linux
        /tmp/bundle/ruby/3.3.0+0/extensions/x86_64-linux/3.3.0+0-static
        /tmp/bundle/ruby/3.3.0+0/gems
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/LICENSE.txt
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl/buffering.rb
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl/pkey.rb
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl/version.rb
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl/marshal.rb
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl/hmac.rb
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl/digest.rb
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl/ssl.rb
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl/pkcs5.rb
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl/cipher.rb
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl/bn.rb
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl/x509.rb
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl.so
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl.rb
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/ext
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/ext/openssl
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/ext/openssl/Makefile
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/ext/openssl/extconf.rb
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/CONTRIBUTING.md
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/BSDL
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/History.md
        /tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/README.md
        /tmp/bundle/ruby/3.3.0+0/doc
        /tmp/bundle/ruby/3.3.0+0/build_info
        /tmp/bundle/ruby/3.3.0+0/plugins
        /tmp/bundle/ruby/3.3.0+0/specifications
        /tmp/bundle/ruby/3.3.0+0/specifications/openssl-3.2.0.gemspec
        /tmp/bundle/Gemfile.lock
        ```
      * Note that `/tmp/bundle/ruby/3.3.0+0/extensions/x86_64-linux/3.3.0+0-static/openssl-3.2.0/openssl.so` is somehow missing (I don't know why. Still investigating.) while `/tmp/bundle/ruby/3.3.0+0/gems/openssl-3.2.0/lib/openssl.so` is present.
7. As mentioned at the top of this description,`bundle install` succeeds, but `bundle exec ruby` fails.
      * It seems like missing `/tmp/bundle/ruby/3.3.0+0/extensions/x86_64-linux/3.3.0+0-static/openssl-3.2.0/openssl.so` causes Bundler to miss openssl, even while there's `/tmp/bundle/ruby/3.3.0+0/extensions/x86_64-linux/3.3.0+0-static/openssl-3.2.0/openssl.so` and the default gem openssl.

### Which command did you run?

`bundle install` && `bundle exec ruby -e "require 'openssl'"`

### What were you expecting to happen?

`bundle install` (re-)installs openssl.gem (or complains about missing `extensions/`), or `bundle exec ruby` finds openssl.gem correctly.

### What actually happened?

```
$ bundle install
Don't run Bundler as root. Installing your bundle as root will break this application for all non-root users on this machine.
Bundle complete! 7 Gemfile dependencies, 36 gems now installed.
Bundled gems are installed into `/tmp/bundle`

$ bundle exec ruby -e "require 'openssl'"
Could not find openssl-3.2.0 in locally installed gems
Run `bundle install` to install missing gems.
```

### If not included with the output of your command, run `bundle env` and paste the output below

<details>

## Environment

```
Bundler       2.5.0.dev
  Platforms   ruby, x86_64-linux
Ruby          3.3.0p-1 (2023-12-13 revision a3b48ac9ad8a5d4eb7ae6c3d4fe9d040361daa7a) [x86_64-linux]
  Full Path   /usr/local/ruby/bin/ruby
  Config Dir  /usr/local/ruby/etc
RubyGems      3.5.0.dev
  Gem Home    /usr/local/ruby/lib/ruby/gems/3.3.0+0
  Gem Path    /root/.local/share/gem/ruby/3.3.0+0:/usr/local/ruby/lib/ruby/gems/3.3.0+0
  User Home   /root
  User Path   /root/.local/share/gem/ruby/3.3.0+0
  Bin Dir     /usr/local/ruby/bin
Tools
  Git         2.25.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2023-12-14
Git SHA           unknown
Released Version  false
```

## Bundler settings

```
clean
  Set via BUNDLE_CLEAN: true
deployment
  Set via BUNDLE_DEPLOYMENT: true
path
  Set for your local app (/app/gems/xxx/.bundle/config): "/tmp/bundle"
  Set via BUNDLE_PATH: "/tmp/bundle"
pkgs.shopify.io
  Set for the current user (/usr/local/etc/.bundle/config): "token:[REDACTED]"
user_config
  Set via BUNDLE_USER_CONFIG: "/usr/local/etc/.bundle/config"
```

## Gemfile

### Gemfile

```ruby
source "https://rubygems.org"

gem "openssl", [">= 3.0", "< 3.3"]
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    openssl (3.2.0)

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  openssl (>= 3.0, < 3.3)

BUNDLED WITH
   2.5.0.dev
```

</details>

**Comment by k0kubun** [comment]
As of writing that, I thought Buildkite's caching was deleting the files, but reading the logs again made me realize that it was deleted when we execute our in-house wrapper of Bundler.

I'll investigate whether it's caused by our script or Bundler first.

**Comment by deivid-rodriguez** [comment]
This may be because #7266 did not yet land to ruby master branch. @hsbt is planning to port that commit soon.
