### ISSUE TITLE
manage 'access control' for gem sources

### ISSUE THREAD

**Issue by mkristian** [rubygems/rubygems#728]
I am the maintainer of nexus-ruby-support for the nexus server (http://www.sonatype.org/nexus).

since the plugin is used by some corporates with a more restrictive security policy, the request for more "control" came up:

https://github.com/sonatype/nexus-ruby-support/issues/44

but that is dealing only with gem command for uploading gems to hosted rubygems repository on nexus. since nexus comes from the maven world to manage maven artifacts the security implementation is using some ideas of how maven does it.

BUT the other side of the coin is the download. currently if rubygems needs to download from password protected site all you can do is to add the username+password into the url of the source. this is secure since you store those credentials in your home directory in **plain text**.

so I wonder if rubygems is interested in offering something similar to what I did with nexus upload https://github.com/sonatype/nexus-ruby-support/wiki/Gem-Nexus-Command

first I wanted to ask bundler as well but I just learned a few minutes ago that bundler will be "integrated" into rubygems.

if rubygems is open to such a feature I could help to integrate it - using the above implementation as starting point of a discussion on the features.

**Comment by copiousfreetime** [comment]
Checking on the interest on this, marking as abandoned  for now.
