### ISSUE TITLE
bundle install looks for public gems in private server only

### ISSUE THREAD

**Issue by pboling** [rubygems/rubygems#7327]
```
Your bundle is locked to xpath (3.2.0) from rubygems repository
https://funky.fury.site/gem/ or installed locally, but that version can
no longer be found in that source. That means the author of xpath (3.2.0) has
removed it. You'll need to update your bundle to a version other than xpath
(3.2.0) that hasn't been removed in order to install.
```

We have a single gem loaded from the private server mentioned in the error, in `:development, :test` groups:
```
  source "https://funky.fury.site/gem/" do
    gem 'funky_gem', '~> 3.1', '>= 3.1.6'
  end
```

That gem has many dozens of dependencies on public gems.  It has worked fine until recently.  Interestingly, NONE of the dependencies of that gem are `xpath`.  `xpath` was only recently added as an indirect dependency when I just added `capybara`.  It has nothing to do with the private server.

Now `bundle install` is failing, but only on CI, with the error at top.

I tried upgrading bundler, but that didn't help.

Originally:
```
BUNDLED WITH
   2.4.22
```

Now:
```
BUNDLED WITH
   2.5.3
```

**Comment by pboling** [comment]
```
group :development, :test do
  gem "xpath", "~> 3.2"

  source "https://funky.fury.site/gem/" do
    gem 'funky_gem', '~> 3.1', '>= 3.1.6'
  end
```
Explicit dependency is working!

**Comment by deivid-rodriguez** [comment]
Hei @pboling, I'd love to help here, but it's hard without a way to reproduce. Can you still reproduce this if you remove the explicit dependency? What are the logs when running with `--verbose`?

**Comment by pboling** [comment]
I was never able to reproduce it locally, and I can't justify reverting it on CI right now.  Perhaps at some point I will be able to.

**Comment by deivid-rodriguez** [comment]
Alright, let me close this now then, but please reopen if you manage to do so in the future and can provide some additional info!

**Comment by pboling** [comment]
I still don't have time to really dig into this, but I am still seeing this on CI when the Gmefile changes, at least sometimes.
```
Your bundle is locked to json-schema (4.1.1) from rubygems repository
https://vitalconnect.fury.site/gem/ or installed locally, but that version can
no longer be found in that source. That means the author of json-schema (4.1.1)
has removed it. You'll need to update your bundle to a version other than
json-schema (4.1.1) that hasn't been removed in order to install.
```
I can't debug any more than that right now, and I still expect that adding the offending gem, `json-schema`, as a discrete direct dependency to the Gemfile (in this case it is an indirect dependency from adding `rswag`) will fix it.

**Comment by deivid-rodriguez** [comment]
Just one quick question, what's the structure of sources in your Gemfile? And in your `Gemfile.lock`. Also, are you using `ruby/setup-ruby` with `bundler-cache: true`? Finally, when you say "when the Gemfile changes", I assume also the lockfile is changing? Actually, do you have a lockfile committed at all? I didn't ask that and maybe you don't!

**Comment by pboling** [comment]
1. `Gemfile` structure:
```
source 'https://rubygems.org'
# ... bunch of gems

# API
gem "jsonapi-rails", "~> 0.4", ">= 0.4.1"
gem "json-schema", "~> 4.1", ">= 4.1.1" # <============== This had to be added
gem "rswag-api", "~> 2.13"
gem "rswag-ui", "~> 2.13"

# MySQL2 AutoLoader
gem 'goldiloader'

group :development, :test do
  gem "annotate"
  gem "xpath", "~> 3.2" # <================== This had to be added

  # Dont load these gems in production
  source "https://vitalconnect.fury.site/gem/" do
    # For WI-839 Coding Standards Compliance
    gem 'vc_ruby', '~> 3.1', '>= 3.1.6'
  end

  # ... bunch more gems
end

# ... other groups

# other root gems
```
This is a decades old app running Rails 7.2 and Ruby 3.2.  Interestingly, I had `rswag` as a dependency initially, and it was fine.  Then I switched to the discrete gems way of managing it (`rswag-ui`, `rswag-api` under root, and `rswag-rspec` under development & test), and that's when `json-schema` began to fail to install, even though it must have already been an indirect dependency via the original `rswag` meta-gem.

2. Yes, the Gemfile.lock has always been committed, and it always updated when the Gemfile is changed, which is always done manually locally, and then pushed to CI.  The CI we are using is bitbucket.
