### ISSUE TITLE
`gem update --system` does not respect RubyGems constraints on current ruby

### ISSUE THREAD

**Issue by nevans** [rubygems/rubygems#7329]
### Describe the problem as clearly as you can

`gem update --system` fails on ruby 2.7, or at least on ruby 2.7 as installed by `ruby/setup-ruby`.  Specifically, this is causing CI failures for gems that still support older rubies.

See e.g: https://github.com/ruby/net-imap/actions/runs/7273131765/job/19916818198?pr=251

### Did you try upgrading RubyGems?

This is, in fact, the problem. 😉 

### Post steps to reproduce the problem

I assume this is happening for other gems supporting older versions of ruby as well.  The workflow file is fairly standard.

```yml
- name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true
        rubygems: latest
```

### Which command did you run?
```
/opt/hostedtoolcache/Ruby/2.7.8/x64/bin/gem --version
  3.1.6
  Default RubyGems version is 3.1.6
  Updating RubyGems to latest version
 
/opt/hostedtoolcache/Ruby/2.7.8/x64/bin/gem update --system
  ERROR:  Error installing rubygems-update:
  	There are no versions of rubygems-update (= 3.5.3) compatible with your Ruby & RubyGems
  	rubygems-update requires Ruby version >= 3.0.0. The current ruby version is 2.7.8.[22](https://github.com/ruby/net-imap/actions/runs/7273131765/job/19916818198?pr=251#step:3:27)5.
  ERROR:  While executing gem ... (NoMethodError)
      undefined method `version' for nil:NilClass
  Updating rubygems-update
  Took  14.85 seconds
Error: The process '/opt/hostedtoolcache/Ruby/2.7.8/x64/bin/gem' failed with exit code 1
```

### What were you expecting to happen?

The latest (compatible) version would be installed.

### What actually happened?

The command failed.

### Misc

Perhaps this is related to https://github.com/rubygems/rubygems/pull/7310?  For purposes of passing CI, the simple workaround is to set a version constraint rather than use `latest`.  Still, it would be nice if that were unnecessary. 🙂

**Comment by simi** [comment]
@nevans hello, this is known problem and could be fixed as mentioned. There is plan to make `gem update` update to latest working version, but sadly it wouldn't be able to fix this in older versions.

**Comment by deivid-rodriguez** [comment]
This was fixed by https://github.com/rubygems/rubygems/pull/4110, which was released with RubyGems 3.2.3. Unfortunately not much we can do for users of older rubies that don't come with a RubyGems version that includes the fix, but should be ok from now on since Ruby 3.0 already incles RubyGems 3.2.3.

**Comment by MSP-Greg** [comment]
This is a bug in RubyGems, but a workaround for GHA (setup-ruby) has been proposed.

See https://github.com/ruby/setup-ruby/pull/551

**Comment by deivid-rodriguez** [comment]
Good catch @MSP-Greg. Indeed there's something that can be done to workaround this in `ruby/setup-ruby`, thanks for working on that!

**Comment by simi** [comment]
> This was fixed by #4110, which was released with RubyGems 3.2.3. Unfortunately not much we can do for users of older rubies that don't come with a RubyGems version that includes the fix, but should be ok from now on since Ruby 3.0 already incles RubyGems 3.2.3.

Are you 100% sure? Per my understanding `gem update --system` doesn't use `gem install` or `gem update` internally sadly.

```
[retro@retro  tmp]❤ ruby -v
ruby 2.7.4p191 (2021-07-07 revision a21a3b7d23) [x86_64-linux]
[retro@retro  tmp]❤ gem -v
3.2.4
[retro@retro  tmp]❤ gem update --system
Updating rubygems-update
ERROR:  Error installing rubygems-update:
        rubygems-update-3.5.3 requires Ruby version >= 3.0.0. The current ruby version is 2.7.4.191.
Installing RubyGems 3.2.4
  Successfully built RubyGem
  Name: bundler
  Version: 2.2.4
  File: bundler-2.2.4.gem
Bundler 2.2.4 installed
RubyGems 3.2.4 installed
Regenerating binstubs
Regenerating plugins



------------------------------------------------------------------------------

RubyGems installed the following executables:
        /home/retro/.rubies/ruby-2.7.4/bin/gem
        /home/retro/.rubies/ruby-2.7.4/bin/bundle

RubyGems system software updated

```

**Comment by MSP-Greg** [comment]
Question - What is the likelihood of updates to RG 3.3.x and 3.4.x?

If they have patch updates, the code in setup-ruby should also be updated.  That's the 'brittle' I referred to in the PR notes.

I looked for a doc stating policy, couldn't find one. I probably missed it.  Of course, it's "maintainer's choice", but wasn't sure about backports, CVE's, etc.

**Comment by deivid-rodriguez** [comment]
You're right @simi, my bad!
