### ISSUE TITLE
Bundler in ruby 3.3.0 removes all platform variants & use ruby variant instead with `bundle install`

### ISSUE THREAD

**Issue by PikachuEXE** [rubygems/rubygems#7330]
### Describe the problem as clearly as you can

Trying to test out ruby 3.3.0 for this project
https://github.com/PikaSer-Cosmos/likecoin-chain-tx-indexer-pika
(Use commit https://github.com/PikaSer-Cosmos/likecoin-chain-tx-indexer-pika/commit/bfd28a62db6fc1138cf7d73a958e801453bd8534 as reference in case I add more updates afterward later)

After installing ruby & switching version I just run `gem update` + `bundle` and `Gemfile.lock` got updated

Bundler is at `2.5.1`

### Did you try upgrading rubygems & bundler?

`gem -v`: `3.5.3`
bundler updated to `2.5.3` on ruby `3.2.2`

If I rerun `bundle` on different ruby versions I got same result:
`3.2.2`: No change to any file
`3.3.0`: Same changes to `Gemfile.lock`

Ruby version switched via 2 terminal tabs with one `asdf shell ruby 3.3.0`
`3.3.0` installed via `ASDF_RUBY_BUILD_VERSION=master asdf install ruby 3.3.0`

They do have different platform though (coz my macOS updated)
`3.2.2` `gem environment`
```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.5.3
  - RUBY VERSION: 3.2.2 (2023-03-30 patchlevel 53) [arm64-darwin21]
  - INSTALLATION DIRECTORY: /Users/pikachuexe/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0
  - USER INSTALLATION DIRECTORY: /Users/pikachuexe/.gem/ruby/3.2.0
  - RUBY EXECUTABLE: /Users/pikachuexe/.asdf/installs/ruby/3.2.2/bin/ruby
  - GIT EXECUTABLE: /opt/homebrew/bin/git
  - EXECUTABLE DIRECTORY: /Users/pikachuexe/.asdf/installs/ruby/3.2.2/bin
  - SPEC CACHE DIRECTORY: /Users/pikachuexe/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/pikachuexe/.asdf/installs/ruby/3.2.2/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - arm64-darwin-21
  - GEM PATHS:
     - /Users/pikachuexe/.asdf/installs/ruby/3.2.2/lib/ruby/gems/3.2.0
     - /Users/pikachuexe/.gem/ruby/3.2.0
```

`3.3.0` `gem environment`
```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.5.3
  - RUBY VERSION: 3.3.0 (2023-12-25 patchlevel 0) [arm64-darwin22]
  - INSTALLATION DIRECTORY: /Users/pikachuexe/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0
  - USER INSTALLATION DIRECTORY: /Users/pikachuexe/.gem/ruby/3.3.0
  - RUBY EXECUTABLE: /Users/pikachuexe/.asdf/installs/ruby/3.3.0/bin/ruby
  - GIT EXECUTABLE: /opt/homebrew/bin/git
  - EXECUTABLE DIRECTORY: /Users/pikachuexe/.asdf/installs/ruby/3.3.0/bin
  - SPEC CACHE DIRECTORY: /Users/pikachuexe/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/pikachuexe/.asdf/installs/ruby/3.3.0/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - arm64-darwin-22
  - GEM PATHS:
     - /Users/pikachuexe/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0
     - /Users/pikachuexe/.gem/ruby/3.3.0
```

### Post steps to reproduce the problem
Apple M1 Pro
macOS `13.6.3 (22G436)`
https://github.com/asdf-vm/asdf-ruby
`bundle config` is empty
`rubygems are configured`
```
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
     - "gem" => "--no-document"
```

Use the project/commit above to reproduce

### Which command did you run?

`bundle`

### What were you expecting to happen?

No change to `Gemfile.lock`

### What actually happened?

![image](https://github.com/rubygems/rubygems/assets/1018543/c76dc355-13bb-48ce-9664-1bf8f93a388c)

### If not included with the output of your command, run `bundle env` and paste the output below

Removed content of `Gemfile` coz already in linked project
```
## Environment

Bundler       2.5.3
  Platforms   ruby, arm64-darwin-22
Ruby          3.3.0p0 (2023-12-25 revision 5124f9ac7513eb590c37717337c430cb93caa151) [arm64-darwin-22]
  Full Path   /Users/pikachuexe/.asdf/installs/ruby/3.3.0/bin/ruby
  Config Dir  /Users/pikachuexe/.asdf/installs/ruby/3.3.0/etc
RubyGems      3.5.3
  Gem Home    /Users/pikachuexe/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0
  Gem Path    /Users/pikachuexe/.gem/ruby/3.3.0:/Users/pikachuexe/.asdf/installs/ruby/3.3.0/lib/ruby/gems/3.3.0
  User Home   /Users/pikachuexe
  User Path   /Users/pikachuexe/.gem/ruby/3.3.0
  Bin Dir     /Users/pikachuexe/.asdf/installs/ruby/3.3.0/bin
Tools
  Git         2.43.0
  RVM         not installed
  rbenv       not installed
  chruby      not installed


## Bundler Build Metadata

Built At          2023-12-25
Git SHA           unknown
Released Version  false

```

**Comment by flavorjones** [comment]
This is because the gem in question does not yet ship a precompiled native extension.

**Comment by PikachuEXE** [comment]
Thanks for replying

I did check `nokogiri` `1.15.5`
https://rubygems.org/gems/nokogiri/versions

The versions on `Gemfile.lock` are still there (they are not ruby version specific right?)
- https://rubygems.org/gems/nokogiri/versions/1.15.5-arm64-darwin
- https://rubygems.org/gems/nokogiri/versions/1.15.5-aarch64-linux
- https://rubygems.org/gems/nokogiri/versions/1.15.5-x86-linux

Similar for `google-protobuf`
https://rubygems.org/gems/google-protobuf/versions

Please let me know if I misunderstand `the gem in question does not yet ship a precompiled native extension` or I got anything wrong thx

**Comment by MSP-Greg** [comment]
google-protobuf is at:
https://rubygems.org/gems/google-protobuf/versions/3.25.1-arm64-darwin

Note that both Nokogiri & google-protobuf have 'REQUIRED RUBY VERSION' shown as `>= 2.7, < 3.3.DEV` on the rubygems.org pages.

Hence, both cannot be installed using Ruby 3.3.0.  RubyGems switches to the 'ruby variant', as many gems do not put a constraint/limit on the upper Ruby version.  They may not work regardless, as it depends on Ruby ABI changes.

**Comment by flavorjones** [comment]
@PikachuEXE precompiling native extensions REQUIRES known ruby versions. Since ruby 3.3 was just released, please expect that there will be a delay before maintainers will be able to ship.

In the meantime, please do compile your dependencies from source (the "ruby" platform gem). Once the precompiled extensions are available, you should be able to "bundle update" and pull in the latest supported versions.

**Comment by PikachuEXE** [comment]
Thanks
Glad to know it's not an issue on bundler/rubygems side

 (Saw some `platform` related note in recent releases so I suspect issue here first)
