### ISSUE TITLE
`Bundler.with_original_env` not resetting to original value when ENV is an empty string

### ISSUE THREAD

**Issue by Edouard-chin** [rubygems/rubygems#7365]
### Describe the problem as clearly as you can

When a Bundler related ENV variable is an empty string, calling `Bundler.with_original_env` doesn't reset it to an empty string. This is especially problematic for the `RUBYOPT` varible and causes issues down the line when one try to invoke bundler from a subprocess. Chruby sets `RUBYOPT` to an [empty string](https://github.com/postmodern/chruby/blob/a543a35790e5528b5a67de20e78a7390f5f7606e/share/chruby/chruby.sh#L43) by default.

### Reproduction steps

```sh
cat > Gemfile << EOF
  source "https://rubygems.org"
EOF

cat > bug.rb << EOF
  require "bundler"

  File.open("Gemfile", "a") do |f|
    f.write("gem 'warning'")
  end

  Bundler.with_original_env do
    system("bundle install")
  end
EOF

RUBYOPT="" bundle exec ruby bug.rb
# Fails:
# Could not find gem 'warning' in locally installed gems.
# Run `/Users/edouard/.gem/ruby/3.3.0/gems/bundler-2.5.4/exe/bundle install` to install missing gems.
```

### Real case scenario

The real case scenario is when a user using chruby uses the `rails new` command. The installation process on Rails looks something like:

1. Rails generate some files, run bundler and all is good until here.
2. Rails configure the new application, and run some rake tasks that modify the Gemfile and finally re-call `bundle install`.
3. This is where the installation stops as running a bundler command in a subprocess fails. This is due to the `RUBYOPT` env variable not being reset to an empty string and instead is set to `-rbundler/setup` which ends up trying to activate the specs from the Gemfile before we even get a chance to install them.

### Git archaeology

In case this can help, this behaviour seems to be intentional https://github.com/rubygems/rubygems/blob/8ffa73df3a250623b13c5bf7ab48ed8b8e84e46f/bundler/spec/bundler/environment_preserver_spec.rb#L71-L77 , however is was [originally added](https://github.com/rubygems/rubygems/commit/6fe7cbac9e8ec9bfbca8460b42e96a3130ce02ea) to preserve the `GEM_PATH` (and later on the `PATH`).

This was later on refactored in https://github.com/rubygems/rubygems/commit/967670f4a9342e1032277e94ec4574217eb240c7, and ultimately all ENV variables would be included for that behaviour.

**Comment by Edouard-chin** [comment]
Sorry, misclicked, haven't finished to write the bug report. Will reopen in a few.

**Comment by Edouard-chin** [comment]
Should be good now. Thank you!

**Comment by deivid-rodriguez** [comment]
Thanks for the investigation!

This seems like a bug to me, and looking at the history you provided it's unclear to me why empty was special cased... 🤔.

Fixing this does not seem to break anything obvious: #7383.

**Comment by deivid-rodriguez** [comment]
Yeah, I did similar experiments but couldn't find any breakage either 🤷‍♂️. I guess let's try and find out!
