### ISSUE TITLE
RubyGems attempts to activate multiple versions of net-http

### ISSUE THREAD

**Issue by stanhu** [rubygems/rubygems#7374]
### Describe the problem as clearly as you can

With the addition of the `net-http` dependency in https://github.com/lostisland/faraday-net_http/pull/31 and release of `faraday-net_http`, our build pipelines started to fail with this error:

```
/usr/local/lib/ruby/3.1.0/rubygems/specification.rb:2284:in `check_version_conflict': can't activate net-http-0.1.1, already activated net-http-0.3.0 (Gem::LoadError)
	from /usr/local/lib/ruby/3.1.0/rubygems/specification.rb:1421:in `activate'
	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:119:in `block in require'
	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:118:in `each'
	from <internal:/usr/local/lib/ruby/3.1.0/rubygems/core_ext/kernel_require.rb>:118:in `require'
```

### Did you try upgrading RubyGems?

Yes.

### Post steps to reproduce the problem

I've distilled the failure into these steps:

1. First, create this `Gemfile`:

```ruby
source 'https://rubygems.org'

source 'https://packagecloud.io/cinc-project/stable' do
  gem 'chef', '~> 17.10.95'
  gem 'chef-utils', '= 17.10.95'
end

gem 'faraday', '1.10.3'
```

2. Then run:

```shell
docker run -it -v $(pwd):/build ruby:3.1 bash
cd /build
gem install net-http:0.1.1 faraday
bundle install
ruby -r "chef" -r 'net/http' -e "puts 1"
```

In this example, we have multiple versions of `net-http` and `faraday` installed:

```
# gem list net-http faraday

*** LOCAL GEMS ***

net-http (default: 0.3.0, 0.1.1)

*** LOCAL GEMS ***

faraday (2.9.0, 1.10.3)
faraday-em_http (1.0.0)
faraday-em_synchrony (1.0.0)
faraday-excon (1.1.0)
faraday-follow_redirects (0.3.0)
faraday-httpclient (1.0.1)
faraday-multipart (1.0.4)
faraday-net_http (3.1.0, 1.0.1)
faraday-net_http_persistent (1.2.0)
faraday-patron (1.0.0)
faraday-rack (1.0.0)
faraday-retry (1.0.3)
```

I see two attempts to require `net/http`:

1. https://github.com/rubygems/rubygems/blob/8ffa73df3a250623b13c5bf7ab48ed8b8e84e46f/lib/rubygems/core_ext/kernel_require.rb#L60
2. https://github.com/rubygems/rubygems/blob/8ffa73df3a250623b13c5bf7ab48ed8b8e84e46f/lib/rubygems/core_ext/kernel_require.rb#L98

On the second attempt, RubyGems attempts to load `net-http` 0.1.1 instead of 0.3.0, and this is where it fails.

When `require 'chef'` runs above, it pulls in a number of other `require` statements, but there are a few unresolved dependencies (i.e. those that don't have an explicit `require`):

* `rexml`
* `faraday`

The first `require 'net/http'` seems to pull in 0.3.0 just fine.

However, in the second attempt, for each unresolved dependency, RubyGems attempts to [traverse the dependency tree in reverse](https://github.com/rubygems/rubygems/blob/v3.2.26/lib/rubygems/specification.rb#L2545-L2572) and activate them automatically **if the dependency includes `net/http` in the path**. For `faraday`, this means it will attempt to load `net-http` -> `faraday-net_http` -> `faraday`.

To do this, it tries to find all the gemspecs that satisfy the requirement: https://github.com/rubygems/rubygems/blob/8ffa73df3a250623b13c5bf7ab48ed8b8e84e46f/lib/rubygems/specification.rb#L2618

For `net-http`, this means that both 0.3.0 and 0.1.1 match: https://github.com/rubygems/rubygems/blob/8ffa73df3a250623b13c5bf7ab48ed8b8e84e46f/lib/rubygems/dependency.rb#L275-L282

If bundler were used, only one would matching gem.

It appears that for some reason, while recursively building up the trail, RubyGems constructs multiple paths for `net-http` -> `faraday-net_http` -> `faraday`. One includes `net-http` 0.3.0, and another includes `net-http` 0.1.1.

### Which command did you run?

See above. Running `ruby -r "chef" -r 'net/http' -e "puts 1"` results in the error.

### What were you expecting to happen?

No error. I would expect RubyGems to load only one version of `net-http`, but maybe this use case is why Bundler is needed.

### What actually happened?

See above. We can use `bundler` or use different paths to install gems, but it was quite a surprise that this simple dependency change broke in this way.

### Run `gem env` and paste the output below

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.5.4
  - RUBY VERSION: 3.1.4 (2023-03-30 patchlevel 223) [aarch64-linux]
  - INSTALLATION DIRECTORY: /usr/local/bundle
  - USER INSTALLATION DIRECTORY: /root/.local/share/gem/ruby/3.1.0
  - RUBY EXECUTABLE: /usr/local/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /usr/local/bundle/bin
  - SPEC CACHE DIRECTORY: /root/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /usr/local/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - aarch64-linux
  - GEM PATHS:
     - /usr/local/bundle
     - /root/.local/share/gem/ruby/3.1.0
     - /usr/local/lib/ruby/gems/3.1.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
     - "install" => "--no-document"
     - "update" => "--no-document"
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /usr/local/bundle/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
```

**Comment by deivid-rodriguez** [comment]
Thanks for the clean report!

It took me a while to figure it out, but I think #7379 should address it. Still working on a proper test and just opened a WIP PR to check with CI.

The culprit was [this guy](https://github.com/chef/chef/blob/4d66a5dc552a37f856dc59516a31d629d44a4769/lib/chef/http.rb#L29), plus a bunch of other conditions that I'm trying to simulate in a test.

**Comment by stanhu** [comment]
@deivid-rodriguez Thanks so much!

**Comment by deivid-rodriguez** [comment]
I think I got a proper fix with regression test now!
