### ISSUE TITLE
Patch: Manual Page Support

### ISSUE THREAD

**Issue by michaeledgar** [rubygems/rubygems#74]
This patch adds support for manual page installation to RubyGems. 
# FEATURES

Manfiles can be:
    explicitly specified in the specification (via the array attribute :manual_pages)
    implicitly discovered in the man/ directory of a gem.

Implicitly discovered manfiles are only installed if they have a filename acceptable as a manfile (.1, .2, ... .8, .9,
.n, .l) OR if they contain required groff macros for manfiles.

Manfiles are installed and updated with the install/update commands. There is an option for these (in the install/update
section) :install_manual, which defaults to false if you are windows, and true otherwise.

Manfiles are removed during the uninstall command.

Currently manfiles are installed into /usr/share/man/ . Since this requires superuser permissions, gems
installed/updated/removed without "sudo" will print a friendly message explaining that their manuals were
not affected. Installation will still succeed.

Lastly, all manuals installed by the rubygems extension are "watermarked" - a small comment is put at the
top of the manfile saying it was installed by Rubygems. No manual files will ever be deleted unless they have that watermark,
preventing a maliciously crafted gem from removing crucial built-in manfiles.

24 tests containing a total of 40 assertions are included. Every method in the "manual manager" is covered.

**Comment by voxik** [comment]
As a Ruby maintainer in Fedora/RHEL, I'd love to see this supported as well.

@michaeledgar do you have the original patch somewhere around?
