### ISSUE TITLE
Bundle outdated's exit status is always 1, even when outdated gems are filtered out when filtering on groups

### ISSUE THREAD

**Issue by gee-forr** [rubygems/rubygems#7425]
### The problem

I'd like to start using `bundle outdated --only-explicit` in my CI pipelines to warn when our gems are getting outdated.

The problem is, if there are outdated gems and they're filtered out, the exit status is still 1, when I would expect it to be 0.

I've taken a look at the `lib/cli/outdated.rb` code and believe I can fix this issue, and I'm happy to push a PR if you believe this is a valid bug?

## Did you try upgrading rubygems & bundler?

This bug is present in the latest version of bundler, and the latest version of the code here on github.

## Post steps to reproduce the problem

Use this gemfile:

```ruby
source 'https://rubygems.org'

# the foo group is necessary for triggering this bug
group :foo do
  gem 'shoulda-matchers',   '~> 5.3.0'
end
```

Run these commands:

1. This should show the outdated gem, and exit with a status of 1

```shell
bundle outdated --only-explicit --group foo
```

2. This **should** show `No minor updates to display.` and return with an exit status of 0, but instead shows the output header, and exits with a status of 1

```shell
bundle outdated --only-explicit  --group foo --filter-minor
```

### Which command did you run?

`bundle outdated --only-explicit --filter-minor --filter-patch --group foo` on a Gemfile with no minor or patch version updates available

### What were you expecting to happen?

I was expecting `bundle outdated` to exit with a status of 0

### What actually happened?

It exits with a status of 1

**Comment by indirect** [comment]
That sounds like a valid bug to me! Happy to get a PR to fix it.

**Comment by deivid-rodriguez** [comment]
Agreed!

**Comment by gee-forr** [comment]
> That sounds like a valid bug to me! Happy to get a PR to fix it.

Excellent news! I'll put something together when I've got a gap this week.

**Comment by deivid-rodriguez** [comment]
@gee-forr Still interested in contributing this? Any help needed?

**Comment by gee-forr** [comment]
> @gee-forr Still interested in contributing this? Any help needed?

Hey @deivid-rodriguez - Yeah - I still 100% plan on issuing a PR. I've just had an intense few 2024 in terms of work commitments. As soon as my work load subsides a little, I'll have some time to issue a fix.

Apologies for the wait.

**Comment by deivid-rodriguez** [comment]
Hi @gee-forr, another user reported this same issue, so I ended up fixing this myself at #8052.

**Comment by gee-forr** [comment]
@deivid-rodriguez - ah crap - sorry man... I completely forgot about this. I've had a crazy year. Thanks for resolving this. I appreciate it.
