### ISSUE TITLE
Error: Incompatible Library Version for Psych Gem in RubyGems/Bundler

### ISSUE THREAD

**Issue by GhostEsso** [rubygems/rubygems#7444]

**Comment by MarchandMD** [comment]
@GhostEsso How did you resolve this?

**Comment by MarchandMD** [comment]
thanks @GhostEsso Turns out I had a random `/.gem` directory somewhere it shouldn't be. 

After removing that useless directory, and removing all non-system versions of ruby, and reisntalling rbenv, things are back to normal.

**Comment by GhostEsso** [comment]
@MarchandMD Thanks Boss 🙏🏽
