### ISSUE TITLE
Issue cloning a git repo with a tag that includes a message

### ISSUE THREAD

**Issue by odarriba** [rubygems/rubygems#7459]
### Describe the problem as clearly as you can

We have an internal gem that we fetch from out git repository using tags.

We do not usually put messages on tags, but from time to time we add some important information on them.

We have faced an issues that, after updating bundler to the latest version available for Ruby < 3.0.0 (Bundler 2.4.22).

### Did you try upgrading rubygems & bundler?

<We have upgraded until the latest version supported by Ruby 2.7.x - Bundler 2.4.22

### Post steps to reproduce the problem

Our current scenario is:
- We deploy using Capistrano
- The previous deployment was on a revision that was not using a tag of that dependency repo with a commit message.
- The current deployment is using a tag with a commit message of that dependency repo.

When we run the deployment, it fails with a message:
```
Server does not allow request for unadvertised object
```

As far as we could see this is what it's happening:
1. When you create a tag with a commit message, a new object is created on the repo to store that message, and it has its own SHA.
2. Bundler uses that SHA as the SHA of the tag, instead of using the SHA of the latest commit tha tag is pointing to
3. We are facing the issue solved in https://github.com/rubygems/rubygems/pull/7114 but as we are not using a `ref` the solution does not apply to our use case.

#### Ways to fix it manually

We could circle the issue in two ways:
- Rolling back bundler to a previous version in which the breaking change was not introduced (we rolled back to the `2.3.x` series)
- Updating `git` (which forces us to use an external repo or compile it)

And after any of thos two ways, we also need to delete the previously cached version of the repository in the `bundler` directory forcing to download it again

### Which command did you run?

`bundle install`

### What were you expecting to happen?

Have the dependencies installed as in my local system and in older versions of bundler

### What actually happened?

When we run the deployment, it fails with a message:
```
Server does not allow request for unadvertised object
```

#### Environment

```
Bundler       2.4.22
  Platforms   ruby, x86_64-linux
Ruby          2.7.7p221 (2022-11-24 revision 168ec2b1e5ad0e4688e963d9de019557c78feed9) [x86_64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.2.8
  Gem Home    /usr/local/lib/ruby/gems/2.7.0
  Gem Path    /home/ubuntu/.local/share/gem/ruby/2.7.0:/usr/local/lib/ruby/gems/2.7.0
  User Home   /home/ubuntu
  User Path   /home/ubuntu/.local/share/gem/ruby/2.7.0
  Bin Dir     /usr/local/bin
Tools
  Git         2.25.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

#### Bundler Build Metadata

```
Built At          2023-11-09
Git SHA           ec2089640
Released Version  true
```

**Comment by deivid-rodriguez** [comment]
Hei @odarriba. Sorry for not replying earlier. Can you create a sample repo showing the issue? You said it's the same issue as https://github.com/rubygems/rubygems/pull/7114, but that affected git's under 2.13.7 and you seem to be using 2.25.1?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback, feel free to reopen if you can provide requested info!
