### ISSUE TITLE
Make lib copy of .so file optional

### ISSUE THREAD

**Issue by voxik** [rubygems/rubygems#749]
Since 4b001a8aa, you keep copies of .so files on their old location.

First of all, I don't think making exception due to one library is good idea and to my knowledge, neither one of gems we have in Fedora (500+ [1]) suffers by this symptom. If there was some, we would need to deal with it already. Not to mention that msgpack is already fixed.

Secondly, this exception completely defy the purpose of platform specific extensions in separated directory, since the libraries will conflict, as they used to. You making exception on the other side and you soon will face anger why shared extensions does not work.

If neither of these two points convinced you, would you mind at least to make this behavior optional with some tiny secrete option, environment variable, overridable by operating_system.rb or something similar, which will be accompanied with big warning that this is just temporary stuff?

It would help us who are packaging gems for Fedora. I'd love to avoid suggesting for this version of Rubygems "in addition, you have to delete all .so files which are somewhere in lib directory of the gem."

[1] https://koji.fedoraproject.org/koji/search?match=glob&type=package&terms=rubygem*

**Comment by anatol** [comment]
`install_extension_in_lib` return value is still `true`. Maybe it is time to make it `false` and stop installing so files into `lib/` by default?
