### ISSUE TITLE
`vendor_gem` receives a block (all in test code)

### ISSUE THREAD

**Issue by ko1** [rubygems/rubygems#7493]
### Describe the problem as clearly as you can

https://github.com/rubygems/rubygems/blob/1aa7252b4acd4e959023b3159756ce542aaa1228/test/rubygems/helper.rb#L1366
The method `vendor_gem` doesn't use a block (yield and so on) but https://github.com/rubygems/rubygems/blob/1aa7252b4acd4e959023b3159756ce542aaa1228/test/rubygems/test_gem_request_set.rb#L452 passes a block for this method.

Is it intentional?

This issue was found by the trial of https://bugs.ruby-lang.org/issues/15554#change-107064

**Comment by hsbt** [comment]
It may be not intentional. I think it might be confusing them with `quick_gem`.

https://github.com/rubygems/rubygems/blob/1aa7252b4acd4e959023b3159756ce542aaa1228/test/rubygems/helper.rb#L709

**Comment by simi** [comment]
You're right @ko1. This test passes also with no block passed to vendor gem in `test_gem_request_set.rb` and block is never called. This test was added at https://github.com/rubygems/rubygems/commit/b68361e9460dd4b5c40520bf3db1be59f91275e7 and at the time `vendor_gem` supported block until https://github.com/rubygems/rubygems/commit/3b7d8d09d9cad78f51bc80ffb6bc2172bb9b5d7d. This can be fixed by passing block again, but since the related test is passing even without the block evaluated, maybe block can be removed from test. :thinking:

**Comment by martinemde** [comment]
I made a quick fix that passes the block from vendor_gem to `save_gemspec`. We can also remove the block. Switch to quick_gem fails the test.

**Comment by simi** [comment]
I would say remove the block, since it is useless in that test. :thinking:

**Comment by martinemde** [comment]
I wonder if the test is broken. It says it resolves a vendored gem, but it doesn't read gemspec and gem deps.

Is the test supposed to work if I remove "b" from the deps and rely on the dependency in "a" to load it? If so, it's broken.

**Comment by martinemde** [comment]
Oh, this is interesting. With the dependency we actually see a failure on truffleruby.

```
  Gem::DependencyResolutionError: conflicting dependencies b (~> 2.0) and b (>= 0)
    Activated b-2
    which does not match conflicting dependency (~> 2.0)
  
    Conflicting dependency chains:
      b (>= 0), 2 activated
  
    versus:
      a (>= 0), 1 activated, depends on
      b (~> 2.0)
  
/home/runner/work/rubygems/rubygems/lib/rubygems/resolver.rb:189:in `resolve'
/home/runner/work/rubygems/rubygems/lib/rubygems/request_set.rb:413:in `resolve'
/home/runner/work/rubygems/rubygems/test/rubygems/test_gem_request_set.rb:473:in `test_resolve_vendor'
     470:     end
     471:     tf.close!
     472: 
  => 473:     res = rs.resolve
     474:     assert_equal 2, res.size
     475: 
     476:     names = res.map(&:full_name).sort
```

**Comment by deivid-rodriguez** [comment]
This was fixed by https://github.com/rubygems/rubygems/pull/7537. The ruby-core change uncovered a problem in RubyGems so seems like a good move!
