### ISSUE TITLE
`bundle plugin install` need `--path` argument

### ISSUE THREAD

**Issue by Whirlwind** [rubygems/rubygems#7504]
In the document (https://bundler.io/guides/bundler_plugins.html#install-a-plugin-from-your-gemfile), there are two ways to install a plugin: `from a command` or `from your Gemfile`.

> Install a plugin from your Gemfile
```
plugin 'my_plugin', path: '/path/to/plugin' # Installs from a path
```

But, there is not a `--path` argument for `bundle plugin install`.

The doc said:
> 6. Running your plugin locally
> 
> To install and run your plugin locally, you can run bundler plugin install --git '/PATH/TO/GEM' copycat

But my plugin directory is not a git repository....

**Comment by deivid-rodriguez** [comment]
This will get fixed by https://github.com/rubygems/rubygems/pull/6960!
