### ISSUE TITLE
code coverage not reflecting in sonar cloud 

### ISSUE THREAD

**Issue by Prabhudevg92** [rubygems/rubygems#7513]
I am running a dot net project in azure devops to generate the code coverage results in sonar cloud.

I have used the dotnet test task to generate the trx file as follows

- task: DotNetCoreCLI@2
  displayName: 'Backend Test'
  inputs:
    command: custom
    projects: '**/*Tests/*.csproj'
    custom: test
    arguments: '--configuration $(buildConfiguration)  --logger trx --collect "Code Coverage"'
  continueOnError: true

- task: PublishTestResults@2
  displayName: 'Publish test  results'
  inputs:
    testResultsFormat: VSTest
    testResultsFiles: '**/*.trx'
    publishRunAttachments: false
  condition: always()

- task: PublishCodeCoverageResults@1
  displayName: 'Publish code coverage'
  inputs:
    codeCoverageTool: Cobertura
    summaryFileLocation: '$(Build.SourcesDirectory)/**/*.xml'
  continueOnError: true

not able to see code coverage reflecting in devops and sonar cloud even after above  tasks.

![Screenshot 2024-03-13 at 3 09 51 AM](https://github.com/rubygems/rubygems/assets/138769434/c1113622-82da-4926-accb-8d1568bebd2e)

![Screenshot 2024-03-13 at 3 12 50 AM](https://github.com/rubygems/rubygems/assets/138769434/6957ec26-0fa9-4969-a0c8-0a3ed4bae865)

**Comment by hsbt** [comment]
It seems to not relate rubygems or bundler.
