### ISSUE TITLE
ERROR: While executing gem ... (Gem::RemoteFetcher::FetchError) SSL_connect returned=1 errno=0 state=error: EC lib

### ISSUE THREAD

**Issue by Nihal-Bstack** [rubygems/rubygems#7522]
### After installing ruby 2.6.6, using rbenv on my Mac
I ran command ```gem update --system 2.7.6"
but getting this error

ERROR:  While executing gem ... (Gem::RemoteFetcher::FetchError)
    SSL_connect returned=1 errno=0 state=error: EC lib (https://rubygems.org/specs.4.8.gz)

output of ```gem env```

RubyGems Environment:
  - RUBYGEMS VERSION: 3.0.3
  - RUBY VERSION: 2.6.6 (2020-03-31 patchlevel 146) [-darwin23]
  - INSTALLATION DIRECTORY: /Users/nihalpandey/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0
  - USER INSTALLATION DIRECTORY: /Users/nihalpandey/.gem/ruby/2.6.0
  - RUBY EXECUTABLE: /Users/nihalpandey/.rbenv/versions/2.6.6/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /Users/nihalpandey/.rbenv/versions/2.6.6/bin
  - SPEC CACHE DIRECTORY: /Users/nihalpandey/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /Users/nihalpandey/.rbenv/versions/2.6.6/etc
  - RUBYGEMS PLATFORMS:
    - ruby
    - -darwin-23
  - GEM PATHS:
     - /Users/nihalpandey/.rbenv/versions/2.6.6/lib/ruby/gems/2.6.0
     - /Users/nihalpandey/.gem/ruby/2.6.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => false
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /Users/nihalpandey/.rbenv/versions/2.6.6/bin
     - /opt/homebrew/Cellar/rbenv/1.2.0/libexec
     - /opt/homebrew/opt/openssl@1.0/bin
     - /Users/nihalpandey/.rbenv/shims
     - /opt/homebrew/bin
     - /opt/homebrew/sbin
     - /usr/local/bin
     - /System/Cryptexes/App/usr/bin
     - /usr/bin
     - /bin
     - /usr/sbin
     - /sbin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/local/bin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/bin
     - /var/run/com.apple.security.cryptexd/codex.system/bootstrap/usr/appleinternal/bin

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.
