### ISSUE TITLE
bundler/inline changes ENV keys to upper case

### ISSUE THREAD

**Issue by rzllmr** [rubygems/rubygems#7530]
### Describe the problem as clearly as you can

After the call to `gemfile do ... end` of _bundler/inline_ the keys of `ENV` are all changed to only upper case characters. This problem I found only with a Windows PC, not on a Mac.

### Did you try upgrading rubygems & bundler?

Yes, I upgraded to the latest available versions.

### Post steps to reproduce the problem

The context for my tests was as follows:
* Windows 10 Build 19045
* Ruby 3.2.2 from [rubyinstaller-devkit-3.2.2-1-x64.exe](https://github.com/oneclick/rubyinstaller2/releases/download/RubyInstaller-3.2.1-1/rubyinstaller-devkit-3.2.1-1-x64.exe)
* Bundler 2.5.7
* Rubygems 3.5.7

### Which command did you run?

``` Ruby
require 'bundler/inline'

ENV['Test_Variable'] = 'value string'
puts("before: #{ENV.each_key.select { |key| key.match?(/test_variable/i) }}")

gemfile do
  # pass
end

puts("after: #{ENV.each_key.select { |key| key.match?(/test_variable/i) }}")
```

Printing all key-value-pairs of ENV also shows that all keys are changed to upper case.

### What were you expecting to happen?

The output should be:
```
before: ["Test_Variable"]
after: ["Test_Variable"]
```

### What actually happened?

The output I've got was:
```
before: ["Test_Variable"]
after: ["TEST_VARIABLE"]
```

#### Environment

```
Bundler       2.5.7
  Platforms   ruby, x64-mingw-ucrt
Ruby          3.2.2p53 (2023-03-30 revision e51014f9c05aa65cbf203442d37fef7c12390015) [x64-mingw-ucrt]
  Full Path   C:/Develop/Ruby32-x64/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.5.7
  Gem Home    C:/Develop/Ruby32-x64/lib/ruby/gems/3.2.0
  Gem Path    C:/Users/<user-name>/.gem/ruby/3.2.0;C:/Develop/Ruby32-x64/lib/ruby/gems/3.2.0
  User Home   C:/Users/<user-name>
  User Path   C:/Users/<user-name>/.gem/ruby/3.2.0
  Bin Dir     C:/Develop/Ruby32-x64/bin
Tools
  Git         2.27.0.windows.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

#### Bundler Build Metadata

```
Built At          2024-03-22
Git SHA           199531f621
Released Version  true
```

**Comment by deivid-rodriguez** [comment]
Thanks for the report @rzllmr. I think #7574 should fix this!

**Comment by rzllmr** [comment]
That's great, thanks a lot @deivid-rodriguez!
