### ISSUE TITLE
problem with jekyllrb.com/tutorials/using-jekyll-with-bundler/

### ISSUE THREAD

**Issue by ledlightjungledStefan** [rubygems/rubygems#7550]
![template_screenprint_copy](https://github.com/rubygems/rubygems/assets/75255909/84171fbe-d373-4013-a268-94fe2f01254e)

With the command line bundle config set --local path 'vendor/bundle' only a .bundle folder was created.

bundle add jekyll was the last command line

### Describe the problem as clearly as you can

I have been reading and trying to Using Jekyll with Bundler.
The last commadn bevore i started was git status from the site https://gitimmersion.com/lab_04.html
I have the output On branch stacktemplateword.
I have not gcc g++ and make.

### Did you try upgrading rubygems & bundler?

ok but it can also be that the template folder should not be used with a .git folder or not?

![it is a git repo](https://github.com/rubygems/rubygems/assets/75255909/262f4c63-ca59-4479-a926-3a11e0d71b04)

### Which command did you run?

last_commands see below

### What were you expecting to happen?

Create A Jekyll Scaffold

### What actually happened?

![last_commands-ERROR](https://github.com/rubygems/rubygems/assets/75255909/9b340b59-41e0-45c8-b1e9-9a8f52e7cd5c)

### If not included with the output of your command, run `bundle env` and paste the output below

![bundle environment protocol](https://github.com/rubygems/rubygems/assets/75255909/f411470a-64a8-4b7f-a634-52b71e408cdc)

**Comment by hsbt** [comment]
It's not RubyGems/Bundler issues. You should check your development environment.
