### ISSUE TITLE
Bundle install errors (9 errors) see attached log file

### ISSUE THREAD

**Issue by Tom-H2oThermo** [rubygems/rubygems#7593]
[6_Build And Deploy.txt](https://github.com/rubygems/rubygems/files/15048971/6_Build.And.Deploy.txt)
[azure-static-web-apps-xxxx.txt](https://github.com/rubygems/rubygems/files/15048972/azure-static-web-apps-xxxx.txt)
[bundle install error.txt](https://github.com/rubygems/rubygems/files/15048973/bundle.install.error.txt)
[gem list.txt](https://github.com/rubygems/rubygems/files/15048974/gem.list.txt)
[mkmf.log](https://github.com/rubygems/rubygems/files/15048975/mkmf.log)
[Bundle Check.txt](https://github.com/rubygems/rubygems/files/15052474/Bundle.Check.txt)
[Gem environment.txt](https://github.com/rubygems/rubygems/files/15052475/Gem.environment.txt)

I'm getting  numerous errors when I run "bundler install".  I've attached a file of the results from when I run this (bundle install error.txt), the mkmf.log file, and a file that lists my gems.  This issue started when I was switching from hosting my Jekyll static site from GitHub pages to Azure, when the workflow failed.  I was getting an error of conflicting dependencies so I tried deleting my gemfile.lock and running "bundler install" hoping that might help.  I've attached the workflow "6_Build And Deploy.txt" file which down near the bottom it lists the conflicting dependencies and a text file of the azure-static-web-apps workflow.  Added Bundle Check and Gem Environment text files.  I've been struggling with this for several days, searched the internet for possible solutions, and I'm totally stuck.

### Did you try upgrading rubygems & bundler?
 Yes.  I have the most current Ruby version, 3.3.0.  My bundler version is 2.5.9 and I am unable to run "bundle install".  I've run "gem update --system" and it returns "Latest version already installed".  When I run "bundle update --bundler" I get the same errors as when I run "install bundler".

### Post steps to reproduce the problem

I'm running Microsoft Windows 11 home on a Surface Laptop 5 x64-based PC.  I'm using VS Code to build/maintain my code.  I'm using GitHub to host my code.  I'm using Microsoft Azure to host my website, although this has not succeeded yet.  I believe I used the RubyInstaller for Windows from rubyinstaller.org (but I forget the details).

### Which command did you run?

 bundler install

### What were you expecting to happen?

 I would expect bundler install to complete successfully without errors

### What actually happened?

I've attached a txt file with the output.  It's too long to paste in here

## Environment

Bundler       2.5.9
  Platforms   ruby, x64-mingw-ucrt
Ruby          3.3.0p0 (2023-12-25 revision 5124f9ac7513eb590c37717337c430cb93caa151) [x64-mingw-ucrt]
  Full Path   C:/tools/ruby33/bin/ruby.exe
  Config Dir  C:/ProgramData
RubyGems      3.5.9
  Gem Home    C:/tools/ruby33/lib/ruby/gems/3.3.0
  Gem Path    C:/Users/tomte/.local/share/gem/ruby/3.3.0;C:/tools/ruby33/lib/ruby/gems/3.3.0
  User Home   C:/Users/tomte
  User Path   C:/Users/tomte/.local/share/gem/ruby/3.3.0
  Bin Dir     C:/tools/ruby33/bin
Tools
  Git         2.44.0.windows.1
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-04-12
Git SHA           4304697e0c
Released Version  true
```

## Gemfile

### Gemfile

```ruby
source "https://rubygems.org"
# Hello! This is where you manage which Jekyll version is used to run.
# When you want to use a different version, change it below, save the
# file and run `bundle install`. Run Jekyll with `bundle exec`, like so:
#
#     bundle exec jekyll serve
#
# This will help ensure the proper Jekyll version is running.
# Happy Jekylling!
gem "jekyll", "~> 4.3.3"
# This is the default theme for new Jekyll sites. You may change this to anything you like.

gem "just-the-docs"
# If you want to use GitHub Pages, remove the "gem "jekyll"" above and
# uncomment the line below. To upgrade, run `bundle update github-pages`.
# gem "github-pages", group: :jekyll_plugins
# If you have any plugins, put them here!
group :jekyll_plugins do
  gem "jekyll-feed", "~> 0.12"
end

# Windows and JRuby does not include zoneinfo files, so bundle the tzinfo-data gem
# and associated library.
platforms :mingw, :x64_mingw, :mswin, :jruby do
  gem "tzinfo", ">= 1", "< 3"
  gem "tzinfo-data"
end

# Performance-booster for watching directories on Windows
gem "wdm", "~> 0.1.1", :platforms => [:mingw, :x64_mingw, :mswin]

# Lock `http_parser.rb` gem to `v0.6.x` on JRuby builds since newer versions of the gem
# do not have a Java counterpart.
gem "http_parser.rb", "~> 0.6.0", :platforms => [:jruby]
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    addressable (2.8.6)
      public_suffix (>= 2.0.2, < 6.0)
    colorator (1.1.0)
    concurrent-ruby (1.2.3)
    em-websocket (0.5.3)
      eventmachine (>= 0.12.9)
      http_parser.rb (~> 0)
    eventmachine (1.2.7)
    ffi (1.16.3)
    ffi (1.16.3-x64-mingw-ucrt)
    forwardable-extended (2.6.0)
    google-protobuf (4.26.1-x64-mingw-ucrt)
      rake (>= 13)
    google-protobuf (4.26.1-x86_64-linux)
      rake (>= 13)
    http_parser.rb (0.8.0)
    i18n (1.14.4)
      concurrent-ruby (~> 1.0)
    jekyll (4.3.3)
      addressable (~> 2.4)
      colorator (~> 1.0)
      em-websocket (~> 0.5)
      i18n (~> 1.0)
      jekyll-sass-converter (>= 2.0, < 4.0)
      jekyll-watch (~> 2.0)
      kramdown (~> 2.3, >= 2.3.1)
      kramdown-parser-gfm (~> 1.0)
      liquid (~> 4.0)
      mercenary (>= 0.3.6, < 0.5)
      pathutil (~> 0.9)
      rouge (>= 3.0, < 5.0)
      safe_yaml (~> 1.0)
      terminal-table (>= 1.8, < 4.0)
      webrick (~> 1.7)
    jekyll-feed (0.17.0)
      jekyll (>= 3.7, < 5.0)
    jekyll-include-cache (0.2.1)
      jekyll (>= 3.7, < 5.0)
    jekyll-sass-converter (3.0.0)
      sass-embedded (~> 1.54)
    jekyll-seo-tag (2.8.0)
      jekyll (>= 3.8, < 5.0)
    jekyll-watch (2.2.1)
      listen (~> 3.0)
    just-the-docs (0.7.0)
      jekyll (>= 3.8.5)
      jekyll-include-cache
      jekyll-seo-tag (>= 2.0)
      rake (>= 12.3.1)
    kramdown (2.4.0)
      rexml
    kramdown-parser-gfm (1.1.0)
      kramdown (~> 2.0)
    liquid (4.0.4)
    listen (3.8.0)
      rb-fsevent (~> 0.10, >= 0.10.3)
      rb-inotify (~> 0.9, >= 0.9.10)
    mercenary (0.4.0)
    pathutil (0.16.2)
      forwardable-extended (~> 2.6)
    public_suffix (5.0.5)
    rake (13.2.1)
    rb-fsevent (0.11.2)
    rb-inotify (0.10.1)
      ffi (~> 1.0)
    rexml (3.2.6)
    rouge (4.2.1)
    safe_yaml (1.0.5)
    sass-embedded (1.75.0-x64-mingw-ucrt)
      google-protobuf (>= 3.25, < 5.0)
    sass-embedded (1.75.0-x86_64-linux-gnu)
      google-protobuf (>= 3.25, < 5.0)
    terminal-table (3.0.2)
      unicode-display_width (>= 1.1.1, < 3)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    tzinfo-data (1.2024.1)
      tzinfo (>= 1.0.0)
    unicode-display_width (2.5.0)
    wdm (0.1.1)
    webrick (1.8.1)

PLATFORMS
  x64-mingw-ucrt
  x86_64-linux

DEPENDENCIES
  http_parser.rb (~> 0.6.0)
  jekyll (~> 4.3.3)
  jekyll-feed (~> 0.12)
  just-the-docs
  tzinfo (>= 1, < 3)
  tzinfo-data
  wdm (~> 0.1.1)

BUNDLED WITH
   2.5.9

**Comment by deivid-rodriguez** [comment]
Hello 👋! Thanks for reporting.

* Regarding the original issue when switching to Azure: Looking into your logs, the problem you are running into was fixed by https://github.com/rubygems/rubygems/pull/7310., released with Bundler 2.5.2. However, your new Azure environment seems to be running Ruby 2.7, which includes a Bundler version older than that. Hence the error. Manually deleting the lockfile is a way to workaround the issue 👍.
* Regarding the problem you're having locally: that suggests that you don't have developer tools installed locally necessary for Bundler to install gems with extensions. I think that may be because you original installed Ruby without devkit from [here](https://rubyinstaller.org/downloads/). I think reinstalling the proper Ruby+Devkit version may fix your problem.

Since this points to a problem already fixed, and a problem not under Bundler control, I'll close this ticket, but let me know if you're still stuck and I can try to help more!

**Comment by Tom-H2oThermo** [comment]
Thank you for you help in this matter.  I'll try to work my way through this tonight.

**Comment by Tom-H2oThermo** [comment]
Its working now.  Sorry for my lack of understanding.  Thank you for your help.

**Comment by deivid-rodriguez** [comment]
No problem, glad you got it working!
