### ISSUE TITLE
`bundle package` lacks a man page

### ISSUE THREAD

**Issue by postmodern** [rubygems/rubygems#7594]
### Describe the problem as clearly as you can

When running `bundle package --help` or `bundle help package`, no man page is displayed. I also check the [`bundler/lib/bundler/man/` directory on GitHub](https://github.com/rubygems/rubygems/tree/master/bundler/lib/bundler/man), and there does not appear to be a man page for `bundle-package.1`.

### Did you try upgrading rubygems & bundler?

No

### Post steps to reproduce the problem

1. `bundle help package`

### Which command did you run?

`bundle help package`

### What were you expecting to happen?

Display the man page for `bundle package` like the other commands.

### What actually happened?

Displayed regular `--help` output.

### If not included with the output of your command, run `bundle env` and paste the output below

```
Bundler       2.5.3
  Platforms   ruby, x86_64-linux
Ruby          3.3.0p0 (2023-12-25 revision 5124f9ac7513eb590c37717337c430cb93caa151) [x86_64-linux]
  Full Path   /opt/rubies/ruby-3.3.0/bin/ruby
  Config Dir  /opt/rubies/ruby-3.3.0/etc
RubyGems      3.5.3
  Gem Home    /home/postmodern/.gem/ruby/3.3.0
  Gem Path    /home/postmodern/.gem/ruby/3.3.0:/opt/rubies/ruby-3.3.0/lib/ruby/gems/3.3.0
  User Home   /home/postmodern
  User Path   /home/postmodern/.gem/ruby/3.3.0
  Bin Dir     /home/postmodern/.gem/ruby/3.3.0/bin
Tools         
  Git         2.44.0
  RVM         not installed
  rbenv       not installed
  chruby      0.3.9
```

## Bundler Build Metadata

```
Built At          2023-12-22
Git SHA           a04f70b115
Released Version  true
```

## Bundler settings

```
gem.changelog
  Set for your local app (/home/postmodern/.bundle/config): false
  Set for the current user (/home/postmodern/.bundle/config): false
gem.ci
  Set for your local app (/home/postmodern/.bundle/config): false
  Set for the current user (/home/postmodern/.bundle/config): false
gem.coc
  Set for your local app (/home/postmodern/.bundle/config): false
  Set for the current user (/home/postmodern/.bundle/config): false
gem.linter
  Set for your local app (/home/postmodern/.bundle/config): false
  Set for the current user (/home/postmodern/.bundle/config): false
gem.mit
  Set for your local app (/home/postmodern/.bundle/config): false
  Set for the current user (/home/postmodern/.bundle/config): false
gem.test
  Set for your local app (/home/postmodern/.bundle/config): false
  Set for the current user (/home/postmodern/.bundle/config): false
path
  Set for your local app (/home/postmodern/.bundle/config): "vendor/bundle"
  Set for the current user (/home/postmodern/.bundle/config): "vendor/bundle"
```

**Comment by deivid-rodriguez** [comment]
`bundle package --help` is working fine for me, but indeed `bundle help package` is not properly showing the man package it's supposed to show.

The problem is that `package` is an alias of `cache`, and while `bundle package --help` was properly redirecting to `bundle help cache`, the proper alias mapping was not happening when running `bundle help package` directly.

#7601 should fix this.

It may come as slightly confusing that `bundle cache` man page is displayed here, but command aliases are listed at the very top of this page, so I think it's OK.
