### ISSUE TITLE
ERROR:  While executing gem ... (Errno::ENOENT)

### ISSUE THREAD

**Issue by captainwycliffe** [rubygems/rubygems#7609]
I was installing Ruby with rbenv and it was succesfully installed.However, when I was working with gems, I tried to run `gem install bundler`  and I encountered this error.I think it is related to `FileUtils` and I don't know how fix this.
This is the error below:

> ERROR:  While executing gem ... (Errno::ENOENT)
>     No such file or directory @ dir_s_mkdir - 
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/fileutils.rb:406:in `mkdir'
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/fileutils.rb:406:in `fu_mkdir'
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/fileutils.rb:384:in `block (2 levels) in mkdir_p'
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/fileutils.rb:382:in `reverse_each'
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/fileutils.rb:382:in `block in mkdir_p'
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/fileutils.rb:374:in `each'
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/fileutils.rb:374:in `mkdir_p'
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/installer.rb:711:in `verify_gem_home'
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/installer.rb:902:in `pre_install_checks'
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/installer.rb:302:in `install'
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/resolver/specification.rb:104:in `install'
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/request_set.rb:194:in `block in install'
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/request_set.rb:182:in `each'
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/request_set.rb:182:in `install'
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/commands/install_command.rb:214:in `install_gem'
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/commands/install_command.rb:230:in `block in install_gems'
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/commands/install_command.rb:223:in `each'
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/commands/install_command.rb:223:in `install_gems'
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/commands/install_command.rb:169:in `execute'
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/command.rb:323:in `invoke_with_build_args'
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/command_manager.rb:185:in `process_args'
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/command_manager.rb:149:in `run'
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/gem_runner.rb:51:in `run'
> 	/home/wycliffekibet/.rbenv/versions/3.2.0/bin/gem:10:in `<main>'

I tried installing different versions of ruby but still encountered the same error

**Comment by deivid-rodriguez** [comment]
Thanks for the report. That's confusing error but I guess permission related. Can you open `/home/wycliffekibet/.rbenv/versions/3.2.0/lib/ruby/3.2.0/rubygems/installer.rb` and add a line like `puts "gem_home: #{gem_home}"` on top of line 711 to see which folder is giving trouble? Once you have that, can you show its current permissions (`ls -la <file>`).

**Comment by captainwycliffe** [comment]
I actually I solved the issue.And yes, it was something related to access.I run `sudo gem install bundler` and it worked perfectly.Thanks for the quick reply.
