### ISSUE TITLE
Bundler `deployment` mode not working with the `BUNDLE_DEPLOYMENT` environment variable

### ISSUE THREAD

**Issue by zarifmahfuz** [rubygems/rubygems#7627]
### Describe the problem as clearly as you can
When setting the `BUNDLE_DEPLOYMENT` to true, I expect deployment mode to be set and `bundle install` to raise an error when Gemfile is changed without corresponding change to Gemfile.lock. But it appears to not be working as expected.

### Did you try upgrading rubygems & bundler?

We're using `bundler version 2.4.22` and I checked the latest version's changelogs for potential bug fixes and did not see any.

### Post steps to reproduce the problem

1. Change Gemfile without changing Gemfile.lock
2. Set BUNDLE_DEPLOYMENT=true
3. Run bundle install
4. No error is raised (incorrect behavior)

### Which command did you run?

```
export BUNDLE_DEPLOYMENT=true
bundle install
```

### What were you expecting to happen?

Expecting a version incompatible error to be raised.

### What actually happened?

No error was raised and `bundle install` ran successfully.

### If not included with the output of your command, run `bundle env` and paste the output below

```
root@sandbox:/app# bundle config list
Settings are listed in order of priority. The top value will be used.
clean
Set via BUNDLE_CLEAN: true

deployment
Set via BUNDLE_DEPLOYMENT: true

jobs
Set for your local app (/app/.bundle/config): 4

path
Set for your local app (/app/.bundle/config): "/tmp/bundle"
Set via BUNDLE_PATH: "/tmp/bundle"

retry
Set for your local app (/app/.bundle/config): 3

user_config
Set via BUNDLE_USER_CONFIG: "/usr/local/etc/.bundle/config"

without
Set for your local app (/app/.bundle/config): [:debug]
Set via BUNDLE_WITHOUT: [:debug]
```

**Comment by zarifmahfuz** [comment]
I have double checked whether the problem exists in the latest bundler version and it does not.

**Comment by indirect** [comment]
I believe in earlier versions of bundler the setting/var was named "frozen", as in `BUNDLE_FROZEN=true`.
