### ISSUE TITLE
2.5.8 perf regression in `Bundler::Source::RubyGems.cached_specs`

### ISSUE THREAD

**Issue by jscheid** [rubygems/rubygems#7676]
### Describe the problem as clearly as you can

With a sizeable Gemfile (>400 gems) bundler overhead is about 0.2s-0.4s with <= 2.5.7, but 2.5-3.0s with >= 2.5.8.
All of the overhead appears to be spent in `Bundler::Source::RubyGems.cached_specs`, which takes about 2s in 2.5.10.

Unfortunately we don't have time at the moment to track it down more, we're going to pin to 2.5.7 for now. Let me know if this is not enough to find the culprit without additional info and we'll try and investigate more at some later time.

We can repro this in a Linux VM running on M3 and also on Intel.

We've tested a number of earlier versions (2.4.7, 2.5.0, 2.5.4, 2.5.7) and they're all unaffected. 2.5.8, 2.5.9, 2.5.10 are all affected.

### Did you try upgrading rubygems & bundler?

Yes

### Post steps to reproduce the problem

Sorry, can't easily share the `Gemfile` with you.

### Which command did you run?

```
time bundle exec irb --script <(echo true)
```

### What were you expecting to happen?

Should complete in <500ms.

### What actually happened?

Completes in >2000ms with 2.5.8+.

## Environment

```
Bundler       2.5.10
  Platforms   ruby, aarch64-linux
Ruby          3.3.1p55 (2024-04-23 revision c56cd86388092faec079981f779f140717020d58) [aarch64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.5.10
  Gem Home    /usr/local/bundle
  Gem Path    /app/.local/share/gem/ruby/3.3.0:/usr/local/lib/ruby/gems/3.3.0:/usr/local/bundle
  User Home   /app
  User Path   /app/.local/share/gem/ruby/3.3.0
  Bin Dir     /usr/local/bundle/bin
Tools         
  Git         2.30.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-05-03
Git SHA           24cac00613
Released Version  true
```

## Bundler settings

```
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
cache_all
  Set for your local app (/usr/local/bundle/config): true
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
user_cache
  Set via BUNDLE_USER_CACHE: "/usr/share/bundle-cache"
```

**Comment by deivid-rodriguez** [comment]
Hello!

Thanks for reporting. Yes, the info provided is enough. This is a regression from https://github.com/rubygems/rubygems/pull/7516. Working on a fix now!

**Comment by deivid-rodriguez** [comment]
#7680 should fix this!

**Comment by jscheid** [comment]
Brilliant, that was quick, thanks @deivid-rodriguez!

I can confirm this does bring us back to reasonable start up time 🎉 
```
$ time bundle exec irb --script <(echo true)
63(main):001> true
=> true
63(main):002> 

real	0m0.356s
user	0m0.261s
sys	0m0.074s
```
