### ISSUE TITLE
NoMethodError: undefined method `+' for nil:NilClass

### ISSUE THREAD

**Issue by arianf** [rubygems/rubygems#7697]
I'm getting: `NoMethodError: undefined method '+' for nil:NilClass`

```
/gems/bundler-2.5.11/lib/bundler/compact_index_client/cache.rb:109:in `parse_version_checksum'
/gems/bundler-2.5.11/lib/bundler/compact_index_client/cache.rb:59:in `block in checksums'
...
```

with ruby 3.2.0

https://github.com/rubygems/rubygems/blob/4afb2d450a3e279bb67a969a4b8906e5211c4498/bundler/lib/bundler/compact_index_client/cache.rb#L109

**Comment by arianf** [comment]
Downgrading to bundle version `Bundler version 2.5.10` fixes the issue for me

**Comment by arianf** [comment]
Looks like an issue with our internal rubygems mirror

**Comment by arianf** [comment]
Looks like this would effect anyone with https://jfrog.com/artifactory/ mirrors, reopening

**Comment by pascalbetz** [comment]
thanks @arianf for reporting and the temporary solution with downgrading.

I was able to sneak this into my Dockerfile

```
RUN gem install bundler -v "2.5.10"
RUN bundle _2.5.10_ install --jobs 4
```

to enforce an older version. Did not know the `_version_` syntax before :-)

**Comment by berkos** [comment]
> Looks like this would affect anyone with https://jfrog.com/artifactory/ mirrors, reopening. As the versions file produced by Artifactory includes extra lines, causing issues with 2.5.11

Thanks in advance for opening this.
I can confirm the same exact issue with a Gemfile that is using internal Artifactory as a mirror.

**Comment by deivid-rodriguez** [comment]
This has been fixed by https://github.com/rubygems/rubygems/pull/7672, which will be released shortly. Closing!
