### ISSUE TITLE
`bundle lock --add-platform windows` prints a warning and adds `unknown`

### ISSUE THREAD

**Issue by runephilosof-abtion** [rubygems/rubygems#7702]
### Describe the problem as clearly as you can

Given the what's new in 2.5 https://bundler.io/v2.5/whats_new.html I assume I can add the `windows` platform with `bundle lock --add-platform windows`.

I thought it would work the same as with `ruby`
```
bundle lock --add-platform ruby
```

### Did you try upgrading rubygems & bundler?

rubygems 3.5.11
bundler 2.5.11

### Post steps to reproduce the problem

```
docker run --rm -it ruby:3.3.1 bash
gem update --system
bundle init
bundle lock --add-platform windows
```

### Which command did you run?

```
bundle lock --add-platform windows
```

### What were you expecting to happen?

Gemfile.lock should contain `windows`.

### What actually happened?

Gemfile.lock contained `unknown`

### If not included with the output of your command, run `bundle env` and paste the output below

````
root@514425efd8bc:/# bundle env
## Environment

```
Bundler       2.5.11
  Platforms   ruby, x86_64-linux
Ruby          3.3.1p55 (2024-04-23 revision c56cd86388092faec079981f779f140717020d58) [x86_64-linux]
  Full Path   /usr/local/bin/ruby
  Config Dir  /usr/local/etc
RubyGems      3.5.11
  Gem Home    /usr/local/bundle
  Gem Path    /root/.local/share/gem/ruby/3.3.0:/usr/local/lib/ruby/gems/3.3.0:/usr/local/bundle
  User Home   /root
  User Path   /root/.local/share/gem/ruby/3.3.0
  Bin Dir     /usr/local/bundle/bin
Tools         
  Git         2.39.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-05-28
Git SHA           4afb2d450a
Released Version  true
```

## Bundler settings

```
app_config
  Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
silence_root_warning
  Set via BUNDLE_SILENCE_ROOT_WARNING: true
```

## Gemfile

### Gemfile

```ruby
# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"
```

### Gemfile.lock

```
<No /Gemfile.lock found>
```

````

**Comment by runephilosof-abtion** [comment]
Related to https://github.com/rubygems/rubygems/pull/6391

**Comment by deivid-rodriguez** [comment]
I know it's confusing but you're not supposed to feed `--add-platform` with `windows` value. Even if they are both named `platforms`, the `:platforms` option in the Gemfile DSL is closer to "Ruby Implementation" (particularly, as documented here: https://bundler.io/v2.5/man/gemfile.5.html#PLATFORMS), while PLATFORMS section in lockfile is closer to the value of `ruby -e 'puts RUBY_PLATFORM'`.

I think we should, at least:

* Add a note about this in https://bundler.io/v2.5/man/gemfile.5.html#PLATFORMS.
* Reject invalid values from `bundle lock --add-platform` and never lock "unknown".

**Comment by runephilosof-abtion** [comment]
How come `ruby` is a platform in Gemfile.lock then?
