### ISSUE TITLE
Validation runs twice on bundle commands

### ISSUE THREAD

**Issue by thomasmarshall** [rubygems/rubygems#7722]
### Describe the problem as clearly as you can

Running `bundle` causes the gemspec to be validated twice (and possibly other things happen twice).

639f0b72f40979b552b4bae44a122cfd176115a was intended as a refactor, but it looks like the behavior changed.

- The previous logic for `resolve_if_needed` previously returned `false` with no side effects, but it now returns `false` after calling `resolve_with_cache!`.
- Previously `sources.cached!` was called only if resolution was needed (via `setup_sources_for_resolve`), but now it is called if resolution is not needed (via `resolve_with_cache!`).

I think this is closer to the original logic, but I must admit I don't have enough context to confidently propose a change like this:

```ruby
def resolve_if_needed(options)
  @definition.prefer_local! if options["prefer-local"] && !options["local"]

  if @definition.no_resolve_needed? && !@definition.missing_specs?
    false
  elsif options["local"]
    @definition.resolve_with_cache!
    true
  else
    @definition.resolve_remotely!
    true
  end
end
```

<details>
  <summary>Diff</summary>

```diff
diff --git a/bundler/lib/bundler/installer.rb b/bundler/lib/bundler/installer.rb
index 256f0be34..fbadfb0f7 100644
--- a/bundler/lib/bundler/installer.rb
+++ b/bundler/lib/bundler/installer.rb
@@ -235,11 +235,13 @@ def install_in_parallel(size, standalone, force = false)
 
     # returns whether or not a re-resolve was needed
     def resolve_if_needed(options)
-      @definition.prefer_local! if options["prefer-local"]
+      @definition.prefer_local! if options["prefer-local"] && !options["local"]
 
-      if options["local"] || (@definition.no_resolve_needed? && !@definition.missing_specs?)
-        @definition.resolve_with_cache!
+      if @definition.no_resolve_needed? && !@definition.missing_specs?
         false
+      elsif options["local"]
+        @definition.resolve_with_cache!
+        true
       else
         @definition.resolve_remotely!
         true
```
  

</details>

### Did you try upgrading rubygems & bundler?

The issue is in the `master` branch as of 639f0b72f40979b552b4bae44a122cfd176115a.

### Post steps to reproduce the problem

- Clone the repo
- Add a `puts "validating"` statement in `Bundler::RubygemsIntegration#validate`
- `ruby -I../rubygems/lib ../rubygems/bundler/spec/support/bundle.rb` in a gem directory
- See that `"validating"` is output twice

### Which command did you run?

```
ruby -I../rubygems/lib ../rubygems/bundler/spec/support/bundle.rb
```

### What were you expecting to happen?

The gemspec would only be validated once.

### What actually happened?

The gemspec was validated twice.

### If not included with the output of your command, run `bundle env` and paste the output below

Not applicable.

**Comment by deivid-rodriguez** [comment]
Thanks for the report @thomasmarshall. I tried fixing this in #7725. Also, I will review your work to make generated gems more usable by default next week. Excited about that improvement!
