### ISSUE TITLE
Bundler always chooses to compile native extensions

### ISSUE THREAD

**Issue by jaydorsey** [rubygems/rubygems#7736]
### Describe the problem as clearly as you can

I'm trying to understand why I can `gem install grpc` just fine, but `bundle install` with grpc in my `Gemfile` always forces grpc to compile. 

The grpc compile fails for reasons, but that's not what I'm trying to fix/understand right now.

![SnagitHelper2024 2024-06-12 11 14 20](https://github.com/rubygems/rubygems/assets/191564/8c3a1ae4-fdd0-49a6-a031-9e1d1c6d3a8a)

macOS: Sonoma 14.5
chip: M3 Max
ruby: 3.2.4 (also 3.1.2)
xcode: 15.2
bundler: 2.5.11
rubygems: latest (`gem update --system`)

Gemfile:

```
# frozen_string_literal: true

source 'https://rubygems.org'
ruby file: ".ruby-version"

gem 'grpc', '~> 1.61.0'
```

Gemfile.lock:

```
GEM
  remote: https://rubygems.org/
  specs:
    google-protobuf (3.25.3)
    google-protobuf (3.25.3-arm64-darwin)
    googleapis-common-protos-types (1.15.0)
      google-protobuf (>= 3.18, < 5.a)
    grpc (1.61.0)
      google-protobuf (~> 3.25)
      googleapis-common-protos-types (~> 1.0)
    grpc (1.61.0-arm64-darwin)
      google-protobuf (~> 3.25)
      googleapis-common-protos-types (~> 1.0)

PLATFORMS
  arm64-darwin
  ruby

DEPENDENCIES
  grpc (~> 1.61.0)

RUBY VERSION
   ruby 3.2.4p170

BUNDLED WITH
   2.5.11
```

![image](https://github.com/rubygems/rubygems/assets/191564/2c0f297a-9eca-4baa-bde0-6c0d37eec7bf)

I've tried:
1. Other ruby versions
2. Other bundler versions
3. Other grpc versions
4. Other gems that have native compilation and precompiled versions (in the past; I think I've noticed this behavior for a while)

The result is the same: I can't seem to force bundler to find the binary like `gem install` does

I even tried manually remove the reference to the non-platform-specific version from the `Gemfile.lock`, so only the arm64/darwin references are left in thelock file; it always tries to compile. (Note: I'm not sure that's even a "thing" that's supposed to work but I'm running out of ideas at this point)

![image](https://github.com/rubygems/rubygems/assets/191564/2b4d840e-f418-4ed7-8009-9df60c536acc)

I know not everyone has access to an M3 Max, but I'd be willing to pair with someone on this issue if that helps triage or fix this issue (if it's a bug and not by design)

### Did you try upgrading rubygems & bundler?

Yes.

### Post steps to reproduce the problem

1. Copy my `Gemfile` and `Gemfile.lock` above
2. `gem update system` and `gem update bundler`
3. `bundle install`
4. Observe the 

### Which command did you run?

`bundle install`

### What were you expecting to happen?

The precompiled binary that `gem install` used is also used by bundler.

### What actually happened?

Bundler tries to compile the native extension (which results in an error, which is another, separate issue for grpc)

## Environment

```
Bundler       2.5.11
  Platforms   ruby, arm64-darwin-23
Ruby          3.2.4p170 (2024-04-23 revision af471c0e0127eea0cafa6f308c0425bbfab0acf5) [arm64-darwin-23]
  Full Path   /Users/jay.dorsey/.local/share/rtx/installs/ruby/3.2.4/bin/ruby
  Config Dir  /Users/jay.dorsey/.local/share/rtx/installs/ruby/3.2.4/etc
RubyGems      3.5.11
  Gem Home    /Users/jay.dorsey/.local/share/rtx/installs/ruby/3.2.4/lib/ruby/gems/3.2.0
  Gem Path    /Users/jay.dorsey/.gem/ruby/3.2.0:/Users/jay.dorsey/.local/share/rtx/installs/ruby/3.2.4/lib/ruby/gems/3.2.0
  User Home   /Users/jay.dorsey
  User Path   /Users/jay.dorsey/.gem/ruby/3.2.0
  Bin Dir     /Users/jay.dorsey/.local/share/rtx/installs/ruby/3.2.4/bin
Tools
  Git         2.45.2
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-05-28
Git SHA           4afb2d450a
Released Version  true
```

## Bundler settings

> NOTE: I also tried it with no build.grpc settings, and some others
```
build.grpc
  Set for the current user (/Users/jay.dorsey/.bundle/config): "--use-system-libraries"
build.libv8
  Set for the current user (/Users/jay.dorsey/.bundle/config): "--with-system-v8"
build.nokogiri
  Set for the current user (/Users/jay.dorsey/.bundle/config): "--use-system-libraries"
build.therubyracer
  Set for the current user (/Users/jay.dorsey/.bundle/config): "--with-v8-dir=/usr/local/opt/v8"
console
  Set for the current user (/Users/jay.dorsey/.bundle/config): "pry"
disable_version_check
  Set for the current user (/Users/jay.dorsey/.bundle/config): true
force_ruby_platform
  Set for the current user (/Users/jay.dorsey/.bundle/config): true
gem.changelog
  Set for the current user (/Users/jay.dorsey/.bundle/config): false
gem.ci
  Set for the current user (/Users/jay.dorsey/.bundle/config): false
gem.coc
  Set for the current user (/Users/jay.dorsey/.bundle/config): false
gem.linter
  Set for the current user (/Users/jay.dorsey/.bundle/config): false
gem.mit
  Set for the current user (/Users/jay.dorsey/.bundle/config): false
gem.test
  Set for the current user (/Users/jay.dorsey/.bundle/config): false
ignore_funding_requests
  Set for the current user (/Users/jay.dorsey/.bundle/config): "true"
jobs
  Set for the current user (/Users/jay.dorsey/.bundle/config): 8
retry
  Set for the current user (/Users/jay.dorsey/.bundle/config): 1
suppress_install_using_messages
  Set for the current user (/Users/jay.dorsey/.bundle/config): "1"
update_requires_all_flag
  Set for the current user (/Users/jay.dorsey/.bundle/config): true
```

### Gemfile

```ruby
# frozen_string_literal: true

source 'https://rubygems.org'
ruby file: ".ruby-version"

gem 'grpc', '~> 1.61.0'
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    google-protobuf (3.25.3-arm64-darwin)
    googleapis-common-protos-types (1.15.0)
      google-protobuf (>= 3.18, < 5.a)
    grpc (1.61.0-arm64-darwin)
      google-protobuf (~> 3.25)
      googleapis-common-protos-types (~> 1.0)

PLATFORMS
  arm64-darwin

DEPENDENCIES
  grpc (~> 1.61.0)

RUBY VERSION
   ruby 3.2.4p170

BUNDLED WITH
   2.5.11
```

**Comment by jaydorsey** [comment]
> It's the `force_ruby_platform` setting that you have configured. Run `bundle config unset force_ruby_platform` and you should be fine!

🤦 

I've had that set in my config for 2 years at this point, I don't know how I missed this. Thank you so much this has been the bane of my existence w/ compiled gems

**Comment by deivid-rodriguez** [comment]
I'm glad we got that sorted out!
