### ISSUE TITLE
`bundle install` deleting platforms from Gemfile.lock

### ISSUE THREAD

**Issue by elondres-mim** [rubygems/rubygems#7759]
### Describe the problem as clearly as you can

Recently (within the last 3 months) we've run into a situation where running `bundle install` deletes all platforms from Gemfile.lock except for the platform of the machine the command was run on. It also removes any gem entries in Gemfile.lock with a specified platform other than the platform of the machine the command was run on.

### Did you try upgrading rubygems & bundler?

Yes, this is still happening as of Bundler 2.5.13

### Post steps to reproduce the problem

Have x86_64-linux specified as a platform in Gemfile.lock and at least one gem such as google-prototbuf.

Run `bundle install` on an x86_64-darwin machine.

### Which command did you run?

`bundle install`

### What were you expecting to happen?

Gems are installed according to the platforms specified in Gemfile.lock

### What actually happened?

All platforms except the platform of the machine running the command were removed from Gemfile.lock

**Comment by deivid-rodriguez** [comment]
I don't know why this is happening. I also made a few tests and couldn't reproduce this. Can you provide more information? Thanks!

**Comment by jasnow** [comment]
ONE WAY TO REPRODUCE

1. Use this repo: https://github.com/jasnow/trail. Note that it include "ruby" as a platform.

2. Run "bundle lock --add-platform x86_64-linux". Note that it "ruby" was removed as a platform.

3. Tried " bundle lock --add-platform ruby" but it was not added back.

**Comment by deivid-rodriguez** [comment]
Hi @jasnow. Unfortunately I still can't reproduce the problem. No platform is removed for me. If you can create a Dockerfile that reproduces the issue, that'd be great. Or at least share your working environment (`bundle env`, `gem env` output) so I can try to imitate it.

**Comment by jasnow** [comment]
> Hi @jasnow. Unfortunately I still can't reproduce the problem. No platform is removed for me. If you can create a Dockerfile that reproduces the issue, that'd be great. Or at least share your working environment (`bundle env`, `gem env` output) so I can try to imitate it.

Thanks for update.

**Comment by jasnow** [comment]
Think this PR fixed this issue: https://github.com/rubygems/rubygems/pull/7864

**Comment by deivid-rodriguez** [comment]
That's great news, thanks for letting me know @jasnow! @elondres-mim can you confirm that this is fixed for you too?

**Comment by deivid-rodriguez** [comment]
I'll assume this is fixed.
