### ISSUE TITLE
Credentials now readded from Gemfile.lock if they were removed in 2.5.11

### ISSUE THREAD

**Issue by broksonic21** [rubygems/rubygems#7761]
### Describe the problem as clearly as you can

I know there's been a lot of convos on this (thanks for working on it @deivid-rodriguez!), but I'm now seeing more churn I wasn't expected

Our scenario:

* We have creds in the Gemfile in some scenarios
* We upgraded to Bundler 2.5.11 -> they were removed from the lockfile
* That's fine, since Dependabot also bumped to 2.5.11, so we were consistent
* However, upon upgrading to 2.5.12/2.5.13, the credentials are _put back in_. That's not what I'd expect after https://github.com/rubygems/rubygems/pull/7720 - I thought was only to keep them if they were there, not re-add them if they had been removed. 
* Which means we can't bump to 2.5.12/2.5.13 until all corresponding tooling (dependabot etc) updates as well again

### Did you try upgrading rubygems & bundler?

Yes, that's what is causing this issue

### Post steps to reproduce the problem

* We have creds in the Gemfile in some scenarios
* We upgraded to Bundler 2.5.11 -> they were removed from the lockfile
* That's fine, since Dependabot also bumped to 2.5.11, so we were consistent
* However, upon upgrading to 2.5.12/2.5.13, the credentials are _put back in_. That's not what I'd expect after https://github.com/rubygems/rubygems/pull/7720 - I thought was only to keep them if they were there, not re-add them if they had been removed. 
* Which means we can't bump to 2.5.12/2.5.13 until all corresponding tooling (dependabot etc) updates as well again

### Which command did you run?

bundle update --bundler
bundle install

### What were you expecting to happen?

If no creds because of 2.5.11, they stayed with no creds in 2.5.12/2.5.13

### What actually happened?

Creds were re-added back in

### If not included with the output of your command, run `bundle env` and paste the output below

Bundler       2.5.11 (or 2.5.12/2.5.13)
  Platforms   ruby, arm64-darwin-22

**Comment by deivid-rodriguez** [comment]
😞 Sorry about that, yeah, that was the intention of #7720 and what I tried to cover in the specs in that PR. But it sounds like I missed something, let me look into it!
