### ISSUE TITLE
Compact index format assumes no dashes in versions, but this is not always true

### ISSUE THREAD

**Issue by maxfisher-g** [rubygems/rubygems#7766]
### Describe the problem as clearly as you can

Hi, I would like to parse Rubygems data from the compact index API.

Looking at the definition of the compact index format described [here](https://github.com/rubygems/guides/blob/main/rubygems-org-compact-index-api.md), the description for how versions are formatted says 

> The pieces of each line are:
> VERSION - The version of the rubygem. Read VERSION until either - (minus) or space character is encountered.
> [-PLATFORM] - The platform, if it is not the default platform ruby. The first - (minus) character in the VERSION[-PLATFORM] chunk splits the VERSION and PLATFORM. The PLATFORM may contain more dashes. Read platform until a space is encountered. 
> ...

This implies that VERSION strings should not contain any dash characters. 

However, according to https://github.com/rubygems/rubygems/issues/3086, dashes are actually allowed in prerelease version strings. This occurs in at least one package, for example [asciidoctor-reducer](https://rubygems.org/gems/asciidoctor-reducer/versions) has versions `1.0.0-rc.1` and `1.0.0-beta.1`.

The [compact index listing](https://rubygems.org/info/asciidoctor-reducer) for this package simply includes the dashes in the version string, which if parsed according to the above rules results in a platform of `rc.1` or `beta.1` respectively.

Is this a problem? Does the official parser for this format have an allowlist of valid platform names that is used to produce a correct parsing of the version strings?

Regards, 
Max

**Comment by simi** [comment]
@maxfisher-g I'll check later, for now feel free to check on your own, current parsing logic is here.

https://github.com/rubygems/rubygems/blob/master/bundler/lib/bundler/compact_index_client/parser.rb

**Comment by martinemde** [comment]
Those seem like bad versions. We have a rule that should be turning `-` into `.pre.` so I wonder why that's not happening.

**Comment by deivid-rodriguez** [comment]
Yeah. With a bit of [effort](https://github.com/asciidoctor/asciidoctor-reducer/commit/73af77685fc95a7d0b2e7eb70b7964eb61e5da32), you could previously build and push a gem with dashes in version.

We do prevent this since https://github.com/rubygems/rubygems.org/pull/4023, but this gem was pushed earlier.

Not sure if there's anything else actionable here. I don't think it's worth warning this on the client side. Perhaps we could remove/yank the bad versions in rubygems.org.

**Comment by maxfisher-g** [comment]
Alright, thanks all. Happy to close this.
