### ISSUE TITLE
`bundle config auto_install` discards `Bundler.ui.level` during `bundle install`

### ISSUE THREAD

**Issue by Earlopain** [rubygems/rubygems#7769]
### Describe the problem as clearly as you can

The ui loglevel is part of the rubygems object which gets reset during `auto_install`.

Relevant code:
* https://github.com/rubygems/rubygems/blob/a15e2cb599e1415d0e9577eb7ca2d0df985a4c38/bundler/lib/bundler.rb#L174-L191
* https://github.com/rubygems/rubygems/blob/a15e2cb599e1415d0e9577eb7ca2d0df985a4c38/bundler/lib/bundler.rb#L606-L610
* https://github.com/rubygems/rubygems/blob/a15e2cb599e1415d0e9577eb7ca2d0df985a4c38/bundler/lib/bundler.rb#L632-L637
* https://github.com/rubygems/rubygems/blob/a15e2cb599e1415d0e9577eb7ca2d0df985a4c38/bundler/lib/bundler.rb#L94-L97

If in application code you do `Bundler.ui.level = "silent"` to prevent output then that doesn't hold true if the user has auto_install configured. This impacts `ruby-lsp` which requires that bundler makes no output since stdout is used to comunicate with the language server client. https://github.com/Shopify/ruby-lsp/issues/2130

### Fix idea

Just remembering the loglevel and restoring that after a reset seems like a straightforward fix. If that makes sense and you'd consider the current behaviour a bug, I can draft a PR for that

**Comment by deivid-rodriguez** [comment]
Thanks for the report, makes sense.

I wonder if a simpler solution would be to not reset `@rubygems` at all:

```diff
diff --git a/bundler/lib/bundler.rb b/bundler/lib/bundler.rb
index e7efeb8fa6..d73b7e18e1 100644
--- a/bundler/lib/bundler.rb
+++ b/bundler/lib/bundler.rb
@@ -630,10 +630,8 @@ def reset_paths!
     end
 
     def reset_rubygems!
-      return unless defined?(@rubygems) && @rubygems
       rubygems.undo_replacements
       rubygems.reset
-      @rubygems = nil
     end
 
     def configure_gem_home_and_path(path = bundle_path)
```

**Comment by Earlopain** [comment]
I ran tests locally with that change and all tests pass. I'll create a PR for this + test

**Comment by deivid-rodriguez** [comment]
Any news?

**Comment by Earlopain** [comment]
Sorry, kind of forgot about this. From last looking into this, I couldn't find anything pointing directly to bundler. The theory above was nice but didn't hold up in practise. I'll close since _I think_ there's nothing wrong here

**Comment by deivid-rodriguez** [comment]
Thanks for the update and please do reopen and you find something is actually wrong!
