### ISSUE TITLE
Bundler: Intermittent write permission errors on Windows servers

### ISSUE THREAD

**Issue by abhidev8** [rubygems/rubygems#7782]
### Describe the problem as clearly as you can

Recently, we have noticed that all our Windows servers are intermittently experiencing bundler permission errors in both our non-production and production environments. These errors seem to arise unpredictably, sometimes every 3-4 days, or occasionally just once a week or every 10 days, making it challenging to discern a clear pattern. The following error has been captured on the Chef Automate dashboard:

```
Error Log & Stacktrace
Expected process to exit with [0], but received '23'
---- Begin output of ["bundle", "install"] ----
STDOUT: 
STDERR: There was an error while trying to write to
`C:/Windows/system32/config/systemprofile/.bundle/cache/compact_index/artifactory.abcdcorp.com.443.abcderfg12435336/versions`.
It is likely that you need to grant write permissions for that path.
---- End output of ["bundle", "install"] ----
Ran ["bundle", "install"] returned 23

Backtrace
----------------------------------------------------
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/mixlib-shellout-3.2.5-universal-mingw32/lib/mixlib/shellout.rb:300:in `invalid!'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/mixlib-shellout-3.2.5-universal-mingw32/lib/mixlib/shellout.rb:287:in `error!'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/mixlib-shellout-3.2.5-universal-mingw32/lib/mixlib/shellout/helper.rb:130:in `shell_out_compacted!'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/mixlib-shellout-3.2.5-universal-mingw32/lib/mixlib/shellout/helper.rb:54:in `shell_out!'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.9.26-universal-mingw32/lib/chef/cookbook/gem_installer.rb:77:in `block (2 levels) in install'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.9.26-universal-mingw32/lib/chef/cookbook/gem_installer.rb:59:in `open'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.9.26-universal-mingw32/lib/chef/cookbook/gem_installer.rb:59:in `block in install'
C:/opscode/chef/embedded/lib/ruby/3.0.0/tmpdir.rb:96:in `mktmpdir'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.9.26-universal-mingw32/lib/chef/cookbook/gem_installer.rb:58:in `install'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.9.26-universal-mingw32/lib/chef/cookbook/cookbook_collection.rb:59:in `install_gems'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.9.26-universal-mingw32/lib/chef/policy_builder/policyfile.rb:173:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/3.0.0/forwardable.rb:238:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.9.26-universal-mingw32/lib/chef/client.rb:495:in `setup_run_context'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.9.26-universal-mingw32/lib/chef/client.rb:281:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.9.26-universal-mingw32/lib/chef/application.rb:305:in `run_with_graceful_exit_option'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.9.26-universal-mingw32/lib/chef/application.rb:281:in `block in run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.9.26-universal-mingw32/lib/chef/local_mode.rb:42:in `with_server_connectivity'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.9.26-universal-mingw32/lib/chef/application.rb:264:in `run_chef_client'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.9.26-universal-mingw32/lib/chef/application/base.rb:352:in `run_application'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-17.9.26-universal-mingw32/lib/chef/application.rb:67:in `run'
C:/opscode/chef/embedded/lib/ruby/gems/3.0.0/gems/chef-bin-17.9.26/bin/chef-client:25:in `<top (required)>'
C:/opscode/chef/bin/chef-client:172:in `load'
C:/opscode/chef/bin/chef-client:172:in `<main>'
```
We are encountering these errors specifically on Windows servers. Some of our servers run Chef 17.9.26, while others are on version 18.3.0. However, regardless of the version, we are experiencing this intermittent issue.

> Here are the details for Ruby, RubyGems, and Bundler on Windows Server 1 with Chef Infra Client Version 17.9.26.

Ruby Version - `ruby 3.0.3p157`
Rubygems Version - `3.1.6`
Bundle Environment
```
Bundler       2.2.32
  Platforms   ruby, x64-mingw32
Ruby          3.0.3p157 (2021-11-24 revision 3fb7d2cadc18472ec107b14234933b017a33c14d) [x64-mingw32]
  Full Path   C:/opscode/chef/embedded/bin/ruby.exe
  Config Dir  C:/ProgramData
  RubyGems      3.1.6
  Gem Home    C:/opscode/chef/embedded/lib/ruby/gems/3.0.0
  Gem Path    C:/Users/username/.gem/ruby/3.0.0;C:/opscode/chef/embedded/lib/ruby/gems/3.0.0
  User Home   C:/Users/username
  User Path   C:/Users/username/.gem/ruby/3.0.0
  Bin Dir     C:/opscode/chef/embedded/bin
Tools
  Git         not installed
  RVM         not installed
  rbenv       not installed
  chruby      not installed
 
## Bundler Build Metadata
Built At          2024-06-20
Git SHA           unknown
Released Version  false
```

> Here are the details for Ruby, RubyGems, and Bundler on Windows Server 2 with Chef Infra Client Version 18.3.0

Ruby Version - `ruby 3.1.2p20`
Rubygems Version - `3.3.7`
Bundle Environment
```
Bundler       2.3.7
  Platforms   ruby, x64-mingw-ucrt
Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x64-mingw-ucrt]
  Full Path   C:/opscode/chef/embedded/bin/ruby.exe
  Config Dir  C:/ProgramData
 RubyGems      3.3.7
  Gem Home    C:/opscode/chef/embedded/lib/ruby/gems/3.1.0
  Gem Path    C:/Users/username/.local/share/gem/ruby/3.1.0;C:/opscode/chef/embedded/lib/ruby/gems/3.1.0
  User Home   C:/Users/username
  User Path   C:/Users/username/.local/share/gem/ruby/3.1.0
  Bin Dir     C:/opscode/chef/embedded/bin
Tools
  Git         not installed
  RVM         not installed
  rbenv       not installed
  chruby      not installed
 
## Bundler Build Metadata
Built At          2024-06-20
Git SHA           unknown
Released Version  false
```
We have verified with our Windows System Administration team that the user executing the `chef-client`, creating any `temp` folders, and running `bundle` commands during the `chef-client` process on our Windows servers has the appropriate read, write, and execute permissions. The Windows Admin team has also confirmed that they do not see any issues with virus scanners or firewall rules that could be causing this issue.

### Did you try upgrading rubygems & bundler?
No, we haven't upgraded `rubygems` & `bundler` on our servers because we're experiencing intermittent issues with both the older and newer versions.

### Post steps to reproduce the problem

During the investigation, we altered the original bundle source code to check if the intermittent issue continues. We implemented the retry logic into the `updater.rb` file at `C:\opscode\chef\embedded\lib\ruby\3.0.0\bundler\compact_index_client`. Furthermore, we added code to determine if any process is accessing the .../Temp/... folder (not the destination), which may prevent the `chef-client ` process from moving it due to failure in deleting the source folder.

> Please see the attached modified `updater.rb` file, which includes the retry and file lock code. The modifications begin after the line `if correct_response` in the file.

[updater-with-retry.zip](https://github.com/user-attachments/files/15912061/updater-with-retry.zip)

We implemented the aforementioned code on one of our development servers (logging into the server and manually altering the `updater.rb`) and monitored it for two weeks. The logs indicate that the write error has ceased, and the retry mechanism is functioning as anticipated.

We tried to "monkey-patch" the retry logic by adding the patch code to one of our cookbook libraries (cookbook name: `xyz_core`; path: `xyz_core\libraries\deafult.rb`), although we're uncertain if this is the appropriate location for such code. However, when we run `chef-client`, none of the statements that are supposed to confirm whether our code is being loaded during the `chef-client` execution are displayed. Below is the monkey-patch code and the `chef-client` log output.

[monkeypatch-updater.zip](https://github.com/user-attachments/files/15912285/monkeypatch-updater.zip)
[chef-client.zip](https://github.com/user-attachments/files/15912321/chef-client.zip)

It is expected that the print statements from the patching code would be displayed at the bundle operation point during the `chef-client` run; however, no statements are appearing as illustrated below.

```
Installing cookbook gem dependencies:
[2024-06-20T13:35:42+00:00] INFO: Fetching gem metadata from https://artifactory.xyzicorp.com/artifactory/api/gems/xyz-rubygems/.....
Resolving dependencies...
Using aws-eventstream 1.3.0
Using aws-partitions 1.944.0
Using aws-sigv4 1.8.0
Using jmespath 1.6.2
Using aws-sdk-core 3.197.0
Using aws-sdk-ssm 1.128.0
Using bundler 2.2.32
Bundle complete! 1 Gemfile dependency, 7 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

Could someone from the community help us address this intermittent issue and provide guidance on correctly implementing monkey patching in the code, if that is the necessary solution to resolve this problem? If more details are needed, please inform me. Thank you for your assistance.
@deivid-rodriguez 

### Which command did you run?
Executed the `chef-client` command on the Windows server.

### What were you expecting to happen?
A `chef-client` run is expected to complete successfully without encountering any permission errors.

### What actually happened?
The `chef-client` run is encountering permission errors as outlined in the problem description.

**Comment by deivid-rodriguez** [comment]
It seems you've gone a long way investigating this problem. Are there multiple `bundle install` commands running at the same time? I guess if they were all creating the compact index cache at the same time, this could happen.

I think for starters, you'll need to upgrade Bundler. Even if the issue still happens in upgraded Bundler, we want to make sure any fix will work against the current code and the Bundler implementation you have patched is quite old.

**Comment by abhidev8** [comment]
> Are there multiple bundle install commands running at the same time? I guess if they were all creating the compact index cache at the same time, this could happen.

I'm not certain if I've understood your question correctly, but we operate hundreds of Windows servers with `chef-client` running every 30 minutes. Therefore, I believe `bundle install` would execute just once during each of these 30-minute intervals.

> I think for starters, you'll need to upgrade Bundler. Even if the issue still happens in upgraded Bundler, we want to make sure any fix will work against the current code and the Bundler implementation you have patched is quite old.

As indicated in the problem description, this issue has occurred with both bundler versions `v2.2.32` and `v2.3.7`. Could you recommend a specific bundler version to use?

**Comment by deivid-rodriguez** [comment]
> I'm not certain if I've understood your question correctly, but we operate hundreds of Windows servers with chef-client running every 30 minutes. Therefore, I believe bundle install would execute just once during each of these 30-minute intervals.

Yeah, that was the question, that if a certain moment it could happen that two separate `bundle install` processes are running at the same time.

> As indicated in the problem description, this issue has occurred with both bundler versions v2.2.32 and v2.3.7. Could you recommend a specific bundler version to use?

Yes, the latest. If we end up needing to patch this on our side, we'll patch the latest version.

**Comment by abhidev8** [comment]
If I understand correctly, my next steps are to upgrade Bundler to the latest version and check if the issue persists. If it does, you will patch the latest version, correct?

**Comment by deivid-rodriguez** [comment]
If upgrading does not fix it, we should keep digging. A good starting point would be to adapt your current patch to the latest version of Bundler and verify if that fixes things. But ideally we should gain some more understanding of what's wrong here, i.e., what's preventing Bundler from writing into the `versions` file.

**Comment by abhidev8** [comment]
> what's preventing Bundler from writing into the versions file.

I believe the problem does not lie in writing to the `versions` file. After debugging the bundler source code, it appears that the issue arises when the `versions` file is being moved from the `temp` folder to the actual Windows system path. This occurs within the `mv` function in `fileutils.rb`. Please correct me if I am mistaken.

Here are the sample debug statements from the `mv` function observed during my testing.
```
Renaming file from source:C:/Windows/Temp/bundler-compact-index-20240212-7188-ueoc7a/versions to destination: C:/Windows/system32/config/systemprofile/.bundle/cache/compact_index/artifactory.xyzicorp.com.80.50348f5dc08e250a1d0f9de781/versions
```

**Comment by deivid-rodriguez** [comment]
I see. That makes sense, all the other file operations happen on a per-process temporary folder 👍. I guess we can protect this move with a file lock, but I still wonder if this can happen without multiple `bundle install` invocations running concurrently. Could you change your recipe to run `bundle install --verbose` instead and post logs?

**Comment by deivid-rodriguez** [comment]
Thanks. So that's running `bundle install --verbose` with Bundler 2.2.32 + your patch? That seems to be working fine. I was expecting to see logs of the error, ideally using the latest verison of Bundler.

**Comment by abhidev8** [comment]
> Thanks. So that's running bundle install --verbose with Bundler 2.2.32 + your patch? That seems to be working fine. I was expecting to see logs of the error, ideally using the latest version of Bundler.

No, this log is without my patch.

I have also tried to keep my "monkeypatching" code in `client.rb` on my test windows machine, as it will be executed during the initial steps of `chef-client`. After running chef-client, I noticed that the 'puts' statements at the module level are displayed in the output. However, the statements within the update function are not appearing, which suggests that this function is not being invoked during the bundler operation. I am still exploring the correct location for this patching code to ensure that the updater function is invoked during the bundler operation.

**Comment by abhidev8** [comment]
> Thanks. So that's running bundle install --verbose with Bundler 2.2.32 + your patch? That seems to be working fine. I was expecting to see logs of the error, ideally using the latest version of Bundler.

No, this log is without my patch.

I have also tried to keep my "monkeypatching" code in `client.rb` on my test windows machine, as it will be executed during the initial steps of `chef-client`. After running chef-client, I noticed that the 'puts' statements at the module level are displayed in the output. However, the statements within the update function are not appearing, which suggests that this function is not being invoked during the bundler operation. I am still exploring on the correct location for this patching code to ensure that the updater function is invoked during the bundler operation.

**Comment by deivid-rodriguez** [comment]
But I see no errors in the log you posted. Can you post a log with errors, and possibly up to date Bundler?

**Comment by abhidev8** [comment]
> But I see no errors in the log you posted. Can you post a log with errors, and possibly up to date Bundler?

OK, I'll try that and get back to you. I need to verify if upgrading Bundler to the latest version works correctly, as it may have dependencies on RubyGems and other potential dependencies.

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback. If you can still reproduce this after upgrading Bundler, feel free to reopen!
