### ISSUE TITLE
Gem platform should treat `arm` as 32-bit arm instead of generic arm

### ISSUE THREAD

**Issue by ntkme** [rubygems/rubygems#7821]
https://github.com/rubygems/rubygems/blob/197de10d73cc2ebe8f708ebfa0b37ea6341db962/lib/rubygems/platform.rb#L179-L187

In practice, for Linux and Windows builds of Ruby, `arm` is strictly used to represent 32-bit arm, and `aarch64` is 64-bit arm. 

For Mac, historically Ruby before 3.0 incorrectly reports itself as `arm` on 64-bit arm. Since Ruby 3.0 this has been fixed and Mac always report as `arm64`.

The main problem here is that for ARMv8 and newer processors, 32-bit instruction support is not required for 64-bit processors. For example, Apple M family chip is aarch64 only with no hardware support for aarch32 at all. Although most of the aarch64 CPUs on the market other than Apple’s ones do also support aarch32, more aarch64-only processors may come out in the future.

As `arm` is widely used to identify aarch32, and aarch64 (arm64) processors may not necessarily support aarch32, it is not safe to interpret an `arm` gem as generic arm support.

**Comment by ntkme** [comment]
Ironically, although the statement in the code comment about arm is problematic, the actual implementation is fine.

The implementation matches the gem platform `arm` with runtime platform `/^arm/`. In reality this only matches `arm` (32-bit matches 32-bit) or `arm64` (only used by Mac, which is always 64-bit). It does not cause any trouble on Linux or Windows as they report as `aarch64`, and thus will not cause false positives.

**Comment by deivid-rodriguez** [comment]
Thanks for the insight! So this is just a matter of rewording the documentation, correct? Would you be willing to send us a PR?

**Comment by ntkme** [comment]
I would recommend just removing this logic. It is only useful when a gem author incorrectly publish a `arm-darwin` gem, and that is allowed to be installed on `arm64-darwin`. It does not match any other real world scenario. I've checked the rubygems index with the script below and there isn't any gem incorrectly published as `arm-darwin`. Thus this check does not do anything in practice.

``` ruby
Gem::SpecFetcher.fetcher.available_specs(:complete).each do |available_specs|
  available_specs.each do |source, specs|
    specs.each do |spec|
      if spec.platform.start_with?('arm-darwin')
        puts spec
      end
    end
  end
end
```

**Comment by deivid-rodriguez** [comment]
Ok, let's remove it then 👍.

**Comment by ntkme** [comment]
Wait a sec. I found out why this is added. It was https://github.com/rubygems/rubygems/issues/532.

Looks like some distribution has runtime `armv7-linux` instead of `arm-linux`, and removing it might cause problem. This is more complex than it is.

I think arm (32-bit) probably need to match any arm v5 - v7, but it cannot safely match armv8. I will create a PR to limit what `arm` can match against
