### ISSUE TITLE
`date` gem causes non-existent system path in standalone `setup.rb`

### ISSUE THREAD

**Issue by citrusmoose** [rubygems/rubygems#7865]
### Describe the problem as clearly as you can

Adding the `date` gem to a Gemfile and running `bundle install --standalone` causes a relative system path to be added to `setup.rb`, and that path doesn't even exist.  I'm not sure if this is specific to `date` or other system libraries (but none of the others I spot checked seemed to have this problem).  It should be noted that the `date` gem does put its `.so` in its `lib` dir, rather than the typical `extension` dir.

### Did you try upgrading rubygems & bundler?

I'm using `ruby 3.3.4` and `bundler 2.5.15`.

### Post steps to reproduce the problem

`Dockerfile`

```
FROM ruby:3.3.4

RUN gem install bundler -v 2.5.15

WORKDIR /app

RUN true \
  && echo "source 'https://rubygems.org/'" >>Gemfile \
  && echo "gem 'date', '3.3.4'" >>Gemfile \
  && bundle config set path vendor/bundle \
  && bundle lock \
  && bundle env \
  && BUNDLE_DEPLOYMENT=true bundle install --standalone \
  && cat vendor/bundle/bundler/setup.rb \
  && true
```

### Which command did you run?

`bundle install --standalone`

### What were you expecting to happen?

The relative system path not to exist in `seutp.rb`.

### What actually happened?

> $ docker build --progress=plain .
> [internal] load .dockerignore
> transferring context: 2B done
> DONE 0.0s
> 
> [internal] load build definition from Dockerfile
> transferring dockerfile: 406B done
> DONE 0.0s
> 
> [internal] load metadata for docker.io/library/ruby:3.3.4
> DONE 0.0s
> 
> [1/4] FROM docker.io/library/ruby:3.3.4
> DONE 0.0s
> 
> [2/4] RUN gem install bundler -v 2.5.15
> Successfully installed bundler-2.5.15
> 1 gem installed
> DONE 1.4s
> 
> [3/4] WORKDIR /app
> DONE 0.0s
> 
> [4/4] RUN true   && echo "source 'https://rubygems.org/'" >>Gemfile   && echo "gem 'date', '3.3.4'" >>Gemfile   && bundle config set path vendor/bundle   && bundle lock   && bundle env   && BUNDLE_DEPLOYMENT=true bundle install --standalone   && cat vendor/bundle/bundler/setup.rb   && true
> Fetching gem metadata from https://rubygems.org/.
> Resolving dependencies...
> Writing lockfile to /app/Gemfile.lock
> ## Environment
> 
> ```
> Bundler       2.5.15
>   Platforms   ruby, x86_64-linux
> Ruby          3.3.4p94 (2024-07-09 revision be1089c8ec5ba40e09b1553e36b3174bf4014d9d) [x86_64-linux]
>   Full Path   /usr/local/bin/ruby
>   Config Dir  /usr/local/etc
> RubyGems      3.5.11
>   Gem Home    /usr/local/bundle
>   Gem Path    /root/.local/share/gem/ruby/3.3.0:/usr/local/lib/ruby/gems/3.3.0:/usr/local/bundle
>   User Home   /root
>   User Path   /root/.local/share/gem/ruby/3.3.0
>   Bin Dir     /usr/local/bundle/bin
> Tools
>   Git         2.39.2
>   RVM         not installed
>   rbenv       not installed
>   chruby      not installed
> ```
> 
> ## Bundler Build Metadata
> 
> ```
> Built At          2024-07-09
> Git SHA           ee7468dc1a
> Released Version  true
> ```
> 
> ## Bundler settings
> 
> ```
> app_config
>   Set via BUNDLE_APP_CONFIG: "/usr/local/bundle"
> path
>   Set for your local app (/usr/local/bundle/config): "vendor/bundle"
> silence_root_warning
>   Set via BUNDLE_SILENCE_ROOT_WARNING: true
> ```
> 
> ## Gemfile
> 
> ### Gemfile
> 
> ```ruby
> source 'https://rubygems.org/'
> gem 'date', '3.3.4'
> ```
> 
> 
> ### Gemfile.lock
> 
> ```
> GEM
>   remote: https://rubygems.org/
>   specs:
>     date (3.3.4)
> 
> PLATFORMS
>   ruby
>   x86_64-linux
> 
> DEPENDENCIES
>   date (= 3.3.4)
> 
> BUNDLED WITH
>    2.5.15
> ```
> Fetching gem metadata from https://rubygems.org/.
> Fetching date 3.3.4
> Installing date 3.3.4 with native extensions
> Bundle complete! 1 Gemfile dependency, 2 gems now installed.
> Bundled gems are installed into `./vendor/bundle`
> ```
> require 'rbconfig'
> module Kernel
>   remove_method(:gem) if private_method_defined?(:gem)
> 
>   def gem(*)
>   end
> 
>   private :gem
> end
> unless defined?(Gem)
>   module Gem
>     def self.ruby_api_version
>       RbConfig::CONFIG["ruby_version"]
>     end
> 
>     def self.extension_api_version
>       if 'no' == RbConfig::CONFIG['ENABLE_SHARED']
>         "#{ruby_api_version}-static"
>       else
>         ruby_api_version
>       end
>     end
>   end
> end
> if Gem.respond_to?(:discover_gems_on_require=)
>   Gem.discover_gems_on_require = false
> else
>   [::Kernel.singleton_class, ::Kernel].each do |k|
>     if k.private_method_defined?(:gem_original_require)
>       private_require = k.private_method_defined?(:require)
>       k.send(:remove_method, :require)
>       k.send(:define_method, :require, k.instance_method(:gem_original_require))
>       k.send(:private, :require) if private_require
>     end
>   end
> end
> $:.unshift File.expand_path("#{__dir__}/../../../../usr/local/lib/ruby/gems/3.3.0/extensions/x86_64-linux/#{Gem.extension_api_version}/date-3.3.4")
> $:.unshift File.expand_path("#{__dir__}/../#{RUBY_ENGINE}/#{Gem.ruby_api_version}/gems/date-3.3.4/lib")
> ```
> DONE 19.1s
> 
> exporting to image
> exporting layers
> exporting layers 0.1s done
> writing image sha256:09bd1ba71cf76466968729f38e0678d798776ddebc4bfca03573d2189d4aa8dd done
> DONE 0.1s

**Comment by deivid-rodriguez** [comment]
Thanks for reporting, https://github.com/rubygems/rubygems/pull/7870 should fix this!
