### ISSUE TITLE
`bundle check` does not always return `1` when gem is missing

### ISSUE THREAD

**Issue by luispadron** [rubygems/rubygems#7885]
### Describe the problem as clearly as you can

When using `bundle check` according to the docs I would expect:

- exit code `0` iff all gems are synced and installed
- exit code `1` iff some gems are not installed
- some other exit code when something else is broken?

However, using `bundle check` will fail with an exit code of `11` if the gem points to a git repository that has not been checked out yet. This seems wrong and I would expect `bundle check` to return `1` here according to the docs.

This seems to happen because the error here: https://github.com/rubygems/rubygems/blob/36c282828d39e215eb21d94616834e6a0b459f64/bundler/lib/bundler/source/git.rb#L236 is unhandled by the `bundle check` tool.

### Did you try upgrading rubygems & bundler?

AFAICT this bug exists in the latest versions

### Post steps to reproduce the problem

- Create a gem file with a gem that points at a git repository
- Run `bundle check`
- See non-one exit code

### Which command did you run?

`bundle check`

### What were you expecting to happen?

I'd expect this to return the missing git gem and exit code of `1`.

### What actually happened?

It failed with an exit code of `11`.

### If not included with the output of your command, run `bundle env` and paste the output below

```
Bundler             2.4.10
  Platforms         ruby, arm64-darwin-23
Ruby                3.2.2p53 (2023-03-30 revision e51014f9c05aa65cbf203442d37fef7c12390015) [arm64-darwin-23]
  Full Path         /Users/<user>/.rvm/rubies/ruby-3.2.2/bin/ruby
  Config Dir        /Users/<user>/.rvm/rubies/ruby-3.2.2/etc
RubyGems            3.4.10
  Gem Home          /Users/<user>/.rvm/gems/ruby-3.2.2
  Gem Path          /Users/<user>/.rvm/gems/ruby-3.2.2:/Users/<user>/.rvm/rubies/ruby-3.2.2/lib/ruby/gems/3.2.0
  User Home         /Users/<user>
  User Path         /Users/<user>/.gem/ruby/3.2.0
  Bin Dir           /Users/<user>/.rvm/gems/ruby-3.2.2/bin
Tools
  Git               2.45.2
  RVM               1.29.12 (latest)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

**Comment by deivid-rodriguez** [comment]
That makes sense to me, would you be able to provide a PR?

**Comment by jeromedalbert** [comment]
@luispadron I can help with a PR if needed!

**Comment by luispadron** [comment]
Hi folks! I don't know that I'll have time put up a PR for this soon. 

We're working around this now by checking the error message
