### ISSUE TITLE
bundle install fails

### ISSUE THREAD

**Issue by CorySpitzer** [rubygems/rubygems#7903]
### Describe the problem as clearly as you can

 I followed along with the Rails docs for setting up a Hello, World app. I tried to run bundle install and it failed with "LoadError: linked to incompatible  - /home/cory/.ruby/gems/psych-5.1.2/lib/psych.so"
etc.

### Did you try upgrading rubygems & bundler?

Yes, it failed

Make sure you're using the latest version of both `bundler` and `rubygems`.

Running `gem update --system` should get both installed on your system, and then
`bundle update --bundler` should change your lockfile to use the new version of
bundler that was just installed.

running `gem update --system` gives

Ignoring psych-5.1.2 because its extensions are not built. Try: gem pristine psych --version 5.1.2
Ignoring stringio-3.1.1 because its extensions are not built. Try: gem pristine stringio --version 3.1.1
<internal:/home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:149:in `require': linked to incompatible ��vU - /home/cory/.ruby/gems/psych-5.1.2/lib/psych.so (LoadError)
        from <internal:/home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
        from /home/cory/.ruby/gems/psych-5.1.2/lib/psych.rb:13:in `<top (required)>'
        from <internal:/home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
        from <internal:/home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems.rb:609:in `load_yaml'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/config_file.rb:347:in `load_file'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/config_file.rb:190:in `initialize'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/gem_runner.rb:72:in `new'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/gem_runner.rb:72:in `do_configuration'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/gem_runner.rb:34:in `run'
        from /home/cory/.rbenv/versions/3.2.4/bin/gem:10:in `<main>'

It's likely that your issue has been fixed in recent versions, so just upgrading
might do the trick, and will also save us some time :)

### Which command did you run?

`bundle install`

### What were you expecting to happen?

I expected my gems to be installed

### What actually happened?

Bundler 2.4.19 is running, but your lockfile was generated with 2.1.4. Installing Bundler 2.1.4 and restarting using that version.
Ignoring psych-5.1.2 because its extensions are not built. Try: gem pristine psych --version 5.1.2
Ignoring stringio-3.1.1 because its extensions are not built. Try: gem pristine stringio --version 3.1.1
WARN: Unresolved or ambiguous specs during Gem::Specification.reset:
      stringio (>= 0)
      Available/installed versions of this gem:
      - 3.1.1
      - 3.0.4
WARN: Clearing out unresolved specs. Try 'gem cleanup <gem>'
Please report a bug if this causes problems.
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
LoadError: linked to incompatible  - /home/cory/.ruby/gems/psych-5.1.2/lib/psych.so
  <internal:/home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
  <internal:/home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
  /home/cory/.ruby/gems/psych-5.1.2/lib/psych.rb:13:in `<top (required)>'
  <internal:/home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
  <internal:/home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems.rb:609:in `load_yaml'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/config_file.rb:347:in `load_file'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/config_file.rb:190:in `initialize'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems.rb:330:in `new'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems.rb:330:in `configuration'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/fetcher.rb:254:in `connection'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/fetcher.rb:100:in `initialize'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/source/rubygems.rb:258:in `new'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/source/rubygems.rb:258:in `block in fetchers'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/source/rubygems.rb:256:in `map'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/source/rubygems.rb:256:in `fetchers'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/source/rubygems.rb:400:in `block in remote_specs'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/index.rb:9:in `build'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/source/rubygems.rb:399:in `remote_specs'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/source/rubygems.rb:133:in `specs'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/self_manager.rb:117:in `remote_specs'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/self_manager.rb:125:in `find_latest_matching_spec'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/self_manager.rb:44:in `install_and_restart_with'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/self_manager.rb:22:in `install_locked_bundler_and_restart_with_it_if_needed'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/cli/install.rb:15:in `run'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/cli.rb:261:in `block in install'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/settings.rb:130:in `temporary'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/cli.rb:260:in `install'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/libexec/bundle:37:in `block in <top (required)>'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
  /home/cory/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/libexec/bundle:29:in `<top (required)>'
  /home/cory/.rbenv/versions/3.2.4/bin/bundle:25:in `load'
  /home/cory/.rbenv/versions/3.2.4/bin/bundle:25:in `<main>'

```

## Environment

```
Bundler       2.4.19
  Platforms   ruby, x86_64-linux
Ruby          3.2.4p170 (2024-04-23 revision af471c0e0127eea0cafa6f308c0425bbfab0acf5) [x86_64-linux]
  Full Path   /home/cory/.rbenv/versions/3.2.4/bin/ruby
  Config Dir  /home/cory/.rbenv/versions/3.2.4/etc
RubyGems      3.4.19
  Gem Home    /home/cory/.ruby
  Gem Path    /home/cory/.gem/ruby/3.2.0:/home/cory/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0:/home/cory/.ruby
  User Home   /home/cory
  User Path   /home/cory/.gem/ruby/3.2.0
  Bin Dir     /home/cory/.ruby/bin
OpenSSL
  Compiled    OpenSSL 1.1.1f  31 Mar 2020
  Loaded      OpenSSL 1.1.1f  31 Mar 2020
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools
  Git         2.25.1
  RVM         not installed
  rbenv       rbenv 1.3.0-3-gbf1fcd3
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-07-27
Git SHA           unknown
Released Version  false
```

### Gemfile

```ruby
source "https://rubygems.org"

ruby "3.2.4"
# ruby "2.7.0"

# Bundle edge Rails instead: gem "rails", github: "rails/rails", branch: "main"
gem "rails", "~> 7.1.3", ">= 7.1.3.4"

# The original asset pipeline for Rails [https://github.com/rails/sprockets-rails]
gem "sprockets-rails"

# Use sqlite3 as the database for Active Record
gem "sqlite3", "~> 1.4"

# Use the Puma web server [https://github.com/puma/puma]
gem "puma", ">= 5.0"

# Use JavaScript with ESM import maps [https://github.com/rails/importmap-rails]
gem "importmap-rails"

# Hotwire's SPA-like page accelerator [https://turbo.hotwired.dev]
gem "turbo-rails"

# Hotwire's modest JavaScript framework [https://stimulus.hotwired.dev]
gem "stimulus-rails"

# Build JSON APIs with ease [https://github.com/rails/jbuilder]
gem "jbuilder"

# Use Redis adapter to run Action Cable in production
# gem "redis", ">= 4.0.1"

# Use Kredis to get higher-level data types in Redis [https://github.com/rails/kredis]
# gem "kredis"

# Use Active Model has_secure_password [https://guides.rubyonrails.org/active_model_basics.html#securepassword]
# gem "bcrypt", "~> 3.1.7"

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem "tzinfo-data", platforms: %i[ mswin mswin64 mingw x64_mingw jruby ]

# Reduces boot times through caching; required in config/boot.rb
gem "bootsnap", require: false

# Use Active Storage variants [https://guides.rubyonrails.org/active_storage_overview.html#transforming-images]
# gem "image_processing", "~> 1.2"

group :development, :test do
  # See https://guides.rubyonrails.org/debugging_rails_applications.html#debugging-with-the-debug-gem
  gem "debug", platforms: %i[ mri mswin mswin64 mingw x64_mingw ]
end

group :development do
  # Use console on exceptions pages [https://github.com/rails/web-console]
  gem "web-console"

  # Add speed badges [https://github.com/MiniProfiler/rack-mini-profiler]
  # gem "rack-mini-profiler"

  # Speed up commands on slow machines / big apps [https://github.com/rails/spring]
  # gem "spring"
end

group :test do
  # Use system testing [https://guides.rubyonrails.org/testing.html#system-testing]
  gem "capybara"
  gem "selenium-webdriver"
  gem "webdrivers"
end
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    actioncable (7.1.3.4)
      actionpack (= 7.1.3.4)
      activesupport (= 7.1.3.4)
      nio4r (~> 2.0)
      websocket-driver (>= 0.6.1)
      zeitwerk (~> 2.6)
    actionmailbox (7.1.3.4)
      actionpack (= 7.1.3.4)
      activejob (= 7.1.3.4)
      activerecord (= 7.1.3.4)
      activestorage (= 7.1.3.4)
      activesupport (= 7.1.3.4)
      mail (>= 2.7.1)
      net-imap
      net-pop
      net-smtp
    actionmailer (7.1.3.4)
      actionpack (= 7.1.3.4)
      actionview (= 7.1.3.4)
      activejob (= 7.1.3.4)
      activesupport (= 7.1.3.4)
      mail (~> 2.5, >= 2.5.4)
      net-imap
      net-pop
      net-smtp
      rails-dom-testing (~> 2.2)
    actionpack (7.1.3.4)
      actionview (= 7.1.3.4)
      activesupport (= 7.1.3.4)
      nokogiri (>= 1.8.5)
      racc
      rack (>= 2.2.4)
      rack-session (>= 1.0.1)
      rack-test (>= 0.6.3)
      rails-dom-testing (~> 2.2)
      rails-html-sanitizer (~> 1.6)
    actiontext (7.1.3.4)
      actionpack (= 7.1.3.4)
      activerecord (= 7.1.3.4)
      activestorage (= 7.1.3.4)
      activesupport (= 7.1.3.4)
      globalid (>= 0.6.0)
      nokogiri (>= 1.8.5)
    actionview (7.1.3.4)
      activesupport (= 7.1.3.4)
      builder (~> 3.1)
      erubi (~> 1.11)
      rails-dom-testing (~> 2.2)
      rails-html-sanitizer (~> 1.6)
    activejob (7.1.3.4)
      activesupport (= 7.1.3.4)
      globalid (>= 0.3.6)
    activemodel (7.1.3.4)
      activesupport (= 7.1.3.4)
    activerecord (7.1.3.4)
      activemodel (= 7.1.3.4)
      activesupport (= 7.1.3.4)
      timeout (>= 0.4.0)
    activestorage (7.1.3.4)
      actionpack (= 7.1.3.4)
      activejob (= 7.1.3.4)
      activerecord (= 7.1.3.4)
      activesupport (= 7.1.3.4)
      marcel (~> 1.0)
    activesupport (7.1.3.4)
      base64
      bigdecimal
      concurrent-ruby (~> 1.0, >= 1.0.2)
      connection_pool (>= 2.2.5)
      drb
      i18n (>= 1.6, < 2)
      minitest (>= 5.1)
      mutex_m
      tzinfo (~> 2.0)
    addressable (2.8.7)
      public_suffix (>= 2.0.2, < 7.0)
    base64 (0.2.0)
    bigdecimal (3.1.8)
    bindex (0.8.1)
    bootsnap (1.18.3)
      msgpack (~> 1.2)
    builder (3.3.0)
    capybara (3.39.2)
      addressable
      matrix
      mini_mime (>= 0.1.3)
      nokogiri (~> 1.8)
      rack (>= 1.6.0)
      rack-test (>= 0.6.3)
      regexp_parser (>= 1.5, < 3.0)
      xpath (~> 3.2)
    concurrent-ruby (1.3.3)
    connection_pool (2.4.1)
    crass (1.0.6)
    date (3.3.4)
    debug (1.9.2)
      irb (~> 1.10)
      reline (>= 0.3.8)
    drb (2.2.1)
    erubi (1.13.0)
    globalid (1.2.1)
      activesupport (>= 6.1)
    i18n (1.14.5)
      concurrent-ruby (~> 1.0)
    importmap-rails (2.0.1)
      actionpack (>= 6.0.0)
      activesupport (>= 6.0.0)
      railties (>= 6.0.0)
    io-console (0.7.2)
    irb (1.14.0)
      rdoc (>= 4.0.0)
      reline (>= 0.4.2)
    jbuilder (2.12.0)
      actionview (>= 5.0.0)
      activesupport (>= 5.0.0)
    loofah (2.22.0)
      crass (~> 1.0.2)
      nokogiri (>= 1.12.0)
    mail (2.8.1)
      mini_mime (>= 0.1.1)
      net-imap
      net-pop
      net-smtp
    marcel (1.0.4)
    matrix (0.4.2)
    mini_mime (1.1.5)
    mini_portile2 (2.8.7)
    minitest (5.24.1)
    msgpack (1.7.2)
    mutex_m (0.2.0)
    net-imap (0.3.7)
      date
      net-protocol
    net-pop (0.1.2)
      net-protocol
    net-protocol (0.2.2)
      timeout
    net-smtp (0.5.0)
      net-protocol
    nio4r (2.7.3)
    nokogiri (1.15.6)
      mini_portile2 (~> 2.8.2)
      racc (~> 1.4)
    nokogiri (1.15.6-x86_64-linux)
      racc (~> 1.4)
    psych (5.1.2)
      stringio
    public_suffix (5.1.1)
    puma (6.4.2)
      nio4r (~> 2.0)
    racc (1.8.0)
    rack (3.1.7)
    rack-session (2.0.0)
      rack (>= 3.0.0)
    rack-test (2.1.0)
      rack (>= 1.3)
    rackup (2.1.0)
      rack (>= 3)
      webrick (~> 1.8)
    rails (7.1.3.4)
      actioncable (= 7.1.3.4)
      actionmailbox (= 7.1.3.4)
      actionmailer (= 7.1.3.4)
      actionpack (= 7.1.3.4)
      actiontext (= 7.1.3.4)
      actionview (= 7.1.3.4)
      activejob (= 7.1.3.4)
      activemodel (= 7.1.3.4)
      activerecord (= 7.1.3.4)
      activestorage (= 7.1.3.4)
      activesupport (= 7.1.3.4)
      bundler (>= 1.15.0)
      railties (= 7.1.3.4)
    rails-dom-testing (2.2.0)
      activesupport (>= 5.0.0)
      minitest
      nokogiri (>= 1.6)
    rails-html-sanitizer (1.6.0)
      loofah (~> 2.21)
      nokogiri (~> 1.14)
    railties (7.1.3.4)
      actionpack (= 7.1.3.4)
      activesupport (= 7.1.3.4)
      irb
      rackup (>= 1.0.0)
      rake (>= 12.2)
      thor (~> 1.0, >= 1.2.2)
      zeitwerk (~> 2.6)
    rake (13.2.1)
    rdoc (6.7.0)
      psych (>= 4.0.0)
    regexp_parser (2.9.2)
    reline (0.5.9)
      io-console (~> 0.5)
    rexml (3.3.2)
      strscan
    rubyzip (2.3.2)
    selenium-webdriver (4.9.0)
      rexml (~> 3.2, >= 3.2.5)
      rubyzip (>= 1.2.2, < 3.0)
      websocket (~> 1.0)
    sprockets (4.2.1)
      concurrent-ruby (~> 1.0)
      rack (>= 2.2.4, < 4)
    sprockets-rails (3.5.1)
      actionpack (>= 6.1)
      activesupport (>= 6.1)
      sprockets (>= 3.0.0)
    sqlite3 (1.6.9)
      mini_portile2 (~> 2.8.0)
    sqlite3 (1.6.9-x86_64-linux)
    stimulus-rails (1.3.3)
      railties (>= 6.0.0)
    stringio (3.1.1)
    strscan (3.1.0)
    thor (1.3.1)
    timeout (0.4.1)
    turbo-rails (2.0.6)
      actionpack (>= 6.0.0)
      activejob (>= 6.0.0)
      railties (>= 6.0.0)
    tzinfo (2.0.6)
      concurrent-ruby (~> 1.0)
    web-console (4.2.1)
      actionview (>= 6.0.0)
      activemodel (>= 6.0.0)
      bindex (>= 0.4.0)
      railties (>= 6.0.0)
    webdrivers (5.3.1)
      nokogiri (~> 1.6)
      rubyzip (>= 1.3.0)
      selenium-webdriver (~> 4.0, < 4.11)
    webrick (1.8.1)
    websocket (1.2.11)
    websocket-driver (0.7.6)
      websocket-extensions (>= 0.1.0)
    websocket-extensions (0.1.5)
    xpath (3.2.0)
      nokogiri (~> 1.8)
    zeitwerk (2.6.16)

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  bootsnap
  capybara
  debug
  importmap-rails
  jbuilder
  puma (>= 5.0)
  rails (~> 7.1.3, >= 7.1.3.4)
  selenium-webdriver
  sprockets-rails
  sqlite3 (~> 1.4)
  stimulus-rails
  turbo-rails
  tzinfo-data
  web-console
  webdrivers

RUBY VERSION
   ruby 2.7.0p0

BUNDLED WITH
   2.1.4
```
But running `bundle install` a different time produced something different:

Bundler 2.4.19 is running, but your lockfile was generated with 2.1.4. Installing Bundler 2.1.4 and restarting using that version.
Ignoring psych-5.1.2 because its extensions are not built. Try: gem pristine psych --version 5.1.2
Ignoring stringio-3.1.1 because its extensions are not built. Try: gem pristine stringio --version 3.1.1
/home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/friendly_errors.rb:96:in `gsub': invalid byte sequence in UTF-8 (ArgumentError)

      <<-EOS.gsub(/^ {8}/, "")
                  ^^^^^^^^^^^
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/friendly_errors.rb:96:in `serialized_exception_for'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/friendly_errors.rb:88:in `exception_message'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/friendly_errors.rb:68:in `request_issue_report_for'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/friendly_errors.rb:50:in `log_error'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/friendly_errors.rb:123:in `rescue in with_friendly_errors'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/friendly_errors.rb:115:in `with_friendly_errors'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/libexec/bundle:29:in `<top (required)>'
        from /home/cory/.rbenv/versions/3.2.4/bin/bundle:25:in `load'
        from /home/cory/.rbenv/versions/3.2.4/bin/bundle:25:in `<main>'
<internal:/home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:149:in `require': linked to incompatible �5]=�U - /home/cory/.ruby/gems/psych-5.1.2/lib/psych.so (LoadError)
        from <internal:/home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
        from /home/cory/.ruby/gems/psych-5.1.2/lib/psych.rb:13:in `<top (required)>'
        from <internal:/home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
        from <internal:/home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:149:in `require'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems.rb:609:in `load_yaml'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/config_file.rb:347:in `load_file'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems/config_file.rb:190:in `initialize'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems.rb:330:in `new'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/rubygems.rb:330:in `configuration'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/fetcher.rb:254:in `connection'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/fetcher.rb:100:in `initialize'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/source/rubygems.rb:258:in `new'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/source/rubygems.rb:258:in `block in fetchers'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/source/rubygems.rb:256:in `map'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/source/rubygems.rb:256:in `fetchers'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/source/rubygems.rb:400:in `block in remote_specs'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/index.rb:9:in `build'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/source/rubygems.rb:399:in `remote_specs'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/source/rubygems.rb:133:in `specs'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/self_manager.rb:117:in `remote_specs'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/self_manager.rb:125:in `find_latest_matching_spec'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/self_manager.rb:44:in `install_and_restart_with'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/self_manager.rb:22:in `install_locked_bundler_and_restart_with_it_if_needed'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/cli/install.rb:15:in `run'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/cli.rb:261:in `block in install'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/settings.rb:130:in `temporary'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/cli.rb:260:in `install'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/cli.rb:34:in `dispatch'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/cli.rb:28:in `start'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/libexec/bundle:37:in `block in <top (required)>'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/3.2.0/bundler/friendly_errors.rb:117:in `with_friendly_errors'
        from /home/cory/.rbenv/versions/3.2.4/lib/ruby/gems/3.2.0/gems/bundler-2.4.19/libexec/bundle:29:in `<top (required)>'
        from /home/cory/.rbenv/versions/3.2.4/bin/bundle:25:in `load'
        from /home/cory/.rbenv/versions/3.2.4/bin/bundle:25:in `<main>'

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=linked+to+incompatible++-+%2Fhome%2Fcory%2F.ruby%2Fgems%2Fpsych-5.1.2%2Flib%2Fpsych.so&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there. -->

**Comment by deivid-rodriguez** [comment]
Do you have the `GEM_HOME` environment variable set?

**Comment by CorySpitzer** [comment]
Yes, GEM_HOME=/home/cory/.ruby/

**Comment by deivid-rodriguez** [comment]
That's the issue. You probably compiled `psych` using a different Ruby version, that are trying to reuse it with a different Ruby version. That doesn't work for extension gems. Unsetting `GEM_HOME` should do the trick. Did Rails docs tell you to set that environment variable?

**Comment by CorySpitzer** [comment]
No, they never told me to set it. I guess it was automatic. 

Unsetting fixed the problem. Now there's a beautiful wall of green. Thanks!

**Comment by deivid-rodriguez** [comment]
Cool, glad that fixed it!
