### ISSUE TITLE
Word Choices in the Template

### ISSUE THREAD

**Issue by CorySpitzer** [rubygems/rubygems#7904]
I'm not sure where to make contributions to this exact template, so I'm offering them here.
https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md

"Be as **much** clear and precise as you can."

Could remove "much," as it's unnecessary.

"Note that while you **are seeing** this issue in your computer"

Could read "Note that while you **see** this issue in your computer"

"There **is a number of** things that could influence this:"

Could read "There **are many** things that could influence this:"

"Ideally, we recommend you to set up the list of steps"

Could remove "to," as it's unnecessary.

Thanks!

**Comment by deivid-rodriguez** [comment]
Closed by #7905
