### ISSUE TITLE
Misleading error message when a non-rubygems.org source has only older releases for a gem from rubygems.org

### ISSUE THREAD

**Issue by technicalpickles** [rubygems/rubygems#7909]
I posted about this in [slack](https://bundler.slack.com/archives/C08V1RPAP/p1722345742148459), and @segiddins asked me to file an issue, so here it is 😁 

### Describe the problem as clearly as you can

We have a private gem source in addition to rubygems.org, ie:

```
source 'https://rubygems.org'

gem 'activesupport'

source('https://redacted-source/private') do
  gem 'redacted-gem' # also depends on bigdecimal
end
```

I tried to update bigdecimal, but was getting this error:

```
Resolving dependencies...
Could not find compatible versions

Because every version of redacted-gem depends on bigdecimal >= 3.1.1
  and bigdecimal >= 3.1.1 could not be found in rubygems repository https://redacted-source/private/,
  redacted-gem cannot be used.
So, because Gemfile depends on redacted-gem >= 0,
  version solving has failed.
```

The problem turned out that at some point, an earlier release of bigdecimal was pushed up to `redacted-source`. rubygems.org did have the version we were looking for

### Did you try upgrading rubygems & bundler?

Yes, both

### Post steps to reproduce the problem

I haven't confirmed this, but speculate:

- make a gemfile / gemfile.lock that locks an open source gem to a non-latest release (3.1.1)
- add a gem that depends on an open source gem (bigdecimal in my example), and push to custom source
- download the non-latest .gem file, and push  it to the custom source
- try to `bundle update --conservative bigdecimal`, and see the error

### What were you expecting to happen?

I'd have expected an error message to reflect that while the redacted-source didn't have the requested version, there was a version on another source that does match

**Comment by technicalpickles** [comment]
I'm trying to reproduce with gemstash locally, but haven't had much luck. `bundle update --conservative` fails in a different way: just not finding a later version:

```
❯ bundle update --conservative bigdecimal
Fetching gem metadata from http://localhost:9292/private/...
Fetching gem metadata from https://rubygems.org/........
Resolving dependencies...
Resolving dependencies...
Bundler attempted to update bigdecimal but its version stayed the same
Bundle updated!
```

Here's what I have for reproduction so far: https://github.com/technicalpickles/bundler-source-error-reproduction

**Comment by deivid-rodriguez** [comment]
Thanks!

I see one difference between your initial report and the repro. In the repro, the Gemfile does not depend directly on bigdecimal. In that case, I believe Bundler chooses the most specific source for bigdecimal (the private source), and that would explain the behaviour?

The behavior in the original post, I can't really explain it. If there's a direct dependency on bigdecimal from the global source, then I have no idea why Bundler is looking for it in the other source.

**Comment by technicalpickles** [comment]
Good point. I did notice that when reproducing, and ended up choosing the first gem that uses it (activesupport). Updated the body to reflect it

**Comment by deivid-rodriguez** [comment]
Aaah, I see.

Looking into it again, I do think there's a bug here. Since there's a lockfile, Bundler should respect the existing source, even if the gem is being unlocked. It doesn't seem like that's happening, given the error message.

I'll try to repro with a spec to confirm that this is what's happening.

**Comment by deivid-rodriguez** [comment]
@technicalpickles Indeed this is a bug in Bundler, working on a fix. Thanks for the nice repro!

**Comment by deivid-rodriguez** [comment]
#7915 should fix this!
