### ISSUE TITLE
bunlder 2.4 -> 2.5 starts using wrong warn method

### ISSUE THREAD

**Issue by KostyaSha** [rubygems/rubygems#7914]
### Describe the problem as clearly as you can

After upgrading 2.4.22 to 2.5.0 (or 2.5.17) on ruby 3.3.4 `bundled_gems.rb` picks wrong `warn` method.

So i have 
```ruby
module My
 def warn(msg)
 end
end
```

and if i do `require csv` it fails trying to say that it will be decoupled and fails on the next line

https://github.com/ruby/ruby/blob/f85c7deacc25738bd83ba182370c283ba82b61d4/lib/bundled_gems.rb#L74
because my warn has no second parameter.

My code starts from binstub file that loads bundler
```
require "rubygems"
require "bundler/setup"

load Gem.bin_path("mygem", "mybin")
```

### Did you try upgrading rubygems & bundler?

yeap

### Which command did you run?

`bin/mybin`

**Comment by deivid-rodriguez** [comment]
Hi, thanks for reporting. I'm unsure what's going on, but it sounds like you investigated a bit. Can you take a step further and create a test repository with instructions to reproduce the problem? Thank you 🙏.

**Comment by KostyaSha** [comment]
I tried minimise with irb, but it didn't fail. Our private project is too complex for decoupling... I can do something under debugger, but i not sure what to check.

**Comment by deivid-rodriguez** [comment]
It definitely seems due to https://github.com/rubygems/rubygems/pull/6831. If you remove all private code (except for the `warn` override), and all private gems, does it still reproduce?

**Comment by KostyaSha** [comment]
Probably i can try pick  a ruby patch and build rvm version

**Comment by deivid-rodriguez** [comment]
No worries, I managed to figure it out. See https://github.com/ruby/ruby/pull/11296.
