### ISSUE TITLE
Gem::Package::TarHeader is unable to handle negative mtime values

### ISSUE THREAD

**Issue by arianf** [rubygems/rubygems#7917]
### Describe the problem as clearly as you can

We're using `Gem::Package::TarReader` to extract `.tar` files.

We've noticed that when a tar header has a negative mtime value, `TarHeader` will raise an error.

https://github.com/rubygems/rubygems/blob/6ccc6bad93bf82b95424aa14a6667d8d06fdf768/lib/rubygems/package/tar_header.rb#L133

It raises an error because the `mtime` value is no longer an integer value.

This behavior is not the same as what `tar -xzf ./file` or using `Archive Utility` on macOS, it's able to extract these tar's just fine.

It is happening because the `mtime` value is no longer an integer, but a hexadecimal value, which is failing the following check:

https://github.com/rubygems/rubygems/blob/6ccc6bad93bf82b95424aa14a6667d8d06fdf768/lib/rubygems/package/tar_header.rb#L131

### Post steps to reproduce the problem

```bash
# I ran this on Debian, which is what docker.com/ruby are running.
touch --date=@-1000 test.txt

# to verify that works, let's check the Modify date:
stat test.txt | grep Modify
Modify: 1969-12-31 15:43:20.000000000 -0800

# then let's tar this empty test.txt file up
tar -czvf test.tar.gz ./test.txt 
# => ./test.txt
```

Now that we have our file, let's run a irb console:
```ruby
require 'zlib'
require 'rubygems/package'

Gem::Package::TarReader.new(Zlib::GzipReader.open('./test.tar.gz')).each { }
```

The resulting error:
```
/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/package/tar_reader.rb:60:in `rescue in each': "\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFC\x18" is not an octal string (Gem::Package::TarInvalidError)
        from /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/package/tar_reader.rb:55:in `each'                                             
        from (irb):9:in `<main>'                                                                                                         
        from /usr/local/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'                                              
        from /usr/local/bin/irb:25:in `load'                                                                                             
        from /usr/local/bin/irb:25:in `<main>'                                                                                           
/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/package/tar_header.rb:133:in `strict_oct': "\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFC\x18" is not an octal string (ArgumentError)
                                                                                                                                         
    raise ArgumentError, "#{str.inspect} is not an octal string"                                                                         
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^                                                                         
        from /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/package/tar_header.rb:114:in `from'                                            
        from /usr/local/lib/ruby/site_ruby/3.2.0/rubygems/package/tar_reader.rb:56:in `each'                                             
        from (irb):9:in `<main>'                                                                                                         
        from /usr/local/lib/ruby/gems/3.2.0/gems/irb-1.6.2/exe/irb:11:in `<top (required)>'                                 
        from /usr/local/bin/irb:25:in `load'                                                                                
	from /usr/local/bin/irb:25:in `<main>'
```

### Which command did you run?

```ruby
Gem::Package::TarReader.new(Zlib::GzipReader.open('./test.tar.gz')).each { }
```

### What were you expecting to happen?

On macOS when you run `tar -xvzf` you get the extract with no warnings:

```console
$ tar -xvzf /Users/arian/Downloads/test.tar.gz 
x ./test.txt

$ stat -f "%m" /Users/arian/Downloads/test.txt         
-1000

$ mdls -name kMDItemFSContentChangeDate /Users/arian/Downloads/test.txt
kMDItemFSContentChangeDate = 1969-12-31 23:43:20 +0000
```

On Debian, it'll give you a warning, but still extract the file:
```console
$ tar -xvzf  test.tar.gz 
./test.txt
tar: ./test.txt: implausibly old time stamp 1969-12-31 15:43:20
```

### What actually happened?

See the error above, but here it is again:

```ruby
"\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFC\x18" is not an octal string (Gem::Package::TarInvalidError)
```

**Comment by arianf** [comment]
I think this is how you can convert `"\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFC\x18"` to a negative number:

```ruby
mtime_string = "\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFC\x18"

byte_size = mtime_string.bytesize

number = mtime_string.unpack1('H*').to_i(16) # hexadecimal is base-16

bit_length = byte_size * 8 # 8 bits in a byte

signed_max = 1 << (bit_length - 1)

# Convert to signed integer
number -= (1 << bit_length) if number >= signed_max

number
# => -1000
```

**Comment by deivid-rodriguez** [comment]
I'm not sure but I'd say `Gem::Package::TarReader` was never intended as a general purpose `tar` reader, but just as a tool to read tar files created by rubygems when packaging gems. That said, if the change needed to make it compatible with GNU tar is relatively easy, I'm not opposed to accepting it. I wonder what others think here, particularly maintainers that have been around longer than myself like @indirect!

**Comment by indirect** [comment]
I strongly recommend that @arianf use the `tar` gem for reading or writing tar files. The `Gem::Package::TarReader` class is NOT the Ruby tar standard library, it is a library for RubyGems to read gems. :)

That said, I'm not opposed to adding support if a PR is provided and @deivid-rodriguez is ok with the idea of us incorporating it. 👍🏻

**Comment by arianf** [comment]
Totally understood, I already plan on migrating this legacy code of ours to `minitar`. As I'm sure you are already aware, this class is the top suggested for untar'ing in ruby across the internet:

* https://stackoverflow.com/questions/856891/unzip-zip-tar-tag-gz-files-with-ruby
* https://stackoverflow.com/questions/30355389/read-from-a-tar-gz-file-without-saving-the-unpacked-version
* https://stackoverflow.com/questions/34358926/how-to-extract-tar-file

**Comment by jeromedalbert** [comment]
It seems like `Gem::Package::TarReader` has been used as the unofficial built-in way to handle tar archives in Ruby, whether for good or bad reasons, as Ruby's stdlib lacks this capability.

I do not have a dog in this fight, having never needed to handle tars in Ruby. My first thought would be to use `system('tar -xvzf test.tar.gz')` as a simplistic workaround, although writing to disk may be undesirable depending on the project. My second thought is what is the use case for a file's mtime to be older than 1970-01-01, but I guess backfilling metadata representing old music records could be one.

**Comment by deivid-rodriguez** [comment]
Interesting links! I actually did not know `Gem::Package::TarReader` was the de facto standard for reading `tar` files in Ruby 😅. I guess in the future it could make sense to extract a stdlib out of this class, and make it the official way for reading tar files in Ruby.

Anyways, if you're willing to provide a PR to make this class GNU compatible, I don't mind taking it!

**Comment by segiddins** [comment]
https://github.com/rubygems/rubygems/blob/3fdc2f627e6bb476b722c7d37b61074430dea82e/lib/rubygems/package/tar_header.rb#L136 should make it a trivial thing to support

**Comment by jeromedalbert** [comment]
> https://github.com/rubygems/rubygems/blob/3fdc2f627e6bb476b722c7d37b61074430dea82e/lib/rubygems/package/tar_header.rb#L136
> 
> should make it a trivial thing to support

It may not be as trivial as using that function, at least in its current implementation. Using the mtime string mentioned by the OP:

```ruby
mtime_string = "\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFF\xFC\x18".b

Gem::Package::TarHeader.oct_or_256based(mtime_string)
# => returns 4294967295 instead of the expected -1000
```

**Comment by jeromedalbert** [comment]
> I already plan on migrating this legacy code of ours to [`minitar`](https://github.com/halostatue/minitar)

@arianf Can you confirm that this is still an issue you care about, and if so would you be willing to open a PR? Or did you find a workaround such as using minitar?

Otherwise if there is not much interest maybe we can close this issue and re-open if needed.

**Comment by deivid-rodriguez** [comment]
Let's close for now as @jeromedalbert suggested.
