### ISSUE TITLE
Feature request: output progress to stderr instead of stdout

### ISSUE THREAD

**Issue by mattbrictson** [rubygems/rubygems#7938]
Normally, when commands like `bundle lock` or `bundle outdated` are run, progress is reported to stdout, like this:

```
$ bundle lock --update
Fetching https://github.com/mattbrictson/minitest-snapshots.git
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Writing lockfile to Gemfile.lock
```

For large Gemfiles with many Git sources, this feedback is valuable, as the network operations and dependency resolution can take several seconds or more.

However, when scripting these commands or piping their output to other tools, the feedback is lost.

For example, when the `--print` flag is added:

```
$ bundle lock --update --print
```

This instructs Bundler to emit the updated lock file to stdout instead of writing it to the file. In this scenario, I would expect feedback messages to be printed to stderr, as is the convention for download progress in programs like `curl`:

stderr:

```
Fetching https://github.com/mattbrictson/minitest-snapshots.git
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
```

stdout:

```
[lockfile contents]
```

Unfortunately, passing `--print` to `bundle lock` or likewise passing `--parseable` or `--porcelain` to `bundle outdated` has the effect of silencing progress output altogether.

https://github.com/rubygems/rubygems/blob/b22914018e9c5f7b5b31eab6fa39ea4e82c623dc/bundler/lib/bundler/cli/lock.rb#L19

Ideally, progress messages should always go to stderr unless explicitly silenced with `--quiet`.

I realize this is probably a breaking change, but maybe it could be considered for 3.0?

**Comment by deivid-rodriguez** [comment]
I think this is a good idea, and I wouldn't personally call it breaking. I think we can only consider changes in output to be breaking if they modify "parseable" flags, but in this case, the parseable flags are actually somewhat broken because progress output is getting interleaved, right?

**Comment by mattbrictson** [comment]
> in this case, the parseable flags are actually somewhat broken because progress output is getting interleaved, right?

Currently, `outdated --parseable` does not output progress _at all._ It outputs a list of outdated gems to stdout, and nothing else.

I'm proposing that `outdated --parseable` output progress to stderr. So tools that were expecting parseable output on stdout would not break. They would only break if for some reason they expected stderr to be empty. For `outdated`, this might be the case, because `outdated` exits with a non-zero status if any gems are outdated. So tools might be looking at stderr to decide "did `outdated` exit non-zero because of an unexpected error? or because there are outdated gems?".

So we might need to be careful about that use case, and at least document how to distinguish between those scenarios in a backwards-compatible way.

I think the logic is:

```ruby
stdout = `bundle outdated --parseable`
raise "bundle outdated command failed" if stdout.empty? && !Process.last_status.success?
```

The change to `lock --print --update` is less likely to be considered a breaking change. Currently `lock --print --update` does not output progress and I'd like to see progress printed on stderr.

In both cases, if for some reason users of the parseable output consider the progress→stderr output undesirable or distracting, I propose they could pass `--quiet`, which would essentially make the parseable behavior work the way it does currently. Unfortunately this would not be backwards compatible, as `--quiet` is not currently an allowed option.

```
$ bundle lock --quiet --print --update
Unknown switches "--quiet"
```

**Comment by deivid-rodriguez** [comment]
Oh, good point!

Then indeed changes to `bundle outdated --parseable` are more delicate. I think each Bundler internal error has its own exit status code that's different from 0 or 1, so that would be the proper way of distinguishing error cases. We can add documentation for that 👍.

**Comment by mattbrictson** [comment]
Should I try to put a PR together? I was thinking about adding a `progress` method to the `Bundler.ui` API that would write to stderr, and then make changes like these:

```diff
diff --git bundler/lib/bundler/fetcher/base.rb bundler/lib/bundler/fetcher/base.rb
index cfec2f8e94..9ea59e420c 100644
--- bundler/lib/bundler/fetcher/base.rb
+++ bundler/lib/bundler/fetcher/base.rb
@@ -44,7 +44,7 @@ def log_specs(&block)
         if Bundler.ui.debug?
           Bundler.ui.debug yield
         else
-          Bundler.ui.info ".", false
+          Bundler.ui.progress ".", false
         end
       end
     end
diff --git bundler/lib/bundler/source/git/git_proxy.rb bundler/lib/bundler/source/git/git_proxy.rb
index 2fc9c6535f..e03e55f90d 100644
--- bundler/lib/bundler/source/git/git_proxy.rb
+++ bundler/lib/bundler/source/git/git_proxy.rb
@@ -102,7 +102,7 @@ def full_version
         def checkout
           return if has_revision_cached?
 
-          Bundler.ui.info "Fetching #{credential_filtered_uri}"
+          Bundler.ui.progress "Fetching #{credential_filtered_uri}"
 
           extra_fetch_needed = clone_needs_extra_fetch?
           unshallow_needed = clone_needs_unshallow?
diff --git bundler/lib/bundler/source/rubygems.rb bundler/lib/bundler/source/rubygems.rb
index 1085fdc2d8..bc70ed9dae 100644
--- bundler/lib/bundler/source/rubygems.rb
+++ bundler/lib/bundler/source/rubygems.rb
@@ -415,11 +415,11 @@ def remote_specs
       def fetch_names(fetchers, dependency_names, index)
         fetchers.each do |f|
           if dependency_names
-            Bundler.ui.info "Fetching gem metadata from #{URICredentialsFilter.credential_filtered_uri(f.uri)}", Bundler.ui.debug?
+            Bundler.ui.progress "Fetching gem metadata from #{URICredentialsFilter.credential_filtered_uri(f.uri)}", Bundler.ui.debug?
             index.use f.specs_with_retry(dependency_names, self)
-            Bundler.ui.info "" unless Bundler.ui.debug? # new line now that the dots are over
+            Bundler.ui.progress "" unless Bundler.ui.debug? # new line now that the dots are over
           else
-            Bundler.ui.info "Fetching source index from #{URICredentialsFilter.credential_filtered_uri(f.uri)}"
+            Bundler.ui.progress "Fetching source index from #{URICredentialsFilter.credential_filtered_uri(f.uri)}"
             index.use f.specs_with_retry(nil, self)
           end
         end
```

Is that the right approach?

**Comment by deivid-rodriguez** [comment]
I think that's a good approach 👍, happy to take a PR, we can decide on backwards compatibility details later.

**Comment by mattbrictson** [comment]
Turns out, _lots_ of Bundler's specs have assertions like:

```ruby
expect(err).to be_empty
```

That means my change to emit progress messages to stderr causes many specs to fail. I'm working through those and hope to have a  PR ready later this week.

**Comment by deivid-rodriguez** [comment]
I see! Before you start fixing a bunch of broken specs, let me confirm with the rest of the team that this is ok. @indirect @simi any concerns here?

**Comment by mattbrictson** [comment]
My first thought was to route all progress messages to stderr instead of stdout, as I sketched out in my [earlier comment](https://github.com/rubygems/rubygems/issues/7938#issuecomment-2293865809). Although the code change is small, it has a large impact because nearly every CLI operation ends up writing "Fetching..." or "Resolving..." to stderr instead of stdout. So a lot of specs are affected. Consequently it seems like the risk is high.

Given that, I am considering a very narrowly-focused alternative: route progress messages to stderr _only for `bundle lock --print` and `bundle outdated --parseable`._ This would leave the vast majority of use cases untouched, and only change behavior for those specific scenarios.

I am leaning toward the second approach, or perhaps abandoning this enhancement altogether given the unforeseen risks of modifying Bundler's output.

**Comment by deivid-rodriguez** [comment]
Yeah, in general shell status should be used for checking the outcome of `bundle` commands, but there's the risk someone is actually using "empty stderr" instead as you pointed out earlier. I think that's brittle and not really recommended for any CLI tool, since as you also pointed out, it's common for CLI tools to print progress to stderr.

I'd say it's fine to try with those commands and see if any issues come up. In particular, `bundle lock --print` seems pretty useless if progress is interleaved in the output.

**Comment by indirect** [comment]
I agree with @deivid-rodriguez. _Hopefully_ nothing is depending on empty stderr, and checking the return code instead, but it seems much safer to start by limiting the change to commands where it is actually important for usability, vs rolling out a big change and hoping it doesn't break anyone.

**Comment by deivid-rodriguez** [comment]
Cool, thanks both for not letting me be overoptimistic 😅. Let's try this change with `bundle lock --print` first. Are you ok with that @mattbrictson?

**Comment by mattbrictson** [comment]
> Let's try this change with `bundle lock --print` first.

@deivid-rodriguez yes, that sounds like a great place to start. I'll work on that.

**Comment by mattbrictson** [comment]
OK! I've opened a small, focused PR on changing just the behavior of `bundle lock --print`: #7957

**Comment by mattbrictson** [comment]
Completed via #7957 and #7966
