### ISSUE TITLE
Bundler.require(*groups) ActiveSupport::ProxyObject is deprecated

### ISSUE THREAD

**Issue by allcentury** [rubygems/rubygems#7953]
### Describe the problem as clearly as you can

In [Rails 7.2](https://github.com/rails/rails/releases/tag/v7.2.0) ActiveSupport::ProxyObject is marked as deprecated and the offending line it points to in any rails app, seems to be:

```ruby
Bundler.require(*groups)
```

Warning message is:

```
DEPRECATION WARNING: ActiveSupport::ProxyObject is deprecated and will be removed in Rails 8.0.
Use Ruby's built-in BasicObject instead.
```

### Did you try upgrading rubygems & bundler?

Yes, I'm on bundler 2.5.17

### Post steps to reproduce the problem

gem install rails -v 7.2
rails new ... 
rails c

### Which command did you run?

rails console

### What were you expecting to happen?

No warning

### What actually happened?

There was a warning

### If not included with the output of your command, run `bundle env` and paste the output below

```
RUBY VERSION
   ruby 3.3.0p0

BUNDLED WITH
   2.5.17
```

**Comment by indirect** [comment]
This warning is not coming from Bundler. Bundler is requiring the gems you have asked it to require. You should find the gem that is triggering this deprecation warning and open an issue with that gem. You can discover which gem is causing the warning by commenting out gems in your Gemfile and running `ruby -rbundler/setup -e "Bundler.require"` until you have narrowed it down.
