### ISSUE TITLE
Unnecessary error about minimum ruby version during gem install.

### ISSUE THREAD

**Issue by chriseppstein** [rubygems/rubygems#798]
Using ruby 1.8.7:

```
$ gem install listen
Fetching: timers-1.1.0.gem (100%)
Successfully installed timers-1.1.0
Fetching: celluloid-0.15.2.gem (100%)
ERROR:  Error installing listen:
	celluloid requires Ruby version >= 1.9.2.
```

Ruby 1.8.7 has not been supported since listen version 1.3.1. So using 1.8.7 that is the version that I should get when I install.

The issue here is that sass wants to support ruby 1.8.7 because that's still the default on a lot of system ruby installs but we also want to allow people to use new versions of this dependency on their new rubies if that's what they have. But if we relax our dependency requirements, the users of sass (who are not rubyists) will not be able to install sass onto 1.8.7 without specifying a version explicitly. It seems like rubygems has all the information to make this decision correctly instead of giving an error here.

**Comment by copiousfreetime** [comment]
Closing as this is a ruby 1.8.7 issue and 1.8.7 is deprecated
