### ISSUE TITLE
rubygems binstub _VERSION_ syntax prevents executables from accepting files named _foo_

### ISSUE THREAD

**Issue by postmodern** [rubygems/rubygems#799]
rubygems binstubs allow selecting which version of the gem to load by specifying the version as the first argument which begins and ends with `_`:

<pre>
#
# This file was generated by RubyGems.
#
# The application 'rdoc' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0"

if ARGV.first =~ /^_(.*)_$/ and Gem::Version.correct? $1 then
  version = $1
  ARGV.shift
end

gem 'rdoc', version
load Gem.bin_path('rdoc', 'ri', version)
</pre>

```
$ mygem _1.2.3_ --args ...
```

Unfortunately, this prevents executables from operating on file names that begin and end with `_`

```
$ mygem _some_file_
/usr/share/rubygems/rubygems/requirement.rb:90:in `parse': Illformed requirement ["some_file"] (Gem::Requirement::BadRequirementError)
    from /usr/share/rubygems/rubygems/requirement.rb:120:in `block in initialize'
    from /usr/share/rubygems/rubygems/requirement.rb:120:in `map!'
    from /usr/share/rubygems/rubygems/requirement.rb:120:in `initialize'
    from /usr/share/rubygems/rubygems/requirement.rb:55:in `new'
    from /usr/share/rubygems/rubygems/requirement.rb:55:in `create'
    from /usr/share/rubygems/rubygems/dependency.rb:58:in `initialize'
```

It is my humble opinion that it would be safer to specify the version via a environment variable.

```
$ GEM_VERSION=1.2.3 mygem _some_file_ --args ....
```

**Comment by bbrowning** [comment]
I know I'm over a year late here, but I just wanted to note that this change did break using anything but exact version in the version qualifiers. For example, you used to be able to do:

    $ rails _~\>3.2_ new foo

The "\" there is just needed for shell escaping purposes. The point is that "~> 3.2" used to be considered a valid version identifier for picking gem versions.

That no longer works and instead an exact version has to be specified, such as:

    $ rails _3.2.21_ new foo

It's not a huge problem, but is an issue I hit when updating RubyGems versions.
