### ISSUE TITLE
NoMethodError: undefined method `inflate' for module Gem

### ISSUE THREAD

**Issue by muneer78** [rubygems/rubygems#7998]
- What did you do?

  I ran the command `/Users/muneer78/.rvm/gems/ruby-3.3.4/bin/bundle update`

- What did you expect to happen?

  I expected Bundler to...

- What happened instead?

  Instead, what actually happened was...

Error details

    NoMethodError: undefined method `inflate' for module Gem
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/fetcher.rb:90:in `fetch_spec'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/remote_specification.rb:71:in `_remote_specification'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/remote_specification.rb:76:in `method_missing'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/resolver.rb:160:in `block in __dependencies'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/resolver.rb:157:in `each'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/resolver.rb:157:in `__dependencies'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/resolver.rb:112:in `activate_platform'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/resolver.rb:275:in `block in search_for'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/resolver.rb:275:in `each'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/resolver.rb:275:in `search_for'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/resolver.rb:332:in `block in verify_gemfile_dependencies_are_found!'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/resolver.rb:330:in `each'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/resolver.rb:330:in `verify_gemfile_dependencies_are_found!'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/resolver.rb:199:in `start'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/resolver.rb:183:in `resolve'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/definition.rb:198:in `resolve'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/definition.rb:137:in `specs'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/definition.rb:126:in `resolve_remotely!'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/installer.rb:194:in `resolve_if_need'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/installer.rb:69:in `run'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/installer.rb:21:in `install'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/cli/update.rb:51:in `run'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/cli.rb:197:in `update'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/invocation.rb:126:in `invoke_command'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor.rb:359:in `dispatch'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/vendor/thor/lib/thor/base.rb:440:in `start'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/cli.rb:10:in `start'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/exe/bundle:19:in `block in <top (required)>'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/lib/bundler/friendly_errors.rb:7:in `with_friendly_errors'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/gems/bundler-1.11.2/exe/bundle:17:in `<top (required)>'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/bin/bundle:25:in `load'
      /Users/muneer78/.rvm/gems/ruby-3.3.4/bin/bundle:25:in `<main>'

Environment

    Bundler   1.11.2
    Rubygems  3.5.18
    Ruby      3.3.4p94 (2024-07-09 revision be1089c8ec5ba40e09b1553e36b3174bf4014d9d) [arm64-darwin23]
    GEM_HOME  /Users/muneer78/.rvm/gems/ruby-3.3.4
    GEM_PATH  /Users/muneer78/.rvm/gems/ruby-3.3.4:/Users/muneer78/.rvm/gems/ruby-3.3.4@global
    RVM       1.29.12-next (master)
    Git       2.30.1 (Apple Git-130)
    rubygems-bundler (1.4.5)

Bundler settings

    set
      Set for the current user (/Users/muneer78/.bundle/config): "--local path vendor/bundle"

**Comment by deivid-rodriguez** [comment]
Hi! You're using an ancient Bundler. Make sure to run `bundle update --bundler` and try again. If you still get issues, feel free to reopen and post updated backtrace using Bundler 2.5.18. Thanks!
