### ISSUE TITLE
How to set a path for only a specific group of gems

### ISSUE THREAD

**Issue by ag-TJNII** [rubygems/rubygems#8036]
I'm iterating on a AWS lambda deployment, and I'm running into issues with gem management.  My Gemfile currently looks like this:

```
source 'https://rubygems.org'

gem 'httparty', '~> 0.22'
gem 'jwt', '~> 2.8'

# These gems are not needed to be installed in /vendor as they come for free in Lambda
group 'aws' do
  gem 'aws-sdk-dynamodb', '~> 1.120'
  gem 'aws-sdk-s3', '~> 1.157.0'
  # DynamoDB / AWS SDK dependency
  gem 'ox', '~> 2.14'
end

# Dev/test specific gems
group 'development' do
  gem 'rspec', '~> 3.13'
  gem 'rubocop', '~> 1.22.0'
  gem 'simplecov', '~> 0.22'
end
```

I've grouped my gems into 3 logical groups:

- Top level gems, which are always needed
- AWS gems, which are only needed local
- development gems, which are only needed for test / lint

Since this is running in a lambda I need to include the top level gems in `vendor/bundle` for the code to run.  [Per AWS](https://docs.aws.amazon.com/lambda/latest/dg/ruby-package.html) the recommended command for this is `bundle config set --local path 'vendor/bundle'`.  I do not want to include the AWS or development gems in `vendor/` as they're not needed in the lambda (AWS gems are already present) and bloat the deployment badly.  To accomplish this I can set `without` to exclude `aws:development`, to get a config file like so:

```
---
BUNDLE_PATH: "vendor/bundle"
BUNDLE_WITHOUT: "aws:development"
```

Now if I run `bundle install` it only installs the gems the Lambda needs into vendor/bundle.  This works for the lambda use case, but it's project wide.  For example, with this config if I run rspec:

```
$ bundle exec rspec -fd --fail-fast
bundler: failed to load command: rspec (/home/tom/.rbenv/versions/3.3.4/bin/rspec)
/home/tom/.rbenv/versions/3.3.4/lib/ruby/site_ruby/3.3.0/bundler/rubygems_integration.rb:265:in `block in replace_bin_path': can't find executable rspec for gem rspec-core. rspec-core is not currently included in the bundle, perhaps you meant to add it to your Gemfile? (Gem::Exception)
```

Which makes sense as I just configured bundler to not install rspec.  At this point my understanding of the process starts to fall apart.  If I run bundler with command line arguments it prints warnings like:

```
[DEPRECATED] The `--with` flag is deprecated because it relies on being remembered across bundler invocations, which bundler will no longer do in future versions. Instead please use `bundle config set with 'development'`, and stop using this flag
```

But, I need bundler to behave with two different modes.  I need one mode to only install the lambda gems into `vendor/` for vendoring, and then I need it to also behave like normal to install gems for dev/test.  In the [config manual](https://bundler.io/v2.5/man/bundle-config.1.html) I don't see any options for this.

I think what I want is some kind of a profile.  I must be missing something as setting a project wide setting to enable/disable groups seems to defeat the purpose of declaring groups at all.  How are settings like this meant to be selected?  Can I set something like a profile that says "With the lambda profile apply the `BUNDLE_PATH: "vendor/bundle"` and `BUNDLE_WITHOUT: "aws:development"`, but otherwise do not apply these settings"?

### `bundle env` (Paths sanitized)

```
Bundler       2.5.17
  Platforms   ruby, x86_64-linux
Ruby          3.3.4p94 (2024-07-09 revision be1089c8ec5ba40e09b1553e36b3174bf4014d9d) [x86_64-linux]
  Full Path   [HOME]/.rbenv/versions/3.3.4/bin/ruby
  Config Dir  [HOME]/.rbenv/versions/3.3.4/etc
RubyGems      3.5.17
  Gem Home    [HOME]/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0
  Gem Path    [HOME]/.gem/ruby/3.3.0:[HOME]/.rbenv/versions/3.3.4/lib/ruby/gems/3.3.0
  User Home   [HOME]
  User Path   [HOME]/.gem/ruby/3.3.0
  Bin Dir     [HOME]/.rbenv/versions/3.3.4/bin
Tools
  Git         2.39.2
  RVM         not installed
  rbenv       rbenv 1.2.0-100-gbf1fcd3
  chruby      not installed
```

## Bundler Build Metadata

```
Built At          2024-08-01
Git SHA           74d92b2502
Released Version  true
```

## Bundler settings

```
path
  Set for your local app ([HOME]/[PROJECT]/.bundle/config): "vendor/bundle"
without
  Set for your local app ([HOME]/[PROJECT]/.bundle/config): [:aws, :development]
```

### Gemfile

```ruby
source 'https://rubygems.org'

gem 'httparty', '~> 0.22'
gem 'jwt', '~> 2.8'

# These gems are not needed to be installed in /vendor as they come for free in Lambda
group 'aws' do
  gem 'aws-sdk-dynamodb', '~> 1.120'
  gem 'aws-sdk-s3', '~> 1.157.0'
  # DynamoDB / AWS SDK dependency
  gem 'ox', '~> 2.14'
end

# Dev/test specific gems
group 'development' do
  gem 'rspec', '~> 3.13'
  gem 'rubocop', '~> 1.22.0'
  gem 'simplecov', '~> 0.22'
end
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    ast (2.4.2)
    aws-eventstream (1.3.0)
    aws-partitions (1.976.0)
    aws-sdk-core (3.205.0)
      aws-eventstream (~> 1, >= 1.3.0)
      aws-partitions (~> 1, >= 1.651.0)
      aws-sigv4 (~> 1.9)
      jmespath (~> 1, >= 1.6.1)
    aws-sdk-dynamodb (1.122.0)
      aws-sdk-core (~> 3, >= 3.205.0)
      aws-sigv4 (~> 1.5)
    aws-sdk-kms (1.91.0)
      aws-sdk-core (~> 3, >= 3.205.0)
      aws-sigv4 (~> 1.5)
    aws-sdk-s3 (1.157.0)
      aws-sdk-core (~> 3, >= 3.201.0)
      aws-sdk-kms (~> 1)
      aws-sigv4 (~> 1.5)
    aws-sigv4 (1.9.1)
      aws-eventstream (~> 1, >= 1.0.2)
    base64 (0.2.0)
    bigdecimal (3.1.8)
    csv (3.3.0)
    diff-lcs (1.5.1)
    docile (1.4.1)
    httparty (0.22.0)
      csv
      mini_mime (>= 1.0.0)
      multi_xml (>= 0.5.2)
    jmespath (1.6.2)
    jwt (2.9.0)
      base64
    mini_mime (1.1.5)
    multi_xml (0.7.1)
      bigdecimal (~> 3.1)
    ox (2.14.18)
    parallel (1.26.3)
    parser (3.3.5.0)
      ast (~> 2.4.1)
      racc
    racc (1.8.1)
    rainbow (3.1.1)
    regexp_parser (2.9.2)
    rexml (3.3.7)
    rspec (3.13.0)
      rspec-core (~> 3.13.0)
      rspec-expectations (~> 3.13.0)
      rspec-mocks (~> 3.13.0)
    rspec-core (3.13.1)
      rspec-support (~> 3.13.0)

    rspec-expectations (3.13.3)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.13.0)
    rspec-mocks (3.13.1)
      diff-lcs (>= 1.2.0, < 2.0)
      rspec-support (~> 3.13.0)
    rspec-support (3.13.1)
    rubocop (1.22.3)
      parallel (~> 1.10)
      parser (>= 3.0.0.0)
      rainbow (>= 2.2.2, < 4.0)
      regexp_parser (>= 1.8, < 3.0)
      rexml
      rubocop-ast (>= 1.12.0, < 2.0)
      ruby-progressbar (~> 1.7)
      unicode-display_width (>= 1.4.0, < 3.0)
    rubocop-ast (1.32.3)
      parser (>= 3.3.1.0)
    ruby-progressbar (1.13.0)
    simplecov (0.22.0)
      docile (~> 1.1)
      simplecov-html (~> 0.11)
      simplecov_json_formatter (~> 0.1)
    simplecov-html (0.13.1)
    simplecov_json_formatter (0.1.4)
    unicode-display_width (2.6.0)

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  aws-sdk-dynamodb (~> 1.120)
  aws-sdk-s3 (~> 1.157.0)
  httparty (~> 0.22)
  jwt (~> 2.8)
  ox (~> 2.14)
  rspec (~> 3.13)
  rubocop (~> 1.22.0)
  simplecov (~> 0.22)

BUNDLED WITH
   2.5.17
```

**Comment by deivid-rodriguez** [comment]
Can you add the `without` configuration only to your lambda package?

**Comment by indirect** [comment]
More generally, the way Bundler handles "profiles" is via environment variables. When you are doing local development, don't set any special configuration. When you are creating the packaged files that will be deployed to lambda, set the path and without options, either using `bundle set` or using env vars. When you are running the package on lambda, be sure to include the `.bundle/config` file if you used `bundle set`, or be sure to set the same env vars if you used those.

**Comment by ag-TJNII** [comment]
> More generally, the way Bundler handles "profiles" is via environment variables. 

Okay, so instead of command line arguments I should be adjusting the behavior with ENV vars, that makes sense.  I'll set these settings in the environment in the pipeline that makes the lambda deployment zipfile.  That answers the spirit of the question, with the deprecation warnings I wanted to make sure I was inline with the intended direction of the project.  Thanks!
