### ISSUE TITLE
Use of flock can cause problems on some NFS shares

### ISSUE THREAD

**Issue by dark-panda** [rubygems/rubygems#806]
I've recently had a problem with installing gems to home directories that have been mounted over NFS on a cluster of linux servers. It seems that `flock` does not work over NFS in some situations, namely on older kernels. The recent calls to `flock` added in the more recent versions of rubygems is thus causing gem installs to hang on some systems where NFS is being used. 

Here's my situation and setup:

- group of linux servers running CentOS 5, Ruby 2.1.0, linux kernel  2.6.18 with home directories mounted off of a central NFS server.

- the calls to `flock` in `remote_fetcher.rb` and in `rubygems.rb` hang when used against the file systems mounted via NFS.

According to http://nfs.sourceforge.net/#faq_d10 , some support for NFS was added to flock in kernel 2.6.12, although I'm having no luck with the RHEL version 2.6.18 that CentOS 5 ships with. 

It might be worth looking into creating separate lock files rather than trying to lock the file itself with `flock`. This would involve creating and detecting the existence of a separate file and not relying on `flock` at all.

**Comment by djberg96** [comment]
See https://github.com/rubygems/rubygems/pull/1327

**Comment by djberg96** [comment]
Closing, best we can do.
