### ISSUE TITLE
Under bundler, `Bundler::StubSpecification#activated?` returns false after activation

### ISSUE THREAD

**Issue by Earlopain** [rubygems/rubygems#8068]
### Describe the problem as clearly as you can

Without bundler, I can do the following to understand if a gem is activated:

```rb
$ irb
irb(main):001> Gem::Specification.stubs.to_a.find { _1.name == "rainbow" }.activated?
=> nil
irb(main):002> gem "rainbow"
=> true
irb(main):003> Gem::Specification.stubs.to_a.find { _1.name == "rainbow" }.activated?
=> true
```

I would like to to the same with bundler, however I currently have to do a bit more to make that work.

### Did you try upgrading rubygems & bundler?

Yes, Bundler 2.5.20, Rubygems 3.5.20

### Post steps to reproduce the problem

* gem install rainbow
* Create a Gemfile with rainbow and lock
* Run the following in `irb`:
  ```rb
  gem "rainbow"
  Gem::Specification.stubs.to_a.find { _1.name == "rainbow" }.activated?
  # => true
  ```
* Run the following in `bundle exec irb`
  ```rb
  gem "rainbow"
  Gem::Specification.stubs.to_a.find { _1.name == "rainbow" }.activated?
  # => false
  ```
* However:
  ```rb
  gem "rainbow"
  Gem::Specification.stubs.to_a.find { _1.name == "rainbow" }.stub.activated?
  # => true
  ```

### Possible solution

I think there is a type in the code here: https://github.com/rubygems/rubygems/blob/c63c4b0305de7a5712436d37decca648b14b0091/bundler/lib/bundler/stub_specification.rb#L48-L50

I'm somewhat confident that should be `activated?` instead, since calling `activated` raises `NoMethodError` and `activated?`  now just delegates to the `RemoteSpecification`:
https://github.com/rubygems/rubygems/blob/c63c4b0305de7a5712436d37decca648b14b0091/bundler/lib/bundler/remote_specification.rb#L112-L114

However, it could also just be that checking in the stub is expected. I'm not sure on the relation of all these classes and what they really mean.

**Comment by deivid-rodriguez** [comment]
Hi @Earlopain. I think you analysis makes sense and this is typo. Can you create a PR fixing it?

The `Bundler::StubSpecification` class is just a wrapper over RubyGems `Gem::StubSpecification` that it's available to add a "source" to it and potentially fetch information missing locally from the remote source.
