### ISSUE TITLE
Bundler 2.5.20 Possibly Broke Git-Sourced, Cached Gems?

### ISSUE THREAD

**Issue by stevenharman** [rubygems/rubygems#8069]
### Describe the problem as clearly as you can

Last night a nightly job started breaking. That job builds a base image used for running our Rails monolith in CI. The error message reported is:

```
Git error: command `git rev-parse --is-bare-repository` in directory /root/preinstalled-gems/vendor/cache/activerecord-session_store-7743696dbcbd has failed.
fatal: not a git repository (or any of the parent directories): .git
```

The `activerecord-session_store` Gem is added as a Git-sourced dependency in our `Gemfile`:

```ruby
# Gemfile
gem 'activerecord-session_store', github: 'docsend/activerecord-session_store', branch: 'optional-insecure-session-fallback'
```

That dependency has been pinned like that for some time. No changes there.

However, the `Dockerfile` we use to build that base image does install a fresh Bundler each time it builds. So last night, it started picking up Bundler version `2.5.20`. I verified this update broke our build by instead pinning the version installed by the `Dockerfile` to `2.5.19`. And once I did that, we were again able to build our base image.

Looking through the [CHANGELOG for 2.5.20](https://github.com/rubygems/rubygems/blob/master/bundler/CHANGELOG.md#2520-september-24-2024) I noticed "Ensure refs directory in cached git source #8047". Which sure sounds like it's probably related.

### Did you try upgrading rubygems & bundler?

The problem is with the latest bundler.

### Post steps to reproduce the problem

I don't have full steps, nor a minimally reproducible example. If really needed, I can try to get something together. For now, here's where the `Dockerfile` is failing.

```docker file
# Pre-install Gems into a dir that we later Symlink into the Rails app's
# ./vendor/bundle during CI's "setup" step thus pre-baking most Gems into the
# base image. Only any changes since the nightly build need to be installed.
RUN gem install bundler --no-document && \
    bundle config set --local deployment "true" && \
    bundle config set --local path "vendor/bundle" && \
    bundle check || bundle install --local --retry=3 && \
    bundle clean && \
    rm -rf vendor/cache && rm Gemfile*
```

### What were you expecting to happen?

This works with Bundler < 2.5.20.

### What actually happened?

When using Bundler 2.5.20, we see the following log lines:

```
 > [stage-5  9/17] RUN gem install bundler --no-document &&     bundle config set --local deployment "true" &&     bundle config set --local path "vendor/bundle" &&     bundle check || bundle install --local --retry=3 &&     bundle clean &&     rm -rf vendor/cache && rm Gemfile*:
0.693 Successfully installed bundler-2.5.20
0.693 1 gem installed
1.217 Bundler can't satisfy your Gemfile's dependencies.
1.217 Install missing gems with `bundle install`.
1.362 Don't run Bundler as root. Installing your bundle as root will break this
1.362 application for all non-root users on this machine.
5.000 Git error: command `git rev-parse --is-bare-repository` in directory
5.000 /root/preinstalled-gems/vendor/cache/activerecord-session_store-7743696dbcbd has
5.000 failed.
5.000 fatal: not a git repository (or any of the parent directories): .git
------
```

**Comment by deivid-rodriguez** [comment]
Hei @stevenharman, thanks for reporting. Yeah, if you can put up a reproducible example, that'd be great!

**Comment by stevenharman** [comment]
@deivid-rodriguez I tried to un-pin our app from 2.5.19, moving to the latest 2.5.23 and I'm still seeing an error, but it's changed. One of our git-sourced dependencies is from a private repo, and trying to install that on CI fails:

```
 > [stage-5  9/17] RUN gem install --no-document &&     bundle config set --local deployment "true" &&     bundle config set --local path "vendor/bundle" &&     bundle check || bundle install --local --retry=3 &&     bundle clean &&     rm -rf vendor/cache && rm Gemfile*:
9.723 fatal: could not read Password for 'https://****************************************@github.com': No such device or address
9.803 
9.804 Git error: command `git clone --bare --no-hardlinks --quiet --no-tags
9.804 --single-branch --
9.804 https://****************************************@github.com/docsend/<REDACTED>.git
9.804 /root/preinstalled-gems/vendor/cache/<REDACTED>-7e40eeeb44b4` in directory
9.804 /root/preinstalled-gems/vendor/cache/<REDACTED>-7e40eeeb44b4 has failed.
9.804 fatal: could not read Password for
9.804 'https://****************************************@github.com': No such device or
9.804 address
------

Similarly, it looks like Bundler is fetching all of our git-based Gems from the internet, as just before the above failure log lines, we see this:

```
#25 [stage-5  9/17] RUN gem install --no-document &&     bundle config set --local deployment "true" &&     bundle config set --local path "vendor/bundle" &&     bundle check || bundle install --local --retry=3 &&     bundle clean &&     rm -rf vendor/cache && rm Gemfile*
#25 8.724 Fetching https://github.com/docsend/activerecord-session_store.git
#25 9.091 Fetching https://github.com/stevenharman/puma-plugin-telemetry.git
#25 9.464 Fetching https://github.com/docsend/<REDACTED>.git
```

So something is amiss. Bunder should not be hitting the Internet for any of those as they are already in `vendor/cache`.

Interestingly, if I locally deleted the Gem's folder from `bundle/cache` and then re-run `bundle`, it will use the new "bare clone" format. Adding that to git and running on CI and that gem is no longer fetched from the Internet. Repeating for all of our get-sourced Gems does the same.

New bug? Related to this one?

**Comment by deivid-rodriguez** [comment]
I think you'll still need one "remote" run to migrate the cache to the new format. I don't think `--local` will work with the old format. That said, we got recently reported [an issue](https://github.com/rubygems/rubygems/issues/8217) with the new format. I'm unsure what to do about it because I feel the only way to get that working again would be to go back to the previous format 🙈.

**Comment by stevenharman** [comment]
> you'll still need one "remote" run to migrate the cache to the new format

I'm not exactly sure I follow. Locally I'd deleted the `vendor/cache` directory that contained the old checkout and then ran `bundle install`, which seems to have fetched it in the new format. I then committed that and pushed up to CI. Is there a different set of steps I need to do?

And will that need to be done for all git-sourced dependencies? I tried it with one of our non-private dependencies and now see a different error:

```
 > [stage-5  9/17] RUN gem install bundler --no-document &&     bundle config set --local deployment "true" &&     bundle config set --local path "vendor/bundle" &&     bundle check || bundle install --local --retry=3 &&     bundle clean &&     rm -rf vendor/cache && rm Gemfile*:
1.704 Install missing gems with `bundle install`.
1.904 Don't run Bundler as root. Installing your bundle as root will break this
1.904 application for all non-root users on this machine.
6.968 Git error: command `git fetch --force --quiet
6.968 /root/preinstalled-gems/vendor/cache/puma-plugin-telemetry-51cd78814b6e --depth
6.968 1 51cd78814b6e59b28f53ed19f5385faf2fdc037d` in directory
6.968 /root/preinstalled-gems/vendor/bundle/ruby/3.1.0/bundler/gems/puma-plugin-telemetry-51cd78814b6e
6.968 has failed.
6.968 error: Server does not allow request for unadvertised object
6.968 51cd78814b6e59b28f53ed19f5385faf2fdc037d
------
```

> I'm unsure what to do about it because I feel the only way to get that working again would be to go back to the previous format.

I wonder if we need to revisit the reason for switching formats and see if there's another way to tackle it? Or see if we can figure out a way to successfully migrate folks - which feels like something that's missing right now, yeah?

**Comment by deivid-rodriguez** [comment]
> I'm not exactly sure I follow. Locally I'd deleted the vendor/cache directory that contained the old checkout and then ran bundle install, which seems to have fetched it in the new format. I then committed that and pushed up to CI. Is there a different set of steps I need to do?

Oh sorry, I misunderstood your comment. Then this sounds like a bug. I think we got a similar report in Slack. If you can provide a reproducible example I can take a look.

> I wonder if we need to revisit the reason for switching formats and see if there's another way to tackle it? 

Yep, ideally we find a different way to tackle the original issue (git caches being broken for gems with extensions) without changing the cache format.

**Comment by stevenharman** [comment]
@deivid-rodriguez I was able to pull together a minimal reproduction and [put it here](https://github.com/stevenharman/bundler_git_cache_bug_maybe). One thing I noticed while making this that I couldn't trigger the error I mentioned in my last message:

```
error: Server does not allow request for unadvertised object
```

I did see a different error, though I think maybe that makes sense since I had a "new structure" in the cache, but was accidentally still using an older Bundler version.

Either way, this example does show the (maybe bug) where newer bundlers are still fetching cached gems from the remote, despite them being in `vendor/cache`.

I'm really not sure where this leave us, other than, as we've said before, feeling like maybe it's best to go back to the old cache structure?

**Comment by deivid-rodriguez** [comment]
I will have a look and think about it, thanks for the repro!

**Comment by stevenharman** [comment]
Well, crap. It turns out the new cache format will totally break when deployed to Heroku (#8274).

**Comment by deivid-rodriguez** [comment]
Right. Thanks for reporting that too. I'll try to have a closer look soon.
