### ISSUE TITLE
Local server cannot be accessed neither with plain HTTP nor with SSL

### ISSUE THREAD

**Issue by BertramScharpf** [rubygems/rubygems#8093]
I'm rolling out some self-written software as Ruby Gems on a local server. This worked perfectly for at least 15 years. Since Rubygems 3.5.19 it is no longer accepted. My `.gemrc` contains this:

    :sources:
    - https://rubygems.org/
    - http://localmachine/gems/

And this is the Rubygems output:

    # gem update
    Updating installed gems
    Updating mycoolgem
    ERROR:  Error installing mycoolgem:
            Unable to resolve dependency: user requested 'mycoolgem (= 2.12)'
    Nothing to update

I tried to offer `https://localmachine:443` and to set in the `.gemrc`:

    :ssl_verify_mode: "0"

but this doesn't work either:

    # gem update
    ERROR:  SSL verification error at depth 0: self-signed certificate (18)
    ERROR:  Certificate /C=DE/... is not trusted
    Updating installed gems
    Updating mycoolgem
    ERROR:  Error installing mycoolgem:
            Unable to resolve dependency: user requested 'mycoolgem (= 2.12)'
    Nothing to update

I definitely asked to trust the server but RubyGems ignores it. At least this should be considered a bug.

I searched the Rubygems documentation and even the source code for an option to disable the SSL requirement but I didn't find anything. Nor does the running program give any hint.

**Comment by deivid-rodriguez** [comment]
Hello 👋!

The only potential change in 3.5.19 that I think could be related is https://github.com/rubygems/rubygems/pull/8006. I fixed an issue with that in https://github.com/rubygems/rubygems/pull/8080, which I will be releasing soon.

I assume that will fix this problem, so let me optimistically close this. Once I release RubyGems 3.5.21, please try it and reopen if not really fixed!

**Comment by BertramScharpf** [comment]
I admit that I had indeed a broken server configuration. Yet, this just rather revealed the problem than causing it. After fixing my server, the remaining problem is that updates cannot be done because my server doesn't offer the gem in question. This here fixes my issue:

    --- original/site_ruby/3.3/rubygems/resolver/composed_set.rb
    +++ site_ruby/3.3/rubygems/resolver/composed_set.rb
    @@ -53,6 +53,8 @@
       def find_all(req)
         @sets.map do |s|
           s.find_all req
    +    rescue Gem::RemoteFetcher::FetchError
    +      []
         end.flatten
       end

**Comment by deivid-rodriguez** [comment]
Did you try the latest version? We shipped https://github.com/rubygems/rubygems/pull/8080, which may have fixed the issue.

**Comment by BertramScharpf** [comment]
FreeBSD:

    # pkg info | grep gems
    ruby33-gems-3.5.20             Package management framework for the Ruby language

Arrgh! I was so glad about yesterdays update that I confused 20 with 21.

I manually merged the 3.5.21 changes into the `/usr/local/lib/ruby/site_ruby/3.3` directory. Now it works. Thank you.

**Comment by deivid-rodriguez** [comment]
I'm glad it worked! And also glad that even if this regression was inconvenient, it helped you fix your server configuration!
