### ISSUE TITLE
Gems do not support sbin

### ISSUE THREAD

**Issue by jamtur01** [rubygems/rubygems#81]
I have executables that belong in sbin, according to the LSB (they're daemons), but Gems don't seem to support this,
and I can't seem to find a way to hack it, even.

Currently, all of my packagers are having to work around this limitation, which means instead of a small amount of work
in one package, it's a big hack in 4 other packages.

It would be great if an 'sbindir' option were added to Gems.

See http://rubyforge.org/tracker/?func=detail&atid=578&aid=11604&group_id=126.

**Comment by djberg96** [comment]
Three years, no patch, time to close I'm afraid.
