### ISSUE TITLE
Gem::Specification#gem_dir incorrect for development gem

### ISSUE THREAD

**Issue by ivoanjo** [rubygems/rubygems#8108]
Hey! First of all, thanks a lot for all the amazing work y'all put into maintaining rubygems :pray: :bow:.

### Describe the problem as clearly as you can

I would at Datadog maintaining the [`datadog` (previously `ddtrace` gem)](https://github.com/datadog/dd-trace-rb). I was testing our gem test suite with the latest Ruby gems, and it started failing due to I change I bisected in Rubygems.

Specifically #8030 made the `#gem_dir` do this for a gem that's being developed in the current folder (e.g. loaded via `gemspec` in the `Gemfile`):

```
$ pwd
/home/ivo.anjo/datadog/dd-trace-rb
$ bundle exec ruby -e "require 'datadog'; puts Gem.loaded_specs['datadog'].gem_dir"
/home/ivo.anjo/datadog/gems/datadog-2.3.0
$ gem -v
3.6.0.dev
```

This folder does not exist and thus some of our specs fail because they were using `gem_dir` to assert that a few file paths were in well-known locations.

As a reference, here's how it looks in the latest stable rubygems:

```
$ bundle exec ruby -e "require 'datadog'; puts Gem.loaded_specs['datadog'].gem_dir"
/home/ivo.anjo/datadog/dd-trace-rb
$ gem -v
3.5.21
```

I don't think we're misusing `gem_dir` for this usage, but happy to replace it with something more appropriate, if we're holding it wrong. For reference [this is the spec that started failing](https://github.com/DataDog/dd-trace-rb/blob/master/spec/datadog/profiling/native_extension_helpers_spec.rb#L19)

### Did you try upgrading RubyGems?

Yup, I bisected this using Ruby 3.1 just as a second check, and 3.1 also fails after #3080 was merged.

### Post steps to reproduce the problem

```
$ git clone git@github.com:DataDog/dd-trace-rb.git
$ bundle install
$ bundle exec ruby -e "require 'datadog'; puts Gem.loaded_specs['datadog'].gem_dir"
```

### Which command did you run?

```
$ bundle exec ruby -e "require 'datadog'; puts Gem.loaded_specs['datadog'].gem_dir"
```

### What were you expecting to happen?

Correct path output

### What actually happened?

A non-existing path was returned

### Run `gem env` and paste the output below

```
RubyGems Environment:
  - RUBYGEMS VERSION: 3.6.0.dev
  - RUBY VERSION: 3.4.0 (2024-10-07 patchlevel -1) [x86_64-linux]
  - INSTALLATION DIRECTORY: /home/ivo.anjo/.rvm/gems/ruby-head
  - USER INSTALLATION DIRECTORY: /home/ivo.anjo/.gem/ruby/3.4.0+0
  - RUBY EXECUTABLE: /home/ivo.anjo/.rvm/rubies/ruby-head/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /home/ivo.anjo/.rvm/gems/ruby-head/bin
  - SPEC CACHE DIRECTORY: /home/ivo.anjo/.gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /home/ivo.anjo/.rvm/rubies/ruby-head/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /home/ivo.anjo/.rvm/gems/ruby-head
     - /home/ivo.anjo/.rvm/rubies/ruby-head/lib/ruby/gems/3.4.0+0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
      # ...
```

**Comment by deivid-rodriguez** [comment]
Hello @ivoanjo. Thanks for the kind words and for trying out our latest code!

I'm not fully sure why this is happening, but I went with an alternative that does not have the issue.
