### ISSUE TITLE
Gem contents subcommand seems to yield wrong output for default gem

### ISSUE THREAD

**Issue by BertramScharpf** [rubygems/rubygems#8119]
I detected that the `gem contents` command yields file paths that don't exist.

    # uname
    FreeBSD
    # gem --version
    3.5.21

I have a look at this gem:

    # gem list bundler
    *** LOCAL GEMS ***
    bundler (2.5.21, default: 2.5.18)

The presence of the version 2.5.21 files can be confirmed:

    # gem contents bundler -v 2.5.21 | wc -l
        336
    # for c in `gem contents bundler -v 2.5.21 ` ; do [ -f "$c" ] && echo exists: $c ; done  | wc -l
        336
    # gem contents bundler -v 2.5.21 | tail -n 5
    /usr/local/lib/ruby/gems/3.3/gems/bundler-2.5.21/lib/bundler/vendored_uri.rb
    /usr/local/lib/ruby/gems/3.3/gems/bundler-2.5.21/lib/bundler/version.rb
    /usr/local/lib/ruby/gems/3.3/gems/bundler-2.5.21/lib/bundler/vlad.rb
    /usr/local/lib/ruby/gems/3.3/gems/bundler-2.5.21/lib/bundler/worker.rb
    /usr/local/lib/ruby/gems/3.3/gems/bundler-2.5.21/lib/bundler/yaml_serializer.rb

Yet, the version 2.5.18 files reside in a different place than told by Gems:

    # gem contents bundler -v 2.5.18 | wc -l
        343
    # for c in `gem contents bundler -v 2.5.18 ` ; do [ -f "$c" ] && echo exists: $c ; done | wc -l
          0
    # gem contents bundler -v 2.5.18 | tail -n 5
    /usr/local/lib/ruby/3.3/lib/bundler/vendored_uri.rb
    /usr/local/lib/ruby/3.3/lib/bundler/version.rb
    /usr/local/lib/ruby/3.3/lib/bundler/vlad.rb
    /usr/local/lib/ruby/3.3/lib/bundler/worker.rb
    /usr/local/lib/ruby/3.3/lib/bundler/yaml_serializer.rb

Here's where the files reside:

    # find /usr/local/lib/ruby/site_ruby/3.3/bundler | sort | tail -n 5
    /usr/local/lib/ruby/site_ruby/3.3/bundler/vendored_uri.rb
    /usr/local/lib/ruby/site_ruby/3.3/bundler/version.rb
    /usr/local/lib/ruby/site_ruby/3.3/bundler/vlad.rb
    /usr/local/lib/ruby/site_ruby/3.3/bundler/worker.rb
    /usr/local/lib/ruby/site_ruby/3.3/bundler/yaml_serializer.rb
    # grep 'VERSION.*freeze' /usr/local/lib/ruby/site_ruby/3.3/bundler/version.rb
      VERSION = "2.5.18".freeze

Is there something I don't understand, is it FreeBSD or is it a problem of Gems?

**Comment by deivid-rodriguez** [comment]
This is a bug in RubyGems, thanks for reporting!

**Comment by deivid-rodriguez** [comment]
#8132 should fix this 👍.
