### ISSUE TITLE
RubyGems 3.5.21 cannot load nexus_command

### ISSUE THREAD

**Issue by roberts1000** [rubygems/rubygems#8120]
### Describe the problem as clearly as you can

After running `gem install nexus`, I can run `gem nexus pkg/something.gem` to push a gem up to Nexus. Before RubyGems 3.5.21, this worked as expected. On RubyGems 3.5.21, I get the following error:

```
$ gem nexus pkg/something.gem
ERROR:  Loading command: nexus (LoadError)
        connect load such file -- rubygems/commands/nexus_command
```

If I downgrade to RubyGems 3.5.20

```
$ gem update --system 3.5.20
$ gem -v
3.5.20
```

then run it again, it works:

```
$ gem nexus pkg/something.gem
Uploading 1 gem to Nexus ...
Created something.gem
```

Reinstalling the `nexus` gem doesn't help.

### Did you try upgrading RubyGems?

Yes. RubyGems 3.5.21 is currently the latest.

### Post steps to reproduce the problem

See above

### Which command did you run?

See above

### What were you expecting to happen?

See above

### What actually happened?

See above 

### Run `gem env` and paste the output below

`gem env` output between RubyGems 3.5.20 and 3.5.21 is identical expect for the `RUBYGEMS VERSION:` line.

**Comment by deivid-rodriguez** [comment]
Oh, good, I'm sorry. I completely misunderstood how plugin commands work and completely broke this in 95f60f0e60614ac2397cd0debdafa07c0b72c1ef. I'll fix this and make a quick release. Thanks for the quick report.

**Comment by roberts1000** [comment]
Thanks for the quick fix!
