### ISSUE TITLE
`gem` command silently refuses to uninstall `jar-dependencies` for jruby-9.4.8.0

### ISSUE THREAD

**Issue by hurricup** [rubygems/rubygems#8134]
This was broken somewhere between rubygems 3.3.26 and rubygems 3.5.21 (first works as expected)
Repro steps (mine, but pretty sure other works as well, this fails on every version manager we test):
1. Install an rvm 
2. Install jruby-9.4.8.0
3. run `gem update --system` so you would have rubygems 3.5.21
4. jruby has a default gem `jar-depndencies:0.4.1`
5. create a `Gemfile`
```
source 'https://rubygems.org'

gem 'rails', '<= 7.0.8'
gem 'activesupport', '<= 7.0.8'
gem 'minitest'
gem 'shoulda'
gem 'minitest-spec-rails'
gem 'psych', "!= 5.1.1" if RUBY_PLATFORM == 'java'
```
6. run `bundle install`
7. ensure that other copy of `jar-dependencies:0.4.1` was installed (it should be available in bundler output and user gems path, e.g. `/usr/share/rvm/gems/jruby-9.4.8.0/gems`). So now we have 2 copies of those: default and not.
8. run `gem uninstall -a -x -I -V --backtrace date:3.3.4 net-smtp:0.5.0 net-imap:0.4.16 minitest:5.25.1 net-protocol:0.2.2 timeout:0.4.1 psych:5.1.2 minitest-spec-rails:7.3.0 racc:1.8.1 shoulda-context:2.0.0 shoulda-matchers:4.5.1 jar-dependencies:0.4.1 shoulda:4.0.0 net-pop:0.1.2`
9. Get output:
```
Successfully uninstalled net-pop-0.1.2
Successfully uninstalled shoulda-4.0.0
Successfully uninstalled shoulda-matchers-4.5.1
Removing convert_to_should_syntax
Successfully uninstalled shoulda-context-2.0.0
Successfully uninstalled racc-1.8.1-java
Successfully uninstalled minitest-spec-rails-7.3.0
Successfully uninstalled psych-5.1.2-java
Successfully uninstalled minitest-5.25.1
Successfully uninstalled net-imap-0.4.16
Successfully uninstalled net-smtp-0.5.0
Successfully uninstalled net-protocol-0.2.2
Successfully uninstalled timeout-0.4.1
Successfully uninstalled date-3.3.4-java
```
All gems were uninstalled but `jar-dependencies`. No warnings no nothing. 
you may use one of our test images for reproduction: `docker run --rm -it rubymine/test_environment:rvm-single-ssh-jruby bash -l`

**Comment by deivid-rodriguez** [comment]
Hi @hurricup, thanks for the report!

Coincidentially, https://github.com/rubygems/rubygems/pull/8131, which I opened yesterday, will fix this.
