### ISSUE TITLE
shebang problem when installing gem executable into non-standard location with --install-dir on an --enable-load-relative ruby

### ISSUE THREAD

**Issue by NicholasBHubbard** [rubygems/rubygems#8135]
I ran into the following problem which I thought was a variation of #2929, however I was informed that that issue had been fixed long ago.

# Steps to reproduce

### First build an --enable-load-relative ruby and use it to install a gem (in this case fpm) to a non-standard location with --install-dir
```
$ mkdir -p tmp/share
$ cd tmp
$ wget https://cache.ruby-lang.org/pub/ruby/3.3/ruby-3.3.5.tar.gz
$ tar -xf ruby-3.3.5.tar.gz
$ cd ruby-3.3.5
$ ./autogen.sh
$ ./configure --enable-load-relative --prefix $(realpath ../share)
$ make
$ make install
$ cd ..
$ mkdir gems
$ share/bin/gem install --install-dir gems fpm
```
### When I try to use the gem though I get the following error
```
$ gems/bin/fpm --version
gems/bin/fpm: 6: exec: gems/bin/ruby: not found
```
### The problem can be seen by inspecting the top of the `gems/bin/fpm` executable
```
$ head -n 16 gems/bin/fpm 
#!/bin/sh
# -*- ruby -*-
_=_\
=begin
bindir="${0%/*}"
exec "$bindir/ruby" "-x" "$0" "$@"
=end
#!/tmp/share/bin/ruby
#
# This file was generated by RubyGems.
#
# The application 'fpm' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'
```

This shows that this executable expects ruby to be in the same directory as itself.

### Workaround

During gem installation if I use the gem configuration file option `custom_shebang: $ruby`, then it just puts the path to the executing ruby interpreter as the shebang on the installed gem executable, and all is well (assuming GEM_PATH points at the custom gem dir).

**Comment by deivid-rodriguez** [comment]
Nice repro @NicholasBHubbard, thanks!

I think https://github.com/rubygems/rubygems/pull/7872 may fix this?
