### ISSUE TITLE
"gem install [XYZ]" does not suggest all useful names

### ISSUE THREAD

**Issue by rubyFeedback** [rubygems/rubygems#8176]
I just tried this:

    gem install taglib

The result was:

    ERROR:  Could not find a valid gem 'taglib' (>= 0) in any repository
    ERROR:  Possible alternatives: taglob, taglib2, rtaglib, tomlib, tdlib,
    tass-lib, talis, taglog, taglish, tagline # I added a newline ^^^ here,
                                              # for ease of display

However had, the gem I wanted was called "taglib-ruby". This name was 
not suggested under "Possible alternatives: ", even though such a gem
does actually exist ... **hmm**. \o/ \o? \o’

So:

    gem install taglib-ruby

Would work. But it was not suggested in the alternatives.

I do not know the code, but could an explicit "if gem name starts with XYZ", aka "taglib",
also suggest alternatives? I assume the code currently does not check for "-" following
immediately the given query name (in my case above "taglib"), so perhaps this could be
added as well. Could someone have a look at the code logic? I think "taglib-ruby" should
be a valid suggestion to make. (If it only subselects from an array, perhaps that array
can be extended by one or two more entries; or specifically via a ".start_with?" check, for
similarly named cases such as "taglib-ruby", aka "SEARCH_QUERY-ruby" or "SEARCH_QUERY-anythingElseHere".

Gem homepage of taglib-ruby is here: https://rubygems.org/gems/taglib-ruby

The underlying C++ library is called "taglib", which I assume is one reason why this
is called "taglib-ruby". (I myself would not have chosen that as a gem name, but it 
is not my project so not under my control.)

Edit: I see that "tass-lib" is suggested, which includes a '-', but to me it is very confusing
why the query "taglib" leads to "tass-lib", but not to "taglib-ruby". Would not the latter
be a morea realistic similarly named alternative? How is the distinction made here, 
to prioritize "tass-lib" rather than "taglib-ruby"? Is that using the levensthein distance
or so? If so then we should perhaps add an additional check for the same name first,
**before** checking for **every** character. Otherwise we'd get "tass-lib" rather than
"taglib-ruby". I haven't counted the levensthein distances here, so perhaps taglib-ruby
loses, but the substring match is "taglib", which is six characters matching for the given
input query being "taglib", whereas for "tass", only 2 characters match, there are two
mismatches, and 2 gaps (the trailing "ib").

Edit 2: I am not suggesting to make the logic too complicated, actually, just trying to
understanding the logic here indirectly. In my issue request, a simple same-name
subquery (e. g. all gems **starting** with the same query name, in this case "taglib")
could be **prioritized**. That would be a fairly simple fix, e. g. add  one if clause
before, to check for .start_with?() and adding it to the array of suggestions to be made.

**Comment by deivid-rodriguez** [comment]
Apparently we used to give this result, but we no longer do after https://github.com/rubygems/rubygems/pull/8083/. Summoning @martinemde and @duckinator for their thoughts.

**Comment by duckinator** [comment]
Thanks for the report, @rubyFeedback!

I agree, it should suggest `taglib-ruby`.

Some background/explanation on how it works, since you seem interested in that:

The current code works on levenshtein distance (number of one-character edits), so `taglib` -> `taslib` -> `tasslib` -> `tass-lib` is 3 changes, but `taglib` -> `taglib-ruby` is 5 changes (it just appends `-ruby` one character at a time), so oddly enough `tass-lib` is ranked higher.

Prior to #8083, there was additional code trying to do something _similar_ to what you suggested, but it just used `.include?` and so gave a lot of nonsense results (e.g. `gem install railss` => `capistrano-rails-synchronizer`).

Given the code also has significant performance issues _and_ bizarre results I opted for simplifying it as a first step.

**I have an in-progress PR over at #8084 for speeding up suggestions. I'll try to wrap that up next week. Once that's done I'll look into improving the results for cases like this.** :slightly_smiling_face:

**Comment by duckinator** [comment]
I just wrapped up working on #8084. Just waiting for someone else to review it.

**Comment by martinemde** [comment]
I do wonder if this is just a special case. Should this also return "tagline-fake-extension-name" because you clearly did not type anything close to that.

The `-ruby` suffix might just be the only case where there is a common set of matching names that would exceed the typo distance.

**Comment by duckinator** [comment]
Yeah, the `-ruby` suffix and `ruby-` prefix are really common. I think it might make sense to special-case exact matches for `#{name}-ruby` and `ruby-#{name}` so they get included despite the normal algorithm rejecting them.

**Comment by duckinator** [comment]
Made a PR addressing this, over at #8197.

**Comment by duckinator** [comment]
@rubyFeedback sorry for the delay on my side of things, but #8197 was just merged and addresses this!
