### ISSUE TITLE
bundle install --local with default gems tries to install them again

### ISSUE THREAD

**Issue by eregon** [rubygems/rubygems#8179]
```
$ ruby -v
ruby 3.3.5 (2024-09-03 revision ef084cc8f4) [x86_64-linux]
$ bundle --version
Bundler version 2.5.16
$ gem list | grep -E 'abbrev|bigdecimal'
abbrev (default: 0.1.2)
bigdecimal (default: 3.1.5)
$ cat Gemfile
source 'https://rubygems.org'

gem "abbrev", "0.1.2"
gem "bigdecimal", "3.1.5"
$ bundle install --local
Resolving dependencies...
Fetching gem metadata from https://rubygems.org/.
Fetching abbrev 0.1.2
Installing abbrev 0.1.2
Fetching bigdecimal 3.1.5
Installing bigdecimal 3.1.5 with native extensions
Bundle complete! 2 Gemfile dependencies, 3 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```

As a note I reinstalled a fresh ruby 3.3.5 with:
```
rm -rf ~/.rubies/ruby-3.3.5
ruby-build ruby-3.3.5 -d ~/.rubies
```
to ensure it's exactly the same as the release archive.

```
$ ls -l
total 8
-rw-r--r--. 1 eregon eregon  79 Oct 23 14:30 Gemfile
-rw-r--r--. 1 eregon eregon 200 Oct 23 14:35 Gemfile.lock
```
so that shows there is no `vendor` dir created (as expected, I don't have any Bundler config set for the above)

### Describe the problem as clearly as you can

I would expect default and bundled gems to not be reinstalled since they are already installed.
Also even more problematic, `--local` seems completely ignored here.

### Did you try upgrading rubygems & bundler?

No, because we are updating to Ruby 3.3.5 and corresponding RubyGems & Bundler in TruffleRuby and so need to get these versions to work in our CI. Using a different version of RubyGems or Bundler would likely cause incompatibility with CRuby and also require extra approvals.

## Environment

```
Bundler       2.5.16
  Platforms   ruby, x86_64-linux
Ruby          3.3.5p100 (2024-09-03 revision ef084cc8f4958c1b6e4ead99136631bef6d8ddba) [x86_64-linux]
  Full Path   /home/eregon/.rubies/ruby-3.3.5/bin/ruby
  Config Dir  /home/eregon/.rubies/ruby-3.3.5/etc
RubyGems      3.5.16
  Gem Home    /home/eregon/.rubies/ruby-3.3.5/lib/ruby/gems/3.3.0
  Gem Path    /home/eregon/.gem/ruby/3.3.0:/home/eregon/.rubies/ruby-3.3.5/lib/ruby/gems/3.3.0
  User Home   /home/eregon
  User Path   /home/eregon/.gem/ruby/3.3.0
  Bin Dir     /home/eregon/.rubies/ruby-3.3.5/bin
Tools         
  Git         2.46.2
  RVM         not installed
  rbenv       not installed
  chruby      0.3.9
```

## Bundler Build Metadata

```
Built At          2024-10-23
Git SHA           unknown
Released Version  false
```

### Gemfile

```ruby
source 'https://rubygems.org'

gem "abbrev", "0.1.2"
gem "bigdecimal", "3.1.5"
```

### Gemfile.lock

```
GEM
  remote: https://rubygems.org/
  specs:
    abbrev (0.1.2)
    bigdecimal (3.1.5)

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  abbrev (= 0.1.2)
  bigdecimal (= 3.1.5)

BUNDLED WITH
   2.5.16
```

**Comment by eregon** [comment]
I had previously noticed this issue with this config: `bundle config --global path vendor/bundle` but now it seems to happen even with no Bundler config at all.

**Comment by deivid-rodriguez** [comment]
Just verified and this is also fixed in the latest version. Please upgrade before reporting issues.

**Comment by eregon** [comment]
Unfortunately upgrading is not really an option, see this part of the report:

> Did you try upgrading rubygems & bundler?

No, because we are updating to Ruby 3.3.5 and corresponding RubyGems & Bundler in TruffleRuby and so need to get these versions to work in our CI. Using a different version of RubyGems or Bundler would likely cause incompatibility with CRuby and also require extra approvals.

We'll have to disable some tests in TruffleRuby due to this bug.

**Comment by deivid-rodriguez** [comment]
> No, because we are updating to Ruby 3.3.5 and corresponding RubyGems & Bundler in TruffleRuby and so need to get these versions to work in our CI. Using a different version of RubyGems or Bundler would likely cause incompatibility with CRuby and also require extra approvals.

Upgrade separately in a different environment to verify if the bug is fixed in the latest version. If the reporter wants something fixed, I assume it will upgrade when fixed. It makes no sense to report a bug to a piece of software that you refuse to upgrade.

**Comment by eregon** [comment]
Right, I should have tried with latest Bundler, sorry.
I tried with TruffleRuby, confirmed it also happens on CRuby 3.3.5 (latest release from 2024-09-03, which should have a reasonably recent RubyGems & Bundler) but didn't try installing latest Bundler on CRuby.
