### ISSUE TITLE
Something went wrong with gems after last Arch linux full system update

### ISSUE THREAD

**Issue by levaconline** [rubygems/rubygems#8182]
### Describe the problem as clearly as you can
I'm not sure what went wrong after last full system update. I'm I crushed gems? Any suggestion/solution?

ruby -v
ruby 3.2.5 (2024-07-26 revision 31d0f1a2e7) [x86_64-linux]

### Which command did you run?
Many...
1.
vagrant reload
`RubyGems' were not loaded.
/opt/vagrant/embedded/gems/gems/vagrant-2.4.1/bin/vagrant:89:in `<main>': uninitialized constant Gem::Specification (NameError)

vagrant_spec = Gem::Specification.find_all_by_name("vagrant").detect do |spec|
                  ^^^^^^^^^^^^^^^

2.
gem query --local
`RubyGems' were not loaded.
/usr/bin/gem:10:in `require': cannot load such file -- rubygems/gem_runner (LoadError)
Did you mean?  rubygems/defaults/operating_system
	from /usr/bin/gem:10:in `<main>'

3.
gem update --system
`RubyGems' were not loaded.
/usr/bin/gem:10:in `require': cannot load such file -- rubygems/gem_runner (LoadError)
Did you mean?  rubygems/defaults/operating_system
	from /usr/bin/gem:10:in `<main>'

### What actually happened?
Not sure. After full system update (Arch linux: yay -Syu) obviously something went wrong with gems.

### Run `gem env` and paste the output below
gem env
`RubyGems' were not loaded.
/usr/bin/gem:10:in `require': cannot load such file -- rubygems/gem_runner (LoadError)
Did you mean?  rubygems/defaults/operating_system
	from /usr/bin/gem:10:in `<main>'

**Comment by deivid-rodriguez** [comment]
Hi.

The `RubyGems' were not loaded` error comes from [Ruby itself](https://github.com/ruby/ruby/blob/4755d28f9b2aba730563547ae44abcc5af0bc46f/gem_prelude.rb#L1-L10) and means that RubyGems is not in your `$LOAD_PATH`.  That means Arch Linux Ruby is essentially broken. I suggest to report this to Arch Linux.

I'll close this now since I don't think this is a RubyGems issues, but feel free to link to this issue anyways from the Arch Linux report.

Good luck!

**Comment by christian-heusel** [comment]
There already is an issue reported with Arch Linux and vagrant: https://gitlab.archlinux.org/archlinux/packaging/packages/vagrant/-/issues/3

Maybe it's related to the one above one 😅 

>  That means Arch Linux Ruby is essentially broken

I don't think that's the case, I think that is a problem specific to this system 😊

**Comment by levaconline** [comment]
Ah, it seems "newer ending story". Arch sending me to ask CachyOS (regardless it is removed from my Arch linux time ago). It seems it is time for me to start playing the "Russian roulette".
https://bbs.archlinux.org/viewtopic.php?pid=2204599#p2204599

**Comment by levaconline** [comment]
Notice for people for similar issue. Problem was not in removed CachyOS. Problem is in Vagrant which does not work with newer versions of Ruby. So, Ruby must be in IgnorePKG. Since Ruby was in ignore list, Good knows what versions of gems must be ignored/downgraded. Those info I couldn't find in vagrant documentation. 
So, Ruby and ruby-rexm were in ignore list, but other gems Arch upgraded regularly which caused issue once when Ruby lost compatibility with it's old gems.

As [christian-heusel](https://github.com/christian-heusel) mentioned true address for issue is Vagrant, not CachyOS (which was removed long rime ago).
https://github.com/rubygems/rubygems/issues/8182#issuecomment-2436306910

**Comment by levaconline** [comment]
Question for ruby gems may be if anybody know which gems fir to Ruby version: ruby 3.2.5 (2024-07-26 revision 31d0f1a2e7) [x86_64-linux]

Currently my gem list is following and  versions does not fit to Vagrant only working version of Ruby 3.2.5

Here is my current list of gems and I don;t know to which version to downgrade them to fit to Ruby 3.2.5?

```
gem query --local  
WARNING:  query command is deprecated. It will be removed in Rubygems 4.
WARNING:  It is recommended that you use `gem search` or `gem list` instead.

*** LOCAL GEMS ***

abbrev (default: 0.1.2)
base64 (default: 0.2.0)
benchmark (default: 0.3.0)
bigdecimal (default: 3.1.5)
bundler (default: 2.5.16)
cgi (default: 0.4.1)
csv (default: 3.2.8)
date (default: 3.3.4)
debug (1.9.1)
delegate (default: 0.3.1)
did_you_mean (default: 1.6.3)
digest (default: 3.1.1)
drb (default: 2.2.0)
english (default: 0.8.0)
erb (default: 4.0.4 ruby)
error_highlight (default: 0.6.0)
etc (default: 1.4.3)
fcntl (default: 1.1.0)
fiddle (default: 1.1.2)
fileutils (default: 1.7.2)
find (default: 0.2.0)
forwardable (default: 1.3.3)
getoptlong (default: 0.2.1)
io-console (default: 0.7.1)
io-nonblock (default: 0.3.0)
io-wait (default: 0.3.1)
ipaddr (default: 1.2.6)
irb (default: 1.13.1)
json (default: 2.7.1)
logger (default: 1.6.0)
matrix (0.4.2)
minitest (5.22.3)
mutex_m (default: 0.2.0)
net-ftp (0.3.5)
net-http (default: 0.4.1)
net-imap (0.4.12)
net-pop (0.1.2)
net-protocol (default: 0.2.2)
net-smtp (0.5.0)
nkf (default: 0.1.3)
observer (default: 0.1.2)
open-uri (default: 0.4.1)
open3 (default: 0.2.1)
openssl (default: 3.2.0)
optparse (default: 0.4.0)
ostruct (default: 0.6.0)
pathname (default: 0.3.0)
power_assert (2.0.3)
pp (default: 0.5.0)
prettyprint (default: 0.2.0)
prime (0.1.2)
prism (default: 0.19.0)
pstore (default: 0.1.3)
psych (default: 5.1.2)
racc (default: 1.7.3)
rake (13.1.0)
rbs (3.4.4)
rdoc (default: 6.6.3.1)
readline (default: 0.0.4)
reline (default: 0.5.7)
resolv (default: 0.3.0)
resolv-replace (default: 0.1.1)
rexml (3.3.2)
rinda (default: 0.2.0)
rss (0.3.1)
ruby2_keywords (default: 0.0.5)
securerandom (default: 0.3.1)
set (default: 1.1.0)
shellwords (default: 0.2.0)
singleton (default: 0.2.0)
stringio (default: 3.1.1)
strscan (default: 3.0.9)
syntax_suggest (default: 2.0.0)
syslog (default: 0.1.2)
tempfile (default: 0.2.1)
test-unit (3.6.2)
time (default: 0.3.0)
timeout (default: 0.4.1)
tmpdir (default: 0.2.0)
tsort (default: 0.2.0)
typeprof (0.21.9)
un (default: 0.3.0)
uri (default: 0.13.1)
weakref (default: 0.1.3)
yaml (default: 0.3.0)
zlib (default: 3.1.1)

```
Obviously, Vagrant demand huge list if gems in IgnorePKG.

**Comment by deivid-rodriguez** [comment]
Thanks for following up and linking to arch linux vagrant package issue. List of default gems for each Ruby can be checked at https://stdgems.org/.

**Comment by levaconline** [comment]
Thank you [deivid-rodriguez](https://github.com/deivid-rodriguez)  It seems it can be helpful. I can't understand why Vagrant can't sync (or release new version of Vagrant compatible with recent Ruby/gems?!
I already asked ChatGPT but it was snot so helpful. Link you sent me, give hope.

Just in case here is what chatgpt told me (from whole list i sent to chatgpt, it found only 3 gems compatible with Ruby 3.2.5).

————————

> Here are the compatible versions for the gems you mentioned with Ruby 3.2.5:
> 
> ### 1. Bundler
> - Compatible Version: Bundler 2.2.x and earlier versions should work well with Ruby 3.2.5.
> - Latest Recommended Version: 2.2.33 is a stable version to use.
> 
> ### 2. JSON
> - Compatible Version: JSON gem version 2.6.x is generally compatible with Ruby 3.2.5.
> - Latest Recommended Version: 2.6.3 is a good choice.
> 
> ### 3. Minitest
> - Compatible Version: Minitest version 5.14.x and earlier are compatible with Ruby 3.2.5.
> - Latest Recommended Version: 5.14.4 is a stable version.
> 
> ### Downgrading Instructions
> If you need to downgrade these gems, you can do so with the following commands:
> 
> gem uninstall bundler
> gem install bundler -v '2.2.33'
> 
> gem uninstall json
> gem install json -v '2.6.3'
> 
> gem uninstall minitest
> gem install minitest -v '5.14.4'
> 
> These versions should ensure compatibility with Ruby 3.2.5. If you have more gems to check or need further assistance, just let me know!

————————

> 5. Consult Documentation
> 
> There isn't a single definitive document that lists all gem versions compatible with Ruby 3.2.5, but you can gather information from the following sources:
> 
>     RubyGems.org: For each gem, check the specific versions and their metadata.
>     GitHub Repositories: Many gems have their changelogs that detail compatibility.
>     Ruby Version Management: Tools like RVM or rbenv can sometimes help with managing different Ruby environments and their respective gems.

Thank you again!

**Comment by Arooj-web-developer** [comment]
RubyGems Environment:
  - RUBYGEMS VERSION: 3.4.19
  - RUBY VERSION: 3.2.3 (2024-01-18 patchlevel 157) [x86_64-linux]
  - INSTALLATION DIRECTORY: /root/.local/share/mise/installs/ruby/3.2.3/lib/ruby/gems/3.2.0
  - USER INSTALLATION DIRECTORY: /root/.local/share/gem/ruby/3.2.0
  - RUBY EXECUTABLE: /root/.local/share/mise/installs/ruby/3.2.3/bin/ruby
  - GIT EXECUTABLE: /usr/bin/git
  - EXECUTABLE DIRECTORY: /root/.local/share/mise/installs/ruby/3.2.3/bin
  - SPEC CACHE DIRECTORY: /root/.local/share/gem/specs
  - SYSTEM CONFIGURATION DIRECTORY: /root/.local/share/mise/installs/ruby/3.2.3/etc
  - RUBYGEMS PLATFORMS:
     - ruby
     - x86_64-linux
  - GEM PATHS:
     - /root/.local/share/mise/installs/ruby/3.2.3/lib/ruby/gems/3.2.0
     - /root/.local/share/gem/ruby/3.2.0
  - GEM CONFIGURATION:
     - :update_sources => true
     - :verbose => true
     - :backtrace => true
     - :bulk_threshold => 1000
  - REMOTE SOURCES:
     - https://rubygems.org/
  - SHELL PATH:
     - /root/.local/share/mise/installs/ruby/3.2.3/bin
     - /root/.local/share/mise/installs/node/22.11.0/bin
     - /root/.local/bin
     - /usr/local/sbin
     - /usr/local/bin
     - /usr/sbin
     - /usr/bin
     - /sbin
     - /bin
     - /usr/games
     - /usr/local/games
     - /mnt/c/Program Files/WindowsApps/CanonicalGroupLimited.Ubuntu_2404.1.66.0_x64__79rhkp1fndgsc
     - /mnt/c/Program Files
     - /mnt/c/Winnt
     - /mnt/c/Windows/System32
     - /mnt/d/-php 16-x64
     - /mnt/d/nodejs/
     - /mnt/d/my matlab/runtime/win64
     - /mnt/d/my matlab/bin
     - /mnt/d/New folder/Scripts/
     - /mnt/d/New folder/
     - /mnt/c/Users/Admin/AppData/Local/Microsoft/WindowsApps
     - /mnt/c/Users/Admin/.dotnet/tools
     - /mnt/c/Users/Admin/AppData/Local/Programs/Microsoft VS Code
     - /mnt/c/Users/Admin/AppData/Local/Programs/Microsoft VS Code/bin
     - /mnt/c/Users/Admin/AppData/Roaming/npm
     - /snap/bin
     - /usr/local/bin
     - /usr/local/bin
     - /root/.local/share/mise/installs/ruby/3.2.3/bin/ruby
