### ISSUE TITLE
Windows bash use - binstubs fail to be found via which

### ISSUE THREAD

**Issue by MSP-Greg** [rubygems/rubygems#8185]
### Describe the problem as clearly as you can

Not sure if this is a problem coming from `make install` or RubyGems.

The 'prolog' in the bash binstubs is:
```text
:""||{ ""=> %q<-*- ruby -*-
@"%~dp0ruby" -x "%~f0" %*
@exit /b %ERRORLEVEL%
};{ #
bindir="${0%/*}" #
exec "$bindir/ruby" "-x" "$0" "$@" #
>,
}
```

Part of this file is WIndows bat/cmd code.  This causes bash's `which` command to not be able to find the script.  Note that `bundle -v` does work.

I shortened the 'prolog' to the below, and `which` can find the file, and `bundle -v` also works.
```text
#!
bindir="${0%/*}" #
exec "$bindir/ruby" "-x" "$0" "$@"
```

### Did you try upgrading RubyGems?

Using `ruby 3.4.0dev (2024-10-25T14:52:22Z master 05f894aba2) +PRISM [x64-mingw-ucrt]`

### Post steps to reproduce the problem

Install a 'proper' Windows Ruby, switch to a bash shell, and run `which bundle`

**Comment by deivid-rodriguez** [comment]
Hi! This is a `make install` thing. See https://github.com/ruby/ruby/blob/eb1e1d99b79baab18595ff6a2a159d3b5cc1645a/tool/rbinstall.rb#L412-L417.

RubyGems does not generate `.cmd` binstubs, I wonder if Ruby could do the same.

Can you report this to https://bugs.ruby-lang.org and reference this issue?
