### ISSUE TITLE
error message installing bundle from command line 

### ISSUE THREAD

**Issue by DOkuwa** [rubygems/rubygems#8201]
### Describe the problem as clearly as you can

`The` problem is running this command 
azureuser@Daley-DB bin]$ bundle install --gemfile=/usr/local/rvm/src/ruby-3.0.0/.bundle/gems/rake-13.0.3/Gemfile
 and the error message is below 
Another error message occurs 
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=You+don%27t+have+write+permissions+for+the+%2Fusr%2Flocal%2Frvm%2Fgems%2Fruby-3.0.0%2Fwrappers+directory.&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in `there.`

**Comment by deivid-rodriguez** [comment]
Hi. Could you please copy the actual error message? I think the error is truncated and lacks a lot of information.

**Comment by deivid-rodriguez** [comment]
Please reopen once you provide the requested information 👍.

**Comment by DOkuwa** [comment]
`[azureuser@Daley-DB bin]$ bundle install --gemfile=/usr/local/rvm/src/ruby-3.0.0/.bundle/gems/rake-13.0.3/Gemfile
Another error message occurs 
Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=You+don%27t+have+write+permissions+for+the+%2Fusr%2Flocal%2Frvm%2Fgems%2Fruby-3.0.0%2Fwrappers+directory.&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there`

**Comment by deivid-rodriguez** [comment]
Is that really all you get? What's the output of `bundle env`?

**Comment by DOkuwa** [comment]
`bundle env
## Environment

```
Bundler             2.5.22
  Platforms         ruby, x86_64-linux
Ruby                3.0.0p0 (2020-12-25 revision 95aff214687a5e12c3eb57d056665741e734c188) [x86_64-linux]
  Full Path         /usr/local/rvm/rubies/ruby-3.0.0/bin/ruby
  Config Dir        /usr/local/rvm/rubies/ruby-3.0.0/etc
RubyGems            3.2.3
  Gem Home          /usr/local/rvm/gems/ruby-3.0.0
  Gem Path          /usr/local/rvm/gems/ruby-3.0.0:/usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0
  User Home         /home/azureuser
  User Path         /home/azureuser/.local/share/gem/ruby/3.0.0
  Bin Dir           /usr/local/rvm/gems/ruby-3.0.0/bin
Tools
  Git               2.43.5
  RVM               1.29.12 (latest)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2024-10-16
Git SHA           342d4542fda
Released Version  true`

**Comment by deivid-rodriguez** [comment]
Can you run `gem uninstall rubygems-bundler` and try again?

**Comment by DOkuwa** [comment]
`[azureuser@Daley-DB bin]$ bundle install --gemfile=/usr/local/rvm/src/ruby-3.0.0/.bundle/gems/rake-13.0.3/Gemfile
fatal: not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
Gem::FilePermissionError: You don't have write permissions for the /usr/local/rvm/gems/ruby-3.0.0/wrappers directory.
  /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers/installer.rb:26:in `ensure'
          /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/gem-wrappers-1.4.0/lib/gem-wrappers.rb:19:in `install'
          /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0/gems/gem-wrappers-1.4.0/lib/rubygems_plugin.rb:15:in `block in <top (required)>'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/source/path/installer.rb:43:in `block in run_hooks'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/source/path/installer.rb:42:in `each'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/source/path/installer.rb:42:in `run_hooks'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/source/path/installer.rb:34:in `post_install'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/source/path.rb:234:in `generate_bin'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/source/path.rb:78:in `install'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/installer/gem_installer.rb:55:in `install'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/installer/gem_installer.rb:17:in `install_from_spec'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/installer/parallel_installer.rb:133:in `do_install'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/installer/parallel_installer.rb:87:in `call'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/installer/parallel_installer.rb:66:in `call'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/installer.rb:201:in `install'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/installer.rb:87:in `block in run'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/process_lock.rb:19:in `rescue in lock'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/process_lock.rb:15:in `lock'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/installer.rb:71:in `run'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/installer.rb:23:in `install'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/cli/install.rb:68:in `run'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/cli.rb:247:in `block in install'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/settings.rb:158:in `temporary'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/cli.rb:246:in `install'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/cli.rb:35:in `dispatch'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/cli.rb:29:in `start'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/exe/bundle:28:in `block in <top (required)>'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/exe/bundle:20:in `<top (required)>'
          /usr/local/rvm/gems/ruby-3.0.0/bin/bundle:23:in `load'
          /usr/local/rvm/gems/ruby-3.0.0/bin/bundle:23:in `<main>'
Errno::EACCES: Permission denied @ rb_sysopen - /usr/local/rvm/gems/ruby-3.0.0/bundler.lock
  /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/process_lock.rb:9:in `initialize'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/process_lock.rb:9:in `open'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/process_lock.rb:9:in `lock'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/installer.rb:71:in `run'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/installer.rb:23:in `install'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/cli/install.rb:68:in `run'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/cli.rb:247:in `block in install'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/settings.rb:158:in `temporary'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/cli.rb:246:in `install'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/cli.rb:35:in `dispatch'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/cli.rb:29:in `start'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/exe/bundle:28:in `block in <top (required)>'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
          /usr/local/rvm/gems/ruby-3.0.0/gems/bundler-2.5.22/exe/bundle:20:in `<top (required)>'
          /usr/local/rvm/gems/ruby-3.0.0/bin/bundle:23:in `load'
          /usr/local/rvm/gems/ruby-3.0.0/bin/bundle:23:in `<main>'

```

## Environment

```
Bundler             2.5.22
  Platforms         ruby, x86_64-linux
Ruby                3.0.0p0 (2020-12-25 revision 95aff214687a5e12c3eb57d056665741e734c188) [x86_64-linux]
  Full Path         /usr/local/rvm/rubies/ruby-3.0.0/bin/ruby
  Config Dir        /usr/local/rvm/rubies/ruby-3.0.0/etc
RubyGems            3.2.3
  Gem Home          /usr/local/rvm/gems/ruby-3.0.0
  Gem Path          /usr/local/rvm/gems/ruby-3.0.0:/usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0
  User Home         /home/azureuser
  User Path         /home/azureuser/.local/share/gem/ruby/3.0.0
  Bin Dir           /usr/local/rvm/gems/ruby-3.0.0/bin
OpenSSL
  Compiled          OpenSSL 1.1.1k  FIPS 25 Mar 2021
  Loaded            OpenSSL 1.1.1k  FIPS 25 Mar 2021
  Cert File         /etc/pki/tls/cert.pem
  Cert Dir          /etc/pki/tls/certs
Tools
  Git               2.43.5
  RVM               1.29.12 (latest)
  rbenv             not installed
  chruby            not installed
  rubygems-bundler  (1.4.5)
```

## Bundler Build Metadata

```
Built At          2024-10-16
Git SHA           342d4542fda
Released Version  true
```

## Bundler settings

```
gemfile
  Set via BUNDLE_GEMFILE: "/usr/local/rvm/src/ruby-3.0.0/.bundle/gems/rake-13.0.3/Gemfile"
```

## Gemfile

### ../../../src/ruby-3.0.0/.bundle/gems/rake-13.0.3/Gemfile

```ruby
source "https://rubygems.org"

gemspec

group :development do
  gem "bundler"
  gem "minitest"
  gem "coveralls"
  gem "rubocop"
end
```

### ../../../src/ruby-3.0.0/.bundle/gems/rake-13.0.3/Gemfile.lock

```
<No /usr/local/rvm/src/ruby-3.0.0/.bundle/gems/rake-13.0.3/Gemfile.lock found>
```

## Gemspecs

### rake-13.0.3.gemspec

```ruby
# -*- encoding: utf-8 -*-
# stub: rake 13.0.3 ruby lib

Gem::Specification.new do |s|
  s.name = "rake".freeze
  s.version = "13.0.3"

  s.required_rubygems_version = Gem::Requirement.new(">= 1.3.2".freeze) if s.respond_to? :required_rubygems_version=
  s.metadata = { "bug_tracker_uri" => "https://github.com/ruby/rake/issues", "changelog_uri" => "https://github.com/ruby/rake/blob/v13.0.3/History.rdoc", "documentation_uri" => "https://ruby.github.io/rake", "source_code_uri" => "https://github.com/ruby/rake/tree/v13.0.3" } if s.respond_to? :metadata=
  s.require_paths = ["lib".freeze]
  s.authors = ["Hiroshi SHIBATA".freeze, "Eric Hodel".freeze, "Jim Weirich".freeze]
  s.bindir = "exe".freeze
  s.date = "2020-12-21"
  s.description = "Rake is a Make-like program implemented in Ruby. Tasks and dependencies are\nspecified in standard Ruby syntax.\nRake has the following features:\n  * Rakefiles (rake's version of Makefiles) are completely defined in standard Ruby syntax.\n    No XML files to edit. No quirky Makefile syntax to worry about (is that a tab or a space?)\n  * Users can specify tasks with prerequisites.\n  * Rake supports rule patterns to synthesize implicit tasks.\n  * Flexible FileLists that act like arrays but know about manipulating file names and paths.\n  * Supports parallel execution of tasks.\n".freeze
  s.email = ["hsbt@ruby-lang.org".freeze, "drbrain@segment7.net".freeze, "".freeze]
  s.executables = ["rake".freeze]
  s.files = ["CONTRIBUTING.rdoc".freeze, "Gemfile".freeze, "History.rdoc".freeze, "MIT-LICENSE".freeze, "README.rdoc".freeze, "Rakefile".freeze, "bin/bundle".freeze, "bin/console".freeze, "bin/rake".freeze, "bin/rdoc".freeze, "bin/rubocop".freeze, "bin/setup".freeze, "doc/command_line_usage.rdoc".freeze, "doc/example/Rakefile1".freeze, "doc/example/Rakefile2".freeze, "doc/example/a.c".freeze, "doc/example/b.c".freeze, "doc/example/main.c".freeze, "doc/glossary.rdoc".freeze, "doc/jamis.rb".freeze, "doc/proto_rake.rdoc".freeze, "doc/rake.1".freeze, "doc/rakefile.rdoc".freeze, "doc/rational.rdoc".freeze, "exe/rake".freeze, "lib/rake.rb".freeze, "lib/rake/application.rb".freeze, "lib/rake/backtrace.rb".freeze, "lib/rake/clean.rb".freeze, "lib/rake/cloneable.rb".freeze, "lib/rake/cpu_counter.rb".freeze, "lib/rake/default_loader.rb".freeze, "lib/rake/dsl_definition.rb".freeze, "lib/rake/early_time.rb".freeze, "lib/rake/ext/core.rb".freeze, "lib/rake/ext/string.rb".freeze, "lib/rake/file_creation_task.rb".freeze, "lib/rake/file_list.rb".freeze, "lib/rake/file_task.rb".freeze, "lib/rake/file_utils.rb".freeze, "lib/rake/file_utils_ext.rb".freeze, "lib/rake/invocation_chain.rb".freeze, "lib/rake/invocation_exception_mixin.rb".freeze, "lib/rake/late_time.rb".freeze, "lib/rake/linked_list.rb".freeze, "lib/rake/loaders/makefile.rb".freeze, "lib/rake/multi_task.rb".freeze, "lib/rake/name_space.rb".freeze, "lib/rake/packagetask.rb".freeze, "lib/rake/phony.rb".freeze, "lib/rake/private_reader.rb".freeze, "lib/rake/promise.rb".freeze, "lib/rake/pseudo_status.rb".freeze, "lib/rake/rake_module.rb".freeze, "lib/rake/rake_test_loader.rb".freeze, "lib/rake/rule_recursion_overflow_error.rb".freeze, "lib/rake/scope.rb".freeze, "lib/rake/task.rb".freeze, "lib/rake/task_argument_error.rb".freeze, "lib/rake/task_arguments.rb".freeze, "lib/rake/task_manager.rb".freeze, "lib/rake/tasklib.rb".freeze, "lib/rake/testtask.rb".freeze, "lib/rake/thread_history_display.rb".freeze, "lib/rake/thread_pool.rb".freeze, "lib/rake/trace_output.rb".freeze, "lib/rake/version.rb".freeze, "lib/rake/win32.rb".freeze, "rake.gemspec".freeze]
  s.homepage = "https://github.com/ruby/rake".freeze
  s.licenses = ["MIT".freeze]
  s.rdoc_options = ["--main".freeze, "README.rdoc".freeze]
  s.required_ruby_version = Gem::Requirement.new(">= 2.2".freeze)
  s.rubygems_version = "2.7.6".freeze
  s.summary = "Rake is a Make-like program implemented in Ruby".freeze
end
```

--- TEMPLATE END ----------------------------------------------------------------

Unfortunately, an unexpected error occurred, and Bundler cannot continue.

First, try this link to see if there are any existing issue reports for this error:
https://github.com/rubygems/rubygems/search?q=You+don%27t+have+write+permissions+for+the+%2Fusr%2Flocal%2Frvm%2Fgems%2Fruby-3.0.0%2Fwrappers+directory.&type=Issues

If there aren't any reports for this error yet, please fill in the new issue form located at https://github.com/rubygems/rubygems/issues/new?labels=Bundler&template=bundler-related-issue.md, and copy and paste the report template above in there.`

This is the actual command and error message 
I am sorry i forgot to show this

**Comment by DOkuwa** [comment]
` gem uninstall rubygems-bundler
ERROR:  While executing gem ... (Gem::InstallError)
    rubygems-bundler is not installed in GEM_HOME, try:
        gem uninstall -i /usr/local/rvm/rubies/ruby-3.0.0/lib/ruby/gems/3.0.0 rubygems-bundler`

**Comment by deivid-rodriguez** [comment]
We will be releasing some improvements shortly in Bundler 2.5.23 that may lead to a better error message here, but overall the problem is the permissions of `/usr/local/rvm/rubies/ruby-3.0.0/`. Your current user can't write to it and Bundler & RubyGems needs to write to it.

**Comment by deivid-rodriguez** [comment]
Can you share why you're running `bundle install --gemfile=/usr/local/rvm/src/ruby-3.0.0/.bundle/gems/rake-13.0.3/Gemfile` in the first place? I can't imagine any situation where you'd need to run that.

**Comment by deivid-rodriguez** [comment]
The problem now is that even if gems where installed properly, you're probably run `bundle exec` from a folder without a `Gemfile` (since the Gemfile is at `/usr/local/rvm/src/ruby-3.0.0/.bundle/gems/rake-13.0.3/Gemfile`). But again, I wonder why you're using the Gemfile of a specific installed gem in the first place.

**Comment by DOkuwa** [comment]
Hi

I am just following the instructions from github 
Now i have removed jruby reinstalled it again i am having a different error
`[root@Daley-DB-second bin]# bundle install
Error: No such file or directory:
/opt/jruby-9.4.9.0/bin/jruby: line 729: exec: : not found`

**Comment by deivid-rodriguez** [comment]
Can you link to the instructions that you are following?

That error is telling you that jruby cannot be found at `/opt/jruby-9.4.9.0/bin/jruby`. Does that file exist?

**Comment by DOkuwa** [comment]
`[root@Daley-DB-second bin]# pwd
/opt/jruby-9.4.9.0/bin
[root@Daley-DB-second bin]# ls -al
total 3088
drwxr-xr-x. 2 root root    4096 Nov  6 14:32 .
drwxr-xr-x. 5 root root     103 Nov  4 20:44 ..
-rwxr-xr-x. 1 root root    5501 Nov  4 20:44 ast
-rw-r--r--. 1 root root      40 Nov  4 20:44 ast.bat
-rwxr-xr-x. 1 root root     565 Nov  4 20:44 bundle
-rw-r--r--. 1 root root      43 Nov  4 20:44 bundle.bat
-rwxr-xr-x. 1 root root     567 Nov  4 20:44 bundler
-rw-r--r--. 1 root root      44 Nov  4 20:44 bundler.bat
-rw-r--r--. 1 root root     170 Nov  4 20:42 .dev_mode.java_opts
-rwxr-xr-x. 1 root root     526 Nov  4 20:44 erb
-rw-r--r--. 1 root root      40 Nov  4 20:44 erb.bat
-rwxr-xr-x. 1 root root     123 Nov  4 20:44 gem
-rw-r--r--. 1 root root      40 Nov  4 20:44 gem.bat
-rwxr-xr-x. 1 root root     548 Nov  4 20:44 install_doc
-rw-r--r--. 1 root root      48 Nov  4 20:44 install_doc.bat
-rwxr-xr-x. 1 root root     526 Nov  4 20:44 irb
-rw-r--r--. 1 root root      40 Nov  4 20:44 irb.bat
-rwxr-xr-x. 1 root root     541 Nov  4 20:44 jgem
-rw-r--r--. 1 root root      41 Nov  4 20:44 jgem.bat
-rwxr-xr-x. 1 root root     390 Nov  4 20:44 jirb
-rw-r--r--. 1 root root      41 Nov  4 20:44 jirb.bat
-rwxr-xr-x. 1 root root    2282 Nov  4 20:44 jirb_swing
-rw-r--r--. 1 root root      47 Nov  4 20:44 jirb_swing.bat
-rwxr-xr-x. 1 root root   20751 Nov  4 20:44 jruby
-rwxr-xr-x. 1 root root     125 Nov  4 20:44 jruby.bat
-rwxr-xr-x. 1 root root     188 Nov  4 20:44 jrubyc
-rw-r--r--. 1 root root      43 Nov  4 20:44 jrubyc.bat
-rwxr-xr-x. 1 root root     245 Nov  4 20:44 jrubyd.bat
-rwxr-xr-x. 1 root root 1029632 Nov  4 20:44 jruby.dll
-rwxr-xr-x. 1 root root  960000 Nov  4 20:44 jruby.exe
-rw-r--r--. 1 root root       0 Nov  4 20:42 .jruby.java_opts
-rw-r--r--. 1 root root     206 Nov  4 20:42 .jruby.module_opts
-rwxr-xr-x. 1 root root   20751 Nov  4 20:44 jruby.sh
-rwxr-xr-x. 1 root root  962048 Nov  4 20:44 jrubyw.exe
-rwxr-xr-x. 1 root root     590 Nov  4 20:44 lock_jars
-rw-r--r--. 1 root root      46 Nov  4 20:44 lock_jars.bat
-rwxr-xr-x. 1 root root     532 Nov  4 20:44 racc
-rw-r--r--. 1 root root      41 Nov  4 20:44 racc.bat
-rwxr-xr-x. 1 root root     532 Nov  4 20:44 rake
-rw-r--r--. 1 root root      41 Nov  4 20:44 rake.bat
-rwxr-xr-x. 1 root root     532 Nov  4 20:44 rdoc
-rw-r--r--. 1 root root      41 Nov  4 20:44 rdoc.bat
-rwxr-xr-x. 1 root root     528 Nov  4 20:44 ri
-rw-r--r--. 1 root root      39 Nov  4 20:44 ri.bat
[root@Daley-DB-second bin]#`

**Comment by deivid-rodriguez** [comment]
And what are the contents of the `bundle` file in that folder? Please wrap the output in triple quotes (```) so that it's readable.

**Comment by DOkuwa** [comment]
``[root@Daley-DB-second bin]# more bundle
#!/usr/bin/env jruby
#
# This file was generated by RubyGems.
#
# The application 'bundler' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0.a"

str = ARGV.first
if str
  str = str.b[/\A_(.*)_\z/, 1]
  if str and Gem::Version.correct?(str)
    version = str
    ENV['BUNDLER_VERSION'] = str

    ARGV.shift
  end
end

if Gem.respond_to?(:activate_bin_path)
load Gem.activate_bin_path('bundler', 'bundle', version)
else
gem "bundler", version
load Gem.bin_path("bundler", "bundle", version)
end``

**Comment by DOkuwa** [comment]
`[root@Daley-DB-second bin]# more bundle
#!/usr/bin/env jruby
#
# This file was generated by RubyGems.
#
# The application 'bundler' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0.a"

str = ARGV.first
if str
  str = str.b[/\A_(.*)_\z/, 1]
  if str and Gem::Version.correct?(str)
    version = str
    ENV['BUNDLER_VERSION'] = str

    ARGV.shift
  end
end

if Gem.respond_to?(:activate_bin_path)
load Gem.activate_bin_path('bundler', 'bundle', version)
else
gem "bundler", version
load Gem.bin_path("bundler", "bundle", version)
end
[root@Daley-DB-second bin]#`

**Comment by deivid-rodriguez** [comment]
You're almost there with the formatting of your messages, just one more quote 😆. You can use "preview" to see how your post is getting rendered.

I guess running `/usr/bin/env jruby` runs into the same error. Which means that `jruby` is not in your PATH. How did you install Ruby? Generally using a version manager like [asdf](https://github.com/asdf-vm/asdf) is recommended, and not running as root is also normally better.

Can you please link to the instructions that you are following?

**Comment by DOkuwa** [comment]
I download jruby from https://www.jruby.org/download and get started with
Download JRuby: Visit the [download page](https://www.jruby.org/download) and grab the binaries for the latest JRuby release.
Unpack JRuby: Unpack the file you downloaded. You’ll then have a "jruby-<version>" directory.
Run JRuby: The JRuby startup script lives in the "bin" directory. Run "bin/jruby -v" to confirm it.

I have never heared of asdf and would try that today

**Comment by DOkuwa** [comment]
`[azureuser@Daley-DB-second jruby-9.4.9.0]$ /usr/bin/env jruby
Error: No such file or directory:
/opt/jruby-9.4.9.0/bin/jruby: line 729: exec: : not found`

**Comment by deivid-rodriguez** [comment]
I see, thanks for sharing the instructions you are following. I think those instructions should mention that you need to add the bin folder in the extracted jruby- directory to your `PATH`. If you run `PATH=$PATH:/opt/jruby-9.4.9.0/bin bundle install`, does it work?

**Comment by deivid-rodriguez** [comment]
Oh, misread the error. It seems `/opt/jruby-9.4.9.0/bin/jruby` is running fine, but failing to internally `exec` to something else. I wonder if folks at https://github.com/jruby/jruby/ may be able to help you more.

**Comment by DOkuwa** [comment]
I have installed jruby again using rvm 
I have bundle install working and also bundle exec rspec 
but came out with one error 

`bundle  exec rspec
Your RubyGems version (2.7.10) has a bug that prevents `required_ruby_version` from working for Bundler. Any scripts that use `gem install bundler` will break as soon as Bundler drops support for your Ruby version. Please upgrade RubyGems to avoid future breakage and silence this warning by running `gem update --system 3.2.3`
/usr/local/rvm/gems/jruby-9.2.9.0/gems/logstash-core-5.6.4-java/lib/logstash/settings.rb:476: warning: constant ::Fixnum is deprecated
/usr/local/rvm/gems/jruby-9.2.9.0/gems/logstash-core-5.6.4-java/lib/logstash/settings.rb:480: warning: constant ::Fixnum is deprecated
/usr/local/rvm/gems/jruby-9.2.9.0/gems/logstash-core-5.6.4-java/lib/logstash/settings.rb:503: warning: constant ::Fixnum is deprecated
/usr/local/rvm/gems/jruby-9.2.9.0/gems/logstash-core-5.6.4-java/lib/logstash/settings.rb:507: warning: constant ::Fixnum is deprecated
--- jar coordinate com.fasterxml.jackson.core:jackson-databind already loaded with version 2.9.1 - omit version 2.15.4
--- jar coordinate com.fasterxml.jackson.module:jackson-module-afterburner already loaded with version 2.9.1 - omit version 2.15.4
--- jar coordinate com.fasterxml.jackson.core:jackson-core already loaded with version 2.9.1 - omit version 2.15.4
--- jar coordinate com.fasterxml.jackson.core:jackson-annotations already loaded with version 2.9.1 - omit version 2.15.4
Sending Logstash's logs to  which is now configured via log4j2.properties

An error occurred while loading ./spec/inputs/grpc_spec.rb.
Failure/Error: require "logstash/devutils/rspec/shared_grpc"

LoadError:
  no such file to load -- logstash/devutils/rspec/shared_grpc
# /usr/local/rvm/gems/jruby-9.2.9.0/gems/polyglot-0.3.5/lib/polyglot.rb:65:in `require'
# ./spec/inputs/grpc_spec.rb:3:in `<main>'
# ------------------
# --- Caused by: ---
# Polyglot::PolyglotLoadError:
#   Failed to load logstash/devutils/rspec/shared_grpc using extensions rb, treetop, tt
#   /usr/local/rvm/gems/jruby-9.2.9.0/gems/polyglot-0.3.5/lib/polyglot.rb:55:in `load'
Run options: exclude {:redis=>true, :socket=>true, :performance=>true, :couchdb=>true, :elasticsearch=>true, :elasticsearch_secure=>true, :export_cypher=>true, :integration=>true, :windows=>true}

All examples were filtered out


Finished in 0.00217 seconds (files took 7.56 seconds to load)
0 examples, 0 failures, 1 error occurred outside of examples`

**Comment by deivid-rodriguez** [comment]
That seems unrelated to Bundler or RubyGems. You may want to ask JRuby maintainers about it, or maybe the logstash project, or the polyglot gem.
