### ISSUE TITLE
GEM_ROOT

### ISSUE THREAD

**Issue by dsisnero** [rubygems/rubygems#8223]
### Describe the problem as clearly as you can
I know that we can set GEM_HOME but in order to make it possible to set GEM_HOME for various rubies - have an environment GEM_ROOT

if that is set then SET default GEM_HOME (if it is not set) to 
`"GEM_ROOT/#{RUBY_ENGINE}/#{RUBY_VERSION}"
`

**Comment by deivid-rodriguez** [comment]
Can you explain why you need this? If you have several rubies installed, you need a version manager anyways, right?

**Comment by deivid-rodriguez** [comment]
Oh, I guess it's maybe because you're using Ruby on Windows, which does not have a good version manager? You may be interested in https://github.com/oneclick/rubyinstaller2/issues/378.

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.

**Comment by dsisnero** [comment]
please re-open - yes I am on windows so need this functionality

**Comment by deivid-rodriguez** [comment]
Can you try a ruby version manager instead? Most people are happily using version managers when they need multiple rubies, anmd I really don't want Bundler and RubyGems to take more responsibilities! See https://github.com/magynhard/rvm-windows which has just been released.

**Comment by deivid-rodriguez** [comment]
There's actually a builtin tool as well: https://github.com/oneclick/rubyinstaller2/wiki/The-ridk-tool#ridk-use.
