### ISSUE TITLE
bundle install failed since "Could not verify the SSL certificate"

### ISSUE THREAD

**Issue by sandy-lcq** [rubygems/rubygems#8243]
### Describe the problem as clearly as you can
bundle  install failed with following error:

```
Could not verify the SSL certificate for https://rubygems.org/.
There is a chance you are experiencing a man-in-the-middle attack, but most likely your system doesn't have the CA certificates needed for
verification. For information about OpenSSL certificates, see https://railsapps.github.io/openssl-certificate-verify-failed.html. To connect
without using SSL, edit your Gemfile sources and change 'https' to 'http'.
```

On ubuntu22.04:

```
$ bundle --version
Bundler version 2.3.5
$ ruby --version
ruby 3.0.2p107 (2021-07-07 revision 0db68f0233) [x86_64-linux-gnu]
```

I  tried `sudo update-ca-certificate`, not works,   
I think my cert is ok, since `curl -v https://rubygems.org/` works well,  I can see ssl cert passed.

I tried  `export SSL_CERT_FILE=/etc/ssl/certs/ca-certificates.crt`, not works

### Did you try upgrading rubygems & bundler?

```
$ gem update --system
ERROR:  Your RubyGems was installed trough APT, and upgrading it through RubyGems
itself is unsupported. If you really need the latest version of RubyGems (tip:
you usually don't), then you need to install RubyGems (and Ruby) manually,
maybe using tools like ruby-install, rvm, etc.

$ bundle update --bundler
# will also failed with ssl cert failure
```

**Comment by deivid-rodriguez** [comment]
Hi!

Does `gem install bundler` work?

**Comment by sandy-lcq** [comment]
It also not work
`
$ gem install bundler

ERROR:  SSL verification error at depth 2: unable to get issuer certificate (2)
ERROR:  SSL verification error at depth 2: unable to get issuer certificate (2)
ERROR:  SSL verification error at depth 2: unable to get issuer certificate (2)
ERROR:  Could not find a valid gem 'bundler' (>= 0), here is why:
          Unable to download data from https://rubygems.org/ - SSL_connect returned=1 errno=0 peeraddr=151.101.65.227:443 state=error: certificate verify failed (unable to get issuer certificate) (https://rubygems.org/specs.4.8.gz)
ERROR:  SSL verification error at depth 2: unable to get issuer certificate (2)
ERROR:  SSL verification error at depth 2: unable to get issuer certificate (2)
`

**Comment by deivid-rodriguez** [comment]
Can you try troubleshooting using [this script](https://github.com/rubygems/ruby-ssl-check)?

**Comment by deivid-rodriguez** [comment]
Closing due to lack of feedback.

**Comment by sandy-lcq** [comment]
Hi, Devid
Thanks,  I tried that scripts,  and found out the problem is my certificate issue.

**Comment by ruudgrosmann** [comment]
Thanks for the script. It helped me a great deal to pinpoint my problem.
