### ISSUE TITLE
Make sure all Bundler commands have a man page

### ISSUE THREAD

**Issue by deivid-rodriguez** [rubygems/rubygems#8268]
### Describe the problem as clearly as you can

When Bundler commands don't have a man page, they don't show up in bundler.io. Also, `--help` output for them is not man friendly and inconsistent with the other commands.

We should make sure all Bundler commands have a corresponding man page.

The steps to achieve this are:

* [ ] Add a man page for `bundle issue`, the only command without a man page right now. 
* [ ] Add a spec that ensures all commands have a man page. An idea would be to make sure that for every file in `bundler/lib/bundler/cli/<command>.rb` (except for `common.rb`), there's a corresponding `bundle-<command>-1.ronn` file in `bundler/lib/bundler/man`.

**Comment by andrew** [comment]
For part 1: https://github.com/rubygems/rubygems/pull/8271

**Comment by jeromedalbert** [comment]
And here's part 2: https://github.com/rubygems/rubygems/pull/8280
