### ISSUE TITLE
2.6.0-dev: `bundle lock --add-checksums` doesn't add checksums

### ISSUE THREAD

**Issue by Earlopain** [rubygems/rubygems#8270]
### Describe the problem as clearly as you can

With the following Gemfile and Lockfile:

```rb
source "https://rubygems.org"

gem "bcrypt"
```

```rb
GEM
  remote: https://rubygems.org/
  specs:
    bcrypt (3.1.20)

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  bcrypt

BUNDLED WITH
   2.6.0.dev
```

When I run `bundle lock --add-checksums` the lockfile is modified to the following:

```rb
GEM
  remote: https://rubygems.org/
  specs:
    bcrypt (3.1.20)

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  bcrypt

CHECKSUMS
  bcrypt (3.1.20)

BUNDLED WITH
   2.6.0.dev
```

The checksum section is present but is missing the actual checksums. Only after I run `bundle lock --update` is the checksum section properly populated.

### Quick thoughts

I added some debug output to https://github.com/rubygems/rubygems/blob/3680ce4cdafb1d6fab7bf6d3d20c4e2e046af8f2/bundler/lib/bundler/lockfile_generator.rb#L69-L75 and the store is empty. I guess the checksums haven't been calculated at that point?

## Environment

```
Bundler       2.6.0.dev
  Platforms   ruby, x86_64-linux
Ruby          3.4.0p-1 (2024-11-20 revision b56aacba78c95c1d7151c8cb66165fb69510bac3) [x86_64-linux]
  Full Path   /home/earlopain/.rbenv/versions/3.4-dev/bin/ruby
  Config Dir  /home/earlopain/.rbenv/versions/3.4-dev/etc
RubyGems      3.6.0.dev
  Gem Home    /home/earlopain/.rbenv/versions/3.4-dev/lib/ruby/gems/3.4.0+1
  Gem Path    /home/earlopain/.gem/ruby/3.4.0+1:/home/earlopain/.rbenv/versions/3.4-dev/lib/ruby/gems/3.4.0+1
  User Home   /home/earlopain
  User Path   /home/earlopain/.gem/ruby/3.4.0+1
  Bin Dir     /home/earlopain/.rbenv/versions/3.4-dev/bin
Tools         
  Git         2.47.0
  RVM         not installed
  rbenv       rbenv 1.3.0
  chruby      not installed
```

**Comment by deivid-rodriguez** [comment]
Thanks for the report, yeah, it seems like the checksums have not been calculated 🤷‍♂️.  I'll take a look tomorrow 👍.
