### ISSUE TITLE
A RubyGems update was available which I ran at ITS suggestion and it completely nuked my entire Rubygems everything!  

### ISSUE THREAD

**Issue by desnw** [rubygems/rubygems#8273]
### Which command did you run?
gem update --system 3.5.23
gem update --system

Your rubygems crashed so horrifically bad that I also now can't even update it to the old version.  I can find NO OPTION to do a SIMPLE ROLLBACK (don't understand how there is no ROLLBACK function in the year 2024?!?!)

### What were you expecting to happen?

I EXPECTED IT to update the Rubygems system like it has 1000000 other times with no issue, this is the first time this has EVER FAILED and to fail THIS BADLY is kind of awful.

### Run `gem env` and paste the output below

$ gem env
C:/ruby/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/gem_runner.rb:9:in `require_relative': cannot load such file -- C:/ruby/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems (LoadError)
        from C:/ruby/Ruby32-x64/lib/ruby/site_ruby/3.2.0/rubygems/gem_runner.rb:9:in `<top (required)>'
        from <internal:C:/ruby/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from <internal:C:/ruby/Ruby32-x64/lib/ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in `require'
        from C:/ruby/Ruby32-x64/bin/gem:8:in `<main>'

I am quite annoyed that your program crashed so horrifically bad you left me with a completely USELESS DEV ENVIRONMENT, it is crashed and now RubyGems is 100% dead as a doornail.  How do I REALLY FIX THIS!

Might I make a VERY VERY STRONG SUGESTION to include a SIMPLE ROLLBACK COMMAND?
If there is one I can't find it documented anyplace nor do the AI clients offer any help at all.

**Comment by desnw** [comment]
I was able to fix it by downloading the latest RubyGems from https://rubygems.org/pages/download and then I opened a BASH shell with admin rights (just to be safe) and I ran Ruby setup.rb and it seems to have installed, have no idea why the "update" that RUBYGEMS TOLD ME TO RUN didn't work so I want to leave this open as there is still an issue if the updater isn't working.

$ ruby setup.rb
  Successfully built RubyGem
  Name: bundler
  Version: 2.5.23
  File: bundler-2.5.23.gem
Bundler 2.5.23 installed
RubyGems 3.5.23 installed
Regenerating binstubs
Regenerating plugins
Parsing documentation for rubygems-3.5.23
Installing ri documentation for rubygems-3.5.23

# 3.5.23 / 2024-11-05


IT THEN GAVE ME ABOUT 500 PAGES OF INFORMATION ABOUT THE VARIOUS RUBYGEMS VERSIONS.

If I run 
$ gem --version

I now get:
3.5.23

**Comment by deivid-rodriguez** [comment]
No information whatsoever about how to reproduce the issue, so we can't really help much.  I'm glad you were able to fix the issue. If you find more clues on what might've contributed to create this problem, feel free to share.

**Comment by desnw** [comment]
Get a Windows BOX, install Ruby, run the commands as your app requires.  
I included the screenshots directly from BASH, so not sure what else you could possibly want.

**Comment by deivid-rodriguez** [comment]
We have CI on Windows testing this command and it's green, and there are a lot of users on Windows happily upgrading RubyGems. You yourself said that you've run this 1000000 times and it always worked. Obviously it's not that simple. I'd like some repro steps to see the issue happening. For example, install Ruby on Windows on a Github Actions workflow and share a link to the problem happening.

**Comment by desnw** [comment]
I don't know that a Windows CI is going to tell you everything or anything in this case but that is up to you folks.  I already solved my particular issue after the Rubygems update FAILED.  I was reporting it because if I ran into it with a very straight forward and simple install I would assume someone else is also going to run into it.  So I was reporting it to help the Ruby/Rails community so that a problem could be identified before it became a bigger issue.  I guess time will tell if this is a one-off issue or not.  If you are saying you haven't seen it before then I guess just keep it in mind in the event more reports start coming in.  Thank you for your time, go ahead and close it.

**Comment by MSP-Greg** [comment]
JFYI, needed a break, so I tried:
```
gem update --system 3.5.23
gem update --system
```

Did so from both a Window shell and a MSYS2 bash shell.  Both worked.  I used Ruby 3.2.6.

**Comment by desnw** [comment]
Thank you @MSP-Greg for testing that, appreciate it.  

It is possible it is just a one off issue.  It was just such a hard crash I wanted to be sure there wasn't an unknown bug or a dependency issue (Mimemagic comes to mind) as I have seen those change and break things before.

**Comment by MSP-Greg** [comment]
@desnw

I should have mentioned it.  If this happens again, check what's installed in `lib/ruby/site_ruby/3.2.0`.

At a minimum, you should see `rubygems.rb`, `bundler.rb`, a `rubygems` folder, and a `bundler` folder.

I have no idea what happened.  But, over the years, I decided that doing as much as possible from a Windows shell is a good idea.
