### ISSUE TITLE
Issue on RybyGems gem's page - no link to the Homepage

### ISSUE THREAD

**Issue by justi** [rubygems/rubygems#8290]
When rubygems_mfa_required is true, no homepage link is displayed on the RubyGems gem's page.

### Post steps to reproduce the problem

Add to .gemspec file:

`spec.metadata["rubygems_mfa_required"] = "true"`

Push to the remote repo and refresh the RubyGems page.

### Which command did you run?

`
gem build && gem push
`

### What were you expecting to happen?

RubyGems gem's page should have a link to the Homepage
RubyGems gem's page should have a link to GitHub (widget with the stars icons)

### What actually happened?

There is no link to the Homepage and GitHub

**Comment by deivid-rodriguez** [comment]
Hi! Are you sure this is related to `spec.metadata["rubygems_mfa_required"] = "true"`? I don't see how it could be related. Could this be https://github.com/rubygems/rubygems.org/issues/4924 instead? Do you have a public example of this so we can look into it more closely?

**Comment by justi** [comment]
Hello @deivid-rodriguez, there are the examples without a Homepage:
https://rubygems.org/gems/no_comments - https://github.com/justi/no_comments/blob/main/no_comments.gemspec - my gem.

With Homepage and no mfa:
https://rubygems.org/gems/ezcater_rubocop - https://github.com/ezcater/ezcater_rubocop/blob/main/ezcater_rubocop.gemspec
https://github.com/jenseng/hair_trigger - https://github.com/jenseng/hair_trigger/blob/master/hairtrigger.gemspec

Now I found a specific case: https://github.com/ONLYOFFICE-QA/onlyoffice_webdriver_wrapper/blob/master/onlyoffice_webdriver_wrapper.gemspec - here is the mfa turned but the links are displayed properly (https://rubygems.org/gems/onlyoffice_webdriver_wrapper)

I notice it uses a different statement than other examples:
`spec.metadata = {}`

I'll try to change the configuration and get back to you.

**Comment by justi** [comment]
@deivid-rodriguez I've got it.

It was related in this way:
When you set the flag in `spec.metadata["rubygems_mfa_required"] = "true"`,  the `spec.matadata` hash overrides the rest of the settings, for example the homepage settings in `spec.homepage`. 

The solution is to define homepage in this hash:
`spec.metadata = {
    "homepage_uri" => spec.homepage,
    "rubygems_mfa_required" => "true"
  }`

I saw that is not explained in [the guide](https://guides.rubygems.org/mfa-requirement-opt-in/), maybe it will be a good idea to mention it?

**Comment by deivid-rodriguez** [comment]
@justi I'm confused, I see the homepage link displayed properly in all the examples you gave. Maybe we're not talking about the same link? Can you show a screenshot?

**Comment by justi** [comment]
When you look at my gem's previous version: https://rubygems.org/gems/no_comments/versions/0.1.7 there is no Homepage link. The corresponding gemspec file was: https://github.com/justi/no_comments/blob/d3a1b6214c9fde7ad8737d61cf472b96dbc1288b/no_comments.gemspec

**Comment by deivid-rodriguez** [comment]
@justi I see. After a second look, I'm pretty sure this is the same as https://github.com/rubygems/rubygems.org/issues/4924 and there's now an open PR to address it: https://github.com/rubygems/rubygems.org/pull/5249.

**Comment by justi** [comment]
Looks like you are right!

**Comment by deivid-rodriguez** [comment]
Cool, let me close this in favor of that issue and PR, then.
