### ISSUE TITLE
bundler 2.6.0: NoMethodError: undefined method `redact' for Gem::Uri:Class

### ISSUE THREAD

**Issue by mpalmer** [rubygems/rubygems#8336]
CI just upgraded to Bundler 2.6.0, and now we've got this:

```
NoMethodError: undefined method `redact' for Gem::Uri:Class
      redacted_uri = Gem::Uri.redact(uri)
                             ^^^^^^^
  /var/lib/gems/3.1.0/gems/bundler-2.6.0/lib/bundler/rubygems_integration.rb:396:in `download_gem'
          /var/lib/gems/3.1.0/gems/bundler-2.6.0/lib/bundler/source/rubygems.rb:479:in `download_gem'
          /var/lib/gems/3.1.0/gems/bundler-2.6.0/lib/bundler/source/rubygems.rb:436:in `fetch_gem'
          /var/lib/gems/3.1.0/gems/bundler-2.6.0/lib/bundler/source/rubygems.rb:420:in `fetch_gem_if_possible'
          /var/lib/gems/3.1.0/gems/bundler-2.6.0/lib/bundler/source/rubygems.rb:162:in `install'
          /var/lib/gems/3.1.0/gems/bundler-2.6.0/lib/bundler/installer/gem_installer.rb:55:in `install'
          /var/lib/gems/3.1.0/gems/bundler-2.6.0/lib/bundler/installer/gem_installer.rb:17:in `install_from_spec'
          /var/lib/gems/3.1.0/gems/bundler-2.6.0/lib/bundler/installer/parallel_installer.rb:133:in `do_install'
          /var/lib/gems/3.1.0/gems/bundler-2.6.0/lib/bundler/installer/parallel_installer.rb:124:in `block in worker_pool'
          /var/lib/gems/3.1.0/gems/bundler-2.6.0/lib/bundler/worker.rb:62:in `apply_func'
          /var/lib/gems/3.1.0/gems/bundler-2.6.0/lib/bundler/worker.rb:57:in `block in process_queue'
          /var/lib/gems/3.1.0/gems/bundler-2.6.0/lib/bundler/worker.rb:54:in `loop'
          /var/lib/gems/3.1.0/gems/bundler-2.6.0/lib/bundler/worker.rb:54:in `process_queue'
          /var/lib/gems/3.1.0/gems/bundler-2.6.0/lib/bundler/worker.rb:90:in `block (2 levels) in create_threads'
```
## Environment
```
Bundler       2.6.0
  Platforms   ruby, x86_64-linux
Ruby          3.1.2p20 (2022-04-12 revision 4491bb740a9506d76391ac44bb2fe6e483fec952) [x86_64-linux]
  Full Path   /usr/bin/ruby3.1
  Config Dir  /etc
RubyGems      3.3.15
  Gem Home    /var/lib/gems/3.1.0
  Gem Path    /root/.local/share/gem/ruby/3.1.0:/var/lib/gems/3.1.0:/usr/local/lib/ruby/gems/3.1.0:/usr/lib/ruby/gems/3.1.0:/usr/lib/x86_64-linux-gnu/ruby/gems/3.1.0:/usr/share/rubygems-integration/3.1.0:/usr/share/rubygems-integration/all:/usr/lib/x86_64-linux-gnu/rubygems-integration/3.1.0
  User Home   /root
  User Path   /root/.local/share/gem/ruby/3.1.0
  Bin Dir     /usr/local/bin
OpenSSL       
  Compiled    OpenSSL 3.0.13 30 Jan 2024
  Loaded      OpenSSL 3.0.15 3 Sep 2024
  Cert File   /usr/lib/ssl/cert.pem
  Cert Dir    /usr/lib/ssl/certs
Tools         
  Git         2.39.5
  RVM         not installed
  rbenv       not installed
  chruby      not installed
```
## Bundler Build Metadata
```
Built At          2024-12-16
Git SHA           d6be0319aaf
Released Version  true
```
## Bundler settings
```
gemfile
  Set via BUNDLE_GEMFILE: "/[...]/server/test/Gemfile"
```
### server/test/Gemfile
```ruby
[...]
```
### server/test/Gemfile.lock
```
[...]
```

(Copy-pasting that report template makes reporting bugs a breeze, btw; a big :+1: to whoever built that...)

Bundler 2.6.0 declares a dependency on rubygems >= 3.3.3, but Gem::Uri.redact was introduced in, if I'm reading the entrails correctly, 3.6.0.

**Comment by abdullah-101998** [comment]
I am facing the same issue

**Comment by megha1906** [comment]
Do we have any work around for this?

**Comment by simi** [comment]
Can you try to update RubyGems by `gem update --system`?  [redact](https://github.com/rubygems/rubygems/commit/b8a6580d7ccb46a70890ceb6b582a27fa52fbfd2) was added in RubyGems 3.4.0.

**Comment by MuhammadAb98** [comment]
> Do we have any work around for this?

**I encountered the same issue and found a workaround to resolve it.**

**My CircleCI Step (Before Fix):**

- run: name: `Configure Bundler command: | echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV source $BASH_ENV gem install bundler`

**After the Fix:**

- run: name: `Configure Bundler command: | echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV source $BASH_ENV gem install bundler -v 2.3.25 `

**Explanation of the Fix:**
The issue was caused by CircleCI upgrading Bundler to version 2.6.0, which was not compatible with my project setup. To fix this, I explicitly defined the compatible Bundler version (2.3.25) in my pipeline configuration.

**Here's how I identified the compatible version:**

- I downgraded the Bundler version locally to test compatibility using the command gem install bundler -v and verified which version worked without errors.
- Once I identified the compatible version, I updated my CircleCI pipeline to explicitly install Bundler 2.3.25, ensuring consistency between local and CI environments.

This resolved the issue and allowed the bundle install command to work as expected.

VERSIONS: https://rubygems.org/gems/bundler/versions

**Comment by mt-clearhaus** [comment]
I am also facing this. The responsible PR: https://github.com/rubygems/rubygems/pull/8222

<details>
<summary>Reproduction using the latest debian:bookworm-slim (Ruby 3.1)</summary>

```
$ docker run --rm -it debian:bookworm-slim bash

root@a83878b17ba8:/# apt update && apt install -y ruby
[...]

root@a83878b17ba8:/# gem install bundler
Fetching bundler-2.6.0.gem
Successfully installed bundler-2.6.0
[...]

root@a83878b17ba8:/# cat > Gemfile << EOF
> source 'https://rubygems.org'

ruby '~> 3.1'

gem 'hello-world'
> EOF

root@a83878b17ba8:/# bundle install
[...]
Fetching hello-world 1.2.0
--- ERROR REPORT TEMPLATE -------------------------------------------------------

```
NoMethodError: undefined method `redact' for Gem::Uri:Class

      redacted_uri = Gem::Uri.redact(uri)
                             ^^^^^^^
  /var/lib/gems/3.1.0/gems/bundler-2.6.0/lib/bundler/rubygems_integration.rb:396:in `download_gem'
          /var/lib/gems/3.1.0/gems/bundler-2.6.0/lib/bundler/source/rubygems.rb:479:in `download_gem'
          /var/lib/gems/3.1.0/gems/bundler-2.6.0/lib/bundler/source/rubygems.rb:436:in `fetch_gem'
[...]
```
</details>

**Comment by mpalmer** [comment]
> Do we have any work around for this?

Downgrade bundler: `gem install 'bundler:<2.6.0'`

> Can you try to update RubyGems by gem update --system?

Using @mt-clearhaus' very straightforward repro, which is practically identical to my setup, produces the following:

```
root@048cc3693410:/# gem update --system
ERROR:  Your RubyGems was installed trough APT, and upgrading it through RubyGems
itself is unsupported. If you really need the latest version of RubyGems (tip:
you usually don't), then you need to install RubyGems (and Ruby) manually,
maybe using tools like ruby-install, rvm, etc.
```

(I'd like to give a tip o' the hat to the "tip: you usually don't" part of that error message)

**Comment by deivid-rodriguez** [comment]
This has been fixed by Bundler 2.6.1, you should be able to remove now any workarounds you had to introduce. Sorry for the trouble!

**Comment by emseedee** [comment]
Just came here to report this, only to find it's been fixed. Thanks for such a speedy response.

**Comment by kazuhitonakayama** [comment]
I was helped! Thanks a lot
