### ISSUE TITLE
Rubygems system 3.6.1 breaks rake release

### ISSUE THREAD

**Issue by kalsan** [rubygems/rubygems#8354]
Steps to reproduce:

```bash
gem update --system 3.6.1
rake release # in a gem that has always worked
```

leads to: 

```
Pushing gem to https://rubygems.org...
There was a problem saving your gem: Platform is invalid, Platform can only include letters, numbers, dashes, and underscores, Full name can not end with a period, dash, or underscore, Platform can't be blank
```

However, without changing anything else, the following works:

```bash
gem update --system 3.5.22
rake release
```

Therefore I assume this is a rubygems related issue.

**Comment by deivid-rodriguez** [comment]
Thank you for reporting! I was just fixing this over at #8355, will make a patch release with that fix later today.

**Comment by simi** [comment]
for reference, this was reported to rubygems.org also https://github.com/rubygems/rubygems.org/issues/5355
