### ISSUE TITLE
We need an alternative to yank

### ISSUE THREAD

**Issue by myronmarston** [rubygems/rubygems#858]
Yanking a gem can easily screw users of the gem.  Users that have the yanked version in their `Gemfile.lock` will suddenly get errors the next time they deploy.   Depending on how your deploy process is setup, this could cause downtime.

I think there are situations where yanking is appropriate, but they are few and far between:

* The gem contains malicious code that is more harmful than broken deploys/downtime would be.
* The gem accidentally contains private credentials that, for whatever reason, you cannot invalidate (e.g. because they get used in an iOS app or whatever, and invalidating them would screw over your users).

Currently there's no way to indicate that a version of a gem is not recommended, so gem authors sometimes yank botched or buggy releases without realizing the repercussions (example: headius/thread_safe#40).

I think we need an alternative to yanking for botched or buggy versions that gem authors can use to label a gem as "not recommended" or "problematic" that does not screw over users of the gem in the way yank does.  I imagine yank would remain for really serious situations.

Here's how I'm imagining this would work:

* The `gem` command would have a way to tag a gem as problematic with an accompanying reason or message.
* The page on rubygems.org for that version would prominently display the message.
* bundler and the rubygems client would ideally understand this metadata:
  * If a problematic version of a gem is in `Gemfile.lock`, `bundle install` would continue to install it, but it would print out the message so users are aware of the reason it was tagged as problematic.
  * `bundle update` would not update to a problematic version of a gem.
  * `gem install gemname` (without a version argument) would install the latest non-problematic version of the gem.
  * `gem install gemname --version <problematic version>` would install that version but print the message so users know that version is not recommended.

I know this would be a lot of work, and require the coordination of the rubygems, rubygems.org and bundler teams...but `yank` seems problematic enough that I think we need to work towards having alternatives.

Thoughts?

**Comment by zfhui** [comment]
As of http://blog.rubygems.org/2015/04/13/permadelete-on-yank.html installing a yanked gem with `gem install gemname` automatically installs the newer version and `gem install gemname -v <problematic-version>` prints out an error like `ERROR:  Could not find a valid gem 'gemname' (= <problematic-version>) in any repository`.

**Comment by sodabrew** [comment]
I agree that a complete yank is better than the old half-yank, but it's not a resolution to this ticket imo.

A minimum resolution here could be some kind of deprecation notice - so when mark a gem version as "deprecated" and/or yanked then the end user sees a bit of explanatory text, e.g.  a reference to a CVE number or something like that to close the loop on /why/ the gem was yanked.

**Comment by copiousfreetime** [comment]
Summary so far:

* yank command should prompt the user for an explanation of why the the gem is being yanked.
* installation of a yanked gem should display the explanation, and either install a newer version, or if part of a bundler locked item go ahead and install.

**Comment by indirect** [comment]
For the record, we have changed how yanks work on rubygems.org since this issue was opened. Yanked gems are now completely deleted, both gemspec and .gem file. The gem is no longer accessible to anyone, and so it is impossible to install a yanked gem. It would be nice to know that a version was yanked, rather than that it never existed at all, but we do not currently provide that information in any of the data returned to Bundler or the `gem` command.

**Comment by copiousfreetime** [comment]
Okay, closing this then as deprecated.
