### ISSUE TITLE
open command test and code fails on Windows due missing fork()

### ISSUE THREAD

**Issue by luislavena** [rubygems/rubygems#860]
From test failure:

https://gist.github.com/luislavena/9742847#file-gistfile1-txt-L14-L19

Usage of `fork()` without guards around code will result on failures on non-fork() friendly platforms (Windows, JRuby).

Creating this issue as placeholder before starting with fixes.

**Comment by djberg96** [comment]
Looks like it was replaced by a mock. Closing.
