### ISSUE TITLE
UTF-8 error on Cygwin (under Windows)

### ISSUE THREAD

**Issue by engelhro** [rubygems/rubygems#863]
Hi,

I'm using Rubygems on Windows 8.x, installed into a Cygwin64 environment. After upgrading to Rubygems 2.2.0 (this also happens with 2.2.1 and 2.2.2), I receive the following error on certain commands like "gem update", "gem command" or "gem query -r":

```
ERROR:  While executing gem ... (ArgumentError)
    invalid byte sequence in UTF-8
```

So my gems installation is broken. However, after manually downgrading (extracting the archive and running "ruby setup.rb") to Rubygems 2.1.1 or earlier everything works fine again. Any idea how to solve that? Is this an issue with Rubygems, or do I just need to adapt some settings? In the first case: which additional information do you need? Thanks for your help!

**Comment by renyan** [comment]
how to solve this issue?

**Comment by FredWe** [comment]
@renyan 

By reading this->[Re: gem command broken on Cygwin 64 with Ruby 2.0.0p481](https://cygwin.com/ml/cygwin/2014-09/msg00098.html)the solution is Setting the encoding to "BINARY"

I used this command `$ LANG="${LANG%%.*}.BINARY" gem update`
It works.
