### ISSUE TITLE
Only prompt for a password a single time when using an encrypted client certificate.

### ISSUE THREAD

**Issue by rampion** [rubygems/rubygems#877]
When configured to use an encrypted client certificate, `gem` currently prompts for a password to decrypt the certificate on each HTTPS request:
This can result in two password prompts for each HTTPS gemserver, all for the same password.

For example:

    % gem list foo -r --verbose

    *** REMOTE GEMS ***

    Enter PEM pass phrase:
    HEAD https://gemserver.bar.com/latest_specs.4.8.gz
    200 OK
    Enter PEM pass phrase:
    GET https://gemserver.bar.com/latest_specs.4.8.gz
    200 OK
    Enter PEM pass phrase:
    HEAD https://www.quux.com/gemserver/latest_specs.4.8.gz
    200 OK
    Enter PEM pass phrase:
    GET https://www.quux.com/gemserver/latest_specs.4.8.gz
    200 OK
    foo (0.0.1)
    %

It be nice if `gem` could cache the decrypted private key from the certificate between requests and reuse for each request.

**Comment by copiousfreetime** [comment]
This appears to effectively be solved with connection pools. @rampion if that is not the case please reopen.
