### ISSUE TITLE
Would like to merge .gemrc install: flags with Gem::ConfigFile::OPERATING_SYSTEM_DEFAULTS

### ISSUE THREAD

**Issue by lamont-granquist** [rubygems/rubygems#900]
We're shipping ruby as part of a package of software designed for desktop users where we'd like to set the default behavior of install/upgrade to be --user.  We can get most of what we want via this operating_system.rb file:

https://github.com/opscode/omnibus-chef/blob/af1f0586f8f1009700214b66fb7581ce3c7e39de/files/rubygems_customization/operating_system.rb

The only bug here is that if a user specifies a .gemrc file like this:

```
install: --no-ri --no-rdoc
update: --no-ri --no-rdoc
```

Then we lose our --user default.   There's is a workaround for this:

```
gem: --no-rdoc --no-ri
```

That's arguably better, but it means that we have to maintain a FAQ and install instructions for people to fix their .gemrc.  And the .gemrc which breaks the --user behavior that we want is widely documented around the web, and the difference between the two is not made clear in any of the stackoverflow questions about it

e.g. blog post that suggests what we don't want:

http://julianyap.com/2013/03/26/setting-up-a-ruby-rbenv-environment-on-os-x.html

So, it'd be nice to get what we want via merging the options.  If that's not possible it'd be nice to be able to change the default of the option[:user_install] to true for our install via some supported way.  I managed to get what I want via a monkeypatch:

```
class Gem::Installer

  old_initialize = instance_method(:initialize)
  define_method(:initialize) do |gem, options|
    options ||= {}
    options[:user_install] = true
    old_initialize.bind(self).(gem, options)
  end
end
```

But that's brittle and I'd rather not do that.   There might be some other hook already available to get what I need but I've been searching around and I can't seem to find it and I burned the better part of a day beating my head against this yak.

Any help solving this to make our experience more frictionless would be appreciated...

**Comment by copiousfreetime** [comment]
Checking on interest in this issue.

It appears what would need to be done is change the default behavior in the `Gem::ConfigFile` to merge configuration hash values instead of a cascading overwrite. 

Marking abandoned for now unless we get some interest.

**Comment by lamont-granquist** [comment]
We're still maintaining monkeypatches in chef-dk but i'm personally not super interested in fixing it right now -- @danielsdeleo might still want to see it happen.

**Comment by danielsdeleo** [comment]
I still would like this to happen but I won't be able to put time into it personally. If you need to close this to keep your issues queue manageable, I can accept it.
