### ISSUE TITLE
Can't create a virginal environment in ruby 2

### ISSUE THREAD

**Issue by zenspider** [rubygems/rubygems#901]
Brand spankin' new install of ruby. 

```
10043 % rm -rf xxx; ruby -v; GEM_HOME=xxx GEM_PATH=xxx RUBYOPT=--disable-gems gem list
ruby 2.1.1p76 (2014-02-24 revision 45161) [x86_64-darwin13.0]

*** LOCAL GEMS ***

bigdecimal (1.2.4)
io-console (0.4.2)
json (1.8.1)
minitest (4.7.5)
psych (2.0.3)
rake (10.1.0)
rdoc (4.1.0)
test-unit (2.1.1.0)
```

This is Not Good™.

**Comment by krainboltgreene** [comment]
Not quite sure how to handle this problem. On the one hand `gem list` should report all gems it knows about and `--disable-gems` (as documented) only stops Ruby from *loading* gems on start. These are two different interactions.

Perhaps this calls for a new flag/env on rubygems cli to tell you if something is loaded or not?

**Comment by bronzdoc** [comment]
I'm going to close this because it is to old, but if this problem is still of your interest feel free to let us know with a new issue!”

**Comment by zenspider** [comment]
Super old and super ignored. This is still a problem and shouldn't have been closed just for age.
