### ISSUE TITLE
Tests fail locally, pass on Travis

### ISSUE THREAD

**Issue by schneems** [rubygems/rubygems#914]
Pulled from master, tests fail for me:

```
  1) Failure:
TestGemSpecification#test_self_attribute_names [/Users/schneems/Documents/projects/rubygems/test/rubygems/test_gem_specification.rb:510]:
--- expected
+++ actual
@@ -10,6 +10,7 @@
  "extensions",
  "extra_rdoc_files",
  "files",
+ "has_rdoc",
  "homepage",
  "licenses",
  "metadata",


1717 tests, 5087 assertions, 1 failures, 0 errors, 1 skips
rake aborted!
Command failed with status (1): [/Users/schneems/.rubies/ruby-2.1.1/bin/rub...]
/Users/schneems/.gem/ruby/2.1.1/gems/hoe-3.12.0/lib/hoe/test.rb:83:in `block in define_test_tasks'
Tasks: TOP => default => test
(See full trace by running task with --trace)
```

Is there any guidance on what versions of dependencies need to be installed to get the tests running? Perhaps we should have a documentation section on running the tests correctly in the README?

**Comment by steakknife** [comment]
Lol @ garden-variety vendor A :point_right:  blames :point_right: B, A :point_left: blames :point_left: B Tragedy of the Commons :tm: , leave users in limbo with the check.  Super awesome.

**Comment by drbrain** [comment]
YARD is monkey patching RubyGems. YARD does not use the documentation-generation hooks. That have existed for the 2.x series.

There's no valid reason for YARD to blame RubyGems here.
