### ISSUE TITLE
Failed to Use gem in OS X 10.10

### ISSUE THREAD

**Issue by codetalks-new** [rubygems/rubygems#935]
/Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:212:in `initialize': Permission denied - /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-14/2.0.0/RedCloth-4.2.9/gem_make.out (Errno::EACCES)
$ruby -v
ruby 2.0.0p451 (2014-02-24 revision 45167) [universal.x86_64-darwin14]

**Comment by thegreyspot** [comment]
I also have this issue.  I am using grunt for compiling my scss and js and after updating to El Capitan, I get this error:

'''
Michaels-MacBook-Pro:wnmu thegreyspot$ grunt watch
Running "watch" task
Waiting...OK
>> File "assets/sass/styles/templates/be_campaign/be_campaign.scss" changed.

Running "compass:scss" (compass) task
Warning: Command failed: /Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:212:in `initialize': Permission denied - /Library/Ruby/Gems/2.0.0/extensions/universal-darwin-15/2.0.0/nokogiri-1.6.6.2/gem_make.out (Errno::EACCES)
	from /Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:212:in `open'
	from /Library/Ruby/Site/2.0.0/rubygems/ext/builder.rb:212:in `write_gem_make_out'
...
'''

I have never had to use Sudo before with this grunt. What am I missing?
