### ISSUE TITLE
InvalidSpecificationException on a 5-page long description with TODOs in it

### ISSUE THREAD

**Issue by renier** [rubygems/rubygems#956]
Bundler is flagging my gemspec as invalid, because:

```
The validation message from Rubygems was:
  "FIXME" or "TODO" is not a description
```

For my description, I read in my README.md file, which is pretty descriptive already. There are a couple of sections that I've marked with TODO in the readme because they need expansion. Obviously having TODOs in my 5-page description should not make the gemspec "invalid". So what can we do here?

This is coming from rubygems [here](https://github.com/rubygems/rubygems/blob/8ac36ada957451b03e04fdec24cb3d8664358129/lib/rubygems/specification.rb#L2582).

I think that regexp should really be `/\AFIXME|\ATODO/`, which catches the default description put by gem skeleton generators.

Thoughts?

**Comment by tusharmaroo** [comment]
@drbrain +1 for this issue!! I am working on a gem called todo_tracker. If you want to have a look its here... https://github.com/CraftApps/todo_tracker/blob/0-1-0/todo_tracker.gemspec#L12

Also Instead of Just checking for 'TODO' in entire row, we can use some other constraint.

What do you say?
