### ISSUE TITLE
gem installation via proxy will not work if an invalid name server is specified.

### ISSUE THREAD

**Issue by ewegene** [rubygems/rubygems#978]
- Ruby: 2.1.2p95
- Rubygems: 2.2.2
- OS: CentOS 5.10

If an invalid/unreachable name server is specified in /etc/resolv.conf the gem installation process will fail, despite using the --http-proxy flag:

```
# gem install --http-proxy=http://hostname:3128/ bundle --no-ri --no-rdoc
ERROR:  While executing gem ... (Errno::ENETUNREACH)
    Network is unreachable - sendto(2) for "<ip address>" port 53
```

If I remove all name server settings (delete resolv.conf) it works fine.
If a proxy server is configured Rubygems should not depend on the local nameserver settings.

**Comment by bshand** [comment]
This error occurs if /etc/resolv.conf lists multiple DNS servers, and one of them is temporarily unreachable. You cannot work around it by specifying the proxy server by IP address, or adding the proxy server to /etc/hosts. (With Ruby: 2.3.0, Rubygems: 2.5.1, CentOS: 7)

**Comment by gpkvt** [comment]
This also happens if you specify an IP-Address as Proxy-URL. In this situation there is no DNS needed. (Ruby 2.1.5, Rubygems: 2.2.2, Debian Jessie)
