### ISSUE TITLE
RUBYGEMS_GEMDEPS ignores :platforms option in Gemfile

### ISSUE THREAD

**Issue by glittershark** [rubygems/rubygems#983]
The current version (4.1.4) of Rails initializes with a Gemfile that contains the following line:

``` ruby
gem 'tzinfo-data', platforms: [:mingw, :mswin]
```

however, running any gem's executable on Linux fails because that gem isn't installed.

EDIT: `$ gem version # => 2.2.2`

**Comment by franklinyu** [comment]
This happens to my RubyGems 2.5.1 which comes with Ruby 2.3.1. The exactly same gem generated by Rails 5.0.
