### ISSUE TITLE
"Overly Strict" Gem Version Specification Warning is Overly Strict

### ISSUE THREAD

**Issue by jfelchner** [rubygems/rubygems#987]
If the gem dependency is based on a semantically versioned gem that is on release `0.x` then, by definition, the API is volatile.

For those developers on a `0.x` release, I've noticed most of them behave as if the minor version is the major and the bugfix version is the minor.  Look at `rake` for a classic example.

Because of this I feel as though, if you're depending on a `0.x` release in your gemspec, that you should not receive an "overly strict" warning if you lock your dependency like so:

``` ruby
spec.dependency 'rake', '~> 0.9.4'
```

Currently this produces:

```
WARNING:  pessimistic dependency on rake (~> 0.9.4) may be overly strict
  if rake is semantically versioned, use:
    add_runtime_dependency 'rake', '~> 0.9', '>= 0.9.4'
```

I feel as though there should be no warning.

**Comment by jaredbeck** [comment]
I'm still getting this warning in gem `2.2.5`:

```
WARNING:  pessimistic dependency on pry-nav (~> 0.2.4, development) may be overly strict
  if pry-nav is semantically versioned, use:
    add_development_dependency 'pry-nav', '~> 0.2', '>= 0.2.4'
```

Should we re-open this issue, or do you want me to create a new issue?

**Comment by jaredbeck** [comment]
Nevermind, I updated to gem `2.6.11` and the warning went away. Thanks!
